### ISSUE TITLE
Sort desktop icons per monitor.

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/nemo#1002]
If I move icons to another monitor, when I sort them they all snap back to the monitor on the left side. It would be nice if each monitor had separate collections of icons.

**Comment by Tasqa** [comment]
I have a sort of similar problem. Everytime I connect my external monitor and make it primary, the desktop icons stay on the laptop (2nd) screen.

It would be more useful if the dekstop icons are shown on the primary screen by default.

**Comment by Pe3ucTop** [comment]
+1 
Agree ! Icon position need be in respect to primary monitor/screen. 
Each time I connect second monitor (at left of primary) - Icons got shown there, not on main screen.

**Comment by Pe3ucTop** [comment]
Also I think this issue is connected to issue #996 ...

**Comment by Tasqa** [comment]
On the latest Cinnamon (3.x) it places the icons on the primary monitor. But it does not correctly remember the locations of the icons. Should I put this in a new bug report and reference it?

**Comment by Pe3ucTop** [comment]
Sorry for long reply, 
Yes, I think it is still a bug and need solution - icon position remember and on primary screen independent to second / third monitor resolution.

**Comment by feren** [comment]
Long (and probably not going to happen anytime soon) idea, but you might want to adopt kinda something similar to the way StarDock Fences works on Windows by having each display like one of that program's fences and then each one holds the desktop icons in their respective places...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
