### ISSUE TITLE
MTP device name in title bar

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/nemo#1004]
A recent update of libmtp makes it possible to mount those devices.
But in the root folder, the title bar says "unnamed device" (not sure about correct translation) while the sidebar is showing my phone correctly as "RAZR HD"

**Comment by icarter09** [comment]
@bitboy85 are you still experiencing this issue?

**Comment by bitboy85** [comment]
Seems gone in LM 19.2 Cinnamon.
