### ISSUE TITLE
Copy files betwen root and user session.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/nemo#1005]
If i open a root session in nemo, i can not copy a file to a non root session or nemo will crash. I test the inverse behaviour with an ssh connection to a server (with root credentials) and i cannot copy file directly from the ssh session to my local root session, but i can copy a file to a local user session and then move it to a root session.

**Comment by Vahan86** [comment]
@lestcape, is this still an issue for you with latest version of Nemo?

**Comment by lestcape** [comment]
- I can copy a file between root session and non root session now. 
- Nemo will report an error now about copy a file between a root ssh session and a local root session (operation unsupported). 

I don' t know why the operation will be unsupported in the last case, but that it's now a consistent behaviour.
