### ISSUE TITLE
Quick find should close it's window after a while or by an up/down/updir key press

### ISSUE THREAD

**Issue by simonzack** [linuxmint/nemo#1006]
The quick find bar (activated by starting to type a file name) should close itself after a while or by an up/down/updir key press. The latter is since up/down/updir doesn't do anything in this window anyway so saves time, while the former saves the user from hitting escape, and is standard on windows.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Sure. I don't see there being much benefit over just using Esc though.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
