### ISSUE TITLE
Don't switch to breadcrumbs view on escape

### ISSUE THREAD

**Issue by simonzack** [linuxmint/nemo#1007]
When the location bar is activated, and escape is pressed it switches to breadcrumb view. This doesn't make much sense, shouldn't escape move the focus to the files & folders pane?

**Comment by kehugter** [comment]
This would also allow to hide the path/breadcrumbs toggle button when the user only wants to use one of the two.

**Comment by JosephMcc** [comment]
The behavior is consistent with how it behaves in other places like the gtk file chooser dialogs.
