### ISSUE TITLE
New style tabs for "Properties" window.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/nemo#1009]
The file/folder "Properties" window uses old style tabs, whereas "File Management Preferences" window uses new style tabs which are more elegant. It would be nice to have the new style tabs for "Properties" window as well.

Thank you.

**Comment by Vahan86** [comment]
@tomasbruna, thank you very much for implementing the requested feature.

@mtwebster, can we close this Issue?

**Comment by JosephMcc** [comment]
Done
