### ISSUE TITLE
New toggle-context icon is a trap  

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#1012]
In current master after merging https://github.com/linuxmint/nemo/pull/988 is a usability issue. 

The new "+" icon is not popper separated from the "Open" menu entry in front of it. 
Even though I already know, that this icon is for collapsing the extended Menu view I found myself clicking on it to select the application which I want to open. 
This impression the "+" belongs to "Open" is gained by the highlighting of the entire row. 

I like the in place config idea very much, but we need a visuals separation from the "Open" entry. 

How about grouping the conditional menu entries together and add a new "more" menu entry with the "+"
This will also improve the situation that for a feature  like "duplicate", you will fist look at the place where it has bin the last time you clicked on it. Skimming up to "Open" enable the expanded menu and back to the place where duplicate has bin, will take some extra time.  

An other improvement would be to remove the highlighting from the icon. This might be doable by an Icon with a border.  

Or we may highlight the Icon permanently. 

Or we may expand the menu after a timer has expires. 

What do you think?

**Comment by RavetcoFX** [comment]
I agree with this, it doesn't make sense to the average user.

**Comment by JosephMcc** [comment]
I would much rather see the expander as it's own menu item or see the extended menu items go into their own flyout. I understand this breaks the grouping but I still think it would be better.

Having it in it's current place is just strange. I've never seen a menu that behaves like that.

**Comment by JosephMcc** [comment]
This was improved and now the text changes in the menu to let you know what's going on. We have seen really no usability complaints about it.
