### ISSUE TITLE
Background greys out after specific actions

### ISSUE THREAD

**Issue by Miclmeo** [linuxmint/nemo#1015]
When having Nemo windows open, after I do specific things (i.e. Dropbox sync, editing pictures from within Shotwell), the background in Nemo changes from #ffffff (white) to #d6d6d6 (grey). New windows have white background again, but once they turn grey, there's no turning back.

I'm not exactly sure what the pattern is, maybe it has to do with thumbnail refreshing (as Dropbox adds an emblem to a synced folder, and it only happens when I do something with another program that changes files somehow).

I also found the offender for this. It's /usr/share/themes/Mint-X/gtk-3.0/gtk-main.css --> theme_bg_color (in line 3). Changed that value to #a6d6a6 and now Nemo gets all green after Dropbox sync : ) But I have no idea how to fix that permanently. Can't imagine it's a feature.

The problem persists as of version 2.6.7 in Mint 17.2 (Cinnamon). When I did a fresh install in Sep 2014, there was no issue with using Nemo. It creeped in maybe around March or so (NOT instantly after any Nemo upgrade!)

BTW: Seeing all these theming options are css files. I think it would be certainly nice to have a GUI option for a few basic theming options like colour of background in Nemo, or transparency of the Cinnamon panel. Is something like this considered?

**Comment by gritty-gitty** [comment]
This issue has been annoying me too for a long time in another context. Here is how to reproduce it:
* Start up Nemo, e.g. with [Super+e] in your home folder;
* Open any of the folders there in a new tab, e.g. by middle-clicking on it:
	* The new folder opens with a new tab in the background;
	* The home folder becomes light gray;
* Close the other folder, e.g. by middle-clicking on its tab:
	* The home folder will remain open, but its background will turn dark gray.

However, the other folder is always started with a white background, which you can verify if you bring it to the foreground by clicking on its tab right away after having opened it as a background tab. 
* Strangely enough, that folder will remain white when you close the other one, i.e. the home folder.

**Comment by icarter09** [comment]
@Miclmeo are you still experiencing this issue on the latest version of nemo?

**Comment by Miclmeo** [comment]
Can't tell for the latest version but I have upgraded to Mint 18.1 a while ago, the issue hasn't occurred again since then. If noone else has this problem anymore I guess this can be closed? It's been 5 years...
