### ISSUE TITLE
Simple Text File Icons

### ISSUE THREAD

**Issue by gritty-gitty** [linuxmint/nemo#1016]
The ability of Nemo to display a thumbnail of the contents of a text based file as its icon is a nice feature, as long as the default Mint-X icon themes are used. But with other icon themes, even the most complete ones, these files are displayed with “no icon”, so that the icons corresponding to the actual MIME subtype of such a file are *never* used.

For instance, an HTML file will always have that “empty” icon, as any other text type will do, so there will be no visual clue to distinguish them from each other.

**Comment by JosephMcc** [comment]
Open nemo and go to Edit->Preferences. On the Preview tab set the first option, "Show text in icons", to Never. That will give the mimetype icons. This feature is probably going away in Nemo 3.0 since it no longer works in newer gtk versions.
