### ISSUE TITLE
Nemo Bug - Desktop Global Resize of Icons Doesn't Work Properly

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/nemo#1018]
I'm a newbie to Linux Mint so I hope that I am doing this reporting correctly. System Details:
Linux Mint 17.2 x64 Cinnamon Edition
Cinnamon 2.6.23
Nemo 2.6.7

In Nemo I selected the following menu item: Edit > Preferences > Views. In that dialogue there is an item titled "Icon View Defaults". That item has a "Default zoom level" setting. I wanted to globally resize (make smaller) all the icons on my desktop. I set the size to 66%. And it worked but with with very varied results.

For example, my "Computer", "Home" and "Rubbish Bin" icons went down to nice small size (just what I wanted). However, icons for other types of file on the desktop gave very varied results. One internet link that I had on the desktop did resize to a nice small size - however other internet links were left in a rather large size. Likewise, launchers on the desktop did not resize to a nice small size, nor did my USB Flash Drive icon reduce to a nice small size. Similarly, text file icons didn't reduce to a nice small size.

As you can see this setting isn't producing consistent results across all file types icons on the desktop - some it makes small, others it leaves rather large. To me that seems like a bug in Nemo and actually a very important one. If Linux wants to be a success as a dominant OS in the future then really this is the kind of thing that can turn people on or off when they first try Linux - just how polished the desktop looks and works. Therefore, I think this bug very important and one that should be dealt with as a priority.

I have attach a screenshot of the look of icons that I am talking about which I hope makes my description of the problem clearer.
![screenshot from 2015-11-20 19 52 22](https://cloud.githubusercontent.com/assets/15947700/11310241/6f0370fe-8fc0-11e5-9bc1-7f77ffc23561.png)

Hope this helps.

**Comment by CottonEaster** [comment]
Compare also #1807 and perhaps #1680. I note also that changing desktop icon size seems to make no attempt at all to preserve the existing layout.

**Comment by icarter09** [comment]
@RadicalRadish are you still experiencing this issue on the latest version of nemo?

**Comment by RadicalRadish** [comment]
@icarter09 I don't use Linux Mint any more. Switched back to Windows 7 a couple of years ago. Might at some time in the future come back to Mint but I'm hoping that if I do the Linux experience is a bit more polished than it was when I left. Overall I thought Linux and Mint were quite a good OS but difficult to use compared to Windows and getting drivers for peripherals was a bit of a problem sometimes.

**Comment by icarter09** [comment]
@RadicalRadish no worries and thanks for the update. If you do come back to Linux Mint and notice this issue is still present, then feel free to open up a new ticket. Thanks.
