### ISSUE TITLE
Nemo 2.8.5 (Linux Mint 17.3 fresh install): Unable to copy file on pendrive

### ISSUE THREAD

**Issue by marcogiannini** [linuxmint/nemo#1019]
I have a problem with nemo and file copy on pendrive USB. 
When i tray to copy some file or folder to pendrive with nemo as normal user i have this message 
![schermata del 2015-11-23 12 03 30](https://cloud.githubusercontent.com/assets/4943897/11335231/f89e093e-91da-11e5-98e5-6c4bf8a67753.png)

If i launch Nemo with sudo no problem. Same if i use Thunar or other file manager.

This is a video of the issue

https://www.youtube.com/watch?v=cs1EiSCaNk8&feature=youtu.be

**Comment by ManIVIctorious** [comment]
Sounds like you don't have write Access on your pendrive. Please open the drive as root, rightclick the background and check the access-rights (sorry, not on my pc, don't know the exact Name...)

**Comment by marcogiannini** [comment]
Done. In the video it is all explained. The bug only occurs with Nemo as normal user. If I try to copy files on the pendrive with Nemo it does not work, but if I try to copy same files with Thunar everything works properly. The only way to run the copy with Nemo is to use sudo.

**Comment by marcogiannini** [comment]
SOLVED: After restarting the bug has disappeared
