### ISSUE TITLE
Search bar looses focus when displaying results for the first time

### ISSUE THREAD

**Issue by FM33** [linuxmint/nemo#1021]
Hello,

After activating search bar, if I pause during typing, the search runs and the search bar looses focus, no matter there are results or not.
I re click into the the search field and then the issue does not occur any more until I close/reopen the search.

2.8.4 WebUpd8 / Ubuntu 14.04 x64

**Comment by JosephMcc** [comment]
Can't reproduce this on the official version of Nemo 3.0.6
