### ISSUE TITLE
Pressing letter quick find

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1026]
So here is a thing I found. When I'm in the file manager and I press a letter on the keyboard than it brings me to the first file that starts with that letter. The problem is when there is no file for that letter than it doesn't do anything, but IMO it should bring me to the file that is closest to that letter in the alphabet. Other thing I noticed is that after using this feature (pressing a letter to bring me to the file) if I try to close the file manager right after I pressed a letter it won't close immediately.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
