### ISSUE TITLE
FTP dismount crash

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1027]
This is what happened: I mount an FTP location (with user name and pw and I select remember until log off) and if I dismount this location (by clicking on the little up arrow beside its name) while I'm inside that same mounted folder than the file manager and also the desktop crashes and i have to restart with ctrl+alt+esc (I'm on Mint 17.2 Cinnamon).

**Comment by Vahan86** [comment]
@ngabor7, is this still an issue for you with Nemo 3.0.6 (Mint 18)?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
