### ISSUE TITLE
Copy/move/delete task prioritization

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1033]
So when I'm copying/moving a large amount of files in one batch, and then if in the meanwhile I start to delete/move/copy a single small file it should execute that task right away, but now it waits for the first task to complete, and only then it will start the second one however small it is.

**Comment by ngabor7** [comment]
Related idea I found on Mint Community page: http://community.linuxmint.com/idea/view/4611

**Comment by ngabor7** [comment]
Maybe one cool way to implement it is first to implement the pause feature, and then when a new task is added to the queue it is first paused all until the tasks in front of it are completed or if the user explicitly unpauses the task. What do you think?

**Comment by neurobin** [comment]
>new task is added to the queue it is first paused
>...or if the user explicitly unpauses the task

agreed...

**Comment by keitalbame** [comment]
seems a good enhancement to me.

**Comment by fish-face** [comment]
A pause button would be a welcome addition and is nowadays a common feature of desktop environments. It's quite common, for example, that I am downloading a load of stuff, which saturates my internet connection, and then want to do something else which requires the network. Having no recourse but to cancel the download is very frustrating.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
