### ISSUE TITLE
Update the % in the titlebar when a new task is added/removed to the copy/move/delete dialog

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1034]
I just noticed that when I'm adding/removing a new copy/move task while there is one already running it takes some time for the percentage number to update in the titlebar (from 10sec to 1min).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
