### ISSUE TITLE
Bookmarks for folders with custom icons are changing icons 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#1035]
I have two folders with custom icons. 
On in my home directory and one in Downloads. 
I have bookmarks to both of them. 

When I start nemo normal, only the bookmark of the folder in the home directory has a custom icon. 
If I navigate to the onther directory the icon of that bookmark changes to the custom icon. 
If I shutdown nemo "nemo -q" and start it again with "nemo ~/Downloads" only the other bookmark has the custom icon.

**Comment by simonwiles** [comment]
Related: #747 (and many closed issues).

**Comment by xenopeek** [comment]
Current version of Nemo uses symbolic icons in the sidebar. Custom folder icons aren't shown in the sidebar.
