### ISSUE TITLE
segfault when closing any window

### ISSUE THREAD

**Issue by virgi26** [linuxmint/nemo#1038]
Hi
I'm getting segmentation fault every time i'm closing any nemo window, which leads to closing of every nemo window.
I'm running Cinnamon on Opensuse Leap 42.1
nemo is 2.8.6-1.1
cinnamon is 2.8.6-3.1

logs just show
traps: nemo[30353] general protection ip:497ef4 sp:7fff39328a28 error:0 in nemo[400000+1c2000]

**Comment by xenopeek** [comment]
If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
