### ISSUE TITLE
Apparent resource leak when copying files using nemo

### ISSUE THREAD

**Issue by cemacf** [linuxmint/nemo#1039]
Total to copy 2,161,471 files, 39.9GB

The first rate displayed was 6.5MB/s, but dropped steadily thereafter
-  it always dropped, never increased  -  until by around 22,000 files
  and 355MB copied, the rate was below 500KB/s (note that's kilobyte,
  not megabyte), and still dropped steadily.

I find it difficult to believe that such a systematic and catastrophic
fall is not symptomatic of something bad, but I took a top while the
merge dialog was waiting for me to confirm replacement of all, another
while it was still copying, another after cancelling (I wasn't going
to wait a day or more for a result), and another after closing nemo.

www.macfh.co.uk/Temp/Linux%20-%20Top%20-%2045GB.txt

I then used the cp -a command in a console to effect the same copy,
and it took 1hr 14mins, whereas nemo was predicting about a
day by the time I aborted it.

**Comment by icarter09** [comment]
@cemacf are you still experiencing this issue on the latest version of nemo?
