### ISSUE TITLE
Add compatibilty to Ultracopier / Catchcopy

### ISSUE THREAD

**Issue by Spheerys** [linuxmint/nemo#104]
Hi,

I'm looking for a filemanager which support ultracopier to improve the copy files process
There is a project to standardize the copy press to make the compatibilty works.
This project is called Catchcopy

If you like the idea, there is the two websites :
- http://ultracopier-fr.first-world.info/
- http://catchcopy.first-world.info/wiki

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
