### ISSUE TITLE
Elevated nemo does not remember folder views.

### ISSUE THREAD

**Issue by Kosyne** [linuxmint/nemo#1042]
Per the title, folder views are not remembered when using an elevated instance of nemo, despite having nemo set to remember per-folder views.
1. Open nemo as root.
2. Change a folder's view to something other than default. (List, Compact...)
3. Navigate away from folder, then navigate back to see that it has reset.

Expected behavior: Folder preferences should be based on the root user's per-folder preferences. (Or, perhaps the preferences of the user who opened the elevated nemo instance.)

**Comment by ACinnamonUserInUK** [comment]
I too find this frustrating.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
