### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by alihanozturk** [linuxmint/nemo#1043]
/bin/sh: ./merge_action_strings: /usr/bin/python2: bad interpreter: No such file or directory
/usr/bin/python2 istiyor ancak Pisilinux'ta bu /usr/bin/python2.7 

http://www.sudrap.org/paste/text/663920/

**Comment by xenopeek** [comment]
There's not enough for us to go on here. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
