### ISSUE TITLE
Nemo appears to not understand Roman Numerals

### ISSUE THREAD

**Issue by belandsoft** [linuxmint/nemo#1044]
If I have some files inside a folder named with Roman Numerals, nemo appears to not understand it's meaning and does not order this files correctly in any type of view. As is shown in this screenshot (compact view), but it's the same on eg. listview:

![schermata del 2015-12-10 15-25-28](https://cloud.githubusercontent.com/assets/3130417/11717691/5638bb46-9f52-11e5-8530-40b2bcac50e7.png)

**Comment by mtwebster** [comment]
There's no reason to expect this to work... just rename the files and number them.

**Comment by belandsoft** [comment]
Microsoft Windows understands this type of file names and order it
correctly, i was hoping that a linux file manager will be MORE powefull of
Windows one and not less....

2015-12-11 1:58 GMT+01:00 Michael Webster <notifications@github.com>:
