### ISSUE TITLE
Remember entered text in file name field after unsuccessful rename attempt

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1045]
If I'm using a forbidden character when I'm renaming a file, after pressing enter it will forget the new text I typed in and go back to the original name. I think it should leave the text and the cursor there, show the warning massage and then let me enter the necessary changes. What do you think?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
