### ISSUE TITLE
Segfault changing view and closing

### ISSUE THREAD

**Issue by sbsbs15** [linuxmint/nemo#1047]
Hi, I found a bug in nemo 2.8.6.
When I open a folder, change the view and close it, nemo crashes (Desktop folders dissapears).

Cheers.

Edit (gdb results):
[gdb.txt](https://github.com/linuxmint/nemo/files/61801/gdb.txt)

**Comment by jf99** [comment]
Same happens here with Arch Linux (same version nemo 2.8.6).

**Comment by legion1978** [comment]
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
nemo: cairo-surface.c:928: cairo_surface_reference: La declaración `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' no se cumple.
Abortado (`core' generado)

**Comment by sbsbs15** [comment]
Is this a build problem??
@mtwebster how can we fix it?

**Comment by lokcon** [comment]
Same on Arch Linux with Nemo 2.8.6

**Comment by jf99** [comment]
Note that it does not matter how you change the view. Let's say you are in your home directory with icon view. Now you can either
- change the view directly or
- go to a subdirectoy which has list view as default

No matter what you do, nemo will crash when you close its window. This issue might also be related to #1038 .

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/nemo/commit/fb97b62aad23bb44820713c8084785bbc147bfd7

**Comment by sbsbs15** [comment]
Thanks for solving this!
@clefebvre can you add a point release? this bug is very annoying

**Comment by sebalis** [comment]
I am experiencing this issue under Arch (Antergos, to be precise), it doesn’t of course appear every time a Nemo window is closed and https://bbs.archlinux.org/viewtopic.php?id=206248 has some more details about actions that do trigger the crash. Perhaps you’d like to check that all those scenarious are covered by this fix? Needless to say, the users in this thread and I would be very grateful for a new release.
