### ISSUE TITLE
Add "Refresh" option to the right click context menu

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1048]
Now the only option to refresh the file list is to press F5. I think there should be an option to refresh using the right click context menu.

**Comment by jf99** [comment]
But make the context menu entry optional. You can already have a refresh button in your toolbar.

**Comment by thirteen-01** [comment]
Would be nice, i like more rightclick's

**Comment by cinnamoner** [comment]
Obviously, I endorse the suggestion. I think the devs know what we want. So let us not disturb or distract them that often. I've imagined myself in their situation and I now empathize with them.

**Comment by 001101** [comment]
@cinnamoner You just get Interrupt when you let it be ;)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by 001101** [comment]
> Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.
> 
> For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

Where can I keep track of the status from my idea?

**Comment by icarter09** [comment]
If it is implemented, then you will see it as a PR and then part of an update for Nemo.

**Comment by 001101** [comment]
> If it is implemented, then you will see it as a PR and then part of an update for Nemo.

Why is there an If at the start of your sentence?

**Comment by icarter09** [comment]
https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by icarter09** [comment]
"When you submit an idea, it is processed and then closed. It might lead to an implementation, it might lead to a design discussion within the team, it might be planned for a particular release and put on the roadmap, it might lead to nothing at all, or it might stick in people’s minds as something they could improve later on. Either way, your role is done when the idea is reported and once it’s understood by the development team."

**Comment by 001101** [comment]
i know
