### ISSUE TITLE
copy & move to history

### ISSUE THREAD

**Issue by 001101** [linuxmint/nemo#1049]
Hello,

looking for a way to implement a small history for the copy to and move to functions, so that you can select from the last five locations easily and don't have always to click your way through the hole path again.

Can you please give me some hints where to start at?

Kind Whishes

**Comment by anandrkris** [comment]
:+1:  for this. Great idea to have files to copy / move to Recent folders .
I am not a developer but can see `recent:///` shows the recent files.

**Comment by anandrkris** [comment]
@mtwebster - This is really an interesting and nifty idea. Can you please have a look?

**Comment by 001101** [comment]
Nice to hear all this, have already forgotten my wish :)

I will make a new approach to find a solution the next weeks, when I have time, my skills are now a little bit better.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by 001101** [comment]
> Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.
> 
> For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

Where can I keep track of the status from my idea?

**Comment by icarter09** [comment]
If it is implemented, then you will see it as a PR and then part of an update for Nemo.
