### ISSUE TITLE
File System Properties Discrepancy

### ISSUE THREAD

**Issue by cj0nes** [linuxmint/nemo#1050]
File System Properties reports significantly more data than the actual drive can hold.

![filesystempropertiesdiscrepancy](https://cloud.githubusercontent.com/assets/13335711/11963160/858e3d60-a8aa-11e5-97d6-7e0b62c84c97.png)

**Comment by leigh123linux** [comment]
The issue is caused by /proc/kcore

http://askubuntu.com/questions/263189/1-suspicious-file-with-size-140tb


![untitled](https://cloud.githubusercontent.com/assets/1299302/11974557/461f26cc-a95d-11e5-9e7d-c38ac2dc93d0.png)

**Comment by JosephMcc** [comment]
This has been fixed.
