### ISSUE TITLE
"Open With VLC media player" in context menu randomly becomes "too white" or grey to distinguish

### ISSUE THREAD

**Issue by BRKsays** [linuxmint/nemo#1051]
Sometimes when I open context menu to play a video, the "Open With VLC media player" menu entry at the top is greyed out and can't be distinguished. But it is quickly remedied when the mouse cursor is hovered on top of "Open With VLC media player". I don't use the default video player but I set it up as default for a while to check and it didn't grey out. But I'm not sure whether it is a VLC specific bug or not; so I posted here. [Here](https://www.youtube.com/watch?v=eB2GkC1N7oQ) is a video showing the issue.

I'm running Linux Mint 17.3 "Rosa" cinnamon 64-bit.

![vlcsnap-2015-12-24-09h45m19s101](https://cloud.githubusercontent.com/assets/5929272/11989472/f129a09e-aa23-11e5-931e-3d918ede7925.png)
![vlcsnap-2015-12-24-09h45m29s224](https://cloud.githubusercontent.com/assets/5929272/11989473/f1538a3a-aa23-11e5-8407-36942d35ebe5.png)

**Comment by icarter09** [comment]
@BRKsays are you still experiencing this issue on the latest version of nemo?
