### ISSUE TITLE
[bug] Compressing to another location

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1052]
I noticed when I'm compressing a file/folder with the graphical "Compress" tool and as a location I set another folder then the one the file is in it won't move the compressed file there but simply put it next to the original file as if I didn't even change the compress location. Do you have the same problem? I'm running Mint 17.2 64 bit, Cinnamon 2.6.13, Nemo 2.6.7.

**Comment by sadegroot** [comment]
I'm experiencing the same issue. I'm running Mint 17.3 64-bit, Cinnamon 2.8.7, Nemo 2.8.7.

**Comment by icarter09** [comment]
@ngabor7 are you still experiencing this issue on the latest version of nemo?
