### ISSUE TITLE
[bug] Can't copy folder from or to an FTP location

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1054]
I noticed that I can't copy folder from or to an ftp location, but I can copy files. I was using Nemo and mounted the ftp location as usual. Setup: Mint 17.2, Nemo 2.6.7, Cinnamon 2.6.13 and I was connected to an ftp server on my android https://play.google.com/store/apps/details?id=lutey.FTPServer&hl=en

**Comment by Vahan86** [comment]
@ngabor7, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
