### ISSUE TITLE
fstab mounting not as device in nonroot nemo

### ISSUE THREAD

**Issue by ikuria** [linuxmint/nemo#1055]
want to mount my nas to show it under "device" category in nemo (left), but only in nemo with root (right) it worked well:
https://i.imgur.com/rmZeInY.png
(Geräte = Devices)

my fstab line:
//white/Public /media/ikuria/MyCloud cifs sec=none,rw,users,uid=1000 0 0
- i didnt want it as bookmark
- i didnt want it as network folder because i got volume left information as device (and its pretty _g_)

so what is wrong, the fstab? maybe permission fault? or nemo has a bug to display this mount as device correctly? or it isnt a bug because nemo defines it as network folder :(

**Comment by icarter09** [comment]
@ikuria are you still experiencing this issue on the latest version of nemo?
