### ISSUE TITLE
Make the panes clear when open - a suggestion with mockup

### ISSUE THREAD

**Issue by jasiralavi** [linuxmint/nemo#1056]
Currently the panes are not clear when they are open side by side.
Can we get a different background color for the second pane to distinguish it?
It would also be great to show the folder name like when tabs are open. Please check my mock-up attached here - hope it makes better sense.

![current-nemo-with-panes-open](https://cloud.githubusercontent.com/assets/16372030/12010580/b60a7c48-acd2-11e5-9793-29e9ca0ee397.png)
![nemo-with-panes-mockup](https://cloud.githubusercontent.com/assets/16372030/12010581/bb96449e-acd2-11e5-92c5-809b21d09181.png)

**Comment by JosephMcc** [comment]
The coloring of the panes is controlled by your gtk theme. This is what it looks like in Mint-X for example: https://dl.dropboxusercontent.com/u/71834451/screenshots/nemo-pane.png

**Comment by jasiralavi** [comment]
I'm using nemo on ubuntu 15.10. The pane does show up with a different (white background) with it first opens in some cases. But once you click inside it takes the same color as the first pane. The invisible scrollbar of ubuntu makes it more harder to see where the split is. 

I agree that the theme makes the difference, but I think it would be good if nemo can give a bit of drak/light depth so that the application has better usability across various distributions and themes.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
