### ISSUE TITLE
A suggestiont to make sidebar toggle experience better

### ISSUE THREAD

**Issue by jasiralavi** [linuxmint/nemo#1057]
Currently the F9 key toggles the sidebar. But Nemo offers two views for the sidebar - Places and Tree. 

I suggest that we add a Shift+F9 short cut to toggle between the Tree and Places views when the side bar is open. If it is closed this can function same as F9.

Another option is to let F9 key cycle through the three modes. 
e.g. F9 → Open Sidebar (Tree) → F9 → Open Places view → F9 → Close Sidebar → ...

A third option would be to assign two keys:
F9 → toggles Places view
F8 → toggles Tree view

**Comment by Rio517** [comment]
https://github.com/linuxmint/nemo/pull/111 from @clefebvre added the toggle buttons on the bottom, but I agree that a shortcut to toggle  places/tree view would be helpful. I think a single toggle vs two separate shortcuts for each view type would be easier for users to remember.

**Comment by jasiralavi** [comment]
I also think that we can get rid of the sidebar open/close button.
The buttons for Tree and Places view are enough to toggle the sidebar as well. Here's how it should work.
1. If the Tree button is pressed then:
   1.1. if sidebar was closed, then it opens with Tree view 
   1.2. if the Places view is open, the click changes the sidebar view to Tree view (and toggles off the Places button)
2. Similarly If the Places button is pressed then:
   2.1. if sidebar was closed, then it opens with Places view 
   2.2. if the Tree view was open, it changes that view to Places view (and toggles off the Tree view button)
3. When both buttons are off, then the sidebar is closed. 
   3.1. When Tree view is open, clicking on it again will close the sidebar
   3.2. Similarly, when Places view is open, clicking on it again will close the sidebar.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
