### ISSUE TITLE
Sometimes emblems show only after hitting refresh

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1058]
Sometimes - or always? - when one adds an emblem to a previously emblemless icon, then, at least if the icon is on the desktop (as against displaying in a standard Nemo window), the emblem shows only after hitting refresh (F5). What should happen: the change should show immediately or almost immediately.

Linux Mint 17.3 x64 Cinnamon 2.8.6. Nemo 2.8.6.

**Comment by CottonEaster** [comment]
This problem has persisted into Mint 17.3 with Nemo 3.6.4.

**Comment by CottonEaster** [comment]
This problem has persisted into Mint 18.3 with Nemo 3.6.5.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
