### ISSUE TITLE
File verification tab

### ISSUE THREAD

**Issue by Kurt-Aust** [linuxmint/nemo#1061]
It would be rather nice if there was a tab under file properties that displayed verification details.

I was thinking that it would ideally generate MD5, SHA-1 and SHA-256 checksums and also monitor the contents of the clipboard for a match, similarly to the way the HashTab windows utility does it.
http://implbits.com/products/hashtab/

Also on the same tab a notification if the file is digitally signed or not, automatically checking if such a signature is valid (it's a tad silly that Microsoft windows doesn't check the signature).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
