### ISSUE TITLE
[Feature Request] Excluding extensions on nemo_action

### ISSUE THREAD

**Issue by Magissia** [linuxmint/nemo#1063]
Currently we can whitelist extensions an action should be executed on, but blacklisting is not possible.
A nemo action compressing current selection with pre-set parameters should be accessible to any extensions but the one used by the compressed file.

For example, I should be able to use lbzip2 on anything, excluding .bz2 files.
Right know, this is not possible. (And if possible, the action sample should be improved to reflect that)

**Comment by ManIVIctorious** [comment]
duplicate of issue #405

**Comment by Magissia** [comment]
Indeed, didn't look far enough.
Apologies.
