### ISSUE TITLE
crash in nemo when pressing escape while dragging column

### ISSUE THREAD

**Issue by ctrlbru** [linuxmint/nemo#1064]
Mint 17.2 64 bit, nemo 2.6.7+rafaela, when I'm dragging a column in list view and I press the ESC key while still dragging, I get

(nemo:5497): Gdk-CRITICAL **: gdk_event_get_device: assertion 'event != NULL' failed
(nemo:5497): Gdk-CRITICAL **: gdk_device_get_associated_device: assertion 'GDK_IS_DEVICE (device)' failed
Segmentation fault

On my machine this can be reproduced every single time.

**Comment by mtwebster** [comment]
This is a gtk bug - https://bugzilla.gnome.org/show_bug.cgi?id=739920

I've submitted a patch, but it isn't necessary in newer gtk versions, so it'll probably wait until we move from gtk 3.10 to 3.18

**Comment by JosephMcc** [comment]
I can no longer reproduce this an Mint 18.
