### ISSUE TITLE
Context Menu - Open with <Default app>  shows wrong Application name, but correct icon

### ISSUE THREAD

**Issue by kanehekili** [linuxmint/nemo#1065]
Nemo's context menu usually shows in its first entry "Open with <Name of default app>" and its appropriate icon. E.g. selecting a .txt file shows "Open with gedit". When selecting a .png file afterwards the correct icon is shown, but the text remains "Open with gedit"
Can be reproduced with any combination of files.
It may happen, that the text is not displayed at all. Only "Open" is shown.
Nemo Version: 2.8.4
Cinnamon Version: 2.8.4

**Comment by kanehekili** [comment]
After updating to 17.3 the problems seems to be resolved... Cinnamon/Nemo Version 2.8.6

**Comment by JosephMcc** [comment]
Should have been fixed by this: https://github.com/linuxmint/nemo/commit/0e5d188e82321442e4eed12432a818fef6b0afea
