### ISSUE TITLE
File index dialogbox crashes when closing nemo.

### ISSUE THREAD

**Issue by croutch** [linuxmint/nemo#1066]
When I open Nemo and go to my / mnt / media and transfer files to / mnt / media1 and then I go to the / home / user in the same session. If I go back to the / mnt / media and closes Nemo. Then crashes all the nemo window and file indexing dialog box and the file transfer and all other Nemo session also closes. Then it's just to start over and look for any folders that were given half the transfer. 
I mean that even if I close down nemo should the file transfer still run in the background with filindexerins box open. Because I do not shut down the transfer of files Just Nemo.
Bug or feature?

I have tried to get into a gdb output but nothing happens to it.
I'm using Arch Linux cinnamon 2.8.6-1

**Comment by xenopeek** [comment]
If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
