### ISSUE TITLE
Nemo crash report

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/nemo#1068]
I was checking journalctl, and saw this in there. Thought you might be interested in the stack trace. I'm running Cinnamon on Arch.

> Process 2016 (nemo) of user 1000 dumped core.  
>                                              Stack trace of thread 2016:
>                                              #0  0x0000000000494984 n/a (nemo)
>                                              #1  0x00007f3b9d83d015 g_closure_invoke (libgobject-2.0.so.0)
>                                              #2  0x00007f3b9d84f061 n/a (libgobject-2.0.so.0)
>                                              #3  0x00007f3b9d857dfc g_signal_emit_valist (libgobject-2.0.so.0)
>                                              #4  0x00007f3b9d85812f g_signal_emit (libgobject-2.0.so.0)
>                                              #5  0x00007f3b9f40b0fa n/a (libgtk-3.so.0)
>                                              #6  0x00007f3b9d8437b8 g_object_run_dispose (libgobject-2.0.so.0)
>                                              #7  0x00007f3b9f2ddb1d n/a (libgtk-3.so.0)
>                                              #8  0x00007f3b9f2099a0 n/a (libgtk-3.so.0)
>                                              #9  0x00007f3b9d83d015 g_closure_invoke (libgobject-2.0.so.0)
>                                              #10 0x00007f3b9d84f57e n/a (libgobject-2.0.so.0)
>                                              #11 0x00007f3b9d857dfc g_signal_emit_valist (libgobject-2.0.so.0)
>                                              #12 0x00007f3b9d85812f g_signal_emit (libgobject-2.0.so.0)
>                                              #13 0x00007f3b9f40b0fa n/a (libgtk-3.so.0)
>                                              #14 0x00007f3b9d841d95 g_object_unref (libgobject-2.0.so.0)
>                                              #15 0x00007f3b9f207dac gtk_container_remove (libgtk-3.so.0)
>                                              #16 0x00007f3b9f40b004 n/a (libgtk-3.so.0)
>                                              #17 0x00007f3b9d841d95 g_object_unref (libgobject-2.0.so.0)
>                                              #18 0x00007f3b9f183280 n/a (libgtk-3.so.0)
>                                              #19 0x00007f3b9d5702fe n/a (libglib-2.0.so.0)
>                                              #20 0x00007f3b9d5702d1 n/a (libglib-2.0.so.0)
>                                              #21 0x00007f3b9d570e81 g_node_traverse (libglib-2.0.so.0)
>                                              #22 0x00007f3b9f184901 n/a (libgtk-3.so.0)
>                                              #23 0x00007f3b9d841e0a g_object_unref (libgobject-2.0.so.0)
>                                              #24 0x00000000004b955f n/a (nemo)
>                                              #25 0x00007f3b9d841e0a g_object_unref (libgobject-2.0.so.0)
>                                              #26 0x00007f3b9f2c0e10 gtk_main_do_event (libgtk-3.so.0)
>                                              #27 0x00007f3b9ee3ad32 n/a (libgdk-3.so.0)
>                                              #28 0x00007f3b9d568dc7 g_main_context_dispatch (libglib-2.0.so.0)
>                                              #29 0x00007f3b9d569020 n/a (libglib-2.0.so.0)
>                                              #30 0x00007f3b9d5690cc g_main_context_iteration (libglib-2.0.so.0)
>                                              #31 0x00007f3b9db288ec g_application_run (libgio-2.0.so.0)
>                                              #32 0x0000000000430806 n/a (nemo)
>                                              #33 0x00007f3b9c702610 __libc_start_main (libc.so.6)
>                                              #34 0x0000000000430869 n/a (nemo)
>                                              Stack trace of thread 2018:
>                                              #0  0x00007f3b9c7c218d poll (libc.so.6)
>                                              #1  0x00007f3b9d568fbc n/a (libglib-2.0.so.0)
>                                              #2  0x00007f3b9d5690cc g_main_context_iteration (libglib-2.0.so.0)
>                                              #3  0x00007f3b9d569109 n/a (libglib-2.0.so.0)
>                                              #4  0x00007f3b9d58f715 n/a (libglib-2.0.so.0)
>                                              #5  0x00007f3b9ca8d4a4 start_thread (libpthread.so.0)
>                                              #6  0x00007f3b9c7cb13d __clone (libc.so.6)
>                                              #6  0x00007f3b9c7cb13d __clone (libc.so.6)
>                                              Stack trace of thread 2019:
>                                              #0  0x00007f3b9c7c218d poll (libc.so.6)
>                                              #1  0x00007f3b9d568fbc n/a (libglib-2.0.so.0)
>                                              #2  0x00007f3b9d569342 g_main_loop_run (libglib-2.0.so.0)
>                                              #3  0x00007f3b9db5f236 n/a (libgio-2.0.so.0)
>                                              #4  0x00007f3b9d58f715 n/a (libglib-2.0.so.0)
>                                              #5  0x00007f3b9ca8d4a4 start_thread (libpthread.so.0)
>                                              #6  0x00007f3b9c7cb13d __clone (libc.so.6)
>                                             Stack trace of thread 2021:
>                                              #0  0x00007f3b9c7c218d poll (libc.so.6)
>                                              #1  0x00007f3b9d568fbc n/a (libglib-2.0.so.0)
>                                              #2  0x00007f3b9d5690cc g_main_context_iteration (libglib-2.0.so.0)
>                                              #3  0x00007f3b9059925d n/a (libdconfsettings.so)
>                                              #4  0x00007f3b9d58f715 n/a (libglib-2.0.so.0)
>                                              #5  0x00007f3b9ca8d4a4 start_thread (libpthread.so.0)
>                                              #6  0x00007f3b9c7cb13d __clone (libc.so.6)

**Comment by MrOats** [comment]
I am running Manjaro 64-bit and Nemo (2.8.6-1) crashes during any event (whether it be closing a nemo window, or opening a file within nemo). Here is an example stack trace I saved:

    Process 17062 (nemo) of user 1000 dumped core.

                                                            Stack trace of thread 17062:
                                                            #0  0x0000000000494984 n/a (nemo)
                                                            #1  0x00007fa8f40fb015 g_closure_invoke (libgobject-2.0.so.0)
                                                            #2  0x00007fa8f410d061 n/a (libgobject-2.0.so.0)
                                                            #3  0x00007fa8f4115dfc g_signal_emit_valist (libgobject-2.0.so.0)
                                                            #4  0x00007fa8f411612f g_signal_emit (libgobject-2.0.so.0)
                                                            #5  0x00007fa8f5cc93da n/a (libgtk-3.so.0)
                                                            #6  0x00007fa8f41017b8 g_object_run_dispose (libgobject-2.0.so.0)
                                                            #7  0x00007fa8f5b9bcfd n/a (libgtk-3.so.0)
                                                            #8  0x00007fa8f5ac7a20 n/a (libgtk-3.so.0)
                                                            #9  0x00007fa8f40fb015 g_closure_invoke (libgobject-2.0.so.0)
                                                            #10 0x00007fa8f410d57e n/a (libgobject-2.0.so.0)
                                                            #11 0x00007fa8f4115dfc g_signal_emit_valist (libgobject-2.0.so.0)
                                                            #12 0x00007fa8f411612f g_signal_emit (libgobject-2.0.so.0)
                                                            #13 0x00007fa8f5cc93da n/a (libgtk-3.so.0)
                                                            #14 0x00007fa8f40ffd95 g_object_unref (libgobject-2.0.so.0)
                                                            #15 0x00007fa8f5ac5e2c gtk_container_remove (libgtk-3.so.0)
                                                            #16 0x00007fa8f5cc92e4 n/a (libgtk-3.so.0)
                                                            #17 0x00007fa8f40ffd95 g_object_unref (libgobject-2.0.so.0)
                                                            #18 0x00007fa8f5a41290 n/a (libgtk-3.so.0)
                                                            #19 0x00007fa8f3e2e2fe n/a (libglib-2.0.so.0)
                                                            #20 0x00007fa8f3e2e2d1 n/a (libglib-2.0.so.0)
                                                            #21 0x00007fa8f3e2ee81 g_node_traverse (libglib-2.0.so.0)
                                                            #22 0x00007fa8f5a42911 n/a (libgtk-3.so.0)
                                                            #23 0x00007fa8f40ffe0a g_object_unref (libgobject-2.0.so.0)
                                                            #24 0x00000000004b955f n/a (nemo)
                                                            #25 0x00007fa8f40ffe0a g_object_unref (libgobject-2.0.so.0)
                                                            #26 0x00007fa8e9d9b30d n/a (libcanberra-gtk-module.so)
                                                            #27 0x00007fa8e9d9b4b4 n/a (libcanberra-gtk-module.so)
                                                            #28 0x00007fa8f56c52c8 n/a (libgdk-3.so.0)
                                                            #29 0x00007fa8f3e26c7a g_main_context_dispatch (libglib-2.0.so.0)
                                                            #30 0x00007fa8f3e27020 n/a (libglib-2.0.so.0)
                                                            #31 0x00007fa8f3e270cc g_main_context_iteration (libglib-2.0.so.0)
                                                            #32 0x00007fa8f43e68ec g_application_run (libgio-2.0.so.0)
                                                            #33 0x0000000000430806 n/a (nemo)
                                                            #34 0x00007fa8f2fc0610 __libc_start_main (libc.so.6)
                                                            #35 0x0000000000430869 n/a (nemo)

                                                            Stack trace of thread 17068:
                                                            #0  0x00007fa8f308018d poll (libc.so.6)
                                                            #1  0x00007fa8f3e26fbc n/a (libglib-2.0.so.0)
                                                            #2  0x00007fa8f3e270cc g_main_context_iteration (libglib-2.0.so.0)
                                                            #3  0x00007fa8e2df825d n/a (libdconfsettings.so)
                                                            #4  0x00007fa8f3e4d715 n/a (libglib-2.0.so.0)
                                                            #5  0x00007fa8f334b4a4 start_thread (libpthread.so.0)
                                                            #6  0x00007fa8f308913d __clone (libc.so.6)

                                                            Stack trace of thread 17065:
                                                            #0  0x00007fa8f308018d poll (libc.so.6)
                                                            #1  0x00007fa8f3e26fbc n/a (libglib-2.0.so.0)
                                                            #2  0x00007fa8f3e270cc g_main_context_iteration (libglib-2.0.so.0)
                                                            #3  0x00007fa8f3e27109 n/a (libglib-2.0.so.0)
                                                            #4  0x00007fa8f3e4d715 n/a (libglib-2.0.so.0)
                                                            #5  0x00007fa8f334b4a4 start_thread (libpthread.so.0)
                                                            #6  0x00007fa8f308913d __clone (libc.so.6)

                                                            Stack trace of thread 17083:
                                                            #0  0x00007fa8f308018d poll (libc.so.6)
                                                            #1  0x00007fa8af9e2f51 n/a (libpulse.so.0)
                                                            #2  0x00007fa8af9d4571 pa_mainloop_poll (libpulse.so.0)
                                                            #3  0x00007fa8af9d4c0e pa_mainloop_iterate (libpulse.so.0)
                                                            #4  0x00007fa8af9d4cc0 pa_mainloop_run (libpulse.so.0)
                                                            #5  0x00007fa8af9e2ee6 n/a (libpulse.so.0)
                                                            #6  0x00007fa8af7835f8 n/a (libpulsecommon-7.1.so)
                                                            #7  0x00007fa8f334b4a4 start_thread (libpthread.so.0)
                                                            #8  0x00007fa8f308913d __clone (libc.so.6)

                                                            Stack trace of thread 17066:
                                                            #0  0x00007fa8f308018d poll (libc.so.6)
                                                            #1  0x00007fa8f3e26fbc n/a (libglib-2.0.so.0)
                                                            #2  0x00007fa8f3e27342 g_main_loop_run (libglib-2.0.so.0)
                                                            #3  0x00007fa8f441d236 n/a (libgio-2.0.so.0)
                                                            #4  0x00007fa8f3e4d715 n/a (libglib-2.0.so.0)
                                                            #5  0x00007fa8f334b4a4 start_thread (libpthread.so.0)
                                                            #6  0x00007fa8f308913d __clone (libc.so.6)

**Comment by Zerophase** [comment]
Come to think about it I have noticed Nemo crashing every couple hours lately. I think I usually have multiple instances of Nemo open, with maybe 2 to 3 tabs on a couple of them when it happens.

**Comment by MrOats** [comment]
Are you running 2.8.6-1?

**Comment by Zerophase** [comment]
Yes, I am.

**Comment by MrOats** [comment]
Okay.. honestly I have been experiencing it since the middle of the 2.8 series. I don't know what has been going on lately.

**Comment by mtwebster** [comment]
Does anyone know what the -1 includes?

This commit: https://github.com/linuxmint/nemo/commit/fb97b62aad23bb44820713c8084785bbc147bfd7 fixes how the context menu toggle is handled, and although I can't be sure (these traces are incomplete), I'm willing to bet this is one of the issues fixed by that commit.  I'll try to get a point release put out that includes this.

**Comment by MrOats** [comment]
If somebody tells me a way to debug or logs to look for I will happily help.

**Comment by MrOats** [comment]
I ran strace on Nemo, I hope it helps.. 
[nemo-dump.txt](https://github.com/linuxmint/nemo/files/104199/nemo-dump.txt)

**Comment by MrOats** [comment]
I ran valgrind (with full memory checking) on Nemo, I hope this helps too:
[nemo-valgrind.txt](https://github.com/linuxmint/nemo/files/104275/nemo-valgrind.txt)

**Comment by MrOats** [comment]
If you have any tools you want me to run, let me know

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.
