### ISSUE TITLE
Option (by default) to change partition label from the file manager

### ISSUE THREAD

**Issue by Snevzor** [linuxmint/nemo#1069]
Instead of having for example "1337 GB volume" one should be able to change the label easily by e.g. right clicking the partition 'identifier' and choosing a rename/relabel option. 
Currently it is of course possible using the command line or with Gparted but that's not user friendly (in the sense of not easy enough and not efficient enough).

edit: some file managers provide the function but you have to unmount manually first. Someone not familiar with Linux might not know what unmounting is and the option relabel will be grayed out or not even available. Why not automatically unmount when choosing the option to relabel/rename and mounting back automatically afterwards? So: right click on partition/volume -> relabel/rename -> fill in new name -> prompt for password -> done.

**Comment by MrOats** [comment]
+1

**Comment by bitboy85** [comment]
+1

**Comment by leigh123linux** [comment]
Why should we reinvent the wheel?
It's already possible to use gnome-disk-utility to edit 'file system label' without dismounting.
