### ISSUE TITLE
[Feature Request] Rename by hitting enter

### ISSUE THREAD

**Issue by andrew160** [linuxmint/nemo#1070]
It would be very convenient if you could rename files/folders by just hitting enter, then the current functionality of enter (open) should be swapped to Ctrl+Enter

I'm sure not everyone will want this, so I think it should be an option somewhere, either in the UI or hidden.

**Comment by glebihan** [comment]
The main function of a file browser is to navigate through folders and open files.
It makes no sense to have make the shortcut to open files more complicated than a simple key press, and it is Enter is every single file browser I've ever seen.

There's already a shortcut (F2) for renaming files.

**Comment by andrew160** [comment]
@glebihan
>It makes no sense to have make the shortcut to open files more complicated than a simple key press, and it is Enter is every single file browser I've ever seen.

It's the default behavior on OS X, and since many are moving over to Linux Mint, I think it is a reasonable request.

But thanks for telling about F2 shortcut, I will use it for the time being.

**Comment by mtwebster** [comment]
You can also enable click-to-rename in preferences.  Select a file, then click on the test of its name.

**Comment by leigh123linux** [comment]
Why does every dumb Windoze/Mac user want to fuck up the default linux shortcuts?, why the fuck should I have to relearn them !

**Comment by andrew160** [comment]
@mtwebster 
Yeah, I used it a bit, but it's too slow when you're used to doing almost everything with the keyboard.

Anyway, I've been using F2 now and it's pretty much the same in terms of convenience. so disregard this request.

**Comment by wmzart** [comment]
To get the enter key working, you can change the accels/nemo file accordingly.

First set an environment variable (in /etc/environment) to:

`GNOME22_USER_DIR=~/.config/nemo`
 
(Maybe replace the tilde (~) with the real path of your profile directory.)

Then in the following directory: `~/.config/nemo/accels/`

create the following file: `nemo`

With following content:

```
(gtk_accel_path "<Actions>/DirViewActions/Rename" "Enter")
```

Or use sed in place to modify the line:

```
sed -i 's/.*DirViewActions\/Rename\".*/\(gtk_accel_path \"<Actions>\/DirViewActions\/Rename\" \"Enter\"\)/g' ~/.config/nemo/accels/nemo
```

Restart your system and it should work.


More information is visible in the source code at:

```c
char *
nemo_get_accel_map_file (void)
{
	const gchar *override;
 
	override = g_getenv ("GNOME22_USER_DIR");
 
	if (override) {
		return g_build_filename (override, "accels/nemo", NULL);
	} else {
		return g_build_filename (g_get_home_dir (), ".gnome2/accels/nemo", NULL);
	}
}
```

The path/file for accels is either “.gnome2/accels/nemo” or “$GNOME22_USER_DIR/accels/nemo”.
