### ISSUE TITLE
Delete confirmation dialog shows wrong/outdated background image

### ISSUE THREAD

**Issue by damian01w** [linuxmint/nemo#1072]
When I choose "Delete" option in file context menu, the confirmation dialog shadowed background is wrong and shows outdated image (maybe comes from previous operation).

![captura de pantalla de 2016-01-16 10-26-09](https://cloud.githubusercontent.com/assets/16244534/12372562/fd9e8e6e-bc3b-11e5-9527-a1ab175c4947.png)

![captura de pantalla de 2016-01-16 10-16-44](https://cloud.githubusercontent.com/assets/16244534/12372542/d7ddb372-bc3a-11e5-8ded-4f7ed16640c1.png)

**Comment by mjenki03** [comment]
Do you know the steps to reproduce?

**Comment by damian01w** [comment]
Steps to reproduce:
1- Choose one folder and press shift+delete (or delete from folder context menu) and click "cancel" in the confirmation dialog.
2- Choose another folder and do same thing. 
3- The confirmation dialog shadowed background is outdated and comes from previous action (step 1).

**Comment by mtwebster** [comment]
Turn off:  window settings->behavior->attach dialog windows to the parent window.

This is a bug with certain video cards and the shading used when this option is on.

**Comment by JosephMcc** [comment]
Don't think this is actually related to Nemo specifically. We also set that "attach dialogs" option off by default know since it does cause issues in certain cases.
