### ISSUE TITLE
interactive search on the desktop

### ISSUE THREAD

**Issue by apicici** [linuxmint/nemo#1073]
Among the changes in nemo 2.8.5, there is
>* nemo-icon-container: prevent interactive search on the desktop

I used to do interactive searches on the desktop quite often. Could a setting to re-enable this feature be included, should one want to?

**Comment by MrOats** [comment]
+1 I thought Cinnamon/Nemo was bugging out before. I miss this feature.

**Comment by JosephMcc** [comment]
This was reimplemented and works in Nemo 3.0

**Comment by CottonEaster** [comment]
Presumably the reason that this search was disabled in the first place was that it confused people. Now that the search is back, it has confused, to my knowledge, at least two people - and, plausibly, many more. Perhaps there should be some sort of notification, or at least a informative title box to the search window.
