### ISSUE TITLE
Nemo: Segfault 

### ISSUE THREAD

**Issue by petter3k** [linuxmint/nemo#1074]
Arch Linux x64

nemo 2.8.6

From dmesg:

```
nemo[1216]: segfault at 50 ip 0000000000494984 sp 00007ffefbaf3e18 error 6 in nemo[400000+1c2000]
traps: nemo[3518] general protection ip:494984 sp:7ffe2bf4e228 error:0 in nemo[400000+1c2000]
```

**Comment by MrOats** [comment]
Manjaro Linux x64 (from systemd):

```
Jan 17 22:36:22 ManjaroLinux.local kernel: nemo[25562]: segfault at 7f62131f92e0 ip 0000000000494984 sp 00007ffd93ad4638 error 7 in nemo[400000+1c2000]
Jan 17 22:36:25 ManjaroLinux.local systemd-coredump[10230]: Process 25562 (nemo) of user 1000 dumped core.

                                                            Stack trace of thread 25562:
                                                            #0  0x0000000000494984 n/a (nemo)
                                                            #1  0x00007f62131f0015 g_closure_invoke (libgobject-2.0.so.0)
                                                            #2  0x00007f6213202061 n/a (libgobject-2.0.so.0)
                                                            #3  0x00007f621320adfc g_signal_emit_valist (libgobject-2.0.so.0)
                                                            #4  0x00007f621320b12f g_signal_emit (libgobject-2.0.so.0)
                                                            #5  0x00007f6214dbe0fa n/a (libgtk-3.so.0)
                                                            #6  0x00007f62131f67b8 g_object_run_dispose (libgobject-2.0.so.0)
                                                            #7  0x00007f6214c90b1d n/a (libgtk-3.so.0)
                                                            #8  0x00007f6214bbc9a0 n/a (libgtk-3.so.0)
                                                            #9  0x00007f62131f0015 g_closure_invoke (libgobject-2.0.so.0)
                                                            #10 0x00007f621320257e n/a (libgobject-2.0.so.0)
                                                            #11 0x00007f621320adfc g_signal_emit_valist (libgobject-2.0.so.0)
                                                            #12 0x00007f621320b12f g_signal_emit (libgobject-2.0.so.0)
                                                            #13 0x00007f6214dbe0fa n/a (libgtk-3.so.0)
                                                            #14 0x00007f62131f4d95 g_object_unref (libgobject-2.0.so.0)
                                                            #15 0x00007f6214bbadac gtk_container_remove (libgtk-3.so.0)
                                                            #16 0x00007f6214dbe004 n/a (libgtk-3.so.0)
                                                            #17 0x00007f62131f4d95 g_object_unref (libgobject-2.0.so.0)
                                                            #18 0x00007f6214b36280 n/a (libgtk-3.so.0)
                                                            #19 0x00007f6212f232fe n/a (libglib-2.0.so.0)
                                                            #20 0x00007f6212f232d1 n/a (libglib-2.0.so.0)
                                                            #21 0x00007f6212f23e81 g_node_traverse (libglib-2.0.so.0)
                                                            #22 0x00007f6214b37901 n/a (libgtk-3.so.0)
                                                            #23 0x00007f62131f4e0a g_object_unref (libgobject-2.0.so.0)
                                                            #24 0x00000000004b955f n/a (nemo)
                                                            #25 0x00007f62131f4e0a g_object_unref (libgobject-2.0.so.0)
                                                            #26 0x00007f6208e9030d n/a (libcanberra-gtk-module.so)
                                                            #27 0x00007f6208e904b4 n/a (libcanberra-gtk-module.so)
                                                            #28 0x00007f62147ba5c8 n/a (libgdk-3.so.0)
                                                            #29 0x00007f6212f1bc7a g_main_context_dispatch (libglib-2.0.so.0)
                                                            #30 0x00007f6212f1c020 n/a (libglib-2.0.so.0)
                                                            #31 0x00007f6212f1c0cc g_main_context_iteration (libglib-2.0.so.0)
                                                            #32 0x00007f62134db8ec g_application_run (libgio-2.0.so.0)
                                                            #33 0x0000000000430806 n/a (nemo)
                                                            #34 0x00007f62120b5610 __libc_start_main (libc.so.6)
                                                            #35 0x0000000000430869 n/a (nemo)

                                                            Stack trace of thread 25566:
                                                            #0  0x00007f621217518d poll (libc.so.6)
                                                            #1  0x00007f6212f1bfbc n/a (libglib-2.0.so.0)
                                                            #2  0x00007f6212f1c342 g_main_loop_run (libglib-2.0.so.0)
                                                            #3  0x00007f6213512236 n/a (libgio-2.0.so.0)
                                                            #4  0x00007f6212f42715 n/a (libglib-2.0.so.0)
                                                            #5  0x00007f62124404a4 start_thread (libpthread.so.0)
                                                            #6  0x00007f621217e13d __clone (libc.so.6)

                                                            Stack trace of thread 25565:
                                                            #0  0x00007f621217518d poll (libc.so.6)
                                                            #1  0x00007f6212f1bfbc n/a (libglib-2.0.so.0)
                                                            #2  0x00007f6212f1c0cc g_main_context_iteration (libglib-2.0.so.0)
                                                            #3  0x00007f6212f1c109 n/a (libglib-2.0.so.0)
                                                            #4  0x00007f6212f42715 n/a (libglib-2.0.so.0)
                                                            #5  0x00007f62124404a4 start_thread (libpthread.so.0)
                                                            #6  0x00007f621217e13d __clone (libc.so.6)

                                                            Stack trace of thread 25577:
                                                            #0  0x00007f621217518d poll (libc.so.6)
                                                            #1  0x00007f61d7bdaf51 n/a (libpulse.so.0)
                                                            #2  0x00007f61d7bcc571 pa_mainloop_poll (libpulse.so.0)
                                                            #3  0x00007f61d7bccc0e pa_mainloop_iterate (libpulse.so.0)
                                                            #4  0x00007f61d7bcccc0 pa_mainloop_run (libpulse.so.0)
                                                            #5  0x00007f61d7bdaee6 n/a (libpulse.so.0)
                                                            #6  0x00007f61d797b5f8 n/a (libpulsecommon-7.1.so)
                                                            #7  0x00007f62124404a4 start_thread (libpthread.so.0)
                                                            #8  0x00007f621217e13d __clone (libc.so.6)

                                                            Stack trace of thread 25568:
                                                            #0  0x00007f621217518d poll (libc.so.6)
                                                            #1  0x00007f6212f1bfbc n/a (libglib-2.0.so.0)
                                                            #2  0x00007f6212f1c0cc g_main_context_iteration (libglib-2.0.so.0)
                                                            #3  0x00007f6205f9f25d n/a (libdconfsettings.so)
                                                            #4  0x00007f6212f42715 n/a (libglib-2.0.so.0)
                                                            #5  0x00007f62124404a4 start_thread (libpthread.so.0)
                                                            #6  0x00007f621217e13d __clone (libc.so.6)

                                                            Stack trace of thread 10229:
                                                            #0  0x00007f6212179cf9 syscall (libc.so.6)
                                                            #1  0x00007f6212f6087a g_cond_wait_until (libglib-2.0.so.0)
                                                            #2  0x00007f6212ef0a69 n/a (libglib-2.0.so.0)
                                                            #3  0x00007f6212ef108b g_async_queue_timeout_pop (libglib-2.0.so.0)
                                                            #4  0x00007f6212f4316a n/a (libglib-2.0.so.0)
                                                            #5  0x00007f6212f42715 n/a (libglib-2.0.so.0)
                                                            #6  0x00007f62124404a4 start_thread (libpthread.so.0)
                                                            #7  0x00007f621217e13d __clone (libc.so.6)
```

**Comment by bauner** [comment]
Also the same
Arch Linux x64

nemo 2.8.6
I have this problem with all 2.8.x versions

It happens after closing the nemo filemanager
dmesg:
[ 3728.919831] nemo[888]: segfault at 50 ip 0000000000494984 sp 00007fffe009c8b8 error 6 in nemo[400000+1c2000]
[ 3747.536308] traps: nemo[1755] general protection ip:494984 sp:7ffe469a6098 error:0 in nemo[400000+1c2000]

Systemd log:
Feb 19 11:09:23 pc systemd-coredump[1875]: Process 1841 (nemo) of user 1000 dumped core.
                                           
                                           Stack trace of thread 1841:
                                           #0  0x0000000000494984 n/a (nemo)
                                           #1  0x00007efc552f9015 g_closure_invoke (libgobject-2.0.so.0)
                                           #2  0x00007efc5530b061 n/a (libgobject-2.0.so.0)
                                           #3  0x00007efc55313dfc g_signal_emit_valist (libgobject-2.0.so.0)
                                           #4  0x00007efc5531412f g_signal_emit (libgobject-2.0.so.0)
                                           #5  0x00007efc56ec712a n/a (libgtk-3.so.0)
                                           #6  0x00007efc552ff7b8 g_object_run_dispose (libgobject-2.0.so.0)
                                           #7  0x00007efc56d99bbd n/a (libgtk-3.so.0)
                                           #8  0x00007efc56cc5980 n/a (libgtk-3.so.0)
                                           #9  0x00007efc552f9015 g_closure_invoke (libgobject-2.0.so.0)
                                           #10 0x00007efc5530b57e n/a (libgobject-2.0.so.0)
                                           #11 0x00007efc55313dfc g_signal_emit_valist (libgobject-2.0.so.0)
                                           #12 0x00007efc5531412f g_signal_emit (libgobject-2.0.so.0)
                                           #13 0x00007efc56ec712a n/a (libgtk-3.so.0)
                                           #14 0x00007efc552fdd95 g_object_unref (libgobject-2.0.so.0)
                                           #15 0x00007efc56cc3d8c gtk_container_remove (libgtk-3.so.0)
                                           #16 0x00007efc56ec7034 n/a (libgtk-3.so.0)
                                           #17 0x00007efc552fdd95 g_object_unref (libgobject-2.0.so.0)
                                           #18 0x00007efc56c3f280 n/a (libgtk-3.so.0)
                                           #19 0x00007efc5502c2fe n/a (libglib-2.0.so.0)
                                           #20 0x00007efc5502c2d1 n/a (libglib-2.0.so.0)
                                           #21 0x00007efc5502ce81 g_node_traverse (libglib-2.0.so.0)
                                           #22 0x00007efc56c40901 n/a (libgtk-3.so.0)
                                           #23 0x00007efc552fde0a g_object_unref (libgobject-2.0.so.0)
                                           #24 0x00000000004b955f n/a (nemo)
                                           #25 0x00007efc552fde0a g_object_unref (libgobject-2.0.so.0)
                                           #26 0x00007efc56d7ceb0 gtk_main_do_event (libgtk-3.so.0)
                                           #27 0x00007efc568f6e12 n/a (libgdk-3.so.0)
                                           #28 0x00007efc55024dc7 g_main_context_dispatch (libglib-2.0.so.0)
                                           #29 0x00007efc55025020 n/a (libglib-2.0.so.0)
                                           #30 0x00007efc550250cc g_main_context_iteration (libglib-2.0.so.0)
                                           #31 0x00007efc555e48ec g_application_run (libgio-2.0.so.0)
                                           #32 0x0000000000430806 n/a (nemo)
                                           #33 0x00007efc541be610 __libc_start_main (libc.so.6)
                                           #34 0x0000000000430869 n/a (nemo)
                                           
                                           Stack trace of thread 1844:
                                           #0  0x00007efc5427de5d poll (libc.so.6)
                                           #1  0x00007efc55024fbc n/a (libglib-2.0.so.0)
                                           #2  0x00007efc550250cc g_main_context_iteration (libglib-2.0.so.0)
                                           #3  0x00007efc55025109 n/a (libglib-2.0.so.0)
                                           #4  0x00007efc5504b715 n/a (libglib-2.0.so.0)
                                           #5  0x00007efc545494a4 start_thread (libpthread.so.0)
                                           #6  0x00007efc54286dcd __clone (libc.so.6)
                                           
                                           Stack trace of thread 1845:
                                           #0  0x00007efc5427de5d poll (libc.so.6)
                                           #1  0x00007efc55024fbc n/a (libglib-2.0.so.0)
                                           #2  0x00007efc55025342 g_main_loop_run (libglib-2.0.so.0)
                                           #3  0x00007efc5561b236 n/a (libgio-2.0.so.0)
                                           #4  0x00007efc5504b715 n/a (libglib-2.0.so.0)
                                           #5  0x00007efc545494a4 start_thread (libpthread.so.0)
                                           #6  0x00007efc54286dcd __clone (libc.so.6)
                                           
                                           Stack trace of thread 1847:
                                           #0  0x00007efc5427de5d poll (libc.so.6)
                                           #1  0x00007efc55024fbc n/a (libglib-2.0.so.0)
                                           #2  0x00007efc550250cc g_main_context_iteration (libglib-2.0.so.0)
                                           #3  0x00007efc4810025d n/a (libdconfsettings.so)
                                           #4  0x00007efc5504b715 n/a (libglib-2.0.so.0)
                                           #5  0x00007efc545494a4 start_thread (libpthread.so.0)
                                           #6  0x00007efc54286dcd __clone (libc.so.6)
                                           
                                           Stack trace of thread 1871:
                                           #0  0x00007efc542829c9 syscall (libc.so.6)
                                           #1  0x00007efc5506987a g_cond_wait_until (libglib-2.0.so.0)
                                           #2  0x00007efc54ff9a69 n/a (libglib-2.0.so.0)
                                           #3  0x00007efc54ffa08b g_async_queue_timeout_pop (libglib-2.0.so.0)
                                           #4  0x00007efc5504c16a n/a (libglib-2.0.so.0)
                                           #5  0x00007efc5504b715 n/a (libglib-2.0.so.0)
                                           #6  0x00007efc545494a4 start_thread (libpthread.so.0)
                                           #7  0x00007efc54286dcd __clone (libc.so.6)

**Comment by MrOats** [comment]
@petter3k It should be fixed soon as a point release is made and packaged for your distribution. You can manually compile it yourself as well and run it from there.

**Comment by bauner** [comment]
@MrOats 
Thx the problem is fixed after building and installing the current version myself

**Comment by petter3k** [comment]
Great. Closing the ticket.
