### ISSUE TITLE
Recursive link & nemo crash

### ISSUE THREAD

**Issue by Kruschenstein** [linuxmint/nemo#1076]
I run these stupid commands on a term:

``` shell
touch tmp
ln -s tmp l1
ln -s l1 l2
ln -s l2 l1
rm tmp
```

Then I tried to launch nemo. And when I tried to go to the directory where I run the commands, nemo crashed and I had a `Segmentation fault` error message.
If l1 & l2 links are deleted, nemo can be launched normally without any error.

This problem is not urgent, but I prefer inform you that there is a bug with that.

I'm on a Linux Mint 17.2 Cinnamon 64-bit & my nemo version is 2.6.7

**Comment by xenopeek** [comment]
The test case can be created easieer with just these commands:
```
ln -s l1 l2
ln -s l2 l1
```
This issue affects Nemo, Caja, and Nautilus (all crash with segmentation fault). Dolphin and Thunar don't have a problem with the test case.
