### ISSUE TITLE
Settings for middle click on folder

### ISSUE THREAD

**Issue by Reisenfag** [linuxmint/nemo#1078]
Now there is only the possibility to override the action for left click - open in the current / new window. Middle-click always opens in a new tab. It would be nice if it was possible to assign the opening of a new window on the middle button and the left would open as before.

**Comment by uiii** [comment]
:+1: I would really appreciate that.

**Comment by Arnaudv6** [comment]
interested too

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
