### ISSUE TITLE
error: no dependency information found for /usr/lib/libxml2.so.2

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo#1079]
On system Ubuntu Server 15.10 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64
I experience this error whether I run dpkg-buildpackage on sources with 2.8.6 tag or current commit 3c19e0262899f6a10cc499f66cde719485246bc6
I tried to reinstall libxml2 but there is no change in behavior.

...
make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Nemo/git-nemo'
   dh_installgsettings
   dh_icons
   dh_perl
   dh_link
   dh_compress
   dh_fixperms
   debian/rules override_dh_strip
make[1]: Entering directory '/home/actionmystique/Program-Files/Ubuntu/Nemo/git-nemo'
dh_strip --dbg-package=nemo-dbg
make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Nemo/git-nemo'
   debian/rules override_dh_makeshlibs
make[1]: Entering directory '/home/actionmystique/Program-Files/Ubuntu/Nemo/git-nemo'
dh_makeshlibs -Xusr/lib/nemo/extensions-3.0/
make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Nemo/git-nemo'
   dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/lib/libxml2.so.2 (used by debian/nemo/usr/lib/nemo/nemo-convert-metadata)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/nemo.substvars debian/nemo/usr/bin/nemo-connect-server debian/nemo/usr/bin/nemo-open-with debian/nemo/usr/bin/nemo-autorun-software debian/nemo/usr/bin/nemo debian/nemo/usr/lib/nemo/nemo-extensions-list debian/nemo/usr/lib/nemo/nemo-convert-metadata returned exit code 2
debian/rules:13: recipe for target 'binary' failed
make: **\* [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

Whole log: [nemo dpkg-buildpackage error.txt](https://github.com/linuxmint/nemo/files/104775/nemo.dpkg-buildpackage.error.txt)

**Comment by jean-christophe-manciot** [comment]
Here's a workaround from **[dpkg-shlibdeps: error: no dependency information found for](http://stackoverflow.com/questions/11238134/dpkg-shlibdeps-error-no-dependency-information-found-for)**: add the following lines in debian/rules:
```
override_dh_shlibdeps:
	dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
```

**Comment by laurencechan** [comment]
> Here's a workaround from **[dpkg-shlibdeps: error: no dependency information found for](http://stackoverflow.com/questions/11238134/dpkg-shlibdeps-error-no-dependency-information-found-for)**: add the following lines in debian/rules:
> 
> ```
> override_dh_shlibdeps:
>     dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
> ```
> 
> _It is necessary to insert a TAB instead of spaces before "dh_shlibdeps ..."_

This not work for me.
I add this line in debian/rules
![image](https://user-images.githubusercontent.com/17173306/70609846-7af9de80-1c3d-11ea-80e3-6546a8cf7fae.png)
But still encountered the same error message.
![image](https://user-images.githubusercontent.com/17173306/70609912-9664e980-1c3d-11ea-938f-6b022935787d.png)

**Comment by jean-christophe-manciot** [comment]
Is your editor transforming tabs into spaces?

**Comment by icarter09** [comment]
@jean-christophe-manciot are you still experiencing this issue on the latest version of nemo?

**Comment by jean-christophe-manciot** [comment]
No.
