### ISSUE TITLE
Add "Close this window then open file" to nemo

### ISSUE THREAD

**Issue by coucout** [linuxmint/nemo#1081]
Very often, as everybody i think, i open nemo to search a file and open it only, not to manipulate files (copy, paste, rename etc...).
In this context of use, it would be very cool if the concerning Nemo window could be immediately closed then the desired file is opened. I think it would be more productive because when you have finished editing/viewing the file, your brain do not need to ask : "Why this Nemo window is opened ?". Or in multitasking perspective, your taskbar is not overcrowded with unnecessary window/buttons.

So i suggest to add a function to Nemo, like "Shift Double Click" to achieve this idea, same with contextual menu "open with", "Shift click".

**Comment by coucout** [comment]
I've added an action like this in my configuration but it's a palliative and request xdotool dependency:
```
[Nemo Action]
Active=true
Name=Close this window and open the document
Exec=<LaunchThenClose.sh %F>
Icon-Name=document-open
Selection=s
Extensions=nodirs
Quote=double
```
and "LaunchThenClose.sh":
```sh
#!/bin/sh
xdotool key alt+F4
xdg-open "$1"
```

**Comment by dg1727** [comment]
This issue seems to be like #567

**Comment by JosephMcc** [comment]
Looks like a duplicate to me.
