### ISSUE TITLE
Browser should default to --no-desktop

### ISSUE THREAD

**Issue by jmadero** [linuxmint/nemo#1082]
When using Nemo in different distros - the fact that by default nemo takes over the desktop becomes problematic. 

Is there a real benefit for a file browser to take over the desktop by default vs. having the --no-desktop option enabled by default?

This is particularly problematic for anyone running Nemo on Enlightenment (E17, E18, or E19) and it's derivatives (such as Moksha). If there is no real gain to the default behavior and there is potential for problems, I suggest changing the default behavior.

Thanks

**Comment by MrOats** [comment]
Nemo was meant for the Cinnamon environment, so the desktop icons should be left for it. There is a configuration setting somewhere to make it so Nemo does not handle icons without running it with that flag. Maybe consult the packager to use that config in the installation process?

**Comment by RavetcoFX** [comment]
perhaps if it was set to detect if it was running with Cinnamon, it would only show the desktop then, and not on other DE's

**Comment by jmadero** [comment]
Feel free to close if it's not going to be changed. I've never heard of a file browser that was "meant to be used" with a single DE - thus why each is a separate package that can be installed in any DE. Nemo is hands down the best file browser for me right now and I can easily work around this (I just changed the executable in /usr/share/application/nemo.desktop) but if there is any interest in Nemo being used on non-Cinnamon DEs this issue could prevent a casual user from using it because of the default behavior.

If it's not going to be resolved I won't be irritated :) Thanks for the awesome browser

**Comment by mtwebster** [comment]
Well it actually *is* meant just for cinnamon, but we try to accomodate everyone where possible.

Hopefully in 3.0 we'll have in place a gsettings key as well as a check whether the desktop is already managed.  We have yet to add the latter, the former I broke recently while reworking desktop handling (it will be fixed).

**Comment by MrOats** [comment]
Ah, so that gsettings key I mentioned is actually broke?





On Sun, Jan 31, 2016 at 9:36 AM -0800, "Michael Webster" <notifications@github.com> wrote:












Well it actually is meant just for cinnamon, but we try to accomodate everyone where possible.



Hopefully in 3.0 we'll have in place a gsettings key as well as a check whether the desktop is already managed.  We have yet to add the latter, the former I broke recently while reworking desktop handling (it will be fixed).

**Comment by mtwebster** [comment]
No, in the current release it's fine, I meant in development currently.

**Comment by MrOats** [comment]
Sweet, hopefully things will turn out swell. Are you going to make another bug fix release soon?

**Comment by leigh123linux** [comment]
Fixed in nemo-3.4
