### ISSUE TITLE
Problem with file-roller and samba 

### ISSUE THREAD

**Issue by luca-vercelli** [linuxmint/nemo#1085]
I have a problem with file-roller, however I think it can be an issue of Nemo.

I have mounted on my laptop a remote shared folder, say smb://192.168.200.3/alkecondivisa.
The mount works, and I have read and write permissions (tested using gedit).
I go in Nemo, to the remote folder, I select the files I want compress, then I launch file-roller with right click. 
A dialog box opens, asking me if I want to compress such files. I choose the "zip" format, then press OK, and file-roller gives me an error "Not enough permissions".

Nemo launches file-roller with the following command line:
file-roller --default-dir=smb://192.168.200.3/alkecondivisa/myfolder --add smb://192.168.200.3/alkecondivisa/myfolder/file1 smb://192.168.200.3/alkecondivisa/myfolder/file2

I think the problem is that "smb://" is a protocol that only Nemo understands.

**Comment by bitboy85** [comment]
Sounds like this: https://bugs.launchpad.net/file-roller/+bug/1071759

**Comment by luca-vercelli** [comment]
I still think this is not file-roller's fault.
Reading that bug on launchpas, I realize that opening an archive with file-roller works.
Creating an archive does not work.
This depends on how file-roller is called in the two cases. When I open an archive from a shared folder, file-roller is launched with a command-line such as:

    file-roller /run/user/1000/gvfs/smb-share:server=192.168.200.3,share=alkecondivisa/mypath/myfile.zip

and not with

    file-roller smb://192.168.200.3/alkecondivisa/mypath/myfile.zip

The two notations are "the same" for the user, however most programs do not understand the second notation.

**Comment by luca-vercelli** [comment]
Problem is quite annoying.
I strongly believe the bug is here:
https://github.com/linuxmint/nemo-extensions/blob/master/nemo-fileroller/src/nemo-fileroller.c
in routine extract_to_callback().
This routine gives file-roller a URI as argument, but this is wrong, it should give an absolute local path.

**Comment by luca-vercelli** [comment]
I would like to resolve this by myself. Can anybody help me?
I want to transform an URI (smb://192.168.200.3/myshare/mypath/myfile.zip) into its real local path (/run/user/1000/gvfs/smb-share:server=192.168.200.3,share=myshare/mypath/myfile.zip).
I am pretty sure there is already some code in Nemo that does this: it is exactly what happens when I choose to "Open" a zip archive.
Can anybody tell me where is the code-snippet I am searching for?

**Comment by luca-vercelli** [comment]
I am sorry, my analysis was wrong.
This is not a bug in nemo, it is a bug in file-roller.
I have launched file-roller with "right" arguments, and the error is still present.
