### ISSUE TITLE
nemo overrides the desktop + start error

### ISSUE THREAD

**Issue by geplus** [linuxmint/nemo#1086]
When I start nemo, it override my desktop (xfdesktop in my case) whith his cinnnamon-desktop dependence. 

In the termital, it gives this error:

`(nemo:6983): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files`

see:#1082

**Comment by geplus** [comment]
#1082

**Comment by JosephMcc** [comment]
Please just add this to the already opened bug report you linked to.
