### ISSUE TITLE
Errors found by cppcheck

### ISSUE THREAD

**Issue by IgorPolyakov** [linuxmint/nemo#1088]
I found some uninitialized variable.
[libnemo-private/nemo-action.c:465]: (error) Uninitialized variable: is_desktop
[libnemo-private/nemo-icon-canvas-item.c:451]: (error) Uninitialized variable: scale

**Comment by xenopeek** [comment]
> [libnemo-private/nemo-action.c:465]: (error) Uninitialized variable: is_desktop

This one is solved. is_desktop is initialized on line 440: https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-action.c#L440

> [libnemo-private/nemo-icon-canvas-item.c:451]: (error) Uninitialized variable: scale

This one isn't solved but doesn't do harm right now. scale is indeed not initialized (so could lead to divide by zero) but it is set in the same block as pixbuf and pixbuf is initialized as NULL. On the lines scale is used pixbuf is checked and if it is NULL then scale isn't used. As currently written a divide by zero can't happen from uninitialized scale.
```
   GdkPixbuf *pixbuf = NULL;
   gint scale;

   if (item != NULL) {
       canvas = EEL_CANVAS_ITEM (item)->canvas;
       scale = gtk_widget_get_scale_factor (GTK_WIDGET (canvas));
       pixbuf = item->details->pixbuf;
   }

   if (width)
       *width = (pixbuf == NULL) ? 0 : (gdk_pixbuf_get_width (pixbuf) / scale);
   if (height)
       *height = (pixbuf == NULL) ? 0 : (gdk_pixbuf_get_height (pixbuf) / scale);
```
