### ISSUE TITLE
Nemo Text File Preview

### ISSUE THREAD

**Issue by EvilSupahFly** [linuxmint/nemo#1089]
It's been so long now since I started using Nemo that I can't recall, but at one point, didn't the Preview function also generate thumbs of plain text files?

Can that be re-added?

**Comment by ChrisJAllan** [comment]
The option is still there in Preferences->Preview, so this is most likely a bug.

**Comment by JosephMcc** [comment]
That option only works in certain gtk versions. At some point after gtk3.10, don't remember which version, that functionality was removed. That option will likely be removed soon. We just haven't gotten around to yet.

**Comment by EvilSupahFly** [comment]
Well that explains it then. I'm running 3.16.7.

Thanks, @JosephMcc

**Comment by donlencho** [comment]
Sad. I'd like to turn this into a feature request then.

**Comment by JosephMcc** [comment]
@donlencho I would consider it gone for good. Even before it was removed it didn't work properly with HiDPI. It would probably be far more work than it's worth for something that provides a very small amount of functionality if it was even possible.

**Comment by ManIVIctorious** [comment]
@donlencho this won't be possible for the cinnamon devs since the functionality was removed in the underlying gtk library, maintained by an other project
