### ISSUE TITLE
Hidden files/folders, show icons with different shade of color

### ISSUE THREAD

**Issue by kiranmys999** [linuxmint/nemo#1093]
When I select from menu to show hidden files and folders in Nemo, the color of the files and folders is the same shade as the non hidden files. This makes it visually hard to distinguish hidden from non hidden. I have to stare at the screen to find the dot preceding the hidden files.

It would be much more convenient to visually distinguish if the hidden files and folders are colored with a different shade than the non hidden ones. This feature already exists in Dolphin, Thunar, PCmanFM file managers.

**Comment by palmerito0** [comment]
Agree. Its even in windows.

**Comment by uiii** [comment]
:+1:

**Comment by chmln** [comment]
hate to +1 but +1

**Comment by defnull** [comment]
This is not an easy change. Currently hidden files are filtered out way before displaying.

**Comment by fischel** [comment]
+1 that will be a great feature :)

**Comment by biberesser** [comment]
Still no progress? *bump*
Just open your own home directory with Nemo (with visible .dotfiles): Wall of .dotfiles.
Now try quickly scanning for your documents folder...

Windows Explorer solves this usability issue quite well:
In Windows Explorer _hidden_ files (equivalent of .dotfiles) are visibly greyed out,
and _compressed_ files (NTFS file system compression) are colored blue-ish.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
