### ISSUE TITLE
Cannot get rid of desktop after latest upgrade

### ISSUE THREAD

**Issue by SandiDusic** [linuxmint/nemo#1097]
I'm using a tiling WM (awesome) so I have no use for the desktop (it only appears in the workspace I've first run nemo in, making it even less convenient). Upon installation, I've consulted [this wiki page](https://wiki.archlinux.org/index.php/Nemo#Show_.2F_hide_desktop_icons) to successfully disable the desktop. After the latest (system-wide) upgrade the desktop appears again. Not even running nemo with `nemo --no-desktop` gets rid of it.

The OS is Manjaro, if it's any help.

**Comment by mtwebster** [comment]
What version are you running?  This is broken in current development, due to some major changes to desktop handling being worked on, and will be fixed before the next release.   It should be fine using the current *release* version, however.

**Comment by SandiDusic** [comment]
I'm using nemo-2.8.6.r20.gf539ba5-1 The problem might be that Arch is a rolling release, so I got a newer version. I could rollback. Which version would suffice?

**Comment by mtwebster** [comment]
The latest tagged version should be fine - 2.8.6

If you want a few additional bug fixes, try the branch `2.8-maintenance` - it will be rolled out as 2.8.7 here soon.

**Comment by itzexor** [comment]
SandiDusic, you should report this to the manjaro packagers here https://github.com/manjaro/packages-community/issues

The arch packages use the stable version, so they should be fine if you can install them. There are 11 different packages to cinnamon though.

**Comment by mtwebster** [comment]
Fixed in source: https://github.com/linuxmint/nemo/pull/1109
