### ISSUE TITLE
Illogical triangle on column title for indicating sort

### ISSUE THREAD

**Issue by coucout** [linuxmint/nemo#1098]
Am I the only one thinking that the triangle indicating sort are inverted on column titles ?
For example, sort on "size", seeing the shape of the triangle from top to bottom, logically it must be like that, no ? :
▼ : the largest files first, the smallest at the end of the list
▲ : the smallest files first, the largest at the end
But in nemo, it's inverted. Why ?
My logic, like in MS Windows:
![triangle_logic](https://cloud.githubusercontent.com/assets/3479885/13147127/4c6a8ba2-d658-11e5-99f5-746a4462b5aa.png)

But i think in nemo (and others software), theses triangles are understood as "arrows". So why not go to the end of the logic and use "true" arrow, like in Google Drive on the web:
![google_drive_logic](https://cloud.githubusercontent.com/assets/3479885/13147173/7c0510f8-d658-11e5-8ee5-9a7a9bf3caf8.png)

It would be less ambigous. For the moment is there a way to change the characters code used to display these information in Nemo config files ?

**Comment by coucout** [comment]
Oups, i've made a mistake because, even in Google Drive, the logic is the same that in MS Windows.
So there's really a bug in Nemo (and others product)
There's a very interesting blog article about that, and gnome utilisation of triangles here : http://notes.ericjiang.com/posts/456

**Comment by JosephMcc** [comment]
This is the sort of thing that could be argued from both sides all day long. The fact though is that what Nemo currently uses is the convention among gnome apps and even qt apps under linux. Like vlc. So weather it is the "best" or "right" way, I don't think matters much. Changing Nemo to completely break the convention used by most the other common apps on a typical linux system would probably be a bad idea.
