### ISSUE TITLE
Improve user rights and ownership management

### ISSUE THREAD

**Issue by joe-13** [linuxmint/nemo#1100]
Hi
I find it very awkward to manage rights and ownership graphically with nemo.
For example, from my account (administrator), I want to manage rights and ownership for my kid's folder X (located in /home/kids_name).
Let's say I want to modify the group (from 'kids_name' to 'family') and the rights (read and write for this group).
Well I can't do it recursively for all the files, when root (through nemo option open folder as root... I know some people hate it but you can't expect people doing those tasks once in a while to know the command lines - and it's so much easy graphically).
And I can't do that when simply using my (admin) account. The option doesn't show up in the 'permissions' tab of the properties.

The only way I managed to do that so far is to use gnome commander, with the root permission.

**Comment by xenopeek** [comment]
Whether as normal user or as root, there is a button to apply the **permissions** of a directory to the enclosed files. There is no button to apply **ownership** (owner and group) of a directory to the enclosed files. I take it you are expecting the button to apply permissions to also apply ownership?

You can only change permissions on files if you are the owner or you are root.

**Comment by gabrielfern** [comment]
the button does not work @xenopeek (not even to change only permissions to enclosed ones)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
