### ISSUE TITLE
Nemo Memory Leak

### ISSUE THREAD

**Issue by jadenPete** [linuxmint/nemo#1101]
Recently, after installing the Unity-compatible version of Nemo from WebUpD8, I encounter a memory leak. I can prove this, because I left it running in the background for about two hours and it ate about 350 MB. They said to report any non-unity related bugs to the mainstream github page (here), so here I am. can someone help me? Page: http://www.webupd8.org/2013/10/install-nemo-with-unity-patches-and.html

**Comment by rynomster** [comment]
I'm having a serious problem with nemo lately on ubuntu 15.10:
nemo:
  Installed: 2.8.6+really2.6.7-2~webupd8~wily1
  Candidate: 2.8.6+really2.6.7-2~webupd8~wily1
  Version table:
 *** 2.8.6+really2.6.7-2~webupd8~wily1 0
        500 http://ppa.launchpad.net/webupd8team/nemo/ubuntu/ wily/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.7-1 0
        500 http://za.archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages

I've had to kill it a few times in the past week, as memory usage is sometimes as high as 4GB, and it often is using 70% of one of my cores. I really love nemo, it's great, but its starting to become a bit frustrating.

**Comment by JosephMcc** [comment]
So both of you are running non official versions of Nemo. I would be curious to know if this happens running the official version. If not you need to take it up with the webupd8 team.

**Comment by rynomster** [comment]
I'll give it a bash

**Comment by JosephMcc** [comment]
Also keep an eye on nemo's memory usage and see if you see a lot of increases happen when doing certain things.

**Comment by jadenPete** [comment]
I've installed an older, more stable version from noobslab and it works fine. I think it's just the newer versions.

**Comment by mtwebster** [comment]
Well that's helpful.

**Comment by jadenPete** [comment]
How do I install the official version?

**Comment by jadenPete** [comment]
Wait a minute. I think this is nautilus's fault. When I was running the latest version of nautilus, a while back (a stable version, provided by ubuntu), it had a memory leak. Since nemo is based on nautilus, and this happens with the more recent versions, I think it is nautilus.

**Comment by jadenPete** [comment]
Nevermind, Noobslab updated their ppa too :(

**Comment by mehdip2007** [comment]
im using Antergos/Arch linux and recently nemo ram consumption goes up to 2.5GB in 8 hours of working and up to 5.6GB with idle system the version im using are as the followings :
nemo version : nemo 3.0.0
 uname -a :
Linux Arch 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux

is there anything we can do about about other that killing it?

**Comment by mc0e** [comment]
@mehdip2007 asking [once](https://github.com/linuxmint/nemo/issues/378) is enough.

**Comment by kehugter** [comment]
Still huge leaks in Debian testing. Goes up to 7-8GB on light usage a couple of time a day.

nemo 3.0.6

**Comment by igormp** [comment]
This seems to still be an issue on 3.8.2 while just idling on my home folder.
![myimage](https://user-images.githubusercontent.com/5247904/40572326-41db6efa-607f-11e8-9f02-0a3a089bde99.png)

**Comment by leigh123linux** [comment]
Closed, adding a screenshot of ram use isn't useful!

**Comment by igormp** [comment]
Which other info could be useful? I'd be glad to provide any.
I'm currently using it on Arch, but since it seems to be a problem across some distributions, I doubt this is of any relevance.

**Comment by leigh123linux** [comment]
Start a new issue and provide template info and plugins list.

To get plugins run (path will need changing for arch).

```
/usr/libexec/nemo-extensions-list
```
