### ISSUE TITLE
Padding on tab text

### ISSUE THREAD

**Issue by tacojones** [linuxmint/nemo#1108]
There's a space on child tabs in front of the tab text (see image below). It doesn't seem to be possible to get rid of the space, and the white space/padding sometimes doubles with new child tabs.

Also, it's currently impossible to set different text colors for active and inactive tabs. I've read that this is a gtk3 parsing issue, and it's always been possible with gtk2. But it might be possible as a theming feature in Nemo?

http://i.imgur.com/Xqdcm7U.png

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
