### ISSUE TITLE
Hiding a files whith "hidden files hidden" does not work 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#1110]
How to reproduce the issue:
- create a new text file 
- Raname it to ".hide"
- The old name persists 
- If you open the file in gedit, the new name is shown 
- If you rename it again to a non dot name the file name changes as desired 

nautilus 3.10 suffers the same issue

**Comment by xenopeek** [comment]
This looks to be related to #491 and likely have the same root cause.

**Comment by icarter09** [comment]
@daschuer are you still experiencing this issue on the latest version of nemo?

**Comment by xenopeek** [comment]
Taking another look at it, this is exactly the same issue as #491 so closing this one.
