### ISSUE TITLE
Desktop does not follow "Show hidden files" setting 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#1111]
Hidden files are always hidden. 
That is not that bad, but the desktop context menu allows to toggle the setting. 
(Which effects all Nemo windows by the way)

**Comment by daschuer** [comment]
Yeehaw, I got #1111 :-)

**Comment by ManIVIctorious** [comment]
Unfortunately I have been faster ;)
#312

**Comment by xenopeek** [comment]
This is a duplicate of #312 and can be closed as such I think.
