### ISSUE TITLE
Allow Scrips to Be Set as "Run" or "Run in Terminal" on a Script-by-Script Basis

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/nemo#1112]
Hi,

As things stand just now in Nemo it is only possible to make a "global setting" to have scripts run automatically on double-clicking on them. Such a setting is made in **Nemo Edit > Preferences > Behaviour (tab**), under the item "**Executable Text Files**", "**Run executable text files when they are opened**".

The problem with this setting is that it is a global setting and would affect all scripts. From that point of view it is actually a dangerous setting to have around, so much so that it is a security vulnerability in Linux Mint, (I'm very surprised that users aren't required to 'sudo' to make that setting at all).

In any case, I would like to request the following items as a feature request:

In Nemo the user should be able to right-click on a script and have the following options available and, when set, applied permanently for that individual script (until such times as the user changes the setting):
a) "Automatically run this script when it is opened/launched.
b) "Automatically run this script in the terminal when it is opened/launched."
c) "Automatically display this script in a text editor when it is opened/launched."

I would add that making such a setting for any individual script should require the user to enter the sudo password to apply that setting to the script. (Doing this plugs the security vulnerability.)

In doing this the user is effectively setting up a default action for each **individual script** when it is double-clicked to open/launch - just like the options available here:

![screenshot from 2016-03-06 12 44 03](https://cloud.githubusercontent.com/assets/15947700/13554184/611c85b6-e399-11e5-8d3c-d9a1abe99bc6.png)

However, the important thing here is that this is done on a **script-by-script basis** and the action set is performed automatically on double-clicking the script. As a bonus this gets away from the dangerous global setting.

I hope my idea is found useful.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
