### ISSUE TITLE
Add option to launch terminal window maximized

### ISSUE THREAD

**Issue by miloskroulik** [linuxmint/nemo#1113]
It would be useful, if we could launch terminal window from Nemo maximized. The result should be the same as running:

`gnome-terminal --window --maximize`

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
