### ISSUE TITLE
Nemo 2.8.x as well as 2.6.x doesn't create new "Empty Document" in the correct folder

### ISSUE THREAD

**Issue by hotice** [linuxmint/nemo#1117]
I've tried this with both Nemo 2.8.7 as well as 2.6.7 and sometimes when right clicking and selecting "Create New Document" > "Empty Document", it doesn't create the document in the current folder but a different one. See below.

Steps to reproduce:
have a folder ~/Downloads/test which has a subfolder ~/Downloads/test/testsubfolder
1. Open "Downloads" from the sidebar, then **quickly** (if not done quickly enough, the bug doesn't occur) middle click Downloads from the sidebar again, so it also opens in a new tab
2. on the second Downloads tab, middle click "testsubfolder" so it opens in a new tab
3. switch to the "testsubfolder" tab
4. in the "testsubfolder" tab, right click and select "Create new document > Empty document".

The result varies:
- sometimes nemo just crashes
- sometimes the new empty document is created under ~/Downloads/test, and not as it should be, under ~/Downloads/test/testsubfolder
- most of the times the file is created under ~/Downloads, instead of ~/Downloads/test/testsubfolder

This last case happens most of the time and there's nothing in the debug log about it. Unfortunately I was unable to catch one of the crashes while running gdb.

Tested with 0 extensions enabled.

**Comment by xenopeek** [comment]
Can you reproduce this issue on Nemo 3.0.6? I can't reproduce it on that. But your steps to reproduce are either missing a step or have one directory too many so I might not be doing the same test.

You say:
> have a folder ~/Downloads/test which has a subfolder ~/Downloads/test/testsubfolder

And then:
> 1. Open "Downloads" from the sidebar, then quickly (if not done quickly enough, the bug doesn't occur) middle click Downloads from the sidebar again, so it also opens in a new tab
> 2. on the second Downloads tab, middle click "testsubfolder" so it opens in a new tab

But when I open Downloads from the sidebar I see the test directory, not the testsubfolder directory in that.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
