### ISSUE TITLE
Read file properties of every file

### ISSUE THREAD

**Issue by blade1989** [linuxmint/nemo#1118]
I Installed `nemo-audio-tab` package a while back, and love it, but I still would love to see the file properties of more file types. I tried a cli software called `exiftool`, and it displays the metadata of Muziek/VIdeos/Documents files.

I tried to edit the files in the `nemo-audio-tab` package, so that it displays the file properties(metadata and all), of all supported files, by using the output of exiftool. But, not really well versed in `Python`. So, I got nowhere.

Anther tool that can read the `metadata` of media files is `medainfo`

**Comment by bitboy85** [comment]
I 've created a nemo-video-tab. Just copy the files in the zip to /usr/share/nemo-python/extensions.
Its a parser for mediainfo. Bit rough but should work. It also gives you an idea how to create a version useable for pictures.
If anyone wants to put it in the repo feel free to do so.
[nemo-video-tab.zip](https://github.com/linuxmint/nemo/files/180820/nemo-video-tab.zip)

**Comment by blade1989** [comment]
@bitboy85 Thanks, tried it out. Looks good. But, more interested in the meta data file. Also, do you know if this will ever work?

**Comment by blade1989** [comment]
Wrong Button xD

**Comment by bitboy85** [comment]
Not sure what you mean with meta data file. My provided extension can only parse output from mediainfo cli version. If the information is not given, its not possible to show it in the property window. If its there you can easy edit the python file to extract the lines you wanting to have.

**Comment by mxyzplx** [comment]
Thanks for the nemo-video-tab. I've been looking for something just like that for I don't know how long.

**Comment by blade1989** [comment]
@bitboy85 typo! metadata of the file.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
