### ISSUE TITLE
Reopen: Bookmarks won't retain folder colour

### ISSUE THREAD

**Issue by airatin** [linuxmint/nemo#1119]
This is a copy of #1071 which was closed but still isn't fixed...

"Hi,

Whenever I reboot Cinnamon or start Linux (Mint, 17.3), the folder colours won't appear in the bookmarks. However, they do appear once I click on that folder in Nemo. It would be nice if they appeared in the bookmarks right when I start the system, without having to click on them (or open a Nemo file directory to where these folders are located). Maybe I'm not explaining it well, so please see attached pictures (I added 2 custom colours of my own, in case you're wondering where those are from).

When I start up the system:
![1](https://cloud.githubusercontent.com/assets/16682521/13724300/2e962222-e84f-11e5-829e-791b833a5df1.png)

After I open the file directory where the bookmarks (folders) are located, or click on them individually:
![2](https://cloud.githubusercontent.com/assets/16682521/13724301/396e3bc6-e84f-11e5-9dfe-4470b96c0bc9.png)"

**Comment by mtwebster** [comment]
Don't do this, just ping me on the other bug again.
