### ISSUE TITLE
Clicking twice needs a little enhancement

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/nemo#1120]
Whilst it's very handy to be able to click a file, pause, and then click it again to edit its name, there are times when this doesn't behave in what I'd consider an intuitive fashion. Perhaps it's because I'm more used to the Windows behaviour, but for me, intuitive behaviour is: "If you click an already-selected file, you can edit its name."

This would mean that you can click a file that has already been selected using the keyboard in order to edit its name. It would also mean that you don't have to re-click within a set period of time to edit the name. (Currently, you have to click it, pause -- but not for too long -- and re-click.)

**Comment by mtwebster** [comment]
The behavior you describe is exactly what we wanted to avoid here.  As a long-time windows user (as I type this at work, on a windows box) the most annoying thing would be the constant accidental triggering of renaming, or the 'oh crap I have to select something else first then re-select this or else it'll try to rename it' garbage.

Between having a timeout, as well as having it only trigger if you select the *actual text* of the item, I felt we got a decent trade-off between functionality and staying out of the user's way.

**Comment by rmwiseman** [comment]
Fair enough, though for me, accidental rename happens much more on Nemo than it ever did on Windows.  But that's fine: at least I can disable it on Nemo!  Thanks for responding so quickly.
