### ISSUE TITLE
Nemo reports false file system size

### ISSUE THREAD

**Issue by cardich** [linuxmint/nemo#1122]
Re. Linux Mint 17.3 'Rosa' Cinnamon 64-bit (fully updated on March 22, 2016)
When I open (from the desktop) Computer/File System/Properties, it reports:
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
Contents: 692191 items (and 2037 hidden), totalling 140,8 TB
(some contents unreadable)
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
This is incorrect because my disk size is 500 GB.
Also, the number of items is not reproducible.

**Comment by itzexor** [comment]
This should be fixed by commit https://github.com/linuxmint/nemo/commit/fe1f9cd21b521a5f2a89aa6be105fb1af86406b9 also see #1050. I'm not sure when this will be available in mint 17.3, though.

**Comment by JosephMcc** [comment]
I closing this since it should be fixed in git master in addition to being a duplicate.
