### ISSUE TITLE
Nemo replaces desktop background in Cinnamon

### ISSUE THREAD

**Issue by rpbaptist** [linuxmint/nemo#1124]
A bit of background: 

I removed the file `/usr/share/glib-2.0/schemas/org.gnome.desktop.background.gschema.xml` because it was drawing over Cinnamon's background. See https://github.com/linuxmint/Cinnamon/issues/4862

Now when I start Nemo I see the following error:

```
(nemo:4741): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(nemo:4741): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.background' is not installed

[1]    4741 trace trap (core dumped)  nemo .
```

I get it that removing schemas can break things, but I don't think this should be a requirement for nemo when I am using `org.cinnamon.desktop.background`.

**Comment by rpbaptist** [comment]
More information:

I editted the file `org.gnome.desktop.background.gschema.xml` so it was refering to a valid image.

I am now in the following situation:

I can select an image with cinnamon backgrounds. This image will remain until I start nemo. Nemo will replace the cinnamon settings with the gnome settings listed in this schema file.

I don't think nemo should be changing the wallpaper in cinnamon, so this definitely appears to be a bug to me.

The warning above seems to be unrelated, but something I will look into as well.

**Comment by mtwebster** [comment]
Nemo does not depend on nor use org.gnome.desktop.background schema.  Talk to the maintainer of the ppa you're using, I have no idea why this change was made here.

**Comment by rpbaptist** [comment]
You are completely right. I installed nemo from a ppa meant for Unity. Thanks for your response.

**Comment by rpbaptist** [comment]
I upgraded nemo from your official nightly PPA and problem solved :smile:
