### ISSUE TITLE
remove files from a folder but still show number of items

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/nemo#1126]
hi every body
i work with nemo and see when i remove or delete or move some files from a specific folder the number of items that show with gray color  unther each folder don't update and i must enter and close to force update item numbers!!
any idea to fix this problem?

**Comment by f2404** [comment]
Seems to have been fixed in 3.0.0.

**Comment by JosephMcc** [comment]
@LinArcX Can you test if you are still having the problem under Nemo 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by SerafDosSantos** [comment]
Like this? #1326 Could it be related?
