### ISSUE TITLE
switch between folders like windows  7 or later

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/nemo#1127]
a useful and very common actions i do in windows is that:
when i select specific folder to rename or copy his name or something else, i can switch in "Selection Mod" with Tab key.
in the other words, i can jump between Arbitrary folder with "Tab key from keyboar" and rename for example a folder.
but this act, still does not exist in nemo!
is it possible to wish some day i have this improvment?!
so thanks..

**Comment by RafaelOliveira** [comment]
This is something I want from Windows. If you are renaming a file, you can use Tab to rename the next file without need to click in that file and select rename. Its easy to rename fast many files.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1020
