### ISSUE TITLE
Slow file transfers on CIFS shares

### ISSUE THREAD

**Issue by emosuka** [linuxmint/nemo#1129]
Writing files to a CIFS share using Nemo is exceedingly slow. I get 11-12 MB/s at most. The same transfer using `cp` will max out my Gbit ethernet, however.

It's likely an issue with the way the share is mounted, or with some arcane network configuration, or it could be on the remote end (FreeNAS in my case), but then issues like this are very common and there's an endless list of possible causes. The problem even pops up often enough in pure Windows networks (at least using other file managers than Explorer) and if you try to Google for a solution you'll find people mostly end up giving up on fixing the underlying issue.

The _workaround_, meanwhile, is always the same: transfer larger chunks. It seems Nemo uses `g_file_copy()` which if I'm reading the glib source code right uses a 64kB buffer (hard-coded of course). That may be perfectly fine in theory, but in the real world networks rarely run as smoothly as that.

So is there any way the block size used for file copy/move could be a user setting?

**Comment by pedroapero** [comment]
I can confirm it's not related to the mounting method or to FreeNAS. I use Debian (nemo_2.2.4-2) to copy to Windows. I get the same result mounting the share manually or with nemo. I mount manually, I get 6MB/s when copying with nemo and 30 with cp/rsync.

**Comment by tosiara** [comment]
I have same issue on Mint 18.3 with Nemo 3.6.5
cp, rsync and ddrescue gives 13 MB/s, while copying same file to the same share using Nemo gives just 3 MB/s
Tried to mount cifs with different versions (3.0, 2.0, 1.0) - no effect
Remote samba server runs on Ubuntu 16 version 2:4.3.11+dfsg-0ubuntu0.16.04.13

**Comment by leigh123linux** [comment]
There is nothing we can do to fix slow gvfs-smb so file the issue against gvfs instead.
