### ISSUE TITLE
Symlinks to desktop files are untrusted (was: refuses to launch application symlinks)

### ISSUE THREAD

**Issue by maxyz** [linuxmint/nemo#1130]
Forwarding: Debian#814771 http://bugs.debian.org/814771

Originally submitted by Michal Suchanek:
I made a symlink on my desktop

lrwxrwxrwx chromium.desktop -> /usr/share/applications/chromium.desktop

When I try to start chromium from my desktop nemo complains that the
application is non-executable and untrusted. There is no reasonable way to make
the application file in /usr/share/applications executable. The symlink itself
is.

Please amend this mechanism so that launching symlinks to system applications
is possible without nemo complaining.

**Comment by icarter09** [comment]
@maxyz are you still experiencing this issue on the latest version of nemo?

**Comment by xenopeek** [comment]
This can be reproduce in Nemo 4.6.4 on Linux Mint 20 Cinnamon:

1. Symlink some file to the desktop, say Calculator with command: `ln -s /usr/share/applications/org.gnome.Calculator.desktop ~/Desktop`
2. Double-click the Calculator symlink on the desktop results in: ![image](https://user-images.githubusercontent.com/21159972/85861898-4c9ab580-b7c1-11ea-9476-32322925163c.png)

There appears to be no way to mark this symlink to a desktop file as trusted.

**Comment by smurphos** [comment]
Relatively straightforward to work around
`sudo chmod +x /usr/share/applications/org.gnome.Calculator.desktop`
then
`ln -s /usr/share/applications/org.gnome.Calculator.desktop ~/Desktop`

But why would you symlink to a launcher anyway? Copy the launcher to the Desktop. This is effectively the same as right click on the application in the menu and add to desktop.

`cp /usr/share/applications/org.gnome.Calculator.desktop ~/Desktop; chmod +x ~/Desktop/org.gnome.Calculator.desktop`

**Comment by xenopeek** [comment]
Thanks. That made me open Nemo as root and indeed when I launch the symlink from there Nemo does offer to option to mark it as trusted (which is currently done by setting execute permission on the .desktop file). I'll consider this solved.

Related to #1404
