### ISSUE TITLE
Large folder issues

### ISSUE THREAD

**Issue by pkese** [linuxmint/nemo#1132]
I have a decent computer with 16 GB memory and a fast CPU, because I do a lot of image analysis.

So I have large folders with gigabytes of really small jpegs and lots of issues with Nemo.

First of all, I had to disable thumbnails overall. Otherwise my computer would block so badly - up to a point when it would become so unresponsive that nothing but a hard-reset would get it back to life (I can't even ssh into it or [ctrl][alt]-[f1] switch to text mode).

Even with thumbnail generation disabled, it still takes up minutes to display anything in the folder (usually I don't actually browse those big folders, but rather just open them and click on the first image to launch an image preview program like Shotwell).

The other thing is issues with having an open folder window while at the same time another program is generating/filling new images into that folder or updating existing ones. Things just become unresponsive (not sure though if that was when I still had thumbnails enabled).

I just wish things could just work without breaking.

**Comment by emosuka** [comment]
Sadly I think the best you can do right now is use another file manager.

Nemo is unbelievably slow when browsing folders, and that's an issue that comes up a lot. The fact that no developers are chiming in suggests that improving it is not a priority.

Why Nemo is the default file manager on Mint is a bit of a mystery to me. It seems very unfinished compared to some of the alternatives. I suggest you give Thunar a try.

**Comment by howdev** [comment]
Thunar is incredibly fast. Mint should contribute and use Thunar instead.
there are threads about Nemo. Nemo has been slow a few versions back. It seems to me also they do not think it is important problem.

**Comment by LinuxOnTheDesktop** [comment]
Here is way the problem could be mitigated: Nemo could have some sort busyness indicator. Just now (on the Mint alpha build), I opened a folder containing many files, tried to which from thumbnail to icon view, and thought Nemo had hung. In fact, Nemo was merely busy dealing with the icons. Had I _known_ it was busy, I'd have had a better experience.

Compare perhaps also the following issues: #1123; #1907; #2061.

@howdev: well, there are some pretty nice things about Nemo.

**Comment by howdev** [comment]
@LinuxOnTheDesktop even if Nemo had busy indicator. if taking too long to load a folder, the indicator still indicate it had hung.

Nemo is a fork of Nautilus and is in more distributions than Thunar. Even now Ubuntu still uses Nautilus.

**Comment by xenopeek** [comment]
Thumbnail generation is much improved in Nemo 4.6.4, delaying that as much as possible (till files scroll into view) to reduce I/O load. This should solve both above issues.
