### ISSUE TITLE
Hitting out of pants when rename a file in "LIST VIEW"

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/nemo#1134]
my home directory is very messy and every time i want to rename a Long file name i face a proble.
see pictures:
<a href="http://uupload.ir/"><img src="http://uupload.ir/files/gjig_11111.png" border="0" alt="آپلود عکس" /></a>

<a href="http://uupload.ir/"><img src="http://uupload.ir/files/449p_222222.png" border="0" alt="آپلود عکس" /></a>

<a href="http://uupload.ir/"><img src="http://uupload.ir/files/1qv_33333333.png" border="0" alt="آپلود عکس" /></a>

**Comment by f2404** [comment]
This seems to have been resolved in 3.0.0.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
