### ISSUE TITLE
"Arrange items" needs an option (or multiple options) to reverse-sort

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/nemo#1140]
I like to have my Nemo windows with the most recently-modified files at the top.  It appears to be possible to automatically sort newly-opened windows by modified time, but always with oldest at the top.  It would be really useful to have a "reverse order" tickbox or both "By Modification Date" and "By Modification Date (reverse)" or similar.

I'm using Nemo 2.8.7 on Mint 17.3.

**Comment by u2n** [comment]
Same preferences here. Achieve by:

Edit | Preferences | Behavior tab | Ignore per-folder view preferences <<-checked
and:
On Views tab, pick: By Modification Date
then:
Click column header Date Modified to select desired sort direction, in our case, newest on top.

Note there is a separate issue with the date pointer direction. In all of Linux, the convention is: pointer down = oldest first, pointer up = newest first. MS Windows uses the opposite.

Sometime after the Nautilus fork, the pointer convention was reversed, which aligns Nemo with MS Windows -- and makes confusion for regular Linux users. This really needs to go back as it was before the change, unless all other projects in the world of Linux also agree to the switch.

**Comment by rmwiseman** [comment]
I'm now using Nemo 3.8.6 on Mint 19 and this feature is still missing.  I find it very hard to believe that it's only a minority of people who like to see their latest files at the top of the list by default!  I did check out the source from Github to see if I could work out how to implement the feature, but I fear my changes would be a bit of a hack.  From what I've seen, though, it doesn't _feel_ like it would be a big change to have a "reverse default sort direction" tickbox in the preferences alongside the "Sort folders before files" option.

**Comment by mtwebster** [comment]
You've always been able to select the sort type from the menu a second time to reverse it (the arrow changes direction to signify it) - it's just not documented or very discoverable.  I'll be moving the sort options to the new popup window and this feature will be available there.  Note the sort doesn't apply itself to generic things like the 'Computer' icon.

**Comment by rmwiseman** [comment]
No problem -- I really appreciate your time and effort.

**Comment by esauvisky** [comment]
No progress on this feature? It's basically the only thing stopping me from moving from s* nautilus to nemo :sob:

**Comment by mtwebster** [comment]
So it turns out this setting has been implemented from the beginning, there was just never a way to change it in the preferences.

For the time being you can use the command line to set it:

```
gsettings set org.nemo.preferences default-sort-in-reverse-order true
```
or
```
gsettings set org.nemo.preferences default-sort-in-reverse-order false
```

**Comment by rmwiseman** [comment]
Fantastic!  Many thanks.
