### ISSUE TITLE
Ability to specify two starting directories when openning with 2 panes

### ISSUE THREAD

**Issue by JosephHenley** [linuxmint/nemo#1143]
Hi,

I use nemo with two panes.  I can specify only one starting directory on the command line.  It would be great to be able to specify the starting directories for each of the two panes.  Thanks!

Joe Henley

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
