### ISSUE TITLE
Nemo crashes when adding a column to search result list

### ISSUE THREAD

**Issue by jf99** [linuxmint/nemo#1145]
Steps to reproduce:
- Start a search in any folder
- Right-click the column-title bar
- In the context menu add another column e.g. "Date modified"
-> segmentation fault in nemo

This happens on Arch with Nemo 2.8.7-4.

Related to that: When you remove a column via the same context menu, the column disappears but when you open the context menu again, it is still selected (Look at the attached screenshot where I removed "Size" but it's still there). Removing another column makes nemo crash.
![nemo-search](https://cloud.githubusercontent.com/assets/7962377/14638076/d4299062-0635-11e6-8be0-43174f7ef177.png)

**Comment by f2404** [comment]
Works for me in 3.0.0.

**Comment by jf99** [comment]
Nope, still an issue in 3.0.0 for me. However it does not happen on another machine (with manjaro). So it's apparently system specific. Can I provide any more useful information?

**Comment by f2404** [comment]
@jf99 Could you post the crash info? It can be found in `journalctl` if your system is using systemd.

**Comment by jf99** [comment]
```
systemd-coredump[4143]: Process 794 (nemo) of user 1000 dumped core.

Stack trace of thread 794:
#0  0x00007fd4eef488e0 n/a (libgtk-3.so.0)
#1  0x00007fd4eef16a4b n/a (libgtk-3.so.0)
#2  0x00007fd4eef1e0b0 gtk_tree_view_insert_column (libgtk-3.so.0)
#3  0x0000000000456a57 n/a (nemo)
#4  0x0000000000457c2a n/a (nemo)
#5  0x00007fd4ed350fa5 g_closure_invoke (libgobject-2.0.so.0)
#6  0x00007fd4ed362ff1 n/a (libgobject-2.0.so.0)
#7  0x00007fd4ed36bd8c g_signal_emit_valist (libgobject-2.0.so.0)
#8  0x00007fd4ed36c0bf g_signal_emit (libgobject-2.0.so.0)
#9  0x00007fd4eed1f1c1 n/a (libgtk-3.so.0)
#10 0x00007fd4ed350fa5 g_closure_invoke (libgobject-2.0.so.0)
#11 0x00007fd4ed362b2c n/a (libgobject-2.0.so.0)
#12 0x00007fd4ed36bd8c g_signal_emit_valist (libgobject-2.0.so.0)
#13 0x00007fd4ed36c0bf g_signal_emit (libgobject-2.0.so.0)
#14 0x00007fd4eef3c2be gtk_widget_activate (libgtk-3.so.0)
#15 0x00007fd4eee139d6 gtk_menu_shell_activate_item (libgtk-3.so.0)
#16 0x00007fd4eee13d04 n/a (libgtk-3.so.0)
#17 0x00007fd4eedf723a n/a (libgtk-3.so.0)
#18 0x00007fd4ed3511d4 n/a (libgobject-2.0.so.0)
#19 0x00007fd4ed36b4e8 g_signal_emit_valist (libgobject-2.0.so.0)
#20 0x00007fd4ed36c0bf g_signal_emit (libgobject-2.0.so.0)
#21 0x00007fd4eef39ecc n/a (libgtk-3.so.0)
#22 0x00007fd4eedf44be n/a (libgtk-3.so.0)
#23 0x00007fd4eedf634c gtk_main_do_event (libgtk-3.so.0)
#24 0x00007fd4ee92e625 n/a (libgdk-3.so.0)
#25 0x00007fd4ee95b492 n/a (libgdk-3.so.0)
#26 0x00007fd4ed07af07 g_main_context_dispatch (libglib-2.0.so.0)
#27 0x00007fd4ed07b160 n/a (libglib-2.0.so.0)
#28 0x00007fd4ed07b20c g_main_context_iteration (libglib-2.0.so.0)
#29 0x00007fd4ed640afd g_application_run (libgio-2.0.so.0)
#30 0x0000000000430576 n/a (nemo)
#31 0x00007fd4ec210710 __libc_start_main (libc.so.6)
#32 0x00000000004305d9 n/a (nemo)

Stack trace of thread 4136:
#0  0x00007fd4ec2d37f9 syscall (libc.so.6)
#1  0x00007fd4ed0bfafa g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fd4ed04f929 n/a (libglib-2.0.so.0)
#3  0x00007fd4ed04ff4b g_async_queue_timeout_pop (libglib-2.0.so.0)
#4  0x00007fd4ed0a23ca n/a (libglib-2.0.so.0)
#5  0x00007fd4ed0a1975 n/a (libglib-2.0.so.0)
#6  0x00007fd4ec598424 start_thread (libpthread.so.0)
```

**Comment by f2404** [comment]
This looks similar to #1156 
Could you check if my patch referenced there resolves the issue for you?

**Comment by jf99** [comment]
I'm sorry to say, that I can't. I really need this computer to run stable and cannot install any experimental software. Also, I don't know how to apply patches. So I will have to wait until the next version tick of nemo rolls out.

However, I can tell you that I cannot reproduce the bug #1156 with going back from the trash.

**Comment by f2404** [comment]
That's a shame... Anyway, your crash is happening in the same gtk_tree_view_insert_column() function as mine, so I think it's a good chance that the patch will also fix this one.

**Comment by f2404** [comment]
Can you try it in 3.0.1?

**Comment by jf99** [comment]
I'm going to try it as soon as possible. Just waiting for Arch's package maintainer.
https://www.archlinux.org/packages/community/x86_64/nemo/

**Comment by jf99** [comment]
Finally a new package! The crash does no longer happen with nemo 3.0.3. However, there's still something wrong with selecting and unselecting columns. I made a video for you.
[nemo-bug.zip](https://github.com/linuxmint/nemo/files/287676/nemo-bug.zip)

**Comment by f2404** [comment]
> Finally a new package! The crash does no longer happen with nemo 3.0.3.
Glad to hear this!

> However, there's still something wrong with selecting and unselecting columns. I made a video for you.
Thanks for the video. Yep, there's definitely something wrong.
Could you open another issue for that and close this one?

**Comment by jf99** [comment]
New issue #1190.
