### ISSUE TITLE
No white background in some view mode on nemo

### ISSUE THREAD

**Issue by pierre-guillot** [linuxmint/nemo#1150]
Hello,
I recently update my archlinux, now Cinnamon's version is : 

- Cinnamon 2.8.8
- Kernel 4.1.21-1-lts
-  gtk2 2.24.30-1
- gtk3 3.20.3-1

But, some view modes aren't background color, principal problem is when you want to rename a file, you don't see the cursor (each time, before the screenshot, i select file "RECEUIL.odt and type on F2) : 

https://framapic.org/Il1Q7BT7ynNa/PJNWho1SEYCa.png

https://framapic.org/W8ZZYp5OjO2Y/r2C41Y9RYTT8.png

**Comment by mxmlnkn** [comment]
Note also that in the left panel for some reason after updating part of the bottom is also gray while the rest is white. This is unsightly.

**Comment by JosephMcc** [comment]
Gtk3.20 brought significant changes to theming. Style classes have been added to git master at the request of some theme authors. Wait for these changes to make it to your distro. Also make sure you use a theme that properly supports 3.20. That partial gray area in the nemo sidebar is from changes to  gtk scrolled windows that it doesn't look like the theme you are using properly supports.

**Comment by dglava** [comment]
I am getting those annoying invisible/transparent text boxes during renaming with the default Adwaita theme too. Only the "List View" has a visible background during renaming. Renaming files in the "Icon" and "Compact" views feels pretty awkward because of this.

![](http://s32.postimg.org/j6qm0xdr9/2016_05_01_15_40_34.png)

**Comment by mxmlnkn** [comment]
I still have this problem and I noticed that the background becomes white when I open another tab, i.e. when I have more than one tab open in one nemo window!

**Comment by pierre-guillot** [comment]
Just test on my Archlinux with latest updates, install zuki-themes-git via yaourt, apply theme and it work with it.

**Comment by mxmlnkn** [comment]
@pierre-guillot
Debian doesn't have zuki, but I was using Clearlooks and found

    clearlooks-phenix-theme - GTK3 port of Clearlooks theme

With that it still does not work, it looks even worse, but i guess that really not nemo's fault. Although I still find it weird, that the background style changes when opening a new tab.

**Comment by dglava** [comment]
It works with the Zuki themes, because they apply a custom fix for it. The Arc theme does too if I remember correctly. The default GTK3 theme (Adwaita), and probably every other theme without the custom fix won't work, i.e.: it will have the awkward transparent renaming background.
