### ISSUE TITLE
Nemo theming is broken on GTK 3.20

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/nemo#1151]
When one enters F2 to edit the file name, it's barely visible that anything has changed. No selection can be seen.

**Comment by JosephMcc** [comment]
New style classes have been added to nemo at the request of some theme authors. Also make sure you are using a theme that properly supports 3.20.

**Comment by marmistrz** [comment]
I'm using zukitre gtk3.20 theme on Nemo 2.8.7 on Arch.

**Comment by marmistrz** [comment]
Still not working with Nemo 3.0.0, any of the themes Adwaita, Zukitre, Vertex.

**Comment by marmistrz** [comment]
Nemo 3.0.5 - the problem persists, even with the Adwaita theme, which is surely gtk3 compatible.
Using gtk3 3.20.6-1, under Arch Linux.f

Maybe the Mint gtk3 patches are an issue here.
