### ISSUE TITLE
[SOLVED]Nemo doesnt remember bookmark

### ISSUE THREAD

**Issue by azzamsa** [linuxmint/nemo#1152]
i have installed Nemo file manager from repo ( nemo 2.2.4 ), on My Machine Debian 8.0.0 and im using KDE 4.14.2, -- my nemo doesnt remember the Bookmark. -- i have tried installing nemo from repo,from ubuntu patches ( webupd) but no luck,when closing nemo,all the bookmarks lost.

-- sometimes it solved by installing nautilus too, but it does not guarantee nemo will always remember the bookmark.

**Comment by azzamsa** [comment]
it solved by upgrading to nemo 2.8 , i have not found any error around 2 days.

i will update this when i got any errors.

**Comment by azzamsa** [comment]
i did not get any error in Bookmark on Nemo 2.8.
thanks

**Comment by f2404** [comment]
Could you please close the issue?
