### ISSUE TITLE
Allocating size to GtkButton without calling  gtk_widget_get_preferred_width/height()

### ISSUE THREAD

**Issue by mxmlnkn** [linuxmint/nemo#1153]
After updating to nemo 2.8.7. I get the following error in my .xsession-errors

    (nemo:16703): Gtk-WARNING **: Allocating size to GtkButton 0xf7cdb0 without calling 
    gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

When the window is inactive no errors appear, but every time I click on the window or do any other action like changing the folder 8kB of errors are produced. In a normal workflow .xsession-errors increases to megabytes  fast.

**Comment by xzorg6** [comment]
I have a similar problem, since nemo 2.8.7 or maybe the gtk 3.20 update.
It's still reproducible in nemo 3.0.0

Just by browsing into 1 folder you can see 50 lines of this :
> $ nemo
> (nemo:5778): Gtk-WARNING **: Allocating size to GtkGrid 0x7fe50c014440 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
> ...
> (nemo:5778): Gtk-WARNING **: Allocating size to GtkGrid 0x7fe50c014440 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

Archlinux / 64bits / Cinnamon 3.0.1 / Nemo 3.0.0 / gtk3 3.20.3

**Comment by itzexor** [comment]
I have been trying to track this down without progress since 3.20 was released. I finally just recompiled gtk3 without debug support so i can read the logs again. Not really a solution, but I can't figure it out...

**Comment by itzexor** [comment]
I have made some progress on quieting these warnings. This patch will stop the bulk of the spam, the GtkGrid warnings, but won't resolve all of them. 

https://github.com/itzexor/nemo/commit/2c60a3edaef10e9ef331740d55d3c45dd366c5db

**Comment by itzexor** [comment]
This GTK commit silences the NemoWindowPane warnings https://github.com/GNOME/gtk/commit/ddcf47026dbbe58dca3b34c7bb1ec63bb50a861a

I'm not sure if that's going to hit 3.20 but if it's fixed upstream I'm leaving that one alone.

**Comment by itzexor** [comment]
@mxmlnkn Found the patch needed for the GtkButton warnings and it's included as well, thanks for the report btw as I wasn't looking for those ones initially.

**Comment by mesutevin** [comment]
I have same problem.

![nemo-problem](https://cloud.githubusercontent.com/assets/5961149/16483019/2a718c6e-3ebb-11e6-80ec-94ba5df70cb7.png)

How can I fix it ?

**Comment by rambhavan** [comment]
terminator:3979): Gtk-WARNING **: Allocating size to GtkVScrollbar 0x559a73d963e0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
