### ISSUE TITLE
Desktop-item delete-confirmation dialog on wrong monitor

### ISSUE THREAD

**Issue by autarkper** [linuxmint/nemo#116]
If you have multiple monitors, the confirmation dialog that pops up when you want to delete a desktop item is apparently centered relative to the entire screen, making it end up on the wrong monitor in some configurations.

How to reproduce:
0) Set up a dual-monitor configuration.
1) Create a disposable item on your desktop.
2) Select the item and press Shift+Delete.

Current behavior: the confirmation dialog pops in the center of the virtual desktop.
Desired behavior: the confirmation dialog should pop up in the center of your primary monitor (or possibly, the monitor containing the mouse pointer).

**Comment by JosephMcc** [comment]
Closing this since it seems to work as expected in Nemo 2.8, centering the dialog on the proper monitor.
