### ISSUE TITLE
Location button looks weird

### ISSUE THREAD

**Issue by f2404** [linuxmint/nemo#1162]
The last location button looks weird after switching from text location mode (nemo was started in text mode, then Toggle Location Entry button pressed): http://imgur.com/78TVRBU

UP: The switch is accompanied by the following error:
`Gtk-CRITICAL **: gtk_widget_draw: assertion '!widget->priv->alloc_needed' failed`.

**Comment by JosephMcc** [comment]
Are you using Adwaita? It has never handled Nemo very well.

**Comment by f2404** [comment]
Yes, I am. But the button look fixes after changing directory or even window focus, so I'm thinking there could be something in Nemo...

**Comment by JosephMcc** [comment]
You don't say what version of Gtk you are using. There is an issue in newer gtk versions with how this updates due to the way the arrows are appended to either end of the pathbar. There is a pending PR to address the issue here: https://github.com/linuxmint/nemo/pull/1157

**Comment by f2404** [comment]
Yep, sorry, forgot about that.
I'm running Arch Linux, gtk3 3.20.3, nemo 3.0.0.

**Comment by f2404** [comment]
Yes, the button looks better with the arrow that the patch adds.

**Comment by f2404** [comment]
Fixed by #1157
