### ISSUE TITLE
Sidebar doesn't have the preferred width in dual-pane view

### ISSUE THREAD

**Issue by whiteywhiteman** [linuxmint/nemo#1164]
After updating to nemo 3.0.0 the sidebar doesn't take the preferred width in dual-pane view.
Instead the minimum width is set on every start-up.

According to dconf-editor, "org.nemo.window-state.sidebar-width" updates correctly on resizing,
but after restarting nemo the width is set to minimum. This problem does only occur if "Always start in dual-pane view" is checked in the preferences.

**Comment by f2404** [comment]
It only happens if the window size is not big enough. If you enlarge Nemo window horizontally and broaden the sidebar afterwards, it will keep its width on the next start-up.
I'm not sure if this is a bug or rather a desirable behavior.

**Comment by mtwebster** [comment]
I think this is related to the behavior where if you resize the window narrow enough, it begins shrinking the sidebar of its own volition to maintain space for the directory view.  I mean to have it maintain the sidebar width regardless of resizing - this may also get fixed as a result.

**Comment by whiteywhiteman** [comment]
When the problem occurred, nemo ran in maximized mode on a 1600x900 screen. So I think there was enough horizontal space, even in dual-pane view.
I fixed it by shrinking the window to about 1300x400, then I enlarged the sidebar and on the next start-up the problem was gone. So from now on it works in maximized mode, too.

I guess that the update to 3.0.0 was the reason for this behavior.

**Comment by qoheniac** [comment]
This odd behaviour still exists in version 3.4.4 and your workaround still does it. Thanks for sharing!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
