### ISSUE TITLE
Ability to place sidebar on the right

### ISSUE THREAD

**Issue by gadlol** [linuxmint/nemo#1165]
Wouldn't be great - useful if we could place sidebar on the right?

http://askubuntu.com/questions/754229/how-can-i-place-the-nautilus-nemo-sidebar-to-the-right

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
