### ISSUE TITLE
Preference tabs lost on resize

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo#1166]
Resizing the preferences window to make it smaller than the tab width hides the whole tab area. This is especially problematic if the user has a larger font size and the tabs appear hidden upon opening the preferences window.

[Video example](http://webmshare.com/0EXgj)

Would it be possible to add arrows like in [pavucontrol](http://s32.postimg.org/7l2syj0ut/2016_04_30_17_37_08.png)? If not, maybe set a minimum size for the window and prevent if from being resized below a certain point?

Nemo version: 3.0.0
GTK3 version: 3.20.3

**Comment by f2404** [comment]
@dglava Could you try the patch? It sets the minimum size for the window.

**Comment by dglava** [comment]
Thanks! I tried it and it works.

However, there's still a tiny problem: [Example](http://s1.webmshare.com/dLaRb.webm). I assume it's happening because the text in the tabs is longer?

The initial window size isn't large enough to display the tabs. The minimum size setting is still respected, but it's not large enough to display the tabs. This is affecting the Bosnian localization for Nemo, but not the English one (possibly affecting other localizations too).

**Comment by f2404** [comment]
I have slightly increased the default width - please check if it's fine now.

**Comment by dglava** [comment]
Everything is working properly now. Thank you for fixing this.
