### ISSUE TITLE
Select all files in a folder with a left  mouse click in 'List View'

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/nemo#1168]
I like to have Nemo (Nemo 2.8.7, Mint Cinnamon 17.3) in List View to see how big my files are and when they were last time accessed. However, it isn't possible to select more files with left mouse click like it is possible in Icon View and Compact View. I know about ctrl + click.

Wouldn't this be a nice feature to have?

**Comment by f2404** [comment]
How are you doing this in Icon View or Compact View? For me, left click just moves the selection.

**Comment by hrvoojex** [comment]
Sorry I am bad at english but I will try to explain. In icon view you make left click, you hold the left click button and select all the files you want. Than you release the left button. This is not possible in list view.

**Comment by f2404** [comment]
Ah, you mean the drag-select functionality. Yes, it's not supported by List View.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/416
