### ISSUE TITLE
Moving file resets clipboard

### ISSUE THREAD

**Issue by mxmlnkn** [linuxmint/nemo#1171]
How to reproduce:
1. Create a folder with one subdirecotry `a/` and two files `b` and `c`
2. Select `b` and press Ctrl+X (cut)
3. Go into `a/` and press Ctrl+V (paste) -> everything works, roll back to step 2
4. Move (LMB+hold+drage&drop) `c` into `a/`
5. Now go into `a/` and press Ctrl+V
   
   What happens:
    nothing
   
   What should have happened:
   `b` should have been pasted into `a/`

Btw: It is really hard to see which files are actually cut out, but I guess this could be related to #1150

**Comment by xenopeek** [comment]
You're assuming Ctrl+X in your file manager works like in your text editor. Ctrl+X marks a file to be moved to another location. Ctrl+V completes the move. Pressing Ctrl+V again afterward in another directory doesn't move the file again as it is no longer at the original location.

So this is unrelated to your steps 4 and 5.

**Comment by mxmlnkn** [comment]
The file `b` is still in the original location. The only file which was moved since cutting `b` is `c`.

**Comment by xenopeek** [comment]
Right, then I misunderstood your step 3. With "roll back to step 2" you meant "move b back to the original directory and select to cut it again with Ctrl+X".

Nautilus and Caja all behave the same way as Nemo with your test. Dolphin and Thunar do what you want in the test. So it looks deliberate how it works. Thus this should probably be tagged as a feature request.

**Comment by mxmlnkn** [comment]
Interesting, I could only test Nemo and Thunar and Windows Explorer which I used for years so that may be the reason why I thought this to be a bug. But feature request is fine by me, too. I can't tag/label though.

**Comment by mxmlnkn** [comment]
![nemo-selection](https://cloud.githubusercontent.com/assets/6842824/20640274/82fb3bda-b3d9-11e6-8978-0fcd5d16bfd6.gif)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
