### ISSUE TITLE
Cut & Paste files from the trash should actually paste the file in the correct directory

### ISSUE THREAD

**Issue by CreamyCookie** [linuxmint/nemo#1175]
I wanted to cut and paste some files from the trash into another folder. Sadly, the filed were not pasted in the folder I had opened but were instead restored to their original location.

**Comment by xenopeek** [comment]
Same on Nemo 3.0.6. Whether you cut or copy a file from the trash directory, when you paste it in another directory the file is instead moved or copied from trash to to the directory it was originally deleted from.

All other file managers I tried do handle it as @CreamyCookie expects, pasting the file to the current directory.

**Comment by lzkill** [comment]
I confirm this behavior on Mint 18 with Cinamon.

**Comment by leigh123linux** [comment]
This is the expected behaviour for gvfs-trash
