### ISSUE TITLE
Icons disappear since v3.0.0

### ISSUE THREAD

**Issue by X0rg** [linuxmint/nemo#1177]
Hi,

Since v3.0.0 and still in v3.0.1, desktop icons disappear when I do some actions, like opening a new Nemo window. They reappear immediately, it blinks. I don't have this bug in 2.8.7.
I use GTK 3.20.4 on Arch Linux x86_64.

Nemo is started from .xinitrc with the following command:
```nemo --no-default-window &> /tmp/nemo.log &```
The file nemo.log is full of lines like them:
```Allocating size to GtkXXXX 0xXXXXXXX without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?```

How I can investigate on this bug?

**Comment by f2404** [comment]
What is your system? I don't observe this on mine: Arch Linux, Cinnamon 3.0.1.
The `Allocating size` warnings are not relevant - they always appear when starting Nemo. Is there anything interesting in `~/.xsession-errors`?

**Comment by X0rg** [comment]
I use Budgie Desktop on my Arch Linux, not sure if it is related.
I don't have a `~/.xsession-errors` file.

**Comment by f2404** [comment]
The symptoms look like as if the desktop was restarted on each Nemo start. This could be Budgie Desktop's issue - could you maybe try it with other file manager(s) that can handle desktop?

**Comment by X0rg** [comment]
It could be a bug with budgie-helper. It's a fork of gnome-flashback 3.18.1.
I'll try to rebase budgie-helper 3.20.0.

**Comment by X0rg** [comment]
I don't have this issue with Nautilus.
In fact, I have removed budgie-helper because when I use it, desktop icons disappear all time and Conky too.
With a patched budgie-helper (rebased on GNOME-Flashback 3.20), it doesn't solve this issue.

**Comment by X0rg** [comment]
I have rebuilt Nemo with debug symbols. I run `nemo -n` from GDB.
This is what I can see when icons disappear and reappear:
```
(nemo:14921): Gtk-WARNING **: Allocating size to GtkGrid 0x1422130 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[New Thread 0x7fffc37fe700 (LWP 16054)]
[New Thread 0x7fffd9456700 (LWP 16055)]
[New Thread 0x7fffdaafd700 (LWP 16056)]
[New Thread 0x7fffd8c55700 (LWP 16057)]
[New Thread 0x7fffc3fff700 (LWP 16058)]

(nemo:14921): Gtk-WARNING **: Allocating size to GtkGrid 0x1422130 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[Thread 0x7fffd9456700 (LWP 16055) exited]
[Thread 0x7fffc3fff700 (LWP 16058) exited]
[Thread 0x7fffc37fe700 (LWP 16054) exited]
[Thread 0x7fffc2ffd700 (LWP 16045) exited]
[Thread 0x7fffdb5fc700 (LWP 15970) exited]
[Thread 0x7fffdaafd700 (LWP 16056) exited]
```

**Comment by norbusan** [comment]
I see the same on Debian/unstable with nemo 3.0.1.

Furthermore, I believe that it only happens when I start/stop gtk apps. Starting or stopping a purely qt app does not make nemo flash.

**Comment by lukefromdc** [comment]
For desktop icons to blink out an come back means the file manager (nemo) is crashing or exiting and restarting.

**Comment by JosephMcc** [comment]
@lukefromdc The desktop icons will disappear when Nemo crashes but at least for me Nemo doesn't autorestart itself.

Since the nemo desktop window respects your panel struts for placing icons my guess would be something is making it recalculate this. You will see the same thing happening for example when you  add or remove a panel.

**Comment by norbusan** [comment]
On Debian/Sid this is getting seriously annoying. Most of the times nemo does restart, but eg when opening a pdf with evince via click then nemo crashes reproducibly every time.

Thanks

**Comment by lukefromdc** [comment]
You are right: I'm used to working with Caja, which still supports auto-restart
from a session startup file in /usr/share/applications. Nautilus changed that 
before Nemo was forked off so that part of startup is different.

**Comment by X0rg** [comment]
My bisecting log:
```
git bisect start
# bad: [e32b76962fdcf91ff2a4ee45547feae791f2abd5] 3.0.0
git bisect bad e32b76962fdcf91ff2a4ee45547feae791f2abd5
# good: [f1dfc689914b1e6caf62301b1dd9a12460a2b7a9] 2.8.7
git bisect good f1dfc689914b1e6caf62301b1dd9a12460a2b7a9
# good: [f1dfc689914b1e6caf62301b1dd9a12460a2b7a9] 2.8.7
git bisect good f1dfc689914b1e6caf62301b1dd9a12460a2b7a9
# good: [fb21adbdf825e7087301d246d478faa4484205ed] 2.8.6
git bisect good fb21adbdf825e7087301d246d478faa4484205ed
# good: [fb21adbdf825e7087301d246d478faa4484205ed] 2.8.6
git bisect good fb21adbdf825e7087301d246d478faa4484205ed
# bad: [6dfa9ec77819e7e1359f590ba817d64ef0551764] Merge branch 'master' of github.com:ChrisJAllan/nemo
git bisect bad 6dfa9ec77819e7e1359f590ba817d64ef0551764
# bad: [58cd4d52154ca93bf6f980c49455e64a3149722c] file-utils: ensure directories exist before restoring from trash https://git.gnome.org/browse/nautilus/commit/?id=f1cb32831df32009f7e8bd5fcc35c5ccdf64eee4
git bisect bad 58cd4d52154ca93bf6f980c49455e64a3149722c
# bad: [e286f3a2da0d0e8a684a0f452da1f65153c2c948] nemo-list-view.c: Always keep the name column visible
git bisect bad e286f3a2da0d0e8a684a0f452da1f65153c2c948
# bad: [b2b154a10d12c214bdb35febb4ac6f4c90d7d135] nemo-desktop-manager: Allow non-x-primary monitors to be primary for purposes of layout fallback and handling orphaned desktop icons.
git bisect bad b2b154a10d12c214bdb35febb4ac6f4c90d7d135
# good: [b8ad53de270c2f44d9927b723f32a87aa813adf1] Merge pull request #1059 from linuxmint/monsta-patch-1
git bisect good b8ad53de270c2f44d9927b723f32a87aa813adf1
# bad: [408519133f3432281688dd8d36355e9cbe186ba6] desktop: Overflow items from inactive monitors to the primary monitor. The original position (on the inactive monitor) is maintained in the metadata.  If the monitor is re-activated, the icons return to their original position.  If an 'orphaned' icon is dragged to some new position and/or monitor, that new position becomes its permanent one.
git bisect bad 408519133f3432281688dd8d36355e9cbe186ba6
# bad: [dc0e0cf2089df9752669eca9aa5cd52c1d705cbc] desktop:  add independent physical monitor handling
git bisect bad dc0e0cf2089df9752669eca9aa5cd52c1d705cbc
# first bad commit: [dc0e0cf2089df9752669eca9aa5cd52c1d705cbc] desktop:  add independent physical monitor handling
```
This bug appears with dc0e0cf.

How to debug that?

**Comment by dezldog** [comment]
I have this problem too with Mint 18. An additional this I can add is that nemo on crashes on the opening of the first folder when none other are open. It reduces the irritation to just always keep a window open and minimized. Starting applications and some other operations will still cause a crash....

**Comment by lukefromdc** [comment]
It was also thaat same independant monitor commit or one related to it that created the partial desktop issue on Compiz when two different size monitors are hooked up.

**Comment by norbusan** [comment]
In my case nemo does not crash when the Icons flicker. I checked that nemo uses the same PID before and after the dis/re-appearance of the icons. So it seems to be something else but a crashing nemo, maybe the above mentioned commit.

**Comment by dezldog** [comment]
So, I just checked the PID and mine is not changing either. I'm a little embarrassed I didn't check that before I posted... :-\

It seems to me that is is possibly still a Nemo bug; just one around refreshes. I have _no_ idea how to check for that or even describe it in a useful way to check against other bugs... any suggestions anyone?

**Comment by mtwebster** [comment]
The desktop will re-layout if things change like the desktop size or number of monitors - this will be the 'blink' that's seen - the icons and view are destroyed and re-created.  However, the times when this happen are very limited (or should be at least) - do any of you use auto-hiding panels or something like that?

**Comment by norbusan** [comment]
Hi
no, I don't have any auto-hide feature running.
Can you tell me which is the function that triggers this, and I can gdb/breakpoint there and see what is going on.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/blob/master/src/nemo-desktop-manager.c#L83

If you look through that file, a lot of triggers can call that function, from settings changing to the workarea changing (which happens if you add a panel or modify the size of one)

**Comment by JosephMcc** [comment]
A couple more things that can trigger workarea changes are changing themes or in some cases just changing settings in the panel settings. Essentially anything that affects the size of the panel. This could likely also happen in some cases when using a dock.

**Comment by norbusan** [comment]
Ok, what I see is that al the updates are triggered by the call to `layout_changed(manager)` in `gdk_filter_func`, but no other. The code there is
`````
    switch (xevent->type) {
        case PropertyNotify:
            if (xevent->xproperty.atom == gdk_x11_get_xatom_by_name ("_NET_WORKAREA"))
                layout_changed (manager);
            break;
`````
Does this help you?

**Comment by X0rg** [comment]
> The desktop will re-layout if things change like the desktop size or number of monitors - this will be the 'blink' that's seen
In my case, I use only one monitor, always in 1080p.
For example, when Nemo manage desktop, clicking on Home icon do a "blink".

**Comment by norbusan** [comment]
Comparing the code in nautilus and nemo, I see that the update is called at the same time, but that the actual update function does not recreate all windows on the nautilus side, but only adjust the margin:
`net_workarea_changed` calls `canvas_container_set_workarea` calls `nautilus_canvas_container_set_margins` (only).

Nemo OTOH destroys the toplevel window unconditionally and rebuilds it.

**Comment by dezldog** [comment]
ok, so in my case I was using AWN dock. I had been using it for a while with no problems, and sadly I didn't notice what update caused the problems. Discontinuing the use of AWN made the issue go away. I'm going to noodle around a bit on the AWN log and see if there is some awareness of this issue there. :)

**Comment by mtwebster** [comment]
There probably is nothing wrong with AWN dock - when I reworked desktops I didn't anticipate this many things triggering the reset - it's possible they're happening quickly enough in succession that it's causing the issues (and eventual crash, possibly) - the catch-all relayout function was honestly meant to be temporary until I worked out some more specific reactions to changes (like possibly just resizing and not re-doing the entire desktop each time), but I didn't have any issues personally so never had impetus to change it.

I'll try out some dock programs and see what can be done.

**Comment by X0rg** [comment]
I'm using Cairo Dock (if this information can help you).

**Comment by mtwebster** [comment]
@X0rg I have Cairo setup but I can't seem to trigger this - would you mind sharing your Configuration->behavior settings (and anything else you might think relevant, I'm not familiar with it) - also, have you noted any sure-fire steps to reproduce this?  Thanks

**Comment by mtwebster** [comment]
Never mind ;)

**Comment by norbusan** [comment]
"never mind" ? Does that mean you can finally reproduce it?

**Comment by mtwebster** [comment]
Yes, working on a fix now

**Comment by norbusan** [comment]
Great! If you need tests let me know your git branch and I pull from there.

**Comment by X0rg** [comment]
I'm available to test, me too. ;)

**Comment by mtwebster** [comment]
This is pushed to master, if you guys want to try it out.  This should take care of the problem.  The only issue there may be is if someone uses a dock on a non-primary monitor, it won't 'see' it to compensate for it, though there will always be a constant 50px buffer all around, so hopefully this compromise is acceptable.

**Comment by lukefromdc** [comment]
This also fixed the desktop size issue in compiz, no more need to patch it
for my purposes.

**Comment by norbusan** [comment]
Fix confirmed, thanks a lot!

**Comment by leigh123linux** [comment]
@mtwebster Your commit breaks a lot of things here.

using gtk-3.22, issues are

1. when using hidpi the icons go beneath the panel
2. switching from hidpi to normal and visa versa causes icon corruption
3. switching from hidpi to normal and visa versa the icons don't resize properly and the text is mis-placed

**Comment by norbusan** [comment]
Umpf, good that gtk-3.22 is the last one, they are changing everything with every minor release :-(

**Comment by leigh123linux** [comment]
@norbusan I just tested with gtk-3.20 and it's even more broken than gtk-3.22 (previous post updated).

**Comment by norbusan** [comment]
Ok, so it is a hidpi issue. Are all these bugs introduced by the latest change, or are they also present in stock 3.0.6?

**Comment by leigh123linux** [comment]
@norbusan it's https://github.com/linuxmint/nemo/commit/c5a513468ee8c3497f0673e3ca019ccd3f409f8b that has broken it

**Comment by X0rg** [comment]
It seems to appear with Cairo Dock when it reserves space for Dock, not when keeping below windows.

I'm using GTK 3.22, and I can confirm this issue is solved for me with the Git version. Thank for your fix.
