### ISSUE TITLE
First pane in dual-pane view has minimum size

### ISSUE THREAD

**Issue by tflori** [linuxmint/nemo#1180]
I have a UHD-Display and I want to start nemo every time very big with two panes in list view and the columns should not be equal.

For me it looks like a bug that the width of columns and the width of the first pane is set to minimum or equality every time when I start nemo.

This is what I get every time when I start (since 3.0 the two panes are not equal on start).
![bildschirmfoto von 2016-05-19 10-44-08](https://cloud.githubusercontent.com/assets/4855611/15387682/abd38380-1dae-11e6-8b41-c7a568666b80.png)

This is what I want and have to make manually every time:
![bildschirmfoto von 2016-05-19 10-46-32](https://cloud.githubusercontent.com/assets/4855611/15387751/fb528cee-1dae-11e6-87b4-421ad8e13673.png)

**Comment by xenopeek** [comment]
What Linux distribution are you on and have you retested this with Nemo 3.0.6 or newer? I can't reproduce it on Linux Mint 18 with Nemo 3.0.6 but I don't have a HiDPI monitor.

**Comment by tflori** [comment]
I'm using Manjaro Linux. I have the latest updates. Gnome Shell version 3.20.3 and Nemo version 3.0.6... I just reproduced it (so it still exists). Currently my "workaround" is not to start automatically in 2 column mode and hit f3 after start (then the columns have equal width)...

**Comment by calis2002** [comment]
Any updates on this? I'm on Manjaro 17.0 (Cinnamon) with Nemo 3.2.2 and this is really annoying ;(
Or anything i can do to help on getting this fixed?

**Comment by DerEnderKeks** [comment]
Same problem here on Fedora 25 with Nemo 3.2.2. 
![Screenshot](https://cloud.githubusercontent.com/assets/12559640/25052189/d6e18e5e-2150-11e7-911e-0ca45e827abf.png)

**Comment by tflori** [comment]
@xenopeek I can confirm this is still an issue. I updated to Gnome Shell 3.22.3 and Nemo 3.2.2 and the problem remains the same. Do you plan to fix this issue?

**Comment by sks4903440** [comment]
Is there any way to specify the default ratio of the two panes?

**Comment by calis2002** [comment]
Come on guys. Version 3.6.4 and still not fixed?

**Comment by jaszhix** [comment]
To fix this issue, run this command in a terminal:

```
gsettings reset org.nemo.window-state geometry
```

**Comment by calis2002** [comment]
That fixes the issue for one time. But if you resize the window, then restart nemo you have the same issue again.

**Comment by tflori** [comment]
this is just working because both panes have the minimal width then.. are you able to reproduce this problem, or are you just guessing what might be the problem?

if you are just guessing: how can we help you to find the issue?

**Comment by jaszhix** [comment]
I opened a PR that fixes it.
