### ISSUE TITLE
Crash when switching directories from one with a custom icon visible.

### ISSUE THREAD

**Issue by jplatte** [linuxmint/nemo#1186]
Basically nemo always crashes when I try to go anywhere from my home directory because I have [MEGAsync](https://github.com/meganz/MEGAsync) installed and it sets a custom icon for its directory. If I remove `~/.local/share/gvfs-metadata/home`, this doesn't happen anymore, but MEGAsync seems to check its icon is in place whenever it is shut down, and I really don't want to clear out the metadata every boot. I checked with `gvfs-info` what MEGAsync actually did to the directory, and it seems to be only the following additional metadata:

```
  metadata::custom-icon: file:///usr/share/icons/hicolor/256x256/apps/mega.png
  metadata::nautilus-list-view-sort-column: name
  metadata::nautilus-list-view-sort-reversed: false
  metadata::nemo-list-view-sort-column: name
  metadata::nemo-list-view-sort-reversed: false
```

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stack trace for the crash.

**Comment by jplatte** [comment]
I no longer use MEGAsync or Nemo.
