### ISSUE TITLE
Change nemo tabs width and height

### ISSUE THREAD

**Issue by RaitaroH** [linuxmint/nemo#1187]
It would be nice if you could make the tabs in nemo smaller, even when you have only 2 or 3, instead of them resizing and filling all the available space. Similar tab behaviour to what you can see in a browser for example, the tabs stay at their size, if you have to many you can scroll through them.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
