### ISSUE TITLE
Ctrl + mouse click selects files but does not set focus to Nemo window

### ISSUE THREAD

**Issue by f2404** [linuxmint/nemo#1191]
If another window is active, Ctrl+clicking files in Nemo will select them but won't change the focus. This can be very confusing.

Shift+click, however, will do nothing unless Nemo window is selected.

Arch Linux, Cinnamon 3.0.4, Nemo 3.0.3.

**Comment by xenopeek** [comment]
This is unrelated to Nemo I believe and instead related to how Gtk+ handles this. When I open another Gtk+ program like Gedit and give focus to another program with a partially overlapping window, I can Ctrl+click/drag or Shift+click/drag inside the Gedit window without focus changing. This way I can select text for copying from the Gedit window for middle-click paste without changing focus.

**Comment by icarter09** [comment]
@xenopeek do you think this ticket should be closed?
