### ISSUE TITLE
All text files open up blank when connecting to remote share using sftp

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1194]
Don't know if this is a bug, a missing feature, or an oversight on my part, but whenever I try to open up text files in an sftp folder in nemo v3.0.3 they show up blank. I must manually drag them to a local directory first and then open them to see their contents. Pretty annoying when you are trying to edit many files remotely! Perhaps I need to mount them first?

Thanks.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
