### ISSUE TITLE
Add button to toggle split panel mode

### ISSUE THREAD

**Issue by sikejsudjek** [linuxmint/nemo#1196]
Just a suggestion to add the option of having a button that can toggle split panel mode in the nemo taskbar. I would find this very useful !

**Comment by anandrkris** [comment]
Related issue
https://github.com/linuxmint/nemo/issues/1296

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
