### ISSUE TITLE
Add to right click context menu for desktop to add shortcuts for files and urls

### ISSUE THREAD

**Issue by sikejsudjek** [linuxmint/nemo#1197]
Is it possible to add shortcuts in the right click context menu of the desktop area to add 'shortcut to file' and 'shortcut to url' ? I asked in the cinnamon section, but they said it was nemo that controlled this. 
The reason I ask is because the method for adding shortcuts via the app launcher is confusing for people moving from windows. Xfce by contrast has these options and is much, much easier to use than on Nemo with Cinnamon.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
