### ISSUE TITLE
arayüz güncellemeleri için tavsiye linuxmint 18 cinnamon

### ISSUE THREAD

**Issue by xspacexx** [linuxmint/nemo#1198]
![ekran goruntusu - 2016-06-11 11-12-04](https://cloud.githubusercontent.com/assets/19875592/15985979/d53d134e-3005-11e6-9598-903f51bdcc7b.jpg)

![ekran goruntuddsu - 2016-06-11 11-17-31](https://cloud.githubusercontent.com/assets/19875592/15985988/f3c1a118-3005-11e6-87e8-39d694f3252a.jpg)

arkadaşlar sürüm güncellemesi yerine artık her çıkan sürümde birazda arayüz güncellemesi ve kullanım kolaylıgı saglayın linux bu yüzden pek tercih edilmiyor yani biraz son kullanıcıya hitap edin benim beklediğim bi özellikti bunlar mesala ama denedim bi yine hala eski halinde duruyor lütfen rica ediyorum bu tür özellikler ekleyin

**Comment by xenopeek** [comment]
Biz Türkçe okuyamaz. Otomatik çeviri iyi bir iş yapmaz. Biz çeviri anlayamıyorum. yalnız Görüntüler yeterli değildir. İngilizce'de bu yazabilir misin? Ya da birisi sizin için çevirebilir? Belki birileri yardımcı olabilir https://forum.linuxmint.net.tr/ üzerinde.

We can't read Turkish. Automatic translation doesn't do a good job. We can't understand the translation. Images alone aren't enough. Could you write this in English? Or can someone translate it for you? Perhaps on https://forum.linuxmint.net.tr/ somebody can help.

**Comment by feren** [comment]
@xenopeek 
From all I can see, this is what I've noticed odd about it:
 - The Drives are in the home folder rather than the left-pane
 - The Drives have bigger icons than the folders
 - There's a trash icon on the bottom-right?
 - That's about all I can notice odd about his install

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
