### ISSUE TITLE
Add an option to disable Elevated privileges toolbar.

### ISSUE THREAD

**Issue by J08nY** [linuxmint/nemo#1200]
I work with Kali Linux(https://www.kali.org/) which uses root by default. I would thus far really appreciate if the omnipresent bar warning of elevated privileges could be turned off. I would gladly submit a PR if this is deemed doable.

**Comment by anandrkris** [comment]
One option is to have the Info bar shown with a Close button. (And if it can remember choice, should solve it). Or easier to have configuration under Edit > Preferences that can enable / disable this info bar.

You can search for show_root_bar in this 
https://github.com/linuxmint/nemo/blob/015db702c7234d6c2ceda8707045186480dcc62e/src/nemo-toolbar.c

Note: Am not a developer just a casual user.

**Comment by azdps** [comment]
I would like to see an option to turn off the elevated privileges warning as well.

**Comment by J08nY** [comment]
This should be solved by #1610 when it's merged.
