### ISSUE TITLE
Shift+Click to select does not work for filenames in Nemo 2.8.7

### ISSUE THREAD

**Issue by dmrauch** [linuxmint/nemo#1201]
Hi everybody,

I am running 17.3 Cinnamon Edition along with Nemo 2.8.7 and am wondering why it is not (as in never, i.e. this is no intermittent behaviour) possible for me to shift-click to select a substring of some filename (after hitting F2 or 'Rename...' on the file icon, of course). Having to use the arrow buttons or del/backspace to select/delete is a bit tedious for long filenames.

Is this the intended behaviour or is there something weird going on only for me? And it doesn't happen only for me, could this be changed so that the filename text entry behaves like any other text field?

Many thanks!
Daniel

**Comment by xenopeek** [comment]
Nautilus and Caja both also don't support shift+click to select text from cursor position to where you clicked. Thunar and Dolphin do support this.

This should be tagged as feature request.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
