### ISSUE TITLE
GtkStock deprecation related warnings

### ISSUE THREAD

**Issue by f2404** [linuxmint/nemo#1203]
There is a number of warnings related to deprecation of GtkStock shown, e.g.

``` c
nemo-open-with-main.c: In function ‘main’:
nemo-open-with-main.c:147:43: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
                                           GTK_STOCK_CANCEL,
                                           ^~~~~~~~~~~~~~~~
nemo-open-with-main.c:151:40: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
                                        GTK_STOCK_OK,
                                        ^~~~~~~~~~~~
```

I could take care of them (just did the same to xfce4-terminal) and just want to confirm that they have not been left on purpose. Are you interested?

**Comment by xenopeek** [comment]
GTK_STOCK_* is found in a lot more files:
- eel/eel-editable-label.c
- eel/eel-stock-dialogs.c
- libnemo-private/nemo-bookmark.c
- libnemo-private/nemo-clipboard.c
- libnemo-private/nemo-column-chooser.c
- libnemo-private/nemo-desktop-link-monitor.c
- libnemo-private/nemo-file-conflict-dialog.c
- libnemo-private/nemo-file-operations.c
- src/nemo-connect-server-dialog.c
- src/nemo-location-bar.c
- src/nemo-mime-actions.c
- src/nemo-open-with-main.c
- src/nemo-places-sidebar.c
- src/nemo-properties-window.c
- src/nemo-query-editor.c
- src/nemo-tree-sidebar.c
- src/nemo-view.c
- src/nemo-window-bookmarks.c
- src/nemo-window-manage-views.c
- src/nemo-window-menus.c
- src/nemo-window-pane.c
Possibly good to discuss this in person with the developers on IRC in the developer channel. See http://developer.linuxmint.com/contributing.html for how to make use of IRC effectively.

http://stackoverflow.com/a/36811163 shows alternatives to GTK_STOCK_*.

**Comment by JosephMcc** [comment]
Feel free to make PR's to fix these sorts of things. When replacing gtk_stock just watch that you aren't breaking any functionality and you aren't actually changing what icons are being used. This warning is in so many places in Nemo you might want to break it into some sort of organized multiple PR's instead of doing a ton of them in one giant one if you can. That way if it does have some negative side effect it is easier to pinpoint where it happened.

**Comment by JosephMcc** [comment]
I'm closing this. These deprecations are all over in nemo. PR's are welcome to clean them up.
