### ISSUE TITLE
Starting nemo takes long sometimes

### ISSUE THREAD

**Issue by Piiit** [linuxmint/nemo#1204]
Sometimes, when I try to start nemo, it hangs for a long time showing the output below in console. For some minutes I cannot start any other instance of nemo, nor react with the GUI of it. After 3 minutes everything goes back to normal... 

Nemo 2.8.7
Mint Cinnamon 17.3

```
$ nemo
Initializing folder-color-switcher extension...
Initializing nemo-dropbox 2.8.0

** (nemo:7017): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed

** (nemo:7017): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed

(nemo:7017): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed

(nemo:7017): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed

(nemo:7017): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed

(nemo:7017): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed

(nemo:7017): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed

(nemo:7017): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed

** (nemo:7017): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed

** (nemo:7017): CRITICAL **: nemo_menu_provider_get_background_items: assertion 'NEMO_IS_MENU_PROVIDER (provider)' failed
```

**Comment by f2404** [comment]
Could this extension be the reason: `Initializing nemo-dropbox 2.8.0`? Can you try nemo without it?

**Comment by Piiit** [comment]
I tried it already, it makes (currently) no difference... It happens sometimes, haven't understood the pattern yet. I cannot retry it now, because nemo behaves normally... with and without extensions.

ps. @f2404 hi, is there an easy way to start nemo without extensions from commandline?

**Comment by Piiit** [comment]
The difference that I noticed is that now it starts without GLib-GIO-CRITICAL error messages.

**Comment by f2404** [comment]
@Piiit It seems there's no easy way to tell nemo not load extensions... I would still uninstall nemo-dropbox and live without it some time.

**Comment by xenopeek** [comment]
@Piiit is this issue still occurring?

**Comment by Piiit** [comment]
@xenopeek I have now upgraded to LM18, never had this issue again... so I close it.

**Comment by jluismoran** [comment]
In my case this issue happens when I have my smartphone connected to my PC in only charge mode. Maybe, this could due about some error around the device mounting.

**Comment by bvx89** [comment]
@jluismoran Thank you! Unplugging my phone fixed the issue.

**Comment by jessewriter** [comment]
I'm having this issue with LM18.3 and it seems to be more frequent lately.  not using dropbox.

same error: (nemo:5599): GLib-GIO-CRITICAL **: g_file_info_get_attribute_uint64: assertion 'G_IS_FILE_INFO (info)' failed
after starting nemo from terminal
