### ISSUE TITLE
Compiler error : -Werror=unused-const-variable=

### ISSUE THREAD

**Issue by Salamandar** [linuxmint/nemo#1207]
Compiling Nemo doesn't work : 

    At top level:
    nemo-notebook.c:54:29: error: 'url_drag_types' defined but not used [-Werror=unused-const-variable=]
     static const GtkTargetEntry url_drag_types[] =
                                 ^~~~~~~~~~~~~~
    cc1: some warnings being treated as errors
Compiling using

    make V=1 CFLAG=-Wno-error

does not work either.

**Comment by f2404** [comment]
This has been fixed in https://github.com/linuxmint/nemo/commit/6884c297a618d66c9d433aac0a6cf5aa74e71cb5

**Comment by Salamandar** [comment]
Oh, didn't see the nemo-git package in the AUR was tracking the 2.8-maintenance branch… Sorry :p

**Comment by f2404** [comment]
Yep, the same happened to me, that's why I knew the answer :)

**Comment by Salamandar** [comment]
Oh ! So you probably know why the makepkg prepare() function does not run. I'll try to remove all the patches the maintainer added in the PKGBUILD.

**Comment by f2404** [comment]
Should the issue be closed now?

**Comment by Salamandar** [comment]
Hum, I dunno why the issue was reopened. Probably a missclick.
