### ISSUE TITLE
Show hidden files button, with visible state

### ISSUE THREAD

**Issue by rphair** [linuxmint/nemo#1213]
(Please let me know if this is already in Nemo 3.x, which I have no way of testing right now.)  In 2.x there is no way to tell whether the directory listing is showing hidden files.  You'd have to navigate to a folder with hidden files in it and toggle Ctrl-H, perhaps more than once to be sure, to get the desired state if you hadn't memorised it already.

It would put the user more in control (more consistently with the Nemo design as I see it) if there were a Toolbar Preferences checkbox, in addition to the 13 already there in 2.8.7, for **Show hidden files button**.  This could also show the toggled state of hidden files: pressed if so, normal if not.

**Comment by f2404** [comment]
No, there's still no indication in Nemo 3.
But would it be convenient to go to Preferences->Toolbar to look at the checkbox? I'm thinking there could be an indication not so far away, in the bottom bar maybe?

**Comment by rphair** [comment]
No no no, look at the top bar ("Toolbar") in Nemo, especially in the group of buttons where you'd see the button "Toggle location entry" (itself a toggle button, though its state is not visible on the button itself), "Open a terminal", and another toggle button for the search window.  I'm talking about a button like that.  The checkbox in Preferences would merely be to enable it.

**Comment by f2404** [comment]
Ah, I see what you mean. Yes, I think that could be useful (better than hitting Ctrl+H twice, anyway).

**Comment by rphair** [comment]
yes, the excellence of Nemo is that it's a navigational instrument: not just removing extra keystrokes but also uncertainty about moving through & viewing your files.  For instance, even if you hit Ctrl-H twice in a directory without having hidden files, it will tell you nothing.  A toggle button with visible state would guide & inform you in any possible situation, like an indicator on the dashboard of a car.

**Comment by xenopeek** [comment]
This isn't changed on Nemo 3.0.6. Would many users toggle to show hidden files often if ever? This may make more sense as an extension https://github.com/linuxmint/nemo-extensions.

**Comment by JosephMcc** [comment]
I labeled this as a feature request but I'm not a big fan of adding even more buttons to the toolbar. Just personal opinion.

**Comment by NikoKrause** [comment]
Just right click on a whitespace somewhere in a folder. In the context menu there is an option `Show hidden files`. If hidden files are shown, the checkbox is checked. If not the checkbox is emtpy.
![screenshot-area-2017-08-01-190855](https://user-images.githubusercontent.com/8415124/28837508-3df796d2-76ed-11e7-9498-4154b9134f73.png)

**Comment by rphair** [comment]
Great!  That's like telling a car driver, "You don't need a brake light on the dashboard," after you've mounted the brake light inside the glove box... "All you need to do is open up that glove box & you can see the brake light right there!"

In that same analogy, comments further up are saying: "You don't need to the brake light at all, since you should always be able to remember whether or not your food is on the brake."

In general, UNIX users want to do with their eyes (and typing) what Windows users would have to reach to the mouse for.  With thanks to @NikoKrause, it is better than nothing to have that checkbox available somewhere, even with a repetitive motion conceptually unrelated either to the context menu or the blank screen the user is expected to click on.

The purpose of indicators is to indicate things: perhaps an unfashionable idea (e.g. as GNOME takes away more configurable options every year) but easily accommodated by an indicator toggle with a default state of OFF.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
