### ISSUE TITLE
File copy queue 

### ISSUE THREAD

**Issue by f2404** [linuxmint/nemo#1214]
Is it strictly required to perform all file copy/move operations in a queue manner?
I'm not able to copy a tiny little file using Nemo while it's copying a large file over ssh which could take half an hour.

**Comment by mtwebster** [comment]
The queue can be disabled entirely in nemo preferences

**Comment by f2404** [comment]
OK, thanks.
Why is it enabled by default?

**Comment by mtwebster** [comment]
Because multiple simultaneous operations to removable devices can cause freezes in certain situations and with some hardware.

**Comment by f2404** [comment]
OK, thanks.
