### ISSUE TITLE
Falled desktop redraw in GTK 3.21.3

### ISSUE THREAD

**Issue by lukefromdc** [linuxmint/nemo#1215]
Beginning with the various GdkDrawingContext changes to GTK during the 3.21.2 cycle, the desktop background in Caja has become "persistant" with a failure to redraw and "erase" when any icon is moved. In addition, all icon and text shadows are rendered at 100% opacity. The offending GTK 3 commit is 
https://git.gnome.org/browse/gtk+/commit/?id=2c7b21718f18ab743cd79784ae28cad582f58503
"Simplify the widget rendering entry point"
lots of internal changes in gtkwidget internal cairo interaction

This also affects Caja 
https://github.com/mate-desktop/caja/issues/575
Only Nautilus is not affected by this, in fact an instance of the new split-out nautilus-desktop is a workaround for this.

**Comment by lukefromdc** [comment]
This bug report was just filed against GTK 3.21.3

https://bugzilla.gnome.org/show_bug.cgi?id=768415

**Comment by xenopeek** [comment]
Is this related to  #1215?

**Comment by lukefromdc** [comment]
https://github.com/linuxmint/nemo/issues/1231
and
https://github.com/linuxmint/nemo/issues/1215#issuecomment-242506297

are the same issue.
https://github.com/linuxmint/nemo/pull/1235
and
https://github.com/linuxmint/nemo/pull/1232
were both submitted over it, with 
https://github.com/linuxmint/nemo/pull/1235
probably being the better of the two.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1231
