### ISSUE TITLE
Nemo doesn't suggest files starting with dot 

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/nemo#1216]
Press Ctrl+L
Start typing file name, for example .bashrc. 
Nemo will suggest only `.` which is upper directory

**Comment by xenopeek** [comment]
Nemo will only suggest directory names in Ctrl+L. .bashrc is a file nor a directory. Hidden directories are suggested when you type the first letter after the dot. Tested on Nemo 3.0.6 (Linux Mint 18).

I think this one can be closed?

**Comment by Yanpas** [comment]
I was using 2.8 at that point. Did nemo support dropdown list of suggested directories?

**Comment by xenopeek** [comment]
I looked at Nemo 2.8.6 on Linux Mint 17.3; exact same behavior. In Ctrl+L it suggests only to complete the directory name you have partially typed. No dropdown list.

There is a problem with Ctrl+F (search bar) not showing matching hidden files. See #604.
