### ISSUE TITLE
Text selection color is white or light under some themes

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/nemo#1217]
Try to rename file under Greybird theme or Adwaita. Selection color will be white and Grey

**Comment by JosephMcc** [comment]
In the list view, icon view? What version of Gtk?

**Comment by Yanpas** [comment]
Icon view, GTK 3.18 (Xubuntu 16.04)

**Comment by ramonsantos** [comment]
I'm with this same problem. 
My OS is Fedora 24 with the theme Adwaita. The Nemo version is 3.0.5 and the version of GTK is 3.20

**Comment by xenopeek** [comment]
Duplicate of #1333
