### ISSUE TITLE
Bookmarks not showing if in superuser rights

### ISSUE THREAD

**Issue by Hammerhand17** [linuxmint/nemo#1222]
Hi, I am trying to add new bookmarks to sidebar in nemo. When I drag a folder to sidebar, the word "bookmars" appears, but I can drop the folder inside, just in the "computer" section. 

If I open the folder as superuser, I can add folders to the "bookmarks" section, but they are not showing in the non-superuser section.

Every bookmark I add keeps only in the mode I open (superuser/not-superuser).

**Comment by xenopeek** [comment]
Which version of Nemo are you using? What is your Linux distro and its version? On Linux Mint 18 Cinnamon with Nemo 3.0.6 I can drop bookmarks under the "Bookmarks" label that appears when I drag a directory over the sidebar.

As for superuser vs non-superuser, yes they have different home directories. Nemo stores and read settings such as bookmarks only from the user's own home directory.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
