### ISSUE TITLE
Bug with filemanager.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/nemo#1223]
Have noticed a bug.

When some folder in FM is opened, and you change your icon theme in settings - your FM will crash if you press "back" arrow or open random folder. It happens after icon theme being changed.

**Comment by HTechnology** [comment]
I tried to recreate the conditions of the bug, but I have noticed no bug, it works perfectly when I press "back" arrow or open a folder. I use : opensuse 13.2, nemo 3.0.6 and cinnamon 3.0.7

**Comment by alxgvr** [comment]
maybe it was fixed...

2016-08-18 22:08 GMT+03:00 HTechnology <notifications@github.com>:

**Comment by HTechnology** [comment]
Yes, may be, hope nobody else don't complain about this bug :) .

**Comment by xenopeek** [comment]
@alxgvr what is your Nemo version and what Linux distribution are you using? Is this problem still occurring for you?

**Comment by alxgvr** [comment]
Looks like problem is gone. At the moment all works fine.

Чт, 25 авг. 2016 г. в 22:01, xenopeek <notifications@github.com>:
