### ISSUE TITLE
Columns always start in minimal width

### ISSUE THREAD

**Issue by dvbeek** [linuxmint/nemo#1225]
When I start Nemo, all columns except the Name start in the minimal width (all columns only show '...').
I can resize them to see the information, but at the next start or a new tab all sizes are back to minimal.

I use Nemo on my laptop (version 2.8.7, Mint) and at home (version 3.0.5, Ubuntu) without problems, but at my working pc (version 3.0.5, Ubuntu) it only has this problem.

**Comment by xenopeek** [comment]
I'd recommend to create a new user account, log in to that, and see if the problem is also present there. To determine if this is a system-wide issue (perhaps you have a very low screen resolution?) or an issue only with your own user account.

**Comment by dvbeek** [comment]
Thanks for the reply.

The problem exists also for a new created user.
And I have 2 displays, both 1920 x 1080 px.

**Comment by JosephMcc** [comment]
I can't reproduce this. In fact I can't even get them to shrink to the point where I get the '...' instead of label.

**Comment by Garibaldo** [comment]
I have the exact same problem. I'm running the latest Cinnamon from the nightly ppa.

**Comment by JosephMcc** [comment]
Be aware some things are now broken in Cinnamon without a minimum of gtk3.10

**Comment by dvbeek** [comment]
Whem I compare my work-ubuntu (problem) with my home-ubuntu (no problem):
- Work: Ubuntu 14.04.5 LTS / GTK 3.10.8-0ubuntu1.6 / Cinnamon 3.0.7
- Home: Ubuntu 14.04.4 LTS / GTK 3.10.8-0ubuntu1.6 / Cinnamon 2.8.8
The biggest difference is Cinnamon, maybe the newer version causes the problem?

**Comment by JosephMcc** [comment]
As mentioned Cinnamon/Nemo 3.0 are not supported or tested on distros using gtk3.10. That would include trusty. Can't guarantee that is the cause of the issue but it is possible.

**Comment by xenopeek** [comment]
I tried just installing Nemo 3.0.6 and fully upgrading from the Cinnamon Nightly PPA on Linux Mint 17.3 (based on Ubuntu 14.04). I can't reproduce this Nemo issue with either approach. The column layout is different though.

Nemo 2.8.6:
![17 3 nemo 2 8 6](https://cloud.githubusercontent.com/assets/21159972/17921357/bb93716e-69d9-11e6-8034-e8f86514faea.png)

Nemo 3.0.6:
![17 3 nemo 3 0 6](https://cloud.githubusercontent.com/assets/21159972/17921358/bb9538aa-69d9-11e6-8040-360302563557.png)

**Comment by xenopeek** [comment]
I could reproduce the issue on Ubuntu 14.04.5 by installing Nemo from Cinnamon Nightly PPA.

I can fix the issue on Ubuntu 14.04.5 with Nemo 3.0.6 by installing libgtk-3-0 from Linux Mint 17.3.

Broken:
![14 04 5 nemo 3 0 6 error](https://cloud.githubusercontent.com/assets/21159972/17922388/f696ae52-69de-11e6-825f-e6775ee44913.png)

Fixed:
![14 04 5 nemo 3 0 6 fixed](https://cloud.githubusercontent.com/assets/21159972/17922400/0c04d958-69df-11e6-98d6-4a6986d252b5.png)

To avoid breaking dependencies also install libgtk-3-bin and libgail-3-0 from Linux Mint 17.3, but those aren't needed to make the issue go away. Mind that I mention this to help with analysis. Ubuntu will consider this a downgrade so you will have to pin these packages if you don't want to have software updater revert to the Ubuntu version.

Links to where you can find the packages if you want to try that:
http://packages.linuxmint.com/search.php?keyword=libgtk-3-0&release=Rosa&section=any
http://packages.linuxmint.com/search.php?keyword=libgtk-3-bin&release=Rosa&section=any
http://packages.linuxmint.com/search.php?keyword=libgail-3-0&release=Rosa&section=any

**Comment by JosephMcc** [comment]
Ah, good catch. We patched our own version of gtk in Mint for 3.10. We don't do that anymore in Mint 18. Now that you brought this up I do believe we may have patched some things specifically for GtkTreeView.
