### ISSUE TITLE
Desktop icons kept highlighted when mouse cursor moves away

### ISSUE THREAD

**Issue by f2404** [linuxmint/nemo#1228]
The desktop icons get highlighted when mouse cursor moves over them and return to their normal state when the cursor moves away. But, this does not happen if the cursor moves directly to some app window from an icon - in this case the icon will remain highlighted until the cursor happens to get to unoccupied desktop area.
Arch Linux, Cinnamon 3.0.7, Nemo 3.0.6.

**Comment by f2404** [comment]
In this screenshot, the Home icon is highlighted while the mouse pointer moved away to the Firefox window:
![home_icon_highlighted](https://cloud.githubusercontent.com/assets/14939413/16990109/e34fea7c-4ea7-11e6-8521-6aaa40e70908.png)

**Comment by Piiit** [comment]
I can confirm this issue with Linux Mint Cinnamon 18, Nemo 3.0.6 and Cinnamon 3.0.7...

**Comment by Cos-mo** [comment]
I cannot confirm this behavior, as long as the desktop icon gets only hovered, not marked (via single left click).

You might check the behavior with a fresh new user account.

**Comment by JosephMcc** [comment]
I can reproduce this the way it's shown by f2404.

**Comment by f2404** [comment]
I cannot reproduce it anymore with 3.2.0.
