### ISSUE TITLE
Async model view

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/nemo#1229]
I just realized that the file view is synchronous. Using a high latency file system like sshfs heavily freezes the ui. Please make this async.

![bildschirmfoto vom 2016-07-21 14-25-31](https://cloud.githubusercontent.com/assets/3252315/17022576/11773746-4f4f-11e6-8a55-69d5d3a511b1.png)

**Comment by KoczurekK** [comment]
+1, I sometimes recognise this while working with veeery slow hard drives over some IDE->SATA connectors. :(

**Comment by xenopeek** [comment]
This looks like another example for #1220.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
