### ISSUE TITLE
Change focus from the sidebar to the contents view easily

### ISSUE THREAD

**Issue by LogicStuff** [linuxmint/nemo#1230]
I find it hard to change focus (either by keyboard, or automatically) from the sidebar to the contents view in Nemo 2.8.7 on Ubuntu 16.04.

I would like to be able to navigate through folders quickly, by typing in starting characters of folders, using arrows and pressing enter/backspace, without having to use a mouse, or possibly any shortcut to switch the problematic focus on the sidebar.

[![enter image description here](http://i.stack.imgur.com/sCiKl.png)](http://i.stack.imgur.com/sCiKl.png)
### How I can switch:
- using a mouse
- by switching between icon/list/compact views with a shortcut - <kbd>control</kbd>+<kbd>1</kbd>/<kbd>2</kbd>/<kbd>3</kbd> (ridiculous)
- by opening the bookmarked folder in a new window - <kbd>control</kbd>+<kbd>return</kbd> (even more so)
- by opening the bookmarked folder in a new tab - <kbd>shift</kbd>+<kbd>return</kbd>, switching to the previous tab and back with <kbd>alt</kbd>+<kbd>1</kbd> and <kbd>alt</kbd>+<kbd>2</kbd> (...)
### How I would like to switch:
- at the first click/<kbd>return</kbd> key press on the sidebar.
- also with a shortcut (like <kbd>tab</kbd>), back and forth

What can be done about it?

**Comment by xenopeek** [comment]
I couldn't find a way to switch focus between main window and sidebar on Nemo 3.0.6 either.

**Comment by Cos-mo** [comment]
There is a workaround:

You can use F6 (press it once or twice) to focus to the pane (but not back to the side pane).

But there is a limitation:
This works only, if you have dual panes set and you have to set Nemo in the preferences, that it opens with 2 panes. In this case F 6 toggles between the 2 panes. The trouble is, that in case, you open the second pane with F3 only after the start of the Nemo window, F 6 does not work - more precisely: only after having switched at first using the mouse.

**Comment by xenopeek** [comment]
Related to #897 and #816.

**Comment by christianbueno1** [comment]
thank you @Cos-mo ,F6 is very useful.
Now we can go to my drive only by keyboard.
Super+E
F6, put the focus in the side pane
Type the name of your drive, in my case "nuevo vol"
Enter
Enter  one more time for go into the drive and the focus will be in the view pane.
Type the name of the desired folder.
![screenshot from 2016-11-03 01-37-43](https://cloud.githubusercontent.com/assets/10623247/19957864/55d1de3a-a168-11e6-9f5c-637cf77a2aaa.png)

**Comment by jerkey** [comment]
this seems like a huge oversight, pretty much every other program with a GUI has the standard keys available for switching panes and focus.  that a file manager picked as the default in a popular operating system is missing this basic functionality is sad.

talking about workarounds and weird key combos that sortof achieve the goal of compensating for this bug is disheartening.  I wish i had the skill set to just fix it.

**Comment by rohitchormale** [comment]
I think we can close this issue. On nemo v3.4.7, F6 can be used to toggle between sidebar and main window

**Comment by Cos-mo** [comment]
On Nemo 3.6.5 I see no progress. 
F6 is expected to toggle between the 2 panes. Only if Nemo is set to open with 2 panes F6 works; if Nemo gets launched with only 1 pane and you open a second pane with F3 the key F6 does do nothing, except with the workaround I described above.
Toggling between pane and side-bar does sometimes work with F6, but not reliable. If there are 2 panes open F6 is never able to set the focus to the side-bar

**Comment by vstepaniuk** [comment]
Why not to make it switch with Tab and Shift+Tab as everywhere?

**Comment by Neutrino-Sunset** [comment]
F6 is a royal pain in the arse on a laptop, where you have to hold a function modifier key next to [super] for the function keys to work this is a two handed shortcut.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
