### ISSUE TITLE
gtk-3.21.4 no desktop redraws or bg changes until restart

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/nemo#1231]
Caja has the same issue

https://github.com/mate-desktop/caja/issues/575

I have managed to fix the redraw issue with this patch

[canvas-container.patch.txt](https://github.com/linuxmint/nemo/files/376660/canvas-container.patch.txt)

taken from

https://git.gnome.org/browse/nautilus/commit/?h=gnome-3-8&id=6d6bf1e7c6049b4bd300ae1d90833a8b5fcf30c4

There is a side affect, the background is rendered grey.

![screenshot from 2016-07-21 19-13-07](https://cloud.githubusercontent.com/assets/1299302/17033686/370591e2-4f77-11e6-978d-20fe96683908.png)

**Comment by leigh123linux** [comment]
changing theme to adwaita get the background working

I've tried the css from this but it doesn't work

https://git.gnome.org/browse/nautilus/commit/?id=f3ea3f0260f62426947238a28cbef79c1242ab9b

**Comment by leigh123linux** [comment]
![screenshot from 2016-07-22 00-26-42](https://cloud.githubusercontent.com/assets/1299302/17042140/2c896e2e-4fa3-11e6-8701-15a960db7393.png)
![screenshot from 2016-07-22 00-26-49](https://cloud.githubusercontent.com/assets/1299302/17042142/2cb0418e-4fa3-11e6-880f-384e90734671.png)
![screenshot from 2016-07-22 00-26-55](https://cloud.githubusercontent.com/assets/1299302/17042144/2cb0fc1e-4fa3-11e6-85f4-b225ebfd6f78.png)
![screenshot from 2016-07-22 00-27-02](https://cloud.githubusercontent.com/assets/1299302/17042143/2cb05dd6-4fa3-11e6-8719-93e7243a7e15.png)
![screenshot from 2016-07-22 00-27-11](https://cloud.githubusercontent.com/assets/1299302/17042141/2caf5abc-4fa3-11e6-9e12-54fed249a94c.png)

**Comment by lukefromdc** [comment]
I found that I needed this patch to your nemo-application.css to get all themes I have to work (with the patch you sent me), due to the paned and notebook widgets picking up the background:

```
--- /home/luke/Desktop/nemo-style-application.css   2016-07-26 00:16:35.497198233 -0400
+++ /home/luke/Desktop/nemo-style-application.css_FIXED 2016-07-26 00:54:24.208289398 -0400
@@ -1,7 +1,10 @@
 /* Desktop text stuff */

 .nemo-desktop-icon-view,
-.nemo-desktop-icon-view .view {
+.nemo-desktop-icon-view .view,
+.nemo-window-pane,
+.nemo-desktop-window paned,
+.nemo-desktop-window notebook{
     background-color: transparent;
 }

```

**Comment by sebalis** [comment]
I’m seeing this bug with the latest gnome packages as contained in the Arch Linux “community” and “extra” repositories (i.e. most gnome packages are 3.22.0-1, nemo is 3.0.6-2). Is there something I need to do? The bug is very annoying, my current (least bad) workaround is to kill and restart nemo.

**Comment by leigh123linux** [comment]
@sebalis if this https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/nemo was compiled against gtk-3.22 it should work.

**Comment by sebalis** [comment]
Thanks, but ripping out my existing nemo package (and then compiling nemo-git from AUR) seems rather daunting as more than 20 other packages depend on it. If a newly released nemo package might resolve this in a few days or so then I could live with waiting and using my workaround.

**Comment by leigh123linux** [comment]
@sebalis Daunting?, Why use Arch then?

```
pacman -S community/nemo
```

**Comment by sebalis** [comment]
Let’s say bothersome rather than daunting. To answer your question, I want rolling releases and recent software and am okay with the involved risk. But at least while I don’t know how to deal with replacing a package with its -git variant when there are about 25 packages depending on it, the task seems too large and manual. But if this is an opportunity for me to learn and you’d be willing to give me pointers, I’d be interested.

**Comment by leigh123linux** [comment]
You shouldn't need to use git as the community nemo package has been patched

https://github.com/linuxmint/nemo/issues/1316

**Comment by sebalis** [comment]
Thank you so much! It was a simple case of “pacman -S community/nemo” and restarting nemo one last time. Even before commenting I had noticed that I had the nemo package both from the antergos and community repos (identical version numbers just described in #1316). Now wondering how to rectify that, but in any case I have now become learned that this can happen and there are ways of handling it.

**Comment by lukefromdc** [comment]
Nemo is really not that difficult to build.
