### ISSUE TITLE
Desktop drawn wrong size in compiz

### ISSUE THREAD

**Issue by lukefromdc** [linuxmint/nemo#1234]
https://github.com/lukefromdc/nemo/commit/9cb9c48f59baa28a21fa7d5b6f89b4d85d546d4b
does not work in compiz, and brings back the failure to draw the desktop full size at least when running GTK 3.21.  
Submitted PR 
https://github.com/linuxmint/nemo/pull/1233
for this, anyone know a better way to do this?

**Comment by leigh123linux** [comment]
Is the fixed in 3.2.x?

**Comment by lukefromdc** [comment]
Works fine with 3.2

This was apparently fixed by: 

https://github.com/linuxmint/nemo/commit/c5a513468ee8c3497f0673e3ca019ccd3f409f8b
desktop: Don't rebuild the desktop any time _NET_WORKAREA changes - 

which in turn required For HDPI issues:

https://github.com/linuxmint/nemo/commit/d4c3a5f357b35f19a9d97efaf317f6be5c3b7f76
nemo-desktop-manager.c: run layout_changed when the widget scale 

Since then the desktop has worked in compiz

**Comment by leigh123linux** [comment]
Thanks for replying.
