### ISSUE TITLE
An option for not showing thumbnail when icon is small

### ISSUE THREAD

**Issue by focusime** [linuxmint/nemo#1236]
I usually use icon view to browse photos , and thumbnail help a lot in finding the picture  I want. But sometimes I also use list view (with 50% of icon size) to find my target by file name. And everytime I toggle to the list view, it woult still spend some time to show the small, barely recognizable thumbnail, which is wasting resource and not necessary.  So maybe it would be better for old PC if we can set a threshold for not showing the thumbnail in small icon.

P.S. Sorry about my poor english. I use linux mint in chinese, so some phrase may not used correctly.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
