### ISSUE TITLE
Drag and Drop on archive file doesn't work properly when the names contain spaces, Mint 18

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/nemo#1237]
Drag and Drop on archive file woks properly only when both the archive and the dropped file(s)/folder(s) filenames don't contain spaces. The dropped files/folders with space containing names are simply ignored, Also when the archive name contains spaces, a new archive is generated with spaces replaced with zeroes , also the new archive contains only the dropped files/folders.

Examples:

**'example.zip' + 'document.odt'** _-> working as expected,  'document.odt' is added to the other files in the archive_

**'example.zip' + 'new document.odt'** _-> nothing happens_

**'example.zip' + 'new document.odt', 'document.odt'** _-> only  'document.odt' is added_

 **'example with spaces.zip' + 'document.odt'** _-> generates   'example0with0spaces.zip'  containing only 'document.odt' (in the case when the original archive is not empty), also nothing happens to the original archive_

The correct command I guess is **file-roller --add-to '_[archive name]_' '_[file 1]_' '_[file 2]_' ...**

**Comment by xenopeek** [comment]
I can confirm this issue. Easily reproduced with your example. Looks to be a problem in function nemo_view_move_copy_items in nemo-view.c.

**Comment by surenenfiajyan** [comment]
This problem also present in Caja in Mint Mate 18.
