### ISSUE TITLE
linuxmin 18: no more recent places

### ISSUE THREAD

**Issue by timmie** [linuxmint/nemo#1238]
After upgrade to mint 18, the recent places menu is not available when saving or opening files.

How can this be brought back?

**Comment by timmie** [comment]
EDIT:  only applies to selecting location & filename in Firefox PDF save dialogues.

**Comment by JosephMcc** [comment]
As I said before https://github.com/linuxmint/nemo/issues/1221#issuecomment-230877609
Nemo has nothing to do with the open/save dialogs provided by applications.

**Comment by JosephMcc** [comment]
Two things. One, the setting pointed to my mtwebster does enable it in the Gtk open/save dialogs here. Two, this has nothing to do with Nemo. Issues with the open/save dialogs provided by toolkits like Gtk need to be brought up with the upstream developers.
