### ISSUE TITLE
Location bar disappeared in File->Open in gedit, firefox and other application

### ISSUE THREAD

**Issue by dreamworkerln** [linuxmint/nemo#1240]
Linux Mint 18 Cinnamon: 
In File->Open button "type a file name"  disappeared in gedit, firefox and other application. 
This button allow always show Location bar, instead pressing Ctrl+L every time. 
Howto always show Location bar in File->Open dialog ? Thanks.

Was
![screenshot from 2016-07-28 13-22-29](https://cloud.githubusercontent.com/assets/3149061/17210548/ad1058ec-54d4-11e6-881c-bb95b6ad09f9.png)

Now
![screenshot from 2016-07-28 13-21-17](https://cloud.githubusercontent.com/assets/3149061/17210526/8eda7010-54d4-11e6-8e8d-a5d00da7cd5e.png)

**Comment by JosephMcc** [comment]
This has nothing at all to do with Nemo. Your better off getting help in the Linux Mint forums.
