### ISSUE TITLE
Crash on window close (Ubuntu 16.04 Nemo 2.8.6)

### ISSUE THREAD

**Issue by atl94** [linuxmint/nemo#1241]
Nemo crashes occasionally when I close windows. Per the other issues here, I looked to disable scrollbars under effects but that is not an available option as far as I can tell in 2.8.6.

http://pastebin.com/xfuAuBia

**Comment by xenopeek** [comment]
Could you retest this with the current version of Nemo, 3.0.6? You can either add one of the Cinnamon PPAs that have that version for Xenial (like https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon I think) or you can install the packages needed directly.

To install the packages needed directly please first remove all your current installed nemo packages. Then make sure python-gi is installed or install it with:
`sudo apt install  python-gi`

Then download the needed packages with:
`wget http://packages.linuxmint.com/pool/backport/n/nemo/nemo_3.0.6+sarah_amd64.deb http://packages.linuxmint.com/pool/backport/n/nemo/libnemo-extension1_3.0.6+sarah_amd64.deb http://packages.linuxmint.com/pool/backport/n/nemo/nemo-data_3.0.6+sarah_all.deb http://packages.linuxmint.com/pool/backport/c/cinnamon-desktop/cinnamon-desktop-data_3.0.2+sarah_all.deb http://packages.linuxmint.com/pool/backport/c/cinnamon-desktop/libcinnamon-desktop4_3.0.2+sarah_amd64.deb`

And finally install them all:
`sudo dpkg -i *.deb`

To revert to the older Ubuntu version of Nemo remove all the installed packages with following command and reinstall Nemo from Ubuntu's Software Center:
`sudo apt purge cinnamon-desktop-data libcinnamon-desktop4 nemo nemo-data libnemo-extension1`

**Comment by atl94** [comment]
I did so about a week ago using the embrosyn ppa and have since not received a crash after disabling scroll bars. The power icon now links to nothing (just a window with the only option being "cancel"), but it's easy to work around and a small price to pay for a stable cinnamon.

**Comment by JosephMcc** [comment]
If your original issue is no longer a problem would you please close this?
