### ISSUE TITLE
Icon themes  bug - scaling

### ISSUE THREAD

**Issue by Raijukami2** [linuxmint/nemo#1243]
In LM17.3, nemo is version 2.8.7 and it doesn't cause any problems to icon themes I downloaded from other sources. In LM18 nemo has been updated and now it breaks set icon themes. Please note that this doesn't happen for everything, more exactly for those icons themes that  have every size possible. The default icon themes from mint work of course because they have every size required.

The icon sets I am talking about are here:
https://www.gnome-look.org/p/1002340/              Breeze Dark Classic
http://alecive.deviantart.com/art/AwOken-163570862    AwOken Icon theme
Yes they are not made for Cinnamon exactly but for gnome which Cinnamon was based on.
This icon sets work perfectly in 17.3 but not in LM18. On the other hand they do work in Xfce and Mate from LM18 because their file managers don't have this issue.
I think that the problem is in the icon scaling. Awoken has problems both with the places icons (folders) and other ones. Places are in 24x24 (which look fine in list mode) and in 128x128 which are scaled to fit, but in the latest nemo they don't. 

Some info:
1. On my PC (host) - system is up-to-date
Host: PC Kernel: 4.2.0-42-generic x86_64 (64 bit gcc: 4.8.4)
Desktop: Cinnamon 2.8.8 (Gtk 3.10.8~8+qiana) Distro: Linux Mint 17.3 Rosa
    Nemo:2.8.7
2. On the virtual machine - clean install, updated system
Host: mint18-VirtualBox Kernel: 4.4.0-31-generic x86_64 (64 bit gcc: 5.3.1)
Desktop: Cinnamon 3.0.7 (Gtk 3.18.9-1ubuntu3.1) Distro: Linux Mint 18 Sarah
    Nemo:3.0.6
    Thunar:1.6.10  - used for side by side example

I put LM18 in a virtual machine (on my hardware there is the same issue) and I put nemo side by side with thunar installed from the software manager.
Here is the Breeze dark:
https://i.imgur.com/4vgwYKP.png
http://i.imgur.com/MwUUUjz.png
http://i.imgur.com/tMNMGZC.png
Please note how the icons in nemo are larger and how the context menu is affected.

Here is the Awoken white:
http://i.imgur.com/S2rK5qQ.png
http://i.imgur.com/nynimNH.png
http://i.imgur.com/f0u2TNz.png
As you can see here the scaling issue is really easy to spot because the icons are shown in 128x128 both on the desktop (which nemo takes care of) and in the file manager itself. Thunar though does display the icons as it should.

I didn't want to post this because these are not icons officially supported, but because they used to work and now they don't, I think is enough of a reason to at least bring attention to a potential bug. It is also possible that Nemo simply changed and doesn't support these icon themes in the same way that gtk has been updated. If that is the case than this is not a bug and I will have to find another icon theme.

As a side note, please include a white set of action icons in the official icon sets (or make an official dark set), because these icons are black and if you have a dark theme they simply blend in. This is actually one of the reasons I don't use the official icon themes. See what I mean:
http://i.imgur.com/J9LP4vA.png     Awoken white action icons in gedit 2.30.4 LM17.3
http://i.imgur.com/HZ3LNJi.png     Mint-x action icons in gedit 2.30.4 LM17.3

**Comment by JosephMcc** [comment]
The issue is with the old unmaintained icon themes and not nemo. As of gtk3.14 there were major changes in icon theme handling so these themes no longer work properly. They work for now in caja and thunar because those are still gtk2.
