### ISSUE TITLE
Treeview toggle to show/hide ~/.hidden folders

### ISSUE THREAD

**Issue by RiaanBurger** [linuxmint/nemo#1244]
I love the treeview and it is my default for the left side panel. As a web
developer we have loads of .hidden folders in our working directories, so hiding
them altogether isn't really an option.

Being able to easily toggle hiding the .hidden folders in my ~ for the treeview
will help navigation a heck of a lot. It will place additional mounts and /
right there in easy reach and visible. Of course, as a Linux user one often also
browse those ~/.hidden folders, so switching between hidden and visible should
be easy, otherwise one will just leave them visible all the time again.

Thank you for an amazing file manager you C guys you! Wish I knew C, then I'd jump in with a pull request for this.

**Comment by xenopeek** [comment]
The keyboard shortcut Ctrl+H toggles showing of hidden files and directories. It will show hidden directories in the treeview sidebar.

**Comment by RiaanBurger** [comment]
Thank you xenopeek. Unfortunately it toggles bot the file view and the treeview and for treeview. Really, it would just be nice to be able to hide all the ~/.hidden folders in treeview, not all .hidden ones. ~ is so littered with hidden folders what once you open it anything that comes after it in tree view becomes essentially scroll-hell-hidden far down.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
