### ISSUE TITLE
Nemo says a file was modified today when it was actually yesterday

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/nemo#1247]
`ls -l` on the file shows the modified date is `Aug  2 16:05` but in Nemo the `Date Modified` is displayed as `today at 4:05:59 PM`.  The date is currently 3 August and it's just after 11am -- so we've not even got to 4:05:59pm yet!

I'm running an up-to-date Mint 18 and `apt list nemo` returns `nemo/sarah,now 3.0.6+sarah amd64 [installed]`.

PS My time zone is BST (GMT+1) at the moment.

**Comment by ManuelSchneid3r** [comment]
Just becaues I made the effort before I found this issue : :smile: 

![auswahl_023](https://cloud.githubusercontent.com/assets/3252315/17708447/514b9f4c-63e5-11e6-8e63-1cc9db57e14b.png)

**Comment by tonywhelan** [comment]
I have the same issue on Mint 18.1 64-bit, Cinnamon 3.2.7, kernel 4.4.0-53-generic. 
Nemo version 3.2.2+serena. However I can see that this has been fixed in Nemo 3.4.1-sonya 9on my test PC).
