### ISSUE TITLE
Cannot move file to trash

### ISSUE THREAD

**Issue by dodona2** [linuxmint/nemo#1253]
I can move the file /data/Music/New/xxx to the trashbin. However setting a link:
ln -s /data/Music/New/ ~/Downloads/Music/
then the nemo action 'Move to Trash' on ~/Downloads/Music/xxx causes:

> Cannot move file to trash, do you want to delete immediately?
> The file "xxx" cannot be moved to the trash.

nemo 3.0.6
mint:18
ubuntu:16.04 LTS (Xenial Xerus)
kernel:Linux INDRA 4.4.0-34-generic
x86_64 x86_64 GNU/Linux

**Comment by xenopeek** [comment]
Following your steps I can't reproduce this on nemo 3.0.6. I did:
`sudo mkdir -p /data/Music/New/xxx`
`sudo chown -R ${id -un}:${id -gn} /data`
`ln -s /data/Music/New/ ~/Downloads/Music`
And can move xxx to trash from both /data/Music/New/ and from ~/Downloads/Music/.
What filesystem is /data on? Run `findmnt /data` to find out. And what is the ownership and permissions on /data/Music/New/? Run `ls -ld /data/Music/New/` to find out.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
