### ISSUE TITLE
Wrong pourcent progress

### ISSUE THREAD

**Issue by phenix-factory** [linuxmint/nemo#1255]
![selection_080](https://cloud.githubusercontent.com/assets/1810149/17725001/5176b2a6-6447-11e6-8389-231d7c1e3741.png)

Hello,

I think something is wrong in the title bar ;).
I just copied some file to an external drive, USB3. Linux Mint 18, Nemo 3.0.6.

**Comment by feren** [comment]
I can confirm BTW, that this has sometimes happened to me too in some circumstances,,.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/591
