### ISSUE TITLE
Next Desktop Background in the Desktop right-click menu when slideshow's enabled

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1258]
Like you can see in Windows, could you make (at least) a 'Next Desktop Background' menu item for the Desktop right-click menu in Nemo's Desktop Handling UI whilst the Background Slideshow option is then enabled??

**Comment by JosephMcc** [comment]
Not sure about this, but it is available if you add the "Slideshow Controls" applet to the  panel.

**Comment by feren** [comment]
Yeah, I know, it's just slightly inconvenient to do that, and some people may not realize there's such an applet though...

**Comment by Cos-mo** [comment]
Adding it to the desktop context menu might probably be the first step to overload it and make it 
confusing for the users.

Probably a hint for the applet in the background settings page might help to get the user informed about it.

**Comment by MegaV0lt** [comment]
Temp workaround: https://github.com/linuxmint/Cinnamon/issues/6756#issuecomment-319838034

**Comment by xenopeek** [comment]
Thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by DanielRios549** [comment]
I know that the issue is closed, but there is an applet that does it exactly, but we have to add it to the panel, it would be more simple if the desktop context menu "identifies" that a slideshow is configured, and simply active an option to change the wallpaper...

**Comment by mtwebster** [comment]
Just use the action defined [here](https://github.com/linuxmint/Cinnamon/issues/6756#issuecomment-319838034).  It's simple and does what you want.

**Comment by DanielRios549** [comment]
I'm already using it, but an Action is something added by the user, not a feature that comes with the interface, most of the user won't see this issue and won't know that is possible to have this feature. And this action does not update automatically when you active ou descative the slideshow, a native implementation never would have this bug.
