### ISSUE TITLE
Left side (Tree view or Places) don't keep width aftert nemo restart if dual pannel is used

### ISSUE THREAD

**Issue by silviulaurentiu** [linuxmint/nemo#1259]
Reproduce the issue:
Edit -> Preferences -> Behavior -> Check:  Always start in dual-panel view
Adjust the left side panel (Tree view or Places) to about 300px.
Restart Nemo
Now the left side panel (Tree view or Places) width will have only about 50px, not about 300px which was set before to restart Nemo.

Thanks for your time!

**Comment by JosephMcc** [comment]
It seems ok here in Mint18 with latest nemo from git master. The panes have a minimum width. If I check the preference and then in dual pane mode adjust the size of the window so it can fit both panes plus the sidebar at the size I want it, closing and reopening nemo puts things back just the way I left them.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1164

**Comment by silviulaurentiu** [comment]
Thank you for your answer.
On my PC the issue is still present.
My OS is Linux Mint 18 Cinnamon and the version of Nemo is 3.0.6
Take a look on the attachment.
Thanks a lot for your time!

[Nemo - possible issue.pdf](https://github.com/linuxmint/nemo/files/454064/Nemo.-.possible.issue.pdf)

**Comment by rodobodolfo** [comment]
Same here on fresh mint 18 install, nemo 3.0.6
It only happens if I have "Always start in dual pane" option set.

**Comment by JosephMcc** [comment]
It's best to post in the linked duplicate issue that is still open.
https://github.com/linuxmint/nemo/issues/1164
