### ISSUE TITLE
Future: Keep last used location and view

### ISSUE THREAD

**Issue by silviulaurentiu** [linuxmint/nemo#1260]
I think will be useful if Nemo will be able to restore after restart the last view of Treeview / Places and last used locations, tabs ...

**Comment by JosephMcc** [comment]
So what you want is sort of like a "save session" preference?

**Comment by silviulaurentiu** [comment]
What I want to say is the next phrase: I some folders in the tree is opened, the same tree structure to be opened after restart. Please take a look on the attachment
[Nemo future.pdf](https://github.com/linuxmint/nemo/files/455494/Nemo.future.pdf)

**Comment by larry2311** [comment]
This feature request was very difficult to find, so would be getting very little exposure.
That said, no File Manager that I am aware of can do this. I consider this an almost essential feature; however, it does not exist as a feature or a plugin extension.
So, can I please encourage the incorporation of this as a new feature in the roadmap.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by silviulaurentiu** [comment]
Many thanks for this great news!
:-)

**Comment by jondo** [comment]
This is marked as completed, but with LM 21.3 / Cinnamon / Nemo 6.0.2 I still see no reopened nemo windows (even on local file systems) after logout/login. Is there some configuration I need to activate? I didn't find any.

**Comment by jondo** [comment]
”icarter09 closed this as completed on Dec 1, 2019"
