### ISSUE TITLE
Allow lasso selection in detail view

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1264]
You can select a number of objects in Nemo by holding the left mouse button pressed and drawing a rectangle, which includes the objects in question. But you can do this only in icon view and in list view, you cannot do this in detail view, not even if you at first click below the last shown object in the file pane.

For detail view this function would also give the need, that not the complete line for an selected objects gets marked, but only a part of it; usually marking the name columns would be enough. With this you could start to draw the lasso from a position left to the name column.

Affects all versions.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/416
