### ISSUE TITLE
Nemo action Check 256sum: visual action notification

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1265]
Using the build-in action for a sha256 brings the problem, that after calling it from the context menu of an ISO-file does not display any notification, that the command gets executed or does work at all.

I used the Mint 18 Cinnamon 64 bit ISO for testing. It takes 15 to 20 seconds, until the result gets displayed (this is acceptable and not my concern), but in those 20 seconds there is not the least indication, that Nemo is reacting for the command at all: No change in the mouse cursor, no hint in the state bar or anything else visible.
My suggestion: A popup opening at once displaying something like "Calculating ..."

**Comment by SethosII** [comment]
@Cos-mo Can you take a look at the [referenced pull request](https://github.com/linuxmint/mintsystem/pull/65) and see if this implements your feature request?

**Comment by Cos-mo** [comment]
@SethosII 

thank you for looking at the issue.

I used your code, taken from [here](https://github.com/linuxmint/mintsystem/pull/65/commits/5f1b3534e1413b2489ced865c4aaf98674add54b) and it is a real great improvement. The progress window pops up after a second or so and gives a fine feedback.

Used on Mint 18.2 / Nemo 3.4.6
Used file to test: ISO image of Mint 18.2 beta

There is still a small glitch; After the computing of the hash has finished the progress window closes, but it takes about 2 seconds, until the window with the computed hash appears. A first time user might think, that the nemo action has silently crashed.

I can imagine that is perhaps not possible to get the result window quicker to open. But perhaps it is doable to give the auto-closing of the progress window a small delay? (Just an idea)

In general: Yes, it satisfies my request.

**Comment by SethosII** [comment]
@Cos-mo Thank you for your feedback. I did some tests and also mentioned a delay only when the system is on high load/has low resources.
