### ISSUE TITLE
Nemo 3.0.6 does not display the content preview in the icons of text files

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1270]
At best to see in icon view.

If the preview has been enabled in the preferences, the content for text files does not get shown at all. Take a look at the user's home with displaying hidden files or in /usr/share/doc. All files with text content do only show a blank icon. - Nemo 2.8.7 does not give this problem.

It seems, that other file types are not affected by this bug (tested with the default wallpapers in /usr/share/backgrounds) and a PDF-file.

**Comment by JosephMcc** [comment]
This functionality was no longer supported as of Gtk3.14. Not much we can do about it except remove the option so at least the proper mimetype icons get used. That is now the case in git master. Was removed by https://github.com/linuxmint/nemo/commit/70753fac0eb1483ad828ed78a5401a3834bcc4c7

**Comment by Cos-mo** [comment]
If this is a regression by GTK 3.14, than removing the option is the least, what should be done. No user gets the idea, why there is an option, which actually cannot work.
