### ISSUE TITLE
Allow more granular setting of zoom level

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1273]
At present, desktop icons at 100% are a bit too big, and at 66% (the largest smaller size possible) they are too small. Somewhere between 75 and 85% if what I am after!

**Comment by hubertmeier** [comment]
On a HiDPI-Screen 100% are too small, 150% are too big and the spaces between the icons are much too big.

It would be useful to have small steps (5% or 10%) or we can choose the size of the icons (32x32, 48x48x, ... 256x256 

and

we can choose the space between the icons (in % or pixel).

**Comment by hobarrera** [comment]
This is starting to become a bug rather than a feature with retina/HighDPI screens.

My options currently vary from "uselessly tiny" to "small", and the last zoom option is such a large jump that it's simply too large. 😢

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
