### ISSUE TITLE
Batch file renaming

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1277]
Well, pretty simple to add, all you'd need is fork batch renaming from Thunar and then integrate that into Nemo...

It would be nice to have it in Nemo, would save me having to install Thunar for batch file renaming...

**Comment by JosephMcc** [comment]
> Well, pretty simple to add, all you'd need is fork batch renaming from Thunar and then integrate that into Nemo...

Pull Requests are welcome.

**Comment by feren** [comment]
I'm not actually sure how I'd go about Pull Requesting, I know how to do it (kinda), but not how to make it GTK 3 Compatible and separate Thunar Batch File Renaming from the program itself... (You guys would have to Pull Request it)

**Comment by JosephMcc** [comment]
Oh, well I though it would be simple.

**Comment by feren** [comment]
Ok, well, hope it ends up in Nemo though in the future... :)

**Comment by brmmm3** [comment]
In Gnome 3.22 Nautilus get's a batch file renaming feature. Maybe this would be easier to merge.

**Comment by Darthpenguin** [comment]
This is an old thread. Not sure if it is okay to post on it. But ditto for this. I would love to see a batch rename function built-in to Nemo that is as powerful as thunar's batch rename feature.

**Comment by alexanderdd** [comment]
Still waiting for this. 

Any comments on what @brmmm3 said?

(Yes I understand how open source development works but I can't code myself and don't know any devs).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by alexanderdd** [comment]
Looks like Gnome Nautilus has it, even metadata-based. Anyone know how to get this to Nemo?
https://www.linuxuprising.com/2019/04/how-to-enable-metadata-based-batch.html?m=1
