### ISSUE TITLE
Italian translation only - Create new Template

### ISSUE THREAD

**Issue by Timmy93** [linuxmint/nemo#1278]
I'm using Linux Mint 17.3 Cinnamon 2.8.8 (but the bug is also in Mint 18) and I think to have found a bug in templates.

I created a model in "~/Modelli" (it's italian) that should be the english "~/Templates".
A simple empty file saved as "text.txt".
Then when I press right click of mouse>Create new document>text.txt it creates me a new file called: "text.txt senza nome" (in english "Unamed text.txt").
The problem is that the only part highlighted is "text" so if I change the name in "newText" I obtain: "newText.txt senza nome".

Is it possible to solve this problem? It's not so heavy to cancel each time " senza nome" from the new file but it's of course a bit annoying.

Here is a picture of the problem.
 ![schermata del 2016-09-05 19 05 57](https://cloud.githubusercontent.com/assets/10899430/18254228/d1f848a0-739b-11e6-86f4-822ef6f0486e.png)

**Comment by itzexor** [comment]
Would "Senza nome text.txt" be incorrect grammar or look bad? If not, then I think the translation needs to be fixed. The template string needs to come after the text for that to work. Currently the string in the Italian translation is "%s senza nome" which is why it has this problem. It will only select up to the file extension which is placed where the %s is.

**Comment by itzexor** [comment]
https://translations.launchpad.net/linuxmint/latest/+pots/nemo/it/960/+translate

**Comment by Timmy93** [comment]
"Senza nome" correspond to "Untitled" in English and is perfectly correct. The problem is that a new document is:
**WHAT IS:** "name.txt senza nome"
**WHAT SHOULD BE:** "name senza nome.txt"

**Comment by Timmy93** [comment]
@itzexor I proposed in launchpad a possible solution: "Nuovo %s", that's the same of "New %s".
In this way there's no need to fix the translation. :)

**Comment by itzexor** [comment]
Alright, cool. I was looking into ways to fix the way we handle that string, but making the translation work is much cleaner.

**Comment by laltroweb** [comment]
Same here (latest mint 64bit italian).
eg > New GIMP Image.xcf senza nome

i glad to entire remove this "senza nome" and maintain just template filename.

any help to solve this s really appreciated :)

**Comment by Timmy93** [comment]
@itzexor I can confirm that also in mint 18.1 the problem is still there. I imagine that my proposal wasn't accepted.

**Comment by itzexor** [comment]
I'm not sure why it wasn't accepted. The launchpad stuff is not handled by us directly. I would try again and let them know that the %s must come at the end of the translation for this to work properly.

**Comment by itzexor** [comment]
#1464 should fix the issue in nemo by removing the translation entirely. New files will show up using the template name only.
