### ISSUE TITLE
UI: "+" sign to display more right click actions is not really obvious

### ISSUE THREAD

**Issue by donlencho** [linuxmint/nemo#1281]
I've just upgraded to Mint 18 and struggled to find how to activate more actions in the right-click menu in Nemo, like "move to..." etc. I knew they were there (or supposed they weren't removed for Cinnamon 3) but just couldn't find them. I looked in the Nemo preferences, in the plugins, wondered if there was a plugin missing, in the system preferences and finally found this link that explains the issue with pictures:
http://unix.stackexchange.com/questions/290517/right-click-menu-in-nemo-missing-create-shortcut-and-copy-move-to

I can understand the need to save space, but really, that's not very discoverable. How would anyone click there thinking it is something else than more options for the "Open" command?

To be discoverable I would propose replacing the + sign by an extra line saying "More actions" / "Less actions" to toggle them. Or put that in the preferences.

**Comment by JosephMcc** [comment]
Hovering the icon does display the text "Show more actions". We discussed different approaches to this when it was being implemented and this turned out being the nicest way.

**Comment by donlencho** [comment]
Well, I'm just saying I was looking for it and didn't find it. Maybe people not looking for it will have a better chance discovering it, ;-)

**Comment by dg1727** [comment]
@donlencho I opened forum thread https://forums.linuxmint.com/viewtopic.php?f=47&t=239580 on this.
