### ISSUE TITLE
Bring back preview for text files

### ISSUE THREAD

**Issue by donlencho** [linuxmint/nemo#1282]
As mentioned in #1089, this is no longer in Nemo because it was removed in Gnome (but the option still is in Nemo's preferences).
I liked it and wondered if it would be possible to bring it back in Nemo (after all one of Nemo's reasons of being is to provide us things Gnome removed!).
Thanks for considering it.

**Comment by JosephMcc** [comment]
I feel like I'm picking on you and closing your issues. Trust me, that isn't the intention ;)

As was noted in the other issue, this feature was removed from icon handling in GTK, which we don't control, and is really out of our hands. It didn't work properly with HiDPI even before then. The preference is now gone in git master and won't be there for Nemo 3.2. We should have removed it from 3.0 but that was an oversight on our part.

**Comment by donlencho** [comment]
Alright, no worries!
