### ISSUE TITLE
Icons disappear from other Desktops

### ISSUE THREAD

**Issue by Timmy93** [linuxmint/nemo#1283]
If I select a picture (cat.png) in the Desktop 1 and then I press space bar I can see the preview of the pic. Then if I close the preview and I move to Desktop 2 there are no icons on the desktop. (I see only the background image)

**Comment by JosephMcc** [comment]
I can reproduce this. The desktop icons can no longer be seen on any other workspace.

**Comment by feren** [comment]
I can also reproduce it by just simply switching work-spaces with the hotkey...

**Comment by cinnamoner** [comment]
@feren Maybe they've got abducted by aliens :)
