### ISSUE TITLE
Please fix the nemo bug

### ISSUE THREAD

**Issue by LinuxHax00r** [linuxmint/nemo#1285]
Nemo hast been very slowth since 2014, and I wanth thou to fix it please, the codings aren't that hard, i looked at it myself, so please make it muchet faster especially whenth doing zip files and going to a folder with hundreds of thousands of images.

Thou art thanked, by the LinuxHax00r

**Comment by feren** [comment]
Proper grammar please...

**Comment by LinuxHax00r** [comment]
My good sir, I did useth propper _GENTLEMANLY_  grammer

**Comment by JosephMcc** [comment]
I'm closing this. I'm sure everyone would like us to "make it faster". It isn't really a proper bug or feature request though. We already have numerous open issues about particular areas that could be faster or improved.

**Comment by LinuxHax00r** [comment]
@JosephMcc but all of the open reports were never fixed, so very quite obviously thou need to be reminded to FIX it ever day until it is done

**Comment by LinuxHax00r** [comment]
And if it is not fixed sooneth i will just go use a better system like ubuntu or fedora or get thy friend who does codings to fix it properly since him is probably more competent then any of you
