### ISSUE TITLE
Make the user interface tabbed like in windows

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1286]
pleaseth do this, it should be easy if you do codings properly, i looked at the coding myself

![image](https://cloud.githubusercontent.com/assets/22120090/18412699/adfeaa6a-7752-11e6-9bcc-99b860628f41.png)

**Comment by feren** [comment]
Good idea. I +1 that!
PS: This is one of the things I'd definitely do if I ever forked Nemo

Also: By good grammar on the other one I meant 'slowth' = 'slow', etc

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
