### ISSUE TITLE
Paste shortcut/symlink on desktop

### ISSUE THREAD

**Issue by kolorafa** [linuxmint/nemo#1287]
There is a common task for a lot of people to store shortcuts to a lot of directories/files from like dropbox in random places (mostly on desktop).

Yes, you can open console, or move the file with ctrl+shift, but most of the people first copy a file, and expect when clicking on desktop to "paste shortcut".

When you click on folder you have "Create symlink" but when clicking on free space inside of a folder that option doesn't exists, is it a bug? Do i need to open file manager, go to my home find desktop folder to create symlink?

I did create custom action "Create shortcut on desktop" for now, but it would be highly appreciated to be able just right click and do "Paste shortcut" especially on desktop.

**Comment by RavetcoFX** [comment]
I know it's not exactly what you're looking for, but if you drag a folder/file with the middle mouse button to the desktop, you'll get an option to link it there

**Comment by kolorafa** [comment]
When trying to move with middle button (that is impossible/hard on touchpad) it just moves the file (somehow the same as with left click), to create symlink i need to hold ctrl+shift.

When trying to move with right button it doesn't allow and opens the context menu.

But god to know there should be something like that.


OS: Arch Antergos (Cinnamon)
Nemo 3.0.6

**Comment by mtwebster** [comment]
Open the context menu, click the + button towards the end of the first entry, it'll show additional entries, including 'Make link' - you can do that then just drag it onto your desktop.

**Comment by kolorafa** [comment]
There is no + in desktop context menu.


![](http://kolorafa.firehost.pl/test/snapshot-2016-09-11-11-18-08.png)

**Comment by mtwebster** [comment]
I mean, you can right-click any item, and click Make Link.  It will make a shortcut right there in the same folder as the original item.  Then just drag the link anywhere you want (including the desktop).

**Comment by kolorafa** [comment]
True, that probably will be the way i will say to family if they ask for making shortcut on desktop.

But that just more extra steps... :(
- create shortcut
- cut
- paste desktop
- change name to oryginal

in place of
- copy
- paste shortcut

but thanks for the quick answer and workarounds!

**Comment by MrElectroNick** [comment]
Hi. Want to add +1 here as my wife just asked how she can make link to folder/file on desktop. There's no way to do that from desktop - the only option is to create launcher. There's also no such option in Nemo.
The only option is to use middle mouse button which is not present on laptops.

I believe user friendly option would be to add desktop context menu option (on right click) somewhere under "Create a new launcher here..." and open dialog to lookup a file or folder to link to desktop.

In Nemo it also make a lot of sense to add menu item with current folder set as link destination by default - this will act exactly like hit Ctrl+M->Ctrl+X->go to another folder (Desktop)->Ctrl+V

UI friendliness is really important and we know that non techie people have only access to what they see in menus. I figured out about Ctrl+M only by googling as there's no UI way to figure out that shortcut.

If this is something that coded in python and Gtk - I can personally help with that :-)

Me, my colleagues and my family will be really appreciated if such functionality will be present in Mint!

And thanks for awesome work guys!

**Comment by cruftytheclown** [comment]
+1 from me as well.  Also, I think Make Link should be visible by default without hitting + for more options.

Also, the + sign next to Open in the right click menu is not obvious at all. My expectation when seeing it is that it relates directly to and only to the Open menu item. I'm guessing that it lets me open multiple items at once, or add arguments to the opening of the file.
And when I hover over it it says "show more actions" but, still I'm thinking "Oh, more Open actions or something?"
 Instead, I think that you should have a thin menu item in the middle of the menu which looks like:  v   And when you click on the v it would animate expand that section of the menu, showing you the more actions there. Just an idea.

**Comment by monsta** [comment]
> When trying to move with middle button (that is impossible/hard on touchpad) it just moves the file (somehow the same as with left click)

It seems like the same issue with recent GTK+3 versions as we have in Caja: https://github.com/mate-desktop/caja/issues/753

**Comment by awsms** [comment]
Still not implemented?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
