### ISSUE TITLE
Right-click drag and drop + Context Menu after drop

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1289]
Basically, just like the one on Windows where if you drag and drop an item with the right-click button instead, you're given a context menu for things including 'Make Shortcut Here', 'Copy Here', 'Move Here' and 'Cancel' and it would be a nice power-user feature to have in Nemo

**Comment by ManIVIctorious** [comment]
This is already possible by holding the alt button while dropping, but honestly I would be glad if this behaviour could be made standard

**Comment by Cos-mo** [comment]
You get exactly what you want if you use the middle mouse button for dragging.

**Comment by xhsdf** [comment]
>You get exactly what you want if you use the middle mouse button for dragging.

That stopped working some time ago. At least for me.

**Comment by feren** [comment]
@ManIVIctorious Due to the Muffin Window Manager, Alt is impossible as it's used for dragging windows instead

**Comment by feren** [comment]
@Cos-mo I'm a laptop user here so it's quite hard to trigger a middle-click though

**Comment by JosephMcc** [comment]
> @ManIVIctorious Due to the Muffin Window Manager, Alt is impossible as it's used for dragging windows instead

Not exactly true. This is configurable in Cinnamon-settings->Windows->Behavior. You can set which key is used to move windows or disable it and then @ManIVIctorious suggestion works fine.

It does seem to need a cinnamon restart to take effect though, which could be improved.

**Comment by xhsdf** [comment]
Is middle-click drag still working for you guys?

**Comment by JosephMcc** [comment]
> Is middle-click drag still working for you guys?

Just tried it and it seems to be working as expected.

**Comment by xhsdf** [comment]
It's not working for me on 2 different machines. It just acts like a normal left-click drag.

**Comment by JosephMcc** [comment]
I'm pretty sure I run with all default preferences in Nemo. Do you change any of those by chance? Wonder if one of them could affect the behavior.

**Comment by xhsdf** [comment]
The only changes I made are
gsettings set org.nemo.desktop show-desktop-icons false
gsettings set org.nemo.icon-view thumbnail-size 128

**Comment by JosephMcc** [comment]
Obviously I can't drag things to the desktop with those settings but otherwise it works fine for me still.

**Comment by xhsdf** [comment]
Just did a fresh install of Nemo on a virtual machine: Still doesn't work.
I'm using Arch btw.
It was working before but stopped with an update a while ago. I thought the feature was removed.

**Comment by JosephMcc** [comment]
Middle click drag doesn't work for one of our devs who uses Arch either. It works fine under Mint. Alt + left dragging does work, you just need to press the Alt key after starting the drag.

**Comment by dg1727** [comment]
This issue seems like the 3rd bullet point in issue #1087 opened by @Translator5

**Comment by mtwebster** [comment]
The behavior mentioned in this comment: https://github.com/linuxmint/nemo/issues/1289#issuecomment-246785179

should ben fixed by  https://github.com/linuxmint/muffin/commit/2e10d8ebfa36ba5c8608740617f49755336f46cd

**Comment by xenopeek** [comment]
Disabling <alt> for window dragging in System Settings > Windows > Behavior makes it available to Nemo. Alt+drag then does the same thing as middle mouse drag; pops a move/copy/link/cancel choice menu on the drag destination.

You also have Ctrl+drag to do a copy instead of move.

Perhaps implementing #1335 is an option, letting user configure the modifier key. Or why don't we say use Shift instead of Alt?

**Comment by RobertoRDT** [comment]
Hello everybody, any news about this feature request? Is it going to be implemented in Cinnamon 4.0? and/or is there any chance that the previous behavior (middle mouse button context menu after drag and drop) is going to be restored, at least as an option? This is the main reason why I'm sticking with LM 18.3.

**Comment by monsta** [comment]
Side note: see https://gitlab.gnome.org/GNOME/gtk/issues/1512 about the middle button problem.

**Comment by RobertoRDT** [comment]
> Side note: see https://gitlab.gnome.org/GNOME/gtk/issues/1512 about the middle button problem.

That sort of makes things worse, because it means this is not an issue that can be solved in Nemo alone, is it?

**Comment by monsta** [comment]
Nope. File managers can't do much when GDK does its work like it's always the left mouse button...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
