### ISSUE TITLE
Advanced folder permissions settings: senseless triple choice

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1291]
To see the problem activate in the nemo preferences to show the the advanced permissions.

The next paragraph is only for making the issue easier to describe (for me) and to understand (for you), all described here works as expected:
Mark a file and open the properties -> permissions. You get for every permission 2 choices, which you can set: empty = permission removed and x = permission set.
Mark multiple files and do the same. You get now a third choice: slash = don't change. This 3rd choice is needed and does only make sense, if more than 1 file is selected, as they could possibly have different settings, but the user might only to change one of them.

Now to the issue, related to folders:
If you open the properties of only 1 folder selected, there are in the upper department (folder permissions) 3 choices (as described above). But there should only the 2 first described choices be available, the third one is meaningless with only 1 folder selected. Just as for files the third choice should only be available, if there are more than 1 folder selected. The third choice does confuse users.

Note: For the lower department (file permissions) this is OK as it is now, as there could of course be more than 1 file in the marked folder.

**Comment by icarter09** [comment]
@Cos-mo are you still experiencing this issue on the latest version of nemo?
