### ISSUE TITLE
Desktop Disappears When Internet Shortcut is Clicked

### ISSUE THREAD

**Issue by mountbaldy** [linuxmint/nemo#1292]
I have a laptop cart with Linux Mint 17.3 on it that is experiencing issues with disappearing shortcuts.  Whenever you click on an Internet shortcut the desktop disappears and nothing happens (IE the shortcut does not take you to the intended target, it just flat out does not work.) When this happens, ALL of the desktop icons go missing.  

I did try the `killall nemo` command and then re-run `nemo` and this does not resolve it.  I have also gone into Menus\Settings\Desktop and turned "Show desktop icons" off and then back on.  When you do this, the icons re-appear but do not work.  

I also, upgraded from a previous version to 17.3 to see if that would help and it did not.  

Any suggestions are appreciated!

Thanks!!

Joe Gill

**Comment by mountbaldy** [comment]
One note here...  The Home and Computer desktop shortcuts work, just not the Internet shortcuts.  The current browser we are using is Firefox. 

Joe

**Comment by feren** [comment]
@mountbaldy Try running 'killall nemo' again, but this time, then open a Terminal, type in 'nemo', reproduce the bug, then get the output, you may want to use the 'code' markup feature in GitHub for the output too... (If it's really big output, I'd recommend Pastebin)

**Comment by norbusan** [comment]
@feren see https://github.com/linuxmint/nemo/issues/1290 for a backtrace. I have similar problems, nemo crashing.

**Comment by mountbaldy** [comment]
@feren I'll try and do this today if I get some time today.  I do believe nemo crashed.  If memory serves me correct, when I run 'killall nemo'.  The command prompt returns something to the effect 'nemo' not found or something.  I'll get you a bug report though.

My fix for this was to delete existing internet shortcuts and re-create them.  The funny thing is that every single laptop on that cart of 30 laptops had this issue.  It's the only cart in district with Linux Mint.  So I can't speak for others.

**Comment by feren** [comment]
Ok, once you do, I'll try to invite some of the guys that know what the bug could be to this thread if I don't know what's going on it the output...

**Comment by Lukky56** [comment]
Hello I'm a french user of Linux mint and I have the same crash in the same conditions in version 18.1.
I have two screens and in the screen principal I have not the problem 90% of time.
Sorry for my poor english.

**Comment by icarter09** [comment]
@Lukky56 are you still experiencing this issue on the latest version of nemo?
