### ISSUE TITLE
Multitab - focus remains in last tab

### ISSUE THREAD

**Issue by branislav-zahradnik-gdc** [linuxmint/nemo#1294]
Nemo 3.06 (Ubuntu 16.04)

Use cases:
- window A, select file, Ctrl-X
- window B, with multiple tabs, select first tab, Ctrl-V
- result: file is moved into dir in last tab
- window with multiple tabs, select file
- switch back to first tab, select dir, right mouse button, select open in new tab
- result: application related to file is started
- change to dir, change back, select other file - doesn't help

**Comment by icarter09** [comment]
@branislav-zahradnik-gdc are you still experiencing this issue on the latest version of nemo?
