### ISSUE TITLE
Nemo only works with sudo over terminal

### ISSUE THREAD

**Issue by TheFunkyPresident** [linuxmint/nemo#1295]
I run Cinnamon 3.0.7 on Arch Linux on a ThinkPad T450s.
Unfortunately nemo only works if i start it up over the terminal with `sudo nemo`
If I Start it without `sudo`
it takes really long to come up and then is very slow and unresponsive.

**Comment by feren** [comment]
How much data is in your /home folder? (In my experience, the more data in a user, the slower things can be sometimes)

**Comment by TheFunkyPresident** [comment]
There's hardly any data in home.
Also we are not talking about minor delays. It is really extremely slow and unresponsive.

**Comment by feren** [comment]
What is the Terminal output?

**Comment by TheFunkyPresident** [comment]
When running `sudo nemo` the output is:
`(nemo:9578): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(nemo:9578): dconf-WARNING **: failed to commit changes to dconf: Fehler beim Erzeugen der Befehlszeile »dbus-launch --autolaunch=25b6c319cc904427824383e6b415dfb5 --binary-syntax --close-stderr«:Der Kindprozess wurde mit Status 1 beendet

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x23656a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x2365850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x23656a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x2365850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
^C
[paul@TP450s ~]$ ls /run/media/paul/C279-F131/ > /home/paul/output_sudo_nemo.txt 
[paul@TP450s ~]$ sudo nemo

(nemo:9704): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(nemo:9704): dconf-WARNING **: failed to commit changes to dconf: Fehler beim Erzeugen der Befehlszeile »dbus-launch --autolaunch=25b6c319cc904427824383e6b415dfb5 --binary-syntax --close-stderr«:Der Kindprozess wurde mit Status 1 beendet

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkButton 0x13f86a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkButton 0x13f8850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkButton 0x13f86a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkButton 0x13f8850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
(nemo:9578): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(nemo:9578): dconf-WARNING **: failed to commit changes to dconf: Fehler beim Erzeugen der Befehlszeile »dbus-launch --autolaunch=25b6c319cc904427824383e6b415dfb5 --binary-syntax --close-stderr«:Der Kindprozess wurde mit Status 1 beendet

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x23656a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x2365850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x23656a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkButton 0x2365850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9578): Gtk-WARNING **: Allocating size to GtkGrid 0x21ef190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
^C
[paul@TP450s ~]$ ls /run/media/paul/C279-F131/ > /home/paul/output_sudo_nemo.txt 
[paul@TP450s ~]$ sudo nemo

(nemo:9704): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(nemo:9704): dconf-WARNING **: failed to commit changes to dconf: Fehler beim Erzeugen der Befehlszeile »dbus-launch --autolaunch=25b6c319cc904427824383e6b415dfb5 --binary-syntax --close-stderr«:Der Kindprozess wurde mit Status 1 beendet

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkButton 0x13f86a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkButton 0x13f8850 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: Allocating size to GtkGrid 0x1283190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nemo:9704): Gtk-WARNING **: All`

When running `nemo`there is no output

Also I realized then running nemo as another user is also working unproblematicly.

**Comment by feren** [comment]
If it does unproblematicaly...
1. Try resetting dconf recursively for nemo `gsettings reset-recursively org.nemo`
2. Not Fixed? Try deleting .nemo, .config/nemo and .local/share/nemo from your home folder
3. Still Not Fixed? Migrate data to a new user...

**Comment by feren** [comment]
@JosephMcc You might want to add a Bug tag to this issue...

**Comment by leigh123linux** [comment]
I can't reproduce the issue in Mint or Fedora.
