### ISSUE TITLE
wishlist: add/personalize buttons

### ISSUE THREAD

**Issue by polhallen** [linuxmint/nemo#1296]
Hello,
like mate, kde, etc. is it possible add new options to add some buttons like "new tab", "new window", "delete" and other staff?

thanks for help!

Pol

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
