### ISSUE TITLE
Desktop not updating

### ISSUE THREAD

**Issue by 256shadesofgrey** [linuxmint/nemo#1297]
Every time anything happens directly on the desktop, it leaves traces. For example if I move an icon, it is still shown in it's original spot, but only as a picture, it's not clickable. Windows do not leave a trace (that shadow of a window in the screenshot is the screenshot app fading out). Doing a "killall nemo" and restarting it resets the background, but doesn't fix the issue. Same goes for switching in the desktop settings between any of the options for the desktop layout.

I'm running Debian testing with cinnamon...
nemo version: 3.0.6
cinnamon version: 3.0.7
libgtk version: 3.21.5-3

![screenshot from 2016-09-18 01-49-07-cropped](https://cloud.githubusercontent.com/assets/10959599/18612007/e72fe4d4-7d4c-11e6-8fb9-ac12b6deb506.png)

**Comment by leigh123linux** [comment]
Fixed 

https://github.com/linuxmint/nemo/commit/f20ec9beee2a3592e723f5140664e2137ab5a7be
