### ISSUE TITLE
Warning or Hint should be shown, when an external medium is not recognized or mountable

### ISSUE THREAD

**Issue by Piiit** [linuxmint/nemo#1301]
Plugging in an USB-harddrive or stick, which has a filesystem that is not supported, should trigger a HINT.
For instance, 
"Cannot mount XY, because its filesystem ABC is not supported."

...or... 

"Cannot mount XY, because its (supported) filesystem ABC is not installed yet. Do you like to install it now?" <-- maybe with a link that opens the installer with the right modules selected

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
