### ISSUE TITLE
Trash action buttons can squish sidebar

### ISSUE THREAD

**Issue by wjandrea** [linuxmint/nemo#1303]
When the Nemo window is narrow, the trash action buttons do not truncate, and do not move off the screen. This can cause the sidebar to get squished against the left side. After navigating away from the trash, the sidebar must be manually resized.

For example: I often open a Nemo window pinned to the right or left side, and I use the French translation, in which the button labels are very verbose (compare "Restaurer les éléments sélectionés" with "Restore selected items" in English, or with the much simpler "Restaurer" in the French version of Nautilus). See image 1:

![image](https://cloud.githubusercontent.com/assets/22385371/18797126/6abd7072-819a-11e6-9b83-88f22c994caa.png)

Nautilus does not suffer from this problem, even at very narrow sizes. The action buttons move off the screen. See image 2:

![image](https://cloud.githubusercontent.com/assets/22385371/18797159/97beae24-819a-11e6-9b75-913e517beccf.png)

**Comment by icarter09** [comment]
@wjandrea are you still experiencing this issue on the latest version of nemo?
