### ISSUE TITLE
"Open in terminal" always goes to HOME folder

### ISSUE THREAD

**Issue by cpitclaudel** [linuxmint/nemo#1305]
Right-clicking empty space and selecting "Open in terminal" always open my terminal in `/home/<me>/`.  How can I help debug this?

**Comment by feren** [comment]
Doesn't happen here...

**Comment by cpitclaudel** [comment]
> Doesn't happen here...

Hence my question :) Is there a way I can help debug this? I tried compiling from source to step through the code, but there are no installation instruction, and autogen.sh fails:

```
libnemo-extension/Makefile.am:74: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
autoreconf: automake failed with exit status: 1
```

> Maybe try reinstalling Nemo with your package manager?

Doesn't change anything :/

**Comment by feren** [comment]
There's some ways:
1. Terminal:
```
killall nemo
nemo
```

(then launch in Terminal again)
PS: What's your Terminal application? Mine's GNOME Terminal

**Comment by feren** [comment]
Also, try in Open As Root Nemo Mode and see if the bug persists there

**Comment by cpitclaudel** [comment]
Killing all instances of nemo and starting it from the terminal doesn't change anything.

Opening Nemo as root doesn't change anything either.

How can I compile nemo? It should be easy to step through the code in GDB and see what happens if I can just get it to compile.

**Comment by cpitclaudel** [comment]
My terminal is gnome-terminal

**Comment by cpitclaudel** [comment]
Ok, I think I know what the issue is: https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1587154

**Comment by cpitclaudel** [comment]
Indeed, confirmed that the bug is upstream.
