### ISSUE TITLE
Default editor not in context menu for menu entries

### ISSUE THREAD

**Issue by klavs** [linuxmint/nemo#1306]
Menu entries in `/usr/share/applications` get resolved in Nemo - icon visible, double-click opens the application.

Seems that the open action in context menu is now overridden by the `Exec`. To open the menu entry as a text file in default editor, you have to select "Open With" -> "Other Applications" -> "Default Application: ...".

**Comment by feren** [comment]
Affects Me Too... (Gets really annoying after a while)

**Comment by xenopeek** [comment]
> To open the menu entry as a text file in default editor, you have to select "Open With" -> "Other Applications" -> "Default Application:

I've tested this on Linux Mint 17 with Nemo 2.2.2. It works exactly the same on that as on Linux Mint 18 with Nemo 3.0.6. So this isn't something recently changed.

Perhaps this should be called tagged a bug because the default application _is_ set to Text Editor but it doesn't open with that.

**Comment by mtwebster** [comment]
This is deliberate - .desktop files are handled in a specific manner, and ignore the chosen mimetype handler.  The same holds for executable text files/scripts.  I have additional handlers that show up in the immediate `Open With` menu, but the primary/actual default is squirreled away in the default editor.

What I would probably fix is the fact that the default app is not shown in the Open with submenu (or as an additional item in the primary menu when there are only 2 associations).

**Comment by Vahan86** [comment]
@JosephMcc, issue https://github.com/linuxmint/nemo/issues/544, https://github.com/linuxmint/nemo/issues/572
