### ISSUE TITLE
Dragging to the bin often fails

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1309]
What happens: dragging to the bin often fails, such that the dragged icon ends up superimposed on the bin. Here is a picture of a particularly thorough - and thus particularly silly - superimposition:

![selection_004](https://cloud.githubusercontent.com/assets/9998846/18936604/a898ea26-85e0-11e6-88fd-d4fa7bf66852.png)

What should happen: even if the cause of the problem is that the user has not dragged to exactly the right location, the item should be moved to the bin. That is, a degree of imprecision should be built in (presuming that the lack of such tolerance is indeed the cause of the problem; perhaps it is not).

Nemo: 3.0.6+Sarah
Cinnamon 3.0.7
Linux Mint 18

**Comment by CottonEaster** [comment]
It might be worth remarking that this problem still exists on Cinnamon 3.4.6 and Nemo 3.4.7.

**Comment by RealMtwebster** [comment]
This is definatly an issue for me I will fix soon

**Comment by CottonEaster** [comment]
This problem persists in Mint 18.3, I am afraid.

```
~ $ nemo --version
nemo 3.6.4
```

**Comment by CottonEaster** [comment]
I apologise if there is some setting that fixes the problem, but this problem - which seems a fairly major user inconvenience, and something that can embarrass when showing people Mint - persists.
