### ISSUE TITLE
Preview generation decision

### ISSUE THREAD

**Issue by kaefert** [linuxmint/nemo#1311]
As already requested by another user in [this entry here](https://github.com/linuxmint/nemo/issues/1181): For most of your users there is probably no reason to want nemo to not generate thumbnails for huge movie files, since those don't need to be read in it's entire size to get a snapshot picture for a thumbnail.

But the even more pressing issue for me:
I sometimes work with huge tif files that I would very much like to prevent nemo from trying to generate thumbnails for, since it only eats huge amounts of CPU and RAM until it's killed without ever succeeding to generate a thumbnail. What's strange is that it seems to me it tries to generate these even when they are larger then the cutoff size I've selected in the preferences.

I would wish for a more fine grained configuration possibility, so that I could make nemo not thumbnail large TIFFs but still have thumbnails for huge video files.

related:
https://github.com/linuxmint/Cinnamon/issues/2703
https://github.com/linuxmint/nemo/issues/478

**Comment by kaefert** [comment]
Okey so after I reduced the limit from 4GB to 2GB and rebooted nemo no longer tries to generate a thumbnail for the 4,2GB sized TIF file I have tested with. So probably it was just the 1000 vs 1024 issue before.

But still it would be very nice if I could have thumbnails for large movies but not for large tiff files

**Comment by kaefert** [comment]
I guess this is a feature request, but it's also kind of a bug.

When you have configured nemo to generate thumbnails for files larger then such a big tiff file, it will try and never finish but simply eat a big chunk of extra RAM and 100% of one CPU core until it is killed.

**Comment by JosephMcc** [comment]
I was a bit iffy as to what to tag this one. Marked the other one as a bug, so this does make more sense now.

**Comment by Atomic0ne** [comment]
I would like to add something to this ...
It is possible to disable thumbnailing for remote locations, and it is possible to set the file size limit.
But sometimes, i want to override this, without changing the settings.
So, i would like to have a shortcut / button to force Thumbnail generation (per file, or the whole folder / selected files).

As i recognized, changing the settings for file size to a high value, it generates thumbnails, then changing back to previous value, thumbnails will be kept.
So, maybe it's a workaround to do this by a simple py-script that temporarily changes the value for "Size" back and forth !?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
