### ISSUE TITLE
Missing maximize button in gimp, when opening image file from nemo in root mode

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/nemo#1313]
Go to a folder, which has pictures in it. 
Rightclick on whitespace in this folder and press 'Open as admin/root' (<- translated from German).
Now nemo is open as root.
Open an image file with gimp. Gimp has no maximize button.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/5739
