### ISSUE TITLE
Nemo Desktop issue.

### ISSUE THREAD

**Issue by kolorafa** [linuxmint/nemo#1316]
I don't know how to describe it. When you select something or click on any file, it gets highlighted but the highlight never disapear.

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-16-22-25-42.png)

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-16-22-26-25.png)

When I move icons...

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-16-22-42-55.png)

It only happen on cinnamon desktop, inside of Nemo file manager works normally.

OS: Arch (antergos)
Cinnamon 3.0.7
nemo 3.0.6

**Comment by ManIVIctorious** [comment]
This issue should already be solved in arch linux, please try to update to nemo 3.0.6-2 package

**Comment by telmotrooper** [comment]
@ManIVIctorious Having the same issue as @kolorafa even though I'm already running 3.0.6-2.

`community/nemo 3.0.6-2 [installed]`

Note: I'm running an Arch based distro called Antergos.

Tried reinstalling nemo with `sudo pacman -S nemo` and got a few errors.

>[telmo@Telmo-PC ~]$ sudo pacman -S nemo
>warning: nemo-3.0.6-2 is up to date -- reinstalling
>resolving dependencies...
>looking for conflicting packages...
>
>Packages (1) nemo-3.0.6-2
>
>Total Installed Size:  3.57 MiB
>Net Upgrade Size:      0.00 MiB
>
>:: Proceed with installation? [Y/n] y
>(1/1) checking keys in keyring                     [######################] 100%
>(1/1) checking package integrity                   [######################] 100%
>(1/1) loading package files                        [######################] 100%
>(1/1) checking for file conflicts                  [######################] 100%
>(1/1) checking available disk space                [######################] 100%
>:: Processing package changes...
>(1/1) reinstalling nemo                            [######################] 100%
>:: Running post-transaction hooks...
>(1/4) Compiling GSettings XML schema files...
>No such key 'scroll-method' in schema 'org.cinnamon.settings-daemon.peripherals.touchpad' as >specified in override file '/usr/share/glib-2.0/schemas/90_antergos.gschema.override'; ignoring >override for this key.
>No such key 'keyboard-applet-use-flags' in schema 'org.cinnamon' as specified in override file '/>usr/share/glib-2.0/schemas/90_antergos.gschema.override'; ignoring override for this key.
>error parsing key 'overview-corner' in schema 'org.cinnamon' as specified in override file '/usr/>share/glib-2.0/schemas/90_antergos.gschema.override': 0-5:can not parse as value of type >'as'.Ignoring override for this key.
>(2/4) Updating icon theme caches...
>(3/4) Updating the desktop file MIME type cache...
>(4/4) Updating the MIME type database...

**Comment by kolorafa** [comment]
It was already in nemo-3.0.6-2

[krzysztof@asusturawa ~]$ sudo pacman -S nemo
[sudo] hasło użytkownika krzysztof: 
ostrzeżenie: nemo-3.0.6-2 jest w najnowszej wersji -- ponowne instalowanie
rozwiązywanie zależności…
szukanie sprzecznych pakietów...
błąd:  nie udało się otworzyć pliku /var/lib/pacman/local/wine-1.9.21-1/desc: Nie ma takiego pliku ani katalogu

Pakiety (1) nemo-3.0.6-2

Do zainstalowania:       3,57 MiB
Zmiana po aktualizacji:  0,00 MiB

:: Kontynuować instalację? [T/n] 
(1/1) sprawdzanie kluczy w bazie                   [######################] 100%
(1/1) sprawdzanie spójności pakietów               [######################] 100%
(1/1) wczytywanie listy plików                     [######################] 100%
(1/1) sprawdzanie konfliktów plików                [######################] 100%
(1/1) sprawdzanie dostępnego miejsca na dysku      [######################] 100%
:: Przetwarzanie zmian pakietu... 
(1/1) przeinstalowywanie nemo                      [######################] 100%
:: Uruchamianie po-transakcji...
(1/4) Compiling GSettings XML schema files...
Brak klucza „scroll-method” w schemacie „org.cinnamon.settings-daemon.peripherals.touchpad”, jak określono w pliku zastąpienia „/usr/share/glib-2.0/schemas/90_antergos.gschema.override”; ignorowanie zastąpienia dla tego klucza.
Brak klucza „keyboard-applet-use-flags” w schemacie „org.cinnamon”, jak określono w pliku zastąpienia „/usr/share/glib-2.0/schemas/90_antergos.gschema.override”; ignorowanie zastąpienia dla tego klucza.
błąd podczas przetwarzania klucza „overview-corner” w schemacie „org.cinnamon”, jak określono w pliku zastąpienia „/usr/share/glib-2.0/schemas/90_antergos.gschema.override”: 0-5:can not parse as value of type 'as'.Ignorowanie zastąpienia dla tego klucza.
(2/4) Updating icon theme caches...
(3/4) Updating the desktop file MIME type cache...
(4/4) Updating the MIME type database...
[krzysztof@asusturawa ~]$ killall nemo
[krzysztof@asusturawa ~]$ nemo

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:650:14: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:650:14: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:653:17: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:847:14: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:847:14: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:850:17: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:1238:14: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:1238:14: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:1242:17: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:2776:8: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:2776:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:2781:8: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:2781:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5700:12: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5700:12: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5721:18: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5721:18: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5823:12: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5825:16: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5825:16: Expected a string.

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5982:12: not a number

(nemo:1394): Gtk-WARNING **: Theme parsing error: gtk.css:5982:12: Expected a string.
Initializing nemo-dropbox 3.0.0
Nemo-Share-Message: Called "net usershare info" but it failed: "net usershare" zwrócił błąd 1: Can't load /etc/samba/smb.conf - run testparm to debug it


(nemo:1394): Gtk-WARNING **: Allocating size to NemoWindowPane 0x22a3300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
^C
[krzysztof@asusturawa ~]$

**Comment by telmotrooper** [comment]
Just wanted to point out that on my laptop that already had Antergos, Cinnamon and Nemo I just updated everything and the issue didn't show up, even though running nemo still shows all those warnings mentioned before.

**Comment by ase1590** [comment]
I'm also experiencing this on Antergos despite having the 3.0.6-2 version

**Comment by telmotrooper** [comment]
I'm just here to confirm that the fix suggested by @ase1590 does indeed work.

**Comment by leigh123linux** [comment]
Fixed in git

https://github.com/linuxmint/nemo/commit/4e5a1037de0dc24e44a58e239e281b4c2d5740af

**Comment by kolorafa** [comment]
Doing pacman -S community/nemo and rebooting fixed the issue for me too.
I will also try the git version over the weekend.

Thanks for the hard work.

**Comment by sebalis** [comment]
You don’t even need to reboot, or restart your session. Just kill your nemo process(es) and restart them after updating the package from community.

**Comment by ase1590** [comment]
this is now fixed by latest nemo 3.0.6-2.1 antergos package.
