### ISSUE TITLE
Suggestion to improve privacy

### ISSUE THREAD

**Issue by BrainAxe** [linuxmint/nemo#1317]
Please add a folder locking option in nemo so that users can secure secret files. Thanks.

**Comment by feren** [comment]
+1
Also, it would be cool to have a lockdown key that prevents the user seeing anything but their home folder and its contents (aka: Prevent users accessing '/')

**Comment by leigh123linux** [comment]
Nemo already has this

https://github.com/linuxmint/nemo-extensions/tree/master/nemo-seahorse

nemo also has a permissions tab in properties

@BrainAxe  locking the folder wouldn't prevent root from accessing it.

@feren  preventing users viewing / seem pointless as they only have read access, they could also view / from the terminal.
