### ISSUE TITLE
Feature request: Implement "direct saving" from XApps

### ISSUE THREAD

**Issue by jondo** [linuxmint/nemo#1319]
Quoting [a GtkFileChooser issue](https://bugzilla.gnome.org/show_bug.cgi?id=324789):

> When I work with an app that creates files I usually already have the destination directory open in a [nemo] window somewhere in the background; it would really be simpler for me to write the name (if necessary) and then drag the "handle" to the directory, rather than work my way (clickety-clickety-click) to the destination directory again :-)
> [...]
> I guess the drag-save handle could be a small icon next to the file name, with a suitable tooltip such as "drag this handle to the destination to save", to add discoverability to a function that while useful would be largely a question of habit.

If this is implemented, it probably makes sense to do it via the "XDS (Direct Save Protocol)", as mentioned in [this GTK+ issue](https://bugzilla.gnome.org/show_bug.cgi?id=321211).

I would suggest to just give the new file a default name and immediately change into filename editing mode.

From the XApps, I would especially like to have this in xed.
Of course, this could also be useful for other applications, e.g. the "save screenshot" dialog.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
