### ISSUE TITLE
Tag Next Point Release

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/nemo#1320]
@clefebvre Its been a while since nemo has had a point release tagged. If that is not intentional, could you tag one the next chance you get? Thanks :smiley:

**Comment by leigh123linux** [comment]
I think the next tag will be 3.2.0 and that will probably be in the next couple of weeks hopefully.

**Comment by lots0logs** [comment]
Damn, I was hoping we could get a point release which includes #1235. Kind of ~~need~~ *want* it soon, like yesterday soon :laughing:

**Comment by clefebvre** [comment]
We're just days away from 3.2 @lots0logs.

**Comment by leigh123linux** [comment]
3.2.x is released
