### ISSUE TITLE
Swithable transition effect while opening folder

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/nemo#1323]
Hello dear friends.

I think that it would be great to have transition effect when you click to open some folder, or return back to previous folder. Old content will gradually disappear, new will gradually appear.
If user will dislike this, he could switch it off in preferences.

It would give a feeling of comfort and modernity. 
Also it would give feeling consistency of Cinnamon's transition effects with Nemo's ones. It would seem that Nemo and Cinnamon are parts of one system.

Best regards, 
Vladislav.

**Comment by vlad1777d** [comment]
Yeah, something like this. 
It could be even something like this effects in Cinnamon:
![2016-10-24 19-18-57](https://cloud.githubusercontent.com/assets/12682937/19653911/fe892d2c-9a1e-11e6-8480-c998fdd9adda.png)

**Comment by feren** [comment]
Oh wait, almost forgot, +1

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
