### ISSUE TITLE
There should be a mouse shortcut button for Extra Pane

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/nemo#1325]
Right now I can quickly open up a second pane using a keyboard with F3 but the whole purpose of a file browser is to give you nice clicky fancy looking way of doing things, to this end I thick the fact that to open an extra pane with a mouse I need to dive into the menus, something thats easier said than done if you're using the hidden menu bar feature.

I suggest "Extra Pane" should be addable as a button right next to "Open a terminal in the active folder"

**Comment by anandrkris** [comment]
:+1: Also, should be configurable Edit > Preferences > Toolbar
I feel, the current options are limited given that it is configurable.

**Comment by anandrkris** [comment]
https://github.com/linuxmint/nemo/issues/1196
https://github.com/linuxmint/nemo/issues/1296
Linking issues related to Toggle Bar.
@mtwebster - Any chance of adding these additional options? Thanks.

**Comment by Vahan86** [comment]
@JosephMcc, Issue #1196.
