### ISSUE TITLE
Item Counter in Trash Not Updated

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/nemo#1326]
![screenshot from 2016 10 26 15 27 23](https://cloud.githubusercontent.com/assets/3285430/19743826/ec1bcdf4-9b98-11e6-84b7-7fb58dd5215a.png)

Noticed lately:
When I empty the trash, the counter at the bottom does not update.

Mint 18, Cinnamon 3.0.7

**Comment by SerafDosSantos** [comment]
Looks like it is fixed in Mint 18.1

**Comment by JosephMcc** [comment]
Can it be closed then?

**Comment by SerafDosSantos** [comment]
For me, I think so.
