### ISSUE TITLE
[Git] Conky prevents desktop handling

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/nemo#1327]
Conky prevents desktop handling.

**Steps to reproduce.**

1. add conky to autostart apps
2. log in
3. kill nemo
4. start nemo

**result**
nemo can't handle desktop as conky has claimed it

```
** (nemo:3759): WARNING **: Desktop already managed by another application, skipping desktop setup.
```

**Comment by leigh123linux** [comment]
The commit responsible is https://github.com/linuxmint/nemo/commit/9164abea248997abf3cd22c24883c938bbb8d711 , can we exclude conky from this check?

**Comment by mtwebster** [comment]
Sigh I suppose...  :)
