### ISSUE TITLE
Nemo video thumbnails upside down

### ISSUE THREAD

**Issue by darrenhopkinson** [linuxmint/nemo#1331]
Running Linux Mint 18 and using Nemo to browse videos, I find that the thubnails are always shown upside down. Playing the videos with VLC always plays them with the correct orientation (although they are upside down if played in the "Videos" application).

I can provide an example video if necessary (7.7MB) although attaching videos here is disallowed.

Note that the source of the videos is the Nexus 5x phone, which is known to use uncommon metadata for encoding photo/video orientation (see https://productforums.google.com/forum/#!topic/nexus/eGbLbf9ytS8)

**Comment by leigh123linux** [comment]
You will need to provide the file.

**Comment by darrenhopkinson** [comment]
@leigh123linux - Thanks, what's the best way for me to do that here?

**Comment by leigh123linux** [comment]
Dropbox or something similar would be good.

**Comment by darrenhopkinson** [comment]
Example video:

https://www.dropbox.com/s/y80ozgrlhuj8die/VID_20161101_105844.mp4?dl=0

**Comment by clefebvre** [comment]
The linked video is auto-rotated and shows up correctly, both in xplayer and nemo thumb after @leigh123linux 's commits.

**Comment by darrenhopkinson** [comment]
Thanks for your great work, guys. (I've just sent a bitcoin donation to the linux mint project).
