### ISSUE TITLE
Spam of nemo[571]: Allocating size to GtkGrid 0x2ea6140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate? in syslog

### ISSUE THREAD

**Issue by nathan-b** [linuxmint/nemo#1332]
Every time a Nemo window opens, I get a lot of these

```
Nov 02 13:25:54 nathanb-linux nemo[571]: Allocating size to GtkGrid 0x3258cc0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Nov 02 13:25:54 nathanb-linux nemo[571]: Allocating size to GtkButton 0x2700a40 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

This is very noisy in the log. I don't know if the right answer is to suppress the warning or work around it by calling the referenced function(s), but I think something must be done.

**Comment by itzexor** [comment]
This should be fixed in master. If you want to apply the fix manually, rebuild and patch with this
https://github.com/linuxmint/nemo/commit/2c60a3edaef10e9ef331740d55d3c45dd366c5db.patch
