### ISSUE TITLE
[Bug] Alt+Drag only works when holding Alt AFTER dragging the item

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1334]
Now I figured out how to switch the Alt+Drag combination for Muffin, when I try Alt+Drag on anything in a folder in Nemo, it doesn't work, meanwhile, if I drag it, then hold Alt, it works. That's a pretty annoying glitch in Nemo to have...

Linux Mint 18 - Sarah

**Comment by JosephMcc** [comment]
Not sure I understand. If I disable the alt key for moving windows, alt + dragging works fine in Nemo. If I enable the alt key, then then I must first start the drag and then press alt. There is really no other way for this to work. With alt enabled for window dragging it gets preference over application specific shortcuts.

**Comment by feren** [comment]
@JosephMcc Basically, I disabled it
If you try Alt+Drag on a item in the order Alt, then start dragging it, it doesn't start dragging
Meanwhile, if you hit Alt WHILE you're dragging, it works

Windows doesn't have this bug so it's most likely confusing for new users that know the hotkey

**Comment by feren** [comment]
Hang on, let me get Kazam to show you what I mean...

**Comment by feren** [comment]
@JosephMcc The first attempt is holding Alt, then dragging, then the second attempt, is dragging, then holding Alt:
https://www.dropbox.com/s/91byy6cg68p2r3m/Screencast%202016-11-04%2016%3A28%3A35.mp4

**Comment by JosephMcc** [comment]
It seems to work fine here.

**Comment by feren** [comment]
That's odd... It doesn't for sure here...

Maybe try turning off Menu from visibility? That may be the bug cause

**Comment by feren** [comment]
UPDATE: Nope, even with menus turned on, it still doesn't work as expected

**Comment by feren** [comment]
@JosephMcc I think I might know why it doesn't work with Tab before drag:
On the menu, the first letter of the names of the menu items get an underline for keyboard ease, but that might mean it's grabbing it, stopping the Alt+Drag trick from working... That could be why it isn't working...

**Comment by Timmy93** [comment]
Linux Mint 18.1

I changed the setting like you from Alt to Ctrl and now if I first press Alt and then I drag the icon I don't have any problem.
The icon is selected and, at release time, nemo asks me if I want to create the shortcut, copy or move.

**Comment by feren** [comment]
Ok, I'll close this (for now) but if I still have the problem, I'll probably reopen it...
