### ISSUE TITLE
copy/move window title updating glitch

### ISSUE THREAD

**Issue by fotoneex** [linuxmint/nemo#1337]
Noticed the following on v2.8.7 in LM 17.3. 
If you copy or move files and then start subsequent copy /move operations, they stack (coorectly). But if you "allow" one to go ahead in parallel then after that completes and the big copy / move job is again the only one running - THEN:
The (child) window title bar remains frozen: "n%  nnnn of mmmm file copied" and is no longer updated from the copy /move job in progress.
Tested this on v3.0.6 with LM 18.  I note the same behaviour except that the percentage does change correctly going forward, but the file count remains frozen.
This is just the title bar, not the data area below where everything works fine as the copy /move progresses.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1255
