### ISSUE TITLE
Bookmarks: make properties accessible and editable

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/nemo#1339]
I have a couple of Samba Network shares bookmarked. They worked fine for ages. Now they cause Nemo to hang. In the interim passwords have changed, and Nemo rightly prompts me for new login details. But then hangs. 

The hang aside, what I am frustrated by is that I cannot see the properties of these bookmarks, or edit them. That would seem to be a very useful feature. 

I don't know and can't find on-line any help as to, where these bookmarks are stored, be it on the filesystem or elsewhere and how I might inspect them and edit them to check what might be up.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
