### ISSUE TITLE
Extra Pane mode is enabled automatically after opening Nemo.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/nemo#1342]
How to reproduce the issue:
1. Open Nemo and enable Extra Pane mode.
2. Then disable Extra Pane mode and close Nemo.
3. Open Nemo again: Extra Pane mode is enabled.

Nemo 3.0.6

**Comment by JosephMcc** [comment]
On git master it's actually worse than your explanation :). Open a nemo window, F3 to set dual pane mode. Close and then re-open the window. It opens in a broken dual pane type of view. There is no separator, it doesn't actually look like dual panes. Hitting F3 again switches back to a true dual pane mode.

**Comment by Vahan86** [comment]
Checked in Nemo 3.2.2. The issue is fixed.
