### ISSUE TITLE
nemo should not display desktop window when using wayland

### ISSUE THREAD

**Issue by soloturn** [linuxmint/nemo#1343]
when logging in on command line i am starting gnome in wayland with:
   dbus-run-session -- gnome-shell --display-server --wayland
when i start nemo via the windows key, two windows open. expected, the file browser. plus, unexpected, a desktop window which i cannot close any more.

starting nemo from a terminal:
   nemo --no-desktop
then everything works like in a "gnome-session" started via startx.

**Comment by leigh123linux** [comment]
Disabling desktop icons should fix the issue for you

```
gsettings set org.nemo.desktop show-desktop-icons false
```

**Comment by soloturn** [comment]
thanks, included now here: https://wiki.archlinux.org/index.php/Wayland#Gnome

**Comment by leigh123linux** [comment]
I have tested my pull request on gnome wayland and now nemo works as expected and can draw the desktop properly.
