### ISSUE TITLE
Open and Save dialog boxes do not respect folder sorting order

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1345]
`System:    Kernel: 4.4.0-47-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7 Distro: Linux Mint 18 Sarah`

When I uncheck "Sort folders before files" checkbox in Nemo preferences so that Nemo doesn't treat folders any differently from files when sorting them, folders are still sorted and grouped together in Open and Save dialog boxes.

To test this, try to save this page, navigate to some folder that has lots of files and folders  and click on "Modified" column to sort it by modify date. Folders are grouped together.

**Comment by JosephMcc** [comment]
Open and save dialogs are provided by the toolkit that was used to create the application. In the case of your example, saving a page with Firefox, that's gtk. It has nothing at all to do with Nemo. No setting in Nemo will have any effect on them.
