### ISSUE TITLE
 Properties dialog does not indicate that size calculation is ready

### ISSUE THREAD

**Issue by davidsusu** [linuxmint/nemo#1346]
This issue was originally reported in context of nautilus, see: https://bugzilla.gnome.org/show_bug.cgi?id=764463

In the folder properties dialog there is no information about the status of the size calculation. Often, it seems like it stopped calculating, but then suddenly continues. It whould be very useful to place a progress animation next to the size field.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
