### ISSUE TITLE
Menu bar appears in Desktop

### ISSUE THREAD

**Issue by sayyaff** [linuxmint/nemo#1348]
![621d53ac-9099-11e6-8e0c-26746bc950ba](https://cloud.githubusercontent.com/assets/8475267/20656167/cf2fdfac-b54f-11e6-966c-cb9ab8ef2f61.png)

For Desktop a menu bar is created. Picture is given in above
This issue can be created by installing OS ubuntu 16.04.1 LTS, cinnamon-desktop-environment and Pantheon desktop environment

- after installing all go to cinnamon desktop environment
- logout cinnamon desktop environment
- log in with Pantheon desktop environment
- search for file their would be two file appearing open both and one of them would generate cinnamon desktop then logout Pantheon desktop environment
- log in with cinnamon desktop environment then this occurs

**Comment by leigh123linux** [comment]
Do you have nautilus installed?

http://elementaryos.stackexchange.com/questions/4091/how-to-fix-pantheon-desktop-if-i-got-this-messed-up-screen-after-i-log-in

**Comment by sayyaff** [comment]
No It's uninstalled

**Comment by sayyaff** [comment]
No I have purged it still didn't solve the problem

**Comment by JosephMcc** [comment]
I've seen other reports of similar things when mixing Cinnamon and Pantheon. It seems the two just don't play well together. I could be wrong or maybe something has changed but I didn't think Pantheon was really designed for use outside of Elementary?

**Comment by leigh123linux** [comment]
This should be fixed now the desktop process is separate.
