### ISSUE TITLE
Lost compress/extract options in context menus

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/nemo#1349]
I just upgraded to Cinnamon 3.2.1 (3.2.2 now) / nemo 3.2.0, and when I right-click on a file or folder I no longer have the compress/extract options in the context menu.

This used to work fine in Cinnamon/nemo 3.0.7.

Using Ubuntu 16.10; nemo-fileroller is installed.

**Comment by leigh123linux** [comment]
Any errors in the logging or when start it from a terminal (you have to kill the running instance), run.

```
killall nemo;nemo
```

Also check nemo plugins to see if it's active

```
gsettings get org.nemo.plugins disabled-extensions
```

If it isn't listed it'sactive

**Comment by jmgomezpoveda** [comment]
```
$ killall nemo;nemo

(nemo:18631): Gtk-WARNING **: Allocating size to NemoWindowPane 0x558f88aa3ba0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

```
$ gsettings get org.nemo.plugins disabled-extensions
@as []
```

**Comment by xenopeek** [comment]
Not reproducible on Nemo 4.6.4. Considering age of issue, closing this.
