### ISSUE TITLE
Keyboard focus moved away from Tree view in sidebar

### ISSUE THREAD

**Issue by autarkper** [linuxmint/nemo#135]
(current master)

With the Tree view open in the sidebar, navigating in the tree with the up- and down-arrow keys sometimes sets keyboard focus to the main view, away from the Tree view. That makes the Tree view very awkward to use with the keyboard.

How to reproduce:
0) Select Tree in the view selector.
1) Tab to the Tree view.
2) Use the down- and up-arrow keys to navigate from directory.

Current behavior: Keyboard focus is sometimes moved away from the Tree view to the main view.
Desired behavior: Keyboard focus should always stay in Tree view on arrow-key navigation.

I have not yet found a reliable pattern for when the keyboard focus is moved away like this.

**Comment by Vahan86** [comment]
I've checked this issue on Nemo 3.0.6.  It seems to be fixed.

@mtwebster, can we close this issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
