### ISSUE TITLE
"Recent" sidebar item does not work with Nemo 3.2.0 in Ubuntu 16.10 (GTK 3.20)

### ISSUE THREAD

**Issue by hotice** [linuxmint/nemo#1351]
In Ubuntu 16.10 (which has GTK 3.20), the "Recent" sidebar item doesn't display any recent files. When clicking it,  this is displayed: "Could not display recent:///. Error: Message recipient disconnected from message bus without replying. Please select another viewer and try again."

This occurs with Nemo 3.2.0 without any patches / modifications. It does not occur with Nemo 3.2.0 in Ubuntu 16.04 / GTK 3.18.

Let me know of any extra info you may need.

**Comment by leigh123linux** [comment]
Works fine here with gtk-3.20 or gtk-3.22

![screenshot from 2016-11-29 16-55-49](https://cloud.githubusercontent.com/assets/1299302/20719761/cedd13b6-b654-11e6-9325-1f2ca85c54a6.png)

Did you compile from source or are you using ppa?

**Comment by jnv** [comment]
There is a similar issue reported on [Launchpad](https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1633162) and it looks like an error in gvfs-daemon service. According to [this comment](https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1633162/comments/15):

> Adding "Environment=DISPLAY=:0" in the service file:
> `/usr/lib/systemd/user/gvfs-daemon.service`, solves it.

**Comment by leigh123linux** [comment]
Why is that user service running, it shouldn't be needed for cinnamon.

```
systemctl --user disable gvfs-daemon.service
```

Any way I am closing the issue as it isn't a nemo issue.

**Comment by jnv** [comment]
> Why is that user service running?, it shouldn't be needed for nemo.

Well, you use GtkRecentManager which can be backed by GVFS. Also `recent://`, `network://` and `trash://` pseudo-protocols are handled by GVFS. Even if you disable the unit, Nemo will probably spawn the daemon on its own.

Anyway, just for the reference, the solution above fixes the issue both for Nemo and Nautilus, so it is up to Ubuntu to fix the systemd unit.
