### ISSUE TITLE
Alterning grey lines

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/nemo#1352]
Hi,

I use linux mint 18 cinnamon edition and I try to get alterning grey lines in file manager (nemo) with the method decribed in:
`http://askubuntu.com/questions/285559/how-to-reenable-alternating-grey-lines-in-nautilus-files-3-6-list-view`
but it does not work. It only take the color of the odd lines. I don't know if that bug is specific to nemo or comes from GTK itself.
Cheers,

**Comment by JosephMcc** [comment]
The ability to do this was deprecated in gtk awhile back and it doesn't seem to work anymore.

**Comment by KevinNadaud** [comment]
Ok, thanks for the answer.
