### ISSUE TITLE
[Feature Request] Tick-box selection of Files and Folders in Nemo GUI

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1353]
Basically, this comment on http://blog.linuxmint.com/?p=3165 :
```
Thank you for that great OS and Desktop Envoirement. Just one thing would be realy cool: That you could tick/check folders to get them marked/elected like in Windows.
Thank you!
```

A way you could do this is using some code off of Pantheon Files, as I've seen such a feature there too...

**Comment by JosephMcc** [comment]
Maybe I'm missing something but what's the point? Selected files/folders are highlighted already so I don't see what this adds to anything outside of extra work and complication for the devs.

**Comment by ManIVIctorious** [comment]
Maybe he is talking about something like this:
https://anditosan.files.wordpress.com/2010/08/dolphinsymmetry3.png

Which would allow mouse-only selections (without pressing ctrl)

**Comment by JosephMcc** [comment]
Another very similar request: https://github.com/linuxmint/nemo/issues/934

**Comment by felipeabou** [comment]
I still hope to see this feature implemented. It's very useful.
