### ISSUE TITLE
crash when opening folder with large number of .jp2 files

### ISSUE THREAD

**Issue by skramm** [linuxmint/nemo#1357]
I have downloaded from a server a bunch (>500) of jpeg 2000 files to /tmp.
When attempting to view the content of the folder with Nemo 1.8.4 (on Ubuntu 14.04), it crashes after a second. I know there are opened issues on viewing them with Linux due to some patent problems but the case here is not about viewing, it's just about viewing the content of the folder.

When started from command line, I get:
`(nemo:10091): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(nemo:10091): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Segmentation fault (core dumped)`

Note: I can't guarantee none of the files are corrupted, as I interrupted the download. This could indeed be the source of the problem, as if I copy one (valid) file somewhere else, it doesn't crash. But a file explorer is not expected to crash if one of the files is corrupted...

BTW, this happens with Nautilus 3.10.1 too, but with a different error message on stdout:
`Nautilus-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Permission denied
You do not have permission to create a usershare. Ask your administrator to grant you permissions to create a share.
Segmentation fault (core dumped)
`

As far as I understand, this is probably due to a failure in attempting to produce a thumbnail of the file. I am not familiar with the codebase, but could'nt it be possible to **disable** the computation of thumbnails for some file types ?

References:

- [Wikipedia JPEG2000 ](https://en.wikipedia.org/wiki/JPEG_2000)
- [related bug on Launchpad about Nautilus](https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1410918)

**Comment by leigh123linux** [comment]
Fixed in 2.8.0

https://github.com/linuxmint/cinnamon-desktop/commit/f7927e9a8201761b6654955739e87b93d3695169

**Comment by skramm** [comment]
ok, thanks, I should've tried a recent version before instead of getting along with my distros default version. BTW, were can I get some help on the build process ? My problem is:
I have downloaded 3.2.1 and it requires the cinnamon desktop package (which I don't use). This seems odd to me: I thought Nemo could be used with whatever desktop.
Is this really mandatory, or can I pass some option to disable it?
If it is mandatory, is it a recent dependency ? Where can I find the most recent release number that doesn't have this dependency ?
If you don't know the answer, would you mind pointing me on some place where I can ask? Thanks.

**Comment by leigh123linux** [comment]
cinnamon-desktop package is just the shared code, all nemo versions require it to build.

**Comment by skramm** [comment]
Thanks  @leigh123linux. Ok, I tried, but,once I have installed `cinnamon-desktop`, `./configure` fails and tells me:

    configure: error: Package requirements (
	gail-3.0
	cinnamon-desktop >= 2.6.1
	libxml-2.0 >= 2.7.8
	x11
    ) were not met:
    No package 'gail-3.0' found`

But:

    $ sudo apt-get install gail-3.0
     libgail-3-0 is already the newest version.
     libgail-3-0-dbg is already the newest version.
    $ pkg-config --modversion cinnamon-desktop
    2.8.1
    $ pkg-config --modversion libxml-2.0
    2.9.1
    $ pkg-config --modversion x11
    1.6.2

Could be indeed a problem with the way libgail is installed by package manager, but can't be sure. Has no `.pc` file. And `locate libgail` gives these locations:

    /usr/lib/debug/usr/lib/x86_64-linux-gnu/libgailutil-3.so.0.0.0
    /usr/lib/x86_64-linux-gnu/libgailutil-3.so.0
    /usr/lib/x86_64-linux-gnu/libgailutil-3.so.0.0.0
    /usr/lib/x86_64-linux-gnu/libgailutil.so.18
    /usr/lib/x86_64-linux-gnu/libgailutil.so.18.0.1
    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so

You have any idea of the next steps I can take ? Don't hesitate to point me elsewhere (team forum, whatever...), I'm not familiar with local habits.

**Comment by leigh123linux** [comment]
You need the dev (headers) packages to compile code i.e libgail-3-0-dev

see the depends list

https://github.com/linuxmint/nemo/blob/master/debian/control#L5

**Comment by skramm** [comment]
Thanks. Well, I wonder if I'm going to get throught this... Anyway, I'll post my steps, in case this is useful to others.

- libgail: The package name is actually `libgail-3-dev`, available for trusty/14.04. Installed.
- I installed **all** the packages mentioned on the deps page, **except** cinnamon-l10n, that [doesn't have a candidate for trusty](http://packages.ubuntu.com/search?lang=fr&keywords=cinnamon-l10n&searchon=names). 

Starting from a fresh extracted archive (release 3.2.1):

     $ autoconf
     configure.ac:32: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
     configure.ac:34: error: possibly undefined macro: AM_MAINTAINER_MODE
     ...

It seems that this can be solved with autoreconf, according to [this SE answer](http://unix.stackexchange.com/a/18680/73337). But it exits with error:

    $ autoreconf --install
    libtoolize: putting auxiliary files in `.'.
    libtoolize: copying file `./ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
    libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
    libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
    configure.ac:40: installing './compile'
    configure.ac:48: installing './config.guess'
    configure.ac:48: installing './config.sub'
    configure.ac:32: installing './install-sh'
    configure.ac:32: installing './missing'
    cut-n-paste-code/libegg/Makefile.am: installing './depcomp'
    automake: error: cannot open < gtk-doc.make: No such file or directory
    autoreconf: automake failed with exit status: 1

I can next proceed with `autoconf`, stays silent but eventually `./configure` fails with (3 last lines):

    config.status: creating data/nemo-autorun-software.desktop.in
    config.status: creating docs/Makefile
    config.status: creating docs/reference/Makefile
    config.status: error: cannot find input file: `docs/reference/libnemo-extension/Makefile.in'

Is this related to the missing `cinnamon-l10n` package ? I'd say no, but who knows. And translation files is not an issue for me, I would assume it can be build without (but again, can't tell...)
And I do have the `gtk-doc-package` installed (has no .pc file, but `apt-get install` says it is already there)
Any hint on what to do next?

**Comment by leigh123linux** [comment]
Did you install autoconf-archive and gtk-doc-tools

**Comment by skramm** [comment]
Yep, did both, through package manager. (sorry, typo in previous post, I meant `gtk-doc-tools`, not `gtk-doc-package`)
Maybe a version problem ? But I don't know how to check that, neither of them seems to have a .pc file. And `locate` gives no result. I also checked the content of theses packages with `dpkg -L` and had a look in the files, but found nothing obvious.
