### ISSUE TITLE
 GLib-GObject-WARNING **: g_object_weak_unref: couldn't find weak ref 0x7f953c773ab0(0x227bf60)

### ISSUE THREAD

**Issue by zosy** [linuxmint/nemo#1358]
OS: centos 7.1511 x86_64  with gnome-shell 3.14.2
nemo version: 3.2.1
error:  
(nemo:7869): GLib-GObject-WARNING **: g_object_weak_unref: couldn't find weak ref 0x7f953c773ab0(0x227bf60)
(nemo:7869): GLib-GObject-WARNING **: g_object_weak_unref: couldn't find weak ref 0x7f953c773ab0(0x227bf60)
reproduce: every time close nemo it will  generate two  warnings  like that.

**Comment by mtwebster** [comment]
Can you reproduce it?  Happens where you're ______ ?

**Comment by fluisgirardi** [comment]
I disabled all plugins (I'm testing RabbitVCS plugin).  Every time that I switched from Icon/Compact view to a detailed view, this happens. The unique difference that I noted from the previous comment to now, is the message changed to (nemo:4494 => nemo:9793))

 (nemo:9793): GLib-GObject-WARNING **: 16:33:02.958: g_object_weak_unref: couldn't find weak ref 0x7f235fe9e510(0x5642c15b7030)

(nemo:9793): GLib-GObject-WARNING **: 16:33:02.959: g_object_weak_unref: couldn't find weak ref 0x7f235fe9e510(0x5642c15b7030)

On the previous comment, I changed from my home folder to a folder that was saved in detailed view, using favorites on the sidebar.

**Comment by fluisgirardi** [comment]
Maybe because I disabled all plugins, when I go from my home to a folder saved in detailed view, this message is displayed:

(nemo:10149): GLib-GObject-WARNING **: 16:39:25.091: g_object_weak_unref: couldn't find weak ref 0x7f7276bf9510(0x5616accdca30)

(nemo:10149): GLib-GObject-WARNING **: 16:39:25.091: g_object_weak_unref: couldn't find weak ref 0x7f7276bf9510(0x5616accdca30)

**Comment by fluisgirardi** [comment]
Well, I'm not able to find why the source changes ( nemo:4494 => nemo:9793 => nemo:10149 => nemo:10119 ), but all the times is when the view is changed to detailed view.

**Comment by xenopeek** [comment]
Not reproducible with Nemo 4.6.4.
