### ISSUE TITLE
Crash when deleting files

### ISSUE THREAD

**Issue by felixsanz** [linuxmint/nemo#1359]
If you press the DEL key on a file twice, the file is deleted but the second keypress is crashing nemo process.

```
** (nemo:22457): CRITICAL **: generate_initial_job_details: assertion 'files != NULL' failed
fish: “nemo” terminated by signal SIGSEGV (Address boundary error)
```

Version: nemo 3.2.0

**Comment by morton-f** [comment]
same here - DEL key pressed accidentally twice deletes file but nemo crashes. It should be "double-click", not too slow and not two fast.

```
morton@studio ~ $ dmesg |grep nemo
[  318.103898] nemo[1846]: segfault at 0 ip 00000000004ebe2d sp 00007ffefcf19a20 error 4 in nemo[400000+1c4000]
[  645.717239] nemo[2510]: segfault at 0 ip 00000000004ebe2d sp 00007ffcf76f7aa0 error 4 in nemo[400000+1c4000]
[ 1027.364208] nemo[2950]: segfault at 0 ip 00000000004ebe2d sp 00007fff48f79fa0 error 4 in nemo[400000+1c4000]
```

**Comment by JosephMcc** [comment]
Seems this was accidentally fixed while fixing another bug: https://github.com/linuxmint/nemo/commit/32e5fc880d2ec3d1de2b289e62bb4d34d518962c
