### ISSUE TITLE
odd behaviour of nemo

### ISSUE THREAD

**Issue by ferrvittorio** [linuxmint/nemo#1361]
Hi,
whenever I invoke nemo (3.2.0) it pulls up an empty desktop overlay window
I am running Arch Linux with Gnome 3 environment, Wayland
See Attached, anybody ever seen anything like that? Note lower left corner

Thanks

![schermata del 2016-12-14 08-56-46](https://cloud.githubusercontent.com/assets/22936074/21174331/d31ae2b2-c1dc-11e6-82f9-6d4cc6b051a4.png)

**Comment by leigh123linux** [comment]
Fixed in 3.2.1

https://github.com/linuxmint/nemo/commit/8242e271c733aee2b6a635a8c6bb1afb28a6c26c
