### ISSUE TITLE
Feature request: raw file viewer

### ISSUE THREAD

**Issue by markfilipak** [linuxmint/nemo#1362]
Excuse me if this is the wrong place to post this request -- I could find no place for feature requests.

I'm fairly new to Linux. As you know, it's neigh impossible to know what sort of contents a file has. A raw viewer would be very helpful as a tool for those newbies who are trying to hack the file system as a learning experience.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
