### ISSUE TITLE
[BUG] Icons overlap in the desktop 

### ISSUE THREAD

**Issue by Timmy93** [linuxmint/nemo#1364]
When an icon is released near to another one, the two overlaps and become hard to manage them.

Note1: The "keep aligned" setting ("mantieni allineate" in italian) must be turned ON.
Note2: If the previous setting is turned off and then on, the overlapped icons will be separated.

OS: Linux Mint 18.1 Cinnamon 3.2.6 64-bit - fully updated
Kernel not modified: 4.4.0-53-generic

Here is a easy graphic sample to reproduce the bug.
1) Ensure to turn on the "keep aligned" setting.
![3-crop](https://cloud.githubusercontent.com/assets/10899430/21296851/32a2f6f2-c575-11e6-8995-86f71f3caed6.jpg)
2) Move an icon next to another one.
![1-crop](https://cloud.githubusercontent.com/assets/10899430/21296849/32a1bf30-c575-11e6-8788-ebc01edf2cb7.jpg)
3) Here is the problem.
![2-crop](https://cloud.githubusercontent.com/assets/10899430/21296850/32a27c2c-c575-11e6-9b73-7a0b777e6bc5.jpg)

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/nemo/issues/316

**Comment by Timmy93** [comment]
@Vahan86 no, sorry, that's another problem. There the filename overlaps, here the whole icon, not only the name.

Previously (Mint 17.3) the problem wasn't so evident (it happened but was more hard to reproduce).

If you see more carefully, in the third image, you cannot clearly read the file name due to the overlap.

**Comment by Swiftpaw** [comment]
All we need is for the desktop to be treated in the same way that Nemo treats browsing a folder's contents inside a Nemo window, in a perfect grid.  I think users would prefer this to be the default behavior of their desktop icons, to keep them always aligned in a grid like Windows and most other desktops do, but you can have an option to turn this off (again, like in Windows).

The problem is the "Keep Aligned" option isn't satisfactory because it only keeps icons separated into columns, not BOTH columns and rows like the "Align to grid" option in Windows does, and like Nemo/Nautilus does when viewing a folder's contents inside a file browser window.

**Comment by Pival81** [comment]
This problem has been around for years, when will this be fixed?

**Comment by Timmy93** [comment]
So far is not even labeled as a bug, I really don't know what to say.

**Comment by Mint1864** [comment]
Hello:
Welcome to Cinnamon Desktop Hell ...

<rant>
This behaviour (the Cinnamon desktop behaviour) is (mis)managed by Nemo.
ie: Nemo is in charge of how the Cinnamon desktop behaves.

This is just part of a specific issue (desktop grid) that has annoyed a legion of Linux users who have requested, asked and complained for years but, alas, to no avail.

Just check for issue #108, which relates directly to the desktop grid behaviour: the first post at Github is from november 2012 but it had long been a complaint on the web

As the discussion got denser, it was actually edited. ie: entire posts deleted.

While I hold the utmost respect for those who developed Mint and are working to develop Mint further, I also understand that it is *they* who do the work and obviously set the priorities.

But in my humble opinion I think they are (at least here) missing the mark by a wide margin. 
Today, issue #108 has no asignee, no project or milestone ie: it has been ignored from the start (11/2012). 

Unless this changes, I think we cannot hold any reasonable expectation for this specific Nemo/Cinnamon issue to get fixed.
</rant>

Mint1864

**Comment by Swiftpaw** [comment]
It was originally a GNOME project, and GNOME 3 dropped having icons on the desktop entirely didn't it?  If so, this is an issue that needs to be picked up by devs who are working with desktops with icons such as Ubuntu and Mint.

The solution seems simple enough to me:

1.  Have an always sorted option that applies icon sorting sorting whenever an icon is moved or dropped onto the desktop.

2. Have the desktop be like the folder/file view pane in Nemo, just without the window borders and other panes and things.  You could even keep the side scrollbar for when your desktop got completely full with icons! X3

3. Just apply the same icon grid to the desktop as is in Nemo.

1 seems easy to implement, 2 seems harder but it might not be that hard, 3 seems like it wouldn't be too hard either.  Who knows GTK speak?? :wolf:

**Comment by JosephMcc** [comment]
You do realize that if it was "so easy" that it would be done already. It's just a matter of someone having the time and patience to get it done.

As for the assignees, milestones, etc. We have never used those so that doesn't mean anything.

**Comment by JosephMcc** [comment]
The root cause of this is the same as https://github.com/linuxmint/nemo/issues/108 so lets just keep the discussion there.

**Comment by Jitnaught** [comment]
This problem is occurring for me in the Linux Mint 18.3 beta (Cinnamon 3.6.6, Nemo 3.6.4), but only when I have the desktop Icon Size set to Smaller. If I copy files to the desktop/move files on the desktop to the same location as another file, all of them will be in the same location on the desktop, overlapping each other. If I have Icon Size set to Normal it works normally.

**Comment by leifliddy** [comment]
Experiencing the same issue. Running Fedora 27 with cinnamon 3.6.5. The icons on the right-hand side of the desktop are fine. All the icons below the 'Computer' icon the left-hand side are all overlapping each other. Changed all icon sizes to 100% and rebooted. Issue persists.

**Comment by leifliddy** [comment]
Found a solution for this issue. That is to disable 'use-desktop-grid'.
Open dconf-editor and deselect org.nemo.desktop.use-desktop-grid
or just run:
gsettings set org.nemo.desktop use-desktop-grid false

Cinnamon desktop will now revert to it's original behavior. You'll no longer see the right-click menu 'Desktop' option. Desktop icon size are now adjusted via Nemo file browser --> Edit --> Preferences --> Icon View Defaults --> Default zoom level. 

Everything is working perfect now. Wished they would have tested the grid system a bit more before they rolled it out. Caused me nothing but pain for the last couple of months.
