### ISSUE TITLE
Hang when compressing. (Apologies if this should be filed under 'file-roller', not Nemo)

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/nemo#1366]
I just tried to compress, via Nemo, a 156MB text file. The compressor seems to have hung: it's not responding to input, using no CPU, and giving no output. Image:

![image](https://cloud.githubusercontent.com/assets/9998846/21376503/784544bc-c72d-11e6-970b-41d2096cf9eb.png)

**Comment by leigh123linux** [comment]
file-roller is from ubuntu repo so file the issue at launchpad
