### ISSUE TITLE
"Copy to" and "Move to" entries briefly appear in context menu

### ISSUE THREAD

**Issue by mpetroff** [linuxmint/nemo#1367]
When right clicking on some files and directories, "Copy to" and "Move to" entries appear in the context menu after a very brief delay, are there for a very short period of time, and then disappear; this is incredibly distracting. This behavior only happens on certain files and directories, and I haven't found a clear pattern as to when it does and does not occur.

The bug appears to be related to how the `context-menus-show-all-actions` preference is processed; this behavior only happens when this preference is set to `false`. This option appears to have been removed from the preferences window last year in 6d88469c7ceccc931f2c6a6d7b0ed0d4887bacba for unclear reasons, but it can still be changed through dconf. Why was the option removed from the UI when it still exists? I find it quite useful, since it hides a number of options I never use, which would otherwise waste space.

I'm experiencing this issue with Nemo 3.2.2. I only noticed it after upgrading to Linux Mint 18.1, so I don't think it's present in Nemo 3.0; however, I can't find anything in the commits between the two releases that would have introduced this bug.

The GIF below shows the behavior, slowed down by a factor of five.
![bug](https://cloud.githubusercontent.com/assets/1450212/21412477/a259d308-c7be-11e6-8e40-d2c2b10b9e14.gif)

**Comment by JosephMcc** [comment]
This happens for me as well. It's really fast but I have noticed it.

**Comment by jstwinkles** [comment]
I've noticed the same behavior on my system as well.  Running Nemo 3.6.5 on Mint 18.3 Cinnamon.  I've sat and watched it for a while and it appears to happen at a very regular 3 second interval.  Very distracting, and it sometimes even causes me to select the wrong context menu item when all of the entries get shifted.

**Comment by xenopeek** [comment]
I can't reproduce this on Nemo 4.6.4. Also not after toggling the deprecated `/org/nemo/preferences/context-menus-show-all-actions` dconf setting.
