### ISSUE TITLE
Feature request: a confirmation for mouse drag and drop operation option

### ISSUE THREAD

**Issue by morton-f** [linuxmint/nemo#1368]
... to prevent such actions as one accidentally dragged the 'boot' directory ... somewhere and even didn't notice that .

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
