### ISSUE TITLE
[Bug] Nemo tells me to unplug partition after unmounting it (v3.2.2)

### ISSUE THREAD

**Issue by dqgls** [linuxmint/nemo#1369]
When unmounting a partition from within Nemo's sidebar, either by clicking on the unmount icon or by selecting "unmount" in the right-click menu, this desktop notification appears with that purple USB icon:

> You can now unplug [partition name]

This does not happen when unmounting a partition from right-click menu of partition's desktop icon or through "Removable drives" applet.

I've skimmed through the code a bit and it seems there's a missing `g_drive_is_media_removable` check when `nemo_application_notify_unmount_*` gets called in `nemo-places-sidebar.c`. Just a guess.

**Comment by icarter09** [comment]
@dqgls are you still experiencing this issue on the latest version of nemo?
