### ISSUE TITLE
[Bug] "Show more actions" has unstable mouse hover when icons in menus are disabled

### ISSUE THREAD

**Issue by dqgls** [linuxmint/nemo#1370]
See attached ogv file: [nemo-show-more-actions.ogv.tar.gz](https://github.com/linuxmint/nemo/files/670609/nemo-show-more-actions.ogv.tar.gz)

The problem is that the width of the right-click menu changes when you hover over the "Show more actions" button, causing the button to have an unfixed location which makes mouse hover unstable.

This happens only if you disable "Show icons in menus" option under Themes settings. On a related note, the Open icon should not be shown in the right-click menu at all when that Themes option is disabled.

**Comment by JosephMcc** [comment]
I can't reproduce the problem here. It seems to work fine.

**Comment by JosephMcc** [comment]
I can reproduce this in Nemo 3.8.5
