### ISSUE TITLE
undo menu: option for more details

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1372]
undo: what file 
not only operation(move,copy,rename) ? 
- what file (name, size)?  ,
 is it permanent?(copy↔delete)

also menu for undo history maybe did 3 actions but the 2nd action was an error 
(undo that without touching 1/3)

& keep this info how long?.

**Comment by cmrdt** [comment]
one of reasons for this was when mouse was glitchy and goes nuts
or if clumsy and accidentally drag-drop file/folder to ??? place
and dont know where it went and what happened exactly

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
