### ISSUE TITLE
[Bug] Nemo needs to prompt user to install Samba when sharing a folder instead of giving cryptic error

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1373]
Samba isn't a default package in Ubuntu or Mint, but in Ubuntu there is a hook in Nautilus to install Samba when the user tries to share a folder.  In Mint, when you try to share a folder from a clean install, you get a cryptic error about a file permission issue instead of being told to install Samba or having apt attempt to do so for you like in Ubuntu.

Please make Samba file sharing easy like in Ubuntu by including that installation hook for new users, and thanks for making Mint the most awesome! :wolf:

**Comment by two-dogs** [comment]
a bug report exists, pls update issue to include 'bug'
https://bugs.launchpad.net/linuxmint/+bug/1608061 &
https://forums.linuxmint.com/viewtopic.php?f=42&t=224391

**Comment by Swiftpaw** [comment]
Looks like a commit has been made to master to fix this issue, so if Mint 18.3 has this version upon release, it should be resolved in that.

https://github.com/linuxmint/nemo-extensions/pull/228

I've added "[Bug]" to the subject but I'm not sure how I add the Bug tag.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
