### ISSUE TITLE
Graphics effect needed when triggering an icon (single or double-clicking) - feature request

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1374]
One papercut for the Mint desktop is that it's not clear to a user if something is happening or if they double-clicked an icon fast enough to run/trigger an action.  This can lead to opening something multiple times.  If there was some kind of effect once an icon was triggered though, that would give visual feedback to the user that they properly triggered an action and there is no reason to click more.  This would help new users in their transition to Linux.

Sadly I can't find any examples of graphical icon click effects but there are a lot of nice ways you could do that to add that visual feedback.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
