### ISSUE TITLE
Possibility to add keyboard shortcut for custom nemo action

### ISSUE THREAD

**Issue by fin0** [linuxmint/nemo#1376]
How can I add an shortcut for one of my actions?

(If it can be done adding a line in ~/.gnome2/accels/nemo, then I have the additional problem that on my system this file is auto generated on every reboot, so editing something here will not help. I have Cinnamon 3.2.7 and nemo 3.2.2.)

Is this something that is not implemented yet (as my research suggests)?

**Comment by bluss** [comment]
This would be important for [Kupfer](http://kupferlauncher.github.io/) integration

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
