### ISSUE TITLE
Cant sort by "Date Created"

### ISSUE THREAD

**Issue by NeverUsedID** [linuxmint/nemo#1377]
Sometimes when you extract some archives, the date modified is in the past, so you will not find the folder with sort by "Date Modified", instead you need to sort by "Date Created". this option is missing in Nemo.

**Comment by ManIVIctorious** [comment]
The date created (birth) doesn't get recorded by all filesystems, you can check that by using the `stat <file>` command in terminal. Its sad, but I think this would have to be addressed in the kernel and therefore this issue can not be solved by the file manager.

**Comment by NeverUsedID** [comment]
Thank you to clarify this.

**Comment by ryleestatler** [comment]
If you're sorting images and videos from a camera, you use the metadata date taken. Also who cares if some filesystems don't have creation dates? the one linux runs on does.
