### ISSUE TITLE
Please rename label "Rubbish Bin" to "Trash"

### ISSUE THREAD

**Issue by ovari** [linuxmint/nemo#1380]
Linux Mint 18.1 Cinnamon 64-bit

Please rename label “Rubbish Bin” to “Trash”

![1](https://cloud.githubusercontent.com/assets/17465872/21694394/1ba13906-d3d9-11e6-821c-c915aec2ae72.png)
![2](https://cloud.githubusercontent.com/assets/17465872/21694393/1b9ebdf2-d3d9-11e6-9389-11a37e53f525.png)

Thank you

Edit by Clem: In Cinnamon/Nemo’s code there are no occurences of “Rubbish bin”, only of “Trash”. The reason you see “Rubbish bin” is because of en_GB translations: https://translations.launchpad.net/linuxmint/latest/+pots/nemo/en_GB/+translate?batch=10&show=all&search=trash and https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/en_GB/+translate?batch=10&show=all&search=trash. Now, why do you see “Trash” in a few places? I’m not sure.. looking at the code, it should be translated as Rubbish bin as well.. can you create a github issue on nemo for this?

**Comment by feren** [comment]
@clefebvre I've made an issue to save this guy/girl the job and referred to this issue as well:
https://github.com/linuxmint/nemo/issues/1381

**Comment by ovari** [comment]
Can this issue be closed as you have created a better one at #1381? Thank you
