### ISSUE TITLE
Compilation error on Ubuntu Xenial

### ISSUE THREAD

**Issue by droidzone** [linuxmint/nemo#1382]
1. While configuring, newer version of tracker installed from the package manager is not recognized:

`1097:configure:17423: $PKG_CONFIG --exists --print-errors "tracker-sparql-0.16"
1098:Package tracker-sparql-0.16 was not found in the pkg-config search path.
1099:Perhaps you should add the directory containing `tracker-sparql-0.16.pc'
1101:No package 'tracker-sparql-0.16' found
1103:configure:17440: $PKG_CONFIG --exists --print-errors "tracker-sparql-0.16"
1104:Package tracker-sparql-0.16 was not found in the pkg-config search path.
1105:Perhaps you should add the directory containing `tracker-sparql-0.16.pc'
1107:No package 'tracker-sparql-0.16' found
1110:No package 'tracker-sparql-0.16' found
1111:configure:17475: checking for TRACKER
1112:configure:17482: $PKG_CONFIG --exists --print-errors "tracker-sparql-0.14"
1113:Package tracker-sparql-0.14 was not found in the pkg-config search path.
1114:Perhaps you should add the directory containing `tracker-sparql-0.14.pc'
1116:No package 'tracker-sparql-0.14' found
1118:configure:17499: $PKG_CONFIG --exists --print-errors "tracker-sparql-0.14"
1119:Package tracker-sparql-0.14 was not found in the pkg-config search path.
1120:Perhaps you should add the directory containing `tracker-sparql-0.14.pc'
1122:No package 'tracker-sparql-0.14' found
1125:No package 'tracker-sparql-0.14' found
1126:configure:17534: checking for TRACKER
1127:configure:17541: $PKG_CONFIG --exists --print-errors "tracker-sparql-0.12"
1128:Package tracker-sparql-0.12 was not found in the pkg-config search path.
1129:Perhaps you should add the directory containing `tracker-sparql-0.12.pc'
1131:No package 'tracker-sparql-0.12' found
1133:configure:17558: $PKG_CONFIG --exists --print-errors "tracker-sparql-0.12"
1134:Package tracker-sparql-0.12 was not found in the pkg-config search path.
1135:Perhaps you should add the directory containing `tracker-sparql-0.12.pc'
1137:No package 'tracker-sparql-0.12' found
1140:No package 'tracker-sparql-0.12' found
`
Had to manually download [older packages](http://security.ubuntu.com/ubuntu/pool/universe/t/tracker/) meant for trusty. 
After that tracker was recognized, and configure proceeded normally.
2. Next, make throws an error and aborts:
`make[2]: Entering directory '/home/joel/nemo/eel'
  CC       eel-accessibility.lo
  CC       eel-art-extensions.lo
  CC       eel-canvas.lo
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
eel-canvas.c:2230:47: error: redundant redeclaration of ‘eel_canvas_accessible_init’ [-Werror=redundant-decls]
 G_DEFINE_TYPE_WITH_CODE (EelCanvasAccessible, eel_canvas_accessible, GTK_TYPE_ACCESSIBLE,
                                               ^
/usr/include/glib-2.0/gobject/gtype.h:1943:17: note: in definition of macro ‘_G_DEFINE_TYPE_EXTENDED_BEGIN’
 static void     type_name##_init              (TypeName        *self); \
                 ^
eel-canvas.c:2230:1: note: in expansion of macro ‘G_DEFINE_TYPE_WITH_CODE’
 G_DEFINE_TYPE_WITH_CODE (EelCanvasAccessible, eel_canvas_accessible, GTK_TYPE_ACCESSIBLE,
 ^
eel-canvas.c:2226:1: note: previous definition of ‘eel_canvas_accessible_init’ was here
 eel_canvas_accessible_init (EelCanvasAccessible *accessible)
 ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
eel-canvas.c:2230:47: error: redundant redeclaration of ‘eel_canvas_accessible_class_init’ [-Werror=redundant-decls]
 G_DEFINE_TYPE_WITH_CODE (EelCanvasAccessible, eel_canvas_accessible, GTK_TYPE_ACCESSIBLE,
                                               ^
/usr/include/glib-2.0/gobject/gtype.h:1944:17: note: in definition of macro ‘_G_DEFINE_TYPE_EXTENDED_BEGIN’
 static void     type_name##_class_init        (TypeName##Class *klass); \
                 ^
eel-canvas.c:2230:1: note: in expansion of macro ‘G_DEFINE_TYPE_WITH_CODE’
 G_DEFINE_TYPE_WITH_CODE (EelCanvasAccessible, eel_canvas_accessible, GTK_TYPE_ACCESSIBLE,
 ^
eel-canvas.c:2128:1: note: previous definition of ‘eel_canvas_accessible_class_init’ was here
 eel_canvas_accessible_class_init (EelCanvasAccessibleClass *klass)
 ^
eel-canvas.c: In function ‘emit_event’:
eel-canvas.c:2732:3: error: enumeration value ‘GDK_NOTHING’ not handled in switch [-Werror=switch-enum]
   switch (event->type) {
   ^
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DELETE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DESTROY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_EXPOSE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_FOCUS_CHANGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_CONFIGURE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_MAP’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_UNMAP’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_PROPERTY_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_SELECTION_CLEAR’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_SELECTION_REQUEST’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_SELECTION_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_PROXIMITY_IN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_PROXIMITY_OUT’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DRAG_ENTER’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DRAG_LEAVE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DRAG_MOTION’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DRAG_STATUS’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DROP_START’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DROP_FINISHED’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_CLIENT_EVENT’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_VISIBILITY_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_SCROLL’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_WINDOW_STATE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_SETTING’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_OWNER_CHANGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_GRAB_BROKEN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_DAMAGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_TOUCH_BEGIN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_TOUCH_UPDATE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_TOUCH_END’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_TOUCH_CANCEL’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_TOUCHPAD_SWIPE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_TOUCHPAD_PINCH’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2732:3: error: enumeration value ‘GDK_EVENT_LAST’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_NOTHING’ not handled in switch [-Werror=switch-enum]
  switch (ev.type)
  ^
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DELETE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DESTROY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_EXPOSE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_KEY_PRESS’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_KEY_RELEASE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_FOCUS_CHANGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_CONFIGURE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_MAP’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_UNMAP’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_PROPERTY_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_SELECTION_CLEAR’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_SELECTION_REQUEST’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_SELECTION_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_PROXIMITY_IN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_PROXIMITY_OUT’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DRAG_ENTER’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DRAG_LEAVE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DRAG_MOTION’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DRAG_STATUS’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DROP_START’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DROP_FINISHED’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_CLIENT_EVENT’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_VISIBILITY_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_SCROLL’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_WINDOW_STATE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_SETTING’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_OWNER_CHANGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_GRAB_BROKEN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_DAMAGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_TOUCH_BEGIN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_TOUCH_UPDATE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_TOUCH_END’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_TOUCH_CANCEL’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_TOUCHPAD_SWIPE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_TOUCHPAD_PINCH’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:2778:2: error: enumeration value ‘GDK_EVENT_LAST’ not handled in switch [-Werror=switch-enum]
eel-canvas.c: In function ‘eel_canvas_button’:
eel-canvas.c:3028:2: error: enumeration value ‘GDK_NOTHING’ not handled in switch [-Werror=switch-enum]
  switch (event->type) {
  ^
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DELETE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DESTROY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_EXPOSE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_MOTION_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_KEY_PRESS’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_KEY_RELEASE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_ENTER_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_LEAVE_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_FOCUS_CHANGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_CONFIGURE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_MAP’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_UNMAP’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_PROPERTY_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_SELECTION_CLEAR’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_SELECTION_REQUEST’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_SELECTION_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_PROXIMITY_IN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_PROXIMITY_OUT’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DRAG_ENTER’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DRAG_LEAVE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DRAG_MOTION’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DRAG_STATUS’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DROP_START’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DROP_FINISHED’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_CLIENT_EVENT’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_VISIBILITY_NOTIFY’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_SCROLL’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_WINDOW_STATE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_SETTING’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_OWNER_CHANGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_GRAB_BROKEN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_DAMAGE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_TOUCH_BEGIN’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_TOUCH_UPDATE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_TOUCH_END’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_TOUCH_CANCEL’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_TOUCHPAD_SWIPE’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_TOUCHPAD_PINCH’ not handled in switch [-Werror=switch-enum]
eel-canvas.c:3028:2: error: enumeration value ‘GDK_EVENT_LAST’ not handled in switch [-Werror=switch-enum]
eel-canvas.c: In function ‘eel_canvas_draw_background’:
eel-canvas.c:3276:2: error: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Werror=deprecated-declarations]
  gtk_style_context_get_background_color (style_context, GTK_STATE_FLAG_NORMAL, &color);
  ^
In file included from /usr/include/gtk-3.0/gtk/gtkicontheme.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtk.h:120,
                 from eel-canvas.c:70:
/usr/include/gtk-3.0/gtk/gtkstylecontext.h:1160:6: note: declared here
 void gtk_style_context_get_background_color (GtkStyleContext *context,
      ^
eel-canvas.c: In function ‘eel_canvas_set_pixels_per_unit’:
eel-canvas.c:3515:17: error: declaration of ‘allocation’ shadows a previous local [-Werror=shadow]
   GtkAllocation allocation;
                 ^
eel-canvas.c:3481:16: note: shadowed declaration is here
  GtkAllocation allocation;
                ^
cc1: all warnings being treated as errors
Makefile:780: recipe for target 'eel-canvas.lo' failed
make[2]: *** [eel-canvas.lo] Error 1
make[2]: Leaving directory '/home/joel/nemo/eel'
Makefile:524: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/joel/nemo'
Makefile:453: recipe for target 'all' failed
make: *** [all] Error 2
`
I had to suppress the error with --disable-Werror flag.
Then, make was successful, and nemo works fine.

3. It would be nice to have a list of dependencies to install while compiling, and include in the documentation. It requires:
`automake gtk-doc-tools gobject-introspection libgtk-3-dev libgail-3-dev libcinnamon-desktop-dev libxml2-dev libnotify-dev libexif-dev libexempi-dev`

in addition to the older tracker packages.

**Comment by starsep** [comment]
I had same problem with `-Werror` (Linux Mint 18.1 Cinnamon 64-bit, gcc Ubuntu 5.4.0-6ubuntu1~16.04.4).
Thanks for solution!
Obviously (but I'd like to clarify) the solution was executing `autogen.sh` with `--disable-Werror` flag.

Adding list of dependencies would certainly be useful.

**Comment by pjsanfil** [comment]
I had the same problem with warnings being treated as errors. 
For installing dependencies I just used `sudo apt build-dep nemo`   to get them all.

**Comment by JosephMcc** [comment]
A side note for those of you building on Debian based distros. `apt build-dep nemo` will install the dependencies and then you can just build using `dpkg-buildpackage`

**Comment by xenopeek** [comment]
I think this one can be closed.
