### ISSUE TITLE
Add "Use default" and "Use parent directory permissions" buttons in files properties

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1383]
Hello,

I think it could be useful to have a "Use default" button under the file's icon and an "use parent directory permissions" button on top of "last modification" (see images).

don't be jealous of my gimp skills please. 
![feature reset to default](https://cloud.githubusercontent.com/assets/10365117/21734321/1e3a39e4-d463-11e6-99d8-af4860e17c83.png)
![feature use parent dir perms](https://cloud.githubusercontent.com/assets/10365117/21734322/1e3dc4b0-d463-11e6-8aee-e8c0c6972c6e.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
