### ISSUE TITLE
root personals folders icons are buggy in the left bar

### ISSUE THREAD

**Issue by LucienPe** [linuxmint/nemo#1384]
_Importance :_ low.
**How to reproduce**
```
sudo su
nemo
```
**Note : ** Sometimes only the desktop icon is buggy. And we have a lot of nemo error:
```
# nemo
(nemo:11188): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Nemo-Share-Message: Called "net usershare info" but it failed: « net usershare » a retourné l'erreur 255 :
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Aucun fichier ou dossier de ce type (Any file or folder of this type)
Please ask your system administrator to enable user sharing.

^C
# echo $?
130
```

![root buggy icons](https://cloud.githubusercontent.com/assets/10365117/21734491/f258d5fa-d463-11e6-91a0-c0de5bdd30e7.png)

**Fix**
If nemo is launched by the root user, tell the user and exit.

**Comment by JosephMcc** [comment]
When nemo is lauched as root you get the giant red bar warning as much. I think that's sufficient.
