### ISSUE TITLE
drag from nemo drop into libreoffice should work with wayland

### ISSUE THREAD

**Issue by soloturn** [linuxmint/nemo#1386]
this happens when using arch linux, gnome wayland started manual:
https://wiki.archlinux.org/index.php/GNOME#Wayland_sessions

drag a png file from nemo into libreoffice writer does not work. the mouse pointer stays as a hand after trying.

**Comment by leigh123linux** [comment]
Sorry we don't support wayland.
Nemo file drag works fine with Xorg.

**Comment by soloturn** [comment]
btw - this:
http://superuser.com/questions/880121/how-to-get-back-to-type-ahead-search-in-nautilus

is why i use nemo :)

**Comment by leigh123linux** [comment]
I can understand why you use nemo, why would anyone choose to run wayland when it isn't as good/stable as Xorg?
