### ISSUE TITLE
drag - alt tab - drop should work with wayland

### ISSUE THREAD

**Issue by soloturn** [linuxmint/nemo#1387]
drag a file, alt-tab to another application, like nautilus (gnome) or avidemux (qt5), drop does currently not work, mouse cursor is stuck. to resolve, it is necessary to alt-tab back to nemo and press escape.

this is in gnome wayland, started manual as described in the arch linux wiki:
https://wiki.archlinux.org/index.php/GNOME#Wayland_sessions

**Comment by leigh123linux** [comment]
Sorry we don't support wayland,

**Comment by soloturn** [comment]
oh, i read that linux mint will support wayland when it stabilized a little more? i am aware that gnomes or waylands view on desktop icons and maybe others might be quite orthogonal how linux mint sees it ... does this mean mint will never support wayland?
