### ISSUE TITLE
Nemo doesnt provide a way to use list view with small icons with regular font size

### ISSUE THREAD

**Issue by simplew** [linuxmint/nemo#139]
Im used to List View in file managers, and in Nemo if i want to use that view with small icons (size 16x16) i need to choose zoom level 33%.

Now the problem is that one chooses zoom level 33% it resizes also the text, putting it too small.
Normally filemanagers allow the user to use any icon size but they keep the text size (following the defined font size), that doesnt happen in Nemo.

Of course that can depend on the developer approach, whether just resize images and text or just resize images, but Nemo does not allow the user to have List View with icons 16x16 with the font size configured in Cinnamon Settings.

**Comment by rik-shaw** [comment]
@mtwebster @clefebvre I understand this was "merged", but still with Nemo 3.0.x I don't understand how I can use list view zoom and *not* change text size, only zoom icons?  In "Icon View" the text size does NOT change with zooming (which I would desire also for "List View").

**Comment by pmo-19** [comment]
@mtwebster @clefebvre This behaviour is a real pity. Most probably the guy asking for smaller icons was using outdated display hardware. When I look at a `List View` on my new 4K HD screen the icon is almost invisible. Why is there no way to configure this behaviour ?
May be the next step taken the admins will be to remove the icons altogether in List View ?
For the moment I am using the 1.8.5 version which was not polluted by this `patch`.
