### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by icefapper** [linuxmint/nemo#1390]
It would be great if a "tagging" mechanism could be incorporated into Linux mint's file/folder manager. That way, several "tags" can be attributed to a file/folder (possibly via the properties dialog box for each file or folder).

Then, much like a "Tree view" sidebar will let the user have a high level view of the directory structure, a "Tag view" (which possibly augments other view types, rather than replace them) will let them view only the elements that have a certain tag associated with them.

Among advantages this has over the traditional "same things in a folder with a relevant name" approach is that more than a single tag can be associated with a single element.

Thank you.

**Comment by LozM** [comment]
Started reading through issues looking for someone else who had already brought this up. Very much like OS X handles tagging.

**Comment by JosephMcc** [comment]
Duplicate.
