### ISSUE TITLE
[Question] How do I stop nemo from highjacking Openbox's desktop menu?

### ISSUE THREAD

**Issue by txtsd** [linuxmint/nemo#1391]
I use Openbox, and I'm unable to use its menu by right-clicking on the desktop after I start nemo. How can I get nemo to stop interfering?

**Comment by leigh123linux** [comment]
Disable desktop icons will prevent nemo from drawing the desktop

```
gsettings set org.nemo.desktop show-desktop-icons false
```

**Comment by txtsd** [comment]
Thank you!
