### ISSUE TITLE
Estimated time to copy/move files is wildly inaccurate

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1392]
Hi all,

I'm using Nemo 3.2.2 and Cinnamon 3.2.8.

When I copy files (they're usually over 1GB+ in size) to a USB drive, Nemo's file copy dialog shows ridiculous progress bar indicator. In mere seconds after dragging a file onto the USB drive, progress bar goes from 0 to 98% and then just stands there for minutes until the file is finally copied. I don't think I've ever seen it in between those two numbers.

Why is that? Is this something specific to my install?

Thanks and let me know if I can provide more diagnostic info.

**Comment by leigh123linux** [comment]
It's a gvfs issue not nemo.
