### ISSUE TITLE
install tries to copy actions to /usr/share/nemo ignoring the autogen --prefix argument

### ISSUE THREAD

**Issue by pjsanfil** [linuxmint/nemo#1399]
make install errors in question (full output attached)
[nemo_make_install.txt](https://github.com/linuxmint/nemo/files/731235/nemo_make_install.txt)

:

make[1]: Entering directory '/home/pjsanfil/Projects/nemo/files'
find -mindepth 1 -maxdepth 1 -type d -exec cp -R {} / \;
cp: cannot create regular file '/usr/share/gtksourceview-2.0/language-specs/nemo_action.lang': Permission denied
cp: cannot create regular file '/usr/share/gtksourceview-3.0/language-specs/nemo_action.lang': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/90_new-workspace.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/91_delete-workspace.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/92_show-expo.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/add-desklets.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/change-background.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/desktop-settings.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/mount-archive.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/myaction.py': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/new-launcher.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/sample.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/actions/set-as-background.nemo_action': Permission denied
cp: cannot create regular file '/usr/share/nemo/script-info.md': Permission denied
make[1]: Leaving directory '/home/pjsanfil/Projects/nemo/files'

**Comment by xenopeek** [comment]
Nemo has uses meson for build nowadays so I think this can be closed. If this issue still affects you on Nemo 4.6.4 please open a new issue.
