### ISSUE TITLE
 Nemo Doesn't Show Icons in Sctripts Menu 

### ISSUE THREAD

**Issue by tsujan** [linuxmint/nemo#140]
First, thank you for creating Nemo. I use it with Cinnamon on Debian.

Please see this report, which I should have posted here instead of Launchpad: https://bugs.launchpad.net/linuxmint/+bug/1086982

BTW, is there any plan to add filtering, like in Nautilus-3.6 but without replacing the current search mechanism?

**Comment by mtwebster** [comment]
Fixed in current Nemo
