### ISSUE TITLE
Remove hostname from path

### ISSUE THREAD

**Issue by GillesJ** [linuxmint/nemo#1400]
Currently there are no settings for the copy behaviour of nemo.
Nemo lacks the ability to copy a file's path from the GUI without the remote host being prefixed to the path.
This is an important option for working on remote servers with nemo as a remote filebrowser.

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
