### ISSUE TITLE
join two seperate windows as single window

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/nemo#1403]
i have currently two window that they are open.in one of them, i have three tabs and the other i have one.
i want to join them like action in chrome happens.
when you drag one window, it can be replaces as a tab in another window.
i think this is a cool feature.:)

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
