### ISSUE TITLE
Right click -> Open in Terminal doesn't work in Xubuntu

### ISSUE THREAD

**Issue by VelocityRa** [linuxmint/nemo#1406]
Running on Ubuntu 16.04.1 LTS. Using XFCE with Nemo as my File Explorer instead of Thunar.

Related to https://github.com/linuxmint/nemo/issues/19#issuecomment-253618289

Running `x-terminal-emulator` in console opens up Terminix as it should.

Issue happens with both xfwm4 and Compix (doesn't really seem relevant).

I can provide any other info.

**Comment by feren** [comment]
This is because (I think) Nemo is currently only configured to launch the command `gnome-terminal`, which, of course, is not included by default in Xubuntu, the easiest workaround for now is the following command:
`sudo apt-get install gnome-terminal -y`

**Comment by VelocityRa** [comment]
Thanks, it works but it doesn't use my preferred terminal (Terminix), it just opens Terminal.

I'll look around and see if I can fix it later.

**Comment by ChrisJAllan** [comment]
Nemo uses Cinnamon's default terminal stored the gsettings key "org.cinnamon.desktop.default-applications.terminal" "exec".

To change it to Terminix without going through the Cinnamon settings thing, use
`gsettings set org.cinnamon.desktop.default-applications.terminal exec 'terminix'`

**Comment by VelocityRa** [comment]
Thank you so much, it worked! I found a similar solution online, same thing but it was for gnome so it didn't work.

**Comment by helio-frota** [comment]
@ChrisJAllan thanks!
working fine on fedora 27:
`gsettings set org.cinnamon.desktop.default-applications.terminal exec 'tilix'`

**Comment by kiksilog** [comment]
on arch linux xfce:

`gsettings set org.cinnamon.desktop.default-applications.terminal exec 'xfce4-terminal'`

**Comment by vonpupp** [comment]
I would suggest to use an OS variable like `TERMINAL` and if it is not set, then fall back to the gnome settings.

**Comment by haristjuli** [comment]
@VelocityRa so how do you solve that with Xubuntu?

**Comment by romullosousa** [comment]
funcionou pra min no Manjaro! o Nemo não estava abrindo o xfce4-terminal

**Comment by prashant-raghu** [comment]
> Nemo uses Cinnamon's default terminal stored the gsettings key "org.cinnamon.desktop.default-applications.terminal" "exec".
> 
I wanted to make hyper my default terminal and this solved the issue. Thanks a ton.
