### ISSUE TITLE
Nemo asks to execute or open non-executable files on encfs folder

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/nemo#1408]
Hi, 

I have an encrypted folder, when I try to open a file into this folder (text or other) Nemo asks to execute or open even if this file is not executable. This behavior only appears on my encrypted folder, not on other folders. If I try to execute this file in a terminal, I have a error saying this file is not executable (logically).

This bug appears on the 3.2.2 version of Nemo and I try to reproduce it on version 2.8, it is not present.

Do you have any idea to fix that ? Maybe you need more informations ?

Cheers

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. Created an encrypted volume with `encfs` then placed some files in it, both documents and some executable scripts. Nemo opens each as you would expect.
