### ISSUE TITLE
Disappearing desktop icons and grid offset

### ISSUE THREAD

**Issue by TheStarvingOne** [linuxmint/nemo#1409]
I am writing according to the fact I couldn't find a report speaking about this issue.

It happens always after I boot my system - the desktop icons are gone. They reappear after processing "killall nemo" in terminal and then running nemo again. Unfortunately they get a weird offset to the right bottom corner that made me keep trying to put my icons to the right place one time. Accidentally I've found out that changing size settings for the panel in options deletes that offset.

Besides of that if I could mention it, as it looks a little disturbing - there was a request for a little more refined desktop grid overall. What is a little sad it was mentioned around 5 years ago and isn't implemented yet. I am speaking about this report https://github.com/linuxmint/nemo/issues/108

Some info in case it is needed:
Linux Mint 18.1 64bit
Cinnamon 3.2.7
Nemo 3.2.2
Kernel 4.4.0-62-generic
Nvidia 367.57-0ubuntu0.16.04.1 driver

Intel Core 2 Quad Q8300
Nvidia GeForce GTX 670
8GB RAM
Using two screens if important

I hope I could help somehow with this report..!

Before panel settings change
![pulpit_003](https://cloud.githubusercontent.com/assets/25557438/22622855/7d88d7e8-eb47-11e6-88ad-97c75fdd1ba5.png)

After...
![pulpit_006](https://cloud.githubusercontent.com/assets/25557438/22622856/7d8a6c48-eb47-11e6-8f2b-35e0cbf6f85c.png)

**Comment by xenopeek** [comment]
Nemo desktop grid code has seen a lot of changes. If the issue happens still, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
