### ISSUE TITLE
deluge-gtk freezes when using the Open Folder function with nemo

### ISSUE THREAD

**Issue by sponix** [linuxmint/nemo#1410]
1) Linux Mint 18.1 Cinnamon 64-bit -- Cinnamon 3.2.7 -- nemo 3.2.2 Also takes place with Cinnamon 3.2.8 and nemo from the Nighly PPA. Also tried the latest stable deluge-gtk from the PPA and the issue still occurs.
2) Ran deluge-gtk, selected a torrent, and choose "Open Folder"
3) The Location of the Torrent opened in the nemo file browser, and deluge-gtk froze solid
4) Expected the torrent data location to open and deluge-gtk to continue running as normal
5) This freezes deluge-gtk every time and only a force quit or kill -9 will close it afterwards

This issue seems to be only with Cinnamon, I can do the exact same thing in Mate and it functions fine.. But if I install nemo within Mate and set it as the default file browser the freezes take place again..

![screenshot from 2017-02-04 21-42-26](https://cloud.githubusercontent.com/assets/25559127/22623509/072e6e2e-eb23-11e6-917d-a5a9410c8f2b.png)

[deluge.txt](https://github.com/linuxmint/nemo/files/752725/deluge.txt)
[strace_deluge.txt](https://github.com/linuxmint/nemo/files/752726/strace_deluge.txt)

**Comment by leigh123linux** [comment]
Please file the issue against deluge instead.

**Comment by sponix** [comment]
I will file with deluge also if you would be so kind as to point me in the correct direction.

Also, this issue is specific to the nemo file browser. The Open Folder request from within deluge works fine with other file browsers. So, I felt this was the appropriate place to start.

Thanks
