### ISSUE TITLE
Progress windows:  Show elapsed time; option for whether to close immediately

### ISSUE THREAD

**Issue by dg1727** [linuxmint/nemo#1412]
Suggestion:  Any progress box for a lengthy operation (copy, move; I don't know if there are others) should show the elapsed time.  This is so the user will get an idea of how long a similar copy may take in the future (either copying a very large group of files, or copying from/to a slow device such as a USB flash drive or a network drive).  

To make sure the user can read the **overall** elapsed time once the operation is finished, there could also be an option (e.g., in Edit > Preferences > Behavior tab, near the existing "Disable file operation queueing") similar to "Require a click on OK to dismiss file-operation windows when done."  Or maybe default the option to On and call it e.g. "Automatically close file-operation windows when done."  

Nemo 3.2.2

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
