### ISSUE TITLE
Directories open with Nautilus instead of Nemo

### ISSUE THREAD

**Issue by jjaakkol** [linuxmint/nemo#1413]
My system is Ubuntu 16.04 / Serena. 

When Nautilus and Nemo are both installed in the system, directories can be opened with Nautilus instead of Nemo (I need to support both, so I can't remove neither). When this happens the desktop icons can get duplicated, since both Nautilus and Nemo are handling them. 

This happens because the mime type inode/directory is registered to Nautilus. This can be reproduced by installing Nautilus and running command  'xdg-open file:///tmp': if it opens Nautilus instead of Nemo in a Cinnamon desktop you are affected.

If you have media auto open enabled (org.gnome.desktop.media-handling automount-open true) then plugging a USB drive starts Nautilus and desktop icons are duplicated.

This can be fixed by making Nemo the default handler for inode/directory mime type for Cinnamon sessions. Create a world readable file in world readable directory /etc/xdg/xdg-cinnamon/mimeapps.list with contents:

$ cat /etc/xdg/xdg-cinnamon/mimeapps.list 
[Default Applications]
inode/directory=nemo.desktop

[Added Associations]

This fix has the added benefit that it fixes the problem for all file managers who try to register the inode/directory mimetype. 

- Jani

**Comment by leigh123linux** [comment]
I've been setting inode/directory for a couple of years for fedora cinnamon packaging. 

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-desktop.git/tree/x-cinnamon-mimeapps.list#n75

**Comment by xenopeek** [comment]
Related to https://github.com/linuxmint/Cinnamon/issues/2532

**Comment by xenopeek** [comment]
I can't reproduce the issues on Ubuntu 20.04 LTS after installing Nemo.
