### ISSUE TITLE
Suggestion: make the workings of the permissions window clearer

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1414]
It seems to me that many a person will be baffled by the Nemo file permissions window, and that this bafflement can be eased without much ado - as follows. Insert some wording along the lines of the following (see the red text on the image; the image is from [this website](http://www.dailykos.com/story/2016/5/17/1527567/-Keep-your-nose-out-of-my-stuff-Managing-users-groups-files-and-permissions-in-Linux-Part-II).
![linux_mint_permissions_3](https://cloud.githubusercontent.com/assets/9998846/22924074/b3b6c13a-f29b-11e6-959f-1b93d9f8c85e.jpeg)

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
