### ISSUE TITLE
Reproducible segfault in nemo

### ISSUE THREAD

**Issue by zeehio** [linuxmint/nemo#1415]
This segfault is reproducible both on fully updated Linux Mint 18 and 18.1. I have tested it in two computers (one laptop, one desktop workstation).

1. Assuming you have some files or folders in the desktop
2. Click on the desktop, on any empty region
3. Type some letters that match the beginning of a file, as if you were looking for it. The typed letters appear on the bottom right of the desktop and the file is selected.
4. Erase those letters using `Backspace` so the text on the bottom right is empty
5. Press `Esc`. The text dialog disappears.
6. Press `Del`. As there is no file selected nothing should happen. However you will get a segfault.
7. Open nemo if you want the icons in the desktop to appear again.

```
segfault at 0 ip 00000000004ebe2d sp 00007ffc62653ce0 error 4 in nemo[400000+1c4000]
```

I installed `nemo-dbg` package and ran `gdb nemo`. When I reproduced the bug I got on the console:

```
Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00000000004ebe2d in job_is_local (files=0x0, destination=0x0)
    at nemo-file-operations.c:6784
6784	nemo-file-operations.c: El fitxer o directori no existeix. (File or directory not found)
(gdb) 
```
Based on the [offending line](https://github.com/linuxmint/nemo/blob/a9a3e977e9240d0f90129738905346be0ce79991/libnemo-private/nemo-file-operations.c#L6784) I believe a fix would be to check if `files == NULL` and return, before accessing `files->data`, but maybe `files` should not have been `NULL` in the first place and the patch needs to be elsewhere.

Thanks for your time and great work

**Comment by JosephMcc** [comment]
I PR'd a fix for this. Thanks for the excellent bug report. Made fixing easy.
