### ISSUE TITLE
Nemo handles viewing and changing of multiple execute-bits poorly

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1416]
Scenario

1. Select multiple potentially executable files in Nemo.
2. Right-click.
3. Find the 'allow executing' option.
4. That option will be ticked even if only one of the selected files has the bit set. 
5. Changing the option - for, as said, multiple files - does not seem to actually affect the files.

Other operating systems handle 3 and 4 better. With 3, they show a greyed tick box when some but not all files have some option enabled. (Or at least that is how Windows does it, but I am confident there is something similar on Macs.) With 4 - i.e. when a user tells the computer to set or unset an option for some group of files - the other operating systems actually . . do that.

Suggestion: make Mint, in these respects, like the other operating systems. (For - if an argument is needed - why not? What's good about the status quo here? Indeed, surely 3 is misleading and 4 is at best misleading and at worst broken.)

Thanks for your time.

Mint 18.1 Cinnamon.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
