### ISSUE TITLE
Segfault when using mounted archives

### ISSUE THREAD

**Issue by sparkchaser** [linuxmint/nemo#1419]
Running Nemo 3.0.6 under Ubuntu 16.10 (Nemo and Cinnamon 3.0.7 installed from official apt packages).

Steps to reproduce:

1. Create a .zip file (mine has ten 1KB text files with randomly-generated contents)
2. Open a Nemo window and browse to the location of the zipfile
3. Mount the zipfile using right-click -> Mount Archive command.
4. Zipfile will show up as a new device on the left-hand column.  Right-click on the zipfile's device to get a context menu.
5. Context menu appears.  Click elsewhere in the Nemo window to dismiss the context menu.
6. Right-click the zipfile's device once again.
7. Nemo will hang for a second, then die with a segfault.

This seems to be the easiest way to reproduce.  The crash has occurred on step 5 on a few occasions.  The crash can also occur if you try to click a command like "unmount" or "properties" in the context menu on step 5 (the selected operation appears to work despite the crash).  In all of these cases, the debug messages are similar.

Left-clicking on the zipfile's device and browsing the contents that way works fine.  Unmounting the zipfile by right-clicking on the corresponding desktop icon also works fine (my desktop is handled by Nemo).  I can also do whatever I want using the right-click menu on anything _other than_ mounted archives without problems.  This seems to be isolated to using the right-click menu on a mounted archive inside a Nemo window.

I'm attaching a log of the information I was able to get from the debugger (using gtk/glib debug symbols).  If there's anything I can do to gather additional debug information, please let me know.

[nemo_debug.txt](https://github.com/linuxmint/nemo/files/781164/nemo_debug.txt)

**Comment by zeehio** [comment]
I can't reproduce it on Nemo 3.2.2 on Linux Mint 18.1.
I tried it 3 times. I'm not sure if that is enough...

**Comment by JosephMcc** [comment]
I can't reproduce this on git master either.

**Comment by sparkchaser** [comment]
I just compiled a fresh version from git master, and I can still see the problem.

[nemo_debug2.txt](https://github.com/linuxmint/nemo/files/784114/nemo_debug2.txt)

I also observed that step 6 in my original description is unnecessary.  The segfault happens after the context menu is dismissed, no additional action is required.

**Comment by xenopeek** [comment]
I tried to reproduce this on Linux Mint 18.3 Cinnamon 64-bit with Nemo 3.6.5. I used the exact same steps and no segfault happens. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo. Include a stacktrace.
