### ISSUE TITLE
Alternate tree-view behaviour as an option

### ISSUE THREAD

**Issue by BinaryFu** [linuxmint/nemo#142]
It would be nice to have optional alternate behavior for the tree-view, so that when you single-click on the folder the tree expands (as it does currently when clicking the expand arrow or double-clicking the name) and at the same time the click triggers the collapse of the tree at other levels. 

This would give the tree-view browsing a nice flow to it as it reduces the need for constantly double clicking (or carefully aiming at the small expansion arrow) and then manually closing multiple undesired expanded views of the tree hierarchy.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
