### ISSUE TITLE
Nemo segfault, error 4 in libgtk-3.so

### ISSUE THREAD

**Issue by FabioLolix** [linuxmint/nemo#1420]
I'm using Manjaro Cinnamon on 2 pc, one on stable update and the other on testing update
Sometime Nemo crash unexpectedly
Nemo v 3.2.2
Cinnamon v 3.2.8

> feb 19 16:16:56 fabio-asus kernel: nemo[1183]: segfault at ff10030054 ip 00007fe5ddd9f21b sp 00007ffee7b27a10 error 4 in libgtk-3.so.0.2200.8[7fe5dda1a000+6fa000]
> feb 19 16:16:56 fabio-asus systemd[1]: Created slice system-systemd\x2dcoredump.slice.
> feb 19 16:16:56 fabio-asus systemd[1]: Started Process Core Dump (PID 11842/UID 0).
> feb 19 16:16:58 fabio-asus systemd-coredump[11843]: Process 1183 (nemo) of user 1001 dumped core.
>                                                     
>                                                     Stack trace of thread 1183:
>                                                     #0  0x00007fe5ddd9f21b gtk_widget_hide (libgtk-3.so.0)
>                                                     #1  0x00000000004b0e09 n/a (nemo)
>                                                     #2  0x000000000049fa58 n/a (nemo)
>                                                     #3  0x00000000004da0c5 n/a (nemo)
>                                                     #4  0x00007fe5dbe9043a g_main_context_dispatch (libglib-2.0.so.0)
>                                                     #5  0x00007fe5dbe907f0 n/a (libglib-2.0.so.0)
>                                                     #6  0x00007fe5dbe9089c g_main_context_iteration (libglib-2.0.so.0)
>                                                     #7  0x00007fe5dc44a54d g_application_run (libgio-2.0.so.0)
>                                                     #8  0x00000000004306e9 n/a (nemo)
>                                                     #9  0x00007fe5daf9b291 __libc_start_main (libc.so.6)
>                                                     #10 0x000000000043074a n/a (nemo)
>                                                     
>                                                     Stack trace of thread 1185:
>                                                     #0  0x00007fe5db05a48d poll (libc.so.6)
>                                                     #1  0x00007fe5dbe90786 n/a (libglib-2.0.so.0)
>                                                     #2  0x00007fe5dbe9089c g_main_context_iteration (libglib-2.0.so.0)
>                                                     #3  0x00007fe5dbe908e1 n/a (libglib-2.0.so.0)
>                                                     #4  0x00007fe5dbeb80d5 n/a (libglib-2.0.so.0)
>                                                     #5  0x00007fe5db320454 start_thread (libpthread.so.0)
>                                                     #6  0x00007fe5db0637df __clone (libc.so.6)
>                                                     
>                                                     Stack trace of thread 11827:
>                                                     #0  0x00007fe5db05ef19 syscall (libc.so.6)
>                                                     #1  0x00007fe5dbed603a g_cond_wait_until (libglib-2.0.so.0)
>                                                     #2  0x00007fe5dbe64e89 n/a (libglib-2.0.so.0)
>                                                     #3  0x00007fe5dbeb8aa6 n/a (libglib-2.0.so.0)
>                                                     #4  0x00007fe5dbeb80d5 n/a (libglib-2.0.so.0)
>                                                     #5  0x00007fe5db320454 start_thread (libpthread.so.0)
>                                                     #6  0x00007fe5db0637df __clone (libc.so.6)
>                                                     
>                                                     Stack trace of thread 1206:
>                                                     #0  0x00007fe5db05a48d poll (libc.so.6)
>                                                     #1  0x00007fe5dbe90786 n/a (libglib-2.0.so.0)
>                                                     #2  0x00007fe5dbe9089c g_main_context_iteration (libglib-2.0.so.0)
>                                                     #3  0x00007fe5d0f474bd n/a (libdconfsettings.so)
>                                                     #4  0x00007fe5dbeb80d5 n/a (libglib-2.0.so.0)
>                                                     #5  0x00007fe5db320454 start_thread (libpthread.so.0)
>                                                     #6  0x00007fe5db0637df __clone (libc.so.6)
>                                                     
>                                                     Stack trace of thread 1186:
>                                                     #0  0x00007fe5db05a48d poll (libc.so.6)
>                                                     #1  0x00007fe5dbe90786 n/a (libglib-2.0.so.0)
>                                                     #2  0x00007fe5dbe90b12 g_main_loop_run (libglib-2.0.so.0)
>                                                     #3  0x00007fe5dc476316 n/a (libgio-2.0.so.0)
>                                                     #4  0x00007fe5dbeb80d5 n/a (libglib-2.0.so.0)
>                                                     #5  0x00007fe5db320454 start_thread (libpthread.so.0)
>                                                     #6  0x00007fe5db0637df __clone (libc.so.6)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1227
