### ISSUE TITLE
Add "Paste into Folder" to right-click menu of tab

### ISSUE THREAD

**Issue by dg1727** [linuxmint/nemo#1423]
Suggestion:  If file(s) are available to be pasted (they've been cut or copied), the menu that opens on right-clicking a tab should have a "Paste into Folder" option, as is done for folder icons.  

Currently, the right-click menu has only New Tab, Move Tab Left/Right, and Close Tab options.  

Nemo 3.2.2

**Comment by jony0008** [comment]
I agree, It would speed up moving files a lot, if you could select files and by the right-click menu create new folder and the files would then automatically be moved into the new folder.

**Comment by NikoKrause** [comment]
I'm not sure what this request is about. If you have copied/cut files, you can right click and just hit `paste` to copy/move them.

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
