### ISSUE TITLE
Sometimes a rapid left-then-right-click is treated as a double-click

### ISSUE THREAD

**Issue by dg1727** [linuxmint/nemo#1424]
To reproduce this issue:  

1.  Have 2 tabs open in a window (they can be showing the same folder).  The active tab should contain a file that does something recognizable when double-clicked (probably almost any file or folder is like this).  
2.  Right-click the inactive tab (this opens a menu), then click in the main file-view area of the window to dismiss that menu.  
3.  Rapidly left-then-right-click the file mentioned in step 1.  The user may do this to bring up the usual right-click context menu.  Issue:  Nemo acts instead as though the file had been double-clicked.  

Nemo 3.2.2

**Comment by afdsgsg** [comment]
@JosephMcc This is not a feature request? This looks like a bug report, regardless of whether it is valid or not.

**Comment by JosephMcc** [comment]
Fair enough. I'll change it.

**Comment by xenopeek** [comment]
This is not a bug but standard behavior. Left+right click emulates middle click on Linux. You must have been clicking so fast that you triggered the middle click emulation.

Middle click in Nemo is configured to open selected directory in a new tab (just Firefox does for middle clicking links) and open selected file with default program.
