### ISSUE TITLE
Right-click menu option to copy filename to clipboard

### ISSUE THREAD

**Issue by dg1727** [linuxmint/nemo#1427]
Currently, if you right-click a file, the options include "Cut" and "Copy."  If you choose, say, "Copy" and then paste into a text editor, you get the full path & filename as plain text.  

Feature request:  Add right-click menu options like "Copy Filename.ext" and "Copy File Basename".  Or if that's deemed too complex for many users, then just "Copy Filename" which includes the extension.  

Seemingly half-a-dozen times a day I use the workaround of starting to rename the file, then choosing Copy (to clipboard) in the resulting text-editing field.  This doesn't work as well in read-only folders, though, which don't allow files to be renamed.  In those cases I open a text editor to paste the full path & filename into after "copying" the file (see first paragraph).  

I assume the suggested feature could be done in a custom action, but even then it should probably be integrated into Nemo eventually, since this feature is so useful.  Like the "Duplicate" right-click menu option which was added since my previous version of Nemo, and which I also use seemingly several times a day.  

I'm using Nemo 3.2.2

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
