### ISSUE TITLE
Invisible bookmark

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1428]
![image](https://cloud.githubusercontent.com/assets/9998846/23291442/79314294-fa50-11e6-928e-b99c7ee53593.png)

In the inserted image, I am edited a bookmark that I have added recently - but which, as you can see, doesn't appear in the bookmarks sidebar (unless I am missing something, in which case I apologise).

Miny 18.1 Cinnamon

**Comment by xenopeek** [comment]
Documents, Downloads, Music, Pictures and Videos are standard bookmarks displayed under My Computer (which you have folded in your screenshot). If you want them to be displayed under Bookmarks, drag the bookmark you from its current place on the left sidebar to where you want it on the left sidebar.
