### ISSUE TITLE
Gap in Trash between the "Empty Trash" box and the top

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/nemo#1430]
Like seen in the picture there's a gap:
![screenshot-area-2017-02-26-130804](https://cloud.githubusercontent.com/assets/8415124/23339618/d810d6b2-fc26-11e6-84ae-6e73e4f65dc5.png)

**Comment by JosephMcc** [comment]
Yeah, I noticed that.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/commit/c5e554c66cf2080499ae60101779e09cdf8c2244
