### ISSUE TITLE
Screen does not lock while right-click menu is open

### ISSUE THREAD

**Issue by igordashaar** [linuxmint/nemo#1433]
While the right-click menu is open (either on the desktop or within a nemo window) my Lenovo Thinkpad with Linux Mint 18.1 cinnamon 64bit will not lock its screen. This is reproducible on my machine when closing the laptop and also when pressing ctrl+alt+L.

Reproducing:
1. Right-Click on the Desktop
2. EITHER close the Laptop OR press ctrl+alt+L 
after that the Laptop is still unlocked (no need to enter login password) 

This works always.

**Comment by feren** [comment]
I can confirm the same thing using Vivaldi's Vivaldi button menu

**Comment by JosephMcc** [comment]
This has nothing to do with Nemo. See https://github.com/linuxmint/cinnamon-screensaver/issues/93
