### ISSUE TITLE
Nemo crashes if a filename in the trash contains a percent sign

### ISSUE THREAD

**Issue by wjandrea** [linuxmint/nemo#1434]
I created a file named `file%name`, then moved it to the trash. When I opened the trash in Nemo, it crashed. Nautilus does not have this bug.

Nemo version 1.8.4
Ubuntu version 14.04.5

**Comment by JosephMcc** [comment]
I just tried this on git master and couldn't reproduce it. The version of Nemo you are using is quite old at this point.
