### ISSUE TITLE
Thumbnails of files more than 8 gigabytes.

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/nemo#1439]
Please make thumbnails of video files larger than 8 gigabytes. Up to 8 gigabytes of the file's thumbnail looks like a frame from the video. More than 8-just the icon of the video file. Now there are a lot of videos of the size of the bark more than 10, 12, 20 gigabytes, and all of them are displayed as icons of the video file. It's not beautiful.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/nemo/issues/1181
