### ISSUE TITLE
After updating LibreOffice displaying login screen.

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/nemo#1440]
After updating LibreOffice from their official repository to the new version, when you log in, the login screen is displayed. In the settings, auto-login is enabled. It can not be disconnected in any way, it is displayed for 30 seconds.
Linux Mint 18.1 Cinnamon.

**Comment by leigh123linux** [comment]
File your issue against LibreOffice or fully explain your issue, also nemo is just a file manager and has nothing to do with login!
