### ISSUE TITLE
FEATURE REQUEST -  select multiple files via mouse

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#1441]
in Thunar,  it is possible to click into the empty space behind the Type or Date Modified Column to draw an rectangle to select multiple files. I would like to have this functionality in nemo as well.

![ezgif-1-744353e99c](https://cloud.githubusercontent.com/assets/8189198/23832581/82704b4a-0737-11e7-930f-b9003d8e26cf.gif)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/416
