### ISSUE TITLE
Ability to remove 'Desktop' link in Sidebar

### ISSUE THREAD

**Issue by atomi** [linuxmint/nemo#1442]
All other links I can remove except 'Desktop', I'd like to just have just:

- Home
- File System
- Trash

Under 'My Computer'

**Comment by nazar-pc** [comment]
For me Desktop link disappears if Nemo is not managing desktop (sorry for confusion here), namely, when in dconf `/org/nemo/desktop/show-desktop-icons` is `false`.

**Comment by atomi** [comment]
Yes! That works thanks @nazar-pc
