### ISSUE TITLE
[Feature request] Add NFS to Connect to Server...

### ISSUE THREAD

**Issue by mxa** [linuxmint/nemo#1443]
Currently I can use Nemo to connect to the following servers: SSH, FTP (with login), public FTP, Windows share, WebDAV (HTTP), Secure WebDAV (HTTPS). Strangely absent is NFS.

**Comment by charsi** [comment]
+1 I'd like this feature as well. Quite strange that there is an option for windows share built in but not NFS

**Comment by xenopeek** [comment]
libnfs could be used to add NFS support to gvfs (https://mail.gnome.org/archives/gvfs-list/2015-March/msg00000.html). The correct version is available on upcoming package bases. The protocol would need to added to the hardcoded lists in nemo-connect-server-dialog.c.

A workaround for users that need NFS support now: https://askubuntu.com/a/751278

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
