### ISSUE TITLE
Nemo displays an extra hard drive which doesn't make any sense

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/nemo#1444]
Open Computer, besides a hard drive named "File System" you will also see another hard drive with its model name. Nemo has displayed this for years. This doesn't seem to serve to any useful function, so I think it makes sense to hide it from the user. It only causes confusion.
![screenshot from 2017-03-19 01 20 19](https://cloud.githubusercontent.com/assets/13224708/24076182/e58a88b0-0c43-11e7-951d-e21ea8a6836c.png)

**Comment by GoCyberEd** [comment]
I do not see this on my system with Nemo 3.0.6

**Comment by NikoKrause** [comment]
I don't see it either. Can you create a screenshot of your partitions in `gparted`?

**Comment by xenopeek** [comment]
No response to request for more information. Closing.

**Comment by chaeya** [comment]
I am using nemo 3.8.6+tara in mint 19 and i have same issue. is it fixed?
