### ISSUE TITLE
SIGSEGV in nemo_file_can_set_permissions (file=file@entry=0x0) at nemo-file.c:5084

### ISSUE THREAD

**Issue by fhimpe** [linuxmint/nemo#1445]
I encountered this crash on Debian Stretch AMD64:

Package: nemo
Version: 3.2.2-3
Severity: normal

nemo crashes when double clicking on a desktop icon which is a link to a website.

The desktop file is named "Treasures of ancient Rome | kijk online | canvas.be.desktop" and contains this:
[Desktop Entry]
Encoding=UTF-8
Name=Koppeling naar Treasures of ancient Rome | kijk online | canvas.be
Type=Link
URL=https://www.canvas.be/video/treasures-of-ancient-rome
Icon=text-html

This is the backtrace of the crash when double clicking this icon on the desktop:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  nemo_file_can_set_permissions (file=file@entry=0x0) at nemo-file.c:5084
5084    nemo-file.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8268c7ea80 (LWP 15386))]
(gdb) thread apply all bt

Thread 5 (Thread 0x7f825cbab700 (LWP 15390)):
#0  0x00007f8264cb454d in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8265aeb9f6 in g_main_context_poll (priority=<optimized out>, n_fds=6, fds=0x7f8250005c00, timeout=<optimized out>, context=0x55fc0efe7cc0) at ././glib/gmain.c:4228
#2  0x00007f8265aeb9f6 in g_main_context_iterate (context=0x55fc0efe7cc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3924
#3  0x00007f8265aebd82 in g_main_loop_run (loop=0x55fc0efe7c50) at ././glib/gmain.c:4125
#4  0x00007f82660d3636 in gdbus_shared_thread_func (user_data=0x55fc0efe7c90) at ././gio/gdbusprivate.c:247
#5  0x00007f8265b133d5 in g_thread_proxy (data=0x55fc0ef80590) at ././glib/gthread.c:784
#6  0x00007f8264f7a424 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f8264cbd9bf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f825d3ac700 (LWP 15389)):
#0  0x00007f8264cb454d in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8265aeb9f6 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7f82580008c0, timeout=<optimized out>, context=0x55fc0efddbd0) at ././glib/gmain.c:4228
#2  0x00007f8265aeb9f6 in g_main_context_iterate (context=context@entry=0x55fc0efddbd0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3924
#3  0x00007f8265aebb0c in g_main_context_iteration (context=0x55fc0efddbd0, may_block=may_block@entry=1) at ././glib/gmain.c:3990
#4  0x00007f8265aebb51 in glib_worker_main (data=<optimized out>) at ././glib/gmain.c:5783
#5  0x00007f8265b133d5 in g_thread_proxy (data=0x55fc0ef80540) at ././glib/gthread.c:784
#6  0x00007f8264f7a424 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f8264cbd9bf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f82577fe700 (LWP 15392)):
#0  0x00007f8264cb454d in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8265aeb9f6 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7f82440010c0, timeout=<optimized out>, context=0x55fc0f005cf0) at ././glib/gmain.c:4228
#2  0x00007f8265aeb9f6 in g_main_context_iterate (context=context@entry=0x55fc0f005cf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3924
#3  0x00007f8265aebb0c in g_main_context_iteration (context=0x55fc0f005cf0, may_block=1) at ././glib/gmain.c:3990
#4  0x00007f825c15e46d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#5  0x00007f8265b133d5 in g_thread_proxy (data=0x55fc0f001f70) at ././glib/gthread.c:784
#6  0x00007f8264f7a424 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f8264cbd9bf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f82562e4700 (LWP 19697)):
#0  0x00007f8264cb90f9 in syscall () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8265b3134a in g_cond_wait_until (cond=cond@entry=0x55fc0efdda98, mutex=mutex@entry=0x55fc0efdda90, end_time=end_time@entry=9455503609) at ././glib/gthread-posix.c:1442
#2  0x00007f8265abfe89 in g_async_queue_pop_intern_unlocked (queue=0x55fc0efdda90, wait=wait@entry=1, end_time=9455503609)
    at ././glib/gasyncqueue.c:422
#3  0x00007f8265ac04e8 in g_async_queue_timeout_pop_unlocked (queue=<optimized out>, timeout=timeout@entry=500000)
    at ././glib/gasyncqueue.c:570
#4  0x00007f8265b13da6 in g_thread_pool_wait_for_new_task (pool=<optimized out>) at ././glib/gthreadpool.c:262
#5  0x00007f8265b13da6 in g_thread_pool_thread_proxy (data=<optimized out>) at ././glib/gthreadpool.c:296
#6  0x00007f8265b133d5 in g_thread_proxy (data=0x7f821c002cf0) at ././glib/gthread.c:784
#7  0x00007f8264f7a424 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f8264cbd9bf in clone () at /lib/x86_64-linux-gnu/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 1 (Thread 0x7f8268c7ea80 (LWP 15386)):
#0  0x000055fc0d6a4ca0 in nemo_file_can_set_permissions (file=file@entry=0x0) at nemo-file.c:5084
#1  0x000055fc0d60f431 in application_unhandled_uri (parameters=0x55fc0f6b6be0, uri=<optimized out>) at nemo-mime-actions.c:1248
#2  0x000055fc0d60f431 in activate_files (parameters=<optimized out>) at nemo-mime-actions.c:1603
#3  0x000055fc0d60f431 in activate_callback (files=<optimized out>, callback_data=<optimized out>) at nemo-mime-actions.c:1760
#4  0x000055fc0d6a9ac2 in file_list_file_ready_callback (file=<optimized out>, user_data=0x55fc0f7093e0) at nemo-file.c:7996
#5  0x000055fc0d688786 in ready_callback_call (callback=0x55fc0f43ea40, directory=0x55fc0f3747b0 [NemoVFSDirectory])
    at nemo-directory-async.c:1241
#6  0x000055fc0d688786 in call_ready_callbacks_at_idle (callback_data=<optimized out>) at nemo-directory-async.c:1790
#7  0x00007f8265aeb6aa in g_main_dispatch (context=0x55fc0ef57800) at ././glib/gmain.c:3203
#8  0x00007f8265aeb6aa in g_main_context_dispatch (context=context@entry=0x55fc0ef57800) at ././glib/gmain.c:3856
#9  0x00007f8265aeba60 in g_main_context_iterate (context=context@entry=0x55fc0ef57800, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3929
#10 0x00007f8265aebb0c in g_main_context_iteration (context=context@entry=0x55fc0ef57800, may_block=may_block@entry=1)
    at ././glib/gmain.c:3990
#11 0x00007f82660a770d in g_application_run (application=0x55fc0ef5d130 [NemoApplication], argc=1, argv=0x7ffe8ae46528)
    at ././gio/gapplication.c:2381
#12 0x000055fc0d5d8bcd in main (argc=1, argv=0x7ffe8ae46528) at nemo-main.c:106

-- System Information:
Debian Release: 9.0
  APT prefers testing
  APT policy: (900, 'testing'), (800, 'unstable'), (700, 'stable'), (500, 'testing-debug')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.9.0-1-amd64 (SMP w/4 CPU cores)
Locale: LANG=nl_BE.utf8, LC_CTYPE=nl_BE.utf8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages nemo depends on:
ii  desktop-file-utils         0.23-1
ii  gsettings-desktop-schemas  3.22.0-1
ii  gvfs                       1.30.3-1
ii  libatk1.0-0                2.22.0-1
ii  libc6                      2.24-9
ii  libcairo-gobject2          1.14.8-1
ii  libcairo2                  1.14.8-1
ii  libcinnamon-desktop4       3.2.4-4
ii  libexempi3                 2.4.1-1
ii  libexif12                  0.6.21-2+b2
ii  libgail-3-0                3.22.8-1
ii  libgdk-pixbuf2.0-0         2.36.5-2
ii  libglib2.0-0               2.50.3-1
ii  libglib2.0-data            2.50.3-1
ii  libgtk-3-0                 3.22.8-1
ii  libnemo-extension1         3.2.2-3
ii  libnotify4                 0.7.7-1+b1
ii  libpango-1.0-0             1.40.4-1
ii  libpangocairo-1.0-0        1.40.4-1
ii  libx11-6                   2:1.6.4-3
ii  libxml2                    2.9.4+dfsg1-2.2
ii  nemo-data                  3.2.2-3
ii  shared-mime-info           1.8-1

Versions of packages nemo recommends:
ii  cinnamon-l10n    3.2.2-2
ii  gvfs-backends    1.30.3-1
ii  gvfs-fuse        1.30.3-1
ii  librsvg2-common  2.40.16-1+b1
ii  nemo-fileroller  3.2.1-2

Versions of packages nemo suggests:
ii  eog                  3.20.5-1+b1
ii  evince [pdf-viewer]  3.22.1-3
ii  totem                3.22.1-1
ii  xdg-user-dirs        0.15-2+b1

-- no debconf information

**Comment by ChrisJAllan** [comment]
It doesn't seem like Nemo supports web links at all.

**Comment by xenopeek** [comment]
I created the same file on Linux Mint 18.3 Cinnamon with Nemo 3.6.5, and double-clicking it works as expected (opens the link in web browser). If this issue still affects you please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
