### ISSUE TITLE
rapid filtering of folder contents

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1446]
support for fast/rapid search of only the visible contents within folder (faster than full-search)

similar to [qt-tab-bar](qttabbar.wikidot.com) program-addon for (windows explorer)
esp since when a folder is opened, it's contents already loaded in memory,
perhaps target latency  ≲ 0.1to0.2s

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
