### ISSUE TITLE
Dual pane has only a single path

### ISSUE THREAD

**Issue by motoschifo** [linuxmint/nemo#1447]
The dual page mode has just one folder path on top (the active one).
Can a second folder path be added for other pane, like it was on older releases?
Now I need to click on other page to check the absolute path and make a new click to go back, just to knows a path.
Is should be useful if other buttons will be replicated (previous, next, new folder, refresh, etc).

Thanks

**Comment by JosephMcc** [comment]
This is unlikely to happen. I had partly implemented this at one time and it was decided that we didn't want to go that direction.
