### ISSUE TITLE
Location bar exits

### ISSUE THREAD

**Issue by motoschifo** [linuxmint/nemo#1448]
If I go to location bar (pressing CTRL+L) it doesn't change back to normal when I exited from it (pressing ESC or ENTER).
I need to press twice again CTRL+L.
Previous releases (ex. on Mint 17) do not have this issue.

Thanks

**Comment by JosephMcc** [comment]
Good. If I set pathbar to use the location bar I don't want it to change just because I hit enter. I'd be highly annoyed by having to use reactivate constantly.

**Comment by motoschifo** [comment]
CTRL+L is usually intended to do a fast copy/paste.
No problem with that, I will do my changes locally.
