### ISSUE TITLE
Cannot reduce desktop icon size using .xpm image file

### ISSUE THREAD

**Issue by igitur** [linuxmint/nemo#145]
Recently did a clean install of Nadia, so currently I have Cinnamon 1.6.7+nadia installed.

Downloaded and unzipped Aptana Studio 3 and created launcher on desktop, using the icon included in the Aptana bundle. The desktop icon is HUGE and I can't resize is to a lower size. This never was a problem before.

Can't attach the icon here :( It's a .xpm file and available in the Aptana Studio Linux package available from the website.

**Comment by Vahan86** [comment]
@igitur, is this still an issue for you with Nemo 3.0.6 (Mint 18)?

**Comment by igitur** [comment]
@Vahan86 Sorry, I'm not using Mint anymore, so I can't answer you on that one.

**Comment by Vahan86** [comment]
@igitur, thanks for your reply, in this case can you please close this issue?

**Comment by a1eksandre** [comment]
Actually it's still a problem for version: 3.2.7+serena (Mint 18.1)

**Comment by igitur** [comment]
@a1eksandre I'm no longer using Mint, but I reopened the issue for you to take forward.

**Comment by icarter09** [comment]
@a1eksandre you still experiencing this issue on the latest version of nemo?

**Comment by a1eksandre** [comment]
@icarter09 no, that was long time ago.
