### ISSUE TITLE
Large images in directory messes up grid layout

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/nemo#1451]
Image describes everything. 

![image](https://cloud.githubusercontent.com/assets/5832930/24158308/973f4bfa-0e64-11e7-86fc-b7ac74f7c851.png)

**Comment by xenopeek** [comment]
Preview images can be wider and/or taller than standard icons, with certain limits. A square preview image shows you both limits. Tall preview images can thus increase row height. Preview images (like for photos or documents) would be less useful if restricted to a smaller size. This is intended behavior.
