### ISSUE TITLE
usbs inserted via usb-hubs aren't recognized as such, data integrity of removable media

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1456]
#only usb plugged into computer directly has usb icon..
does it make it treat it differently and what ways and no ways to view or control this
if mounting and unmounting showed what commands were passed (feature-learnability)

will this affect caching or writing in non-optimal ways?
e.g. removable drives prone to removal/disconnects (or usb-sig-interruptions)
and risk of data-loss

(already has some data loss related to nemo
and other apps hanging until
either 
for quit (there mention I/O errors) and other apps acting up (hardware?)
(also unable to cancel nemo file move operation) any apps using usb acting weird
bad-idea?- risky unplug and replug usb, -fed-up, some apps unfroze, but data-loss..
(was low -free ram also factor), but one frozen part shouldn't affect other in this way
esp when risk of data corruption is involved, (hanging app/usb holds the other hostage)
should more operations have throbbers to prove the app is still..moving?

should mint avoid caching on removable media as does on ms-windows(properties->hardware..)?
there currently aren't any user-exposable GUI's to set mount/drive related properties/settings
also lack of reporting if inserted media has errors
or any alerts on data-corruption events

btw after using  usbs on linux (fat32 exfat), windows complains often..  (chdsk)

should there be more evident clearer dialogs if it might me a hardware issue also?
more testing/detection/simulation/ui-fuzzing/debug ?

**Comment by leigh123linux** [comment]
udisk2 handles the mounts in nemo

**Comment by xenopeek** [comment]
As mentioned mounts are done by udisks2. If this issue is still affecting you please retest with Nemo 4.6.4 or newer.
