### ISSUE TITLE
Sometimes Can't open folder on remote server

### ISSUE THREAD

**Issue by kentanilsson** [linuxmint/nemo#1459]
Error box shows up telling "there is no folder"
Access path: ftp://<user>@ftp.<serverurl>.com
That is ending up in /home/<myaccountname> and is world readable.
Once nemo crashed. Today.
Restarted and access site. Works fine!!! For now.

**Comment by xenopeek** [comment]
If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
