### ISSUE TITLE
Type-ahead find box should be auto-cleared by more actions

### ISSUE THREAD

**Issue by eyalroz** [linuxmint/nemo#1461]
I'm a heavy user of the "type-ahead find" feature, i.e. when you type characters at your file manager window, and they: (1) Show up in a box and (2) Cause the cursor/focused item to move to the first file or folder which matches what has already been typed. (I'm explaining to make sure you know what I'm referring to...)

However, nemo's type-ahead find box has a problematic behavior: It often retains what I've already typed even when I want to be typing in something new, from scratch. Specifically, when I:

* Press a non-printing-character key, like Enter, an arrow key, Escape
* Move to another folder (e.g. by double-clicking it or some other way)
* Press Backspace while the folder pane rather than the type-ahead find box is focused
* Select an item with the mouse
* ... or even just mouse-click anywhere

I expect the type-ahead find box to be _cleared_, and will now be used for a different search; but - it isn't.

This is exacerbated by the fact that it is possible for the type-ahead find box to disappear, and for a folder change to have happened, so that you now have no visual indication that there's characters in the type-ahead find buffer. At that point I very often instinctively start a new "search" with type-ahead find only to get a glimpse of character left in the buffer from the previous search; and if I press Backspace, it's often the actual window that's focused, in which case I go back up, which is usually the opposite of what I wanted to do, and I have to repeat myself several times.

This behavior is, to my knowledge, not the norm. The type-ahead find behavior of Windows Explorer is good; and I'm pretty sure KDE's file manager is find and probably some others as well.

PS - Thank you for all your hard work :-)

**Comment by xenopeek** [comment]
Related to #276

**Comment by eyalroz** [comment]
@icarter09  : With respect - It's not a feature request. It's a bug - it's unexpected, detrimental behavior that should be changed, not missing functionality that could be added.

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I'm seeing that the type-ahead find box is auto-clearing the previous search when testing against the expected use cases. @eyalroz are you still experiencing this issue? Thanks.

**Comment by eyalroz** [comment]
I'm using Devuan 3.0 these days, with Nemo 3.8.5, so I can't check that version.

On my version, I still see the the issue manifesting in most/all cases I mentioned above.

**Comment by leigh123linux** [comment]
> I'm using Devuan 3.0 Beowulf (64-bit; it's Debian Buster without systemd) these days, with Nemo 3.8.5, so I can't check that version.
> 
> On my version, I still see the the issue manifesting in most/all cases I mentioned above.

Your version is EOL, I'm going to close this issue as it has been fixed in recent versions.

**Comment by eyalroz** [comment]
@leigh123linux : Fair enough, but I reserve the right to (ask you to) reopen it if I see this again when my version is updated.
