### ISSUE TITLE
Selecting multiple files with keyboard in Icon View is erratic

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1462]
When selecting multiple files in Nemo using the keyboard, selection becomes illogical and erratic.

    Nemo version: 3.2.2 Desktop: Cinnamon 3.2.8  Distro: Arch Linux

Steps to reproduce:

1) Find a folder with a lot of files and select Icon View.
2) Click on a file or just use arrow keys to focus on a file
3) Use left and right arrow keys while holding the Shift key to select multiple files in the same row
4) Go the the right edge of the row and keep pressing right arrow (while holding shift) and you'll notice that quite often, you end up selecting pages worth of files instead of selecting the next, far left, file of the next row. For some reason, Nemo jumps to the last row of files.
5) This rarely happens when you reverse the order and you select files on the previous row.

**Comment by vinsifroid** [comment]
I agree, it does the same for me too, `Nemo : v3.2.2 , Desktop: Cinnamon 3.2.7 , Distro: Linux Mint 18.1 64-bits`
I want to add too that when moving with arrow key while holding Shift key, if a file name is to big, it will just stop from selecting but in a weird way.
For exemple : 
1. you select files like said above with arrow keys and Shift.
2. a file name is very big (mine is 143 characters for example) but you still can select it
3. you continue selecting until next line
4. when you want select the file right below the big file, it's refuse to do it

**Comment by nick-s-b** [comment]
@vinsifroid Bug confirmed here as well. It just stops selecting on files with long names. I haven't noticed that before myself but it's definitely a bug.

**Comment by xenopeek** [comment]
Couldn't reproduce this on Nemo 4.6.4. Tried with a directory with 5200 files with filenames 200 long.
