### ISSUE TITLE
How to customize nemo visually?

### ISSUE THREAD

**Issue by skullscream** [linuxmint/nemo#1465]
This is not an actual bug but I couldn't PM anyone who's working on this so I have to do it this way.

I'm interested what file(s) should I go to to change some visual aspects of nemo file manager. I've marked what I'd like to change on the screenshot. I have some knowledge of CSS which I'm guessing I'd need to edit it?

[http://i.imgur.com/yVc4bRAg.png](http://i.imgur.com/yVc4bRAg.png)

**Comment by JosephMcc** [comment]
This isn't the place for this. You could try #linuxmint-help on IRC or the Mint forums where there are several users that usually give feedback on these types of issues.
