### ISSUE TITLE
'Set as default' is broken

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1468]
The 'set as default' option within Nemo's 'open with' function is broken, at least for some files and/or programs.

I've WPS Writer set as default for .docx files. When I try to change the default to LibreOffice Writer, LibreOffice Writer appears in the window's default field but only momentarily: after a few seconds, WPS Writer is back!

The System Settings way of setting defaults does work (for the case in question), but it left a .docx icon on my desktop with its WPS icon, even after refreshing the desktop.

**Comment by CottonEaster** [comment]
This problem persists (though it seems only to beset some file types). Please see attached video. But, ah, github does not support video attachments. So [see here instead](https://app.box.com/s/36f8ib5egc76zhkvtzqc8spes6wxvbdo) (link to a box upload).

**Comment by CottonEaster** [comment]
I may have misfiled this bug, because it affects me - still, i.e. some months later - even while I use a file-manager other than Nemo as my default. I submit that the problem is a fairly serious one.

**Comment by xenopeek** [comment]
I can't reproduce this issue. I installed WPS Office Alpha 21 (.deb file from their website) and it doesn't appear to hijack file type association on its own like it does on Windows. Setting XPS Writer as default and then changing it back to LibreOffice Writer all works as expected. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
