### ISSUE TITLE
WebDav path issue when using Connect to Server

### ISSUE THREAD

**Issue by alexsr** [linuxmint/nemo#1469]
I was connecting to an owncloud server using the connect to server interface and for some reason it did not take the whole path I put in.
The dav link looks similar to this:
davs://mail@example.org/owncloud/remote.php/dav/files/mail@example.org/
While connecting to the owncloud dav worked, the mounted network folder path was missing files/mail@example.org/
I also tried to use the folders input field to possibly circumvent the issue but to ne success.

**Comment by khartahk** [comment]
I'm not sure what version of ownCloud you're using, but on 9.0.0 (stable) this is working for me: davs://USER@example.org/remote.php/webdav

**Comment by alexsr** [comment]
The issue is, that I can only access a specific path of the owncloud installation with my credentials. "../webdav/files/user@example.org/" to be specific, but nemo does not use the path I set. Instead it uses the main path "../webdav/"

**Comment by icarter09** [comment]
@alexsr are you still experiencing this issue on the latest version of nemo?

**Comment by alexsr** [comment]
Sorry, I can no longer test, whether or not the issue still exists as I no longer use Mint and nemo due to work policy.
I guess I will just close this.

**Comment by montvid** [comment]
I must report that nemo webdav is broken on lmde 4. I am using lighttpd 1.4.55 as webdav server and it works with cadaver and many android clients but not nemo. Nemo detects the https certificate but is stuck in infinite spinning of the task showing nothing.

**Comment by montvid** [comment]
The same with Nautilus 3.38.1 on Fedora 33 VM. I guess the problem might be that the server is not nextcloud but lihghttpd. But still other clients work fine.

**Comment by montvid** [comment]
rclone webdav implementation works with nemo but lighttpd does not. Have to check with lighttpd devs then :smile: .
