### ISSUE TITLE
Android MTP problem

### ISSUE THREAD

**Issue by nerox8664** [linuxmint/nemo#1470]
I have an Android 7.1 device with usb-mtp. When i start copying files to mtp-device all nemo windows freezes. Also, they are unfreeze only when copying is done or when i disconnect device.

Nemo version: 3.2.2
Arch Linux, kernel 4.10.11
gvfs 1.32.1
gvfs-mtp 1.32.1
udev rules are correct

Also, there are similar issues - https://github.com/linuxmint/nemo/issues/917, https://github.com/linuxmint/nemo/issues/691

**Comment by infectedmushi** [comment]
if you are using "multi-core" applet, disable disk monitoring, and reboot.

**Comment by nerox8664** [comment]
nope, i don't use "multi-core applet"

**Comment by leigh123linux** [comment]
Closed as it's a duplicate of #691
