### ISSUE TITLE
Bookmarks renaming on different cases but equal string on first char

### ISSUE THREAD

**Issue by g-alfieri** [linuxmint/nemo#1476]
I can't get to rename a bookmark if I try to change the case of the first char without changing the remaining part of the string.

It's a very minor issue I can workaround changing the string and then coming back at desired name with the toggled first char.

**Comment by xenopeek** [comment]
I can't reproduce this on Nemo 3.6.5. Changing only the first letter of a bookmark to lower case (or back to upper case) works as expected. So either it was fixed in Nemo or you had some other issue.
