### ISSUE TITLE
[Feature Request] Display hidden files and folders with an "alpha"

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/nemo#1480]
I am coming from Wind0ws and like that Cinnamon very much. One thing i real miss is the feature, that Nemo is showing hidden files and folders with the same alpha as normal files. In Wind0ws was a better solution to display that files with an alpha. (Sample from Windows 7):
![](http://pix.toile-libre.org/upload/original/1494055705.png)

Would be nice to have that effect in nemo also

**Comment by MegaV0lt** [comment]
If display with alpha ist too complicatetd, maybe an special overlay-icon (! or similar)

**Comment by MegaV0lt** [comment]
Here is an example how it could look like  (1) in actual nemo:
![](https://dl.dropboxusercontent.com/1/view/besmw742srerk20/Apps/Shutter/Auswahl_20170801_12%3A42%3A29.png)

1= hidden with 50% hlpha
2= hidden current state

**Comment by MegaV0lt** [comment]
Screenshot again:
![](https://i.imgur.com/HNCvPaQ.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
