### ISSUE TITLE
Setting to open nemo in disk view (computer view) 

### ISSUE THREAD

**Issue by duck7000** [linuxmint/nemo#1483]
I recently switched from Windows to Linuxmint and i love it.

One thing bothers me a little.
If i start the filemanager (nemo) it always starts in my home directory.
There is no option in the settings to start nemo in Computer view.

Can this setting been added?

Thanks!
Ed

**Comment by NikoKrause** [comment]
You can right click on the desktop and choose `Desktop settings`. There you can turn on a switch to show the `Computer` on the desktop.

If you want to change it in the panel, right click the nemo icon in the panel, choose `Edit` and change the Command form `nemo %U` to `nemo computer:///`.

**Comment by duck7000** [comment]
Thanks a lot it works like a charm!

**Comment by NikoKrause** [comment]
Which one was it?

**Comment by duck7000** [comment]
Sorry if i'm not clear enough, i ment the second part:

> If you want to change it in the panel, right click the nemo icon in the panel, choose Edit and change the Command form nemo %U to nemo computer:///.

I did know about the desktop shortcut, but that is not what i'm after

**Comment by NikoKrause** [comment]
Ah, yes it's unlikely to happen.

**Comment by NikoKrause** [comment]
> Is this useful to include in the settings so that a user can choose?

It's unlikely to happen. I don't think that there are a lot of users, who want that. And those users who want that, can add it to the panel launcher on their own as described.
Instead of changing the existing one, you can also create a new panel launcher, so you can have both, `home` and `computer` in the panel.

Also looking at the Roadmap https://github.com/linuxmint/Roadmap:
> nemo: retire computer:/// place (which is completely useless) or revamp it into something better

**Comment by duck7000** [comment]
Thank you for your explanation.

I tried your method and it works great but i realize that in fact there is no added value, like the roadmap also stated..
So i agree with your statement.

**Comment by NikoKrause** [comment]
So this can be closed?

**Comment by duck7000** [comment]
yes it can be closed, sorry about the delay
