### ISSUE TITLE
Fast empty trash

### ISSUE THREAD

**Issue by bkmeneguello** [linuxmint/nemo#1484]
Nemo list all trash files before empty, should exists an option to fast empty the trash directory, without progress indication.

**Comment by osmand** [comment]
yes it is slow, with improvement you can have a progress indicator still if you know the filecount, though.

**Comment by xenopeek** [comment]
If I right-click the Trash (on the desktop or in Nemo sidebar) and select "Empty Trash", it empties it for me quickly and without showing the files. That's on Nemo 3.6.5 with a SSD drive and I had about 2,000 files in the trash for about 1 GB total disk space.
