### ISSUE TITLE
Right Click Drag Menu, Folder arranging with _, Copy/Edit Paths

### ISSUE THREAD

**Issue by dynamikspeed** [linuxmint/nemo#1486]
In Windows Explorer the following can be done if they can be added to Nemo or turned on in settings as an option that would be great. As I use Windows in work i keep trying to do these in Nemo and failing.

1. I dragged folders with the right mouse button held down this would provide me with the context menu and gave me options to copy, move, create shortcut, cancel. Useful if you want to move a folder instead of clicking Cut and then opening the folder and Paste.
2. Left clicking the text on a folder once lets you rename it. This would be useful instead of having to right click > rename or pressing F2. (I found this in Nemo Prefs maybe it can be set as default)
3. I can start a folder name with _ and it moves to the front of the folder list when it is arranged by name. This is useful when you have lots of folders and want to prioritise certain ones to the front of the folder list. I tried this in Nemo and it just goes on the next letter after _ and arranges it like that. The numbers work such as 1. 2. 3. which can get messy. The _ and symbols would be useful as it is in Windows.
4. When left clicking on the folder name at the top in explorer it changes to the folder path and can be copied/edited. The same can be done when right clicking the folder name a menu pops up to copy/edit.

**Comment by mtwebster** [comment]
1) Hold alt while dragging to get an Ask menu when dragging.  By default, a drag *moves files within the same filesystem* and copies when files are in different ones.  Holding control while dragging will always force a copy.

2) edit->preferences->Behavior->Click on a file's name twice to rename it

4) Ctrl-L will toggle between 'breadcrumbs' path bar, and location entry, which will show you the current path.

**Comment by dynamikspeed** [comment]
That's excellent, thank you.
How about the begin folder with _ moves it to the front of a folder list?

**Comment by ManIVIctorious** [comment]
The sort by name order is local aware and global for your user account so this is is something nemo isn't aware of.
E.g. your underscore first sort should work in an "ASCIIbettical" sort order.
You can try it out by stating nemo from a terminal with the following commands:
`export LC_COLLATE=C`
`nemo&`
unfortunately it will sort underscores between uppercase and lowercase characters...

If this is what you want you can either set this line in your .bashrc or in /etc/locale.conf and run the command local-gen (root privileges required)

**Comment by dynamikspeed** [comment]
OK i tried that it's not what i was looking for but I am now using 0 to put the folders at the start and this seems to be working ok.
