### ISSUE TITLE
Nemo 3.4: [Feature Request] Allow user to disable shadows on selected desktop icon labels

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1487]
Basically, on the Nemo 3.4 Desktop, you get a drop-shadow on the selection box of the file name when you select a file, but to me, it looks ugly, so if there's an option soon to disable that shadow, and possibly also disable the file name shadow too when it's in the selected state (like it was before), then I'll be more happy with it.

**Comment by feren** [comment]
Also, is it possible to also be able to remove the selection box shadow on the hovered state too?

**Comment by mtwebster** [comment]
I've just pushed a change removing the drop shadows from the highlight boxes and the text.  The box shadows were causing some repaint issues, leaving artifacts behind.

For 3.6 I'm hoping to restore the ability to theme the desktop (while still providing fallback styling for themes that don't have support) - so I may reevaluate this stuff at that time, but I'd like to avoid preferences for things like shadows.

**Comment by cinnamoner** [comment]
@mtwebster Awesome 👍

**Comment by feren** [comment]
@mtwebster Thanks!
