### ISSUE TITLE
 Nemo 3.4.1: people will be thrown by unmovable icons . . 

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/nemo#1488]
. . and will struggle to find a way to allow them to be moved. First I checked the right-click desktop context menu, and didn't (in the top level menu . .) see what I sought. Then I looked in Nemo's options, and that was no help. Then I found it.

Some sort of message, in release documentation but also, I suggest, the first few times one tries to move icons (or something like that) is in order, I suggest. Otherwise people will get frustrated - within seconds of trying the (generally admirable) new version of Cinnamon. But - I've just seen https://github.com/linuxmint/nemo/issues/108#issuecomment-301262447 - I recognise that I am commenting upon what is a work in progress.

[Originally this post was on the Cinnamon bugtracker.]

**Comment by JosephMcc** [comment]
The reason for this was explained in the linked post. The current behavior is intentional.
