### ISSUE TITLE
Grid: refreshing desktop with F5 moves icons

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1489]
To reproduce: with the grid on, move an icon somewhere; press F5; observe that the icon has returned to its previous position.

Also, selecting >1 icon and dragging sometimes throws some icon(s) to one place and some other icon(s) elsewhere.

Nemo 3.4.1.

**Comment by xenopeek** [comment]
Does this issue still affect you on Nemo 3.6.5? For now closing this issue as there isn't enough information here to go on. You can reopen the issue if it is not fixed at your end and the responsible component proves to be Nemo.

If you do reopen, include how you have configured your desktop icon alignment (auto-arrange: yes/no, align to grid: yes/no, sort: by name/size/type/date, align: vertical/horizontal). ![Screenshot](https://i.imgur.com/RXBcX6p.png)
