### ISSUE TITLE
Nemo 3.4.1: files saved to the desktop, from Firefox or Chome, do not appear

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/nemo#1490]
To repoduce: save a file to the desktop from Firefox or Chrome; notice that the file is not visible on the desktop; open a normal Nemo window and verify that the files are actually there. Pressing F5 doesn't help. I have only one monitor attached to the computer.

**Comment by mtwebster** [comment]
linuxmint/nemo@880502f2320895a8c
