### ISSUE TITLE
In root Nemo, 'Make link' is available from the File menu but not from the context menu

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1492]
When Nemo is run normally, i.e. not as root, a 'make link' option is available via both the 'File' drop-down menu and the right-click context menu. However, when Nemo is run as root, only the former is available. Since the former - the drop-down method of making a link, in root Nemo works - why can't we have that option in the context menu too? If we did, it would be both convenient and consistent, whereas at the moment the lack of the option is unconvenient and - because inconsistent - counter-intuitive.

**Comment by CottonEaster** [comment]
If this issue - which breaks one's workflow (habits) - will not be acted upon, might I ask why not? For, it seems like a good idea to me, and it would be a nice addition to the forthcoming revised version of Nemo. Cf. also #1676.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
