### ISSUE TITLE
no text under desktop icons

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/nemo#1494]
With **nemo 3.4.1** and **cinnamon-desktop 3.4.0** desktop icons have no text underneath. When selected a little horizontal line, like a dash appears instead.

**Comment by oberon2007** [comment]
I forgot to add that I am running Manjaro.
Here is a screenshot of the current new situation (Computer icon is selected):
![](http://imgur.com/pmFVOxX.png)

**Comment by leigh123linux** [comment]
Did you build DIY or get it from repo?

**Comment by oberon2007** [comment]
I built it.
And I already found the reason:
My "Desktop font" in font settings was set to 'none'.
Is this a new setting? A new gsetting to be defined also maybe?

**Comment by oberon2007** [comment]
Maybe I should add that I am the maintainer of Manjaro-Cinnamon. Since Archlinux isn't providing the latest Cinnamon packages I built all the new releases for Manjaro now.

**Comment by leigh123linux** [comment]
It isn't new

https://github.com/linuxmint/nemo/blame/master/libnemo-private/org.nemo.gschema.xml.in#L472

I fix it with a schema override

http://pkgs.fedoraproject.org/cgit/rpms/nemo.git/tree/nemo-fedora.gschema.override

**Comment by oberon2007** [comment]
Ok. Thanks. So the default is empty. Seems that until now a fallback was used in my case for some reason. I'll add an override in our defaults aswell, yes. 👍

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/7a1b730e548d439d4cc1af91f2f9f6781e87d38c

**Comment by oberon2007** [comment]
Great @mtwebster , thanks! Maybe **nemo** should now depend on **ttf-unicornpoo**? 😂
