### ISSUE TITLE
File names not displayed on desktop

### ISSUE THREAD

**Issue by kjkrum** [linuxmint/nemo#1496]
With Nemo 3.4.1 and Cinnamon 3.4.0 on Ubuntu 16.04, file names are not displayed on the desktop.

I did an apt update yesterday.  I'm not sure what version of Nemo I had before.

```
kevin@aphrodite:~/Desktop$ ls -p
derp/  print/
kevin@aphrodite:~/Desktop$ touch foo
```
Result:
![nemo-desktop](https://cloud.githubusercontent.com/assets/1007080/26072231/a5767470-395f-11e7-9306-b3d2108dcc8a.png)

It also forgot where the folders were previously positioned.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1494
Set a font for your desktop.

**Comment by kjkrum** [comment]
How do you set a font for your desktop?  My google-fu is failing.
