### ISSUE TITLE
hiding raid partitions in sidebar

### ISSUE THREAD

**Issue by atomi** [linuxmint/nemo#1497]
how do I hide the additional partitions that don't get mounted from a btrfs raid array?

ie 
![screenshot 2017-05-15 17 46 46](https://cloud.githubusercontent.com/assets/83137/26085140/d66db14c-3996-11e7-8891-b3c2685cded4.png)

I would prefer only one 'minio' mount show up.

**Comment by icarter09** [comment]
@atomi are you still experiencing this issue on the latest version of nemo?
