### ISSUE TITLE
Nemo is showing wrong icons in sidebar after first start

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/nemo#1498]
LM18.1 Cinnamon

Nemo is showing wrong icon of my folders Nextcloud and Dropbox. They were added by drag and drop and the folders are on the second internal hd.
Picture at first start after boot:

![nok](http://pix.toile-libre.org/upload/original/1493647789.png)

After going to the second hd the icons are displayed ok.

![ok](http://pix.toile-libre.org/upload/original/1493647851.png)

PS: The overlayicons (Checkmark) get displayed only if the folders are shown on the right side.

**Comment by MegaV0lt** [comment]
Still the same under LMC 18.2 (Updated today)

**Comment by MegaV0lt** [comment]
Noone has a clue?

**Comment by leigh123linux** [comment]
@MegaV0lt Is this still an issue?

**Comment by MegaV0lt** [comment]
For me with Cinnamon 19.2 not. Now the icons are all grey on dark background.
![Auswahl_20191211_12:50:34](https://user-images.githubusercontent.com/2804301/70619235-dd8ab480-1c14-11ea-91fb-6a5c186809fe.jpg)
