### ISSUE TITLE
Desktop icons missing

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/nemo#1499]
As of some days ago, I no longer see any desktop icons.

When upgrading (I'm on nightlies from glebihan PPA for Ubuntu - multiple Ubuntu versions), I am also not prompted to restart Nemo, unless I have a normal windows open, so I don't think it's even started.

Additionally, when I used to stop Nemo, it would redraw the desktop icons whenever I started a normal Nemo windows - this also doesn't happen anymore.

Please advise as to troubleshooting.

**Comment by mtwebster** [comment]
As of 3.4, nemo uses a separate process - `nemo-desktop` to manage the desktop icons.  Normal nemo will only run while you have open windows.  The desktop process should autostart when you log in (this can be controlled via cinnamon-settings, or directly with dconf-editor,) just like it used to.

**Comment by Fjodor42** [comment]
Turns out glebihan hasn't begun packaging that yet, which I have now requested.

Thank you for clarifying :-)
