### ISSUE TITLE
Problem with autofs that may owe to Nemo

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/nemo#1500]
I get this regularly in the log (filed under 'other'):

`key ".hidden" not found in map source(s)`

and after upgrading to version of autofs newer than the one in Mint's repositories, that above error message has this friend who comes along too:

`rmdir_path: lstat of /mnt/autofs/Windows/.hidden failed`

where /mnt/autofs/Windows/ is an autofs mount point for a drive on a Windows computer on my home network.

I mention all this because [I found a suggestion](https://unix.stackexchange.com/questions/361775/autofs-hidden-no-such-file-or-directory) that Nautilus - and so Nemo? - is to blame. Apologies if, in trying to be rid of this troublesome bug, I bark up the wrong tree.

Linux Mint 18.1 x64 Cinnamon. Nemo 3.2.2.

**Comment by ACinnamonUserInUK** [comment]
Looking more closely at materials linked by the page I cited, it seems that this problem is being fixed, now, at the level of the Linux kernel.

**Comment by mtwebster** [comment]
Our code base is a bit different here - we do actually read the file ourselves in Nemo still - https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-directory-async.c#L1906 

I didn't catch anywhere is the parent folder (that is, the folder the .hidden file exists inside of) anything special?  if you run `gvfs-info .` does it display any attributes that could be used to identify the folder as something *not* to read the .hidden file in?

Either way, I'm inclined to wait to do anything until we see what they resolve upstream.  I'm not keen on removing hidden file support for now if it's not actually affecting you other than some warnings.

**Comment by ACinnamonUserInUK** [comment]
@ mtwebster: here you go

```
/mnt/autofs/Windows/Windows_Documents $ gvfs-info /mnt/autofs/Windows/
display name: Windows
edit name: Windows
name: Windows
type: directory
size:  0
uri: file:///mnt/autofs/Windows
attributes:
  standard::type: 2
  standard::name: Windows
  standard::display-name: Windows
  standard::edit-name: Windows
  standard::copy-name: Windows
  standard::icon: folder
  standard::content-type: inode/directory
  standard::fast-content-type: inode/directory
  standard::size: 0
  standard::allocated-size: 0
  standard::symbolic-icon: folder-symbolic, folder
  etag::value: 1495120396:68094
  id::file: l47:27540
  id::filesystem: l47
  access::can-read: TRUE
  access::can-write: FALSE
  access::can-execute: TRUE
  access::can-delete: FALSE
  access::can-trash: FALSE
  access::can-rename: FALSE
  time::modified: 1495120396
  time::modified-usec: 68094
  time::access: 1495120435
  time::access-usec: 947959
  time::changed: 1495120396
  time::changed-usec: 64094
  unix::device: 47
  unix::inode: 27540
  unix::mode: 16877
  unix::nlink: 6
  unix::uid: 0
  unix::gid: 0
  unix::rdev: 0
  unix::block-size: 1024
  unix::blocks: 0
  unix::is-mountpoint: TRUE
  owner::user: root
  owner::user-real: root
  owner::group: root
  metadata::nemo-icon-view-auto-layout: true
  metadata::nemo-icon-view-tighter-layout: false
```

```
mnt/autofs/Windows/Windows_Documents $ gvfs-info /mnt/autofs/Windows/Windows_Documents
display name: Windows_Documents
edit name: Windows_Documents
name: Windows_Documents
type: directory
size:  65536
uri: file:///mnt/autofs/Windows/Windows_Documents
attributes:
  standard::type: 2
  standard::name: Windows_Documents
  standard::display-name: Windows_Documents
  standard::edit-name: Windows_Documents
  standard::copy-name: Windows_Documents
  standard::icon: folder
  standard::content-type: inode/directory
  standard::fast-content-type: inode/directory
  standard::size: 65536
  standard::allocated-size: 65536
  standard::symbolic-icon: folder-symbolic, folder
  etag::value: 1492316741:260156
  id::file: l45:281474976714747
  id::filesystem: l45
  access::can-read: TRUE
  access::can-write: TRUE
  access::can-execute: TRUE
  access::can-delete: FALSE
  access::can-trash: FALSE
  access::can-rename: FALSE
  time::modified: 1492316741
  time::modified-usec: 260156
  time::access: 1492316741
  time::access-usec: 260156
  time::changed: 1492316741
  time::changed-usec: 260156
  unix::device: 45
  unix::inode: 281474976714747
  unix::mode: 16877
  unix::nlink: 2
  unix::uid: 1000
  unix::gid: 0
  unix::rdev: 0
  unix::block-size: 16384
  unix::blocks: 128
  unix::is-mountpoint: TRUE
  owner::user: nicholas
  owner::user-real: Nicholas Joll
  owner::group: root
```

**Comment by ACinnamonUserInUK** [comment]
I should add that I do have a problem associated with autofs - and so suffer from more than error messages in the logs - but I think this might be a separate (a systemd?) problem. It's that sometimes the computer gets stuck in a 'stop job' loop when trying to unmount autofs shares when shutting down. I've had to try all sorts of stuff to get around it, and at present a combination of a run-on-shutdown-script to manually dismount the shares, and using the watchdog utility (in 'hardware' mode) seems to solve it. It's a very annoying problem and rather embarrassing for Linux in that it tends to strike when I use my laptop away from home for teaching.

There are bug reports in various places on the Internet about this shutdown problem.

**Comment by mtwebster** [comment]
is "autofs" always part of the path?  Does its configuration allow you to specify a different folder instead?  I'm basically looking for a reliable hint that I should not check this file (though from the sound of those other discussions, even if I fix my use of it in Nemo, something underlying may still be doing it)

**Comment by ACinnamonUserInUK** [comment]
On my system, 'autofs' is always part of the path for the shares, _but_ that isn't so by necessity or even default. The share paths can be anything one likes and they do not have defaults. Moreover - worse, for our purposes - the files that set the paths have arbitary names. Well, they do more or less: one file that can set the names is called (always) `/etc/autofs.master` and, by convention and recommendation, other files that set the paths have a leafname prefix of `auto.`, as in e.g. `/etc/autofs/auto.usb-cifs-share`.
