### ISSUE TITLE
compact view gone

### ISSUE THREAD

**Issue by rcrath** [linuxmint/nemo#1503]
Manjaro linux
Cinnamon 3.40
nemo 3.41

Compact view no longer works.  Instead, when I choose compact view it gives the icons view again. Hope its not a new "feature", as one of the primary reasons I moved to Cinnamon was nautilus bagging the compact view, which I depend on.

I am going to check downstream in the manjaro community too, as they beat arch in getting cinnamon 3.4 into their repos.

**Comment by rcrath** [comment]
here is a screenshot of my compact view (it is set in preferences to come up at 66% of full size)
![screenshot from 2017-05-19 17-43-57](https://cloud.githubusercontent.com/assets/944636/26272730/bcdd0a34-3cbb-11e7-867b-ddc73737b4a4.png)

**Comment by rcrath** [comment]
Actually I see it is not the same as icon view since the filenames are still at the side.  just the icons are now huge.  maybe this is a byproduct of fixing #1032 ?  the layout is supposed to go column then row, but now it goes row then column, like reading abook.  this makes finding things alphabetically very slow. 
 If this is the new way, I would like to request plese an option to set it back to the old behavior!  Anyway, I have a really difficult time with this.  maybe I can get on another computer I have not upgraded and send a screenshot of what it formerly looked like once I get home.

**Comment by mtwebster** [comment]
This is what I get on the latest build - 

![screenshot from 2017-05-20 01-10-10](https://cloud.githubusercontent.com/assets/262776/26273237/60041cec-3cf9-11e7-8c2a-ef04efdc04ce.png)

Nothing should be changing with any views except the desktop (and that is even 'optional' via gsettings) - if anything has changed, it's probably a regression, and we'll try to get it fixed.  I'm not sure why you're seeing what you're seeing, or even what version you're running - I do know someone else has mentioned this to me in chat, or something similar, but I can't reproduce it anymore.

**Comment by ccenl** [comment]
Hello,

i'm having the same issue - and i also hope, it isn't a new feature.

Using Manjaro with Cinnamon too

**Comment by rcrath** [comment]
Verified by several [manjaro users](https://forum.manjaro.org/t/nemo-3-42-compact-view-gone/24122/5).  Looking into it there too, in case its a packaging error or something.

**Comment by rcrath** [comment]
@mtwebster thanks for checking.  Will try to install the latest build from source and see if that fixes it.

**Comment by rcrath** [comment]
compiling from latest git fixes the compact view, but cinnamon crashed on startup after reboot.  restarting it seemed to work.  LMK if you want logs or anything.

**Comment by oberon2007** [comment]
Fixed with latest git snapshot:

![](http://imgur.com/l9AGFL2.png)

I'll push the package to Manjaro repos as **v3.4.1-1.1**

**Comment by rcrath** [comment]
THanks!

**Comment by rcrath** [comment]
confirming lates build fixes it.  closing! thanks.
