### ISSUE TITLE
Disappearing desktop icons

### ISSUE THREAD

**Issue by frankfontein** [linuxmint/nemo#1504]
I run Linux Mint 18.1 with three displays. Several times now, most desktop icons have disappeared after a 'suspend' the night before. I see other people have had the same problem and as a developer I'd love to be able give more information to allow nailing this bug, but at this stage all I can offer is that with three screens, all icons from the middle screen have gone, but the two icons from the left screen have ended up on the middle screen (there were none on the right). I'll try to be more specific when it happens again (every 1-2 weeks so far). One more thing: Thunderbird used to open on my right screen, this morning it opened on the middle screen.

**Comment by lobstaj** [comment]
Linux mint 18.1 cinnamon with only one single laptop display. Icons disappear randomly, apparently after suspend.

@dodona2 No offense. But "log-out before suspend" seems as good a workaround as "shutdown instead of suspend" or "install fedora instead of using mint". If suspend cannot be used to preserve the computer state with all open applications, it seems quite useless...

**Comment by IzzySoft** [comment]
Also on 18.1 with a single monitor. Desktop suddenly empty, without "suspend". Checking `ps aux | grep nemo` showed no nemo process running. Starting a "file explorer" makes the icons reappear, closing it makes them disappear again. Not sure what made it crashing, but how can at least the corresponding background process be restarted – without logging out and in again? Restarting Cinnamon doesn't do the trick.

PS: Seems like starting a nemo window and leaving it open for a few minutes solved it in my case. Even after closing the file browser window, icons remained – and `ps` reported one running nemo process. Strange, but might be helpful to others encountering this.

**Comment by icarter09** [comment]
can anyone comment on this still being an issue on the latest version of nemo?

**Comment by IzzySoft** [comment]
@icarter09 I haven't seen it for a long time. Seems to be solved around 18.2/18.3 (at least for me). Cannot speak for multi-monitor of course: still have only one.

**Comment by frankfontein** [comment]
Same for me - all seems well now
      running three monitors
    
    
    Frank
    
    
    
    On 11/05/20 6:20 pm, Izzy wrote:
    
    
      
      @icarter09
        I haven't seen it for a long time. Seems to be solved around
        18.2/18.3 (at least for me). Cannot speak for multi-monitor of
        course: still have only one.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/linuxmint/nemo/issues/1504#issuecomment-626495486",
"url": "https://github.com/linuxmint/nemo/issues/1504#issuecomment-626495486",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by icarter09** [comment]
thanks @IzzySoft and @frankfontein for the update.
