### ISSUE TITLE
<Alt> unhides menubar regardless of other key combinations

### ISSUE THREAD

**Issue by caligari87** [linuxmint/nemo#1505]
Described initially in [this reddit thread.](https://www.reddit.com/r/linuxmint/comments/6chik4/nemo_opens_menubar_when_i_switch_workspaces/) If focused, Nemo unhides the menubar whenever Alt is pressed, not respecting any other key combinations. This is particularly apparent when switching workspaces with the default Ctr+Alt+Left/Right key combo. The menubar then stays open until pressing Alt again with the window focused.

This behavior is unlike other programs which only unhide the menubar if Alt is pressed alone (such as Firefox). 

Nemo 3.2.2
Cinnamon 3.2.7

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/1389
https://github.com/linuxmint/nemo/issues/918
