### ISSUE TITLE
Search changes the columns displayed. Cannot sort by date modified.

### ISSUE THREAD

**Issue by jgoldgh** [linuxmint/nemo#1506]
When you  do a search in Nemo, it changes the columns to include the location. Makes sense.  The problem is, I'm trying to find a recent file so I'd like the list sorted by the modification date. Can't do that if the column isn't there. 

I find how to add the column but when the search results are displayed, it ignores the setting.  When I start a new search after adding the column it shows up for a bit but then rudely, it's removed.  This is a bug and it makes it almost impossible to search for  recent items.

This is running on Linux Mint Cinnamon 18.1. All updates have been applied.

**Comment by JosephMcc** [comment]
Not saying this couldn't be better. But can't you click recents in the sidebar and then run your search there? That at least sorts through the recent stuff.

**Comment by jgoldgh** [comment]
Hi JosephMcc,

This is a new machine so...no recent list. There are ways to get around the problem. I installed the gnome search tools and that got around it.  It's still an issue though.  I assume that the Nemo developers want Nemo to have basic search functionality. As it is, they don't so I thought I'd let them know.  It's up to them if they want to fix it or not.  I'm just trying to do my part.

**Comment by icarter09** [comment]
@jgoldgh are you still experiencing this issue on the latest version of nemo?
