### ISSUE TITLE
Scrolling shortcut-combos

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1508]
currently lacking/annoying when in huge folder and have to jump to
folder-file-boundary to go to newest/oldest files/folders

also in mswin, shift+scroll-bar click does jump-to
and right-click returns menu,
(what about options to jump to folder-file boundary , page/line up/down, to top/bottom)

also lacks ubuntu-hybrid scrollbar/buttons-functionality or ms-win middle-mouse-click autoscroll joystick-like capability

count this be implemented

also scrolling-positions changes arent undone
when dragging scroll-bar horizontally-far enough (if vertical scrollbar, perpendicular to-the-left)
and esc key doesnt work

also what about 
[shift | ctrl | alt | meta]+ [left | middle | right] scroll-bar combos?
what about pie-menus, or hover/swype ?

also what about mini-scroll-whole-document view
similar to sublime-text's or atom-addon or firefox findbar-tweak_addon/greasemonkey-script?

**Comment by icarter09** [comment]
@cmrdt are you still experiencing this issue on the latest version of nemo?
