### ISSUE TITLE
Absent files are displayed.

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/nemo#1509]
Hello.

There are several temporary files displayed in Nemo, but when you click on them, it'll say that they are absent:
![2017-05-30 19-00-39](https://cloud.githubusercontent.com/assets/12682937/26592787/7fc844a8-456a-11e7-8c80-a88942f5978e.png)
This files appear when I work with Xed (seems, it creates temporary saves here).

To update folder I need every time go to previous folder, than go to current one (or to add update button).
It makes this files will be not displayed.

System, on which bugs are present:
- Debian Sid  (Nemo 3.2.2)
- Linux Mint 18.1 (Nemo 3.2.2)
Almost all folders (including this), in which I work are or mounted to /home from "Storm" disc, or are placed on "Storm" disk directly. This is 1.5 Tb Seagate disc with primary ntfs partition on all 1.5 Tb space.

Best regards,
Vladislav

**Comment by feren** [comment]
You could also refresh BTW (F5)

**Comment by icarter09** [comment]
@vlad0337187 are you still experiencing this issue on the latest version of nemo?

**Comment by vlad0337187** [comment]
@icarter09 , didn't met it for a long time, if I'll be able to reproduce it again - will write here.
