### ISSUE TITLE
Feature Request: Quicker toggle between location entry

### ISSUE THREAD

**Issue by legolord208** [linuxmint/nemo#1514]
So, you know the Location Entry Toggle?
![image](https://cloud.githubusercontent.com/assets/12830969/26820273/95345ccc-4aa2-11e7-8498-d7d2cae02b87.png)

Well, it would be awesome if pressing *anywhere* outside, for example
![image](https://cloud.githubusercontent.com/assets/12830969/26820422/0e7e207c-4aa3-11e7-82c4-d008e791cb74.png)

would toggle it and focus, but also untoggle it once you are done.

**Comment by leigh123linux** [comment]
I don't see any need for this.

**Comment by JosephMcc** [comment]
Yeah, I don't want random things happening when I click on nothing in the toolbar.
