### ISSUE TITLE
Feature Request : Automatically detect images to use as custom folder icons

### ISSUE THREAD

**Issue by Chronigan** [linuxmint/nemo#1518]
I have a lot of photos stored on a network share and I like having an individual icon for each folder to tell me what is in it. I was thinking it would be great if Nemo could automatically detect what I wanted to use for the icon, say an image file named .folder.icon , and apply it to that folder as well as add it to the icon cache. This would make it much easier for different computers that use the share to display the same unique icons.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
