### ISSUE TITLE
[Feature Request] Option to Span Desktop BG Across Monitors

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1519]
Basically, what the title says, I'm just surprised this isn't already in Nemo on Linux Mint, especially with the advent of dual/triple-monitor-wallpapers and such...

**Comment by JosephMcc** [comment]
Nemo has nothing to do with this and there is already a spanned option in cinnamon-settings backgrounds.

**Comment by feren** [comment]
@JosephMcc Odd, when a buddy of mine tried it with his two monitors and a dual-monitor BG, it only spanned on one screen, rather then around both
