### ISSUE TITLE
Transfers show wrong speed and estimates

### ISSUE THREAD

**Issue by m-sundman** [linuxmint/nemo#1522]
The transfer speed is apparently calculated as an average since the transfer started, not showing changes in the speed and ignoring such changes in the time estimate.
It's actually even worse, the average is calculated since the transfer was **_enqueued_**, so even with a constant speed any transfers that have been waiting in the transfer queue will have **grossly incorrect** speed and time estimate. (E.g., I'm currently moving a file showing a speed of 20 kB/sec although my transfer speed is, and has constantly been, over 2000 kB/sec, so nemo shows 100 times less than reality.)

**Comment by m-sundman** [comment]
I'm currently using 3.2.2, but this issue has plagued nemo since forever, afaik.

**Comment by xenopeek** [comment]
Considering the age of this issue closing it. If this issue still affects you with Nemo 4.6.4 on Linux Mint 20 this can be reopened.

**Comment by najamelan** [comment]
@xenopeek I can confirm this issue is still happening exactly as described by OP in version 4.6.5 and is rather poor UX. I think shown speed should be either actual speed, or if that is to jittery or unreliable, maybe average the last 5s at most.
