### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [linuxmint/nemo#1523]
nemo-3.4.3:

	prefix:                 /usr
	source code location:	.
	compiler:		gcc
	libexif support:	yes
	libexempi support:	yes
	Tracker support:	no

        debugging support:      yes
	nemo-extension documentation: no
	nemo-extension introspection: yes

make  all-recursive
make[1]: Entering directory '/home/solaraquarion/build/nemo-git/src/nemo'
Making all in eel
make[2]: Entering directory '/home/solaraquarion/build/nemo-git/src/nemo/eel'
  CC       eel-accessibility.lo
  CC       eel-art-extensions.lo
  CC       eel-canvas.lo
eel-canvas.c: In function ‘eel_canvas_item_grab’:
eel-canvas.c:869:2: error: ‘gdk_display_get_device_manager’ is deprecated: Use 'gdk_display_get_default_seat' instead [-Werror=deprecated-declarations]
  manager = gdk_display_get_device_manager (display);
  ^~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:171:20: note: declared here
 GdkDeviceManager * gdk_display_get_device_manager (GdkDisplay *display);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eel-canvas.c:870:2: error: ‘gdk_device_manager_get_client_pointer’ is deprecated [-Werror=deprecated-declarations]
  device = gdk_device_manager_get_client_pointer (manager);
  ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkdisplay.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
/usr/include/gtk-3.0/gdk/gdkdevicemanager.h:44:14: note: declared here
 GdkDevice *  gdk_device_manager_get_client_pointer (GdkDeviceManager *device_manager);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eel-canvas.c:872:2: error: ‘gdk_device_grab’ is deprecated: Use 'gdk_seat_grab' instead [-Werror=deprecated-declarations]
  retval = gdk_device_grab (device,
  ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkdnd.h:33:0,
                 from /usr/include/gtk-3.0/gdk/gdkevents.h:34,
                 from /usr/include/gtk-3.0/gdk/gdkdisplay.h:31,
                 from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
/usr/include/gtk-3.0/gdk/gdkdevice.h:230:15: note: declared here
 GdkGrabStatus gdk_device_grab        (GdkDevice        *device,
               ^~~~~~~~~~~~~~~
eel-canvas.c: In function ‘eel_canvas_item_ungrab’:
eel-canvas.c:912:2: error: ‘gdk_display_get_device_manager’ is deprecated: Use 'gdk_display_get_default_seat' instead [-Werror=deprecated-declarations]
  manager = gdk_display_get_device_manager (display);
  ^~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:171:20: note: declared here
 GdkDeviceManager * gdk_display_get_device_manager (GdkDisplay *display);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eel-canvas.c:913:2: error: ‘gdk_device_manager_get_client_pointer’ is deprecated [-Werror=deprecated-declarations]
  device = gdk_device_manager_get_client_pointer (manager);
  ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkdisplay.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
/usr/include/gtk-3.0/gdk/gdkdevicemanager.h:44:14: note: declared here
 GdkDevice *  gdk_device_manager_get_client_pointer (GdkDeviceManager *device_manager);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eel-canvas.c:916:2: error: ‘gdk_device_ungrab’ is deprecated: Use 'gdk_seat_ungrab' instead [-Werror=deprecated-declarations]
  gdk_device_ungrab (device, etime);
  ^~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkdnd.h:33:0,
                 from /usr/include/gtk-3.0/gdk/gdkevents.h:34,
                 from /usr/include/gtk-3.0/gdk/gdkdisplay.h:31,
                 from /usr/include/gtk-3.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkprivate.h:28,
                 from eel-canvas.c:69:
/usr/include/gtk-3.0/gdk/gdkdevice.h:239:15: note: declared here
 void          gdk_device_ungrab      (GdkDevice        *device,
               ^~~~~~~~~~~~~~~~~
eel-canvas.c: In function ‘eel_canvas_draw_background’:
eel-canvas.c:3276:2: error: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Werror=deprecated-declarations]
  gtk_style_context_get_background_color (style_context, GTK_STATE_FLAG_NORMAL, &color);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkicontheme.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtk.h:123,
                 from eel-canvas.c:70:
/usr/include/gtk-3.0/gtk/gtkstylecontext.h:1201:6: note: declared here
 void gtk_style_context_get_background_color (GtkStyleContext *context,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:768: eel-canvas.lo] Error 1
make[2]: Leaving directory '/home/solaraquarion/build/nemo-git/src/nemo/eel'
make[1]: *** [Makefile:512: all-recursive] Error 1
make[1]: Leaving directory '/home/solaraquarion/build/nemo-git/src/nemo'
make: *** [Makefile:441: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mtwebster** [comment]
Assuming you are using autogen to configure, try adding `--enable-compile-warnings=yes` to the autogen call.
