### ISSUE TITLE
Bring back desktop icons for other desktop environments

### ISSUE THREAD

**Issue by Tank-Missile** [linuxmint/nemo#1525]
In the latest couple of releases, the functionality of the file manager handling the desktop icons is now gone. This makes it impossible for the icons to appear in other desktop environments such as XFCE. I understand it's a "Deprecated" feature from reading the "show-desktop-icons" dconf setting, but I don't see what is wrong with having it in. I find Nemo to be the most robust file manager to use despite some crashes (if I still get these crashes I'll submit another issue), and it far exceeds Thunar. If this feature can not be added directly back into Nemo, perhaps an extension would suffice?

**Comment by feren** [comment]
@Tank-Missile It's now a separate process called 'nemo-desktop'
You might as well Close the issue, it'd save Joseph from doing so...

**Comment by Tank-Missile** [comment]
Oh, my apologies! I was not aware of this change. The new command works perfectly.

**Comment by mtwebster** [comment]
You should be able to have nemo manage the desktop still. That dconf key still works (I think we un-deprecated it and never removed the note). Just make sure nothing else tries to manage the desktop besides nemo.

**Comment by Tank-Missile** [comment]
The only other thing "managing the desktop" is the compiz wallpaper plugin, and that does prevent nemo from showing the desktop, but I put the blame on the compiz devs for not providing a WM_CLASS for it so nemo can ignore it.
