### ISSUE TITLE
[Feature Request] If No Desktop Handler is found running on any DE, launch Nemo Desktop on Nemo Start Proceedure

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1526]
Sorry if this has already been asked, but this'd be useful for a large number of reasons, including Nemo on other DEs where they'd then leave users confused as Nemo would give them a Desktop before 3.4 in this case, while, now, it suddenly doesn't because of the new process and what-not...

Basically, do what the title says as a feature possibly added to Nemo

**Comment by feren** [comment]
The key thing here is AUTOMATICALLY though, as it's all well in saying it can be done manually, but what if someone doesn't know if nemo-desktop is now a thing? They'd probably end up reporting an issue in vain here as a result or something else...

**Comment by leigh123linux** [comment]
I think I can speak for the other cinnamon devs on this.

1. We're not interested in adding support for other DE's, if users want to use nemo outside of cinnamon they can enable it themselves.
2. auto-starting in other DE's has caused us enough issues in the past.

**Comment by feren** [comment]
Ok, that's a good enough point.
