### ISSUE TITLE
[Feature Request] Before letting a user choose a custom icon for Folders & Files, let them choose from the current icon set's icons first

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1527]
Basically, this feature can be found in KDE, and is surprisingly useful, as this would mean you'd be able to set a certain icon in an Icon Set, with that icon changing to the icon chosen in the current icon set, with it changing depending on icon set, rather than just being only able to choose a single icon, which wouldn't then adapt to the icon set if one was to change their icon set. Also, of course, have an option in the System Icon chooser dialog to go custom icon too if not have it directly below where the current 'Change Icon' button is.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
