### ISSUE TITLE
Syntax-highlighting conditional/color/value/graph formatting

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1528]
if folders/labels (e.g. detail-view) could look different also depending on 

- file size, esp empty files look different, (GB MB..)
- age (day,week, month,year), maybe time-of-day, day-of-week, season
- file-permissions (read,write,execute..)
- rating?
- compressed files

(cut-pending files already apply opacity~transparent)

maybe format numbers and dates so that significant-digits are bolder, year,month,date look different (weak-color tinting?)
make less irrelevant info less prominent , reduce clutter  (maybe even making the `M` in AM/PM fainter)

**Comment by JosephMcc** [comment]
This would be a mess given the huge number of different themes and styles people use. Just don't think it adds enough to deal with all the issues we'd get from it.
