### ISSUE TITLE
Icons for certain file types : executables

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1529]
whether for certain files e.g. `.exe` (windows)
and the relevant -> android mac ios  
- make them more identifiable

? avoid adding whether if would cause stability/performance/security problems

- but windows apps gnome-thumbnailer seems to work

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
