### ISSUE TITLE
Regenerate thumbnails when zooming in

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo#153]
Currently, the small thumbnails are just rescaled(a lot of pixelation, especially for svgs where you want sharp edges.) when a user zooms in(all views).

Pro's
*Sharp thumbnails

Con's
*Regeneration overhead when zooming in(but average users rarely zoom in)
*Would be super slow for large folders.

**Comment by icarter09** [comment]
@gauravjuvekar is this still an issue?

**Comment by gauravjuvekar** [comment]
@icarter09  Seems to be fixed atleast for pngs
