### ISSUE TITLE
Feature request: Faster file copying without asking for 'merge'

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#1530]
When using Windows I was annoyed with the OS asking if I wanted to replace files when copying,

I was hoping you here could value this insight.

When copying an exact file to another directory, asking if you want to replace it is quite pointless as far as I can see,

If the files have exact same size, same content, same name, then they already are the same file, there is no need to ask, right?

clicking on merge dir, then merge file, then 'do this for all files' then clicking merge again is a waste of time.

Just check if they are the same file and just delete the first or overwrite (which would be pointless) automatically, and continue to the next file!

thanks for reading,

this has annoyed me for years in Windows and I recently switched to mint, and I like it, I hope you could add this little improvement, or at least give the option to copy files this way in some menu somewhere.

**Comment by osmand** [comment]
reply?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
