### ISSUE TITLE
Hightlighted element hardly readable after dual-pane switch

### ISSUE THREAD

**Issue by Piiit** [linuxmint/nemo#1531]
_Not sure if this is the right place, could also be a Mint-Y theme issue._

![auswahl_065](https://user-images.githubusercontent.com/6096063/27509579-abf48600-5900-11e7-918e-4a7867c89eb0.jpg)

**How to reproduce?**
- Open nemo with dual-pane
- Select an element (folder or file)
- click on the other pane

The selected element is hardly readable, white font-color on lightgray background.

**Comment by JosephMcc** [comment]
> Not sure if this is the right place, could also be a Mint-Y theme issue.

Thats fairly easy to test. Just try it with another theme.

It does look to be a theme issue. I'll look at fixing it.

**Comment by feren** [comment]
Looks like a missing Selected Status BG to me...
