### ISSUE TITLE
Cinnamon 3.4.2: assertion failed: (!container->details->auto_layout)

### ISSUE THREAD

**Issue by seigneurfuo** [linuxmint/nemo#1533]
**Description!**
Nemo-desktop doesn't want to start: no icons, no contextual menu.

**System configuration:**
Host: manjaro Kernel: 4.11.6-1-MANJARO x86_64 (64 bit)
Desktop: Cinnamon 3.4.2  Distro: Manjaro Linux

**nemo-desktop** on a terminal:
ERROR:nemo-icon-view-grid-container.c:1167:nemo_icon_view_grid_container_finish_adding_new_icons: assertion failed: (!container->details->auto_layout)
Abandon (core dumped)

**Comment by leigh123linux** [comment]
Fixed  by https://github.com/linuxmint/nemo/commit/ab5185ba5a8744d738284ad83402dbc44962511c

P.S you forgot to add nemo version!
