### ISSUE TITLE
Can nemo actions be made to work with filenames containing quotes?

### ISSUE THREAD

**Issue by SuffolkPunch** [linuxmint/nemo#1534]
Hello,

Can nemo actions be made to work with filenames containing quotes?

I have created the following nemo action:  
```
    [Nemo Action]
    Name=Show bitrate
    Comment=Show the bitrate of the selected mp2, mp3, m4a, flac and ogg audio files
    EscapeSpaces=true
    Exec=/usr/bin/gnome-terminal -e "/home/mjw/Scripts/nemo-ShowBitrate %F"
    Selection=notnone
    Extensions=nodirs;
    Dependencies=avprobe
    Extensions=mp2;mp3;m4a;flac;ogg;
```
The problem I get is that if there's a quote anywhere in the full filename of an audio file I select to apply this action to, then the action doesn't do anything. It doesn't even call the executable defined in the action because no terminal pops-up.

As an example the following filename has a single quote, and the script fails on it.
`/home/mjw/Videos/The Handmaids Tale/The Handmaid's Tale_e05_Faithful_no trailer.mp2`

However, if I remove the quote, then the action works and produces the following output.

```
***************************************************
*         In the current folder:                  *
*       Show the bitrate of the selected          *
*   mp2, mp3, m4a, flac, and ogg audio files      *
*                                                 *
***************************************************

1 audio file selected in /home/mjw/Videos/The Handmaids Tale

The Handmaids Tale_e05_Faithful_no trailer.mp2
   format_name=mp3
   duration(s)=3045.408000
   bit_rate(bps)=192000


Press any key to close shell...
```

Is this a known feature of nemo_actions? A known bug? Or maybe there's a setting for nemo_action (similar to EscapeSpaces=true) which allows it to escape single quotes and pass across the list of selected filenames?

**Comment by SuffolkPunch** [comment]
Updated with nemo_action debug output, obtained in a terminal by running the commands:
`nemo --quit
 
NEMO_ACTION_VERBOSE=1 nemo
`

I changed my nemo_action to the following to see if Quote=backticks would help.:
```
[Nemo Action]
Name=Show bitrate
Comment=Show the bitrate of the selected mp2, mp3, m4a, flac and ogg audio files
EscapeSpaces=true
Quote=backtick
Exec=/usr/bin/gnome-terminal -e "/home/mjw/Scripts/nemo-show-bitrate %F"
Selection=notnone
Extensions=nodirs;
Dependencies=avprobe
Extensions=mp2;mp3;m4a;flac;ogg;
and, once again, the action fails to even run my script 'nemo-show-bitrate' for filenames with a single quote in them.
```
I called this nemo-action in the folder 
`/media/mjw/Music/Audio/recorded/Ackroyd (Peter). The Fiery World/`
where there is an audio file
`tfw_0'1.mp3`
So the full filename of the mp3 file is
`/media/mjw/Music/Audio/recorded/Ackroyd (Peter). The Fiery World/tfw_0'1.mp3`
which contains 4 single spaces and 1 single quote.

Got debug data on what happens when the nemo_action is called:
```
Action Tooltip: Show the bitrate of the selected mp2, mp3, m4a, flac and ogg audio files
Action Spawning: /usr/bin/gnome-terminal -e "/home/mjw/Scripts/nemo-show-bitrate `/media/mjw/Music/Audio/recorded/Ackroyd\ (Peter).\ The\ Fiery\ World/tfw_0'1.mp3`"
Failed to parse arguments: Argument to "--command/-e" is not a valid command: Text ended before matching quote was found for '. (The text was '/home/mjw/Scripts/nemo-show-bitrate `/media/mjw/Music/Audio/recorded/Ackroyd\ (Peter).\ The\ Fiery\ World/tfw_0'1.mp3`')
```
This shows that all spaces in the selected filename are escaped correctly, but bash complains that text ended before a matching single quote was found. It seems that the single quote in the audio filename is _still_ treated by bash as a syntactical unit rather than a simple character, despite Quote-backtick wrapping the full filename in a pair of backticks!

**Comment by ManIVIctorious** [comment]
Have you tried quote=single?

**Comment by SuffolkPunch** [comment]
> Have you tried quote=single?

Have just tried that, prompted by your comment.

The NEMO_ACTION_VERBOSE output follows:


```
Action Label: Show bitrate
Action Tooltip: Show the bitrate of the selected mp2, mp3, m4a, flac and ogg audio files

Action Spawning: /usr/bin/gnome-terminal -e "/home/mjw/Scripts/nemo-show-bitrate '/media/mjw/Music/Audio/recorded/Ackroyd\ (Peter).\ The\ Fiery\ World/tfw_0'1.mp3'"

Failed to parse arguments: Argument to "--command/-e" is not a valid command: Text ended before matching quote was found for '. (The text was '/home/mjw/Scripts/nemo-show-bitrate '/media/mjw/Music/Audio/recorded/Ackroyd\ (Peter).\ The\ Fiery\ World/tfw_0'1.mp3'')
```
`
You can see that Quote=single wraps the selected audio filename in a pair of single quotes, but bash still trips on the single quote in that filename!

**Comment by mtwebster** [comment]
Just so I can compare apples to apples, can you share your bitrate script?

I've added escaping of quotes to the file path, but depending upon how the action Exec is constructed, it's still a bit tricky, and i'd like to reproduce/solve the issue exactly as you present it as well.

Thanks

**Comment by SuffolkPunch** [comment]
Thanks!
Here's a listing of the shell script 'nemo-show-bitrate'

```
#!/bin/bash
echo "***************************************************"
echo "*         In the current folder:                  *"  
echo "*       Show the bitrate of the selected          *"
echo "*   mp2, mp3, m4a, flac, and ogg audio files      *"
echo "*                                                 *"   
echo "***************************************************"
echo ""

# This script is called by nemo_action '/usr/share/nemo/actions/show-bitrate.nemo_action'
# which passes as arguments the selected audio files. E.g.
# $@ = /home/mjw/Videos/Continuum/Continuum_s2e08_Second Listen_no trailer.mp2

indent() { 
    # if you pipe a multi-line string into indent it adds 3 spaces at the start of each line
    # and adds the appropriate units after 'duration' and bit_rate'
    sed 's/^/   /; s/duration/duration(s)/; s/bit_rate/bit_rate(bps)/'
}

for basename in "$@"
# basename = filename.extension, where 'filename' includes the path to the current folder
do
    PWD=${basename%/*} # deletes shortest match of '/*' from end of basename string
done

if [[ "$#" -ne 1 ]]
    then
        echo "$# audio files selected in $PWD"
    else
        echo "$# audio file selected in $PWD" 
fi

echo ""

for basename in "$@"
do
    filename=${basename##*/} # deletes longest match of '*/' from start of basename string
    echo "$filename"
    avprobe -show_format "$basename" 2> /dev/null | egrep -h "format_name|duration|bit_rate" | indent
    # 2> /dev/null causes any error messages output to stderr to be rediected to /dev/null (ie thrown away)
    echo ""
done

echo ""
read -n1 -r -p "Press any key to close shell..." key

exit 0
```

**Comment by SuffolkPunch** [comment]
Hi Micheal,

Any further progress with this issue?

Regards,

martin

**Comment by mtwebster** [comment]
I've got a working branch, but I'm having trouble with a solution that will accept both single and double quotes in a filename.

The problem I'm running into is that I think items inside the -e command could need escaped twice.  Other cases of running commands (such as launchers, etc..) usually offer an option "run in terminal" - i think this would eliminate the extra layer, and possibly simplify things.

As soon as I can get some sort of acceptable patch I'll post it so we can try it out.

**Comment by SuffolkPunch** [comment]
That's encouraging.  I guess I'll need to learn how to apply a patch!

**Comment by mtwebster** [comment]
The pr I just added seems to work well.  I altered the action to:

```
[Nemo Action]

Name=Show bitrate
Comment=Show the bitrate of the selected mp2, mp3, m4a, flac and ogg audio files
EscapeSpaces=true
Exec=/home/mtwebster/.local/share/nemo/scripts/test %F
Selection=notnone
Extensions=nodirs;
Dependencies=avprobe;
Extensions=mp2;mp3;m4a;flac;ogg;
Terminal=true
```

And it handles any combination of single or double quotes in a file name.

You can try the following to test if you'd like:

First, enable source repositories (start the Software Sources tool and
check "Enable source code repositories", then click the reload/refresh
button.  Finally, close the tool.

Then,

```
sudo apt-get build-dep nemo
git clone git@github.com:mtwebster/nemo.git
cd nemo
git checkout action-escape-quotes
dpkg-buildpackage

cd ..
sudo dpkg -i *.deb
```

Make sure to kill any existing nemo and nemo-desktop processes.

If you run into any issues, let me know.

**Comment by SuffolkPunch** [comment]
Thanks!

Ok - have enabled source code repos.
Never having used git before, have just installed it using Synaptic.
Next steps:
1.  Try some simple git training lessons, first.
2. After that, do I need to be in a specific directory when I run the commands you list? Or do I just pick a convenient place in my home directories?
3.If I need to reverse this patch, how do i do that?

**Comment by SuffolkPunch** [comment]
Micheal,

I'm tripping-up at the step
`git clone git@github.com:mtwebster/nemo.git`
This elicits the following response:
```
Cloning into 'nemo'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Help!

**Comment by mtwebster** [comment]
Ah sorry. Try https://github.com/mtwebster/nemo.git

**Comment by Nemesis77swe** [comment]
Reopening this?
isn't this issue still active? I'm having so much issues with filenames with an ' in, nemo seems to escape it like this:   '/tmp/example/we\'\''re testing file 1.txt'
