### ISSUE TITLE
copying moving files - verify

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1537]
when nemo crashes when copy/pasting
or if write-protect or volume dirty

how it is to be ordered depending
copying/monitoring on 
- same partition
- same disc different partition
- what format and support level (ext4, FAT32 ..)
- benchmark stats of drive and lifespans (read write speeds, cluster size), whether it's HDD, SSD, how full it is, fragmented?

- management of file-name collisions
- too long file-folder names?
- UI to deal with merge and 
  - make more evident which file newer, bigger, not-corrupt (color coding, symbols, esp if many prompts, fatigue/intensive load, risk of error)
  - logic tables, rule-sets
 - ?avoid replacing with empty files

 - do same for all, if's, just this folder, rename|keep|replace

 - checksum verify esp if long time & complex move..

- ideas similar to fastcopy, ultracopier, tera-copy?.

**Comment by icarter09** [comment]
@cmrdt are you still experiencing this issue on the latest version of nemo?
