### ISSUE TITLE
Can't reopen/restore file transfer window after closing it (file transfers aren't canceled either)

### ISSUE THREAD

**Issue by satoshimatos** [linuxmint/nemo#1538]
Build:
Arch Linux
GNOME 3.24.2
nemo 3.4.4

---

Upon transferring large files the "file transfer window" pops up, the one which gives me information as to how much data is being transferred, the rate at which the data is being transferred and the ETA. I accidentally closed the window by clicking X and I could find no way of restoring/reopening that window, despite the fact that the transfer was still ongoing, since I kept refreshing the folders to which the files were being transferred and their size kept increasing.
Alt+tab/Ctrl+tab/Alt+~ didn't work either. I looked at the "View" section on the top menu bar and I also could not find a way to reopen the "file transfer window".
Am I missing something?

**Comment by ManIVIctorious** [comment]
Do you have the system tray disabled? Normally when you close the file transfer dialogue a tray icon gets launched which shows the progress and allows restoring

**Comment by friday** [comment]
I get this too. Gnome has no system tray any more and even with it enabled via shell extensions nothing shows in the tray.

Emptying trash will show the progress for files too (until the former has completed).

**Comment by xenopeek** [comment]
Nemo 4.6.4 on Linux Mint 20 Cinnamon shows a panel status icon when the progress window is closed:
![image](https://user-images.githubusercontent.com/21159972/85920072-d0f84180-b870-11ea-9c4c-513bf5858719.png)
The progress window can be restored by clicking on the status icon. On Gnome Shell you may have to add an extension to show tray icons.
