### ISSUE TITLE
There is still no GUI option to change the desktop grid size, and I can't locate the information on the hack

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1540]
Dear Developers

(1) When I tried out the beta of Mint 18.2., I learned that the size of the desktop grid was adjustable. I was pleased, because on the defaults, the columns of icons that I had on the right and left hand sides of the screen (respectively) got shifted towards the center of the screen.

Pre-18.2, my icons were like this:

![right](https://user-images.githubusercontent.com/9998846/27810484-7239faca-604a-11e7-969c-6c45252d1383.png)

and that is how I wanted them. After installing 18.2 - with its snap-to-grid feature - the icons ended up like this:

![wrong](https://user-images.githubusercontent.com/9998846/27810481-6d3154a6-604a-11e7-8d93-85d8d32aa3fa.png)

I read that it was hoped that there would be a GUI option to change the grid size. Upon installing the released version of 18.2, I discover that _the GUI option has yet to arrive_.

(2)

(2.1) It was not elementary to discover how to get the desired result i.e. shift the icons back to the screen-edges. Websearching reminded me that of the procedure. Viz.: Dconf editor, org -> nemo -> desktop -> reduce the 'horizonal-grid-adjust' value . Now, surely it can't be very hard to provide an option _within Nemo_ for this.

(2.2) Reducing the 'horizonal-grid-adjust' value truncates - pushes onto a second line - some of the filenames of the icon, whereas all I wanted to achieve was a reduced x offset. Or at least that can happen; I managed to find a value for `horizonal-grid-adjust` that put the icons where I wanted them and also did not truncate my filenames. The point, though, is that offset should be independent of truncation/text-wrapping.

**Comment by mtwebster** [comment]
Not exposing the adjustment settings was on purpose.  I'm not convinced it's the best way to go.  There is a lot more development to do with this and we may decide to let some desired text field size determine spacing, or try to become a bit more intelligent about evaluating available space on the screen.

As for being unable to fully occupy all the space - this is somewhat a limitation with the freedesktop standards regarding how client app toolkits (like gtk) communicate with window managers.  Only the primary monitor's true work area is available to nemo.  Any non primary monitor has some artificial padding applied to account for potential panel avoidance.

**Comment by ACinnamonUserInUK** [comment]
Thanks.

> As for being unable to fully occupy all the space - this is somewhat a limitation with the freedesktop standards regarding how client app toolkits (like gtk) communicate with window managers. Only the primary monitor's true work area is available to nemo. Any non primary monitor has some artificial padding applied to account for potential panel avoidance.

And yet, decreasing 'horizonal-grid-adjust' does reduce the left- and right-margins. But perhaps I misunderstand. Anyway, certainly it is desirable that: (1) this padding problem be fixed somehow; and - if this is a separate problem - (2) the icons could be spaced either as the user stipulates or in a predetermined way that is more intelligent than at present.

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
