### ISSUE TITLE
Dragging a group of icons slightly downwards results in a random arrangement of those icons

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1541]
If you point me towards some video recording software, then I can document this for you.

Mint 18.2.

**Comment by mtwebster** [comment]
`Ctrl-alt-shift-r`?

**Comment by leigh123linux** [comment]
Use the builtin video recorder.

**Comment by ACinnamonUserInUK** [comment]
I don't seem to have that software installed. Ctrl-atl-shift-r seems to do nothing. What's the name of the package, please?

**Comment by mtwebster** [comment]
It's built into Cinnamon - when you hit that, look for a small green bar and red dot in the lower right corner of the monitor, showing you're recording.  If not, check the hotkey - Keyboard->Shortcuts->System->Screenshots and recording.

The resultant file should be placed in ~ (.webm format) when you cancel it (by using the same hotkey).

**Comment by mtwebster** [comment]
I will mention, when not in auto-arrange mode (with just keep-aligned active), when dragging, you'll see a horizontal or vertical separator appear, depending on desktop orientation.  If you drop when it's active, it will 'insert' your selection into the desktop at that point, pushing any existing icons further along the arrangement order to make room.  Perhaps this is what you refer to?

**Comment by ACinnamonUserInUK** [comment]
The recorder: ooh, marvellous!

I had no idea - and had the shortcut turned off. Video attached. Quite possibly the behaviour has the explanation you suggest. If so, I find the behaviour slightly counter-intuitive. Also, it would be delightful were CTRL-Z to return the icons to their previous position.

Github is rejecting the video format. I'll try zipping it. Ah, OK, that seemed to work:

[cinnamon-20170704-1.zip](https://github.com/linuxmint/nemo/files/1120778/cinnamon-20170704-1.zip)

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
