### ISSUE TITLE
Cannot generate thumbnails for MP4/MKV/AVC video files and cannot preview them either

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1542]
Hi all,
I'm running Cinnamon under Arch and I've noticed that I cannot preview MP4/MKV files that are encoded with AVC and I don't see their thumbnails either. When I hit space bar to preview, I can only hear the sound, for example. I can preview Webm files just fine (I know that .wmv also fails but I don't care about that).

When I run nemo from the terminal, I see these kinds of error messages:

```
(nemo:4886): CinnamonDesktop-WARNING **: Error creating thumbnail for file:///home/ns/Downloads/video1.mp4: Unrecognized image file format
```

Am I missing some kind of a package that would allow me to see thumbnails and previews for non-free formats?

My system info: `Kernel: 4.11.7-1-ARCH x86_64 (64 bit) Desktop: Cinnamon 3.4.3  Nemo: 3.4.5 Distro: Arch Linux`
Thanks!

**Comment by mtwebster** [comment]
I'm not sure what the best program is for Arch - we use xplayer and xreader in Mint, they provide thumbnailers for most formats.

Possibly this may help? https://bbs.archlinux.org/viewtopic.php?pid=1699194#p1699194

**Comment by nick-s-b** [comment]
@mtwebster Thank you! `pacman -S gst-libav gst-plugins-ugly` solved it. 
`
