### ISSUE TITLE
Downloaded file sits atop existing icon

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1543]
Cinnamon 3.4.3
Distribution - Mint 18.2
 Intel Mobile GM965/GL960 Integrated Graphics Controller
64 bit

**Issue**

I downloaded a pdf with Firefox and this was the result:

![image](https://user-images.githubusercontent.com/9998846/27834646-43a20054-60c7-11e7-9632-5d42f5925a3e.png)

I have the horizontal grid set to 0.75 and I am using the grid but not auto-arrangement.

Pressing F5 did not remove the superposition.

**Steps to reproduce**

Try configuring the Nemo desktop such that it is as I described above, and then downloading a file.

**Expected behaviour**

The new icon should not overlap any existing icon.

**Other information**

Screen resolution: 1280 x 800 (16:10)

EDIT: I discover that turning off the 'align to grid' function makes no difference. Nor does moving the icon that gets the new icon on top of it - in that latter case, the new icon appears atop of _another_ icon! Arg!

**Comment by mtwebster** [comment]
I can't reproduce this in any type of layout.

Can you provide exact steps, also how many monitors you have (if > 1)

**Comment by CottonEaster** [comment]
I have only one monitor.

Steps: well, at present, any icon added to my desktop via download - in Firefox or Chrome - ends up sitting atop another icon. The same result obtains when I open a terminal via Nemo and type `touch ~/Desktop/test`. By contrast, creating a new file via right-clicking the desktop seems to position the new icon by reference to where the mouse pointer is. Moreover, if I move the overlapped icon - which is the bottom-most icon in a column of icons on the right-hand side of the screen, then new icons end up overlapping the next icon up. That is - see the screenshot I supplied - the 'Scripts' icon ends up the one being overlayed. 

```
~ $ dconf dump /org/nemo/
[plugins]
disabled-actions=['mint-sha256sum.nemo_action', 'add-desklets.nemo_action', 'nemo-sendto-clamtk.nemo_action', 'mount-archive.nemo_action', 'blueman-sendto.nemo_action', 'mint-artwork-cinnamon-thunderbird.nemo_action']
disabled-extensions=['NemoTerminalProvider+NemoPython', 'PastebinitExtension+NemoPython', 'NemoDropbox', 'EvPropertiesPlugin', 'NemoCompareExtension+NemoPython', 'SeahorseNemo', 'NemoFilenameRepairer', 'ColumnExtension+NemoPython', 'ChangeColorFolder+NemoPython']

[window-state]
side-pane-view='places'
sidebar-width=236
start-with-status-bar=true
my-computer-expanded=false
geometry='1242x610+13+51'
sidebar-bookmark-breakpoint=1
maximized=true
start-with-sidebar=true

[sidebar-panels/tree]
show-only-directories=true

[preferences]
show-reload-icon-toolbar=true
show-full-path-titles=true
quick-renames-with-pause-in-between=false
show-advanced-permissions=false
start-with-dual-pane=false
show-home-icon-toolbar=true
show-new-folder-icon-toolbar=false
close-device-view-on-device-eject=true
show-compact-view-icon-toolbar=false
tooltips-in-icon-view=true
executable-text-activation='ask'
show-up-icon-toolbar=true
size-prefixes='base-10'
tooltips-show-path=false
enable-delete=true
show-open-in-terminal-toolbar=true
default-sort-order='name'
default-folder-viewer='icon-view'
show-label-search-icon-toolbar=true
show-icon-text='never'
show-directory-item-counts='never'
context-menus-show-all-actions=true
date-format='informal'
last-server-connect-method=5
show-computer-icon-toolbar=true
show-image-thumbnails='always'
show-location-entry=true
show-hidden-files=true
show-places-in-to-menus=false
thumbnail-limit=uint64 3145728

[desktop]
text-ellipsis-limit=3
show-desktop-icons=true
computer-icon-visible=false
horizontal-grid-adjust=0.75
home-icon-visible=true
trash-icon-visible=true
network-icon-visible=false
show-orphaned-desktop-icons=false
font='Noto Sans UI 11'
volumes-visible=true

[compact-view]
default-zoom-level='smaller'

[icon-view]
captions=['none', 'none', 'none']
default-zoom-level='standard'
default-use-tighter-layout=false
labels-beside-icons=false

[list-view]
default-zoom-level='smaller'

```

**Comment by CottonEaster** [comment]
I have the problem no longer - now that I have Mint 19. Good job!
