### ISSUE TITLE
Icons disappear with autologin - Lightdm (2 monitor)

### ISSUE THREAD

**Issue by Timmy93** [linuxmint/nemo#1544]
```
 * Nemo version (nemo --version) - nemo 3.4.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.2 - Cinnamon
 * Graphics hardware *and* driver used - Intel i5 5200u integrated gpu and default driver
 * 32 or 64 bit - 64bit
 ```

**Issue**
There are no icons on the desktop at startup when is enabled autologin (This guide: https://wiki.archlinux.org/index.php/LightDM#Enabling_autologin).

1. If I use only my laptop monitor (1366x768) I have no problem, icons available.
2. If I plug my second monitor (1920x1080) and then I turn on the pc, icons NOT available.
3. If I turn on the pc and then I plug my second monitor (1920x1080), icons available.
4. If I remove the HDMI when the pc is ON, the screen becomes black on both the external monitor and the laptop one.

**Steps to reproduce**
1. Find a second monitor (1920x1080 in my case) and set it as the ONLY ONE to use when is plugged.
2. Enable autologin (you must use lightdm), turn off the PC.
3. When the PC is off plug the monitor and turn the PC on.
4. When it finish to boot the desktop is empty but everything works without problem

**Expected behaviour**
[...]
3. When it finish to boot there are the icons on the desktop.

**Other information**
Workaround: Press Ctrl+Alt+Backspace, you will find all the icons in this way.
Previously with MDM this problem didn't exist.

**Comment by leigh123linux** [comment]
Maybe this would help

https://ubuntuforums.org/showthread.php?t=2321445

**Comment by Timmy93** [comment]
Thank you @leigh123linux this simple command solved my problem!

It was enough to copy the config file in this way:
`sudo cp ~/.config/monitors.xml /var/lib/lightdm/.config/`

**Comment by Timmy93** [comment]
Thank you @leigh123linux this simple command solved my problem!

It was enough to copy the config file in this way:
`sudo cp ~/.config/monitors.xml /var/lib/lightdm/.config/`
