### ISSUE TITLE
When using Nemo's search field, typing space after the first term hides the term and often crashes Nemo too

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1546]
```
 * nemo 3.4.5
 * windowed nemo
 * Distribution - Arch
 * nvidia 
 * 64 bit
 ```

**Issue**
When using Search, it's next to impossible to search for multiple search terms (or a phrase) in Nemo.

**Steps to reproduce**
Hit Ctrl+f to initiate search (or click on the looking glass)
Start typing a word. For example "first":
![first](https://i.imgur.com/UGzJdfo.png)
Press the space bar so you can search for multiple terms.
Type the first letter of the second word.
Your first word has now disappeared. 
![second](https://i.imgur.com/qUzT5Bl.png)
You have to click back into the field and even then, you might or might not be able to search for the second term. It might even crash.

**Expected behaviour**
You should be able to type in multiple words into the Search bar.
![fs](https://i.imgur.com/tHuUtfg.png)

**Other information**
A workaround is to type the phrase you want to search for somewhere else and then copy/paste it into Nemo's search field.

**Comment by mmirg** [comment]
I'm experiencing similar behavior as well with nemo frequently segfaulting when I try to search.  There doesn't seem to be any one particular sequence of events that triggers it, I can trigger it in a similar to fashion to nick-s-b but also sometimes by deleting letters in my search query and searching again or just by waiting with search open.  I tried launching nemo in verbose mode (NEMO_ACTION_VERBOSE=1 nemo?) but still only get "Segmantation fault" printed to the console upon a crash.
