### ISSUE TITLE
Nemo-desktop crashing when following link on the desktop

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1549]
```
Mint 18.2 Cinnamon 64 bit / Nemo 3.4.6
 ```
I let Cinnamon create with the account detail settings the file .face (here with the football) and created a link for that. I moved the link to the desktop.

The file opens after double-clicking it on the desktop fine and display correctly in Xviewer; so the file is not corrupted and also the link is proven to be correct.

Now I selected the command to follow the link to the original file.

Expected: A Nemo window for the containing folder gets opened. This works perfectly in Mint 18.

Issue: In Mint 18.2 the process nemo-desktop crashes, no Nemo window gets opened. Consequently all icons on the desktop vanish and the right click menu on the desktop is not available.
The only way to get this back is to launch in the command-line (alt-F2) nemo-desktop.

It appears, that after splitting between the processes nemo and demo-desktop the latter one is not able to launch a nemo-window and crashes because of this inability.

**Comment by joao-jeronimo** [comment]
Hello.
For me what happens is that nemo-desktop crashes at startup whenever I have any file in ~/Desktop.

When I have even a single file ou folder in ~/Desktop it says when started from terminal:
$ nemo-desktop 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 237, in mro
    return mro(cls)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 271, in mro
    for base in C.__bases__:
TypeError: get_background_items must return a sequence of Nemo.MenuItem
**
ERROR:../../gi/pygobject.c:969:pygobject_new_full: assertion failed: (tp != NULL)
Abortado

Thanks,
JJ
