### ISSUE TITLE
Horizontal icon spacing on HiDPI displays is too large (2x)

### ISSUE THREAD

**Issue by mtwebster** [linuxmint/nemo#1550]
_From @squared9 on July 8, 2017 10:12_

```
 * Cinnamon version 3.44
 * Distribution - Mint 18.2
 * Graphics hardware: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
                   intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20151010
 * 64 bit
 ```

**Issue**
On a HiDPI (in my case 3200x1800) display horizontal icon spacing with auto align is double of what I would expect - please see:
http://imgur.com/a/usVyR

**Steps to reproduce**
Just switch HiDPI on, make sure auto align is on and do e.g. auto-arrange or move icons manually.

**Expected behaviour**
Icon spacing should be either reduced or made configurable. Currently HiDPI desktop's usability regressed comparing to older Cinnamon.

**Other information**
Please do not turn on icon auto-arrange by default, it changes desktop one is used to without any reason.

_Copied from original issue: linuxmint/Cinnamon#6684_

**Comment by mtwebster** [comment]
_From @JosephMcc on July 8, 2017 10:58_

> Please do not turn on icon auto-arrange by default, it changes desktop one is used to without any reason.

Not trying to sound offensive but not knowing the reason doesn't mean there isn't one. Having it enabled by default was needed to make things work for people upgrading from a previous version.

**Comment by mtwebster** [comment]
The spacing can currently be adjusted using dconf-editor if desired. (`apt install dconf-editor`)

You can adjust `vertical-grid-adjust` and `horizontal-grid-adjust` in org.nemo.desktop.

This is not exposed in any UI at this time because the determinations for spacing may change as the new desktop is further developed.

As @JosephMcc mentioned, auto-arrange is turned on for transitional purposes, and easily turned off again, so I don't see this as an issue at this time.

**Comment by squared9** [comment]
Thanks!

FYI, setting horizontal-grid-adjust to 0.6, vertical-grid-adjust to 0.75 and icon size to 'larger' gives me a similar desktop as before upgrading.

**Comment by leigh123linux** [comment]
The OP has found a solution.
