### ISSUE TITLE
Desktop of 2nd monitor needs to be refreshed for icons to show there

### ISSUE THREAD

**Issue by mYnDstrEAm** [linuxmint/nemo#1553]
```
 * nemo 3.2.2
 * Debian 9.0 with Cinnamon
 * nvidia-driver
 * 64 bit
 * 2 monitors
 ```

**Issue**

When I start up my PC I have to first press F5 after clicking somewhere on the desktop of my 2nd monitor for icons to show there. Until then I can only see the wallpaper with no icons visible. I can see the icons of my 1st monitor without refreshing though.

**Expected behaviour**

The icons should show up after starting without having to do anything (e.g. via automatically refreshing at a certain point).

**Comment by Timmy93** [comment]
I can confirm that this happens also to me!

**Comment by mtwebster** [comment]
@Timmy93 what version of nemo?

**Comment by Timmy93** [comment]
@mtwebster That's my system:
Host: timmy-Lenovo-G50-80 Kernel: 4.8.0-58-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.4.4 (Gtk 3.18.9-1ubuntu3.3) dm: lightdm Distro: Linux Mint 18.2 Sonya
Nemo: 3.4.6

**Comment by xenopeek** [comment]
I couldn't reproduce this in Nemo 4.6.4 on Linux Mint 20 Cinnamon. After log in it shows icons on 1st and 2nd display where I put them on previous boot (with auto-arrange off).
