### ISSUE TITLE
[Feature Suggestion] New tool to include with Nemo

### ISSUE THREAD

**Issue by Chronigan** [linuxmint/nemo#1555]
I've written a little program that I am finding useful and thought I would share it. The source is at [https://github.com/Chronigan/Symlink](url)

It works off a nemo action and allows you to easily create a symlink by selecting and right clicking any number of files/folders and then choosing a directory to save them in.

If you think it would be useful, please feel free to include it.

**Comment by NikoKrause** [comment]
Right click on a file and press the little + button in the top right corner of the rightclick context menu:
![screenshot-area-2017-08-01-181652](https://user-images.githubusercontent.com/8415124/28835558-09aff452-76e6-11e7-884c-82ddc08ffa87.png)

A few more actions appear. One of them is `Make Link`, which creates a symbolic link of the chosen file. Also works for more than one chosen file:
![screenshot-area-2017-08-01-181808](https://user-images.githubusercontent.com/8415124/28835592-3227ed90-76e6-11e7-96fc-3beefb628bc3.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
