### ISSUE TITLE
Feature request: make a 'recent items' icon available in the sidebar

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1557]
If one has been working with a particular folder, it would be very useful were Nemo to give one quick access to it. As things stand, if I navigate to a folder in Nemo, and then - say - want to download a file in Firefox to that folder, then I must use the Firefox save window to find the folder all over again - even though the save window is using, I believe, Nemo.

Other file managers have this functionality already.

```
 * Nemo version: 3.4.6.
 * Is issue with desktop or windowed nemo? Both.
 * Distribution - Mint 18.2.
 * Graphics hardware *and* driver used: not relevant.
 * 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment]
Open Menu and search for `Privacy`. When you turn on the setting "Remember recently accessed files", then a `Recent` icon appears in the sidebar of nemo:
![screenshot-area-2017-08-01-180922](https://user-images.githubusercontent.com/8415124/28835233-f95b1074-76e4-11e7-91b4-dbc11077dfe7.png)

**Comment by CottonEaster** [comment]
Excellent. I had not seen that sidebar item - because I had 'my computer' rolled up (and bookmarks' rolled down). Apologies.
