### ISSUE TITLE
Desktop icons zoom

### ISSUE THREAD

**Issue by stenvix** [linuxmint/nemo#1558]
```
 * Nemo version  3.4.6
 * Is issue with desktop or windowed nemo? Both
 * Distribution - Mint Betsy 2
 * Intel Graphics
 * 64 bit
 ```

**Issue**
Can't set desktop icons scale by default from view settings.
Can't set desktop icons scale by CTRL + mouse scroll

**Steps to reproduce**
- Open nemo
- Toolbar -> Edit -> Preferences -> View
- Icon View Defaults
- Default zoom level (200%)

or
- Show desktop
- Hold CTRL and scroll wheel

**Expected behaviour**
Icons have 200% scale

**Other information**
On previous (3.4.3) all working properly

**Comment by mtwebster** [comment]
Ctrl-scroll wheel has never worked on the desktop.

As for the other, it never made any sense to have the Icon view default also control the desktop size.  For 3.4 we separated the desktop from windowed nemo, and gave it a more accessible way of adjusting icon size (context menu->Desktop)

**Comment by stenvix** [comment]
What if I want icon size much bigger than "larger" option provided? Can I set that value in another way?

**Comment by feren** [comment]
@stenvix That Desktop Icons Applet in Spices?

**Comment by stenvix** [comment]
@feren in cinnamon 3.2.7 I can choose options between 33% and 400%, but in 3.4 I just have "larger" and  "smaller" options, can I increase "larger" scale from dconf or another tool.

**Comment by mtwebster** [comment]
No, the only other option for you is to not use the new desktop, and just run the old one, which will then obey the "Default zoom level" - 

`gsettings set org.nemo.desktop use-desktop-grid false`

I'm curious ... Why do you need so large?  Simple preference?  Accessibility? Are you trying to achieve some strange setup with 4k displays?

**Comment by stenvix** [comment]
Because I have 14'' display with FHD resolution, and have not so much icons on desktop that have small size with that settings

**Comment by dcht00** [comment]
I want to set them to smaller than "smaller". I switched to nemo-desktop from nautilus on Ubuntu (GNOME) 18.04 . I guess for now, probably the thing to try next seems to be make my own svg icon set.

**Comment by mtwebster** [comment]
How small is smaller?  I'm not against adding an additional size or two, within reason.  The current sizes are 32, 48, and 64 (for the grid desktop)

**Comment by mtwebster** [comment]
24px added here:

https://github.com/linuxmint/nemo/commit/80672f071742453ec0e84e4a46ec1ab28fe62379

**Comment by dcht00** [comment]
Great :) Off-topic, but how long do you think this will take to reach the nemo package in Ubuntu 18.04 repos? I would appreciate if you would point me to either a simple build instruction, or a PPA that would have it sooner. (Not really sure where nemo has documentation, maybe something to add to the main README.md).
