### ISSUE TITLE
nemo disable thumbnails in compact-view and list-view

### ISSUE THREAD

**Issue by naftahorn** [linuxmint/nemo#1561]
```
 * Nemo version (nemo --version) 
- 3.4.6
 * Is issue with desktop or windowed nemo? 
- windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 
- Mint 18.2
 * Graphics hardware *and* driver used: 
- h/w=GeForce GTX 970M/PCIe/SSE2, driver=NVIDIA 384.47
 * 32 or 64 bit: 
- x64
 ```

**Issue**
I'd like to see nemo do the same as caja file manager for compact and list-views.
In caja file manager, and when the view is either list or compact, thumbnails are disabled.  If I switch to icon-view then I can see the thumbnails.  I like having them in the icon-view, but within the other 2 views i prefer to just have the file mimetype icons.

**Steps to reproduce**
I normally have compact-view at 66% and list-view at 50%.  Nemo is configured to show thumbnails for local files only, and only for files that are less than 1MB.

Open a folder with plenty of image files (.jpg, .pnd, .bmp) and perhaps throw in a smattering of .txt and .pdf files to boot.  In icon-view i can see a decent thumbnail as expected.  When in list and compact view i can still see a thumbnail that corresponds to the sizing parameter that was selected for that view.

**Expected behaviour**
In list and compact view i'd like to only see the mime-type icon for the file.

**Other information**

**Comment by naftahorn** [comment]
Oops ... meant for this to be a feature request, and NOT an issue.

**Comment by nick-s-b** [comment]
I've made a similar request a while back:

https://github.com/linuxmint/nemo/issues/1280

**Comment by naftahorn** [comment]
Hello moderators can you link my feature request here with @nick-s-b 's request #1280 , then close this request.

Thanks!

**Comment by simonwiles** [comment]
This is a really good idea -- I too would love to be able to set an option to enable this behaviour.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
