### ISSUE TITLE
The `Public` folder and _Sharing Options_ is obsolete. 

### ISSUE THREAD

**Issue by jean** [linuxmint/nemo#1566]
```
 * Nemo version (nemo --version): nemo 3.4.6
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.2
 ```

**Issue**
The `Public` folder and _Sharing Options_ is obsolete. 
From browsing forums, it seems that this functionality went away in Mint 17, and samba sharing now has to be setup via editing config files again ([file share mint 18 & win 10?](https://forums.linuxmint.com/viewtopic.php?f=60&t=247523&hilit=public+share)). That's fine, but a polished UI shouldn't leave options lying around that are guaranteed to stop at an error. 

**Steps to reproduce**
Try to _Create Share_ via `nemo`. 

> 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory

**Expected behaviour**
A share on the local network. 

**Other information**

**Comment by leigh123linux** [comment]
This is a ubuntu samba issue and nothing to do with nemo.

**Comment by jean** [comment]
The menu option is appearing in nemo. Nemo shouldn't be showing UI elements for absent functionality.

**Comment by leigh123linux** [comment]
Public folder isn't created or part of nemo. xdg-user-dirs creates it along with 'Video', 'Pictures and the others.
These directories are always going to be visible to nemo 

I believe the issue belongs to nemo-share

https://github.com/linuxmint/nemo-extensions/tree/master/nemo-share

There are also some instructions there for it's setup

https://github.com/linuxmint/nemo-extensions/tree/master/nemo-share/debian

**Comment by leigh123linux** [comment]
There is already this report for samba

https://github.com/linuxmint/nemo/issues/1373
