### ISSUE TITLE
Nemo file search broken when searching for several name fragments separated by space

### ISSUE THREAD

**Issue by marksarnold** [linuxmint/nemo#1567]
```
 * Nemo version 3.4.6
 * Windowed nemo
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver - see bottom of post
 * 64 bit
 ```

==========ISSUE========
I recently upgraded from LinuxMint 18 to 18.1 and then on to 18.2 right away

A few days after the upgrade, I noticed that the Nemo file search feature is no longer working the way it used to. If I want to search files by several name fragments, I used to be able to specify the fragments separated by space.
Example: I have a file called "some_very_long_file_name.txt" and I could search for "long name" in the Nemo search bar and it would find the file.
Now, it still finds the file when I type "long ", but as soon as start typing a new word after space, the search bar input field will blank out and whatever I enter after space will no longer have any effect on the search result. The result will remain the result for whatever was there up to the first space.

I tried out the same thing in Nautilus, but Nautilus still works as expected...

**Steps to reproduce**
Create an empty folder. Create a file named "some_long_file_name.txt" and another named "some_very_long_file_name.txt". 
Click the search icon to bring up the search bar, and try to search for "some long". Most likely, this will cause the issue. If not, try to add another space and name fragment. When I repeatedly tried it, I found that things work right about 20% of the time, but the issue shows up about 80% of the time.

**Expected behaviour**
Work as it used to

**Other information**
Graphics hardware/driver:
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
$ inxi -G
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           Card-2: NVIDIA GK107M [GeForce GT 750M]
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa) FAILED: nouveau
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile
           GLX Version: 3.0 Mesa 12.0.6
mark@XPS15-msata ~ $ 

```

**Comment by mtwebster** [comment]
Fixed by 2bee2d58edfa0b7dbe39733b35a but hasn't been released yet.

**Comment by marksarnold** [comment]
So once this is released, I assume it will come in through the regular Update Manager? Would this be in the Nemo package or somewhere else?

**Comment by mtwebster** [comment]
Yes - would show as 'nemo' in the update manager.
