### ISSUE TITLE
bug: dual screen issues

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#1568]
In latest mint

1. when setting the secondary monitor, the mouse transitions is incorrect, correcting the display's height compared to the first display results in opposite effect compared to the expected.

2. When starting, the login screen shows up on my secondary monitor, not the primary.

**Comment by JosephMcc** [comment]
This is the place to post Nemo related issues. A doesn't seem like either of your issues have anything to do with the file manager.
