### ISSUE TITLE
request: add teamviewer to basic usb installer

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#1569]
I've noticed I do have teamviewer in my software manager of installed mint, but when attempting to help someone else install mint over video chat, I realise that in the basic usb mint boot iso, teamviewer does not show up in software manager, I don't know why.

I suggest you make sure teamviewer is available to all new mint installs and bootups, because trying helping others install mint should be made easier.

**Comment by JosephMcc** [comment]
Nothing to do with Nemo.

**Comment by osmand** [comment]
You're right.
