### ISSUE TITLE
Make nemo look amazing

### ISSUE THREAD

**Issue by swedenfortrumpcom** [linuxmint/nemo#1571]
Like the images below is how nemo should look like and work, this would be my ultimate dream for liunux

![image](https://user-images.githubusercontent.com/30671943/28898105-54e7031e-77a1-11e7-9f9b-90f1601d8095.png)

![image](https://user-images.githubusercontent.com/30671943/28898101-4d4892a8-77a1-11e7-9e82-89fdf1e94b31.png)

![image](https://user-images.githubusercontent.com/30671943/28898117-63764174-77a1-11e7-832b-b3ef85d13390.png)

![image](https://user-images.githubusercontent.com/30671943/28898124-693abf68-77a1-11e7-8a40-38a8c5ec72f5.png)

**Comment by leigh123linux** [comment]
Yuk!

**Comment by swedenfortrumpcom** [comment]
that wasnt conscrutive to to say "yuk" and close this, please reopen and haev conversatioon
