### ISSUE TITLE
Desktop icons overlapping at login

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/nemo#1573]
```
 * Nemo version 3.4.6
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used - Open Source Radeon driver on (from lspci) VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 05)
 * 64 bit
 ```

**Issue**
When I boot up and login, any icons below the bottom 25% or so of the screen get moved up so that they all overlap on top of each other.

**Steps to reproduce**
Reboot and login

**Expected behaviour**
Icons remain where I had them placed before reboot

**Other information**
This is with auto-arrance turned off, and align to grid turned on

This also does not occur when I logout and then login again, only a restart or cold boot. Could it be holding onto the GRUB menu resolution (1024x768) and placing the icons vertically according to that resolution instead of my desktop's native resolution (1600x900)?

**Comment by mfreeman72** [comment]
Here are screenshots. One is how it should look, or in other words, how it looks before I reboot. The other is how it looks after I boot up. You'll see that before I reboot, the icons extend all the way to the bottom of the screen. After I boot up, the icons near the bottom have been pushed up.
![after boot-up](https://user-images.githubusercontent.com/7842664/29136659-bb61c98e-7cf2-11e7-9450-31ba0dbe0f51.png)
![how it should look](https://user-images.githubusercontent.com/7842664/29136660-bb65149a-7cf2-11e7-958e-167a2b077be4.png)

**Comment by mfreeman72** [comment]
Ok. Definitely GRUB related. I changed by GRUB resolution to match the vertical resolution of my desktop, and the problem went away. Even though this is a solution, this should be looked into anyway, as someone might want to have a lower GRUB resolution to make the menu more readable, or for whatever reason they want.

**Comment by 2green2freak** [comment]
I have got a similar problem, when switching my 2nd monitor on or off. All my desktop icons are shifted after the switch. When I move them a bit they align to the correct grid. 
Both displays have 1080p resolution. Check these screenshots:

After turning off second screen (all are shifted):
![screenshot from 2017-08-20 14-11-50](https://user-images.githubusercontent.com/13122119/29494772-ab72a530-85b1-11e7-819b-ac6d6ce32e00.png)
After moving the right column of icons
![screenshot from 2017-08-20 14-12-01](https://user-images.githubusercontent.com/13122119/29494771-ab728ad2-85b1-11e7-8252-836279586b03.png)
After moving some of the left icons (to make it more visable)
![screenshot from 2017-08-20 14-12-14](https://user-images.githubusercontent.com/13122119/29494770-ab7257ce-85b1-11e7-9b12-0818b194c701.png)

Sometimes they even overlap:
![screenshot from 2017-08-20 14-08-32](https://user-images.githubusercontent.com/13122119/29494792-f806ceda-85b1-11e7-8f46-2a1ffc8e1263.png)

**Comment by NegativeIQ** [comment]
![alt text](https://i.imgur.com/WXN3Cfg.png "Image")

Most common icons bugging on my desktop. On the left is how they are supposed to be and how i arrange them, on the right is what i get after refresh (F5). Also if i put www right under home, home jumps to its position and overlaps www.

**Comment by xenopeek** [comment]
I couldn't reproduce this in Nemo 4.6.4 on Linux Mint 20 Cinnamon. I put icons along each border of the display (with auto-arrange off) and after reboot the icons are still there. My boot resolution is lower than after log in so this looks to have been solved.
