### ISSUE TITLE
Dragging of nemo windows

### ISSUE THREAD

**Issue by chaosink** [linuxmint/nemo#1574]
```
 * 3.4.6
 * What's the difference between desktop and windowed nemo?
 * Mint 18.2
 * GeForce GTX 980, nvidia-384
 * 64 bit
 ```

**Issue**

FEATURE REQUEST

In Mint 17.x, users can drag nemo windows by holding the mouse pointer on the blank area of tool bar, menu bar and title bar. But now the area shrink to only the title bar resulting in less convinience.

Could this feature come back?

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
I can use menu bar and title bar ok here.

**Comment by chaosink** [comment]
@leigh123linux Menu bar is not OK here, even when I just installed Mint 18.2.

**Comment by JosephMcc** [comment]
In Nemo 3.8 dragging on the menu bar works fine. This used to set in the theme. Not sure that is still respected. Dragging by toolbar does not but I'm not sure the gtk still allows that.
