### ISSUE TITLE
Used Space not updated after delete

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/nemo#1575]
LM 18.2 Cinnamon

Nemo 3.4.6

After deleting files, the used storage bar in the left pane and the info at the bottom are not updated.
You need to click another storage and then back to get the new size.

**Comment by bitboy85** [comment]
Still there in Nemo 3.6.5.
In case of usb drive you need to dismount and mount again to update the bar.

**Comment by icarter09** [comment]
@bitboy85 are you still experiencing this issue on the latest version of nemo?
