### ISSUE TITLE
[FEATURE] Full new tab

### ISSUE THREAD

**Issue by BBric** [linuxmint/nemo#1577]
When a new tab is opened in a sub panel the new tab occupy only the sub panel, but the expected behaviour could be to obtain a big tab that can be equally divided. Thus a setting for toggle between these two possibilities could be useful.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
