### ISSUE TITLE
Dashboard icon during a file operation

### ISSUE THREAD

**Issue by BBric** [linuxmint/nemo#1578]
When a file is copied/moved the icon in the dashboard should not be the same than the default icon because it's confusing.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
