### ISSUE TITLE
show-desktop-icons affecting Nemo sidebar

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo#1579]
```
 * Nemo version: 3.4.6
 * Is issue with desktop or windowed nemo? I think windowed
 * Distribution: Arch Linux
 ```

**Issue**
The key *org.nemo.desktop show-desktop-icons* affects Nemo's sidebar under My Computer
Setting it to "true", displays the Desktop place in my sidebar. Setting it to "false" removes it.

**Steps to reproduce**
The Desktop icon is visible in the sidebar under My Computer ([image](https://s14.postimg.org/5rjta4cch/2017-08-13-09_27_51.png))
gsettings set org.nemo.desktop show-desktop-icons false
The Desktop icon is hidden in the sidebar under My Computer ([image](https://s14.postimg.org/nt2y7x6dd/2017-08-13-09_27_46.png))
gsettings set org.nemo.desktop show-desktop-icons true
The Desktop icon is visible again in the sidebar under My Computer

**Expected behaviour**
I don't know if this is a bug or intentional behaviour. I encountered it while trying to figure out why the Desktop place was showing up on one computer, but not on another one running the same version of Nemo.

Can you confirm if this is intentional behaviour?
To be honest, I don't really know how to "fix" this if it's indeed unwanted behaviour, but I thought I'd ask just in case.

**Comment by dglava** [comment]
Version 3.4.7 has this too.

**Comment by mtwebster** [comment]
This is intentional - for those that want no desktop folder whatsoever, it's that assumed if you don't want the desktop folder on your ..er desktop, you don't use the folder either, so have no need to access it in the sidebar.

**Comment by dglava** [comment]
Thank you for the explanation.
