### ISSUE TITLE
GVFS mounts can die and leave behind network options which don't work

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#158]
Supposing I've opened a bunch of network shares like so:

![image](https://f.cloud.github.com/assets/772445/15434/357cfaf2-4767-11e2-81e0-243f013c48e9.png)

if I leave these open for a very long time, and suspend/resume or have my network get plugged or unplugged etc. then under some circumstances the backing GVFS mount gets removed without removing the Nemo shortcut. When I click on a mount after some time like this I get this message:
![image](https://f.cloud.github.com/assets/772445/15435/69da52f4-4767-11e2-96e5-50454186f570.png)

which is unhelpful at best. Clicking on a shortcut from my bookmarks correctly reconnects the mount, and allows the link to work again.

The correct behavior under this circumstance should be to do exactly that - if the link resolves to a mount that is unavailable for some reason, then the first error should be an attempt to reconnect to it, and the second should both remove it from the list and indicate that it's unavailable.

**Comment by Vahan86** [comment]
@wrouesnel, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
