### ISSUE TITLE
Thumbnail issues

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/nemo#1580]
I noticed some unexpected behaviours with thumbnails:

- thumbnails not showing up in a file open dialog if the folder was not accessed in a normal nemo window
- i have a mp3 music folder on a cifs share. After adding album covers with a tag editor, thumbnails are not updating

Nemo Version is 3.4.7, Cinnamon

**Comment by JosephMcc** [comment]
You should be presented with an issue template when creating a new issue. Please use it.
