### ISSUE TITLE
Thumbnails not shown

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/nemo#1581]
```
 * Nemo version 3.4.7
 * Windowed nemo?
 * Linuxmint Cinnamon 18.2
 * Intel integrated Graphics
 * 64 bit
 ```

**Issue**
Thumbnails not showing up in a file open Dialog.

**Steps to reproduce**
Download a few Images to a new Folder.
Open EasyTag, select an mp3 and add an Image
In the Dialog to select the Image, there are no thumbnails

**Expected behaviour**
Thumbnails are showing up

**Other information**
This happens in all file open dialogs but this one has also no image preview.
If you oben this Folder in a normal nemo window thumbnails are generated and only after that tey are showing up in the file open dialog.

**Comment by JosephMcc** [comment]
File open dialogs in applications have nothing to do with Nemo. They are provided by the toolkit used to write the particular application.
