### ISSUE TITLE
Nemo 3.4.7 can not render arc darker theme on its side bar correctly (ubuntu 16.04.1)

### ISSUE THREAD

**Issue by sudoyang** [linuxmint/nemo#1582]
```
 * Nemo version (nemo --version)
3.4.7
 * Is issue with desktop or windowed nemo?
windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux phy-ThinkPad-X1-Carbon 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 * Graphics hardware *and* driver used
Intel® HD Graphics 620 (Kabylake GT2)
How to check what driver is being used?

 * 32 or 64 bit
64
 ```

**Issue**
I am using nemo from this blog. But the nemo can not bring arc darker theme in its side bar. An old version (3.2) of nemo works totally fine. http://www.webupd8.org/2017/08/nemo-34-without-cinnamon-dependencies.html

**Steps to reproduce**
Open the nemo you can see it. Below it the example
![selection_014](https://user-images.githubusercontent.com/2531404/29336916-7f00943a-81dd-11e7-8f85-83b19ddd9deb.jpg)

which should be like
![selection_015](https://user-images.githubusercontent.com/2531404/29336945-988d4308-81dd-11e7-8668-3b228974280a.jpg)

**Expected behaviour**

Render the arc darker theme in a right way.

**Other information**

None.

**Comment by leigh123linux** [comment]
Works fine under cinnamon.

**Comment by feren** [comment]
@sudoyang TBF, this is more of an upstream issue with the Arc theme itself than a Nemo issue. But until Horst makes a comeback, you'll have to wait.

**Comment by sudoyang** [comment]
@feren  Thanks for letting me know!
