### ISSUE TITLE
Allow for custom values on previewable files limit

### ISSUE THREAD

**Issue by fcastilloec** [linuxmint/nemo#1583]
```
 * Nemo version nemo 3.4.7
 * All distros
 ```

I would like to see an easy way to set a custom value for the limit on previewable files. As an example, I'd like to have all my music collection with thumbnails but some song files are over 10MB, changing the limit to 100M (10 fold increase!) will include so many other files that I really don't want to be included. A limit of 20MB or even 25MB would be great!
As a workaround, I edited `org.nemo.preferences.thumbnail-limit` to 26214400 (25MB). I believe it is working, but there's a _bug_ with the preferences window in nemo that shows 100MB when setting my value. I don't want to call it a _bug_bacause the preference window was never intended to display other values besides the ones on that list.

So, it would be great if either there's a way to set a custom value in the preference window, and/or if a custom value is set on `dconf` show that value in the preference window.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
