### ISSUE TITLE
[FEATURE] Allow setting "enable-tree-lines" for the GtkTreeView

### ISSUE THREAD

**Issue by kellerkindt** [linuxmint/nemo#1585]
Just like in dolphin on KDE:
![screenshot_20170817_220024](https://user-images.githubusercontent.com/1133787/29433099-3803a0dc-839e-11e7-80ea-e8152ac2cc8d.png)

One needs to be able to set: [GtkTreeView#set-enable-tree-lines](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-set-enable-tree-lines)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
