### ISSUE TITLE
Display both place and tree in sidebar

### ISSUE THREAD

**Issue by greenlaw110** [linuxmint/nemo#1587]
```
 * Nemo version: 3.4.7
 * Is issue with desktop or windowed nemo? windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64 bit
 ```

**Issue**

At the moment I can either `Place` or `Tree` in the sidebar:
![image](https://user-images.githubusercontent.com/216930/29501744-34ab8594-866e-11e7-999d-730f9b0d2a00.png)

I want to view both places and trees at the same time, just like what Windows Explorer does:
![image](https://user-images.githubusercontent.com/216930/29501815-ade15baa-866e-11e7-8e2c-33da7f3c544b.png)

**Steps to reproduce**
Open Nemo window with sidebar enabled

**Expected behaviour**
See both places and trees in the sidebar

**Other information**

**Comment by MegaV0lt** [comment]
Great idea. I would also welcome this feature

**Comment by kavalanche** [comment]
It would be nice if we could pin favourites above the directory tree.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by trompx** [comment]
Do you mind sharing why you think this is a bad idea? I'd also like to be able to render both, one under the other.
