### ISSUE TITLE
Firefox does not honour 'preferred' file manager

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1589]
```
 * Nemo version (nemo --version) 3.4.7
 * Is issue with desktop or windowed nemo? Desktop (I imagine) - but possibly this is not a Nemo problem at all (but a Cinnamon one, or a Firefox one); please advise.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel on-board graphics. (Irrelevant to issue.)
 * 32 or 64 bit: 64
 ```

**Issue**

Firefox does not use the preferred file manager (the one set as the 'preferred application' for file management, in Mint's system settings) when opening files from the Firefox download manager.

**Steps to reproduce**

Set the preferred file manager to something other than 'files' (a.k.a. Nemo). Use the Firefox download manager to open the folder of a downloaded item.

**Expected behaviour**

Firefox should use the preferred file manager.

**Other information**

This may be a Firefox bug.

The same problem occurs in Ubuntu: see https://askubuntu.com/questions/267514/open-containing-folder-in-firefox-does-not-use-my-default-file-manager

**Comment by clefebvre** [comment]
Yes, this is upstream. FF relies on dbus rather than xdg.
