### ISSUE TITLE
Context menu has an item 'Desktop settings' and an item 'desktop'

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1590]
This is not user-friendly, or so it seems to me. Mint aims to be user-friendly. Ergo, it would be good to change it.

![image](https://user-images.githubusercontent.com/9998846/29582625-eddb8eca-876c-11e7-8679-9e5bd012c173.png)

Mint 18.2. Nemo 3.4.7. Cinnamon 3.4.6.

**Comment by leigh123linux** [comment]
So what!

**Comment by RealMtwebster** [comment]
@leigh123linux stop being a condescending hypocritical asshole, otherwise we will delete you
