### ISSUE TITLE
preview type icons causing memory leak and high cpu on desktop

### ISSUE THREAD

**Issue by twifty** [linuxmint/nemo#1591]
```
 * Nemo version 3.4.6
 * Issue with nemo-desktop.
 * Distribution - Manjaro: Gnome 3.24
 ```
I have enabled `nemo-desktop` to draw my desktop in place of `nautilus`. Noticing my system becoming sluggish, `htop` stated that `nemo-desktop` was using 80-100% cpu with about 3Gb of memory. Closed then relaunched - cpu hovered around 30% (far too high to be idle) and the memory increased at a rate of about 1Mb every 5 seconds.

The cause was a libreoffice `file.ods` on my desktop. I noticed it didn't have an icon. Placing the file in a subdirectory stopped both the memory leak and high cpu, though it did not release/free the memory. Another relaunch fixed that.

There appears to be a problem in that nemo cannot find the icon for the file type/schema causing it loop indefinitely while consuming more and more memory. Eventually, when the memory usage becomes high enough, the cpu usage causes a system slowdown.

When I say icon, nautilus actually showed a preview of the first table in the document. Opening the newly created subdirectory in `nemo` (the actual file manager), this preview is also used as the icon. This issue is only relevant to `nemo-desktop` with these kind of 'preview' icons. All other 'normal' file icons are rendered correctly.

**Comment by icarter09** [comment]
@twifty are you still experiencing this issue on the latest version of nemo?

**Comment by twifty** [comment]
TBH, I switched to KDE so nemo was no longer required.

**Comment by icarter09** [comment]
@twifty no worries and thanks for the update.

**Comment by crose-project** [comment]
FYI: We had a similar issue (high CPU usage, high memory consumption for process `nemo-desktop`, user home via NFS, error reproduceable on several linux hosts ) with Cinnamon 5.2.7 on Ubuntu 22.04.1.

Finally the affectecd user had ~1000 PDF files on the desktop. The situation became worse around 700-800 PDF files on the desktop. We checked this via:

`for II in ``seq 1 800``; do cp ~/Desktop/test.pdf ~/Desktop/$II.pdf; done`

The user will clean the Desktop directory now.

If some nemo developer read this, maybe an upper limit can be defined for the thumbnail rendering.

Thanks.
C
