### ISSUE TITLE
nemo-desktop: "follow link to original file" crashes desktop session

### ISSUE THREAD

**Issue by zorbama** [linuxmint/nemo#1596]
```
 * Nemo version: 3.4.5
 * nemo-desktop
 * Distribution - Linux Mint 18.2
 * Graphics hardware: AMD Radeon R7 260X
 * Graphics driver: AMDGPU
 * 64 bit
 ```

**Issue**

When right-clicking a file/folder link on the desktop and selecting "Follow link to original file", nemo-desktop crashes. If done twice, nemo-desktop doesn't restart until a command is manually run.

**Steps to reproduce**

1. Make a link to a file/folder and put it on the desktop.
1. From the desktop, right-click the link.
1. Click "Follow link to original file".

**Expected behaviour**

The file/folder's original path should open in a new Nemo window.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/146659264a70782927e6b9a59f259b0bcf6e77b5

Please update nemo (current is 3.4.7)
