### ISSUE TITLE
bytestring syntax

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxmint/nemo#1597]
Hello guys. Please allow me to ask you for your advise regarding a key override for
`org.nemo.preferences bulk-rename-tool`.

This key appears to be of type bytestring ("ay"). After setting it to `gprename` in nemo's preferences dialog the returned value for `gsettings get org.nemo.preferences bulk-rename-tool` is `b’gprename’` and I would like to use this as the default in the Manjaro-Cinnamon edition.

In the running environment `gsettings set org.nemo.preferences bulk-rename-tool "b’gprename’"`
works fine, but I fail at finding the correct syntax to include in an override file.
I have tried everything I can think of and would really appreciate if you could help me out here.
I've tried square brackets, double/single quotes, including the nul terminator as mentioned on [developer.gnome.org](https://developer.gnome.org/glib/stable/gvariant-text.html) in all kinds of combinations and variations - without success.
Your help will be much appreciated.

**Comment by xenopeek** [comment]
It looked like you used fancy single-quotes (`’`). Use normal single-quotes (`'`).

I can't get it to work with gprename; gprename looks to crash after launching. But Thunar's bulk renamer works after this:

`gsettings set org.nemo.preferences bulk-rename-tool "b'thunar -B'"`

**Comment by smurphos** [comment]
How to use gprename as the bulk-renamer


Install gprename

`apt install gprename`

Create wrapper script (copy this whole code block into a terminal and press enter)
```
sudo tee /usr/local/bin/gprename-nemo <<'EOB'
#!/bin/bash
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }
filePath=$(urldecode "$1")
gprename "$(dirname "$filePath")"
EOB
```
Make wrapper script executable
`sudo chmod +x /usr/local/bin/gprename-nemo`
Set the wrapper script as the bulk-renamer
`dconf write /org/nemo/preferences/bulk-rename-tool "b'gprename-nemo'"`
