### ISSUE TITLE
Right-click context menu on trash shows "Send per E-Mail"

### ISSUE THREAD

**Issue by Piiit** [linuxmint/nemo#1603]
```
 * Nemo version (nemo --version) 3.4.7
 * Is issue with desktop or windowed nemo? windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) LM18.2
 * Graphics hardware *and* driver used i915
 * 32 or 64 bit - 64 bit
 ```

**Issue**
Context menu clicking the trash icon inside the side-pane of nemo shows "Send per E-Mail".

**Steps to reproduce**
Right-click context menu on trash (inside the side-pane of nemo).

**Expected behaviour**
 "Send per E-Mail" shouldn't be there. I suggest to remove it.

**Other information**

**Comment by Piiit** [comment]
Update: Same for "Recent" inside the side-pane.

**Comment by Piiit** [comment]
Update: Same for "Network" inside the side-pane.

**Comment by dglava** [comment]
I am experiencing this as well. I don't know if it's intentional or not, but it's really annoying on the Trash icon, because I accidentally click it all the time.

As a temporary workaround, I removed the files `send-by-mail.nemo_action` and `send-by-mail.py` from `/usr/share/nemo/actions/`. That seems to get rid of it from the right click context menu.

**Comment by xenopeek** [comment]
The file `send-by-mail.nemo_action` indeed plays a role here. It has "Extensions=nodirs" setting. In `nemo-places-sidebar.c` I think the context menu is created by function `bookmarks_check_popup_sensitivity` and that calls `nemo_action_get_visibility` from `nemo-action.c` to check which nemo actions should be displayed for the selected item. Apparently the code that checks for condition "Extensions=nodirs" sees Trash and Network _not_ as directories and therefor displayes the Send by Email action.

If this isn't an obvious bug, I think special case for Trash and Network should be added here https://github.com/linuxmint/nemo/blob/e0cd29e71f01860992a51b670e7dd6a47c03e3a0/src/nemo-places-sidebar.c#L2327
or here https://github.com/linuxmint/nemo/blob/e0cd29e71f01860992a51b670e7dd6a47c03e3a0/libnemo-private/nemo-action.c#L1515

**Comment by icarter09** [comment]
Nemo  4.6.5
Mint 20 64bit

I no longer see the `Send by Email` for Trash, but Network is still showing it as an option.
