### ISSUE TITLE
Display time modified in informal mode

### ISSUE THREAD

**Issue by markkrj** [linuxmint/nemo#1604]
We should be able to see the time a file was modified yesterday, or Friday, etc. I like the 'informal' display format for 'today' modified files, but it's so bad if there is multiple files modified in another day in the same week. If there is more than 1 files modified yesterday, or Wednesday, or whatever other day in the same week, we should be able to see what is newer. Something like, "Yesterday at 9:00"

EDIT: I installed Mint XFCE on an old leptop, and it's file manager (Thunar, which is a Nautilus fork, as is Nemo) behaves exactly like Nemo should do. There is an "Today at 9:00 AM" and a "Today" option. Nemo only offer an "Yesterday" option. It's so frustrating to open an folder with multiples files modified "Yesterday" and not being able to see the time it was modified.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
