### ISSUE TITLE
Connect to SSH server using private key file instead of username and password (feature request)

### ISSUE THREAD

**Issue by ashvince** [linuxmint/nemo#161]
I love the functionality for connecting to SSH sites to do secure file copies where it automatically mount the target but this only works with usernames passwords. Is it possible to use a private key file instead?

The functionality seems to missing from the connect to server menu in Nemo 1.1.2.

In my case I need to do something similar to WinSCP where I enter a private key to authenticate me with a gateway machine which then uses the supplied username to figure out which machine I am trying to connect to then creates an SSH tunnel to that machine.

**Comment by lmmx** [comment]
It's solved (e.g. connect to server with password and bookmark, later find no need to resupply password if keys are set up). I'd suggest closing this.
