### ISSUE TITLE
desktop-file-validate fails with nemo.desktop

### ISSUE THREAD

**Issue by rezso** [linuxmint/nemo#1611]
Nemo version: 3.4.7 release tarball.
The desktop-file-validate fails with nemo.desktop:
/usr/share/applications/nemo.desktop: error: DBusActivatable filename must conform to reverse-DNS notation
This rule is added in desktop-file-utils 0.23.

**Comment by leigh123linux** [comment]
Fixed https://github.com/linuxmint/nemo/commit/2704903578bfd8aaeda19be40cd5f15133bc439b
