### ISSUE TITLE
Detailview "ugly" and wrong on german locale

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/nemo#1612]
```
 * nemo 3.4.7
 * Distro: Linux Mint 18.2 Sonya
 * Graphics:  Card: Advanced Micro Devices [AMD/ATI] Kaveri [Radeon R7 Graphics] bus-ID: 00:01.0
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1920x1200@59.95hz
           GLX Renderer: Gallium 0.4 on AMD KAVERI (DRM 2.49.0 / 4.10.0-35-generic, LLVM 4.0.0)
           GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes

 * 64 bit
 ```

**Issue**
Detailvier the date colum in german local looks ugly and also is wrong due missing dots

**Steps to reproduce**
open nemo and switch to detailview

**Expected behaviour**
show the date in a nice formatted manner and respect locale settings

**Other information**
screenshot:
![](https://i.imgur.com/Rxi3h8C.png)

**Comment by NikoKrause** [comment]
It's not wrong. Months translate right `Oct -> Okt` and also Days `Th -> Do` etc.
It's just ugly. And beauty is in the eye of the beholder.

A little more info:
That's are handle with `strftime`.
Please have a look here to get an idea what this is: http://www.phpbox.de/php_befehle/strftime.php

What you are looking for is the translation of the string, which produces this date. And the string you are searching for is [this one here on launchpad](https://translations.launchpad.net/linuxmint/latest/+pots/nemo/de/+translate?batch=10&show=all&search=%25c).

It's `%c`. And `%c` means:
> Full date and time output according to local settings
And that's what you see in your detailview in nemo.

If you want: 
* `Di., 03. Okt. 2017 09:26:13 CEST`, you'll need to translate `%c` to `%a., %d. %b. %Y %X %Z`
* `Di., 03.10.2017 09.26:13 CEST`, you'll need to translate `%c` to `%a., %x %X %Z`

The translation is handled on launchpad, see my link above. If you want this to be changed, you'll need to propose it there or contact the German translator: https://launchpad.net/~toba

**Comment by MegaV0lt** [comment]
Well, no idea of the tecnical background. But shirt versions of day and month have to have the "." to be correct. Maybe it is a general linux problem?

Would it be possible to add a settings-string to nemo to customise the datestring like it canb be don with the clock in the taskbar?
![](https://i.imgur.com/NHt2YE9.png)

**Comment by NikoKrause** [comment]
It's not a general linux problem.
You have two options here.
Change the translation as suggested in my previous post, i.e. get in contact with the translation.

Second option: Get in touch with the developers of strftime and tell them, that they have implemented the wrong localized version of `%c`.

I don't see the point in adding an extra setting in nemo for that. There's all info you need. And it's an info, that a normal user shouldn't get the chance to mess up accidentally.

**Comment by Moilleadoir** [comment]
There’s a whole cascade of standards bodies that decide these formats, so it would be good to check first what the current German standard and international standard for German are. These bodies do make mistakes from time to time, but the strftime standard might also be the accepted one.

If you look at Unicode’s [Common Data Locale Repository for German](https://www.unicode.org/cldr/charts/latest/summary/de.html), you can see their short day formats starting at line 1813. The abbreviated and short formats for English are the same but for German they’re different (Sun/So. vs Sun/So). Maybe this is one source of the problem?

**Comment by MegaV0lt** [comment]
Right! 
So = Wrong
So. = Right

Also Month:
Jan = Wrong
Jan. = Right

**Comment by MegaV0lt** [comment]
> I don't see the point in adding an extra setting in nemo for that.

I do. See sample screenshot from the time panel. The formatings are wrong and have to be displayed the right way in my opinion. Regardless how they are treated internally. so an option to customize them would be the right way.

**Comment by MegaV0lt** [comment]
Here is a sample how to do it right fom Xfe:
![auswahl_20171010_09 53 19](https://user-images.githubusercontent.com/2804301/31375184-fd199b7a-ada0-11e7-8d70-ff037f5cb780.png)

In settings i can see:
![auswahl_20171010_09 55 02](https://user-images.githubusercontent.com/2804301/31375223-1e36b9fa-ada1-11e7-9270-f197f5a09efe.png)

**Comment by MegaV0lt** [comment]
Next Sample how to do it right is taken from my Win7 Explorer
![auswahl_20171010_11 32 53](https://user-images.githubusercontent.com/2804301/31379639-2244edf6-adaf-11e7-8846-f7762d70d523.png)

**Comment by NikoKrause** [comment]
I told you your options.

**Comment by MegaV0lt** [comment]
strftime has the right options: %x and %X, but nemo is not using it and uses wrong formatet ones

**Comment by NikoKrause** [comment]
It uses `%c` which is localized according to strftime.

Using `%x %X` is wrong in other languages: it's 24-hour Format

Did you get in touch with the translator?

**Comment by MegaV0lt** [comment]
no, was not able to find it...

Well the man says: 
`       %x     The preferred date representation for the current locale without the time.

       %X     The preferred time representation for the current locale without the date.
`

**Comment by NikoKrause** [comment]
I get your point that it looks ugly in German.
But it really should be fixed through translation to not mess up other languages.

**Comment by to-ba** [comment]
I have added a list a while ago in the UbuntuGermanTranslators-Wiki for the right format:
https://wiki.ubuntu.com/UbuntuGermanTranslators/Standard%C3%BCbersetzungen#Datumsformat_DIN_5008_-_strtime_und_qt

It would be better to correct it in the source »strftime«. But I do not know where it can corrected. I have searched for it yesterday.

**Comment by to-ba** [comment]
Is https://translations.launchpad.net/linuxmint/latest/+pots/nemo/de/+translate?batch=10&show=all&search=%25c the right string? I have tested it with my Nemo (3.4.7) and an other translation for »%c«, but it takes no effect. /usr/share/locale/de/LC_MESSAGES/nemo.mo

Can you test it?

**Comment by NikoKrause** [comment]
Did you rebootet after you changed the .mo file?

**Comment by to-ba** [comment]
Yes

**Comment by NikoKrause** [comment]
@mtwebster Can you tell us, if this is the right line?

**Comment by mtwebster** [comment]
I suspect the format shown in the list view image in the first post is not translated by nemo at all - check out:

https://github.com/linuxmint/nemo/blob/3.4-maintenance/libnemo-private/nemo-file.c#L4570

we don't translate the `%c` - we let `g_date_time_format()` handle it.

Digging in glib, looks like we end up here: https://github.com/GNOME/glib/blob/glib-2-48/glib/gdatetime.c#L2298

which uses either this:
https://github.com/GNOME/glib/blob/glib-2-48/glib/gdatetime.c#L174
or this:
https://github.com/GNOME/glib/blob/glib-2-48/glib/gdatetime.c#L206

In Mint (via Ubuntu) we appear to use the former, which uses langinfo, which draws it all from LC_TIME - 

Run this in a terminal:
```
locale -k LC_TIME | grep d_t_fmt
```

The `d_t_fmt` line should show what `%c` represents when the locale format is being used in Nemo.

Did a quick search, [this](https://ccollins.wordpress.com/2009/01/06/how-to-change-date-formats-on-ubuntu/) seems to show a reasonably simple way of overriding it.

**Comment by Moilleadoir** [comment]
I tried this the other day and it seemed to confirm it’s not Nemo and not a translation issue.

(assuming you have a German locale set up)
````
sean@nung:~$ export LC_ALL=de_DE.UTF8
sean@nung:~$ date
Fr 13. Okt 13:33:08 AEDT 2017
sean@nung:~$ date +%c
Fr 13 Okt 2017 13:33:14 AEDT
sean@nung:~$ date +%x
13.10.2017
sean@nung:~$ locale -k LC_TIME | grep d_t_fmt
d_t_fmt="%a %d %b %Y %T %Z"
era_d_t_fmt=""
sean@nung:~$ export LC_ALL=en_AU.UTF8
sean@nung:~$ date
Friday 13 October  13:34:04 AEDT 2017
sean@nung:~$ date +%c
Fri 13 Oct 2017 13:34:10 AEDT
sean@nung:~$ date +%x
13/10/17
sean@nung:~$ locale -k LC_TIME | grep d_t_fmt
d_t_fmt="%a %d %b %Y %T %Z"
era_d_t_fmt=""
````
So, it looks like Nemo is just using the format that it’s given. I’ve tried running other File Managers - Caja’s dates look exactly the same as Nemo, Nautilus seems to use the same as the default date format (13. Okt) but it’s date formatting is stupid anyway. I can’t get Thunar to launch with a German interface.

Note that date also gives 24-hour format for the Australian English and Irish locales, neither of which use 24-hour format.

I don’t think making a custom locale is either simple or a good suggestion for fixing a standard.

**Comment by MegaV0lt** [comment]
Why not use %x %X like xfce?
https://github.com/linuxmint/nemo/issues/1612#issuecomment-335391538

**Comment by to-ba** [comment]
Tell me where, then I change the translation.

**Comment by xenopeek** [comment]
As noted in above analysis Nemo uses '%c' date format when choosing locale date format. That's not translatable by translators. According to strftime '%c' uses the "preferred date and time representation for the current locale." This issue is about disagreement with the date and time representation strftime uses for German being the preferred one.

Instead of trying to bypass what strftime does for German I think implementation of feature request #968 would make everybody happy: allowing the user to also set a custom date format.

**Comment by MegaV0lt** [comment]
After years "date" is still displaying wrong fomat...
