### ISSUE TITLE
Can we have thumbnails larger than 256px? label:"FEATURE REQUEST"

### ISSUE THREAD

**Issue by sverx** [linuxmint/nemo#1613]
```
 * issue with windowed nemo
 * Distribution: Mint 18.2 (64 bit)
 ```
As per the subject, I find 256px max too little for thumbnails having a 15" FHD display.
Icons: I don't care their size, but in preview mode for instance I'd like to see my JPGs bigger.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
