### ISSUE TITLE
[FEATURE REQUEST] Sort Devices & Network in sidebar

### ISSUE THREAD

**Issue by Moilleadoir** [linuxmint/nemo#1614]
```
 * Nemo version 3.4.7
 * Windowed
 ```

**List of devices and network mounts is not sorted (mount order?)**
It would be much more helpful/logical if these were sorted alphabetically (by name or location). At the moment this is totally beyond the user’s control and seems unnecessarily chaotic.

No other File Manager I’ve looked at does this (Nautilus, Thunar, Caja, Pantheon Files) so it would be a unique feature for Nemo.

**Comment by dannn-o** [comment]
+1 for this much-needed feature request.

**Comment by roarshak** [comment]
+1 here too.

**Comment by archmunky** [comment]
I would also like to see this feature. Nemo is by far my favorite file manager but it's a bit of a pain to find the device I'm looking for when the the devices are in a random/non-alphabetized order.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
