### ISSUE TITLE
Duplicate devices in left pane when running as root

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1615]
```
 * Nemo version (nemo --version) 3.4.7
 * Is issue with desktop or windowed nemo? Windowed.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2
 * Graphics hardware *and* driver used Not relevant.
 * 32 or 64 bit: 64.
 ```

**Issue**

Duplicate devices in left pane when running as root,

[Screenshot](https://imgur.com/a/lb7r2).

**Steps to reproduce**

Uncertain. The device in question is router-attached storage and used to be an autofs share but is now mounted via fstab in conjunction with systemd.

**Expected behaviour**

There should be only one entry per device. Or, if there is a problem, I should be able to delete the phantom device entry or at least do something.

**Other information**

The same problem seems to have been reported by someone else, in 2015, [here](https://www.google.co.uk/search?q=linux+mint+nemo+duplicate+devices&ei=kvPcWbeVG5qOvQTDjYT4Cw&start=10&sa=N&biw=1280&bih=707).

Removing a folder to which the device used to be mounted does not seem to solve the problem - even after `sudo killall nemo`. Nor does trying to eject one of the duplicate devices help.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
