### ISSUE TITLE
Window goes out of tiling when using f3 split window

### ISSUE THREAD

**Issue by overkill22** [linuxmint/nemo#1616]
* Nemo version: 3.4.7
 * Issue with windowed Nemo
 * Distribution: Mint 18.2 64bit, Cinnamon 3.4.6
 * Graphics hardware *and* driver used: Intel Core M-5Y71, Intel Corp Broadwell-U Integrated Graphics

**Issue**
I tile the window on the right or left of the screen, press f3 to split the Nemo window into 2 parts, move to any folder >>> the window goes out of the tiling. This happens only while tiling on the left or right (taking half of the screen), not when tiling in the corners or at the top or bottom.
If the split window is activated before tiling the window, Nemo won't allow the tiling on the side or corner, only at the top or bottom.

**Steps to reproduce**
01.
Open Nemo;
tile the window on the left or right;
split the window with f3;
browse folders.

02.
Open Nemo;
split the window with f3;
try to tile on the left or right, or corners.

**Expected behaviour**
01. I can browse the folders with the split window (f3) when the window is tiled to the left or right of the screen as I can do when the window is tiled at the top, bottom, corners of the screen.

02. I can tile the window to the left, right, corners of the screen, when the window is in split mode (f3) as I can do at the top and bottom.

![01-tile-then-f3-01](https://user-images.githubusercontent.com/16596491/31419453-91cac4ba-ae6e-11e7-93a2-7e887de99eee.png)
![01-tile-then-f3-02](https://user-images.githubusercontent.com/16596491/31419454-9226add4-ae6e-11e7-89c6-c57476a6a9fc.png)
![02-f3-then-tile-01](https://user-images.githubusercontent.com/16596491/31419455-925e1242-ae6e-11e7-9e84-824b196c70bc.png)
![02-f3-then-tile-02](https://user-images.githubusercontent.com/16596491/31419456-929432e6-ae6e-11e7-8d0c-f18b29b1edcb.png)

**Comment by mtwebster** [comment]
I'm pretty sure this is a window manager (muffin) issue.  Many program windows will attempt to tell the window manager what their minimum size can be, and the window manager may refuse to tile in a certain orientation if the resulting window size would be smaller than those minimums.

I can reproduce this, but not always.  And I'm not sure what the connection is with navigating folders being the thing that triggers this.  I have a feeling it may only happen when navigating between folders that use different views (such as navigating between a list-view folder and icon-view folder.) - can you test this?

Even with dual panes and the sidebar I can still tile in any spot on my monitor, but I think somehow during view changes, the window manager is thinking it needs to un-tile this window (for whatever reason, but my suspicion is that the window has reported it's minimum sizes to be larger than the current actual size, breaking the tile state.)

**Comment by mtwebster** [comment]
Issue moved to [linuxmint/muffin #301](https://github.com/linuxmint/muffin/issues/301) via [**ZenHub**](https://www.zenhub.com/)
