### ISSUE TITLE
Duplicate sidebar icons for nfs mounts

### ISSUE THREAD

**Issue by joaojotta** [linuxmint/nemo#1618]
So, I'm mounting some nfs drives and I see them twice on the sidebar.
I saw this issue reported somewhere back in 2012 for Thunar and PCManager as well as Naitilus and Nemo.

[Picture here](https://s1.postimg.org/4yu25ynqj3/Screenshot_from_2017-10-12_18-18-16.png)
_(the **Movies** folder is the one duplicated)_

Here are my fstab options (am I doing anything wrong?):
`USER@IPADDRESS:/mnt/folder            /mnt/folder        fuse.sshfs  noauto,x-systemd.automount,_netdev,users,idmap=user,IdentityFile=/home/USER/.ssh/,allow_other,x-gvfs-show,reconnect 0 0`

Nemo 3.4.7
64 bit
Arch

Thanks!

**Comment by icarter09** [comment]
@joaojotta are you still experiencing this issue on the latest version of nemo?
