### ISSUE TITLE
vCard support

### ISSUE THREAD

**Issue by LohnerZ** [linuxmint/nemo#1620]
It's would be great, if nemo could detect and manage vCard files (or vCard file's symlink).
For example some useful function:

    show contacts on desktop or in a folder with photo
    make a symlink from contacts applications to desktop by drag&drop (app integration)
    show contact details in contacts or mail app (app integration)
    send mail from selected contact (right click menu & mail app integration)
    show received mails from selected contact (mail app integration)
    send files as attachment with drag&drop event to hovered vCard file
    etc.

**Comment by leigh123linux** [comment]
This isn't something we are interested in adding.
