### ISSUE TITLE
Open Terminal when in Trash opens in HOME directory…

### ISSUE THREAD

**Issue by Salamandar** [linuxmint/nemo#1623]
```
 * Nemo version : >=3.0
 ```
**Issue**
When in Trash, ctrl-right-click -> Open Terminal Here will open Terminal app in $HOME.
I accidentally rm -rf * in my HOME instead of ~/.local/share/Trash…

**Expected behaviour**
It should open Terminal with cwd == '.local/share/Trash' or '.local/share/Trash/files'.

**Comment by leigh123linux** [comment]
Trash is handled by gvfsd-trash

**Comment by sgmanohar** [comment]
This would be fine if the terminal fails, 
but not fine if the terminal puts you in $HOME.
