### ISSUE TITLE
Lock-ups if symlink points at temporarily inaccessible nfs automount

### ISSUE THREAD

**Issue by nigel2357** [linuxmint/nemo#1627]
```
 * Nemo version (nemo --version)                                  
3.4.7
 * Is issue with desktop or windowed nemo?                 
both but especially desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)        
Fedora 26 (Cinnamon spin)
 * Graphics hardware *and* driver used                         
intel J1900 integrated
 * 32 or 64 bit                                                                   
64 bit
 ```

**Issue**
Given
/misc/shared auto-mounts server:/shared  (tested working)
ln -s /misc/shared /home/Desktop/
The server is down or the server is inaccessible

Then it is impossible to properly log in

If the link is in one's home folder, it is almost as bad: one cannot open the Home icon on the Desktop, which defeats most non-technical users. 

**Steps to reproduce**
1.Configure autofs such that reference to /misc/shared auto-mounts an nfs share, and test it's working 
2.in shell,
  ln -s /misc/shared ~/Desktop/
3.Log out, log in again, this works
4.Log out, disconnect the network cable, attempt to log in again

Hangs.

**Expected behaviour**
Pessimally, the same, but this is a very poor user experience.

It would be very nice if Nemo did not attempt to follow any link until it was explicitly commanded to do so as a consequence of the user double-clicking on a link icon. The problem indicates that Nemo is actually following the link with no explicit user request to do so at login time, and is not prepared to handle a hang-up when the link points at an inaccessible resource.

**Other information**
May overlap with or be same as issue 1378.

It's an nfs 3 share. 

/etc/auto.master contains
/misc /etc/auto.misc

/etc/auto.misc contains
shared  -rw,soft,intr  server:/mnt/shared

Tried adding bg mount option. Tried hard instead of soft. No change.

This was reported to Fedora as Bug 1506703. Closed by them, self referred upstream to here.

**Comment by icarter09** [comment]
@nigel2357 are you still experiencing this issue on the latest version of nemo?
