### ISSUE TITLE
File name field in Nemo does not lose focus when changing directories

### ISSUE THREAD

**Issue by frozenstuff** [linuxmint/nemo#1628]
Nemo version 3.4.7
Mint 18.2 Cinnamon 64 Bit
Dell XPS 13 9350
 

The highlighted Name field in Nemo does not lose focus or unhighlight when changing directories, creating an odd behavior.

1. Save/create a new file in text editor. 
2. File saver opens up with Home directory as default. 
3. Can immediately type and change file name as expected.

Where issue occurs:
1. Save/create a new file in text editor.
2. File saver opens up. Click on another directory such as "Downloads"
3. Immediately start typing new file name.

Despite the Name field still being highlighted, Nemo will search your text instead of naming your file because the focus/highlight was lost. Nemo should either keep the focus on the Name field or indicate to the user that it's no longer highlighted.

**Comment by mtwebster** [comment]
Unfortunately nemo doesn't provide this dialog.  It's built in to the Gtk toolkit and we have no control over it.
