### ISSUE TITLE
Preview when mouseover

### ISSUE THREAD

**Issue by bigbruno** [linuxmint/nemo#1629]
When you hover over an image in Dolphin, a preview is displayed, can you include this feature in Nemo?

![image](https://user-images.githubusercontent.com/6098501/32137580-8d48fbb4-bc01-11e7-8abb-1e6be91724f0.png)

**Comment by DanielRios549** [comment]
The preview actually exists, you can acess it to select the file and use super + space. I'd like this features, in a separate area, like on Windows Explorer

**Comment by bigbruno** [comment]
Alt+space not is good option, is more easy use two clicks and open file, mouse over is very better.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
