### ISSUE TITLE
Search with Arabic text is broken

### ISSUE THREAD

**Issue by matwachich** [linuxmint/nemo#1631]
```
 * Nemo version 3.4.5, Cinnamon 3.4.3
 * Is issue with desktop or windowed nemo? Don't know :(
 * Distribution - Mint 18.2 x64
 * Graphics hardware *and* driver used: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller, Pentium Dual-Core CPU T4500
 * 64 bits
 ```

**Issue**
Searching a file with Arabic language is broken

**Steps to reproduce**
Open Nemo, click the search button, type some arabic text **with a space** caracter.

Result: the text seems to vanish and anything you type after the space is not considered.

**Expected behaviour**
Seems pretty obvious

**Other information**
Thank you

**Comment by xenopeek** [comment]
@matwachich are you still affected by this issue on newer versions? Is this issue still reproducible? Could you retest on Linux Mint 20 Cinnamon.

**Comment by nasserbinlaboun** [comment]
I tested it and It's working properly on Linux Mint 20 Cinnamon
