### ISSUE TITLE
Nemo ignore file extension based on file contents

### ISSUE THREAD

**Issue by sevenskull** [linuxmint/nemo#1632]
```
 * Nemo version 3.4.6
 * The issue happens on desktop and windowed
 * Distribution - Linux Mint 18.2 64bit
 * The issue is independent of graphic hardware and driver (tested on multiple)
 * 64 bit
 ```

**Issue**
First i tried to google it, but no luck, maybe i don't know what to ask for.
The issue is: There's a weird behavior on some files, which sometimes the same file extension open with different applications, based on what is the file content, also it changes the icon.
My example is with a .tpl extension which should be opened with my text application (xed), but some files start with html tags "<anytag>", so it assumes that should be opened on browser instead of file editor.
If this is not a bug, it's a very weird behavior, and can someone help-me how to stop this. Also, if it opens every file on a folder to check the first lines, i think it could even increase the performance.

**Steps to reproduce**
Create a file
test.tpl > write anything but html tags
Create another file
test_with_html.tpl > write some html tags

**Expected behaviour**
The expected would be to open file (same extension) with the same application for both.

**Other information**

**Comment by ManIVIctorious** [comment]
Well, honestly this is not an error at all. This is just the way how Linux defines file types. You can associate file types based on the file name or on its content. This is especially powerful when combined (like in Linux and BSDs). To solve your specific issue you should create a new mime type for these tpl files.

A good read on the topic is provided in the Arch Linux wiki:
 https://wiki.archlinux.org/index.php/Default_applications

I hope this was helpful and if it solves your specific problem please close this issue.
Maybe a feature request for a graphical way to manage mime types would be a good idea...

**Comment by mtwebster** [comment]
The simplest way to get around this is right-click the file with the html content, Open With->Other Application... and click xed (or whatever) and click "Set as default".  Now, the file will still show an icon appropriate to its content (mimetype) but it will open with xed.

As for the performance hit, typically the mimetype for a file is checked only when its contents change, and its type is stored in filesystem metadata - this is not done by nemo, but at a lower layer that we really don't have a lot of control over.
