### ISSUE TITLE
Feature Request: Possibility to change volume name

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/nemo#1633]
It would be nice if you could change a volume name (from an USB drive) within nemo because ex-Windows users will start searching this function within the file manager.

**Comment by ManIVIctorious** [comment]
And please consider the addition of the ability to hide selected volumes from the sidebar

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
