### ISSUE TITLE
At extraction of CD, using the button on the CD drive, in nemo the disk remains open and does not notify you of extraction

### ISSUE THREAD

**Issue by VAVUS7** [linuxmint/nemo#1634]
* Nemo version 3.7.4
 * Distribution - Mint 18.2
 * 64 bit

Issue
At extraction of CD, using the button on the CD drive, in nemo the disk remains open and does not notify you of extraction

**Comment by xenopeek** [comment]
Is this issue still reproducible? Could you retest on Linux Mint 20 Cinnamon.

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

Was not able to reproduce this issue. Upon pressing of the CD drive, the disk was no longer open in Nemo.
