### ISSUE TITLE
Too much horizontal space between icons

### ISSUE THREAD

**Issue by gabrc52** [linuxmint/nemo#1635]
```
 * Nemo version 3.4.7
 * Is issue with desktop or windowed nemo? At least windowed nemo
 ```

**Issue**

The horizontal padding/space between icons is too large, so there is a lot of unused space.

**Steps to reproduce**

Set View to Icons (Icon view)

**Expected behaviour**

Horizontal padding is like in nautilus

**Comment by leigh123linux** [comment]
The spacing it correct IMO, if it was any closer the font labels would overlap.

**Comment by JosephMcc** [comment]
Having used nautilus a bit lately, it does have a nicer, more compact layout, in the icon view imho.

**Comment by leigh123linux** [comment]
@JosephMcc Which nautilus version? 3.26  looks shitty to me

![screenshot from 2017-11-04 05-37-39](https://user-images.githubusercontent.com/1299302/32402718-59f47538-c122-11e7-9e63-964e7516278a.png)

That's using the default.

**Comment by JosephMcc** [comment]
Nautilus 3.26 but you can reduce the icons to a reasonable size. They are just overly large by default.

**Comment by JosephMcc** [comment]
![screenshot from 2017-11-03 23-02-57](https://user-images.githubusercontent.com/2231759/32402906-45aa6f7e-c0eb-11e7-9896-b69dc1668035.png)

**Comment by leigh123linux** [comment]
As I said reducing the horizontal padding causes issues

![screenshot from 2017-11-04 06-15-01](https://user-images.githubusercontent.com/1299302/32402979-abf83798-c127-11e7-8700-bcde03ca457c.png)

**Comment by JosephMcc** [comment]
Not sure what's wrong with yours but it's fine here
![screenshot from 2017-11-03 23-20-28](https://user-images.githubusercontent.com/2231759/32402997-b0ccb9f4-c0ed-11e7-8096-b2d753cd8197.png)

**Comment by leigh123linux** [comment]
Did you try 'small' yet

**Comment by JosephMcc** [comment]
Small as they go and still don't see your issue
![screenshot from 2017-11-03 23-28-04](https://user-images.githubusercontent.com/2231759/32403065-d73b35f6-c0ee-11e7-8774-15fb96957f97.png)

**Comment by leigh123linux** [comment]
If the 'cjs' and 'flags' name longer it would happen IMO

**Comment by JosephMcc** [comment]
In any case the layout is just nicer. After you use Nautilus for a few days, Nemo just feels like it could use a much more compact layout.

**Comment by JosephMcc** [comment]
I knew it: https://github.com/linuxmint/nemo/issues/802
