### ISSUE TITLE
bug: occasional focus stuck to a background tab

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1637]
```
windowed nemo 3.4.7
Mint 18.2
64 bit
 ```

**Issue**
occasionally, when using multiple-tabs, keyboard **f**ocus is stuck-to a background-tab
- alt+enter **i**nvokes item from a **b**ackground tab
- u**n**able to rename file/folder in active-tab

workarounds 
- drag tab into seperate window
- open another window/kill-restart nemo and work from there

**Comment by xenopeek** [comment]
Is this issue still reproducible? Could you retest on Linux Mint 20 Cinnamon.

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I tried several ways to see if I could reproduce this issue, but had no luck. I'm going to close this ticket. @cmrdt if it is still an issue for you, please provide the steps to reproduce and we'll reopen the ticket if necessary. Thanks.
