### ISSUE TITLE
feature request: add menu troubleshooting option to restart nemo

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/nemo#1638]
```
windowed nemo 3.4.7
Mint 18.2 64 bit
 ```

**Issue**
occasionally (maybe related to search function or memory leaks where memory isnt freed though tabs&windows closed) nemo uses >2GB ram (rarely >5GB)

if could add an official menu option  to restart/kill nemo
would that be better than the hackish `killall nemo` or use of task-manager ?

similar to cinnamon's
![clipboard03](https://user-images.githubusercontent.com/24411108/32413252-ac0cdc1e-c205-11e7-820f-8ba7245c7577.png)

**Comment by leigh123linux** [comment]
What's wrong with using the close button or close in the menu?

**Comment by cmrdt** [comment]
no, closing the windows does not kill the process nemo
![screenshot from 2017-11-05 08-31-23](https://user-images.githubusercontent.com/24411108/32415209-d0e2cc9c-c22d-11e7-92c6-b77218aa3a1c.png)

**Comment by leigh123linux** [comment]
It does but it might take a minute or two.
