### ISSUE TITLE
Nemo Desktop drag & drop - copy/move issue

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/nemo#1642]
```
 * Nemo version (3.4.7)
 * Issue with desktop
 * Mint 18.2
 * Graphics hardware tested - Intel (Mesa 17.07), NVIDIA (375.66 also 384.90)
 * 64 bit
 * 3 very different hardware systems tested, plus VirtualBox with Mint ISO as a live session
 ```

**Issue**

Drag & Drop files to the desktop are moving when they should be copying, and copying when they should be moving.

**Steps to reproduce the issue (also happens with Mint ISO as live session)**

1. In ~/ create an empty document, then on another partition also create an empty document
2. Drag empty document form ~/ to the desktop, empty document moves as expected. Drag it back to ~/
3. Now drag the empty document from the other partition to the desktop, empty document also moves (rather than copies). Move the empty document back to other partition.

Logout and back in, then perform the following (basically reverse of above)...

4. This time, first drag empty document from the other partition to the desktop, empty document copies as expected. Delete copied empty document from the desktop.
5. Now drag empty document from ~/ to the desktop, instead of moving it now copies

**Other information**

- Seems whichever sequence is performed first after login sets up a president for other file transfers to the desktop until the next login.

- Above only happens while dragging files to the desktop. Opening ~/Desktop in a window and dragging files there from other locations works as expected.

- Issue seems to have begun since 18.2, connected with desktop grid updates?

**Comment by mtwebster** [comment]
reproduced,  thanks for the detail - it is connected with the grid changes.

**Comment by tkalfaoglu** [comment]
Still exists in nemo-desktop 3.8.6
