### ISSUE TITLE
Open terminal icon does not work in root nemo

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1643]
```
 * Nemo version (nemo --version) 3.4.7
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 17.2
 * Graphics hardware *and* driver used:  Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller; 2.1 Mesa 17.0.7

 * 32 or 64 bit: 64
 ```

**Issue**

When I click Nemo's toolbar terminal icon, when running as root, nothing at all happens.

**Steps to reproduce**

Open Nemo as root. Click the icon (if it is there; if it is not, add it through Nemo's options).

**Expected behaviour**

A terminal should open, in the folder that Nemo is at.

**Other information**

**Comment by CottonEaster** [comment]
The problem persists into nemo 3.6.5, unfortunately.

**Comment by feren** [comment]
Trying it on Mint 17.3 Cinnamon, I can't reproduce this issue, not sure about the Cinnamon creators though (version 3.6.4), have you got GNOME Terminal installed?

**Comment by CottonEaster** [comment]
@feren 

Yes, the two computers on which I have the problem (Mint 18.3 Cinnamon on both) each has Gnome-Terminal. Still, perhaps there is a problem with my DCONF / Gsettings config - could you tell me what value therein should be where, please?

**Comment by feren** [comment]
org.cinnamon.desktop.default-applications.terminal exec (But given you're using a proper Mint 18.3 Install, it should already be set as gnome-terminal out of the box, as Mint themselves have intended)

**Comment by CottonEaster** [comment]
Thanks. I've checked on one of the affected computers[1] and the DCONF is set already as you say it should be - thus;

![image](https://user-images.githubusercontent.com/9998846/34449896-ecc73464-ecf5-11e7-85a8-c09f57ab144e.png)

But - ah - I have found that the computer in question *is no longer affected*; opening a terminal from root nemo now works. How odd - it didn't work yesterday. I'll test on my other computer . .


[1] The computer at issue started with XFCE and was switched to Cinnamon. The other affected computer (the second of my two Mint computers) started out as, and is currently, Cinnamon.

**Comment by CottonEaster** [comment]
It works, now, on my other computer too. So, I am closing the issue.

**Comment by CottonEaster** [comment]
This problem has just re-occured for me (on Mint 18.3): pressing the terminal icon, within root nemo, is doing nothing.

**Comment by clefebvre** [comment]
Please troubleshoot and find the exact cause of the problem. You can reopen the issue if the responsible component proves to be Cinnamon.

http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.
