### ISSUE TITLE
Toolbar button to toggle show/hide hidden files

### ISSUE THREAD

**Issue by jpork** [linuxmint/nemo#1646]
```
 * Nemo version (3.6.2)
 * Is issue with windowed nemo?
 * Distribution - (Fedora 27)
 * 64 bit
 ```
Having a toolbar button for toggle showing/hiding hidden files would be very useful. This button could also provide visual feedback about the current hidden file display state (show or hide). 

Sometimes I prefer the shortcut Ctrl+h sometimes I miss the button. It depends on whether I use a desktop pc or a laptop and if my hands are currently busy with keyboard or mouse.

This button would give also feedback about the current display status. Otherwise I need to toggle this feature on and off in order to really know that the current folder has really no hidden files.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
