### ISSUE TITLE
Nemo doesn't hold with Trash folders from mounted partitions

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/nemo#1647]
```
 * Nemo version: 3.4.7
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 18.2
 * Graphics hardware *and* driver used: Nvidia GT630 + Nvidia proprietary driver
 * 32 or 64 bit: 64 bit
 ```

**Issue**
When you mount some folders from different hard disk / partition to your system, than remove files from them, they appear in .Trash-1000 subfolder of that mounted folder. 
After this you can't see them in Trash tab of Nemo. It's quite difficult to look over each mounted folder (one for images, one for some program's data, etc).
You need only to delete them (from .Trash-1000/files), and their info (from .Trash-1000/info).

**Steps to reproduce**
1. Mount some partition in fstab.
2. Mount some folders in fstab.
3. Reboot.
4. Remove some file from mounted folder.

**Expected behaviour**
I think, there are 2 ways:
 - Not to place files on mounted folder into Trash bin, telling user: "cannot remove to trash on mounted folder. Delete it totally ?"
 - Just add to Trash tab all files from all .Trash-1000 folders on all mouned partitions / folders. I think it's a better way. Maybe to divide trash tab in Nemo to separate tabs: each for each .Trash-1000 folder. But I'm not sure about it. Anyway, just adding files is better way than leaving all as it is, or removing them passing the Trash bin.

**Other information**
My /etc/fstab file:
[fstab.txt](https://github.com/linuxmint/nemo/files/1480681/fstab.txt)
My "sudo fdisk -l output":
[fdisk.txt](https://github.com/linuxmint/nemo/files/1480682/fdisk.txt)

Best regards,
Vladislav

**Comment by matthiasfaeth** [comment]
I prefer option 2 of expected behaviour, too: 
- add to Trash tab all files from all .Trash-1000 folders on all mouned partitions / folders 
- divide trash tab in Nemo to separate tabs: one for each .Trash-1000 folder.

**Comment by gusbrs** [comment]
Just chiming in to report I'm also affected by this with Nemo 5.6.3, Cinnamon 5.6.7, and Mint 21.1, and have been affected by it since at least somewhere along the Mint 20 cycle.

As to what to do about this, listing files from `.Trash-$uid` is a requirement of the freedesktop Trash specifications, which states: 

> For showing trashed files, implementations SHOULD support (1) and (2) at the same time (that is, if both $topdir/.Trash/$uid and $topdir/.Trash-$uid are present, it should list trashed files from both of them).

(see https://specifications.freedesktop.org/trash-spec/trashspec-latest.html).

I don't know how Nemo implements the trashing of files and the listing of the Trash's contents, but curiously, in my system, trashed files from a partition different from the "home trash" also beats `gio trash --list`. So there may be something upstream at play.

For the record, since in another related issue (https://github.com/linuxmint/nemo/issues/3030), it was stated that it worked for partitions mounted with `fstab`, my partition for which this fails is mounted with `pam_mount`.  Though I don't see how the mounting method should have any bearing upon expected behavior, it should work however the filesystem was mounted.

**Comment by mtwebster** [comment]
The trash spec is implemented by GVfs - Nemo only accesses a `trash://` and uses `g_file_trash`(from glib) to send things there.

I did quick look at the bug tracker there and glib - one related thing I came across was this:
https://gitlab.gnome.org/GNOME/glib/-/issues/251

Someone there did note that the spec doesn't require that mounts be supported, though in this case, as you observe, it half-works, which is worse than not at all.

Doing a quick test, it looks like it supports fstab-defined mounts for me, but not something like a usb stick.

**Comment by gusbrs** [comment]
Oh, though I get your position, I certainly didn't expect to trigger the closing of the issue.  :-(

So, Nemo does rely on glib after all. The problem is not in trashing the files, which is done correctly, it is just when listing the files which `gio trash --list` does not look into (is this what `trash://` is behind the scenes?).

By the specification, true, theoretically it does not require that files be trashed to the topdir of mounts. But as soon as encrypted partitions come into play, not supporting this quickly becomes sloppy. But, *if the topdir trash directories do exist*, per specs they "should" be listed, as the quote from my comment seems to state clearly, as far as I read it.

(I couldn't check the links you provided, as gnome.org seems to be faulting on my side at the moment. But I will later on. Thanks, btw.)

**Comment by mtwebster** [comment]
Well now it seems to work for me. On a USB stick and any mounts...

I'll keep an eye on it - if for no other reason than to discover what random thing I did to make it work.

**Comment by gusbrs** [comment]
> Well now it seems to work for me. On a USB stick and any mounts...
> 
> I'll keep an eye on it - if for no other reason than to discover what random thing I did to make it work.

I have a guess, or at least some more info.

I have a setup here with an internal HDD, where `/dev/sda2` is where the system is installed (and where `/home` is), `/dev/sda4` is a luks encrypted partition where I store my personal files. Then I have a second *external* HDD for backup, it has only one partition `/dev/sb1`, also luks encrypted.

Both `/dev/sda4` and `/dev/sdb1` get mounted at login with `pam_mount`, with pretty much the same options:

```
<volume user="<myuser>" fstype="crypt" path="UUID=<uuid of /dev/sda4>" mountpoint="/mnt/foo" options="defaults,fsck" />
<volume user="<myuser>" fstype="crypt" path="UUID=<uuid of /dev/sdb1>" mountpoint="/mnt/bar" options="defaults,fsck,nofail" />
```
If I move a file from `/home` to the trash, it goes to `$HOME/.local/share/Trash`, as expected, and everything works as it should. That's the easy case, they are both in the same filesystem.

If I move a file somewhere below `/mnt/bar` to trash, it goes to `/mnt/bar/.Trash-1000`, and it also appears in the Trash for Nemo, and can be cleared with "empty trash" etc. So, all good so far.

However, if I move a file somewhere below `/mnt/foo` to trash, it goes to `/mnt/foo/.Trash-1000`, as it should, but it does not appear in the Trash for Nemo. Which, with this setup, is at least better than if the consistency of `gio` meant the file went to `$HOME/.local/share/Trash`, which is in a non-encrypted partition, and would be a deal breaker for whatever system would do this.

The only difference, as far as I can tell, is that one is a partition of an internal disk (a "non removable" one), while the other is plugged in through USB. And, out of that distinction, `gio` appears to classify the files in `/mnt/foo` as "non user interesting", to use the expression in that bug report. It really beats me... Not to mention the inconsistency between moving to trash and listing the trash files.

**Comment by ddouglas87** [comment]
I'm having this issue where my main drive deleting items appears in the trash can in Nemo, but deleting on a secondary drive moves the files to .Trash-1000 and this does not appear in the trash bin.  What's interesting is the secondary hard drive is set to nofail and is still having issues:

```
bunny@happy:~$ cat /etc/fstab 
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda2 during installation
UUID=******* /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda1 during installation
UUID=*******  /boot/efi       vfat    umask=0077      0       1
#swapfile                                 none            swap    sw              0       0
/dev/disk/by-uuid/******** /mnt/hunk auto nosuid,nodev,nofail,x-gvfs-show 0 0
```

I commented out the swapfile, though I doubt that has anything to do with it.  Hunk is the hard drive that creates .Trash-1000 and has issues.

Does anyone know a manual solution to this (getting .Trash-1000 to report in Trash in Nemo)?

**Comment by Jeremy7701** [comment]
What filesystem is on `/dev/disk/by-uuid/********` ?

**Comment by ddouglas87** [comment]
>What filesystem is on /dev/disk/by-uuid/******** ?

It says ext3/ext4.  I believe it's been long enough since it's been formatted that it's ext3.

**Comment by Jeremy7701** [comment]
If its a ext3 or ext4, you could just mount it as ext4 (but possibly only get the ext3 features) - are all those mount options (`auto nosuid,nodev,nofail,x-gvfs-show`) actually necessary?

**Comment by ddouglas87** [comment]
I have no idea if they're necessary.  The Mint installer formatted the hdd and mounted it around 10 years ago back when it was I think Mint v2 or v3 and I've not touched the hard drive since, even through os reinstalls, because it holds backup data.

**Comment by Jeremy7701** [comment]
That's great - I wouldn't touch anything else if its now working for you.

**Comment by ddouglas87** [comment]
I just tried to delete something else and no go, it's not being put in the trashcan.  I have no idea why it randomly worked once and now is not.
