### ISSUE TITLE
Adding returning folder animation

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/nemo#1648]
```
 * Nemo version: 3.4.7
 * Is issue with desktop or windowed nemo?: windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 18.2
 * Graphics hardware *and* driver used: Nvidia GT 630 and Nvidia proprietary driver
 * 32 or 64 bit: 64 bit
 ```

**Issue**
When you drag folder icon to some "wrong" place, like panel, there is animation of returning that icon back onto it's place. But when you drag icon to the free place in folder (which is done by mistake very often) (while automatic sorting turned on), it's absent.

**Steps to reproduce**
1. Open some folder.
2. Drag icon to Cinnamon's panel (to the free space).
3. Turn on automatic arranging of items (for example, by name) (if it was not turned on already)
4. Drag icon to free space on the same folder.

**Expected behaviour**
I think, it would be great to add "returning folder animation" when you just dragged folder to free space on the same window (while content is sorted automatically).
Such behavior is already realized when you drag folder to, for example, panel or some other "wrong" place, so I think it would be not very hard to implement it for other cases too.

**Other information**
Video (.mkv) with example (in .zip archive): [nemo_dragging.mkv.zip](https://github.com/linuxmint/nemo/files/1480705/nemo_dragging.mkv.zip)

**Comment by xenopeek** [comment]
Is this issue still reproducible? Could you retest on Linux Mint 20 Cinnamon.

**Comment by vlad0337187** [comment]
@xenopeek , sorry, I didn't install new Mint yet.

I checked it in Nemo 4.4.2 in Fedora 32 - there is no returning folder to it's place animation
(if dragged it into a free place in same folder).

But there is animation if to drag this folder, for example, to the panel.

**Comment by xenopeek** [comment]
I retried it from the video on Linux Mint 20 just now and it looks to behave the same. Some notes:

- when you drag a file to a valid drop target the mouse cursor changes to indicate that (a plus, arrow, link or question mark icon is added)—and you can press modifier keys to change the drop action before you let go of the mouse button (Ctrl=copy, Shift=move, Ctrl+Shift=link, Alt=ask what to do)
- there is no return animation for dropping on a valid drop targets
- if you drag a file to an invalid drop target—e.g. to the panel, to a window titlebar or to any of the parts of a window that don't accept dropping (for example with Calculator you can only drop on the input field)—the mouse cursor doesn't change to indicate it's a drop target and you get this return animation
- the default drop action in Nemo when dragging a file within a directory is to move it but while dragging you can press modifiers  to make a copy or a link of the file in the same directory
- and with View > Arrange Items > Manually set in Icon View you can use this to move files to rearrange them

While from the video it looks like there should be a return animation as drag & drop within a directory looks like it should be an invalid drop target, from above last two points I think you'll agree users should get the valid drop target indicator when dragging within a directory.

**Comment by vlad0337187** [comment]
@xenopeek I got your idea.

My thoughts: if you drag and drop file to the same folder - it won't move anywhere. It'll be left at the same folder. So it would be OK to add animation of slow returning it back - describing user that it won't be moved there.

And also it would be good to check: is manual arranging activated or not. If it's activated - than dragging item to the same folder would make sense. And same animation won't be needed.
