### ISSUE TITLE
Toolbar buttons for "View" modes are buggy

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1649]
```
 * Nemo version (nemo --version)
nemo 3.6.2

 * Is issue with desktop or windowed nemo?
windowed

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch

 * Graphics hardware *and* driver used
Nvidia 387.22
 * 32 or 64 bit
64bit
 ```

**Issue**
New version of nemo has some real issues with how "View" toolbar buttons work. 

1) After you start nemo, none of the view buttons are selected. For example, I'm clearly in the "List view" but the button for "List view" is not selected:
![view](https://i.imgur.com/DTQIzbu.jpg)

You can click around on items in the "Favorites" sidebar and view buttons will not be updated.

2) Sometimes, buttons will reflect the wrong state of the view. I cannot reproduce it with 100% repeatability but nemo would sometimes have "Icon view" button selected when the view was actually in the "List view". For example, in a pic below nemo's toolbar states I'm in icon view when I'm in a list view:
![icon](https://i.imgur.com/UwNSDFO.jpg)
When you double-click on a folder, the button reflects the parent's state and doesn't update the state of th current folder.

This bug is new. Previous versions of nemo did not have these issues.

**Comment by mtwebster** [comment]
I've noticed this as well, I need to find what caused it.

**Comment by feren** [comment]
Yeah, I noticed it too, it seems like the Views set only last the Nemo Process's lifetime as being pushed down button-wise...
