### ISSUE TITLE
Suggestion: Add ability to hide Desktop icon labels unless hovered over

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1650]
So, I got a little bit inspired by this Desktop Configuration on Windows, and thought, my Desktop would look kind of cool like that, though, I then soon realised, **there's not yet a way I know of of hiding the Desktop Icon Labels**, in such a way that means they appear on hover, and the icons themselves remain there...

http://kdb.jockington.com/imgs/i.imgur.com/zdEt61L.jpg

So, yeah, it'd be awesome to have the ability to Hide Desktop Icon Labels, with the option to make them visible when hovering over an icon...

**Comment by xenopeek** [comment]
Thanks, your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
