### ISSUE TITLE
Long file names lead to messy visual layout in icon view

### ISSUE THREAD

**Issue by HadrienG2** [linuxmint/nemo#1651]
```
 * Nemo version 3.6.2
 * In windowed mode
 * OpenSUSE Tumbleweed
 * NVidia GeForce GTX 980M + Nouveau driver
 * x86_64
 ```

**Issue**

In some folders, instead of displaying icons on a regular grid, Nemo 3.6.2 puts variable, seemingly random horizontal spacing between them. This seems to be correlated with the presence of files with long file names, which are never abbreviated or spread across multiple lines.

[![Screenshot @ http://hpics.li/69faca1](https://img4.hostingpics.net/thumbs/mini_296326WTFNemo.png)](https://www.hostingpics.net/viewer.php?id=296326WTFNemo.png)

**Steps to reproduce**

1. Open any folder with a bunch of files.
2. Give a long name to one of these.

**Expected behaviour**

I have difficulty understanding whether this behavior is by design, or the result of a bug. But other file managers that I know of try to tackle the problem of long file names in other ways, which I think result in a cleaner and more understandable visual layout:

- Keep a regular grid, but increase the horizontal grid spacing (Thunar)
- Force a line feed when the file name gets too long, if vertical size of the name grows too long as well cut the name with an ellipsis symbol "..." ([OSX Finder](https://www.howtogeek.com/wp-content/uploads/2015/03/img_55074446b5b33.png))

**Other information**

**Comment by leigh123linux** [comment]
It's pango bug

https://bugzilla.gnome.org/show_bug.cgi?id=789625
