### ISSUE TITLE
Nemo can't do SSH connections.

### ISSUE THREAD

**Issue by svin83** [linuxmint/nemo#1652]
* Nemo version 3.4.7
* Linux Mint 18.2 Sonya
Linux version 4.10.0-40-generic (buildd@lcy01-amd64-005) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 (Ubuntu 4.10.0-40.44~16.04.1-generic 4.10.17)

**Issue**
Impossible to connect to ssh servers to manage files. I even did a test, and relaxed the security on my remote server temporarily, to allow password logins, but Nemo still can't connect.

And there's no way to auth without passwords, since  there's no way to specify key files.

**Steps to reproduce**
Try to connect to any ssh server.
I have tried with a couple of Raspberry Pi 3 cards, and an OpenWRT-router. Both the Pi's and the router were on my LAN (10.0.0.2,10.0.0.7 and 10.0.0.101)

I even tested with two remote servers, and none of them would work either.

**Expected behaviour**
For the logins to work when passwords are correct.
To be able to specify id file for authentication without passwords.

**Other information**
When i enable password only logins, I get the "Please verify your user details" or the "Connection Failed"

 Logging in with "ssh user@host -i keyfile" in terminal works, (on ALL hosts I try) but Nemo fails EVERY time.

**Comment by svin83** [comment]
I noticed it "works" if an SFTP server is running on the host, but  not if it's just SSH or SCP. So this entry should be renamed to SFTP since that's what it really is...

**Comment by leigh123linux** [comment]
Works fine here as long as have openssh-server running on the remote.

**Comment by svin83** [comment]
I'm sorry, but you need to learn the difference between SSH and SFTP.

The SMB implementation is bad too. The SMB4K client, several mobile apps
(like AndSMB and ES Explorer Pro) and Windows computers can all open a
share that Nemo can't connect to.

But if it's more important to close cases than to fix what doesn't work,
then I appologize for bothering you.

Den lør. 7. apr. 2018, 09:51 skrev Leigh Scott <notifications@github.com>:

**Comment by SouthboundLucas** [comment]
I had similar issues when the /etc/sshd/sshd_config line:

**Comment by Kylejustknows** [comment]
> I noticed it "works" if an SFTP server is running on the host, but not if it's just SSH or SCP. So this entry should be renamed to SFTP since that's what it really is...

Yes. I did some tests and confirmed this.

Nemo CANNOT connect to a pure SSH SCP server as a file manager.  It throws the EXIT command right after the successful login.

The server side must have SFTP protocol. Which made it unusable to connect the low-end devices which dropbear is used.

**Comment by svein83** [comment]
> > I noticed it "works" if an SFTP server is running on the host, but not if it's just SSH or SCP. So this entry should be renamed to SFTP since that's what it really is...
> 
> Yes. I did some tests and confirmed this.
> 
> Nemo CANNOT connect to a pure SSH SCP server as a file manager. It throws the EXIT command right after the successful login.
> 
> The server side must have SFTP protocol. Which made it unusable to connect the low-end devices which dropbear is used.

Yeah.. Well.. I got tired of broken/lacking functionality and the fact that legitimate issues were ignored (until the list of open issues got too big to ignore?) and then closed (not resolved).

So I ditched both Linux Mint and Nemo about a week after this issue was closed. Never looked back.
