### ISSUE TITLE
Option 'show thumbnails for local files only' disregarded for Samba

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1655]
* Nemo version (nemo --version): 3.6.4
 * Is issue with desktop or windowed nemo? Window
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 17.3 Sylvia
 * Graphics hardware *and* driver used: Intel Mobile 965; 2.1 Mesa 17.0.7
 * 32 or 64 bit: 64

**Issue**

I've some Samba shares, on a different computer, mounted via systemd in fstab. I've got Nemo set to show previews (a.k.a. thumbnails) of 'local files only' - yet, it shows previews of those files. Now, Samba is faster than it was than under Mint 18.2, but, still, I'd like to be able to turn previews off for these files. And, after all, they are not 'local'. Or so it seems to me.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by CottonEaster** [comment]
Still present on Nemo 3.6.5. Note that, Samba (or the difficulty of troubleshooting it) being what it is, sometimes one needs all the speed one can get. Also, I really do not see how files on other computers can count as local. So this _is_ a bug, so far as I can tell.

![image](https://user-images.githubusercontent.com/9998846/37237831-4eeeaf4e-2411-11e8-93f4-8169fd6917b7.png)

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
