### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by Hairybiker** [linuxmint/nemo#1657]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
3.6.4
windowed
Mint 18.3
NV Gtx 750, NV 384.90
64bit
**Issue**
In previous versions, pressing Ctrl + 1 or 2 or 3 would change the icon layout between the presets,  icon/list/detail no longer working

**Steps to reproduce**
Press Ctrl-1 and it produces a search bar with 1 in it. c+2/3 does nothing

**Expected behaviour**
change icon layout

**Other information**

**Comment by JayPiEs** [comment]
i have the same problem, what is the solution?
why is this bug report closed?

**Comment by fcastilloec** [comment]
I have this same problem, why was this bug closed without given any explanation on how to fix this?

**Comment by spsf64** [comment]
@fcastilloec I think it has already been fixed in master branch, we have to wait for the next release...

**Comment by mtwebster** [comment]
Yes it's fixed, just waiting on a release, sorry

**Comment by JayPiEs** [comment]
does anyone knows when it will be released? Isn't it possible to have minor updates?
