### ISSUE TITLE
"Device is already mounted" error when auto-mounted while in "Computer" view

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#1660]
```
 * Nemo version 3.6.4 (issue present since 2.3.4)
 * Is issue with windowed nemo
 * Distribution - Ubuntu 16.04.3
 * Graphics: 4th Gen Core Processor Integrated Graphics Controller, driver: i915
 * 64 bit
 ```

**Issue**
When Nemo is open in "Computer" view (listing all drives) and you plug in a USB storage device, the view will update to show the new device, however, when the device is subsequently automatically mounted and you then try to open it by double clicking on it, Nemo tries to mount it again, resulting in the message "Device /dev/sdxx is already mounted at `/media/name/mountpoint'."
Only after manually refreshing the view, will double clicking open the mounted device.

**Steps to reproduce**
1. Open "Computer" view (list of drives) in Nemo.
2. Plug in USB storage device.
3. Wait for it to show up and be automatically mounted.
4. Double click on the device. 

**Expected behaviour**
The device is opened and its contents are shown.

**Other information**
none.

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I'm not able to reproduce this issue. Using the steps provide I was able to produce the Expected behaviour.
