### ISSUE TITLE
No ask for emptying trash if you eject a USB stick from panel

### ISSUE THREAD

**Issue by Lupusaurus** [linuxmint/nemo#1661]
If you move files to trash in a USB memory, and you eject it from the side panel (through the button or context menu), Nemo didn't ask if you want to empty the trash as it do if you eject it from the desktop, the pathbar, or the context menu by right clicking inside the root folder of the volume.

Nemo version 3.6.4, 64bits.

**Comment by leigh123linux** [comment]
Use the template!

**Comment by Lupusaurus** [comment]
Sorry, better now?
