### ISSUE TITLE
Crash when unmounting drive

### ISSUE THREAD

**Issue by alindt** [linuxmint/nemo#1662]
- Nemo version (nemo --version)
**$ nemo --version
nemo 3.6.4**

- Is issue with desktop or windowed nemo?
**Issue with windowed nemo (file browser)**

- Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
**$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia**

- Graphics hardware *and* driver used
**$ inxi -G
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: X.Org 1.19.3 driver: intel Resolution: 1600x900@60.00hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile GLX Version: 3.0 Mesa 17.3.0-devel
Integrated Graphics Chipset: Intel(R) HD Graphics 4000**

- 32 or 64 bit
**$ uname -p
x86_64**

**Issue**
Nemo window crashes when unmounting a drive (eject icon or Menu=>Eject) while the drive contents are displayed (drive "folder" is selected)

**Steps to reproduce**

1. mount drive by clicking it in "Devices" tree
2. click eject icon or rclick => Eject
3. (**crash**)

**Expected behaviour**
Nemo changes location to a default folder (e.g. Home) and doesn't crash.

**Other information**
```
$ nemo

(nemo:1848): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Initializing nemo-image-converter extension

===> EJECTING DRIVE
===> NEMO WINDOW CLOSES

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(nemo:1848): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

^C
$
```

**Comment by xenopeek** [comment]
Can you please retest this with Nemo 3.6.5? I tried reproducing on Cinnamon but it seems to work fine. Which desktop environment are you running BTW?

**Comment by alindt** [comment]
**$ nemo --version
nemo 3.6.5**

It happens under both Cinnamon and MATE.

NOTE: when opening another tab in Nemo, selecting the removable drive and then ejecting, only the current tab closes - so this might not be a crash per se, it's only that the Nemo window closes when not using multiple tabs instead of keeping it open and changing location to a default directory.

**Comment by clefebvre** [comment]
This is by design. I first had it move to a default location. If I remember well @mtwebster changed it to close the window instead (my solution left a lot of windows open and all pointing to the same directory... especially when a given drive had multiple volumes).

**Comment by alindt** [comment]
@clefebvre By design? That's a pretty wonky design, IMHO...
Then how come for @xenopeek "it works fine" - which I understand to mean the changing to a default directory after unmounting a drive?

**Comment by xenopeek** [comment]
My bad, that "it works fine" was from another issue I was working on.

**Comment by alindt** [comment]
It just occurred to me that I might have been misunderstood: the behaviour I'm reporting is that if there's only one window (no tabs) and you unmount a drive, the whole nemo window closes instead of changing the location to a default one - I don't mean NOT closing the current tab if there are multiple tabs open.
