### ISSUE TITLE
Feature Request: Better control over file name and launcher name colors on desktop?

### ISSUE THREAD

**Issue by afdsgsg** [linuxmint/nemo#1665]
```
 * nemo 3.2.2
 * Is issue with desktop or windowed nemo? Desktop
 * Mint 18.2
 ```

**Feature request**

I would like it if:

1. When you change your desktop background, the text under the icons on your desktop, are inverted from the desktop background, such as seen with CSS filter:invert(100%); - which doesn't appear to be supported by gtk themes.

OR

2. When you change your desktop background, you are given the opportunity to set the text color on the desktop as well.

Note that the second option would probably be easier, and look better in practice, but I don't know if it would introduce more complexity, such as two completely different teams having to consult with each other to make it happen.

**Use case**

If you want to change your desktop background between something really light and really dark without changing your theme and without manually editing your theme's files.

See here for an idea of what I mean:
https://imgur.com/6yVJlA7

**Expected behaviour**

You change your desktop background and the text is immediately recolored to be made legible again.

**Other information**

I've seen the issue of desktop text color being brought up before here as well:
[https://forums.linuxmint.com/viewtopic.php?t=167081](https://forums.linuxmint.com/viewtopic.php?t=167081)

**With that, please correct me if I should post this elsewhere. Thank you.**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
