### ISSUE TITLE
Folding sharing: '"net usershare" returned error 255'

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1667]
```
 * Nemo version (nemo --version) 3.6.4
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

Please see this screenshot:

![image](https://user-images.githubusercontent.com/9998846/33837817-90b056de-de85-11e7-9250-69bde5bf2c2f.png)

**Steps to reproduce**

Try to share a folder, at least on the version of Samba I am using (viz., 4.3.11).

**Expected behaviour**

There should be no error.

**Other information**

EDIT: The share works fine if added manually to /etc/samba/smb.conf

**Comment by leigh123linux** [comment]
Your issue belongs to nemo-extensions

https://github.com/linuxmint/nemo-extensions/tree/master/nemo-share

**Comment by CottonEaster** [comment]
It would be nice were github to have a 'transfer issue' function! But I've done it manually.
