### ISSUE TITLE
Cinnamon desktop artifacts after new files are created/moved 

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1669]
```
 * Nemo version (nemo --version)
nemo 3.6.4
Cinnamon 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia 387.34
 * 32 or 64 bit
64bit 
```

**Issue**
After a new file is created on the desktop, there's some artifacting as you move your mouse around. It's a minor issue but it's annoying.
![https://i.imgur.com/bZqeR0L.png](https://i.imgur.com/bZqeR0L.png)

**Steps to reproduce**
Create a new file or move a new file that doesn't have an icon preview created onto the desktop. For example, here's a video of what happens when I create a new screenshot of the desktop:

![artifact](https://thumbs.gfycat.com/DapperPoisedIndochinesetiger-size_restricted.gif)
https://gfycat.com/gifs/detail/DapperPoisedIndochinesetiger

Then just hover your mouse over it after the preview was created. Artifacts disappear after you click the icon.

**Comment by xenopeek** [comment]
I tried reproducing this with Nemo 3.6.5 and couldn't. But I don't have a Nvidia card. Can you retest with Nemo 3.6.5?

**Comment by nick-s-b** [comment]
@xenopeek Yep. I can still reproduce it.
````
$ nemo --version
nemo 3.6.5
$ cinnamon --version
Cinnamon 3.6.7
$ nvidia-smi
Wed Jan 31 15:18:00 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 Driver Version: 387.34                    |
````
![image](https://thumbs.gfycat.com/GlumElasticGar-size_restricted.gif)
Vid: https://gfycat.com/GlumElasticGar

Let me know if I can provide any more info. I'm happy to help... love nemo!

**Comment by leigh123linux** [comment]
I sure this was fixed a while back.
