### ISSUE TITLE
USB drive context menu contains both 'eject' and 'safely remove drive'

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1671]
```
 * Nemo version (nemo --version) 3.6.4
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

My USB drive context menu contains both 'eject' and 'safely remove drive'. There seems to be no difference between these options. At the least, the difference is not explained to the user.

**Steps to reproduce**

Insert USB device and (unless one has disabled this feature) wait for an icon for it to appear on the desktop. Right-click that icon.

**Expected behaviour**

There should be a _single_ context-menu item that pertains to ejecting/safely removing.

**Other information**

**Comment by CottonEaster** [comment]
This problem seems to persist into Mint 19.1, a year later.

I would test this in a VM but my VM of Mint has trouble handling USB sticks at all.

If the bug is reproducible, then new users will encounter it and be thrown by it.

**Comment by LinuxOnTheDesktop** [comment]
I note the persistence of this small, irritating, potentially confusing and seemingly needless problem.I would try to fix it myself, were I to know how.

**Comment by 2635599** [comment]
'USB drive context menu contains both 'eject' and 'safely remove drive'"  both need to be removed altogether. neither one is actually needed anymore, and has been need in any os for years.

**Comment by LinuxOnTheDesktop** [comment]
@ 2635599: really? Does one not need to dismount USB volumes (on all operating systems) before physically removing them, at least in some instances?

**Comment by 2635599** [comment]
@LinuxOnTheDesktop simply put NO. this has not been the case for a very long time. just physically remove them. safely remove is one of the first features i turn off regardless of os, and type of usb drive.

**Comment by LinuxOnTheDesktop** [comment]
[This article](https://www.howtogeek.com/118546/htg-explains-do-you-really-need-to-safely-remove-usb-sticks/) says that on Linux and Windows one _does_ need 'safely remove'. [This one](https://www.maketecheasier.com/the-need-to-safely-remove-usb-devices/) says the same about Windows. I did find an article that said one does _not_ need it, but that article seemed less well informed than the others.

We can agree, though, that certainly one does not need _two_ options. Unfortunately, though, this bug report seems to be getting no attention from the developers.

**Comment by 2635599** [comment]
to be EXTREMELY blunt i do not care what you say or those articles say, cause i am not going to argue with you about something i am right about. i have not used safely remove since at least vista. i know there are plenty that say you still need safely remove, but make no mistake they know better. as for eject that was and is meant for optical drives, why they ever made it cover usb drives as well i will never know. as for peeps addressing this "issue" it's not a issue so nothing to address.

**Comment by LinuxOnTheDesktop** [comment]
> it's not a issue so nothing to address.

Yet, you wrote, also 

> both need to be removed altogether

And so I suggested the compromise of removing the 'eject' option. Anyhow: let us leave the matter for the developers to decide.

**Comment by ManIVIctorious** [comment]
It is definitely required for encrypted devices. Without the signal the cryptsetup does not get unlocked, making it impossible to remount it without root privileges or system reboot.
For write safely remove also sends a notification when all data are written to disk, which can be quite important since the ioscheduler can considerably delay the write.

If your writes have been completed and the device is not encrypted/locked you don‘t have to savely remove it though

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I'm not able to reproduce this issue. Right clicking the mounted USB drive only has `Eject` listed.

**Comment by vassilisw** [comment]
This is madness! But still if he is right about it then he is right!  
Now back to reality: Indeed I can confirm that **Nemo** on **Mint 19 and 20**, _sometimes_ shows _"Safely Remove Drive"_ that also speeds down the hdd (if it is the case), and some times doesn't. Instead just _"Unmount"_ is available that does not speeds down the media.

**Comment by Jeremy7701** [comment]
Under different circumstances, I can recall having seen all three - but never more than one at a time!
_Unmount_ - but only if I issued a CLI mount command - only ever used as a NFS mount, so no effect on disk speed.
_Safely remove_ - I've seen this, can't remember where.
_Eject_ - this one shown for all USB connections including ebook readers, phone connections etc.

**Comment by icarter09** [comment]
I just checked with both an external drive and a USB drive. I wasn't able to reproduce the issue on the desktop for either and also not in the sidebar in the Nemo window. 
Can anyone provide a screen shot of this issue occurring? Don't want to close this ticket out if someone is still experiencing the issue. Thanks.

**Comment by vassilisw** [comment]
This seems to be happening when the usb drive is already connected at boot.

![image](https://user-images.githubusercontent.com/16954451/116047547-d97dfc00-a67c-11eb-8f5a-581ee992e593.png)
![image](https://user-images.githubusercontent.com/16954451/116047620-ef8bbc80-a67c-11eb-8ce0-1cb619357ae2.png)
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"
```
