### ISSUE TITLE
MTP-USB devices list problem

### ISSUE THREAD

**Issue by nerox8664** [linuxmint/nemo#1677]
```
 * nemo 3.6.4
 * windowed nemo
 * Arch Linux
 * nvidia prime 
 * 64 bits
 * Android MTP-device
 * not very good usb-cable 
 ```

**Issue**
There is a problem with displaying MTP devices list. When I disconnect my MTP device, it still keep in the devices list in the left nemo panel. So, when I attach it again, a new device in the list is appeared.

**Steps to reproduce**
Attach MTP-USB device, detach MTP-USB device several times.

**Expected behaviour**
As I think, the detached device should disappear from the devices list.

**Other information**
![2017-12-17 00-54-08](https://user-images.githubusercontent.com/3521007/34074651-e01b4efc-e2c4-11e7-8cb3-2d984a26cae2.png)
![2017-12-17 00-54-32](https://user-images.githubusercontent.com/3521007/34074652-e04553fa-e2c4-11e7-8b6c-23854ff1435e.png)

**Comment by andreldm** [comment]
It's a gvfs bug as described here: https://gitlab.gnome.org/GNOME/nautilus/issues/154

**Comment by leigh123linux** [comment]
Closed

https://bugzilla.gnome.org/show_bug.cgi?id=789491
