### ISSUE TITLE
"Send by email" context menu item

### ISSUE THREAD

**Issue by bastimeyer** [linuxmint/nemo#1678]
```
 * Nemo version: 3.6.4
 * Nemo windowed mode
 * Distribution: Arch 
 * xf86-video-intel
 * 64 bit
 ```

**Issue**

- Right-clicking the `Trash` menu item in nemo's side bar opens a context menu which includes a "Send by email" action.
- The context menu of the trash desktop icon doesn't include such an action, but isn't perfect either, since it includes a disabled "Move to trash" action instead.

![image](https://user-images.githubusercontent.com/467294/34076062-ca7a7724-e2da-11e7-8821-b58eb8c4c450.png)
I'm using the screenshot of this reddit thread posted by /u/NICO_THE_PRO (not me):
https://www.reddit.com/r/CrappyDesign/comments/7k9747/when_you_really_hate_someone_just_email_him_your/

**Other information**

"Send by email" may be correct English, but IMO "Send via email" is a much better phrasing for this action and you can see this being used basically everywhere else.

The context menu action was implemented here:
#1625

**Comment by leigh123linux** [comment]
Your translation issue belong to cinnamon-translations

**Comment by bastimeyer** [comment]
> Your translation issue

that was just a side node....

The issue here is, as described in the text above the screenshot, that there is a "Send by email" context menu action for the trash menu item in nemo's sidebar, which doesn't make any sense.

**Comment by bastimeyer** [comment]
So you don't want to reopen this thread? I'm sorry if I wasn't clear enough with my first post...

According to the reddit thread I've linked, many people including me think that "Send by email" shouldn't be an option on the Trash context menu.

It's included in the context menu, because of this line
https://github.com/linuxmint/nemo/blob/3.6.4/files/usr/share/nemo/actions/send-by-mail.nemo_action#L181
and trash not being a regular directory...

**Comment by leigh123linux** [comment]
No, file another without the translations issue
