### ISSUE TITLE
"Send by email" context menu action

### ISSUE THREAD

**Issue by bastimeyer** [linuxmint/nemo#1679]
```
 * Nemo version: 3.6.4
 * Nemo windowed mode
 * Distribution: Arch 
 * xf86-video-intel
 * 64 bit
 ```

Opening another thread, since #1678 was apparently misleading...

**Issue**

Right-clicking the **Trash** menu item in Nemo's side bar opens a context menu which includes a "Send by email" action. **This context menu action doesn't make any sense** and shouldn't be there. It's included because trash is not a regular directory and thus not excluded by [this line](https://github.com/linuxmint/nemo/blob/3.6.4/files/usr/share/nemo/actions/send-by-mail.nemo_action#L181) (added in #1625)...

![image](https://user-images.githubusercontent.com/467294/34076062-ca7a7724-e2da-11e7-8821-b58eb8c4c450.png)
I'm using the screenshot of this reddit thread posted by /u/NICO_THE_PRO (not me):
https://www.reddit.com/r/CrappyDesign/comments/7k9747/when_you_really_hate_someone_just_email_him_your/

**Comment by dglava** [comment]
Same issue as #1603.

As mentioned there, it also happens on the Network icon in the sidepane.

**Comment by xenopeek** [comment]
Same issue as  #1603.
