### ISSUE TITLE
Suggestion: Extra-pane button in toolbar 

### ISSUE THREAD

**Issue by DanielRios549** [linuxmint/nemo#1682]
```
 * Nemo version (3.6.5)
 * Is issue windowed nemo
 * Distribution - (Mint 18.3)
 * 64 bit
 ```
Why ins't there an option to add "extra pane" to toolbar? I think it is an important feature for missing.

My suggestion is adding an option in preferences > tollbar tab, to create a button in toolbar to toggle this feature.

The expected behaviour is the same as F3 keyboard shortcut.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by naheller** [comment]
Hi - did this ever go anywhere? I see it's marked as complete, but I don't see the change in Nemo. Happy to help if it's still open.

Mint 22.2
Cinnamon 6.4.8
Nemo 6.4.5
