### ISSUE TITLE
Suggestion: Hide folder and files graphically

### ISSUE THREAD

**Issue by DanielRios549** [linuxmint/nemo#1685]
```
 * Nemo version (3.6.5)
 * Is issue windowed nemo
 * Distribution - (Mint 18.3)
 * 64 bit
 ```

Recently, I learned that we can hide a folder or file without the dot in front of them, just by creating a file called .hidden, and adding the folders or files we want to hide to this file. I think it's a good idea to add an option in properties window to make this graphically.

To reproduce it is simply necessary a right click on file and/or folder, and click on hidden checkbox, in basic tab.

The expected behaviour is simply adding the file or folder names inside the .hidden file, creating it, if not exists.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
