### ISSUE TITLE
Nemo follow FreeDesktop standards for its icon

### ISSUE THREAD

**Issue by orschiro** [linuxmint/nemo#1686]
I am not sure if I should report this against Nemo or Cinnamon. Please indicate.

My problem is that I am using Numix Circle icon theme and Nemo is the only application that is not using the proper icon:

![image](https://user-images.githubusercontent.com/170947/34885486-6d9c8c7c-f7c0-11e7-887d-283c6b62b6f9.png)

I reported this against Numix first but it seems to be better suited here. Quoting one of the Numix contributors:

> It's just the file manager you use doesn't use the correct icon. I hate cinnamon just because they don't respect the FreeDesktop standards. They're using an icon from the Places context instead of the Applications context. See here for more information https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

Source: https://github.com/numixproject/numix-icon-theme-circle/issues/78#issuecomment-357224587

Original issue for reference: https://github.com/numixproject/numix-icon-theme-circle/issues/78#issue-288046152

**Comment by bil-elmoussaoui** [comment]
https://github.com/linuxmint/nemo/blob/master/data/nemo.desktop.in.in#L135
`folder` is not an application icon.  The icon must be renamed to either `nemo-file-manager` or `system-file-manager` 
See here https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html

**Comment by leigh123linux** [comment]
@bil-elmoussaoui  Does the same apply to nautilus?

https://gitlab.gnome.org/GNOME/nautilus/blob/master/data/org.gnome.Nautilus.desktop.in#L8

**Comment by bil-elmoussaoui** [comment]
@leigh123linux Well, the use their own icon name, so I don't see any problem with that........You can use `org.whatever.Nemo` or whatever icon name, as soon as it's not an icon from an other context....

**Comment by clefebvre** [comment]
I agree. I don't think users see "nemo" as an application per se, they just see places, but that doesn't mean we should enforce using places icon. If we want to make that choice, we can use an app icon and simply have our icon theme make the nemo icon look like a place. So in short, I kinda agree with the bug report here.

That said.. 

> I hate cinnamon just because they don't respect the FreeDesktop standards. They're using an icon from the Places context instead of the Applications context. See here for more information https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

^ This is super-lame. You can use specs to justify a point of view. Explain it though and be constructive. Hating is ridiculous.

Let's forget that poor introduction and start fresh, shall we? Nice to meet you Bilal. We don't hate your work. If you can act like a gentleman we'll be delighted to help.

**Comment by bil-elmoussaoui** [comment]
@clefebvre Sorry, but i didn't mean that I hate the work you guys do. It's awesome! But through, a lot of your apps uses icons from other contexts... And I have reported few of them. I don't use Cinnamon daily, but I installed it just to make sure you guys get the right bug reports and make the icon themes makers life easier!

**Comment by clefebvre** [comment]
@bil-elmoussaoui, no problem. We're all focused on very different things and we can always learn from each other. It's actually a pleasure to be shown how to improve once everything's cordial and done in a good mood. Let's address this here.

@orschiro can you prepare a PR for this?

**Comment by bil-elmoussaoui** [comment]
@clefebvre Done that ;) the default theme should link the `nemo` icon to `folder` icon

**Comment by clefebvre** [comment]
@bil-elmoussaoui thanks :)

**Comment by bil-elmoussaoui** [comment]
@clefebvre Thanks to you ;) and sorry again for the bad use of the word "hate"!

**Comment by orschiro** [comment]
@clefebvre @bil-elmoussaoui I am grateful for how this issue ended. 

Looking forward to more Numix design in Linux Mint. :-)
