### ISSUE TITLE
Search options are broken in Nemo, can only search by "file type"

### ISSUE THREAD

**Issue by herpderpus** [linuxmint/nemo#1688]
```
  Nemo version (3.6.5)
  Distribution - (Mint 18.3)
  64 bit
 ```

**Issue**
Trying to search for a file, and then clicking the + icon to add search parameters, only shows "file type" in what appears like it should be a scrollable list with multiple options.

I made a thread about it some time ago here: https://forums.linuxmint.com/viewtopic.php?f=47&t=258508

**Comment by xenopeek** [comment]
Nemo no longer offers search options so closing this.
