### ISSUE TITLE
[Feature Request] Open with... shortcuts

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#1690]
```
 * Nemo 3.6.5
 * Both desktop and windowed
 * All distributions
  ```

**Issue**

Often times I think it would be convenient to have a quick way to open a file not with the standard application, but a secondary choice, but as soon as there's more than three associated programs, the "Open with..." menu is a hassle, as there are no keyboard shortcuts inside the list.

The main examples are all cases of different applications for viewing and editing (images, videos, html, etc.).

**Feature Request**

Dynamically create keyboard shortcuts from the first letter of the application name.

**Discarded idea**

This was my first thought, that I discarded as too complicated and limited. I still decided to include it here, in case I am wrong and it is actually easier to implement than the above:
Offer a shortcut (like Ctrl+Enter) for a secondary program for each file type. Two issues:
1. Storing the second favourite program may be a big task, as it is probably not supported by the current file type association databases.
2. Why stop at two programs? Sometimes you have more, like a photo gallery viewer, an individual image viewer and several editors.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
