### ISSUE TITLE
Files selected by type-ahead search can't be copied

### ISSUE THREAD

**Issue by christophra** [linuxmint/nemo#1699]
```
 * nemo 2.8.7
 * Windowed
 * Mint 17.3
 * i7-5500U integrated graphics, intel drivers
 * 64 bit
 ```

**Issue**
When using the type-ahead search, files (i.e. files and directories) are selected and can be opened by pressing "enter". However they can not be copied with Ctrl+C, unless selected again.

**Steps to reproduce**
1. Open nemo.
2. Type a letter.
=> first match (if any) is selected
3. Ctrl+C
4. Change directory
5. Ctrl+V
=> no copy appears.

**Expected behaviour**
It gets copied.

**Other information**
I know this is an old version, so please accept my apologies if this has been fixed.

**Comment by xenopeek** [comment]
Not reproducible with Nemo 4.6.4 on Linux Mint 20 Cinnamon. While the type-ahead search is still open, pressing Ctrl+C does copy the highlighted file and it can be successfully pasted elsewhere afterwards. This appears to have been fixed.
