### ISSUE TITLE
Auto-arrange slows down the desktop

### ISSUE THREAD

**Issue by gabrielfern** [linuxmint/nemo#1705]
```
 * Nemo version (nemo --version)
nemo 3.6.5
 * Is issue with desktop or windowed nemo?
desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
mint 18.3
 * Graphics hardware *and* driver used
intel hd graphics 620, the open source default, it happens with nvidia too and nvidia driver
 * 32 or 64 bit
64 bit
 ```

**Issue**
Making auto-arrange on makes the desktop menus extremely slow, and menu of properties extremely slow too, but not with files only with folders icons. This doesn't happen with mint y icons for example, but with svg icons.

**Steps to reproduce**
Turn auto-arrange, so use some of the svg based icons.

**Expected behaviour**
Context menus and animations of menus in properties smooth.

**Other information**
Check out the video below that shows what happens with auto-arrange on
https://youtu.be/IBSlVf2qMVc

**Comment by xenopeek** [comment]
I can't notice a difference in the time it takes to open Properties for a desktop folder—with a 0.5 MB SVG icon—between having auto-arrange on and off with Nemo 4.6.4 on Linux Mint 20 Cinnamon. I assume this is fixed.
