### ISSUE TITLE
SVG based icon themes

### ISSUE THREAD

**Issue by gabrielfern** [linuxmint/nemo#1706]
```
 * Nemo version (nemo --version)
nemo 3.6.5
 * Is issue with desktop or windowed nemo?
both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
mint 18.3
 * Graphics hardware *and* driver used
intel hd graphics 620, the open source default, it happens with nvidia too and nvidia driver
 * 32 or 64 bit
64 bit
 ```

**Issue**
This only happens with icons of folders, not with files. The problem, which occurs on all svg based icon theme as far as i know,  is that moving with the arrow keys on folders is not as smooth as it should be, first there are a delay when you starts to move to other folder quickly, it it only selects the next folder after a delay, and second problem, it eventually jumps folders when moving through more than 2, like if there's 3 folders if you hit the right arrow key twice it teletransport the selected folder to the third, not moving through the middle, and if there're lots of folders it can appear various folders after if you move using the arrow key quickly, not selecting any before folder in the path.
This only happens with svg icon themes, not with mint y for example.
As we see here, i've thought this issue was with the icon, but testing in nautilus, this seems to be a nemo issue, only.

**Steps to reproduce**
Install some svg based icon theme, and select one folder on nemo and start moving to others.

**Expected behaviour**
All movement through folders being smooth and selecting al folders in the path, not teleporting to a folder without selecting the before folders in the path.

**Other information**
Check out a example of this happening
https://youtu.be/o53a04q4HR0
It literally doesn't select the folder on the middle if i hit right arrow key twice.
Again, not happen with nautilus on the same system and using the same themes.

**Comment by xenopeek** [comment]
If this is still an issue for you please retest on Linux Mint 20 Cinnamon or with Nemo 4.6.4 on other distro and add which icon theme you used and where you got it. I've tried but can't reproduce it.
