### ISSUE TITLE
[Improvement] "Computer view" in nemo file manager.

### ISSUE THREAD

**Issue by SiamSami** [linuxmint/nemo#1714]
It's not an issue but rather an improvement. In nemo file manager, there's no "Computer view". I mean, the view where it shows all the partitions with how many spaces does the partition have. There's file called "Computer" in Cinnamon desktop environment. However, it doesn't show the spaces left in the partitions. Even Windows has this feature.

So please add this feature as soon as possible.....

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
