### ISSUE TITLE
Nemo Crash on Ubuntu 

### ISSUE THREAD

**Issue by 4C3** [linuxmint/nemo#172]
I wish I could give the steps to reproduce this but I don't really know how. It is kinda random

gdb nemo
GNU gdb (GDB) 7.5-ubuntu
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /usr/bin/nemo...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/nemo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb695ab40 (LWP 16232)]
[New Thread 0xb5f7fb40 (LWP 16233)]
[New Thread 0xb55ffb40 (LWP 16234)]
[New Thread 0xb4dfeb40 (LWP 16235)]
[New Thread 0xae990b40 (LWP 16241)]

*\* (nemo:16225): WARNING **: Can not calculate _NET_NUMBER_OF_DESKTOPS

*\* (nemo:16225): WARNING **: Can not calculate _NET_NUMBER_OF_DESKTOPS

*\* (nemo:16225): WARNING **: Can not get _NET_WORKAREA

*\* (nemo:16225): WARNING **: Can not determine workarea, guessing at layout
[Thread 0xb55ffb40 (LWP 16234) exited]
[New Thread 0xb55ffb40 (LWP 16242)]
[New Thread 0xadd7db40 (LWP 16243)]
[New Thread 0xad57cb40 (LWP 16244)]
[New Thread 0xacd7bb40 (LWP 16245)]
[New Thread 0xac57ab40 (LWP 16246)]
[New Thread 0xabd79b40 (LWP 16247)]
[New Thread 0xab578b40 (LWP 16248)]
[New Thread 0xaad77b40 (LWP 16250)]
[Thread 0xae990b40 (LWP 16241) exited]
[Thread 0xabd79b40 (LWP 16247) exited]
[Thread 0xaad77b40 (LWP 16250) exited]
[Thread 0xab578b40 (LWP 16248) exited]
[Thread 0xad57cb40 (LWP 16244) exited]
[Thread 0xb55ffb40 (LWP 16242) exited]
[Thread 0xacd7bb40 (LWP 16245) exited]
[Thread 0xac57ab40 (LWP 16246) exited]
[Thread 0xadd7db40 (LWP 16243) exited]
[Thread 0xb4dfeb40 (LWP 16235) exited]
[New Thread 0xb4dfeb40 (LWP 16276)]
[Thread 0xb4dfeb40 (LWP 16276) exited]
[New Thread 0xb4dfeb40 (LWP 16277)]
[Thread 0xb4dfeb40 (LWP 16277) exited]
[New Thread 0xb4dfeb40 (LWP 16312)]
[Thread 0xb4dfeb40 (LWP 16312) exited]
[New Thread 0xb4dfeb40 (LWP 16405)]
[Thread 0xb4dfeb40 (LWP 16405) exited]
[New Thread 0xb4dfeb40 (LWP 16415)]
[Thread 0xb4dfeb40 (LWP 16415) exited]

(nemo:16225): Gdk-ERROR **: The program 'nemo' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 33949 error_code 9 request_code 62 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Program received signal SIGTRAP, Trace/breakpoint trap.
0xb74cc3fd in g_logv () from /lib/i386-linux-gnu/libglib-2.0.so.0
(gdb) backtrace
#0  0xb74cc3fd in g_logv () from /lib/i386-linux-gnu/libglib-2.0.so.0
#1  0xb74cc583 in g_log () from /lib/i386-linux-gnu/libglib-2.0.so.0
#2  0xb7a58219 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#3  0xb7a63a0b in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#4  0xb7795ad6 in _XError () from /usr/lib/i386-linux-gnu/libX11.so.6
#5  0xb7792a4e in ?? () from /usr/lib/i386-linux-gnu/libX11.so.6
#6  0xb7792aa7 in ?? () from /usr/lib/i386-linux-gnu/libX11.so.6
#7  0xb77937a0 in _XReply () from /usr/lib/i386-linux-gnu/libX11.so.6
#8  0xb778eccb in XSync () from /usr/lib/i386-linux-gnu/libX11.so.6
#9  0xb7a72a06 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#10 0xb7a4aecb in gdk_window_process_all_updates () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#11 0xb7b86979 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#12 0xb7a2bebe in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#13 0xb74c1c30 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#14 0xb74c49e3 in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
#15 0xb74c4d80 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#16 0xb74c4e61 in g_main_context_iteration () from /lib/i386-linux-gnu/libglib-2.0.so.0
#17 0xb7664b3c in g_application_run () from /usr/lib/i386-linux-gnu/libgio-2.0.so.0
#18 0x080679f8 in ?? ()
#19 0xb71444d3 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#20 0x08067a45 in ?? ()

(gdb) quit

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.10
DISTRIB_CODENAME=quantal
DISTRIB_DESCRIPTION="Ubuntu 12.10"

**Comment by Vahan86** [comment]
@4C3, is this still an issue for you with Nemo 3.0.6 (Mint 18)?
