### ISSUE TITLE
USB sticks do not get icon on desktop if removed (properly) and reinserted

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1737]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Desktop (?)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit: x64
 ```

**Issue**

USB sticks do not get icon on desktop if removed (properly) and reinserted.

**Steps to reproduce**

1) Insert stick.
2) Wait a few seconds.
2) Remove stick (with 'eject' or 'safely remove').
3) Wait a few seconds.
4) Repeat 1-3, possible twice.

**Expected behaviour**

The icon should appear each time (on each step 1).

**Other information**

**Comment by leigh123linux** [comment]
This is a known gvfs issue

**Comment by clefebvre** [comment]
Is this reproducible ALWAYS? or SOMETIMES?

Anything relevant in syslog/dmesg?

**Comment by CottonEaster** [comment]
Reproducible: often (so, not always, but more than the word 'sometimes' suggests.

Here is a snipset from syslog:

![image](https://user-images.githubusercontent.com/9998846/35573826-0b600f2a-05d0-11e8-8948-6af3e5ac076e.png)

I am unsure that dmesg contains anything relevant.

**Comment by CottonEaster** [comment]
Two usb drives, including one no longer attached to the computer, showed up in Nemo's 'computer' window. It was difficult to remove either of them from them, using either (!) the 'eject' or the 'safely remove' context menu options.

**Comment by xenopeek** [comment]
Closing considering age of issue and OP is no longer on GitHub to retest.
