### ISSUE TITLE
Suggestion for improvement of user experience: show numbers on Nemo zoombar

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1748]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.3

 ```

**Issue**

- Nemo's GUI settings allow the user to set _percentage_ zoom levels.
- The slider at the bottom of Nemo windows gives _no percentages_. 
- That feature (/lack of feature) of the slider makes it hard to set the former as one likes, for fairly obvious reasons.
- So, why not show percentages on the zoom bar, perhaps as a tooltip?

**Comment by CottonEaster** [comment]
I'd like to bump this, especially given the following.

If one changes Nemo's 'icon view defaults' zoom level, Nemo immediately - well, upon closing the options window, I think - applies the setting to the current window. Or at least it does so if no custom view has been defined. (Again: I think. I find it all rather confusing.) _However_, if one then changes the default zoom back, then the icons in the present window do not change (because now that window has a custom setting?)

**Comment by JosephMcc** [comment]
> That feature (/lack of feature) of the slider makes it hard to set the former as one likes, for fairly obvious reasons.

I don't buy this. Slide it until it's the size you like. The actual percentage number doesn't really mean much.

The behaviour from the setting window does seem a bit strange and I don't know why that happens. I'm not familiar with that but it's a separate issue.
