### ISSUE TITLE
Misplaced banner when viewing trash

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1750]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel HD Graphics 620; don't know about driver (I-Nex and CPU-G won't install, `lscpi | grep VGA` does not yield much - computer is a 'ThinkPad 13').
 * 32 or 64 bit: 64
 ```

**Issue**

Rubbish bin/empty trash bar is vertically misplaced. Please see attached screenshot.
![nemo misplaced banner](https://user-images.githubusercontent.com/9998846/35702241-81d0d68c-0790-11e8-8530-d0428b803bd2.png)

**Steps to reproduce**

System Settings -> User Interface Scaling -> 'Double'.
System Settings ->Fonts -> 'Text scaling factor' -> 1.0 (though I've had it at other values previously, if this is relevant).

**Expected behaviour**

Banner should be vertically aligned (though I would not mention this infelicity were it not likely connected to problems that are more severe).

**Other information**

13.3 FHD screen.

**Comment by JosephMcc** [comment]
This was a dup anyway :) https://github.com/linuxmint/nemo/issues/1430
