### ISSUE TITLE
[Feature request] Check if files differ if they conflict.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo#176]
When a file conflict occurs, check if the files differ and provide a message "The files are identical" of something in the file conflicts dialogue if they are identical.

You could use the shell command 'diff'

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by YabamenoTate** [comment]
Are there any plans for this to be implemented?

**Comment by Jeremy7701** [comment]
Files are never identical - they might have the same name but will have different create/update/access timestamps.

**Comment by YabamenoTate** [comment]
I consider “identical files” to be binary matches. of contents.
Unless we consider timestamps, partitions, etc,
if there is no difference in the contents of the files, I would not lose any data by overwriting.
This is the basis for the user's decision to overwrite or rename.
Furthermore, if the contents are identical, the write process to the storage can be omitted when overwriting, which is friendly to the storage life, which is all good!
