### ISSUE TITLE
Nemo ignores locale settings (partially)

### ISSUE THREAD

**Issue by Lonnyzrag** [linuxmint/nemo#1770]
```
 * Nemo version (nemo --version) : nemo 3.6.5
 * Is issue with desktop or windowed nemo? : windowed nemo 
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : Mint 18.3 XFCE fresh install
 * Graphics hardware *and* driver used : VBox, Nvidia, Nouveaux (does not seems related, reproduced on several machines)
 * 32 or 64 bit : 64 bit (32 bit not checked)
 ```

**Issue**

Nemo displays menu (complete) and dialogs (partially) in wrong language  after fresh installation of Mint 18.3 Xfce

**Steps to reproduce**
sudo apt update && sudo apt install nemo
start nemo via menu or bash (with or without --no-desktop)

**Expected behaviour**
Menu and Dialogs should be displayed in language configured with mintlocale

**Other information**
also documented here: [My Mint forum entry](https://forums.linuxmint.com/viewtopic.php?f=47&t=263028&p=1424388#p1424388)

i could reproduce this issue on 3 machines (1x virtualbox vm, 1x real metal with nvidia prop drivers, 1x real metal with nouveaux)

`~ $ apt-show-versions nemo-data`
`nemo-data:all/sylvia 3.6.5+sylvia uptodate`
`~ $ apt-show-versions nemo`
`nemo:amd64/sylvia 3.6.5+sylvia uptodate`
`nemo:i386 not installed`
`~ $ apt-show-versions libnemo-extension1`
`libnemo-extension1:amd64/sylvia 3.6.5+sylvia uptodate`
`libnemo-extension1:i386 not installed`
`apt-show-versions xfce4-session`
`xfce4-session:amd64/xenial 4.12.1-3ubuntu1 uptodate`
`xfce4-session:i386 not installed`

`~ $ mintlocale 
Starting mintlocale
User language in .dmrc: de_DE.UTF-8
User language in $LANG: de_DE.UTF-8
Current language: de_DE.UTF-8
Current region: de_DE.UTF-8
AccountsService language is: 'de_DE'`

`cat /etc/default/locale 
LANG=de_DE.UTF-8
LANGUAGE=de_DE:de
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
`
`wc -l .xsession-errors
0 .xsession-errors
`

**Comment by Pjotr123** [comment]
One shouldn't ever try to replace the default file manager, which is after all the backbone of the desktop environment. It's simply asking for all kinds of weird problems.

**Comment by Lonnyzrag** [comment]
really? this is your explanation/help?
btw: i have also installed nemo besides thunar on a test machine. and starting nemo with --no-desktop shows the same behavior. So if there is a option for "--no-desktop" which implies that i can start the application which is first of all a file manager, shouldn't it behave as other applications that are not used as primary component in other DE's?

**Comment by Pjotr123** [comment]
Yes, really, this is my explanation/help.

You've just spoiled your system. Try to undo it or, even better, do a clean re-installation of Mint Xfce. Klare Sache und damit hopp.

**Comment by Lonnyzrag** [comment]
As I have overseen that "--no-desktop" parameter is deprecated which means (in my opinion) that nemo should no longer work without issues in other DE's than cinnamon.

So I guess no one would work on compatability issues like this one. i will close the issue
