### ISSUE TITLE
assign keyboard shortcuts - how?

### ISSUE THREAD

**Issue by herrdeh** [linuxmint/nemo#1771]
```
 * Nemo version 3.4.7
 * windowed nemo
 * ubuntu 17.10
 * nvidia 340
 * 64 bit
 ```

**Issue**
How can I assign keyboard shortcuts to nemo?

**Steps to reproduce**
I found the recommendations to create:
~/.config/nemo/accels   or
~/.gnome2/accels/nemo 
Neither work.

**Expected behaviour**
Being one of the most used apps, the file manager should be well configurable, I think.

**Additional info**
If a conveniant configuration method does not exist, there should be one.

**Comment by NikoKrause** [comment]
Menu -> System Settings -> Keyboard -> Shortcuts (tab) -> Create Custom Shortcuts (button)

**Comment by herrdeh** [comment]
Could it be the case you're talking about Linux Mint?
I'm on ubuntu GNOME - I do not think we have such a handy way of dealing with it. True?

**Comment by NikoKrause** [comment]
Ah yes indeed. My bad. I thought this was the Cinnamon repo. Sorry

**Comment by dejo-ro** [comment]
Using ~/.gnome2/accels/nemo worked for me with nemo 3.6.5 on Ubuntu 18.04   @herrdeh , have you tried logging out and back in after creating the file (not just restarting nemo)? This seems crucial.

**Comment by herrdeh** [comment]
Sorry you didnt hear such a long time.
I tried your suggestion, but on my system (ubu 18.04, nemo 3.6.5) editing the file 
`~/.gnome2/accels/nemo/accels` does not do anything. After something like 15s after system login, the file is altered back to the previous state.

**Comment by xenopeek** [comment]
There's information on the forum on how to set accels for Nemo: https://forums.linuxmint.com/viewtopic.php?p=1696073#p1696073.

**Comment by nilslindemann** [comment]
I further had to define the environment variable `GNOME22_USER_DIR`, like described [here](https://forums.linuxmint.com/viewtopic.php?p=2057171#p2057171). [The code](https://github.com/linuxmint/nemo/blob/72f2fa785efc8fd432eb2bd843b75287ae1adc1c/libnemo-private/nemo-file-utilities.c#L166-L187=) indicates it should just work, when putting the _nemo_ file under _~/.gnome2/accels/_ but that is not the case for me, dunno why.
