### ISSUE TITLE
Cannot drag or drop files in bottom-right-snapped window

### ISSUE THREAD

**Issue by imasaru** [linuxmint/nemo#1778]
```
 * Nemo version: v3.4.5
 * Is issue with desktop or windowed nemo? Windowed Nemo
 * Distribution: Mint 18.2
 * Graphics hardware *and* driver used: NVIDIA GeForce GTX 750Ti + nvidia-340 (NVIDIA binary driver)
 * 32 or 64 bit: 64-bit
 ```

**Issue**
When I snap/pin a Nemo window specifically to the bottom-right of the screen, I cannot drag and drop files inside the window or from another window into that window. All other snap positions work.

The cursor is not visible in the screenshots, but notice how the intended folder is highlighted in green when the window is not snapped to the bottom-right:

![candrag](https://user-images.githubusercontent.com/10376491/36080344-4beec328-0f54-11e8-9962-c929839f34bf.png)

![cannotdrag](https://user-images.githubusercontent.com/10376491/36080345-4dcd62da-0f54-11e8-9ec0-d9aefdb4fee8.png)

**Steps to reproduce**
1. Snap a Nemo window to the bottom-right of the screen.
2. Try to drag a file into a folder. Instead of the "plus-hand" that appears when copying a file, or the "arrow-hand" that appears when moving, the hand is just a hand.

**Expected behaviour**
One should be able to drag and drop a file or folder as with any other snapped Nemo window.

**Other information**
None that I can think of, besides my using the `nvidia-340` instead of the latest version due to compatibility issues with [Redshift](https://github.com/jonls/redshift).

**Comment by xenopeek** [comment]
Possibly this had a different cause when it was reported but in current Linux Mint 20 Cinnamon there is a general issue with drag & drop not working for bottom right tiled window: https://github.com/linuxmint/muffin/issues/566

**Comment by ACR-Jeff** [comment]
Still an issue in LMDE 4 with Nemo version 5.0.3
