### ISSUE TITLE
Wallpaper is not zoomed in on secondary screen

### ISSUE THREAD

**Issue by 3n4rKy** [linuxmint/nemo#1780]
```
 * nemo 3.6.5
 * nemo-desktop
 * Ubuntu 16.04 with gnome 3.18.5
 * NVidia GTX 650 Ti with driver 384.111
 * Two displays left: 1920x1200 (16:10, secondary) / right: 2560x1440 (16:9, primary)
 * 64 bit
 ```

**Issue**
When starting nemo-desktop the wallpaper on the left display has a huge black bar at its top. On the arrange display dialogue a small black bar is normal because of the resolution difference but this doesn't appear on screen of course. It's neither possible to reduce the bar by rearranging the displays.  The only effect I got is that the bottom of the wallpaper appears in the top of the screen in the black bar.
gsettings set org.gnome.desktop.background picture-options is set to "zoom" 
When i set both displays to the same resolution (1920x1200) it's working fine and wallpapers are filling the whole desktop

**Steps to reproduce**
- take 2 display with different resolutions
- use a wallpaper with zoom
- start nemo-desktop

**Expected behaviour**
I assume that nemo-desktop takes the alignment from the display with the higher resolution and applies this to the one with lower resolution instead of zooming in.

**Other information**
I know this is not a fundamental issue but it prevents me from using nemo-desktop.

This is how it looks with a black bar (nemo-desktop started):
![with_nemo-desktop](https://user-images.githubusercontent.com/7541464/36198283-70ab03c4-1176-11e8-96ac-37d4661d4abd.jpg)

This is how it looks correct (nemo-desktop stopped):
![without_nemo-desktop](https://user-images.githubusercontent.com/7541464/36198284-70c8c0c6-1176-11e8-8aed-b1fec55a93dd.jpg)

**Comment by JosephMcc** [comment]
Nemo doesn't handle the desktop wallpaper. Do you see the problem without nemo-desktop running?

**Comment by 3n4rKy** [comment]
Hi,
no, as I wrote, without nemo-desktop (second screenshot) the wallpaper is fine. With nemo-desktop running (first screenshot), the wallpaper is zoomed in and has a black bar at the top.

**Comment by xenopeek** [comment]
Zoom looks to work properly on Linux Mint 20 Cinnamon with two different resolution displays, at least with Intel.
