### ISSUE TITLE
Shortcuts for Bookmarks

### ISSUE THREAD

**Issue by astier** [linuxmint/nemo#1781]
```
 * Nemo 3.6.5
 * Desktop I guess
 * Mint 18.3
 * 64 bit
 ```

**Issue**
Is it possible to make shortcuts to quickly change the current directory to a desired bookmark-directory?
If so then how?
If not, can it be implemented?

Thanks.

**Comment by david-k** [comment]
Is there any solution to this?

**Comment by astier** [comment]
No.

**Comment by david-k** [comment]
Dammit. I already tried setting `can-change-accels` in `org.cinnamon.desktop.interface` to `true`, and also played around with `~/.gnome2/accels/nemo`, but so far nothing has worked.

Anyway, thank you for the clarification.

**Comment by astier** [comment]
Hm I rather meant I couldn't find any solution so far. Maybe the devs are hiding it and don't want to tell anybody.
