### ISSUE TITLE
Add pause/resume option to copy dialog

### ISSUE THREAD

**Issue by tow3r91** [linuxmint/nemo#1786]
The copy dialog of nemo must have an option for pausing and resuming the copy tasks.

That is an useful function that is present in others file managers such as Dolphin and Pcmanfm.

**Comment by shadow73s** [comment]
Agree, that will be very usefull.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Atalanttore** [comment]
Right now I would need a pause button to pause copying a very large file. Unfortunately there is no pause button and I have to cancel the copy process now and start it again later.

**Comment by metal450** [comment]
Why has this issue been closed? It has not actually been resolved.

**Comment by staltux** [comment]
why this is closed if in 2025 nemo dont have this feature in 6.4.5 ?

**Comment by leigh123linux** [comment]
@staltux  It's fixed in nemo-6.6.0, older releases are considered EOL

**Comment by staltux** [comment]
I didn't expect Arch Linux to have such an old version, thank you
