### ISSUE TITLE
How do I resize specific icons on Desktop?

### ISSUE THREAD

**Issue by nitrocode** [linuxmint/nemo#1787]
Running Mint 18.3 with nemo 3.6.5

**Issue**

I noticed in previous versions, I was able to resize specific desktop icons instead of all of them. I read on this issue https://github.com/linuxmint/Cinnamon/issues/6883 that the feature was removed in nemo 3.4. 

Is this true? If so, why? and is there a workaround such as a plugin?

**Steps to reproduce**

Right click on icon and notice "Resize icon" is missing

**Expected behaviour**

Resize icon is there

**Other information**

None

**Comment by JosephMcc** [comment]
It was removed because there was a higher demand to see the implementation of the desktop grid for icon layout.

**Comment by nitrocode** [comment]
@JosephMcc so what's a workaround to increase the size of an icon if it's too small? If we created a larger image would that work?

**Comment by gabix** [comment]
Hi! Is there a way to get the individual icon resize functionality back?

**Comment by mtwebster** [comment]
For now, you can execute:
```
gsettings set org.nemo.desktop use-desktop-grid false
```
in a terminal, this will restore the legacy desktop behavior, including the ability to resize icons.

This may go away entirely in time, and we are no longer supporting its use or actively maintaining it.

**Comment by gabix** [comment]
Thanks!!!!
![image](https://user-images.githubusercontent.com/2479678/39335680-6adcfa1e-498a-11e8-8bd3-7239581e691a.png)
