### ISSUE TITLE
Crash when attemtping cut-and-paste operation

### ISSUE THREAD

**Issue by ryanmusante** [linuxmint/nemo#1789]
```
 * Nemo 3.6.5
 * windowed
 * Manjaro
 * nvidia 390.25
 * 64 bit
 ```

**Issue**

xmg kernel: traps: nemo[10740] general protection ip:7f27c59d931f sp:7ffc3a0bd068 error:0 in libgobject-2.0.so.0.5400.3[7f27c59a2000+54000]

Crash when attemtping cut-and-paste operation

**Steps to reproduce**

1. Select directory with subdirectories
2. Select subdirectory
3. F2 to rename
4. Right-click to highlight and select copy
5. Crash

**Expected behaviour**

No Crash

**Comment by mtwebster** [comment]
Not sure what version Manjaro is on but this should be fixed in master: https://github.com/linuxmint/nemo/commit/f2eecb2b8921ac0dbd2092800729b937a2dce250
