### ISSUE TITLE
Opening nemo as root causes weird cinnamon behavior

### ISSUE THREAD

**Issue by gfreeau** [linuxmint/nemo#179]
If you try to open nemo as root (sudo nemo .), the cinnamon desktop changes to default. It appears the current cinnamon sessions changes to root permissions. You cannot change settings etc.

Restarting cinnamon, dropping to tty1 and doing a cinnamon --replace does not return it to normal. So far the only way to return to normal is a restart.

**Comment by xenopeek** [comment]
This can be closed I think. It appears Nemo run as root won't handle the desktop. Running `nemo --quit` to stop Nemo from handling the desktop and starting it with `sudo nemo` or `gksudo nemo` doesn't make Nemo handle the desktop again. Only starting it without sudo/gksudo makes it handle the desktop again.

**Comment by pranav-cw** [comment]
> This will only happen if you _didn't_ already have a user Nemo session running before running sudo nemo.
> 
> The first thing Nemo wants to do when starting up is check if it's handling the desktop, and take it over if not. You had nothing handling the desktop, so root nemo took over.
> 
> You can always sudo nemo --quit to end the root session, then just plain nemo (or quicklaunch or from menu) to restore normal desktop.



> This will only happen if you _didn't_ already have a user Nemo session running before running sudo nemo.
> 
> The first thing Nemo wants to do when starting up is check if it's handling the desktop, and take it over if not. You had nothing handling the desktop, so root nemo took over.
> 
> You can always sudo nemo --quit to end the root session, then just plain nemo (or quicklaunch or from menu) to restore normal desktop.

This worked. Thanks.
