### ISSUE TITLE
[Feature Request] Automatically select pane upon click 

### ISSUE THREAD

**Issue by d-packs** [linuxmint/nemo#1790]
```
 * Nemo version 3.6.4
 * Issue with windowed nemo
 * Distribution - Arch Linux
 * DE: Budgie
 * WM: BudgieWM
 * Graphics hardware *and* driver used Mesa DRI Intel(R) Ivybridge Mobile / i915
 * 64 bit
```
**Issue**
When two panes are present, the first click in a pane is ignored and only serves for activating the pane, it's just the second click that gets registered and selects an object

**Steps to reproduce**
Open Nemo in 2 pane mode, click an object in a pane then click an object in the other pane. The second click will not select the object in the second pane. It will just activate the pane.

**Expected behaviour**
Clicking an object should select/perform action on an object, instead of simply activating the containing pane.

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
