### ISSUE TITLE
Directories mounted via fstab show up in the devices list multiple times

### ISSUE THREAD

**Issue by stephbur** [linuxmint/nemo#1793]
```
 * Nemo version (3.4.7)
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - (Ubuntu 17.10)
 * 64 bit
 ```

**Issue**

I have a harddisk mounted to  `/media/data_1` containing several folders (Music, Videos, Pictures, etc.).
I mount those folders to their counterpart in the home directory via fstab entries (see below).
Starting maybe about a year ago, the entry `data_1` now appears in the Devices list once for every mount command.  The top entry named `data_1` points in fact to the root of `data_1`. But the other entries named `data_1` point to `/media/data_1/Music` for instance.

**Steps to reproduce**

Mount several folders on the same hard drive via fstab to other folders. 

`/media/data_1/Music	/home/user/Music	none	bind	0	0 `
`/media/data_1/Photos	/home/user/Pictures	none	bind	0	0`

**Expected behaviour**
I would expect `data_1` only to be listed once or that the other entries in devices are at least named after the directory they point to.

**Other information**

**Comment by CottonEaster** [comment]
This seems to be the same problem, and indeed a more exact diagnosis of the problem, as reported here: https://github.com/linuxmint/nemo/issues/1656.

**Comment by Mintulix** [comment]
Still no progress here (nemo 3.8.5).
It used to work right, must be a small regression and easy to fix.
Again: different binds from the same "master-mount" are always listet in the devices list with the same wrong name (just master-mount, not master-mount/Music e.g.). You can't distinguisch them.

**Comment by ShamrockLee** [comment]
The problem of the icons of bind-mounted directories got solved after recent upgrades and restarting.
I am using Debian Testing (currently Debian Bullseye) and my Nemo version is `4.2.3`.
```
$ apt show nemo
Package: nemo
Version: 4.2.3-2
Priority: optional
Section: misc
Maintainer: Debian Cinnamon Team <debian-cinnamon@lists.debian.org>
Installed-Size: 4,844 kB
Depends: cinnamon-desktop-data (>= 4.2), desktop-file-utils (>= 0.7), gsettings-desktop-schemas, gvfs (>= 1.3.2), libcinnamon-desktop4 (>= 4.2), libglib2.0-data, libnemo-extension1 (= 4.2.3-2), libxapp1 (>= 1.4.2), nemo-data (= 4.2.3-2), shared-mime-info (>= 0.50), libatk1.0-0 (>= 1.32.0), libc6 (>= 2.14), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.10.0), libexempi8 (>= 2.5.0), libexif12 (>= 0.6.21-1~), libgail-3-0 (>= 3.0.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.49.2), libgtk-3-0 (>= 3.21.5), libnotify4 (>= 0.7.0), libpango-1.0-0 (>= 1.20.0), libpangocairo-1.0-0 (>= 1.14.0), libselinux1 (>= 1.32), libx11-6, libxml2 (>= 2.7.4)
Recommends: cinnamon-l10n (>= 4.2), gvfs-backends, gvfs-fuse, librsvg2-common, nemo-fileroller (>= 4.2)
Suggests: eog, evince | pdf-viewer, totem | mp3-decoder, xdg-user-dirs
Breaks: cinnamon (<< 4.2), cinnamon-core (<< 4.2~), nemo-fileroller (<< 4.2)
Homepage: http://cinnamon.linuxmint.com/
Tag: uitoolkit::gtk
Download-Size: 1,094 kB
APT-Manual-Installed: no
APT-Sources: http://opensource.nchc.org.tw/debian testing/main amd64 Packages
Description: File manager and graphical shell for Cinnamon
 Nemo is the official file manager for the Cinnamon desktop. It allows one
 to browse directories, preview files and launch applications associated
 with them. It is also responsible for handling the icons on the Cinnamon
 desktop. It works on local and remote filesystems.
 .
 Several icon themes and components for viewing different kinds of files
 are available in separate packages.

```
