### ISSUE TITLE
Crash when dragging item owned by root to desktop

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1794]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

When I drag an item such as `/usr/games` from a Nemo window to the desktop, whilst holding ctrl - the intention being to create a shortcut - all the icons on the desktop disappear.

**Steps to reproduce**

As above.

**Expected behaviour**

A shortcut should appear?

**Other information**

I am using custom versions of nemo, suppied to me by @mtwebster , so that I could work around another bug.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
