### ISSUE TITLE
FEATURE REQUEST: Open multiple tabs via command line

### ISSUE THREAD

**Issue by Yoshimaster96** [linuxmint/nemo#1795]
This feature has been requested as early as 2013. It is now 2018, and it still doesn't exist. I for one would love to have this feature, it would make setting up workspaces via shell scripts (which I do sometimes) much easier.

**Comment by JosephMcc** [comment]
Is there another request for it here?

**Comment by klemsgithub** [comment]
hi, i needed this feature too so i have implemented it :) (https://github.com/linuxmint/nemo/pull/2032)

**Comment by 2635599** [comment]
they need to consecrate on having nemo save a group of tabs between sessions first.

**Comment by klemsgithub** [comment]
yes but i have already performed the code modification, all they need to do is to accept the pull resquest i made...

**Comment by 2635599** [comment]
that would probably be better as an action you can add. why have scripts and terminal commands to execute when nemo already supports adding actions?

**Comment by klemsgithub** [comment]
I do not understand what are nemo actions. are you talking about context menu?
My need is to launch a nemo windows with a list of specified uri through a script...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
