### ISSUE TITLE
[Feature Request] Apply view to subdirectories recursively

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo#1797]
```
 * Nemo 4.2.3
 * Windowed Nemo
 ```

**Issue**
There is no way to make Nemo use the  current view on the subdirectories.

**Other information**
Ideally I would like a way to tell Nemo to apply the same view from the current directory to all the directories below recursively. I have found [this](https://forums.linuxmint.com/viewtopic.php?t=137422) on the Mint forums, but it doesn't appear to work with the current version.

I guess there could be a button which would apply the view too all directories below.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
