### ISSUE TITLE
Nemo crashes on Wayland when copying large files

### ISSUE THREAD

**Issue by chadwellak** [linuxmint/nemo#1802]
```
 * Nemo version (nemo --version) 

3.6.5

 * Is issue with desktop or windowed nemo? 

Desktop backend

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 
Fedora 27

 * Graphics hardware *and* driver used 

Intel HD 5500, i915

 * 32 or 64 bit  

x86_64
 ```

**Issue**

Gnome 3.26.2 <i>ON WAYLAND</i>
When copying a file that is large enough to require nemo to draw a window with a progress bar (I  don't know if it's zenity) nemo will crash. Locally, this has to be a very large file but on a network destination it only needs to be big enough to trigger a progress bar.
<i>this does not occur within gnome on xorg</i>

**Steps to reproduce**

Gnome <i>ON WAYLAND</i>
Copy a sufficiently large file from one location to another (locally, depending on your drive speed, > 10GB or to a network location that isn't on the LAN, something I'm guessing > 20MB?). The point at which a progress bar would pop up nemo crashes with the following error:
(nemo:10753): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Segmentation fault (core dumped)

**Expected behaviour**

No crash, progress bar, successful copy.

**Other information**

Possibly relevant environment variables:
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0

The same behavior occurs with GDK_BACKEND=wayland

As noted above, this only occurs when running Gnome on Wayland; everything is fine with Gnome on Xorg. I would just use Xorg but unfortunately Wayland is way better scaling some important applications on my HiDPI screen.

This occurs whether it is two separate nemo windows or just one with two panes (which is the main reason I use nemo).

**Comment by mtwebster** [comment]
Any chance of a full trace of the crash?  (Install debug symbols for at least nemo, gtk, glib, run under gdb)

I don't have anything setup here using wayland currently.  When I get a chance I'll try to address.

Thanks

**Comment by mtwebster** [comment]
Taking a quick look, I'm almost certain it's our xapp GtkWindow extensions for window icon and progress reporting (which is x11 only currently.)

I've patched xapps: https://github.com/linuxmint/xapps/commit/fea3ca82fb78a8dfbf8d6c89d5349c8e90763446

I'll look soon for any other potential culprits.

**Comment by chadwellak** [comment]
I can get you a back trace but it may be a little while.

On Mar 8, 2018 8:17 PM, "Michael Webster" <notifications@github.com> wrote:

Taking a quick look, I'm almost certain it's our xapp GtkWindow extensions
for window icon and progress reporting (which is x11 only currently.)

I've patched xapps: linuxmint/xapps@fea3ca8
<https://github.com/linuxmint/xapps/commit/fea3ca82fb78a8dfbf8d6c89d5349c8e90763446>

I'll look soon for any other potential culprits.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxmint/nemo/issues/1802#issuecomment-371716144>, or mute
the thread

**Comment by deekej** [comment]
I got biten by this few days ago. :) I would like to switch to Nemo completely, it's much better than Gnome's stock Files, but I can't ATM moment because of this... :-/

**Comment by tkalfaoglu** [comment]
Same problem here.. 

[turgut@tklaptop ~]$ nemo
** Message: 10:08:22.701: Init Stock Icons
Gdk-Message: 10:08:34.068: Window 0x5626b8b78ca0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 10:08:34.068: Window 0x5626b8b78ca0 is a temporary window without parent, application will not be able to position it on screen.

(nemo:62245): Gdk-CRITICAL **: 10:08:34.077: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
[NULL @ 0x56180b890ec0] Failed to parse extradata
[NULL @ 0x56180b890ec0] Failed to parse extradata
Gdk-Message: 10:08:38.300: Window 0x5626b89c6970 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 10:08:38.300: Window 0x5626b89c6970 is a temporary window without parent, application will not be able to position it on screen.

(nemo:62245): Gdk-CRITICAL **: 10:08:38.306: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed

(nemo:62245): Gdk-WARNING **: 10:08:41.781: gdkwindow-x11.c:5579 drawable is not a native X11 window



Segmentation fault (core dumped)
[turgut@tklaptop ~]$ 
[turgut@tklaptop ~]$ 
[turgut@tklaptop ~]$

**Comment by jtts** [comment]
Here is a backtrace with degging symbols for glib2 (2.56.1), gtk3 (3.22.30) and nemo (3.8.3):

[gdb-nemo-2018-06-10-output-A.txt](https://github.com/linuxmint/nemo/files/2087941/gdb-nemo-2018-06-10-output-A.txt)
[gdb-nemo-2018-06-10-trace-A.txt](https://github.com/linuxmint/nemo/files/2087942/gdb-nemo-2018-06-10-trace-A.txt)

I can confirm that the segfault is caused by any file operation that's big/slow enough to need a progress window, whether it is copying, moving, renaming or deletion.

**Comment by mtwebster** [comment]
Ok really really fixed here: https://github.com/linuxmint/xapps/commit/650a3cc01e7233ddc0b3c3d02488c3a5047746f2

This time I actually installed shell and tested under wayland :)  Sorry for my previous laziness.

**Comment by jtts** [comment]
It looks to me like that patch did it. No more segfault for me. Thanks! And don't worry, I switched to Gnome on Wayland on this week, so at least from my perspective you worked pretty fast! ;)

**Comment by deekej** [comment]
I can't wait for this change to land in Fedora, the Nemo is perfect for me. Thanks! :)

**Comment by leigh123linux** [comment]
@deekej  It requires karma

https://bodhi.fedoraproject.org/updates/FEDORA-2018-607e45bd4c

or it could sit in testing for many weeks.

**Comment by deekej** [comment]
Ah, it's already in Bodhi. Thanks for the info, I'll give it a test... ;)

**Comment by mtwebster** [comment]
been fixed..
