### ISSUE TITLE
Trying to set >1 file executable fails to make any of the files executable

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1803]
```
 * Nemo version (nemo --version): 3.6.5
 * Is issue with desktop or windowed nemo? Windowed (haven't tried desktop)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3 - fresh install.
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
```

**Issue**

Trying to set >1 file executable fails to make any of the files executable.

**Steps to reproduce**

Select >1 item in nemo. Get the properties window up. Tick the 'make executable' box. See whether the files have become executable. On my system, none of them have.

**Expected behaviour**

The items should become executable.

**Other information**

**Comment by leigh123linux** [comment]
What file system type are the files on (ext4?) and are they local or network?

**Comment by CottonEaster** [comment]
The files are nearly all text files that lack file extensions and which contains bash or dash scripts. They are on the local file system, though they were downloaded via `rclone`. Making them executable via `sudo chmod +x -R *` works.

**Comment by leigh123linux** [comment]
Post the file system type!!!!

**Comment by CottonEaster** [comment]
Oh, I'm sorry. I misread your request. The answer is: ext4 (using the logical volume management thingy that Mint asks about upon installation).

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
