### ISSUE TITLE
Drag n Drop images from browser

### ISSUE THREAD

**Issue by LogX7** [linuxmint/nemo#1804]
```
 * Nemo version 3.6.5
 * Distribution - mint 18.3
 * Graphics hardware *and* driver used GT740 with Nvidia-384
 * 64 bit
 ```

**Issue**
can't drag n drop images from browsers 
i have to use the save as method

**Comment by revast** [comment]
If you hold down the CTRL Key while dragging, it works. 
So I guess this bug report can be closed.

**Comment by LogX7** [comment]
@revast  NO IT DOESN'T

**Comment by NikoKrause** [comment]
You didn't told us, which browser you use. With Chrome it seems to work directly.
With Firefox you have to press CTRL as mentioned by @revast .
In the video you see the exact moment when I press the CTRL key the cursor changes to a + symbol:
[Video](https://streamable.com/tck4q)

**Comment by LogX7** [comment]
i have to do view image before dragging ... i'm talking about dragging the image directly from the page

**Comment by NikoKrause** [comment]
I guess this is a browser related issue since it works with Chrome/Chromium.
You would need to report this to Firefox.

**Comment by LogX7** [comment]
I just went to chrome
