### ISSUE TITLE
[Feature request] Add sorting direction to "Arrange items by" column in display settings

### ISSUE THREAD

**Issue by d-packs** [linuxmint/nemo#1806]
```
* Nemo version 3.6.4
 * Issue with windowed nemo
 * Distribution - Arch Linux
 * DE: Budgie
 * WM: BudgieWM
 * Graphics hardware *and* driver used Mesa DRI Intel(R) Ivybridge Mobile / i915
 * 64 bit
 ```

**Issue**
There is no sort order choice for the "Arrange items by" setting in **_Edit > Preferences > Views_** Tab

**Steps to reproduce**
1. Open Nemo
2. Using the main menu navigate to **_Edit > Preferences > Views_** 
3. The "Arrange Items" setting does not allow setting the direction of the sorting action to be specified

**Expected behaviour**
A "Sort direction" field should be present

**Other information**
The main Usage scenario where sorting by date would be relevant is when you would like to see the latest modified files. For this purpose "Descending" would be the desired direction. This is not possible in the current Nemo version, as the hardcoded direction is Ascending (which makes sense when arranging by file name, but no by date).

Here is a mock-up of the additional setting field:
![selection_068_a](https://user-images.githubusercontent.com/33980111/37584563-b00ce788-2b5e-11e8-9140-d6d106594922.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
