### ISSUE TITLE
Segfault/traps upon exiting rename mode

### ISSUE THREAD

**Issue by Celmor** [linuxmint/nemo#1808]
```
 * Nemo version: 3.6.5
 * Is issue with desktop or windowed nemo: windowed
 * Distribution: Manjaro (with 4.15.7-1 kernel)
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 530 / i915
 * 32 or 64 bit: 64 bit
 ```

**Issue**
All nemo windows unexpectedly close upon Segmentation fault

**Steps to reproduce**
- start nemo
- Go into rename mode for a file or folder (F2 or context menu)
- Click on another field on the same line
- Click anywhere else in the file selector panel
->  all nemo windows close and following "traps" message appears in dmesg:
`[ +31.916564] traps: nemo[14077] general protection ip:7fe409ea931f sp:7fffddbfe218 error:0 in libgobject-2.0.so.0.5400.3[7fe409e72000+54000]`

**Expected behaviour**
- rename mode exits
- nemo doesn't close

**Other information**
[Video Recording](https://puu.sh/zMhea/724fb8ddf3.mp4) (6 sec)
[Core dump (gzip compressed)](https://mega.nz/#!R9Fj0CLJ!lLn7qIH93cjkFnxYlvPlQ1jZDIwOuTAJKlmJcmRSqU4)

**Comment by revast** [comment]
+1 can confirm this, witnessed today

**Comment by mtwebster** [comment]
Duplicate: https://github.com/linuxmint/nemo/issues/1689 - fixed
