### ISSUE TITLE
Pasting text in address bar duplicates rather than replaces text

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1809]
```
 * Nemo version (nemo --version): 3.6.5
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: NA.
 * 32 or 64 bit: 64
 ```

**Issue**

See this video: https://app.box.com/s/9r2bogelufeb31icwdl2p3e30enrinu1

**Steps to reproduce**

Unknown. EDIT: but what I did was select text containing a path, select all the text in the address bar, and then paste.

**Expected behaviour**

When all text in the address bar is selected, pasting should wholly overwrite that text.

**Other information**

I reported a similar bug affecting the ALT-F2 command box (though I haven't managed to find that bug now).

**Comment by JosephMcc** [comment]
Can't reproduce. Seems to be fine here on git master.

**Comment by CottonEaster** [comment]
Thanks for checking. I'll re-open this report if, on Mint 19 when it arrives, I still have the problem.
