### ISSUE TITLE
'Stop job' shutdown hang - will this be fixed in Mint 19?

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1812]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo? Perhaps neither, really - but I don't know whether else to file this report or, rather, ask this question
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

I get terrible hangs - well, long delays - on shutdown when I have network shares on my system. It's the dreaded systemd 'stop job' at shutdown. I filed a bug report against systemd, but was told there that their bugtracker treats only bugs with the latest two versions of systemd (currently versions 237 and 238) and (hence) that my systemd was too hold. I was told further to file a bug with my 'upstream distribution'. So I can do that, or - since a further thing I was told was that later versions had likely fixed the bug - perhaps I can simply ask the following.

*What version of systemd will Mint 19 have and will the problem likely be fixed with Mint 19?* Thank you.

**Comment by leigh123linux** [comment]
File the issue against whatever version of systemd ships with ubuntu 'bionic beaver'

**Comment by CottonEaster** [comment]
Thanks. Can you tell whether this problem has arised with Mint?
