### ISSUE TITLE
Moving files from trash to desktop restores them

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/nemo#1814]
```
nemo 3.6.5
windowed
Arch
intel igp  Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
i915
x64
 ```

**Issue**
File is not moved to desktop

**Steps to reproduce**
Drag'n'drop file from trash to desktop

**Expected behaviour**
File is moved to desktop, but to whereever it has been before it was deleted. (standard restore procedure)

**Comment by schaetzc** [comment]
This does not only affect drag'n'drop, but also cut-paste (<kbd>Ctrl</kbd><kbd>X</kbd>, <kbd>Ctrl</kbd><kbd>V</kbd>) and even copy-paste (<kbd>Ctrl</kbd><kbd>C</kbd>, <kbd>Ctrl</kbd><kbd>V</kbd>).

Allowing to move/copy deleted files to another location would be great. Right now it's really unintuitive.

By the way: All three actions (drag'n'drop, cut-paste, copy-paste) result in an error message when the deleted file's original location was deleted or renamed.

**Comment by LinuxOnTheDesktop** [comment]
This problem still besets 19.2. Does it beset 19.3? I hope not, for it is fairly serious problem. For one thing, it can lead users to believe that the OS have irrecoverably deleted their files.

**Comment by leigh123linux** [comment]
@mtwebster Can we close this as it's the expected behaviour for gvfs-trash or do you plan to replace it?

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/0599ae2839263db660c793dd53f9ed70abb9258d
