### ISSUE TITLE
crash at pressing back /  "go to the previous visited location" button

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#1815]
```
 * Nemo version  -  3.6.5-1~webupd8~xenial00
 * Is issue with desktop or windowed nemo? - desktop
 * Distribution - xenial 16.04.3
 * Graphics hardware *and* driver used - virtualbox
 *  64 bit
 ```

**Issue**
crash at pressing back button several times

```
sys:1: Warning: Source ID 425164 was not found when attempting to remove it

Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
finish_info_provider (directory=0x235ac80, file=0x0, provider=0x971b60) at nemo-directory-async.c:4182
4182	nemo-directory-async.c: No such file or directory.

```

**Steps to reproduce**
pressing back button several times, 
but I guess there also has to be a folder missing /already moved/deleted in the list of the folders which gets collected for the back button

**Expected behaviour**
no crash

**Other information**
also (maybe related) nemo gets very slow after using it heavily for some time

**Comment by mtwebster** [comment]
This should be fixed by https://github.com/linuxmint/nemo/commit/5343c5853c5da70d1fa5288b212867766c87bb30

**Comment by revast** [comment]
thanks for fast response!  Should I try compile master? Is it stable enough for daily use? or should I wait for 3.6.6?
