### ISSUE TITLE
no drag selection in list-view    -- feature request

### ISSUE THREAD

**Issue by ErwinBaeyens** [linuxmint/nemo#1818]
```
 * Nemo version 3.6.5
 * Windowed nemo
 * Distribution - Fedora 26
 * Not that it matters but running on a Intel Xeon E3-1200 Integrated Graphics Core
 * 64 bit
 ```

**Issue**
*No drag selection in list mode*
When running nemo in list mode it is not possible to select a group of files by dragging a selection box over the files and directories that you would like to select or work on. In compact or icon mode this is possible. Now you can only select multiple files in list-view by selecting the parent folder or by  selecting the first one and then selecting the next ones by shift - or ctrl - clicking on the following files.  

**Steps to reproduce**
Switch the nemo window to list view and try to select some of the files by dragging a rubberband box over the files you would like to select. 

**Expected behaviour**
Provide the ability to select files by dragging in listview mode just like it possible in the other modes of nemo. 

**Other information**
![screenshot from 2018-03-30 09-44-33](https://user-images.githubusercontent.com/15808295/38129717-7551d90a-3400-11e8-8cc2-eea157e8b316.png)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/nemo/issues/416
