### ISSUE TITLE
Icons rearrange themselves after boot.

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1819]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.3.
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64
 ```

**Issue**

Icons re-arrange themselves after boot. Here are my icons at present:

![image](https://user-images.githubusercontent.com/9998846/38168165-f98fe8b4-353c-11e8-80ec-928aa46b5686.png)

I will add a report in a moment giving their positions are rebooting.
EDIT: problem is intermittent or perhaps dependent somehow on exact icon position. After rebooting, this last time, the icons did not move.

**Steps to reproduce**

From scratch - unknown. On my system as it is at present: reboot.

**Expected behaviour**

Icons should stay where they are put.

**Other information**

Thinkpad X1 Carbon. Hi-DPI.
Align to grid: on. Auto-arrange: off.
All Mint packages up to date.

**Comment by sven0907** [comment]
I have the same Problem but only withe the System icons. 
The error occurs only if the desktop icons are not arranged automatically and not aligned to the grid


![1](https://user-images.githubusercontent.com/39923428/40934450-1daf1d48-6835-11e8-95bf-bcbbf9e868dd.png)
![2](https://user-images.githubusercontent.com/39923428/40934409-006b738a-6835-11e8-9ee9-9354404b79b3.png)

**Comment by mtwebster** [comment]
version?

**Comment by CottonEaster** [comment]
@mtwebster: hello Michael, I gave my relevant version numbers in the original post (unless you want graphics information, which I admit to an omission). @sven0907, what version of Nemo (and Mint) are you using, please?

**Comment by sven0907** [comment]
@CottonEaster,
Version LM 18.3
sven@Aspire-V3 ~ $ nemo --version
nemo 3.4.7
sven@Aspire-V3 ~ $ cinnamon --version
Cinnamon 3.4.6

Hardware: Notebook AspireV3-371 with core i5 16 GB RAM and SSD but Hardware is not importend because i have the same problem in VirualBox

and LM 18.2 with cinnamon is ok and yesterday i test the beta of LM 19 with cinnamon and here is ok too.
