### ISSUE TITLE
gvfsd-metadata spams journalctl when accessing folders

### ISSUE THREAD

**Issue by ryanmusante** [linuxmint/nemo#1821]
```
nemo-git
Windowed
manjaro testing
Nvidia 390.25
64 bit
 ```
With recent update to 3.28 gnome, journalctl is spammed with this message when changing folders or accessing files:

`gvfsd-metadata[2247]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed`

**Steps to reproduce**
1. open nemo
2. select folder in tree on sidebar

**Other**
~/.local/share/gvfs-metadata directory was cleared
reinstalled gvfs
tried nemo and nemo-git

**Comment by leigh123linux** [comment]
Report it against gvfsd-metadata

**Comment by ryanmusante** [comment]
Reported to distro's gvfs, same issue exists.

**Comment by cryptodan** [comment]
This happens on Linux Mint 19 XFCE 64bit 

Aug  8 02:45:30 alphacentauri gvfsd-metadata[29785]: message repeated 7 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Aug  8 02:47:15 alphacentauri systemd[1]: Started Clean the /media/cryptodan/disk mount point.
Aug  8 02:47:15 alphacentauri udisksd[996]: Mounted /dev/loop3 at /media/cryptodan/disk on behalf of uid 1000
Aug  8 02:48:21 alphacentauri ntfs-3g[30076]: Version 2017.3.23 integrated FUSE 28
Aug  8 02:48:21 alphacentauri ntfs-3g[30076]: Mounted /dev/sda4 (Read-Write, label "", NTFS 3.1)
Aug  8 02:48:21 alphacentauri ntfs-3g[30076]: Cmdline options: rw,nodev,nosuid,uid=1000,gid=1000,uhelper=udisks2
Aug  8 02:48:21 alphacentauri ntfs-3g[30076]: Mount options: rw,nodev,nosuid,uhelper=udisks2,allow_other,nonempty,relatime,default_permissions,fsname=/dev/sda4,blkdev,blksize=4096
Aug  8 02:48:21 alphacentauri ntfs-3g[30076]: Global ownership and permissions enforced, configuration type 7
Aug  8 02:48:21 alphacentauri systemd[1]: Started Clean the /media/cryptodan/4602A3EC02A3DF65 mount point.
Aug  8 02:48:21 alphacentauri udisksd[996]: Mounted /dev/sda4 at /media/cryptodan/4602A3EC02A3DF65 on behalf of uid 1000
Aug  8 02:48:23 alphacentauri gvfsd-metadata[29785]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Aug  8 02:48:23 alphacentauri gvfsd-metadata[29785]: message repeated 7 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Aug  8 02:53:16 alphacentauri gvfsd-metadata[29785]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Aug  8 02:53:35 alphacentauri gvfsd-metadata[29785]: message repeated 23 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Aug  8 02:55:13 alphacentauri systemd[1]: Starting Message of the Day...
Aug  8 02:55:13 alphacentauri systemd[1]: Started Message of the Day.

System Specs: http://termbin.com/r5ne

**Comment by CottonEaster** [comment]
Linux Mint 19 x64 Cinnamon, using Nemo:

```
10/10/2018 02:46	X1	gvfsd-metadata[3525]	g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
10/10/2018 02:46	X1	gvfsd-metadata[3525]	g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
10/10/2018 02:56	X1	gvfsd-metadata[3525]	g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
10/10/2018 03:56	X1	gvfsd-metadata[3525]	g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
```
Is [this](https://gitlab.gnome.org/GNOME/gvfs/commit/d7e1397854f32e793b4f65d894908d67072dcb3f) the fix?

**Comment by ryanmusante** [comment]
@CottonEaster Yes, the GVFS package update solved my issues recently.

**Comment by CottonEaster** [comment]
@ryanmusante 
But I have a fully updated Mint Cinnamon, and the message still appears in the log. Did you use a special repository or compile anything yourself?

**Comment by ryanmusante** [comment]
@CottonEaster I'm on manjaro testing branch. I don't remember which update solved it.

**Comment by CottonEaster** [comment]
@ryanmusante 
Thanks; but if we know what package(s) is/are relevant, then, if you'd be so good as to check the relevant version number(s) on your system, I can compare mine. If some new package(s) really is (are) the solution, it would be good were the forthcoming Mint 19.1 to include that stuff.
