### ISSUE TITLE
Desktop wallpaper goes black after running "nautilus" in the Terminal.

### ISSUE THREAD

**Issue by kamyar-nemati** [linuxmint/nemo#1828]
```
 * Nemo version: 3.6.5
 * The issue is with Desktop.
 * Distribution: Mint 18.3
 * Default drivers of the OS are being in use.
 * 64-Bit
 ```

**Issue**
Running the "nautilus" command in the Terminal causes wallpaper goes black. The wallpaper can however be brought back by just simply changing it manually.

**Steps to reproduce**
Desktop background picture (wallpaper) disappears and turns into the black after running the "nautilus" command in the terminal. I realized that after installing "Furius ISO Mount" which comes with "nautilus" as its dependency, the followings have started to happen; Upon right-clicking on either the FireFox downloaded-files list or the Dropbox icon next to the clock in taskbar, selecting the option "Open Containing/Dropbox Folder" will lead to the same black wallpaper issue.

FireFox: "Open Containing Folder" that makes wallpaper black
![screenshot from 2018-04-19 10-05-08](https://user-images.githubusercontent.com/29518086/38967489-de1938b6-43b9-11e8-876d-d42206c97a21.png)

Dropbox: "Open Dropbox Folder" which makes wallpaper black
![screenshot from 2018-04-19 10-05-25](https://user-images.githubusercontent.com/29518086/38967492-e3340560-43b9-11e8-9f0d-b83c70561414.png)

**Expected behaviour**
The desktop background should stay fine when "nautilus" is run.

**Other information**
The issue will no longer exist if "nautilus" is uninstalled.
It seems "nautilus" is being run when the actions in the screenshots are taken.

**Comment by mtwebster** [comment]
Please run the command [here](https://github.com/linuxmint/Cinnamon/issues/3953#issuecomment-380954255) and the followup comments there.

The root problem of nautilus being used to open folders in those cases will be fixed in the next release (at least when nemo-desktop is in use.)

**Comment by JosephMcc** [comment]
This one has been reported multiple times. A search should bring up plenty :)
