### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by bigbruno** [linuxmint/nemo#1829]
I'm compile from github all cinnamon and nemo, because in Deepin Linux package is very obsolete, but today i'm compile and some strings not translated to portuguese, but before all is ok.

In nemo copy and cut, in cinnamon all options to logoff, shutdown, reboot...

**Comment by NikoKrause** [comment]
There was added mnemonics for `Copy` and `Cut`, i.e. `Copy` changed to `_Copy`
And the translation template has been only updated a few hours ago. So this will be fixed.
It's translated here: https://translations.launchpad.net/linuxmint/latest/+pots/nemo/pt/+translate?show=untranslated

About the logoff, shutdown, reboot. I don't see this. Can you create screenshots?

**Comment by bigbruno** [comment]
![image](https://user-images.githubusercontent.com/6098501/39072388-c052edce-44c0-11e8-9c29-26911ed13de5.png)

**Comment by NikoKrause** [comment]
It's translated on my machine. Did you updated the cinnamon-translations?
https://github.com/linuxmint/cinnamon-translations

**Comment by NikoKrause** [comment]
What's the output of

**Comment by NikoKrause** [comment]
What's the output of those commands on your machine?
```
grep "Log out of this system now?" /usr/share/locale/pt/LC_MESSAGES/cinnamon-session.mo

grep "Alternar Utilizador" /usr/share/locale/pt/LC_MESSAGES/cinnamon-session.mo 
```

**Comment by bigbruno** [comment]
Binary file /usr/share/locale/pt/LC_MESSAGES/cinnamon-session.mo matches

Binary file /usr/share/locale/pt/LC_MESSAGES/cinnamon-session.mo matches

**Comment by NikoKrause** [comment]
Hmm... not sure what's going on. The translations are there. But why aren't they used?

**Comment by bigbruno** [comment]
i don't know too

**Comment by NikoKrause** [comment]
Sorry, I am at my wit's end with this
