### ISSUE TITLE
Feature request: decouple Nemo display of timestamps from global setting

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1830]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: N.A.
 * 32 or 64 bit: N.A.
 ```

**Issue**

It would be useful were Nemo's date settings independent of the global setting (yes?) used to determine whether or not e.g. seconds are displayed on the panel clock. For, then, one could see seconds on the clock - which is useful for timing things - without displaying irrelevant information (namely, seconds) in Nemo datestamps.

Windows offers this functionality (in that clicking on its taskbar clock shows seconds; perhaps also the Windows taskbar clock can itself be set to show seconds without it affecting timestamps in Windows Explorer).

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
