### ISSUE TITLE
Feature request: hourglass when running programs from Nemo

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1833]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

I downloaded [GeekBench](http://www.geekbench.com/download/linux/), unpacked it and - hindered admittedly by lack of instructions from the software creator - ran a few files from the archive. Shortly I had multiple instances (none of which opened windows) running and my CPU and motherboard were at almost 100 degrees C. The problem here is partly poorly written software, but if Mint showed an hourglass pointer when a program had been run from Nemo but had yet to open a window, then I feel my computer would be less likely to become toast. (I have written to the authors of the software too.)

**Comment by leigh123linux** [comment]
Sorry I don't get it.
Nemo is just a filemanager, it doesn't run or care what crappy software you choose to run.

**Comment by maxyz** [comment]
I think that the request could be: act as if StartupNotify=True was set when launching an executable directly from nemo.

**Comment by leigh123linux** [comment]
@maxyz Thanks, I still dislike the idea.

**Comment by JosephMcc** [comment]
I believe it's usually up to applications to set the state of the cursor. This isn't something I see us doing.
