### ISSUE TITLE
[Bug] Nemo's show-desktop-icons depreciated DCONF Key still affects nemo-desktop

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1834]
```
 * Nemo version 3.8.0
 * Is issue with desktop or windowed nemo? desktop
 * Distribution - Ubuntu 18.04 with Mint 19 PPA (also affects Mint 18.3)
 * Graphics hardware *and* driver used Intel
 * 32 or 64 bit 64 bit
 ```

**Issue**

There's a DCONF Key in /org/nemo/desktop called show-desktop-icons, and its description clearly states it is depreciated, and yet it still easily affects the running of Desktop Nemo when turned off, preventing it from Drawing Desktop Icons, even overriding the setting in System Settings > Desktop.

**Steps to reproduce**

Just turn org.nemo.desktop show-desktop-icons Off in DCONF Editor

**Expected behaviour**

Nothing will happen, as the key is 'depreciated', and the System Settings > Desktop value will affect the visibility of Desktop Icons instead, or at least be more important a setting than show-desktop-icons

**Other information**
I know this may break some programs like Komorebi 2, who try to hide many Desktop Icon Drawing Programs by disabling them in their respective Settings platforms, but for a setting that's depreciated, shouldn't it be of no effect now?

**Comment by mtwebster** [comment]
It did (accidentally) no longer have any effect when we redid how the desktop is managed, but for the very reason you mentioned (other programs or desktops wanting to disable it *entirely*) we re-enabled its functionality.

This doesn't mean we don't still recommend not using it.  Within the cinnamon environment, there is no way to access it save via the terminal or dconf-editor.  There's another setting we use now that prevents icons from being drawn, but still provides a backdrop to perform right-click actions on.

Deprecated doesn't mean 'broken' or 'removed.'  It means not recommended, and it may be removed at some later date.
