### ISSUE TITLE
Icons in location view 

### ISSUE THREAD

**Issue by sc44** [linuxmint/nemo#1836]
```
Nemo 3.8.0
Arch 
64 bit
 ```
In location view nemo 3.8.0 don't use te theme icons.

**Comment by sc44** [comment]
In the sidebar, i forgot this, and not shure "location view" is right, sorry for my bad english. 
in nemo 3.6.5
![bildschirmfoto vom 2018-04-23 13-32-48_1](https://user-images.githubusercontent.com/38653443/39124302-3d5d13d0-46fb-11e8-9cdf-e33f089d7b1e.png)
3.8.0
![bildschirmfoto vom 2018-04-23 13-27-57_1](https://user-images.githubusercontent.com/38653443/39124458-dab6e37c-46fb-11e8-94ab-d7bf068e0993.png)

**Comment by JosephMcc** [comment]
That was changed intentionally. It now uses symbolic icons.

**Comment by NikoKrause** [comment]
I guess we need symbolic for places in Mint-X
