### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by nerox8664** [linuxmint/nemo#1839]
```
 * nemo 3.8.0
 * windowed nemo
 * Arch Linux
 * GT540M, nvidia-drivers
 * 64 bit
 ```

After nemo update the scrolling has a problem: when a directory contains a magic number of sub-directories with multiline names the scroll freezes. The bug is appeared after the view changed from 4-in row to 3-in row after subdirectory renaming.

**Steps to reproduce**

Create 19 subdirectories. Name them (some of names should be multiline). Go to any subdirectory and go back to the parent directory. See the not-working scroll (unless you click to the empty place).

**Expected behaviour**

Scroll should work.

**Other information**

![2018-04-26 01-29-42](https://user-images.githubusercontent.com/3521007/39276294-2347c394-48f1-11e8-810b-55668cea0f73.png)
![2018-04-26 01-29-52](https://user-images.githubusercontent.com/3521007/39276295-2366a818-48f1-11e8-88fd-5c674ff04109.png)
![output](https://user-images.githubusercontent.com/3521007/39276271-0b506c46-48f1-11e8-8197-64baa6022524.gif)

**Comment by howdev** [comment]
try a different theme or update nemo

**Comment by xenopeek** [comment]
I couldn't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. I created test directories with:

`for i in {10..45}; do f=$(printf "$i - TestAAAAAAA\nBBBBBBBBB\n"); mkdir "$f"; done`
