### ISSUE TITLE
Double tapping (touchpad) a non-highlighted folder does not open it.

### ISSUE THREAD

**Issue by bambamal** [linuxmint/nemo#1845]
```
 * Nemo version: 3.6.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.3 Cinnamon
 * Graphics hardware *and* driver used: Intel Graphics, default driver
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Double tapping (touchpad) a non-highlighted (unmarked) folder does not open it.

**Steps to reproduce**
- Open nemo in any directory
- Double tap a non-highlighted folder with the touchpad

**Expected behaviour**
- It opens

**Other information**
- Double Tapping the highlighted folder opens it.
- Double Clicking a non-highlighted folder with the hardware buttons works too.
- Double tapping a non-highlighted file to open works.
- But double tapping an non-highlighted folder just marks it.
- Elantech Touchpad with libinput driver, same issue with synaptics
- No issues with double tapping anywhere else on the system or in any other application.

**Comment by xenopeek** [comment]
Considering age of this issue closing it. If any still have this issue please retest on Linux Mint 20 Cinnamon.
