### ISSUE TITLE
Idea: Compact View should have (an option to select) a fixed column width

### ISSUE THREAD

**Issue by MiY4Gi** [linuxmint/nemo#185]
Compact View should have (an option to select) a fixed column width, with file names that can't fit into the columns being truncated until the user clicks on the file (just like in WinXP).

I've noticed this recently. When I'm viewing a folder with hundreds of files, some files have unusually long names, and so when I set the view to Compact, the columns containing those files are as wide as the file names are long. I've attached an image to clarify.

This isn't really a bug, but it might be a better usage of space to fix the width of the columns and truncate especially long names. At the least the user should have the option to do so.

![screenshot](https://f.cloud.github.com/assets/3218375/79416/f379262c-61af-11e2-9821-a6704dc42ec5.jpg)

**Comment by Vahan86** [comment]
The issue is still relevant to Nemo 3.0.6.

![screenshot from 2016-11-09 23-02-51](https://cloud.githubusercontent.com/assets/12819058/20151570/0345610c-a6d4-11e6-96d7-452d47209318.png)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
