### ISSUE TITLE
Hang after suspend, when there is no network (and I have some network share(s))

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1855]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel Kabylake GT1.5 3.0 Mesa 17.2.8
 * 32 or 64 bit: 64
 ```

**Issue**

Nemo - desktop and windowed - stalls, i.e. will do nothing at all (will not allow the dragging of desktop icons, will not open windows) until the network is up, when 

1) There is no network access.

and all of the following conditions are true.

2) I have at least one network share that is (/was) mounted.
3) The computer has just resumed from suspend.

**Steps to reproduce**

The conjunction of 1-3.

**Expected behaviour**

Graceful failure, until the network is up. It should continue to be possible to drag icons and open windows.

**Other information**

Kernel 4.16.3-041603-generic
CPU: Intel i7-8550U (8) @ 4.000GHz 
Memory: 2436MiB / 15803MiB

I run ananicy and conky. It is possible one or other or those programs is causing the problem. Also, the affected PC is a 6th generation X1 Carbon, the hardware of which is rather new and so might cause problems.

**Comment by CottonEaster** [comment]
Let me add - after the problem happened again - that _sometimes_ (when no network becomes available) _no desktop appears at all_ (i.e. there are no icons).

The problem means it's hard to get my laptop to work when it is out of the house.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
