### ISSUE TITLE
Firefox download pane opens files in Nemo, when Nemo is not the preferred file manager

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1856]
```
 * Nemo version (nemo --version) 3.6.5
 * Is issue with desktop or windowed nemo? Both?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

My 'preferred' - i.e. default - file-manager is PcManFM (because I have too many problems with Nemo hanging when it cannot connect to my network shares). Yet, Firefox does not respect that choice. I cannot find the string 'nemo' in firefox's `about:config`, so I assume Mint is to blame.

**Steps to reproduce**

Change 'preferred' file manager to something other than Nemo.
Download something with Firefox.
Use the Firefox download pane (pictured) to open the folder into which the download has gone.

![image](https://user-images.githubusercontent.com/9998846/39963156-d74a0c2c-565b-11e8-821e-738f9198134a.png)

**Expected behaviour**

Firefox should open the 'preferred' file manager.

**Other information**

Is this is the wrong place to file this report, please direct me to the right place.

**Comment by mtwebster** [comment]
You reported this already: https://github.com/linuxmint/nemo/issues/1589

Please read this for explanation: https://github.com/linuxmint/nemo/commit/c9cbba6a2f08be69bf02ffcaf9b0faf4a03ace8b

Fixed in 3.8 (nemo-desktop honors preferred file manager for opening via dbus)
