### ISSUE TITLE
Undo "move to trash" doesn't work

### ISSUE THREAD

**Issue by akerka2** [linuxmint/nemo#1858]
```
 * Nemo version 3.6.5
 * Is issue with desktop or windowed nemo? Desktop nemo
 * Distribution - Mint 18.3
 * GTX 1060, nvidia-84
 * 64 bit
 ```
**Issue**
If I move something to trash, "undo" command does not work. 

**Steps to reproduce**
Send some file or folder to Trash by "delete" key or "Move to trash" right-click command. After that click "Edit->Undo Trash" in menu. This command just does nothing. The file stays in Trash.

**Expected behaviour**
Command must restore file from trash to original location.

**Other information**

**Comment by leigh123linux** [comment]
The issue doesn't reproduce with newer nemo.
