### ISSUE TITLE
Nemo crash after focus lost

### ISSUE THREAD

**Issue by onyxnz** [linuxmint/nemo#1859]
```
 * Nemo version (nemo --version) 3.6.4
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Antergos current
 * Graphics hardware *and* driver used: Intel Integrated on Lenovo z710 laptop
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Nemo crash

**Steps to reproduce**
Unmaximize nemo window
Right click a file, choose Rename. The file's prefix/name is highlighted. Click on another window outside Nemo. Click back to the Nemo window, where the file is still highlighted. Press escape, expecting to remove the highlighting, and return to normal mode.
Nemo drops out.

OR 

Unmaximize nemo window
Right click a file, choose Rename. The file's prefix/name is highlighted. Click on another window outside Nemo. Click back to the Nemo window, where the file is still highlighted. 
Click another file.
Nemo drops out.

**Expected behaviour**
Nemo removes highlighting from the file, and returns to await input.

**Other information**
Noticed because I needed to easily copy file names, so when highlighting the file i can press CTRL+C to copy the name for use in a report. The issue also happens without CTRL+C.

**Comment by xenopeek** [comment]
Not reproducible with Nemo 4.6.4 on Linux Mint 20 Cinnamon. Looks to have been fixed if the original cause was Nemo.
