### ISSUE TITLE
Feature request (that would help with bugs): add 'do not automount on start' option, as in pcmanfam

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1860]
Here's the pcmanfm setting:

![image](https://user-images.githubusercontent.com/9998846/40096838-be2fd598-58ca-11e8-8412-c5f4f1879a34.png)

The sort of bugs this would mitigate: #1378

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
