### ISSUE TITLE
Restore last tabs when starting

### ISSUE THREAD

**Issue by piegamesde** [linuxmint/nemo#1861]
```
 * Nemo version 3.8.2
 * Arch Linux
 * 64 bit
 ```

Almost every browser nowadays has an option to restore the last session on start. Most of them look like this:

 - Open a default location (this is what Nemo currently does)
 - Open a fixed set of tabs
 - Restore the tabs from last session (this is what I want)

There is no reason a file manager shouldn't have this feature too and many other file managers do have it, so this is a major drawback for using Nemo.

I know there is #1260 which is related, but it's request is more broad, kind of diffuse and difficult to find. So I'm reopening this in a more specific way in the hope it will get more attention.

**Comment by morfikov** [comment]
I also am missing the `restore tabs on startup` feature. It's really inconvenient to start browsing files all over again  and again, instead of just be placed in the dir/dirs you left off. Any plans to implement this feature since this ticket is kind of old?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
