### ISSUE TITLE
Give an option to keep nemo TAB visible all time

### ISSUE THREAD

**Issue by zbandhan** [linuxmint/nemo#1863]
I need to copy and paste many files almost all time so I use "TAB" very much. But to open "TAB" in Nemo with right click and then left click sometimes makes me deep breathing. If Nemo has an option to keep "TAB" visible, that will be very easy to open new TAB with only click.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
