### ISSUE TITLE
File-finding improvements (feature request)

### ISSUE THREAD

**Issue by mscheper** [linuxmint/nemo#1865]
```
 * Nemo version 3.2.2
 * Distribution: Mint 18.2 64b
 ```
I'd like it if I could filter the icons Nemo shows by [GLOB](https://en.wikipedia.org/wiki/Glob_(programming)#Unix) pattern. The simplest implementation would be allowing GLOB wildcards in the existing 'Search Documents and Folders By Name' feature. Bonus points if it could be applied to a directory ('folder') and its descendants.

Super bonus points to be able to filter by additional criteria as well, e.g. timestamp range or file size. I was hoping to find an extension for this, but I haven't had any luck. (Pointers welcome—I might not be using very good websearching terms.)

Super-dooper bonus points, with a giant plush toy, for command-line geeks like me to be able to pipe `find` or other null-delimited pathnames to nemo, and have it open a window that shows thumbnails and allows normal Nemo actions (move, open, etc.) e.g. `find ~/Pictures -mtime +2 -a -mtime -8 -name 'PANO*.JPG' -0 | nemo`. The super-cool thing about that would be that anybody could write a script that outputs null-delimited (or even tab-delimited) paths, and have Nemo present them for users to see. (If this is actually possible with Nemo's extension/plug-in architecture, I'd really appreciate some tips for how to do it.)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
