### ISSUE TITLE
 [Bug] XClip and XSel broken on Nemo since 3.8.0

### ISSUE THREAD

**Issue by H8to** [linuxmint/nemo#1866]
```
 * Nemo version 3.8.0+
 * Windowed nemo
 * Arch
 * 64 bit
 ```

**Issue**
XClip does not work any more on file renaming selections since Nemo version 3.8.0. 

I downgraded to nemo 3.6.5 and it works again after a reboot. Upgrading to 3.8.0 confirmed the error.

**Steps to reproduce**
I use this to do batch renaming with variables

xclip -o
or 
xsel -p

Save a script anywhere:
``` 
#!/bin/bash
what=$(xclip -o)
sleep 0.1
echo $what >> /tmp/clip.txt
```
Bind this script to a hotkey (F1 on Cinnamon in my case).

Open Nemo and press F2 on a file.
The selection will be appended to /tmp/clip.txt

Since 3.8.0 only an empty variable will be shown. Downgrading to 3.6.5 and rebooting the interface, to be sure that 3.6.5 Nemo is used, helps and the functionality works again.

**Expected behaviour**

xclip should return the selection as in older versions of Nemo.

**Other information**
Feel free to ask!

Best,

H8

**Comment by mtwebster** [comment]
Thanks

Possible (Temporary) workaround: this only affects the list view

**Comment by xenopeek** [comment]
This seems to work fine on Nemo 4.6.4. When I select some file in Nemo then type `xclip -o` in a terminal it outputs the name of the selected file.
