### ISSUE TITLE
Segfault using XDG_DATA_HOME

### ISSUE THREAD

**Issue by unai-ndz** [linuxmint/nemo#1867]
```
nemo 3.8.1 also with nemo 3.8.2 from nemo-git on the AUR
Windowed
Manjaro
Gtx 960 with privative 396.24
64 bits
 ```

**Issue**
It fails to run, giving just this message
segmentation fault (core dumped)  

**Steps to reproduce**
Assign any path to XDG_DATA_HOME
For example:
`export XDG_DATA_HOME=.local/share`
And run nemo

**Expected behaviour**
Nemo runs using the specified path without segfaulting

**Other information**
When running with XDG_DATA_HOME set it manages to create $XDG_DATA_HOME/nemo/scripts
Without XDG_DATA_HOME set it creates $HOME/.local/share/nemo/scripts and nemo/actions

Should I post a gdb backtrace? If so how do I enable debugging symbols?

**Comment by mtwebster** [comment]
A backtrace would be helpful - I tried this without a problem, it creates gvfs-metadata folder, nemo/action and nemo/scripts.  I'm not sure what could be your particular issue.

Is there anything peculiar about the folder you're trying to assign? (Different fs, permissions, etc..)

As far as I know with Arch, you need to build everything with symbols enabled, I don't think there's an easy way to do it.  You'd want at minimum the symbols for nemo, gtk and glib/gio/gobject.

**Comment by unai-ndz** [comment]
Have you tried with `.local/share` or with `$HOME/.local/share`?

Looks like $HOME is needed and fixed my issue (As expected really)
I was just getting confused because it was creating the folders on $HOME/$XDG_DATA_HOME so I though it wasn't necesary.

PD: Messing around I got it to work with `.local/share` a few times, inconsistently though.

**Comment by mtwebster** [comment]
`XDG_DATA_HOME=~/.local/share nemo` works fine as does using the full path or $HOME instead of the tilde.  Which is exactly what is used anyhow if you leave that env variable unset.  Just curious why you are trying to override it?

**Comment by unai-ndz** [comment]
Is a line in my config from an old attempt to clean the home folder from individual .appconfig folders and that sort of things. Pretty useless for various reasons, now I know. But seeing nemo segfaulting for this line raised my curiosity. 

Dumb mistake, I should have think about using the full path before. Anyways, thanks for your time. I'm gonna close this.
