### ISSUE TITLE
Nemo freezes just after loading filelist of large directory (469776 files)

### ISSUE THREAD

**Issue by de47110815** [linuxmint/nemo#1870]
```
 * Nemo version (Nemo 3.6.5)
 * Is issue with desktop or windowed nemo? windowed I guess
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3 sylvia
 * Graphics hardware *and* driver used Desktop AMD R580 PCIE ASUS 

lspci -vnn | grep VGA -A 12
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:67df] (rev e7) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device [1043:0519]
	Flags: bus master, fast devsel, latency 0, IRQ 139
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	Memory at d0000000 (64-bit, prefetchable) [size=2M]
	I/O ports at e000 [size=256]
	Memory at dfe00000 (32-bit, non-prefetchable) [size=256K]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

xserver-xorg-video-ati (1:7.7.0-1) unstable; urgency=medium
ubuntu-drivers-common 1:0.4.17.3linuxmint1

 * 32 or 64 bit  - 64
 ```

**Issue**

Nemo stops responding after going into a subfolder with 469776 files. Subfolder was mounted on 2,5" SSD serial ATA hard drive, (Samsung 850 Pro, almost new, SMART OK). Filesystem NTFS, directory structure flat, all files in one place without subfolders. Acctually it is the current Etherreum Geth Chaindata folder, total size arount 1 TB, drive capacity also 1 TB, Nemo shows free space with 9,7MB. All files have name format example 000846.ldb" and are around 2 - 3 MB size. But all other folders browsing works fine under Nemo on this disk. Nemo shows progress bar "Loading" at the bottom, after loading is ready Nemo shows correctly 469776 objects and  free space with 9,7MB but window is frozen. On my 8 core CPU i4770k 1 core keeps running at 100% but after 2 hours of running time I dont believe he will come back. By the way, under Windows 10 or also under Linux Mint (same installation, not in Virtual Machine) in Programm Krusader directory listing is loaded and sorted/displayed within less than 40-60 seconds.

**Steps to reproduce**
Login to Cinamon Desktop GUI, click on "Dateien" icon predefined in the task bar, mount SSD drive by clicking on it, go to subfolder /ethereumlive/blkchaindir-c-usrs-r-appdata-roaming/Ethereum/geth/chaindata and Nemo hangs. empty window, no files listed, 1 CPU core at 100%. can be repeated within the same session after killing non responding Nemo process.

**Expected behaviour**
show directory listing

**Other information**
3,6GB of 16 GB memory used, CPU other 7 cores are idle. System is stable, no broken software packets or dependencys.
Might be related with issue "Non-empty folder appears empty #1796"?

**Comment by de47110815** [comment]
no not linked with #1902

**Comment by howdev** [comment]
may to do with NTFS. NTFS isn't as reliable as ext4 on Linux.

**Comment by de47110815** [comment]
but it works fine with other distro and GUI, like Ubuntu/Gnome.

**Comment by howdev** [comment]
@de47110815 Ubuntu and Gnome does not use Nemo

**Comment by de47110815** [comment]
my answer was just to mention that in my opinion this error has nothing to do with NTFS implementation under Linux in general. It seems to really be more related with Nemo. Again under the same Mint installation extra software like Krusader data manager shows directory listing correctly after 40-50 seconds. every time.

**Comment by howdev** [comment]
then you have tried nautilus or Thunar?

**Comment by de47110815** [comment]
I will try later this week and will post it here

**Comment by xenopeek** [comment]
Considering its age and no follow-up to above, closing this issue. Thumbnail generation for very large directories could be an issue with Nemo in the past. If you think this issue still affects you please retest with Linux Mint 20 Cinnamon.
