### ISSUE TITLE
Gdebi  - refusing to render service to dead parents

### ISSUE THREAD

**Issue by Chocobo-ts** [linuxmint/nemo#1872]
```
 * Nemo version:  3.8.2
 * Is issue with desktop or windowed nemo? Everywhere
 * Distribution - Mint 19 Beta
 * Graphics hardware *and* driver used: AMD R9 270X / radeon
 * 64 bit
 ```

**Issue**
Gdebi that opened by doubleclick file.deb in nemo unexpectedly closing with "refusing to render service to dead parents" when click "Install Package" instead pkexec call

**Steps to reproduce**
Open .deb file in nemo, click "Install" or "Reinstall"

**Expected behaviour**
Must be appear window  pkexec with password promt

**Other information**
gdebi itself working fine if i run `gdebi-gtk packet.deb` or `xdg-open packet.deb`
Also it work fine in caja 1.20.1

**Comment by smurphos** [comment]
This is fixed in stable Cinnamon 19.
