### ISSUE TITLE
Feature Request: "open tab in front"

### ISSUE THREAD

**Issue by happyniko** [linuxmint/nemo#1873]
**New tabs always open in the background. But when I open a new tab I mostly want to view it immediately. So it would be great if I could open new tabs in the front or if this option could be chosen by the user.**

```
 * Nemo version (3.6.5)
 * Distribution - (Mint 18.3)
  * 64 bit
 ```

**Comment by konoknir** [comment]
Need that too! It's really annoying to focus manually opened tabs all the time

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
