### ISSUE TITLE
Files and folders (by name arrangement)

### ISSUE THREAD

**Issue by gabrielfern** [linuxmint/nemo#1882]
Hey, why are nemo folders ordered before hidden folders (when by name), and in file picker (or selector, the context window to select a file, directory) hidden folders comes before, the usual would be folders with dot come before any other folder with a beginning letter.
Not just folders, files too.

Just a thought.

**Comment by xenopeek** [comment]
Considering age of this observation, closing it. Nemo sorts filenames starting with a `.` or `#` last (if sorting directories first is enabled, sorted last within the list of directories). Nemo started out as a fork of Nautilus, as did Caja. All three sort in this way. Other filemanagers may have other sorting preference.
