### ISSUE TITLE
Sidebar places - place disapear at click

### ISSUE THREAD

**Issue by rypz79** [linuxmint/nemo#1884]
* Nemo version 3.6.5
 * Issue with windowed nemo
 * Distribution - Ubuntu 18.04 x64
 * Graphics: lspci -nnk | grep -iA2 vga 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09)
Subsystem: Hewlett-Packard Company HD Graphics 5500 [103c:802d]
Kernel driver in use: i915

**Issue**
As mentioned in the title

**Steps to reproduce**
Click on any of the places links in the places sidebar (see pictures)

**Expected behaviour**
Not to disappear 

**Other information**
[https://imgur.com/a/suFT35x](url)

**Comment by JosephMcc** [comment]
Thanks for reporting but that's a theme issue, not an issue with Nemo.
