### ISSUE TITLE
cannot remove count items

### ISSUE THREAD

**Issue by howdev** [linuxmint/nemo#1889]
```
 * Nemo version 3.8
 * Is issue nemo filemanager
 * Distribution - 19
 * Graphics hardware not related
 * 64 bit
 ```

**Issue**
there is dotted line under every folder when count item is disabled

**Steps to reproduce**
nemo settings->preview-> count items never

**Expected behaviour**
no dotted line under folders
why display the lines where the count be when count is disabled?

**Other information**

**Comment by xenopeek** [comment]
With Nemo 4.6.4 on Linux Mint 20 Cinnamon I can't see a dotted line when setting count to never and enabling tooltips. This looks to have been fixed.

A screenshot with 2x zoom:

![image](https://user-images.githubusercontent.com/21159972/85927993-09684180-b8aa-11ea-9059-26743ed4e07b.png)
