### ISSUE TITLE
UI/UX suggestion: un-sharing a folder

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1890]
```
 * Nemo version (nemo --version): 3.8.4
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * 32 or 64 bit: 64
 ```

**Issue**

To disable a share that one created in Nemo, one has to use a slider and then click 'modify share'. Simply clicking 'close' - instead of 'modify share' - does not suffice and generates no warning. _Adding a warning_ - about changes being lost - would be a good idea, given (1) I did not realise I had to click 'modify-share', (2) the sharing seems to persist even after one disables Nemo's sharing plugin, (3) the general complexity of Samba.

By the way, how does Nemo setup the shares? It does not alter the smb.conf file.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
File the request against nemo-extensions (nemo-share).
