### ISSUE TITLE
pkexec mintsources fails from a Desktop Launcher.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo#1891]
```
 * Nemo version 3.8.4
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Mint 19
 * Graphics:
  Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.0-rc5 
  direct render: Yes
 * 64 bit
 ```

**Issue**

Software Sources fails to open from a desktop launcher with default command `pkexec mintsources`. `.xsession-errors` includes the error 'Refusing to render service to dead parents.'

Panel and Menu launchers work fine

Can be fixed by changing the launch command for the Desktop launcher to `sh -c "pkexec mintsources"`

**Steps to reproduce**

Create a desktop-launcher for Software Sources from the menu right-click and attempt to launch.
Edit to the launcher as described and retry.

**Expected behaviour**

Desktop-launcher to work without further user intervention.

**Other information**

Issue affects other applications with a launch command of pkexec package-name - e.g lightdm-settings,

**Comment by morvael** [comment]
This happens to me as well on a machine that was upgraded from 18.3. Doesn't happen when 19 was installed from scratch.

**Comment by CottonEaster** [comment]
I think this has been fixed. It works on my system now and, I think, did not before.

**Comment by morvael** [comment]
To me it repeated on another machine that was upgraded not so long ago.

**Comment by CottonEaster** [comment]
The fact that [Ulauncher cannot run MintSources](https://github.com/Ulauncher/Ulauncher/issues/254) may relate to this problem.
