### ISSUE TITLE
Keyboard event fired twice?

### ISSUE THREAD

**Issue by changke** [linuxmint/nemo#1896]
```
 * Nemo 3.8.4
 * windowed nemo
 * Distribution - (Mint 19)
 * Intel 620 / i915
 * 64 bit
 ```

**Issue**
Newly fresh installed Mint 19 Cinnamon. Use keyboard shortcuts to to some operations in nemo, e.g. use backspace key to go up to parent directory, use shift + delete to remove file etc. In most cases, such event will be fired twice, so instead of go up one level of directory nemo navigates two level above, or shows delete confirmation dialogues twice.

**Steps to reproduce**
Start nemo, navigate to any directory, press backspace key

**Expected behaviour**
Nemo navigates to the parent directory, but only 1 level above.

**Other information**
Another machine which was upgraded from Mint 18.3, doesn't have such issue.

Thanks!

**Comment by xenopeek** [comment]
I can't reproduce this on Linux Mint 20 Cinnamon. If any are still affected by this issue please retest on Linux Mint 20 Cinnamon as more context and detail would be needed for how to reproduce it.
