### ISSUE TITLE
Menu key not working on new version (3.8.4) of nemo.

### ISSUE THREAD

**Issue by sevenskull** [linuxmint/nemo#1897]
```
 * Nemo version: 3.8.4
 * Is issue with desktop or windowed nemo? Both
 * Distribution - Mint 19 Tara
 * Graphics hardware *and* driver used: opensource and proprietary
 * 64 bit
 ```

**Issue**
The menu key (button on keyboard) is not working on nemo or desktop anymore, on linux mint <= 17.3 it worked well. The key still work in any other application including start menu.

**Steps to reproduce**
Just go to a folder or file and press the "menu key" on keyboard, that button on the right side, close to the right alt or ctrl or right super.

**Expected behaviour**
Open the context menu (right click mouse)

**Other information**
If this is a bug, can i do something temporary like add a shortcut manually for this. I've read something about using "~/.gnome2/accels/nemo" but i didn't find any doc about the options i can put or the shortcut, can some one help-me with this?
There's something about on this link:
https://github.com/linuxmint/nemo/issues/1771

**Comment by mtwebster** [comment]
Is there a particular context where this doesn't work?  Quickly plugging in a keyboard and testing seemed to work fine.  Does it work in some views and not others - icon but not list view?  Can you provide exact steps that reproduces it for you?

Is that a typo or are you really on Mint 18 with cinnamon 3.8?

**Comment by mtwebster** [comment]
Additionally, can you try disabling any extensions you have running (uncheck all in edit->plugins->extensions then restart)

Also, does right-clicking work anywhere that the key *isn't* working?

**Comment by sevenskull** [comment]
@mtwebster I already tried disabling all plugins, no effect.
I've updated the info, sorry, i am using Mint 19 Tara with cinnamon 3.8.7 and Nemo 3.8.4.
I've noticed this problem in 4 different computers now. My home desktop, my work notebook, and 2 friends who updated to 19.
There's one that i saw working, but it was a fresh install without distr-upgrade, i am wating to finish the upgrade to see if stop working too.
About the extensions, i've already tried disabling them all, no success.

**Comment by aldeano** [comment]
I also have this problem with nemo 3.8.4. The menu key doesn't work, but with right-clicking I can get the menu. Using archlinux up to date.

**Comment by mtwebster** [comment]
Any warnings if you kill Nemo then start from a terminal and try to reproduce?

**Comment by aldeano** [comment]
No, there's no warning, but I find if the folder is viewed in "list view" it works, but in "icon view" and "compact view" it doesn't.

There's a way to get a more verbose option on terminal?

**Comment by mtwebster** [comment]
No but that helps. I think I know the cause now. Thanks.

**Comment by sevenskull** [comment]
When i kill nemo like suggested and start from terminal.
Everytime i press the menu key it shows this message on terminal:

**(nemo:5530): Gtk-CRITICAL **: 16:16:04.681: gtk_menu_popup_at_rect: assertion 'GDK_IS_WINDOW (rect_window)' failed**

**Comment by sevenskull** [comment]
I also did the test in different views.
Icon: fail
Compact: fail
List: success

**Comment by rypz79** [comment]
Same problem with 
`Ubuntu 18.04.1 x64 with GNOME 3.28.2 and Nemo 3.8.4`
The Menu key doesn't work. Only right-click opens the file/folder menu (Alt-Enter works)
The Tab key also doesn't work I cannot change the focus (e.g jump from the side-bar to the menu-bar etc..) 
Any solution(s) to that ?? 
Where are Nemo's keyboard shortcuts located in d.conf ?

TNX

**Comment by sevenskull** [comment]
@rypz79 This was fixed in Nemo 3.8.5 by mtwebster, just upgrade and that will be ok.

**Comment by rypz79** [comment]
@sevenskull I cloned the repo but I couldn't find  _build_,  _configure_ or _make_ files there as explained [here](https://github.com/linuxmint/nemo/blob/master/INSTALL).
The only executables  on the main dir are _makepot_  and _generate_additional_file_
Also there is no PPA with v3.8.5 for Ubuntu 18.04 Bionic Beaver.
How do I update/install Nemo's latest version?

TNX

**Comment by rypz79** [comment]
```
sudo add-apt-repository ppa:gwendal-lebihan-dev/cinnamon-nightly
sudo apt update
```

TNX
