### ISSUE TITLE
dh_install: Cannot find (any matches for) "usr/share/gtk-doc" (tried in ., debian/tmp)

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo#1898]
```
 * Nemo version: 3.8.4
 * Distribution - Debian sid (chroot)
 * Nvidia Geforce GTX & (lib)nvidia-*-390
 * 64 bit
 ```

**Issue**
Cf. title

**Steps to reproduce**
- git checkout 3.8.4
- debuild -i -I --no-sign --build=binary -j1

**Expected behaviour**
Correct build

**Current behaviour**
```
...
make[1]: Entering directory '/home/actionmystique/src/Nemo/nemo-build/git-nemo'
dh_install --list-missing
dh_install: Please use dh_missing --list-missing/--fail-missing instead
dh_install: This feature will be removed in compat 12.
dh_install: Cannot find (any matches for) "usr/share/gtk-doc" (tried in ., debian/tmp)

dh_install: libnemo-extension-dev missing files: usr/share/gtk-doc
dh_install: missing files, aborting
make[1]: *** [debian/rules:47: override_dh_install] Error 25
make[1]: Leaving directory '/home/actionmystique/src/Nemo/nemo-build/git-nemo'
make: *** [debian/rules:18: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -i -I --build=binary --build=binary -j1 -mJean-Christophe Manciot <manciot.jeanchristophe@gmail.com> failed
```

[Full build log](https://github.com/linuxmint/nemo/files/2183585/nemo_3.8.4_amd64.build.txt)
.

**Comment by clefebvre** [comment]
You're probably missing a build dependency or gtk-doc-tools.

**Comment by ItzSwirlz** [comment]
I know this is for a way older version of cinnamon-but I did some digging as I experienced a similar issue building something else

I don't think it physically matters if it's there, but here's what I did

dh_auto_install
dh_install

Now clean what you did-debuild -- clean

now just dh_install

You can see EVEN MORE Libraries are needed. I think the thing is, the files weren't generated by the build process.
