### ISSUE TITLE
Thumbnails not showing for sound/video files

### ISSUE THREAD

**Issue by donlencho** [linuxmint/nemo#1900]
```
 * Nemo version 3.8.4
 * Mint 19
 ```

**Issue**
Thumbnails are generated for image files and pdf, but not for sound or video files (not for any extensions I have tested).

**Steps to reproduce**
Have Nemo display a folder with a video file or a sound file with integrated cover art, it will just show the basic icon.

**Expected behaviour**
Should show a frame from the video or the cover art (at least that's what it was doing before upgrading to Mint 19, and I guess it's the expected behaviour).

**Comment by leigh123linux** [comment]
You need to install a thumbnail program for video file thumbnails, I believe xplayer provides the base for this in Mint.
Xplayer requires the correct gstreamer1 codecs to be installed for this to function.
If  that's all correct try deleting the thumbnail folder/cache  to regenerate.

**Comment by donlencho** [comment]
thanks, indeed xplayer was missing and it's now working after installing it.
