### ISSUE TITLE
White border in Nemo's left panel (Tree view)

### ISSUE THREAD

**Issue by artik** [linuxmint/nemo#1901]
```
nemo 3.8.4
Mint 19
Nvidia HW with nvidia 390 drivers
64 bit
 ```

**Issue**
When switching to "Tree view" a white border appears in the left panel.
"Places" view: https://i.imgur.com/iXjQ1mF.png
"Tree" view: https://i.imgur.com/atoSQmF.png

**Steps to reproduce**
Just display Tree view in the left panel.

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment]
That's a theming issue

**Comment by artik** [comment]
@NikoKrause Strange, I tried all themes, they're all affected

**Comment by NikoKrause** [comment]
> I tried all themes

Which themes exactly do you mean with "all themes"?

**Comment by artik** [comment]
I played with this section https://i.imgur.com/IyBshE8.png

**Comment by artik** [comment]
Where is located the theme's folder ? I read somewhere in ~/.themes but mine is empty

**Comment by artik** [comment]
I found a workaround:

I edited /usr/share/themes/Mint-Y/gtk-3.0.gtk.css

line 3047 i added a margin -1px to the class .nemo-window .sidebar

`  .nemo-window .sidebar {
    color: #C3C3C3;
    background-color: #454545;
    margin: -1px; }`

But I don't think if it's a correct way to fix it.

**Comment by JosephMcc** [comment]
This is definitely a theme issue. I'll look at fixing it.

**Comment by JosephMcc** [comment]
Ok, now fixed in git master of mint-themes: https://github.com/linuxmint/mint-themes/compare/adf0df8296e2...2d7af0fdec35
