### ISSUE TITLE
Nemo crashes when dragging files/folders when window is below a certain size

### ISSUE THREAD

**Issue by trovadr** [linuxmint/nemo#1903]
```
 * Nemo version (nemo --version)
nemo 3.8.4
 * Is issue with desktop or windowed nemo?
Windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19 / Cinnamon desktop
 * Graphics hardware *and* driver used
HD Graphics 630 / Driver: i915
 * 32 or 64 bit
64 bit
 ```

**Issue**
Nemo crashes when dragging files or folders when window is below a certain size.

**Steps to reproduce**
1. `$ nemo ~`
2. Adjust icon zoom level to the maximum setting (not necessary, but it makes the bug easier to reproduce)
3. Reduce the nemo's window width. Stop right before the right border of the file/folders is covered by the window border
4. Select any file or directory and drag in any direction.

**Expected behaviour**
Nemo crashes with the following error:
file ../../libnemo-private/nemo-icon-info.c: line 696 (nemo_get_desktop_icon_size_for_zoom_level): should not be reached
Segmentation fault (core dumped)

**Other information**

The size threshold below which nemo will crash depends on the size of the icons. The window has to be narrower if icons are small in order to reproduce the issue.

**Comment by mtwebster** [comment]
This would have been fixed by https://github.com/linuxmint/nemo/commit/4f157ae8474be4968801101f261ed9cc62bd6b78
