### ISSUE TITLE
[Feature request] Copy dialogue

### ISSUE THREAD

**Issue by ypsy** [linuxmint/nemo#1904]
Hi,
I hope its fine to post feature requests here, couldn't find an appropriate spot.
When copying multiple files with nemo, the name of the file currently being copied is not shown but instead how many have been copied/still need to be copied (e. g. "File 3 of 25 …"). Is there a reason not to display the full name or path? Thought it could come handy sometimes.

Thanks in advance and kind regards

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
