### ISSUE TITLE
(Feature request) Improved copying (deferred dialog - bg copying & md5 check of files in bg while showing dialog)

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#1905]
There is a feature that I have been missing over many years on many operating systems,

I would like to have an option in the settings for using this feature, if I knew about such a feature in any file browser, I would probably deliberately use it for this alone.

When copying files, if there are multiple copies of files, the dialog "do you want to merge, replace skip etc" pops up and the copying stops.

This situation is present afaik on all operating systems and I dont know of any operating system that has improved on this (I may be not very knowledgeable in this matter)

Instead of stopping the entire process (imagine starting copying, then coming back a few hours later expecting a very long job to be finished only to discover it having stopped after the first minute) there are many alternatives that can easily be coded.

1. Continuing the copying in the background for all files that are not duplicates, while building a list next to the dialog showing affected files.

or 2. I know some will have objections I would not (as I said, make it optional) When a dialog is about to pop up, DO show the dialog but at the same time: simply find out if the 2 files are identical or not:

if file A has the same checksum (md5_file *md5sum) as file B, there is no point of asking if you want to replace it, they are already the same file, and if as for most people the timestamps or other attributes are not important you can directly SKIP copying the file. Only IF there are differences inside the files, are there any reason to ask for directions from the user.

Some will say md5 will be slow for large files, sure, but it is not slow for small files. 2 md5 checks for a small file will be completed faster than the response time of the user to even click skip or merge or overwrite on the dialog.

And for large files, even processing for 1 minute to find out if they are identical may be considered better than holding up the line waiting for the user to click on something when the user comes back hours later only to find out it never started in the first place.

I think the copying process definitely needs more autonomy, it can be done with some or a combination of above suggestions.

I dont know but I was thinking maybe there are checksums that could be used for this already in the file system, crc or similar, I dont know if they are suitable for this purpose.

Thanks for reading!

I hope someone can implement this.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
