### ISSUE TITLE
Picture thumbnails in icon view at maximum zoom are still small

### ISSUE THREAD

**Issue by rypz79** [linuxmint/nemo#1910]
```
 * Nemo version: 3.6.5
 * Issue with: Windowed Nemo
 * Distribution: Ubuntu 18.04 x64
 * Desktop Environment: GNOME 3.28.2
 * Graphics: lspci -nnk | grep -iA2 vga 
   00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09)
   Subsystem: Hewlett-Packard Company HD Graphics 5500 [103c:802d]
   Kernel driver in use: i915
 ```

**Issue**
See picture

**Steps to reproduce**
See picture

**Expected behaviour**
Larger thumbnails on all the pane maximum zoom showing 1 picture per pane
For each down zoom level they split in 2 (T for Thumbnail)

T   
----
TT  
TT   
-----
TTTT  
TTTT
------
TTTTTTTT 
TTTTTTTT 
or 
TTTT
TTTT
TTTT
TTTT
-----
(depends on the pane HxL)

**Other information**
![screenshot from 2018-07-26 14-19-58](https://user-images.githubusercontent.com/28814757/43260107-2ceb7674-90e1-11e8-91a8-dfe96360fbd1.png)

**Comment by mtwebster** [comment]
This is a known issue, being actively worked on currently

**Comment by mtwebster** [comment]
This is much improved in Nemo 4.0 (maximum size has increased, and the spacing between items is much more reasonable).
