### ISSUE TITLE
Nemo loses sort criteria and direction on reload of search result

### ISSUE THREAD

**Issue by rouvenvolkmann** [linuxmint/nemo#1912]
```
 * nemo 3.6.5
 * Ubuntu 18.04 and Ubuntu 16.04 (from http://ppa.launchpad.net/webupd8team/nemo3/ubuntu)
 * 64 bit
 ```

When reloading any search result within nemo (e.g. using F5 or the reload button), the sorting is set back to default (by Name, ascending). The same happens after a change of the search.

I expect the sort criteria and direction to be kept after a reload or a change. This would also be consistent with the behavior for normal browsing.

**Comment by icarter09** [comment]
Nemo 4.8.2
Mint 20 64bit

I'm not able to reproduce this issue. Nemo is holding the sort settings/results after F5 is pressed.
