### ISSUE TITLE
No space between icons and labels in gridview

### ISSUE THREAD

**Issue by madsrh** [linuxmint/nemo#1914]
**Issue**
There is no space between the icons and the file/folder name label. 

**Expected behaviour**
There should be a few pixels padding added to match the look of list view.

**Steps to reproduce**

1. Launch Nemo
2. Toggle between list and grid view

### List view ✔️ 

![image](https://user-images.githubusercontent.com/3986894/43361035-300d09cc-92c5-11e8-9784-25a0a15b5715.png)

### Grid view 👎 

![image](https://user-images.githubusercontent.com/3986894/43361038-4198f002-92c5-11e8-901b-2b7e1d883e0e.png)

### Mockup of grid view 👍 

![image](https://user-images.githubusercontent.com/3986894/43361047-8a804482-92c5-11e8-8c4d-e0bf3e89de7b.png)

```
Nemo version 3.6.5 on Ubuntu 18.04 64-bit
 ```

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce the issue in nemo-3.8.x as 3.6.x is EOL.

**Comment by clefebvre** [comment]
I can reproduce it here with master/mint19.

**Comment by leigh123linux** [comment]
@clefebvre weird it didn't reproduce here when I checked  with 3.8.4

![screenshot from 2018-07-29 23-41-51](https://user-images.githubusercontent.com/1299302/43371407-441066ca-9389-11e8-9eea-392ce1f2f1ee.png)

**Comment by madsrh** [comment]
@leigh123linux I think it does. If you select the **dialog-password.svg** file, you'll see. 

![image](https://user-images.githubusercontent.com/3986894/43371538-3f3eeb84-9394-11e8-9258-af70e5885ff2.png)
