### ISSUE TITLE
Mounted BTRFS subvolume/snapshot names

### ISSUE THREAD

**Issue by bastimeyer** [linuxmint/nemo#1915]
```
 * Nemo version: 3.8.5
 * Is issue with desktop or windowed nemo? Windowed nemo
 * Distribution: Arch
 * Graphics hardware *and* driver used: irrelevant
 * 32 or 64 bit: 64 bit
 ```

### Issue

- Nemo uses the same BTRFS partition label for all of its mounted subvolumes or snapshots.
- Also, if multiple subvolumes of the same BTRFS partition get mounted, only one of them is showing its used/overall space bar below it.

I know this issue has to do with the subvolumes which are no real block devices, but it is confusing and annoying in those cases, where you are using BTRFS subvolumes as a replacement for logical block devices. 

Here's an example of Nemo's device list showing a single BTRFS partition with the label "media" and five of its mounted subvolumes (ignore the other three regular block devices):
![screenshot from 2018-07-31 01-17-07](https://user-images.githubusercontent.com/467294/43429082-cf1640fe-9461-11e8-8ecb-f653a00cbfbd.png)

### Expected behavior

Having an option to either

- **hide** items of the devices list (then the user can simply use bookmarks)
- locally **rename** items of the devices list (and store this data, based on device UUID and certain mount parameters (subvol or subvolid))
- use the **subvol path** as name, eg. `/@foo` or `/path/to/subvolume` instead of the BTRFS label, unless it is not a subvolume or snapshot
- use the **basename** of the mounted path

### Steps to reproduce

1. Create a new BTRFS partition and give it a label
    ```sh
    mkfs.btrfs -L label /path/to/device
    ```
2. Mount it and create subvolumes
    ```sh
    mount -t btrfs /mnt
    btrfs subvolume create /mnt/@foo
    btrfs subvolume create /mnt/@bar
    btrfs subvolume create /mnt/@baz
    umount /mnt
    ```
3. Create dirs in `/media` and mount individual subvolumes
    ```sh
    mkdir -p /media/{foo,bar,baz}
    mount -t btrfs -o subvol=/@foo /media/foo
    mount -t btrfs -o subvol=/@bar /media/bar
    mount -t btrfs -o subvol=/@baz /media/baz
    ```
4. Open Nemo and see its devices list showing three mounted devices with the label "label", two of them without a bar

### Other information

Related to #1497

**Comment by leigh123linux** [comment]
Disk names are done by udisks2 not nemo
