### ISSUE TITLE
Adding Nemo Action to "Empty Space" Context Menu

### ISSUE THREAD

**Issue by H8to** [linuxmint/nemo#1916]
```
 * Nemo version nemo 3.8.5
 * Nemo window
 * Distribution - Arch
 ```

**Issue**
After creating a Nemo action it is not possible to use it in the space below folders and files.

**Steps to reproduce**
Create a custom action with extensions=any
Click on a folder -> Shows the action
Click on a file -> Shows the action
Click below both on the empty space -> Does not show the action, only "open terminal here", create folder and so on

**Expected behaviour**
Show actions also where no file or folder is below the cursor

**Other information**
My intention is to have something like "Open Atom Texteditor Here" just like the "open terminal here"

Any advice would be  great!

**Comment by mtwebster** [comment]
See:

https://github.com/linuxmint/nemo/blob/master/files/usr/share/nemo/actions/sample.nemo_action#L48

`Selection=none` should do what you want.

**Comment by toolschmiede** [comment]
Overseen that one.. Thanks!!

**Comment by H8to** [comment]
Must have overseen that one. 
Thanks!
