### ISSUE TITLE
Advanced Search - Operators / Wildcards - Feature Request

### ISSUE THREAD

**Issue by kylebriffa7** [linuxmint/nemo#1918]
```
 * Nemo version 3.8.5
 * Distribution - Mint 19
 * 64 bit
 ```
Hi everyone.

I would like to know if there's a way to use advanced wildcard searches inside Nemo's search field, specifically a negative wildcard/operator.

Basically I want to select the inverse of whatever I am searching for. In Window I used to enter the "NOT" operator e.g.

Code: Select all

NOT *.jpg

Other examples:

Code: Select all

    cat* could return cat, cats, catalogue, catamaran etc.
    cat? Could return cats or cate but NOT cat or catamaran

Would also like some further documentation on the subject as I use this feature a lot.

Thank you.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
