### ISSUE TITLE
Option to remove "Make executable and run" prompt

### ISSUE THREAD

**Issue by ericchiang** [linuxmint/nemo#1923]
```
* Nemo version (nemo --version)
nemo --version
nemo 3.6.5
* Is issue with desktop or windowed nemo?
Desktop
* Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Debian
* Graphics hardware *and* driver used
* 32 or 64 bit
 ```

**Issue**

When opening a file with no registered file handlers, one of the options in the resulting prompt is "Make executable and run".

This is a pretty of terrifying option. You can send a user a bash script called "Hello.doc" and if they don't have a word processor installed, they have the potential to execute it. I realize that there's a warning, but it's a pretty low friction vector for getting owned.

![ink](https://user-images.githubusercontent.com/2342749/44291385-dd51f300-a232-11e8-9805-2eb682cc7dca.png)

**Steps to reproduce**

Open a file with an unrecognized extension type. Such as:

```
$ cat ~/Downloads/Hello.doc 
#!/bin/bash -e

zenity --notification --text="hello, world!"
```

**Expected behaviour**

No option for executing the file.

Properly packaged apps will already have desktop entries, and sufficiently advanced users will already know how to execute binaries they want to run through the terminal.

**Other information**

**Comment by ericchiang** [comment]
cc @mtwebster @clefebvre 

Any thoughts here?

**Comment by jaszhix** [comment]
I can't reproduce this on Nemo 3.9.0. If I follow those steps, LibreOffice opens a document showing a shell script. I don't think LO would be able to execute a shell anyway, and LO has no problems ignoring the executable bit on docs. Most users have a file association for that.

While it does make sense to safety proof the prompt, I don't think its a security risk unless someone really is being careless - in that case I wouldn't think its worth it to remove features to help people that would probably find another way to brick their computer anyway.

**Comment by ericchiang** [comment]
> I can't reproduce this on Nemo 3.9.0. If I follow those steps, LibreOffice opens a document showing a shell script. I don't think LO would be able to execute a shell anyway, and LO has no problems ignoring the executable bit on docs. Most users have a file association for that.

Sorry just to be clear, the issue came up when I uninstalled LibreOffice. If I remove LO for users, that's the prompt they get when they open a docx/pptx/xlsx file, which surprised me a lot.

If you remove LO, you'll be able to execute that script.

> While it does make sense to safety proof the prompt, I don't think its a security risk unless someone really is being careless - in that case I wouldn't think its worth it to remove features to help people that would probably find another way to brick their computer anyway.

Yep, there are lots of ways to get owned. My goal with this issues was to get that number to n-1 :)

"Choose a program" almost always seems like the correct choice for well behaved file types. For the other non-malicious use cases, it seems reasonable to have app developers register real .desktop files.

**Comment by NikoKrause** [comment]
![Delete Computer](https://i.kym-cdn.com/photos/images/original/001/020/946/a40.gif)

**Comment by ericchiang** [comment]
@NikoKrause a little confused by what you're trying to convey there.
