### ISSUE TITLE
 [Feature request]  Return of "Copy to ..." and "Send to" in right clic menu

### ISSUE THREAD

**Issue by wedu31** [linuxmint/nemo#1928]
```
 * Nemo version : 3.6.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : ubuntu 18.04
 * 32 or 64 bit : 64 bits
 
Hi all, first of all i would like to thank you for this useful project !
A couple of days ago, i had ubuntu 14.04 installed and worked with Nemo 1.8.4. It had a very useful option that i'm using every day : the possiblity to "Copy to..." or "Send to..." by the right clic menu
As i upgraded to ubuntu 18.04, i installed nemo using ubuntu repository and i have now Nemo 3.6.5 installed. The option is already present in the Edit menu  but as disappeared from right clic menu of the mouse ...

It would be really nice to allow (via Display/options ?) the return of those entrys in the right clic menu

Thank you all for your efforts
W@m

**Comment by mtwebster** [comment]
Right-click an item in nemo and click the little plus symbol in the upper right corner of the menu.  That will bring back move-to/copy-to.

![screenshot from 2018-08-23 07-05-50](https://user-images.githubusercontent.com/262776/44522067-53c37a80-a6a3-11e8-83be-3c99a7a41c55.png)

**Comment by wedu31** [comment]
Thank you very much. I've didn't seen this option. Sorry.

**Comment by CottonEaster** [comment]
I second this request - and a similar proposal, [here](https://community.linuxmint.com/idea/view/4079), has sixteen votes in favour of it. I'd try to create a Nemo extension myself - an extension that does the needful - but I do not know how.

**Comment by CottonEaster** [comment]
OK, I've implemented this on my own computer. Files are here, on Box. The script therein is setup to work as a normal user or as root, but at present root nemo is not showing my content-menu item.

**Comment by leigh123linux** [comment]
@CottonEaster  Read mtwebster's comment and stop spamming us with worthless crap!!
