### ISSUE TITLE
Deleting non-empty folder in SMB-CIFS (SAMBA) fails

### ISSUE THREAD

**Issue by Martin-Laclaustra** [linuxmint/nemo#1930]
```
 * Nemo version (nemo --version): 3.8.5
 * Is issue with desktop or windowed nemo?: Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19
 * Graphics hardware *and* driver used: irrelevant
 * 32 or 64 bit: 64bit
 ```

**Issue**
Deleting a non-empty folder in a SMB share deletes it in the window, but not in the share. It reappears refreshing the page.
Empty folders are deleted correctly.

**Steps to reproduce**
Delete a non-empty folder in a SMB share. Refresh.

**Expected behaviour**
The folder should not reappear on refresh. 

**Other information**
Also reported here:
https://forums.linuxmint.com/viewtopic.php?t=272816

It happens in the live ISO and in an up-to-date installation.

**Comment by scissorsneedfoodtoo** [comment]
@Martin-Laclaustra, thank you for creating this issue! I wrote that forum post but never got around to reporting it. Just commenting to follow along here.

**Comment by clefebvre** [comment]
It's upstream in samba itself: https://bugzilla.samba.org/show_bug.cgi?id=13204

**Comment by Martin-Laclaustra** [comment]
Thanks Clem, for your answer and for making Linux Mint possible.
I think a fast (and sloppy -said with all our love for developers-) release cycle upstream is creating great instability in distributions.
Do you see a way of clamping this problem to stick in mint to a working version until critical problems upstream are solved? or to have them quickly patched until them?
We could see that the release of LM19 has brought a lot of regressions with it (that should have been filtered out and not released by ubuntu, but they did), as we read in the comments of the 7th September 2018 entry of the linux mint blog.
I encountered myself too many problems and could not cope (I usually tackle the few minor problems), I needed to go back to 18.3.
How can we (the community) help?
For example, I believe that the community would agree with long periods for beta versions, and collaborate (I would) reporting bugs at a centralized bug tracker. The mint release should be stable, as it has always been.
The bug tracker should receive problems no matter the origin (mint or upstream), and then classify. I am sure that many will volunteer to scale up problems, once identified by mint, to their creators, with people being responsible of specific topics (I am talking of community volunteers, not adding work to your core team). Problem reporting in the blog seems inefficient and difficult to track. And scattered places make it difficult to know where to report. (Thanks for the guide to report that you wrote, but I think that it has two problems: 1. It requires some expertises that not all users have; 2. It makes the user responsible for reporting things upstream. I think that an opportunity is lost there, because many errors remain under-reported, and because there is a limited, and variable, amount of time that each user can devote to report the problem)
Finally, I thought of a way to make it easy replicating the bugs. May be it sounds outlandish, but, may be a webpage with a web-vnc accessible sand-boxed up-to-date system (renewed with each connection), that would log all actions and problems, could help, asking the user that reports a bug to connect to it and to replicate the problem.
I hope to be able to help somehow.
Thanks again for your efforts.
