### ISSUE TITLE
Odd/even different line background

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/nemo#1931]
```
 * Nemo version: 3.6.5/3.8.8
 *  windowed nemo
 * Distribution: Mint 18.3/Mint 19
 * Graphics hardware *and* driver used: Intel HD4000, driver i915
 * 64 bit
 ```

**Issue**
It is not possible to have alternating odd/even colors for nemo. I don't know if it depends on the theme or on nemo itself.

This is similar to a previous bug I mentioned:
[https://github.com/linuxmint/nemo/issues/1352](https://github.com/linuxmint/nemo/issues/1352)
It seems that this is again possible: 
[https://developer.gnome.org/gtk3/stable/GtkTreeView.html#GtkTreeView--s-allow-rules](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#GtkTreeView--s-allow-rules)
**Steps to reproduce**
**Expected behaviour**
Have alternating odd/even like in previous version (maybe LM 17). 
**Other information**

**Comment by JosephMcc** [comment]
As mentioned in the other one, as far as I know this doesn't work anymore. In any case there is nothing stopping it from working in Nemo if Gtk would support it.

**Comment by J-P-** [comment]
Just a comment…
I do most if not all work starting with the file manager or fsearch. Almost all (99%) of the time I need and use the detailed list view. I am 30 to 50% less functional if the list is not banded (aka: alternating colored background; striping). This is a huge let down.

I have tried to use alternate fm in Linux but they all suffer from one thing or another for my use-case. I am trying to migrate from Windows where I use xplorer², mostly FreeCommander and previously TotalCommander. A good file manager is like underwear — one never appreciates its value until it is gone.
