### ISSUE TITLE
[Request] Add trailing slash '/' to path in addressbar

### ISSUE THREAD

**Issue by red-kite** [linuxmint/nemo#1936]
The idea is to always print the trailing '/' of the active folder in nemo's address bar.

The reason to do so is to have a little less typing effort when using keyboard-navigation. This behaviour should cause no problem because everything shown in the address bar are folders. Whether using tab-completion or typing the full path with trailing slash, the '/' is firstly shown but then stripped by enter key and has to be retyped again for further navigation.

Example: Show ``/usr/local/bin/`` instead of ``/usr/local/bin`` in address bar

(Could be implemented with option in settings.)

Best regards

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
