### ISSUE TITLE
[Feature Request] Execute text files as root on normal user

### ISSUE THREAD

**Issue by DanielRios549** [linuxmint/nemo#1937]
```
 * Nemo version 3.8.5
 * This issue is with windowed nemo
 * Distribution - Mint 19 64 bit
 * NVIDIA Corporation GM107 [GeForce GTX 750]  driver Nvidia 396.54
 ```

The Nemo File Explorer has an option to execute files, but sometimes is necessary open Nemo as root before, because the program needs root access. I think an option to execute as root would be excellent, I'm saying something like a drop-down menu on the side of "Run in Terminal" and "Run" options, called "As root", for exemple, executing either in terminal or only executing as root, calling pkexec before. Unifying "Run in Terminal" and "Run" options using this drop-down menu, would be good as well.

**Steps to reproduce**

Double click in a executable file on Nemo under normal user, with "Executable Text Files" option set to "Ask each time".

**Expected behaviour**

Run a program as root, without opening Nemo as root before.

**Other information**

This is only an option targeting novice users, I know it's very easy to execute a text file on Nemo now, even with root, but normal users will be using Nemo as normal user 99% of the time, if the file doesn't execute well because of a root permission, they can think there is a problem.

**Comment by ManIVIctorious** [comment]
The problem is especially novice users should not run textfiles (it any other files) as root. This sounds like a very bad idea in my ears

**Comment by leigh123linux** [comment]
@DanielRios549  Fancy running this txt file as standard user then decide if your idea is good.

[test.txt](https://github.com/linuxmint/nemo/files/2374508/test.txt)

P.S you will need to reboot after running it.

**Comment by DanielRios549** [comment]
@ManIVIctorious I understand, maybe an option on settings or dconf would be better.
