### ISSUE TITLE
[Feature Request] Styling of background of text of desktop items

### ISSUE THREAD

**Issue by coderforlife** [linuxmint/nemo#1940]
```
 * Nemo version: v3.8.5
 * Desktop Nemo
 * Distribution: Fedora 28
 ```

**Issue**
The text of desktop items can be minimally styled by editing `~/.config/gtk-3.0/gtk.css` and adding things for `.nemo-desktop.nemo-canvas-item`. Things like `color` and `text-shadow` work. However things like `background-color` cannot be modified (if modified they do end up affecting the hover/selected state though).

This seems to be due to https://github.com/linuxmint/nemo/blob/28773d105d26c7648e23ad087c5f941a26f284e3/libnemo-private/nemo-icon-canvas-item.c#L1068 which is an `if` statement that only activates when the item is highlighted, being renamed, or "prelight" (whatever that is). If the `if` statement is activated than the frame and background of the text is drawn.

It would be nice if the border and background could always be modified even when not selected.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
