### ISSUE TITLE
[Feature Request] Add `Integrated Terminal (F4)` to the view menu

### ISSUE THREAD

**Issue by a-bentofreire** [linuxmint/nemo#1941]
```
 * nemo 3.8.6
 * Desktop: Cinnamon 3.8.9 (Gtk 3.22.30) Distro: Linux Mint 19 Tara
 * Card: Intel HD Graphics 520
 * Display Server: x11 (X.Org 1.19.6 )
 * 64 bit
 ```

**Issue**
Currently there is no visible information to the user that if he presses F4, it will toggle the Integrated Terminal.  
Adding this information to the View menu, it will allow any user to know the existence of this feature.  
It could be placed right after Extra Panel:

> [View]
> ....
> [x] Extra Pane (F3)
> [x] Integrated Terminal (F4)

**Comment by JosephMcc** [comment]
Nemo-terminal isn't a part of Nemo. It's an extra extension. If you have a feature request for that it should be filed here: https://github.com/linuxmint/nemo-extensions/issues

**Comment by a-bentofreire** [comment]
Can nemo at the moment already allow for an extension to add itself to menu including having a checkbox to toggle it?
