### ISSUE TITLE
Nemo hangs while browsing a large video directory 

### ISSUE THREAD

**Issue by rypz79** [linuxmint/nemo#1945]
```
 * Nemo version 3.9.0
 * Windowed Nemo (GNOME 3.28.2)
 * Distribution - Ubuntu 18.04.1 
 * 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
	Subsystem: Hewlett-Packard Company HD Graphics 5500
	Kernel driver in use: i915
	Kernel modules: i915
 * 64 bit
 ```

**Issue**
I have a 159.6GB videos folder with 458 items on my Transcend StoreJet 25M3 TS1TSJ25M3 1TB external HDD, exFAT formatted and connected with USB 3.0 to my HP Spectre 13-4003dx x360 Convertible laptop PC.

I've set File preview as follows:
![screenshot from 2018-09-19 07-40-56](https://user-images.githubusercontent.com/28814757/45731290-7b90fa00-bbdf-11e8-8c82-3f628608f433.png)

**Steps to reproduce**
After Nemo automounts the drive , I enter the folder and start browsing it, Nemo hangs and after 15-20 seconds the OS says that it's not responsive and needs to be forced quit. 

**Expected behaviour**
Browsing the directory seeing all the vids previews and playing a selected one.
Works flawlessly with the default file explorer (Explorer) on Windows 10 x64.

**Other information**
I can add a directory listing with metd-data on it's contents if needed.

**Comment by leigh123linux** [comment]
Can you reproduce the issue using a proper filesystem?, exfat in linux is virtual filesystem provided by fuse.

https://en.wikipedia.org/wiki/Filesystem_in_Userspace

**Comment by rypz79** [comment]
Same simtomps with NTFS.
I don't expect it to work fast I just expect it not to have FCs (force close).

**Comment by leigh123linux** [comment]
If the files are smaller than 4Gb, normal FAT32 would be a good choice.
