### ISSUE TITLE
Renaming a folder is not allowed in a location with many folders

### ISSUE THREAD

**Issue by rpxomi** [linuxmint/nemo#1948]
```
 * nemo 3.8.6
 * windowed
* Arch Linux 
* Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller 
* Intel Open Source i915 (Mesa 18.2.0, OpenGL Core 4.2, OpenGL Compatibility 3.0)
* x86_64
 ```
 ```
Kernel: 4.18.8-arch1-1-ARCH 
Shell: bash 4.4.23 
Resolution: 1366x768 
DE: Cinnamon 3.8.8 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Blue (Arc) 
Theme: Arc [GTK2/3] 
Icons: Arc [GTK2/3] 
Terminal: xfce4-terminal 
CPU: Intel Celeron G1610 (2) @ 2.600GHz 
Memory: 5669MiB 
 ```

**Issue**
In a place with 20 folders, when you create folder number 21 you can not give it a name.

**Steps to reproduce**
1- In the user folder ($)
2- Create 20 folders
3- Create 1 more folder
4- You can not give it a name

**Expected behaviour**
It assigns the name: _Untitled Folder_
Touching F2 or right button: _Rename_... does not allow to change the name

**Other information**
If the name have only letters, only numbers or special characters... it has the same behavior.
Deleting folder number 21 and create a new one, it has the same behavior.
Restart the computer and trying to change the name, it has the same behavior.

![test1](https://user-images.githubusercontent.com/31228150/45813021-daba4180-bca7-11e8-9fd3-2e6c502dab7b.png)

![test2](https://user-images.githubusercontent.com/31228150/45813303-a430f680-bca8-11e8-9ba0-3e42d4733739.png)

**Comment by parnikkapore** [comment]
Can't reproduce. Can you run `nemo` in a terminal, get the issue to happen and post what appears?

**Comment by rpxomi** [comment]
Yes, it is inconsistent. I think this will be closed, by diffuse information. But I do not know why this happens in the instance of Nemo who has running on my computer.

Now the same thing happens, but in a folder with fewer elements. If I maximize the window and then return it to its previous size, I can change the name of the files. Or if I cut several files and pasted them in another location, then I can change the name of the files that are in the original location. 

Run Nemo to enter the home folder, create some folders and I delete them, and this appeared. 
![nemo_terminal_1](https://user-images.githubusercontent.com/31228150/45950067-98a93c80-bfd4-11e8-979b-ff0885dec4ed.png)

And it did not automatically return the prompt of the terminal, it remained 20 or 30 seconds until it returned to be able to continue entering commands.
![nemo_terminal_2](https://user-images.githubusercontent.com/31228150/45950072-9e9f1d80-bfd4-11e8-861a-0f2dcbe0c37b.png)

I tried to use these two commands, but the same thing is still happening. What I realized is that when renaming anything, those errors begin to appear every time I press a key to write a name. Or sometimes, when selecting and deselecting an folder or file with the left click.
![nemo_terminal_3](https://user-images.githubusercontent.com/31228150/45950076-a2cb3b00-bfd4-11e8-977e-2e00c3beb78d.png)

This happens in an installation of Arch Linux from scratch (new partition table, new partitions and new file system). In the doubt that there are things installed that have caused strange behavior.

It is not the first time this happens to me. The error of GLib / Gtk, I have seen previously but searching the internet I did not find a way to solve it. Apparently it is not something general. Is any limit for Nemo? Any configuration file that I can edit? In .config, .local or using dconf-editor I do not see anything related.

**Comment by rpxomi** [comment]
I do not know if it is related to this, but when closing X an assertion appears for g_dbus
![glib_assertion](https://user-images.githubusercontent.com/31228150/45954020-335c4800-bfe2-11e8-85da-0cf5d3de49d7.jpg)

Before, there were also GLib errors in the terminal when closing X, but testing things like...

**edit environment:** 
`sudo nano /etc/environment`
`QT_STYLE_OVERRIDE = gtk2`

**install gconf:** 
`sudo pacman -S gconf`

**and compile glib from the AUR**

those errors do not appear, the assertion and Nemo's GUI problem yes.

I guess it must be something related to GTK.

**Comment by leigh123linux** [comment]
Rename works fine here.

```
mkdir ~/test ;cd test;mkdir {1..20};nemo .
```

nemo has no issue creating and renaming 'Untitled Folder' to 21

**Comment by rpxomi** [comment]
Sure, but using the graphical interface. Not through the terminal.

So that the GLib/Gtk errors appear in Nemo.

And from there you get a behavior similar to what happens to me.

Although I understand that there is no way to prove that this is general.

**Comment by rpxomi** [comment]
But using the graphical interface, not through the terminal. So that GLib/Gtk errors appear in Nemo and from there get a behavior similar to what happens to me (although it is not an absolute affirmation that this will happen).

The problem is not creating the folders, the problem is wanting to rename through the GUI some folder after so many folders have been created in a location.

Because it does not allow to give a name when creating it and it is maintained with the default name, and a folder must be copied in another location to change the name.

Although I understand that there is no way to prove that this is general.

**Comment by mtwebster** [comment]
This log is incomplete: https://user-images.githubusercontent.com/31228150/45950067-98a93c80-bfd4-11e8-979b-ff0885dec4ed.png

can you `killall nemo` then start nemo again from a terminal, I want to see startup logging.

Can you also provide *system* startup logs - journal I guess.  I suspect an issue between gtk, dbus, and some accessibility machinery.

What version of gtk3?

**Comment by mtwebster** [comment]
Thanks @pols12 with that I can reproduce the issue.

The view is only affected at that very small point in vertical size when the scroll bar has *just* appeared...make the window even shorter, and renaming works.  Make it taller so the bar disappears, and renaming also works.

**Comment by rpxomi** [comment]
Thanks!
