### ISSUE TITLE
Unable to run nemo (ver 3.8.6) as root - Archlinux

### ISSUE THREAD

**Issue by spsf64** [linuxmint/nemo#1949]
This happens with Archlinux, not sure if this is a nemo or gtk problem...
It seems related to latest GTK3 3.24.1
I opened a forum topic with more details:
https://bbs.archlinux.org/viewtopic.php?id=240394
Basically it will display a segfault and you can see the coredump too.

It works if GTK  is downgraded to 3.22 .x

TIA

**Comment by leigh123linux** [comment]
Full root doesn't provide the required dbus parts, try

```
su
dbus-launch --exit-with-session nemo
```

**Comment by spsf64** [comment]
Ok, I will post back to arch forums and try to find a solution.
The command "sudo dbus-launch --exit-with-session nemo" does work, however the context menu in GUI does not...
I am not skilled in programming/coding, I will wait to see if this get solved...
Thanks

**Comment by eli-schwartz** [comment]
FWIW as discovered in the distro thread, this seems to occur specifically with the intersection of gtk 3.24.1 and a dbus package compiled `--without-x`

Also this is the same issue discussed on Slack:

> @mtwebster
>> i'm guessing it's happening here: https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtkprivate.c#L305
>> pointer arithmetic on g_dbus_connection_get_unique_name (connection)
>> which could return null according to the docs
>> i'm calling it a gtk bug.  why is it (potentially?) returning null? that may be a nemo or dbus issue i suppose
>> or some bullshit to do with root/pkexec/etc...
>> check environment vars maybe... or.. does it occur when originally having started nemo in a terminal `nemo --quit && nemo` versus opening d-feet->Session bus-> clicking org.Nemo, *then* immediately opening a nemo window so it uses the dbus-launched process.. or simply running `pkexec nemo`

**Comment by robin0800** [comment]
Installing "dbus-x11" (manjaro) makes nemo root  work
