### ISSUE TITLE
List view odd column width

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1952]
```
 * Nemo version - 3.8.6
 * Windowed
 * Distribution - Arch Linux
 * NVIDIA Geforce GTX 1080, driver version: 396.54
 * 64 bit
 ```

**Issue**
When browsing a directory containing files with somewhat long filenames in list view, the name column's width is increased to the point where it pushes the last column to be slightly out of view. 

![image](https://user-images.githubusercontent.com/40209997/45924662-3dc20780-bf38-11e8-86c2-9845ec082783.png)
(Notice the scrollbar on the bottom)

Not only is it still unable to display the full filename, it pushed that last column out of view, so now I have to scroll to see the full information on that last column.

**Steps to reproduce**
* Create a folder
* Create files with really long filenames
* Browse it in Nemo, with list view

**Expected behaviour**
Combined column width not exceeding window width.

**Other information**
I've seen this kind of dumb behavior in KDE's Dolphin, it just doesn't work. If you want to make it calculate the column widths based on the column's content, please make sure the result does not exceed the window width, or else it will do more harm than good.
Additionally please include an option to disable it as well.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
