### ISSUE TITLE
Switch panes with TAB, Keyboard shortcuts [Enhancement]

### ISSUE THREAD

**Issue by rypz79** [linuxmint/nemo#1953]
```
 * Nemo version 3.9.0
 * Windowed Nemo (GNOME 3.28.2)
 * Distribution - Ubuntu 18.04.1 
 * 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
	Subsystem: Hewlett-Packard Company HD Graphics 5500
	Kernel driver in use: i915
	Kernel modules: i915
 * 64 bit
 ```

**Issue**
1) I cannot switch between panes using a keyboard shortcut. The TAB key is my choice of preference. 

2) When not in a dual-pane mode I suggest using TAB (and SHIFT+TAB) or other dedicated key to traverse between (or focus on) the side-bar, main tool-bar and menu-bar.

3) ALT alone doesn't open the menu-bar (Only ALT+key[f,e,g etc...])  

Generally speaking there should be an option for a keyboard shortcuts assignment in Nemo (maybe in a tab under preferences).

**Steps to reproduce**
Open dual pane mode and try to switch between panes
Try to traverse all the menus , bars and buttons only with a keyboard

**Expected behaviour**
Full keyboard control over Nemo

**Other information**

**Comment by kaymio** [comment]
This is a basic component I've been longing for, for a very long time. Tab doesn't do anything. Please add support for this very important part of any file manager.

**Comment by novalis111** [comment]
This would be very useful. The default key is F6 which does exactly that, but TAB + SHIFT+TAB would be much better for compliance with other file managers (gnome commander, krusader, total commander, ...).

Or a simple way to customize (and list) these shortcuts.

**Comment by DuMuT6p** [comment]
Hello,
To note that F6 doesn't switch to "Devices" and "Network" groups. 
I also think that support for TAB (and SHIFT+TAB) is a needed feature. Both for accessability and power users.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by smurphos** [comment]
> Or a simple way to customize (and list) these shortcuts.

Not as simple as it should be but it's not hard to amend nemo's built in keybindings to end-user preference - example https://forums.linuxmint.com/viewtopic.php?p=1696073#p1696073

**Comment by LinuxOnTheDesktop** [comment]
So far as I can see, there is no way whatsoever of using the keyboard to move from the left pane ('My Computer', 'Bookmarks') to the right pane (that latter pane showing the contents of the currently focused directory). That situation is counter-intuitive and makes navigation harder.
