### ISSUE TITLE
It is not possible to set the background image by nemo-action if it has a Cyrillic path.

### ISSUE THREAD

**Issue by eyes-0nly** [linuxmint/nemo#1956]
```
 * Nemo version 3.8.5
 * Windowed Nemo (Cinnamon 3.8.8)
 * Distribution - (Fedora 28)
 * 64 bit
 ```
It is not possible to set the background image by nemo-action(context menu/right-click menu) "set-as-background.nemo_action" if it has a Cyrillic path. For example  "/home/user/Изображения/background.png".

Quick fix.
Change this line in "/usr/share/nemo/actions/set-as-background.nemo_action"

Exec=gsettings set org.cinnamon.desktop.background picture-uri "%U"

To

Exec=gsettings set org.cinnamon.desktop.background picture-uri 'file://%F'

**Comment by mtwebster** [comment]
Hi, I apologize for not addressing this sooner, I had meant to when you first reported it.  This is actually a bug in how nemo parses the action Exec line when it gets activated.

See:
https://github.com/linuxmint/nemo/commit/d41298bc747df3de5cbfe11cb09aedb2e01115b1

This uri:
`file:///home/mtwebster/Pictures/lll/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/0BeachesAndLagoons3.jpg`

was being output to the gsettings command as:

`file:///home/mtwebster/Pictures/lll/0%980%B70%BE0%B11%800%B00%B60%B50%BD0%B81%8F/0BeachesAndLagoons3.jpg`

`%D` is a token for device name (useful for operating on usb drives) and the action parser was removing those and trying and (in my case at least) failing to insert a drive name, but it would still remove the `%D` token, resulting in a bad uri.

With that commit, the parser will skip ahead after inserting something (like a uri) so it doesn't accidentally treat escape codes as replacement tokens.

If you can, please try git master of Nemo to confirm this fixes the issue.  I don't mean to override the PR you made, but this fixes the actual problem (nemo shouldn't have any issue with valid uris)

Also, I'm not sure if you were aware, you can run `NEMO_ACTION_VERBOSE=1 nemo` to have extra logging info sent to the terminal when debugging actions.

Thanks

**Comment by eyes-0nly** [comment]
I patched rpm with your changes 

```
diff -uNr nemo-4.0.2/libnemo-private/nemo-action.c nemo-4.0.2p/libnemo-private/nemo-action.c
--- nemo-4.0.2/libnemo-private/nemo-action.c	2018-11-19 12:52:15.000000000 +0300
+++ nemo-4.0.2p/libnemo-private/nemo-action.c	2018-11-26 19:59:53.747338847 +0300
@@ -1032,8 +1032,8 @@
         str = g_string_insert (str, shift, insertion);
 
         token_type = TOKEN_NONE;
+	ptr = find_token_type (str->str + shift + strlen(insertion), &token_type);
         g_free  (insertion);
-        ptr = find_token_type (str->str, &token_type);
     }
 
     return str;

```
But for some reason, this did not fix the issue. Do I need to rebuild with all master changes?

**Comment by mtwebster** [comment]
Stupid question perhaps - did you kill and restart nemo after installing the modified version (this is more common than you can imagine)?

Can you run with NEMO_ACTION_VERBOSE=1 so I can see how the file name is being parsed out?  I didn't switch my locales or anything, I simply copied the folder name you provided to test, perhaps there's something I'm missing.

**Comment by eyes-0nly** [comment]
Today I checked and it looks like it is working with this patch. Perhaps I really forgot to restart nemo. I apologize for the misinformation earlier. Thank you for your work.
