### ISSUE TITLE
Double clicking and trying to double click again fast makes the mouse click unresponsive

### ISSUE THREAD

**Issue by fermmm** [linuxmint/nemo#1958]
```
 * Nemo version: 3.8.6
 * Is issue with desktop or windowed nemo?: Both
 * Distribution: Mint 19
 * Graphics hardware *and* driver used: Any, I can reproduce the bug in any compuer.
 * 32 or 64 bit: Any
 ```

Nemo in list mode: double clicking and trying to double click again very fast without moving the mouse makes the click unresponsive forever until the pointer is moved, so you cannot make more than one double click "fast" without moving the mouse. This bug is sooo annoying for me, I use list mode always so it happens to me all the time, I cannot get used to this bug.

How to reproduce:

1) Open nemo and chose a folder to test, set the scroll position so when the folder is double clicked (and opened) must show another sub-element under the pointer so doing another double click without moving the mouse should open the sub-element. (It's easy when the folder is the first row of the list).

2) Make sure at least the folder content is displayed in list mode, this bug only happens in list mode. 

3) Do it. Double click the folder and without moving the mouse try to double-click again fast in the sub-element that appears under the pointer, notice the click does not work anymore. You must do it fast to trigger the bug. Move the mouse to make the click to work again.

If you wait like 500ms after the first double-click, the bug does not happen, but forces you to wait to double click again and it's annoying.

If this is a "feature" to prevent the user to do any mistake I think this is not a good idea for the following reasons:
1. The click becomes unresponsive forever unless is moved, this should not be a feature.
2. Is not consistent since it does not happen on other views other than list view.
3. People who clicks fast knows what they are doing or they should, is their problem. 

Thanks.

**Comment by sharpentheaxe** [comment]
Hi fermmm,
       I was able to replicate the issue and I can see what you are saying.  I think this is a feature to prevent clicking past the next folder.  I could not replicate your issue in the icon view.  Would it be better to use the icon view rather than the list view if your a fast clicker?  I am just trying to figure out how else they would prevent someone from clicking into the next folder if they are a hyper clicker.  What do you think should happen?

**Comment by fermmm** [comment]
I think this is not a good feature, it should be just removed, at least it should not be enabled by default. This is the only OS where this feature exists. In the other OS I can click fast and nothing wrong happens because I click fast because I have practice doing that, not because I'm crazy and I click a lot and then I work with the wrong files because I clicked more times than I should, makes no sense to me.

This feature is very strange, is this a feature to make mint usable to people with Parkinson or something like that? In that case it should be disabled by default and should be enabled in an accessibility menu.

**Comment by fermmm** [comment]
> Hi fermmm,
> I was able to replicate the issue and I can see what you are saying. I think this is a feature to prevent clicking past the next folder. I could not replicate your issue in the icon view. Would it be better to use the icon view rather than the list view if your a fast clicker? I am just trying to figure out how else they would prevent someone from clicking into the next folder if they are a hyper clicker. What do you think should happen?

I think this is not a good feature, it should be just removed, at least it should not be enabled by default. This is the only OS where this feature exists. In the other OS I can click fast and nothing wrong happens because I click fast because I have practice doing that, not because I'm crazy and I click a lot and then I work with the wrong files because I clicked more times than I should, makes no sense to me.

This feature is very strange, is this a feature to make mint usable to people with Parkinson or something like that? In that case it should be disabled by default and should be enabled in an accessibility menu.

**Comment by shamoi** [comment]
Oh please someone, fix this!

**Comment by DanielBonnery** [comment]
> Oh please someone, fix this!

This issue has been around for ages and is a real pain.

**Comment by mtwebster** [comment]
@DanielBonnery you appear to be describing a different issue.

- Is the program you want to use set as the default for that file type? What happens when you double-click or click+enter? Nothing? Have you selected the program in the "open with" dialog and clicked "Set as default"?

What program is it?

**Comment by Jeremy7701** [comment]
Have you tried modifying the double-click interval to suit your fingers?
Are you using the current version of nemo (4.8.6)?

**Comment by DanielBonnery** [comment]
> @DanielBonnery you appear to be describing a different issue.
> 
> * Is the program you want to use set as the default for that file type? What happens when you double-click or click+enter? Nothing? Have you selected the program in the "open with" dialog and clicked "Set as default"?
> 
> What program is it?

Thank you for your reply.
Yes, it is another issue with clicking in nemo.
I am using last version for ubuntu bionic, which is 3.6.x
If I double click this file:
![image](https://user-images.githubusercontent.com/4399541/117874331-be280900-b298-11eb-98da-16028ced400b.png)
then nothing happens.
If I select and click enter,  nothing happens (e.g. it is not a matter of time between clicks)
If I double click pdfs it works well.
Default app for tex file is texmaker on my laptop.

**Comment by DanielBonnery** [comment]
Here a gif:
In the beginning I am trying both double clicking and pressin the button Enter. Nothing happens. Right click open -> nothing happens. I need to Right click, open with , other application, select default, OK.

![Peek 2021-05-11 20-50](https://user-images.githubusercontent.com/4399541/117875962-b10c1980-b29a-11eb-9c90-59969e112506.gif)

**Comment by mtwebster** [comment]
It looks like he's maybe already done that.

Try temporarily renaming `~/.config/mimeapps.list` then re-setting texmaker as the default app

**Comment by DanielBonnery** [comment]
Thanks for your help. 
THis is the line for tex extension in `~/.config/mimeapps.list`: 
`[Default Applications]
text/x-tex=texmaker.desktop
[Added Associations]
text/x-tex=texmaker.desktop;kde4-kile.desktop;org.kde.kile.desktop;
`
I removed all texmaker. Then double click opens classical text editor. If I put it back only in 
```
[Default Applications]
text/x-tex=texmaker.desktop
```
the same problem happens. Double clicking has no effect.

**Comment by mtwebster** [comment]
Are there any desktop files in ~/.local/share/applications that are related to texmaker?

If you run nemo from a terminal, are there any warnings when you try to launch texmaker? (`killall nemo` first)

**Comment by DanielBonnery** [comment]
This is what happens, nemo reads the tex file and issues a series of error messages for each line in the file.


![Peek 2021-05-12 10-46](https://user-images.githubusercontent.com/4399541/117954997-7bedde80-b30f-11eb-812e-068a028b8efe.gif)

There is an app related to texmaker.
`$ls ~/.local/share/applications
userapp-texmaker-RREKE0.desktop`

**Comment by mtwebster** [comment]
Try deleting that file in ~/.local/share/applications (or rename it to something that doesn't end in .desktop)

**Comment by DanielBonnery** [comment]
Hello, I just deleted it.
It did not work. 
![Peek 2021-05-14 10-23](https://user-images.githubusercontent.com/4399541/118250522-7bd01900-b49e-11eb-878e-55fcf0dbca39.gif)

**Comment by DanielBonnery** [comment]
Thanks to your help, I found a fix.
Nemo thought that tex files were executable files. So it was trying to execute them. There was the same issue with rnw files and other types. It does not do with all tex files, only those beginning with \documentclass ...
I chnaged the default and asked never to execute executable files and open in text editor when double lcicking.
It solved the issue.

**Comment by Jeremy7701** [comment]
Nemo would only attempt to execute files if they are marked (in permissions) as executable.
Edit -> preferences allows you to influence this behaviour, slightly.

![Screenshot from 2021-05-16 23-58-12](https://user-images.githubusercontent.com/52585119/118415519-b99d8f00-b6a2-11eb-81a3-5f814a734bea.png)
