### ISSUE TITLE
Frequent Random Crashes

### ISSUE THREAD

**Issue by rebeltaz** [linuxmint/nemo#1959]
```
 * Nemo version - 3.6.5
 * Is issue with desktop or windowed nemo? - desktop (I guess?)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Ubuntu 18.04 LTS
 * Graphics hardware *and* driver used - 
      00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
      configuration: driver=i915 latency=0
 * 32 or 64 bit - 64 bit
 ```

**Issue**
Nemo crashes regularly - multiple times a day - with no common denominator among causes... opening a file; navigating to a directory; right-clicking a file/directory; left-clicking a file/directory.... This happened when I was running10.04 LTS as well. 

**Steps to reproduce**
no common denominator among causes... opening a file; navigating to a directory; right-clicking a file/directory; left-clicking a file/directory....

**Expected behaviour**
ummmm... not to crash ;)

**Other information**
I don't know if it's pertinent, but I am running gnome-fallback-session instead of Unity and I have Nemo set as the default file manager. I only have one extension  installed (by default, I suppose) - Nemo Fileroller, but I have disabled that.

**Comment by leigh123linux** [comment]
Nemo 3.6.5 is EOL and you never posted enough info to debug the issue.
