### ISSUE TITLE
Icons get re-arranged, even after F5, after screen mirroring

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1961]
```
 * Nemo version (nemo --version): 3.8.6
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: Intel 620 (Kabylake GT3) 3.0 Mesa 18.2.1
 * 32 or 64 bit: 64
 ```

**Issue**

Icons get re-arranged, even after F5, after screen mirroring. That is: after I connect my laptop to a projector, and set the screens to mirror each other, and then disconnect the projector, and - when necessary, which is sometimes - change screen resolution, then, even after refreshing the desktop, some icons - namely, the Home and Bin icons - move to a different place.

**Steps to reproduce**

Attach external screen (of some particular type?).
Mirror displays.
Unplug external screen.
Reset resolution, if necessary.
Press F5 in hope of righting icon placement.

**Expected behaviour**

Icons should return to where they were, either after disconnection of external monitor (projector) or at least after changing screen resolution or at least after F5.

**Other information**

I believe there is an existing bug report about this; but perhaps it is a closed one, because I searched the open ones to no avail.

If I may say so, this bug, while necessitating only slight user intervention (only two icons moved), does make Mint look bad, and in public (for, though the projector is disconnected, the laptop is still out in public).

**Comment by xenopeek** [comment]
Related to #1965

I think this doesn't happen with Nemo 4.6.4: with auto-arrange off icons stay where they were put when switching resolutions. A side effect of that is when switching to a lower resolution some icons may no longer be in view. But that is a different issue from this one.
