### ISSUE TITLE
When file size is 0 bytes nemo will open as text instead of assigned application to extension and crashes

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/nemo#1962]
nemo 3.8.6
windowed nemo
Linux Mint 19

**Issue**

When file size is 0 bytes nemo will open as text instead of assigned application, this can cause nemo to crash when file is filled with digital data which is opened as text.

**Steps to reproduce**

Go to a folder and create a new text document of 0 bytes. Rename the textfile to a file with extension .mkv. The file will remain a text file. When opening the file it will be opened as text file. When adding some text and saving the file it will then be attached to the assigned application.

**Expected behaviour**

When a file is 0 bytes it still has to be opened with the assigned application for the extension, otherwise when opened and the file is filled with digital data nemo (and cinnamon also) will lock up most of the times.

**Other information**

**Comment by mtwebster** [comment]
This sounds like it's been addressed (https://github.com/linuxmint/nemo/commit/abe24e74a8fd678e86dbadb935dd2c1b6f36372d) though not released yet.

**Comment by mtwebster** [comment]
This is in the current release
