### ISSUE TITLE
Desktop Icons not rendered correctly on different resolution monitor using "Larger" or "Smaller" sized icons

### ISSUE THREAD

**Issue by miguel-pytoluk** [linuxmint/nemo#1965]
```
 * Nemo version: 3.8.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Ubuntu 18.10, running Gnome
 * Graphics hardware *and* driver used: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)  |  driver=i915
 * 64 bit
 ```

**Issue**
Using "Larger sized" icons on Nemo-desktop (using align to grid, but not auto-arrange) on a 2560 x 1080 Monitor, and then switching to a 1920x1080 TV, the "Home" and "mounted device" (DADOS) icons would go to strange places.
(1) Getting back to the 2560x1080 Monitor without changing icons position on TV would not get the icons back to the correct place.
![case 1](https://user-images.githubusercontent.com/19481643/46911303-3b970b80-cf2e-11e8-9407-35359f8a988e.png)
(2) Trying to put the referred icons on the correct spot by dragging get things worse, because icons doesn't seem to be aligned on grid correctly anymore.
![case 2](https://user-images.githubusercontent.com/19481643/46911347-5cac2c00-cf2f-11e8-9966-a76dc78fd33c.png)

The issue is not observed using "Normal sized" icons.

Using "Smaller sized" icons, the issue is not so harmful, but still observable 
![screenshot from 2018-10-13 21-32-07](https://user-images.githubusercontent.com/19481643/46911390-8580f100-cf30-11e8-9ded-a49dbbdc616b.png)

**Steps to reproduce**
Unplug HDMI cable from 2560x1080 monitor to 1920x1080 TV and back to 2560x1080 monitor using "Larger Icons". 
It also occurs using "Smaller Icons", but not as badly, because only "Home" and "mounted device" icons seems to be out of grid, but can be simply dragged to be fixed.

**Expected behaviour**
The "Home" and "mounted device" icons are expected to go to same place on another resolution. Also the grid is expected to be re-rendered on the new resolution, while it seems that grids are "superposing" in a sense.

**Other information**
Using "Normal Sized" icons the issue doesn't happen to occur at all. Since "Larger icons" is my favorite option for my hi-res monitor, i'd have to change to "Normal" before I plug the TV, and when I switch back to the Monitor I set to "Larger" again.

**Comment by mtwebster** [comment]
This is unfortunately part of another problem I've had with the desktop since it was reworked a couple of releases ago.  It was initially done with a strong effort to keep the 'old' desktop available as well for users that don't appreciate change as much as others, and the result is a huge challenge to keep the icons where they belong across all of the possible events that happen to a desktop.

I don't know if I'll get to it for the upcoming release, but it's definitely at or near the top of my todo to re-implement how desktop icons are placed.

**Comment by xenopeek** [comment]
This doesn't happen with Nemo 4.6.4: with auto-arrange off icons stay where they were put when switching resolutions. A side effect of that is when switching to a lower resolution some icons may no longer be in view. But that is a different issue from this one.
