### ISSUE TITLE
Feature request: enable user to type path into open/save box, *immediately*

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1966]
```
 * Nemo version (nemo --version) 3.8.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19 Cinnamon
 ```

**Issue**

When within an application, e.g. Sublime Text, I cause the file-handling - open file or save file - window to open for the first time, there is nowhere to type a path. In order to type a path, I must change folder or else twice press ctrl-l. Indeed, if the application in question is `xed`, then I must: open the file-handling dialogue, change folder, then press ctrl-l (or else, instead of all that, twice press ctrl-l).

This is an inconvenience with no rationale of which I am aware.

I _think_ it is a Nemo problem, as against a problem with some applications.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
Please do a search around. This has been brought up so many times. It has nothing to do with nemo. It's a Gtk issue.
