### ISSUE TITLE
nemo freezes when transfering files

### ISSUE THREAD

**Issue by illumilore** [linuxmint/nemo#1971]
When transfering files to phone using mtp address, nemo will consistently freeze

**Comment by leigh123linux** [comment]
Next time can you provide basic info and a backtrace.

**Comment by momo42** [comment]
I don't believe you read this but I'm shocked to see such rude comments on people wanting to help. Do you really think, illumilores' intention was to spam your bugtracker? Not everyone (including me) is able to provide such infos without advice what to do. I don't think closing the bug and calling the volunteer a spammer is a good strategy to motivate users to hand in better bug reports ...

**Comment by Cobinja** [comment]
That's what the issue template is for that prefills the textfield when you open a new issue.

**Comment by leigh123linux** [comment]
@momo42 Either way your report was worthless without info, I class it as worthless spam and a total waste of my time!
I can also be very rude which I haven't been up to now, you falsely accuse me.

"Fuck off Moron" 

How is that for rude!
