### ISSUE TITLE
change icon theme on xfce

### ISSUE THREAD

**Issue by PowaBanga** [linuxmint/nemo#1973]
```
 * Nemo version (nemo --version)
3.8.6
 * Is issue with desktop or windowed nemo?
hmm, the good answer is probably with nemo, windowed, or in full screen
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Archlinux
 * Graphics hardware *and* driver used
intel core 3
 * 32 or 64 bit
64 bit
 ```
Hi, I installed nemo on my xfce, because i think that it's better than thunar, and my problem is that the icon theme is not accorded with the icon theme setted by xfce. So, i changed the xfce theme by Faenza-Dark, and it's not applied to nemo.
So i installed dconf-editor to fix that and in /org/gnome/desktop/interface/icon-theme i changed default theme (adwaita) by Faenza-Dark. This have no effect.

Does anybody can help me to fix that ?
**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by mtwebster** [comment]
If the rest of your desktop changes themes, nemo should, though you may need to restart it for this to take effect.

`nemo --quit`
`nemo-desktop --quit`

will kill both the desktop and any windowed instance.  The desktop one should restart on its own.

**Comment by PowaBanga** [comment]
ok so i launched nemo, and did this after : 
```
[powabanga@karkatouf ~]$ nemo --quit
[powabanga@karkatouf ~]$ nemo-desktop --quit

(nemo-desktop:2296): Gtk-WARNING **: 14:03:00.266: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "RegisterClient" with signature "ss" on interface "org.xfce.Session.Manager" doesn't exist


** (nemo-desktop:2296): WARNING **: 14:03:00.276: Current gtk theme is not known to have nemo support (Adwaita-dark) - checking...

** (nemo-desktop:2296): WARNING **: 14:03:00.399: Missing support for critical theme elements.  Adding some...
Initializing nemo-image-converter extension
Killing nemo-desktop, as requested
```
But nothing changed ... :/

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4 on Xfce 4.14 (Linux Mint 20 Xfce). Changing the Icons theme through Appearance immediately applies it to Nemo and Thunar.
