### ISSUE TITLE
Nemo crash bug - Desktop icons disappear and no right-click menu

### ISSUE THREAD

**Issue by Serpent6877** [linuxmint/nemo#1974]
This is a fresh Mint 19 install with all updates. Based on other users issues I would say this is related to Nvidia drivers. But unable to confirm 100%.

When I attempt to drag a text file from the desktop to relocate or move to a folder the icons are not movable and all icons will disappear due to Nemo crash. Then I can no longer right-click on the desktop. This is a three monitor configuration. Auto-arrange was un-clicked and still same issues.

* Nemo version (nemo --version)
3.8.6+tara
 * Is issue with desktop or windowed nemo?
Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Mint 19 (Cinnamon)
* Graphics hardware *and* driver used
NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)
NVIDIA Corporation GM204 [GeForce GTX 980] (rev a1)
nvidia-390 (Version 390.87-0ubuntu0~gpu18.04.1)
 * 32 or 64 bit
64 bit

Grabbing a text file from Home Folder and trying to drag it results in:
[Home-Folder-Drag.txt](https://github.com/linuxmint/nemo/files/2527322/Home-Folder-Drag.txt)
xorg.conf
[xorg.conf.txt](https://github.com/linuxmint/nemo/files/2527327/xorg.conf.txt)

_Originally posted by @Serpent6877 in https://github.com/linuxmint/nemo/issues/1972#issuecomment-434108058_

**Comment by Serpent6877** [comment]
This is a fresh Mint 19 install with all updates. Based on other users issues I would say this is related to Nvidia drivers. But unable to confirm 100%.

**Comment by Serpent6877** [comment]
Okay. This is easy to reproduce and is a bug related to multiple Xscreens with the nvidia driver. This bug can be reproduced on a single card with two monitors. In Nvidia settings under "X Server Display Configuration" set the second monitor "Configuration" to "New X screen". Enable Xinerama. CTRL+click the monitor icon and set the position to "Right Of". Save the configuration as /etc/X11/xorg.conf

Reboot. Then try and drag an icon. The second attempt crashes Nemo.

**Comment by mtwebster** [comment]
Multiple XScreens are not supported in Cinnamon or Nemo
