### ISSUE TITLE
2 levels in bookmarks

### ISSUE THREAD

**Issue by azjio** [linuxmint/nemo#1977]
FEATURE REQUEST

make the following:
bookmarks
.................System
................................../usr/share/backgrounds
................................../usr/share/icons
................................../usr/share/themes
................................../usr/share/applications
.................Home
................................../home/user/Downloads
................................../home/user/Documents
.................Video
................................../media/windows/Video
................................../media/windows/torrent
................................../media/windows/Downloads/Video
...etc

Make categories

**Comment by xenopeek** [comment]
Duplicate of #1874
