### ISSUE TITLE
Copy-paste does not work if target if a network (samba share)

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1980]
```
 * Nemo version (nemo --version) 3.8.6
 * Is issue with desktop or windowed nemo? Both?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: N.A.
 * 32 or 64 bit: 64
 ```

**Issue**

Copy-paste does not work if target if a network (samba share). Dragging an item from one window to another does work.

**Steps to reproduce**

Have Nemo window showing local stuff. Have Nemo windowing showing mounted (and otherwise working) samba share. Copy a folder in the first window, using either ctrl-C or context menu. Try to paste it using either keyboard or mouse into second folder.

**Expected behaviour**

Copying. Actual behaviour: nothing.

**Other information**

Cf. #1911?

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
