### ISSUE TITLE
[Feature Request] Advanced drag n drop funcitonality

### ISSUE THREAD

**Issue by SomezGit** [linuxmint/nemo#1982]
```
 * Nemo version (nemo --version)
nemo 3.8.6

 * Is issue with desktop or windowed nemo?
N/A

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19

 * Graphics hardware *and* driver used
Intel HD3000

 * 32 or 64 bit
64 bit
 ```

**Issue**

This is a feature request. On macOS, the Finder has very advanced file manipulation features for drag n drop. For example, when you start dragging a file and you want to move it to a subfolder that is a few levels below from the existing location, then you just drag the file over the first folder and keep it there until the folder flashes and opens up, then inside this folder you hover again, folder is flashing and opens up, then you drop your file you'd been dragging into the folder.

Right now in Nemo nothing happens if I keep the dragged file over a folder and I'm not aware of any way to open up that folder without dropping the file first.

Thank you.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
