### ISSUE TITLE
Show Thumbnails doesn't work with search when Per Folder is set

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1985]
```
 * Nemo version (nemo --version)
4.0.1
 * Is issue with desktop or windowed nemo?
Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia 410.73
 * 32 or 64 bit
64Bit
 ```

**Issue**
I'm using the new "Per Folder" setting for "Show Thumbnails" (which is awesome btw) and I've noticed that when you search for stuff, you can't just show the thumbnails of files you've found by clicking on the "Show Thumbnails" icon in the results view.

**Steps to reproduce**
1) Select Per Folder as a Preview option
2) Put some images into a folder that *doesn't have* "Show Thumbnails" turned on
3) Search for some of these files.
4) Click on "Show Thumbnails" icon in the search results

**Expected behaviour**
I think `nemo` should show you thumbnails in search results when you click on the 'show thumbnails' icon regardless whether you have 'show thumbnails' selected for the folder where the image/video comes from has that option turned on.

Also, I don't want to make another suggestion issue but could we please get a "Show Thumbnails" as a right click option? :)

Anyway, new `nemo` is amazing! Thank you so much.

**Comment by xenopeek** [comment]
I can't find a "Per Folder" setting in Nemo 4.6.4. Thumbnailing was reworked for this release. I think this issue is no longer applicable. If any are still affect by this please retest with Linux Mint 20 Cinnamon and iff you're on another distro compare with Nemo 4.6.4 on your distro.
