### ISSUE TITLE
Mounting filesystem that is dirty

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/nemo#1992]
`There's no indication when mounting a filesystem that has dirty bit set`

 * nemo 3.8.6
 * desktop nemo
 * Distribution - Mint 19
 * 64 bit

**Issue**

If I mount a filesystem that has dirty bit set (such as an MP3 player that appears as a filesystem), I get a warning message in /var/log/kern.log ("FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.") but no indication in Nemo.  There should be some visible indication or warning.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by BillDietrich** [comment]
Still a problem with 4.4.2 on Mint 19.3 Cinnamon.  This problem should be given higher priority and fixed, it could cause data loss.

**Comment by leigh123linux** [comment]
It isn't a nemo issue

https://github.com/storaged-project/udisks/issues/245

gvfs should do the check

https://gitlab.gnome.org/GNOME/gvfs/issues

**Comment by BillDietrich** [comment]
Filed https://gitlab.gnome.org/GNOME/gvfs/issues/443

**Comment by BillDietrich** [comment]
Sorry, this should NOT be closed.  This is a serious issue that can cause data loss for users.  Even if the origin of the problem is upstream, this problem exists in Nemo.

**Comment by xenopeek** [comment]
Is this a Nemo specfic issue? I don't know how to make a filesystem "dirty" for testing but can you test the same with other filemanagers. How for example do Nautilus and Thunar handle this?

**Comment by BillDietrich** [comment]
The root cause is not specific to Nemo.  The dangerous behavior does appear in Nemo, as well as in other file-managers.  Nautilus does the same as Nemo, ignores the problem.  I don't know about Thunar.  A user of Nemo who comes here to search for open issues should be informed of this issue.

**Comment by BillDietrich** [comment]
How to make a filesystem "dirty":  this happens with little portable MP3 players, which often use FAT or FAT32 filesystem.  There is a mention of dirty bit in exFAT filesystem docs, so maybe it is possible on exFAT also.

To make it "dirty": connect MP3 player via USB, it shows up as a filesystem, make some changes such as copying files to it, then disconnect the player from USB without first unmounting / ejecting in Linux / Nemo.

Next time you plug MP3 player into USB, dmesg will say "dirty" but Nemo will give no indication.
