### ISSUE TITLE
adjust grid fails in nemo 4.02

### ISSUE THREAD

**Issue by dodona2** [linuxmint/nemo#1993]
```
 * Nemo version (nemo --version) nemo 4.0.2
 * Is issue with desktop or windowed nemo? desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Fedora 29
 * Graphics hardware *and* driver used Intel build-in
 * 32 or 64 bit 64 bit
 ```

**Issue**

**Steps to reproduce**
gsettings set org.nemo.desktop horizontal-grid-adjust 0.55
gsettings set org.nemo.desktop vertical-grid-adjust 0.5

**Expected behaviour**
desktop icons located narrower

**Other information**

**Comment by mtwebster** [comment]
Right-click desktop->customize

Grid adjust is per-monitor now, those settings are unused.  I need to mark those settings as deprecated, sorry.

**Comment by dodona2** [comment]
thanks a lot!
