### ISSUE TITLE
Help > All Topics (F1) changes the cursor into the loading circle for a certain period of time and doesn't return to normal when it should

### ISSUE THREAD

**Issue by zignd** [linuxmint/nemo#1995]
```
 * Nemo version: 3.8.5
 * Is issue with desktop or windowed nemo? Windowed (the one you open through Files the files shortcut)
 * Distribution: Linux Mint 19 Tara
 * Graphics hardware: Intel Corporation HD Graphics 620
 * 64 bit
 ```

**Issue**

Help > All Topics (F1) changes the cursor into the loading circle for a certain period of time, even after the page has been loaded on the browser or closed, and then returns to the normal arrow cursor

**Steps to reproduce**

Open Files, click Help, then All Topics, the cursor will switch to the loading circle, a web page will open, the loading circle will continue, even if the page has loaded (depending on the speed of internet connection) or was closed by the user, then it returns to the normal arrow cursor.

**Expected behaviour**

The cursor should return to the normal arrow version once the page has loaded or if it has been closed by the user. Or maybe don't even change into the loading cursor at all, but IMHO it will give the impression nothing is happening as the browser is preparing to open the tab that will load the page.

**Comment by xenopeek** [comment]
Retest with Nemo 4.6.4 on Linux Mint 20, this is reproducible.

1. Have default web browser open;
2. Press F1 in Nemo to open help;
3. Focus is set to the web browser window, switch focus back to Nemo window;
4. Notice that though the web page is already loaded the spinning circle cursor is still shown in Nemo.

As there is no help for Nemo the menu option should maybe just be removed.

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I'm not able to reproduce this issue. @xenopeek I tried your steps, but after pressing `F1` the focus stayed with the Nemo help window and did not switch off to the browser.

**Comment by Jeremy7701** [comment]
F1 should load the general Mint help page - [https://www.linuxmint.com/documentation.php](https://www.linuxmint.com/documentation.php) by launching your web browser in a new window.
The circle is a waiting to load indicator, that disappears when the web page is loaded.
The focus changes to the new browser window.
