### ISSUE TITLE
Keyboard search box on desktop: very confusing and cannot be disabled?

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1998]
```
 * Nemo version (nemo --version) 3.8.6.
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used. Irrelevant
 * 32 or 64 bit. 64.
 ```

**Issue**

When one types into the desktop, as it were, Nemo pops up a search box. Or so I have just realised; for years I did not know what the box was. I have encountered reports of others being confused by this as well. Hence I feel some sort of explanation should be provided. When using windowed nemo, the box is part of the nemo footer; this makes the box much less confusing than it is when it appears alone on the desktop. Also: while I seem to remember an option to disable the behaviour, I cannot find that option in Nemo's options.

**Steps to reproduce**

Type 'into' the desktop.

**Expected behaviour**

Users should now what on earth is going on.

**Comment by mtwebster** [comment]
This was removed a while ago then restored due to complaints it was missing:

https://github.com/linuxmint/nemo/commit/5d1711fd84267b823fc482559ab784fc813347d9

then

https://github.com/linuxmint/nemo/commit/a26378261eea3d24e5b98ca5437a6546b8b01732

I'm not messing with it for now.

**Comment by leigh123linux** [comment]
@mtwebster I removed this rubbish from fedora nemo a long time ago, If I add a PR are you going to ignore the complaints this time?

**Comment by CottonEaster** [comment]
It seems to me that _options_ would keep everyone happy - an option to disable/enable the box entirely (I was asking whether such an option exists already) - and an option to disable/enable the box for the desktop.

**Comment by mtwebster** [comment]
I'll consider an option for it for 4.2, I'm not going to do anything for 4.0.

If there were mobs of people wondering what this was I'd address it, but there is just one.  Honestly I don't know how we'd advertise it, other than as displaying a setting to disable it.

**Comment by CottonEaster** [comment]
I was sure I'd seen another report of bafflement; I've been trying to find it, but failing.

As to advertising: you could have a label for the box, a label that says (in the case of nemo desktop) 'search names of desktop icons'.
