### ISSUE TITLE
Tabs are created just to the right of the current tab.

### ISSUE THREAD

**Issue by mumeiyamibito** [linuxmint/nemo#1999]
In Nemo 3.8.6, a new tab is created by middle clicking directory or clicking from menu at right of current tab. However when I middle clicked multiple directories sequentially, the directory I clicked on first is generated on the far right.

It is a bit strange behavior. In Firefox or chrome, newly generated tabs are generated on the current tab or to the right of the recently generated tab.

**Comment by xenopeek** [comment]
Just like the Firefox default, new tabs are created immediately to the right of the current tab. If you open in order SubDir1, SubDir2 and SubDir3 the would show up as new tabs to the right of the current tab, in reverse order (as the most recently opened tab is immediately to the right of the current tab).
