### ISSUE TITLE
[Regression]: Nemo pyextensions: Icons missing on right-click selected item

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#2001]
```
 * Nemo version (nemo --version)
nemo 4.0.5
 * Is issue with desktop or windowed nemo?
windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
ubuntu 18.04
 * Graphics hardware *and* driver used
mesa, vitualbox driver;
graphics card: InnoTek Systemberatung VirtualBox Graphics Adapter driver: vboxvideo
 * 32 or 64 bit
64bit
 ```

**Issue**

![screenshot_2018-12-11_23-52-40](https://user-images.githubusercontent.com/8189198/49835939-2b21d680-fda1-11e8-8d2b-8c28da20c7d1.png)

When right-clicking an item in the filebrowser pane, the entries which belong to python extensions (AND file-manager-actions) are displayed without icons.

noticed in 3.6.8, 4.0.5;**still working in 3.6.5:**

**Steps to reproduce**
Activate some pyextensions (in the picture: Open as Root, Open in Terminal) OR define some actions with file-manager-actions (in the picture: the rest)

**Expected behaviour**
Right-click menu **when having selected an item** is showing the mentioned entries with icons.

**Other information**
Note: _the right-click menu when NOT having an item selected is showing the icons properly!_

![screenshot_2018-12-12_00-11-58](https://user-images.githubusercontent.com/8189198/49836392-b8195f80-fda2-11e8-84f5-7eb49cc9117b.png)

**Comment by leigh123linux** [comment]
Nemo-4 uses python3, you will need to bug the extension author install to port to python3

https://www.giuspen.com/nautilus-pyextensions/

**Comment by revast** [comment]
but file-manager actions is written in c, and it does also not work!

**Comment by mtwebster** [comment]
Likely this:
https://github.com/linuxmint/nemo/commit/fc1194a8ea0a6b8586af8e47d09cccd5fb4d8b2f

Try using symbolic icon names.

The second image showing icons in Open in terminal/root is because those two entries are part of core nemo, during a background click, not an action or extension.

The section under Scripts> is where nemo actions appear, those seem to be fine (other than we probably need to enforce symbolics only there as well)

Ths section above properties is where extensions appear.  Try using symbolic icons on those items (i'm not sure what extension is providing all of that)

**Comment by revast** [comment]
so because of that commit, I have to have symbolic items of everything?

- I mean I have a LOT of items in filemanager-actions, am I supposed to create symbolic items for all of these?

![screenshot_2018-12-17_19-47-39](https://user-images.githubusercontent.com/8189198/50108095-a9b0c500-0234-11e9-8dce-de21849119f0.png)

- why change something which worked before? I really don't get it. It may be cool to have an uniform look, can't we have that without breaking stuff that's working??
- also, the built-in nemo actions still allow any icon to be added, so what's the point here?

**Comment by revast** [comment]
sorry if that looked like this, this was not my intention.

I just wanted to know if there is a valid cause for this commit, like a deprecation or a feature which is only possible through this. 
As there is neither a roadmap nor a proper changelog for nemo (for what I know), its quite hard to tell what the intentions are on some changes. 

sorry again, that was no masterpiece of me. Its good that things change,  I think there is more the sorrow that things break on a wider area which caused me to write this. But even if this happens, you will have your arguments for that, which I just would like do hear then.
