### ISSUE TITLE
Question aboout .hidden files.

### ISSUE THREAD

**Issue by stefbon** [linuxmint/nemo#2002]
Hi,

this is not a bug, but more a question. I consider it perfectly fine if you just point me to somewhere else where I can find the info I need en delete this message.

I'm creating an automatic network filesystem mount service, using Avahi, FUSE, libgcrypt and a ssh library written by my self.

See: https://github.com/stefbon/fs-workspace

It creates an FUSE mountpoint at /run/fs-workspace/user/$USER/network
where networks, groups, servers, and shared directories are created in a virtual map,
and shared directories are available using the SSH/SFTP protocol.

Standard Openssh authentifaction is used (certs not tested) and working pk services like a secretkey is to be done. Futher support for UDP (using libudt) is one of the major upgrades. Also an open source file change protocol has to be developed, which should go in userspace also. It would for example be very very nice to know who (and when) has changed a file. This also counts for locks and leases. Working together sharing files this way becomes much more easy and convenient. Maybe a next version of the sftp protocol is required.

No it supports the .directory files (providing nice icons for network server and share). Nemo uses .hidden files, what is the syntax of these files? I've searched the internet, but found nothing.

Thanks in advance,
Stef

**Comment by leigh123linux** [comment]
> No it supports the .directory files (providing nice icons for network server and share). Nemo uses .hidden files, what is the syntax of these files? I've searched the internet, but found nothing.

So your asking how to hide files?

In linux files prefixed with . are hidden.

1. create a normal txt file

```
touch test.txt
```

2. rename file with . prefix

```
mv test.txt .test.txt
```

**Comment by NikoKrause** [comment]
https://linux-audit.com/linux-history-how-dot-files-became-hidden-files/

**Comment by stefbon** [comment]
No you do not understand. Nemo looks for the file with the name ".hidden", like Dolphin looks for ".directory" files. I know the format of .directory files, but not of .hidden files. Someone knows?

**Comment by NikoKrause** [comment]
You are right. I still do not understand. Please try to explain as simple as possible.

**Comment by stefbon** [comment]
Ok, good for you to ask. With applictions like Dolphin and Nemo you can adjust the view properties of the current directory, like icon. These settings are stored in these special files, Dolphin (and other KDE applications) do that in ".directory" files in the same directory, Nemo (and other Gnome applications?) do that in the file with name ".hidden". Now my application/service supports the ".directory" files (by emulating these). For a shared directory it looks like:

[Desktop Entry]
Icon=/usr/share/icons/Adwaita/512x512/places/folder-remote.png
Type=Service

The format is described somewhere at freedesktop.org. This gives a very nice icon for remote folders.

Now I'm using Nemo a lot lately, and like it very much. But it's not using these ".directory" files to store viewproperties, but a file with name ".hidden". I've seen that support for these file is added to glib lately (providing an universal interface, which is a good thing, but I do not know the format. Is it the same format? I hope so.

Thanks,
Stef Bon
Voorburg

**Comment by ByteHamster** [comment]
As far as I know, the `.hidden` files can only be used to hide files. They can not be used to set icons like `.directory` files. The `.hidden` files simply contain a list of files that should be hidden. Each entry is added in its own line. The file does not support `*` wildcards (https://unix.stackexchange.com/q/31688/103795)

**Comment by xenopeek** [comment]
Question about .hidden files was answered so closing this. As per the read_hidden_file in https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/glocalfileinfo.c and file_is_hidden in https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/glocalfileinfo.c, which is the only place where read_hidden_file is used from, the .hidden file indeed is just a list of filenames to hide in that directory.

For setting custom icons use `gio set`. To figure out what to do run `gio info` on a file or directory you've set that icon on through Nemo. You will find a metadata attribute in the `gio info` output which you should also be able to set for other files with `gio set`. May take some reading of the manpages & experimenting.
