### ISSUE TITLE
[Regression]: emblems of items which have root rights are missing

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#2003]
```
 * Nemo version (nemo --version)
nemo 4.0.5
 * Is issue with desktop or windowed nemo?
windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
ubuntu 18.04
 * Graphics hardware *and* driver used
mesa, vitualbox driver;
graphics card: InnoTek Systemberatung VirtualBox Graphics Adapter driver: vboxvideo
 * 32 or 64 bit
64bit

 ```

**Issue**
when chown-ing an folder/file to root, nemo normally displayed a flag/emblem which visually showed that the item was owned by root. 

but this flag is now missing.
![screenshot_2018-12-12_16-10-14](https://user-images.githubusercontent.com/8189198/49878760-a8dcf500-fe28-11e8-971f-357c29d53238.png)

**Steps to reproduce**
Chown a folder/file  to root. 
The folder does not get an emblem.

**Expected behaviour**
The folder does get an emblem.
![screenshot_2018-12-12_16-09-37](https://user-images.githubusercontent.com/8189198/49878775-b1cdc680-fe28-11e8-8813-7860df7ec469.png)

**Other information**
This is missing in nemo 4.0.5, I can confirm that it still is working in 3.8.6.

**Comment by mtwebster** [comment]
I can't reproduce this.

Does the emblem show after refreshing the folder? (or leaving, re-entering)

Can you reboot and try it? (I'm considering possible file monitor issues)

**Comment by revast** [comment]
ok, I have now set up a new vanilla ubuntu 18.10 vm, and installed nemo 4.0.6 from [PPA ](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/cinnamon/+packages)(for convenience, it's the version for 18.04, but it works fine for testing purposes.) I also restarted the vm, and opened nemo, and chowned xapps-common to root:

![peek 2018-12-17 13-45](https://user-images.githubusercontent.com/8189198/50088104-59b90a80-0202-11e9-9361-5cf480b9fcb8.gif)



- as you can see in the gif, this does not work, the emblem does not get shown. I also refreshed, restarted nemo, does not help.

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4, on Linux Mint 20 Cinnamon. Chowning to root adds the lock emblem above the file emblem I set myself:

![image](https://user-images.githubusercontent.com/21159972/85942384-2e4fc980-b929-11ea-981b-60e13529e7dd.png)

Setting multiple (too many) emblems doesn't overlap the lock emblem.
