### ISSUE TITLE
Text files from Windows marked as executable no matter what

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#2004]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * 32 or 64 bit: 64
 ```

**Issue**

Try as I might, files received from Windows via CIFS get marked executable if they are text files. None of the following fstab options, singly or in concert, seem to change that: `noauto`; `permissions`; `fmask=117`; `users`.

**Steps to reproduce**

Copy a .txt file from Windows to Mint via the network.

**Expected behaviour**

Text files from Windows should not be marked executable when they reach Mint, or at least there should be a way in which the user, via terminal and/or text editor if necessary, can stop the executable bit being set.

**Other information**

To my knowledge this has been a problem with Mint since at least Mint 16.
Surely many users are affected by this problem.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
