### ISSUE TITLE
[Feature request] "Recent folders"

### ISSUE THREAD

**Issue by The-Phi** [linuxmint/nemo#2006]
This feature is currently not present: A quick shortcut to see what are the recent folders visited. I think it could be quite useful for some.

**Comment by NikoKrause** [comment]
Which OS?

**Comment by The-Phi** [comment]
Arch Linux
Nemo version 4.04

**Comment by bastiOo** [comment]
indeed, Nemo lacks any modern search function.
Maybe it is better - and more efficient - to incorporate catfish or just adapt another filebrowser?

**Comment by 2635599** [comment]
> This feature is currently not present: A quick shortcut to see what are the recent folders visited. I think it could be quite useful for some.

as long as the folders can be opened from the recent list.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
