### ISSUE TITLE
Desktop Launchers starting terminal based applications in terminal fail to launch.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo#2009]
```
 * Nemo version 4.06
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0116 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.5 
  compat-v: 3.0 direct render: Yes 
 * 64 bit
 ```

**Issue**
.desktop launchers to start a terminal based application in a terminal are failing to launch. xsession-errors notes that `TERM environment variable not set.`

On attempting to define TERM the error changes to `top: failed tty get`

The same launcher works fine as a panel launcher or a menu launcher. 

**Steps to reproduce**

Create a simple desktop launcher and attempt to launch it

```
[Desktop Entry]
Name=top
Exec=/usr/bin/top
Comment=
Terminal=true
Icon=cinnamon-panel-launcher
Type=Application
```
Try again with this construction

```
[Desktop Entry]
Name=top
Exec=env TERM=xterm-256color /usr/bin/top
Comment=
Terminal=true
Icon=cinnamon-panel-launcher
Type=Application
```

**Expected behaviour**
This launcher construction should just work.

**Other information**
Forum thread 
https://forums.linuxmint.com/viewtopic.php?f=208&t=283883

**Comment by smurphos** [comment]
***Workaround***

This works fine as a desktop launcher, albeit the create launcher dialog doesn't recognise the command as valid.

```
[Desktop Entry]
Name=top
Exec=gnome-terminal -e "sh -c /usr/bin/top"
Comment=
Terminal=false
Icon=cinnamon-panel-launcher
Type=Application
```

**Comment by severach** [comment]
My problem is single quotes. I changed my command to use double quotes and now it works. Might be the same problem in #2039.

Create a launcher with `medit 'foo bar'`. In the old version this opens "foo bar". In the new version this opens "foo".

**Comment by smurphos** [comment]
It looks like this issue is simply that the Terminal=true flag is being ignored for desktop launchers.

'''[Desktop Entry]
Name=top
Exec=gnome-terminal -e top
Comment=
Terminal=false
Icon=cinnamon-panel-launcher
Type=Application'''

'''[Desktop Entry]
Name=top
Exec=gnome-terminal -e top
Comment=
Terminal=true
Icon=cinnamon-panel-launcher
Type=Application'''

Both work just fine.

'''[Desktop Entry]
Name=top
Exec=top
Comment=
Terminal=true
Icon=cinnamon-panel-launcher
Type=Application'''

Fails.

**Comment by smurphos** [comment]
Fixed in master by https://github.com/linuxmint/nemo/commit/359197b041c40d1c9591623b6989d0bfa61cfd8b
