### ISSUE TITLE
Using Del-key or moving files crashes Nemo

### ISSUE THREAD

**Issue by Swaphelaer** [linuxmint/nemo#2010]
```
 * Nemo version (nemo --version)
4.0.6
 * Is issue with desktop or windowed nemo?
windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.1
 * Graphics hardware *and* driver used
NVIDIA Corporation GM206 [GeForce GTX 960]
Native Driver 390.77
 * 32 or 64 bit
64
 ```
**Issue**
Pressing the Del-key to delete multiple selected files crashes Nemo.
It does delete the files tho'
Similar for moving files/subdirs.

**Steps to reproduce**
Open a folder with subfolders.
Open the subfolder by using the arrow (so it shows it in tree format)
Pick multiple files
Press the Del-key.
It doesn't happen every time but a bit randomly, but at least within a few tries.

**Expected behaviour**
Delete the files and reflect that in the filelisting.
Or moving the files as requested.

**Other information**
Three logged instances in syslog when using Del-key :
nemo[26012]: segfault at 30 ip 00007f7b33ea9b8d sp 00007ffd4af21510 error 4 in libgtk-3.so.0.2200.30[7f7b33b6a000+6f1000]
nemo[25755]: segfault at 30 ip 00007f4ca8f3bb8d sp 00007ffca48034e0 error 4 in libgtk-3.so.0.2200.30[7f4ca8bfc000+6f1000]
nemo[25755]: segfault at 30 ip 00007f4ca8f3bb8d sp 00007ffca48034e0 error 4 in libgtk-3.so.0.2200.30[7f4ca8bfc000+6f1000]

When moving files/subsdirs : 
nemo[497]: segfault at 30 ip 00007f02a1f3eb8d sp 00007fff260a2c10 error 4 in libgtk-3.so.0.2200.30[7f02a1bff000+6f1000]

**Comment by Swaphelaer** [comment]
Moving files to another folder yields this in a terminal-window (where i started nemo from to check for messages) :

(nemo:1501): Gtk-CRITICAL **: 18:58:16.330: ../../../../gtk/gtktreeview.c:6678 (validate_visible_area): assertion `has_child' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.


** (nemo:1501): CRITICAL **: 18:58:16.330: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed
sys:1: Warning: ../../../../gobject/gtype.c:4265: type id '0' is invalid
sys:1: Warning: can't peek value table for type '<invalid>' which is not currently referenced

**Comment by Swaphelaer** [comment]
Moving a file 1 subdir up gives :

** (nemo:1148): CRITICAL **: 19:00:41.865: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed

** (nemo:1148): CRITICAL **: 19:00:41.865: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed

**Comment by mtwebster** [comment]
Closing this, as it seems quite similar to #2150 (and the warnings above are the same), which was just fixed.  I'll re-open this later if necessary.
