### ISSUE TITLE
nemo-emblems build: No module named 'distutils.core'

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo#2011]
```
 * nemo-emblems-4.0.2
 * Ubuntu 19.04 disco
 * python3.7
 * python3-distutils: 3.7.1-1ubuntu4
 ```

**Issue**
....
....
........................................... BUILDING: nemo-emblems
....
....
 dpkg-buildpackage -us -uc -ui -i -I --build=binary --build=binary -j1
dpkg-buildpackage: info: source package nemo-emblems
dpkg-buildpackage: info: source version 4.0.2
dpkg-buildpackage: info: source distribution stable
 dpkg-source -i -I --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
debian/rules: 5: debian/rules: %:: not found
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.6 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils.core'
E: pybuild pybuild:338: clean: plugin distutils failed with: exit code=1: python3.6 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p "3.6 3.7" returned exit code 13
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 25
debuild: fatal error at line 1182:

**Steps to reproduce**
debuild -i -I --no-sign --build=binary -j1

**Other information**
I suspect a confusion between python3.6 & python3.7: Ubuntu disco ships with both releases, but:
- nemo-emblems seems to be built with python3.6
- python3-distutils release is 3.7.1-1ubuntu4

**Why not build with the latest python3 available locally, namely here python3.7?**

**Comment by leigh123linux** [comment]
You filed the bug against the wrong package.

https://github.com/linuxmint/nemo-extensions/issues
