### ISSUE TITLE
Crash when renaming directory to 2018

### ISSUE THREAD

**Issue by brmmm3** [linuxmint/nemo#2013]
```
 * Nemo version 4.0.6
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - Mint Cinnamon 19.1
 * Graphics hardware *and* driver used
00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)
 * 64 bit
 ```

**Issue**
In Pictures folder I wanted to create a directory named 2018. After entering RETURN Nemo crashes.

**Steps to reproduce**
Happens always.

**Expected behaviour**

**Other information**

**Comment by 2ramiro** [comment]
I was able to reproduce the error on a different fresh installed system also , the folder where this happens is on an network share , the path is smb://server/temp/geschichte%20Baltikum%20Dokumente on the other pc it is mounted as  /media/tempordner and the same thing happens .

**Comment by digitalcoyote** [comment]
Any chance this is related to #1981 ? I am encountering this issue, but it seems to affect renames as a whole and mainly in folders in any view with many files in a single folder (3,000+ pictures in the file in question )

**Comment by 2ramiro** [comment]
I think it is related , i have also many files in the folders where i have the crashes ,on folders with not so many files i don't have any problems.

**Comment by xenopeek** [comment]
Looks to have been solved in linked issue.
