### ISSUE TITLE
[Feature Request] Need more zoom options between 200% and 400%

### ISSUE THREAD

**Issue by catthou** [linuxmint/nemo#2014]
```
 * Nemo version (nemo --version): nemo 4.0.6
 * Is issue with desktop or windowed nemo?: Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 19.1
 * Graphics hardware *and* driver used:  eVGA GeForce 460 SE, driver version 390.77
 * 32 or 64 bit: 64bit
 ```

**Issue**
I think there should be more zoom levels between 200% and 400%. 200% zoom is my default in nemo thumbnail view because I can't actually discern what's in the thumbnail at smaller zoom levels on my 22" 1080p monitor. I would like to be able to zoom in more on some folders, but zoom jumps immediately to 400%, the max size. It would be nice to have at least one extra zoom level between, at 300%, or maybe even two or three, and possibly one larger.

**Steps to reproduce**
Drag the zoom slider, on the right side of the status bar, up and down; it just immediately from 200% zoom to 400%.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
