### ISSUE TITLE
Root nemo ignores 'noauto', causing stalls

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#2016]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64.
 ```

**Issue**

When run as root, nemo triggers mount requests on all network drives (or all those in fstab), *ignoring* the 'noauto' flag for those drives in fstab. This failure to honour the 'noauto' flag causes severe problems - please see #1950.

**Steps to reproduce**

Have several network shares. Have them be off-line. Run nemo as root (say via a non-root Nemo window).

**Expected behaviour**

No stalls, or at least not long ones; nemo should not mount all network drives, willy-nilly.

**Comment by CottonEaster** [comment]
Ah, it is possible that the problem owes to my using, in fstab, `x-systemd.device-timeout` instead of `x-systemd.mount-timeout`.

**Comment by xenopeek** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
