### ISSUE TITLE
If overlay scrollbars are disabled, root nemo ignores that fact

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#2017]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64.
 ```

**Issue**

When run as root, nemo uses overlay scrollbars, even though I have disabled overlay scrollbars in the system settings.

**Steps to reproduce**

Settings -> Effect -> disable overlay scrollbars; open Nemo as root; hover over a scrollbar.

**Expected behaviour**

I expect root-nemo to honour the system setting.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
