### ISSUE TITLE
deja-dup integration in nemo

### ISSUE THREAD

**Issue by paolostivanin** [linuxmint/nemo#202]
Hello,
i would like to know if it is possible to have the deja-dup integration into the Nemo file manager (like Nautilus).
Thanks!

**Comment by rik-shaw** [comment]
Need to check these out, but there are some nemo actions that have been created to integrate deja-dup with nemo: https://ejjohnson.net/restore-files-directly-from-nemo-and-nautilus/

The direct link to the github repo for the deja-dup nemo actions is here: https://github.com/erickj/nemo-actions

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by avLrrakzA2xRJ4VjIgRk** [comment]
almost 5 years, any update guys?

**Comment by leigh123linux** [comment]
This needs to be done as an extension or something, try filing the issue against nemo-extensions.
