### ISSUE TITLE
New Features I'd Like To See In Nemo

### ISSUE THREAD

**Issue by 2635599** [linuxmint/nemo#2021]
Mint Cinnamon 19.1 Tessa 64 Bit

AMD FX 6300, Asus 970 Gaming/Aura, Samsung 120 Gig 850 EVO, 16 Gig DDR3, 
USB 3.0 Card, AOC 29" Ultra Wide At 2560x1080.
SATA 500 & 500 Gig Hitachi drives, USB 3.0 1 TB WD & 2 TB Seagate Expansion

1. when you chose "open each folder in its own window" that we keep the "open in new tab" option instead of it being removed from the rightclick context menus. 

2. have the ability to combine open windows into one tabbed window. via drag like you do in your browser.

3. have the horizontal alignment of icons fixed so if one row is say 12 icons across so is every row beneath it.

4. the ability to backup my settings in nemo. by this i mean bookmarks, per-folder view settings, sidebar settings, etc....

5. the option to have the last open nemo window(all tabs)reopen on startup.

6. have the ability to rightclick anywhere and create a link / shortcut, not just the ability when you rightclick an item.

7. "create launcher here" added to folders not just the desktop, so we don't have to add a special action for it. 

8. keep all items on the rightclick menu when the icons on the desktop are hidden.

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by 2635599** [comment]
this should of stayed open for others to comment on.

**Comment by 2635599** [comment]
OPEN THIS THREAD NOW!!!!
