### ISSUE TITLE
Nemo File will not show/recognize .desktop files when in sym link folder

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/nemo#2026]
```
 * Nemo version (nemo 4.0.6)
 * Is issue with desktop or windowed nemo?  Not sure, but Files app is where the issue shows up
 * Linux Mint 19.1 Cinnamon
 * Virtualbox Mac OS X nvidia
 *  64 bit
 ```

**Issue**
When you create a symbolic link to a folder, Nemo File will not show/recognize .desktop files as applications, thereby treating them as ordinary files.

From Terminal create a sym link in Home Folder:
**ln -s /usr/share/applications  Applications**

Open Nemo File browser and navigate to Applications
.desktop files show as ordinary files.

**Comment by xenopeek** [comment]
This is basically another example of #1130. It comes down to how Nemo currently treats .desktop files: they are treated as special files only if they are trusted. .desktop files. If their path is a standard system directory they are automatically trusted and for other paths the .desktop files needs to be made executable to be trusted. See also #1404 as how .desktop files are treated is desirable to be changed.
