### ISSUE TITLE
SFTP to link-local IPv6 address

### ISSUE THREAD

**Issue by frost13it** [linuxmint/nemo#2028]
```
 * Nemo version: 4.0.6
 * Distribution - Mint 19.1 Cinnamon
 * 64 bit
 ```

**Issue**

When I trying to open an SFTP connection to IPv6 link-local address e.g.
```
sftp://user@[fe80::705e:df2b:4695:ae58%enp5s0]
```
I get following message: "Error: No hostname specified"

**Expected behaviour**

Connection is opened fine, just like via command-line OpenSSH client:
```
$ sftp user@[fe80::705e:df2b:4695:ae58%enp5s0]
Connected to fe80::705e:df2b:4695:ae58%enp5s0.
sftp>
```

**Comment by leigh123linux** [comment]
This is a gvfs issue, see https://bugzilla.gnome.org/show_bug.cgi?id=604116
