### ISSUE TITLE
Search features

### ISSUE THREAD

**Issue by gc-group** [linuxmint/nemo#2029]
```
 * Nemo version nemo --4.06
 *  **windowed nemo**
 * Distribution - Mint 19.1
 * 64 bit
 ```

**Issue**
Hello, I have an idea that will make Nemo even better. 
For convenient work in the file Manager is often required to search for files. There are situations when there are a lot of these files (a large period of time or a lot of files of different formats: doc, pdf, etc.). In GNOME, there are different kinds of sorting when searching: date, file type, last modified, last used, part of name, full text.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
