### ISSUE TITLE
Nemo does not display the coverart embedded in audio(mp3) as thumbnails

### ISSUE THREAD

**Issue by ajiteshmadai** [linuxmint/nemo#203]
I have installed cinnamon - nemo  on ubuntu 12.10 through the ppa.
AS the title says Nemo does not display the coverart embedded in mp3 as thumbnails for audio mp3 and even m4a files.
Thumbnails for all other file types are shown properly.

**Comment by Vahan86** [comment]
@ajiteshmadai, is this sill an issue for you with Nemo 3.0.6?

**Comment by Po2le** [comment]
I am facing this issue with nemo 3.2.2. 

I would label this a regression since this used to work until Linux mint 17.3 (not sure which nemo version was used back then)

**Comment by leigh123linux** [comment]
nemo requires gstreamer1-plugins-ugly to be installed to display embedded mp3 coverart thumbnails.

**Comment by Coeur-Noir** [comment]
What else ?
https://discourse.ubuntubudgie.org/t/nemo-and-music-files-no-pictures/3467
And same today in UbuntuBudgie with Nemo 4.4.2

**Comment by smurphos** [comment]
@Coeur-Noir - see https://github.com/linuxmint/nemo/issues/2280 
You need to install a compatible thumbnailer - Totem ships with one.
