### ISSUE TITLE
Pressing backspace in file open dialog does not open parent directory

### ISSUE THREAD

**Issue by dmatic** [linuxmint/nemo#2031]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? Windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): mint 19.1 cinnamon
 * Graphics hardware *and* driver used: nvidia gtx 770, driver nvidia 390.77.0ubuntu0.18.04.1
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Pressing backspace in file open dialog does not open parent directory. In previous versions of nemo (which was used in linux mint 19.0) pressing backspace lead to parent directory

**Steps to reproduce**
Go to File->Open in any program (xed, firefox, libreoffice writer...). This opens standard "Open File" dialog. Press backspace and nothing happens

**Expected behaviour**
Pressing backspace should open parent directory, this was the behaviour until linux mint 19.1

**Other information**
Linux mint 19.0 was upgraded to linux mint 19.1 using upgrade manager.

**Comment by xenopeek** [comment]
The mentioned programs use the Gtk file chooser. This is not provided by Nemo but is part of the Gtk toolkit. Upstream issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/1302
