### ISSUE TITLE
Intermittent failure to copy .icm files

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#2033]
```
 * Nemo version (nemo --version) 4.0.6
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: Intel UHD 620 (Kabylake) 3.0 Mesa 18.0.5.
 * 32 or 64 bit: 64
 ```

**Issue**

Sometimes attempts to copy icm files fail.

**Steps to reproduce**

The problem is intermittent. I tried to copy various .icm files - sometimes together, sometimes singly - from USB to my local drive, or from one part of my local drive to another, or from network to local drive. Sometimes the copy failed. Sometimes the failure takes the form of hung nemo progress windows. At other times, nothing at all sees to happen. The local folders at issue varied but included my desktop.

**Expected behaviour**

The copy should work.

**Other information**

I tried to reproduce on a virtual machine with a fairly fresh install of Mint 19.1 but I could not reproduce the problem. Disabling my firewall did not help. No systemd services reported as failed and network shares were (otherwise) working (and as I said it was no only the network that was affected). PCmanFm was able to copy the files without incident.

I could supply one the files.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
