### ISSUE TITLE
Change "My Computer" in left pane to "Files" or "Computer".

### ISSUE THREAD

**Issue by rjrich** [linuxmint/nemo#2035]
```
 * Nemo version 4.0.6
 * Is issue with desktop or windowed nemo: Desktop, I think.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 19.1
 * Graphics hardware *and* driver used: Nvidia GTX 1080Ti latest Linux driver
* 32 or 64 bit: 64 bit
 ```

**Issue**
I do not like the heading "My Computer" in the left-hand pane. I prefer a different heading such as "Files" or just "Computer". Could you please change this? Thank you.

**Steps to reproduce**
Opening Nemo.

**Expected behaviour**
Would like to see just "Files" or "Computer" rather than "My Computer".

**Other information**
N/A

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
