### ISSUE TITLE
Change folder color only for Mint-Y and Mint-X?

### ISSUE THREAD

**Issue by JousNL** [linuxmint/nemo#2037]
```
 * Nemo version 4.06
 * Desktop
 * Mint 19.1 Tessa
 * Graphics hardware *and* driver used: Geforce GTX 770. Driver version 415.25
 * 64 bit
 ```

**Issue**
'Change folder color' works only with Mint-Y and Mint-X icons. When I change the icons to Adwaita or any other preinstalled icons the option disappear. Even when I install another icons their is no option to change the colors. It works only with Mint-Y and Mint-X.

Should it work for other icons or only for Mint-Y and Mint-X icons?

**Comment by xenopeek** [comment]
This only works for Mint-Y and Mint-X, as these icon themes come in multiple color variants (e.g, Mint-Y-Aqua, Mint-Y-Blue ...).
