### ISSUE TITLE
Adjusting desktop icon grid seems multiply broken

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#2038]
```
 * Nemo version (nemo --version) 4.0.6
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used Intel UHD Graphics 620 3.0 Mesa
 * 32 or 64 bit 64
 ```

**Issue**

Trying to increase the vertical gap between my topmost icons and the top of the screen produces strange effects and prevents achievement of that goal. That is: dragging the slider for vertical spacing in the 'increase' direction seems to _decrease_ the spacing after a while; the pointer and the blob on the scroll bar end up far from each other; at no point do I manage to much increase the vertical space between my top-most icon and the top of the screen.

**Steps to reproduce**

See video here: https://app.box.com/s/ka4qq8jy4cus8167qlf2bdo8eqrwraw5. (The video is longer than it shoud be. The cause of that is the bug that prevents the recorder from stopping without Raising Elephants.)

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
