### ISSUE TITLE
Some desktop links are broken with the cinnamon nemo 4.0.6+tessa update

### ISSUE THREAD

**Issue by donnsd** [linuxmint/nemo#2039]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - Mint19.1
 * Graphics hardware nvidia 
 * 64 bit
 ```

**Issue**
Some desktop links are not resolved.  The issue seems to be a ' in the file name.  The desktop shortcuts are wine programs.  They were created from the start menu.
Cinnamon nemo version 4.0.3+tessa works fine.
I've attached a screen shot with the error message.  That is about the best I can do at this point.

https://imgur.com/a/2r9frSc

Thanks,
Don

**Steps to reproduce**
![screenshot from 2019-01-17 15-46-59](https://user-images.githubusercontent.com/24989463/51357945-0989ce00-1a76-11e9-9b59-a5650133b010.png)

![screenshot from 2019-01-17 15-49-26](https://user-images.githubusercontent.com/24989463/51357811-6d5fc700-1a75-11e9-9978-5af8869f5b75.png)
 

I did a fresh install of 19.1, keeping my existing /home stuff.
I then installed all updates except cinnamon-nemo. So using v4.0.3+tessa.
Everything fine.
Install cinnamon-nemo v 4.0.6+tessa, restart system, and problems.  The desktop shortcuts stopped working if there is a ' in the name.

**Expected behaviour**

**Other information**

**Comment by xenopeek** [comment]
Can you add the contents of a desktop file that has this issue? Right-click the file and from the context menu select Open With > Text Editor. Or if not shown choose Other Application and then find the Text Editor there.
