### ISSUE TITLE
Is it possible to add such functionality to the file manager Nemo like Dolphin?

### ISSUE THREAD

**Issue by 4i4obengy** [linuxmint/nemo#2040]
I will try to explain the problem and I hope I am clear. My English is not very good: It is very important for me to be able to search by keyword in docx files. For example, by writing the word "cat" to the search engine and showing me all the docx files in whose text this word has. So: For now Dolphin KDE file manager on Linux Mint KDE does this job perfectly. Unfortunately, you quit KDE. My question is whether it is possible to add such functionality to the file manager Nemo of the Cinnamon? I would like to work with the latest Linux Mint, but now I'm forced to stay at 18.3 KDE.

**Comment by 2635599** [comment]
actually searching by file extension would be a great feature. i've made a few search system wide for a specific file type and it would of been great to be able to narrow the search by searching a key phrase within a specific file type. also you might want to take look at the available search options in windows explorer, cause i know you will find nemo extremely lacking in this area.

**Comment by eli-schwartz** [comment]
1) please fix the issue title to be more descriptive of the issue. It's not important to know that you have a question, it's a lot more important to know that the question is requesting full text search.

2) This could be implemented using e.g. https://wiki.gnome.org/Projects/Tracker/WhatIsTracker (also used by nautilus), although personally I'd prefer such functionality to be an optional addon and not running by default...

**Comment by leigh123linux** [comment]
@eli-schwartz Turn it on

https://github.com/linuxmint/nemo/blob/master/meson_options.txt#L13

**Comment by eli-schwartz** [comment]
So is the OP's nemo package not compiled with tracker support? But the OP claims to be using Linux Mint.

As for enabling it in Arch -- seems like nemo depends on tracker-sparql-1.0, Arch only has tracker-sparql-2.0 since late 2017, I probably failed to get it working then forgot it existed.

**Comment by jazzpaul69** [comment]
full text search would be a real game changer in terms of productivity with linux mint. imho this is something than any user coming from windows explorer would expect out of the box. this would boost productivity much more than the latest mint 20.1 features such as favorites.

**Comment by mtwebster** [comment]
Content search is implemented in nemo 5.0.*
