### ISSUE TITLE
Nemo crashes intermittently when deleting / moving files in a List

### ISSUE THREAD

**Issue by shamoi** [linuxmint/nemo#2041]
```
 * nemo 4.0.6
 * Both windowed and non-windowed
 * Distribution - Linux Mint 19.1
 * GeForce GTX 550 Ti - 390.87
 * 64 bit
```

**Issue**
When the default view is set to " List View ", if the user deletes or moves files from a folder, nemo crashes intermittently.

**Steps to reproduce**
1- Set Nemo to use " List View " as its default view.
2- Boot Nemo.
3- Reach any folder containing a couple of files.
4- Reveal it's files using the tree view.
5- Select and delete or move every files / folders of that folder.
6- Notice that Nemo crashes.

**Expected behaviour**
Nemo should not crash when deleting / moving files or folders when the default view is set to " List View ".

**Other information**
[Trace log](https://termbin.com/15a2)
[Crash dump](https://github.com/linuxmint/nemo/files/2772816/crash.tar.gz)

**Comment by ShrekSWFL** [comment]
Same issue, and man it's annoying!
 Same Nemo 4.0.6
 Same Mint 19.1
 But I have an Nvidia GT 730

**Comment by MilamberValheru** [comment]
Same issue for me!
Same Nemo 4.0.6
Same Mint 19.1
I am using 3 different computers, all the same problem (using Kernel 4.20.0, gfx is Intel) 
It also happen when moving directories using "Edit" -> "Move To ..." Crash after succesful move, if the source directory is still in tree view

**Comment by alekssaul** [comment]
Same issue, Nemo 4.0.6 on Arch linux, Cinnamon 4.0.9

**Comment by momo42** [comment]
I'm also affected (Mint 19.1, Nemo 4.0.6)

**Comment by Marc3001** [comment]
Same here with Nemo 4.0.6 on Mint 19.1 and cinnamon 4.0.9
Each time I try to move file from a nemo window to an other, all windows just close once file is sucessfully moved.

**Comment by shamoi** [comment]
Strangely enough, this issue stopped occuring after migrating from an HDD to an SSD.

**Comment by jessigbeatty** [comment]
Still encountering this issue, hoping for some fix or update!

System specs:
Linux Mint 19.1
Cinnamon 4.0.10
Nemo 4.0.6
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
  Device-2: NVIDIA GM108M [GeForce 940M] driver: N/A

**Comment by Petebacher** [comment]
Same issue here...

Linux Mint 19.1
XFCE 4.12
Nemo 4.0.6
Graphics: Intel 3rd Gen Core processor Graphics Controller

**Comment by mtwebster** [comment]
Closing this, as it seems quite similar to #2150, which was just fixed.  I'll re-open this later if necessary.
