### ISSUE TITLE
Mnemonic for "Replace" button is missing from dialog

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/nemo#2046]
```
nemo 4.0.6
windowed
Arch 64
 ```

**Issue**
Mnemonic for german replace (Ersetzen) is missing.
![bildschirmfoto vom 2019-01-21 18-43-52](https://user-images.githubusercontent.com/3252315/51491707-791df700-1daf-11e9-96b9-30ad7e54f227.png)

**Comment by xenopeek** [comment]
It's the same in English:

![image](https://user-images.githubusercontent.com/21159972/85943676-cbaefb80-b931-11ea-9aa9-1cbd5a1e9aee.png)

Notice how the Replace / Ersetzen button is the default highlighted button. Pressing Enter will active it. Does it need a mnemonic?
