### ISSUE TITLE
[Feature Request] sort desktop icons beginning top right of screen

### ISSUE THREAD

**Issue by bastiOo** [linuxmint/nemo#2048]
I really miss the feature/option to auto-sort my icons from top right of the screen. I don't want to have them on the left side.

for several reasons:
- windows hide icons by default, because most open in top left ( I nearly never use fullscreen windows)
- I use a dock on the right side
- Linux menu is on the right side

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
