### ISSUE TITLE
Sorting by filenames - Incorrect order

### ISSUE THREAD

**Issue by forestfoxy** [linuxmint/nemo#205]
Create the following files:
00KB02
053FD
00714
04701
8189
BR

When the sort by name is pressed, the files appear in the order above. Clearly the order is wrong.

**Comment by Vahan86** [comment]
The issue is still existing in Cinnamon 3.0.7 (Nemo 3.0.6).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by AudioArchitect-R** [comment]
It appears as though this has been added as a feature request over here: [https://github.com/linuxmint/nemo/issues/578](url)

**Comment by xenopeek** [comment]
Closing as there is a feature request for this #578.
