### ISSUE TITLE
Nemo Crashes Randomly

### ISSUE THREAD

**Issue by rebeltaz** [linuxmint/nemo#2053]
```
 * Nemo version    -   3.6.5
 * Is issue with desktop or windowed nemo?   -    desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)    -   Ubuntu 18.04LTS
 * Graphics hardware *and* driver used
    -display                 
       description: VGA compatible controller
       product: Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:26 memory:d0000000-d03fffff memory:c0000000-cfffffff ioport:5050(size=8) memory:c0000-dffff

 * 32 or 64 bit   -  64-bit
 ```

**Issue**
Nemo crashes randomly. 

**Steps to reproduce**
This is not reproducible. It does not happen at any given time or under any given set of circumstances that I can tell. 

**Expected behaviour**
Nemo shouldn't be crashing

**Other information**
I will be happy to provide any information needed if you will tell me what you need and how to get it.

**Comment by leigh123linux** [comment]
nemo-3.6.x is EOL, update to nemo-4.0.x

**Comment by rebeltaz** [comment]
Any idea how to update to 4.0.x under Ubuntu 18.04? 3.6 is the latest version in the repository and when I try to install the http://ppa.launchpad.net/webupd8team/nemo/ubuntu PPA, I get this:

```
Err:8 http://ppa.launchpad.net/webupd8team/nemo/ubuntu bionic Release          
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                
E: The repository 'http://ppa.launchpad.net/webupd8team/nemo/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by eli-schwartz** [comment]
@rebeltaz you will need to ask the Ubuntu devs about that, no one here has any control over how Ubuntu packages anything. You may also wish to use a distribution with more up to date versions of software.

**Comment by leigh123linux** [comment]
@rebeltaz Try http://lmgtfy.com/?q=cinnamon-4+ppa

**Comment by rebeltaz** [comment]
> @rebeltaz Try http://lmgtfy.com/?q=cinnamon-4+ppa

I prefer https://lmddgtfy.net/?q=cinnamon-4%20ppa but thank you.
