### ISSUE TITLE
'Create new launcher here' does nothing

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2054]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel onboard, Mesa 3
 * 32 or 64 bit: 64
 ```
On both my main install of 19.1 and on a VM (Windows host) of Mint 19.1, 'Create new launcher here' (used on the desktop - does it work anywhere else?) does nothing and seems to generate nothing in the log.

**Comment by smurphos** [comment]
https://github.com/linuxmint/Cinnamon/issues/8275

**Comment by LinuxOnTheDesktop** [comment]
Ah yes. So this report is a duplicate - closing.
