### ISSUE TITLE
Nemo-Desktop in Unity-7 (Ubuntu 19.04)

### ISSUE THREAD

**Issue by khurshid-alam** [linuxmint/nemo#2055]
Hi,
Unity community developer here,

As nautilus > 3.30 is now uploaded in Ubuntu 19.10, it doesn't have the desktop any more. The alternate options are to use caja-desktop or  nemo-desktop keeping nautilus default file manger for now. Since `nemo-desktop` does not require any extensive patching I was asked to open a issue here. 

Will it be possible to accept few patches for Unity? Our only requirements are

1) A separate `change-background-unity.nemo_action.in` which will open `unity-control-center appearance` panel when user clicks "change background" from context menu.

2) Perhaps `NoDisplay=false` in nemo-autostart so that user can easily disable it.

I have created a patch for 1). I simply executed  `extract_action_strings` & `merge_action_strings`. Hope that will work for you.

**Nemo-Unity-Patch:** https://paste.ubuntu.com/p/4C9PkQSsxg/

Also I have a question. Does nemo actually draws the background ? In the absence of nautilus, unity-settings-daemon [draws](https://bazaar.launchpad.net/~khurshid-alam/unity-settings-daemon/media-keys-fix/view/head:/plugins/background/gsd-background-manager.c) the background (same as cinnamon-settings-daemon). If nemo doesn't, then we don't need to do anything in u-s-d. 

```
 * 3.8.x
 * Distribution - Ubuntu 19.04
 ```

Thank You.

**Comment by khurshid-alam** [comment]
@Ads20000 No it's needed. I am doing exactly what budgie is doing. However we don't have anything that can ship nemo action files. It is better if nemo does this than doing it ourselves.

**Comment by leigh123linux** [comment]
> @Ads20000 No it's needed. I am doing exactly what budgie is doing. However we don't have anything that can ship nemo action files. It is better if nemo does this than doing it ourselves.

I disagree, you can DIY it.
