### ISSUE TITLE
Use .hidden functionality provide by Glib and remove unrequired code from Nemo

### ISSUE THREAD

**Issue by timothyja** [linuxmint/nemo#206]
My patch that has been applied to Glib http://git.gnome.org/browse/glib/commit/?id=510ba9b4efe1813e24c6dfa7405c3547bf9efdd7
removes the need for file browsers to implement their own implementations of .hidden support. Therefore Nemo can remove its implementation of this as its now handled by Glib (as long as Mint is to use the Glib version that includes it of course)

The link to the Nautilus commit to remove the implementation is:

http://git.gnome.org/browse/nautilus/commit/?id=ace6d2c2170028148785f3fa87eedf883f20f1dd

**Comment by stefbon** [comment]
Very nice! Do you know the format of these ".hidden" files? Are they the same as ".directory" files used by Dolphin for example?

**Comment by icarter09** [comment]
Anyone have any update on this ticket?

**Comment by tarceri** [comment]
Please reopen. The code has not been removed from Nemo.

**Comment by tarceri** [comment]
Untested pull request https://github.com/linuxmint/nemo/pull/2384

**Comment by tarceri** [comment]
Thanks for reopening. My pull request was merged so you can now close it again as this is finally fixed! Thanks.
