### ISSUE TITLE
Clicking in a certain and fairly natural place within a desktop icon's bounding-box does not register

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2060]
```
 * Nemo version (nemo --version) 4.0.6.
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Onboard Intel Mesa 3
 * 32 or 64 bit: 64
 ```

**Issue**

There is a place within the bounding box - the rectangle drawable around the icon and its text - that does not register clicks. The 'dead zone' at issue is between the icon text and the icon image. I had wondered why some of my clicks did nothing and know I have discovered why.

Image of the deadzone (sorry for poor quality; I had to take it on a phone):

![image](https://user-images.githubusercontent.com/47056543/52589099-ef090180-2e35-11e9-98a0-158a782caf14.png)

Note: the icon/file is called 'error' (because it has to do with one of various problems I encounter on Linux).

**Steps to reproduce**

Have desktop icon. Click in vertical space between text and image. I have the problem on my main Mint install and on a VM of Mint (and that VM has a different kernel and at least somewhat different themes).

**Expected behaviour**

Clicking in this space should register. For: it's what one expects; one can click in the deadzone accidentally and thus fail to achieve what one wants; I see no point in disallowing the click.

**Other information**

Perhaps I should stress that I click the deadzone, when meaning to select the icon, approximately once or twice a day.

EDITED to make a few small changes.

**Comment by LinuxOnTheDesktop** [comment]
Can you reproduce this, devs? If you can, do please try to fix. For, surely many users will be irritated by this problem every day.

**Comment by smurphos** [comment]
The issue is reproducible and new in Nemo 4.0.x.

Also has an unpleasant visual side-effect of the hover effect being briefly dis-applied if you move the mouse between icon and label. This also applies to icon-view in the File Manager as-well as the desktop.

**Comment by LinuxOnTheDesktop** [comment]
@smurphos Is there a workaround by any chance, please?

**Comment by LinuxOnTheDesktop** [comment]
I find that in the Cinnamon **alpha** (Cinnamon 4.0.10), and across different icon sets, the issue is harder to trigger (yay!) but still present.

**Comment by LinuxOnTheDesktop** [comment]
I take it that this has yet to be fixed in the beta.

**Comment by cyan-lime** [comment]
Recorded a short GIF to show the issue more clearly. This is something that's always been a bother for me when I've used Cinnamon. It occurs both on the desktop and in Nemo itself in the 'icon view' mode.

![Peek 2020-04-22 12-35](https://user-images.githubusercontent.com/54386705/79934581-3c4f1d00-8496-11ea-9480-a6dfa038afc8.gif)

**Comment by LinuxOnTheDesktop** [comment]
Does this problem owe to Nemo, as against to gtk (or some such)? If the former, there seems nothing to delay a fix (well except, at the moment, the pandemic). If the latter: well, Mint 20, which will have refreshed software stacks, is coming up . . @mtwebster, can you clarify, please?

**Comment by xenopeek** [comment]
Thanks @cyan-lime for the helpful recording.

This isn't reproducible for me on Linux Mint 20 Cinnamon on the desktop or in Nemo with Icon View so looks to have been solved with that version.

I could reproduce it in Nemo with Compact View: there is some space between the icon and the text to the right of it that when moving the mouse cursor over it does the same as in the recording. But that is a different observation, if it should be expected to behave differently, from this issue.

**Comment by LinuxOnTheDesktop** [comment]
@xenopeek xenopeek: surely what your assiduous testing reveals is indeed another version of this same problem. For, what is the problem with the 'compact view' that you describe, if not - to quote the title of this issue, 'Clicking in a certain and fairly natural place within a desktop icon's bounding-box does not register'? If nonetheless you think the problem sufficiently novel to warrant its own issue, then perhaps you should open a new issue for it.



surely what you say about that other problem - with Nemo in compact view - shows that other problem to be a variant upon this problem. That is, that problem with compact view

**Comment by LinuxOnTheDesktop** [comment]
I find that the problem still exists on Mint 20.1.

Can a Mint developer put some pressure on upstream - if it is an upstream problem - or else fix it? It's pretty desperate that _icons can't be clicked_ (or not easily / always clicked)!

**Comment by LinuxOnTheDesktop** [comment]
The problem persists in Mint 21.1.

**Comment by LinuxOnTheDesktop** [comment]
I wonder whether Mint 22 fixes this problem.
