### ISSUE TITLE
Long time to load all video files

### ISSUE THREAD

**Issue by boskobs** [linuxmint/nemo#2061]
```
 * Nemo version: 4.0.6
 * Issue is with windowed nemo
 * Mint 19.1
 * Graphics hardware AMD HD6850, default open source driver
 * 64 bit
 ```

**Issue**
I have one folder with 320 video files. In the old version they would instantly appear with all the thumbnails and appropriate sorting, but in the new version they take their time popping up one by one (almost 2 seconds).

**Steps to reproduce**
Open a folder with ~320 video files, and the files take a bit of time to all appear.

**Expected behaviour**
Open a folder with ~320 video files, and all files appear instantly.

**Other information**
This has been present ever since I upgraded to Mint 19.1.
Compared to Nemo from Mint 19, this one takes a long time to display all files in a folder.

**Comment by xenopeek** [comment]
Thumbnail handling was improved for Nemo 4.6.4 release. I think this should be fixed. If any is still affected by this please retest on Linux Mint 20 Cinnamon.
