### ISSUE TITLE
Bookmarks column should not allow moving folders or files. It is dangerous.

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/nemo#2063]
I wanted to bookmark **/usr** folder in Nemo. By accident I dropped it over **/etc** which was also in bookmarks (I was logged in as root because I needed to fix somethings). Needless to say LM pretty much crashed. Luckily, after panicking and then thinking about it, I powered it down and mounted LM as another storage device on Ubuntu and from terminal, manually moved **/usr** back to **/**

The bookmarks panel should only be for Bookmarks; and not moving folders or files around. If you drop a folder over another bookmarked folder, it  should just add it as a bookmark below that one. Not move the folder inside the other.

At the very least, prompt the user if they do this. Such as: Do you mean to move folder XXX into folder YYY?

**Comment by leigh123linux** [comment]
Perhaps you should take more care when using root perms.

**Comment by wyattbiker** [comment]
A regular user folder can also be moved by accident and mess up your day. This is not a root issue although I was pointing out the extreme case. We need to think of end users if we want Linux to be acceptable as end users. Dragging and dropping the folder in bookmarks is too easy to do. Please reopen ticket for proper discussion instead of bland answer blaming the user. Thanks
