### ISSUE TITLE
tracker 2.0 API is not supported

### ISSUE THREAD

**Issue by leio** [linuxmint/nemo#2065]
```
 * Nemo version 4.0.6
 * Distribution - Gentoo
 * 64 bit
 ```

**Issue**

Tracker API 2.0 is unsupported

**Steps to reproduce**

Try to compile nemo on a system with tracker-2 or newer with `-Dtracker=true`. It'll fail configure.

**Expected behaviour**

tracker-2 works

**Other information**

It is suprising that after all this time nemo still doesn't support tracker-2.0 API. Should tracker support be hard-disabled and not provided as an option, given how unloved it seems?

**Comment by leio** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/gnome-extra/nemo/files/tracker-2.patch fixes the build for me; runtime completely untested by me

**Comment by leigh123linux** [comment]
If you want it please submit a pull request.

**Comment by leio** [comment]
Why close unresolved issues?

**Comment by leigh123linux** [comment]
Submit a pull request if you want it!!

https://github.com/linuxmint/nemo/pulls

**Comment by leigh123linux** [comment]
> Why close unresolved issues?

Are you to lazy to submit it?

**Comment by leio** [comment]
With such an attitude, most definitely lets say I'm too lazy.

I maintain tracker downstream, and merely had to make some software like nemo work with a newer version, so that I wouldn't break it. I have no interest in nemo itself whatsoever. I even provided the link to a patch I'm using 10 months ago. A PR to me would mean I actually tested it at runtime. Though our users seem to have been, in terms of not filing any issues downstream.

So, no, I don't want it. You should though. Otherwise distributions keep patching your software or decide it's too badly maintained to keep it packaged.

**Comment by leigh123linux** [comment]
Linuxmint, Archlinux, Debian and Fedora don't enable it.
I have zero interest in doing runtime testing as tracker hogs my cpu and spams the logging.

@mtwebster @eli-schwartz @maxyz Are you interested in this untested patch?

**Comment by clefebvre** [comment]
Well it is a build option we provide, so technically yes, personally I'd consider this a bug.

The patch is also tiny and whatever runtime testing is involved, it can't be worse than a build failure.

@leigh123linux you're probably reacting to "suprising that after all this time" and "given how unloved it seems". "lazy" and "if you want it" surely won't help either though.

I've no interest in this personally, but I agree it is a bug and we should either support tracker 2, or remove that option entirely.

**Comment by leio** [comment]
I didn't even remember what I wrote 10 months ago. Sorry. There was a question too though - `Should tracker support be hard-disabled and not provided as an option, given how unloved it seems?`. So yes, please either fix the option or remove it. In Gentoo we expose the option to the user, they can decide if they want it or not.

**Comment by clefebvre** [comment]
Thanks @leio, we'll probably remove it.

**Comment by eli-schwartz** [comment]
I have... vague memories that tracker was even an option in the first place, and never enabled it in my distro because we were too new!

I don't recall anyone ever trying to submit a bug report asking for me to enable it, so I'm not sure anyone especially misses it. Given no one seemed to be enabling it, I guess it was in sufficiently low demand that it's fine to remove it... I certainly won't be the person to campaign for it to be re-added, nor to maintain the feature to ensure that it works.

This resolution seems fine to me, I guess.
