### ISSUE TITLE
Videos filmed by same device randomly fail generating a thumbnail 

### ISSUE THREAD

**Issue by hutber** [linuxmint/nemo#2066]
```
 * 3.8.6v
 * Desktop
 * Mint 19
 * Nvidia-Driver-390
 * 64-bit
 ```

**Issue**
Currently some video files display thumbnails, others do not.
All videos were filmed by the same device.
I have cleared .cache/thumbnails
All videos play perfectly

Videos from screenshot below:
20190213_105424.mp4 = 2.5gb
20190213_105336.mp4 = 19.7mb
![image](https://user-images.githubusercontent.com/1344898/52904322-21de3b80-3222-11e9-8d8d-939e93a186ed.png)

**Steps to reproduce**
All videos were filmed with Samsung Galaxy 9, in  H264
Store some videos files in your file system and go to view them in nemo
![image](https://user-images.githubusercontent.com/1344898/52904353-e09a5b80-3222-11e9-9504-4989ca498f8a.png)

**Expected behaviour**
All files have thumbnails

**Other information**

**Comment by RafaMartorell** [comment]
I solve this annoying problem
deleting the file xplayer.thumbnailer from the folder / usr / share / thumbnailers
and after this install totem
sudo apt install totem *
Curiously, with Totem installed, the thumbnails have worked again.

**Comment by leigh123linux** [comment]
The issue is in the thumbnailer not nemo.
