### ISSUE TITLE
Double-click on executable file doesn't launch if there is a hidden file in the directory and view-hidden-files is off

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/nemo#2069]
```
nemo 4.0.6
Windowed nemo
Kernel: 4.15.0-45-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 Desktop: Cinnamon 4.0.9 
Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic 
64 bit
 ```

**Issue**

I have a script file 'something.sh' with execute permission, in a directory/folder.
- If there is no hidden file in the directory, double-clicking on the script file icon launches the script.
- If there IS a hidden file (say, .htaccess) in the directory, and nemo is set to "view hidden files", double-clicking on the script file icon launches the script.
- If there IS a hidden file in the directory, and nemo is NOT set to "view hidden files", double-clicking on the script file icon does nothing, it doesn't launch (it should).

**Comment by BillDietrich** [comment]
Recently saw this problem again, and the "double-clicking doesn't work" behavior persisted in Nemo until  closed all Nemo windows and re-opened one.  Somehow it got into "double-click doesn't do anything" mode.  I still could right-click on files and select "Open".

**Comment by DanielBonnery** [comment]
Hi,
this problem is a real one.
I have some apps that open some specific files (.tex <- texmaker, .R <- Rstudio). I double click them, nothing happens, I have to do "right click", "open with" (the default app is not listed then) "other app", click on the right app and "apply". This is a nuisance.

**Comment by xenopeek** [comment]
I tried reproducing this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. I put a executable test.sh script file in a new directory and put a .nobody hidden file in the same. Tried a few ways as described above but double-clicking the test.sh script file keeps prompting me what to do with it. Also when I switch behavior to always run executable text files it runs each time. Moving the test.sh file up to my home directory (filled with hidden files and directories) doesn't make a difference.

If any are still affected by this issue could you please retest with Nemo 4.6.4. And in that case, is it reproducible with the minimum test I described above—one script file and one dot hidden file in a new directory—or do other things play into being able to reproduce this.
