### ISSUE TITLE
File-open dialogues: some icons do not appear until moused-over

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2070]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel onboard - UHD Graphics 620 - Mesa 3, on a ThinkPad
 * 32 or 64 bit: 64
 ```

**Issue**

In Xed or SublimeText and possibly other programs, opening the file-opening window leaves some icons - I am unsure what determines which; it seems random - leaves some icons (in that window) unpainted until one mouses over the icons.

**Steps to reproduce**

Open a file-opening window in either Xed or SublimeText or quite possibly other applications. Scroll down a bit. Look for missing icons.

**Expected behaviour**

Obviously, the icon should appear before mouse-over.

**Other information**

I had this problem before I upgraded my Mesa stack (from one version of Mesa 3 to another version of Mesa 3). I have it now that I have upgraded that stack.
I would supply a video, but I believe that the inbuilt video recorder still crashes the computer.

Kernel 4.18 - but I've had the problem on 4.20 too.

**Comment by JosephMcc** [comment]
This has been brought up a bunch of times. Nemo has nothing to do with this. Those dialogues are provided by the toolkit used for the app. In this case Gtk. You need to report the bug to them.

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thank you. In short: the gtk people say Mint needs to update.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Here is some detail.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your words prompted me to report the bug against gtk.  The response I got [there]((https://gitlab.gnome.org/GNOME/gtk/issues/1691) was to this effect: Mint needs to update its version of gtk. For, here is that response.:

> [. .] You are using a GTK version (3.22) that is too old and not supported anymore by GNOME developers. GNOME developers are no longer working on that version, so there will not be any bug fixes by GNOME developers for the version that you use.
> You may need to upgrade your Linux distribution to obtain a newer version of GNOME/GTK. Please feel free to reopen this bug report if the problem still occurs with a supported version of GTK, or feel free to report this bug in the bug tracking system of your Linux distribution if your distribution still supports the version that you are using.

**Comment by leigh123linux** [comment]
@LinuxOnTheDesktop  I can reproduce with gtk3-3.24.1

**Comment by LinuxOnTheDesktop** [comment]
@leigh123linux : I've added that datum to the gtk ticket. Thanks.

**Comment by leigh123linux** [comment]
@LinuxOnTheDesktop  I added a comment as well.

**Comment by LinuxOnTheDesktop** [comment]
This is now [fixed upstream](https://gitlab.gnome.org/GNOME/gtk/issues/1691#note_542538).

**Comment by LinuxOnTheDesktop** [comment]
A _workaround_ that _fixes_ the problem - while Mint waits to receive the upstream fix - is to add the following to `/etc/environment`.

```
# Workaround for https://gitlab.gnome.org/GNOME/gtk/issues/1691
GTK_DEBUG=no-pixel-cache
```

Or so I imagined, and I am testing it, and it seems to work.
