### ISSUE TITLE
[Feature Request] Could You Add Securely Wipe To Nemo Trash

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/nemo#2072]
Hi,

Could you add securely wipe option to Nemo's trash.

![nemo-trash](https://user-images.githubusercontent.com/1300133/53298283-99245880-383c-11e9-89b9-1e8b3a51e62e.png)

**Comment by lbrunkho** [comment]
+1 Just add a front end support for srm, could even be a plugin

**Comment by clefebvre** [comment]
@mtwebster
