### ISSUE TITLE
Crashes if Search for Files is empty

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/nemo#2073]
```
LM 19.1
Cinnamon 4.0.9
Nemo
4.0.6
 ```
**Issue**
Crashes if  Search for Files is empty

**Steps to reproduce**
From Nemo menu:

- Go > Search For Files
- leave text search box empty and press Enter

Will quit/crash Nemo with no message

**Expected behaviour**
Should do nothing!

**Comment by shamoi** [comment]
[gdb_trace.log](https://github.com/linuxmint/nemo/files/2909592/gdb_trace.log)

**Comment by Butterfly1984** [comment]
Confirmed in LM 19.2 Cinnamon
Nemo 4.2.2

Ctrl+F to search, then pressing enter while there's no text filled in, crashes Nemo

**Comment by LuvIsBadToTheBone** [comment]
confirmed.
when hit in enter it crashes

linux mint cinnamon 19.2
nemo 4.2.2

coredump
https://pastebin.com/CMwimQeJ
