### ISSUE TITLE
[Feature Request] Show path above each left and right panel.

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/nemo#2074]
Please add the path on each left and right panel. Attached is sample screen shot of Pathfinder (Mac OS X) as an example on how it could look (see https://cocoatech.com/#/ for some good ideas.)  

**Other information**
![image](https://user-images.githubusercontent.com/930478/53452065-53a78d00-39ee-11e9-9be1-fe5fbe899006.png)

Also in ref: #513.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
