### ISSUE TITLE
.desktop launcher does not honor Path= statement

### ISSUE THREAD

**Issue by jjberk** [linuxmint/nemo#2078]
```
 Nemo version: 4.0.6
Cinnamon 4.0.9
Linux Mint 19.1 Cinnamon 64  bit
Kernel 4.15.0-45-generic
Graphics: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller rev. 09 (integrated on ASUS P8Z77-V Pro motherboard), driver asus_wmi,i915

**Issue**
Clicking on the desktop icon with the following .desktop file:

   [Desktop Entry]
   Name=Bkh
   Exec=/home/public/Documents/ACCOUNT/bkh.pl
   Comment=Boekhouding
   Terminal=false
   Type=Application
   Path=/home/public/Documents/ACCOUNT/

opens my (perl) script, but the current directory is my home directory.
It seems the Path= statement is not honored.

**Steps to reproduce**
Make a desktop launcher and look  at the working directory.

**Expected behaviour**
Execute the application with a working directory as specified in the Path statement.

**Other information**
The same .desktop file executes properly under Linux Mint 19 with Cinnamon 3.8.9, Nemo 3.8.6

**Comment by zorbakus** [comment]
Having the same issue with a portable program. It starts in the home directory, and creates its config files there, instead of actual path where the executable is.

[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=Powder Toy
Type=Application
Comment=Physics sandbox game
Categories=Game;Simulation
Icon=powdertoy.png
Exec='/home/username/Games/the-powder-toy/powder64'
Path=/home/username/Games/the-powder-toy

**Comment by xenopeek** [comment]
I retested this with Nemo 4.6.4 on Linux Mint 20 Cinnamon but can't reproduce it. Looks fixed.

I created a Test.desktop file on the Desktop and put this in it:
```
[Desktop Entry]
Name=Test
Exec=/home/username/Documents/test.sh
Terminal=false
Type=Application
Path=/home/username/Music/
```
Then I created the file `~/Documents/test.sh` with simply this in it:
```
#!/bin/bash
zenity --info --title "Test" --text "$PWD"
```
I made the .sh executable and then double-clicked the .desktop file (which ran after Nemo prompting me to trust it). It correctly popped a dialog showing `/home/username/Music` as the current directory—from the Path key in the .desktop file. Changing the Path key and re-running it shows the new directory.

If any are still affected by this please re-test on Nemo 4.6.4 with the above example so we can test the same way.
