### ISSUE TITLE
[Feature request] Add options to switch to using Microsoft WinXP-like and Win7/8.1/10-like Open..., Save as..., and browse UI-style dialog-windows&behavior

### ISSUE THREAD

**Issue by sahwar** [linuxmint/nemo#2081]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

[Feature request] Add options to switch to using Microsoft WinXP-like and Win7/8.1/10-like Open..., Save as..., and browse UI-style dialog-windows and behavior.

Like a collapsible Favorites in the side-menu, down position of (filename input), (select filetype), etc., to be able to select multiple files in Open... by holding the mouse and rectangular-selecting in the small space beside the icons (on the left/right), image/video-preview button, etc.

[https://imgur.com/gallery/YSebhk4](url)

**Steps to reproduce**

**Expected behaviour**

Add option in the Nemo Settings to choose from:

Style for Open.../Save as.../Browse... file-dialogs:
* (X) Nemo/Nautilus-style (DEFAULT)
* (X) Microsoft Windows XP-like style
* (V)  Microsoft Windows7/10-like style

**Other information**

**Comment by feren** [comment]
I'm pretty sure that's up to the Desktop Environment to decide what dialog program it uses for Open and Save/Save As dialogs, not the File Manager.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
