### ISSUE TITLE
[Feature Request] Make back command also open the previously opened folder

### ISSUE THREAD

**Issue by a-bentofreire** [linuxmint/nemo#2083]
Hi.
I often work with dual-panel, and many times I change the directory of the wrong pane during navigation.
To move back to the previous base folder, I press back button, but now I have to open all the sub-folders until I reach the previously open folder.

ex:  
On nemo addressbar, I have `/home/foo/anaconda3`.  
And on the folder tab, I have opened `lib/cairo`.  
Now I click on Documents. The addressbar becomes `/home/foo/Documents`.  
If I press `BACK`, the addressbar returns to `/home/foo/anaconda3`,
but I have to manually open again `lib/cairo`.

I use nemo the whole day, as well as the back command to return to the previous folder.  
This feature would be very helpful :-)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
