### ISSUE TITLE
Nemo actions not working inside the window

### ISSUE THREAD

**Issue by evandrocoan** [linuxmint/nemo#2084]
```
 * Nemo version (nemo 4.0.6)
 * Is issue with windowed nemo?
 * Distribution - Mint 19.1
 * 64 bit
 ```

**Issue**

I created the following action menu on `/home/linux/.local/share/nemo/actions/sublime.nemo_action`:
```
[Nemo Action]
Active=true
Name=Edit with Sublime Text Vanilla
Comment=Edit with Sublime Text Vanilla
Exec=/home/linux/Downloads/run_as_user.sh sublime_vanilla /usr/bin/subl -n
Selection=notnone
Extensions=none,nodirs;
Icon-Name=sublime-text
```

It only shows up and works fine on the XFCE4 desktop:
![image](https://user-images.githubusercontent.com/5332158/54091626-fe119f80-4360-11e9-94e5-c2ae0678f36f.png)

But it does not show up by any means, when I am inside nemo, even after restarting the computer:
![image](https://user-images.githubusercontent.com/5332158/54091649-3c0ec380-4361-11e9-8c9d-c2ab64d41594.png)

**Comment by mtwebster** [comment]
I'm not really certain why this might work on the desktop, but not a window - possibly because of your extensions criteria - no extension allowed, and not a directory, and maybe the desktop file has no extension? (I can't tell).  Regardless, the following might be a better approach:

```
[Nemo Action]
Active=true
Name=Edit with Sublime Text Vanilla
Comment=Edit with Sublime Text Vanilla
Exec=/home/linux/Downloads/run_as_user.sh sublime_vanilla /usr/bin/subl -n %F
Selection=notnone
Mimetypes=text/plain;
Icon-Name=sublime-text
```

Note, I tested this using just `/usr/bin/subl -n %F` as the Exec argument.  If it fails with your particular exec line, let me know.

**Comment by evandrocoan** [comment]
Thanks for the fast response!

I used your example, and it worked!

Then, I changed it a little like this:
```
[Nemo Action]
Active=true
Name=Edit with Sublime Text Vanilla
Comment=Edit with Sublime Text Vanilla
Exec=/home/linux/Downloads/run_as_user.sh sublime_vanilla /usr/bin/subl -n %F
Selection=notnone
Extensions=nodirs;
Icon-Name=sublime-text
```

And it still working! But now, I can see `Edit with Sublime Text Vanilla` everywhere, as is files with no extension, `.zip` files, etc. Exactly what I needed!

**Comment by ThomIves** [comment]
I ran into this problem, came here, and found that on my linux mint system, I needed to use 
`Icon-Name=sublime_text`
and NOT
`Icon-Name=sublime-text`
