### ISSUE TITLE
Icon view in any folder containing image files: rename terminates

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2086]
```
 * Nemo version (nemo --version) 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: intel UHD 620 Mesa 3.
 * 32 or 64 bit: 64
 ```

**Issue**

In and only in folders containing image files, and only when Nemo's 'view' is set to icon, and only when image previews are enabled, if I rename a file (by clicking on it and then choosing 'rename' in the context menu), then _the rename finishes immediately after any key-press_. That is, it is as if I entered one character - for the new file name - and then pressed <return>. But I did not press return.

**Steps to reproduce**

I can reproduce the problem, on my main installation, in any folder that contains >0 image files (and where a preview is displayed). On a version of Mint I have in a VM (on a different machine), I could not reproduce the problem.

**Expected behaviour**

I should be able to enter >1 character for the new file name - as indeed I can if no preview is displayed.

**Other information**

The aberrant behaviour does not occur in PcManFM, even when thumbnails are displayed.

I do not see anything relevant in my logs.

I have the accessibility option to ignore fast duplicate keypresses enabled but, even when I turn it off, I see the strange behaviour.

I found nothing in the official Mint forum about the problem, nor in Reddit's /r/linuxMint.

Linux kernel 5.0.

**Comment by xenopeek** [comment]
I tried to reproduce this on Linux Mint 20 Cinnamon. I copied a bunch of jpeg images into a new directory through other program, had Nemo set to generate thumbnails and default icon view. Tried some things but with the steps given above isn't reproducible.

If you are still affected by this issue, would you please retest with Linux Mint 20 Cinnamon (if only from the LiveISO) and can you recall if there was any difference in Nemo configuration between your hardware and VM install? Like did you have have certain Nemo plugins added to the hardware install that you didn't have on the VM install.
