### ISSUE TITLE
Desktop icons disappearing after switching a multi-panel mode on desktop.

### ISSUE THREAD

**Issue by sleeply4cat** [linuxmint/nemo#2087]
```
 * Nemo 3.6.5
 * Cinnamon 3.6.7
 * Ubuntu 18.04.2
 * GT1030, nvidia-driver-390
 * 64 bit
 ```
**Issue**
After pressing F3 on the desktop, all the icons are blinking or disappearing until rebooted.

**Steps to reproduce**
1. Minimize all the windows
2. Press F3 a few times

**Expected behaviour**
Nothing

**Other information**
Tried to relaunch Nemo and --replace cinnamon with no result.

.xsession-errors:
```
**
ERROR:nemo-window-manage-views.c:489:nemo_window_slot_open_location_full: assertion failed: (target_window != NULL)
** Message: 23:44:10.082: nemo-desktop: session is cinnamon, establishing proxy
```

**Comment by xenopeek** [comment]
Retested this with Nemo 4.6.4 on Linux Mint 20 Cinnamon but can't reproduce. If any are still affected by this please retest with that version and if reproducible also share what actions and extensions you have enabled  in Plugins—shouldn't but might play a role.

**Comment by sleeply4cat** [comment]
Can't reproduce on Ubuntu 20 @ Nemo 4.4.2; still reproducible on Ubuntu 18.04 @ Nemo 3.6.x.
I think, it's ok to close the issue. Ty.
