### ISSUE TITLE
Cannot type file path address on Open File dialog boxes

### ISSUE THREAD

**Issue by evandrocoan** [linuxmint/nemo#2090]
```
 * Nemo version (nemo 4.0.6)
 * Is issue with windowed nemo?
 * Distribution - Mint 19.1
 * 64 bit
 ```

![image](https://user-images.githubusercontent.com/5332158/54400691-d3964e00-46a2-11e9-9a18-6663a4dd649c.png)

### Steps to reproduce

1. Set nemo as your default file 
1. Open Sublime Text
1. Press Ctrl+O
1. Try to type/paste some file path address

**Comment by clefebvre** [comment]
Hi @evandrocoan, this is part of GTK so it's upstream from us. I'm not sure why you don't see an edit button there.. you should.. 

![image](https://user-images.githubusercontent.com/1138515/54401460-a86e2780-46bf-11e9-9e28-3aa40851eab1.png)

In any case, as a workaround, you can use CTRL+L to make the path entry appear.
