### ISSUE TITLE
Open Terminal Here does nothing, i.e., do not open the terminal

### ISSUE THREAD

**Issue by evandrocoan** [linuxmint/nemo#2091]
```
 * Nemo version (nemo 4.0.6)
 * Is issue with windowed nemo?
 * Distribution - Mint 19.1
 * 64 bit
 ```

**Issue**

Open Terminal Here does nothing, i.e., do not open the terminal:
![image](https://user-images.githubusercontent.com/5332158/54402004-02afbe00-46a9-11e9-84c3-37f2dd18a443.png)

**Comment by evandrocoan** [comment]
Doing `sudo apt-get install gnome-terminal -y` fixed the problem: https://github.com/linuxmint/nemo/issues/1406

But I my default terminal is `xfce4-terminal`, then, I created this entry:

**/home/linux/.local/share/nemo/actions/open_in_terminal.nemo_action**
```
[Nemo Action]
Active=true
Name=Open in Terminal
Comment=Open in Terminal
Exec=xfce4-terminal --working-directory="%P"
Selection=none
Extensions=nodirs;
Icon-Name=xfce-terminal
```

Now my custom entry works:
![image](https://user-images.githubusercontent.com/5332158/54404205-82418b00-46b1-11e9-8d1f-644c364459e6.png)

However, the old entry which only opens `gnome-terminal` still there. How can I remove it?

**Comment by evandrocoan** [comment]
I managed to set the old entry to use `xfce4-terminal` with
```
gsettings set org.cinnamon.desktop.default-applications.terminal exec 'xfce4-terminal'
```

**Comment by LinuxOnTheDesktop** [comment]
Perhaps it is worth adding the following here.

On Mint 20, Nemo's terminal icon does nothing if one has xfce4-terminal set as the default terminal _and_ `~/.local/share/applications/xfce4-terminal.desktop` exists. The solution is to delete the latter file. However, I did have it for a reason . .
