### ISSUE TITLE
Feature Request: Ability to Show/Hide Nemo Actions based on script

### ISSUE THREAD

**Issue by zpangwin** [linuxmint/nemo#2092]
```
 * Nemo version (nemo --version) nemo 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1 Cinnamon x64
 * Graphics hardware *and* driver used N/A
 * 32 or 64 bit 64-bit
 ```

**Feature Request**
Would like to request the ability to make Nemo actions be displayed conditionally (e.g. run a script/command and based on the results, then determine whether or not to display the action in the context menu).

As this check should only happen by the user-initiated event of right-clicking on a file/folder, I don't think there would be significant performance overhead here unless the user did something stupid in their script (at which point, it's their fault/their problem), which to be fair, they are perfectly capable of doing today after the command is invoked.

**Expected behaviour**
In the examples below, I assume the "Test" parameter gives a script or command location which is called and then based on the exit code returned by the script/command, used to determine if the Action is to be displayed in the context-menu or not. In this way, it becomes possible to have an action that will only be displayed if a folder contains certain things or meets some other condition (maybe only displays when I am the owner / not the owner / etc).

There are a lot of potential uses for this. Here a couple to illustrate:

#### Example 1 - VLC - queue folder action

Nemo Action file - only display on folders that contain music files
```properties
Active=false
Name=Queue Music in VLC
Comment=Queue all music files in VLC
Exec=/usr/bin/vlc-queue-folder.sh %P
Selection=s
Test=/usr/bin/is-audio-dir %P
Extensions=any;
```

/usr/bin/vlc-queue-folder.sh
```bash
#!/bin/bash
# Note: This is a sample and has not been fully tested
if [[ -d "$1" ]]; then
    exit -1;
fi
# Requires a user setting in VLC to reuse running instance (otherwise will open new instance)
# 1. Tools > Preferences > Interface tab
# 2. Check "Allow one Instance" and "Enqueue items into playlist in one instance mode"
# 3. Save
# 4. Close and restart VLC
vlc --playlist-enqueue "$1"
```

 /usr/bin/is-audio-dir.sh
```bash
#!/bin/bash
# Note: This is a sample and has not been fully tested
if [[ -d "$1" ]]; then
    exit -1;
fi
cd "$1";
# -n == test for non-zero length string
if [[ -n $(find . -type f -regex ".*/.*\.\(flac\|mp3\|ogg\)") ]]; then
    exit 0;
else
    exit -1;
fi
```

#### Example 2 - Using a GUI client for Git
I am using [the Mono version of Git Ext v2.5](https://github.com/gitextensions/gitextensions/releases/tag/v2.51.05) in example (setup instructions [here](https://github.com/gitextensions/gitextensions/wiki/How-To:-run-Git-Extensions-on-Linux) for anyone interested), but easily adjustable to other Git/Hg clients or for other dialogs from the same client

Nemo Action File - only display on (or under) Git repo folders
```properties
Active=false
Name=GitExt Commit
Comment=Launch the Commit/Diff dialog of GitExtensions v2.5 (or similar)
Exec=/usr/bin/git-ext-commit-from-folder.sh %P
Selection=s
Test=/usr/bin/is-in-git-dir.sh %P
Extensions=any;
```

/usr/bin/git-ext-commit-from-folder.sh
```bash
#!/bin/bash
# Note: This is a sample and has not been fully tested
if [[ -d "$1" ]]; then
    exit -1;
fi
cd "$1";
REPO_TOP=$(git rev-parse --show-toplevel 2>/dev/null);
if [[ "$1" != "$REPO_TOP" ]]; then
    cd "$REPO_TOP";
fi
#pass to mono and then to wherever you installed the extracted zip contents
mono "/opt/GitExtensions/GitExtensions.exe" commit &
```

/usr/bin/is-in-git-dir.sh
```bash
#!/bin/bash
# Note: This is a sample and has not been fully tested
if [[ -d "$1" ]]; then
    exit -1;
fi
cd "$1";
git rev-parse --is-inside-work-tree 2>/dev/null
exit $?
```

**Other information**
I might be interested in contributing if I get some time to learn to code base. I have never done any Linux software development though (aside from shell scripts). Seems the code base is in C and I'm a bit rusty so I would probably need to brush up there. Any good resources for a java developer interested in getting their feet wet in the Linux world (or with nemo in particular)?

**Comment by clefebvre** [comment]
https://github.com/linuxmint/nemo/pull/2056

**Comment by zpangwin** [comment]
Should have known you guys probably already thought of it :-)

Thank you!
