### ISSUE TITLE
Double click on blank area to go to the parent folder only works when some file/folder is selected

### ISSUE THREAD

**Issue by apandada1** [linuxmint/nemo#2095]
```
 * Nemo version (nemo --version) = 4.0.6
 * Is issue with desktop or windowed nemo? Windowed Nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) -  Mint 19.1
 * Graphics hardware *and* driver used - Intel HD graphics
This is from the output of `inxi -Fxz`
```
```bash
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Hewlett-Packard 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2) 
  v: 4.5 Mesa 18.2.2 direct render: Yes 
```
```
 * 64 bit operating system
 ```

**Issue**
I have checked the "Double-click on a blank area to go to the parent folder option". The feature only works when some folder or file in the directory is selected. Otherwise, nothing happens when I double click in the blank area.

**Steps to reproduce**
Open nemo>preferences> behavior and check "Double-click on a blank area to go to the parent folder". 
When nothing is selected, nothing happens when you double click in a blank area. When a file or folder is selected, is goes to the parent folder when double-clicked.

**Expected behaviour**
Nemo should go to the parent folder whether or not anything is selected.

**Comment by bagjunggyu** [comment]
I can confirm it since I have the same issue.

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon. Double-clicking blank space (after enabling) works to go up a directory regardless of whether a file is selected or not.

Note though that it currently doesn't work in List View, see #1516.
