### ISSUE TITLE
Nemo Actions - gsettings based conditions are not re-evaluated next time context menu is shown

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo#2097]
```
 * Nemo version 4.0.6
 * Is issue with desktop or windowed nemo? Both
 * Distribution - Mint 19.1
 * Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0116 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.2.8 
  compat-v: 3.0 direct render: Yes 

 * 64 bit
 ```

**Issue**

If a gsettings based condition is used to control presence of a action in the menu it does not re-evaluate the condition after the first time the context menu is shown. A nemo / nemo-desktop restart is required to update the visibility of the action.

As an aside the documentation for `gsettings <schema> <key> <key-type> <[eq|ne|gt|lt]> <value>` could do with improvement. Specifically that valid `<key-types>` are the single letters

b (for boolean)
y ( for byte)
etc as per https://developer.gnome.org/glib/stable/glib-GVariantType.html#GVariantType

**Steps to reproduce**
Try these simple actions intended to enable the slideshow if it is disabled and pause the slideshow if it is enabled and not paused. With a starting point of Slideshow Disabled and Not Paused note that after using the first action to Enable the Slideshow, Enable Slideshow still appears as a menu item, and Pause Slideshow does not appear. Nemo desktop has to be killed and restarted for the context menu contents to update.

```
[Nemo Action]
Name=Enable Slideshow
Comment=If the desktop background slideshow is disabled, enable it.
Exec=gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled true
Icon-Name=preferences-desktop-wallpaper-symbolic
Selection=none
Extensions=any;
Conditions=desktop;gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled b eq false;
```
```
[Nemo Action]
Name=Pause Slideshow
Comment=If the desktop background slideshow is enabled, pause it
Exec=gsettings set org.cinnamon.desktop.background.slideshow slideshow-paused true
Icon-Name=preferences-desktop-wallpaper-symbolic
Selection=none
Extensions=any;
Conditions=desktop;gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled;gsettings org.cinnamon.desktop.background.slideshow slideshow-paused b eq false;
```

**Expected behaviour**

For the gsettings condition to be evaluated everytime the context menu is opened.

**Other information**

**Comment by mtwebster** [comment]
This is because visibility is checked when the selection changes, not when the menu is opened (otherwise there'd be unacceptable delays when opening the menu).  This is common behavior for all menu item checks.  Try your test case above, but select a file item on the desktop (assuming you have them enabled) before right-clicking on the desktop again - the visible action does change.

The issue here is that for background-click items, particularly on the desktop, it's typical for the selection not to change, so this sort of thing occurs.  Ideally if the relevant gsettings key changes, visibility is re-checked, but I'll have to give some thought as to making this happen.

**Comment by smurphos** [comment]
Thanks @mtwebster - it is how you describe.
