### ISSUE TITLE
Feature Request: Location Entry option for Open File Dialog

### ISSUE THREAD

**Issue by Hukuta** [linuxmint/nemo#2098]
It is very convenient that you can paste the path to the folder from the clipboard. 
I do not understand why this Location Entry is not enabled by default. 
It is ok that it can be enabled by button:
![Selection_007](https://user-images.githubusercontent.com/3100053/54839870-6f900d00-4cd4-11e9-8316-23134a479852.png)

But i can't see such button when browser opens Select File(s) Dialog:
![Selection_006](https://user-images.githubusercontent.com/3100053/54839861-6bfc8600-4cd4-11e9-89b0-6000db77c9a3.png)

I found that you can use a Ctrl+L, but it's not obvious and need to press every time..

It would be great if the state of this field in Open File Dialog respect the state of Location Entry in nemo.

**Comment by JosephMcc** [comment]
People keep making requests from us for the open file dialog. We do not develop this. It has nothing at all to do with Nemo. Those dialogs are supplied by whatever toolkit is used to develop the app you are using.

In the dialog you show there which is the Gtk3 dialog, pressing Ctrl + L will show what you want.
