### ISSUE TITLE
Nemo 4.0.6 and Makululinux 15 LinDoz

### ISSUE THREAD

**Issue by 2635599** [linuxmint/nemo#2099]
this isn't actually an issue, but had no idea where to put it on github. i want to install and test makululinux 15 lindoz, but when i looked around the live key i noticed that nemo is 3.8.5, and the current version is 4.0.6. makulu devs say i can't update nemo without breaking the distro. i would like to know if they are correct or if there is an actual way of updating their version of nemo without breaking the distro. thanks in advance for any help with this.

http://www.makululinux.com/wp/lindoz/

**Comment by eli-schwartz** [comment]
Among other things, you'll need to have an updated libxapp, which other parts of cinnamon also use.

It's certainly not been tested to see if it works.

**Comment by 2635599** [comment]
well since cinnamon is the base and i know other file managers worj without issue including dolphin i think my work around is to install dolphin, set it to my liking, and use it like i am currently doing in mint cinnamon 19.1. thanks for the feedback, much appreciated.
