### ISSUE TITLE
[Feature Request] wipe files

### ISSUE THREAD

**Issue by seneq** [linuxmint/nemo#210]
It would be cool if there was a way to securely delete(wipe) a file/folder with nemo. Maybe use the shred functionality. Also this could be available only if running nemo with elevated privileges.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
