### ISSUE TITLE
FEATURE REQUEST: put a line between 'Delete permanently' and 'Restore'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2101]
```
 * Nemo version (nemo --version) 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel onboard
 * 32 or 64 bit: 64
 ```

**Issue**

The bin's context menu has the restore option right next to the delete permanently option. One mouse slip and . . boom. The same menu uses a separator line elsewhere. Why not put such a line between 'restore' and 'delete permanently'?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by LinuxOnTheDesktop** [comment]
Just now and for the nth time accidentally I clicked 'restore' rather than 'delete permanently'.

Would you consider merging a pull request that added a separator?

**Comment by LinuxOnTheDesktop** [comment]
Just now, yet again, I restored an item that I wished to delete permanently.
