### ISSUE TITLE
Dropbox interaction only works when opening the folder from the dropbox panel icon

### ISSUE THREAD

**Issue by Mela** [linuxmint/nemo#2102]
```
 * Nemo version: 3.8.6
 * windowed nemo
 * Distribution: Linux Mint 19, Cinnamon 64.bit
 * GeForce GTX 750, nvidia-driver-390
 *  64 bit
 ```

**Issue**
I'm using dropbox and have the nemo dropbox plugin installed and activated. Since some time (can't exactly pinpoint down when the problem first appeared) I only can access the dropbox context menu when opening a nemo window from the dropbox tray icon but not when I chose a dropbox folder from a bookmark. 

**Steps to reproduce**

Step 1: opening the dropbox folder from the tray icon. 
![Workspace 1_029](https://user-images.githubusercontent.com/361364/54970203-8c9d3800-4f81-11e9-9072-9c0266b9cbdf.png)

Step 2: Dropbox Icons are visible and context menu works as expected. 
![Camera Uploads_031](https://user-images.githubusercontent.com/361364/54970237-adfe2400-4f81-11e9-8da9-ad6fce2a362d.png)

Step 3: opening the same folder from a bookmark in the sidebar:
![Camera Uploads_032](https://user-images.githubusercontent.com/361364/54970298-e271e000-4f81-11e9-939d-6a0c8c9abb2d.png)

Step 4: Dropbox icons have disappeared and the context menu is gone except for the "move to dropbox" entry. 
![Camera Uploads_035](https://user-images.githubusercontent.com/361364/54970402-3bda0f00-4f82-11e9-8464-d6b6a760fef3.png)

**Expected behaviour**

Dropbox folders should be recognized by nemo regardless how they are accessed. 

**Other information**

**Comment by Mela** [comment]
I guess I found the problem: 
I moved my dropbox folder to a bigger hard drive and linked from the old directory to the new. The bookmark was set to the old directory not the new one. Nemo has trouble to recognise the old entries as dropbox folders because the files are physically on another hard drive. 

Still, nemo should be sophisticated enough to work around this.

**Comment by leigh123linux** [comment]
This is a user issue, closing as 'can't fix'.
