### ISSUE TITLE
Nemo closes unexpectedly

### ISSUE THREAD

**Issue by midnightflash** [linuxmint/nemo#2103]
```
 * Nemo version 4.0.6 
 * windowed nemo
 * Distribution - Arch uptodate Cinnamon Desktop
 * Graphics nvidia GeForce GTX 780 418.56-2
 * 64 bit
 ```

**Issue**
From here to then... after a bit of copying and shifting some files Nemo closes. From my sighting, when a file is not to be shown anymore in an open folder because of moving it anywhere or deleting it. The error came up some month ago... don't know why and when though.

**Steps to reproduce**
Use Nemo until it breaks again.

**Expected behaviour**
Nemo works rock solid and does not break when doing usual things.

**Other information**
Made a GDB dump this time...

[New Thread 0x7fffe10d6700 (LWP 17959)]

(nemo:4092): Gtk-CRITICAL **: 14:10:44.044: gtktreeview.c:6666 (validate_visible_area): assertion `has_child' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.

** (nemo:4092): CRITICAL **: 14:10:44.044: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed

(nemo:4092): GLib-GObject-WARNING **: 14:10:44.044: ../glib/gobject/gtype.c:4265: type id '0' is invalid

(nemo:4092): GLib-GObject-WARNING **: 14:10:44.045: can't peek value table for type '<invalid>' which is not currently referenced

Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b8bbf9 in gtk_tree_model_get_valist () from /usr/lib/libgtk-3.so.0
(gdb)

**Comment by midnightflash** [comment]
[Thread 0x7fffe23d1700 (LWP 21960) exited]

** (nemo:21749): CRITICAL **: 14:44:07.760: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed

(nemo:21749): GLib-GObject-WARNING **: 14:44:07.761: ../glib/gobject/gtype.c:4265: type id '0' is invalid

(nemo:21749): GLib-GObject-WARNING **: 14:44:07.761: can't peek value table for type '<invalid>' which is not currently referenced

Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b8bbf9 in gtk_tree_model_get_valist () from /usr/lib/libgtk-3.so.0
(gdb)

**Comment by shadow73s** [comment]
I don't know, if I have the same bug, but in my case crashes when moving files in the same Window.
It happens mostly.
If I move the files to other Window, it don't crashes.

**Comment by xenopeek** [comment]
Considering this is a year old observation without steps to reproduce, closing it for now. If any are still affected by this please retest with Nemo 4.6.4 / Linux Mint 20 Cinnamon.
