### ISSUE TITLE
Nemo doesn't start after changing configuration

### ISSUE THREAD

**Issue by jaheme127** [linuxmint/nemo#2105]
* Nemo version - 4.0.6
 * Window
 * Distribution - Mint 19.1
 * MESA DRI Intel Haswell Mobile
 * 64-bit

**Issue**

My Nemo didn't start anymore. (Only happens to one user - other user still got the nemo window)
I then fixed the issue by myself by starting issue with root and reactivate everything. Then start without root and activating everything again.

**Steps to reproduce**

Remove all extensions and entries for the context menu in Module configuration and restart.

**Expected behaviour**

Quick restart and a working version (or a message if some error occurs)

**Other information**

I had all (almost) plugins activated which I could install with synaptic. The only plugin I tried to use which was not in the repository was "RabbitVCS" which did not work because of other issues.

If you need a full list and cannot reproduce the issue I can give detailed information.

**Comment by xenopeek** [comment]
I retested this on Linux Mint 20 Cinnamon and with some work could narrow it down to the 3rd party plugin nemo-extension-fma. Steps to reproduce:

1. Install the package: `apt install nemo-extension-fma`;
2. In Nemo go to Edit > Plugins and disable the extension FMAMenuPlugin;
3. Restart nemo;
4. Try to open Edit > Plugins again and Nemo will segfault.

To get out of this either uninstall the package with `apt purge nemo-extension-fma` or re-enable all plugins with `dconf reset /org/nemo/plugins/disabled-extensions`.

For completeness sake these are all the Nemo packages (not installed by default on Linux Mint 20 Cinnamon) that I installed:

- nemo-audio-tab
- nemo-compare
- nemo-dropbox
- nemo-extension-fma **[Note 1]**
- nemo-filename-repairer
- nemo-font-manager **[Note 1]**
- nemo-gtkhash
- nemo-image-converter
- nemo-media-columns
- nemo-pastebin
- nemo-seahorse
- nemo-terminal

**Note 1:** nemo-extension-fma and nemo-font-manager come from the Ubuntu 20.04 LTS package base and are for an older Nemo version. I would generally not recommend to install these on Linux Mint 20.

**Note 2:** There are 3 more nemo packages that come from the Ubuntu 20.04 LTS package base and which are for an olde Nemo version, namely nemo-nextcloud, nemo-owncloud and nemo-python. These are not installable on Linux Mint 20.

I can't find where to report to issue upstream, if any know please take further action accordingly.
