### ISSUE TITLE
Some issues with nemo actions

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#2107]
nemo 4.0.6
issue in file manager issue
mint 19.1 latest
gfx 630 nvidia drivers
64 bit

Im working on a method to improve copying for myself, I have one php script and 2 nemo_action files, one for selecting files and the other for pasting them.

issue 1:
I used NEMO_ACTION_VERBOSE=1 nemo to debug,
inside the nemo_action script, in the Exec clause, when giving %P before %F it simply shows up as "command %P [filelist]" when you put  %P at the end it works as it should "command [filelist] [basedir]" I changed my script to support this, this way.

issue 2:
nemo_action1 is for selecting files, folders and making a list of them in my homedir (calls a php script)
nemo_action2 is for pasting somewhere then it may copy it there (that also runs the php script)

somehow, every time when I change directory and right click someplace empty, script 1 shows up in the menu not script 2, I first have to click a file then again in some empty place and then the menu shows option for script 2. If I dont have any file in the dir, I cant even do this. script 1 is 
Selection=notnone
Extensions=any;

script 2 is 
Selection=none
Extensions=any;

issue 3.

this is in nemo_action file
[Nemo Action]
Active=true
Name=SPECIAL_COPY_COMMAND paste
Exec=/home/x/SPECIAL_COPY_COMMAND paste %F
Terminal=true
Icon-Name=
Selection=none
Extensions=any;
EscapeSpaces=true
Quote=double

but it does not open the terminal window 99% of the time
Id really want it to open because the command can take long time to complete. When experimenting with Exec and other commands it mostly never showed terminal either, just occasionally for some reason it has showed up when the command failed.

I can post my 2 nemo actions and script for running, later, it is a php script with shebang as first line.

both commands now work for me it seems, but a terminal does not show the progress/output from the script.

*ok terminal seems to be working again.

**Comment by osmand** [comment]
wow mtwebster, did you just improve nemo because my post? (Im new to this :)

thanks

**Comment by xenopeek** [comment]
Issue 1 is fixed as per above.

Issue 2 isn't reproducible with Nemo 4.6.4 on Linux Mint 20 Cinnamon. I created script1.nemo_action and script2.nemo_action with the keys as shown above (adding keys `Name`, `Exec` and `Active` under section `[Nemo Action]`) and switching directories a number of times and in different ways, script2 always shows up when I click somewhere in empty space after switching. I tested in all 3 views. Should any still be affected by this issue please retest with latest version.

Issue 3 was noted above as working again so with that, closing this as solved.
