### ISSUE TITLE
Two 'main toolbars' when having two panes, then toggling 'view main toolbar'

### ISSUE THREAD

**Issue by bjd-pfq** [linuxmint/nemo#2109]
* Nemo version (nemo --version)
3.6.5

 * Is issue with desktop or windowed nemo?
Windowed nemo

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 18.3

 * Graphics hardware *and* driver used
 * 32 or 64 bit
Nvidia GS 1070; Nvidia 384.130

**Issue**
I usualy have a two-pane nemo application running. Main menu and main toolbar visible. The other day I toggled 'view > main toolbar' (to OFF). 
Then toggled it visible again. 
This time _each_ of the two panes had the directory name, breadcrumbs, the icons / compact   / list buttons, etc.  It all looked very crowded and not really helpful.  This must be a bug, no? I mean, toggling from state A to state B and back should leave me with state A, not state A'.

I remedied the situation by going single-pane, then split-pane again; that view then didn't have the double 'main toolbar's. (Of course I lost the focus of the directory that I had in the closed pane).

**Steps to reproduce**
See above under 'Issue'

**Expected behaviour**
See above under 'Issue'.

**Other information**

**Comment by smurphos** [comment]
I can reproduce this in Mint 19.1 with Nemo 4.0.6

**Comment by JosephMcc** [comment]
So can I.
