### ISSUE TITLE
xapp version

### ISSUE THREAD

**Issue by Sword-Destiny** [linuxmint/nemo#2111]
**Issue**

xapp version is too low on Ubuntu.

**Steps to reproduce**

meson build

**Expected behaviour**

**Other information**

meson.build:84:0: ERROR:  Invalid version of dependency, need 'xapp' ['>=1.4.0'] found '1.0.4'.

**Comment by leigh123linux** [comment]
This isn't a bug!, get the lazy packagers at Ubuntu to fix it.
