### ISSUE TITLE
q: who improves nemo where can I discuss some issues with them personally. I know you are not active at #linuxmint-dev.

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#2114]
title.

why should it be difficult to communicate with you?

if I knew the system, I would attempt to improve some basics that I personally want,
and these few basic improvements would make nemo much better than many other file managers, because as it is, it is as good or shitty as the windows file manager from 1995.

I think people are deliberately avoiding the topic.

**Comment by jaszhix** [comment]
Feel free to open an issue about the things that you would like changed, if it's not a duplicate and follows the [issue template](https://github.com/linuxmint/nemo/blob/master/.github/ISSUE_TEMPLATE.md). That's what this bug tracker is for, but it's not for complaining about how responsive people are on IRC. If everyone wanted to talk to developers personally, most of their time would be spent fielding bug reports/feature requests in an inefficient way.
