### ISSUE TITLE
the sorting icon triangle in nemo should be opposite

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#2116]
when sorting from in ascending order the triangle should be pointy at top, currently it is the opposite way.

**Comment by u2n** [comment]
This drives me crazy! The fix would be so simple. Please anyone give the pointer graphic location so I can reverse to match the rest of the Linux world (not the shrinking Windows world).

**Comment by xenopeek** [comment]
See comment from JosephMcc on the linked issue as for why Nemo won't go against convention and reverse the meaning of the sorting icon triangle.

▼ = regular sort: 1st sorted is a the top, 2nd sorted is below it and so on down the list
▲ = reverse sort: 1st sorted is at the bottom, 2nd sorted is above that and so on up the list

**Comment by amiga-500** [comment]
> See comment from JosephMcc on the linked issue as for why Nemo won't go against convention and reverse the meaning of the sorting icon triangle.
> 
> ▼ = regular sort: 1st sorted is a the top, 2nd sorted is below it and so on down the list ▲ = reverse sort: 1st sorted is at the bottom, 2nd sorted is above that and so on up the list

What baffles me is that 3 years hence and there is still no option in the preferences to just give the users a choice.
