### ISSUE TITLE
feature request, when copying files dont ask to replace if files are identical

### ISSUE THREAD

**Issue by osmand** [linuxmint/nemo#2117]
when copying files the copy dialog stops the whole process and waits all the time until the user responds,

even if the file is a 1 byte file.

for all the resources used in computers, I think it can check if the files are identical, just do md5 or something, or for parts of the file to see if the file is already identical then there is no need to ask for anything, and if the file sizes differ, just see the smaller one is an incomplete part of the other, just see if md5s are same for the length of the large file the size of the small file.

nemo even asks if you want to replace if the files are 0 bytes if I am correct. * yes it does

and also 

when asking if you want to replace the file, the skip button jumps around for every file depending on the length of filename because the dialog box is resized.

**Comment by jay-wilkinson** [comment]
But please make it OPTIONAL.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
