### ISSUE TITLE
remote host connection does not remember password ever

### ISSUE THREAD

**Issue by byteit101** [linuxmint/nemo#212]
I often connect to a remote sshfs server, and have noticed that nemo has no memory of passwords. When I connect to a sftp server, I enter my username and password, and hit "remember forever". however, if I unmount it and remount it, I am prompted again. same thing happens with the "remember for this session" option. it does not remember it past one mount.

**Comment by Redsandro** [comment]
One year later, and I have the same issue, most notably with samba shares.
_"Remember forever"_ forgets immediately.

**Comment by Vahan86** [comment]
@byteit101, is this still an issue for you with Nemo 3.0.6?

**Comment by byteit101** [comment]
Remember for this session appear to work on 3.0.6
