### ISSUE TITLE
Caret within the name of a desktop icon is hard to see 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2121]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

When I rename a desktop icon, the caret is (very) hard to see. Image:

![image](https://user-images.githubusercontent.com/47056543/56432887-ec5bda00-62c6-11e9-8835-2060aaaa2e78.png)

Note that the size of the image means that the caret is more visible than it actually is on my desktop. (The image is actual size, yet, I have HiDPI scaling turned out, with the result that the image pasted here is twice the size that I see.)
**Steps to reproduce**

Have icon on desktop. Start renaming it.

**Expected behaviour**

The caret should be more visible.

**Other information**

I changed desktop theme, border theme, icon theme and pointer theme. No such changes helped (though admittedly I did not try all possible combinations). Changing to a light background did not help either.

I have the problem on my main installation and also on a VirtualBox installation.

**Comment by smurphos** [comment]
As a temporary measure you can over-ride nemo's hardocoded theming for the desktop.

Create a '~/.config/gtk-3.0/gtk.css' file with the content

```
.nemo-desktop.view .entry,
.nemo-desktop.view .entry:active,
.nemo-desktop.view .entry:focus,
.nemo-desktop.view .entry:backdrop {
    caret-color: #000000;
}
```

Save. Alt-F2 to bring up the run dialog - run `pkill nemo-desktop`. If it doesn't restart itself Alt-F2 again and run `nemo-desktop`

**Comment by LinuxOnTheDesktop** [comment]
smurphos,

Thank you: that hack works (though were the caret just a little bit thicker then that too would be good).

Will a change a long these lines make it into Mint (well, Nemo) itself?

**Comment by smurphos** [comment]
> smurphos,
> 
> Thank you: that hack works (though were the caret just a little bit thicker then that too would be good).
> 
> Will a change a long these lines make it into Mint (well, Nemo) itself?

Try
```
.nemo-desktop.view .entry,
.nemo-desktop.view .entry:active,
.nemo-desktop.view .entry:focus,
.nemo-desktop.view .entry:backdrop {
    caret-color: #000000;
    -GtkWidget-cursor-aspect-ratio: 0.1;
}
```

Re making this default - I think the caret-color matching the text color should be default and likely an oversight on the part of the devs. I'll put in a pull request.

**Comment by LinuxOnTheDesktop** [comment]
Thank you. (I prefered a -GtkWidget-cursor-aspect-ratio` of 0.05.) Do please enter a pull request.

**Comment by smurphos** [comment]
> Thank you. (I prefered a -GtkWidget-cursor-aspect-ratio` of 0.05.) Do please enter a pull request.

0.05 seems to be default on my system across several themes. Not many themes set it explicitly but perhaps yours does set a smaller aspect ratio...
