### ISSUE TITLE
Add a Preview pane integrated in Nemo [Feature request]

### ISSUE THREAD

**Issue by Tyco72** [linuxmint/nemo#2122]
For many users it is essential to have a preview pane integrated in the right side of the file manager, to show a large preview for only the currently selected file.
A preview pane allows to use more efficiently the space in the window, showing much more files in the screen, without to fill up the space with previews of files which don't interest. 
It would avoid also the unwanted work in the background of generating/caching previews for all the images contained in the folder (which can be many hundreds of files and of large size).

I guess it would not a too big effort to add a preview pane, at least for photos and videos, because Nemo is already able to generate previews (as icons) for these file types. Consider that MS Window integrates a preview pane in the file explorer since the times of Windows 98. Here a sample pic, of what I mean:

![Preview_Pane_r](https://user-images.githubusercontent.com/47554612/56459326-3231a480-6392-11e9-981d-c5e972daa73e.jpg)

(Issue reported with Nemo 4.0.6 on Linux Mint 19.1 Cinnamon)

**Comment by folkertm** [comment]
I'm not sure @Tyco72 if does that work. The feature was already integrated in older versions of Gnome, e.g. in Fedora 20. But the algorithm had the problem described. The Photos app has the same problem. The higher the number of files and the larger a file the longer Gnome has worked in the background. If I understand you correctly, you can only preview the currently selected file. What if multiple files are selected?

**Comment by Tyco72** [comment]
Hi, thank you. When you select more files it should be not a problem. The preview pane would show the preview only of the last selected file. Anyway only one image at time would be cached.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Tyco72** [comment]
Thank you very much. I'm looking forward for this feature.

**Comment by JayBeeDe** [comment]
Hi,
I would also apreciate this very nice feature... For pdf files it is possible to use evince preview API. Or libreoffice can handle pdf as well as odt, etc. And what about audio/video files preview ? (too complicated for the moment I can admit it)

**Comment by pedroolmedo98** [comment]
I would be a wonderful feature.

**Comment by folkertm** [comment]
Let me write something about this wonderful feature. A field report with Fedora and Gnome. I know this feature was or is already implemented in Gnome and Nemo. But I have always had performance problems with it. My use case is simple, I have local folders with photos in different file sizes. The names of the files are autogenerated, as it is the case today with embedded operating systems for digital cameras. And the view or the view change on the camera is more performant, yes, much more performant than on Fedora with Gnome. When switching from one photo to another, it happens that Fedora/Gnome/Nemo gets stuck and does not return to normal operation. A switch to switch on/off the feature may be useful. But more important is a redesign to solve this performance problem.

**Comment by Jeremy7701** [comment]
Have you considered a dedicated photo management tool such as digiKam etc?

**Comment by ptandler** [comment]
Any update here? I just found [here](https://www.reddit.com/r/linuxmint/comments/caqq54/comment/etbprgj/?utm_source=share&utm_medium=web2x&context=3) that you can use the space key to open a preview as popup. This is already helpful, but

* is not mentioned in the help dialog with all keyboard shortcuts
* does not automatically update when I select another file

> Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.
> 
> For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

Is the list of feature request "that have been documented" and their status (e.g. position in roadmap) available somewhere?

**Comment by nd-** [comment]
I switched from Files (Gnome on Fedora) to Nemo, because Files is really too simple and limited.
Nemo is almost perfect for me, but this feature of a preview pane would be really awesome.

**Comment by Jeremy7701** [comment]
Nemo has many little-known features, some excellent but at least one "feature" is downright weird.
However, full user documentation would appear to be too time consuming.

**Comment by Dan-cer** [comment]
I'm very much interested in this feature too! I know the plugin Nemo-preview that is better than nothing.
However, instead of open an extra window for preview it should displayed in one of the existing double windows.
Thank you in advance for implementing it.
Quite a few other file managers have it already.

**Comment by fpsvogel** [comment]
I'd love to see this feature too. It would be more convenient than pressing Space on each image (or zooming in all the way for large icons) when working with large numbers of images.

**Comment by CyrilCommando** [comment]
I'd like this as well

**Comment by Jeremy7701** [comment]
I prefer the current set-up, since I mostly don't have double windows.
It would be nice to have scroll bars, although I appreciate that this might be difficult to implement.
For large numbers of images, it could be worth installing a photo manager - such as digiKam etc.

**Comment by jonathanschilling** [comment]
I would like to support this request as well. It would be hugely helpful for me to name scientific papers in PDF according to the actual paper title, because the filenames (as they come from the publisher) rarely align with the author name(s) and/or the paper title. This feature would allow to read author name(s) and paper title, while renaming the file in the left pane.

**Comment by lgcvsa** [comment]
Since I've switched to Linux Mint for most of my personal needs this year (all three of my primary use computers at home are now either Linux Mint Cinnamon or LMDE), I find that this is a feature that I desperately need to make my use of my Linux Mint systems more efficient, particularly on the Open File dialogue box when I am uploading a copy of an image I've saved to social media. I find that I frequently end up sharing the same images over and over, and then tend to get buried in my Downloads folder, with indecipherable names that I never can recall. So, i have to keep backing out of the Open File diagloue box, open the full file browser (which has full preview icons), navigate to my Downloads folder, find the file, then copy and paste the filepath.

It's honestly surprising to me that Linux Mint is still lacking this feature. I've been using Linux Mint since about 2011, but now it's my primary OS, as of 2025, so it's become more of a critical issue for me.

**Comment by Jeremy7701** [comment]
You don't need to put all your files in 'my downloads', other places are available.
You aren't restricted to only one nemo tab, you can have multiple nemo windows.

If I intend to keep badly named files, I either put them in a  named sub-directory or I rename them to something sensible.

Having a preview window wouldn't save me from testing lots of files until I found the right one.
But proper organisation allows me to go directly to the right file.

**Comment by lgcvsa** [comment]
> You don't need to put all your files in 'my downloads', other places are available. You aren't restricted to only one nemo tab, you can have multiple nemo windows.
> 
> If I intend to keep badly named files, I either put them in a named sub-directory or I rename them to something sensible.
> 
> Having a preview window wouldn't save me from testing lots of files until I found the right one. But proper organisation allows me to go directly to the right file.

Cool story, bro. Do you feel like senpai will notice you, now?

**Comment by CyrilCommando** [comment]
> Cool story, bro. Do you feel like senpai will notice you, now?

Yeah, I dunno what's up with him. He's militant against a preview window. Posting wherever, whenever someone mentions it

**Comment by Tyco72** [comment]
@lgcvsa @CyrilCommando 
This is unfortunately a common problem of the open source software. Even for widely diffused software, the developers implement only the features that they like. They don't care about what the many common users need or like. It is not a problem only of Linux. I am aware that they are the developers, they decide what to do with their time, but for widely used software it is not the right attitude. Especially for an OS that would like to be a universal alternative to Windows desktop.

**Comment by JosephMcc** [comment]
> Especially for an OS that would like to be a universal alternative to Windows desktop.

Have been part of the dev team for over a decade and have never heard a single member of the team say this is a goal. This is something spread by random people online. Probably because Mint is a pretty easy introduction to Linux for first timers.

**Comment by Tyco72** [comment]
@JosephMcc
Maybe it is not an official goal, but it is what they would like see to happen, since decades. Anyway, it is not happening not only because of the missing of several desired features, but because to replace Windows on desktops on large scale, it is necessary to be binary compatible with the Windows software and drivers. It is actually the goal of ReactOS, but I always wonder why it attracts few developers.
For basic usage (internet browsing+LibreOffice) Linux does its job. I use it to save PCs that can't install Win11 and otherwise would be thrown away.

**Comment by JosephMcc** [comment]
> Maybe it is not an official goal, but it is what they would like see to happen, since decades.

I was talking about Mint, not everyone.

>  It is actually the goal of ReactOS, but I always wonder why it attracts few developers.

Point made.

**Comment by kameshkotwani** [comment]
Is anyone still working on this feature?

**Comment by jonathanschilling** [comment]
I vibe-coded an initial prototype here, but I think it needs a lot of further work: https://github.com/jonathanschilling/nemo/tree/feature-preview-pane-2

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/pull/3650

**Comment by smoky-oni** [comment]
Still looking forward to this feature. Need it too fro .kra files, but, maybe the thumbnails can be inherited from installed programs the file is from or can be opened by (without actually opening in the program) to be viewed in nemo. 

> [#3650](https://github.com/linuxmint/nemo/pull/3650)

is this still a work in progress?
