### ISSUE TITLE
 Add "New folder with Selection" in context menu

### ISSUE THREAD

**Issue by uncertainquark** [linuxmint/nemo#2123]
GNOME's file manager has this excellent feature where after you make a selection of files, the context menu has the option to make a new folder with the selected items. Upon clicking it, the folder is asked to be named, the folder is then made and the selected files are put in it automatically.

![image](https://user-images.githubusercontent.com/22585732/56465697-fc87cc80-6420-11e9-9e4c-c086c28fbde6.png)

**How is this better than regular cut-paste?**
It is reducing the number of steps to achieve the same result. 

_Current behavior_
1. Select files
2. "Cut" them
3. Create new folder
4. Name the folder
5. Enter the folder
6. Paste the files

_Proposes behavior advantage_
1. Select files
2. Select "New folder with Selection" in the context menu
3. Name the folder
4. Hit Enter

That's it!

**Comment by pedro-augusto-santana** [comment]
Hi!
I've implemented this feature recently if you want to install and give it a try, https://github.com/pedro-augusto-santana/nemo_create_new_folder_with_selection

**Comment by icarter09** [comment]
@uncertainquark did the solution provided by @pedro-augusto-santana fix your issue?

**Comment by uncertainquark** [comment]
Hey, I'm no longer on Mint actually, so someone else will have to test it. Sorry.

**Comment by rafaelribeiroo** [comment]
> Hi!
> I've implemented this feature recently if you want to install and give it a try, https://github.com/pedro-augusto-santana/nemo_create_new_folder_with_selection

Not working for me on Mint 19.3, should I do something else besides right click on selection?

**Comment by xenopeek** [comment]
@rafaelribeiroo I had the same issue, you must make sure the file `new_folder_with_selection.sh` is marked as executable. From Plugins in Nemo click on the folder open icon in bottom right of list of Actions. There find that file, right-click it and select Properties and on the Permissions tab set to allow executing it. That made it work for me.

Mind that the current version of nemo_create_new_folder_with_selection is bugged so if you get it from GitHub now, edit the file `new_folder_with_selection.nemo_action` and replace the text:

```
Name[en]=Create new folder with selection
```

with:

```
Name=Create new folder with selection
```

Without a Name key in the file Nemo won't load it.
