### ISSUE TITLE
Guideline for FSearch and Nemo Integration

### ISSUE THREAD

**Issue by blueray453** [linuxmint/nemo#2126]
I need some guideline regarding FSearch and Nemo integration.

I asked for [guideline](https://github.com/cboxdoerfer/fsearch/issues/158) to Christian Boxdörfer regarding implementation of FSearch in go and integrating it with Nemo. His [answer](https://github.com/cboxdoerfer/fsearch/issues/158#issuecomment-485924854) is quite an important read.

However, it is apparent that I have to seek suggestions from Nemo team regarding few issues. The question I mainly want to ask here are 4 & 5.

1. How do drag and drop works in Nemo? I would like to drag a file / some files from FSearch UI to Nemo / Linux Mint Desktop. How do you suggest I do it? Is there any particular Linux Mint / Nemo API which may make the experience better?

2. When I `Right Click > Open in file Manager` in my app, it should open Nemo while the selected file is highlighted. At his moment it just opens Nemo, without selecting the file. How can I do that?

3. Is there any [cinnamon](https://github.com/linuxmint/cinnamon), or may be [muffin](https://github.com/linuxmint/muffin) APIs which I should know about. Which Linux Mint subproject APIs are related to or may be helpful to FSearch project?

I would also appreciate if someone has something extra to add to this.

**Comment by blueray453** [comment]
I got the answer for the second [question](https://unix.stackexchange.com/questions/109554/show-in-folder-does-not-select-file).

```
touch /var/tmp/xxx.txt
nemo /var/tmp/xxx.txt
```

**Comment by xenopeek** [comment]
Sorry you didn't get a follow up on this. I imagine you're not waiting for an answer but for any that stumble upon this.

Nemo is developed with the Gtk+ 3 toolkit and uses drag and drop from that. Online API reference here: https://developer.gnome.org/gtk3/stable/gtk3-Drag-and-Drop.html. You can also install devhelp to get the API documentation on your system and while you're at it install gtk-3-examples for some maybe useful example programs (gtk3-demo and gtk3-widget-factory). Install cinnamon-doc to add Cinnamon API documentation to devhelp. For more information see also the developer guide https://linuxmint-developer-guide.readthedocs.io/en/latest/.
