### ISSUE TITLE
Cycling in and out of focus with Nemo the slower it becomes to gain focus of Nemo

### ISSUE THREAD

**Issue by hutber** [linuxmint/nemo#2134]
```
 * Nemo version 4.0.6
 * Desktop
 * Mint 19.1
 * NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] - 390
 * 64 bit
 ```

**Issue**
Changing focus in and out of Nemo will cause a huge delay in gaining focus of Nemo. The application once focus is finally gained is completely find.

The time taken to get focus is exponential. It seems that if I leave and come back it has 2x then if i leave and come back its x4, then x8 etc (these times are guesses)
 
**Steps to reproduce**

1. Navigate to a folder with images inside
2. Select some images
3. Click focus on another non nemo applications. 
4. Repeat 1 & 2 with different images
5. Repeat 3 & 4 until Nemo becomes unresponsive. 
6. Close all windows (Cntrl+Q) and all delays have disappeared, repeat above to get slowness back.

**Expected behaviour**
No delay in focus at any point

**Other information**
This is a fresh install of nemo 19.1 as of 3 hours ago. The machine is a beast with PCIe SSD.

**Comment by xenopeek** [comment]
The thumbnailer could cause performance issues for Nemo with directories with many large image/movie files. That may be especially noticeable on a new install if you copied over such directories. WIth Nemo 4.6.4 on Linux Mint 20 Cinnamon the thumbnailing is optimized to prefer Nemo's performance over thumbnailing as fast as possible. This should likely solve this issue.
