### ISSUE TITLE
Feature request :  NFS mount and unmount with GUI

### ISSUE THREAD

**Issue by Supermagnum** [linuxmint/nemo#2142]
For KDE (Dolphin, Krusader) there is an NFS kioslave.
Why is there no tools for NFS in Linux mints GUI ?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
