### ISSUE TITLE
Checkboxes/Radiobuttons not following GTK theme colours

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo#2143]
```
 * Nemo version: 4.0.6
 * Is issue with desktop or windowed nemo? Windowed Nemo
 * Distribution - Arch Linux
 * Graphics hardware *and* driver used: Intel Ironlake GPU with the xf86-video-intel driver
 * 32 or 64 bit: 64bit
 ```

**Issue**
The colours of Checkboxes/Radiobuttons isn't following the GTK theme colours.
The item that's being hovered over also looks awkward, because the checkmark turns white against a bright background and basically disappears.

Screenshot: https://i.imgur.com/leuoQag.png

Is this a deliberate style choice, i.e. it's hardcoded in Nemo?

**Comment by mtwebster** [comment]
Have you tried other themes?  There's nothing particular in nemo.

It looks fine for me under gtk 3.24.8 (fedora 30) and 3.22.30 (mint)

**Comment by dglava** [comment]
My bad, you were right. It works with other themes.
Thank you for the quick help.
