### ISSUE TITLE
[Feature request] - Deprecate 'show more/fewer actions' in nemo right-click context menu, and default to showing all actions.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo#2151]
```
 * Nemo version 4.06
 * Is issue with desktop or windowed nemo? Both
 * Distribution - Mint 19.1
 ```
It's a IMHO a useless feature in it's current implementation (hiding or showing 4 actions only), which regularly is the subject of support queries, as the +- icon use is not particularly intuitive.

It might have a raison d'etre if it acted to show/hide user added custom actions, but it doesn't...

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
