### ISSUE TITLE
[Question] how to add "Sign with GPG" option to right-click menu ?

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/nemo#2152]
```
 * Nemo version (nemo 4.0.6)
 * Is issue with desktop or windowed nemo? (I'm using Fedora on laptop)
 * Distribution - (Fedora 30)
 * Graphic: Hybrid VGA (Intel Corporation HD Graphic 5500 + Radeon R7 M265 2GB)
 * 64 bit
 ```
I have the following installed on my system:

- seahorse
- enigmail

I like to add option to sign with GPG to right click menu, so that if I right click a file then I can click then on this new option (sign with GPG) to sign this file. How can I add this option ?

I noticed that there is no seahorse-nemo package in my package manager, but there is, instead, seahorse-nautilus package. Also there is no nemo-seahorse package .....

I want to use GUI not terminal.

Thank you.

**Comment by leigh123linux** [comment]
You will need to build the extension

https://github.com/linuxmint/nemo-extensions/tree/master/nemo-seahorse

**Comment by leigh123linux** [comment]
Fixed

https://src.fedoraproject.org/rpms/nemo-extensions/c/f856dcca0be5899e67e2b079b3c6ed786aa81159?branch=master

https://bodhi.fedoraproject.org/updates/FEDORA-2019-0f4a1494c3

**Comment by Nokia808** [comment]
@leigh123linux 
Thank you very much for this quick fix !
