### ISSUE TITLE
Search view - includes subfolders

### ISSUE THREAD

**Issue by fotoneex** [linuxmint/nemo#2160]
```
 * Nemo version (nemo --version) - 4.06
 * Is issue with desktop or windowed nemo? - unsure
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Linux Mint 19.1
 * Graphics hardware *and* driver used - unsure
 * 32 or 64 bit - 64 bit
 ```
**Issue**
If you use the search view icon/function, what is presented in the list is all matching files, including those in sub-folders.  There is NO indication a file actually comes form a sub-folder (or deeper) and I cannot see an easily discoverable option to control this behaviour.  It should only select files at the current folder level!  

**Steps to reproduce**
For example in Downloads, create a number of folders and folders below those. Scatter some jpg and png files across the structure.  Select search to isolate say the png files (for other processing).  Files are collected recursively.

**Expected behaviour**
I only expect files at the current folder level.  I can see why it searches recursively, but there should be an option to control this - recursive on/off.

**Other information**
Just spent too long figuring out where files came form so they could be put back home after a copy to another area to work on them.

**Comment by scottdoyland** [comment]
In Nemo, if you right click on the columns list of files displayed, eg right click on "Name" column.  You can then select to display the "Location".  This then shows where the files are located.  In fact is displays the "Location" column by default for me when I search (on Nemo 4.0.6, Linuxmint 19.1).

**Comment by xenopeek** [comment]
As above, the Location column is shown by default in search results but if the column was removed it can be added back as described.


![image](https://user-images.githubusercontent.com/21159972/85965611-77e9f400-b9bd-11ea-9197-f1a022c445ea.png)

**Comment by vlad0337187** [comment]
@fotoneex , dunno why this issue was closed, but I found such option:
![Screenshot from 2022-12-11 06-48-50](https://user-images.githubusercontent.com/12682937/206887090-c75604a5-d077-4856-9e42-3e2f0552f076.png)
