### ISSUE TITLE
Ebook(evince thumbnailer) thumbnails fail over SMB

### ISSUE THREAD

**Issue by rousselgeoffrey** [linuxmint/nemo#2163]
nemo 3.6.5
Issue with windowed Nemo
Distribution Ubuntu 18.04 LTS
Graphics hardware Nvidia drivers version 390.77
64 bits

**Issue**

Ebooks tumbnails fail over SMB (samba share) with messages like this:
----------------------------------------------------------------
(nemo:31811): CinnamonDesktop-WARNING **: 01:08:30.200: Error creating thumbnail for smb://akem-hp.local/comics_bds_mangas/Scrooge/Uncle%20Scrooge%20(001-100)%20GetComics.INFO/029%20Uncle%20Scrooge.cbr: Unrecognized image file format
Error loading remote document: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.243" (uid=1000 pid=1488 comm="evince-thumbnailer -s 128 smb://akem-hp.local/comi" label="/usr/bin/evince-thumbnailer (enforce)") interface="org.gtk.vfs.MountTracker" member="LookupMount" error name="(unset)" requested_reply="0" destination=":1.10" (uid=1000 pid=1725 comm="/usr/lib/gvfs/gvfsd " label="unconfined")
 
(nemo:31811): CinnamonDesktop-WARNING **: 01:08:30.365: Unable to create loader for mime type application/x-cbr: Unrecognized image file format
----------------------------------------------------------------

And same messages for PDF files and others.
There is an apparmor profile enforced for evince-thumbnailer (which generate the thumbs for the ebooks),
and so i removed appmor which fixed the issue for me.
Note that Nautilus was able to generate the thumbs over SMB even with appmor and the same configuration.

**Steps to reproduce**

Share a folder with SMB with some ebooks inside (pdf or cbr etc).
(flush the thumbnails if needed)
Connect to the SMB share, open the directory, -via Network- (issue in loopback too).

**Expected behaviour**

Show thumbnails of the ebooks.

**Other information**

**Comment by leigh123linux** [comment]
Sorry there isn't anything to fix within nemo that will fix your appmor problem, also neom-3.6.x is EOL.
