### ISSUE TITLE
Nemo "background click action" not shows until file click or window refresh

### ISSUE THREAD

**Issue by mathiasbaldissera** [linuxmint/nemo#2167]
```
 * Nemo version: 4.0.6
 * Mint 19.1 64bits
 ```

**Issue**
After creating an action for nemo context menu at _~/.local/share/nemo/actions_, that shows "Open folder in VSCode", the action only appears after selected any file or pressed F5 to refresh the window.

Code inside action file (vscode_open_folder.nemo_action):
```
[Nemo Action]

Active=true
Name=Open Folder in VSCode
Comment=Opens current folder in Visual Studio Code
Exec=code %P
Icon-Name=visualstudiocode
Selection=none
Extensions=any;
Quote=double
Dependencies=code;  

```
I think this is because when Nemo open a folder (double click or right click), the folder continue selected (in the previous folder, but don't show it) and, when you select and unselect another folder (or refresh the window), the selection finally "go away"

**Comment by mtwebster** [comment]
Thanks a lot - let me know if this issue occurs in other situations.  I did some optimizations a while back, and this was an unintended side effect.
