### ISSUE TITLE
Nemo 4.2.0 ignores File Size - Prefixes setting

### ISSUE THREAD

**Issue by apawelec** [linuxmint/nemo#2168]
```
 * Nemo 4.2.0
 * Issue with windowed nemo
 * Distribution - Manjaro 18.0.4
 * Intel graphics, modesetting driver
 * 64 bit
 ```

**Issue**

After upgrade to version 4.2.0, Nemo always shows file sizes in Decimal units (status bar, file properties modal etc.), regardless from _File Size - Prefixes_ configured value.

**Steps to reproduce**

1. Assume you currently have default Decimal unit configured.
1. Open preferences dialog and go to Display tab.
1. Change _File Size - Prefixes_ option to Binary.
1. Nemo still shows sizes in Decimal units (even after program restart).

**Expected behaviour**

1. After changing _File Size - Prefixes_ preference, Nemo should show sizes in selected unit.

**Additional info**

In previous version it works correctly.

**Comment by mtwebster** [comment]
I can't reproduce this.  The only issue I see is that when you change that preference, it doesn't affect already-displayed information - you have to refresh somehow to see the change manifest.  If it's a properties window, close and re-open.  If it's status bar, select something else, if it's the list view, passing the mouse over the list will render the new format (or navigating to a new folder).  

I tested in 4.0 and found the exact same behavior.

**Comment by apawelec** [comment]
In version 4.2.1 it works fine.
