### ISSUE TITLE
Idea: Hotkey/Facility to reopen last closed Nemo tab or window.

### ISSUE THREAD

**Issue by MiY4Gi** [linuxmint/nemo#217]
I've gotten really used to this functionality in Google Chrome. Occasionally I would accidentally close a tab in my internet browser, but then I can quickly reopen it using Ctrl+Shift+T. Having this functionality in Nemo would be really convenient.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
