### ISSUE TITLE
Nemo does not recognize file type

### ISSUE THREAD

**Issue by thrashdin** [linuxmint/nemo#2171]
```
 * Nemo version 3.8.5 (desktop)
 * Distribution - Debian 10  64 bit
 ```

**Issue**
Nemo doesn't recognize `.lisp` files as source code files, same with `.asd`.

**Steps to reproduce**
Turn on the "detailed type" option.

**Expected behaviour**
I'm not saying this is very important but it recognizes `.el` files as Elisp source, soo..

**Other information**

**Comment by NikoKrause** [comment]
Linux Mint (as other Linux Distros) uses `xdg/shared-mime-info` for those file endings to be recognized:

https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in#n5939

And it lists only `.el` files for lisp.

**Comment by thrashdin** [comment]
Thank you, I'll head there then.
