### ISSUE TITLE
[feature request] split view within tabs

### ISSUE THREAD

**Issue by WilhelmKuntner** [linuxmint/nemo#2174]
```
 * Nemo version: 4.0.6
 * desktop nemo
 * Distribution: Mint 19.1
 * Graphics hardware: Intel Corporation Haswell-ULT Integrated Graphics Controller; standard open source driver
 * 64 bit
 ```

**Issue**
Many times it would be practical to be able to split view within tabs, for instance like the dolphin file manager does. 

**Steps to reproduce**
Split panes with F3, then open new tab, or vice versa. 

**Expected behaviour**
I completely ignore how difficult it would be to implement such an option. Ideally one could set default behaviour in the nemo preferences: (a) open tabs within panes (actual behaviour) OR (b) split panes within tabs. 

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
