### ISSUE TITLE
Sort hidden files the same as normal files

### ISSUE THREAD

**Issue by stevenxxiu** [linuxmint/nemo#2177]
```
 * Nemo version (nemo --version) 4.2.1-1 on Arch Linux
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch Linux
 ```

**Issue**
Hidden files (those beginning with `.`) are always sorted later, after regular files when they are shown.

They should be sorted the same as regular files, and not sorted after regular files. For example, on both Mac and Windows, they are sorted the same way.

This could be an option to have them sorted later if really needed, but I find this rather strange.

Sorting them in the same way probably reduces the amount of code too.

I also made a comment [here](https://github.com/linuxmint/nemo/issues/578#issuecomment-500096351).

**Comment by mtwebster** [comment]
From left to right:
Nemo, Nautilus, Caja, Thunar

![image](https://user-images.githubusercontent.com/262776/72289972-3ab1c580-361a-11ea-8a57-e33221922e6f.png)

All of them sort hidden files separately from normal files.  The only difference is thunar sorts hidden files *before* while the other three sort them *after* normal files.

None of them offer an option to change this, and I don't really think it would be an improvement (nor do others I've discussed this with).  I find it easier to identify hidden folders/files the way it is now, regardless of how windows or mac does it.
