### ISSUE TITLE
[feature request] No permission warning message

### ISSUE THREAD

**Issue by mrshroomy** [linuxmint/nemo#2178]
```
 * Nemo version (nemo --version)
nemo 4.0.6
 * Is issue with desktop or windowed nemo?
Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux mint 19.1
 * Graphics hardware *and* driver used
AMD Radeon r7 240 Radeon driver
 * 32 or 64 bit
64 bit
 ```

**Issue**
I think that the nemo file manager should show a warning message when you try to move a file/folder to a system folder when you don't got permission (root mode in nemo). I got confused and thought that the folder moved when i tried but it didn't because of me not being in root mode. It would be easier for new users to Linux to make them able to enable root mode on the warning message to move the file/folder that they want.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
