### ISSUE TITLE
Unable to move folder with long name

### ISSUE THREAD

**Issue by int512** [linuxmint/nemo#2179]
* Cinnamon 4.0.8
 * Distribution - Mint 19.01
 * Nemo 4.0.6

**Issue**

**Steps to reproduce**

1. Have folders with Long name like 
_Test1_012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678012345678_

2. Have a folder with a short name like _tr_ just below folder _Test1..._

3. Try to move _Test1..._ folder to _tr_ folder.

Observed behaviour. _Test1.._ folder name lable expands and overlays folder _tr_ , do user is not able to perform drag and drop.

**Expected behaviour**

Folder _Test1..._ successfully moved to folder _tr_

Please see screenshots

![Screenshot from 2019-07-30 09-27-42](https://user-images.githubusercontent.com/127223/62109645-fc635c80-b2ac-11e9-9311-fe15027c39bf.png)

![Screenshot from 2019-07-30 09-34-11](https://user-images.githubusercontent.com/127223/62109735-35033600-b2ad-11e9-92c8-7942efb77c32.png)

**Comment by nmjbhoffmann** [comment]
I might be wrong, but I believe there's a maximum file name (including the path of the file) limit of something like 255 characters for most file systems.

**Comment by icarter09** [comment]
Nemo v4.4.2
Mint 19.3 64bit

I was not able to reproduce this issue. Performed the steps in the ticket and was able to successfully drag/drop the long named folder into the shorter named folder.

**Comment by xenopeek** [comment]
I retested on Nemo 4.6.4, where this is solved but as above it was solved in prior version.

![test](https://user-images.githubusercontent.com/21159972/85965174-34db5100-b9bc-11ea-9237-c754790fec6f.gif)
