### ISSUE TITLE
[Feature Request] Btrfs browse snapshots for current folder

### ISSUE THREAD

**Issue by nmjbhoffmann** [linuxmint/nemo#2180]
```
 * Nemo version 4.0.6
 * Distribution - (Linux Mint 19.1, Cinnamon)
 * 64 bit
 ```
Having a shadowcopy style file browser built into the folder properties window would be an awesome addition. I'm thinking have a list of btrfs snapshots for the volume of the folder in a separate tab in the folder properties. When clicking a snapshot, open a folder for that snapshot but open directly into the folder you're currently browsing, but in the snapshot folder.

I know this can be done through the Timeshift in Linux Mint, and this is mostly a convenience thing. It doesn't need to manage snapshots (though having a button to create a quick manual snapshot would be nice), it just needs to list them if they already exist.

If the volume isn't btrfs (or other possible supported systems), or if there aren't any snapshots, then just don't show the tab.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
