### ISSUE TITLE
Random order of nemo actions in context men

### ISSUE THREAD

**Issue by SEGGER-Alex** [linuxmint/nemo#2183]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
Hi. When starting to use nemo actions to extend the context menu, I came across the issue that there does not seem to be a defined behavior reg. in what order the nemo actions I create are shown in the context menu. I have also seen that menu items were pushed around after logging out and logging in again.

**Steps to reproduce**
Simply add some nemo actions as follows:
00-test.nemo_action => label = 00
01-test.nemo_action => label = 01
02-test.nemo_action => label = 02

You may see in the context menu
01
00
02

**Expected behaviour**
Nemo actions to be added to the context menu in alphabetical order of the nemo action file names. (Like you do for udev rules and startup scripts by naming them: 00-xxx.sh, 01-xxx.sh, ...)

**Other information**
I have checked the source and the fix is pretty simple (verified by building nemo from source):
nemo_action_manager.c => set_up_actions():
`file_list = nemo_directory_get_file_list (directory);`
This list does not seem to be ordered. The items are added to the menu in the order they are in file_list.
What I did is adding this line just after receiving the list:
`file_list = g_list_sort(file_list, _cbSortFileList);`
After that, the list is alphabetical ordered so you have the same behavior as you do for udev rules etc.
Content of _cbSortFileList():
```
static gint _cbSortFileList(gconstpointer a, gconstpointer b) {
  gint r;
  NemoFile* pFileA;
  NemoFile* pFileB;
  const char* s0;
  const char* s1;
  char c0;
  char c1;

  pFileA = (NemoFile*)a;
  pFileB = (NemoFile*)b;
  s0 = nemo_file_peek_name(pFileA);
  s1 = nemo_file_peek_name(pFileB);
  //
  // Order alphabetically
  // Compare ASCII values of file names char by char
  //    < 0:  a < b
  //   == 0:  a == b
  //    > 0:  a > b
  //
  do {
    c0 = *s0++;
    c1 = *s1++;
    if (c0 < c1) {
      r = -1;
      break;
    }
    if (c0 > c1) {
      r = 1;
      break;
    }
    if (c0 == 0) {  // Special case: Both strings are identical and we have hit the \0 char? => Return equal 
      r = 0;
      break;
    }
  } while (1);
  return r;
}
```
Already asked this here and also posted the solution:
https://stackoverflow.com/questions/57279720/determine-nemo-context-menu-actions-ordering/57313035

**Comment by smurphos** [comment]
Pending *cough* a native sort feature being added for actions this little script does the job.

```
#!/bin/bash
mkdir -p /tmp/actions/
mv "$HOME"/.local/share/nemo/actions/*.nemo_action /tmp/actions/
ACTIONS=$(find /tmp/actions -iname '*.nemo_action' | sort -n)
for i in $ACTIONS; do
 touch "$i"
done
mv /tmp/actions/*.nemo_action "$HOME"/.local/share/nemo/actions/
nemo -q 
nemo-desktop -q
nemo-desktop & disown
```

I run it from an action

```
[Nemo Action]
Name=Sort _Actions
Comment=Sort actions by filename.
Exec=<scripts/sort_actions.sh>
Selection=none
Extensions=none;
Icon-Name=user-desktop-symbolic
Quote=double
```

**Comment by LinuxOnTheDesktop** [comment]
I think my system suffers from this too. For, if no Nemo window is open, and then I open one and right-click a folder, then I must scroll down to see the 'move to recycle bin' option. Yet, if I dismiss the menu and then re-open it, I can see the the recycle option near the top of the list of options. The effect of this re-ordering is to make me inclined to think, when I first open the menu, that the option I seek is not there, and so I close the menu and open it again - thus doubling the amount of time it takes me to achieve my goal.

**Comment by LinuxOnTheDesktop** [comment]
I add that sometimes, upon the first but not the second right-click, the menu item that I want is on a part of the menu that is drawn _off the bottom of the screen_.

**Comment by LinuxOnTheDesktop** [comment]
Thanks, Smurphos. I do not fancy recompiling Nemo, so I will use the shell script on that page.

**Comment by LinuxOnTheDesktop** [comment]
@ SEGGER-Alex

It could have a very happy outcome were you to turn that C function into a pull request . .

**Comment by LinuxOnTheDesktop** [comment]
Perhaps it is worth adding the following.

As I said above, sometimes the recycle and delete buttons are not accessible at all (until one closes and re-opens the context menu). Now, I use those functions a lot. So, multiple times a day, I have to double the amount of clicks that I must make. That is a considerable inconvenience.

**Comment by CronWorks** [comment]
I've wanted this for so long that I went ahead and pasted @SEGGER-Alex 's solution into a PR: https://github.com/linuxmint/nemo/pull/2360

Thanks Alex!
