### ISSUE TITLE
Geometry parameter not working anymore

### ISSUE THREAD

**Issue by saulfautley** [linuxmint/nemo#2184]
```
 * Nemo version: 4.2.2
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution: Mint 19.2
 * Graphics hardware *and* driver used: Nvidia GTX 970 / nvidia-driver 430.40-0ubuntu0~gpu18.04.1
 * 64 bit
 ```

**Issue**

Firstly, Nemo's window geometry (position and size) is never remembered. This seems like it has always been the case, I presume by design (for some reason). My workaround for this has been to use the `geometry` launch parameter. Not ideal but at least it's something.

Since updating to Mint 19.2, Nemo no longer honors the `geometry` parameter at all, so setting an initial window position and size is impossible, leaving the _extremely_ limited `Location of newly opened windows` window manager setting as the only control over the window position. Control of the window's size is still impossible, other than manually resizing the window every time.

**Steps to reproduce**

1. Start Nemo with `nemo --geometry=1000x1000+20+20`
2. Nemo window opens centered (based in window manager setting) and with default size (800x580).

**Expected behaviour**

Window should open 20px from top-left corner with 1000px width and 1000px height.

**Other information**

The larger issue here is of course that we have no control over the size and position of windows in Cinnamon/Muffin to begin with. This is something that many other DE's offer, but we're stuck with a _window manager_ that [believes](https://github.com/linuxmint/cinnamon/issues/8154#issuecomment-448491366) _windows_ should be _managed_ by each application and not by the _**window manager**_... 😝️

**Comment by saulfautley** [comment]
Preview of default window not exactly utilizing the screen space it has to work with. And currently no way to change it.

![nemo-bug-current](https://user-images.githubusercontent.com/2036475/62425738-cecb4880-b6dc-11e9-9c72-4b6224cddace.png)

**Comment by smurphos** [comment]
> Firstly, Nemo's window geometry (position and size) is never remembered. This seems like it has always been the case, I presume by design (for some reason). 

That appears to be your underlying issue. Nemo remembers it's size (albeit not position) fine for me and always has done. The geometry on closing the window is stored in dconf so i suspect there may be an ownership issue with the dconf database preventing the closing geometry sticking - likely because you have used `sudo nemo` at some point.

To fix any ownership issues run `sudo chown -Rc $USER:$USER $HOME` and see if that allows nemo to remember it's geometry on closing.

**Comment by saulfautley** [comment]
Thanks @smurphos, I see now that Nemo does indeed remember its size. It doesn't look like it was a permission issue though. It seems that when using the `--geometry` parameter Nemo doesn't just not honor the parameter value anymore, it also completely ignores the saved dconf geometry value and resets to the default "small" size again.

I have an alias script for nemo that always starts it with `--geometry` which is why it seemed like it wasn't remembering the window size.
