### ISSUE TITLE
Incomplete nemo translation!

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/nemo#2185]
```
 * Nemo version (nemo 4.2.2)
 * Is issue with desktop or windowed nemo? [windowed nemo]
 * Distribution - (Mint Cinnamon 19.2 Stable Release)
 * Graphics hardware *and* driver used
Graphics:
  Device-1: NVIDIA G96 [GeForce 9500 GT] vendor: eVga.com. driver: nvidia 
  v: 340.107 bus ID: 01:00.0 chip ID: 10de:0640 
  Display: x11 server: X.Org 1.19.6 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: GeForce 9500 GT/PCIe/SSE2 v: 3.3.0 NVIDIA 340.107 
  direct render: Yes
 * 32 or 64 bit
64Bit
 ```

**Issue**
by pinning a file the word "pin" and "unpin" is not translated to english brazil even though all files are translated in launchpad

**Steps to reproduce**
https://postimg.cc/WdrLG9NV

**Comment by kelebek333** [comment]
You can translate or change on Launchpad.

https://translations.launchpad.net/linuxmint/latest/+pots/nemo/pt_BR/382/+translate

https://translations.launchpad.net/linuxmint/latest/+pots/nemo/pt_BR/381/+translate
