### ISSUE TITLE
Nemo showing incorrect folder size

### ISSUE THREAD

**Issue by voidbert** [linuxmint/nemo#2186]
```
nemo 4.0.6
Windowed nemo but it doesn't matter
Linux Mint 19.1 Cinnamon
The bug is not graphical but I have an RX 480
64-bit
 ```

**Issue**
Nemo is giving me wrong sizes for directories. The size of the parent directory is different than the size of everything inside it.

**Steps to reproduce**
Any folder with multiple files and folders inside will do. The difference is of a few kilobytes and it shouldn't matter but it makes a difference in my situation.

**Expected behaviour**
The size of the parent directory is different than the size of everything inside it. I've tested for hidden files but there are none so, that can't be the cause for the bug.

**Other information**
See the attached images:
![Screenshot from 2019-08-06 15-50-52](https://user-images.githubusercontent.com/50591320/62550406-1e874c80-b862-11e9-84fd-8b245b0c6ab1.png)
![Screenshot from 2019-08-06 15-50-18](https://user-images.githubusercontent.com/50591320/62550407-1f1fe300-b862-11e9-8664-df2cb7b7cb7d.png)

**Comment by J-P-** [comment]
Hi. I don't know much about much, and I'm a neophyte in this Linux world at best. 

However, from the images that were posted, it shows that apples are not being compared with apples.
  Image 1: 15 items totaling 69kb
  Image 2: 20 items totaling 89kb
So unless you can demonstrate that the delta 5 items are 0 bytes each, the complaint is not substantiated.

Just a thought...

**Comment by mtwebster** [comment]
Folders take up space - there's a minimum block size when a folder is created which is 4096b.

When selecting the contents of a folder and getting properties, and folders are ignored (they're reported separately in the selection info in the bottom status bar.)

I'm not sure which is right - they're both 4096 and 0 in a way. I'm going to have a look at some other file managers first.

**Comment by voidbert** [comment]
> Folders take up space - there's a minimum block size when a folder is created which is 4096b.
> 
> When selecting the contents of a folder and getting properties, and folders are ignored (they're reported separately in the selection info in the bottom status bar.)
> 
> I'm not sure which is right - they're both 4096 and 0 in a way. I'm going to have a look at some other file managers first.

Thank you. I was kind of a Linux newbie when I posted this. I tested another file manager (I don't know which) back then and it gave me the smaller size. It should've only counted the files and excluded the folders. That lead me to submit this issue. Thank you for the information! I'm closing the issue (I thought I had already closed it a while ago, my bad).
