### ISSUE TITLE
[Improvement] Enhance contrast of desktop icons' titles

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/nemo#2187]
```
 * Nemo version: 4.2.2
 * Desktop
 * Mint 19.2
 * Intel UHD Graphics 620 / Kernel  4.15.0-55-generic & GeForce MX150 / nvidia-driver-430
 * 64 bit
 ```

**Issue**
The readability of desktop icons' titles is hard when a bright or colorful wallpaper is used, due to the lack of contrast.
![Captura de tela de 2019-08-07 21-34-43](https://user-images.githubusercontent.com/1660320/62667966-5a084080-b960-11e9-9508-f8989fee672c.png)![Captura de tela de 2019-08-07 22-13-47](https://user-images.githubusercontent.com/1660320/62668044-ace1f800-b960-11e9-93ba-7ac7ed33dee7.png)

**Steps to reproduce**
Set Mauritius (Tina) or Positano (Tessa) as wallpaper and place an icon on a bright spot.

**Expected behaviour**
To be able to read the title regardless of which wallpaper is set, with a good readability.

**Other information**
One suggestion is to add some options to increase the shadows or to permanently set a grey box as background (like at mouse hover, that greatly improves contrast).
![WithGreyBox](https://user-images.githubusercontent.com/1660320/62668430-3514cd00-b962-11e9-958c-083188150508.png)

This bug was spotted by user "D3XT3R" from [Plus Diolinux](https://plus.diolinux.com.br/).

**Comment by leigh123linux** [comment]
There is already a pull request for this https://github.com/linuxmint/nemo/pull/2125
I doubt it will be accepted as it make the font look horrible!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
