### ISSUE TITLE
When typing into a search filed, focus from the search field is lost randomly

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#2191]
```
 * Nemo version (nemo --version)
4.2.2
 * Is issue with desktop or windowed nemo?
windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia binary 430.34
 * 32 or 64 bit
64bit
 ```

**Issue**
Whenever I hit Ctrl+F and start typing a search term, the focus is lost and I end up typing the rest into the results listing portion of the window.

**Steps to reproduce**
1. Navigate to a folder that has a lot of items, maybe try /
2. Hit Ctrl+F and immediately start typing some search term that's longer than a few characters and pick a substring that actually appears somewhere... say txt or jpg 
3. as soon as items start appearing below the search box, focus is lost. Sometimes it takes 2-3 characters sometime more for focus to be lost. 

This happens 100% of the time on my install.

**Expected behaviour**
Results window should not steal focus away from the search box.

**Other information**
Something seems to be wrong with 'search as you type' feature.

**Comment by icarter09** [comment]
Nemo v4.4.2
Mint 19.3 64bit

I'm not able to reproduce this issue using the steps provided. @nick-s-b are you still experiencing this issue on the latest version of nemo?

**Comment by nick-s-b** [comment]
@icarter09 just checked. It seems to have been fixed. Running 4.4.2. I do not know if this was fixed intentionally or something else was causing this. I'll pay close attention to it and reopen if it comes back.
