### ISSUE TITLE
Bug: When copying noobs (RPi) to SD

### ISSUE THREAD

**Issue by 1MrBee** [linuxmint/nemo#2192]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
On one window I'm copying noobs to sd card. Then on another window moving files from one directory to another crashes the system.

**Steps to reproduce**
(LinuxMint) copying noobs (RPi) from downloads file to SD card ready for loading into RPi
Then on another window moving files from one directory to another on same drive crashes the system.

**Expected behaviour**
copying to be queued or in wait mode until noobs had been completed it's copying.

**Other information**
contact me if need more

**Comment by leigh123linux** [comment]
Basic info is missing, please use the template!
