### ISSUE TITLE
Feature Request - Open new windows by holding down Strg-Key and Doubleclick on a folder

### ISSUE THREAD

**Issue by shadow73s** [linuxmint/nemo#2194]
Sorry for my poor english.

When I Doubleclick on a folder ist opens in the same Window.
Can you implement that the Doubleclick on a folder with hold down the Strg-Key opens a new Window with the selected folder as path?
I used Windows before and this function was realy comfortable.

```
 * Nemo version 4.2.2
 * Distribution Mint 19.2 Cinnamon
 * 64 bit
 ```

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
