### ISSUE TITLE
Feature Request - Make the expand of the folder-tree detachable my mousemove over a folder

### ISSUE THREAD

**Issue by shadow73s** [linuxmint/nemo#2195]
Sorry for my english.

When I move a file/folder (drag and drop) from one window in another one and I move it over an folder, the folder will expand.
So the view will sometime scroll.
When I let go the Mousebutton while that happen, the file/folder I drag will moved to any subfolder that is in the moment under the coursor.
So it's very annoying that I have to search the file/folder and move it to the right folder.
So my Question will you make it possible to disable the expand of the treefolders?
This will be very helpfull.

```
 * Nemo version 4.2.2
 * Distribution Mint 19.2 Cinnamon
 * 64 bit
 ```

**Comment by ericxob77** [comment]
I completely agree.  It is SO frustrating to not be able to override this behavior.  Related:  How can I drag a file or folder to another Nemo window that has only folders visible and get it to land in the MAIN window, not inside a directory.  On the Mac, it used to be this could be accomplished by dragging the item(s) to the title bar of the receiving window.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
