### ISSUE TITLE
Feature request: smaller tab sizes

### ISSUE THREAD

**Issue by simonzack** [linuxmint/nemo#2199]
Could nemo have smaller tab sizes, like browsers (Chrome, Firefox) do? When I just have 2 tabs, they span the whole screen which is a bit wide.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
