### ISSUE TITLE
Nemo startup time ~25 seconds

### ISSUE THREAD

**Issue by kythre** [linuxmint/nemo#2203]
```
 * Nemo version (nemo --version)
    4.2.2
 * Is issue with desktop or windowed nemo?
    windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
    Arch
 * Graphics hardware *and* driver used
    NVIDIA NVS 5400M
    NVIDIA 390.116
 * 32 or 64 bit
    64 bit
 ```

**Issue**
Nemo initial startup time is 25 seconds. 
```
$ NEMO_BENCHMARK_LOADING=1 nemo

** (nemo:8313): WARNING **: 09:37:06.562: Current gtk theme is not known to have nemo support (Adwaita-dark) - checking...

** (nemo:8313): WARNING **: 09:37:06.647: The theme appears to have no nemo support.  Adding some...
Nemo startup time: 25.560079 seconds
Folder load time: 0.321943 seconds
Idle...Folder load time: 0.353017 seconds
```
No abnormal CPU/memory/HDD usage

**Comment by leigh123linux** [comment]
I can't reproduce with nemo 4.2.3 (Fedora 30).


'Intel Celeron J4105'
```
$ NEMO_BENCHMARK_LOADING=1 nemo
Initializing nemo-image-converter extension
Shutting down nemo-image-converter extension
Nemo startup time: 1.017567 seconds
Folder load time: 0.546484 seconds
Idle...Folder load time: 0.551086 seconds
```

'AMD FX8350' over ssh from 'Intel Celeron J4105'

```
$ ssh -AX leigh@192.168.0.24
Last login: Sun Sep  8 12:35:37 2019 from 192.168.0.30
$ NEMO_BENCHMARK_LOADING=1 nemo
Initializing nemo-image-converter extension
Nemo startup time: 1.570248 seconds
Folder load time: 1.207199 seconds
Idle...Folder load time: 1.230344 seconds
```

**Comment by mtwebster** [comment]
Hi,

Are there a lot of files in that folder?   Does it matter what folder you load? (you can do `nemo <path>`).

What extensions are you running?  Does this behave the same with none loaded? (edit->plugins, bottom view)

Do you have any network or other remote shares bookmarked, or bound/linked into that folder?

Lastly, can you paste nemo's output from this?
```
NEMO_BENCHMARK_LOADING=1 NEMO_DEBUG=Application,DBus  nemo --debug
```

Thanks

**Comment by kythre** [comment]
Doesn't seem to matter which folder I use
No extensions
No network or remote shares bookmarked, or bound/linked
https://hastebin.com/raw/obemotuqec

**Comment by mtwebster** [comment]
What desktop environment are you using?

It appears to be timing out trying to connect to a session manager (this is within gtk) - mainly used to inhibit file idle/powersave actions while file transfers are active.  This issue is likely to occur in any app that uses the GtkApplication class (gnome-terminal is one, for example) - often programs that create multiple windows use it.

In cinnamon, for example, the cinnamon-session provides this (gnome-session, mate-session, etc.. for other desktops).

**Comment by kythre** [comment]
I'm just using bspwm

**Comment by Gr3q** [comment]
I had the same issue on Arch with Cinnamon and Nemo.

I fixed with a complete reinstall.

About the issue: On opening Nemo I was hearing that the HDD was not spinning up for half a minute, then it spun up and Nemo opened.

**Comment by kythre** [comment]
the issue was not having a de and only using a wm.
