### ISSUE TITLE
Please some add support for ultra copier as default copy handler or at least add update default copier in linux mint cinnamon

### ISSUE THREAD

**Issue by ZubairPC** [linuxmint/nemo#2205]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
