### ISSUE TITLE
Feature Request - sidebar  for sftp / smb bookmars

### ISSUE THREAD

**Issue by stefanoful** [linuxmint/nemo#2207]
```
 * Nemo version (nemo 4.2.3)
 * Distribution - (Mint 19.2)
 ``
**Feature Request**

Hello,
There is a way to create a new places on sidebar where to save the sftp / smb bookmarks , folder tree views??
If you could have bookmarks divided by category

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
