### ISSUE TITLE
After Empty Trash, trash icon on the desktop cannot update

### ISSUE THREAD

**Issue by deweiwork** [linuxmint/nemo#2209]
```
 * Cinnamon version (cinnamon --version)
4.2.4

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
ArchLinux

 * Graphics hardware *and* driver used
AMD mesa

 * 32 or 64 bit
64

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
no such file or directory: username
 ```

**Issue**
After Empty Trash, trash icon on the desktop cannot update.

**Expected behaviour**

As following picture shown:
https://imgur.com/nyuJpzI
This icon (trash icon on desktop) until I reboot, icon will become original icon.

**Comment by leigh123linux** [comment]
* Cinnamon version is irrelevant, post nemo --version

**Comment by deweiwork** [comment]
@leigh123linux  OK:
version of nemo is 4.2.3

**Comment by leigh123linux** [comment]
4.2.3 works fine here

https://leigh123linux.fedorapeople.org/pub/screenshots/cinnamon-20190920-1.webm

**Comment by deweiwork** [comment]
Hi @leigh123linux : Which theme do you use? I switch it to try.

**Comment by leigh123linux** [comment]
![Screenshot from 2019-09-20 18-39-42](https://user-images.githubusercontent.com/1299302/65347067-10a14700-dbd6-11e9-8a88-79bcd149dd1c.png)

**Comment by icarter09** [comment]
Nemo v4.4.2
Mint 19.3 64bit

I'm not able to reproduce this issue either. @deweiwork feel free to create a new ticket if you are still experiencing this issue on the latest version of nemo.
