### ISSUE TITLE
[feature request] Convenient way to lock encrypted partitions

### ISSUE THREAD

**Issue by apbaguette** [linuxmint/nemo#2211]
On my laptop I'm using an SD card with multiple partitions, basically as an extra hard disk. I have created a LUKS encrypted volume using the "Disks" application. When I insert the SD card I have to insert the password to unlock the drive. However, there doesn't seem to be a convenient way to lock the partition again. Pressing the eject button from the file manager really ejects the entire SD card, so all other partitions are also unmounted, which isn't really convenient. 

It would be nice to have some feature to re-lock the partition again manually or unmounting the partition, maybe when locking the screen... Now it only really protects against someone stealing the SD card, but the data is still completely in the open when someone steals my entire laptop and manages to log in.

**Comment by mtwebster** [comment]
If there's a terminal command to do accomplish this, you could make an action in nemo - actions are a way to incorporate custom entries into nemo's context menus, so you could potentially right-click on a drive in the sidebar, and have a 'Lock' entry.

Take a look at [this](https://github.com/linuxmint/nemo/blob/master/files/usr/share/nemo/actions/sample.nemo_action) file, as well as the other actions we ship with nemo, [here](https://github.com/linuxmint/nemo/tree/master/files/usr/share/nemo/actions).

Let me know if you have any questions on it.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
