### ISSUE TITLE
Filename textfield in the Save as dialog loses invisible focus when switching folders

### ISSUE THREAD

**Issue by mdindoffer** [linuxmint/nemo#2212]
```
 * nemo 4.2.3
 * Windowed
 * Mint 19.2
 * Intel HD Graphics 520, Mesa 19.1.2
 * 64 bit
 ```

**Issue**
File name textfield in the `Save as` dialog loses focus when switching folders, but the default filename remains selected. Typing in a name after a directory change pops up a file search panel instead of changing the filename. 

**Steps to reproduce**
1. Try to save a new file (e.g. from Xed)
![save as1](https://user-images.githubusercontent.com/12681399/65509512-ef40a380-ded2-11e9-99c1-10f97cba206b.png)
2. Click on a folder bookmark in the left panel
![save as2](https://user-images.githubusercontent.com/12681399/65509531-f8ca0b80-ded2-11e9-9fb7-f190c58dc133.png)
3. Start typing a name to save the file as
![save as3](https://user-images.githubusercontent.com/12681399/65509538-fd8ebf80-ded2-11e9-8d7c-274d23726e1e.png)

**Expected behaviour**
I expect the typing in step 3. to replace the default `Unsaved Document 1` filename in the top of the GUI and type in a new filename instead of a search dialog popping up.
Since the default filename remains selected it makes it even more counterintuitive. I expect the selected text to disappear when typing anything.

**Comment by JosephMcc** [comment]
These dialogs are provided by the Gtk toolkit and have nothing to do with Nemo. If you find bugs or issues with them please report them to the Gtk devs. This isn't something we control.

**Comment by mdindoffer** [comment]
@JosephMcc Oh, my apologies then. 
What version of GTK+ does Cinnamon use in 4.2.4 so I can raise a proper issue with GTK?
All I could find is `GTK_MIN_VERSION=3.12.0`

**Comment by JosephMcc** [comment]
You have to find out what version of Gtk your distro ships. You didn't list it in the issue template. On Mint it's 3.22.
