### ISSUE TITLE
Bug: Pango-1.44 hyphenates  long file names.

### ISSUE THREAD

**Issue by prashantraina** [linuxmint/nemo#2214]
```
 * Nemo version 4.2.3
 * Desktop and windowed nemo.
 * Distribution - Manjaro (Arch)
 * NVIDIA RTX 2080Ti, NVIDIA driver version 430.40
 * 64 bit
 ```

**Issue**

Since a recent update, long filenames are being hyphenated as shown in the screenshot.
This is very confusing, because the filenames may contain actual hyphens.
The non-existent hyphens are still visible even when renaming files! It causes confusion when modifying the file name.

![image](https://user-images.githubusercontent.com/9632639/66007349-06a60080-e480-11e9-90ad-577bf4138fa5.png)

**Steps to reproduce**
Create a file with a long name (> 8 characters on my machine, but this might depend on screen resolution).
Also, when renaming the file using the context menu option, the hyphens are still visible.

**Expected behaviour**

Please add an option in the Preferences or somewhere to disable hyphenation of long filenames and use the old behavior for wrapping long filenames.

**Other information**

**Comment by Salamandar** [comment]
My duplicate issue was closed so I'm here to support this issue :)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Salamandar** [comment]
That's not a feature request, but a "revert feature" request.
