### ISSUE TITLE
Cannot access root on remote machine after reboot

### ISSUE THREAD

**Issue by micksulley** [linuxmint/nemo#2215]
```
 * Nemo version (nemo --version)  nemo 4.0.6
 * Is issue with desktop or windowed nemo?  desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 19.1
 * Graphics hardware *and* driver used  nvidia-driver-390
 * 32 or 64 bit   64 bit
 ```

**Cannot access root on remote machine after reboot**

**Use 'connect to server' to connect to a remote machine with ssh.  Connection is established and all works fine.  Now reboot the remote machine.  Connection is lost, as expected.  Reconnect to the remote machine.  Connection is established but only to the home directory, trying to access the root directory give an error message  'Could not display "sftp://pi@raspberrypi/" The location is not a folder' **

**The connection should be established as before**

**Happy to provide any further info, just tell me what is needed**

**Comment by jaydcarlson** [comment]
I've noticed identical behavior when connecting to a remote SSH host that has restarted. I can still access `/usr` or `/etc` by appending the name of the folder to the address bar, but I cannot access the root directory of the remote SSH host.

Nemo 3.6.4.

**Comment by anri-vin** [comment]
Same here. When adding new connection - root is displayed as expected. After reconnect - I can navigate to all folders except root. Nemo 4.4.2 on x64 Mint 19.3.

**Comment by micksulley** [comment]
I have noticed that when this happens if you connect as a different user you get the expected connection, but then if you reboot again that user/connection is restricted as well.  Doesn't really help much.

**Comment by anri-vin** [comment]
It is not necessary to reboot. Just terminate connection and reconnect is enough.

**Comment by micksulley** [comment]
I recently upgraded to Linux Mint 20 and it works fine now.
