### ISSUE TITLE
Nemo perfomance slow down

### ISSUE THREAD

**Issue by OpenA** [linuxmint/nemo#2216]
```
 * Nemo version (4.2.3)
 * Is issue with desktop or windowed nemo? (both)
 * Distribution - (Mint 19.2 Cinnamon X11)
 * GeForce GTX 650 nvidia-driver-430.26
 * 64 bit
 ```

**Issue**
After 1 month using fresh installed system, nemo perfomance is just go down

**Steps to reproduce**
Both apps (desktop and folder viewer) has very slow reaction at start - click on elems or mouse hovering effects is just happens with 2-5 sec delay.

**Expected behaviour**
Maybe separate start-jobs to another process (workers)?
And in interface show loading stub in folder section, before they done

**Other information**
Actuly, I have a noises in my frontal audio panel (it's normal and not nemo problem) and i heare in headphones long squeak, like as game while loading (just program loop i think). Then nemo is finish his loading the perfomance become normal, but if i enable "show hidden files" this effect repeated some time if i navigate in file browser directories. And anyway, dont matter restored perfomance or not then, i clicking "close window" button, it closes with 2-3 seconds delaing

**Comment by OpenA** [comment]
Oh, i found what this problem came from - im using Template folder for local git projects folder, i didn't know about autoembadded this in nemo context menu.

I think thats a great futhure but maybe need add example file? But anyway, i think separate somer process in different worker/thread can bee improve speed and usability. At least didnt block and freezez user interface at some local troubles (like this)

**Comment by icarter09** [comment]
@OpenA you still experiencing this issue?

**Comment by OpenA** [comment]
No, please close.
Thanks

**Comment by NikoKrause** [comment]
Why don't you close it yourself?

**Comment by OpenA** [comment]
me?

**Comment by NikoKrause** [comment]
The "Close issue" button is right besides the "Comment" button.
