### ISSUE TITLE
Alt + Backspace shortcut to delete

### ISSUE THREAD

**Issue by zooks** [linuxmint/nemo#2219]
```
 * Nemo version (4.2.3)
 * desktop and windowed nemo
 * Distribution - (Mint 19.2)
 * 64 bit
 ```

**Issue**

Please add
`Alt + Backspace` for deleting.

**Steps to reproduce**

-

**Expected behaviour**

Pressing Alt + Backspace should delete a file / folder.

**Other information**

**Comment by smurphos** [comment]
The extant default shortcuts are Delete for send to trash and Shift-Delete to delete permanently

**Comment by leigh123linux** [comment]
Just use the delete key.
