### ISSUE TITLE
Feature Request: Ability to remember extra pane devider position, tabs and locations, column widths

### ISSUE THREAD

**Issue by yerb** [linuxmint/nemo#2220]
If this functionality is already available I am not aware where I can enable it. But if its not, here are my suggestions.

1. Remember 'Extra pane' divider position on exit
2. Remember tabs and their folder locations on exit
3. Add tab Right-click options 'Lock', 'Lock with changes allowed' and 'Duplicate tab', like in Total commander
4. Ctrl-drag tab makes a copy of tab
5. Remember view columns widths

Thank you for this great app.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
