### ISSUE TITLE
Feature Request: Option to disable expanding folder in list view (similar to nautilus feature)

### ISSUE THREAD

**Issue by zpangwin** [linuxmint/nemo#2222]
## Version / System Details

 * Nemo version (nemo --version): Nemo v4.2.3
 * Is issue with desktop or windowed nemo?: Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.2 Cinnamon x64
 * Graphics hardware *and* driver used: Nvidia GeForce 970 + nvidia driver v430.50
 * 32 or 64 bit 64-bit

```
$ cat /etc/linuxmint/info|grep Mint
DESCRIPTION="Linux Mint 19.2 Tina"
GRUB_TITLE=Linux Mint 19.2 Cinnamon
    
$ uname -a
Linux TiNY 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    
$ inxi --graphics
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 430.50 
  Display: x11 server: X.Org 1.19.6 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 430.50 
```
---

## **Issue**
In windowed nemo using list view, dragging a file into the right-hand pane and hovering on a folder too long causes the folder to be expanded. For larger folders containing e.g. 50+ items, the users view can be disrupted when the folder is expanded.

Recently had to test something in Ubuntu 18.04.2 and saw that Nautilus v3.26.4 has a checkbox option under Preferences > Views > List View section for controlling this behavior. I tested and it seemed to control the exact behavior I described above.

Not sure if nemo still merges code from nautilus or if that was a one-time thing, but was hoping that we could either merge that feature from nautilus or otherwise create an equivalent. I'm not good with GTK but in the event that nautilus code base is at all relevant to the current nemo build, I did find [this commit](https://github.com/GNOME/nautilus/commit/906c70d5aae8dccc77a3e5d947e10e5a0bba8739) which might be relevant and using using `grep -PRi 'folder.*expand|expand.*folder' * -B 2 --exclude=NEWS --exclude-dir=po` against the nautilus repo returned hits in `src/nautilus-files-view.c` and `src/resources/ui/nautilus-preferences-window.ui` .

Failing that, hoping that it might at least be possible to have something we could set in dconf / gsettings that would either allow us to toggle this behavior or to increase the hover time before the expansion happens (so that we could effectively disable it by giving a 10-min hover delay or some such)?

----

## **Steps to reproduce**

1. Be in windowed nemo.
2. Use list view
3. Browse somewhere with a sub-folder containing some files and some files. See snippet for convenience
4. If you manually create the sub-folder from terminal, make sure to refresh nemo before continuing
5. In the right-side pane (e.g. NOT the tree/bookmark sidebars), drag the file over a sub-folder that contains at least one file but do not release the mouse button/do not complete the drop action. After approx 2-3 seconds, the folder will expand to show the contents. 

For convenience, you can run the following to skip steps 1-4:

    mkdir -p /tmp/folder-expansion-test/drag-and-hover-over-me-but-dont-drop
    cd /tmp/folder-expansion-test/drag-and-hover-over-me-but-dont-drop
    echo dummy | tee file1.txt file2.txt file3.txt
    cd /tmp/folder-expansion-test
    echo dummy | tee drag-and-hover-me-over-the-folder.txt
    (nemo /tmp/folder-expansion-test) &

----

## **Expected behaviour**
I can check a settings / apply it in gsettings and folder expansion will not happen

----

## **Other information**
N/A

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
