### ISSUE TITLE
Feature Request: Add new default desktop action for "Display Settings" similar to windows. (nemo-action provided)

### ISSUE THREAD

**Issue by zpangwin** [linuxmint/nemo#2223]
## Version / System Details

 * Nemo version (nemo --version): Nemo v4.2.3
 * Is issue with desktop or windowed nemo?: Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.2 Cinnamon x64
 * Graphics hardware *and* driver used: Nvidia GeForce 970 + nvidia driver v430.50
 * 32 or 64 bit 64-bit

```
$ cat /etc/linuxmint/info|grep Mint
DESCRIPTION="Linux Mint 19.2 Tina"
GRUB_TITLE=Linux Mint 19.2 Cinnamon
    
$ uname -a
Linux TiNY 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    
$ inxi --graphics
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 430.50 
  Display: x11 server: X.Org 1.19.6 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 430.50 
```
---

## **Issue**
On many windows machines, it is common to have a (desktop background) right-click / context menu option for the user to quickly be able to access a dialog where the screen resolution can be changed directly from the desktop.

As Mint is one of the top distros that ex-Windows users / dual-booters try, this convenience would no doubt be appreciated by many; especially users that hookup a laptop to monitors at multiple locations.

It is not difficult to create a nemo action to handle this, but I would like to propose having that option be enabled by default for fresh installs.

----

## **Steps to reproduce**

1. Be a new-comer to Mint
2. Boot Mint 19.2 from livedisc / usb
3. Right-click desktop.
4. Don't have option to change resolution and then need to find it under the menu

----

## **Steps to resolve**

1. Create a new file at /usr/share/nemo/actions/show-display-option-on-desktop-context-menu.nemo_action
2. Edit file to add contents shown below
3. Set ownership as root:root
4. Set perms as 644 (-rw-r--r--)

**show-display-option-on-desktop-context-menu.nemo_action**

```
[Nemo Action]
Name=Display Settings
Comment=Display Settings
Exec=/usr/bin/python3 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py display
Icon-Name=display
Selection=none
Extensions=none
Conditions=desktop
```

----

## **Expected behaviour**
On fresh install / live disc, user can right-click on desktop background and get an option labeled "Display Settings" or similar which opens the cinnamon-settings.py display so the user can customsize display settings quickly and easily.

----

## **Other information**
N/A

---

Screenshot
![2019-10-18--175025](https://user-images.githubusercontent.com/29719631/67130661-07ed6200-f1d0-11e9-8698-4224ead6b7a3.png)

**Comment by zpangwin** [comment]
Also, I would be more than happy to re-submit this as a pull request if desired. But if so, please confirm:

* Would simply adding the nemo_action under `files/usr/share/nemo/actions/` be the correct location for default actions?
* Should pull-requests be submitted to any specific branch?
* Do you guys prefer to reference the ticket in the pull request or to close out the ticket and just the let submission/rejection take place solely within the pull request itself?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
