### ISSUE TITLE
Feature Request: Improve Accessibility of Permissions tab drop-downs (e.g. hotkey support, etc)

### ISSUE THREAD

**Issue by zpangwin** [linuxmint/nemo#2224]
## Version / System Details

 * Nemo version (nemo --version): Nemo v4.2.3
 * Is issue with desktop or windowed nemo?: Windowed (But either really)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.2 Cinnamon x64
 * Graphics hardware *and* driver used: Nvidia GeForce 970 + nvidia driver v430.50
 * 32 or 64 bit 64-bit

```
$ cat /etc/linuxmint/info|grep Mint
DESCRIPTION="Linux Mint 19.2 Tina"
GRUB_TITLE=Linux Mint 19.2 Cinnamon
    
$ uname -a
Linux TiNY 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    
$ inxi --graphics
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 430.50 
  Display: x11 server: X.Org 1.19.6 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 430.50 
```
---

## **Issue**
When running windowed nemo, especially when opened as root, changing owner / group (right-click file/folder > Properties > Permission tab) via the drop-downs can run into situations where a large number of items appear so much so that not all items are visible on-screen at once.

Nemo users like myself may find it difficult to quickly and easily change the owner / group due to having to scroll through and find the desired item in a moderately sized list (50-100 items). There are a lot of ways to go about addressing this, so I have listed some potential options in the next section.

Notes:
* User drop-down is only available when using the Nemo option "Open as Root"
* The group drop-down does not contain generally many items when nemo is run from a non-root account. However, when Open as Root is used, both lists contain a lot more values than will fit in the visible area of the drop-down (for me, it has 50 users and 84 groups).

----

## Screenshot

![2019-10-08--173841](https://user-images.githubusercontent.com/29719631/66805086-1bf44380-eef2-11e9-9b43-1119a92831be.png)

----

## **Potential Solutions**

There are a number of different approaches which could improve the accessibility of the Permissions dialog. I will try to list out a few potential solutions, in order of I am **guessing** would be easiest to hardest to do (disclaimer: I am not familiar with the code so this could be way off):

1. Enable "hotkey support" on the drop-downs, so that pressing a letter will select the first (case-insensitive) item starting with that letter, if it exists or ignore the keypress if it does not exist. E.g. if "myuser" is the current owner and I then click on the drop-down and press `r` it would jump to and select "root", etc.
2. Add a checkbox next to dropdown to "Hide service accounts". Clicking the checkbox would be equivalent to using `getent passwd {1000..60000}` / `getent group {1000..60000}` vs. Unchecked being as it is now (equivalent to `getent passwd` / `getent group`). Disclaimer: nemo probably isn't running these commands internally... but what do I know.
3. Searchable drop-down. I imagine this would probably be a lot more work but just listing it on the off chance that perhaps GTK already offers a per-defined form control class that has this functionality and the existing drop-down could be easily swapped out with a searchable one. I will try to skim through GTK docs to see if this is feasible and update accordingly. Disclaimer: I know absolutely nothing about GTK but skimming api class docs doesn't sound too bad.
4. Allow user to define some new gsettings key/value which will define what should appear in the list. e.g. something like `org.nemo.preferences advanced-permissions-user-list ['root', 'bob', 'susan', 'junior', 'sally']` / `org.nemo.preferences advanced-permissions-group-list ['root', 'bob', 'susan', 'junior', 'sally', 'family', 'adults', 'kids'] ` Disclaimer: these values are 100% made up. TBH, this seems like the worst approach for devs (more work) and users (more to maintain) but I guess it would be flexible.
5. ??? (Something I missed)

----

## **Steps to reproduce**

1. Create some folder (e.g. "test") on Desktop or some other location with some user (e.g. "myuser"), preferably a username that starts with a differently letter than R.
2. Open nemo, then right-click and choose Open as Root and authenticate.
3. Browse to the "test" folder then right-click > Properties > Permission tab
4. Left-click on a drop-down for either users or groups and observe the large number of entries which likely does not fit in the visible area even if running from a livedisc / fresh install.
5. Left-click on a drop-down for either users or groups, then press a key (e.g. `r`) ...
6. Observe that nothing happens (e.g. "root" is not selected)

----

## **Expected behaviour**

(Assuming the first proposed solution above - adding hotkey support - was implemented)

1. Create some folder (e.g. "test") on Desktop or some other location with some user (e.g. "myuser"), preferably a username that starts with a differently letter than R.
2. Open nemo, then right-click and choose Open as Root and authenticate.
3. Browse to the "test" folder then right-click > Properties > Permission tab
4. Left-click on a drop-down for either users or groups, then press a key...
5. If a drop-down contains an item that begins with the pressed key (not considering case), the first such item should be selected. In other words, if the owner=myuser and "root" is the first user or group that begins with "R", then clicking the drop-down and pressing `r` should cause "root" to be selected.

----

## **Other information**

Notes:
* User drop-down is only available when using the Nemo option "Open as Root"
* The group drop-down does not contain generally many items when nemo is run from a non-root account. However, when Open as Root is used, both lists contain a lot more values than will fit in the visible area of the drop-down (for me, it has 50 users and 84 groups).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
