### ISSUE TITLE
[Feature Request] Show all open tabs in RMB Copy/Move to

### ISSUE THREAD

**Issue by Swaphelaer** [linuxmint/nemo#2225]
```
 * Nemo version (nemo --version) : 4.2.3
 * Is issue with desktop or windowed nemo? : both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : Mint 19.2 Cinnamon
 * Graphics hardware *and* driver used : NVIDIA Corporation GM206 [GeForce GTX 960] - Nvidia driver 390
 * 32 or 64 bit : 64
 ```

**Issue**
When using "Copy to"/"Move to" also show any open tabs as a destination.

**Steps to reproduce**
It's a request, can't reproduce.

**Expected behaviour**
In the RMB-menu show either show all the open tabs as a target or under a 'Tabs' header which can unfold and show all the open Tabs.

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
