### ISSUE TITLE
[Feature Request] Right click -> Menu -> Create Symlinks (sendto Desktop)

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/nemo#2229]
Hi,

it would be nice to have the option to send a file or a folder as symlink to the desktop (like in Windows -> sendto Desktop)

or as a second option

create a starter to the exec or directory where we can change the icon

Thank you

 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**



**Steps to reproduce**



**Expected behaviour**



**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
