### ISSUE TITLE
[Feature Request] On selecting properties on a desktop.entry for a file or directory start a special editor for this desktop.entry

### ISSUE THREAD

**Issue by hubertmeier** [linuxmint/nemo#2230]
It would be nice to edit the properties of a desktop-starter with a dialogue where i can change the icon

i am not sure if this a feature request for nemo or for cinnamon-desktop ...

Thank you

```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by smurphos** [comment]
When you right click > properties on a desktop launcher (or any other icon) you already get a GUI where you can change the icon. Click the icon in the top left of the properties GUI to open the Icon Picker.

**Comment by hubertmeier** [comment]
Thank you, i did not see that. 
Is it possible to make a new starter which points to a folder instead of an exec-file ?

**Comment by smurphos** [comment]
Yep, use the command format `xdg-open /path/to/folderorfile` for launchers to folders or to open any file in it's default application.
