### ISSUE TITLE
How To Remove Windows Network Folder?

### ISSUE THREAD

**Issue by S3NTYN3L** [linuxmint/nemo#2231]
```
 * Nemo version:  4.2.3
 * Is issue with desktop or windowed nemo?  Not sure what that even means TBH. One can run Nemo in a window that can be maximized or not. :/
 * Distribution: Mint, Cinnamon, Tina
 * Graphics hardware *and* driver used:  Not the issue.
 * 32 or 64 bit:  64-bit
 ```

**Issue**
I cannot delete the "Windows Network" folder found in "Network".

**Steps to reproduce**
Open Nemo, click on "Network" and remember that there are no Windows machines in my home whatsoever.

**Expected behaviour**
Open Nemo, click on "Network" and be content in the fact that the "Windows Network" folder can be deleted is I so choose. And, I REALLY DO choose to do so.

**Other information**
Provided upon request.

Folder in question: https://i.imgur.com/F1qjWI3.png

**Comment by leigh123linux** [comment]
File the issue against gvfs as that provides the virtual file in network folder.

https://en.wikipedia.org/wiki/GVfs
