### ISSUE TITLE
[Thunderbird] dragging message to the desktop or a folder is not working

### ISSUE THREAD

**Issue by ovari** [linuxmint/nemo#2232]
```
 * Nemo version: 4.2.3
 * Is issue with desktop or windowed nemo? both
 * Distribution: Mint 19.2 Cinnamon
 * 64-bit
 ```

Drag-and-drop a message from Thunderbird to the Desktop or folder (in Nemo) creates a "Link" file which does not work. The file that should be created is an email file with extension `.eml`.

This work with the Windows operating system. Not sure if this is a Linux Mint problem or a Thunderbird problem.
https://bugzilla.mozilla.org/show_bug.cgi?id=1527715

**Steps to reproduce**

Drag-and-drop a message from Thunderbird to the Desktop or folder

**Expected behaviour**

A file with extension `.eml` be created that can be open to view the email.

**Other information**
https://bugzilla.mozilla.org/show_bug.cgi?id=1527715

Thank you

**Comment by leigh123linux** [comment]
Thunderbird will need to address this.

https://bugzilla.mozilla.org/show_bug.cgi?id=630512
