### ISSUE TITLE
Feature Request: more versatile sorting and searching of files

### ISSUE THREAD

**Issue by morfikov** [linuxmint/nemo#2233]
I wanted to switch to the `nemo` file manager from the one I'm currently using (`spacefm`), but there are three things that bother me much.

Maybe I start with the file/dir sorting order. `nemo` is able to sort files/dirs by name, size, type, detailed type (whatever that is) and modification date (+reversed). I usually sort files/dirs by their names, but also with options like the `hidden files first` and `case insensitive`. So the list of files/dirs looks like the following:
```
      ________________
.aa/ |       | hidden |
.AA/ |       | dirs   |
.ab/ |       | first  |
.AB/ | dirs  |________|
 aa/ | first |        |
 AA/ |       |        |
 ab/ |       |        |
 AB/ |_______|________|
.aa  |       | hidden |
.AA  |       | files  |
.ab  |       | first  |
.AB  | then  |________|
 aa  | files |        |
 AA  |       |        |
 ab  |       |        |
 AB  |_______|________|
```
So when I look for something, I have to ask myself two questions -- 1) is it a dir or a file, and 2) is it a hidden one? With the current `nemo` sorting order options, I have to add 3rd question -- are the letters capitalized? To simply put this -- it takes more time to find the file I want, since I have to make at least 3 queries instead of just 2, which is at minimum +50% in additional overhead when making queries. :]

Is there any chance for nemo to get such sort options like `hidden first/last` and `case sensitive/insensitive`?

The second thing is in searching for files just by typing letters in the main window. Currently `nemo` is able to highlight only what matches to the point you've typed in the little search bar at the bottom right corner, and it always will be only one match, no matter how many files in the current dir/file list match the letters you've typed. My current file manager is able to jump between the matches using the mouse scroll while still the search box is visible -- so I write `test`+scroll, and I can jump to the next file/dir that has `test` in it's name (not necessary starting with the typed phrase). Will `nemo` get such features, which are really the nice ones?

The third thing is similar to the second one, but includes also hidden files. Currently I have to start typing from `.` to highlight a match in hidden files. And again when I start typing I don't really want to think too much about what I type -- if I type `test`, I expect that `.test` or `.littletest` will be included in the highlights and not just `test*`. At least nemo doesn't pay attention to big and small letters -- that would be a challenge to highlight a file. :D

Besides the three things, `nemo` seems to look like a nice file manager to have, but you see that because of the lack of the aforementioned features it's not really convenient in use when you want to really fast find the files you're looking for. Do the three features have some chances to be implemented? I think many people would really appreciate it.

Have a nice day.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by klesun** [comment]
Um, does anyone know what's the status of this request? Does nemo still not have search by any part of file name? No any plugins or stuff?

**Comment by morfikov** [comment]
> Um, does anyone know what's the status of this request? Does nemo still not have search by any part of file name rather than only from the start? No any plugins or setting or some special shortcut?

They just dumped the request. Nothing has changed since then.
