### ISSUE TITLE
Do not show dashes in file name. That's confusing.

### ISSUE THREAD

**Issue by Salamandar** [linuxmint/nemo#2238]
![Capture d’écran du 2019-11-04 16-32-48](https://user-images.githubusercontent.com/6552989/68133530-db03b380-ff20-11e9-9a06-6892d10aee16.png)
Nemo automatically adds dashes when filenames are splitted over multiple lines.
When a filename contains dashes or/and underlines, that's very confusing. I found myself trying to remove the (unexisting) dash more once.
Sometimes I think that's a "fake" dash, but it's actually **really** in the filename.
If some users really want this, that should be a disablable setting.

**Comment by leigh123linux** [comment]
Duplicate of #2214
