### ISSUE TITLE
Desktop item sort mode is not saved

### ISSUE THREAD

**Issue by GuidoBartoli** [linuxmint/nemo#2239]
```
 * Cinnamon version = 4.0.9
 * Distribution = Linux Mint 19.1
 * Graphics hardware = ACER TravelMate integrated graphics
 * 64 bit
 ```

**Issue**
When customizing the current monitor layout, if a sorting mode other than "name" is selected for items, that value is not maintained, because if you reopen the same menu, the value is always reset to "name"

**Steps to reproduce**
1. Right click on desktop
1. Choose "Customize"
1. Change "Sort items by" to "Size", "Type" or "Date"
1. Close window
1. Right click on desktop
1. Choose "Customize"
1. "Sort items by" is reset to "Name"

**Expected behaviour**
"Sort items by" should remember the previous value

**Comment by necarnot** [comment]
Hello,

I'm witnessing the same issue on 4.0.6 : re-opening it is stuck on "modification time" order, whatever sort mode is chosen before closing.

**Comment by necarnot** [comment]
Hi,

I'm also seeing that when adding a sort column, I see two "Creation date" checkboxes : 
https://framapic.org/gallery#wKYgZxN18I6b/CCAoMjhHm8Mb.png

**Comment by necarnot** [comment]
Thank you @icarter09
