### ISSUE TITLE
Feature Request: Symbolic icons in places

### ISSUE THREAD

**Issue by rilian-la-te** [linuxmint/nemo#224]
Add option to use symbolic icons (like nautilis 3.6)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
