### ISSUE TITLE
Annoyance issue with file/folder name editing

### ISSUE THREAD

**Issue by burtbick** [linuxmint/nemo#2240]
```
 * Nemo version 3.8.5
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - Ubuntu 19.04 With Cinnamon desktop from Ubuntu repository
 * Graphics hardware Ryzen 5 integrated Raedon graphics with driver from Ubuntu 19.04
 * 64 bit 
 ```
Note I had wanted to install Mint 19.x on this new machine but Mint 19.0/1/2 doesn't work and play well with the Ryzen 5 Raedon graphics.  I expect this will be corrected in Mint 19.3 since that is moving to the 5.x kernel which is needed as part of the Ryzen graphics support.  So that is why I installed Ubuntu 19.04 which DOES work well with the Ryzen graphics.

**Issue**
Two annoyance issues that are related:
1 - Create a new file or folder.  There is no feedback showing where the cursor is in the default  name.  As I recall under the previous Mint installation the default name would be highlighted or at least the cursor was showing.  The same issue is present when renaming a file or folder, it just looks like it is still showing the file or folder with no indication that you would be in name edit mode.

**Steps to reproduce**
Create a new file or folder.  Note that the default name 'Untitled Document' or 'Untitled' is shown but no indication that this is in name edit mode.  If you click at the end of the name the cursor does appear.  

**Expected behaviour**
When creating a new file or folder entry an indication that you are in edit mode and not just displaying the new entry in Nemo (e.g. cursor showing, name highlighted, etc.) 

**Other information**
It is unknown if this is an artifact of Cinnamon running on the Ubuntu 19.04 installation, or if this is new behavior in Nemo.  Everything else with Cinnamon installed on Ubuntu 19.04 appears to be working quite well.

I was going to try building the latest Nemo to test but I need a newer version of  xapp in order to complete the build.  Also it appears that the build instructions in the INSTALL file on github are out of date and don't describe the meson build process.

**Comment by burtbick** [comment]
Looking closer at the folder/file name there is a very slight change to a slightly bold font when you select rename or when creating a new file/folder.  It may just be our older eyes that make this less noticeable.  But it at least is a clue that you are in name edit mode.

**Comment by burtbick** [comment]
And one last bit of detail.  If you are in list mode then you get a name field with the entire field highlighted making it clearer that you are in name edit mode.  It is when you are in the Icon view mode that you get the slightly bold name as an indication.  It would be clearer if the name was highlighted when in Icon view instead of the slightly bold font.

**Comment by xenopeek** [comment]
This sounds like it was a theming issue. For example if you had Adwaita set as the theme you would unfortunately have such issues as you described. See #1333 for more about that.

Here is Nemo rename of a new file in action with the default Mint-Y theme for Linux Mint 20 Cinnamon:
![Peek 2020-06-29 04-29](https://user-images.githubusercontent.com/21159972/85966847-3c512900-b9c1-11ea-8501-a2174e380330.gif)
