### ISSUE TITLE
Pasting text into the path box can append when it should overwrite

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2244]
```
 * Nemo version (nemo --version) 4.2.3
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.2
 * Graphics hardware *and* driver used: Intel onboard; Mesa
 * 32 or 64 bit
 ```

**Issue**

If I paste text over a path in the nemo bar, then, if the text I am pasting starts with a space, the result is that the new text gets _appended_ to the old text.

**Steps to reproduce**

Have a path in the bar/box - e.g. '/etc/lightdm'. Have text starting with a space on the clipboard - e.g. ` /test` (_sic_). Paste over the existing text.

**Expected behaviour**

The selected text should be replaced, not appended to.

**Other information**

See screenshot of result.
![2019-11-16_04-41](https://user-images.githubusercontent.com/47056543/68988174-5885c880-082b-11ea-9d3f-b61368bee1f5.png)

I think this effects the alt-F2 box.

**Comment by xenopeek** [comment]
Hm. Not reproducible on Nemo 4.6.4 unless before I paste either I toggle the location entry (click the button / press Ctrl+L) and then clear the text selection highlight or I click on already shown location entry and don't select the text. In those case if I paste the text is inserted at the cursor location, as I would expect. The issue is not reproducible when the text on the location entry is selected—pasting a path starting with a space overwrites the text in the location entry in that case.

**Comment by LinuxOnTheDesktop** [comment]
@xenopeek 

I can reproduce the problem on Nemo 4.6.4. Here is how.

Set Nemo to display the full path in the location bar.
Copy this string to the clipboad:  /etc/systemd/user.
Highlight what is in the location bar already.
Paste the string (anyway you like).

So please re-open this report.

**Comment by xenopeek** [comment]
You're right, with that it is reproducible.

Steps to reproduce:

1. Copy a path from somewhere including a leading space, like " /etc/systemd/user"
2. In Nemo toggle location entry and paste the copied path—it looks like the current path in location entry gets overwritten
3. Press enter to navigate to the pasted path but now it shows that the copied path was appended to the current path

![Peek 2020-07-13 16-43](https://user-images.githubusercontent.com/21159972/87317964-fbf8bb80-c527-11ea-972b-d85de0ef19b0.gif)

**Comment by LinuxOnTheDesktop** [comment]
Hello! Has the latest commit referenced in this report landed? For, the problem still exists.

**Comment by LinuxOnTheDesktop** [comment]
In Nemo 5.0.5 , I find that pasting `.<new text>` over  `<old text>` makes Nemo:

1) try to open`<old text>.<new text>`;

and, because that path does not exist, 

2) display an error box.

Is _1_ by design? If it is, is it the best design? Perhaps not, because it seems fairly easy to get an extraneous leading `.` in one's paste - so perhaps it would be better were Nemo to leave the displayed path as it is (and to display an error message).
