### ISSUE TITLE
Crash if view location during button press is different than on button release in icon views with 2-click renaming enabled.

### ISSUE THREAD

**Issue by iadenisov** [linuxmint/nemo#2248]
```
 * 4.4.0
 * windowed nemo
 * Linux Mint 19.1 Cinnamon
 * Intel / NVIDIA
 * 64 bit
 ```

**Issue**

Nemo crashes if press Enter key just after selecting folder by mouse.

Actually it crashes because release of mouse appears after entering to directory.

**Steps to reproduce**

1. Select folder by mouse and do not release mouse left button.
2. Press Enter key
3. Release mouse left button.

Information from `/var/log/syslog` after crashing:
`Nov 21 09:52:42 lenovo kernel: [ 6715.468801] traps: nemo[6306] general protection ip:7f0fbbffb05d sp:7ffda31575a0 error:0 in libgobject-2.0.so.0.5600.4[7f0fbbfc5000+52000]`

**Expected behaviour**

It should open the folder.

**Comment by leigh123linux** [comment]
Your issue doesn't reproduce here with nemo 4.4.2

**Comment by iadenisov** [comment]
> Your issue doesn't reproduce here with nemo 4.4.2

Great! Maybe it was fixed already.

Where I can download new deb package of Nemo 4.4.2 for Mint 19.1 ?

**Comment by iadenisov** [comment]
I just upgrade my Mint to 19.3.  Now I have Nemo 4.4.2.
The bug is still reproducing.

**Comment by mtwebster** [comment]
Does this reproduce with no extensions enabled?

Do you have crash info in System Reports that you can share?

**Comment by iadenisov** [comment]
> Does this reproduce with no extensions enabled?
> 
> Do you have crash info in System Reports that you can share?

I switched off all default plugins and reproduced this again.

Output `/var/log/syslog`
`dia@lenovo:~$ sudo tail /var/log/syslog 
Dec 26 00:22:58 lenovo dbus-daemon[1663]: [session uid=1001 pid=1663] Successfully activated service 'org.gnome.Terminal'
Dec 26 00:22:58 lenovo systemd[1628]: Started GNOME Terminal Server.
Dec 26 00:42:19 lenovo systemd[1]: Starting Message of the Day...
Dec 26 00:42:19 lenovo systemd[1]: Started Message of the Day.
Dec 26 00:44:45 lenovo rtkit-daemon[1885]: Supervising 4 threads of 2 processes of 1 users.
Dec 26 00:46:51 lenovo kernel: [ 2770.790398] traps: nemo[11270] general protection fault ip:5614273cae37 sp:7ffd643147a0 error:0 in nemo[5614272d1000+1a6000]
Dec 26 00:44:45 lenovo rtkit-daemon[1885]: Supervising 4 threads of 2 processes of 1 users.
Dec 26 00:47:26 lenovo kernel: [ 2805.910586] nemo[11311]: segfault at 39 ip 0000560f4dc0ee2f sp 00007ffddc7bdb30 error 4 in nemo[560f4db15000+1a6000]
Dec 26 00:47:26 lenovo kernel: [ 2805.910601] Code: 55 41 54 55 53 48 89 fb 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 e8 ba bf ff ff 48 85 db 0f 84 61 02 00 00 <48> 8b 13 48 85 d2 74 05 48 39 02 74 13 48 89 c6 48 89 df e8 d9 aa
Dec 26 00:47:47 lenovo kernel: [ 2826.772030] traps: nemo[11351] general protection fault ip:555e1ac50e37 sp:7ffe22b61a70 error:0 in nemo[555e1ab57000+1a6000]
`

**Comment by iadenisov** [comment]
If I run with `sudo` it falling with error messages.

```dia@lenovo:~$ sudo nemo

** (nemo:11420): CRITICAL **: 00:51:05.638: nemo_icon_canvas_item_get_drag_surface: assertion 'NEMO_IS_ICON_CANVAS_ITEM (item)' failed

(nemo:11420): Eel-CRITICAL **: 00:51:05.638: eel_canvas_item_get_bounds: assertion 'EEL_IS_CANVAS_ITEM (item)' failed
segmentation fault
```

**Comment by okaestne** [comment]
Can reproduce this as well.
Mint Cinnamon 19.3, Nemo 4.4.2.

```
Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff5a06032 in g_type_check_instance_cast () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff5a06032 in g_type_check_instance_cast () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x000055555565a7ed in handle_icon_slow_two_click (event=0x555555c7baa0, icon=0x5555563cd840, container=0x555556138150) at ../../libnemo-private/nemo-icon-container.c:4997
#2  0x000055555565a7ed in nemo_icon_container_did_not_drag (event=0x555555c7baa0, container=0x555556138150) at ../../libnemo-private/nemo-icon-container.c:3152
#3  0x000055555565a7ed in button_release_event (widget=<optimized out>, event=0x555555c7baa0) at ../../libnemo-private/nemo-icon-container.c:3484
#4  0x00007ffff72b48f7 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff59e0346 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff59fb3cd in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff59fc12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff73fc534 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff72b186e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff72b3948 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff6dc4765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007ffff6df4f92 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007ffff5705417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff5705650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff57056dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff5cc6e3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x000055555558a242 in main (argc=1, argv=0x7fffffffde98) at ../../src/nemo-main.c:104
(gdb) 
```

**Comment by mtwebster** [comment]
Thanks

**Comment by iadenisov** [comment]
Without "2-click renaming enabled" it also falls
