### ISSUE TITLE
Save as does not focus on filename

### ISSUE THREAD

**Issue by gregers666** [linuxmint/nemo#2252]
```
Cinnamon version 4.2.4
No daily builds
Mint 19.2
64 bit

[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3895687/xsession-errors.txt)

NVidia with NVidia driver

 ```

**Issue**
Save As does not focus on filename but searches directory.

**Steps to reproduce**
- Open Save As
- Try to input filename - it will search directory instead of input filename

**Expected behaviour**
Save As should focus on filename 

**Other information**
https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/387957

**Comment by leigh123linux** [comment]
** (nemo:27293): WARNING **: 08:48:41.970: Current gtk theme is not known to have nemo support (Adwaita) - checking...

** (nemo:27293): WARNING **: 08:48:42.072: The theme appears to have no nemo support.  Adding some...
Nemo-Share-Message: 08:48:45.792: Called "net usershare info" but it failed: "net usershare" zwrócił błąd 255: info_fn: file /var/lib/samba/usershares/trans is not a well formed usershare file.
info_fn: Error was Path is not a directory.
info_fn: file /var/lib/samba/usershares/acdm is not a well formed usershare file.
info_fn: Error was Path is not a directory.

**Comment by www-MKRD-info** [comment]
I get the same behavior and it is annoying as well. Although I have been trained by every other software that the filename always has immediate focus in any Save As or Open window, here even though the highlighting of the file SUGGESTS it is in focus, it is not actually true... I have to click on the filename to obtain focus... If I start typing "over" the suggested "highlighting" of the filename, what I will be typing won't be replacing the highlight but will be searching within the "window" directory as described by post author. Annoying indeed.

**Comment by JosephMcc** [comment]
Ok. This gets brought up a lot. The "Save As" dialog has nothing to do with Nemo or any other tool written by the Mint team. This is an issue with Gtk. The issue needs to get brought up with them and I'm pretty sure it already has.

**Comment by Go-rom** [comment]
This issue is back only when browsing among folders, for those seeking this information please see : https://gitlab.gnome.org/GNOME/gtk/-/issues/326
