### ISSUE TITLE
[Feature Request] Enable/disable recursive search when searching for a file in a folder.

### ISSUE THREAD

**Issue by akem3210** [linuxmint/nemo#2253]
Hey,
I think a button that will either enable or disable recursive lookup when searching
for a file in a folder would be pretty handy, cause sometimes if i have subfolders
with tons of files it's very slow and if i know the file is at the first level, i don't want
it to search deeper.
Thanks.
Best Regards.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
