### ISSUE TITLE
nemo: 'rename filename modus' ends as soon as I press CTRL in Debian 10 / Cinnamon 3.8.8 / Nemo 3.8.5

### ISSUE THREAD

**Issue by drandreaskrueger** [linuxmint/nemo#2264]
```
 * Cinnamon version: Cinnamon 3.8.8
 * Distribution: debian 10 buster
 * Intel 620
 * 64 bit
 ```

**Issue**
Since "Debian 10 buster" / Cinnamon 3.8.8, a very useful keyboard shortcut routine has stopped working. (In Debian 9 I could use keyboard shortcuts to rename files, now that stopped working).

**Steps to reproduce**
1. open nemo
2. create new document "Untitled Document"
3. click on "Untitled Document" to focus
4. press F2 so that it gets into **"rename filename" modus**
5. Ctrl-V, to paste a name from the clipboard

Already when pressing CTRL, the **"rename filename" modus** is ending, and the name cannot be edited anymore.

**Expected behaviour**
1. open nemo
2. create new document "Untitled Document"
3. click on "Untitled Document" to focus
4. press F2 so that it gets into **"rename filename" modus**
5. Ctrl-V, to paste a name from the clipboard
6. now the file is called "Titled Document" (if that was the content of the clipboard)

**Other information**
In Debian 9 stretch it still worked.
Oh, and in Debian 10 is also works when using "rightMouseclick ... paste", but not by keyboard shortcut anymore.

Thanks a lot!

**Comment by drandreaskrueger** [comment]
>  Feel free to open up a ticket in the Nemo repo (https://github.com/linuxmint/nemo).  

good idea.  

> @leigh123linux transferred this issue from linuxmint/cinnamon 2 days ago  

Fantastic, thanks. Didn't know that was possible.  Great.

**Comment by drandreaskrueger** [comment]
Hah. I have news. 
After years on cinnamon, I am now -out of curiosity- trying out the GNOME desktop.

And ... weird ... **the issue does NOT exist in Gnome 3.30.2.** Here I can use Ctrl-C in nemo, no problem.

So it is a cinnamon 3.8.8 / Debian 10 (*)  issue - right?

(*) because on Debian 9 that was not a problem.

Please transfer back?

**Comment by leigh123linux** [comment]
@drandreaskrueger I can't reproduce the issue in nemo-4.4.x.
nemo and cinnamon 3.8.x are both EOL, maybe try filing the issue on the Debian bug tracker instead

**Comment by drandreaskrueger** [comment]
> nemo and cinnamon 3.8.x are both EOL

Oops, ouch. EOL end of life? Then please tell me what I am doing wrong here. Because I have just recently upgraded to the newest Debian version, "buster", and that is shipping 3.8.x, no? 

These are the versions on my system:

```
dpkg --list | grep cinnamon
ii  cinnamon                                                    3.8.8-1                              amd64        Innovative and comfortable desktop
ii  cinnamon-common                                             3.8.8-1                              all          Innovative and comfortable desktop (Common data files)
...
ii  cinnamon-core                                               3.8                                  all          Cinnamon desktop environment - essential components
...
ii  cinnamon-settings-daemon                                    3.8.4-2                              amd64        daemon handling the Cinnamon session settings
...
ii  task-cinnamon-desktop                                       3.53                                 all          Cinnamon
```

Yes, that seems to be right: https://packages.debian.org/buster/cinnamon

Are you sure that cinnamon 3.8 is declared EOL?  Buster is not even 6 months old.

**Comment by leigh123linux** [comment]
@drandreaskrueger  Debian release policy isn't our problem if they choose to distribute end of life versions.
I think your stuck with 3.8.x till Buster goes EOL.

**Comment by drandreaskrueger** [comment]
What a funny situation.

I am now simply not using Cinnamon anymore - Gnome desktop is fine too.

Thanks for your explanations.

Have a good ride into the next decade.

**Comment by leigh123linux** [comment]
> What a funny situation.

I also find it funny anyone would want to use Debian with it's outdated and often buggy packages, that's why I use Fedora.

> 
> I am now simply not using Cinnamon anymore - Gnome desktop is fine too.

Fedora release in March with gnome-3.36, Debian will have 3.30 till it goes EOL

> 
> Thanks for your explanations.
> 
> Have a good ride into the next decade.

Good luck with living in the past :-)
