### ISSUE TITLE
Feature Request: Per Folder Settings for showing hidden files and folder

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/nemo#2266]
```
 * nemo 4.2.3
 * Linux mint 19.2 64bit
 * Intel integrated graphics
 ```

**Issue**
It would be nice to have per folder settings for showing hidden files and folders. That way some folders will show hidden files while others wont.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
