### ISSUE TITLE
Create Folder with Selection

### ISSUE THREAD

**Issue by pedro-augusto-santana** [linuxmint/nemo#2267]
Hi!
So, I've saw this feature in Nautilus and on MacOS, creating a folder with the selected items and automatically moving them to the new folder, and I thought this would be pretty cool with Nemo, so I implemented it.
I'm not the best at programming, still a begginer, so apologies in advance for any obvious errors, I uploaded all the files to my Github https://github.com/pedro-augusto-santana/nemo_create_new_folder_with_selection, if you want to look at the code, fell free to use it anywhere you want, there are installation instructions, and if you think it is a useful feature, I can go and try to make it into the default, but there will be a need for translation.
So here are the files [nemo_folder_with_selection.zip](https://github.com/linuxmint/nemo/files/3965276/nemo_folder_with_selection.zip)

**Comment by Sadi58** [comment]
**Thank you so much, that's what I was looking for!**
I've found another one (Python script) which simply moves the selected items to a new folder with a name predefined in the script, e.g. "New Folder with selection" - which of course is not as good as yours. ;-)
**I think it might be a good idea to include this in the default set of Nemo Actions!**

**Comment by icarter09** [comment]
@pedro-augusto-santana did you put a PR together for this?

**Comment by pedro-augusto-santana** [comment]
Hi! Excuse me but can you explain this for me? I don't know what PR means, sorry if this sounds silly but I'm not really used to this kinds of terms

**Comment by icarter09** [comment]
@pedro-augusto-santana no worries. PR = Pull Request. What you implemented sounds useful and @Sadi58 appreciated it as well so why not create a pull request for it to be implemented into the default set of Nemo Actions.

**Comment by Sadi58** [comment]
@icarter09 you probably know better if and how the script mentioned by @pedro-augusto-santana can be turned into a PR to integrated into nemo code. Personally I have no programming skills ( only some bash scripting skills  at a beginner level ; -)

**Comment by pedro-augusto-santana** [comment]
@icarter09  [Done!](https://github.com/linuxmint/nemo/pull/2310), created the PR, only waiting approval. Thanks for your help!

**Comment by dhonx** [comment]
Great feature @pedro-augusto-santana !!! I will try this & give you feedback ASAP.

**Comment by rafaelribeiroo** [comment]
Not working for me, someone could help me to implement this feature?

**Comment by xenopeek** [comment]
@rafaelribeiroo I had the same issue, you must make sure the files new_folder_with_selection.sh and askpass.sh are both marked as executable.

As per the status of the PR, closing this issue.
