### ISSUE TITLE
[Feature Request] CTRL+LEFT-MOUSEBUTTON => Open in new Tab

### ISSUE THREAD

**Issue by Cyborgscode** [linuxmint/nemo#2269]
Hi,

i like to request a behaviour change, that CTRL+LMB opens the selected favourite/folder in a new Tab instead of overloading the current one.  

This would go hand in hand with browser tab handling in i.e. Firefox and would a neat improvement, which could be implemented in minutes.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
