### ISSUE TITLE
Symlink icon doesn't appear if image aspect ratio < (unknown value)

### ISSUE THREAD

**Issue by ChameleonScales** [linuxmint/nemo#2270]
```
 * Nemo version : 4.0.6
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution: Debian 10 x64
 * Graphics hardware *and* driver used: GeForce GTX 960, nvidia driver
 ```

**Issue**
When image thumbnails are activated, the symlink icon (the little arrow) only appears at certain aspect ratios for the images. I haven't determined the threshold value but for example a 1000x270 image does not display the icon whereas a 500x270 image does.

**Comment by leigh123linux** [comment]
4.0.x is EOL, feel free to reopen if you can reproduce with 4.4.x

**Comment by mtwebster** [comment]
This is an issue with gtk - it won't allow emblems to be greater in size than the smaller of the image's width or height, yet as the size of the 'target' image grows (by zooming nemo's view, for instance) the size of the emblem it wants to apply becomes larger as well, retaining this limitation.

I'm going to re-open this, but as a feature request - this can be worked around, but would require nemo to do the work of applying the emblems itself.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
