### ISSUE TITLE
[add feature] button to switch between list and icon view in browse file window

### ISSUE THREAD

**Issue by jeg139** [linuxmint/nemo#2271]
```
 * Nemo version (nemo --version)
Nemo 4.2.3
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux mint debian edition 3 and mint 19.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
64bits
 ```

**Issue**
When a browse file window is open by a software like file attachements for thunderbird there is no option to switch between list and icon view.

**Steps to reproduce**

**Expected behaviour**
Have a button to switch between list and icon view when in a browse file window.

**Other information**

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
