### ISSUE TITLE
After nemo update, the actions debug logs doesn't show anymore

### ISSUE THREAD

**Issue by brunetton** [linuxmint/nemo#2275]
* Nemo version 4.4.0
 * windowed nemo (file browser)
 * Distribution: Arch

For debugging actions, I'm using nemo like this:

```
nemo -q
NEMO_ACTION_VERBOSE=1 nemo --no-desktop
```

- working version: `4.0.6`
- broken version: `4.4.0`

Something broke between those 2 versions. 

Or maybe did I missed something ? How to display actions debug messages in 4.4.0 ?

Thanks

**Comment by mtwebster** [comment]
I gave actions their own debug flag to make it more consistent with other debugging:
```
NEMO_DEBUG=Actions,Window nemo --debug
```

**Comment by brunetton** [comment]
Thanks for your answer
