### ISSUE TITLE
Rename USB Drives

### ISSUE THREAD

**Issue by ovari** [linuxmint/nemo#2278]
```
 * Nemo version: 4.4.2
 * Distribution: Mint 19.3 Cinnamon
 * 64 bit
 ```

**Issue**

Please enable renaming a USB drive:
1. with a **Rename…** option in the *Contextual Menu*
![image](https://user-images.githubusercontent.com/17465872/71301187-47167a00-23f0-11ea-8f22-948e9a0a8c4b.png)
2. via the **Name:** field in the the *Properties* window
![image](https://user-images.githubusercontent.com/17465872/71301195-53023c00-23f0-11ea-8ca4-82d1e9ca3577.png)

**Other information**

**Rename…** option is shown in the _Contextual Menu_ like for **ods** files
![image](https://user-images.githubusercontent.com/17465872/71301234-d328a180-23f0-11ea-9cda-782a6d4ed80b.png)

Thank you

**Comment by leigh123linux** [comment]
Use gnome-disk-utility as nemo is a file manager not a disk tool.

**Comment by ovari** [comment]
This was a feature in Windows that has been very helpful. Will post a request at `mintstick`. Thank you
