### ISSUE TITLE
No thumbnaills for music and video files after removing xplayer on Linux mint 19.3

### ISSUE THREAD

**Issue by basilky** [linuxmint/nemo#2280]
```
 * nemo 4.4.2
 * Distribution - Mint 19.3
 * Intel Corporation UHD Graphics 620
 * 64 bit
 ```

**Issue**

After upgrading to Linux Mint 19.3, I installed Celluloid and removed Xplayer. After that no thumbnails are getting generated for video and audio files. I have tried deleting ~/.thumbnails and ~/.cache/thumbnails without luck. I have ffmpegthumbnailer installed and I'm able to create thumbnails via command line. Thumbnails are coming back if I reinstall xplayer.

**Comment by basilky** [comment]
I was able to get video previews by removing /usr/share/thumbnailers/xplayer.thumbnailer, so that /usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer will be taken to generate preview. Still not sure how to get mp3 previews(album art cover).

**Comment by smurphos** [comment]
Hi @basilky 

So there are a couple of issues here.

1) xplayer packaging bug

The executable xplayer-video-thumbnailer  is provided by the package xplayer
The xplayer-video-thumbnailer.thumbnailer file is provided by the package xplayer-common

The latter package is a dependency of the former, but not vice-versa so if you remove xplayer without removing xplayer-common you are left with a thumbnailer with no valid executable and no video thumbnails will be produced as you have found.

2) ffmpegthumbnailer doesn't appear to have any support for audio files out of the box or by tweaking it. I've had a hunt around this morning for any working  audio thumbnailers and had a brief stab as making a basic ffmeg based one but without success. So as it stands it looks like the only way to have audio and video thumbnails is to reinstall xplayer in full (or gnome's totem)

**Comment by mtwebster** [comment]
Can you tell me what's expected out of an audio thumbnailer?  I'm not sure I understand the need, and I don't see any difference between having xplayer and not having it with regards to music files.

**Comment by smurphos** [comment]
Hi michael - xplayer's and totem's thumbnailers can both extract a music file's embedded album art if it exists to use as a thumbnail for the file. 

Ffmpeg can also do the extraction at least from the command line.

e.g 'ffmpeg -i /path/to/some/file.mp3  thumbnail.png` will extract the album art as a png

Unfortunately I hit a barrier in that I couldn't convert this into a working thumbnailer (I was targeting mp3 only as I've no idea if other formats support embedded album art). Testing with `NEMO_DEBUG=thumbnails nemo --debug` was producing errors that the temporary files created weren't in a recognised file format.

**Comment by leigh123linux** [comment]
@mtwebster Hr expects something that never existed, there were never any audio thumbnailing only preview.

https://github.com/linuxmint/xplayer/blob/9447412c92b03611571f85eb69bf025e70031f50/src/xplayer-audio-preview.c

I suggest they use nemo-preview instead

**Comment by smurphos** [comment]
Eh?

It's cover art thumbnails for audio files that are gone from 19.2 to 19.3 without xplayer or totem installed...like these...

![screenshot-window-2020-01-07-082302](https://user-images.githubusercontent.com/29017677/71879942-27d55780-3127-11ea-803e-5d5fccc05e5f.png)

**Comment by leigh123linux** [comment]
> 
> Ffmpeg can also do the extraction at least from the command line.
> 
> e.g 'ffmpeg -i /path/to/some/file.mp3 thumbnail.png` will extract the album art as a png
> 

@smurphos  Try using python3-eyed3 instead of ffmpeg

eyeD3 --write-images=DIR mp3_file

**Comment by leigh123linux** [comment]
@smurphos I think I might have a fix to make ffmpegthumbnailer do cover art

```
sudo xed /usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer
```

and add ;audio/flac;audio/mpeg to MimeType line

```
[Thumbnailer Entry]
TryExec=ffmpegthumbnailer
Exec=ffmpegthumbnailer -i %i -o %o -s %s -f
MimeType=video/jpeg;video/mp4;video/mpeg;video/quicktime;video/x-ms-asf;video/x-ms-wm;video/x-ms-wmv;video/x-ms-asx;video/x-ms-wmx;video/x-ms-wvx;video/x-msvideo;video/x-flv;video/x-matroska;application/mxf;video/3gp;video/3gpp;video/dv;video/divx;video/fli;video/flv;video/mp2t;video/mp4v-es;video/msvideo;video/ogg;video/vivo;video/vnd.divx;video/vnd.mpegurl;video/vnd.rn-realvideo;application/vnd.rn-realmedia;video/vnd.vivo;video/webm;video/x-anim;video/x-avi;video/x-flc;video/x-fli;video/x-flic;video/x-m4v;video/x-mpeg;video/x-mpeg2;video/x-nsv;video/x-ogm+ogg;video/x-theora+ogg;audio/flac;audio/mpeg
```

**Comment by basilky** [comment]
Adding audio formats into thumbnailer file doen't help as ffmpegthumbnailer is unable to generate thumbnails from audio. I'm getting following error when trying to generate thumbnail via command line.

Error: decodeVideoFrame() failed: frame not finished

It seems like the error is already reported at https://github.com/dirkvdb/ffmpegthumbnailer/issues/172.

**Comment by leigh123linux** [comment]
@basilky  works fine here with ffmpegthumbnailer-2.2.2

```
[leigh@leigh Desktop]$ ffmpegthumbnailer -i '01-Second Hand News.flac' -o test.png
[swscaler @ 0x55b302f38c00] deprecated pixel format used, make sure you did set range correctly
[leigh@leigh Desktop]$ 
```

**Comment by basilky** [comment]
I'm having only version 2.1.1, from the the Ubuntu 18.04 repo.

**Comment by Coeur-Noir** [comment]
Same « problem » here on ubuntuBudgie 20.04 with Nemo 4.4.2
```
django@ASGARD:~$ dpkg -l | grep thumbnail
ii  ffmpegthumbnailer                     2.1.1-0.2build2                     amd64        fast and lightweight video thumbnailer
ii  libffmpegthumbnailer4v5               2.1.1-0.2build2                     amd64        shared library for ffmpegthumbnailer
ii  libgdk-pixbuf2.0-bin                  2.40.0+dfsg-3                       amd64        GDK Pixbuf library (thumbnailer)
django@ASGARD:~$
``` 
And
```
django@ASGARD:~$ cat /usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer 
[Thumbnailer Entry]
TryExec=ffmpegthumbnailer
Exec=ffmpegthumbnailer -i %i -o %o -s %s -f
MimeType=video/jpeg;video/mp4;video/mpeg;video/quicktime;video/x-ms-asf;video/x-ms-wm;video/x-ms-wmv;video/x-msvideo;video/x-flv;video/x-matroska;video/webm;video/mp2t;audio/flac;audio/mpeg
django@ASGARD:~$ 
```

**Comment by Ahmed-E-86** [comment]
Nemo does not show any thumbnails for Music files. I have this issue on Nemo 4.6.5 - Linux Mint 20 Cinnamon. Is there any temporary fix for now?

**Comment by Jeremy7701** [comment]
In LMDE4 [Debian version of Mint20], nearly all my music files are MP3 and very few contain image thumbnails - although for those music files that contain images, the thumbnailer does work.

```
jeremy@hector:~$ dpkg -l | grep thumbnail
ii  ffmpegthumbnailer                       2.1.1-0.2+b1                        amd64        fast and lightweight video thumbnailer
ii  ffmpegthumbs                            4:18.12.0-1                         amd64        video thumbnail generator using ffmpeg
ii  libffmpegthumbnailer4v5                 2.1.1-0.2+b1                        amd64        shared library for ffmpegthumbnailer
```
It's worth looking at the contents of `/usr/share/thumbnailers/` - mine reads:-
```
ls -lh /usr/share/thumbnailers
-rw-r--r-- 1 root root   99 Dec  1  2018 dia.thumbnailer
-rw-r--r-- 1 root root  803 Feb 12  2020 evince.thumbnailer
-rw-r--r-- 1 root root  259 Feb 17  2016 ffmpegthumbnailer.thumbnailer
-rw-r--r-- 1 root root  213 Aug 30  2018 gnome-font-viewer.thumbnailer
-rw-r--r-- 1 root root  158 Apr 25  2019 librsvg.thumbnailer
-rw-r--r-- 1 root root 2.1K Jan 20  2019 totem.thumbnailer
-rw-r--r-- 1 root root  608 Jun 24 12:47 xreader.thumbnailer
```
In particular, `totem.thumbnailer` has hundreds of mime-types in it.

**Comment by Coeur-Noir** [comment]
_totem.thumbnailer_ is required for mp3 thumbnails.

Or newer version of _ffmpegthumbnailer_ ( depending on what ships your distro ).

**Comment by leigh123linux** [comment]
> _totem.thumbnailer_ is required for mp3 thumbnails. Usually comes with _totem_.
> 

Totem also requires the relevant gstreamer codec to produce the thumbnail.

> Or newer version of _ffmpegthumbnailer_ ( depending on what ships your distro ).
> 
> See #203

**Comment by Ahmed-E-86** [comment]
Installing Totem fixed the issue with audio thumbnails. Thanks for your suggestion.

**Comment by Naushikha** [comment]
Totem fixed thumbnails for me as well, Kudos!
(Linux Mint 20 - Cinnamon)

**Comment by clefebvre** [comment]
This is fixed with a new package called xplayer-thumbnailer.
