### ISSUE TITLE
Pendrive eject wrong work

### ISSUE THREAD

**Issue by kwelf** [linuxmint/nemo#2281]
```
 * Nemo 4.4.2
 * Desktop
 * Mint 19.3
 * Intel HD 630
 * 64bits
 ```

I formated my pendrive with nemo to NTFS and sended a movie with 2GB size to pendrive. After conclusion (progress bar disappear) i tried eject pendrive and works fine but my pendrive led still keep reading for a few minutes and if i push my pendrive from USB port would corrupt my data.

Please improve eject function so it is really safe to remove the USB stick

**Comment by icarter09** [comment]
@kwelf how often have you experienced this issue? I haven't experienced this myself and trying to pinpoint what might be the issue. Thanks.
