### ISSUE TITLE
[Feature Request] Copy/move without first comparing source size and target space

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/nemo#2282]
```
 * Nemo version: 4.4.2
 * Issue with windowed nemo.
 * Distribution: Mint 19.3
 ```

**Issue**
If you try to copy/move a file larger than target space, Nemo starts and contiues with this action without first checking the source size and target space, and gets stuck when no space left, waits a long time, and then gives an error message - if multiple files are involved, some files are copied/moved and some are left at that point.

**Steps to reproduce**
Select and begin to copy/move a file or some files to a target with insufficient space.

**Expected behaviour**
Nemo probably knows total source size and available target space, but it should compare these before starting this such an operation and warn the user if there is not enough space to complete the operation.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
