### ISSUE TITLE
[Feature Request] Displaying size underneath folder icons 

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/nemo#2283]
```
 * Nemo version: 4.4.2
 * Issue with windowed nemo.
 * Distribution: Mint 19.3
 ```

**Issue**
When you select Nemo to display size beneath icon names (**Edit > Preferences > Display > Icon Captions**), you see the size of a file, but number of items in a folder instead of its size.

**Steps to reproduce**
In a Nemo window with files and folders go to the menu **Edit > Preferences > Display > Icon Captions**, and select **Size** in the first row. Then zoom in if necessary to see captions beneath file and folder icon names.

**Expected behaviour**
Nemo should better display something like "_11 items, 33 MB_" beneath folder icon names (without requiring the user to right-click **Properties** for this info.
It's a good idea to display the number of items contained in a folder but often total size is also equally important.

**Comment by mtwebster** [comment]
For this to be at all useful it would need to recurse into subfolders and their subfolders, etc...  which would be way too expensive and time-consuming to do - this is why only the item count is calculated for folders unless explicitly requested (by viewing the folder properties).

Not sure how useful an alternative this would be, but nemo-preview allows you to space-bar on a selected folder, and will immediately popup a window with an ongoing item/size count.

**Comment by Sadi58** [comment]
Understood, thanks!
I definitely prefer improving performance and stability of file manager to adding more features. ;-)

**Comment by herrdeh** [comment]
It's hard to understand to me why this requested feature has not been in existence for decades...
It does not have to be active permanently (yes, this would be an awful performance drain), nevertheless I strongly vote for having it on demand.

Whenever I try to tidy up drives, it's necessary to know where the easy wins are - for that reason I need to sort folders by size. Yes, application as "baobab" do a nice job on that - but why do I need to use an external app for such a crucial job?

**Comment by fires3as0n** [comment]
Every time discussion comes to showing folder sizes in any file viewer, someone mentions that it is a costly operation that will decrease performance. If thinking like that - lets disable GUI at all - it slows down the performance as well. 

Actually in windows I use "Folder size" extension that shows folder sizes, and it is never slow, so it is a myth. 

This is a very required feature, at least as an option, because there are a lot of use cases for it.

**Comment by YellowRoseCx** [comment]
> For this to be at all useful it would need to recurse into subfolders and their subfolders, etc... which would be way too expensive and time-consuming to do - this is why only the item count is calculated for folders unless explicitly requested (by viewing the folder properties).
> 
> Not sure how useful an alternative this would be, but nemo-preview allows you to space-bar on a selected folder, and will immediately popup a window with an ongoing item/size count.

Dolphin does this just fine, but I like Nemo more. Computers are getting faster and faster, I think giving the user an option to enable file size displays based on contents of a user-set folder depth would be extremely helpful. It's very difficult to browse folders that have dozens of subfolders to find the ones with the most data. (on a side note, an option to expand all subfolders 1 deep would be helpful too, but that's for another Issue thread)
