### ISSUE TITLE
Nemo hanging in one folder

### ISSUE THREAD

**Issue by jaheme127** [linuxmint/nemo#2284]
```
Nemo 4.4.2
Mint 19.3 - Std. installation, some Plugins activated (I have this issue I think for at least 1 year - so it's not special about 19.3)
intel Integrated Graphics Controller - Haswell Generation
64 Bit
 ```

**Issue**
When I browse to my downloads folder Nemo hangs for some Seconds or event minutes. 
This only happens in my Downloads folder. In this time nemo cannot be used at all. Browsing a second time to this folder this don't happen again. 

There are folders, pdfs, mp3, pictures and zips in this folder - but I do not notive any special kind of files. There are also not to many files (8 folder, 61 objects) - so that should be okay.

**Steps to reproduce**
Only reproducable in my folder. Unfortunately I can't give you the files but if I can generate some report I could do that

**Expected behaviour**
No blocking time and immediately list of files

**Other information**

**Comment by leigh123linux** [comment]
Duplicates of #2255
