### ISSUE TITLE
[Feature Request] Give examples in file size prefixes options, not just names

### ISSUE THREAD

**Issue by jbn-github** [linuxmint/nemo#2285]
* Nemo version (nemo --version)
$ nemo --version
nemo 4.2.3

 * Is issue with desktop or windowed nemo?
I'm not sure what this is asking.

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Debian GNU/Linux 10 Testing
$ cat /etc/debian_version 
bullseye/sid

 * Graphics hardware *and* driver used
Nouveau with an nVidia video card but this issue is independent of the hardware used.

 * 32 or 64 bit
64 bit

**Issue**
Nemo Display preferences let the user set a file size prefix option. The options use terminology non-technical users are unlikely to understand. The choices should use examples of a filesize to illustrate what the filesize will look like.

The Date format pop-up is helpful because it lists what the current (or near) date looks like.

**Steps to reproduce**
Simply look at the File Size prefix pop-up choices.

**Expected behaviour**
I expected the choices to be examples not terms.

**Other information**
I believe users would like to know what the consequences of their preference choices will be, not learn terminology about the choices and then select the correct term.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
