### ISSUE TITLE
Automatically mount drive when clicking bookmarks

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/nemo#2286]
Currently (Nemo 3.9.0), when bookmarks to folders on unmounted partitions are clicked (in the sidebar), an error message box appears ("Could not find <path>. Please check spelling and try again."). So right now, you have to manually mount the partition via "Devices" section, then click the bookmark again to access it.

It would be nice if Nemo would automatically mount the partition/drive that folder is on, once the bookmark is clicked, without interruption.

**Comment by icarter09** [comment]
Nemo 4.4.2
Linux Mint 19.3

@GitHubIsToxic can you test this out on 4.4.2? I just tried to duplicate this and had no luck. The bookmark was automatically mounted back to the partition/drive.
