### ISSUE TITLE
[Feature request] Persistent removable drive mount state representation

### ISSUE THREAD

**Issue by Fordi** [linuxmint/nemo#2287]
```
 * Nemo version: 4.4.2
 * Is an issue with: desktop nemo.
 * Distribution: Mint 19.3
 * Graphics hardware: Intel Corporation HD Graphics 620
 * Graphics driver: i915
 * Architecture: x86_64
 ```

**Issue**

Post-eject removable drive mount state is not persistently represented by Nemo, resulting in the user not knowing whether or not it's safe to remove the disk if they are doing anything but watching for notifications.

**Steps to reproduce**

1. Insert a USB stick, and write a large amount of data to it
2. Press the eject button in Nemo

**Actual behaviour**

A notification pops up for a short time telling the user not to remove the disk.  Some time later, another notification pops up for a short time telling the user it is safe to remove the disk.

**Expected behaviour**

Something more persistent.  The idea I had was to have the eject button replaced with a burndown wheel (or some other kind of compact progress bar) that represents the size of the write cache, where "100%" is what the size of the write cache was when eject was clicked.  Obviously, if it starts at zero (or under some threshold that means the wait time is going to be trivial), this can be skipped.

The notifications don't actually have to go away or anything; there just needs to be something to show the user in between "don't remove" and "ok, fine" that they still shouldn't remove the drive.

**Other information**

None.

**Comment by Fordi** [comment]
[This looks useful](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats).  Column 13 for the relevant partition shows current IO activity.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
