### ISSUE TITLE
[Feature request] list ZFS pools under devices

### ISSUE THREAD

**Issue by tethragon** [linuxmint/nemo#2290]
Now that at least Ubuntu based distros start to support more actively ZFS, maybe it is time for Nemo to implement some improvements for ZFS support. For example, when creating a ZFS pool (stripped/mirrored/Z1/Z2 etc.) user can access it by entering the corresponding folder where ZFS pool is mounted. Wouldn't it be nice if nemo could list those pools as a "device"? It would be a great UI feature.

Right now, the only way to do that is to create a ZVOL inside the pool and format is as EXT4 or something and then mount this ZVOL from terminal. But this is too much for a "normal" user and also adds overhead to the ZFS pool.

I strongly think that Nemo should be able to "see" zfs pools out of the box and list them under devices, maybe with a separate icon to distinct them from normal devices.

Thank you for reading this request. 

![Selection_001](https://user-images.githubusercontent.com/39238674/71771327-c6a05f00-2f41-11ea-9c32-40b2d014b7aa.jpg)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.ht

**Comment by felbinger** [comment]
Any update on this?

**Comment by Hund** [comment]
Your vdevs show up in the file manager if you mount them under `/media`. :)
