### ISSUE TITLE
Right click to 'Send by Email' fails on filenames with spaces.

### ISSUE THREAD

**Issue by TopView** [linuxmint/nemo#2293]
**Nemo** v3.8.5 (desktop)
**OS:** Debian Buster v10.2 x64
**Desktop:** Cinnamon v3.8.8
**Graphics:** Advanced Micro Devices, Inc. [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v] (prog-if 00 [VGA controller])
**Other:** Thunderbird v68.3.0

**Issue:**  Right click to 'Send by Email' fails on filenames with spaces.

**Steps:**  
Open Nemo on a list of files. 
Right click on a filename with an embedded space.
Click on `Send by Email` in the pop-up menu.

**Results:**
Works okay if selected filename does not have embedded spaces, e.g. `foo`.
Fails if selected filename has any embedded spaces, e.g `foo bar`.

By 'okay', I mean it opens a new email window in Thunderbird with the selected file attached.
By 'Fails', I mean after clicking on `Send by Email` nothing happens.  In particular Thunderbird does not open at all.

**Expected behavior**
It should open Thunderbird with the file attached, even if the file has embedded spaces in it.

I tried adding double quotes to the menu item for Thunderbird, but this didn't affect the issue, i.e.
Under 'Launcher Properties' window, Command: /usr/bin/thunderbird "%u"

**Comment by leigh123linux** [comment]
Works fine here with nemo-4.4.x.

FTR nemo-3.8.x is EOL.
