### ISSUE TITLE
No way to limit number of concurrent FTP connections

### ISSUE THREAD

**Issue by robertc** [linuxmint/nemo#2294]
```
 * Nemo version 4.4.2
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - Fedora 30
 * Graphics hardware *and* driver used - Nvidia GTX 1660 Ti, 440.44
 * 32 or 64 bit - 64 bit
 ```

**Issue**

I was trying to upload a folder to my shared hosting web server, a short way through the upload all access to the server was blocked.  I checked with support and they told me I tried to open hundreds of simultaneous FTP connections so my IP was blacklisted.  I could not find any configuration option in Nemo to limit the number of concurrent connections.

**Steps to reproduce**

1. Try to upload a folder full of files to an FTP server
2. Observe number of connections created

**Expected behaviour**

Most FTP clients have an option to limit the number of concurrent connections to a single server.  Nemo should have an option or a reasonable default.

**Comment by leigh123linux** [comment]
gvfs is responsible for the ftp process not nemo.
Please report is issue at launchpad.

https://launchpad.net/ubuntu/+source/gvfs/+bugs
