### ISSUE TITLE
Nemo no longer gives a notification when an external drive can be safely removed

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/nemo#2295]
Nemo 4.4.2. LM 19.3 Cinnamon.

In the previous versions of LM a notification was generated when one unmounted an external drive in Nemo (by clicking on the icon "safely remove").

**Comment by icarter09** [comment]
![removal notification](https://user-images.githubusercontent.com/4397312/72953045-d6051200-3d61-11ea-99ab-97438e32e2ed.png)

@MenthaSuaveolens is that the notification you are referring to?

**Comment by MenthaSuaveolens** [comment]
@icarter09 Indeed, this is the one I'm referring to. First one gets a message that the device is busy. After a while one finally gets the message that the drive can be safely unplugged.
![DeviceBusyReady](https://user-images.githubusercontent.com/47174957/72967832-84d93a80-3dc2-11ea-963e-ff0b311e915a.jpg)

**Comment by icarter09** [comment]
@MenthaSuaveolens sorry for the late reply. I didn't get the message for the device being busy. I was immediately presented with the drive can be safely unplugged message.

**Comment by icarter09** [comment]
@MenthaSuaveolens are you still experiencing this issue? If so, can you provide a video of the issue occurring? Thanks.

**Comment by MenthaSuaveolens** [comment]
I tried 10 usb-sticks. 9 of them give a notification all right. Only the 1TB external usb-drive gives no notification. Details in the attached screenshot.
![Screenshot-MountedDevice](https://user-images.githubusercontent.com/47174957/104836093-a40e8900-58ab-11eb-9a13-697e4710adce.png)

**Comment by MenthaSuaveolens** [comment]
I notice that when the 1TB device is being plugged in, that at that instance a seg-fault happens in csd-automount. Maybe this is the reason that no notification is issued? Info in file attached
[CrashAutoMount.docx](https://github.com/linuxmint/nemo/files/5825802/CrashAutoMount.docx)

Note. Why can't we paste .odt-documents and do we have to save them as a .docx-document?

**Comment by icarter09** [comment]
I believe you are correct. It's the only one not displaying the notification and also the only one generating a segfault. I'm going to close this ticket out since the main issue looks to be resolved. Please create a new ticket for the issue with the device and segfault. Thanks.

Not sure why github doesn't allow .odt to be pasted.
