### ISSUE TITLE
nemo crashes every time with `Segmentation fault`, no window seen

### ISSUE THREAD

**Issue by leira** [linuxmint/nemo#2296]
```
 * Nemo version (nemo --version)
nemo 3.8.5

 * Is issue with desktop or windowed nemo?
windowed nemo

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
gLinux 5.2.17-1rodete3, which is Debian based.

 * Graphics hardware *and* driver used
nvidia, nvidia driver

 * 32 or 64 bit
64bit
 ```

**Issue**
Every time I try to start nemo, either through icon, or through command line, it crashes with `Segmentation fault`. I attached the [strace](https://github.com/linuxmint/nemo/files/4037789/nemo.strace.tar.gz).

**Comment by leigh123linux** [comment]
sorry 3.8.x is EOL, you should report it to your distro bug tracker instead.
