### ISSUE TITLE
There is no checkbox in the context menu configuration, to remove or add the "Delete" option.

### ISSUE THREAD

**Issue by antrrax** [linuxmint/nemo#2304]
```
 * Nemo version (4.4.2)
 * Distribution - (Mint 19.03 x64
(Cinnamon 4.4.8)
 ```

**Issue**
There is no checkbox in the context menu configuration, to remove or add the "Delete" option.

**Steps to reproduce**
Nemo> main menu> Edit> preferences> context menus

<a href="https://ibb.co/ZSbjVTT"><img src="https://i.ibb.co/xYrkD55/delete.png" alt="delete" border="0"></a>

**Expected behaviour**
Display a checkbox to remove/add the "Delete" from the context menu

**Comment by mtwebster** [comment]
The delete button is already configurable (for now) here:
![image](https://user-images.githubusercontent.com/262776/72768329-05324c80-3bc5-11ea-93e8-89436fe123f4.png)

It needs to be moved to be with the rest but it predated the ability to configure the rest of the items.

**Comment by antrrax** [comment]
Thanks for the answer!
