### ISSUE TITLE
Nemo Crashses: if delete the directory that is opened in the other tab

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/nemo#2307]
```
 * Nemo version : 4.4.2 (can also be on previous versions)
 * Is issue with desktop or windowed nemo? windowed nemo
 * Linux Mint 19.3
 ```

**Issue**

If you delete the directory that is open in the other tab on the same window, nemo crashes.

**Steps to reproduce**

Create a directory and open it in a different tab in the same window. then delete this directory you created on first tab.

**Expected behaviour**

Other tab automatically returning to home directory. Caja and Thunar is also like this.

**Other information**

**Comment by mtwebster** [comment]
I can't reproduce this - it behaves as expected.  Are there files in this new folder?

What distro? Can you provide a coredump (mintreport if in mint)? - Please don't ignore the issue template items.  Thanks

**Comment by kelebek333** [comment]
You can look following record.

![nemo-crashes](https://user-images.githubusercontent.com/1300133/72983878-693a5800-3df3-11ea-9ce5-94817274a9a7.gif)

**Comment by kelebek333** [comment]
No problem when you do the same thing with caja or thunar. You can look caja's record.

![caja-nocrash](https://user-images.githubusercontent.com/1300133/72984127-fd0c2400-3df3-11ea-9c3a-53938449a350.gif)

**Comment by NZamp** [comment]
I can reproduce it on LM 19.3, Cinnamon 4.4.8. 

Just as shown by @kelebek333, after deleting the new directory in a 2-tab window, the window closes. Nemo doesn't crash tho, as other nemo instances and the cinnamon-desktop remain untouched.

Also, if you open another nemo window pointing inside the new directory and delete the directory in the 2-tab window (same steps as before), the 2-tab window closes but the other one goes one dir back (to Home, in this example) and works as expected.

**Comment by shadow73s** [comment]
Hi.
when I delete a Dir, when it is opened as Tab, the whole Window closes and not only the Tab.
Mint 20.2, Nemo 5.0.3
greets

**Comment by Jeremy7701** [comment]
LMDE4 / Nemo 5.0.3 this works for me without any problem.
Also,
I find that a twin pane view (toggle the F3 key) is more accessible than two tabs - it also uses less vertical space.

**Comment by shadow73s** [comment]
Oh, I'm using Cinnamon.
PS: I don't like the twin pane view.
