### ISSUE TITLE
Nemo Build Issues pango found: NO found '1.40.14' but need: '>=1.44.0'

### ISSUE THREAD

**Issue by blueray453** [linuxmint/nemo#2308]
```
 * Nemo version : 4.4.2
 * Distribution - Linux Mint 19.3 Tricia
 * Device-1: Intel driver: i915 v: kernel
 * 64 bit
 ```
**Issue**
```
Native dependency pango found: NO found '1.40.14' but need: '>=1.44.0'
Dependency pango found: NO
```
**Steps to reproduce**

```
$ sudo apt install mint-dev-tools
$ mint-dev-setup
$ apt install gobject-introspection gtk-doc-tools intltool libatk1.0-dev libcinnamon-desktop-dev libexempi-dev libexif-dev libgail-3-dev libgirepository1.0-dev libglib2.0-doc libgtk-3-doc libnotify-dev libxapp-dev libxml2-dev libxt-dev meson
$ mint-dev-build
Please type the number of the project you'd like to build: 32
....
Native dependency pango found: NO found '1.40.14' but need: '>=1.44.0'
Dependency pango found: NO
....
```
**Expected behaviour**

I am expecting to find pango 1.44.0 in the repository. At least I need to know how to update it.

**Comment by mtwebster** [comment]
Is this actually breaking the build using mint-dev-tools?  This is a version check only to enable code specific for a newer version (I've been meaning to print a note out after that line to avoid confusion such as this report) - 1.40.14 is fine

**Comment by blueray453** [comment]
Now nemo is in `/home/ismail/Sandbox/nemo`

The build was successful.

I need to make some changes to the source code of nemo. To be more specific patch with https://github.com/stevenxxiu/nemo-better-sorting-git and then run the newly built nemo as my default file browser (replace existing nemo). How can I do that? 

When I use `$ mint-dev-build` it says -

```
This command does the following:
    - Deletes all build outputs in your Sandbox (~/Sandbox/*_*)
    - Deletes the local version (along with any local changes) for the selected project(s) (~/Sandbox/<projectname>)
    - Downloads and compiles the selected project(s) from Github's master branch(es)
    - Installs the packages produced by the compilation (and overrides local versions)
```

I do not want to delete the local version of nemo. I want to keep the changed nemo directory and build it. Then I need to make the newly built nemo my default file browser (replace existing nemo). How can i do that?

**Comment by blueray453** [comment]
By the way, I can now see `HEAD is now at e3f54bd meson.build: Don't be confusing when pango 1.44.0 isn't found.`

**Comment by mtwebster** [comment]
Deleting the local version is no big deal:

If you let it install the modified version, it will replace the existing one on your machine.  But if you go into mintupdate and refresh, suddenly it has a nemo update there - the updater will always want to replace what you have with its own version (the one you have now).  At that point you can just right-click that update and choose to ignore it.  If you ever want to revert to the current 'official' version, just remove it from the ignore list and let mintupdate run.  There's really not a simple way to have both versions exist on your machine.

You could also just deal with nemo's source by itself:

```
git clone https://github.com/linuxmint/nemo.git

####(you'll need to have turned on 'source code repositories' in Software Sources)
sudo apt-get build-dep nemo   

### enter the nemo folder, run:
dpkg-buildpackage
```
The finished .deb files will be in one folder up, run `dpkg -i *.deb` to install them.  If you make changes to the source simply run `dpkg-buildpackage` again.

I'm sure there's a way to work this thru mint-dev-tools, but I'm having issues with it on my machine at the moment so I can't check.

**Comment by blueray453** [comment]
`mint-dev-tools` helped me find the dependencies though. In my case those were -

`gobject-introspection gtk-doc-tools intltool libatk1.0-dev libcinnamon-desktop-dev libexempi-dev libexif-dev libgail-3-dev libgirepository1.0-dev libglib2.0-doc libgtk-3-doc libnotify-dev libxapp-dev libxml2-dev libxt-dev meson`
