### ISSUE TITLE
Plugins are not displayed in alphabetical order, which can be a problem (though in the context menu the problem rights itself with a reboot)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2317]
```
 * Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Min 19.3
 * Graphics hardware *and* driver used: Intel onboard
 * 32 or 64 bit: 64
 ```

**Issue**

Within both the plugins pane and - more consequentially - _within the context menu_, plugins are not displayed in alphabetical order. As you should be able to see from the plugins I use - indicated below - this is inconvenient.

Screenshots:

![image](https://user-images.githubusercontent.com/47056543/73994893-fb437400-494e-11ea-9783-f09450bb1f77.png)

![image](https://user-images.githubusercontent.com/47056543/73994902-026a8200-494f-11ea-81b8-75a94296c7a9.png)

I cannot supply a screenshot of the plugins as they appear in the context menu. (I cannot do so, I think, because of problems X has taking screenshots of context menus.) I can tell you though that, there, they are in another order again (i.e. not the proper alphabetical order in which the action files appear within a folder, nor in the order shown in the plugin list). For, they appear in this order:

PC - copy to
PC - move to
SYNC - copy to
SYNC - move to
CURRENT - move to
CURRENT - copy to

I will try a reboot (for, I have been modifying my plugin files).

**Steps to reproduce**

Unclear. Possibly:

- add an 'action' files to Nemo the name of which starts with the letter 'z' and restart Nemo;
- add an action file the name of which starts with the letter 'h' and restart Nemo;
- add an 'action' files to Nemo the name of which starts with the letter 'a' and Restart Nemo.
- look at the order of the plugins in (i) the plugin pane, (ii) the context menu.

**Expected behaviour**

The plugin list should be ordered alphabetically and certainly the content menu plugin items should be.

**Other information**

**Comment by LinuxOnTheDesktop** [comment]
_After a reboot, the context menu displayed plugins in the right order._ (I am pretty sure I had closed all nemo instances when I did the testing above, though.) So, a reboot solves the main problem, so there is nothing very severe here. However, the plugin menu - the one in Nemo where one _manages_ the plugins - remains in the wrong order, even after rebooting.

**Comment by smurphos** [comment]
See - https://github.com/linuxmint/nemo/issues/2183#issuecomment-562294068

**Comment by LinuxOnTheDesktop** [comment]
Thanks, Smurphos. I do not fancy recompiling Nemo, so I will use the shell script on that page.

**Comment by mtwebster** [comment]
Fixed in the next release (https://github.com/linuxmint/nemo/pull/2360)
