### ISSUE TITLE
Make nemo-desktop aware of xdg user desktop dir changes

### ISSUE THREAD

**Issue by norbusan** [linuxmint/nemo#2321]
```
 * Nemo version (nemo --version): 4.4.2
 * Is issue with desktop or windowed nemo? desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Debian
 * Graphics hardware *and* driver used: nvidia 440.59
 * 32 or 64 bit: 64 bit
 ```

**Issue**

changes in the XDG user dirs, in particular the desktop directory are not reflected on the desktop window.

Interestingly, nemo already listens to changes to `~/.config/user.dirs` in `libnemo-private/nemo-file-utilities.c` where `xdg_dir_cache_changed_cb` is already called on each change of that file.

If the Desktop folder is shown on the root window, it would be nice if the nemo desktop window would actually reflect the changes to the Desktop. This way we could easily implement different Desktop dirs for different workspaces, without the need to `nemo-desktop -q ; nemo-desktop`.

**Steps to reproduce**

Call
```
xdg-user-dirs-update --set DESKTOP '$HOME/AnotherDesktop'
```
but the Nemo root window is not updated

**Expected behaviour**

Changes are reflected.

**Other information**

**Comment by leigh123linux** [comment]
Try using the proper path

```
xdg-user-dirs-update --set DESKTOP '$HOME/AnotherDesktop'
directory value must be absolute path (was $HOME/AnotherDesktop)
```
```
xdg-user-dirs-update --set DESKTOP '/home/leigh/Desktop'
```

Then kill and restart nemo-desktop

**Comment by norbusan** [comment]
Hi @leigh123linux 
I know about how to set the proper values, my issue was about the need to kill/restart nemo-desktop, which I find disturbing, visually (small flash) as well as programmatically.

The solution with killing and restarting nemo I have mentioned in the original issue text, if you read it completely.

So this is not the solution to what I asked for.
