### ISSUE TITLE
How i can disable "Run as Root" feature?

### ISSUE THREAD

**Issue by hasanmerkit** [linuxmint/nemo#2322]
I created Custom-OS and im not using Nautilus's desktop feature. (I think Nemo's desktop better.)
But in context menu have "Run as root" and i want to remove this menu item. How i can do?
Thanks.

Version: 3.6.5

**Comment by mtwebster** [comment]
You can control the visibility of nearly all menu items in nemo's preferences:

![image](https://user-images.githubusercontent.com/262776/74615167-126f2800-50ec-11ea-91f7-da27c64babef.png)

Note, this only affects the context menus, *not* the dropdown menus.

**Comment by hasanmerkit** [comment]
@mtwebster, my preferences menu is different...
Screenshot: https://i.hizliresim.com/b98OEV.png

**Comment by hasanmerkit** [comment]
@mtwebster, my preferences menu is different...
Screenshot: 
![Adsız](https://user-images.githubusercontent.com/18331715/74615301-8af7d800-5130-11ea-9d83-a3aca0a06fc5.png)

**Comment by mtwebster** [comment]
Oh sorry I didn't notice that version - you'll have to upgrade for this - 3.6 is two years old, you need 4.4.

**Comment by hasanmerkit** [comment]
> Oh sorry I didn't notice that version - you'll have to upgrade for this - 3.6 is two years old, you need 4.4.

How i can update?
apt-get update && apt-get upgrade commands says all packages up-to dated.

(My custom os designed using: Ubuntu 18.04 x64)

**Comment by mtwebster** [comment]
You can try installing the deb packages in the tar.gz file here: https://github.com/linuxmint/nemo/releases/tag/master.mint19

Those should work fine on 18.04, provided you have xapps >= 1.4.0
