### ISSUE TITLE
Updating for Ubuntu 18.04 based OS?

### ISSUE THREAD

**Issue by hasanmerkit** [linuxmint/nemo#2323]
I have nemo 3.6.5 version, how can update?
apt update && apt upgrade output result;
All packages already updated.

Thanks.

My OS: Ubuntu Minimal 18.04 x64 with Gnome

**Comment by leigh123linux** [comment]
Try a more recent PPA repo as we don't provide ubuntu packages.

**Comment by hasanmerkit** [comment]
Can you recomment a PPA for me?

**Comment by leigh123linux** [comment]
Try

https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon

**Comment by hasanmerkit** [comment]
> Try
> 
> https://launchpad.net/~embrosyn/+archive/ubuntu/cinnamon

Thanks, its installed newer version but i need Nemo 4.4 and i cant find on Google.
It's possible?
