### ISSUE TITLE
Inconsistent alignment in Size list column.

### ISSUE THREAD

**Issue by m-kru** [linuxmint/nemo#2325]
Why fields of the `Size` column are aligned to the right, while all other columns are aligned to the left? Even the title `Size` is aligned to the left. What is the purpose of this inconsistency?
![nemo](https://user-images.githubusercontent.com/26227737/75111528-2dd1ba00-563b-11ea-8a2d-76dc45d4240d.png)

**Comment by icarter09** [comment]
It allows for easier viewing when changing the order to either ascending/descending. Chrome dev tools does this as well.
