### ISSUE TITLE
BTRFS raid5 not mounting on newer kernel 4.15.0-70++

### ISSUE THREAD

**Issue by kokokranc** [linuxmint/nemo#2331]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
Failed to mount BTRFS filesystem when using kernel > 4.15.0-50

dmesg:
[  281.708374] BTRFS info (device sdd): disk space caching is enabled
[  281.708376] BTRFS info (device sdd): has skinny extents
[  281.733804] BTRFS info (device sdd): bdev /dev/sdd errs: wr 0, rd 63, flush 0, corrupt 8, gen 0
[  281.733808] BTRFS info (device sdd): bdev /dev/sde errs: wr 0, rd 0, flush 0, corrupt 0, gen 3
[  281.733810] BTRFS info (device sdd): bdev /dev/sdf errs: wr 0, rd 0, flush 0, corrupt 0, gen 3
[  281.733812] BTRFS info (device sdd): bdev /dev/sdg errs: wr 3761, rd 3803, flush 5, corrupt 0, gen 0
[  282.560394] BTRFS critical (device sdd): corrupt leaf: root=2 block=1729445888 slot=51 bg_start=33631669977088 bg_len=3221225472, invalid block group used, have 3457822720 expect [0, 3221225472)
[  282.566230] BTRFS critical (device sdd): corrupt leaf: root=2 block=1729445888 slot=51 bg_start=33631669977088 bg_len=3221225472, invalid block group used, have 3457822720 expect [0, 3221225472)
[  282.566383] BTRFS critical (device sdd): corrupt leaf: root=2 block=1729445888 slot=51 bg_start=33631669977088 bg_len=3221225472, invalid block group used, have 3457822720 expect [0, 3221225472)
[  282.566396] BTRFS error (device sdd): failed to read block groups: -5
[  282.618781] BTRFS error (device sdd): open_ctree failed

the disk is perfectly fine and can be mounted properly on older kernels. False positive preventing mount?

**Steps to reproduce**
mount BTRFS raid5 on kernel 4.15.0-70 and above

**Expected behaviour**
not mounted with error:
[  281.708374] BTRFS info (device sdd): disk space caching is enabled
[  281.708376] BTRFS info (device sdd): has skinny extents
[  281.733804] BTRFS info (device sdd): bdev /dev/sdd errs: wr 0, rd 63, flush 0, corrupt 8, gen 0
[  281.733808] BTRFS info (device sdd): bdev /dev/sde errs: wr 0, rd 0, flush 0, corrupt 0, gen 3
[  281.733810] BTRFS info (device sdd): bdev /dev/sdf errs: wr 0, rd 0, flush 0, corrupt 0, gen 3
[  281.733812] BTRFS info (device sdd): bdev /dev/sdg errs: wr 3761, rd 3803, flush 5, corrupt 0, gen 0
[  282.560394] BTRFS critical (device sdd): corrupt leaf: root=2 block=1729445888 slot=51 bg_start=33631669977088 bg_len=3221225472, invalid block group used, have 3457822720 expect [0, 3221225472)
[  282.566230] BTRFS critical (device sdd): corrupt leaf: root=2 block=1729445888 slot=51 bg_start=33631669977088 bg_len=3221225472, invalid block group used, have 3457822720 expect [0, 3221225472)
[  282.566383] BTRFS critical (device sdd): corrupt leaf: root=2 block=1729445888 slot=51 bg_start=33631669977088 bg_len=3221225472, invalid block group used, have 3457822720 expect [0, 3221225472)
[  282.566396] BTRFS error (device sdd): failed to read block groups: -5
[  282.618781] BTRFS error (device sdd): open_ctree failed

**Other information**
not able to mounted degraded as well

ran scrub on older kernel and the drive is fine

**Comment by leigh123linux** [comment]
This is a kernel issue not nemo.
