### ISSUE TITLE
Show full network paths in title bar

### ISSUE THREAD

**Issue by u8sand** [linuxmint/nemo#2333]
```
 * Nemo version: 4.4.2
 * Windowed nemo
 * ArchLinux
 * Nvidia
 * 64 bit
 ```

**Issue**

I have `Preferences -> Display -> Window and Tab Titles -> Show the full path in the title bar and tab bars` enabled. It works properly for local paths, but not for remote ones (specifically with sftp). It would be ideal if the remote path was displayed together with the protocol prefix (as it appears in the path textbox).

![image](https://user-images.githubusercontent.com/1341861/77177113-637f8c80-6a9b-11ea-824b-041a04be85a9.png)

![image](https://user-images.githubusercontent.com/1341861/77177098-5cf11500-6a9b-11ea-9be7-1d78d82fffc7.png)

**Steps to reproduce**

See screenshots. Enable `Show the full path in the title bar and tab bars` and visit a remote location such as sftp.

**Expected behaviour**

I expect to see `Downloads - sftp://localhost/home/u8sand/Downloads` in my title bar when I go there, not just `Downloads`.

**Other information**

Thanks!

**Comment by icarter09** [comment]
@eli-schwartz
