### ISSUE TITLE
Application itself is what dictates the look of the buttons 

### ISSUE THREAD

**Issue by s1-ranjan** [linuxmint/nemo#2335]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
The buttons in Nemo for Selected Items and Empty Trash are dictated by the theming modes, the theme fails to dictate those buttons.

**Steps to reproduce**
Delete any file or folder and visit the trash and observe the top bar buttons in the Trash.

**Expected behaviour**
The theme should dictate the Restore Selected Item and Empty Trash buttons in Nemo.

**Other information**

**Comment by JosephMcc** [comment]
I'm not a fan of adding suggested and destructive styles to these. I like the current styling. If a theme really wants to color them they could probably use the proper hierarchy of selectors to do so.
