### ISSUE TITLE
Incorrect size unit reported in the properties dialog

### ISSUE THREAD

**Issue by eduardosm** [linuxmint/nemo#2340]
```
 * Nemo version: 4.4.2
 * Distribution: Manjaro
 * 64 bit
 ```

**Issue**

The properties dialog say the size of a file in bytes, but it incorrectly says that the value is in bits.

![bits](https://user-images.githubusercontent.com/761151/77365777-fbf56580-6d56-11ea-9fa0-6aaf8b49497f.png)

**Steps to reproduce**

Right click on a file, properties, check the size.

**Expected behaviour**

Size in bytes.

**Other information**

Only happens if units are configured to use binary prefixes.

The correct unit is shown for directories.

**Comment by leigh123linux** [comment]
#2208
