### ISSUE TITLE
Re-introduce file linking 

### ISSUE THREAD

**Issue by Mek101** [linuxmint/nemo#2343]
```
 * Nemo 4.4.2
 * Mint 19.3

 ```

**Issue**
Re-introduce copy or link dropdown menu with centra mouse drag and drop or make link menu option

**Other information**
I use LM since 17.3, and I remember clearly that, when dragging a file or folder with the central mouse button, Nemo used to open a dropdown menu asking if the user wanted to create a link to the file or a copy. It was extremely useful, and since it has been removed having to open the terminal and scout the internet for how to use ln has been a pain.
Is it possible to reintroduce this feature? Even disabled by default and activable on the nemo settings would be good.
In alternative, the option in the right-click dropdown menu to create a link of the selected file.

Thank you.

**Comment by leigh123linux** [comment]
Look in nemo preferences/ context menus/ then check 'make link'

**Comment by Mek101** [comment]
Do I delete this?

**Comment by leigh123linux** [comment]
Closing is enough.

**Comment by smurphos** [comment]
@Mek101 - you can also drag and drop holding left Alt key as you drop to get a content menu with copy / move / link as options.

**Comment by Coeur-Noir** [comment]
Nemo 4.0.6 here and I can't find anything related to context-menu or make link entry in preferences : 
![Capture d’écran du 2020-03-28 17-01-05](https://user-images.githubusercontent.com/1895947/77864953-0ff40800-722c-11ea-9edd-da2ed0483c26.png)
…there is no « context-menu » between toolbar and plugins in the left panel.
![Capture d’écran du 2020-03-30 02-15-14](https://user-images.githubusercontent.com/1895947/77865057-a6c0c480-722c-11ea-9697-86f738d3fcfd.png)
…there is no « use full context menu » in Menu→Edit

**Comment by mtwebster** [comment]
It appears that version is too old.  More than likely you can restore the link menu item by right-clicking a file, and there should be a + symbol at the right end of the first menu entry, you can click that to expand the menu, it should have the link option
