### ISSUE TITLE
Odd one--Quake emulator//forcing screen resolution on DVI-HDMI screens...Lot goin on

### ISSUE THREAD

**Issue by dcj9** [linuxmint/nemo#2346]
```
 * Nemo version (nemo --version)
 * Is issue with desktop or windowed nemo?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
The buttons look a lil strange, but you can change it back by just forcing the resolution. If you got here. You can put it back :)

**Steps to reproduce**

Forcing screen resoultion on a DVI screen 0, HDMI screen1
**Expected behaviour**

Buttons look a lil funky? I know thats real helpful. Im still gettin used to linux ;) excuse me Oh also, It may have had somethin to do with the fact I was nerding out and for some reason wanted a quake ide looking command prompt that kde...that coulda done it doo cause that sucker never opened

**Other information**

**Comment by icarter09** [comment]
@dcj9 can you post the nemo version and your distribution info? Can you also provided a screen capture of what you are seeing/experiencing? Thanks.
