### ISSUE TITLE
Expanded long filenames of selected icons occlude other icons/filenames.

### ISSUE THREAD

**Issue by bjd-pfq** [linuxmint/nemo#2349]
nemo 4.4.2

When selecting files that have long filenames, the abbreviated filename gets expanded, and the icon + filename attain the selected color.
However, for long filenames, the totality of the selected icon+selected expanded filename quickly starts to occlude other icons.

The way to solve this is to unexpand the filename after the selection has been done.

I hope the screenshot clarifies the problem.

P.S.
It would also be nice if the expanded filename **_on hover_** had an even background, making the filename more legible; the screenshot happens to also show such an expanded filename, almost illegible if it weren't for the tooltip.

![screenshot-20200410-212232](https://user-images.githubusercontent.com/3042621/79018308-c8e30c80-7b73-11ea-8c71-1acd64ce9be0.png)

**Comment by mtwebster** [comment]
The expansion should only be occurring when hovering an individual item.  Once you are no longer hovering, the item should revert to the shortened label.  I can reproduce this, and it's definitely a bug.

I'm not sure I follow you on the second issue - the blue background underlies the full label, I think the uncovered partial text is the label of the item *beneath* the selected one.

The icon partially obscuring the expanded label on the left-most selection is most likely a side-effect from the first issue.

**Comment by bjd-pfq** [comment]
My first (main) issue is the expansion stays when selecting (in this case with Ctrl-Mouse-1) files, occluding icons/labels in the next row, below (the blue selected icons/labels).

My P.S. refers to the hover over another icon, in the third row, causing the expansion of the label, as it should, but the text is almost illegible, because it is laid over the icon and label of the fourth row; if this expanded label had an even background (just for the duration of the hover & expansion) it would be legible. In this case, since it is just a momentary occlusion of the icon+label below it, the occlusion isn't problematic.

**Comment by mtwebster** [comment]
I fixed the selected item issue (remaining expanded when selected), but the second issue doesn't happen here:
![Screenshot from 2020-06-02 22-47-20](https://user-images.githubusercontent.com/262776/83590259-58c58700-a523-11ea-9b98-280aa9e5afc9.png)
The hovered item expands, but with a white background under the text to distinguish it from the item below it.

What theme are you using?  Perhaps try a different one? (controls/gtk theme in cinnamon-settings).
