### ISSUE TITLE
Nemo plugin list is completely empty

### ISSUE THREAD

**Issue by raniesantos** [linuxmint/nemo#2354]
- Nemo **4.4.2**
- Is issue with desktop or windowed nemo? I don't know what this question means
- Mint 19.3
- Graphics hardware *and* driver used
  - NVIDIA GeForce GTX 750
  - sudo lshw -c video | grep 'configuration' output: `configuration: driver=nvidia latency=0`
- 64 bit

**Issue**

Nemo plugin list is completely empty.

![nemo](https://i.imgur.com/6qFfMPf.png)

![synaptic](https://i.imgur.com/0Ml7oUP.png)

**Steps to reproduce**

Sadly, no idea what caused this.

**Expected behaviour**

Plugins should be shown in Nemo preferences.

**Comment by mtwebster** [comment]
Install python-nemo, not nemo-python (sorry for the confusion, this is something debian maintainers did at some point, it's a very old version (3.6).

**Comment by raniesantos** [comment]
The package python-nemo is installed, I also just now reinstalled it through Synaptic. No change.

**Comment by raniesantos** [comment]
The nemo-folder-color-switcher.py file seems to be causing problems. When I remove it the plugins appear in Nemo's preferences again.

Another thing to note is that kdeconnect-send-nemo.py just doesn't show up no matter what.

The plugins for emblems and media columns appear in the list and work normally as long as the folder color switcher is removed.

Here is a zip of all 4 python files and link them here in case anyone wants to check/test them.

[usr_share_nemo-python_extensions.zip](https://github.com/linuxmint/nemo/files/4487330/usr_share_nemo-python_extensions.zip)

**Comment by raniesantos** [comment]
Solution found, closing issue.

Caused by conflict between my custom icon theme and folder color plugin.

Solved by uninstalling folder color plugin.
