### ISSUE TITLE
Drag & drop from trash moves file to wrong destination

### ISSUE THREAD

**Issue by schorschii** [linuxmint/nemo#2355]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? windowed nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.1
 * Graphics hardware *and* driver used: NVIDIA proprietary driver v435
 * 32 or 64 bit: 64 bit
 ```

**Issue**
When moving a file out of the trash via drag & drop, it is not moved to the correct drag & drop destination, but instead to the "original" folder, where the file was before it was moved to trash.

**Steps to reproduce**
1. create a file on your desktop
2. move this file to trash
3. drag&drop this file from trash to your documents folder
4. file will appear on desktop again, but not in documents folder, where the user would expect it after the drag&drop action

**Expected behaviour**
File should appear where the user drops it when performing an drag&drop action.

**Comment by leigh123linux** [comment]
Fixed in 4.4.2

https://github.com/linuxmint/nemo/commit/0599ae2839263db660c793dd53f9ed70abb9258d
