### ISSUE TITLE
Client-side decoration

### ISSUE THREAD

**Issue by m-kru** [linuxmint/nemo#2357]
Is there any way to enable Client-side decoration (CSD) in nemo? If no, are there any plans to add such functionality? Some programs can be configured to use CSD or the traditional Title Bar. It would be really nice if user could configure this.

**Comment by ManIVIctorious** [comment]
You can use the
`export GTK_CSD=1`
environment variable to force GTK to use CSDs, but I am not sure if this is what you want to achieve. Basically it lets GTK draw the titlebar instead of metacity but it won't look that much different

**Comment by m-kru** [comment]
Indeed, it has an impact on some applications, however Nemo is not one of them :smiley: .

**Comment by m-kru** [comment]
I was wrong, it affects Nemo. I just had to reboot the Cinnamon (no idea why).

**Comment by ManIVIctorious** [comment]
You had to restart nemo (note that keeps nemo running in background even when no windows are open)

**Comment by Diegovsky** [comment]
Is it possible to add a dconf setting to override this manually?

**Comment by mtwebster** [comment]
What's the point? It won't be populated with anything, and as a result, would look pretty much the same.

normal decorations:
![image](https://user-images.githubusercontent.com/262776/131702950-1fb92271-7d06-4bec-8bd4-a6c501dc5d74.png)


GTK_CSD=1 nemo
![image](https://user-images.githubusercontent.com/262776/131702878-2e24a4a5-6b02-4b36-a182-be7fd6f823b6.png)

No current plans to change this.

**Comment by Diegovsky** [comment]
Oh sorry. I thought GTK_CSD=1 "merged" the titlebar with the headerbar.

Also, I reckon this might not be the right place to ask, but is it possible to use CSD like nautilus does?

**Comment by mtwebster** [comment]
It's definitely possible, but it would be some work, and if we put toolbar items in it, the toolbar would be *above* the menubar. None of us are big fans of 'popover' menus, or shoving everything into a hamburger button. It'd be a big ui change, not something we're keen on for one of the primary components for Cinnamon (or any Cinnamon components, for that matter).

**Comment by Diegovsky** [comment]
That's fine, I love nemo the way it looks now. Thanks for taking the time to answer me :)
