### ISSUE TITLE
serious compiler warnings

### ISSUE THREAD

**Issue by douglarek** [linuxmint/nemo#237]
I: Program is using uninitialized variables.
[  283s]    Note the difference between "is used" and "may be used"
[  283s] W: nemo uninitialized-variable nemo-window-menus.c:347
[  283s] 
[  283s] I: A function uses a 'return;' statement, but has actually a value
[  283s]    to return, like an integer ('return 42;') or similar.
[  283s] W: nemo voidreturn nemo-icon-view.c:1200
[  283s] W: nemo voidreturn nemo-list-view.c:2849
[  283s] W: nemo voidreturn nemo-view.c:683
[  283s] 
[  283s] I: Program returns random data in a function
[  283s] E: nemo no-return-in-nonvoid-function nemo-view.c:690
[  283s] 
[  283s] I: Program returns random data in a function
[  283s] E: nemo no-return-in-nonvoid-function nemo-view.c:690

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for over 2 years?
