### ISSUE TITLE
Nemo crashes by viewing properties of malformed file

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/nemo#2371]
```
 * Nemo version 4.4.2 (windowed)
 * Mint 19.3 64-bit
 * Display: x11 server: X.Org 1.19.6 driver: modesetting
 * Graphics hardware: Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.0.6 - kisak-mesa PPA
 ```

**Issue**
The main problem is actually the archive manager (file-roller) unpacking an old DOS executable the wrong way, **but** the resulted file crashes Nemo when you want to view its properties.

**Steps to reproduce**
- download the [Commander Keen 4 shareware](http://legacy.3drealms.com/keen4/) - 4keen.zip
- unpack it and enter its directory (4keen)
- right-click INSTALL.EXE and click Properties **or** select INSTALL.EXE and press Alt+Enter

**Expected behaviour**
Nemo should display the file's properties, as broken as they are. In the terminal it's displayed like this:
```
lrwxrwxrwx 1 nicu nicu      3 mai  3 03:01 INSTALL.EXE -> 'MZ'$'\210'
```

**Other information**
Midnight Commander 4.8.19 was able to properly unpack the archive and both the installer and the installed game worked in DOSBox, so at least I know the archive is not corrupt or anything.

I also reported this issue [in Gnome's gitlab](https://gitlab.gnome.org/GNOME/file-roller/-/issues/86).

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I'm not able to duplicate this issue. I downloaded the file listed above and was about to right click on INSTALL.EXE and view the file properties.

**Comment by kneekoo** [comment]
It's still a valid issue:

> System: Host: nas Kernel: 5.4.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 Desktop: MATE 1.22.2 
> Distro: **Linux Mint 19.3** Tricia base: Ubuntu 18.04 bionic 
> CPU: Topology: Quad Core model: Intel Core i5-4690K bits: 64 type: MCP arch: Haswell rev: 3 L2 cache: 6144 KiB 
> Graphics: Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics vendor: ASUSTeK driver: i915 v: kernel 
> Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
> OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.2.2 - kisak-mesa PPA direct render: Yes

Engrampa version: 1.22.2
Caja version: 1.22.2

![caja-file-properties-broken-exe](https://user-images.githubusercontent.com/566306/99219795-b3a32000-27dd-11eb-833f-c665b1e316a3.png)

**Comment by leigh123linux** [comment]
> It's still a valid issue:
> 
> > System: Host: nas Kernel: 5.4.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 Desktop: MATE 1.22.2
> > Distro: **Linux Mint 19.3** Tricia base: Ubuntu 18.04 bionic
> > CPU: Topology: Quad Core model: Intel Core i5-4690K bits: 64 type: MCP arch: Haswell rev: 3 L2 cache: 6144 KiB
> > Graphics: Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics vendor: ASUSTeK driver: i915 v: kernel
> > Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz
> > OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.2.2 - kisak-mesa PPA direct render: Yes
> 
> Engrampa version: 1.22.2
> Caja version: 1.22.2
> 
> ![caja-file-properties-broken-exe](https://user-images.githubusercontent.com/566306/99219795-b3a32000-27dd-11eb-833f-c665b1e316a3.png)

We don't fix caja issues here.

**Comment by kneekoo** [comment]
@leigh123linux My initial report mentions Nemo. I provided the Caja screenshot as well, because it points out to a common issue, likely a library used by both Nemo and Caja.

**Comment by leigh123linux** [comment]
@kneekoo  The real issue is file-roller's unpacking of the zip file.
The link target on your screenshot indicates a missing font package.

![screenshot-window-2020-11-16-113024](https://user-images.githubusercontent.com/1299302/99247669-2e306780-27ff-11eb-8929-47a391512b3c.png)

**Comment by kneekoo** [comment]
That's present in your screenshot as well, but it's not really a font problem - it's just character that is not supposed to be rendered at all, from a binary file. :)

Do you think it would have a positive impact on the bug report I posted in Gnome's gitlab if you or another Mint developer would add input there? Maybe it's something that they forgot to backport, or who knows. It would be nice for this to be closed with a fix.

**Comment by leigh123linux** [comment]
> Nemo 4.6.5
> Mint 20 64bit
> 
> I'm not able to duplicate this issue. I downloaded the file listed above and was about to right click on INSTALL.EXE and view the file properties.

I get a warning message caused by the ascii character (�)

```
[leigh@leigh ~]$ nemo ~/Desktop/4keen/
Initializing nemo-image-converter extension

(nemo:18338): Pango-WARNING **: 12:53:04.408: Invalid UTF-8 string passed to pango_layout_set_text()

(nemo:18338): Pango-WARNING **: 12:53:04.415: Invalid UTF-8 string passed to pango_layout_set_text()

(nemo:18338): Pango-WARNING **: 12:53:04.474: Invalid UTF-8 string passed to pango_layout_set_text()
```

**Comment by leigh123linux** [comment]
Latest nautilus produces the same warning.

```
$ nautilus .

(org.gnome.Nautilus:19862): Pango-WARNING **: 13:51:58.776: Invalid UTF-8 string passed to pango_layout_set_text()

(org.gnome.Nautilus:19862): Pango-WARNING **: 13:51:58.781: Invalid UTF-8 string passed to pango_layout_set_text()

(org.gnome.Nautilus:19862): Pango-WARNING **: 13:51:58.830: Invalid UTF-8 string passed to pango_layout_set_text()
```

**Comment by leigh123linux** [comment]
> That's present in your screenshot as well, but it's not really a font problem - it's just character that is not supposed to be rendered at all, from a binary file. :)
> 
> Do you think it would have a positive impact on the bug report I posted in Gnome's gitlab if you or another Mint developer would add input there? Maybe it's something that they forgot to backport, or who knows. It would be nice for this to be closed with a fix.

If the issue doesn't reproduce there is nothing to fix, maybe locale makes a difference?

```
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by mtwebster** [comment]
It's incorrectly identifying this file as a link, so it looks for the link target (and doesn't find it) which may explain why it's rendering garbage. Unzip handles this fine.

If you gvfs-info on INSTALL.exe after running `tar xf 4keen.zip` you get a valid normal file.  If you check after running `file-roller -e 4keen.zip .` you end up with a broken symlink file.

Nemo/caja can't 'tell' that file-roller messed up, they're only displaying what they think they should for a symlink. The crash could be caused by what's being displayed being uninitialized memory or the wrong memory location. We're trying to fit a square peg into a round hole (wrong file type).

**Comment by Jeremy7701** [comment]
Even the `stat` command incorrectly identifies INSTALL.exe as a link and says it's 3 bytes long, so user-space programs haven't a chance.
GIGO!

**Comment by kneekoo** [comment]
I was hoping that a developer would comment in the [Gnome ticket](https://gitlab.gnome.org/GNOME/file-roller/-/issues/86) I opened - maybe that will set things in motion. As long as file-roller breaks that file so badly, it needs a fix, and with Nemo being affected by this issue, you could add your input there.
