### ISSUE TITLE
Properties window incorrectly shows file size in bits rather than bytes in Binary (long format)

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo#2373]
```
 * Nemo version 4.4.2
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Mint 19.3 
 * Graphics hardware *and* driver used
steve@steve-Inspiron-5580:~$ inxi -G
Graphics:  Device-1: Intel driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.5 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics (Whiskey Lake 3x8 GT2) v: 4.5 Mesa 19.2.
 * 64 bit
 ```

**Issue**

The file properties dialog incorrectly reports file size in bits when the value is actually bytes with the File Size preference set to Binary (Long Format)

**Steps to reproduce**

Open Nemo > Edit > Preferences > Display - switch File Size to Binary (Long Format)

In list view compare the output in the main nemo window to the output in the file properties dialog.

**Expected behaviour**

Correct units

**Other information**
![screenshot-window-2020-05-03-112650](https://user-images.githubusercontent.com/29017677/80912031-0cbfd080-8d32-11ea-9dfb-fd057ecd25c2.png)

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/nemo/issues/2348

**Comment by smurphos** [comment]
Thanks @NikoKrause
