### ISSUE TITLE
Change New Desktop Icon Default Location

### ISSUE THREAD

**Issue by Shaav** [linuxmint/nemo#2374]
```
 * Nemo version: 3.8.6
 * Desktop
 * Mint 19 Cinnamon
 ```

**Issue/Feature Request**

When a new item is created on the desktop (saving a file from a web-browser for example), it appears at the top left of the primary monitor. I was hoping to find a way to change the default new icon location—in my case, I'd rather it was on the top-left of the desktop (left most of three monitors). My primary monitor is where I try keep everything clean and where I'm most likely to have something maximized. So it's a nuisance to have to rearrange my current windows to dig out the file I just saved.

I suspect currently there is no way to change the behaviour so probably this is a feature request.

Closest thing I could find was an ancient issue, #82 which appears to have been complaining about exactly the opposite.

If I've overlooked a setting somewhere, I apologize—I went all though my .config and the dconf editor to no avail and it's a hard issues to search for.

**Comment by leigh123linux** [comment]
Sorry nemo-3.8.6 is EOL, If you can reproduce with 4.4.x  feel free to reopen the issue.
