### ISSUE TITLE
Open in Terninal does not work on KDE

### ISSUE THREAD

**Issue by async84** [linuxmint/nemo#2376]
```
 * Nemo version 4.4.2
 * Is issue with both
 * Distribution - Kubuntu 20.04
 * Graphics hardware *and* driver used N/A
 * 64 bit
 ```

**Issue**

When used on KDE the "Open in Terminal does not work. nothing happens."

**Steps to reproduce**

Right click on nemo

Click "Open in Terminal"

**Expected behaviour**

The Konsole terminal should open in the specified directory

**Other information**

**Comment by feren** [comment]
`gsettings set org.cinnamon.desktop.default-applications.terminal exec 'konsole'`

**Comment by async84** [comment]
This issue is solved by changing the setting 

gsettings set org.cinnamon.desktop.default-applications.terminal exec 'konsole'
