### ISSUE TITLE
Nemo draws a huge "window" when searching on tiling WMs

### ISSUE THREAD

**Issue by WhyNotHugo** [linuxmint/nemo#2380]
```
 * `nemo 4.4.2`
 * Running nemo in windowed. Don't use a desktop
 * ArchLinux
 * Intel GPU, using the built-in kernel driver
 * amd64 architecture
 ```

**Issue**
When I type-to-search (not sure what the feature is called, but, eg: I type `lib`, and the first file with a matching filename is selected), a window is created that shows the typed value.

I'm fairly certain this is a tiny window sitting on the corner of a screen on Cinnamon. However, on a tiling compositor, it's a regular-sized window.

Due to how tiling desktops work, all available space is split between all windows, so my regular window becomes 50% size, and this "window" takes up the other 50%.

Maybe a screenshot will make this way clearer:

![2020-05-06T17:23:59,545477044+02:00](https://user-images.githubusercontent.com/730811/81196245-1873f700-8fbf-11ea-8694-1b8391093ae8.png)

**Steps to reproduce**
1. Open nemo on a tiling compositor (I'm using swaywm).
2. Type something so as to trigger the type-to-match behaviour.

**Expected behaviour**
1. Matching file should be selected.
2. Maybe show what I'm typing in some small area or something (I've no real strong opinions here).

**Actual behaviour**
1. Matching file is selected correctly.
2. A full-sized window (which takes up 50% of the screen) is created to show the input value.

**Other information**
It's possible that this new window is just lacking some GTK hints so that the compositor will give it special treatment.
I'm happy to provide further debug information if it'll be of use.

**Comment by feren** [comment]
_Similar to #2362_

**Comment by WhyNotHugo** [comment]
You're correct, this is a duplicate.

I'll follow discussion there.
