### ISSUE TITLE
Need a symbolic link for nautilus

### ISSUE THREAD

**Issue by coreyfarrell** [linuxmint/nemo#239]
The onboard keyboard program attempts to execute nautilus when you try personalizing layout.  Although onboard should use a better method for opening a folder (xdg-open for example) I'm sure other programs have done the same thing.  I created the symbolic link myself and it allows onboard to show the folder with custom layouts.

**Comment by leigh123linux** [comment]
onboard keyboard program = caribou (not part of cinnamon)
