### ISSUE TITLE
Name highlighted but not editable right away when saving file.

### ISSUE THREAD

**Issue by Draconicrose** [linuxmint/nemo#2390]
```
 * Nemo 4.4.2
 * Windowed (file-saving dialogue)
 * Linux Mint 19.3 Tricia x86_64
 * NVIDIA GTX 1060 Driver 440.82
 * 64 bit
 ```

**Issue**
When saving a file the name gets highlighted but if I start typing the search bar in the bottom right corner shows up instead of the file name changing. This seems to happen more often with flatpacks and non-native apps.

**Steps to reproduce**
Open a flatpack app, or do "save as" in something like Firefox. Try to immediately start typing the file name you want.

**Expected behaviour**
The file name changes and the file can be saved with that file name.

**Other information**
This seems to happen more consistently on the first save after a system reboot.

**Comment by smurphos** [comment]
@Draconicrose - unfortunately nemo doesn't provide file dialogs - they are provided by the toolkit used to build the app (GTK , QT) etc. 

A few of many bug reports on this
https://gitlab.gnome.org/GNOME/gtk/-/issues/2680
https://gitlab.gnome.org/GNOME/gtk/-/issues/2638
https://gitlab.gnome.org/GNOME/gtk/-/issues/326
https://gitlab.gnome.org/GNOME/gtk/-/issues/665
https://gitlab.gnome.org/GNOME/gtk/-/issues/2732

**Comment by Draconicrose** [comment]
@smurphos Ah, I see. I wasn't aware of this. Thank you very much.
