### ISSUE TITLE
Allow nemo to work with other archive managers

### ISSUE THREAD

**Issue by philipzae** [linuxmint/nemo#2391]
```
 * Nemo 4.4.2
 * desktop nemo
 * Distribution - Xubuntu 20.04
 * 64 bit
 ```

**Issue**
Would like to utilize Nemo's 'Compress...' and 'Extract Here' context menu entries, presently integrated with the nemo-fileroller package, with other archive managers like Engrampa.

**Comment by leigh123linux** [comment]
Engrampa would need to add nemo support to it's code.

FTR nemo-fileroller and Engrampa were both forked from the same fileroller code.

https://github.com/mate-desktop/engrampa/blob/master/README#L9

**Comment by philipzae** [comment]
That doesn't make sense that the archive manager needs to add support for a file manager.

**Comment by RDKRACZ** [comment]
Sorry for reviving this old issue. I wanted to open a similar one. There is this `nemo-extension-fileroller` package that adds support for File Roller, isn't it made by the You (Linuxmint team)?. Couldn't something like this be done for Xarchiver, Engrampa?
Should I instead ask Engrampa and Xarchiver for this extension?

**Comment by leigh123linux** [comment]
Engrampa and  nemo-extension-fileroller were forked from nautilus-fileroller.

**Comment by cat-in-136** [comment]
I was disappointed that nobody have not mentioned nemo actions here..., anyway, I found that xarchiver-integration could easily be accomplished with short Nemo action files.

Just put the following files to `~/.local/share/nemo/actions/` and then restart Nemo.

xarchiver_extract.nemo_action
```
[Nemo Action]
Active=true
Name=Extract archive...
Comment=Extrace archive %f with xarchiver
Exec=xarchiver -e %F
Icon-Name=extract-archive-symbolic
Selection=s
Dependencies=xarchiver
Mimetypes=application/epub+zip;application/gzip;application/java-archive;application/vnd.android.package-archive;application/vnd.comicbook-rar;application/vnd.comicbook+zip;application/vnd.debian.binary-package;application/vnd.ms-cab-compressed;application/vnd.ms-htmlhelp;application/vnd.oasis.opendocument.text;application/vnd.openofficeorg.extension;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.rar;application/vnd.snap;application/vnd.squashfs;application/x-7z-compressed;application/x-archive;application/x-arj;application/x-bzip;application/x-bzip-compressed-tar;application/x-bzip1;application/x-bzip1-compressed-tar;application/x-bzip2;application/x-bzip2-compressed-tar;application/x-bzip3;application/x-bzip3-compressed-tar;application/x-cb7;application/x-cbt;application/x-cd-image;application/x-compress;application/x-compressed-tar;application/x-cpio;application/x-cpio-compressed;application/x-java-archive;application/x-lha;application/x-lrzip;application/x-lrzip-compressed-tar;application/x-lz4;application/x-lz4-compressed-tar;application/x-lzip;application/x-lzip-compressed-tar;application/x-lzma;application/x-lzma-compressed-tar;application/x-lzop;application/x-rar;application/x-rpm;application/x-rzip;application/x-rzip-compressed-tar;application/x-source-rpm;application/x-tar;application/x-tarz;application/x-tzo;application/x-xpinstall;application/x-xz;application/x-xz-compressed-tar;application/x-zip-compressed-fb2;application/x-zpaq;application/x-zstd-compressed-tar;application/zip;application/zstd;
```

xarchiver_add_files.nemo_action
```
[Nemo Action]
Active=true
Name=Add to archive...
Comment=Add %f to archive
Exec=xarchiver -c %F
Icon-Name=add-files-to-archive-symbolic
Selection=m
Dependencies=xarchiver
Extensions=any;
```

I'm not an Engrampa user so I did not try but porting would be very straight forward: seems to just change command name and argument (The command line option seems to be different between xarchiver and Engrampa.)
