### ISSUE TITLE
Nemo crashes on repeated F3

### ISSUE THREAD

**Issue by zsugabubus** [linuxmint/nemo#2394]
```
 * Nemo version (nemo --version) 4.6.1
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch Linux
 * 64 bit
 ```

**Issue**
Nemo crashes.

**Steps to reproduce**
1. Open Nemo.
2. Press <kbd>F3</kbd> a few times.
3. Crash.

**Expected behaviour**
No crash, obviously.

**Other information**

<details>
<summary>Stack trace:</summary><pre>
#0  0x00007ffff7929cc6 in gtk_tree_view_get_visible_rect () at /usr/lib/libgtk-3.so.0
#1  0x00005555555d44c9 in prioritize_visible_files (view=0x555555f88970) at ../src/nemo-list-view.c:2203
        last_file = 0x7ffff6bdd455
        vrect = {x = 1434790352, y = 21845, width = 1434137744, height = 21845}
        iter = {stamp = 0, user_data = 0x7fffffffe6f0, user_data2 = 0x0, user_data3 = 0x7fffffffe6e8}
        path = 0x7fffffff
        icon_size = -6416
        cy = 32767
        start_y = -6544
        end_y = 32767
        stepdown = 32767
        bin_y = -1173761859
#2  0x00005555555d4710 in update_visible_icons_cb (view=0x555555f88970) at ../src/nemo-list-view.c:2258
#3  0x00007ffff720e764 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff720e340 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff725bfa9 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff720d221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff7409c9e in g_application_run () at /usr/lib/libgio-2.0.so.0
#8  0x00005555556467f0 in main (argc=1, argv=0x7fffffffe978) at ../src/nemo-main.c:104
        retval = 32767
        application = 0x5555557b1130
(gdb) p $_siginfo
$2 = {si_signo = 11, si_errno = 0, si_code = 1, _sifields = {_pad = {16, 287, 0 <repeats 26 times>}, _kill = {si_pid = 16, si_uid = 287}, _timer = {si_tid = 16, 
      si_overrun = 287, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = 16, si_uid = 287, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _sigchld = {
      si_pid = 16, si_uid = 287, si_status = 0, si_utime = 0, si_stime = 0}, _sigfault = {si_addr = 0x11f00000010, _addr_lsb = 0, _addr_bnd = {_lower = 0x0, 
        _upper = 0x0}}, _sigpoll = {si_band = 1232655613968, si_fd = 0}}}
</pre>
</details>

**Comment by leigh123linux** [comment]
The stacktrace is useless without the debugging symbols.

**Comment by zsugabubus** [comment]
Cannot you reproduce it? It reliably crashes on other computers too. But I can compile Nemo if that helps.

###### But dunno why Arch Linux guys strip debug symbols… it surely takes too much space…

**Comment by leigh123linux** [comment]
It doesn't reproduce here

```
$ rpm -qa nemo
nemo-4.6.1-1.fc33.x86_64
```

**Comment by zsugabubus** [comment]
Ok, then will compile and update other issue too a bit later.

**Comment by zsugabubus** [comment]
Updated my comment, this time I hope it’s more informative. Stack trace seems similar to my other crash, guess they are related.
