### ISSUE TITLE
Switching off thumbnails shows clock icons

### ISSUE THREAD

**Issue by zsugabubus** [linuxmint/nemo#2396]
```
 * Nemo version (nemo --version) 4.6.1
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch Linux
 * 64 bit
 ```

**Issue**
File icon of images changes to an icon showing a clock (guess this is the icon for ‘waiting preview to be loaded’).

**Steps to reproduce**
1. Open Nemo.
2. Switch off ‘Show thumbnails’.

**Expected behaviour**

If I request no thumbnails, I should see the icon for the given file from the icon theme.

**Other information**

I see the icon (from the theme) for a short time after I go to different directory, but then all these icons change to this clock-like stuff at once.

Worked with previous release (or one before it).

**Comment by mtwebster** [comment]
duplicate: https://github.com/linuxmint/nemo/issues/2393
