### ISSUE TITLE
Nemo hangs for few seconds when switching from another application

### ISSUE THREAD

**Issue by OnlineLearningTutorials** [linuxmint/nemo#2398]
I noticed sometime when I switch from firefox or media player to file manager it takes full cpu and hangs for short time after that it work fine. But again switching to another application than nemo again takes time. I get rid of this problem by closing nemo and again starting than it work fine.

**Comment by OnlineLearningTutorials** [comment]
Which other file manager is preferred for linuxmint?

**Comment by leigh123linux** [comment]
You have ignored the template that provides the basic info that we require!

**Comment by OnlineLearningTutorials** [comment]
Sorry, basic info as:
```
 * Nemo version (4.6.2)
 * Is issue with desktop or windowed nemo? (Windows nemo, don't understand it's mean)
 * Distribution - (Linux Mint 20)
 * Graphics hardware *and* driver used (AMD kernel native driver)
 * 64 bit
 ```

**Issue**
nemo usage lot of cpu if we switch already opened nemo instanse. So system hangs for a short time.


**Steps to reproduce**
Open Nemo and work on other application than again switch to nemo.
open nemo open song (with celluloid it takes less cpu than xplayer) after it close the song, than it goes to nemo and hangs for 3 to 5 seconds.


**Expected behaviour**
don't want to hang, atleast other applications.


**Other information**
I stored all of my song in one folder so there is a lot of song, is there a limit a folder can have file?

**Comment by OnlineLearningTutorials** [comment]
When I maximize celluloid. it shows padding 5-10 pixels from top and left and cut interface from bottom and right. However button clicking it not depends on interface shown it get click from where usually close button exists means 5-10px from the close button shown in interface (close button is not shown it hide in screen). is it a celluloid issue? celluloid version 0.19

**Comment by leigh123linux** [comment]
> Sorry, basic info as:

Thanks.

> open nemo open song (with celluloid it takes less cpu than xplayer) after it close the song, than it goes to nemo and hangs for 3 to 5 seconds.

Celluliod uses the gtk file dialog to open files.

https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html

**Comment by OnlineLearningTutorials** [comment]
I think nemo calculate disk space, from calculating size of all files and showing in status bar, which one of the best feature of nemo. But 
 - when a file change very frequently like when using youtube-dl, it frequently makes thumbnail but when download finish, thumbnail remains blank. Or 
 - when there is a lot of file it fetches size of all file so it hangs. 

I use nautilus which show file in exact square and no delay or hang, but I don't like most of the other feature of it. I have not read code but feel like this.

Also when choosing application there is lot of icon of same app like okular occure more than ten times in the list, how to control it manually.

**Comment by OnlineLearningTutorials** [comment]
Nemo is working fine when I disable all extension of it. 
Now I enabled Extensions are -
- Folder Color Switcher
- Nemo Fileroller
- Nemo Image Converter
it working fine now. Suspected extension GtkHash, Seahorse

**Comment by mtwebster** [comment]
The 'nemo hangs for a few seconds when switching..' issue should be fixed by https://github.com/linuxmint/nemo/commit/b0c2b99b46797ca91bdba1d95fda33808174466b

It's possible the thumbnail issue described may be fixed as well by recent fixes in nemo-python and nemo. The fact you mention disabling extensions resolves the issue makes me think this is so - folder color switcher was one extension affected by a bug that could prevent thumbnails from from updating in some cases.
