### ISSUE TITLE
Icons not found for nemo's own toolbar buttons and settings dialog

### ISSUE THREAD

**Issue by dikonov** [linuxmint/nemo#2401]
* Nemo version - 4.6.1
 * Is issue with desktop or windowed nemo? - Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - ALTLinux Sisyphus (unstable)
 * Graphics hardware *and* driver used - 64-bit, AMD (radeon free driver)
 ```
This issue appeared after upgrading nemo to nemo-4.6.1. The settings dialog (see attached screenshot) and some toolbar buttons in nemo display the same placeholder icon instead of their proper icons. I did not change the theme and icon set or any other settings concerning the desktop appearance. The only change was a routine cinnamon and nemo upgrade via apt-get.  

**Steps to reproduce**
Open nemo settings

**Expected behaviour**
Normal dialog

**Actual behaviour**
See screenshot
![nemo_settings-no_icons](https://user-images.githubusercontent.com/4271322/83325360-6acdce00-a274-11ea-8673-b50d1dc18002.jpg)

**Comment by dikonov** [comment]
![nemo_settings-no_icons](https://user-images.githubusercontent.com/4271322/83325520-7b327880-a275-11ea-93ac-d9b9a5808673.jpg)

**Comment by leigh123linux** [comment]
Your theme maybe to blame.

![Screenshot from 2020-05-30 11-24-04](https://user-images.githubusercontent.com/1299302/83325948-43710400-a268-11ea-87c0-0ce4fa1aa108.png)

**Comment by dikonov** [comment]
This same theme worked OK with the previous version of Cinnamon. It has not changed a bit. The issue appeared immediately after upgrading to 4.6.1. It means that nemo/cinnamon itself becomes less and less flexible.

* Why does it force those ugly black-and-white icons in sidebras, toolbars, etc, where colored themeable ones used to be before? 
* Where can I get GTK2+3 and WM themes 100% compatible with Cinnamon and updated to keep in sync with versions? I am not a mint user.

**Comment by dikonov** [comment]
* Where the missing icons should be exactly? Where can I download the missing icons that are not part of the nemo source?

**Comment by dikonov** [comment]
SOLVED. This was a packaging issue after all. The missing icons were not part of any of the usual themes. I had to install a missing package named 'xapps-icons' in my distro. It was the missing dependency for nemo and xed. 

_Background. The icons were supposed to be installed by a general metapackage that installs Cinnamon as a whole, but it was automatically removed because it also required damned pulseaudio, which I block for messing up my bit-perfect hifi audio setup._  Sorry for the noise.
