### ISSUE TITLE
Nemo settings dialog lacks a Close/Apply button

### ISSUE THREAD

**Issue by dikonov** [linuxmint/nemo#2402]
```
 * Nemo version (nemo --version) 4.6.1
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  ALTLinux Sisyphus
 * Graphics hardware *and* driver used  - AMD Turks (radeon free)
 * 32 or 64 bit   - 64
 ```
**Issue**
The settings dialog cannot be closed in a standard way after adjusting settings. There is NO button to do it. No "Close", no "Apply", nothing. The window title is also blank without any controls to remove the blasted dialog from the screen. See the attached screenshot, please.

![nemo_settings-no_icons](https://user-images.githubusercontent.com/4271322/83325488-3c9cbe00-a275-11ea-8bb1-a30977aec59d.jpg)

**Comment by leigh123linux** [comment]
Your theme maybe to blame.

![Screenshot from 2020-05-30 11-24-04](https://user-images.githubusercontent.com/1299302/83325948-43710400-a268-11ea-87c0-0ce4fa1aa108.png)

**Comment by dikonov** [comment]
This is quite possible. However, Cinnamon desktop FUNCTIONALITY must not be dependent on such superficial things as themes. There should be a close button that cannot disappear because of a random broken theme. The user chooses themes by their look and is unable to test all software for disappearing controls.

Such small issues are signs of a fundamentally flawed design of the desktop stack itself.

**Comment by smurphos** [comment]
Right click the titlebar to get a close option if you choice of window border theme doesn't offer a close button on that dialog type.

**Comment by vladimir-didenko** [comment]
@leigh123linux 
> Your theme maybe to blame.

Yes it is theme dependent. Provided screenshot is for the stock decoration theme. But I was able to reproduce this problem with another themes e.g. with Materia (https://github.com/nana-4/materia-theme). It is interesting that when this issue happens it seems there is no close button at all - clicking on the area where close button should be located doesn't do anything.

**Comment by dikonov** [comment]
I do not have this stock theme at all.

Thanks, smurphos! This is a workaround, but is not a permanent solution. 
Please, add a normal Close button to the dialog itself.

**Comment by vladimir-didenko** [comment]
> I do not have this stock theme at all.
Sure you have. It is not visible in the list of themes but it is used by default.

**Comment by dikonov** [comment]
I cycled through all GTK and WM themes that I have installed and see the following: 
1) None of them allows to see the missing icons and/or the dialog close button in the titlebar.
2) There is NO stock theme anywhere in the Appearance applet and there is no way to revert to the stock after you tried a broken theme. 

All I can do now is to switch between different but equally "broken" themes that used to work in all previous versions of Cinnamon (I tested them).

**Comment by vladimir-didenko** [comment]
>None of them allows to see the missing icons and/or the dialog close button in the titlebar.

Missing icons looks like local misconfiguration. Close button is visible in some themes e.g. in Adapta (https://github.com/adapta-project/adapta-gtk-theme) 

> There is NO stock theme anywhere in the Appearance applet

Yes it is a known issue. There is a way to pack it as separate theme and in this case it will be visible.

> and there is no way to revert to the stock after you tried a broken theme.

Stock theme is installed as /usr/share/muffin/theme/metacity-theme-3.xml. You could copy it to /usr/share/themes/Adwaita/metacity-1/metacity-theme-3.xml and it will become visible ad Adwaita.

**Comment by dikonov** [comment]
The missing close button is only available to the users of the latest (and ugliest) themes. I installed some of them and confirm that Adapta, OSX-Arc-White, Jade1 do work here. 

**This does not invalidate the truth that functionality (ability to operate software) should not depend on optional visual enhancements (particular themes).**

**Comment by smurphos** [comment]
@mtwebster - Hi,  looking at the commit message that removed the close button - https://github.com/linuxmint/nemo/commit/ffe7f139afa7a97e1465072a70baf20e83783ff9 was it intentional that the window still hints to the WM that it's a dialog? - https://github.com/linuxmint/nemo/blob/master/gresources/nemo-file-management-properties.glade#L360

**Comment by mtwebster** [comment]
I don't even remember what I had for dinner two days ago, much less two years ago. :smile: 

I'm not sure why the modal flag has an effect on this, but it doesn't change any other existing behavior either.
