### ISSUE TITLE
Context menu opened does not allow switching windows

### ISSUE THREAD

**Issue by mahajanudit** [linuxmint/nemo#2403]
```
 * Nemo version (nemo --version) nemo 4.4.2
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint
 * Graphics hardware *and* driver used Intel
 * 32 or 64 bit 64
 ```

**Issue**
If I have context menu (right click) open in my nemo, and then press Alt-tab to switch windows, nothing happens. It forces me to first close the menu, by mouse click or esc and then I can switch

**Steps to reproduce**
Open nemo, open context menu, press alt-tab

**Expected behaviour**
Close context menu and open switcher

**Other information**

**Comment by nick-s-b** [comment]
That's a limitation of X11. It's a very, very, old bug (must be over 15 years old at this point). You might want to try to raise this issue with Xorg folks again. Maybe someone will try to fix it.

**Comment by mtwebster** [comment]
Yes, this can't be fixed at this level (probably not at any level).
