### ISSUE TITLE
Vertical spacing too big in icon view

### ISSUE THREAD

**Issue by worron** [linuxmint/nemo#2404]
```
 * Nemo version: 4.6.2
 * Windowed nemo
 * Distribution: Manjaro 20.0.2
 * Graphics hardware *and* driver used: Intel hd630 with xf86-video-intel
 * 64 bit
 ```

**Issue**
![nemo-4_6_2-scale_normal](https://user-images.githubusercontent.com/10406966/83467007-662a3500-a481-11ea-8e54-1d14d98d1d01.png)
![nemo-4_6_2-scale_small](https://user-images.githubusercontent.com/10406966/83467011-6c201600-a481-11ea-9c0d-937b7e2eb8c1.png)

**Steps to reproduce**
Open any folder with many items in icon view.

**Expected behaviour**
![nemo-4_4_2-scale_normal](https://user-images.githubusercontent.com/10406966/83467220-f10b2f80-a481-11ea-80df-0db817d5707c.png)
![nemo-4_4_2-scale_small](https://user-images.githubusercontent.com/10406966/83467227-f4062000-a481-11ea-8617-c024002edbdc.png)

**Other information**
After updating 4.4.2 -> 4.6.2 icon view layout changed and vertical space now enormous big. Possible related with #2341.

**Comment by mtwebster** [comment]
Hi, can you give me the output of this command:
```
dconf dump /org/nemo/icon-view/
```
The way spacing was calculated did change in those commits.  Previously it was calculating the ideal spacing for each row individually, which had an enormous impact on performance while loading folders with large numbers of files.

Now, the spacing is calculated once based on the icon size and the label settings - number of allowable lines for filename, and how many lines of extra info.

This doesn't mean what you're showing there is 'as expected', however.  You don't appear to have any extra info lines turned on, and the bottom view looks like it still may be accounting for labels, even though they're not showing.

These issues aside, there *will* be instances where things appear to have a bit too much vertical spacing, but we considered it a fair trade-off for the performance improvements we achieved.

**Comment by worron** [comment]
>Hi, can you give me the output of this command
```
[/]
captions=['none', 'none', 'none']
default-zoom-level='standard'
```

Thanks for detailed reply. I wasn't aware about 'number of allowable lines for filename' settings. Seems it's not available in GUI or may be I just missed it somehow. Anyway after reducing max allowed lines number by `text-ellipsis-limit` my icon view turned into something acceptable. Vertical gap is still slightly non-optimal, but I agree it's fair price for new thumbnail behavior.

I'll close it since issue ended as matter of settings. Thanks again.

**Comment by mtwebster** [comment]
Just fyi - https://github.com/linuxmint/nemo/commit/d937f06211e8c76f7823c1a5d42dde990161c348

This should go quite a ways toward addressing the issues you noticed.

**Comment by worron** [comment]
Nice, seems it'll resolve current issue completely perfect. Waiting this fix release, thanks.

**Comment by james-stevens** [comment]
I'm seeing this issue (excessive vertical spacing), but from what I can tell I shouldn't be??
```
My-PC$ dconf dump /org/nemo/icon-view/
[/]
captions=['none', 'none', 'none']
default-zoom-level='small'
My-PC$ nemo --version
nemo 5.2.4
```
![Screenshot_2022-08-17_13-36-17](https://user-images.githubusercontent.com/30622954/185126114-df1a3473-59d0-43ec-9707-8132bbb16131.png)
