### ISSUE TITLE
Nemo desktop dont show icons or show wrong icon theme

### ISSUE THREAD

**Issue by chmat0s** [linuxmint/nemo#2405]
* Nemo version: 4.6.1
 * Desktop nemo
 * Distribution: Arch Linux (Cinnamon)
 * Graphics hardware *and* driver used: Intel Corporation Skylake GT2 [HD Graphics 520], i915
 * 64 bit

**Issue**
Nemo dont show icons in panel. On desktop show different icons than selected theme. 
![Snímek obrazovky pořízený 2020-06-02 08-27-59](https://user-images.githubusercontent.com/56955928/83487550-82db6280-a4ab-11ea-9fd0-5b3ae0ca803b.png)

**Steps to reproduce**
Upgrade nemo (4.4.2-1 -> 4.6.1-1), cinnamon (4.4.8-1 -> 4.6.1-1)

**Expected behaviour**
Show icon in panel and correct icon selected by theme.

**Other information**
When I restart Cinnamon enviroment  I get error:
Cinnamon warning: Log level 8: gtk_icon_theme_choose_icon_for_scale: assertion 'scale >= 1' failed

I tryed changing zoom in nemo and icons theme.

**Comment by leigh123linux** [comment]
Please file the issue against cinnamon.
