### ISSUE TITLE
Unable to test gsetting FALSE in an action condition

### ISSUE THREAD

**Issue by saraaba** [linuxmint/nemo#2406]
I am trying to have a Nemo action shown when a gsetting is FALSE
I have tried
gsettings schema key boolean ne true
and 
gsettings schema key boolean eq false

Neither are working

I can test if it is true, but not if it is false

Can we test a gsetting value for FALSE in a Condition? if not, why not? My action depends upon a setting being false otherwise it is visible in the context menu like some digital turd when it should not be visible

**Comment by saraaba** [comment]
Here is two actions that will test this

[Nemo Action]
Active=true
Name=Start Slideshow
Comment=If the desktop background slideshow is inactive, start slideshow
Exec=gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled true
Icon-Name=media-playback-start-symbolic
Selection=none
Extensions=any;
Conditions=gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled boolean eq false;desktop;


[Nemo Action]
Active=true
Name=Stop Slideshow
Comment=If the desktop background slideshow is active, stop slideshow
Exec=gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled false
Icon-Name=media-playback-stop-symbolic
Selection=none
Extensions=any;
Conditions=gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled;desktop;

**Comment by smurphos** [comment]
Hi, your syntax isn't quite right

```
Conditions=gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled b eq false;desktop;
```
Is correct.

Ref Conditions=gsettings org.cinnamon.desktop.background.slideshow slideshow-enabled boolean eq false;desktop;

However please see this limitation that will apply to this use case - https://github.com/linuxmint/nemo/issues/2097

This is what I use instead

```
[Nemo Action]
Name=_Toggle Desktop Slideshow
Comment=Toggle the desktop wallpaper slidehow on/off
Exec= sh -c 'if gsettings get org.cinnamon.desktop.background.slideshow slideshow-enabled | grep "false"; then gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled true; else gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled false; fi'
Icon-Name=preferences-desktop-wallpaper-symbolic
Selection=none
Extensions=any;
Conditions=desktop;
```
