### ISSUE TITLE
Directory properties does not display last modified date

### ISSUE THREAD

**Issue by wesinator** [linuxmint/nemo#2408]
**Issue**
Last modified date not displayed for directories
Fixed in GNOME https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/409 

**Steps to reproduce**
Select folder -> Properties

**Expected behaviour**
Displays directory last modified date

Thanks,

**Comment by Jeremy7701** [comment]
Note:- Created/Modified/Created dates are not shown in directory properties.
