### ISSUE TITLE
CLI parameter fails

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2415]
```
 * Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? CLI
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) LMDE
 * 32 or 64 bit 64BIT
 ```

**Issue**
nemo -c  just stops after a brief period.
According to the man page, nemo -c performs a quick check,
Instead it produces:-
running nemo_self_check_file_utilities
running nemo_self_check_file_operations
running nemo_self_check_directory
then it enters an idle state.
CTRL+C returns to CLI
I suggest that the CLI --check option be removed.

**Steps to reproduce**
As user, enter into gnome-terminal,
nemo -c

**Expected behaviour**
Something sensible!

**Other information**
After a few minutes I entered (in a separate window)
ps aux | grep nemo
jeremy    3105  0.0  0.8 668272 65080 ?        Sl   13:09   0:01 nemo-desktop
jeremy    8375  0.0  0.3 392720 27188 pts/1    Sl+  13:47   0:00 nemo -c

**Comment by Jeremy7701** [comment]
Still present in nemo 4.8.4

**Comment by icarter09** [comment]
@Jeremy7701 the PR to fix it is still a WIP.
