### ISSUE TITLE
SyncTeX error - minor cosmetic issue?

### ISSUE THREAD

**Issue by dglava** [linuxmint/nemo#2416]
```
 * Nemo version: 4.6.3
 * Is issue with desktop or windowed nemo: windowed Nemo
 * Distribution: Arch Linux
 * 32 or 64 bit: 64 bit
 ```

**Issue**
The error message `! SyncTeX Error : No file?` is being printed (to stderr) when reloading a directory which contains a PDF file. This affects usage in no way, but I thought I'd report it just in case.

**Steps to reproduce**
Open Nemo
Navigate to a directory with a PDF file
Reload (Ctrl+R)

**Comment by icarter09** [comment]
Nemo 4.8.2
Mint 20 64bit.

I'm not seeing the error message. @dglava if you are still seeing, let me know and I'll reopen this ticket. Thanks.

**Comment by dglava** [comment]
It is still being printed to stderr, but I am not sure if it's a Nemo issue. When I remove [Evince (the document viewer)](https://wiki.gnome.org/Apps/Evince), the messages stop appearing (but then I lose PDF thumbnails). I guess this is an issue on Evince's end then?
