### ISSUE TITLE
Suggestion: Compact View should have option to stack vertically

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/nemo#242]
So when you view a directory in compact mode I think it would be a nice addition to allow folders to be stacked in the same manner as icon view. So to demonstrate in text form, please try to imagine this as a file layout....

Current Behaviour of compact view:
dirAA    dirBA    dirCA
dirAB    dirBB    dirCB
dirAC    dirBC    dirCC 

Any additional files extend to the RIGHT

Suggested optional behaviour of compact view (and current behaviour of icon view):
dirAA    dirAB    dirAC
dirBA    dirBB    dirBC
dirCA    dirCB    dirCC

Any additional files would extend downwards

This would feel much more natural to me as when using a mouse scroll wheel,currently scrolling DOWN tracks RIGHT through the file list, and scrolling UP tracks LEFT through the files. I feel UP should go UP and DOWN should go DOWN. If this is implemented I would argue that it should be default behaviour but one step at a time.

Thoughts?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
