### ISSUE TITLE
Nemo crashes after installing and using thunar

### ISSUE THREAD

**Issue by Goodgun123456789** [linuxmint/nemo#2420]
```
 * Nemo version (nemo --version)
nemo 4.4.2
 * Is issue with desktop or windowed nemo?
Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 19.3 Tricia x86_64
 * Graphics hardware *and* driver used
NVIDIA GeForce GTX 1050 Ti
nvidia-driver-435
 * 32 or 64 bit
64
 ```

**Issue**
Occasionally Nemo will crash, and sometimes not be able to boot with the following message as 
Could not register nemo as a remote: Timeout was reached.  This error of not being able to boot was only after I installed thunar to test it out.
**Steps to reproduce**
install and use thunar
use nemo for an unspecified amount of time
it should eventually crash and not be able to boot again
**Expected behaviour**
nemo opens as normal
**Other information**
I am relatively new to debugging linux, but know my way around the filesystem quite well.  If you need logs, simply tell me where to find them and it shouldn't be an issue.

**Comment by Goodgun123456789** [comment]
seemingly reinstalling the package has been a manual fix, but I wouldn't rely on this

**Comment by xenopeek** [comment]
Doing the above doesn't reproduce this for me. At least not with Nemo 4.6.4 and Thunar 1.8.14 on Linux Mint 20 Cinnamon. If you can reproduce it with that Nemo version, confirm whether Nemo is still running with `ps -e | grep nemo`. If it's still running stop it with `nemo -q` and in either case then try restarting it with `nemo --debug` and maybe that output will give a clue as to why it doesn't start. System logs may provide further information. See the [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/errors.html) for tips for that. If you can reliably reproduce this with Nemo 4.6.4 this can be reopened.
