### ISSUE TITLE
'Open terminal here' fails if the path includes 'admin:///'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2425]
```
 * Nemo version (nemo --version): 4.4.2 (under Mint 19) and 4.6.3 (under Mint 20)
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint Cinnamon 19 and Mint 20
 * Graphics hardware *and* driver used: N.A.
 * 32 or 64 bit: 44
 ```

**Issue**

'Open terminal here' in 'admin' path opens a terminal in the user's home directory (e.g. `/home/James`).

**Steps to reproduce**

Open a Nemo Window.
Type  `admin:///media` into the address bar.
Authenticate (twice, for some reason).
Use the 'open terminal here' icon in Nemo.

_Or_ get VirtualBox to mount a shared folder in `/media` and then, within the VM, click the resulting link to that folder.

**Expected behaviour**

The terminal should open - as root, I suppose - in `/media`. Or if something else is to happen, then it would be good for the user to be given an explanation of why.

**Other information**

Entering `admin:///media' into the bar of (unelevated) Nemo prompts _twice_ for authentication.

**Comment by icarter09** [comment]
Nemo 4.8.2
Mint 20 64bit

I'm not able to reproduce this issue with the steps provided. Was able to open the location `admin:///media` and Nemo only prompted me once for authentication.

**Comment by LinuxOnTheDesktop** [comment]
I have tested this now on one computer. (I can test on another later). The opening of the terminal problem seems gone. However, Nemo still requested authentication twice. I see nothing relevant to the latter in the system's logs.

**Comment by icarter09** [comment]
Closing this ticket. Feel free to open a new ticket related to the authentication being asked twice. I  have seen that behavior before I believe on xed, but not on Nemo.
