### ISSUE TITLE
OpenLocations dbus property doesn't work - returns empty array

### ISSUE THREAD

**Issue by j1warren** [linuxmint/nemo#2429]
```
 * Nemo - 4.6.3
 * Distribution - Mint 20.0 beta
 ```

**Issue**
OpenLocations dbus property returns empty array.

**Steps to reproduce**
`qdbus org.Nemo /org/freedesktop/FileManager1 org.freedesktop.FileManager1.OpenLocations`

or in D-Feet

![nemo463](https://user-images.githubusercontent.com/46167694/85890046-22a2bc80-b7dc-11ea-84db-714c7503768c.png)

**Expected behaviour**
It should return an array of open tabs locations from all Nemo windows.
Nautilus provides the correct array of tabs.

**Comment by leigh123linux** [comment]
Nemo never had this when it was forked from nautilus so the empty array is the expected result.

https://github.com/GNOME/nautilus/commit/a1751d3d870c6cdc092f893755623c4ff20e1ef3

**Comment by j1warren** [comment]
fyi, I think this [bug with commits](https://bugzilla.gnome.org/show_bug.cgi?id=694266) from 2013 is more appropriate to mention than the one above.
