### ISSUE TITLE
Nemo Sidebar Bookmarks Shows Sysfunctional (Send by Email) Option

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/nemo#2430]
```
 * 4.6.4
 * Issue related with file manager, not desktop.

 ```

**Issue**

Nemo shows a sysfunctional "Send by Email" option on context menu of bookmarks (unmounted partition). This option is not shown when the partition mounted.

**Steps to reproduce**

Add a directory to bookmarks from a mounted partition and unmount the partion. Right click added bookmark.
Or create a directory and add bookmarks. Remove created directory and right click added bookmark.

**Expected behaviour**

should not show the dysfunctional "Send by Email" option

**Other information**

You can look following images.

Partition unmounted

![nemo-bookmark-sendmail](https://user-images.githubusercontent.com/1300133/85948545-21979980-b95a-11ea-8ffe-37c06d4b4a0d.png)

Partition mounted

![nemo-bookmark-sendmail-2](https://user-images.githubusercontent.com/1300133/85948963-818f3f80-b95c-11ea-931b-51329eca7f0c.png)

**Comment by icarter09** [comment]
Nemo 4.8.4

@kelebek333 the `Send by Email` action has been removed. It should no longer appear in the popup menu for unmounted partitions. If you are still seeing it, I'll reopen the ticket. Thanks.
