### ISSUE TITLE
[Using Terminal]Toggle Desktop Icons Layout Auto-arrange and Adjust grid-spacing

### ISSUE THREAD

**Issue by BoQsc** [linuxmint/nemo#2435]
* Nemo version (nemo --version)
   ```
   mint@mint:~$ nemo --version
   nemo 4.6.4
   ```
 * Is issue with desktop or windowed nemo?
   `Desktop`
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   ```
   mint@mint:~$ lsb_release -a
   No LSB modules are available.
   Distributor ID:	Linuxmint
   Description:	Linux Mint 20
   Release:	20
   Codename:	ulyana
   ```

 * 32 or 64 bit
   ```
   x64
   ```

**Issue**
I cannot find a **Terminal/Script** way to change the  **Desktop Icons Layout Auto-arrange** settings.
The same goes for the **Adjust vertical-grid-spacing** and **Adjust horizontal-grid-spacing**

![image](https://user-images.githubusercontent.com/21064622/86223273-d9a18e00-bb76-11ea-8d96-bf141da2cb17.png)

**Steps to reproduce**
1. Use D-conf editor
2. Search for the setting with words related to **Desktop Icons Layout Auto-arrange**
3. Be unsuccessful in finding a setting for that.

**Expected behaviour**
Use gsettings to toggle on or toggle off **Desktop Icons Layout Auto-arrange**
Use gsettings to get the values of horizontal-grid-spacing and  vertical-grid-spacing

**Other information**

**Comment by xenopeek** [comment]
Desktop settings are stored in the file `~/.config/nemo/desktop-metadata`. Auto-arrange is stored in the `nemo-icon-view-auto-layout` setting.

**Comment by BoQsc** [comment]
@xenopeek 
> Desktop settings are stored in the file `~/.config/nemo/desktop-metadata`. Auto-arrange is stored in the `nemo-icon-view-auto-layout` setting, spacing in `desktop-grid-adjust` (not present if not changed from default).

These files are acting only  as data files, if edited directly. 
Changing values in any of these directly - do not change the current environment settings 
and after user relogin - the data in these files are restored, to the ones seen in the User Interface.

I'm searching for a way to toggle these settings, and haven't found any yet.

**Comment by xenopeek** [comment]
After changing desktop settings run `nemo-desktop -q` to reload nemo-desktop with your changes.

**Comment by BoQsc** [comment]
> After changing desktop settings run `nemo-desktop -q` to reload nemo-desktop with your changes.

Script critical notice: Seems to be working, however running command `nemo-desktop -q` twice in a row will completely break the nemo-desktop and will require restart of the Linux Mint Operating system.


## Script to resolve
```


# Disable Auto layout (Auto-arrange)
search="(nemo-icon-view-auto-layout=)(.*)"
replace="\1false"
sed -i -r "s|$search|${replace}|g" "$HOME/.config/nemo/desktop-metadata"


# Adjust Desktop Grid
if grep -q "desktop-grid-adjust" "$HOME/.config/nemo/desktop-metadata"; then
    search="(desktop-grid-adjust=)(.*)"
    replace="\164;80;"
    sed -i -r "s|$search|${replace}|g" "$HOME/.config/nemo/desktop-metadata"


  else 
       awk '1;/desktop-monitor-0/{ print "desktop-grid-adjust=64;80";}' "$HOME/.config/nemo/desktop-metadata" > tmp && mv tmp "$HOME/.config/nemo/desktop-metadata" file
fi


nemo-desktop -q
```
