### ISSUE TITLE
Peculiar Emblems behaviour

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2453]
```
 * Nemo version 4.6.4
 * Issue with windowed nemo
 * Distribution - LMDE4
 * Graphics hardware nvidia
 * 64 bit
 ```

**Issue**
See "Steps to reproduce"

**Steps to reproduce**
mkdir -p ~/X/Y
So that Y is a sub-directory of X:-
[optional] Create a few directories/files in X & Y - this is not necessary.
In nemo display the empty directory Y
Right-click [in an area with no files selected] -> properties -> emblems
Select an emblem.
Press close in the emblem box.
Nothing appears to have happened.
However the emblem has been applied to the parent directory [in this case X]

**Expected behaviour**
Should not be able to choose Emblems unless one or more items have been selected.

**Other information**

**Comment by xenopeek** [comment]
I can't reproduce this on Nemo 4.6.4. Following your steps the emblem is correctly applied to the Y folder, the folder for which I opened the properties.

![Peek 2020-07-20 09-35](https://user-images.githubusercontent.com/21159972/87911792-7c5d7600-ca6c-11ea-9c0d-2098d60c079a.gif)

**Comment by Jeremy7701** [comment]
Agree - sorry to have wasted your time.
