### ISSUE TITLE
Sidebar jumps around too much when clicking on items

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#2454]
```
 * Nemo version (nemo --version)
nemo 4.6.4
 * Is issue with desktop or windowed nemo?
Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arcg
 * Graphics hardware *and* driver used
NVIDIA-SMI 440.82
 * 32 or 64 bit
64-bit
 ```

**Issue**
When clicking on folders/items in the sidebar, `nemo` is jumping around and scrolling the contents. It's as if it's trying to center it.

![output](https://user-images.githubusercontent.com/7957590/88000424-94181700-cacb-11ea-9433-8c0979104144.gif)

**Steps to reproduce**
1) Have a number of items in the sidebar (fill out the Bookmarks section)
2) Resize the `nemo` window so there's a scroll bar on the side of the sidebar (can't scroll it around if the content of the sidebar is not overflowing)
3) Click on some items. Notice how `nemo` is jumping around and scrolling the items for no reason whatsoever.

**Expected behaviour**
Please don't move the items around by scrolling. It's incredibly annoying and it's so easy to misclick on items because things move without your control.

**Other information**
This does not happen with other FMs.

**Comment by icarter09** [comment]
Nemo v4.6.5
Mint 20 64bit

I'm unable to duplicate this issue and believe it has been addressed. @nick-s-b are you still experiencing this issue? Thanks.

**Comment by nick-s-b** [comment]
@icarter09 It has been fixed. Just checked it and noticed it myself. Closing the issue!
