### ISSUE TITLE
With menu bar disabled, Alt-toggle for menu bar conflicts with Alt-arrows for file navigation

### ISSUE THREAD

**Issue by hhhorb** [linuxmint/nemo#2459]
* Nemo version ...

Debian Buster https://packages.debian.org/buster/nemo

 * Is issue with desktop or windowed nemo?

Windowed

**Issue**

Alt+left, right or up arrow are standard keyboard shortcuts for navigating the directory, those shortcuts work in Nemo. Alt also toggles the Menubar, and if the Menubar has been disabled, navigating with Alt results in the Menubar appearing and disappearing depending on your next keyboard entry.

**Steps to reproduce**

Open nemo, use keyboard arrows to navigate to a file in the default directory, "Documents" for example.

Press the Enter key to open the Documents folder.

Press Alt+left-arrow to go back one directory, the Menubar appears, disappears, then reappears as the navigation occurs.

**Other information**

Re-assign Alt toggle to another key or key-combo? Example, Ctrl+M is standard in a few GUI file managers.

**Comment by icarter09** [comment]
Nemo 4.8.2
Mint 20 64bit

I'm not able to reproduce this issue. Using `Alt+left arrow` only goes back one directory. The menubar never changes.

**Comment by hhhsssorb** [comment]
I can't confirm as I'm not using Mint. This might be Debian buster specific. But on Buster Cinnamon, if I navigate through nemo and then try to navigate back via Alt-Home or Alt-arrow, pressing the Alt key opens the menu bar (File Edit View...) The next navigation using Alt hides the menu bar.

**Comment by hhhorb** [comment]
I've upgraded too Debian Bullseye Cinnamon and the issue is not present, I can navigate using Alt without any visual glitches.Alt still brings up the Menu, but only after releasing the keypress, so Alt+arrow/Alt+Home shortcuts are still enabled.

Very elegant solution, recommend marking this big [FIXED]
