### ISSUE TITLE
“Right Click > Open In Terminal” Does not work if I activate tmux whenever I start a new shell session

### ISSUE THREAD

**Issue by blueray453** [linuxmint/nemo#2463]
```
 * Nemo version (nemo 4.6.4)
 * issue is with both desktop or windowed nemo
 * Distribution - (Linux Mint 20 Ulyana)
 * 64 bit
 ```

**Issue**

I have asked this in [stackoverflow](https://stackoverflow.com/questions/63161799/right-click-open-in-terminal-does-not-work-if-i-activate-tmux-whenever-i-sta).

I am using the following code to activate tmux whenever I start a new shell session.

```
function tmux-as-default-terminal () {

  if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]]  && [ -z "$TMUX" ]; then
    tmux attach -t default || tmux new -s default
  fi

}

tmux-as-default-terminal
```
However, It has a small issue. When I right click a directory and click "Open In Terminal", it does not open that path. Instead it just open the previous tmux session.

I want to know where is the code which defines `Right Click > Open In Terminal`. And how can I customize it. I mean when I click 'Right Click > Open In Terminal' it should run a custom command. I know I can define new actions in `~/.local/share/nemo/actions` but I want to customize it.

**Steps to reproduce**

Copy Paste the lines in .zshrc or .bashrc

```
function tmux-as-default-terminal () {

  if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]]  && [ -z "$TMUX" ]; then
    tmux attach -t default || tmux new -s default
  fi

}

tmux-as-default-terminal
```

`source ~/.bashrc` or `source ~/.zshrc`

Right click any directory and click `Open In Terminal`

**Expected behaviour**

I want tmux to connect to default session and `cd` to the directory I am in.

**Comment by Susensio** [comment]
Hey @blueray453 , necrobumping this issue because google brought me here. I'm having exactly the same issue. Did you found a solution?

**Comment by blueray453** [comment]
When i set zsh as my default shell and use the following in my zshrc, it is supposed to solve the problem. 

```
function tmux-as-default-terminal() {
  if [[ -o interactive ]]
  then
    if [ -z ${TMUX} ]
    then
      tmux
    fi
  fi
}

tmux-as-default-terminal "$@"
```
