### ISSUE TITLE
Icon of newly created file on desktop is misaligned, then moves on mouse-over

### ISSUE THREAD

**Issue by teo1978** [linuxmint/nemo#2473]
```
 * Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Ubuntu 20.04
 * Graphics hardware *and* driver used: Intel Corporation 3rd Gen Core processor Graphics Controller and NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (don't know about the driver since it doesn't show up in System Info)
 * 64 bit
 ```

**Steps to reproduce**

- Have some icons on the desktop
- Save something to the desktop, e.g. in Chrome, open some website, right-click on some image and do Save As and save it to the Desktop
- Look at the new icon, then move the mouse cursor over it

**Expected behaviour**

The newly created icon should be displayed properly and it should definitely not move when you move the mouse cursor over it

**Observed behavior**

When the icon first shows up, it is misaligned. It is displaced to the right. You can tell something is off especially if there are other icons to compare with.

When you move the mouse cursor over the icon, it suddenly moves. Only the icon moves, not the file name. Then it stays there even if you move the mouse cursor away. The new position is clearly the right one.

Before:

![image](https://user-images.githubusercontent.com/542107/89521987-c4a4c400-d7e0-11ea-817f-1bd9f01c9f00.png) 

After:

![image](https://user-images.githubusercontent.com/542107/89522004-ca9aa500-d7e0-11ea-92bb-20578d85d8b9.png)

**Comment by leigh123linux** [comment]
Closed #2471

**Comment by teo1978** [comment]
Why have you closed this?

**Comment by leigh123linux** [comment]
@teo1978  Because it's a duplicate of your other issue, also 4.4.x is EOL

**Comment by teo1978** [comment]
> Because it's a duplicate of your other issue

If you mean 2471, I don't think it is.

**Comment by teo1978** [comment]
> also 4.4.x is EOL

It's the one I get with apt on Ubuntu 20.04

**Comment by teo1978** [comment]
I can reproduce the issue by starting clean on a given display, moving all the icons forth and back so they are aligned with the current grid, then downloading a new file. This will still reproduce this issue with no screen switching involved.

**Comment by SebastJava** [comment]
Oops! Please take a look at my new https://github.com/linuxmint/nemo/issues/2727. I gave a slightly different description, but i am pretty sure we are talking about the same bug. I am on the latest LinuxMint Cinnamon 20.1, all up-to-date, and i can certainly confirm this. It was bothering me for a long time, but i never took the time to report it until now.

Please take a close look at my "Steps to reproduce". There you will see this (probably) only happens with **picture thumbnails,** and only when you have Cinnamon desktop right-click > **Customize: Auto-arrange=false.**

**Comment by SebastJava** [comment]
> When you move the mouse cursor over the icon, it suddenly moves.

This is true only when the file name is too long to be displayed completely unless you mouse-over it.
