### ISSUE TITLE
Icon remains on desktop forever after file already deleted

### ISSUE THREAD

**Issue by teo1978** [linuxmint/nemo#2474]
* Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Ubuntu 20.04
 * Graphics hardware *and* driver used: Intel Corporation 3rd Gen Core processor Graphics Controller and NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (don't know about the driver since it doesn't show up in System Info)
 * 64 bit

**Issue**

**Steps to reproduce**

- Download a file with Chrome.

- show desktop while it's still downloading

**Expected behaviour**

While downloading, Chrome creates a temporary file, with extension `.download `, with the partially downloaded file. When it's done downloading, the file apparently is copied to one with the final filename and the .download is deleted. Or the file is just renamed, not sure.

Once the .download file is deleted, its icon should disappear from the desktop

**Observed behaviour**

Most of the times it behaves as expected.
However, sometimes randomly, it happens that the icon of the partially downloaded file, after the file is deleted, remains there.

If you select the icon and try to delete the file, you'll get an error message that the file doesn't exist. And the most ironic thing is that the icon will still remain there.

Nautilus had the exact same bug (not sure if they fixed it already).

**Other information**

f5 refreshes the desktop and causes the orphan icon to disappear.
By the way, I had to use my immagination to discover the f5 shortcut, as there is no "refresh" or "reload" item in the context menu, or anywhere where you would discover it.

**Comment by icarter09** [comment]
Nemo v4.6.5
Mint 20 64bit

I'm not able to duplicate this issue. @teo1978 are you still experiencing this issue? If so, is there a download you can point me to reproduce it? Thanks.

**Comment by teo1978** [comment]
It was never systematically reproducible, it was random.

Anyway I have switched to OpenSUSE and KDE Plasma.

**Comment by icarter09** [comment]
Thanks for the update.
