### ISSUE TITLE
Bookmarks lose positioning or scroll to top.

### ISSUE THREAD

**Issue by silocoder** [linuxmint/nemo#2476]
Linuxmint 20
Nemo 4.6.4

Imagine you Clicked on the Home bookmark and scrolled down the list of bookmarks to select one. Bookmarks get reposition to the center of your list. Does not make sense and it's annoying. Should just stay fixed as if you had clicked on files/directories in a pane.

Another issue, not sure when or how it occurs, but happens way to often. Bookmarks likes to refresh itself after few seconds. And scrolls up to whatever directory happens to be highlighted.

Attached is gif.
![Peek 2020-07-30 15-42](https://user-images.githubusercontent.com/57298274/89582110-157ae380-d806-11ea-9183-00a5c3a2c2d1.gif)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/557b7bbfdf697af4d86a94f29bf5dbf2b0d5bfad

This should fix the scroll position resetting whenever a selection changes.  I can't reproduce the second issue.

**Comment by silocoder** [comment]
@mtwebster  I've not tried the new fix yet. What is the best way to install and test without removing my installed version of Nemo? Do I just clone master and compile it as per instructions?

 I can reproduce the second issue which . It seems to happen when refresh occurs of the Home folder files, while scrolling down on the bookmarks.  I will try to reproduce it on the master

**Comment by mtwebster** [comment]
The 'packages.tar.gz' file [here](https://github.com/linuxmint/nemo/releases/tag/master.mint20) has the deb files you could install - extract them to a folder, and `dpkg -i *.deb`.  You probably don't want to install the -dev and -doc packages, as they'll probably 'break' things by wanting additional dependencies.

Alternately you could build.  Open Software sources and enable 'source repositories' first (and update the cache like it wants to after), then:

```
apt build-dep nemo
git clone https://github.com/linuxmint/nemo.git
cd nemo
dpkg-buildpackage
cd ..
(delete the -dev and -doc packages as mentioned above)
dpkg -i *.deb
```

Unfortunately either option will replace the installed version (this is pretty much unavoidable).  However, mintupdate will want to re-install the released version for you.  So if something goes bad, just let mintupdate run (or `apt install -f`)

**Comment by icarter09** [comment]
@silocoder are you still experiencing this issue?

**Comment by silocoder** [comment]
From what I recall the bookmark issue was fixed. But due to other persistent issues with nemo, I decided to switch distros to use kde and dolphin. For me it works better. Thanks.

**Comment by icarter09** [comment]
@silocoder no worries and thanks for the update.
