### ISSUE TITLE
Feature Request:   Duplicate with -copy not (copy).

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/nemo#2477]
```
 * Nemo version 4.4.2  (now)  or any version 
 * Both Windowed or desktop
 * Distribution - Linux Mint 19.3 Cinnamon
 * 64 bit
 ```
Seeing how spaces and () in file names can sometimes hamper other programs, I think it would be an improvement to change this to "<name>-copy" and not "<name> (copy)" when doing a duplicate right click context menu action.

Example:  If I make a copy of a css file, then edit the original, later I want to see where and what I modified.  Granted diff could do it but I use meld, especially for long winded modifications.   And there is a nemo_action(s) for meld in the wild, 'compare later' & 'compare now'.  Works great if I change that file name from (copy) to just -copy.  Meld (or the actions) does not like these special characters and fails when it launches.  Meld is fed multiple arguments and tries to do a compare on arguments like "file.css file (copy).css" which is now 3 arguments and only 1 is a real filename.

This is just one example.  There are a other situations that the space and parens hamper other programs in Linux.   I was brought up with the concept of not using spaces in filenames in Linux.  But then I started on SCO Unix 4 years ago and that may have been a demand in those days.

**Comment by smurphos** [comment]
There's an official nemo-extension for meld - `apt install nemo-compare` - that deals with spaces in filenames just fine.

If you are talking about the examples on the arch wiki - https://wiki.archlinux.org/index.php/Nemo#Meld_compare then they won't work with paths with spaces because they don't include any definition for quoting the argument - adding 'Quote=double' to both actions should fix them.

**Comment by ChooChooAl** [comment]
I installed the nemo-compare from 19.3 synaptic and I can't see how to get to it.  Nemo settings shows no indication.  Running the nemo-compare-preferences just confirms that I'm setup properly.
However the wiki compare actions and script work fine, even for spaces at least in my test:
'test.txt' and 'text (copy).txt'
I did add the Quote=double just to remember the syntax but it's redundant.
If you can explain my nemo-compare install/setup issue I'd appreciate it.  Sounds like this might be a better solution.

**Comment by smurphos** [comment]
It sounds like you are already using the extension.

Nemo > Edit > Plugins > Extensions - Ensure Nemo Compare is checked.

Right click on a file/folder > Compare Later. Right click another file/folder > Compare to: <previous selection>

With the extension the compare options appear right at the bottom of the context menu and are context aware - e.g. with no previous selection the only option is compare later. With a previous selection you get compare later and compare to: <previous selection>

**Comment by ChooChooAl** [comment]
Not sure what I did, but the extension shows at the bottom of the context menu now.  It may have been there all the time, I was looking at the top where actions are listed.  I've set the actions to false so I just have the extension at the bottom now. 
Thanks for your help and since old age must have set in, I'm going to my rocker. :-)
