### ISSUE TITLE
File upload dialogue doesn't show preview of pictures larger than 4100 pixels

### ISSUE THREAD

**Issue by Isolator70** [linuxmint/nemo#2479]
```
 * Nemo version: 4.4.2
 * Is issue with desktop or windowed nemo? Nemo file upload dialogue invoked by Firefox ("open file")
 * Distribution: Linux Mint Cinnamon 19.3
 *Graphics:  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Fujitsu Limited. 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0416 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1600x900~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.0.8 
           compat-v: 3.0 direct render: Yes
 * 64 bit
 ```
**Usecase:**

If one want to upload a picture (see attached examples) to a web service via Firefox, a dialogue window opens. User can select files to upload and in case of an picture a preview on the right side of this upload dialogue appears. I strongly assume it a window from Nemo as it looks like the "normal" Nemo windows.

**Issue**
If user selects a picture which dimensions exceed 4100 px in one or two dimensions (see attached examples) the preview is NOT shown.

**Steps to reproduce**
Download attached example pictures to your local drive.
Start Firefox.
Goto menu of Firefox.
Select "open file" (or similar - I'm on German machine)
Navigate to storage location of downloaded files
a. Mark picture "4100x4100.png" by clicking it once (no double click)
b. Mark picture "4001x4001.png" by clicking it once (no double click)

Only in case of "b" a preview is shown on the right side of the upload dialogue window of Nemo.

**Expected behaviour**

Preview pictures are shown in all up-to-date picture dimensions which are usually today (remeber 102 Megapixel midclass smartphones pictures).

**Other information**

Attached pictures for testing:

a. ![4100x4100](https://user-images.githubusercontent.com/35434137/89709211-2cdcdc80-d97e-11ea-8452-74c9f699d858.png)
b. ![4001x4001](https://user-images.githubusercontent.com/35434137/89709213-36fedb00-d97e-11ea-8f4c-a3a84d8084e7.png)

Screenshot of "good" case: ![4001x4001_good_case](https://user-images.githubusercontent.com/35434137/89709254-9361fa80-d97e-11ea-8484-0b2353b6fad8.png)

Screenshot of "bad" case: ![4100x4100_bad_case](https://user-images.githubusercontent.com/35434137/89709265-a5dc3400-d97e-11ea-8518-9ffb8466ac0a.png)

Hint:
1. Issue on Linux Mint Mate (Caja) is identically!
2. Issue on KDE Dolphin also exists, but there the size of the file is the limit (> 3MB).

On linuxmintusers.de a thread with this topic exists: [https://www.linuxmintusers.de/index.php?topic=62695.msg828221#msg828221]

**Comment by leigh123linux** [comment]
GTK3 provides that not nemo.

https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html

**Comment by Isolator70** [comment]
@leigh123linux: Thanks for this information. As I have no understanding of programming I'd like to know if this is an issue of the GtkFileChooserDialog itself or the way it is used by the application (Firefox)?

I'd like to address the ticket at the right place.

Thank you
