### ISSUE TITLE
Searching icon stopping to early

### ISSUE THREAD

**Issue by plata** [linuxmint/nemo#248]
Not quite sure about this one but the moving searching icon in the down right corner seems to stop to early (i.e. after receiving the first batch and not after the search is finished)

**Comment by Vahan86** [comment]
I can't reproduce the issue in Nemo 3.0.6.
@plata, is this still an issue for you with Nemo 3.0.6?

**Comment by plata** [comment]
Cannot tell. I'm not using Nemo at the moment. As nobody else seems to have had this issue, feel free to close it.

**Comment by Vahan86** [comment]
@plata, thanks for reply, in this case can you please close the issue?
