### ISSUE TITLE
How can we install it ?

### ISSUE THREAD

**Issue by pzim-devdata** [linuxmint/nemo#2493]
**Issue**
I have Nemo 3 and I use Debian Buster with Cinnamon.

Hello, I don't know how to install it. Could you, please, explain it in the readme file on Github?

I have read the Install file in the zip file and it say : "type `./configure' to configure the package for your system in the directory of the package. But I have an error : "No file named ./configure" in your directory.

Could you help me, please ?

![Capture d’écran du 2020-08-24 01-34-13](https://user-images.githubusercontent.com/52496172/90991508-3169dd80-e599-11ea-8f29-92e2e86acec2.png)

Thanks

**Comment by Jeremy7701** [comment]
Install the latest binary package - try `apt-get install nemo`, there are several nemo packages, but nemo and its dependencies should be sufficient for a working version.
I'd recommend that you try this in a VM first, since you don't have an official Mint or LMDE base version.

**Comment by pzim-devdata** [comment]
Ok , I think I will wait for Debian 11 Bullseye. It will have the stable version of Nemo 4 with it.  For now with Debian 10 Buster, when I try `apt install nemo`, I only have Nemo 3.8.5. Thank you ! :-)
