### ISSUE TITLE
Show custom folder/location icons in the sidebar (again)

### ISSUE THREAD

**Issue by mscheper** [linuxmint/nemo#2494]
```
 * Version: 3.8.6
 * Distribution: Mint 19
 * Graphics: Intel Corporation HD Graphics P630
 * 64 bit
 ```

**Issue**

The sidebar currently and exclusively uses what, in #747, are called 'symbolic icons', for the bookmarks and other locations. (I gather these come from the window manager.)

For many users, the custom icons they selected for their bookmarked folders are easier to recognise, especially when they have many bookmarks.

Users should have the option to have their custom icons appear in the Nemo sidebar, as per the regular behaviour in previous versions. Forums abound with requests, confusion and complaints about regression over this issue.

**Steps to reproduce**

1. Go to a folder that contains subfolders.
2. Right-click on the subfolder and select _Properties_.
3. Click on the folder icon, and select a custom icon.
4. Close the _Properties_ dialogue.
5. Drag the subfolder with the custom icon into the sidebar.

**Expected behaviour**

The folder appears with its custom icon in the sidebar.

**Actual behaviour**

The folder appears with the default icon in the sidebar.

**Other information**

It seems a _Sidebar_ Preferences option needs to be added to Nemo, with options for choosing 'symbolic' or regular icons, which sections should be shown, and the background colour, since some custom icons might not look so good on the standard dark grey background. (This can be changed by messing with the style sheet, but that may not be considered good practice.)

**Comment by landNull** [comment]
I would be curious to know the reason for removing this functionality? 
Does it provide any benefit in performance or stability? 
Would adding this functionality back cause any issues?

**Comment by Jeremy7701** [comment]
You need to do it a slightly different way.
1. Select your folder (or file)
2. Right-click on the subfolder and select Properties.
3. Click on the folder/file icon, and select a custom icon (or one of your own design in your home folder).
4. Close the Properties dialogue.

Don't forget that you can use several emblems on icons plus you can design your own and put them in `~/.icons`
AFAIK, the custom icons have to be named with a prefix of 'emblem-'. However, I'm not certain on this point.

For folders, you've also got the colour coding feature...
example:-

![Screenshot from 2021-03-16 13-55-37](https://user-images.githubusercontent.com/52585119/111322254-a1889f80-8660-11eb-9097-07a056d598c9.png)

**Comment by harrego** [comment]
@Jeremy7701 Are you referring to the sidebar icons? My understanding is that changeable file icons within the file explorer are independent to those within the sidebar, which cannot be changed.

**Comment by Jeremy7701** [comment]
Please ignore what I wrote!
Sidebar icons are not changeable - but folders/files in the main window are.

**Comment by mscheper** [comment]
> Sidebar icons are not changeable - but folders/files in the main window are.

Correct. In my view, this is a UI bug, especially since the icons used to be consistent.

**Comment by mtmehdi** [comment]
Still it is not customizable in version 20.2 (Uma) of Linux Mint. Would be great if the developers add this feature in future versions of Linux Mint.

**Comment by freder** [comment]
would be great, indeed!

**Comment by Oober** [comment]
I have also spent hours to find a solution to change the bookmarks' icons. So, I second this feature request.

**Comment by Ahmed00010** [comment]
2022 and the Feature hasn't been added
😒

**Comment by starfire213** [comment]
How in the world has this not been added, This is a basic feature that one would expect to be in a file manager, My videos and music directory became broken so i created new ones, but now they have normal folder icons instead of their respective icons. This should already be a feature.

**Comment by smurphos** [comment]
> How in the world has this not been added, This is a basic feature that one would expect to be in a file manager, My videos and music directory became broken so i created new ones, but now they have normal folder icons instead of their respective icons. 

You need to fix your xdg folder definitions in the file - ~/.config/user-dirs.dirs

**Comment by mtwebster** [comment]
As noted in the OP, this was deliberately removed. There are currently no plans to change this. This does not constitute a bug.

**Comment by Oober** [comment]
> As noted in the OP, this was deliberately removed. There are currently no plans to change this. This does not constitute a bug.

So, this issue is labeled as ”feature request” on November 2020.

You disagree with OP and majority of thread paricipants and close the issue. Interesting.

**Comment by JosephMcc** [comment]
Feature requests like these are closed fairly regularly. We know the idea is out there but have no current plans to change/add it.

**Comment by mscheper** [comment]
> As noted in the OP, this was deliberately removed. There are currently no plans to change this. This does not constitute a bug.

@mtwebster: I wrote the OP, and I'm not aware of it being deliberately removed. I filed it as a regression, not a feature request.

In any case, can you explain why this was deliberately removed? [A lot of people seem interested in the reasoning](https://github.com/linuxmint/nemo/issues/2494#issuecomment-799888242), and with 40 current upvotes for the OP, it seems an unpopular decision.

Can you suggest alternative file managers, that do this properly? Thanks.

**Comment by SolarDesalination** [comment]
> As noted in the OP, this was deliberately removed. There are currently no plans to change this. This does not constitute a bug.

What is the logic behind removing the feature? Monotone colours are harder to recognize which slows down folder recognition. It seems like a regression.

**Comment by premier69** [comment]
removing it is a feature of laziness on behalf of the maintainers.
