### ISSUE TITLE
Drag & drop of files and the anomalous display of a '+' indicator

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2496]
```
 * Nemo version 4.6.5
 * Issue with windowed nemo?
 * Distribution - (LMDE4)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
Dragging and dropping a file in one filesystem to a different filesystem e.g. to `/tmp` acts as a **copy** and paste.
Both filesystems are ext4 and mounted via fstab {I use separate mounts for / and /home}.
Whilst the dragged icon is hovering over the to-filesystem window, a '+' symbol is shown.

However,
Dragging and dropping a file in a filesystem to a sub-directory of the same filesystem acts as a move operation - but no '+' symbol is shown whilst the dragged icon is hovering over the to-filesystem window.

The above "problem" occurs regardless of whether nemo is dragging a file between two panes or two separate windows.

**Steps to reproduce**

As described above.

**Expected behaviour**

Drag and drop should always attempt a move operation - a copy operation should only be done if there are insufficient permissions to remove the original file.

**Other information**

**Comment by smurphos** [comment]
Hi @Jeremy7701 - the behaviour you describe (drag and drop between partitions defaults to copy and within partitions move) is pretty standard across numerous Desktop Environments (and I believe Windows for that matter). To force a move hold shift as you drop, to force a copy hold ctrl as you drop, to create a link crtl-shift, and to get a context menu hold alt. 

The mouse cursor hand icon denotes a move, + icon denotes a copy, arrow icon denotes link creation and a question mark the context-menu.

**Comment by Jeremy7701** [comment]
Thanks @smurphos - much simpler when you know how.
I'll add your comments to my idiots guide about "How to use nemo".
