### ISSUE TITLE
"Run in terminal" fails if path contains spaces

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#2499]
```
 * Nemo version 3.6.5
 * windowed nemo
 * Distribution - Ubuntu 16.04
 * 64 bit
 ```

**Issue**
If the path to an executable script contains spaces, "Run in terminal" does not handle spaces and bash tries to execute the path only up to the first space, resulting in a "file not found" error message.

**Steps to reproduce**

* Make sure Nemo is configured to ask which action to take for executable files
* Create bash script inside a folder with spaces in its path, e.g. ~/space name/script.sh
* Mark script.sh executable
* Double click script.sh in Nemo and select "Run in terminal"

**Expected behaviour**

script.sh is run in terminal.

**Comment by Jeremy7701** [comment]
Current version of Nemo is 4.6.5 ---
However, the problem still stands:-
`/home/jeremy/Desktop/temperature based cpu throttler.sh` [normally run elsewhere and with some underscores] outputs
![Screenshot from 2020-09-02 16-30-03](https://user-images.githubusercontent.com/52585119/92004024-9e1f6d80-ed39-11ea-9c25-f4ce14e738c7.png)

**Comment by leigh123linux** [comment]
It your bash script that is broken not nemo.

Either use '' to wrap it

`/home/jeremy/Desktop/'temperature based cpu throttler.sh'`

or

`'/home/jeremy/Desktop/temperature based cpu throttler.sh'`

or

`/home/jeremy/Desktop/temperature\ based\ cpu\ throttler.sh`

**Comment by Jeremy7701** [comment]
I never normally put spaces in scripts - but if I do, nemo should handle the issue in the same way as it does for opening the same file in a text editor.

This is not an issue for me since I have no difficult names in any scripts. ;)

**Comment by NikoKrause** [comment]
![4dlofp](https://user-images.githubusercontent.com/8415124/92011893-037c5a00-ed4c-11ea-8109-b7b3b5740b14.jpg)

**Comment by HifeFish** [comment]
Sorry about the old version, my bad.

@Jeremy7701 Thank you for looking into it on the newest version.

@leigh123linux The problem is not a line inside the script (even an empty script file produces the error), the problem is the path that nemo hands to the terminal. This path is generated by nemo, so the user has no way of adding quotes or escaping spaces as you suggest.

**Comment by clefebvre** [comment]
I agree with @HifeFish, this is a bug indeed.

**Comment by icarter09** [comment]
@HifeFish @Jeremy7701 what is `Terminal` set to in `Preferred Applications`?

**Comment by Jeremy7701** [comment]
I presume its set to `gnome-terminal` - at least that's what is run from the LMDE4 menu.

![preferred](https://user-images.githubusercontent.com/52585119/99151016-23a39000-2690-11eb-91cd-32ffccdf38d3.png)

**Comment by icarter09** [comment]
Yeah it is. There looks to be a couple of factors driving this issue and that setting looks to be one on them. Thanks.

**Comment by icarter09** [comment]
@Jeremy7701 @HifeFish  can either you try running 
`gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg --`   Thanks.

**Comment by Jeremy7701** [comment]
I made the gsettings change and no error messages are now generated.
(I checked the change had occurred with the GUI `dconf`).
A bash script (`document 1.sh`) which simply creates a file in /tmp was successfully 'run in terminal' from nemo.
