### ISSUE TITLE
Exact search with ""

### ISSUE THREAD

**Issue by plata** [linuxmint/nemo#250]
Search for the exact search string if surrounded with "".

E.g. 
- search for 'this pattern' will find 'this pattern' or 'this xyz pattern'
- search for ' "this pattern" ' should find 'this pattern' only

**Comment by Vahan86** [comment]
If I search for 'this pattern' it finds only 'this pattern' file/folder (tested in Nemo 3.0.6).

**Comment by Vahan86** [comment]
@plata, is this still an issue for you in latest version of Nemo?

**Comment by plata** [comment]
I'm not using Nemo at the moment. As no one else seems to have this issue, I close it.
