### ISSUE TITLE
Need help finding a Nemo settings config file

### ISSUE THREAD

**Issue by joaoherberto** [linuxmint/nemo#2507]
```
 * Nemo version (nemo --version) 4.6.5
 * Is issue with desktop or windowed nemo? Not sure
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Manjaro/Arch
 * Graphics hardware *and* driver used Radeon RX580
 * 64 bit
 ```

**Support Request**
I am creating a default skel that I can deploy on various machines. I want the Home directory in Nemo to use a specific icon size. I can set zoom level with the slider and every time I re-open Nemo it is set as I left it.  I have copied the ~/.cinnamon, ~/.config/nemo, ~/.local/share/nemo & ~/.config/dconf to the new skel but the only setting that does not stay set is the default Zoom level in the Home directory.
I also scoured through dconf-editor but could not find anything.

Any help would be greatly appreciated.

**Comment by mtwebster** [comment]
You can set each folder individually, so the info is stored in file metadata. Look at:

```
gvfs-info ~
```
You should see `metadata:` entries near the bottom (if you've modified the folder view in any way).

I'm not sure if you can pre-seed this onto a new home folder (you'd have to try), but it can be scripted.  There are a number of gvfs-xxx tools you can check out.

**Comment by Jeremy7701** [comment]
I get:-
> gvfs-info ~
> This tool has been deprecated, use 'gio info' instead.
> See 'gio help info' for more info.

But both commands produce the same output.

**Comment by joaoherberto** [comment]
I am thoroughly confused... the metadata for each folder is stored...where? I see I can use `gio info ~`and I see the output and the metadata::nemo-icon-view-zoom-level:4,  but where is that stored so I can transfer it?

**Comment by joaoherberto** [comment]
OK, I think I understand... gio has more options than info, looks like I need to figure out "gio set" command... aya yay yay, this is turning out to be more work than have a folder size should have thrown at it.

Thank you for your help.  I am going to get a stiff drink now.

**Comment by mtwebster** [comment]
This is all managed by gvfs - and stored in ~/.local/share/gvfs-metadata - it's not something we generally deal with directly, we just store and fetch info for specific folders, as if it were any other folder/file info.

Why not just set the default icon size in preferences? That's stored in dconf:
![image](https://user-images.githubusercontent.com/262776/93594384-b91dee80-f983-11ea-91cc-ba476a4a646b.png)

Any folder that hasn't had its view specifically altered will default to these settings, including the home folder.
