### ISSUE TITLE
Right click while dragging causes dropping

### ISSUE THREAD

**Issue by teo1978** [linuxmint/nemo#2508]
```
 * Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? windowed; maybe both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Ubuntu 20.04
 * Graphics hardware 

Intel Corporation 3rd Gen Core processor Graphics Controller
NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]

*and* driver used - I'd be happy to tell you if it showed up in system information

 * 32 or 64 bit: 64
 ```

**Issue**

**Steps to reproduce**

1. Start dragging an icon (a folder or file) from a Nemo window, by pressing the left mouse button on it and then moving the mouse while holding the button pressed.
2. Drag the icon onto something where it could be dropped. DON'T drop it (that is, don't release the left mouse button). For example, you can drag it onto a folder (dropping it there would move the file or folder into the target folder), or you can drag it onto one of the folders in the breadcrumb on the top of the window; or even outside of Nemo into another application.
3. WITHOUT releasing the left mouse button, click the right mouse button. Still hold the left button pressed.

**Expected behaviour**

There is a range of possible behaviours that could be considered correct, but NONE of these include dropping the icon that you are dragging. A drag-n-drop operation that starts by pressing a mouse button can only be completed by releasing that same mouse button. Whatever else I do while I keep the left button pressed can only have one of two outcomes: either being ignored (i.e. keep dragging as if nothing happened) or to abort the drag-n-drop operation (that is for example what happens when you hit the Esc key while dragging, before releasing the left button).

**Observed behaviour**

The instant you click with the right button (that is, the instant you release the right button), the icon you were dragging is dropped,. That is, it behaves as if you had released the left button, even if you haven't.

This is VERY serious, because it can cause you to accidentally move stuff. It breaks the basic contract that if I start a drag-n-drop operation by pressing a button, I must be able to trust that never under any circumstances the operation will be confirmed until I release the button whose pressing started the operation.

**Other information**

**Comment by Jeremy7701** [comment]
This effect also occurs in the current version of nemo - 4.6.5, in LMDE4.
A similar effect is observed if the left button is continually pressed, but the middle button [actually the scroll wheel] is pressed.

It is as if any button-down event is treated as equivalent to a left-button-up event.

**Comment by selmiak** [comment]
This is bad, please fix this.

**Comment by Jeremy7701** [comment]
I think we should leave it to "the team" to decide on appropriate priorities for bug fixing.
Have to say that although I can replicate this bug, it does not affect me personally in everyday use.

**Comment by mtwebster** [comment]
I'm really not sure we can do anything here. During a drag, the client program stops receiving events such as pointer clicks, so we cannot 'ignore' an event from the wrong button here.

I've tested this with other applications that use the same toolkit (gtk3) and got the same behavior.

Trying with another toolkit (qt), right-clicking while dragging pops up the 'ask' menu (copy/move/link/cancel) which doesn't seem to be a bad idea.

I think you would need to raise this with gtk (https://gitlab.gnome.org/GNOME/gtk/-/issues)
