### ISSUE TITLE
UI problem with arabic (icons)

### ISSUE THREAD

**Issue by nasserbinlaboun** [linuxmint/nemo#2509]
```
 * Nemo version 4.6.5
 * Is issue with desktop or windowed nemo? I think nemo
 * Distribution - Mint 20
 * 64 bit
 ```

**Issue**
Back Icon is flipped. Also some other icons should be flipped to other side like (Hide sidebar icon and Path icon).

![bug-nemo](https://user-images.githubusercontent.com/46214964/93668380-6c1d4380-fa7b-11ea-871f-016bb0424c7e.png)

**Steps to reproduce**
Run nemo.

**Comment by nasserbinlaboun** [comment]
Update: 
```
 * Nemo version 5.6.4
 * Is issue with desktop or windowed nemo? I think nemo
 * Distribution - Mint 21.1
 * 64 bit
```

Back icon showing correctly now, but other icons should be flipped to other side like (Hide sidebar icon and Path icon).

![Screenshot_2023-04-17_20-58-55](https://user-images.githubusercontent.com/46214964/232571063-b33a2b1a-ca3f-4464-94a4-4b4597a2b02c.png)

**Comment by JosephMcc** [comment]
Don't remember if we actually include these icons or they use standard named icons but the issue here is that they probably don't have right-to-left versions as part of the theme. The other icons do which is why they show correctly.

**Comment by mtwebster** [comment]
Let me know if it looks like I missed anything - 
![image](https://user-images.githubusercontent.com/262776/234082022-2682e0e2-3457-4e9e-ac37-9be33d6bb5bd.png)

I fixed the disk space indicator positions in the sidebar also.

**Comment by nasserbinlaboun** [comment]
@mtwebster It looks awesome, thank you very much for your work.
