### ISSUE TITLE
[Feature request] Show file-count for the current directory (to keep a cautious eye on things)

### ISSUE THREAD

**Issue by methuzla** [linuxmint/nemo#251]
Nemo should show the number of items & files (at least) in the current directory.
I understand some people prefer not to be informed about such details & see them as clutter; I would be happy if the display were optional.
Maybe it doesn't need a whole footer status bar; perhaps such a count could be placed in other unused space in the panel. It remains essential information.

Why? one - Data security: 
In the last year or so, I have twice suffered file corruption. I am uncertain of the exact reason, I suspect faults in the filesystem handling. Although I didn't see many reports, I can't believe I was alone in losing data. 
What alerted me to data-loss was the sudden reduction in item-counts in a large directory.
Without that, I would not have known there was a problem; as it was, I was able to stop the rot fairly promptly.

This for me is a deal-breaker. 

Why? two - Usability: 
(Rather less important but a little irksome.) When opening a new directory on anything but a super-computer, one is currently faced with a blank panel, and must wait for an undefined time to assess whether loading is complete. No indication as to whether the directory is in fact empty, or is rather large & taking its time. 
There is potential for deleting a non-empty directory when tidying up, if one is impatient. (At times, one is impatient.)
Yes there are work-arounds; that isn't the point.
I would like to see a status  "loading" until the count is complete.

A more general allied point - call me old-fashioned, but I do like programs to let me know what they are doing rather than act secretively & with dumb insolence. It's particularly noticeable when nemo searches a large directory structure - there is no indication of progress. Should one take a deep breath, of fetch a cup of tea, or come back the next day? (Or give up & do something else.)

At least one other person in the world regards removing the file-count as utter lunacy (but can I find the conversation? No).

Removing useful information seems to be a current fashion. There will be cause for regret.
An example of the more mature way of doing things can be seen here
http://wiki.lxde.org/en/File:PCMan_File_Manager.png

There is a whole other philosophical argument about whether a count (/size) of hidden files should appear, relevant to file back-ups & tidy-up deletions. I suspect the top answer is, "only with elevated privileges".

**Comment by Vahan86** [comment]
The file count is displayed on status bar which is located at the bottom of the screen and enabled by default in Nemo.

@JosephMcc, can we close this issue?
