### ISSUE TITLE
Nemo requires newer xapp dependency

### ISSUE THREAD

**Issue by SparkyBluefang** [linuxmint/nemo#2510]
Nemo 4.6.2 introduced a dependency on `xapp-status-icon.h` but still declares a dependency on xapp >=1.4.0. It looks like `xapp-status-icon.h` was added in xapp 1.6.0

https://bugs.gentoo.org/743427
https://github.com/gentoo/gentoo/pull/17597

**Comment by icarter09** [comment]
Looks like this has been fixed on Gentoo. https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=842b34ecef048eeeeebcd19b9f9518cf6ab96db6

@SparkyBluefang can you confirm this? Thanks.

**Comment by SparkyBluefang** [comment]
Yes, we did fix this downstream in Gentoo by updating the ebuild dependency requirement.

However, this was filed with respect to nemo's build system not enforcing the newer version requirement.

https://github.com/linuxmint/nemo/blob/7eb171cef6391af67d186c90f8f5af695bf37343/meson.build#L85

**Comment by icarter09** [comment]
Xapp version requirement has been upgraded to `>=1.9.0`
