### ISSUE TITLE
"Open In Terminal" fails when default terminal is set to "gnome-terminal --maximize"

### ISSUE THREAD

**Issue by yevgenykuz** [linuxmint/nemo#2516]
```
 * Nemo version: 4.6.5
 * Distribution: Linuxmint 20 ulyana
 * Graphics:
           Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           Resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 20.0.8 
 * 64 bit
 ```

"Open In Terminal" fails when default terminal is set to "gnome-terminal --maximize".
Removing the " --maximize" flag fixes the issue.

This can be reproduced by editing the default terminal command (by using "dconf editor", for example).
The value to edit is found at `org.cinnamon.desktop.applications.terminal.exec`

Potentially related issues:
https://github.com/linuxmint/nemo/issues/2499
https://github.com/linuxmint/nemo/issues/2376

**Comment by mtwebster** [comment]
There's another key `exec-arg` for this purpose, you need to put `--maximize -e` in that, and leave the exec command just `gnome-terminal`

**Comment by yevgenykuz** [comment]
Thanks for replying @mtwebster.
I tried the `exec-arg` key before however it just doesn't work for some reason (the terminal doesn't open maximized).
`--maximize -e`, `--maximize -x`, `--maximize --`, `--maximize -- `, `--maximize` - none worked.
It fixes the issue in nemo but i don't have the expected result.

Using the `exec` key for the argument works in all scenarios except in nemo for some reason.

**Comment by yevgenykuz** [comment]
@mtwebster maybe some string checks can be performed before this call to cover this edge case (even if the root cause may not be related to nemo):https://github.com/linuxmint/nemo/blob/17734bf9523a63e528ed20218831eaeaef16e5a4/eel/eel-gnome-extensions.c#L52

**Comment by icarter09** [comment]
@yevgenykuz are you setting `gnome-terminal --maximize` in the exec cmd or were you able to get the exec-arg to work? Sounds like you did not, but wanted to make sure prior to working on this ticket. Thanks.

**Comment by yevgenykuz** [comment]
@icarter09 I couldn't get exec-arg to work unfortunately.

**Comment by icarter09** [comment]
@yevgenykuz setting the `exec-arg` custom value to `--maximize --` seems to work for me. The rest of the values you referenced did not work for me either.

**Comment by yevgenykuz** [comment]
@icarter09 Maybe something changed since the last time i checked.
I will try again as soon as i get back home (in a week), so if i'm the only reason for working on this it may be avoided if i'll get it to work with exec-arg.

**Comment by icarter09** [comment]
Thanks for the quick response and no worries on the timeline. I'll wait to see if it does work for you before preceding further. Thanks

**Comment by yevgenykuz** [comment]
@icarter09 I've spun up a fresh Mint VM, installed all updates, and tried all options again (logging out and in between each one), including `--maximize --`. Unfortunately, none worked.

Launching from Mint start menu shortcuts or default panel launcher, right clicking from desktop/nemo and `Open in Terminal`, typing `gnome-terminal` in a terminal - all open non-maximized (these are all the cases i use in which i need the maximized window).

Did you change `org.cinnamon.desktop.applications.terminal.exec-arg` only or did you try a different setting?

**Comment by icarter09** [comment]
I was only changing the `org.cinnamon.desktop.applications.terminal.exec-arg` setting

**Comment by icarter09** [comment]
@yevgenykuz are you able to share the file/script you are trying to run? Thanks.

**Comment by yevgenykuz** [comment]
@icarter09 I'm trying to launch using the default shortcuts/launch methods that come with a fresh linux Mint installation, no custom scripts/files.

**Comment by yevgenykuz** [comment]
It still doesn't work after the last 20.1 release unfortunately.
A fresh linux mint 20.1 VM, nothing custom.
Right clicking on desktop/any other folder in nemo and then clicking `Open In Terminal` never opens a maximized terminal window, even when setting `org.cinnamon.desktop.default-applications.terminal.exec-arg` to `--maximize --` (by typing `gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg "--maximize --"`).

@icarter09 I hate leaving open issues, so unless you have any other suggestion this issue can be closed.
