### ISSUE TITLE
Can't Restore Deleted Folder

### ISSUE THREAD

**Issue by AhmadHerzallah** [linuxmint/nemo#2524]
```
 * Cinnamon version (cinnamon --version): Cinnamon 4.2.4
   - Please specify if you are using the daily builds PPA: No
 * Distribution - Linux Mint 19.2 Tina
 * Graphics hardware *and* driver used: Intel HD Graphics 620 driver: i915
 * 32 or 64 bit: x86-64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[syslog.txt](https://github.com/linuxmint/cinnamon/files/5316814/syslog.txt)

 ```

**Issue**
I made two copies of a folder, and when I deleted the first copy of the folder, the second one got deleted, when I checked the trash folder I didn't find the folders, so I tried testdisk and photorec and a lot of ways to recover the data, but it recovered so old files and didn't recover the file that I deleted.

**Comment by Jeremy7701** [comment]
Which version of nemo do you have?
The current version of nemo is 4.6.5.
Are you able to replicate this in Mint 20?

I tried creating an empty folder, deleting it, then repeating this (in nemo 4.6.5)
The rubbish bin showed two folders of the same name.

**Comment by AhmadHerzallah** [comment]
my nemo version is 4.2.3

**Comment by icarter09** [comment]
@AhmadHerzallah let us know if you continue to experience this problem once you've upgraded. Thanks.
