### ISSUE TITLE
file names are shown in white characters on white background after copy

### ISSUE THREAD

**Issue by herrdeh** [linuxmint/nemo#2532]
```
 * Nemo version (nemo --version)
4.4.2
 * Is issue with desktop or windowed nemo?
windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
ubuntu GNOME 20.04 - GNOME 3.36.3
 * Graphics hardware *and* driver used
nvidia 450
 * 32 or 64 bit
64bit
 ```

**Issue**
file names are shown in white characters on white background after copy

**Steps to reproduce**
- open a new window
- divide it in two parts (hit F3)
- select another directory with the 2nd window half
- move one or a few files to the 2nd window half

**Expected behaviour**
file names are legible - but it looks like this:

![Bildschirmfoto von 2020-10-10 22-03-19](https://user-images.githubusercontent.com/7152847/95664065-a6db3e80-0b44-11eb-8dfc-edf5f9b692ea.png)

**Other information**
Whole machine was installed cleanly.
Themes are these:
![Bildschirmfoto von 2020-10-10 22-04-12](https://user-images.githubusercontent.com/7152847/95664058-9c20a980-0b44-11eb-898b-7393f7c6faf8.png)

**Comment by leigh123linux** [comment]
You need to report the issue against yaru theme.
