### ISSUE TITLE
".md" files are opened in firefox

### ISSUE THREAD

**Issue by Megatokio** [linuxmint/nemo#2538]
```
 * Nemo version 4.6.5
 * Is issue with desktop or windowed nemo?
 * Distribution - Mint 20
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
clicking on a "*.md" file starts firefox but firefox can't even display it.

**Steps to reproduce**
click on a "*.md" file

**Expected behaviour**
should open mark down editor or the default text editor.

**Other information**
In "Prefered Application" Firefox is only registered for "Web".

**Comment by Jeremy7701** [comment]
Not a nemo problem!

1. In Nemo, right-click on any file with the desired file type or extension, choose “Properties” from the context menu.

2. The “Properties” dialog appears. Click on the “Open With” tab.

3. Select the desired application(s) for the given filetype. Choose the appropriate default application plus any other desired applications. All files with the same filetype will now be opened in the appropriate way.

**Comment by Megatokio** [comment]
this was more like a layer 8 problem. :-] 
i was thinking too complicated and overlooked the obvious.
thank you for the quick answer and directing me in the right direction.
