### ISSUE TITLE
Feature request : registering the F3 state in Nemo

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/nemo#2540]
```
 * Cinnamon version 4.6.7
 * Nemo version 4.6.5
 * No PPA
 * Mint 20 Cinnamon
 * 64 bit
 ```

**Issue**

Nemo doesn't keeps extra panel/no extra panel state. We need always to press F3 after Nemo starting.

**Steps to reproduce**

Start Nemo
Press on F3 to have 2 panels
Quit Nemo
Start Nemo : only one panel instead of two !

**Expected behaviour**

Start Nemo with the same number of panels as after quitting Nemo.

Same bug in CAJA : https://github.com/mate-desktop/caja/issues/277

**Comment by Jeremy7701** [comment]
nemo doesn't  preserve any path info about a single panel - it always starts in the same folder.
A double pane would require two paths + F3 state info.

**Comment by InfoLibre** [comment]
Wouah, I just discovered this option :

![Capture d’écran du 2020-10-29 19-59-15](https://user-images.githubusercontent.com/3955499/97620058-4ba0bb80-1a21-11eb-9560-0aff27cc7af2.png)

:+1:
