### ISSUE TITLE
Nemo crashes with two tabs shown in different view types

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2543]
```
 * Nemo version 2.6.5
 * Is issue with desktop or windowed nemo - Windowed
 * Distribution - LMDE4)
 * 64 bit
 ```

**Issue**
Nemo crashes, see "Steps to reproduce"

**Steps to reproduce**
1. Open 2 tabs in nemo, displaying _either_ the same folder or different folders.
2. Set one tab to icon view, the other to list view.
3. In the icon view tab, right-click and select 'Create new document'
4. A new icon is produced, with the text pre-selected [to allow a decent name to be given]
5. Left-click outside the icon (but within the nemo window)
6. Nemo crashes!

I got a big core dump [118MB] - but unfortunately also,
> The debug symbols are missing for nemo. Please install nemo-dbg.

**Expected behaviour**

_Essentially, two tabs should operate in the same way as two separate windows._

**Other information**
This also occurs with two tabs, one in list view and the other in compact view.
If both tabs are in the same view type, everything is fine.

**Comment by icarter09** [comment]
Nemo 4.8.2
Mint 20 64bit

I'm not able to reproduce this issue with the steps provided.

**Comment by Jeremy7701** [comment]
Cannot reproduce in 4.6.5

**Comment by Jeremy7701** [comment]
Closed
