### ISSUE TITLE
Can't move directories to Trash

### ISSUE THREAD

**Issue by areographe** [linuxmint/nemo#2558]
```
 * Nemo version (nemo --version): 4.6.5
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Manjaro Cinnamon 5.9.8-1
 * Graphics hardware *and* driver used:
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:1916 
           Display: x11 server: X.Org 1.20.9 compositor: muffin driver: intel 
           unloaded: modesetting alternate: fbdev,vesa display ID: :0 screens: 1 
           Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2") 
           s-diag: 582mm (22.9") 
           Monitor-1: eDP1 res: 1920x1080 hz: 60 dpi: 157 size: 310x170mm (12.2x6.7") 
           diag: 354mm (13.9") 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.2.2 
           direct render: Yes 


 * 32 or 64 bit: 64-bit
 ```

**Issue**
I have a home partition mounted at `/home`. If I use Nemo to move any file within `~` to Trash, it works. However, if I try to move any directory within `~` to Trash, it gives me the following warning:

`Cannot move file to trash, do you want to delete immediately? Trash portal failed on ` and then the name of the directory.

I've checked a few of the other bugs mentioning similar errors but this seems different, as the only issue is moving a *folder* to Trash, while moving *files* has no issue.

I can confirm that the directories I've tested this on have had 'myusername:myusername' in terms of ownership and group, as does the `~/.local/share/Trash` directory. I have also tried running `gksu nemo` to use Nemo with elevated privileges, and the same error occurs, even when creating an empty folder in /root and then attempting to move it to Trash.

**EDIT:** I have now tried to move some of the same directories to Trash using `trash-cli` and it works. Looks like it might be a bug exclusive to Nemo, although I don't have any other file managers installed at the moment.

**Steps to reproduce**

Try to move a folder to Trash in Nemo.

**Expected behaviour**

It should move the folder to Trash, but doesn't.

**Comment by leigh123linux** [comment]
The issue doesn't reproduce here.

**Comment by areographe** [comment]
OK! Do you have any suggestions for how I can narrow down what's causing this issue, or any advice on where I should open this issue (e.g. gvfs, cinnamon, etc) @leigh123linux ? Thanks!

**Comment by leigh123linux** [comment]
To test try

`gio trash /path/to/test/directory`

**Comment by areographe** [comment]
Same error, thank you, I will try to file a bug against `gio` / Glib. Cheers!
