### ISSUE TITLE
I can't change the icon of a folder

### ISSUE THREAD

**Issue by hrqmonteiro** [linuxmint/nemo#2566]
```
 * Nemo version: 4.6.5
 * Windowed Nemo
 * Distribution: Void Linux
 * Geforce 920m
 * 64-bit
 ```

I can't change the icon of any folder in Nemo. I do `right-click > properties > click on icon > select another` but as soon as i click 'select' it doesn't change to the new icon. It remains the same.
![2020-11-22_16-22](https://user-images.githubusercontent.com/17055027/99914853-f3d33880-2cde-11eb-9107-d25cf076b7e8.png)
![2020-11-22_16-22_1](https://user-images.githubusercontent.com/17055027/99914857-f6359280-2cde-11eb-87d3-14a66b4f4542.png)
![2020-11-22_16-22_2](https://user-images.githubusercontent.com/17055027/99914860-f9308300-2cde-11eb-826e-fe1e23dc8fbe.png)

**Comment by Jeremy7701** [comment]
Because I have removed the excess directories that nemo pre-creates for me {~/video, ~/downloads etc),
I created a new empty directory in ~/ and followed the above procedure to successfully get a successful change to the icon.
However, I'm using LMDE4 which appears to provide thousands(?) of icons for each theme.
It is not necessary to choose a folder-style type of icon.

**Comment by leigh123linux** [comment]
> Because I have removed the excess directories that nemo pre-creates for me {~/video, ~/downloads etc),

Don't make rubbish up if you don't know, xdg-user-dirs creates those directories not nemo!

> I created a new empty directory in ~/ and followed the above procedure to successfully get a successful change to the icon.
> However, I'm using LMDE4 which appears to provide thousands(?) of icons for each theme.
> It is not necessary to choose a folder-style type of icon.

**Comment by hrqmonteiro** [comment]
> > Because I have removed the excess directories that nemo pre-creates for me {~/video, ~/downloads etc),
> 
> Don't make rubbish up if you don't know, xdg-user-dirs creates those directories not nemo!
> 
> > I created a new empty directory in ~/ and followed the above procedure to successfully get a successful change to the icon.
> > However, I'm using LMDE4 which appears to provide thousands(?) of icons for each theme.
> > It is not necessary to choose a folder-style type of icon.

Ok, so what do i have to do to make it work? I didn't do anything the guy above did, and my Directories are the default ones created by xdg-user-dirs. What do i have to do to solve it?

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I'm not able to reproduce this issue. Following the steps you provided `right-click > properties > click on icon > select another`, I was able to successful change the icon.

**Comment by hrqmonteiro** [comment]
Well, in here it doesn't work. I will try to screen record it so you can follow it better.

Also is it possible that i get a log of it? I'm not that very used to use Nemo, i recently switched to it.

**Comment by hrqmonteiro** [comment]
Also, something that came to my head now: is it possible that this function only works when using Nemo with cinnamon?
Cause i'm not, i am using AwesomeWM.

**Comment by hrqmonteiro** [comment]
> Nemo 4.6.5
> Mint 20 64bit
> 
> I'm not able to reproduce this issue. Following the steps you provided `right-click > properties > click on icon > select another`, I was able to successful change the icon.

Here's a record of me trying to change it.

![simplescreenrecorder-2020-11-23_22 47 06](https://user-images.githubusercontent.com/17055027/100036023-1d26be00-2dde-11eb-8562-6445aac50219.gif)

**Comment by hrqmonteiro** [comment]
When i launch nemo on a terminal i got the following: 

```Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop```
