### ISSUE TITLE
Feature request: enqueue multiple files to Celluloid from Nemo

### ISSUE THREAD

**Issue by FBachofner** [linuxmint/nemo#2567]
Hi @clefebvre and LM development team:

VLC's main desirability over Celluloid (for me, at least) is that enqueueing multiple files from the file manager is simple (right click or double-click on files, etc.).  With Celluloid, only drag and drop is possible (and, until my recent [feature request](https://github.com/celluloid-player/celluloid/issues/601) of the Celluloid team, only to the playlist portion of the window; as of today, new builds will apparently allow drag-and-drop anywhere within the player window).

In response to my enhancement requests @gnome-mpv has **_also_** added a new action which will enable you to add the enqueueing feature to Nemo.

Please specifically reference:

- https://github.com/celluloid-player/celluloid/issues/601#issuecomment-731720375
- https://github.com/celluloid-player/celluloid/commit/026f95dfe96c9d4475d506f1ccaa37dc90ebfc2b

I sincerely hope the Mint team will add such new functionality ASAP.  Like you I am interested in keeping people off snaps (and/or flatpack -- although the Mint team does not seem to dislike flatpacks quite as much as I do ;-)

For further information you can see my original post on the LinuxMint forums:
https://forums.linuxmint.com/viewtopic.php?p=1918794

Thank you for your consideration and continued good luck on the most elegant Linux distro!

**Comment by haggen88** [comment]
It would be very useful !

**Comment by leigh123linux** [comment]
Mint celluloid already has that commit

https://github.com/linuxmint/celluloid/commit/026f95dfe96c9d4475d506f1ccaa37dc90ebfc2b

This issue has nothing to do with nemo.
