### ISSUE TITLE
Links to executables do not run, where the link contains a space - and this affects xfce4-terminal even after applying the gsettings workaround

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2571]
```
 * Nemo version (nemo --version) 4.6.5
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64
 ```

**Issue**

[EDITED.]

When I use Nemo to run-in-terminal a script that has a space in its leafname, an error box appears, saying , ' No such file or directory'.

**Steps to reproduce**

[Edited for: easier reproducibility; clarity; and to ensure that the error message that I give is the one that appears on the latest version - well, version 5.6.4 - of nemo.]

1. Have a executable bash script `~/testy McTesty`
2. . Use Nemo to make a link to it. (The link can be left where it is created, which can be in `~`.)
3. Run the link via Nemo, with Nemo set to ask what to do when running executables - choose 'run in terminal' when asked.
4. See error window that says: 'Failed to execute child process "/home/<myUser>/testy": Failed to execve [_sic_]: No such file or directory.'

**Expected behaviour**

The executable should run.

**Other information**

- I have the problem using both Gnome terminal and xfce4-terminal.
- File manager PcManFm does not have the problem - it runs the executable.
- **I tried the gsetting workaround (`gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg -- `) recommended in #2499) and that makes things work for Gnome-terminal _but not for the xfce terminal_.**
- I open this the present issue at the request of icarter09.

**Comment by LinuxOnTheDesktop** [comment]
It would be nice were this fixed for Mint 20.1. It does seem to be a fairly irritating problem.

**Comment by LinuxOnTheDesktop** [comment]
Still an inconvenience in Mint 20.1. Please note that the sum of small inconveniences is a system that one does not want to use.

**Comment by LinuxOnTheDesktop** [comment]
It would be nice were this rather throwing glitch to be fixed in Mint 20.2.

**Comment by LinuxOnTheDesktop** [comment]
It would be nice were this rather throwing glitch to be fixed in Mint _21_.

**Comment by Jeremy7701** [comment]
The **current** nemo stable (5.4.3) doesn't have this fault with gnome-terminal (the cinnamon offering).
The plugin `nemo-terminal` has a configure screen - maybe this fixes xfce4-terminal?

**Comment by LinuxOnTheDesktop** [comment]
> The current nemo stable (5.4.3) doesn't have this fault with gnome-terminal (the cinnamon offering).

But it does have it with xfce4-terminal and one should not need a plugin to fix the problem.

I installed nemo-terminal (`sudo apt install nemo-terminal`). I went to its configure screen. I see nothing relevant there.

**Comment by LinuxOnTheDesktop** [comment]
The problem persists on Nemo 5.6.4 under Mint 21.1 Cinnamon.

I have not tried to reproduce the problem on Mint 21.2. (Sorry about that. I was going through issues that I opened in order to close those that have been fixed; I thought this one might have been fixed, but it turns out that it has not.) I have edited my original report for clarity and reproducibility.
