### ISSUE TITLE
Nemo Terminal plugin - If active, then all subsequent windows have the plugin activated

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2576]
```
 * Nemo version (4.6.5)
 * Issue with windowed nemo?
 * Distribution - (LMDE4)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
If Terminal plugin is configured to be 'Visible by default = off' but activated in one nemo window then:-
Any subsequent nemo window that is opened defaults to having the Terminal activated.

**Steps to reproduce**
Open nemo window.
Press F4 to activate the Terminal plugin.
Open a second, third, fourth etc Window - they will default to having the Terminal Plugin activated.

**Expected behaviour**
When a new window is opened, it should default to having the Terminal plugin deactivated, especially since there is a preferences setting to make it 'Visible by default = off/on'.

**Other information**
Terminal used = gnome-terminal

**Comment by ItzSwirlz** [comment]
@Jeremy7701 please relocate to https://github.com/linuxmint/nemo-extensions

**Comment by Jeremy7701** [comment]
How do I transfer this to linuxmint/nemo-extensions?

**Comment by icarter09** [comment]
@Jeremy7701 you'll have to close this ticket and recreate it.

**Comment by Jeremy7701** [comment]
relocated to https://github.com/linuxmint/nemo-extensions
