### ISSUE TITLE
Fewer emblems available in 4.8.2

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2601]
```
 * Nemo version (nemo 4.8.2)
 * Is issue with windowed nemo?
 * Distribution - (Mint 20.1Beta)
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
Not many emblems available:-

Nemo 4.6.5 
![2020-12-24@00-04-43](https://user-images.githubusercontent.com/52585119/103045524-c21eed00-457c-11eb-83db-334928ffc33a.png)

Nemo 4.8.2
![2020-12-24@00-05-37](https://user-images.githubusercontent.com/52585119/103045606-2346c080-457d-11eb-8534-8db1074922e0.png)

**Steps to reproduce**

Install Mint 20.1 Beta, default configuration.

**Expected behaviour**

Similar quantity of emblems

**Other information**
I added **four** extra icons of my own in 4.6.5 - but 4.8.2 appears deficient...

**Comment by NikoKrause** [comment]
Sorry, but to me it looks like you are comparing apples with pears. The first image looks like the Mint-X theme to me. The second one is Mint-Y. Switch your icon theme to Mint-X and restart your computer or killall nemo.
