### ISSUE TITLE
Nemo crashes expanding folder with no files in it

### ISSUE THREAD

**Issue by dradma** [linuxmint/nemo#2614]
```
 * Nemo version: Up to and including 4.8.4
 * Is issue with desktop or windowed Nemo?: Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint Up to and including 20.1
 * Graphics hardware *and* driver used: Nvidia 1080Ti, nividia-driver up to and including 4.55
 * 32 or 64 bit: 64 bit
 ```

**Issue**

Nemo crashes when expanding a folder that all contents has been removed from. This has happened for several years now and I'd like to see it finally resolved.

**Steps to reproduce**
- Open Nemo in list view
- Open a terminal in same folder
- Create test folder in terminal
- CD into test folder
- Touch testfile
- Verify new folder in Nemo window (no expander arrow visible)
- Reload (CTRL+R) Nemo and verify expander arrow visible (**do not expand**)
- rm testfile in terminal window
- Click arrow to expand test folder in Nemo
- Nemo crashes and creates segfault

**Expected behaviour**

Nemo expands folder that says (Empty) but doesn't crash

**Other information**

This is only an issue with applications that create folders and tmp files but sometimes remove these files leaving a list of "expandable" folders of which some do not contain files but Nemo shows each as expandable, SABnzbd is one example.

**Comment by ItzSwirlz** [comment]
What is the Segfault?  Can you attach any error logs? (use mintreport)

**Comment by dradma** [comment]
Output of mintreport:

[crash.tar.gz](https://github.com/linuxmint/nemo/files/5762942/crash.tar.gz)

**Comment by icarter09** [comment]
Issue looks to be assertion failures from the fact that a change has taken place in the TreeModel and hasn't properly communicated that change to the TreeView.

**Comment by ItzSwirlz** [comment]
Bug Reproduced on Ubuntu Cinnamon Remix 21.04 Hirsute. Waiting for ubuntu-bug to get the info, I have the dbgsym installed
