### ISSUE TITLE
Nemo 4.x on Ubuntu 18.04

### ISSUE THREAD

**Issue by etkaar** [linuxmint/nemo#2615]
Do you know if Nemo 4.x will work on Ubuntu 18.04? Unfortunately only the old 3.x is available.

**Comment by ItzSwirlz** [comment]
It will most likely not without xapp and stuff like that.. 18.04 isn't really paid attention to me or any UCR devs anymore.

**Comment by NikoKrause** [comment]
Nemo should have the same choice of name as Cinnamon.
This means, that Cinnamon 4.4 comes with Nemo 4.4 etc.

This said: The last Mint version based on Ubuntu 18.04 was Mint 19.3, which comes with Cinnamon 4.4. Therefore Nemo 4.4 does work on Ubuntu 18.04.

You'll probably will have to compile it yourself though, but it should work, if all dependencies are met:
https://github.com/linuxmint/nemo/releases/tag/4.4.2

**Comment by leigh123linux** [comment]
The question has been addressed.
