### ISSUE TITLE
Opening or moving PNG pictures files on the desktop becomes very slow

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/nemo#2622]
```
 * Nemo 4.6.5
 * Is issue with desktop : desktop
 * Mint 20 Cinnamon
 * 64 bit
 ```

**Issue**
I'm not using Nemo but only Pix.
When I open, resize and close PNG files with Pix and if these files are on the desktop, after a few minutes, it becomes very slow to move these files on the desktop or to open them with Pix.
A nemo-desktop task appears and I must manually kill it.

![Capture d’écran du 2021-01-07 18-00-37](https://user-images.githubusercontent.com/3955499/103924509-6aed5080-5116-11eb-85dd-03408655833b.png)

**Comment by icarter09** [comment]
@InfoLibre could you provide more detailed steps to reproduce? I followed the steps, but had no luck reproducing the issue. Thanks.

**Comment by InfoLibre** [comment]
In a terminal, I write this command :
top|grep nemo

After, I register a PNG picture (a screenshot) on the desktop. I open it with Pix, crop it, register it, close Pix and move the picture icon on the desktop, with my mouse. I do all these things again and again. After about 20 times, nemo-desktop begins to take more and more memory and moving the picture icon on the desktop begins very difficult to do.

![Capture d’écran du 2021-01-10 12-22-59](https://user-images.githubusercontent.com/3955499/104121533-3a3c2f80-533f-11eb-8ce2-7411c1dd947f.png)

**Comment by InfoLibre** [comment]
I've got a lot of files on my desktop. Perhaps it is one of the reasons why it is buggy.

**Comment by InfoLibre** [comment]
TI don't have anymore this bug since Linux Mint 21.

**Comment by InfoLibre** [comment]
I close this bug report.
