### ISSUE TITLE
Revisiting scrollbar covers Eject button

### ISSUE THREAD

**Issue by mcoyle1960** [linuxmint/nemo#2631]
This issue was mentioned before and closed ([#2234]([url]https://github.com/linuxmint/nemo/issues/2234(url))) because of a suggested workaround, but I feel that was premature. There are several workarounds to avoid the issue, but at its root the issue still exists. 

In the Sidebar, the scrollbar cover the Eject button rendering it useless.

As an Ubuntu/Gnome user, I feel nemo is the best manager out there, hopefully this fixing this issue makes it even better. Thanks.

```
 * Nemo version (4.6.5)
 * Windowed Nemo?
 * Distribution - Ubuntu 20.10/Gnome 3.38.1
 ```

**Comment by JosephMcc** [comment]
It wasn't really premature. It's how scrollbars work in Gtk. When using one of the Mint-Y themes I don't see this issue. Even narrowing the sidebar keeps the eject buttons always showing.

**Comment by mcoyle1960** [comment]
So as long as Nemo is used in Mint with specific themes, it's not an issue. That's a surprisingly limited sentiment, isn't it?

**Comment by brownsr** [comment]
Not really. Just that the problem appears to be with the implementation of the theme you are using, rather than with nemo.  Would suggest you raise with the developer of whatever theme you are using. 

Regards

Simon

**Comment by Coeur-Noir** [comment]
It's a very weird way of looking at the problem.

This issue is still true today, outside of Mint and with any theme.

Might be enough to « put » the (un)mount icons / buttons a bit further from the right limit of the pane ?
Or to the left of the mount points names ?
