### ISSUE TITLE
Please, build it in flatpak 

### ISSUE THREAD

**Issue by legallyfree** [linuxmint/nemo#2639]
# Suggestion:

Please,

by the time this beautiful file manager will be on flatpak,
I use plasma and I don't want to invade my system with others libraries,

please build it in flatpak.

**Comment by ItzSwirlz** [comment]
er.. uhm.. okay?

Flatpak is something relatively new and cinnamon developers don't really use it. However it is something to consider, maybe?

Nautilus is already a flatpak and does'nt use xapp libraries, so maybe use that?

**Comment by Jeremy7701** [comment]
I have carefully managed to remove most of the flatpak crud - but a few packages have dragged bits of flatpak remnants in as "recommends".
If something is flatpacked, I don't install it.

**Comment by legallyfree** [comment]
> I have carefully managed to remove most of the flatpak crud - but a few packages have dragged bits of flatpak remnants in as "recommends".
> If something is flatpacked, I don't install it.

There are many of us who prefer flatpak today, today storage is a thing of the past, 512Gb, 1 and 2 Tb is the standard on disk in a computer today, what flatpak prevents is that they modify or add libraries that make the system heavy in its operation or end it breaking in its defect.

**Comment by leigh123linux** [comment]
> > I have carefully managed to remove most of the flatpak crud - but a few packages have dragged bits of flatpak remnants in as "recommends".
> > If something is flatpacked, I don't install it.
> 
> **There are many of us who prefer flatpak today**, today storage is a thing of the past, 512Gb, 1 and 2 Tb is the standard on disk in a computer today, what flatpak prevents is that they modify or add libraries that make the system heavy in its operation or end it breaking in its defect.

The 'many' can build then as there are only a few of us.

**Comment by legallyfree** [comment]
> > > I have carefully managed to remove most of the flatpak crud - but a few packages have dragged bits of flatpak remnants in as "recommends".
> > > If something is flatpacked, I don't install it.
> > 
> > 
> > **There are many of us who prefer flatpak today**, today storage is a thing of the past, 512Gb, 1 and 2 Tb is the standard on disk in a computer today, what flatpak prevents is that they modify or add libraries that make the system heavy in its operation or end it breaking in its defect.
> 
> The 'many' can build it then as there are only a few of us.

most of us are not devops or backend or develop on linux.
If you can't do it then let another interested person with Linux knowledge can choose to do it if they want, you don't need to sign up for the discussion.

Now the fact that some like it and others don't like flatpak is a separate discussion.

**Comment by leigh123linux** [comment]
> > > > I have carefully managed to remove most of the flatpak crud - but a few packages have dragged bits of flatpak remnants in as "recommends".
> > > > If something is flatpacked, I don't install it.
> > > 
> > > 
> > > **There are many of us who prefer flatpak today**, today storage is a thing of the past, 512Gb, 1 and 2 Tb is the standard on disk in a computer today, what flatpak prevents is that they modify or add libraries that make the system heavy in its operation or end it breaking in its defect.
> > 
> > 
> > The 'many' can build it then as there are only a few of us.
> 
> most of us are not devops or backend or develop on linux, etc etc.
> If you can't do it then let another interested person with Linux knowledge can choose to do it if they want, you don't need to sign up for the discussion.
> 
> Now the fact that some like it and others don't like flatpak is a separate discussion.

Feel free to use the source code for flatpak.

**Comment by ItzSwirlz** [comment]
I don't know why this was thrown into an argument. I'm just saying use Nautilus instead and if you really want, I'll be willing to do Nemo for Flatpak. I think it'd be great for Hypnotix.

**Comment by legallyfree** [comment]
I just gave a suggestion as part of looking at many apps built in flatpak, but it seems that some don't like flatpak, welcome to it @ItzSwirlz :+1: , I don't see nautilus in flathub. :/
If you make a post about this it would be great, I want to build xpad but looking at the flatpak manual to build is not very didactic as it seems.

**Comment by legallyfree** [comment]
I already found it @ItzSwirlz, they removed it from flathub

**Comment by Jeremy7701** [comment]
It's not easy keeping flatpaks updated - bug fixing a flatpacked thing must be horrible.

**Comment by legallyfree** [comment]
That is why it is only for people who are dedicated to Linux and manipulate the system, who know the system, it is not for everyone, to say that it is horrible would be said by a novice who does not know about it, but for a qualified person it would not be a problem. that's why I made the request.

**Comment by NikoKrause** [comment]
Hypnotix as a Flatpak sounds good to me.

@ItzSwirlz I've seen your name more often lately here on Github. I don't want to be rude, but may I ask how old you are? You don't have to tell, if you don't want to. It's just personal curiosity.

**Comment by Jeremy7701** [comment]
@legallyfree said:-
> That is why it is only for people who are dedicated to Linux and manipulate the system, who know the system, it is not for everyone, to say that it is horrible would be said by a novice who does not know about it, but for a qualified person it would not be a problem. that's why I made the request.

I find that to be a rather insulting comment. Please note that there is no "system" to manipulate and that there are no entry qualifications to Linux. 
Furthermore, this is not a chat forum - it's for raising issues - "bugs" or feature requests and where possible fixes or relevant information.

**Comment by legallyfree** [comment]
> @legallyfree said:-
> 
> > That is why it is only for people who are dedicated to Linux and manipulate the system, who know the system, it is not for everyone, to say that it is horrible would be said by a novice who does not know about it, but for a qualified person it would not be a problem. that's why I made the request.
> 
> I find that to be a rather insulting comment. Please note that there is no "system" to manipulate and that there are no entry qualifications to Linux.
> Furthermore, this is not a chat forum - it's for raising issues - "bugs" or feature requests and where possible fixes or relevant information.

And to say that "it must be horrible to support the errors that flapak generates" is not insulting, so the people who support these packages where you leave them with your comment, your comment shows that you are a newbie in development for having said that , try to be nice saying that the people who make flatpak packages must be people who work on it, I do not see the insult, that you feel discriminated against is something else. You are not qualified is different, it is not an insult.

**Comment by mtwebster** [comment]
Nautilus may still be available from another flatpak repo, I thought it was intended mostly for beta/early testing.

Flatpaks aren't too bad to maintain once you have it packaged. In fact they're less likely to break when your system does, since they are self-contained and are partitioned from the rest of the system.

Unfortunately with flatpaks, you end up dealing with a lot of limitations due to its isolation (sandboxed). For real applications, this is usually acceptable, like messaging, or some drawing or productivity app (warpinator is on flathub also). You can actually get away with a lot, but any more than absolutely necessary is frowned upon.

Nemo has a *lot* of moving parts, it does a lot of things, and there are a bunch of add-ons for it.
You would lose:
- extensions (sharing, folder colors, dropbox, etc...)
- desktop icons
- ability to browse the filesystem other than your home folder. Again I could probably tell it I want full filesystem access but that might get blocked on something like flathub.
- integration with shared system settings (automount, desktop settings, etc...)
- probably much more.

It's not worth even trying - a lot of things that make Nemo nice and useful in the first place would be lost.

**Comment by ItzSwirlz** [comment]
> @ItzSwirlz I've seen your name more often lately here on Github. I don't want to be rude, but may I ask how old you are? You don't have to tell, if you don't want to. It's just personal curiosity.

Shoot me an email, itzswirlz2020@outlook.com
