### ISSUE TITLE
Nemo segfault in libgtk-3.so.0.600.0 (Ubuntu 12.10)

### ISSUE THREAD

**Issue by rmenessec** [linuxmint/nemo#264]
Ubuntu 12.10 (quantal), amd64, libgtk-3-0 package version 3.6.0-0ubuntu3, Cinnamon environment provided by Ubuntu PPA at https://launchpad.net/~gwendal-lebihan-dev/+archive/cinnamon-stable

Nemo crashes periodically (all of it—desktop vanishes), usually leaving behind a segfault in dmesg:

[16076.108708] nemo[3437]: segfault at 2a5c81 ip 00007f9585ab8913 sp 00007ffff0fcec00 error 4 in libgtk-3.so.0.600.0[7f9585806000+4a8000]

It's done this ever since I switched from Unity, and between the upgrade from 12.04 to 12.10. I've also tried running nightly builds from the -stable PPA's provider. The nightly builds seem to have improved Nemo's draw speed (closer to Nautilus), although they haven't fixed the segfaults or the weird problem where colums in Nemo resize themselves, jumping around the screen.

I'm using the X.Org and DRM packages from Intel (01.org), although the segfaults also occur when I'm using the stock Ubuntu 12.10 packages.

It's very hard to predict when or if it'll happen. Sometimes it doesn't occur when my laptop's running for three days straight; other times it happens six times in a day. I'm not aware of any pattern in my DE or general system usage that seems linked to the segfaults.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
