### ISSUE TITLE
Please add build instructions+dependency list

### ISSUE THREAD

**Issue by Hordeking** [linuxmint/nemo#2670]
**Issue**
No build instructions present in repository. Attempts to build met with errors as each attempt to build shows *yet another* unfilled dependency. (Nemo is installed, but I don't have a lot of the dev libs required).

**Expected behaviour**
Expect to find a file in repository "BUILD.md" or similar that details basic build instructions, apt install commands to bring in dependencies, and details of what config options exist and how to set them.

**Comment by brownsr** [comment]
You might like to take a look at the mint-dev-tools repository. There are commands there that do what I think you are asking for.

Building by hand can be instructive though:

dpkg-buildpackage in the appropriate git directory.  If all the dependencies are not installed it will tell you, then install them and iterate.  Once built dpkg -i to install.  There are dependencies on other related repositories like cjs where you have to install them (dpkg -i) before building cinnamon. Managing broken packages and the odd dependency that does not seem to play ball, can be a pain sometimes, you will see messages suggesting you need to run the fix broken install option, just do what it says, but use apt-get not apt.

Regards

Simon

**Comment by Hordeking** [comment]
I will try these, but it still might be nice to put this into a short document that comes with the git repo. Especially for us who aren't very familiar with Meson (it seems to have become suddenly _very_ popular lately). In particular for those of us who are just trying to build the current repo to see if a bug is present in that, and maybe see if they can figure out where the bug was introduced (Unable to copy files from USB device using MTP protocol). I was really hoping for a quick build, check it, bump back a version, build it, check it, until I don't see the bug anymore.

**Comment by freder** [comment]
was also looking for build instructions:

```
meson setup build_dir
cd build_dir
ninja
```

that seems to do it.
