### ISSUE TITLE
[BUG] Cannot enter FTP after unmounting and remounting again (The location is not a folder)

### ISSUE THREAD

**Issue by mochidaz** [linuxmint/nemo#2675]
```
 * Nemo version: 4.8.4
 * Issue with desktop nemo
 * Arch
 * Nvidia 840m, 460.39
 * 64 bit
 ```

**Issue**
So when i connect my laptop to my phone through FTP, unmounting it, and then remounting again (reconnecting), i oftenly get this error: "Could not display "ftp://user@192.168.1.x:2121/" The location is not a folder". I cant do anything except restarting my laptop to get it work again.

**Steps to reproduce**
Connect to an FTP server, unmount it, reconnect.

**Expected behaviour**
Pop up error: "Could not display "ftp://user@192.168.1.x:2121/" The location is not a folder"

**Comment by leigh123linux** [comment]
Closed #2410
