### ISSUE TITLE
Feature Request: Rename files by two mouse clicks

### ISSUE THREAD

**Issue by KuJo-Ger** [linuxmint/nemo#2676]
I'm currently running Linux Mint 20 Cinnamon Edition with nemo 4.6.5

I am a former Windows user and have been using Linux Mint in the Cinnamon edition since my switch in 2017. Since my switch, however, I've been missing one, admittedly small, but nevertheless beloved comfort feature. It is about the renaming of file names.

On Windows, you can rename a file you want to rename with two single mouse clicks. It works like this:
- First select the file in the Explorer with a left mouse click.
- A little bit delayed you click again with the left mouse button on the file. This brings you into the edit mode and the file name is highlighted up to the extension abbreviation.
- With the keyboard you can enter a new file name for the highlighted area and confirm with Enter.
- Done.

It would really be a simplification that has become second nature to me in the many Windows years and that I still miss after almost 4 years of Linux use.

**Comment by NikoKrause** [comment]
![screenshot-window-2021-02-23-121140](https://user-images.githubusercontent.com/8415124/108835954-83370300-75d0-11eb-8ad6-afc1514073b4.png)

**Comment by KuJo-Ger** [comment]
OMG! The function was there all the time ... 

Thank you for this tip.

**Comment by Atalanttore** [comment]
> You should have asked earlier. This feature has been renamed in October 2016, so it's probably there even longer.
> [b8f5cb8](https://github.com/linuxmint/nemo/commit/b8f5cb8c233573a207a588f1aa4308156ad7b190)

The fact that the option is located in the middle of other options does not make it particularly easy to find for normal users.
