### ISSUE TITLE
NEMO won't start

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2681]
```
 * Nemo version (4.8.5)
 * Is issue with desktop or windowed nemo - BOTH
 * Distribution - (LMDE4)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
After recent update to 4.8.5 from 4.8.4

Nemo doesn't start.
Trying to start via command line produces:-
`nemo`
`Initializing nemo-image-converter extension`
`[Nemo Terminal] I: Initializing the Nemo extension`
`free(): invalid pointer`
`Aborted (core dumped)`

**Removing the nemo-terminal package appeared to restore normal behaviour.**

**Steps to reproduce**

See above

**Expected behaviour**

**Other information**
No unusual changes/development made to python etc.

**Comment by mtwebster** [comment]
Does this happen with no extensions enabled?

Is there crash info in Mint Report?

**Comment by Jeremy7701** [comment]
Haven't tried it without extensions and I have a big crash info - but no debug symbols, so I assume it is a bit useless!

**Comment by mtwebster** [comment]
7eaed06b22aea64150a408da460e6d1f132086c7

I'll try and get a new version of nemo-python asap.

**Comment by Jeremy7701** [comment]
Disabling all extensions and reinstalling `nemo-terminal` allows the desktop icons etc to function, but windowed (file-manager) still gives a core dump [120MB+ ]

**Comment by Robotvasya** [comment]
same problem version nemo 4.8.5+ulyssa
after apt  purge  nemo-terminal, nemo starts

**Comment by mtwebster** [comment]
nemo-python 4.8.2 is released, which should fix this. If you're using a mirror for "Main" repos you may have to wait a bit.
