### ISSUE TITLE
Nemo Not Permanently Keeping Login Credentials for SMB Login

### ISSUE THREAD

**Issue by mbluett88** [linuxmint/nemo#2684]
I am running Mint 20.1 with Cinnamon 4.8.6 kernel 5.4.0-66-generic on an HP Omen laptop 15-ek0012la.

Without fail when I select "Remember forever" on SMB logins it does not store the credentials permanently. I am forced to re-enter my SMB credentials on each system startup.

Mint 19.3 behaved the same way.

**Comment by OzzieIsaacs** [comment]
I think this is a duplicate of #2640. 
According to my experience you can just bypass entering the credentials by pressing ESC, or entering the keyring password first in another program.

**Comment by icarter09** [comment]
Closing as the ticket is a duplicate
