### ISSUE TITLE
potential memory leak or lack of option for quitting

### ISSUE THREAD

**Issue by sidmint** [linuxmint/nemo#2688]
```
 * Nemo version 4.4.3
 * issue with windowed nemo
 * Distribution - Mint 19.3 xfce
 * Graphics hardware *and* driver used- Latitude E5440, 5.4.0-54-generic, i5-4310U, Intel HD Graphics 4400
 * 64 bit
 ```

**Issue**

I'm monitoring the processes via gnome-system-monitor. I open pcmanfm or thunar and close it, the process for it opens and closes. I do the same with nemo, the process opens but doesn't close back down and stays in the ram. Even by using ctrl+q. Feels like a memory leak, or at least I should have an option for proper fully quittng to keep my ram low.

**Steps to reproduce**

open nemo and close it.

**Expected behaviour**

The related process must be closed too.

**Comment by Jeremy7701** [comment]
Try `nemo -q` to quit.
Unused RAM is wasted RAM!   ;)

**Comment by mtwebster** [comment]
This is (was) deliberate - nemo persists 30s after you close its last window.

I've been meaning to get rid of it, thanks for the reminder.

https://github.com/linuxmint/nemo/commit/94d613bc98e3ac035489d7dc09ba84b23be0972e
