### ISSUE TITLE
Font bug with nemo

### ISSUE THREAD

**Issue by iceman42** [linuxmint/nemo#2691]
```
 * Nemo version: 4.8.5
 * Desktop
 * Distribution - (ArcoLinux D (lts kernel: 5.11.4-arch1-1) with Cinnamon DE (cinnamon version 4.8.6))
 * Graphics hardware: AMD RX 550 4gb, Driver amdgpu, ati
 * 64 bit
 ```

**Issue**
Got something weird happening with my fonts in nemo. Some of the images for special characters don't load / are not present, and are just shown by question mark in box instead. See image below, where the 'previous', 'next' and 'up' arrows are affected. Also affected is the 'eject' button for mounted drives.

![arco_cinnamon_menu](https://user-images.githubusercontent.com/73859169/110391691-c9c03f00-805f-11eb-9ec6-63a724e3ffe8.png)

**Steps to reproduce**

**Expected behaviour**
The above buttons should be represented by the proper characters

**Other information**
System tray is also affected (removable drives - see image below) as are other cinnamon menus like those for applets, desklets etc.

![arco_cinnamon_panel](https://user-images.githubusercontent.com/73859169/110391694-ca58d580-805f-11eb-9a04-9d8e69985c5c.png)

**Comment by mtwebster** [comment]
When did this begin, after an update or ..?

What icon and gtk themes are you using? Try different ones.

run:
```
ps -A | grep csd
```
and paste the result.

**Comment by iceman42** [comment]
This is a fresh build. Installed on Friday. Has been ever-present.
I'm using Surfn-Mint-Y-Pink as an icon theme, also get the same behaviour for other surfn variants, sardi variants and paper. Adiwaita, Arc, hicolor and high contrast work though.

I'm using the arc-dark-pink gtk theme, changing the theme doesn't affect it (other than this I've only got the standard arc ones and cinnamon).

Uninstalled the surfn themes and the sardi ones started working. Uninstalled paper, then reinstalled surfn and now it works! Thanks for your reply, you pushed me in the right direction, as I thought it was a font problem rather than an icon one.

Here's the output of the command in case you still want it:

```
1916 ?        00:00:00 csd-power
   1917 ?        00:00:00 csd-xrandr
   1918 ?        00:00:00 csd-screensaver
   1920 ?        00:00:00 csd-sound
   1921 ?        00:00:00 csd-color
   1922 ?        00:00:01 csd-background
   1923 ?        00:00:00 csd-housekeepin
   1925 ?        00:00:00 csd-a11y-settin
   1926 ?        00:00:00 csd-print-notif
   1928 ?        00:00:00 csd-automount
   1930 ?        00:00:00 csd-wacom
   1935 ?        00:00:00 csd-media-keys
   1939 ?        00:00:00 csd-cursor
   1940 ?        00:00:00 csd-xsettings
   1941 ?        00:00:00 csd-clipboard
   1944 ?        00:00:00 csd-mouse
   1947 ?        00:00:00 csd-orientation
   1951 ?        00:00:00 csd-a11y-keyboa
   1954 ?        00:00:00 csd-keyboard
   2010 ?        00:00:00 csd-printer
```
