### ISSUE TITLE
[REQUEST] Let Nemo show its real name, to reduce user confusion

### ISSUE THREAD

**Issue by RedBearAK** [linuxmint/nemo#2694]
Please consider letting Nemo show its real name to the user. This would not only help avoid the user being really confused by the identically named "Files" (Nautilus) and the similarly named "File Browser" (Caja, the MATE fork of Nautilus), but it would make it easier for inexperienced users of any distro that has a Cinnamon variant to ask for help with the application. When there are multiple applications with the exact same generic name, how does anyone in a forum know which actual application the user is asking about? 

I understand that Nemo is a fork of Nautilus, that Nautilus is a GNOME application, and that it's part of the GNOME HIG to use simple application names. But I believe GNOME takes this much too far and even tries to hide the real name of the underlying application in the About dialog. (This has actually caused me some difficulty when I needed to know the actual binary name in order to do a specific thing with another GNOME application.)

Nemo, however, is a fork. And since the original GNOME application still exists and can be installed on the same system, this leads to conflict and user confusion due to both applications trying to use the overly generic name of "Files". I don't think this really benefits anyone, including new Linux and/or Mint users. 

Nemo at least shows what it is in the About dialog. But I would like to ask the devs to consider renaming Nemo more openly so that the user can immediately know both which specific application it is and what it does. 

This works perfectly fine for other file managers like "Thunar File Manager". Would it be so bad if, instead of "Files", Nemo was "Nemo File Manager", or "Nemo File Browser"? 

Look at what I see in the Preferred Applications list for default File Manager alternatives: 

![preferred_apps_confusion](https://user-images.githubusercontent.com/64876997/110441184-f0817400-8065-11eb-85b1-ddef1b71e1cf.png)

If I hadn't figured it out already by experimenting, I would have no way of knowing which of those "Files" apps was the one I wanted to pick. It's very lucky they happen to have different icons in my current icon theme, which is not the case with the two applications that call themselves "Archive Manager". That situation is even worse. 

As long as "file" appears somewhere in the name, it should be easy for the user to find in any menu or launcher, and easy for the user to understand what it does. And understandable names are very important, I absolutely agree with that concept. But I think that choosing to re-use the too-generic name of "Files", that is already (and probably always will be) in use by the GNOME application that Nemo came from, is doing a real disservice to the end users of Mint and any other platform that has Cinnamon desktop as a DE option. 

Oh, and to make matters worse, the full descriptions given for both Nautilus and Nemo are also completely identical. Thus adding to user confusion. The only way I know that the blue one in the screenshot below is Nautilus now is because I opened both of them and the brown one was honest about its real name in the About box. So by process of elimination the blue one is Nautilus. But only on this machine, with this icon scheme. If I change the icon theme, they could both end up with identical icons. 

![files_description_ulauncher](https://user-images.githubusercontent.com/64876997/110617477-3ad82300-8142-11eb-9c74-611de288f4fd.png)

**Comment by thom-10** [comment]
100% agree

**Comment by cassepipe** [comment]
Or maybe keep "Files" but display in gray italic the name of the program the same "Leave your comment" is written in the text box I am typing right now before I type anything.

**Comment by RedBearAK** [comment]
@cassepipe 

> Or maybe keep "Files" but display in gray italic the name of the program the same "Leave your comment" is written in the text box I am typing right now before I type anything.
This way when you change the default app, the text on the side changes ?

The Cinnamon Menu applet already has a smarter way of presenting application names. It does this by artificially grafting on the name of the actual "package" behind the application name, in parentheses. But outside of the Cinnamon Menu applet, this doesn't help the user avoid confusion when they see the application name in any other type of app launcher or dock like Plank Dock, or the Alt+Tab switcher (icon mode). It's the actual, official name of the application that needs to change, so that every app launcher and dock will display the same thing, even if you aren't using the Cinnamon desktop. I have seen other distros with different DEs that use Nemo as the default file manager. But for a long time that was not clear to me because it is usually just called "Files", exactly the same as Nautilus, and almost identical to the MATE fork of Nautilus, "Caja", which calls itself "File Browser". 

![cinnamon_menu_archive_manager](https://user-images.githubusercontent.com/64876997/112225306-67c81380-8be1-11eb-83a3-da0a9906e7cf.png)
Cinnamon Menu showing two "Archive Manager" applications. 

![cinnamon_menu_files](https://user-images.githubusercontent.com/64876997/112225309-6991d700-8be1-11eb-82ee-22296f1e1e4e.png)
Cinnamon Menu showing two "Files" applications. 

I'm not disapproving of the idea that Linux applications should have names that are easily understood by new users. I'm just pointing out that most (desktop) Linux software is not nearly isolated enough into its own ecosystem to get away with **overly** generic naming without causing user confusion. 

If it's called "Nemo File Manager" or "Nemo File Browser" it will still immediately appear in any launcher or searchable menu applet when typing in "file", and every new user will immediately understand what it is meant to do. But it will no longer be possible to have two icons on a Plank dock that both just call themselves "Files". And it will cause far less confusion for new Linux users that are trying out different DEs and distros to see what they like.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
