### ISSUE TITLE
'nemo' as root can't Trash items in /home partition.

### ISSUE THREAD

**Issue by glesialo** [linuxmint/nemo#2696]
```
Nemo version: 4.8.6.
Distribution: Cinnamon Mint 20.1 64 bit.
Graphics card: GForce_GTX_970, Nvidia driver: 460.

I have just installed Cinnamon 20.1 (was using 19.3 before) and I have found that,
when I use 'nemo' as 'root', I can't 'Trash' items in the '/home' partition: 'nemo' tells
me that I can only delete them immediately.

I can use Trash all right in another partition, mounted in '/home/common/Store'.

I installed Cinnamon 20.1 in an external HD (to test & troubleshoot it) and then
transferred it to my internal HD. When I noticed the mentioned issue, I booted on
the external HD's again and noticed that, although I have the same problem there,
if I mount the internal drive's 'home' partition on '/mnt' I can 'Trash' that partition's
items all right.

Some system info:

    df -h
    Filesystem      Size  Used Avail Use% Mounted on
    udev            7.8G     0  7.8G   0% /dev
    tmpfs           1.6G  2.3M  1.6G   1% /run
    /dev/sda3        19G   13G  5.7G  68% /
    tmpfs           7.8G  932K  7.8G   1% /dev/shm
    tmpfs           5.0M  4.0K  5.0M   1% /run/lock
    tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
    /dev/sda1       509M  7.9M  502M   2% /boot/efi
    /dev/sda4        19G   12G  6.2G  66% /home
    /dev/sda5       3.6T  3.1T  463G  88% /home/common/Store
    tmpfs           1.6G   44K  1.6G   1% /run/user/1000
    
    ls -ld /home
    drwxr-xr-x 6 root root 4096 Mar 12 11:48 /home
    
    mount
    /dev/sda4 on /home type ext4 (rw,relatime)

There is another change of behaviour I have noticed in this version of 'nemo': Previously
if I copied, with 'nemo' running as 'root', a file from one of my $HOME directories to a
directory owned by 'root' the owner of the copy was 'root'. Now the owner is still me.

**Comment by Jeremy7701** [comment]
I can confirm this happens for me - in LMDE4
Furthermore, if I try to open the Trash bookmark whilst in 'open as root' mode, I get

![Screenshot from 2021-03-14 00-49-04](https://user-images.githubusercontent.com/52585119/111053888-a2061800-845f-11eb-9395-a4fe85545650.png)

**Comment by mtwebster** [comment]
Trash isn't supported under root - the trash 'backend' isn't available there. Also, root's home is /root, not /home/wherever, so nemo preferences may be different also, and the trash folder is in `~/.local/share/Trash`.

We should prevent trash from appearing to be available under root.

I can't speak to any of the other behavior for the OP, but I will leave a few general recommendations:
- Don't use root any more than you have to. This means nemo also.
- Nothing in your home folder should ever be owned by anything other than your username unless you deliberately made it so.
- If you need to edit system files, try to avoid using gui programs, this can cause permission issues in your home folder.

**Comment by glesialo** [comment]
@mtwebster

>We should prevent trash from appearing to be available under root.

So disabled Trash is a feature? I think it is a regression.
Having a Trash option is a safety net that now has disappeared.

People who know what they are doing need to run some Gui applications
as 'root' and 'nemo' provides that option by right clicking on a
directory and selecting 'Open as root'.

In my system there are many resources, owned by 'root' and available
to all users, in the '/home partition'. Now I can't make any mistakes
handling them. :-(

'nemo' preferences as normal user and as 'root' are the same.

**Comment by Jeremy7701** [comment]
> We should prevent trash from appearing to be available under root.

+1

**Comment by mtwebster** [comment]
> 'nemo' preferences as normal user and as 'root' are the same.

Definitely not - running it as root is dangerous by its very nature, that's why we make sure you know about it when you do. Even if you could 'trash' things, it would be *just as dangerous* and easy to break your system completely.

If you're doing certain tasks repeatedly and need this capability, consider leveraging permissions and user groups to make this a bit simpler (and to keep from having to run things as root).

**Comment by glesialo** [comment]
@mtwebster

>'nemo' preferences as normal user and as 'root' are the same.

What I meant is that I checked the settings and they are the same.

I know what I am doing (I have been doing it for many years). It doesn't
have any logic to make something 'dangerous' even more dangerous by
removing a safety net that has always been there.

I just want to know if this is done on purpose or if it is a bug.

Why disable 'Trash' in the 'home' partition and not in any other?
Is there a place in the source code where they selectively choose
to block the 'Trash' feature for a '/home' mount point?

Are you one of the 'nemo' developers or just somebody who chose
to give unasked advice?

**Comment by NikoKrause** [comment]
@mtwebster is THE nemo developer. You can say he is Captain Nemo himself. See https://github.com/linuxmint/nemo/commits/master

**Comment by mtwebster** [comment]
Sorry I was trying to be helpful. Trash is just a uri 'trash:///' that is provided by gvfs (https://gitlab.gnome.org/GNOME/gvfs).

When you trash something locally it gets moved to ~/.local/share/Trash. If you trash something on a different filesystem as .Trash folder gets created and the file is moved there. All of the files in these locations get aggregated into trash:///.

I think I understand the technical reasons why trash (or other special locations like recent:///) is unavailable - these are dbus services that run for the 'session' (read: user) and the root user doesn't have access to this session bus. Maybe you can get a better explanation from the gnome developers.

Regardless, there's nothing I can do to fix this as far as I know, and even if I could I'm not sure I would enable it, as I don't want to encourage using nemo as root (or anything else except when absolutely necessary).

Good luck.

**Comment by glesialo** [comment]
Then, why can I use, running as 'root', Trash in a different partition?

The same instance of 'nemo' refuses to trash items in '/home' but
trashes them without problems in '/home/common/Store', creating
'/home/common/Store/.Trash-0'. The 'dbus' service is the same.

**Comment by mtwebster** [comment]
You're right, I don't know. Maybe you can ask the gnome developers.  The trash location still doesn't work, though you can retrieve the files from the .Trash folder directly.

**Comment by glesialo** [comment]
Thanks. Could you, please, confirm that 'nemo' behaves the same in  your system?

**Comment by mtwebster** [comment]
Yes - like I said, I'm not sure why that works.

**Comment by glesialo** [comment]
Thanks again.
