### ISSUE TITLE
CTRL + Tab key not work when move to other tab

### ISSUE THREAD

**Issue by muhazmi** [linuxmint/nemo#2701]
```
 * Nemo version (nemo --4.8.6)
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 20.1)
 * Graphics hardware *and* driver used: nvidia-driver-460
 * 32 or 64 bit: 64bit
 ```

**Issue**
Can't switch to another tab with CTRL + Tab (Right Tab) or CTRL + SHIFT (Left Tab) + Tab key combination

**Expected behaviour**
It's work normally in the previous version

**Comment by icarter09** [comment]
Nemo v4.8.5
Mint 20.1 64bit

I'm not able to duplicate this issue. `Ctrl + Tab` switches between the tabs for me.
