### ISSUE TITLE
Feature request : Iterate through file by pressing the same letter

### ISSUE THREAD

**Issue by cassepipe** [linuxmint/nemo#2704]
There is a feature of Windows 7 IIRC where when you press the same letter twice, it will iterate through
files that start by that letter, it *very* convenient and intuitive. 
It is way faster to iterate through files that start with some letter than
try to think about what the other letters are and type them on your keyboard.

On the other hand to be able to search for file by just pressing the first letter of that file is also very convenient (and it was implemented poorly on Windows).

My proposition is the following :
If the second letter typed is the same, iterate alphabetically through files that start with that letter.
Else if the second letter is different, launch quick search as is currently the case.

The situation where you have a file that starts with two same letters seems very rare and if there aren't much files in the folder, 
the file will be quickly access by pressing the key repeatedly. If you are in the very hypothetic situation where you have a lot of files and must get to a file that start with two same letters, you can always use Ctrl + F.

What do you think ?

**Comment by AlexFolland** [comment]
I've done some testing in Windows 7's Windows Explorer just now.  The behavior of this is timing-based, which makes it unpredictable and not desirable.

For example, if you have this file list with this selection:

efghi <-- selected
HHello
Hello.dll
Hello.exe

Then you type "h", this is the new situation:

efghi
HHello <-- selected
Hello.dll
Hello.exe

Then you type "h" again quickly (within 1 second), this is the new situation:

efghi
HHello
Hello.dll <-- selected
Hello.exe

Then you type "e" quickly (within 1 second), this is the new situation:

efghi
HHello <-- selected
Hello.dll
Hello.exe

Here's where it diverges based on time.

At this point, if you type "h" again quickly (within 1 second), this is the new situation:

efghi
HHello <-- selected
Hello.dll
Hello.exe

However, if instead you wait more than 1 second to type "h", this is the new situation:

efghi
HHello
Hello.dll <-- selected
Hello.exe

From there, if you wait to type "e", you'll get "efghi", but if you type "e" within 1 second, you'll get no movement, then if you type "h" again, you'll get "Hello.exe", and so on.  It's frustratingly time-sensitive.

I'm all for a feature like this as long as it's consistent and doesn't change behavior based on how quickly you typed letters.

**Comment by cassepipe** [comment]
Oh sorry I did not mean to imply that Windows 7 behavior was better : It's a mess and I thought I had mentioned it in my first post. Timing based search behavior is awful and current Mint behavior is way better.

My proposal is to keep Mint's behavior but with a caveat for iterating through files that start with the same letter.

**Comment by Jeremy7701** [comment]
For example, if you have "this file list (including folders)..." and you've chosen to display it in `date created` order it's not going to behave in a sensible way, is it?

Why not just search for files named 'hel*' (or whatever).

**Comment by cassepipe** [comment]
If you've chosen to display files according to date creation you are trying to search for a file created at a specific date, this is a different use case. 
Where I think my use case is sensible is to quicky get to file by only pressing one key repeatedly not having to think about what the filename really was

**Comment by AlexFolland** [comment]
It's annoying in Windows because it's time-based, as I described in my previous comment.  How do you propose to handle it differently so that it's not time-based and also does not prevent navigating to files with consecutive starting letters in the same folder as files with the same starting letter?

**Comment by cassepipe** [comment]
My proposition is to detect is to keep the actual behaviour unless the second letter is the same.
If  the second letter happens to be the same, just iterate through files that start with that letter.
You see my proposition is not time base.
Occurences where a file starts with the same letter are probably very rare and I don't think it will ever be annoying.

**Comment by Jeremy7701** [comment]
Why not use the CTRL+R history search feature of the CLI, repurposed as a file-only search feature?
I wouldn't use it unless my mouse was broken, but some people might like it.

BTW I have directories where every filename starts with 2020, 2021 etc

**Comment by cassepipe** [comment]
Okay, now that I think of it, it seems to me that the annoying part in the current behaviour is that I lose selection when I make a typo using the quick search. But at least it is consistent which is probably important too.
Glad I could discuss with you all, I don't think it is worth to make a case any further for this idea, so I'll close this.

I *do* have other suggestions which I think are more important, and which I would really love for them to see the light of day.
Such as :
[Tab iteration in menu entries](https://github.com/linuxmint/cinnamon/issues/10042)
[Do not show program results in menu when a path is entered](https://github.com/linuxmint/cinnamon/issues/10330)
[Allow tab completion in the menu form the first \](https://github.com/linuxmint/cinnamon/issues/10331)
