### ISSUE TITLE
Desktop icons go up one grid every reboot

### ISSUE THREAD

**Issue by aprilthecutie** [linuxmint/nemo#2706]
```
 * Cinnamon 4.8.6
 * Distribution - Arch
 * geforce gtx 1060 | nvidia 460.56
 * 64 bit
 * I have no ~/.xsession-errors or /var/log/syslog
 ```

**Issue**

The icons on my desktop are going up one grid space after every reboot

**Steps to reproduce**

1) move icon somewhere where it isn't right at the top
2) reboot
3) it is now one higher

**Expected behavior**

Icons should stay where you put them

**Comment by leigh123linux** [comment]
This issue doesn't reproduce here on fedora.

**Comment by aprilthecutie** [comment]
it's also occurring on Debian 10.

**Comment by aprilthecutie** [comment]
![image](https://user-images.githubusercontent.com/79120883/112249059-7a683a00-8c2d-11eb-99e2-79a22041a1c8.png)

It appears to only be happening to desktop icons such as Home, Computer, and Trash.

**Comment by leigh123linux** [comment]
It doesn't reproduce on the latest Mint.
Perhaps it's an issue with whatever desktop icon setting you have chosen to use.
You posted no logs or useful info so far.

**Comment by Jeremy7701** [comment]
Could the OP show the window that you get by right click -> customise?
e.g.

![Screenshot from 2021-03-24 13-43-20](https://user-images.githubusercontent.com/52585119/112320491-f783c580-8ca6-11eb-93cf-327a88ce7d3f.png)

**Comment by aprilthecutie** [comment]
![Screenshot from 2021-03-24 15-55-36](https://user-images.githubusercontent.com/79120883/112375398-a6310180-8cb9-11eb-8a2f-0eb21baf8ebf.png)
here it is.
