### ISSUE TITLE
Deficient handling of charset incompatibility when copying many files

### ISSUE THREAD

**Issue by eyalroz** [linuxmint/nemo#2709]
* Nemo 3.8.5
* Windowed (but it doesn't matter)
* Distribution: Devuan Beowulf
* Graphics hardware: Irrelevant
* 64 bit

When I copy a file from a filesystem which supports some set of characters, to a filesystem which supports a different set, and the filename has characters in the difference of the sets - I get an error dialog, with the options to Skip, Retry, Skip All and Cancel (actually, 3 of those depending on whether it's a folder or file, I think). You can also copy the path by double-clicking or click-selecting.

This isn't so bad... for a single file. But when you're copying hundreds, thousands, tens of thousands of files - this becomes terrible, in many ways:

* While waiting for you to interact with the dialog box, Nemo does not continue copying other files.
* You get a different dialog for every single file or folder - rather than files & folders adding up within a single dialog (albeit possibly with the ability to make per-file choices).
* You can't get the entire set of charset-incompatible files & folders (or even - the set of failed-to-copy files and folders) all at once, at the end of the copy - in a single dialog, or in a log file or what-not.
* You cannot set a policy regarding character substitutions, to apply to all copied files.
* You cannot set a policy regarding character substitutions, to apply to all _source_ files (this is perhaps less important to have, but also useful if you plan on making a similar copying later on).

IMHO, all of these are necessary features/behaviors and should be implemented. If you like I can split them into separate issue pages here, or keep them here together.

PS - Some of these suggest features are relevant to any sort of copying failures.

**Comment by leigh123linux** [comment]
nemo-3.8.x is EOL, feel free to reopen if you can reproduce on a supported version.

**Comment by eyalroz** [comment]
@leigh123linux : Can you suggest which version I should use to try and reproduce, on a Devuan Beowulf distribution (~= Debian Buster with no systemd)?

**Comment by leigh123linux** [comment]
Try 4.8.x as it's the only version that has support.

**Comment by eyalroz** [comment]
@leigh123linux : With respect - I think it is unreasonable to demand people use only the latest version in order to report 'mis-feature'-type bugs. That is just an aritrary restriction. A developer can easily say: "Oh, this behavior has changed in the latest version".

And it's not that I'm too lazy to build, it's just that building the absolutely newest version requires obtaining and building lots of dependencies which I don't have.

**Comment by eyalroz** [comment]
@leigh123linux : Please reopen, have reproduced this on v4.8.6 .

**Comment by leigh123linux** [comment]
The issue can be addressed on https://github.com/linuxmint/nemo/issues/2708#issuecomment-808439762

**Comment by eyalroz** [comment]
@leigh123linux : They are two separate issues. #2708 is about correctly noticing and reporting the problem to the user and should be rather simple and straightforward to fix. This issue would require some UI/UX thought, and more coding effort, to choose one (or more) ways to tackle charset incompatibilities.
