### ISSUE TITLE
nemo exists immediately saying: Settings schema 'org.nemo.preferences.menu-config' is not installed

### ISSUE THREAD

**Issue by eyalroz** [linuxmint/nemo#2711]
I've just build nemo 4.4.2 from sources on my Devuan Beowulf system (to file other bugs, actually). My distro's nemo version is 3.8.5.

Now, when I try to run nemo, I get the message:
```
(nemo:4395): GLib-GIO-ERROR **: 23:12:29.276: Settings schema 'org.nemo.preferences.menu-config' is not installed
```
and it exists.

Either this shouldn't happen, or I should get a more verbose error message telling me what I need to do...

I should mention I have installed my distro's gsettings-desktop-schemas package.

**Edit:** This has now happened to me also with nemo 4.8.6...:
```
(nemo:2286): GLib-GIO-ERROR **: 17:15:10.928: Settings schema 'org.nemo.preferences.menu-config' is not installed
```

**Comment by mtwebster** [comment]
try:
```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```
This is handled during the install phase of the meson build, I'm not sure why that didn't happen here. Debian builds do it automatically post-install.

**Comment by eyalroz** [comment]
@mtwebster : I actually did not install, trying to run it from the build dir.

The reason is that auto-build failed, and I had to sort of push it to completion... I'm using a custom-build xapp 1.4.9 (my system has 1.2.2); and I point PKG_CONFIG_PATH at the path of its `.pc` file. meson accepted this, but ninja fails to locate some include files. So I just copied them somewhere accessible. But then, ninja failed to link against my libxapp - and its linking command-line doesn't have a -L, so I manually performed the link :-(

When I try ninja/install, it insists on trying to perform the link again itself, which fails.

**Comment by eyalroz** [comment]
Also, your suggestion didn't work, I get the same error message...

**Comment by eyalroz** [comment]
@mtwebster : Update for you... Have now rebuilt nemo 4.8.6 fully with ninja, and have now tried to run the installed executable, from the installation dir. got some message again.

**Comment by mtwebster** [comment]
So you're not actually installing it onto your system? Why not? I'm not sure you're going to be successful with this - there are a lot of shared libraries being used, and some of them will only look in system locations - if you absolutely can't install it, use a virtual machine.

You can try copying your org.nemo.gschema.xml.in to /usr/share/glib-2.0/schemas/org.nemo.gschema.xml and running that compile command but I have no idea if that will solve all of your issues - this isn't something we support or plan on supporting.

**Comment by eyalroz** [comment]
@mtwebster : I'm not installing it on my system since I don't want to destabilize my distribution. I'm running a nicely integrated distribution, none of which I built myself, and a few choice pieces of other software in /opt ... I'm only building nemo because I need to file _another_ bug and people close your bugs if you don't file them against a very recent version.

**Comment by eyalroz** [comment]
Resolved where relevant environment variables (`LD_LIBRARY_PATH`, `XDG_DATA_DIRS`) are set appropriately; see #2714 .
