### ISSUE TITLE
Nemo 4.8.6 won't run after successful build and install

### ISSUE THREAD

**Issue by eyalroz** [linuxmint/nemo#2713]
* Nemo version: 4.8.6
* Desktop
* Distribution: Devuan GNU/Linux Beowulf
* Graphics hardware: On-board Intel i915
* 64 bit

I've built Nemo from sources on my Devuan Beowulf machine - after having also downloaded and built xapp-2.0.7 and cinnamon-desktop-4.8.1.

I built and installed nemo like so:
```
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/opt/cinnamon-desktop-4.8.1/usr/local/lib/x86_64-linux-gnu/pkgconfig/:/opt/xapp-2.0.7/usr/local/lib/x86_64-linux-gnu/pkgconfig"
meson setup build
cd build
ninja
DESTDIR=/opt/nemo-4.8.6 ninja install
```
But then, when I try running it, I get:
```
$ /opt/nemo-4.8.6/usr/local/bin/nemo
/opt/nemo-4.8.6/usr/local/bin/nemo: symbol lookup error: /opt/nemo-4.8.6/usr/local/bin/nemo: undefined symbol: xapp_favorite_info_free
```

PS - I'm only building from sources to reporting two other, unrelated issues...

**Comment by mtwebster** [comment]
Add `--prefix=/opt/nemo-4.8.6` to the meson command, try rebuilding xapps with that, installing it, then building nemo as well, installing it. (Don't use DESTDIR)

Then try:
```
LD_LIBRARY_PATH=/opt/nemo-4.8.6/lib/x86_64-linux-gnu GSETTINGS_SCHEMA_DIR=/opt/nemo-4.8.6/share/glib-2.0/schemas /opt/nemo-4.8.6/bin/nemo
```

**Comment by eyalroz** [comment]
Ok, this worked.
