### ISSUE TITLE
Nemo executes context menu checks on hover instead of when opening context menu

### ISSUE THREAD

**Issue by AlexFolland** [linuxmint/nemo#2718]
```
 * "Nemo version (nemo --version)" `nemo 4.8.5`
 * "Is issue with desktop or windowed nemo?"  What's the difference?  It's nemo on the desktop in windowed mode.  I don't get this question.
 * Distribution - Manjaro Ornara 21.0
 * 64-bit
 ```

**Issue**

Nemo executes context menu conditional checks on hover instead of when opening context menus, which lags the entire program when just mousing over if there are any `.nemo_action`s which execute something.

**Steps to reproduce**

1. Make a custom nemo_action file that executes a program, like one with `Conditions=exec svn info "%F";` in it.
2. Open a task manager like ksysguard which lets you see programs starting and ending in realtime.
3. Make sure nemo and its child processes are visible in that task manager.
4. Hover some folders in Nemo with your mouse cursor and watch the `svn` processes open and close while hovering.

**Expected behavior**

Nemo is expected to execute context menu checks only when opening the context menu.  Otherwise, hovering a whole bunch of stuff just by trying to navigate through the file system lags everything while waiting for these checks to return.

**Other information**

This affects my [TortoiseSVN wine Nemo actions](https://github.com/AlexFolland/tortoisesvn-wine-nemo-actions) project.  My custom `.nemo_action` files work, but because they check for svn info before showing the context menu entries and this bug exists, they lag the whole program just while mousing around.

**Comment by mtwebster** [comment]
Actions (and the rest of the menu) update when the selection changes, not when hovering. Do you have something that is causing a selection change on hover?

They can also update when items in the current view are modified in some way - are these items being continually modified? (Not their contents if they're folders, just the immediate children of the current location). I'll have a look at this.

**Comment by mtwebster** [comment]
Btw, your question about the desktop/windowed - nemo manages the desktop.  It's a different binary, it does a lot of things differently. This is why that question is asked.

**Comment by AlexFolland** [comment]
I noticed this especially when viewing a folder with huuuuuge video files on my local drive (lossless video recorded with OBS using ffmpeg).  I also noticed it when browsing an Amazon S3 share mounted with s3fs.  Every time I hovered something, s3fs was downloading it to run `svn info` on it, which was obviously very latent, causing Nemo to lock up like crazy.  As soon as I disabled my custom actions, the problem went away.  This was all without viewing the files' context menus.

**Comment by AlexFolland** [comment]
> Actions (and the rest of the menu) update when the selection changes, not when hovering. Do you have something that is causing a selection change on hover?

As far as I know, I have nothing that does that.  I do see a highlight moving around while hovering, but I'm pretty sure that's not changing selection.

> They can also update when items in the current view are modified in some way - are these items being continually modified? (Not their contents if they're folders, just the immediate children of the current location).

As far as I know, no software I run is changing files on my local drive constantly in whatever folders I'm browsing with Nemo, but maybe it is somehow.  That seems doubtful.  I'm running Manjaro XFCE without any deep tweaking, with mostly default configuration, which is pretty sane like Arch with a few Manjaro-specific tweaks and later package distribution, as far as I can tell.

**Comment by AlexFolland** [comment]
When browsing an Amazon S3 bucket mounted with `s3fs`, I noticed Nemo queuing up many svn info calls, including multiple on the same file, and continuing to run new ones long after I stopped sending Nemo input.  This was all without showing the right-click context menu once.  As a temporary workaround, I disabled the conditions in my `.nemo_action` files and everything became more responsive.

These actions are in the context menu, so executing the conditions before the context menu is requested would be incorrect behavior as well.  I'm not sure any more if I'm seeing the conditions executed on hover.  Maybe it only seemed like it because it queued them up and executed many after browsing to various folders and clicking around.

**Comment by AlexFolland** [comment]
Thanks for that change!  I will test it by updating to the latest nemo git version and enabling the conditions in my nemo_actions again.

**Comment by AlexFolland** [comment]
The fix worked here.  I can browse folders with huge files in them without waiting for the context menu entries' conditions to execute.  Thanks!  I'm closing this as a result.

**Comment by AlexFolland** [comment]
I've found that this fix introduced a regression.  Now, until I view a file or directory's context menu, I can't rename it with the F2 key or trash it with the Delete key.  Both keys are unresponsive.  The workaround is to view the context menu.

My expected behavior is to still be able to rename or delete with keybinds.

Thank you so much for working on this.

**Comment by mtwebster** [comment]
I'll need to revert this.  I'm going to try just delaying extensions and  actions until the popup menu is activated - these won't be tied to shortcuts.

Shortcuts are directly tied to menu items, and are enabled/disabled in sync with the state of these menu items, so we need to have these handled immediately when the selection changes.

**Comment by mtwebster** [comment]
I made another attempt for this, let me know if it helps (https://github.com/linuxmint/nemo/commit/5a271cd539ef2e545e283c42914edbc02bfc5340)

**Comment by AlexFolland** [comment]
Thanks.  I'm testing it today.

**Comment by AlexFolland** [comment]
It seems to be working beautifully now here.  Thanks!  I'm closing this as a result.
