### ISSUE TITLE
mass rename does not work on network shares

### ISSUE THREAD

**Issue by drtebi** [linuxmint/nemo#272]
Hello,

I have configured nemo to use ThunarBulkRename through a dconf entry:
b'/usr/lib/Thunar/ThunarBulkRename'

... and this works just perfect for local files. However, when trying to do the same thing (select several files, right-click and choose "Rename..."), nothing happens.

I am happy to provide more details if necessary (just let me know how).

Thanks,
DrTebi

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is not related to Nemo. It seems it's more related to Thunar Bulk Rename feature. Can we close it?

**Comment by drtebi** [comment]
I believe I can be closed. This issue seems to have been fixed a long time ago, renaming works just fine on local or network-mounted shares.
Thanks...

**Comment by testman42** [comment]
renaming or multiple renaming?
I have Nemo 3.0.6 (latest stable version) open right now and when selecting multiple files and opening context menu, the "Rename..." entry gets greyed out.
I am not sure what component is responsible for this functionality, but effect remains: Nemo can not rename multiple files.

**Comment by drtebi** [comment]
This issue was about the integration of Nemo and "ThunarBulkRename". With that, the renaming of multiple files is possible.
