### ISSUE TITLE
Feature request : adding telnet protocol

### ISSUE THREAD

**Issue by enigma131** [linuxmint/nemo#2722]
Is it possible to add Telnet protocol in submenu : File, Connecting to server ? (I see SSH protocol but not Telnet)

**Comment by leigh123linux** [comment]
Try filing the request against **gvfs** as that's the framework that provides the network protocols used by nemo

**Comment by enigma131** [comment]
Heu cans you give me an example ?

**Comment by leigh123linux** [comment]
https://gitlab.gnome.org/GNOME/gvfs/-/issues

**Comment by enigma131** [comment]
Ok. I had perhaps wrong asked. What I was asked for, is to have a line telnet in type for this menu:
![connect](https://user-images.githubusercontent.com/31815445/113891827-bb338780-97c5-11eb-999b-3f696e9e04b1.png)
