### ISSUE TITLE
Rename on list mode BUG

### ISSUE THREAD

**Issue by Dasdar990** [linuxmint/nemo#2726]
```
 * Nemo v 4.8.6
 * Windowed Nemo
 * Linux Mint 20.1 (Ulyssa)
 * Nvidia GeForce 1050Ti, nvidia-driver-460
 * 64 bit
 ```

**Issue**
When I press F2 key to rename a file (SHOWED IN LIST VIEW) the text of the previous name does not disappear and I write the new name above the old one. When I confirm by pressing ENTER the old text disappear and the new one shows up as expected

**Steps to reproduce**
Try to rename a file when you are using List View. 

**Expected behaviour**
When you press F2 to rename the text should disappear and then you can write the new one

**Other information**
I tried to take a screenshot but when I try the rename action is aborted .

**Comment by brownsr** [comment]
Thank you for your comment.  When I press F2 in list mode to reproduce this, an editing window is opened with the existing name highlighted.  Starting to type makes the existing name disappear, and pressing enter completes the action.  That seems like normal, intended behaviour.

Regards

Simon

**Comment by Dasdar990** [comment]
I have this issue and I can prove it. I try to make a small video
