### ISSUE TITLE
[Feature Request] Need upload dialog to show full features of Pictures folder not just titles and preview Mint 20.1 64 bit Cinnamon

### ISSUE THREAD

**Issue by jjones1911** [linuxmint/nemo#2738]
I would like to see my Pictures folder as it is from my desktop NOT a view that just gives picture titles and small previews when I try to upload a picture in Mail, Facebook etc.

I believe it does this in XFCE but I use Cinnamon.

Thank you in anticipation
```

John Jones



```

**Comment by Jeremy7701** [comment]
Didn't really understand the original bug report - **but**
If (for example) you try to send a picture attachment on an email, what should happen is that you see a large icon when selecting the file to attach.
This appears to work - **but only if the picture size doesn't exceed 4MBytes** [it works for a 3.5MB or smaller jpeg].
This is not due to my nemo setting of maximum file size to iconise, as I have that set at 8GB.

**Comment by jjones1911** [comment]
Thank you guys for your quick response.  Let me explain in more detail as It is not a bug report.
If I view my pictures from the desktop via the home menu, I have the pictures folder set to show folder icons and picture thumbnails.  Each folder shows the picture icons as thumbnails. That is how I like to see my pics.

Ok, lets say I am on FACEBOOK or in THUNDERBIRD and I want to upload a picture to the post I create or the email I am writing, the file manager opens but not the way I have it set from my desktop. It opens up the pictures folder with just a list of file names not the icons I normally use.  If I want to find a particular picture that I dont know the name of it is a real pain in the rear to have to preview each picture until I get the right one.  I have thousands of pictures so you can imagine the task.

Al I want is for the folder to use my desktop version so I can select my pic to upload without using the preview.

Hope this helps as I have seen many posts in forums that complain about this.

Regards
John

**Comment by JosephMcc** [comment]
That is not the file manager you are seeing. That is a file chooser dialog that is provided by whatever app you are opening it from. That has nothing to do with us and we have no control over it.

**Comment by jjones1911** [comment]
Hmm, Thanks for looking guys. I am a little confused.  I will have to continue research. Thanks anyway
John

**Comment by Jeremy7701** [comment]
A suggestion:-
Copy & paste relevant attachments to the desktop, where they can be easily found.
Delete them when you've sent your email.
Rather tedious though.

**Comment by jjones1911** [comment]
Thanks Jeremy,  I had already done that and yes it is tedious.  I shall keep looking to find a solution (if windows can do it, Linux Mint MUST be able to) somehow.  I will probably try one or two distros that are not based on Ubuntu.
Best regards
John
