### ISSUE TITLE
Nemo cannot create trash directories on btrfs subvolumes

### ISSUE THREAD

**Issue by hasezoey** [linuxmint/nemo#2749]
```
 * Nemo version (nemo --version): 4.8.6
 * Is issue with desktop or windowed nemo?: both?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 20.1
 * Graphics hardware *and* driver used: shouldnt matter here
 * 32 or 64 bit: 64
 ```

**Issue**

Trash folder cannot be created for btrfs subvolumes

**Steps to reproduce**

- create an btrfs partition
- add subvolumes to the btrfs partition
- only mount subvolumes (not id 0)
- try to delete something on there

**Expected behaviour**

should create an trash folder

**Other information**

The Only times when trash works with btrfs subvolumes is:
- when the root (`/`) is an mounted subvolume
- when `/home` is an mounted subvolume

for other things nemo says it cannot create the trash folder

uid & gid: 1000

Note: i only mount *subvolumes* not the whole *parition*
like `sudo mount /dev/sdd /mnt/random1 -o subvol="notroot",compress-force=zstd:10`

i do this to have snapshots (with snapper) and to maybe divide the parition up more

PS: user 1000 owns the *root* of the btrfs *partition* and the *subvolume* folders, but only the subvolume folders are mounted

**Comment by thomas725** [comment]
I just experienced the same bug I believe.
I have an external hard drive formatted with btrfs. I use the gui mounting by nemo (or is it cinnamon?) to have the root subvolume (=/) mounted to `/media/user/diskname`. Outside of any subvolumes the trash feature works fine, but inside subvolumes I instead get a "cannot move to trash, do you want to delete directly?" popup.

At first I thought maybe somethings wrong with the permissions like this suggested:
https://askubuntu.com/questions/75154/cannot-move-file-to-trash-warning-when-trying-to-delete-a-file-in-nautilus
But no, all permissions are there and I can manually create a trash folder inside the subvolumes root folder `/media/user/diskname/@subvolume-name/`

**Comment by leigh123linux** [comment]
File the issue against gvfs-trash (gvfsd) or gio (glib2) as they provide the trash functions.
