### ISSUE TITLE
Search by extension no longer working recursively

### ISSUE THREAD

**Issue by ranolfi** [linuxmint/nemo#2754]
```
 * Nemo version 5.0.0
 * Windowed
 * Distribution: Arch
 * 64 bit
 ```

**Issue**

Since version 5.0.0 it is no longer possible to recursively search for files using a wildcard and extension.

E.g. In a directory with subdirectories containing mp3 files, searching for `*.mp3` won't yield any results.

**Comment by mtwebster** [comment]
This works fine for me - recursion is now disabled by default, there's a toggle in the search bar - 
![recurse-demo](https://user-images.githubusercontent.com/262776/120633575-4b91ef80-c438-11eb-9b20-f5b57059d7eb.gif)

**Comment by ranolfi** [comment]
> This works fine for me - recursion is now disabled by default, there's a toggle in the search bar -
> ![recurse-demo](https://user-images.githubusercontent.com/262776/120633575-4b91ef80-c438-11eb-9b20-f5b57059d7eb.gif)

Oh there is. Alright, thanks.

**Comment by ranolfi** [comment]
Anyway, let the records show that I strongly question the decision of disabling recursion by default, this is confusing and inconsistent with expected behavior across platforms (and with previous versions of the file browser).

**Comment by gkatev** [comment]
> Anyway, let the records show that I strongly question the decision of disabling recursion by default, this is confusing and inconsistent with expected behavior across platforms (and with previous versions of the file browser).

As I just spent ~10 minutes trying to figure out why the search function does not work, I'd also like to say that having recursion enabled by default would probably be for the best.
