### ISSUE TITLE
Custom actions missing in File menu from startup

### ISSUE THREAD

**Issue by OVlasiuk** [linuxmint/nemo#2758]
```
 * 5.0.0
 * windowed
 * Arch
 * Intel UHD Graphics 620 / i915
 * 64 bit
 ```

**Issue**
Shortcuts for custom actions show up in the File menu only after the right-click menu has been displayed.

**Steps to reproduce**
- start up Nemo
- add a custom action to e.g. open pdf files in Zathura: [zathura.txt](https://github.com/linuxmint/nemo/files/6611990/zathura.txt)
- restart Nemo
- select a pdf file in Nemo
- open File menu with Alt-F, notice that the custom action is not listed
- right-click the file, notice that the custom action is listed
- open File menu with Alt-F, the custom action is now listed here as well

The action will remain listed for pdf files until Nemo is restarted.

**Expected behaviour**
Custom action is listed in File menu from startup

**Other information**
This bug is absent in Nemo 4.8.5.

**Comment by Jeremy7701** [comment]
`Extensions=pdf;djvu`
Surely this ought to be

**MimeType=application/pdf;image/vnd.djvu;**

Actually, why not just install zathura and associate it with these file types and right-click the file?
You don't need to write desktop-type files to run a program.

**Comment by OVlasiuk** [comment]
@Jeremy7701  
> Surely this ought to be

Works as-is on my system =)

> Actually, why not just install zathura and associate it with these file types and right-click the file?

Sure, you can right-click the file, trace down the menu to `Open with`, trace another menu to the very end, then click Zathura. Or, just press `Alt-f z` on keyboard.

**Comment by Jeremy7701** [comment]
Apologies. Just assumed that a reference to an extension in Linux must be wrong. Sorry.
You can use extension or mimetypes.

**Comment by OVlasiuk** [comment]
@mtwebster Thanks!
