### ISSUE TITLE
Inconsistent type-ahead with mouse

### ISSUE THREAD

**Issue by donjan** [linuxmint/nemo#276]
(updated March 2015)

Nemo 1.1.2 through 2.4.5, various Ubuntu versions (bi-yearly updates and at least three fresh installs)

Use case:
Open a directory with lots of subdirs ('A...', ... , ''TRD001', 'TRD002', 'TRD003', ...), type first letter of target ('T') to jump to that region and click e.g. 'TRD008' with the mouse. This is handy if you have either a trackpoint or one hand on the mouse already, instead of writing out the full name or using the arrow keys.

Expected:
Nemo correctly dismisses the search box after the mouse click. It also intuitively dismisses the type-ahead when clicking into empty space within the directory.

Problem:
If the directory holds many subdirs, the box stays both when clicking on any dir and into empty space. This is fairly confusing when browsing down a hierarchy, and breaks workflow. One can dismiss it manually by hitting Esc.

From that point on, it will keep this behaviour even if returning to the starting point of the use case. Only a new Nemo instance will behave as expected, the current one is "botched".

Demonstration video: http://caleo.dyx.ch/stuff/.nemo/typeahead.webm (0.5MB)

Reproduce:
Either replicate the demonstration video or 
- open a new nemo instance
- go (by clicking) to File System > usr > share
- hit a letter on your keyboard, the type-ahead box comes up
- click any directory in /usr/share (or even the empty space between icons) and the type-ahead box won't go away.

Workaround:
Hit Esc after mouse-clicking a dir with a type-ahead box on. Also use Esc instead of empty-space clicking to dismiss the box.

Solution:
It shouldn't change behaviour mid-browsing :)

**Comment by voinescuandrei** [comment]
On Nemo 3.0.6 in Fedora 23 this is still the case.

**Comment by JosephMcc** [comment]
I can reproduce this on Mint 18/Cinamon3.2. The box only seems to go away after its timeout is reached.

**Comment by donjan** [comment]
Biennial pulse :)
Bug still persists in Nemo 3.2.2 on Ubuntu 16.04 and 16.10 as shown in the video, easiest reproduced by visiting /usr/share.

**Comment by donjan** [comment]
Just wanted to remark that this issue exists in Ubuntu 18.04. See y'all again when I've used 20.04 for a while.

**Comment by eyalroz** [comment]
Indeed, I think my issue (#1461) is a generalization of this one.
