### ISSUE TITLE
How can I test run nemo - 5.0.1 in a VM?

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2764]
```
 * Nemo 5.0
 * Is issue with desktop or windowed nemo?
 * Distribution - LMDE4
 * Graphics hardware *and* driver used
 * 64 bit
 ```

**Issue**
i'd like to try nemo in a LMDE4 VM
Is this possible and if so how should I go about doing this?

**Steps to reproduce**
N/A

**Expected behaviour**
N/A

**Other information**

**Comment by leigh123linux** [comment]
Your question belongs on linuxmint forum.
