### ISSUE TITLE
Trash not working on NixOS because `gvfs-trash` is deprecated and replaced by `gio`

### ISSUE THREAD

**Issue by papojari** [linuxmint/nemo#2769]
```
 * 5.0.0
 * both
 * NixOS 21.11
 * AMD Radeon HD 7850 with amdgpu
 * 64 bit
 ```

**Issue**

The trash is not working. Trash is not showing up on the left. I can't move stuff to trash the normal way.

**Steps to reproduce**

* Install NixOS 21.11 with GNOME ISO
* install nemo
* try to move something to the trash by selecting and hitting `delete` or right clicking and clicking `Delete`.

**Expected behaviour**

* files are moved to trash
* Trash shows up on the left list

**Other information**

This issue comes from `gvfs-trash` being deprecated on NixOS. It has moved to `gio`. So you could put a file into the trash with `gio trash <file>`.

**Comment by mtwebster** [comment]
This doesn't make sense - we don't use a command to send items to the trash in nemo.

Do other 'virtual' items show up in the sidebar?  Recent files? Favorite files? If you navigate to `trash:///` in the location bar what happens?

Is there anything printed out if you run nemo from a terminal?

This sounds maybe as though you don't have 'gvfs' or 'gvfs-backends' installed.

does `gio trash <somefile>` actually work in a terminal?

What is the output to the following command:
```
python3 -c "from gi.repository import Gio; g = Gio.Vfs.get_default(); print(g.get_supported_uri_schemes()); exit(0)"
```

**Comment by papojari** [comment]
> This doesn't make sense - we don't use a command to send items to the trash in nemo.
> 
> Do other 'virtual' items show up in the sidebar? Recent files? Favorite files? If you navigate to `trash:///` in the location bar what happens?
> 
> Is there anything printed out if you run nemo from a terminal?
> 
> This sounds maybe as though you don't have 'gvfs' or 'gvfs-backends' installed.
> 
> does `gio trash <somefile>` actually work in a terminal?
> 
> What is the output to the following command:
> 
> ```
> python3 -c "from gi.repository import Gio; g = Gio.Vfs.get_default(); print(g.get_supported_uri_schemes()); exit(0)"
> ```

I don't know why but the trash only works when starting nemo in a terminal. Same for *Recent* and *Favorites*. I didn't even notice things like *Recent* or *Favorites* not showing up. Now they do again.

Yes, `gio trash` works.

The only thing printed out when starting nemo in a terminal is

```
** (nemo:37325): WARNING **: 21:08:15.340: Current gtk theme is not known to have nemo support (Materia-dark-compact) - checking...
```

When running

```
python3 -c "from gi.repository import Gio; g = Gio.Vfs.get_default(); print(g.get_supported_uri_schemes()); exit(0)"
```

I get

```
es()); exit(0)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
```

**Comment by mtwebster** [comment]
No not a typo, you're just missing some python bindings for glib/gio. That's ok.

So everything works fine when starting nemo from a terminal? What desktop are you using, gnome-shell or cinnamon? How are you launching nemo when it manifests this problem? The main menu or some launcher? This seems more like some sort of environment issue but without more info I can't say.

If you're in gnome-shell, is nautilus installed? Does trash work there if you launch in the same manner?

**Comment by papojari** [comment]
> No not a typo, you're just missing some python bindings for glib/gio. That's ok.
> 
> So everything works fine when starting nemo from a terminal? What desktop are you using, gnome-shell or cinnamon? How are you launching nemo when it manifests this problem? The main menu or some launcher? This seems more like some sort of environment issue but without more info I can't say.
> 
> If you're in gnome-shell, is nautilus installed? Does trash work there if you launch in the same manner?

I am using sway on Wayland. I launch programs with `wofi --show=drun --lines=10 --prompt=""`.

The trash doesn't work in nautilus if launched with wofi or by terminal.

**Comment by mtwebster** [comment]
Is there any distro support you can bring this up with - forum, irc? I'm completely unfamiliar with that distribution and desktop. From the sound of it, this isn't a nemo-specific issue.

**Comment by papojari** [comment]
Yes, I am gonna ask on their matrix room

**Comment by papojari** [comment]
This issue only occurs when gdm is used as the display manager. When starting sway in a shell with `sway` everything works! I should have listened to the sway wiki not recommending gdm. 🤦‍♀️

_Originally posted by @papojari in https://github.com/NixOS/nixpkgs/issues/128026#issuecomment-920206390_
