### ISSUE TITLE
[feature request] support for fusermount

### ISSUE THREAD

**Issue by donjan** [linuxmint/nemo#277]
Something a certain other file manager hasn't managed to achieve despite issue reports being open for 5+ years: support for unmounting fuse filesystems (notably those mounted via sshfs) by clicking on the eject button in the sidebar.

The entries show up in mtab as (depending on the options of course):
USER@HOST:/REMOTE_MOUNTPOINT /MOUNTPOINT fuse.sshfs rw,nosuid,nodev,user=USER 0 0
and can be unmounted via
fusermount -u /MOUNTPOINT

Currently Nemo complains with
"umount: /MOUNTPOINT is not in the fstab (and you are not root)"
just like Nautilus did, trying only umount.

Any chances of seeing this convenience feature in Nemo?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by leigh123linux** [comment]
Why do we need to support fusermount?, the same support is already available using gvfs for sftp mounts.

**Comment by leigh123linux** [comment]
@clefebvre  @JosephMcc Perhaps you could rename "feature request" to "wish list" as there is little hope that they we ever be implemented due to limited manpower.
Why give hope when there is none? 😈

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
