### ISSUE TITLE
Allow searching for 1- and 2-character queries, but only when Enter is pressed

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/nemo#2772]
It's quite inconvenient when I try to search for a 2-character query and Nemo won't allow me, so I'm forced to use the terminal. I understand 1- and 2-character queries do not load automatically because it would be extremely slow due to the high number of matches.

But if the user consciously presses the "Enter" button, they have clearly made a decision. So I believe Nemo should either load the results if Enter is pressed, or show a popup asking the user if they are sure. Or even more ergonomically, ask the user to press Enter a second time to confirm the short query.

**Comment by mtwebster** [comment]
In nemo 5.0, search has been revamped somewhat, with some changes to this behavior:

- Only enter starts the search (it's not auto-search only once you've typed enough characters)
- There is no minimum to start the search (you can hit enter on an empty pattern) - you can now search for content inside files, so this is a valid application (search all files for ones containing 'foo').
