### ISSUE TITLE
Mouse wheel doesn't respond while dragging a file or folder

### ISSUE THREAD

**Issue by AlexFolland** [linuxmint/nemo#2776]
* Nemo version (nemo --version):
     * `nemo 5.0.2` (built from `aur/nemo-git` with version number `5.0.2.r4.g4c5a7e24-1`)
 * Is issue with desktop or windowed nemo?
     * Windowed, I think.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
     * Manjaro Linux x86_64 running kernel version `5.13.0-1-MANJARO`
 * Graphics hardware *and* driver used
     * Nvidia GeForce 1080 Ti running Nvidia proprietary driver version `470.42.01`
 * 32 or 64 bit
     * 64-bit

**Steps to reproduce**

1. Navigate to a folder that has enough files and folders to require scrolling to see them all.
2. Scroll down until a target folder is not visible.
3. Start dragging a file.
4. While the file is still being dragged, try to use the mouse wheel to scroll to the target folder.

**Observed behavior**

The mouse wheel does not respond in any visible way on-screen while dragging a file or folder.

**Expected behavior**

The mouse wheel is expected to respond while dragging a file or folder, allowing the user to drop the file into an off-screen target folder in an intuitive way.

**Other information**

This expected behavior is supported by several file managers and web browsers, including Windows Explorer in Microsoft Windows, and web applications like Asana and Google Drive running in Mozilla Firefox.  It is a common action I, personally, perform when using those other systems.  I often forget that it does not work in Nemo.

**Comment by Jeremy7701** [comment]
It would seem that the cause is similar to that mentioned in  #2508

**Comment by clefebvre** [comment]
Does this work in other GTK file managers?

**Comment by AlexFolland** [comment]
I tried in Thunar and PCManFM, and it worked in neither of those.  I use Nemo because it's better than those ones in my experience though.

**Comment by Jeremy7701** [comment]
May be worth considering a twin pane approach.
Split the Nemo screen in two with F3.
Scroll the two panes interdependently

Cut & Paste or drag and drop or whatever...

**Comment by mtwebster** [comment]
I remember some time back I was investigating some issue with drag-and-drop that was occurring 'mid-flight' during the drag. It turned out the application doesn't get any mouse events during this time, so I'm pretty certain the only place this could be implemented would be the 'toolkit' level - in Gtk. It would probably be best there anyhow, so that all applications could benefit from it.

**Comment by AlexFolland** [comment]
Thanks.  I'll follow up with that report.
