### ISSUE TITLE
How do I upgrade to the latest version?

### ISSUE THREAD

**Issue by arunkumaraqm** [linuxmint/nemo#2778]
```
 * Nemo version 4.4.2
 * Is issue with desktop or windowed nemo? Don't know what this means.
 * Distribution - Ubuntu 20.04
 * DE - Gnome
 * 64 bit
 ```

**Issue**
I can't update Nemo. Running `sudo apt-get install nemo` says 'Nemo is already in the newest version' but I see version 5 in the releases here.

**Comment by Jeremy7701** [comment]
Version 5 is the Mint beta version.
The current stable version for Mint and LMDE is 4.8.6.
This is not an "issue".

**Comment by leigh123linux** [comment]
> ```
>  * Nemo version 4.4.2
>  * Is issue with desktop or windowed nemo? Don't know what this means.
>  * Distribution - Ubuntu 20.04
>  * DE - Gnome
>  * 64 bit
> ```
> 
> **Issue**
> I can't update Nemo. Running `sudo apt-get install nemo` says 'Nemo is already in the newest version' but I see version 5 in the releases here.

File the issue against whatever ppa repo provides it.

**Comment by arunkumaraqm** [comment]
@leigh123linux Sorry, I don't understand. It's been two years since then and I still use the same version of Nemo. I'd like to update.
