### ISSUE TITLE
[Feature request] Make the file properties screen also show the size in bytes regardless of the prefix setting

### ISSUE THREAD

**Issue by KaMyKaSii** [linuxmint/nemo#2786]
```
 * Nemo version (nemo --version) - 5.0.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Mint 20.2 Uma
 ```

**Issue**

I often use the "Binary" prefix because it takes up little screen space and doesn't cause confusion when looking quickly at the size column (in the list view). But it is extremely inconvenient to have to change the prefix to "Binary (long format) in order to see the size in bytes of a file/folder. 

**Expected behaviour**

I would like the file properties screen to always show the size of the file/folder in bytes next to  the size in the prefix chosen by the user.

Thank you.

**Comment by Jeremy7701** [comment]
This would be very useful for people with really gigantic files.

**Comment by shadow73s** [comment]
Yeah, that will be nice.
The better way, make a separate property.
