### ISSUE TITLE
LMDE4 - upgrade to Cinnamon 5.0.5 doesn't include bulky.

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2788]
```
 * Nemo version 5.0.3
 * Is issue with desktop or windowed nemo?
 * Distribution - LMDE4
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

Nemo upgrade doesn't include **bulky**

**Steps to reproduce**

Update/Upgrade LMDE4

**Expected behaviour**

Supply a function to rename multiple files.

**Other information**

**Comment by clefebvre** [comment]
This is planned and not directly related to nemo. Bulky will be made available this week in LMDE though you will need to install it yourself.
