### ISSUE TITLE
File rename

### ISSUE THREAD

**Issue by n5edd** [linuxmint/nemo#2803]
```
 * Nemo version (4.8.6)
 * Is issue with desktop or windowed nemo? Window
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20.1 Cinnamon
 * Graphics hardware *and* driver used  AMD Radeon RX570, default driver.
 * 64 bit
 ```

**Issue**
Nemo will not allow renaming a file when the name change only involves changing case. It gives an popup error indicating
 the file name could not be changed because the file name is already in use.

**Steps to reproduce**
Open folder window.
Select a file, press F2
Change the case of a letter or letters without changing any other name format, select 'Enter' or left click on a blank part of the window.
Error popup opens.

**Expected behaviour**

Accept change. I'm not trying to generate a 2nd entry but merely revise an existing entry. This should not be an issue with 'rename'.

**Other information**

**Comment by mtwebster** [comment]
I can only reproduce this on a fat32 filesystem, what filesystem is that on?

**Comment by Jeremy7701** [comment]
Could not replicate this in current Nemo (5.0.3)

**Comment by n5edd** [comment]
As I stated in the ticket, I am using Mint 20.1 64bit. FS is EXT4.
Fat, Fat32, NTSF are not in consideration as I am aware they do not consider case, in file naming. However, to my knowledge, Linux always has. Nemo version 4.8.6 is the current version for Mint 20.1.
I don't remember having this issue with Mint 18.3 but that was too long ago to know for sure.
Jeremy, what system are you using 5.0.3 on?

**Comment by mtwebster** [comment]
You didn't state the filesystem in the ticket, and considering I couldn't reproduce it on anything but fat32, I think it's a reasonable question to ask. We have no way of knowing your level of experience.

Cannot reproduce on Mint 20.2, nemo 5.0.3+, or Mint 20.1, Nemo 4.8.6.

Does this occur in any location (or drive if you have more than one)? Does it occur in the live cd session?

**Comment by Jeremy7701** [comment]
I cannot reproduce this problem on any of my ext4 partitions, SSD or nvme0.
However, since `nvme0n1p1` is actually `/boot/efi` - a VFAT partition I **can** create a file in `/boot/efi/` (with root), although I would not ordinarily do so.
This behaves exactly as described by you in your "bug" report.
Are you perhaps encountering this problem on a USB key?

**Comment by n5edd** [comment]
My mistake. I assumed if I stated Mint 20.1 it would be understood that the FS was EXT4. Apologies, I forget there are others available. That aside, I have done addition testing. I thought I was on a local drive but it turns out, I wasn't. My system has a Seagate NAS and a QNAP NAS attatched to the local network. I was actually on the QNAP NAS. I have since checked and renaming works as I expected it should on a local drive as well as on the Seagate NAS. The strange thing to me is that both NAS's use Linux on EXT4 drives. Anyway, I'm closing the ticket as it is now a QNAP issue, not a NEMO issue. Thanks.

**Comment by n5edd** [comment]
Not using USB key but being they are FAT or EFAT by default, I wouldn't expect it to work on them anyway. No, my problem was on a NAS. I have closed the ticket. Sorry for the trouble.
 
 
 
-----Original Message-----

**Comment by mtwebster** [comment]
Wondering about other filesystems is mainly due to the fact that a lot of our users come from Windows, and may not be aware of these sorts of differences - it's not from any effort to be patronizing. Regardless I'm glad this has been more or less cleared up.

**Comment by n5edd** [comment]
No worries. I just wanted to be sure Nemo wasn't recently changed to act more like MS's file explorer. Still, it is odd to me that one Linux based NAS would have the issue where another doesn't. Anyway, sorry for the trouble.

 Cheers,
Ed
 
 
-----Original Message-----
