### ISSUE TITLE
CD/DVD burn process

### ISSUE THREAD

**Issue by rmvantol** [linuxmint/nemo#281]
When I insert a blank CD/DVD and I drop a file on it, I see it being copied to be burned, but I cannot find any button to start the burning process itself. Is this a known issue?

**Comment by Lx** [comment]
I've also experienced this issue just now.  When I insert a blank disc, a Nemo window to `burn:///` opens, and I can drag files into it, but there's nothing on the toolbar or in the menus to actually initiate a burn.

If burning CDs isn't supported by Nemo, it probably shouldn't be presented as an option when inserting a blank disc.

**Comment by mydoghasworms** [comment]
Still an issue in November 2015. Why is this issue closed then?

**Comment by JosephMcc** [comment]
It's not closed. The linked issue is.

**Comment by mydoghasworms** [comment]
OIC. Thanks :+1:

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by leigh123linux** [comment]
This should filed against nemo-extensions, nautilus uses brasero-nautilus package to display burn options.

https://github.com/linuxmint/nemo-extensions

**Comment by HbmMods** [comment]
*Still* an issue 12 years later. If Nemo can't burn CDs, then it shouldn't give the illusion of being capable by including the `burn:///` folder which does absolutely nothing.
