### ISSUE TITLE
nemo: hard-codes path to /usr/lib/gvfs/gvfsd-archive

### ISSUE THREAD

**Issue by Fantu** [linuxmint/nemo#2811]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992242:
> nemo hard-codes the path to /usr/lib/gvfs/gvfsd-archive. This path is an
> implementation detail of the gvfs package, and in newer versions it has
> been moved to /usr/libexec/gvfsd-archive. At the moment there is a symbolic
> link /usr/lib/gvfs/gvfsd-archive available, but we want to remove these
> symlinks during the Debian 12 release cycle.
> 
> Ideally, nemo should detect whether the archive backend is available in
> some other way, like looking for its D-Bus name in the list of activatable
> names, or looking for /usr/share/gvfs/mounts/archive.mount.
> 
> If that isn't possible, please update the path to its canonical location
> since Debian 11, which is /usr/libexec/gvfsd-archive.

**Comment by leigh123linux** [comment]
Fedora use libexec as well.

```
gvfs-archive-1.48.1-2.fc35.x86_64 : Archiving support for gvfs
Repo        : fedora
Matched from:
Filename    : /usr/libexec/gvfsd-archive
```

**Comment by mtwebster** [comment]
It looks like we only reference this in a couple of nemo 'actions' to mount an archive. We may be able to just change it to call 'gio mount', which is available in buster (lmde4) as well.

**Comment by Fantu** [comment]
@mtwebster thanks, the commit you added missed the add of "gnome-disk-utility" to nemo recommends

**Comment by mtwebster** [comment]
Done, thanks.

https://github.com/linuxmint/nemo/commit/95fced721b03ef4ba8e7f549f6b5a1c946eae16d
