### ISSUE TITLE
Nemo doesn't recognize executable binaries

### ISSUE THREAD

**Issue by SvenGeier** [linuxmint/nemo#2812]
```
 * Nemo version (nemo --version) **5.0.3**
 * Is issue with **windowed** nemo
 * Distribution - (**Mint 20.2**, )
 * Graphics hardware *and* driver used **Nvidia GTX560, nv driver**
 * 32 or **64 bit**
 ```

**Issue**
 Double-clicking an executable does not run it, but opens a dialog stating that it doesn't know what application to use to open this file.

**Steps to reproduce**
1) Run any of the standard x-binaries from the command line, e.g. `%/usr/bin/xlogo ` to show the X logo. 
2) Then use nemo to navigate to /usr/bin and double-click `xlogo`

**Expected behaviour**
Expect the binary to be executed, duh

**Other information**
More in-depth description here: https://forums.linuxmint.com/viewtopic.php?p=1712324#p1712324

**Comment by leigh123linux** [comment]
See https://github.com/linuxmint/nemo/issues/2385
