### ISSUE TITLE
Error while compiling: gobject introspection is missing (but installed)

### ISSUE THREAD

**Issue by germefur** [linuxmint/nemo#2813]
```
 * Compiling
 * Distribution - Linux Mint 20.2 Uma
 * x86_64
 ```

**Issue**
when i try to compile nemo from source, it says

meson.build:78:0: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake

and i have gobject-introspection installed, I dont know what package need to install

**Steps to reproduce**

compile? with `meson build`

**info**

the output while building:
```
The Meson build system
Version: 0.53.2
Source dir: /home/germe/Documentos/files/git/nemogerme
Build dir: /home/germe/Documentos/files/git/nemogerme/build
Build type: native build
Project name: nemo
Project version: 5.0.3
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Has header "malloc.h" : YES 
Has header "sys/mount.h" : YES 
Has header "sys/param.h" : YES 
Has header "sys/vfs.h" : YES 
Has header "X11/XF86keysym.h" : YES 
Checking for function "mallopt" : YES 
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gtk+-3.0 found: YES 3.24.20
Run-time dependency gio-2.0 found: YES 2.64.6
Run-time dependency gio-unix-2.0 found: YES 2.64.6
Run-time dependency glib-2.0 found: YES 2.64.6
Run-time dependency gmodule-no-export-2.0 found: YES 2.64.6
Run-time dependency gobject-2.0 found: YES 2.64.6
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)

meson.build:78:0: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake

A full log can be found at /home/germe/Documentos/files/git/nemogerme/build/meson-logs/meson-log.txt
```

the "nemogerme" folder is because im trying to modify some things...

**Comment by icarter09** [comment]
What does the `meson-log.txt` show?

**Comment by treeswift** [comment]
Hi @icarter09,
the issue reproduces for me, please see `meson-log.txt` attached. Ubuntu 18.04.

```
$ uname -a
Linux notmystudio 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ sudo apt-get install gobject-introspection
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gobject-introspection is already the newest version (1.56.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

[meson-log.txt](https://github.com/linuxmint/nemo/files/7775519/meson-log.txt)

**Comment by treeswift** [comment]
P.S. Per the answer here:
https://stackoverflow.com/questions/59140646/package-gobject-introspection-1-0-was-not-found-in-the-pkg-config-search-path-in

I installed `libgirepository1.0-dev` and that installed the missing `*.pc` file for me. IOW, I got past

```
Run-time dependency gobject-introspection-1.0 found: YES 1.56.1
```

Maybe nontrivial relationship between the `pkg-config` package and the Debian package needs to be clarified somewhere in the build documentation.

**Comment by leigh123linux** [comment]
User inability to compile code isn't a bug.

**Comment by treeswift** [comment]
Second-guessing dependencies isn't compiling, it's the malpractice that structured software repositories in the Linux world exist to render unneeded.

**Comment by leigh123linux** [comment]
@treeswift Why guess when there are already listed?

https://github.com/linuxmint/nemo/blob/master/debian/control#L5
