### ISSUE TITLE
add "[Space] = Preview on/off" to list of Keyboard Shortcuts (ctrl-F1)

### ISSUE THREAD

**Issue by DGedye** [linuxmint/nemo#2818]
```
 * Nemo version  5.0.3 on 64bit Mint 20.2
 * Graphics hardware *and* driver used N/A
 
 ```

**Issue**
I only just found out via the forums that nemo has a preview function turned on and off by the spacebar.
I felt really stupid that I had missed something so obvious. But then I checked nemo's list of keyboard shortcuts (ctrl-F1) and that is not listed! It seems a rather glaring omission. 
https://forums.linuxmint.com/viewtopic.php?p=2057774#p2057774

**Steps to reproduce**
Launch nemo
ctrl-F1
"[Space] = Preview on/off" is not listed as a shortcut!

**Expected behaviour**
"[Space] = Preview on/off" should be listed as a shortcut.

**Other information**

**Comment by Jeremy7701** [comment]
I think that it is part of a general lack of documentation for nemo.
I've discovered that nemo has many non-obvious features (not all revealed via shortcuts).

**Comment by JosephMcc** [comment]
In the case of the preview functionality (and possibly some others) there is a reason. The shortcuts window shows only what's available in Nemo's core. What you are talking about is an extension we ship with Mint called `nemo-preview`. That is actually a  separate package from Nemo itself.

**Comment by LinuxOnTheDesktop** [comment]
I too had no idea about this functionality. Worse: when I clean my keyboard - with, admittedly, the computer on, but with only the desktop showing - often a preview window pops up, with a spinner in it, and I get the following error message in the log.

`JS ERROR: Error calling prepare() on viewer: Gio.IOErrorEnum: The specified location is not supported#012_createRenderer/<@/usr/share/nemo-preview/js/ui/mainWindow.js:327:50#012run@/usr/share/nemo-preview/js/ui/main.js:55:24#012@../src/main.c:2:6`

I feel that all major functionality should be advertised in one way or another and that, where possible, random key presses should not log an error messages. Moreover, it seems that whatever Nemo (or its extension) was trying to preview could not be previewed.
