### ISSUE TITLE
Nemo takes minutes to open a window if one of several other programs have been run.

### ISSUE THREAD

**Issue by SnerkRabbledauber** [linuxmint/nemo#2821]
```
 * Nemo version (nemo --version)
 nemo 4.8.6

 * Is issue with desktop or windowed nemo?
 windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 linux Mint 20.1 Cinnamon
 * Graphics hardware *and* driver used
 NVIDIA GP107
nvidia-driver-460 version 460.91.03-ubuntu0.20.04.1
 * 32 or 64 bit
 64
 ```

**Issue**
After running certain programs nemo takes 4 minutes to open. Once it opens then you can open folders and navigate normally. but if you try to open another nemo window it takes 4 minutes again. 

**Steps to reproduce**
Choose Files from the Mint menu and time how long it takes to open a window. On my system it takes 4 seconds.
Now take one of the following actions:
  * Open Transmission, right click on a torrent and choose open folder. It will open quickly.
  * Run the Discord desktop application. Just running it seems to be enough.
  * Run the Obsidian Notes desktop application. Just running it seems to be enough.
Now open a nemo window the same way you did before. It will take minutes to open. On my system I time it at 4 minutes.
Closing the other program you ran makes no difference in nemo startup time. I have to reboot to restore quickness.

**Expected behaviour**
Open in seconds, no matter what other programs have been run previously.

**Other information**

**Comment by mtwebster** [comment]
Did this just start happening? After an update? Do you have any extensions running that you can disable to rule them out?

Try starting nemo from a terminal (make sure it's not running first - `nemo --quit && nemo` - are there any warnings printed when this happens?

If you create a new user account, does this happen there as well?

**Comment by SnerkRabbledauber** [comment]
Actually I just now was trying to upgrade to a better nvidia driver and installed libstdc++6 version 10. Now this is no longer happening. Note that I did not successfully change to a new nvidia driver. But just installing a higher version of libstdc++6 appears to have done the fix.
Just to answer your questions in case someone else experiences this. I think it started after a discord update. When it was happening it happened even if I run nemo from the command line. I would get an error saying had timed out waiting for something. I think it was something about registering nemo as some sort of service or something. I'm sorry I can't tell you exactly now since it stopped happeing.

**Comment by SnerkRabbledauber** [comment]
Update. I removed all i386 libraries from my system to get this problem to go away.

**Comment by SnerkRabbledauber** [comment]
Further update. Removing all i386 libraries did not actually stop the problem. Since then I have been trying to figure out what triggers it. It seems to just be a matter of time. Yesterday I upgrade to Mint 20.2 and it is still happening. Even if I reboot and just leave the server sitting overnight, when I came back in the morning there was the 4 minute lag when trying to open nemo from the desktop. When I try from the command line i get this error:

   Could not register nemo as a remote: Timeout was reached

Some version information:
$ cat /etc/linuxmint/info 
RELEASE=20.2
CODENAME=uma
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20.2 Uma"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_uma_cinnamon_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_uma_cinnamon.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 20.2 Cinnamon
$ nemo --version
nemo 5.0.5
$

**Comment by Mintulix** [comment]
@SnerkRabbledauber I have nearly the same problem (1 minute instead of 4), but only in conjunction with the error described in #https://github.com/linuxmint/cinnamon/issues/10570
Do you use different accounts and/or have this nemo start delay after suspend?

**Comment by SnerkRabbledauber** [comment]
I only use one account and never suspend.
I also need to say that this has not happened for a long time now. Some upgrade or another seems to have fixed it. Current version info below. But I suspect it was an upgrade of something other than OS that fixed this.

$ cat /etc/linuxmint/info 
RELEASE=20.2
CODENAME=uma
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20.2 Uma"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_uma_cinnamon_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_uma_cinnamon.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 20.2 Cinnamon

**Comment by Mintulix** [comment]
Thanks for clarifying this. It seems I was an the wrong track and removed the direkt link to the Cinnamon error.
If your nemo lag is gone, you may close this issue.
