### ISSUE TITLE
Nemo Search Function Broken

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/nemo#2822]
```
 * Nemo version 5.0.3
 * Is issue with desktop or windowed nemo? Windowed nemo
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 460.91.03 bus ID: 01:00.0 
           chip ID: 10de:1d01 
           Display: x11 server: X.Org 1.20.11 driver: nvidia 
 * 64 bit
 ```

**Issue**
After 2 searches today the next searches don't work any more. The only search that is working is search in same directory.
Parallel installed Nautilus is working fine at the same time.
Searching with Nemo in another machine is OK.

**Steps to reproduce**
Click on search button in toolbar and type in any item.
Enter
Message popping up immediately (within nano-sec): No files found
Trying to search all partitions or certain directories. Only same directory gives success.

**Expected behaviour**
Any searching either in all devices on the machine or certain directories should be possible and succeed.

**Other information**
I tried re-installing nemo and search-related packages via synaptic without any effect. Also I moved 
/~/.config/nemo
/~/.local/share/nemo
to another directory, closed and restarted nemo without any effect.
Also I used Timeshift to restore a previous snapshot from the day before, without any effect.

**Comment by mtwebster** [comment]
Did you turn this off?

![image](https://user-images.githubusercontent.com/262776/131259837-6cc95744-0928-443b-a611-76e6b0458cfe.png)

**Comment by Dan-cer** [comment]
Yessss! Bingo! I didn't know anything of that function and yes, i clicked on it. Now it is all OK. I'll close this topic.


Thank you very much for your quick answer and solution! 

Michael Webster schrieb am Sonntag 29 August 2021 19:35:20 (+02:00):



Did you turn this off?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
