### ISSUE TITLE
If there are no nemo windows open, the  "nemo --quit"  command produces strange messages

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2827]
```
 * Nemo version (5.0.3)
 * Is issue with windowed nemo?
 * Distribution - (LMDE4)
 * Graphics hardware *and* driver used
 * 64 bit

**Issue**

If there are no nemo windows open, the `nemo --quit` command produces extraneous messages:-
```
Initializing nemo-image-converter extension
[Nemo Terminal] I: Initializing the Nemo extension
Initializing nemo-pastebin extension...
DEBUG:nemo-pastebin:Initializing nemo-pastebin extension...
nemo-media-columns: using a timeout of 0.20 second(s) for file processing
```

**Steps to reproduce**
Ensure there are no nemo windows active.
From a Terminal window, enter the `nemo --quit` command

**Expected behaviour**
The command **silently** completes.


**Other information**

If there is at least one nemo window open, the quit command behaves as it should.

**Comment by icarter09** [comment]
Nemo v5.0.3
Mint 20.1 64bit daily build

I'm not able to reproduce this. I keep getting the expected behavior

**Comment by mtwebster** [comment]
Nemo is not running if there are no windows. When you run nemo --quit, the program has to get far enough to parse the command line, then it quits. This isn't really a bug, just the way these types of applications work (single process, multiple windows), and not worth rearranging how things get initialized to silence these messages.
