### ISSUE TITLE
Allow user to delete and rename files from an application "Open" window (as is already possible in a "Save" window)

### ISSUE THREAD

**Issue by rgreen5** [linuxmint/nemo#2828]
```
 * Nemo version (nemo --version): 4.8.6
 * Is issue with desktop or windowed nemo? - Windowed
 * Distribution - Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal
 * Graphics hardware *and* driver used: Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Dell 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0116 
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 21.0.3 
           compat-v: 3.0 direct render: Yes
 * 32 or 64 bit: 64 bit
 ```
**Issue**
It is not possible to either **delete** (send to trash) or **rename** files from an application's "Open" window. This seems curious since you *can* delete or rename from an application "Save" window.

**Steps to reproduce**

1. Open, say, LibreOffice. Make sure you have some LO files already stored in a convenient directory.
2. Click on the LO "Open File" icon and navigate to an existing LO file.
3. Right-click on a file and inspect the options available.

**Expected behaviour**

There should be options for "Rename" and "Move to Rubbish Bin" (UK En.)

**Other information**

These options *are* available in the "Save" window, so it seems curious that they are not available in the "Open" window, as well. MS Windows allows them, and, in my experience it is an invaluable and time-saving feature.

**Comment by leigh123linux** [comment]
This isn't a nemo issue.
GtkFileChooserDialog is provided by GTK3.

**Comment by rgreen5** [comment]
A link to the relevant GTK3 reporter would have been appropriate here. Trying  [GNOME > gtk > Issues](https://gitlab.gnome.org/GNOME/gtk/-/issues?scope=all&state=opened&search=open+window) instead.
