### ISSUE TITLE
Space gets lost when moving big files.

### ISSUE THREAD

**Issue by GHNewbiee** [linuxmint/nemo#2836]
It happens very often. This is the steps to reproduce it:

- Plugin a USB stick memory
- Select and remove big files (eg. iso) from your hard disk to USB stick
- While transferring, choose a big file in USB stick and delete it.
- After completion of removing the files, check the free space of the USB stick comparing with the sum of all contents. The size of the big file you have deleted is not included. It's lost! (BTW, any idea how can I **recover** the lost size apart from formatting?)

In addition, the info appearing while moving it is totally wrong!

After so many years of development, Nemo is still unreliable.

**Comment by mtwebster** [comment]
You 'trashed' them instead of deleting. Empty your trash or delete .Trash-xxx from the drive.

Use the issue template next time and DBAD.

**Comment by GHNewbiee** [comment]
Wrong!!! Don't be so in a hurry!!! You are not the only one who knows about trashing and deleting.

**Comment by GHNewbiee** [comment]
> While transferring, choose a big file in USB stick and delete it.

Are you an official member of the team (eg developer, etc)?

**Comment by GHNewbiee** [comment]
If I remember correct, even when you trash it, you cannot see it in the trash bin.

**Comment by Jeremy7701** [comment]
It's a **hidden file/directory**.
Either delete it (don't trash it) or look at your hidden directories to delete the Trash.

**Comment by GHNewbiee** [comment]
@mtwebster Speakless?!!! Twice has happened to me! Check and come back to apologize! DH!

**Comment by mtwebster** [comment]
From your screenshot, nemo see 232 items on the drive. Are you certain there are no hidden files on this drive?

> Are you an official member of the team (eg developer, etc)?
Yes.

Again, please fill out the issue template (on all of the issues you've opened).

**Comment by Jeremy7701** [comment]
Is it possible to block this person?

**Comment by GHNewbiee** [comment]
> Is it possible to block this person?

Blocking **`mtwebster`** will not solve the problem. Definitely, I do not agree with the method "Head aches, cut head". We just have to convince him by humanitarian and democratic means to check and confirm the issue described above.

**Comment by NikoKrause** [comment]
> > While transferring, choose a big file in USB stick and delete it.
> 
> Are you an official member of the team (eg developer, etc)?

LOL

https://github.com/linuxmint/nemo/graphs/contributors
