### ISSUE TITLE
How to select the last file

### ISSUE THREAD

**Issue by GHNewbiee** [linuxmint/nemo#2837]
Please have a look at the following screencast.

https://user-images.githubusercontent.com/26875662/134174970-21552e91-2268-40a0-b9b7-58b8b84537be.mp4

`ventoy...tar.gz` is the last file. I am trying to select it by mouse but the horizontal bar interferes.Is there any option to make horizontal bar permanent displayed. *Tia*

**Comment by Jeremy7701** [comment]
Fill out the template showing the details of distro, 32/64 bit, version of nemo, window or desktop etc etc

**Comment by Jeremy7701** [comment]
BTW "that bottom horizontal bar" is the window scroll bar (there is another on the right).
You need a wider window or different elements positioned differently in your window.

**Comment by JosephMcc** [comment]
Your issues are going to be closed if you refuse to use the supplied issue template. It's there for a reason. This is also not a general user Q and A forum. Questions like this are likely to get much more help on the Linux Mint forums.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/e8c8b1099112f3d157849c7a1c303110ea144583
