### ISSUE TITLE
Add image resize option to Nemo?

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/nemo#286]
Many of the integrated functions (like send with Thunderbird, for example) are great in Nemo.  However, one key missing function (in my opinion, and for many users I have worked with) is the ability to resize images on right-click.  Nautilus extensions that do this are:

nautilus-image-converter
nautilus-image-manipulator

(I have personally only used the "image-converter" one in Nautilus but found reference to the other as well here:
https://github.com/linuxmint/nemo-extensions)

Any chance this functionality may come to Nemo?  Thanks.

**Comment by Vahan86** [comment]
@JosephMcc, can be marked as a feature request?

**Comment by JosephMcc** [comment]
As mentioned above nemo-image-converter is now available.
