### ISSUE TITLE
Type ahead find

### ISSUE THREAD

**Issue by aloispichler** [linuxmint/nemo#2861]
```
 * Nemo version 5.0.5
 * Distribution - Arch
 * 64 bit
 ```

**Issue**
_type ahead find_ displays the directory or file starting with the characters typed.
Example: type "John",
Nemo highlights the files *"John\*"*, i.e., starting with "John".

**Desired behavior**
Nautilus also finds the files "\*John\*", i.e., containing "John".

Thank you.

**Comment by fschaupp** [comment]
Hey! Great idea! 
I see at least 4 open questions here:
- how do we rate the new matches in comparison to the ones starting with John? Should there be some sort of "when the search string matches more than 70% of the actual name, we rate it higher than results just starting with it and having less than x% of a match"? (Opening up some more questions) - Should they be appended, when all starting matches were 'fetched'/displayed instead? Should it consider last/frequently used files with a bias boost?
- should the feature be an option or the default (or just for 'newcomers')?
- how about the performance impact of the first mentioned option? Does it pay off for the battery juice it invests? 
- How to make it 'chewable' for the user? Does the average user get it?

Maybe you see here some new paths for making great advancements in the search bar 💪

**Comment by aloispichler** [comment]
In fact, “_type ahead find_”  should work and behave exactly the same way as “_Search for files_”.
This would be consistent behavior, which Nautilus does as well.
