### ISSUE TITLE
Allow icon view in "Insert image" window

### ISSUE THREAD

**Issue by rgreen5** [linuxmint/nemo#2870]
```
 * Nemo version (nemo --version): 4.8.6
 * Is issue with desktop or windowed nemo? - Windowed
 * Distribution - Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal
 * Graphics hardware *and* driver used: Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Dell 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0116 
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 21.0.3 
           compat-v: 3.0 direct render: Yes
 * 32 or 64 bit: 64 bit

 ```

**Issue**

*Note*: This may be a GTK rather than a Nemo issue. However I'm filing it here just in case.

The "Insert Image" window in LibreOffice Writer, for example, displays images as a list. As the thumbnails are too small to be seen effectively, preview also needs to be enabled. However, even with "Preview" enabled, there are drawbacks; i.e. (1) navigation through a list of files is slower than if they were displayed as icons  (2) only the currently selected image is visible; and (3) very small images may be overmagnified and blurred.

*Suggestion*: Allow images to be displayed as icons in the "Add/Insert" window just like the standard Nemo file explorer window.

**Steps to reproduce**

1. Open a default document in LO Writer.
2. Chose Insert > Image and navigate to a folder with many images in it, ideally small ones such as backgrounds.
3. Navigate through the list with preview on.
4. Now navigate to the same folder using Nemo file explorer. Note the greater utility afforded by having the images displayed as icons.

**Comment by JosephMcc** [comment]
This is an issue/request with Gtk's file dialog. We have no control over this.
