### ISSUE TITLE
Desktop Respond Very Slowly

### ISSUE THREAD

**Issue by blueray453** [linuxmint/nemo#2873]
```
 * Nemo version: nemo 5.0.5
 * The issue is with **Desktop**
 * Distribution: Mint 20.2
 * Graphics hardware *and* driver used: Intel UHD Graphics 630
 * 64 bit
 ```

**Issue**

The issue is with the desktop icons and nowhere else.

After an hour of so after turning on my PC, If I click any icon in desktop, it takes more or less 1sec to select that icon. Then if I want to click another icon, it again takes more or less 1sec to select that icon....

When the issue occured, I used `nemo -q` but it did not improve the situation. When I used `nemo-desktop -q` the performance was improved. So, I think the issue is with `nemo-desktop`.

**Steps to reproduce**

Start Mint 20.2. Keep browsing with Firefox. Do a Little work in Codium. Maybe after using it for an hour, when I click any icon in desktop, it takes more or less 1sec to select that icon. The response become very slow. So, I have to open `nemo` from panel and then through it browse files in desktop.

**Expected behaviour**

Clicking on icons in desktop should select it instantly.

**Other information**

```
% nemo --version
nemo 5.0.5

% hostnamectl
Icon name: computer-desktop
Chassis: desktop
Operating System: Linux Mint 20.2
Kernel: Linux 5.13.0-21-generic
Architecture: x86-64

% inxi -F
System:    Host: ismail-i5 Kernel: 5.13.0-21-generic x86_64 bits: 64 Desktop: Cinnamon 5.0.7 Distro: Linux Mint 20.2 Uma
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME H370-PLUS v: Rev 1.xx serial: <superuser/root required>
           UEFI: American Megatrends v: 2301 date: 07/10/2020
CPU:       Topology: 6-Core model: Intel Core i5-8600K bits: 64 type: MCP L2 cache: 9216 KiB
           Speed: 4172 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 4216 2: 3649 3: 3917 4: 3285 5: 2250 6: 1763
Graphics:  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa
           resolution: 1920x1080~60Hz, 1920x1080~60Hz
           OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 21.0.3
Audio:     Device-1: Intel Cannon Lake PCH cAVS driver: snd_hda_intel
           Sound Server: ALSA v: k5.13.0-21-generic
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
           IF: enp5s0 state: up speed: 100 Mbps duplex: full mac: 18:31:bf:b5:e6:5b
Drives:    Local Storage: total: 14.78 TiB used: 10.19 TiB (68.9%)
           ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 250GB size: 232.89 GiB
           ID-2: /dev/sdb vendor: Western Digital model: WD40EFRX-68WT0N0 size: 3.64 TiB
           ID-3: /dev/sdc vendor: Western Digital model: WD82PURX-64GVLY0 size: 7.28 TiB
           ID-4: /dev/sdd vendor: Western Digital model: WD40PURX-64N96Y0 size: 3.64 TiB
Partition: ID-1: / size: 227.74 GiB used: 42.30 GiB (18.6%) fs: ext4 dev: /dev/sda2
Sensors:   System Temperatures: cpu: 51.0 C mobo: N/A
           Fan Speeds (RPM): N/A
Info:      Processes: 255 Uptime: 1d 2h 23m Memory: 31.20 GiB used: 4.58 GiB (14.7%) Shell: zsh inxi: 3.0.38
```
More Details Can Be Found On : https://forums.linuxmint.com/viewtopic.php?f=90&t=361543

**Comment by Jeremy7701** [comment]
You need to identify a reproducible cause before submitting this as an issue.
You have had a number of responses in https://forums.linuxmint.com/viewtopic.php?f=90&t=361543

**Comment by blueray453** [comment]
I think the issue is with nemo-desktop. If there was something wrong with ram or cpu then the whole system will get affected , not just the desktop icons. 

I am attaching some screenshot of `glances` command output.

![Screenshot-2021-11-22-15:29:14](https://user-images.githubusercontent.com/855297/142837904-03c3fe30-559a-4aee-959b-a0cc1026276e.png)
![Screenshot-2021-11-22-15:33:14](https://user-images.githubusercontent.com/855297/142837909-05e4a09e-0a34-4a01-adf8-9e6de05ab56b.png)
![Screenshot-2021-11-22-15:33:55](https://user-images.githubusercontent.com/855297/142837915-2e6e1f0a-3e09-4b89-a795-275c6e64a10b.png)
![Screenshot-2021-11-22-15:34:13](https://user-images.githubusercontent.com/855297/142837919-c1c8460d-53a8-46e8-adc4-86873dd59f55.png)
![Screenshot-2021-11-22-15:34:46](https://user-images.githubusercontent.com/855297/142837924-cbdde4e3-2b14-4524-9b75-14776730ebc1.png)
![Screenshot-2021-11-22-15:34:54](https://user-images.githubusercontent.com/855297/142837928-84d64c64-a9b6-47e4-8515-b17a3374a495.png)
![Screenshot-2021-11-22-15:34:58](https://user-images.githubusercontent.com/855297/142837934-af9a23b6-d05a-4918-9056-559af1edff27.png)

Being said that , what more information can i provide you so that we can identify the cause.

**Comment by mtwebster** [comment]
Are any items on your desktop image files? If so, try removing them temporarily to see if there's a difference.

Try deleting your thumbnail cache:

```
rm -rf ~/.cache/thumbnails
```

**Comment by blueray453** [comment]
> Try deleting your thumbnail cache:
>
> rm -rf ~/.cache/thumbnails

This actually seems to solve my problem. However, let me check for 2-3 days before I close the issue.

**Comment by blueray453** [comment]
@mtwebster issue fixed. Thank you very much.

**Comment by Jeremy7701** [comment]
Has the very high Cinnamon CPU usage also dropped?

**Comment by blueray453** [comment]
No, it is still there. These are new screenshots. After cleaning the cache.
![Screenshot from 2021-11-22 21-30-15](https://user-images.githubusercontent.com/855297/143071321-78d7c6f0-4e80-462f-a6b1-1faf9189e8f1.png)
![Screenshot from 2021-11-22 21-30-26](https://user-images.githubusercontent.com/855297/143071329-1d0c049d-26cf-4ce7-8cd5-461d5383badf.png)

**Comment by mtwebster** [comment]
Try removing applets (and desklets and extensions if you have any) one at a time, then restarting cinnamon to see if any of these components is causing the issue.

**Comment by blueray453** [comment]
I removed the applets I installed (does not have any desklets or extensions).

After that the cpu performance improved. But it still spikes above 150.
![Screenshot from 2021-11-23 23-58-33](https://user-images.githubusercontent.com/855297/143079466-5d232e26-933d-4555-89b5-f289e884e454.png)
![Screenshot from 2021-11-23 23-58-54](https://user-images.githubusercontent.com/855297/143079475-84fd1697-0d49-4ccf-9ee2-d8a3ea63146a.png)

**Comment by mtwebster** [comment]
Your nemo-desktop process is back to 100% also.  Did you ever try removing any images from the desktop folder temporarily?

If any problem files are showing up in recent files, that could potentially affect cinnamon as well. Try removing any stock applets that list files in some way (such as the main menu).

**Comment by blueray453** [comment]
Sorry, i did not understand 

> Did you ever try removing any images from the desktop folder temporarily?

**Comment by mtwebster** [comment]
If removing the thumbnail cache fixed the nemo-desktop issue (at least temporarily), it could indicate there's a file on your desktop that is giving the thumbnailer problems. This problem file could cause cinnamon to have similar problems.

Try removing all files from your desktop, temporarily, and restarting cinnamon and nemo-desktop.

**Comment by blueray453** [comment]
Last night I kept the PC running. Downloading some stuff in desktop.

Today morning , the issue reappeared

![Screenshot-2021-11-24-10:39:04](https://user-images.githubusercontent.com/855297/143176118-2f4781ba-370a-4403-9c07-d0a259912ead.png)

Then I ran `nemo-desktop -q` and the issue went away.

![Screenshot-2021-11-24-10:40:47](https://user-images.githubusercontent.com/855297/143176154-ab2e20a1-a418-4db9-a895-90a2a7ef3c1f.png)

Last time when I cleared the cache, it was 300MB+ . today I checked the cache size. It has total 108 files sized 3.2MB. So, I do not think this time the issue is caused by cache.



.

**Comment by Jeremy7701** [comment]
And yet you are still running one copy of nemo - using 1.3%.
Cinnamon on 50% is still a very high usage.

**Comment by blueray453** [comment]
This is the value I got after I used `nemo-desktop -q`.

There are two screenshots. One before running `nemo-desktop -q` , and one after running the command.

It remains stable for a while after running `nemo-desktop -q`.

I noticed that if I download multiple files in desktop using firefox then the usage of `nemo-desktop` become very high.

**Comment by mtwebster** [comment]
Can you paste the output of the following commands:
```
dconf dump /org/nemo/
```
and
```
dconf dump /org/cinnamon/
```

**Comment by blueray453** [comment]
Here, I am attaching the two dump files.

[cinnamon-dump.txt](https://github.com/linuxmint/nemo/files/7602445/cinnamon-dump.txt)
[nemo-dump.txt](https://github.com/linuxmint/nemo/files/7602447/nemo-dump.txt)
