### ISSUE TITLE
Mint no longer recognizing Android phone (worked previously)

### ISSUE THREAD

**Issue by ReaderGuy42** [linuxmint/nemo#2877]
```
 * Nemo version 5.0.5
 * Is issue with desktop or windowed nemo?
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used - (see inxi below)
 * 32 or 64 bit
 ```

**Issue**
I had been connecting my Huawei P Smart fine for the past few months since I started using Mint. Just today it started that the PC no longer recognizes my Huawei phone. I know the cable is working, i.e. transferring data since in "Devices" in Nemo the "HiSuite" thing shows up, which is Huawei's built-in Windows suite of accessing the phone, which I've never used (also this is the same cable that I've been using for months; I also checked with another cable but no change). Normally, so far, along with HiSuite the devices of the phone hard drive and the SD card would also show up. Now they don't.

I'm not sure what changed.

**Steps to reproduce**
plug in USB cable connected to smart phone (Huawei p smart ~2017/18)

**Expected behaviour**
connect phone drive and added micro SD card

**Other information**
here's my inxi info:
```

System:
  Kernel: 5.13.0-21-generic x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 5.0.7 info: kdocker wm: muffin 5.0.2 dm: LightDM 1.30.0 
  Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:
  Type: Laptop System: Acer product: Aspire A315-51 v: V1.14 
  serial: <filter> 
  Mobo: SKL model: Venusaur_KL v: V1.14 serial: <filter> UEFI: Insyde 
  v: 1.14 date: 10/31/2018 
Battery:
  ID-1: BAT1 charge: 5.4 Wh condition: 5.4/37.0 Wh (15%) volts: 8.6/7.7 
  model: PANASONIC AP16M5J type: Li-ion serial: <filter> status: Full 
CPU:
  Topology: Dual Core model: Intel Core i3-6006U bits: 64 type: MT MCP 
  arch: Skylake rev: 3 L2 cache: 3072 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 15999 
  Speed: 600 MHz min/max: 400/2000 MHz Core speeds (MHz): 1: 600 2: 600 
  3: 600 4: 600 
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] 
  vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:1916 
  Display: x11 server: X.Org 1.20.11 driver: modesetting 
  unloaded: fbdev,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.0.3 
  direct render: Yes 
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Acer Incorporated ALI 
  driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:9d70 
  Sound Server: ALSA v: k5.13.0-21-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: Acer Incorporated ALI driver: r8169 v: kernel port: 3000 
  bus ID: 02:00.1 chip ID: 10ec:8168 
  IF: enp2s0f1 state: down mac: <filter> 
  Device-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter 
  vendor: Lite-On driver: ath10k_pci v: kernel port: 3000 bus ID: 03:00.0 
  chip ID: 168c:0042 
  IF: wlp3s0 state: up mac: <filter> 
Drives:
  Local Storage: total: 931.51 GiB used: 494.47 GiB (53.1%) 
  ID-1: /dev/sda vendor: Western Digital model: WDS100T2B0A-00SM50 
  size: 931.51 GiB speed: 6.0 Gb/s serial: <filter> rev: 20WD temp: 25 C 
  scheme: GPT 
Partition:
  ID-1: / size: 915.40 GiB used: 494.46 GiB (54.0%) fs: ext4 dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 40.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
  1: deb https://typora.io/linux ./
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb http://mirror.funkfreundelandshut.de/linuxmint/packages uma main upstream import backport
  2: deb http://ftp.fau.de/ubuntu focal main restricted universe multiverse
  3: deb http://ftp.fau.de/ubuntu focal-updates main restricted universe multiverse
  4: deb http://ftp.fau.de/ubuntu focal-backports main restricted universe multiverse
  5: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
  6: deb http://archive.canonical.com/ubuntu/ focal partner
  Active apt repos in: /etc/apt/sources.list.d/protonvpn-stable.list 
  1: deb [signed-by=/usr/share/keyrings/protonvpn-stable-archive-keyring.gpg] https://repo.protonvpn.com/debian stable main
  Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list 
  1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
  Active apt repos in: /etc/apt/sources.list.d/smathot-cogscinl-focal.list 
  1: deb http://ppa.launchpad.net/smathot/cogscinl/ubuntu focal main
  Active apt repos in: /etc/apt/sources.list.d/syncthing.list 
  1: deb https://apt.syncthing.net/ syncthing stable
Info:
  Processes: 226 Uptime: 41m Memory: 7.65 GiB used: 2.65 GiB (34.7%) 
  Init: systemd v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Shell: bash 
  v: 5.0.17 running in: gnome-terminal inxi: 3.0.38

```

**Comment by Jeremy7701** [comment]
Did you update/install anything via all those non-mint repos or knowingly install anything via flatpaks [or other methods] recently?
Are you able to easily try a lower release of the kernel, instead of "Kernel: 5.13.0-21-generic"?
Why is your ProtonVPN from a Xenial [2016] repo? - a Ubuntu 2020 version is available.

Obviously none of these things may have caused your problem, but since you are running a non-standard Mint, why not try running a "live" version of Mint?

**Comment by ReaderGuy42** [comment]
I've been trying to get something working on a new Raspberry Pi system, so possibly. When I go into the Update Manager, it doesn't offer me to change to another kernel. It just asks if I want to remove it, e.g. the 5.4 one. I'd been using that one till a few weeks ago, when someone recommended trying to switch to a new one in order to try and see if that helps the system speed up a little, which I think it did. And I'm fairly certain that I've since been able to transfer things to my phone.

Regarding the ProtonVPN, I'm really still new to Linux in general so when I'm trying to install something I'm not always sure if what I'm doing is the right way. But so far I don't think I've broken anything irrevocably.
Thanks!

**Comment by Jeremy7701** [comment]
On your boot menu [GRUB] it is advised that you always keep the last 2 or 3 kernel versions.
So it should be possible to just select a previous kernel such as 5.4 (assuming this is a kernel problem, which actually seems unlikely). There's probably a video on the internet about how to do this, as sometimes the GRUB display is skipped.

Normally one wouldn't run with a later kernel, unless the current one can't provide a wanted feature. For kernels, later doesn't _necessarily_ mean better.

But try the live boot first.

**Comment by ReaderGuy42** [comment]
Yeah sorry, it seems to be a phone problem. I tried it on a Windows machine and the same thing happens, where the HiSuite appears but nothing else. I'll close this then. Thanks though!
