### ISSUE TITLE
[Feature Request] Show by default the 'Make Link' option in Nemo context menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/nemo#2883]
I helped a friend who was new to Linux install LM Cinnamon, and he being one of those users who works a lot with links on the desktop told me about the lack of this functionality by default when right clicking with Nemo (you have to activate it from the menu bar / edit / preferences / contextual menu  .... and add it as visible entrie). 
Checking I realized that it is an option that is by default in many desktop environments (MATE, Xfce, GNOME, Budgie, Pantheon, Aqua [OSX] or Explorer [Windows]). At the moment in Mint Cinnamon the fastest option to create links is using 'Ctl+M' or 'Ctl+Shift and drag'  _which for novice users may not be very intuitive_.  I suggest you consider adding the option to the context menu.

Best regards

**Comment by Jeremy7701** [comment]
As opposed to the current "Make Link" entry in the context menu?

**Comment by haggen88** [comment]
@Jeremy7701  I mean that the current "Make Link" entry in the context menu is not an option that appears by default.

**Comment by Jeremy7701** [comment]
I'd suggest that's because 'Make Links' is not selected to be shown in Preferences, Context menus by default?

**Comment by haggen88** [comment]
exactly

**Comment by IndubitablyLeft** [comment]
I'd like to add to this: Using Nemo, attempting to right click and drag a file/folder to a different window or the desktop simply triggers the normal context menu, as if you'd simply right clicked on the file itself. Windows makes use of this gesture to implement a context menu that prompts the user if they would like to move, copy, or make a link to the source file. It would be beneficial if Nemo implemented the same behavior.

**Comment by mikkovedru** [comment]
To help illustrate the point. The issue starter wants the following menu action to be available/enabled by default.
![image](https://user-images.githubusercontent.com/2521942/145022068-42d11717-2940-411c-a5c8-bf7cdd3cc8d2.png)

**Comment by dominichayesferen** [comment]
This was also a valid concern brought up by Luke in the LinusTechTips Linux Challenge.

**Comment by Jeremy7701** [comment]
I think that this is a perfectly decent default. It protects new users from feature overload.
How many people, especially those new to Linux, need a GUI to create symbolic links?
Indeed, new users probably don't even know what a symbolic link is.
More experienced users can just tick all the boxes.

However, the preferences portion that relates to "Icon view" and 'Arrange items' / 'Organise by Name' appears mysterious, since icons can be sorted in many ways - although the 'Arrange items' is greyed-out on my view menu/context menu [and I don't understand what it means anyway].

**Comment by mikkovedru** [comment]
@Jeremy7701 
>How many people, especially those new to Linux, need a GUI to create symbolic links?
>Indeed, new users probably don't even know what a symbolic link is.

Creating symbolic links (called `shortcuts`) is a basic functionality available in Windows to any user. Copy, move and create a shortcut - are 3 main/basic functions.

It would be weird to shield users from this basic (it's not like you can break anything with it) functionality they are used to.

**Comment by Jeremy7701** [comment]
When I used Windows (about 10 years ago) Windows shortcuts were just little files that sat on the Desktop.
Linux symbolic links are (mainly) used in a quite different way - and extensively in system files. You can damage a lot of things if you treat them as things of no consequence, to be renamed or deleted at will (excepting those you have created yourself).

**Comment by mikkovedru** [comment]
> When I used Windows (about 10 years ago) Windows shortcuts were just little files that sat on the Desktop.

This describes 90% of use cases in my Linux Mint I have been rocking since 2014. The rest (10%) is `~/Pictures/` and `~/Music/` being located on the different drive.


> Linux symbolic links are (mainly) used in a quite different way - and extensively in system files. You can damage a lot of things if you treat them as things of no consequence, to be renamed or deleted at will (excepting those you have created yourself).

The exact same logic applies in Windows as well: don't touch the files you have not created yourself and are not absolutely sure about. Users are not imbeciles, no need to treat them as such.

**Comment by Jeremy7701** [comment]
OK

**Comment by clefebvre** [comment]
I agree with @Jeremy7701 and I think he's said it all.. 

Aside from the keyboard shortcuts this feature is also discoverable via the Edit menu.
