### ISSUE TITLE
Drag and drop on Wayland with a file from recent:/// drops the url "recent:///<HEXADECIMAL>"

### ISSUE THREAD

**Issue by berbiche** [linuxmint/nemo#2890]
```
 * Nemo version: 5.2.0
 * Is issue with desktop or windowed nemo: windowed
 * Distribution: NixOS
 * Graphics hardware *and* driver used: AMD RX 5700XT, amdgpu
 * 32 or 64 bit: 64bit
 ```

**Issue**

Dragging a file from Nemo on Firefox from the `recent:///` folder will drop a file with a name like `recent:///<HEXADECIMAL>`.

I used a PDF file to do this operation and Firefox supports PDF files.
I was able to open said file with `Right click > Open with > Firefox`.

**Steps to reproduce**

1. Open the `recent:///` folder
2. Open Firefox
3. Drag a file from the `recent:///` folder on Firefox (preferably a file Firefox supports)
4. The file does not open

**Expected behaviour**

The correct file should open in Firefox when doing a drag-and-drop operation from the `recent:///` folder.

**Other information**

* Desktop environment: Sway 1.6.0 (Wayland)
* Firefox 95.0b3

Both Nemo and Firefox were running as Wayland applications.

**Comment by ToxicMushroom** [comment]
cannot reproduce on 121.0.1 and sway 1.8.1, is this still an issue ?

**Comment by berbiche** [comment]
Hi,

I no longer have a Linux setup with this configuration, so I can't comment whether the issue has been resolved.
I suggest closing the ticket.
