### ISSUE TITLE
Feauture Request: Implement Icon View Mode In Save Prompts/Dialogs

### ISSUE THREAD

**Issue by ShawnNogi** [linuxmint/nemo#2891]
* Nemo version: 5.0.5
 * Distribution: Linux Mint 20.2 Cinnamon

Feauture Request:
Add icon view mode via the save as dialog for pictures and videos similar to windows. Being able to get a quick glimpse of all thumbnails to ensure you aren't downloading a duplicate seems to be an essential missing feature of Nemo. Icon view mode does not appear to exist via any save dialog screens, no matter the source of save dialog.

I've attached for reference what having an icon view mode while saving looks like on WIndows. This view is also saved so you don't have to change to it every time you are saving. 

Windows Screenshot
![msedge_BK0WQ5iJTl](https://user-images.githubusercontent.com/39767738/145532815-bf3814de-15ca-4527-aee2-0f17d51ecf4a.png)

**Comment by ShawnNogi** [comment]
Also a side note; "CreateNew folder" seems to be mysteriously missing from the right click context menu on save prompts.

**Comment by Jeremy7701** [comment]
In an application "save as" dialog, to create a new sub-folder, just click the new folder icon:
![Screenshot from 2021-12-10 11-45-54](https://user-images.githubusercontent.com/52585119/145570337-2cca1b8a-8755-427b-a22a-8cf3c3376e1f.png)

If you want nemo to look like Windows explorer, the simplest way would be to run Windows explorer.
You must expect different file managers to be different.

**Comment by JosephMcc** [comment]
The save/open dialogs are provided by the application and the toolkit it uses. Gtk, Qt, etc. Nemo has nothing to do with those and we have no control over them.

**Comment by ShawnNogi** [comment]
> In an application "save as" dialog, to create a new sub-folder, just click the new folder icon: ![Screenshot from 2021-12-10 11-45-54](https://user-images.githubusercontent.com/52585119/145570337-2cca1b8a-8755-427b-a22a-8cf3c3376e1f.png)
> 
> edit: Actually you can create empty folders without bothering to save anything in them. /edit.
> 
> If you want nemo to look like Windows explorer, the simplest way would be to run Windows explorer. You must expect different file managers to be different.

@Jeremy7701 

I said right click context menu as in when you click the right click on your mouse. I'm aware of the new folder icon. It's not really that i want it to look like windows explorer. The right click to create folder exist in the nemo manager natively . It just seems like inconsistent GUI issues for a newbie but I suppose it's actually that every application developer needs to use a certain toolkit as Joseph said.
