### ISSUE TITLE
thumbnailer xcf

### ISSUE THREAD

**Issue by szedar14** [linuxmint/nemo#2894]
```
 * Nemo version (nemo --version) 5.0.5
 * Is issue with desktop or windowed nemo? Yes
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20.2
 * Graphics hardware *and* driver used: Graphics:
  Device-1: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] driver: nvidia 
  v: 470.86 
  Device-2: AMD Picasso driver: amdgpu v: kernel 
  Display: x11 server: X.Org 1.20.11 driver: amdgpu,ati,nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~120Hz 
  OpenGL: renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2 v: 4.6.0 NVIDIA 470.86
 * 64 bit
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**
When are you going to get thumbnail previews to work for xcf image files?

**Comment by Jeremy7701** [comment]
Are the thumbnailers part of `nemo` or part of some other project?
I ask because I'm trying to develop a usable thumbnailer for EPUB files...

**Comment by mtwebster** [comment]
Here's a bit of info: https://tecnocode.co.uk/2013/10/21/writing-a-gnome-thumbnailer/

Nemo (via libcinnamon-desktop) generates many image files internally (png,  etc...), any additional mimetypes are handled by separate programs, and they're defined in /usr/share/thumbnailers. This works more or less like nemo search helpers (I modeled the search helper definitions after how thumbnailers are handled, actually).

btw, .xcf files preview fine for me: 
![image](https://user-images.githubusercontent.com/262776/146190056-6e3adf11-3e11-44be-998d-ac030400982e.png)

**Comment by Jeremy7701** [comment]
There is a program - `xcf2png` in the Debian 10 package **xcftools** which might be used - but unfortunately it gives an error "Version 12 of SVG file not supported" - which appears to be the version used by Gimp 2.10.8 (not the most recent version).
See [https://moritzmolch.com/blog/1749.html](https://moritzmolch.com/blog/1749.html)

**Comment by mtwebster** [comment]
Flatpaks run in a sandbox ("virtual" filesystem), so it could be that it's either not generating thumbs, or they're unable to be saved in their normal location (~/.cache/thumbnails). Either way, there's not really anything we can do in Nemo. Maybe open a bug report for gimp: https://www.gimp.org/bugs/report.html.
