### ISSUE TITLE
Thumbnails don't generate

### ISSUE THREAD

**Issue by RDKRACZ** [linuxmint/nemo#2899]
```
 * Nemo version 4.6.5
 * Distribution - openSUSE Leap 15.3
 * Graphics hardware driver - Nvidia GTX 1070, proprietary, v470.86
 * 64 bit
 ```

**Issue**
![Screenshot_20211221_124404](https://user-images.githubusercontent.com/43277609/146936114-e17db1a1-6dec-4a7b-92c7-a9866385eddf.png)

**Comment by Jeremy7701** [comment]
Do you have a file called `/usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer` and do you have `ffmpegthumbnailer` installed?

**Comment by RDKRACZ** [comment]
>Also, you are a couple of Nemo releases behind current stable - although this is probably not the cause of the problem.

Sadly, this is the latest release available for openSUSE Leap. Tbh I switched to nemo from pcmanfm because it is 5 years behind the upstream...
Installing `ffmpegthumbnailer` fixed the issue. Maybe some information about the requirement of this package for thumbnails to work could be added somewhere in the Nemo's Preview settings?

**Comment by Jeremy7701** [comment]
This will only fix video thumbnails - if you are missing other thumbnailers then other programs may be needed, but note that not every type is presently catered for.
