### ISSUE TITLE
[Feature request] Automatic hiberfile removal

### ISSUE THREAD

**Issue by dtsund** [linuxmint/nemo#290]
Currently, when attempting to mount a hibernating Windows partition, Nemo returns an error window directing the user to either boot and shut down Windows, mount it read-only from the command line, or mount with the remove_hiberfile option, again from the command line.  A more user-friendly option would be to provide a similar warning, but give the window three buttons: "Cancel" to do nothing, "Mount read-only" to repeat the mount invocation with the -ro option, and "Mount, removing hiberfile" to repeat the mount invocation with -o remove_hiberfile.

**Comment by Topperfalkon** [comment]
This would be really useful. Either that, or an additional option to "Mount as...", which gives a window allowing the setting of mount options, including setting read-only or removing hiberfil

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
