### ISSUE TITLE
Feature Request - add a "create new folder" button

### ISSUE THREAD

**Issue by tlongfellow** [linuxmint/nemo#2903]
```
 * Nemo version (nemo --version)5.0.5
 * Is issue with desktop or windowed nemo?yes
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)Mint 20.2
 * Graphics hardware *and* driver used
 * 32 or 64 bit64
 ```

**Issue**
Not an issue, but a feature request. I do a lot of programming, and I make a lot of short tutorial videos, I am constantly creating, changing, and reorganizing files and folders, and it sure would be handy to have a "create folder" button on the tool bar. I am aware there is a keyboard short cut, but don't care for keyboard short cuts on the whole, as they are hard to remember and clumsy (for me) to use. Thank you for considering my request!

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Look in preferences/toolbar and select 'new folder'

**Comment by tlongfellow** [comment]
I don't know how I missed that in the preferences. Thank you!!
