### ISSUE TITLE
Nemo rename files bug

### ISSUE THREAD

**Issue by Dasdar990** [linuxmint/nemo#2914]
```
 * Nemo 5.2.4
 *Windowed Nemo
 * Mint 20.3
 * GTX 1050Ti 
 * 64 bit
 ```

**Issue**
When renaming a file this happens (watch the video)

**Steps to reproduce**
Open Nemo, use List View and press F2 to rename a file

https://user-images.githubusercontent.com/56268536/150772023-4a0ddfd7-de55-46f1-89fa-67862116056d.mp4

I don't know why once I submitted this bug but I was ignored. I also tried to reinstall nemo but it didn't fix it

**Comment by Jeremy7701** [comment]
This was submitted 10 minutes ago.
Have you been ignored for 10 minutes.
It would help if you filled out the template as it is not obvious what you are submitting as a bug.
What should it be doing in your video?

**Comment by Dasdar990** [comment]
No, I submitted almost a year ago but the issue was closed. In the video you can see that when you press F2 to rename the file, the original name you want to change should disappear when you start writing the new one. 
This is what happens 

https://user-images.githubusercontent.com/56268536/150775855-02b5f70f-a48c-497d-a42a-801465530b7d.mp4


This is what it does in Icon View (that should be the normal behaviour)


https://user-images.githubusercontent.com/56268536/150775596-18e10daf-799b-4d8f-982b-a23ac01f38fd.mp4

**Comment by Jeremy7701** [comment]
On Nemo 5.0.5 [I use LMDE, so I'm still waiting for the updates to catch up].
All I can say is (that for me) the correct behaviour occurs, with no overtyping in both icon & list views.

I have a Mint 20.3 in a VM - but I couldn't reproduce your bug there, either.
Unless this is a reproducible problem - for example have you tried the latest live Mint boot?
Then, I suspect your issue will get closed again.

**Comment by Dasdar990** [comment]
Thanks for the feedback, I'll try a live version to see if I can reproduce it.

**Comment by mtwebster** [comment]
What Gtk ("control") theme are you using? Try a different one possible.

Are you using nvidia drivers or native? Is this in a VM?

**Comment by Dasdar990** [comment]
> What Gtk ("control") theme are you using? Try a different one if possible.
> 
> Are you using nvidia drivers or native? Is this in a VM?

I am using Vimix dark doder, and thanks to your comment I realised that it is the cause of the issue. Is there any way I can fix this without changing theme?

**Comment by spont4e** [comment]
I have the same problem with renaming

**Comment by mujehoxe** [comment]
Experiencing the same with white-sur
