### ISSUE TITLE
Progress dialogs apparently have wrong window type (not "dialog")

### ISSUE THREAD

**Issue by SevenSystems** [linuxmint/nemo#2917]
```
 * Nemo version - 4.8.6
 * Is issue with desktop or windowed nemo? - windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) - Pop!_OS 21.10
 * Graphics hardware *and* driver used - irrelevant
 * 32 or 64 bit - irrelevant
 ```

**Issue**

nemo seems to set the wrong window type for its progress dialogs (for example, "10% Copying foo to bar"). This causes pop-shell (a tiling window manager GNOME extension) to try to tile progress dialogs from nemo, which results in visual disaster. I've reported this to the pop-shell maintainers, who directed me here because they think it's a nemo bug.

**Comment by SevenSystems** [comment]
Thanks, that was quick!

**Comment by mtwebster** [comment]
Sure, it was a simple fix.

I didn't actually test it with tiling, so please confirm it here when you try it.

Thanks
