### ISSUE TITLE
Open as root option doesn't work

### ISSUE THREAD

**Issue by RDKRACZ** [linuxmint/nemo#2929]
```
 * Nemo version (nemo --version) 5.2.0
 * Distribution Void Linux 64 bit with Cinnamon 5.2.7
 * Graphics hardware *and* driver used Intel GPU kernel driver
 ```

**Issue**
After entering the password in the polkit window I get `Could not parse arguments: Cannot open display:`

**Steps to reproduce**
Right-click on some empty space inside a folder, choose Open as root.

**Expected behaviour**
New nemo window should spawn with root privileges 

**Other information**
This is not related to my yesterday's issue which is on a different machine.

**Comment by mtwebster** [comment]
Is `DISPLAY` set in your environment? Is it in the root user's environment?

What happens if you:
```
DISPLAY=:0 nemo .
```
then try to open as root from that window.

Or:
```
DISPLAY=:0 pkexec nemo .
```

**Comment by RDKRACZ** [comment]
>Is DISPLAY set

```
$ echo $DISPLAY
:0
[k0rr@void ~]$ sudo su
Password: 
# echo $DISPLAY 
:0
```

For `DISPLAY=:0 nemo` it opens nemo but when I try to use _open as root_ and enter my password still nothing happens and the error is the same.

The second command:
```
DISPLAY=:0 pkexec nemo
Could not parse arguments: Cannot open display: 
```

It didn't open nemo at all.

**Comment by paorie** [comment]
Same for me. Have you solve it?

OS: Arch Linux x86_64
Kernel: 6.2.0-zen1-1-zen
DM: sddm
DE: Hyprland

**Comment by leigh123linux** [comment]
It's the default for wayland.

https://wiki.archlinux.org/title/Running_GUI_applications_as_root

It's broken by design.
