### ISSUE TITLE
Nemo-Actions unable to extend tokens

### ISSUE THREAD

**Issue by Prozium** [linuxmint/nemo#293]
I am having an issue to extend tokens, eg i want an action to run mplayer \* in the current directory, so the action looks like this Exec=mplayer %U\* - that won't work it will not start mplayer by passing the URL of the folder and add *

Try and see for yourselves Exec=notify-send mplayer %U*
This also applies to %F meaning %F\* wont work either

**Comment by Vahan86** [comment]
@Prozium, is this still an issue for you with Nemo 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
