### ISSUE TITLE
Feature request: Remove the peculiar file hiding facility [see below for details]

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#2932]
```
 * Nemo version 5.0.5
 * Is issue with windowed nemo?
 * Distribution - (LMDE4)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
The "feature" which allows non-hidden folder/file names to be stored in a text file named `.hidden` in order to cause them to behave as hidden folder/files  **should be removed**.

**Steps to reproduce**
Example:-

**Display hidden files**
Suppose a folder contains a the following files:-

![1](https://user-images.githubusercontent.com/52585119/154757271-f1945738-f66a-48e0-a42e-801b440f295c.png)

**.hidden** contains:-
![2](https://user-images.githubusercontent.com/52585119/154757568-0de671b5-a375-4802-8a4b-62619430266a.png)

Now suppose we choose to hide the display of hidden files:-

![3](https://user-images.githubusercontent.com/52585119/154758070-5c606087-0f5d-4e23-94b1-2f840ad61d1a.png)

Clearly, nemo uses the content of files called `.hidden` in a rather unusual way.

**Expected behaviour**

I would expect that choosing to hide the display of hidden files would look like this:-

![4](https://user-images.githubusercontent.com/52585119/154758946-e5968a10-5fff-44be-88ba-954885ee945a.png)

**Other information**

Treating the contents of a specially named data file to control the UI has got to be wrong.

**Comment by mtwebster** [comment]
The second nemo view looks  exactly as it should - A and bash.sh are in the .hidden file, so they're treated as hidden. What am I missing?

This is a pretty common feature I think, and I can think of situations where it might be handy (where maybe renaming is restricted, but you want files hidden).

**Comment by Jeremy7701** [comment]
I agree that the feature works, but should the behaviour of nemo depend on the contents of a datafile (even a specially named one)?

I agree that it could be a useful trick to hide certain files - but in the absence of extensive user documentation, it seems like a "hidden feature".
I had assumed this was some ancient feature that few people were aware of. -;)

**Comment by Jeremy7701** [comment]
I've closed this - apparently `nautilus` also thinks this is a good  idea.
