### ISSUE TITLE
[BUG] Nemo Desktop button in sidebar doesnt work if desktop folder is symlink to other location

### ISSUE THREAD

**Issue by BeatLink** [linuxmint/nemo#2935]
```
 * Nemo version 5.2.4
 * Is issue with desktop or windowed nemo: Windowed
 * Distribution - Mint 20.3
 * Graphics hardware *and* driver used Intel Corporation HD Graphics 620, default drivers
 * 32 or 64 bit: 64 Bit
 ```

**Issue**
If the Desktop Folder is a symlink pointing to another location, the Desktop option in the My Computer sidebar does nothing when clicked on. 

**Steps to reproduce**
1. Move the Desktop folder from your home folder
2.  Create a symlink to the move folder and place the symlink in the home folder. Name it Desktop
3. Notice in nemo that the Desktop option under My Computer in the sidebar does nothing when clicked

**Expected behaviour**
The Desktop option under My Computer in the sidebar should follow the symlink and open the folder the symlink is pointed to

**Other information**
Currently my personal files, including the Desktop folder are kept on a seperate drive in my system. Symlinks are in my home folder that link to these files and folders, the Desktop folder being one of them.

**Comment by okaestne** [comment]
Nemo should respect the `XDG_DESKTOP_DIR` path. Could you please try adding the following line to `~/.config/user-dirs.dirs`?

`XDG_DESKTOP_DIR="/YOUR_PATH_TO/Desktop"`

**Comment by smurphos** [comment]
> * Move the Desktop folder from your home folder
> * Create a symlink to the move folder and place the symlink in the home folder. Name it Desktop
> * Notice in nemo that the Desktop option under My Computer in the sidebar does nothing when clicked

> XDG_DESKTOP_DIR="/YOUR_PATH_TO/Desktop"

The initial moving of Desktop will break XDG_DESKTOP_DIR=
After creating the symlink it can then be recreated as the default =/home/$USER/Desktop

Issue can be avoided by replacing an empty Desktop folder with a Desktop symlink without moving or deleting the original folder.

**Comment by BeatLink** [comment]
> Nemo should respect the `XDG_DESKTOP_DIR` path. Could you please try adding the following line to `~/.config/user-dirs.dirs`?
> 
> `XDG_DESKTOP_DIR="/YOUR_PATH_TO/Desktop"`

This solution worked a treat! Thanks!
