### ISSUE TITLE
No thumbnails for windows share

### ISSUE THREAD

**Issue by Wallby** [linuxmint/nemo#2950]
```
 * Nemo version  5.2.4
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - LMDE 5, cinnamon 5.2.7
 * Graphics hardware *and* driver used doesn't seem applicable
 * 32 or 64 bit 64 bit
 ```

**Issue**
I added a windows share through nemo using _"file"_ -> _"connect to server..."_. This works, though no thumbnails show..
![Untitled](https://user-images.githubusercontent.com/13614975/160282768-45cd26fd-e937-4d7f-b8ef-661aad13d909.png)

**Other information**
In LMDE 4 in /usr/etc/fstab I put..
```
//maarten-pc.local/share/ 	/media/share 	cifs 	credentials=/media/share.smb,iocharset=utf8,vers=3.0,user,noauto,noperm,exec 0 0
```
.. which worked w. thumbnails too.

**Comment by Jeremy7701** [comment]
Presumably a **/etc/fstab** mount is considered to be a "local" file?
Although I have to say that I get thumbnails in USB connected devices such as Mobiles, Kobo's, USB sticks etc (in LMDE4).

**Comment by okaestne** [comment]
Did you check the thumbnail preferences in `Edit -> Preferences -> Preview`? Please check that "Show Thumbnails" is set to "Yes" and not to "Local Files Only"

**Comment by Wallby** [comment]
@okaestne That worked.

**Comment by okaestne** [comment]
Nice :+1: Feel free to close this issue
