### ISSUE TITLE
Incremental listing of populated directories in MTP.

### ISSUE THREAD

**Issue by HT-7** [linuxmint/nemo#2959]
* Nemo version (nemo --version): 3.6.4
 * Is issue with desktop or windowed nemo? Desktop.
 * Linux Mint 18.3 (LTS) 64-Bit

----
### Issue
Opening highly populated directories such as a download folder with thousands of files on an MTP device such as a smartphone sometimes causes it to hang up or show an error like "libmtp error: could not get object handles" or similar.

### Steps to reproduce
Open a folder which contains several thousands of files. This could be a download folder, camera folder, or screenshot folder.

### Expected behaviour
List files **while** the directory listing is being loaded, so if loading fails, the files are partially listed, which is more useful than nothing. Windows Explorer does this too.

Those listed files can be moved out to depopulate the directory, so next time the fewer remaining files can be listed completely.

### Other information
The handling of MTP on Nemo is mostly superior and more stable to that of Windows Explorer. Usually, directories with many files load faster (if they load successfully), it hangs up less frequently, many small files are transferred faster, and files moved away from the device are deleted individually rather than all at once after transfer, meaning in case of interruption, the MTP device (e. g. smartphone) has at least *some* free space rather than none, and no de-duplication of files is necessary, and when "preparing" to transfer files, it actually indicates how many files it has counted which signals the user that it did not hang up rather than nothing but a loading animation.

However, I have observed that Windows Explorer starts listing files of populated directories (such as a download folder) immediately after being opened, whereas Nemo only lists files after the directory listing finished to load.

If incremental loading is not possible due to limitations in `libmtp`, I will have to reach out to their developers. Perhaps they can help us.

**Comment by Jeremy7701** [comment]
A directory is a file (containing a list of directories and/or files).

**Comment by leigh123linux** [comment]
Linux Mint 18.3 isn't supported, you need to update.

https://endoflife.software/operating-systems/linux/linux-mint

If you can reproduce with nemo-5.2.x feel free to reopen.
