### ISSUE TITLE
After using the back-arrow GUI button to navigate from /etc to / (drive root) then pressing enter to re-open "etc", Nemo instead displays the contents of "Home"

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/nemo#2961]
```
 * tested using a fully-updated installation of LMDE5 as of 2022-04-04, though it occurs with stock LMDE5 as well as some version of Mint 20.3.

 ```

As described in the title...

1. in Nemo, click "File system" in the left-side bar

2. double-click on the "etc" folder

3. click the back-arrow GUI button in Nemo itself

4. with "etc" still highlighted, press the enter keyboard key

5. Nemo will now be displaying the contents of... "Home"?

Expected behavior is obviously be that it should be displaying the contents of the "etc" folder instead.

**Comment by NintendoManiac64** [comment]
Turns out that step 5 doesn't always display the contents of "Home", rather it instead just always displays the contents of whatever folder you were looking at before you clicked "File system" in the left-side bar.  So if you originally opened the trash and then clicked "File system", then step 5 will be displaying the contents of the trash.

Also, for step 3, if you instead click the up-arrow GUI button in Nemo itself, then the enter key as described in step 4 will not even work i.e. step 5 won't even occur and you'll still be looking at the "File system" despite "etc" clearly being highlighted and therefore the enter key should work... but it doesn't.

Lastly, Thunar installed on the very same installation of LMDE5 does not have any of these issues.

**Comment by Jeremy7701** [comment]
LMDE4 (nemo 5.0.5) also has these issues.

**Comment by mtwebster** [comment]
The navigation buttons are becoming the focus when you click them.

Navigate Home->Filesystem->etc
Click back - Home->Filesystem - back button focused
Hit enter - Home - back button again.

The "Up" button behaves differently because Filesystem is the root, it can't go 'up' anymore.

I can't reproduce this in 20.3, but I can in LMDE5. This must be some behavioral change in the toolkit (gtk) that has changed how focus works.

**Comment by NintendoManiac64** [comment]
Just for reference, the issue does not occur in Caja on LMDE5 either.
