### ISSUE TITLE
[UX Design Improvement Request] Modernize Sidebar Places

### ISSUE THREAD

**Issue by mahajanudit** [linuxmint/nemo#2974]
```
 * Nemo version (nemo --version) 5.2.4
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Ubuntu 22.04 LTS
 * Graphics hardware *and* driver used Intel Mesa
 * 32 or 64 bit 64bit
 ```

**Issue**
Sidebar places style looks a bit outdated compared to modern UX
Sidebar in "Places" mode instead of "tree" looks something like this: 
![Screenshot from 2022-04-28 15-25-18](https://user-images.githubusercontent.com/2698052/165858882-21f0acf1-a48f-4f6e-b481-71b8ba4914ac.png)

The arrows here beside "My Computer" and "Devices" and other categories look a bit outdated.
Also, since it's not a tree mode, I feel they should not even be visible until the user hovers over them. We can hide the arrows and give the categories a bit more modern look with spacing, like Mac 
![image](https://user-images.githubusercontent.com/2698052/165858374-c35b175a-ed19-4aeb-ae25-f42a12ac61f9.png)
Or even have icons for these categories to modernize the look a bit.

One more potential change I was thinking of showing the space filed bar beside the name in some way like in Mac instead of below the name. Below the name it kind of interferes with the name a bit and looks a tad out of place IMO. This can be somewhat seen in the screenshot above. It's fine with "Home" but if you look at "File System" it seems to be overlapping "y" a bit. That just looks a bit out of place. Something like a pie showing the usage beside the name might look a bit more professional.

**Steps to reproduce**
Just open nemo in Home and the sidebar in "places" mode.

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
Thanks for the feedback but some of the issues you are pointing out are simply down to your theme. The spacing, the text intersecting the level bar. Even the icons. The arrows are there for a reason because those are collapsible.

**Comment by mahajanudit** [comment]
@JosephMcc is having the pie chart instead of bar for disk usage also part of the theme? Do you happen to have any examples I can use? I would love to experiment with that style.
Also, is there a theming options where these arrows are only visible when I hover over them? I really like how in Windows these arrows are not shown until the mouse moves to the sidebar. This keeps the look very clean

**Comment by JosephMcc** [comment]
The pie chart isn't doable. That is part of nemo's code that would have to be rewritten. For the arrows, I think the only thing you could do is hide the arrows only when you aren't over them. I don't think you could make them show by hovering just anywhere in the sidebar.

**Comment by mahajanudit** [comment]
Got it thanks.
