### ISSUE TITLE
Nemo thumbnail / preview generation fails on samba share

### ISSUE THREAD

**Issue by pdev77** [linuxmint/nemo#2979]
```
 * Cinnamon version = Cinnamon 5.2.7
 * Distribution - Linux Mint 20.3 Una
 * Graphics hardware *and* driver used
 * 64 bit
(nemo:3703): Gtk-WARNING **: 22:12:38.206: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(nemo:3703): CinnamonDesktop-WARNING **: 22:13:06.253: Unable to create loader for mime type video/mp4: Unrecognised image file format

(nemo:3703): CinnamonDesktop-WARNING **: 22:13:06.254: Error creating thumbnail for smb://192.168.1.11/photos2022_rw/ToProcess/VID-20210224-WA0004-(2MB).mp4: Unrecognised image file format

 ```
**Issue**
Unable to generate thumbnails for ANY mp4 files on samba mount
Those same files can have thumbnails generated on local drive or when browsing the files via the /var/run/user/1000/gvfs/smb-share:server=192.168.1.11.. mount

**Steps to reproduce**
Launch nemo
Browse to "smb://192.168.1.11/photos2021_rw/"
mp4 files do not generate thumbs (setting for preview in nemo is "YES" and for files < 1GB
Video file in question is 6MB

Browse to /var/run/user/1000/gvfs/smb-share:server=192.168.1.11,share=photos2021_rw
Thumbs are generated

**Expected behaviour**
Thumbs are generated

**Other information**
Same behaviour replicated from 20.3 live USB image

**Comment by pdev77** [comment]
* VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06) / i915 . Kernel 5.

**Comment by vimes666** [comment]
I just handled a complaint about missing thumbnails when connecting to a phone on the linux mint forum.
I noticed the 'show-image-thumbnails' setting in the nemo preferences has been removed.
The default was 'local files only' which corresponds with the observed behaviour.
I supplied a work-around using the dconf-editor in the forum topic. Here is the topic: [](https://forums.linuxmint.com/viewtopic.php?f=49&t=388423)

**Comment by PS1Online** [comment]
The problem persists on Nemo 5.6.3 (latest version)

**Comment by trakout** [comment]
Also have this issue on `5.6.4`, but the following workaround works well and results in video thumbnails loading with Nemo:

Create a mount point:
```
sudo mkdir /media/<username>/<mount_name>
sudo chown <username>:<username> /media/<username>/<mount_name>
```

Mount with cifs-utils:
```
sudo mount -t cifs -o username=$USER,password=<smb password),uid=$USER,gid=$USER //<smb server>/<share> /media/<username>/<mount_name>
```

_Notes_
Unmounting requires sudo:
```
sudo umount /media/<username>/<mount_name>
```

If you run into an error while mounting that states 'Mounting cifs URL not implemented yet...', make sure that the smb protocol is not included in the mounting command:

```
...gid=$USER, smb://0.0.0.0/....   # incorrect
...gid=$USER, //0.0.0.0/....       # correct
```

Credit: folks at https://forums.linuxmint.com/viewtopic.php?t=367530

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/nemo/pull/3265
