### ISSUE TITLE
What is this feature? (Context-menu > Background > scripts)

### ISSUE THREAD

**Issue by bdh1993** [linuxmint/nemo#2980]
```
 * Nemo version : 5.0.3
 * Distribution - Mint 20.2
 * 64 bit
 ```

**Issue**

Checking or unchecking the checkbox does not find any features.

Message displayed when checking debug checkbox.
("chage_notify: /org/nemo/preferences/menu-config/background-menu-scripts")

I founded this summary on org.nemo.gschema.xml files.
("Show the background context menu's Scripts submenu.")

![image](https://user-images.githubusercontent.com/58254473/167067398-25cf2433-6cca-42d9-87bd-e7b3b6e526c7.png)

**Steps to reproduce**

nemo --debug
checking or unchecking scripts

background mouse right click
folder mouse right click
file mouse right click

**Expected behaviour**

It should be marked or missing like any other option.

**Comment by smurphos** [comment]
If you have placed executable files in ~/.local/share/nemo/scripts you get a Scripts sub-menu in your context menu. allowing you to launch those executables from the context menu. 

The executable get passed the current selection(s) as $@ and runs in an environment with some additional nemo specific environment variables available i.e it's one way to add personalised functionality to your context menu.

If no content in that folder the Scripts submenu is not displayed.

Visit ~/.local/share/nemo/scripts in Nemo and click on the more info banner to see the documentation.

```
#### Scripts

When executed from a local folder, scripts will be passed 
the selected file names. When executed from a remote folder
(e.g. a folder showing web or ftp content), scripts will
be passed no parameters.

In all cases, the following environment variables will be
set by Nemo, which the scripts may use:

- NEMO_SCRIPT_SELECTED_FILE_PATHS: newline-delimited paths for selected files (only if local)
- NEMO_SCRIPT_SELECTED_URIS: newline-delimited URIs for selected files
- NEMO_SCRIPT_CURRENT_URI: URI for current location
- NEMO_SCRIPT_WINDOW_GEOMETRY: position and size of current window
- NEMO_SCRIPT_NEXT_PANE_SELECTED_FILE_PATHS: newline-delimited paths for selected files in the inactive pane of a split-view window (only if local)
- NEMO_SCRIPT_NEXT_PANE_SELECTED_URIS: newline-delimited URIs for selected files in the inactive pane of a split-view window
- NEMO_SCRIPT_NEXT_PANE_CURRENT_URI: URI for current location in the inactive pane of a split-view window
```

Nemo also supports actions as a way to add personalised context menu entries - visit ~/.local/share/nemo/actions and click more info. These are more versatile - the major advantage being they are context aware and be set up to appear only when relevant to the selection.

**Comment by bdh1993** [comment]
It was a difficult situation because I couldn't find an explanation for this function.

Thank you for your help.

I found it!!!
