### ISSUE TITLE
Nemo Feature Request

### ISSUE THREAD

**Issue by agentl074** [linuxmint/nemo#2985]
I think it would be cool to allow an option to change icon type -- like Windows 10 -- to be able to click on an icon mode which changes the icon from a list to a picture type while opening files. 

Linux Mint 20.3 Cinnamon

**Comment by Jeremy7701** [comment]
I have never seen Windows 10.

Do you mean like this?
![Screenshot from 2022-05-15 16-53-57](https://user-images.githubusercontent.com/52585119/168481915-bd8c92ce-e0ed-49d0-951c-12d83b0bc638.png)

**Comment by agentl074** [comment]
Yes, but (if it is possible) allow these modes when opening/sending a file through an app. If it is not possible due to a restriction, thanks for the response :)

**Comment by Jeremy7701** [comment]
I wouldn't expect this to be generally useful or desirable.
A GUI application chooses its own layout for optimal layout and very few applications manipulate many multiple files simultaneously.

**Comment by agentl074** [comment]
This is from a Windows 10 machine 
![Windows10FileManagerIconList](https://user-images.githubusercontent.com/102109024/168494969-e2413180-95b2-41dd-b5ac-b0d95489fda7.jpg)

**Comment by Jeremy7701** [comment]
Yet another reason to avoid Windows.

**Comment by agentl074** [comment]
LOL yup... it's my last remaining Windows machine... everything else is Mint :)

**Comment by mindinsomnia** [comment]
As I understand it, you're requesting the ability to view files in thumbnail view while in the open files dialog window.

And yes that would be very helpful, right now when doing any kind of design work, not being able to see thumbnails means when picking an image to import into a design, one has to guess, try to work based off memory what the contents of the files are by name alone (difficult with dozens of photos for example) or go open a Nemo window, to see thumbnails in the folder, take note of the correct file's filename, then switch back to the open dialog window and find the file again.

**Comment by Jeremy7701** [comment]
Try using a proper photo/image management tool - such as `digiKam` - (for example).
It's a KDE tool.
