### ISSUE TITLE
While safing; Ctrl + L to show the path doesn't work

### ISSUE THREAD

**Issue by IT-Spezialist-des-Asozialen** [linuxmint/nemo#2993]
```
 * Nemo version 5.2.4
 * Is issue with desktop or windowed nemo? - desktop
 * Distribution - Mint 20.3
 * Intel Corporation HD Graphics 5500 
 * 64 bit
 ```

**Issue**
When I press Ctrl + L while I want to safe a file, the path is not show. The buttons are still shown.

Before pressing Ctrl + L:
![grafik](https://user-images.githubusercontent.com/89655752/170733376-7739fc2b-6e45-4bcf-ad62-d460bc7c38f9.png)

After pressing Ctrl + L:
![grafik](https://user-images.githubusercontent.com/89655752/170733433-0ff93467-a6f2-43aa-a857-95c31f5ce98d.png)

**Other information**
I ask a friend and he told me that I could type the path in the "Name:"-field.

**Comment by smurphos** [comment]
The save as dialog is not provided by Nemo - it's set by the toolkit (GTK,  QT etc) that the app you are saving from uses for its GUI. The GTK save as dialog doesn't allow switching between path-bar and location-bar.

**Comment by IT-Spezialist-des-Asozialen** [comment]
Ok, thanks, then I'll aks there.
