### ISSUE TITLE
Picture selection looks bad: the picture gets heavily darkened when selected...

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/nemo#2996]
```
 * Nemo version 5.2.4
 * Issue with both desktop and windowed Nemo 
 * LinuxMint Cinnamon 20.3
 * 64 bit
 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
           driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa 21.2.6
 ```

**Issue**
The pictures thumbnails get very dark when selected. Check this screenshot and compare the selected `Tulips (copy).jpg` versus the original.

![Nemo-picture-selection](https://user-images.githubusercontent.com/31940713/171179040-82800232-3cc0-4c03-a079-52a5e009383a.png)

**Steps to reproduce**

* Edit > Preferences > Preview > Show thumbnails
* View > Icon view
* Select some picture

**Expected behaviour**

I would expect my picture thumbnail to remain unchanged when selected, so i can still look at it and make sure i made a good choice. The selected state could be made visible otherwise, like getting a thick light background around the picture instead, take Windows 10 file selection for example:

![Windows10-iconview-select-1](https://user-images.githubusercontent.com/31940713/171182060-db9a702e-2028-42bf-afa5-085ffc843e7c.png)

(That's not a picture being selected there but this still illustrate my point about adding some border on selected items rather than just darkening them with a mix of accent color... Besides, it would be better to do it this way or some other way for all files, as explained further down...)

**Other information**

It also looks bad on every other icons, not just thumbnails, when i combine different colors for icons and controls. For example, when i set my controls to blue and my icons to yellow, the selected files are made of dark green, and this doesn't look good either:

![Nemo-file-selection](https://user-images.githubusercontent.com/31940713/171181198-01d13696-7618-4754-946e-1b4838e6bc59.png)

**Comment by SebastJava** [comment]
File selection also looks better in Elementary OS, IMHO:

![image](https://user-images.githubusercontent.com/31940713/171203577-5bc997f1-ac3b-4859-b679-318ea0954dee.png)

This way the icons and thumbnails remains unchanged, they just get a grey background around them instead, plus this little check mark (✔).

**Comment by Jeremy7701** [comment]
The "darkening" effect is an indication that you have selected an icon.
For a green icon theme (Mint-X-Dark):-

Unselected:
![Screenshot from 2022-05-31 16-16-39](https://user-images.githubusercontent.com/52585119/171209823-d3dc6f64-e06e-4c36-b51e-1b30ddecaf0b.png)

Selected:
![Screenshot from 2022-05-31 16-15-26a](https://user-images.githubusercontent.com/52585119/171209933-7dcbde25-88c0-479d-8a9b-1a8e5bdb95e5.png)

To see the true colours, try opening the image thumbnail as an image?

**Comment by SebastJava** [comment]
@Jeremy7701 

Of course, i know the "darkening" effect is an indication that i have selected an icon. And of course i could open the image to look at it again.

This is more a GUI issue. Or a design issue. I don't know how to call it.

To sum up, all i am saying is... Sometimes i take a quick look at a picture's thumbnail and i select it. But then i think about it again and look at the picture's thumbnail again because i am unsure but... once the picture is selected you can't really appreciate it anymore, just by looking at the thumbnail.

P.S.: This is bothering me so much that sometimes i find the quickest way to take a second peek at the picture is to deselect it for 2-3 secs and then re-select it again. Sure, this is not a real big bug, i am just saying it is not the most comfortable user experience. And i think i have seen much better ways to put an accent on selected files in Elementary OS or Pantheon, but i was unable to find this screenshot i saw a long time ago...

**Comment by mindinsomnia** [comment]
I have to agree, the visual effect is not the best, a box in the background of the file icon to show that it is selected would be preferable, to not interfere with the icon or thumbnail.

**Comment by Drugwash2** [comment]
Unfortunately (for me) Nemo is written in C and it's a lot of code so can't look through it any soon, if ever.

If I were the developer of Nemo I'd offer the user three _selection type_ options:
- **outline** [a reasonably thin border around the object]
- **background** [colored background behind the object - á la Windows style]
- **blended background** [blended colored background - as it is now]

All three would use the current theme's Accent color.
Each view type - icon, list, compact - would have its own _selection type_.

The _background_ option practically already exists as it is used in list view for the file and folder icons.

Considering the (unexplicable to me) minimalist style trend I wouldn't hold my breath for such choice to be implemented.

**Comment by Drugwash2** [comment]
Yeah, you practically combined options 1 and 2 (outline + background). I did think of it while building the option list above but thought it would be too much for the beginning. It is a valid option though, and it provides unequivocal feedback.
Now if only the devs would listen to the users... 🙄

**Comment by Drugwash2** [comment]
Oh I now about the Backgrounds panel, I even copied the shadow code and implemented it in **[Plymouth Manager](https://forums.linuxmint.com/viewtopic.php?p=2166341#p2166341)**.
However, that code is Python while Nemo is C so it wouldn't be so easily ported.  Hopefully not impossible though.
It's all up to the Nemo devs and how high a priority this issue would be deemed by them.

**Comment by mindinsomnia** [comment]
@SebastJava Great find, that is indeed more or less perfect.

**Comment by Drugwash2** [comment]
I don't think it's as simple as modifying the GTK theme. Just tried some of the installed themes and none changed the selection mode. But please feel free to try it yourself, one never knows.

**Comment by JosephMcc** [comment]
I'm treating this as a feature request since there really isn't a bug here. I agree it could probably look a little nicer. I'm not an expert on Nemo but taking a look, this seems like a good bit of work to change for what's relatively small gain. So I'm not sure it will get much priority. I will say that you aren't going to be able to change it with theming.

**Comment by SebastJava** [comment]
@JosephMcc 
> I agree it could probably look a little nicer.

It is not just about making things nicer. It is about making things nicer AND functional. That is my definition of design.

The photos are selected according to several criteria, including colors and contrasts. The problem here is that it is no longer possible to assess the quality of the photo once it has been selected. So, often, I deselect then reselect just to be sure of my choices... It is really awkward.

Ok, it's not a bug but... almost. Let's say it's some kind of GUI failure.

**Comment by Drugwash2** [comment]
You can always try Double Commander...

![Screenshot from 2022-07-07 22-46-12](https://user-images.githubusercontent.com/29117024/177859387-5d97016d-0311-4b8f-8f12-24632fa697df.png)
