### ISSUE TITLE
[Feature Removal Request] Delete & Move To Trash

### ISSUE THREAD

**Issue by mdhishamsayed** [linuxmint/nemo#2999]
```
 * Nemo version 5.2.4
 * Not An Issue
 * Distribution - Arch Linux
 * intel hd graphics 2000 *and* xf86-video-intel
 * 64 bit
 ```

**Issue**
well it is not an issue but i am actually confused why there are delete and move to trash buttons, if there is only move to trash button, then it would save some people because if one pressed delete instead of move to trash in a hurry, then that file would be unrecoverable, you would say that we have a dialog but when people are in a hurry then what will one do?
please take it as a feature removal request and not as a bug report

**Steps to reproduce**
in any context menu see two buttons, move to trash and delete

**Expected behaviour**
only move to trash should be seen

**Other information**
NOT A BUG

**Comment by leigh123linux** [comment]
Un-check the 'Include a delete command ..........'

![image](https://user-images.githubusercontent.com/1299302/172002200-b315ecae-5b42-48ee-b5ea-5e3e5b21657a.png)

**Comment by mtwebster** [comment]
This is all configurable (see previous post), and by default, safety-first: If you hit the delete key, it sends the file to trash (recoverable). If you right-click-Delete, *it pops up a confirmation dialog*. There are exceptions for sending files to the trash - if they're in a location that doesn't support it. In that case, it will let you know and also ask you to confirm it.
