### ISSUE TITLE
Nemo shows 107GB Instead of 100gb

### ISSUE THREAD

**Issue by mdhishamsayed** [linuxmint/nemo#3002]
```
 * Nemo version - 5.2.4
 * Is issue with desktop or windowed nemo? both
 * Distribution - Arch
 * Graphics hardware *and* driver used - Intel HD Graphics 2000 & xf86-video-intel
 * 64 bit
 ```

**Issue**
Nemo shows 100gb hard drive as 107 gb hard drive

**Steps to reproduce**
install arch linux with cinnamon and nemo,
create a 100gb hard disk partition
see the result in nemo

**Expected behaviour**
Nemo should show 100gb than 107GB

**Other information**
![Screenshot from 2022-06-13 10-23-27](https://user-images.githubusercontent.com/95240865/173282119-56985969-275c-403a-a876-6b62cdd26249.png)

**Comment by Jeremy7701** [comment]
This is **the** MB / MiB issue.
Is a kilobyte 1,000 bytes or 1024 bytes? (and similarly for MB, GB, TB etc).

You can set a preference for this in nemo (it calls the two choices decimal or binary).
You can also ask for sizes to be shown as the exact number of bytes, if you want.

**Comment by Jeremy7701** [comment]
See Edit -> Preferences -> Display; A default is supplied and it would appear to be the 1,000,000,000 bytes in a GB.
Gparted is using units of GiB.

If you buy a 1TB disk, you will find that you are only given 931 "honest" GB.
IMOH It's mostly a sales gimmick.

**Comment by mdhishamsayed** [comment]
@Jeremy7701 You are actually correct and it actually a sales gimmick
it uses 1000 not 1024 now

**Comment by auroraanna** [comment]
it is not a sales gimmick, kilo means 1000, not 1024 etc. so differenciating between Kibibyte, Kilobyte etc. is sensical. If you don't you, you will forever confuse if which of the two you actually mean.

**Comment by auroraanna** [comment]
> If you don't you, you will forever confuse if which of the two you actually mean.

this is why this shouldn't be hidden in a setting

**Comment by claudiux** [comment]
@auroraanna https://en.wikipedia.org/wiki/Binary_prefix

**Comment by leigh123linux** [comment]
@auroraanna  Take your pathetic argument elsewhere!
