### ISSUE TITLE
Directories beginning with a dot appear later than normal directories

### ISSUE THREAD

**Issue by carbongreat13** [linuxmint/nemo#3007]
```
 * Nemo version - 5.4.0
 * Is issue with desktop or windowed nemo? - windowed
 * Distribution - Arch Linux
 * Graphics hardware *and* driver used - Intel HD 4600/xf86-video-intel
 * 64 bit
 ```

**Issue**
If you select the list view and order the files by name, they will appear in the following order: uppercase, lowercase, dotfiles.

This is against \*nix tradition, so the order must be changed to dotfiles -> mixed case.

**Comment by JosephMcc** [comment]
Thanks for the suggestion bu there really is no "must change" here. Nemo has worked this way for as long as I can remember and changing it would probably just upset a bunch of users who are used to this behavior.
