### ISSUE TITLE
Allow renaming folders by right-clicking/F2 breadcrumbs.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo#301]

**Comment by icarter09** [comment]
@gauravjuvekar is this still an issue? Looks like it's working for F2, but not on right-click.

**Comment by gauravjuvekar** [comment]
@icarter09 No, it's not implemented. Given Linux Mint's new method of closing feature requests, I don't think this implementation will be tracked anymore on Github.

**Comment by icarter09** [comment]
@gauravjuvekar thanks for the update. I'll mark it as a feature request and will add it to the list of other feature requests for the Linux Mint team to look over.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
