### ISSUE TITLE
Moving files or folders by dragging never works - just creates a copy of the original in the target folder

### ISSUE THREAD

**Issue by ineuw** [linuxmint/nemo#3014]
```
 * Nemo version 5.2.4
 * Issue is with desktop and windowed nemo
 * Distribution - Mint 20.3
 * Graphics Intel Graphics native driver
 * 64 bit
```
**Issue**
Moving files or folders by dragging never works - just creates a copy of the original

**Steps to reproduce**
On the desktop, click on a file or folder and drag it to another folder to be moved. This only creates a copy of the object in the target folder. Dragging slowly moves the object 10% of the time. Same result when holding down the Ctrl key while dragging slowly. 

**Expected behaviour**
Move (not copy) the dragged object to the target folder.

**Comment by Jeremy7701** [comment]
It depends whether you are moving between filesystems or not.

Drag on file system to same filesystem = **move**
   Such as drag from `/home/user/Desktop` to `/home/user` = move

Between _different_ filesystems:-
Drag file = **copy**

To specify what happens more explicitly:-
Hold the shift key down and then drag = **move**
or
Hold the CTRL key down and then drag = **copy**
or
Hold the ALT key down and then drag will give you a prompt.

You might prefer CTRL-X or CTRL-C and CTRL-V at the destination (just like a text editor) to move/copy files and directories.

**Comment by ineuw** [comment]
@Jeremy7701, my appreciation for clearing this up, It probably explains why I have this problem with the process. The desktop folder into which the drag fails is a symlinked folder on the desktop. The source folder is part of folder structure that is shared with Windows through FreeFileSync and Google Drive. It is EXT4 format on Linux, but is NTFS on Windows.

I assume that if this is correct, there is no remedy, but use the keyboard method.
