### ISSUE TITLE
Missing file size in bytes, in file properties window

### ISSUE THREAD

**Issue by sblendorio** [linuxmint/nemo#3023]
```
 * Nemo version 5.2.4
 * Is issue with desktop or windowed nemo? desktop
 * Distribution - Mint 20.3
 * Graphics hardware *and* driver used: AMD Radeon Graphics, open source driver
 * 64 bit
 ```

When I ask for file properties, I get (for example) size in MB or in GB, but not in bytes
![image](https://user-images.githubusercontent.com/2118813/178794084-f244514a-b5bc-4d64-b015-d88fa4d98d55.png)

**Steps to reproduce**
Right click on filename, click on Properties

**Expected behaviour**
Expected also the file size in bytes (not ony in multiples, so MB or GB).

**Comment by Jeremy7701** [comment]
There is a setting for that.

In nemo, Edit -> Preferences -> Display.
Change File size to use one of the `long format` options.
