### ISSUE TITLE
Scaling for all icons

### ISSUE THREAD

**Issue by Jyusup** [linuxmint/nemo#3024]
```
 * Nemo version 5.2.4
 * desktop
 * LMDE 5
 * Don't know
 * 64 bit
 ```

**Issue**
Scaling for all icons? f.e. <- or ->. 

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by Jeremy7701** [comment]
If you want to set all icon sizes (generically):-

On your desktop, right-click in a blank area and choose "Customize".
You can change many things in the dialog box - such as icon size, grid spacing etc.

**Comment by Jyusup** [comment]
![Uploading IMG_20220716_202213_900.jpg…]()
Please tell me how can I change these icons? They are too small

**Comment by JosephMcc** [comment]
Closing this since there really isn't enough info and if you are talking about the desktop, it was answered.

@Jyusup your link just comes back to this issue.

**Comment by Jyusup** [comment]
> grid spacing

![image](https://user-images.githubusercontent.com/55563363/183894575-383646a8-0679-46b4-b650-cd9a4ace2c83.png)
it doesnt work. How can i make bigger these icons?

**Comment by Jyusup** [comment]
> Closing this since there really isn't enough info and if you are talking about the desktop, it was answered.
> 
> @Jyusup your link just comes back to this issue.

![image](https://user-images.githubusercontent.com/55563363/183894765-f3be4880-39c9-49c7-9d58-162e46baae87.png)
No, not answered. I cant make these bigger.
