### ISSUE TITLE
Preferences don't fit mobile phone screen but with scrollbars they likely easily would

### ISSUE THREAD

**Issue by ell1e** [linuxmint/nemo#3027]
```
 * Nemo version (nemo --version) **5.2.4**
 * Is issue with desktop or windowed nemo? **windowed**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) **postmarketOS 22.06 (for phones)**
 * Graphics hardware *and* driver used: **some mali embedded thing I think**
 * 32 or 64 bit: **64-bit**
 ```

**Issue**
Preferences don't fit mobile phone screen but with scrollbars they likely easily would:

![20220717_20h01m54s_grim](https://user-images.githubusercontent.com/64124388/179418981-4a93588c-3d24-41ac-addb-d9cc06d4673f.png)

**Steps to reproduce**

1. Install Phosh desktop on a PinePhone and start Nemo
2. Tap File > Preferences

**Expected behaviour**

Scrollbars exist to reach cut-off contents. Sadly right now there are none

**Other information**

**Comment by JosephMcc** [comment]
On the desktop that window does have scrollbars. Beyond that, developing for small screen form factors like phones or tablets is outside of scope for us. Our focus is solely on development for the desktop.

**Comment by ell1e** [comment]
Is it intentional then that the scrollbars somehow disappear in this scenario? Phosh is basically just a fairly standard GNOME 3 stack with wlroots compositor, so that seems fascinating.

For what it's worth, nemo in overall is rather usable with a mobile form factor, so maybe it'd be less work than you think to make that work. (Could also easily on a best-effort basis for an otherwise not officially condoned use.)
