### ISSUE TITLE
nemo-share and nemo-image-converter missing in repositories

### ISSUE THREAD

**Issue by LAfricain** [linuxmint/nemo#3029]
```
 * Nemo version: 5.2.4
 * Distribution: Ubuntu Unity 22.04
 * 64 bit
 ```

**Issue**
I'm looking of packages called nemo-share and nemo-image-converter in Ubuntu-softwaare or with apt, I can't find it.

**Expected behaviour**
For a full migration from nautilus this two packages are very useful.

**Other information**

**Comment by Fantu** [comment]
major of nemo extensions are not packaged in debian and derivate as I not have enough time to improve debian packaging for debian upload and maintain it, @ItzSwirlz  started working on some but seems that recently don't have enough time also him.

**Comment by LAfricain** [comment]
Hi guys, Thank you for your answers. @ItzSwirlz where can I complain to you? I'll see in the backports.
