### ISSUE TITLE
Question - Could we deprecate the EscapeSpaces field in Actions?

### ISSUE THREAD

**Issue by veractor** [linuxmint/nemo#3059]
This came up when I was writing #3057. As of [this commit](https://github.com/linuxmint/nemo/commit/b83bd6059e52f2067e60c80adc842beacc6a542f), including `Quote=double` or `Quote=single` in a Nemo Action file will guarantee that all file paths will be passed on correctly for that action. If those lines are not included, then including `EscapeSpaces=true` will also do the same.

So why not also escape spaces too when the `Quote` field is not `double` or `single`? This would eliminate all the possibilities where file paths would be passed on unescaped, and lets the user even omit the `Quote` field if they wanted. Then, the `EscapeSpaces` field would be obsoleted, since it is no longer required for correctly passing on file paths, and could then be made to do nothing.

I believe that this has minimal effect to existing behaviour, and will not break existing actions. Most Nemo Action files I have seen either has `Quote=double` or `EscapeSpaces=true`, and those will behave exactly the same after the change. The only change in behaviour is when both of them are set, where even spaces in quotes were escaped, and is likely not the desired behaviour.

**Comment by mtwebster** [comment]
I'm ok with this

**Comment by veractor** [comment]
Thank you!
