### ISSUE TITLE
[Feature Request] Reassign shortcuts && new command for open in new tab

### ISSUE THREAD

**Issue by proft** [linuxmint/nemo#306]
Hi!

Please add this small enhancement:
1. Reassign shortcuts for actions, especially for _rename_. Now it is assign to `F2`, but I use it for other action.
2. Sometimes I want to open new folder in current Nemo from terminal. Something like this `nemo --new-tab ~/Video`.

Thanks!

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by proft** [comment]
Yup, we can!

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
