### ISSUE TITLE
Feature Request: Sort by capital filenames first

### ISSUE THREAD

**Issue by matthewelmer** [linuxmint/nemo#3075]
```
 * Nemo version 5.4.3
 * Distribution - Mint 21 Cinnamon
 * 64 bit
 ```

It would be nice to sort capital filenames first, aka enable the option of LC_COLLATE=C just for nemo instead of forcing the user to enable LC_COLLATE=C globally on their system. I'm extremely surprised that this isn't an option--GNU Make assumes this behavior in its guide: https://www.gnu.org/software/make/manual/make.html#Makefile-Names

I guess this file manager isn't meant for developers, but it would be really nice to have the option for those of use that do write code!

**Comment by mtwebster** [comment]
Just create a launcher that runs:
```
sh -c "LC_COLLATE=C nemo"
```
This will work for pretty much any program.

This is pretty niche and for nearly all users it's more appropriate to sort based on their locale.  Many (most?) popular code editors - even minimalist ones - include some sort of file manager view or tree as well, so having the option in nemo probably isn't necessary.

**Comment by matthewelmer** [comment]
Fair enough. Thanks for the help!
