### ISSUE TITLE
How to know selected files count in shell script

### ISSUE THREAD

**Issue by lalamax3d** [linuxmint/nemo#3076]
1- apologies in adv, its not issue(bug) its just a question i am stuck with.

in a shell script, i can iterate files (selected) very nice via code below. how to know array length of selfiles. 
any ideas will help, huge thanks again.

```
selFile=$NEMO_SCRIPT_SELECTED_FILE_PATHS
# Q. i wanted to know the count of selFile here.
for i in $selFile
do
	#echo file is :: $i >> $log
done
```

**Comment by Jeremy7701** [comment]
One way is to convert `selfile` into an array, then count the array elements.
e.g.
```
selfile=$NEMO_SCRIPT_SELECTED_FILE_PATHS
words=( $selfile )  # convert to array
echo ${#words[@]}  # output the number of elements in the words array.
### words[0] contains the first entry etc...
```
