### ISSUE TITLE
Search in original window receives search results from duplicate window

### ISSUE THREAD

**Issue by JackNWhite** [linuxmint/nemo#3102]
```
 * nemo 5.2.4
 * Windowed
 * Mint Cinnamon 20.3
 * Quadro T2000 / NVIDIA driver 470.141.03-0ubuntu0.20.04.1
 * 64 bit
 ```

**Issue**
When a Nemo window containing an active search is duplicated (with New Window), the duplicate results box is empty, but results found in that window later also appear in the original window's results.

**Steps to reproduce**
1. Open a new Nemo window
2. Open search with Ctrl+F
3. Search for some known files
4. Open a new Nemo window with Ctrl+N
5. Search for some other files with a overlap with the first lot of files (for example, I was searching originally for duplicate files tagged with my host name, so I searched in step 3 for "hostname" and then in the second window for "filename1.ext", where the original search returned "filename_hostname.ext"

_filename_hostname.ext_ will appear both in the search results where you searched for it, and in the original results.

**Expected behaviour**
The new result should only appear in the new search window.

![demo01](https://user-images.githubusercontent.com/10062543/197771299-4dd14955-473f-4311-886a-c4a07a92d9dc.png)
![demo02](https://user-images.githubusercontent.com/10062543/197771321-c1371d2d-e745-4e7c-b3ad-f01efa746348.png)
![demo03](https://user-images.githubusercontent.com/10062543/197771335-73c3ab7e-5cb3-45eb-8792-b6ea11bf474d.png)
![demo04](https://user-images.githubusercontent.com/10062543/197771349-d9c7fff9-bb54-48c5-b8df-ce43efb9e9bf.png)

**Comment by mtwebster** [comment]
Duplicate, this is fixed in 5.4:

ref: https://github.com/linuxmint/nemo/issues/2941
