### ISSUE TITLE
Nemo crashes with: CRITICAL: nemo_directory_file_monitor_add: assertion 'NEMO_IS_DIRECTORY (directory)' failed

### ISSUE THREAD

**Issue by astier** [linuxmint/nemo#3115]
```
 * nemo 5.4.3
 * I start nemo from within cinnamon.
 * Arch
 * Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]
 * 64 bit
 ```

**Issue**

Nemo crashes even before the window opens. The output is:

```
** (nemo:10804): WARNING **: 18:50:38.735: Current gtk theme is not known to have nemo support (Adwaita-dark) - checking...

** (nemo:10804): WARNING **: 18:50:38.788: The theme appears to have no nemo support.  Adding some...

** (nemo:10804): CRITICAL **: 18:50:39.078: nemo_directory_file_monitor_add: assertion 'NEMO_IS_DIRECTORY (directory)' failed

(nemo:10804): GLib-GObject-WARNING **: 18:50:39.078: invalid (NULL) pointer instance

(nemo:10804): GLib-GObject-CRITICAL **: 18:50:39.078: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nemo:10804): GLib-GObject-WARNING **: 18:50:39.078: invalid (NULL) pointer instance

(nemo:10804): GLib-GObject-CRITICAL **: 18:50:39.078: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Steps to reproduce**

Start nemo in terminal.

**Expected behavior**

Nemo should open.

**Comment by mtwebster** [comment]
Can you provide coredump info?

**Comment by astier** [comment]
[core.nemo.1000.6582f2b1dfe44cc2819585976b92b878.30396.1668393071000000.gz](https://github.com/linuxmint/nemo/files/9999080/core.nemo.1000.6582f2b1dfe44cc2819585976b92b878.30396.1668393071000000.gz)

**Comment by astier** [comment]
I actually have this problem for at least 1-2 years. Maybe longer. Even on fresh arch installs. One day nemo just stopped working and I have no idea why.

**Comment by astier** [comment]
Some other user said in some xfce-thunar-issue also that he couldn't open nemo. While this issue wasn't about nemo and it was never further discussed I want to mention this here just for documentation porpuses.
https://gitlab.xfce.org/xfce/thunar/-/issues/353

Also @mtwebster could you give me a hint what `nemo_directory_file_monitor_add: assertion 'NEMO_IS_DIRECTORY (directory)' failed` means? What is `nemo_directory_file_monitor_add` trying to do? And what does  `NEMO_IS_DIRECTORY` mean?

**Comment by astier** [comment]
I also would like to mention that it also doesn't work when I try to open nemo while running the cinnamon-desktop-environment (v5.6.8) or gnome on arch linux. It does open on a pure Linux-Mint install.

**Comment by astier** [comment]
I dont know why but nemo works now.
