### ISSUE TITLE
[Feature Request] Make desktop able to show hidden files

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#312]

**Comment by Vahan86** [comment]
Still an issue in Cinnamon 3.0.7 (Nemo 3.0.6).

**Comment by gustavklopp** [comment]
Cinnamon 3.4.6 and still an issue (Nemo 3.4.7)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
