### ISSUE TITLE
Option to not search links

### ISSUE THREAD

**Issue by wallart1** [linuxmint/nemo#3128]
```
 * Nemo version (nemo --version) 5.2.4
 * Is issue with desktop or windowed nemo? Yes
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20.3
 * Graphics hardware *and* driver used - See SystemInfo.zip, attached
 * 32 or 64 bit
 ```

**Issue**
Every time I search my home directory with Nemo, it also searches a link to an NFS mount.

**Steps to reproduce**
Mount an NFS export to a system mountpoint, like /NFS1.
Put a link to that mount point on your Cinnamon desktop.
Use Nemo to search your /home directory.

**Expected behaviour**
An option to tell Nemo not to follow links when searching.

**Other information**
[SystemInfo.zip](https://github.com/linuxmint/nemo/files/10125755/SystemInfo.zip)

**Comment by mtwebster** [comment]
As a temporary workaround, you can add any location to a 'skip' list, using dconf-editor (it's not an exposed setting at the moment):
![image](https://github.com/linuxmint/nemo/assets/262776/caeb575e-d93b-4717-9f9c-568b9e76e24a)

**Comment by wallart1** [comment]
Thank you very much. That will do nicely.
