### ISSUE TITLE
segmentation fault when rename audio files file twice

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#313]
This happens on ubuntu raring x64 and nemo 1.8.1

The first rename works fine. When trying to rename the same file a second time, nemo crashes with segmentation fault, at the moment when i select Rename from the file context menu. It happens on every attempt. 

Her is the backtrace;  
daniel@schleppi:~/workspace$ gdb nemo
GNU gdb (GDB) 7.5.91.20130417-cvs-ubuntu
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /usr/bin/nemo...Reading symbols from /usr/lib/debug/usr/bin/nemo...done.
done.
(gdb) set height 0
(gdb) run
Starting program: /usr/bin/nemo 
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec478700 (LWP 21767)]
[New Thread 0x7fffebc77700 (LWP 21768)]
[New Thread 0x7fffea1fe700 (LWP 21769)]

(nemo:21763): Nemo-Python-WARNING **: g_module_open libpython failed: /usr/lib/libpython2.7.so.1.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
ImportError: could not import gobject (error was: '/usr/lib/x86_64-linux-gnu/libpyglib-gi-2.0-python2.7.so.0: undefined symbol: _Py_ZeroStruct')

(nemo:21763): Nemo-Python-WARNING **: pygobject initialization failed

(nemo:21763): Nemo-Python-WARNING **: nemo_python_init_python failed
[New Thread 0x7fffe97f9700 (LWP 21770)]
[New Thread 0x7fffd9182700 (LWP 21772)]
[New Thread 0x7fffce27b700 (LWP 21773)]
[New Thread 0x7fffcd5c7700 (LWP 21775)]
[Thread 0x7fffcd5c7700 (LWP 21775) exited]
[Thread 0x7fffd9182700 (LWP 21772) exited]
[Thread 0x7fffce27b700 (LWP 21773) exited]
[New Thread 0x7fffce27b700 (LWP 21778)]
[New Thread 0x7fffd9182700 (LWP 21779)]
[Thread 0x7fffea1fe700 (LWP 21769) exited]
[Thread 0x7fffd9182700 (LWP 21779) exited]
[New Thread 0x7fffd9182700 (LWP 21784)]
[Thread 0x7fffce27b700 (LWP 21778) exited]

(nemo:21763): GLib-GObject-WARNING **: invalid cast from `GtkImageAccessible' to`GtkIMContext'

(nemo:21763): GLib-GObject-WARNING **: invalid cast from `GtkImageAccessible' to`MeegoIMContext'

(nemo:21763): GLib-GObject-WARNING **: invalid cast from `GtkImageAccessible' to`MeegoIMContext'

(nemo:21763): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.36.0/./gobject/gsignal.c:3429: signal name `preedit-changed' is invalid for instance`0xe0f810' of type `GtkImageAccessible'

(nemo:21763): GLib-GObject-WARNING *_: /build/buildd/glib2.0-2.36.0/./gobject/gsignal.c:3429: signal name `commit' is invalid for instance`0xe0f810' of type `GtkImageAccessible'
*_\* Error in `/usr/bin/nemo': free(): invalid pointer: 0x0000000000e0f870 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x80a46)[0x7ffff42eea46]
/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so(+0x3e3c)[0x7fffd877ee3c]
/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so(+0x3e91)[0x7fffd877ee91]
/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so(+0x3f32)[0x7fffd877ef32]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x128350)[0x7ffff7209350]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18f49c)[0x7ffff727049c]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xce)[0x7ffff53cd55e]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x21af8)[0x7ffff53deaf8]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xb06)[0x7ffff53e6996]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82)[0x7ffff53e6f92]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2be77e)[0x7ffff739f77e]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_send_focus_change+0xd3)[0x7ffff73ad583]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2cf81f)[0x7ffff73b081f]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2db3b1)[0x7ffff73bc3b1]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2db95a)[0x7ffff73bc95a]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18f49c)[0x7ffff727049c]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x190)[0x7ffff53cd620]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x21af8)[0x7ffff53deaf8]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xb06)[0x7ffff53e6996]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x82)[0x7ffff53e6f92]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2be77e)[0x7ffff739f77e]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x60e)[0x7ffff72702ae]
/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x4c5e2)[0x7ffff6e9f5e2]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x135)[0x7ffff5109f05]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49248)[0x7ffff510a248]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34)[0x7ffff510a304]
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1bc)[0x7ffff56aa52c]
/usr/bin/nemo[0x42c199]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7ffff428fea5]
/usr/bin/nemo[0x42c1e5]
======= Memory map: ========
00400000-00570000 r-xp 00000000 08:05 1853786                            /usr/bin/nemo
00770000-00771000 r--p 00170000 08:05 1853786                            /usr/bin/nemo
00771000-00776000 rw-p 00171000 08:05 1853786                            /usr/bin/nemo
00776000-011e5000 rw-p 00000000 00:00 0                                  [heap]
7fffc0000000-7fffc0022000 rw-p 00000000 00:00 0 
7fffc0022000-7fffc4000000 ---p 00000000 00:00 0 
7fffc4000000-7fffc402e000 rw-p 00000000 00:00 0 
7fffc402e000-7fffc8000000 ---p 00000000 00:00 0 
7fffc8000000-7fffc8029000 rw-p 00000000 00:00 0 
7fffc8029000-7fffcc000000 ---p 00000000 00:00 0 
7fffccc16000-7fffccd17000 rw-p 00000000 00:00 0 
7fffccd17000-7fffccdc7000 r--p 00000000 08:05 266592                     /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
7fffccdc7000-7fffccdc8000 ---p 00000000 00:00 0 
7fffccdc8000-7fffcd5f9000 rw-p 00000000 00:00 0 
7fffcd5f9000-7fffcd9f9000 rw-s 00000000 00:04 11206674                   /SYSV00000000 (deleted)
7fffcda3a000-7fffcda7b000 rw-p 00000000 00:00 0 
7fffcda7b000-7fffcda7c000 ---p 00000000 00:00 0 
7fffcda7c000-7fffce27c000 rw-p 00000000 00:00 0 
7fffce27c000-7fffce29d000 r-xp 00000000 08:05 1314706                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fffce29d000-7fffce49c000 ---p 00021000 08:05 1314706                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fffce49c000-7fffce49d000 r--p 00020000 08:05 1314706                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fffce49d000-7fffce49e000 rw-p 00021000 08:05 1314706                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fffce49e000-7fffce5f6000 r-xp 00000000 08:05 1848689                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.0
7fffce5f6000-7fffce7f6000 ---p 00158000 08:05 1848689                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.0
7fffce7f6000-7fffce7fe000 r--p 00158000 08:05 1848689                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.0
7fffce7fe000-7fffce800000 rw-p 00160000 08:05 1848689                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.0
7fffce800000-7fffce801000 rw-p 00000000 00:00 0 
7fffce801000-7fffce838000 r-xp 00000000 08:05 1843680                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffce838000-7fffcea37000 ---p 00037000 08:05 1843680                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffcea37000-7fffcea3a000 r--p 00036000 08:05 1843680                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffcea3a000-7fffcea3b000 rw-p 00039000 08:05 1843680                    /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7fffcea3b000-7fffcea6f000 r-xp 00000000 08:05 1844233                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.36.4
7fffcea6f000-7fffcec6e000 ---p 00034000 08:05 1844233                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.36.4
7fffcec6e000-7fffcec6f000 r--p 00033000 08:05 1844233                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.36.4
7fffcec6f000-7fffcec70000 rw-p 00034000 08:05 1844233                    /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.36.4
7fffcec70000-7fffcec72000 r-xp 00000000 08:05 2099102                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffcec72000-7fffcee71000 ---p 00002000 08:05 2099102                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffcee71000-7fffcee72000 r--p 00001000 08:05 2099102                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffcee72000-7fffcee73000 rw-p 00002000 08:05 2099102                    /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7fffcee73000-7fffcee98000 r-xp 00000000 08:05 1843704                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.2.2
7fffcee98000-7fffcf098000 ---p 00025000 08:05 1843704                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.2.2
7fffcf098000-7fffcf099000 r--p 00025000 08:05 1843704                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.2.2
7fffcf099000-7fffcf09a000 rw-p 00026000 08:05 1843704                    /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.2.2
7fffcf09a000-7fffd4000000 r--p 00000000 08:05 14689                      /usr/share/icons/gnome/icon-theme.cache
7fffd4000000-7fffd4021000 rw-p 00000000 00:00 0 
7fffd4021000-7fffd8000000 ---p 00000000 00:00 0 
7fffd800a000-7fffd8011000 r--p 00000000 08:05 148871                     /usr/share/locale-langpack/de/LC_MESSAGES/file-roller.mo
7fffd8011000-7fffd8026000 r--p 00000000 08:05 148900                     /usr/share/locale-langpack/de/LC_MESSAGES/rhythmbox.mo
7fffd8026000-7fffd8078000 r--p 00000000 08:05 266618                     /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf
7fffd8078000-7fffd8342000 r-xp 00000000 08:05 1843464                    /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.4
7fffd8342000-7fffd8542000 ---p 002ca000 08:05 1843464                    /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.4
7fffd8542000-7fffd854d000 r--p 002ca000 08:05 1843464                    /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.4
7fffd854d000-7fffd854e000 rw-p 002d5000 08:05 1843464                    /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.4
7fffd854e000-7fffd854f000 rw-p 00000000 00:00 0 
7fffd854f000-7fffd8561000 r-xp 00000000 08:05 1854253                    /usr/lib/libmaliit-glib.so.0.94.2
7fffd8561000-7fffd8760000 ---p 00012000 08:05 1854253                    /usr/lib/libmaliit-glib.so.0.94.2
7fffd8760000-7fffd8761000 r--p 00011000 08:05 1854253                    /usr/lib/libmaliit-glib.so.0.94.2
7fffd8761000-7fffd8762000 rw-p 00012000 08:05 1854253                    /usr/lib/libmaliit-glib.so.0.94.2
7fffd8765000-7fffd8766000 rw-p 00000000 00:00 0 
7fffd8766000-7fffd8771000 r--p 00000000 08:05 148809                     /usr/share/locale-langpack/de/LC_MESSAGES/totem.mo
7fffd8771000-7fffd8772000 r--p 00000000 08:05 148866                     /usr/share/locale-langpack/de/LC_MESSAGES/libdbusmenu.mo
7fffd8772000-7fffd877a000 r--s 00000000 08:05 670062                     /home/daniel/.local/share/gvfs-metadata/root-53e778cf.log
7fffd877a000-7fffd877b000 r--s 00000000 08:05 670058                     /home/daniel/.local/share/gvfs-metadata/root
7fffd877b000-7fffd8781000 r-xp 00000000 08:05 2112155                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
7fffd8781000-7fffd8980000 ---p 00006000 08:05 2112155                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
7fffd8980000-7fffd8981000 r--p 00005000 08:05 2112155                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
7fffd8981000-7fffd8982000 rw-p 00006000 08:05 2112155                    /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
7fffd8982000-7fffd8983000 ---p 00000000 00:00 0 
7fffd8983000-7fffd9183000 rw-p 00000000 00:00 0                          [stack:21784]
7fffd9183000-7fffd91d5000 r--p 00000000 08:05 266594                     /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
7fffd91d5000-7fffd922c000 r--p 00000000 08:05 266625                     /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf
7fffd922c000-7fffd922f000 r-xp 00000000 08:05 2099601                    /usr/lib/x86_64-linux-gnu/pango/1.8.0/modules/pango-basic-fc.so
7fffd922f000-7fffd942e000 ---p 00003000 08:05 2099601                    /usr/lib/x86_64-linux-gnu/pango/1.8.0/modules/pango-basic-fc.so
7fffd942e000-7fffd942f000 r--p 00002000 08:05 2099601                    /usr/lib/x86_64-linux-gnu/pango/1.8.0/modules/pango-basic-fc.so
7fffd942f000-7fffd9430000 rw-p 00003000 08:05 2099601                    /usr/lib/x86_64-linux-gnu/pango/1.8.0/modules/pango-basic-fc.so
7fffd9430000-7fffd9431000 r--s 00000000 08:05 920910                     /var/cache/fontconfig/c05880de57d1f5e948fdfacc138775d9-le64.cache-3
7fffd9431000-7fffd943a000 r--s 00000000 08:05 920902                     /var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3
7fffd943a000-7fffd943c000 r--s 00000000 08:05 920904                     /var/cache/fontconfig/99e8ed0e538f840c565b6ed5dad60d56-le64.cache-3
7fffd943c000-7fffd9441000 r--s 00000000 08:05 920887                     /var/cache/fontconfig/2cd17615ca594fa2959ae173292e504c-le64.cache-3
7fffd9441000-7fffd9442000 r--s 00000000 08:05 920918                     /var/cache/fontconfig/e7071f4a29fa870f4323321c154eba04-le64.cache-3
7fffd9442000-7fffd9443000 r--s 00000000 08:05 920884                     /var/cache/fontconfig/0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-3
7fffd9443000-7fffd9449000 r--s 00000000 08:05 920906                     /var/cache/fontconfig/a755afe4a08bf5b97852ceb7400b47bc-le64.cache-3
7fffd9449000-7fffd9452000 r--s 00000000 08:05 918956                     /var/cache/fontconfig/6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3
7fffd9452000-7fffd9462000 r--s 00000000 08:05 920882                     /var/cache/fontconfig/04aabc0a78ac019cf9454389977116d2-le64.cache-3
7fffd9462000-7fffd9490000 r--s 00000000 08:05 917998                     /var/cache/fontconfig/365b55f210c0a22e9a19e35191240f32-le64.cache-3
7fffd9490000-7fffd94aa000 r-xp 00000000 08:05 1843706                    /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.12
7fffd94aa000-7fffd96a9000 ---p 0001a000 08:05 1843706                    /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.12
7fffd96a9000-7fffd96aa000 r--p 00019000 08:05 1843706                    /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.12
7fffd96aa000-7fffd96ab000 rw-p 0001a000 08:05 1843706                    /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.12
7fffd96ab000-7fffdc000000 r--p 00000000 08:05 25402                      /usr/share/icons/hicolor/icon-theme.cache
7fffdc000000-7fffdc037000 rw-p 00000000 00:00 0 
7fffdc037000-7fffe0000000 ---p 00000000 00:00 0 
7fffe0000000-7fffe0026000 rw-p 00000000 00:00 0 
7fffe0026000-7fffe4000000 ---p 00000000 00:00 0 
7fffe4000000-7fffe4021000 rw-p 00000000 00:00 0 
7fffe4021000-7fffe8000000 ---p 00000000 00:00 0 
7fffe8000000-7fffe8001000 r--s 00000000 08:05 920886                     /var/cache/fontconfig/1ac9eb803944fde146138c791f5cc56a-le64.cache-3
7fffe8001000-7fffe8004000 r--s 00000000 08:05 920891                     /var/cache/fontconfig/385c0604a188198f04d133e54aba7fe7-le64.cache-3
7fffe8004000-7fffe8005000 r--s 00000000 08:05 920916                     /var/cache/fontconfig/dc05db6664285cc2f12bf69c139ae4c3-le64.cache-3
7fffe8005000-7fffe8007000 r--s 00000000 08:05 920899                     /var/cache/fontconfig/767a8244fc0220cfb567a839d0392e0b-le64.cache-3
7fffe8007000-7fffe800c000 r--s 00000000 08:05 920888                     /var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3
7fffe800c000-7fffe801e000 r-xp 00000000 08:05 1843710                    /usr/lib/x86_64-linux-gnu/libdbusmenu-gtk3.so.4.0.12
Program received signal SIGABRT, Aborted.
0x00007ffff42a5037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) thread apply all bt

Thread 11 (Thread 0x7fffd9182700 (LWP 21784)):
#0  0x00007ffff464205e in pthread_cond_timedwait@@GLIBC_2.3.2 ()

   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff5149935 in g_cond_wait_until ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff50dfb81 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff50e01ca in g_async_queue_timeout_pop ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff512e6b2 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff512deb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff463df8e in start_thread ()

   from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff4367e1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffe97f9700 (LWP 21770)):
#0  0x00007ffff435b3cd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff510a1dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff510a304 in g_main_context_iteration ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff510a361 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff512deb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff463df8e in start_thread ()

   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff4367e1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffebc77700 (LWP 21768)):
#0  0x00007ffff435b3cd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff510a1dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff510a6ba in g_main_loop_run ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff56dc4f6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff512deb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff463df8e in start_thread ()

   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff4367e1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffec478700 (LWP 21767)):
#0  0x00007ffff435b3cd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff510a1dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff510a304 in g_main_context_iteration ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffec47fa1d in ?? ()

   from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff512deb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff463df8e in start_thread ()

   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff4367e1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7fc3980 (LWP 21763)):
#0  0x00007ffff42a5037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff42a8698 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff42e25ab in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff42eea46 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007fffd877ee3c in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#5  0x00007fffd877ee91 in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#6  0x00007fffd877ef32 in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#7  0x00007ffff7209350 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff727049c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff53cd55e in g_closure_invoke ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff53deaf8 in ?? ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff53e6996 in g_signal_emit_valist ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff53e6f92 in g_signal_emit ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff73ad583 in gtk_widget_send_focus_change ()

   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff73b081f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff73bc3b1 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff73bc95a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff727049c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff53cd620 in g_closure_invoke ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff53deaf8 in ?? ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff53e6996 in g_signal_emit_valist ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff53e6f92 in g_signal_emit ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff72702ae in gtk_main_do_event ()

   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff6e9f5e2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007ffff5109f05 in g_main_context_dispatch ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff510a248 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff510a304 in g_main_context_iteration ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff56aa52c in g_application_run ()

   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#30 0x000000000042c199 in main (argc=1, argv=0x7fffffffe1c8) at nemo-main.c:101

(gdb) AB

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 2 years?
