### ISSUE TITLE
File copy to exFAT filesystem will fail if filename contains 'illegal' chars

### ISSUE THREAD

**Issue by sverx** [linuxmint/nemo#3137]
```
* Nemo version -> nemo 4.8.6
* Is issue with desktop or windowed nemo? -> both
* Distribution -> Linux Mint 20.1
* Graphics hardware *and* driver used -> Intel Core i5 own GPU
* 32 or 64 bit -> 64
 ```

**Issue**
Normally files (and folders) copied to `FAT32` filesystem gets their name changed if containing 'illegal' chars, such as `:`, but if the target filesystem is `exFAT` this doesn't happen and the copy fails.

**Steps to reproduce**
* Create a document on your Desktop, call it `Document: empty` for instance.
* Connect an `exFAT` formatted USB pendrive.
* Drag and drop the file from the desktop to the pendrive.
* The file copy operation fails.

**Expected behaviour**
I'm expecting the copy to be performed with the target filename to be changed if containing 'illegal' chars, such as `:`.

**Other information**
(this issue is a replacement for my previous one, now that I finally got how to make a proper one... previous issue was #3107 - now closed by me)

**Comment by leigh123linux** [comment]
It is fixed in later nemo releases.

https://github.com/linuxmint/nemo/commit/8ca3d47894222c1e848bd8fd7f2341d9209c6e43
