### ISSUE TITLE
Seaching for files in subfolders

### ISSUE THREAD

**Issue by raulsas** [linuxmint/nemo#3140]
```
 * Nemo version (5.2.4)
 * Is issue with desktop  nemo
 * Distribution - (Mint 20.3  Kernel 5.4.0-135)
 * NVIDIA Corporation GP108 [GeForce GT 1030]
 * 64 bit
 ```

**Issue**

Unable to search for files within a folder since nemo update. Search functionality only works for the current folder...

**Steps to reproduce**

Just search on any folder

**Expected behaviour**

It use to list all files matching the seach frase inside every folder from the parent one.  It happens in current nautilus 3.36.3  

**Other information**
I can't downgrade to any previous nemo version.

**Comment by Jeremy7701** [comment]
What does the command **gsettings get org.nemo.search search-files-recursively** display (it should say true, but you may get a value of false).
Use as written, spaces are significant.

Alternatively you can use the GUI editor - dconf - to set/display these hidden settings.
Use a key of /org/nemo/search/search-files-recursively for the GUI program.
**Be very careful if you change anything.**

**Comment by mtwebster** [comment]
![image](https://user-images.githubusercontent.com/262776/208696009-6d94d220-7d0a-4b2b-a9f5-843d507a4efd.png)

Check out the buttons on the right-hand side there. The one currently depressed toggles searching in subfolders.
