### ISSUE TITLE
Can you make Nemo show thumbnails in subfolders like Dolphin?

### ISSUE THREAD

**Issue by BrainKicker** [linuxmint/nemo#3141]
```
 * Nemo version (5.4.3)
 * Distribution - (Mint 21 x86_64)
 * 64 bit
 ```

**Suggestion**

Can you make Nemo show thumbnails in subfolders like Dolphin does?

![Screenshot_20221221_000547](https://user-images.githubusercontent.com/30545094/208767186-550701f3-d579-481a-a2c2-ca436bcd0631.png)

![Screenshot_20221221_000556](https://user-images.githubusercontent.com/30545094/208767197-50325b27-5d02-46fe-977e-92f8fd9c5974.png)

**Expected behaviour**

I want to see files in the subfolders like on the second screenshot.

**Comment by BrainKicker** [comment]
The first screenshot is Nemo, the second is Dolphin.

**Comment by Jeremy7701** [comment]
You would need a very big screen to fit a folders contents into a folder icon!

**Comment by BrainKicker** [comment]
Not really. For example, Dolphin fits a maximum of 4 thumbnails into a folder icon.

**Comment by Jeremy7701** [comment]
I can fit one.
![Screenshot from 2022-12-21 13-30-09](https://user-images.githubusercontent.com/52585119/208916952-4f0733b6-8fc4-415a-91ae-d95d7731d87a.png)

**Comment by BrainKicker** [comment]
But Dolphin can fit more.
![изображение](https://user-images.githubusercontent.com/30545094/208925801-cd5f5be3-90b8-4f1c-bbe9-ed977b590239.png)

**Comment by mtwebster** [comment]
This looks nice, but I don't see it as being useful - the little images don't tell much, except that there's something in the folder, and they're not even shown for every folder, just for ones with thumbnail-able files.

If I name a folder "Pictures" I know what to expect in there - I don't need little previews to tell me.

**Comment by BrainKicker** [comment]
If you have a lot of directories with pictures inside, it's faster for you to identify which a directory is by looking on thumbnails, than reading it's name.

Besides, it helps to understand with a quick glance which directories have files within and which don't.

And, as you said, this looks nice. I think that this is a sufficient reason for implementing the feature.

**Comment by EmiOnGit** [comment]
I double this. I have to have lots of images saved in many files. To be able to have a quick preview of some of the content is insanely more useful than searching through the names sometimes

**Comment by Jeremy7701** [comment]
You would need giant icons to hold a worthwhile number of sub-icons.
Perhaps you could use the desktop as one big icon - there's space to hold the filenames in addition to the sub-icons!
