### ISSUE TITLE
Not possible to drag the pathbar to other window (it changes to location entry)

### ISSUE THREAD

**Issue by Martin-Laclaustra** [linuxmint/nemo#3146]
```
 * Distribution - Mint 21.1
 ```
**Issue**
With Mint 21.1 update, a single click on pathbar last item changes it to location entry and makes it impossible to drag the path to other window. This also provides an inconsistent interface, because clicking any other item on the pathbar does not change it (changes the shown contents, as expected), and it can be dragged.
Dragging the path is a useful feature, particularly dragging it into load/save dialogs, as these dialogs lack several navigation aids.
The pathbar/location entry part of Nemo excelled in its consistency, and I particularly appreciated how much better it worked with respect to the windows counterpart.
If the windows behavior mimicking was intentional, please add an option to disable it. (There is already the button to switch between pathbar and location entry, so the new way of switching "unidirectionally" by clicking the last item does not add much)

**Steps to reproduce**
Open Nemo and navigate to any directory.
Try to drag the last item (necessary for passing the whole path, dragging other item in the pathbar passes only the partial path).
It is not possible, the pathbar changes to location entry.

**Expected behaviour**
(That of Mint 21)
Open Nemo and navigate to any directory.
Try to drag the last item (necessary for passing the whole path, dragging other item in the pathbar passes only the partial path).
Success.

**Other information**
I really praise your work. It would be even better if proposed interface advancements are backed by an option for disabling (sometimes the look like real improvements but some other functionality suffers, like in this case).

**Comment by mtwebster** [comment]
The clicking the current location button did nothing anyhow, and allowing one to see the current location's path entry seemed pretty useful.

A more thorough explanation of why we did this change: https://github.com/linuxmint/nemo/issues/3134#issuecomment-1345348258, though the behavior was slightly modified in 003e516cdaadd9a.

We're definitely not *against* having user options, but we really can't add one for every change we make - if makes things more difficult to maintain in the long run and can be confusing for users - we'd rather try to figure out what the best behavior might be that works for the majority of users, and this is what we've attempted to do in this case.

**Comment by Martin-Laclaustra** [comment]
Thank you for the quick response.
Is it possible to trigger the action of the click _when the button is released_ and avoid it if the current location button is dragged, so that _both_ functions are available?
Else, how can something equivalent to dragging the path be achieved? (because dialogs do not allow to paste a path, thus, despite it is possible to copy it from the location entry there is no way to feed it to dialogs).

**Comment by Martin-Laclaustra** [comment]
After reading other similar issues, May I suggest that you reopen this issue and allow some extra feedback from other users?

**Comment by mtwebster** [comment]
Ah I had already fixed it not long after your original report :) but thanks - it was never our intent to take away this feature, it just isn't a widely-used one and we didn't consider it during testing.

I'm going to leave this issue closed, as it was specifically about a drag-and-drop issue. This already an issue or two related to this - some more constructive than others.
