### ISSUE TITLE
Add the translations in the launchers (/usr/share/nemo/actions/)

### ISSUE THREAD

**Issue by roxfr** [linuxmint/nemo#3150]
Hello,
Could you add the translations for the launcher : /usr/share/nemo/actions/**set-resolution.nemo_action**
See image below.
Thank you.
Regards,
Roxfr

![01](https://user-images.githubusercontent.com/52124613/210251862-7263a77b-51ae-4844-bba6-286d80d483d9.png)

**Comment by roxfr** [comment]
Same for /usr/share/nemo/actions/**mintstick-verify.nemo_action**

![02](https://user-images.githubusercontent.com/52124613/210264354-e2221253-d9a3-48ee-b49c-ad6bfb1ec5d0.png)

**Comment by mtwebster** [comment]
ref: https://github.com/linuxmint/nemo/commit/4e730b05223677352604bdec9267bd0571b8b979

**Comment by roxfr** [comment]
Thank you!
