### ISSUE TITLE
Font problem in list view with date related columns (Solved, not an issue)

### ISSUE THREAD

**Issue by spsf64** [linuxmint/nemo#3156]
```
 * Nemo version (nemo --version 5.6.1)
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - (Arch)
 * Graphics hardware *and* driver used
 * 32 or 64 bit: 64Bit
 ```

**Issue**
When list view is selected and any column with date is added, the font is not uniform

**Steps to reproduce**
Add a new column with date view

**Expected behaviour**
Foloow system wide selected font

**Other information**
Attached file:
![ss](https://user-images.githubusercontent.com/1877391/211096774-56712238-3d16-4ec7-8f49-f02821573577.png)

**Comment by Jeremy7701** [comment]
See nemo preferences, monospace font selection.

![Screenshot from 2023-01-06 23-45-00](https://user-images.githubusercontent.com/52585119/211118165-ed9c5aed-3cfe-47b2-a563-158701a08f69.png)

**Comment by spsf64** [comment]
> See nemo preferences, monospace font selection.
> 
Wow; Thank you @Jeremy7701 !
Never realized this option existed because it is the first time I changed default fonts...

**Comment by Jeremy7701** [comment]
It's a new feature.

**Comment by tmelorc** [comment]
It would be good to use mono font in other columns also. 
Is it possible?
