### ISSUE TITLE
[Cinnamon] 'Undo' history is forgotten when windowed Nemo is closed

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/nemo#3159]
```
 * 5.6.1
 * windowed Nemo
 * Mint 21.1 Cinnamon
 ```

**Issue**
After performing any file operations, if you close Nemo and then reopen Nemo, you cannot undo the aforementioned file operations.

**Steps to reproduce**
1. open Nemo
2. create a new file or folder
3. rename the newly-created file or folder
4. close Nemo
5. reopen Nemo
6. try to do an 'Undo' operation (whether via the 'Edit' menu or via 'Ctrl+z'
7. observe how step 3 does not get undone

**Expected behaviour**
The history for undo should be retained even when you close Nemo

**Other information**
Caja on Mint 21.1 MATE does not have this issue.

(Thunar 4.16.10 doesn't even support this function and is therefore N/A)

**Video demonstrating the issue**

[undo.webm](https://user-images.githubusercontent.com/11896003/211705600-93260157-afbe-452d-9519-927c1514951f.webm)

**Comment by mtwebster** [comment]
This works in mate because caja and caja desktop are all the same process. Nemo is two separate processes, so this is not possible.
