### ISSUE TITLE
[Cinnamon] File operation history is completely separate between desktop and windowed Nemo

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/nemo#3160]
```
 * 5.6.1
 * desktop & windowed Nemo
 * Mint 21.1 Cinnamon
 ```

**Issue**
The history for file operations is completely separate between desktop Nemo and windowed Nemo, meaning that file operations performed on the Cinnamon desktop cannot be undone from within windowed Nemo and vice-versa.

**Steps to reproduce**
1. create a new file or folder on the desktop
2. rename the newly-created file or folder
3. open Nemo
4. try to do an 'Undo' operation (whether via the 'Edit' menu or via 'Ctrl+z'
5. observe how step 2 does not get undone
6. within windowed Nemo, create another new file or folder located at `~/Desktop`
7. rename the file or folder created in step 6
8. close Nemo
9. while on the desktop, press Ctrl+z
10. observe how step 7 was not undone

**Expected behaviour**
The history for file operations should be shared between desktop Nemo and windowed Nemo.

**Other information**
Mint 21.1 MATE does not have this issue between desktop and windowed Caja.

(Thunar 4.16.10 doesn't even support this function and is therefore N/A)

**Video demonstrating the issue**

[history.webm](https://user-images.githubusercontent.com/11896003/211707156-92d322c4-f4f5-4964-95bf-6cf43e88735c.webm)

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/issues/3159#issuecomment-1378817224
