### ISSUE TITLE
Links to text webpages, creating by dragging from browsers, open in xed

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#3173]
```
 * Nemo version: 5.6.3
 * Is issue with desktop or windowed nemo? Both
 * Distribution: Mint 21.1
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

On webpages that contain only plain text, dragging a link to them to the desktop, or to elsewhere in the file system, creates a file that, when double-clicked, opens, not in the default browser, but in xed - even though xed is not my default text editor.

Moreover, when the browser used to create the link is Firefox, the resulting would-be shortcut is called 'Link to' (_sic_). When Chrome is used to create the shortcut, the shortcut has a fuller name, such as, 'Link to https://www.rainlendar.net/download/Changes.txt'.

The behaviour that I have described seems to occur irrespective of whether Chrome or Firefox was used to _create_ the shortcut.

**Steps to reproduce**

1. On Cinnamon, and in Firefox or Chrome, navigate to a a webpage the name of which ends with '.txt' - such as https://www.rainlendar.net/download/Changes.txt or https://raw.githubusercontent.com/lifchicker/Updater/master/README.TXT.
2. Create a shortcut - on, say, the desktop - by dragging from the browser's URL bar.
3. If Firefox was used to create the shortcut, note that the shortcut's name is wrong.
4. Double-click the newly-created shortcut.
5. See that xed loads.

**Expected behaviour**

- At stage 3, and even if one is using Firefox, the shortcut should not be called, 'Link to'.
- At stage 4, the default browser should load.

**Other information**

[This forum thread](https://forums.linuxmint.com/viewtopic.php?f=47&t=390032) discusses the issue.

**Comment by mtwebster** [comment]
Chromium, Brave (really chromium), Firefox and Chrome all consistently create a 'Link to <url>' shortcut for me. This is done by nemo, not the browser.

As for a text editor opening, I don't think this is an unreasonable outcome - it is a text file after all:
```
[08:49:16 PM] mtwebster@mintbox3:~/Desktop> gio info https://www.rainlendar.net/download/Changes.txt
display name: Changes.txt
edit name: Changes.txt
type: regular
uri: https://www.rainlendar.net/download/Changes.txt
attributes:
  standard::type: 1
  standard::display-name: Changes.txt
  standard::edit-name: Changes.txt
  standard::icon: text-plain, text-x-generic, text-plain-symbolic, text-x-generic-symbolic
  standard::content-type: text/plain
  standard::fast-content-type: text/plain
  standard::symbolic-icon: text-plain-symbolic, text-x-generic-symbolic, text-plain, text-x-generic
  etag::value: W/"63cbef0c-1f6d6"
  id::filesystem: http:uri=https%3A%2F%2Fwww.rainlendar.net%2Fdownload%2FChanges.txt,prefix=%2Fdownload%2FChanges.txt
  time::modified: 1674309388
  time::modified-usec: 0
  metadata::xed-position: 0
[08:49:32 PM] mtwebster@mintbox3:~/Desktop> 
```
Most gui programs you use accept uris as a way to open a file.  file:// uris point to a local file, https:// uris point to some remote file, but they're treated identically. If you ever see the acronym 'gvfs', 'gnome virtual filesystem' - that's a layer over your real filesystems that enables special locations like `trash://`, `recent://`, `favorites://`, etc... it can enable us to interact with files normally, regardless of where they're actually located - https is included in this.

Why xed is being opened regardless of the default editor is less clear, I'll attempt to discover why.

**Comment by mtwebster** [comment]
Ah scratch that, today I can reproduce the 'Link to' issue.

**Comment by LinuxOnTheDesktop** [comment]
Excellent stuff.

I take it that: 
- commit 5b6cc56124a26e18dcf4b1c5f8ab8d34992f06d6 fixes the problem of a link being named, simply, 'Link to';  
- commit 818d2fe789420bcff26c0564e197937a4071f36a makes it the case that links to online text files will open in the default browser rather than in a text editor.

**Comment by mtwebster** [comment]
Yes - we talked about it, it does make the most sense to open an http location in a browser, plus the editor giving an error if you tried to save the file added to the broken feel.
