### ISSUE TITLE
Can't generate thumbnail after saving image

### ISSUE THREAD

**Issue by bwat47** [linuxmint/nemo#318]
Steps to reproduce:

Download image to home dir. Edit it in gimp (change size or something). Save the image, overwriting with the same filename. Filetype doesn't seem to matter (saw issue with jpg and png)

What happens: nemo just gets totally stuck trying to generate a thumbnail for it. moving the image to another dir instantly gave it a thumbnail.

edit: forgot to mention, nemo 1.8.2

**Comment by grizzlyfred** [comment]
Also not seeing it with Rebecca 17.1.

**Comment by White-Owl** [comment]
Mint 17.2, Nemo 2.6.7
The bug is still present.

**Comment by Vahan86** [comment]
@bwat47, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
