### ISSUE TITLE
Cannot use "Save As" dialog normally

### ISSUE THREAD

**Issue by andyhasit** [linuxmint/nemo#3186]
```
 * Nemo version 5.6.3
 * Is issue with desktop or windowed nemo?
 * Distribution - Mint 21.1
 * Graphics:
     * Intel Corporation HD Graphics 5500 
     * driver: i915
 * 64 bit
 ```

**Issue**

Cannot deselect selected subdirectory in "Save As" dialog, making it very difficult to use the dialog.

**Steps to reproduce**

With say LibreOffice or VS Code:

1. Select "Save As"
2. Go up a directory. The directory you came from is selected (fair, but unnecessary)
3. Click on white space to deselect the selected sub directory - it does not let you. You can select different sub-directory, but cannot select none, meaning you cannot save to that directory.
 
Note: changing the file name deselects the selected sub directory (and lets you save) but:

1. Not everyone figures this out.
2. If you select another directory, you are back to being unable to deselect it, and therefore not able to save, until you modify the text.
3. It's highly inconvenient if you just want to save the file elsewhere without changing the name.

As far as I can tell there's no way around this other than changing the file name. Hitting escape closes the overall dialog box. 

**Expected behaviour**

Click on white space deselects the selected sub directory and thereby lets you save in the directory

**Other information**

I'd rank this as a pretty high priority bug given how many people will find themselves unable to "Save As" unless they figure out the trick.

**Comment by leigh123linux** [comment]
You need to file the issue against gtk as it provides the dialog

https://gitlab.gnome.org/GNOME/gtk/-/issues

https://docs.gtk.org/gtk3/class.FileChooserDialog.html

**Comment by andyhasit** [comment]
> You need to file the issue against gtk as it provides the dialog
> 
> https://gitlab.gnome.org/GNOME/gtk/-/issues
> 
> https://docs.gtk.org/gtk3/class.FileChooserDialog.html

Thanks for pointing me in the right direction. I'll file the bug with gtk, but surely this issue should not be closed here until we update gkt to a version which has that fix?

**Comment by andyhasit** [comment]
The issue matches this one: https://gitlab.gnome.org/GNOME/gtk/-/issues/3590 which is 2 years old! 
Unfortunately you need a GNOME account to log or upvote issues.
