### ISSUE TITLE
[Change] When applying folder icon, use relative path to src icon instead of absolute

### ISSUE THREAD

**Issue by danimesq** [linuxmint/nemo#3200]
Depends on "[[Change] Store folder data, such as custom icon, in a dotfile inside it](https://github.com/linuxmint/nemo/issues/3201)".

This would ensure portability on folder data such as icons/emblems.

**Comment by Jeremy7701** [comment]
?

**Comment by danimesq** [comment]
Related to: https://github.com/linuxmint/nemo/issues/3201

**Comment by mtwebster** [comment]
It's already portable with the current implementation - metadata gets moved with a file.
