### ISSUE TITLE
[Change] Store folder data, such as custom icon, in a dotfile inside it

### ISSUE THREAD

**Issue by danimesq** [linuxmint/nemo#3201]
This should ensure portability.

**Comment by Jeremy7701** [comment]
?

**Comment by danimesq** [comment]
I'm sure the title (even without the description) is more at explaining than a "?" at asking.

**Comment by Jeremy7701** [comment]
> I'm sure the title (even without the description) is more at explaining than an "?" at asking.

My apologies, @danimesq
