### ISSUE TITLE
nemo-tracker-search

### ISSUE THREAD

**Issue by plata** [linuxmint/nemo#321]
I suggest to replace nemo-search-engine-simple with (meta-)tracker by default for nemo. nemo-search-engine-simple is a simple recursive search-algorithm that online works for filenames and isn't really fast. To speed up the search and more importantly to enable searching in file-content, tracker should be used as a search engine. There is a tracker implementation right now that gets enabled if ibtracker-sparql-0.14-dev is installed at build-time. Anyway this still only searches in filenames (src: mtwebster).
To keep the changes simple and operate on a up-to-date search-engine in the future without much work, Catfish could be used. It combines different search-engines (Find, Slocate, Doodle], Tracker, Beagle, Strigi and Pinot). I guess it will be possible to integrate the controls into the nemo-gui and run catfish-logic in the back without much a do. So if there are updates to any engine, nemo will get the best of it for free.
An other advantage is that if you enable tracker with the current implementation, if no indexing is done or failed, nothing will be found if you search. With catfish that should not happen (as it also uses find).
This would solve several ideas on the community-site as well.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
