### ISSUE TITLE
(Suggestion) Top Right corner of a window, closes the window

### ISSUE THREAD

**Issue by Chipsum** [linuxmint/nemo#3210]
In my past utilization of operating systems, I am used to top right the mouse cursor on WINDOWS, and it closes the window, it a cool feeling a fast way to multitask, at least this is how I felt during the past decades.
I would love to see the same approach with Nemo, or anything related, with the cinnamon theme in case.
![image](https://user-images.githubusercontent.com/37517008/227017357-f359d11f-62b6-4c0f-9d6e-5665a1768220.png)
and thank you so much !

**Comment by Jeremy7701** [comment]
Strangely enough, you are not using Windows, nor should you be.

**Comment by Chipsum** [comment]
@Jeremy7701 it's not about using windows or not, it's about how I feel when I use window(s).

**Comment by dominichayesferen** [comment]
I believe this is either a Cinnamon feature to suggest, or a Mint-Y change to suggest.
