### ISSUE TITLE
Is Hover Highligting of File Name Rows via Mouse Over Removed?

### ISSUE THREAD

**Issue by amiga-500** [linuxmint/nemo#3216]
In **v4.4.2** (on Ubuntu 20.04LTS using GNOME+XOrg/Wayland) as the mouse moves over file names there is a visibile row highlighter (shown in grey in my theme) -- see attached video. In **5.2.4**  (on Ubuntu 22.04LTS using GNOME+XOrg/Wayland) this highlighting is now gone (see attached video).

Is Nemo 5.2.4 working correctly (ie. hover highlighting of file names are now removed) or is this a bug in 5.2.4?

**Nemo v4.4.2:**

![position](https://user-images.githubusercontent.com/5191497/231555054-b3ed0788-43fd-43de-a33f-30a003fcf617.gif)

**Nemo v5.2.4:**

![position2](https://user-images.githubusercontent.com/5191497/231626711-6439811f-d2a2-493b-870b-f89d1a44ba7a.gif)

And yes, i already know i can simply edit my ~/.config/gtk-3.0/gtk.css file to add back the missing feature, but i am more curious if its a glitch/bug due to my install or if it was intentionally removed.  Preferably, i like that its gone so i dont want it back..so that wasnt my concern.

**Comment by Jeremy7701** [comment]
The current stable nemo is 5.6.4 in LMDE5/Mint 21.1
Hovering shows multi-line displays - which I prefer.

![Screenshot from 2023-04-12 19-07-31](https://user-images.githubusercontent.com/52585119/231546940-7b6696c9-8588-4f53-8dbc-419dcda34210.png)

**Comment by amiga-500** [comment]
To clarify..this is what i mean...this is 4.4.2 (Ubuntu 20.04 using GNOME):

![position](https://user-images.githubusercontent.com/5191497/231555054-b3ed0788-43fd-43de-a33f-30a003fcf617.gif)

The latest for GNOME on 22.04 is 5.2.4.  And it is this version that the above hover highlighting no longer occurs.  So just wondering if it was intentional and is normal that it is now missing.  I can make another video showing this but just imagine the highlighting (shown in grey) is missing while the orange (me actually clicking) still exists in 5.2.4.

**Comment by mtwebster** [comment]
This has always been theme-specific thing as far as I know.  I fired up Mint 19.3 (which has 4.4.3) and none of the Mint themes have this - I went as far back as 2013 for when they last had this: https://github.com/linuxmint/mint-themes/commit/4231ba7ff87a05eaf265eba59868db8c5a6d7c5f

**Comment by amiga-500** [comment]
Ahhh that explains it then.  thank very much!
