### ISSUE TITLE
How do i alternate background row colors when in ListView?

### ISSUE THREAD

**Issue by amiga-500** [linuxmint/nemo#3217]
There isnt an option so i figure i must edit the ~/.config/gtk-3.0/gtk.css file
The problem is i dont know the css selector for the rows.
i know when i do get it then i just uaw :nth-child(even) and/or nth-child(odd) to get it to work.

Using the GTK+DEBUG tool it doesnt drill down to show the row selector names.  At most i can only get this part:

_.nemo-window-pane .view_ which is the area i want to affect.  I just need to find the children rows names to set.

**Comment by mtwebster** [comment]
It seems like it may no longer be supported - https://gitlab.gnome.org/GNOME/gtk/-/issues/581

Otherwise you'd use something like:
```
.nemo-window-pane treeview.view {
    -GtkTreeView-allow-rules: true;
    -GtkTreeView-even-row-color: #ff0000;
    -GtkTreeView-even-row-color: #00ff00;
}
```

**Comment by amiga-500** [comment]
Ahhh thanks very much for the info.
