### ISSUE TITLE
BUG: Using Wayland - Context Menu (via Right-Click) Doesnt Close when Clicking Away on Left Side

### ISSUE THREAD

**Issue by amiga-500** [linuxmint/nemo#3218]
This problem only happens using Wayland (in Ubuntu). So, this is not an X11 problem and therefore doesn't affect Mint (and, by extension, Cinnamon) users.

This has been a bug for years in Wayland.  Please fix!

![position4](https://user-images.githubusercontent.com/5191497/231936829-670a7f49-af0d-4655-bdcf-d49e9e139c66.gif)

**How to Recreate the Problem:**

1. Using GNOME (with Wayland as the windowing protocol) open a file window in list view.
2. Right-click directly on an existing file to bring up its context menu. You **_MUST_** directly highlight the file for this problem to occur (in the video it's shown in orange).
3. Click on the left-side, outside of this context menu.  It won't close!

You would expect this context menu to close. It won't.   There appears to be an invisible window on the left-side of this context menu with  the same approximate dimensions of the visible context menu.  It is there and does not register click events.  It's very jarring when trying to click-close.  You always think Nemo crashed hard.

The only way to close this menu (besides selecting an item in this menu) is to either click above, below, right-side, or move a distance away on the left-side.

**Comment by Sohail-XD** [comment]
Same issue, you can also tap esc to close it.

**Comment by ToxicMushroom** [comment]
Can reproduce 
sway: 1.8.1
nemo: 5.8.1

**Comment by mtwebster** [comment]
Does it happen with the sidebar disabled? It seems like the dead zone is the approximate width of the sidebar (and grows if you drag it larger). If I turn it off completely, the problem goes away.

**Comment by Lassebq** [comment]
Can reproduce on hyprland and river

**Comment by leigh123linux** [comment]
See https://gitlab.gnome.org/GNOME/gtk/-/issues/160 and  https://gitlab.gnome.org/GNOME/nautilus/-/issues/1658

**Comment by mtwebster** [comment]
Hi, can anyone test the PR I just opened for this before I merge it?

#3281

I was fixing another problem and discovered it also appears to address this one as well.

Thanks

**Comment by ToxicMushroom** [comment]
> Hi, can anyone test the PR I just opened for this before I merge it?
> 
> #3281
> 
> I was fixing another problem and discovered it also appears to address this one as well.
> 
> Thanks

I certainly can but ehm how `./configure && make && make install` as in the INSTALL file doesnt work

**Comment by mtwebster** [comment]
Ah sorry - we don't have an INSTALL file, I'll have to re-add something.

If you're in Mint or something else Debian/Ubuntu-based, you can simply run:
```shell
apt install devscripts
sudo mk-build-deps -ir # generates a dependencies meta-package
dpkg-buildpackage
```
The packages will be created in the parent directory.

More generically, once you've got dependencies installed, you can run something like:
```shell
meson builddir --prefix=/usr
ninja -C builddir
sudo ninja -C builddir install
```

**Comment by Lassebq** [comment]
> Ah sorry - we don't have an INSTALL file, I'll have to re-add something.
> 
> If you're in Mint or something else Debian/Ubuntu-based, you can simply run:
> 
> ```shell
> apt install devscripts
> sudo mk-build-deps -ir # generates a dependencies meta-package
> dpkg-buildpackage
> ```
> 
> The packages will be created in the parent directory.
> 
> More generically, once you've got dependencies installed, you can run something like:
> 
> ```shell
> meson builddir --prefix=/usr
> ninja -C builddir
> sudo ninja -C builddir install
> ```

On arch-based distros it's as easy as chaning 2 lines (repo url and add `git checkout branch`) in PKGBUILD of [nemo-git](https://aur.archlinux.org/packages/nemo-git) and then building package with `makepkg -si`
