### ISSUE TITLE
Probable unclear doc for nemo-actions

### ISSUE THREAD

**Issue by jkopczyn** [linuxmint/nemo#3223]
* Nemo version (nemo --version) `5.6.4`
 * Is issue with desktop or windowed nemo? `Desktop`
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) `Mint 21.1`
 * Graphics hardware *and* driver used: card `Intel Alder Lake-P`, kernel driver `i915`
 * 32 or 64 bit `64-bit`

**Issue**
I am unable to set up nemo actions for the desktop. I expect that I am misunderstanding the docs, though it is possible it is a true bug.

**Steps to reproduce**
1. Save
```
[Nemo Action]
Active=true
Exec=/usr/bin/xfce4-display-settings
Icon-Name=preferences-desktop-display
Selection=none
Extensions=any;
Conditions=desktop;
Name=Change Displays
Comment=Rearrange displays
```
to `~/.local/share/nemo/actions/displays.nemo_action`.

2. Right-click the desktop and examine the dropdown menu that appears.

3. Fail to see any entry named 'Change Displays' (or anything similar)

**Expected behaviour**

This should appear as a line in the right-click menu from the desktop, with the text 'Change Displays' and the icon for the built-in Display settings app.

Also it should bring up the Display settings when you click it, but I don't currently have any reason to doubt that part.

**Comment by mtwebster** [comment]
Get rid of all the trailing whitespace - it's taken literally by the keyfile parser:
![image](https://user-images.githubusercontent.com/262776/234096889-2563c8e2-47d0-4daf-a381-5d0f8a22b337.png)

Once you do it should work, and it'll be formatted properly in most text editors:
![image](https://user-images.githubusercontent.com/262776/234097185-fefe9aad-9645-48fa-9325-0b96da96758f.png)

**Comment by jkopczyn** [comment]
The file doesn't have any trailing whitespace; that's probably an artifact of copying it to Github. May still be worth adding that to the docs.

**Comment by mtwebster** [comment]
Ah ok - this action works ok for me. Stupid question: Assuming you're running xfce, are you sure nemo-desktop is running? (and not thunar)

**Comment by jkopczyn** [comment]
...yeah, that was it. I'd checked that nemo was *installed* and I thought I'd confirmed that it was the default and I hadn't changed defaults, but none of those checks actually included checking what the active file manager was. Thank you again, for answering my stupid question.
