### ISSUE TITLE
Why Was Binay (long format) and Decminal (long format) dropped from a File's Properties?

### ISSUE THREAD

**Issue by amiga-500** [linuxmint/nemo#3224]
An earlier version of Nemo, when setting Preferences > Display > File Size Prefixes > Binary then it would show the File Size in KiB..great.  And when you went to the file's properties (rclick > properties) then where it says "Size:" you would see the Binary (long format) version.  THe same applies if u selected Decimal (ie, under a file's properties "Size:" would show the Decimal long format).  So it all made complete sense.

Now the latest Nemo drops the Binary (or Decimal) long format in the File Properties area and simply shows whatever u selected under Preferences.  

So presently one now has to select Binary (long format) from Preferences to now see it in a File's Properties.  However, doing it this way one is now stuck seeing the long format version in every directory.  It's just a wrong Ux design choice. 

Can you please fix this?  In short, bring back  the prior version of Nemo where it logically, applied your preferences to the folder but in the  file properties it would show the long format version of your selection.  It helps keep the clutter to a minimum.

**Comment by Jeremy7701** [comment]
Are you asking for a file to appear to have a different kind of size according to which directory it is in?
You don't say which version of nemo you see the problem in, but the standard settings work for me in 5.6.4.

**Comment by amiga-500** [comment]
No that is not what i mean.  Here are some screen recordings to make it clear.  I'm using Ubuntu.

**Nemo v4.4.2:**
![nemo4 gif](https://user-images.githubusercontent.com/5191497/233947378-f7025398-3af7-44b7-a86a-1507030701b8.gif)

Nemo v5.6.3
![nemo5 gif](https://user-images.githubusercontent.com/5191497/233947374-c2c3fa77-7414-4d8a-be39-ff4d00fb04c6.gif)

So what we are comparing is how under the Properties area it shows the exact size of he file in bytes.  It did this in v4 but in v5 it is now gone.  The only way to see the exact size of the file in bytes (or bits) is to turn on "Long Format" in preferences.  However, doing so will then show it in the nemo file window, not just under properties.  Notice how for v4, it only shows "MB" in the file window but shows the long format under file properties.

**Comment by okaestne** [comment]
Should be fixed with #3225

**Comment by amiga-500** [comment]
> Should be fixed with #3225

Thank you for the heads up!
