### ISSUE TITLE
Ubuntu 23.04 - Mouse Cursor is WRONG when Context-Menu Closes!!

### ISSUE THREAD

**Issue by amiga-500** [linuxmint/nemo#3243]
This happen only in Ubuntu 23.04.  It appears to be due to GNOME v 44.1 and 44.2.  Even when downgrading Nemo from 5.6.3 to lower versions the problem still occurs.  So its defintiely GNOME related.  However, other file managers like Nautilus work fine.  So it appears maybe Nemo isnt considering other factors that is causing this problem.  I am using X11.

![sss](https://github.com/linuxmint/nemo/assets/5191497/532f4da8-c2dd-4a50-9e3c-957f1c70b1a8)

**Comment by sagitariozod** [comment]
I have the same problem when the mouse cursor goes over the edge of one window to another. It happens on Ubuntu 23.04 and 23.10.

Greetings.

**Comment by mtwebster** [comment]
This isn't a nemo bug - I can reproduce it with other Gtk3 applications.

I've opened a bug report against Mutter:
https://gitlab.gnome.org/GNOME/mutter/-/issues/2871

**Comment by amiga-500** [comment]
Thank you for the reply and for opening the bug report.
