### ISSUE TITLE
21.2 Trash bin on desktop can't be moved and no files placed in it

### ISSUE THREAD

**Issue by Tibladar** [linuxmint/nemo#3250]
### Distribution

Mint 21.2

### Package version

5.8.0

### Frequency

Always

### Bug description

When trying to move the trash bin on the desktop it can be dragged but not dropped like other files, the position resets:
![drag](https://github.com/linuxmint/nemo/assets/52620063/87f8685d-2c2c-4fb7-84a3-83a8b400289e)

When dropping/releasing the mouse a "moving file" window is shown which never completes:
![grafik](https://github.com/linuxmint/nemo/assets/52620063/ec2b4f6c-111d-44b3-b2b2-3e0b2627df8b)

Dropping files on the trash bin is also not working, the dropped file is placed on top of the trash bin and can also be moved away again:
![into](https://github.com/linuxmint/nemo/assets/52620063/2f29c6da-267b-4de4-ae8b-77500c4997a6)

### Steps to reproduce

- Move the trash bin on the desktop and drop it somewhere on the desktop

- Drop files on the trash bin

### Expected behavior

- The trash bin should be moved instantly

- Dropping files on the trash bin should put them in it

### Additional information

.xsession-errors and the terminal show these two warnings when moving the trash bin:
```
$ nemo-desktop --quit && nemo-desktop 
Killing nemo-desktop, as requested
** Message: 11:21:50.492: nemo-desktop: session is cinnamon, establishing proxy
sys:1: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
sys:1: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

When dropping files on the trash bin no error is shown

This worked fine before upgrading to Mint 21.2 (which isn't released yet, I know)

**Comment by fugo** [comment]
Arch Linux with Budgie Desktop  
Mutter 43.5  
Same behavior after upgrade - not possible to drag files to trash.   
Can't move trash icon or PC icon [=crash nemo-desktop]  .  
I had this first with Nemo 5.8.0.1, now also with 5.8.1  
Downgrade to 5.6.5 helps.

Start:
```bash
nemo-desktop

** (nemo-desktop:215208): WARNING **: 16:02:00.632: Current gtk theme is not known to have nemo support (Graphite-blue-Dark) - checking...
Initializing nemo-image-converter extension
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-mediainfo-tab.py", line 13, in <module>
    from MediaInfoDLL3 import *
ModuleNotFoundError: No module named 'MediaInfoDLL3'
Initializing Nextcloud-client-nemo extension
Using python version sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)
nemo-media-columns: using a timeout of 0.30 second(s) for file processing
sys:1: Warning: g_strstr_len: assertion 'haystack != NULL' failed
** Message: 16:02:01.154: nemo-desktop: session is not cinnamon (checked XDG_SESSION_DESKTOP,DESKTOP_SESSION environment variables.) Applying default behavior
```
Move PC icon
```bash
sys:1: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
sys:1: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(nemo-desktop:215208): GLib-GIO-CRITICAL **: 16:11:12.103: g_file_get_child: assertion '!g_path_is_absolute (name)' failed

(nemo-desktop:215208): GLib-GIO-CRITICAL **: 16:11:12.103: g_file_equal: assertion 'G_IS_FILE (file2)' failed

(nemo-desktop:215208): GLib-GIO-CRITICAL **: 16:11:12.103: g_file_copy: assertion 'G_IS_FILE (destination)' failed
```
