### ISSUE TITLE
Nemo freezes/crashes when changing view type after performing Search/Find

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#3257]
### Distribution

Arch Linux

### Package version

5.8.2

### Frequency

Always

### Bug description

Latest version of `nemo` freezes if you try to switch from List View to Icon View after performing the search.

### Steps to reproduce

1) Go to a folder/directory of choice
2) Perform a search by hitting Ctrl+F or clicking on the hourglass icon
3) After search results have been displayed, click on the "Icon View" icon
4) `nemo` will now freeze and/or crash. "Icon View" icon will display a grayed-out state,

![2023-06-26_15-03-fs8](https://github.com/linuxmint/nemo/assets/7957590/f85299f5-7894-4373-84c6-65a8eb2d4580)

### Expected behavior

Search should display Icon View.

### Additional information

This is a new bug. I've been using this "Icon View" feature after a Search for close to a decade. I've even filed a bug about `nemo` forgetting view preferences for Find/Search https://github.com/linuxmint/nemo/issues/2584

**Comment by mtwebster** [comment]
Fixed by aef2e99fdecf254675a0ece5ba7ad866d1fbe08b, ccf1347ceed53b5550d3021a812886e3d404fd71

**Comment by nick-s-b** [comment]
Thank you so much @mtwebster ! Just updated and everything is perfect again.

**Comment by Jeremy7701** [comment]
Is "icon view" a new feature?
I'd always assumed that searches would only present a list view - it seemed a logical behaviour...

**Comment by mtwebster** [comment]
Searches always default to the list view, but you can switch to a different type to view the results. It's not new.

**Comment by nick-s-b** [comment]
@mtwebster 
>Searches always default to the list view, but you can switch to a different type to view the results. It's not new.

Michael, would it be possible to have a preference for the preferred search-results view? I'd like to set it to be the Icon View, for example, because previews work so great. Right now, if I search for something, see the results, click on Icon View, and then immediately change/modify/add something to the search field, it reverts to List View. It would be much more logical to always keep the search results set to what the last setting was. This is how other file managers do it too.
Thanks!

**Comment by Jeremy7701** [comment]
You could just press CTRL + 1 to get an icon view. :-)
Note that if you are searching a folder with sub-folders, then the icon view doesn't show the full path information in an obvious way.
So whilst I previously didn't know the icon view option existed, I shan't be using it - for the reason given above.
