### ISSUE TITLE
nemo crashes during content search

### ISSUE THREAD

**Issue by mstrauss2018** [linuxmint/nemo#3258]
### Distribution

Linux Mint 21 Cinnamon

### Package version

5.6.4

### Frequency

Always

### Bug description

/home/mike has 136525 files in many subfolders
I try a content search from from my Linux user profile and it crashes. I have no problem searching individual folders 1 layer from the root.
I noticed that during the search memory usage got to 100% then used swap space which was only the default 2GB and when SWAP usage got to 100% nemo crashed. I thought I needed more swap so I created a swap file which brought the SWAP total to 36.5GB. All that did was allow the search to continue longer, but then that would get to 100% then neo would crash.

[terminal log.txt](https://github.com/linuxmint/nemo/files/11884821/terminal.log.txt)
[xsession-errors.txt](https://github.com/linuxmint/nemo/files/11884822/xsession-errors.txt)
[Crash Report.txt](https://github.com/linuxmint/nemo/files/11884824/Crash.Report.txt)

### Steps to reproduce

launch LM. open neo in ome folder. 
hit the search icon
type one word in the conent search field
hit search
in less than 15 minutes, neo will crash
if you are monitoring system resources, you will see memory usage go up to 99.6% then swap space will go up to 99% then neo closes

### Expected behavior

nemo should list all files in my system that contain the word I searched for and stop searching. nemo search window should not close unless i close it

### Additional information

this has been happening since original installation which tells me none of the updates are the cause.

**Comment by Jeremy7701** [comment]
I'd expect something like this to happen.

Processing:-
Any file that nemo recognises as searchable (except for text files) is passed into one of a number of text converter programs;
The text is then searched and (mostly) discarded;
Repeat for the next file...

In the worst case, where all 136525 files are searchable you will run 136525 extraction programs and 136525 text searches.

I tried a content search on a directory containing 155 items, all searchable on a fast desktop and it took about 20 seconds.
So searching your home directory for a file containing a word requires a specialised tool to do the job.

**Comment by mstrauss2018** [comment]
I did not see this as a response to my post.Your explanation makes sense. Any thoughts on how to correct this?

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 27, 2023 at 9:58 AM, ***@***.***> wrote:   


I'd expect something like this to happen.

Processing:-
Any file that nemo recognises as searchable (except for text files) is passed into one of a number of text converter programs;
The text is then searched and (mostly) discarded;
Repeat for the next file...

In the worst case, where all 136525 files are searchable you will run 136525 extraction programs and 136525 text searches.

I tried a content search on a directory containing 155 items, all searchable on a fast desktop and it took about 20 seconds.
So searching your home directory for a file containing a word requires a specialised tool to do the job.

**Comment by mstrauss2018** [comment]
This is depressing. Windows searches never had this issue. What are your thoughts to fix or get around?Although I think Nemo is the best do you think another file manager would be better for this?
I think it is possible to have multiple file managers installed. What do you think?

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 27, 2023 at 10:34 AM, ***@***.***> wrote:   I did not see this as a response to my post.Your explanation makes sense. Any thoughts on how to correct this?

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 27, 2023 at 9:58 AM, ***@***.***> wrote:   


I'd expect something like this to happen.

Processing:-
Any file that nemo recognises as searchable (except for text files) is passed into one of a number of text converter programs;
The text is then searched and (mostly) discarded;
Repeat for the next file...

In the worst case, where all 136525 files are searchable you will run 136525 extraction programs and 136525 text searches.

I tried a content search on a directory containing 155 items, all searchable on a fast desktop and it took about 20 seconds.
So searching your home directory for a file containing a word requires a specialised tool to do the job.

**Comment by mtwebster** [comment]
I can reproduce this, there are some off-limits system locations that nemo is dipping into a system location where it shouldn't, due to a bad symbolic link.

**Comment by Jeremy7701** [comment]
If you have any information on the files where you expect to get a match, you should use it.
For example, most of my data files are either PDF or EPUB files.
Using the CLI:-
`find -type f -name "*.pdf" -exec grep -l 'line' {} +`
It took **only a few seconds** to list all PDF files that contain the string 'line' in them, it skips all other kinds of file types.
My /home directory has about 82,000 files in total.
I would expect nemo to do a much more reliable job of capturing/searching the text from a PDF file, though.

**Comment by mtwebster** [comment]
The problem  with that approach is that in many cases you're likely to run into a lot of false positives (and even misses) because you'll also pick up formatting words and encoding. A file of mine that showed up from your example command:
```
[04:29:27 PM] mtwebster@mintbox3:~/Downloads> cat file.pdf | grep -a  line
/PageMode/UseOutlines
/Outlines 278 0 R
```
Neither of those occurrences are part of the actual document content.

Windows search was nice if you had indexing enabled, but could be really slow if you made it search unindexed content. For the work I did the files I wanted to search were pretty centralized, so indexing was worthwhile.

Nemo supports a similar mode, but it's not part of the default build, and requires some additional dependencies that aren't always well-behaved (tracker-miner). You can also extend nemo to search additional file types.

**Comment by mstrauss2018** [comment]
No, I don't have a wine folder but I do have a PlayOnLinux folder which is basically a wine folder /home/mike/.PlayOnLinux

**Comment by mstrauss2018** [comment]
How can I find that symbolic link. How can I fix that bad symbolic link?

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 29, 2023 at 6:37 AM, Michael ***@***.***> wrote:   


Closed #3258 as completed via 0a391ab.

**Comment by mtwebster** [comment]
Look in that PlayOnLinux folder, I think that uses wine underneath, so there's probably a directory structure in it similar to what I mentioned in https://github.com/linuxmint/nemo/issues/3258#issuecomment-1609967334

If you're using PlayOnLinux, I'm not sure you can change anything. If you're no longer using that, you can just delete the entire .PlayOnLinux folder.

**Comment by Drugwash2** [comment]
The **z:** drive/folder in Wine and PlayOnLinux prefixes is nothing but a link to the root (`/`) folder of the system. As such it contains everything that root contains. I'd rather suspect the `kcore` file (?) in `/proc` which on my system appears to be 131 TB (!!!) large. A keyword search within such file - or whatever it actually is - would definitely screw up any application that is not aware of it.

PlayOnLinux does have a structure similar to Wine, its prefixes being in `~/.PlayOnLinux/wineprefix/`. Each Wine prefix in that path will contain the same folder structure for the **z:** drive/folder so for each of the prefixes a full search of the entire system partition will be performed, and each time the same `kcore` "file" will be searched in.

Of course I may be wrong and the cause could be entirely different.

**Comment by mtwebster** [comment]
Yeah for me it was choking on /proc/self/pagemap, which was interesting to observe but that's about it.

Regardless, it shouldn't happen any longer since https://github.com/linuxmint/nemo/commit/0a391ab5914817e57da8915676dde20a2c87bd7b

**Comment by Drugwash2** [comment]
On my systems (Mint 19.2 real and 21.1 VM) `/proc/self/pagemap` appears as zero bytes size. There' probably something else at play here. Good thing it's fixed now.

**Comment by mstrauss2018** [comment]
I forgot about z drive bring napped to /.This would explain why the mem and swapped are being maxed out. It's causing a loopback effect in which case the search never ends. This has got you be the cause

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 29, 2023 at 10:11 AM, ***@***.***> wrote:   


On my systems (Mint 19.2 real and 21.1 VM) /proc/self/pagemap appears as zero bytes size. There' probably something else at play here. Good thing it's fixed now.

**Comment by mstrauss2018** [comment]
I seriously beleive that something in the home folder is causing the search to be stuck in a loop which would explain why RAM and SWAP gets maxed out.. I don't know if it's one of the hidden files or play on linux which does have a link back to the root directory /

With this in mind I changed the folder structure in my Linux by changing the values of /home/mike/.config/user-dirs.dirs

Before:
XDG_DESKTOP_DIR="$HOME/esktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"

After:
XDG_DESKTOP_DIR="$HOME/main/Desktop"
XDG_DOWNLOAD_DIR="$HOME/main/Downloads"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/main/Documents"
XDG_MUSIC_DIR="$HOME/main/Music"
XDG_PICTURES_DIR="$HOME/main/Pictures"
XDG_VIDEOS_DIR="$HOME/main/Videos"

Before making the change, I created the folder /home/mike/main

Then once I made the change, Linux just automatically moved my Desktop, Downloads, Documents and other folders. It even updated the links to the left.
I did not move any hidden files (or play on linux) into the Main Directory. I only moved my personal folders and files.

Now, when I search /home/mike/main for content, it doesnt crash on me and I get the results I was expecting.

It might be good idea for the developers to mimic my folder structure.

Hope this is helpful

Mike

**Comment by Jeremy7701** [comment]
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.

Note that $HOME should already be equal to /home/mike - assuming your user name is mike.
So XDG_DESKTOP_DIR="$HOME/main/Desktop" ought to be =  /home/mike/main/Desktop !!!
So XDG will be rather confused!

**Comment by mstrauss2018** [comment]
yes it is /home/mike/main/Desktop

Thanks
