### ISSUE TITLE
Nemo v5.8.x does not handle .desktop files of Type=Link correctly

### ISSUE THREAD

**Issue by ktamp** [linuxmint/nemo#3266]
### Distribution

Arch

### Package version

5.8.x

### Frequency

Always

### Bug description

When copying a .desktop file of Type=Link from one folder to another, instead of copying the .desktop file, the content of the referenced URL is saved as a .html file. The same thing happens also when trying to rearrange .desktop files of Type=Link on the desktop.

For Nemo v5.8.3 and v5.8.4 things are even worse, as the above actions cause Nemo to crash. If the actions are performed on the desktop, Nemo is reloaded the first time it crashes, but the second time Nemo is not reloaded and the desktop icons disappear.

### Steps to reproduce

- Navigate to a site using Firefox.
- Drag from the left of the URL address to the  desktop or to a folder. This will create a .desktop file of Type=Link.
- Try to copy this .desktop file to another folder or to arrange it to a new position on the desktop.

### Expected behavior

The .desktop file should be copied.

### Additional information

Nemo up to v5.6.5 worked correctly.

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/nemo/commit/c64905efd219a4da64846e600ebd1f4ed0583131
