### ISSUE TITLE
Inconsistent behavior when saving files with the browser

### ISSUE THREAD

**Issue by Quertin** [linuxmint/nemo#3272]
### Distribution

Linux Mint 21.1 Cinnamon

### Package version

nemo 5.6.4

### Frequency

Always

### Bug description

Downloading a file and then pressing ctrl-v to replace the highlighted filename without overwriting the file extension only works as long as you do not navigate folders by double clicking.

### Steps to reproduce

Copy some name with ctrl-c then download a file inside your browser with right click "save as", now in nemo navigate to some folder with mouse double clicks and press ctrl-v.

### Expected behavior

Ctrl-v should only replace the filename up to the ".file extension (.mp4 .jpg ...)" like it does when not navigating to any folder.

**Comment by JosephMcc** [comment]
It sounds like you are talking about the browsers save dialog. That is not Nemo. That is provided by the toolkit the browser is built with. We have no control over that. The bug would need to reported to them.

**Comment by Quertin** [comment]
> It sounds like you are talking about the browsers save dialog. That is not Nemo. That is provided by the toolkit the browser is built with. We have no control over that. The bug would need to reported to them.

This here is not nemo ? this window appears with multiple applications like firefox, transmission etc.. 
![3](https://github.com/linuxmint/nemo/assets/136612013/89bc05f2-8587-477c-89f4-b09cc88f220b)

**Comment by rcalixte** [comment]
> This here is not nemo ? this window appears with multiple applications like firefox, transmission etc..

Correct, this is the GTK file-chooser. You may be able to edit this depending on the application (e.g. [Firefox in Manjaro](https://forum.manjaro.org/t/browsers-like-firefox-require-xdg-desktop-portal-package-to-use-os-default-file-manager/106933)). Firefox has an [open bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1285711) upstream as well. The portal for Cinnamon was not released until Mint 21.2 and Cinnamon 5.8 so you might need to upgrade before testing some of these changes to see if you can get them to work for you.

**Comment by Quertin** [comment]
Oh then i'm sorry for bothering you here.
