### ISSUE TITLE
Launching [nemo favorites:///] not working

### ISSUE THREAD

**Issue by Zynthasius31** [linuxmint/nemo#3283]
### Distribution

Arch Linux (6.4.4-zen1-1)

### Package version

5.8.4

### Frequency

Always

### Bug description

I wanted to make Favorites as default tab, but when I start nemo with
`nemo favorites:///` it says,
The folder contents could not be displayed.
Sorry, could not display all the contents of "favorites": The specified location is not supported
I tried removing all entries and nemo -q, but still doesn't work.

### Steps to reproduce

$ nemo favorites:///

### Expected behavior

_Prompt _appears...

The folder contents could not be displayed.
Sorry, could not display all the contents of "favorites": The specified location

### Additional information

$ nemo
```
** (nemo:33407): WARNING **: 16:38:33.255: Current gtk theme is not known to have nemo support (Amy-Dark-GTK) - checking...

** (nemo:33407): WARNING **: 16:38:33.276: The theme appears to have no nemo support.  Adding some...
```
$ nemo favorites:///
```
** (nemo:33625): WARNING **: 16:38:33.255: Current gtk theme is not known to have nemo support (Amy-Dark-GTK) - checking...

** (nemo:33625): WARNING **: 16:38:33.276: The theme appears to have no nemo support.  Adding some...
```

**Comment by mtwebster** [comment]
What is GTK3_MODULES set to?
```
env | grep GTK3_MODULES
```

It should be set, and include `xapp-gtk3-module`. This initializes the favorites virtual filesystem *before* nemo tries to open the location. I'm assuming you can navigate to favorites if you start nemo normally?

**Comment by Zynthasius31** [comment]
> I'm assuming you can navigate to favorites if you start nemo normally?

Yes I can

> It should be set, and include xapp-gtk3-module.

It works now, thanks. I couldn't even think about gtk3 modules.
