### ISSUE TITLE
Nemo Search Not Finding Files in New Folders On An External Drive

### ISSUE THREAD

**Issue by mbluett88** [linuxmint/nemo#3284]
### Distribution

Mint 20.3

### Package version

5.8.4

### Frequency

Always

### Bug description

If I create a **new** folder on an **external drive** and place a **new** file in it, Nemo's search cannot find it. 
     In my case, I am using a Western Digital 4 TB HD Model 2620 (not SSD) drive mounted via USB which is an NTFS partition.
     Even if I remount the drive the problem still occurs.

If I place the same new file in an existing folder, created before I upgraded to 5.8.4 it finds the file perfectly.

Creating a file (in a new folder) on the disk that Linux Mint is installed on, Nemo finds the file as it should.

If I create a new folder it is found and when I open it within the search window it shows the file. But, searching for the file does not work.

Files can be found properly on a Kingston USB thumb drive when creating new folders (and files within them).

Also a My Passport Ultra model 260D (5TB) drive works fine (NTFS partition).

This appears to be a very isolated problem in that it seems only to be happening with specific types of external drives.

### Steps to reproduce

1)  Mount an external drive via USB.
2)  Create a new folder
3)  Open the folder and create a new file in it
4)  Exit the folder
5)  Use Nemo's search to search for the newly created file

### Expected behavior

The search should find any files on any mounted partition

**Comment by mbluett88** [comment]
I wanted to try a version of Nemo prior to 5.8.4 to see if the problem exists as well. But, I can't seem to do that without uninstalling Cinnamon. I tried it anyway but then upon trying to reinstall Nemo it states it is going to reinstall 5.8.4. This is under Linux Mint 20.3. Strange dependencies.

**Comment by mtwebster** [comment]
> before I upgraded to 5.8.4 it finds the file perfectly.

From what previous version? Search was completely revamped in nemo 5.0.

Where is the mount point for the drive? /media?  Where are you initiating the search from? Being somehow hardware or mount-specific doesn't make much sense - if you can navigate to the folder and see the file in nemo, then it should be able to find it with search.

There are some forbidden locations that nemo won't _enter_ during a search (`['/dev', '/proc', '/sys', 'dosdevices', '.git', '/run']` - perhaps it's being mounted in `/run`** whereas the other devices aren't?

Tested with a WD 500gb hard drive in external enclosure, USB-connected, NTFS partition, works fine if I search from the drive's root folder (`/media/<user>/data`) or from simply `/media`.


** `/run` has been removed from this list (1ae5a6d4e2) for the next upcoming point release.

**Comment by mbluett88** [comment]
> > before I upgraded to 5.8.4 it finds the file perfectly.
> 
> From what previous version? Search was completely revamped in nemo 5.0.

Sorry, 5.6.3

> 
> Where is the mount point for the drive? /media? 
Yes.

Where are you initiating the search from? Being somehow hardware or mount-specific doesn't make much sense - if you can navigate to the folder and see the file in nemo, then it should be able to find it with search.
> 
> There are some forbidden locations that nemo won't _enter_ during a search (`['/dev', '/proc', '/sys', 'dosdevices', '.git', '/run']` - perhaps it's being mounted in `/run`** whereas the other devices aren't?

They all mount in /media

**Comment by mbluett88** [comment]
I tried "ls -R | grep <filename>"  and it is able to find the file without problem.

**Comment by mbluett88** [comment]
I am VERY puzzled why this happens with only one of my external drives.

**Comment by mbluett88** [comment]
Finally discovered a problem in the 5.8.4 code that causes my search to fail.

In the function [b]should_skip_child[/b] (which is new code between Nemo 5.8.4 & 5.4.2), there is a Glib function that is supposed to return the file size (in bytes).

The code is as follows:
[code]
   if (g_file_info_get_attribute_uint64 (info, G_FILE_ATTRIBUTE_STANDARD_SIZE) == 0) {
       return TRUE;
   }
[/code]

Maybe the intention is to use this [b]should_skip_child[/b] function for things other than performing a search. But, if it is solely required for performing a search then obtaining the file size is really not necessary. So, this bit of code could be removed without impacting normal functions within Nemo and thus resolving the search problem I am experiencing.

**Comment by mtwebster** [comment]
This is already removed in current git master:
https://github.com/linuxmint/nemo/commit/1ae5a6d4e24e7ce82eac8a875a0b502aaf2d54a6

Hope there will finally be a new release in a day or two.

**Comment by mbluett88** [comment]
I am curious: Why was it removed?

**Comment by mbluett88** [comment]
Thanks for the update. I guess this bug report can be closed.

**Comment by Wikinaut** [comment]
same problem here
