### ISSUE TITLE
When copying or moving a web Link, nemo actually downloads the link instead

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#3294]
### Distribution

Arch

### Package version

nemo 5.8.4

### Frequency

Always

### Bug description

This is a bizarre bug. I think I just noticed it today but it's been present for a while just going off some of my files that this bug has affected.

### Steps to reproduce

1. Drag a URL out of your browser (I used CHromium) onto the Desktop or into any other folder
2. You will now have a "Link to ..." file which actually has a ".desktop" extension: 
![Screenshot at 2023-08-09 23-17-38-fs8](https://github.com/linuxmint/nemo/assets/7957590/2d389ca1-5b57-4607-a5af-a17d386a0759)
````
$ ls -l 'New Issue · linuxmint\nemo.desktop'
-rw-r--r-- 1 ad ad 200 Aug  9 23:19 'New Issue · linuxmint\nemo.desktop'

$ cat 'New Issue · linuxmint\nemo.desktop'
[Desktop Entry]
Encoding=UTF-8
Name=Link to New Issue · linuxmint/nemo
Type=Link
URL=https://github.com/linuxmint/nemo/issues/new?assignees=&labels=&projects=&template=bug_report.yaml
Icon=text-html
```` 
3. Drag it into another folder or just right click copy/paste it
4. "Link to ..." or "*.desktop" has not been copied into the new folder but the file has been downloaded instead: 
![Screenshot at 2023-08-09 23-22-01-fs8](https://github.com/linuxmint/nemo/assets/7957590/b31dc0c1-304e-43f3-8ab5-be6906d192d0)
````
$ ls -l /tmp/Untitled Folder'
total 36K
-rw-r--r-- 1 ad ad 34K Aug  9 23:21 new
````
Yes, the contents of `new` is the html of this page. 
5. And if you attempt to move the *.desktop file with cut/paste, you get an "Error while copying... Operation not supported" error: 
![Screenshot at 2023-08-09 23-28-16-fs8](https://github.com/linuxmint/nemo/assets/7957590/8c9a92a0-18e3-4cd6-92bb-656541ecbd72)

### Expected behavior

I'd expect the link file to be copied/moved and not for `nemo` to download the actual link.

**Comment by claudiux** [comment]
Same bug on LM21.2. After closing with 'Cancel' the 'Error while copying...' window, the file containing html appears.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/issues/3285
