### ISSUE TITLE
File size calculation problem?

### ISSUE THREAD

**Issue by wgm-gh** [linuxmint/nemo#3295]
### Distribution

Mint 20.2 Uma

### Package version

5.0.5

### Frequency

Always

### Bug description

Unless file size calculation may be done in more than 1 way, of which I'm unaware: 
Nemo seems to report a larger file size than elsewhere, both in the details shown in the main work area and in the file properties window.
May be related, and limited, to tars/archives.

The attached show 235MB in Nemo and 224MB on the LibreOffice and VirusTotal websites.

![2023-08-13_15-51-25_NemoSize](https://github.com/linuxmint/nemo/assets/71336538/63f9855d-cf33-4ee5-8b6c-653ff52604c5)
![2023-08-13_15-52-12_VtSize](https://github.com/linuxmint/nemo/assets/71336538/deea9f45-3ae1-4d91-8db6-e0b3db069676)
![2023-08-13_15-52-34_LoSize](https://github.com/linuxmint/nemo/assets/71336538/0ada3fe2-1f94-40b4-b24d-8129a0b3261e)

### Steps to reproduce

n/a

### Expected behavior

Display true file size. If there exist multiple "truths", explain or allow choosing which to display via Settings. Default should imho accord with what's widely considered standard.

**Comment by leigh123linux** [comment]
Does the issue exist in nemo-5.8.x as your version has been unsupported for many years.

**Comment by wgm-gh** [comment]
Unless you care to instruct me, maybe someone else can test - as I accept the Update Manager's recommendations, never get offered upated Nemos and don't know how to update manually.

**Comment by leigh123linux** [comment]
Try the latest mint release iso to confirm the issue still exists

**Comment by mtwebster** [comment]
There are multiple ways to express file sizes.

The file size is 224 'mebibytes' which converts to 235 megabytes

https://www.gbmb.org/blog/what-is-the-difference-between-megabytes-and-mebibytes-32

Preferences->Display, with the File Size combo, select 'binary' - you'll then see the 224 MiB (mebi) and total bytes..

**Comment by wgm-gh** [comment]
Thank you both. 

If the discrepancy's cause is (/"are"?) the different measures of size, the bug is the use of "MB" when the figure represent "MiB"s.

This is untested in the latest. I'm afraid I won't get to doing that soon.

**Comment by mtwebster** [comment]
The website's units are incorrect, not Nemo's:

![image](https://github.com/linuxmint/nemo/assets/262776/887cba43-2f2d-4ca0-837f-bb4eea7219b5)
![image](https://github.com/linuxmint/nemo/assets/262776/955b2cfa-4e6c-473d-9a09-d22937c9770f)
![image](https://github.com/linuxmint/nemo/assets/262776/01af7605-6757-40f1-beab-f3af541255d3)
