### ISSUE TITLE
Nemo 5.8.4 not generating icons as it did in 5.6.3

### ISSUE THREAD

**Issue by mbluett88** [linuxmint/nemo#3302]
### Distribution

Mint 20.3

### Package version

5.8.4

### Frequency

Always

### Bug description

Nemo 5.8.4 no longer generates icons as it did in 5.6.3.

### Steps to reproduce

Add some pdf or mp4's files to a folder.
Icons are not generated.

### Expected behavior

Nemo should generate icons as in 5.6.3.

**Comment by Jeremy7701** [comment]
Check file preview preferences.

**Comment by mbluett88** [comment]
> Check file preview preferences.

You mean Edit > Preferences > Preview right?

There are no specific settings for file types. So, I don't see how that will help.

**Comment by mbluett88** [comment]
Unfortunately, I cannot test this under LM 20.3 any longer because just this morning I wiped LM 20.3 and performed a fresh install of LM 21.2. I did this because I read that LM 21.2 supports ePub file icon images. However, after doing this fresh install I see NO generated icons. Both xreader & ffmpegthumbnailer are installed saying they are the latest versions. Also, cleared the thumbnails cache. That did not help. No errors when running nemo except for /var/lib/samba/usershares no such file or directory (which I fixed by installing samba).

**Comment by mbluett88** [comment]
Got this working. Nemo is now generating icons for everything, even ePubs.
I enabled "Show Thumbnails" in Edit > Preferences > Toolbar. Strange place to put that option. I would have though that should have been in the Preview section.

**Comment by Jeremy7701** [comment]
Nemo allows you to choose to have content-specific thumbnails switched on (or off) via a toolbar entry.
Some people like to work with massive folders which take a long time to thumbnail properly.
A python program constructs EPUB thumbnail's and it works 95% of the time because not all EPUB's contain strictly correct XML.

**Comment by mbluett88** [comment]
What you (Jeremy7701) have mentioned only works under Linux Mint 21.1 or 21.2 as those versions include handling ePub files. LM 20.3 did not handle this type of file with regard to reading meta-data.
