### ISSUE TITLE
Segmentation fault when paste file via Ctrl-v

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#331]
Nemo crashes if i try to copy files from an usb stick to my hdd. The crash uccurs every time i try. It does not crash when I use the context menu.

Here is the backtrace:

daniel@schleppi:~/workspace/auto-dj-crates/mixxx$ gdb nemo
GNU gdb (GDB) 7.5.91.20130417-cvs-ubuntu
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /usr/bin/nemo...Reading symbols from /usr/lib/debug/usr/bin/nemo...done.
done.
(gdb) run
Starting program: /usr/bin/nemo 
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec477700 (LWP 6753)]
[New Thread 0x7fffebc76700 (LWP 6754)]
[New Thread 0x7fffea1fd700 (LWP 6755)]

(nemo:6749): Nemo-Python-WARNING **: g_module_open libpython failed: /usr/lib/libpython2.7.so.1.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
ImportError: could not import gobject (error was: '/usr/lib/x86_64-linux-gnu/libpyglib-gi-2.0-python2.7.so.0: undefined symbol: _Py_ZeroStruct')

(nemo:6749): Nemo-Python-WARNING **: pygobject initialization failed

(nemo:6749): Nemo-Python-WARNING **: nemo_python_init_python failed
[New Thread 0x7fffe97f8700 (LWP 6756)]
[New Thread 0x7fffd9068700 (LWP 6758)]
[New Thread 0x7fffcdd9d700 (LWP 6760)]
[New Thread 0x7fffcd59c700 (LWP 6761)]
[Thread 0x7fffd9068700 (LWP 6758) exited]
[Thread 0x7fffea1fd700 (LWP 6755) exited]
[Thread 0x7fffcd59c700 (LWP 6761) exited]
[New Thread 0x7fffcd59c700 (LWP 6762)]
[New Thread 0x7fffea1fd700 (LWP 6763)]
[Thread 0x7fffcdd9d700 (LWP 6760) exited]
[Thread 0x7fffcd59c700 (LWP 6762) exited]
[New Thread 0x7fffcd59c700 (LWP 6764)]
[New Thread 0x7fffcdd9d700 (LWP 6765)]
[Thread 0x7fffcdd9d700 (LWP 6765) exited]
[Thread 0x7fffea1fd700 (LWP 6763) exited]
[New Thread 0x7fffea1fd700 (LWP 6766)]
[New Thread 0x7fffcdd9d700 (LWP 6767)]
[Thread 0x7fffcd59c700 (LWP 6764) exited]
[Thread 0x7fffea1fd700 (LWP 6766) exited]

(nemo:6749): GLib-GObject-WARNING **: invalid uninstantiatable type `(null)' in cast to`GtkIMContext'

(nemo:6749): GLib-GObject-WARNING **: invalid uninstantiatable type `(null)' in cast to`MeegoIMContext'

(nemo:6749): GLib-GObject-WARNING **: invalid uninstantiatable type `(null)' in cast to`MeegoIMContext'

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff50f8be7 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff50f8be7 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff50f9a81 in g_hash_table_remove_all ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fffd8663e49 in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#3  0x00007fffd8664eb6 in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#4  0x00007fffd8664f32 in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#5  0x00007fffd8665026 in ?? ()

   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#6  0x00007ffff72584be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff72022ec in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff72705ac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff53cd81b in ?? ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff53e62df in g_signal_emit_valist ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff53e6f92 in g_signal_emit ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00000000004d7648 in key_press_event (widget=<optimized out>,

```
event=<optimized out>) at nemo-icon-container.c:5513
```

---Type <return> to continue, or q <return> to quit---
#14 0x00007ffff72705ac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff53cd81b in ?? ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff53e62df in g_signal_emit_valist ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff53e6f92 in g_signal_emit ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff73b97a3 in gtk_window_propagate_key_event ()

   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff73bc2eb in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff727049c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff53cd620 in g_closure_invoke ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff53deaf8 in ?? ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff53e6996 in g_signal_emit_valist ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff53e6f92 in g_signal_emit ()

   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff726e555 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff7270185 in gtk_main_do_event ()

---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff6e9f5e2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#30 0x00007ffff5109f05 in g_main_context_dispatch ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff510a248 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff510a304 in g_main_context_iteration ()

   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff56aa52c in g_application_run ()

   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#34 0x000000000042c199 in main (argc=1, argv=0x7fffffffe088) at nemo-main.c:101

(gdb)

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 2 years?

**Comment by daschuer** [comment]
I cannot reproduce it wit Nemo 3.0.6
