### ISSUE TITLE
"Drop into current location" drops into parent folder after changing to subdir

### ISSUE THREAD

**Issue by arxo** [linuxmint/nemo#3314]
### Distribution

Mint 21.2

### Package version

5.8.4

### Frequency

Quite often

### Bug description

Directory changes are not processed properly by the "Drop into current location" area, causing dropped files to end up in a wrong location.

### Steps to reproduce

1. have a shortcut to a folder on the desktop (e.g. Home)
2. create new file dummy.txt on desktop
3. open Nemo via the folder shortcut
4. enter a sub folder of the opened folder (e.g. /home/myUser/Documents)
5. ctrl-drag the newly created file onto the "Drop into current location" area to copy it
6. release mouse button over "Drop into current location" (do NOT release it anywhere else)
![image](https://github.com/linuxmint/nemo/assets/43294041/52433522-e53c-4e5a-9e80-8c8b030922b1)

=>

File copied to /home/myUser/dummy.txt

### Expected behavior

File copied to /home/myUser/Documents/dummy.txt

**Comment by AlexFolland** [comment]
I tried to reproduce this issue with Nemo 6.0.0, but I can't figure out how to perform steps 5 and 6.  When I hold the Ctrl key before and/or during the drag of a file, I don't see a "Drop into current location" region on the screen anywhere.  How do I get this to appear?  Where does it appear, when you see it?  Can you show me a larger screenshot with more context for how it is shown when it appears?  Also, does this issue still manifest for you with Nemo 6.0.0 or later?

**Comment by mtwebster** [comment]
This feature was removed for 6.0. Instead, dropping items onto any blank areas of the view (even in occupied rows) will be considered a drop into the current location. Only drops onto actual text or icon will be considered as going *into* that child folder.

**Comment by AlexFolland** [comment]
Thanks for the clarification.  That matches my expectation as a user.
