### ISSUE TITLE
Attempt to open file: 'Invalid URL [. . .] No ":" in the uri

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#3317]
### Distribution

Mint 21.1

### Package version

5.8.5

### Frequency

Always

### Bug description

I have this file: `/home/<username>/NJ/Sync/PC_and_laptops/Heraclitus - handout.docx` (where <username> contains no spaces or unusual characters.

![image](https://github.com/linuxmint/nemo/assets/47056543/73a6dbe4-1d9f-4a6f-9417-84d3e44dcaf0)

### Steps to reproduce

Uncertain. The error message suggests perhaps that the hyphen within the leafname is the problem. Yet, renaming the file to remove the hyphen did not help. Getting Nemo to 'duplicate' the file did not help either - the duplicate had the same problem.

### Expected behavior

The file should open.

### Additional information

I can open the file from within LibreOffice Writer and so doing suggests no corruption of the file. Ditto for Word within VirtualBox.

The file was created - or moved to the local file system - by Syncthing.

```
$ stat 'Heraclitus - handout.docx'
  File: Heraclitus - handout.docx
  Size: 711708    	Blocks: 1392       IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 24382380    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/<username>)   Gid: ( 1000/<username>)
Access: 2023-09-29 11:18:31.405459924 +0100
Modify: 2023-09-28 22:02:40.411474700 +0100
Change: 2023-09-29 10:54:43.963655598 +0100
 Birth: 2023-09-29 10:54:43.843654677 +0100
```

EDITED to shrink the image.

**Comment by mtwebster** [comment]
Does  nemo open it  if you just rename it entirely  (no spaces or hyphens)?

What does:
```shell
gio info <file>
```
show?

Does it do the same if you right-click, Open with.. and choose the app there (maybe double-clicking the app  in the "other application" window)

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the response.

As I mean to have said, **removing all spaces and hyphens from the leafname** did not work. I add now that **removing all of those characters from the entire path** did not help either: when I turned the file inti `~/.h.docx`, the problem persisted.

**gio info**
```
$ gio info h.docx 
display name: h.docx
edit name: h.docx
name: h.docx
type: regular
size:  711708
uri: file:///home/<my_username>/NJ/Sync/PC_and_laptops/h.docx
local path: /home/<my_username>/NJ/Sync/PC_and_laptops/h.docx
unix mount: /dev/nvme0n1p2 /home ext4 rw,relatime,lazytime,stripe=32746
attributes:
  standard::type: 1
  standard::name: h.docx
  standard::display-name: h.docx
  standard::edit-name: h.docx
  standard::copy-name: h.docx
  standard::icon: application-vnd.openxmlformats-officedocument.wordprocessingml.document, x-office-document, application-vnd.openxmlformats-officedocument.wordprocessingml.document-symbolic, x-office-document-symbolic
  standard::content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  standard::fast-content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  standard::size: 711708
  standard::allocated-size: 712704
  standard::symbolic-icon: application-vnd.openxmlformats-officedocument.wordprocessingml.document-symbolic, x-office-document-symbolic, application-vnd.openxmlformats-officedocument.wordprocessingml.document, x-office-document
  etag::value: 1695934960:411474
  id::file: l66306:24382380
  id::filesystem: l66306
  access::can-read: TRUE
  access::can-write: TRUE
  access::can-execute: FALSE
  access::can-delete: TRUE
  access::can-trash: TRUE
  access::can-rename: TRUE
  time::modified: 1695934960
  time::modified-usec: 411474
  time::access: 1696015227
  time::access-usec: 688006
  time::changed: 1696015227
  time::changed-usec: 620004
  time::created: 1695981283
  time::created-usec: 843654
  unix::device: 66306
  unix::inode: 24382380
  unix::mode: 33204
  unix::nlink: 1
  unix::uid: 1000
  unix::gid: 1000
  unix::rdev: 0
  unix::block-size: 4096
  unix::blocks: 1392
  owner::user: <my_username>
  owner::user-real: 
  owner::group: <my_username>
  thumbnail::failed: TRUE
  thumbnail::is-valid: TRUE
```

**Open with, in Nemo**

'Open with' Libre Office Writer _works_.

**Comment by mtwebster** [comment]
Is that what you want to open it with?  Are you sure that's set to the 'default' handler: go into Other application.. make sure it's listed under 'Default Application'. If it isn't, select Libre Office and 'Set as default'. If it's already the default, change it to something else and back again.

**Comment by LinuxOnTheDesktop** [comment]
> Is that what you want to open it with?

Yes.

> make sure it's listed under 'Default Application'

I did not think of that - because I was so thrown by the error message. I find that the default for the filetype is . . 'AptUrl'. I don't know what that is. I set the default to Writer, and now opening the file in Nemo, via double-clicking, works. (Thank you.) So I suppose one question - perhaps not for you - is: how did AptUrl end up the default, and another question is: could the error message (if it owes to Nemo) be improved?

**Comment by LinuxOnTheDesktop** [comment]
I find that on another Mint PC, the default opener of the docx file was . . Calibre, which couldn't handle the file. But I suppose it's not up to Mint to stop every silly program from arrogating opening privileges.

**Comment by Jeremy7701** [comment]
If "someone" opens **ANY** docx file using a program name, there is nothing to stop them doing so. They may even say they always want to use this program and then it will apply to **every** docx file. So nemo is just performing normally.

**Comment by LinuxOnTheDesktop** [comment]
@Jeremy7701:

First:  'someone'?

Next: 'So nemo is just performing normally.' So, you think that the AptUrl-as-default owes to user error? Even if 'yes', is the consequent error message under Nemo's control? If again 'yes': how about making that message more informative?

**Comment by mtwebster** [comment]
The only way I could see improving it would be to point out what the application was that just failed. We could also maybe offer a button to get aat the open-with dialog from there.

**Comment by LinuxOnTheDesktop** [comment]
I'm not wholly sure that nothing Mint-y caused the file association to go awry. But presuming it didn't: both of your suggestions, @mtwebster, seem good to me; I think they'd increase Mint's user-friendliness.

**Comment by Jeremy7701** [comment]
The message is issued by the program.
Incidentally, apturl is the first program in the alphabetic list of GUI applications.

**Comment by mtwebster** [comment]
I started looking at making a change to the dialog and realized that is an apturl dialog, *not* nemo's.

I'm not really sure there's a way to deal with this in nemo. Programs use return codes to note something went wrong, but I don't really want nemo to need to 'watch' a process all the way until it ends to see if it fails (it could be .5s, it could be hours).

I've had this happen a couple of times in the past (wrong program association out of the blue), but this is usually quite a normal, unseen part of the system, and I don't want to make too big an issue of it. Other than with folders, right-clicking will always show how a selection will be opened if you double-click, however (first item in the menu).
