### ISSUE TITLE
how to install nemo on spoinkos aka kubuntu 23.10

### ISSUE THREAD

**Issue by DOOMMARINE117** [linuxmint/nemo#3327]
how do you install this on kubuntu?

**Comment by leigh123linux** [comment]
Try looking for a ppa repo that provides nemo

**Comment by DOOMMARINE117** [comment]
> Try looking for a ppa repo that provides nemo

ok, i got it installed. im trying to remember.

how to move bookmarks in a single line? when i try to mvoe teh bookmarks it goes to the fodler instead of just dropping the folders in bookmark. so how do i get it so i can just move them to the bookmarks? so ican reorganize them?
