### ISSUE TITLE
Location entry switches back to buttons 

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/nemo#3329]
### Distribution

Mint 21.2

### Package version

nemo 5.8.5

### Frequency

Always

### Bug description

The "Location entry" can be buttons or path in textbox right?
Well, even I am selecting to always so the path in textbox by clicking the corresponding toolbar button, the location entry switches back to buttons when I change directory.

![image](https://github.com/linuxmint/nemo/assets/16954451/e9c70db4-5c2a-4bc0-8411-b372b60ba061)
![image](https://github.com/linuxmint/nemo/assets/16954451/05016234-d267-4da3-bf6d-96b8df6ebcd6)

### Steps to reproduce

Open Nemo  
Toggle Location entry to show the path in textbox  
Change directory  
The Location entry is switched back to the button mode.

### Expected behavior

The Location entry should stay in user's selected mode

**Comment by Jeremy7701** [comment]
Set Preferences -> Display to show the full path in window/tab bars.

**Comment by mtwebster** [comment]
This is intended behavior now. Clicking the current location in the path *bar* will bring up the path *entry*, as will <kbd>Control</kbd>-<kbd>L</kbd> and `/`. One the location changes or you hit <kbd>Escape</kbd>, the pathbar will be restored.

You can default to the path entry full-time if you go to the View menu -> Toolbar.
