### ISSUE TITLE
File chooser dialog location bar does not support double-click like in standalone Nemo

### ISSUE THREAD

**Issue by yushiyangk** [linuxmint/nemo#3338]
### Distribution

21.2

### Package version

5.8.5

### Frequency

Always

### Bug description

In a standalone Nemo window, with "Location entry toggle" disabled, I can double-click on any item in the location bar to change it to a text entry, and then press Esc to change it back to a nice GUI view.

On the other hand, in "Open File" or "Save As" dialogs, the location bar has the same nice GUI view, but when I double click on it, nothing happens.

The reason I believe they are intended to behave identically is that in both the standalone window and in the dialogs, I can press Ctrl+L to change the location bar to the text entry.

I believe the lack of double-click support in the dialogs is simply an oversight.

Thank you.

### Steps to reproduce

1. Open a "Open File" or "Save As" dialog
2. Press Ctrl+L and observe that the location bar changes to a text entry, like in standalone Nemo
3. Press Ctrl+L again or press Esc to change it back to the default location bar
4. Double click on the location bar, but nothing happens, unlike standalone Nemo

### Expected behavior

The location bar should change to text entry when I double click on it.

**Comment by leigh123linux** [comment]
The File chooser dialog is part of GTK3, not nemo.
