### ISSUE TITLE
Nemo Actions are randomly ordered in ascending or descending

### ISSUE THREAD

**Issue by reasonset** [linuxmint/nemo#3342]
### Distribution

Manjaro Linux

### Package version

6.0.1

### Frequency

Quite often

### Bug description

The order of Nemo Actions used to be in ascending lexicographical order, but now they are in ascending or descending order each time the context menu is opened.

### Steps to reproduce

* Create multiple Nemo actions
* Right click

### Expected behavior

Always displayed in ascending order.

### Additional information

This issue is the same as the one referred to in the following URL:
https://forums.linuxmint.com/viewtopic.php?p=2355329&hilit=harukamy#p2355329

**Comment by mtwebster** [comment]
In the next release you'll be able to place actions in any order, as well as construct submenus to place related actions in.

https://github.com/linuxmint/nemo/commit/ef4adc04dfdec53a267768a113cd15f844831d94

**Comment by reasonset** [comment]
Thank you!!!
