### ISSUE TITLE
Nemo forgetting folder View and Zoom changes after Mint 21.3 update

### ISSUE THREAD

**Issue by Deiwos** [linuxmint/nemo#3352]
### Distribution

Mint 21.3

### Package version

6.0.2

### Frequency

Always

### Bug description

If I set a folder to, say, Compact View, then move to another directory or close the window and reopen to that directory, the View setting is reset to the default Icon View. The same is true with changing the Zoom setting to make icons larger or smaller; they are reset to default size when returning to the directory. This is Nemo opened normally as user, not as root.

### Steps to reproduce

Open Nemo, select Compact View, change directories, then go back.

### Expected behavior

View settings should be saved per directory, so that a directory set to Compact View will always be in Compact View whenever you navigate to it until such time as it is changed to a different view setting.

### Additional information

This started happening after the 5.8.5-victoria to 6.0.2-virginia update.

https://www.youtube.com/watch?v=uFG7le3qyHo

**Comment by Jeremy7701** [comment]
I get the "expected behaviour" in nemo 6.0.2 in LMDE6.

**Comment by Deiwos** [comment]
Update: several restarts later (???) Nemo is working as intended now so I guess I'll close this?
