### ISSUE TITLE
[Wayland] Drag and drop uri behaviour issues

### ISSUE THREAD

**Issue by ToxicMushroom** [linuxmint/nemo#3354]
### Distribution

Arch Linux x86_64

### Package version

nemo 6.0.2

### Frequency

Quite often

### Bug description

Some programs do not seem to play nicely with nemo providing uri's under `text/plain;charset=utf-8` mime types.
For example some website under chromium (e.g. **seafile**), some electron apps such as **discord**, or **code - OSS**.

The other file big managers _nautilus_ and _dolphin_ do not provide uris under `text/plain;charset=utf-8` and they do not have these issues.
I validated this correlation myself by using a simple wayland drag and drop producer client.

**Conclusion** being that the issue seems to be caused by the uri's under `text/plain;charset=utf-8`

_If required I can provide a minimal drag and drop source application in rust if you want to test this yourself._

### Steps to reproduce

1. launch `code` or `discord --ozone-platform-hint=auto` under a wayland compositor | receiver
2. open nemo in a folder with files you want to drag
3. drag a file into a surface in the receiver
4. see that the receiver does not give any signs of wanting to accept the dnd
5. drop the file, nothing happens.

### Expected behavior

step 4 would show the receiver wanting to take the file as with the other 2 mentioned file managers.
step 5 would accept the file.

### Additional information
What each file manager returned for different mime types
|                              | **Nemo**                       | **Nautilus**                   | **Dolphin**                    |
|------------------------------|--------------------------------|--------------------------------|--------------------------------|
| **text/uri-list**            | `file:///path.ext\r\n` | `file:///path.ext\r\n` | `file:///path.ext\r\n` |
| **text/plain**               | `file:///path.ext\r\n` | _Empty String_                             | `file:///path.ext`     |
| **text/plain;charset=utf-8** | `file:///path.ext\r\n` | `/path.ext`            | _Empty String_                             |

Description of each file manager's provided mime types (seems to be ignored by some drag and drop receivers)
```rust
// nemo
"x-special/gnome-icon-list", "text/uri-list", "UTF8_STRING", "COMPOUND_TEXT", "TEXT", "STRING", "text/plain;charset=utf-8", "text/plain", "DELETE"

// dolphin
"text/uri-list", "application/x-kde4-urilist", "application/vnd.portal.filetransfer"

// nautilus
"application/x-gtk-local-dnd", "application/vnd.portal.filetransfer", "application/vnd.portal.files", "text/uri-list", "text/plain;charset=utf-8"
 ```

**Comment by zeroeightysix** [comment]
Can reproduce

Dropping files from `nautilus` and other file managers to Discord on chromium works;
dropping the same files from `nemo` to the same application does not.
The same goes for the native Discord client, and other electron-based applications
