### ISSUE TITLE
This is a fundamental limit for any FAT32 file system.

### ISSUE THREAD

**Issue by alr86** [linuxmint/nemo#3355]
This is a fundamental limit for any FAT32 file system.
Not a bug.
Choose a different file system!

_Originally posted by @Jeremy7701 in https://github.com/linuxmint/nemo/issues/3343#issuecomment-1884893541_

I know that it is not a bug, but when I want to transfer a large file, it should show me a warning so that it does not become a bug. But nothing says

**Comment by leigh123linux** [comment]
Duplicate of #3343
