### ISSUE TITLE
[Feature request] A new file copy manager

### ISSUE THREAD

**Issue by nicu03** [linuxmint/nemo#336]
I think nemo needs a better looking (+ more features) file copy manager.
I'm thinking at something like:
http://codesector.com/teracopy
or
http://mike-ward.net/content/images/blog/Living-with-Windows-8_781F/filecopy.png
(sorry for the win 8 example, but IMO it looks pretty nice).

I know there is a multi-platform copy manager:
http://ultracopier.first-world.info/
but this cannot replace your default copy manager from nemo, it just stays in your notification bar, and it's quite a pain in the a... to use.

P.S. I would also like to contribute as a dev for this feature but I'm not sure if I have enough C experience for this job

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
I'm pretty sure this has been improved since this issue was opened. If people want additional things added/changed they can open new issues. I'm pretty sure there already are some.
