### ISSUE TITLE
Latest commit doesn't build as it's not finding `NEMO_DEBUG_ACTIONS`

### ISSUE THREAD

**Issue by stevenxxiu** [linuxmint/nemo#3364]
### Distribution

Arch Linux

### Package version

ef4adc04dfdec53a267768a113cd15f844831d94

### Frequency

Always

### Bug description

*Nemo* isn't building. It's not finding `NEMO_DEBUG_ACTIONS`in <https://github.com/linuxmint/nemo/blob/981c9ed2f155da2c8803da510ad81a2a8911e4e4/libnemo-private/nemo-action.c#L2013>. But this is only defined in <https://github.com/linuxmint/nemo/blob/981c9ed2f155da2c8803da510ad81a2a8911e4e4/libnemo-private/nemo-debug.h#L50> if `ENABLE_DEBUG` is set.

The broken commit is <https://github.com/linuxmint/nemo/commit/ef4adc04dfdec53a267768a113cd15f844831d94#diff-1a797e43a5446c59e66d25c8a2d8c21083b79c193545045c5419ce021c9c8d67>.

### Steps to reproduce

Build by:

```sh
meson --prefix=/usr \
      --libexecdir=lib/${pkgname} \
      --buildtype=plain \
      ..
ninja
```

### Expected behavior

*Nemo* builds.

**Comment by leigh123linux** [comment]
Plain buildtype fails for me as well, plain is the fedora default.
It compiles ok if I use.

--buildtype=debugoptimized
