### ISSUE TITLE
Symbolic folder icons have the wrong color on Dark Mode & don't inherit color from CSS

### ISSUE THREAD

**Issue by SploxFox** [linuxmint/nemo#3365]
### Distribution

21.3

### Package version

6.0.2

### Frequency

Always

### Bug description

Despite the icon being symbolic (meaning it should be able to inherit the theme's color), it is always black. This is fine on light mode, but on dark mode you can't see the icon at all.

### Steps to reproduce

Set your theme to dark mode and set the folder icon to a **symbolic icon**.

### Expected behavior

The icon should inherit the theme's `color`, since it is a symbolic icon. Instead, it remains black.

### Additional information

Using my theme (Catppuccin):
![NemoCatppuccin](https://github.com/linuxmint/nemo/assets/23511780/4c30093d-d420-415a-a922-80e0887a1347)

Using Adwaita:
![NemoAdwaita](https://github.com/linuxmint/nemo/assets/23511780/06cce2a7-e23f-4de0-8592-0190c295bde6)

**Comment by rcalixte** [comment]
Can you include a screenshot of the issue and which theme you're using?

**Comment by SploxFox** [comment]
Sure, I've updated the post to include screenies. I use a custom theme, Catppuccin, but the problem still persists using the builtins (such as adwaita) as well.

**Comment by mtwebster** [comment]
Symbolic icons aren't currently supported for files in the main view or tree sidebar, and there are no plans to at this time.

**Comment by SploxFox** [comment]
> Symbolic icons aren't currently supported for files in the main view or tree sidebar, and there are no plans to at this time.

That is... disappointing, to say the least.
