### ISSUE TITLE
Discovery of hosts and services using avahi (mDNS) does not work in nemo.

### ISSUE THREAD

**Issue by CoolAller** [linuxmint/nemo#3367]
### Distribution

Debian 12 bookworm

### Package version

5.6.4-1

### Frequency

Always

### Bug description

Discovery of hosts and services using avahi (mDNS) does not work in nemo. This function has been working in dolphin (KDE) for a long time.

### Steps to reproduce

Open Nemo -> Network, none of the hosts (mDNS) will be displayed.

### Expected behavior

Nemo should automatically discover and display mDNS hosts and be able to connect to them. I also think that the smb://ip-adress entry is inappropriate, since avahi is a separate service and does not require samba, so the smb:// entry is incorrect.

**Comment by mtwebster** [comment]
This isn't something we'd implement in nemo directly, but inherit from gvfs (virtual filesystem).

Assuming this describes what you're after: https://gitlab.gnome.org/GNOME/gvfs/-/issues/506

It looks like [this commit](https://gitlab.gnome.org/GNOME/gvfs/-/commit/26e350041dcc5c3dfdad3516c0fdc45a114ed851) implements the functionality, but it's very recent and probably not available on most distros yet.

KDE uses its own vfs implementation.

**Comment by CoolAller** [comment]
[mtwebster](https://github.com/mtwebster) WS-Discovery is of course good, but I'm talking about mDNS (avahi). And yes, mDNS support is already available in Windows 10. I don’t know how this is implemented in dolphin, but as soon as I install it in Cinnamon, I immediately get the functionality that is required - devices are displayed in the network using mDNS.
