### ISSUE TITLE
GIMP Thumbnails reset to GIMP Icon after View Reload

### ISSUE THREAD

**Issue by robinboncoeur** [linuxmint/nemo#3369]
### Distribution

Mint 21.1

### Package version

Nemo 5.6.4

### Frequency

Always

### Bug description

I am having a problem with Nemo thumbnails of GIMP XCF files. If I save an image as .xcf file, the thumbnail reflects the image. However, as soon as I do a refresh of a folder [Alt] [View] [Reload] in Nemo, the icon reverts back to the default GIMP icon, which is singularly useless.

In Nemo, I've tried to resolve this issue by

* selecting the Show Thumbnails under View;
* in Preferences-> Preview Previewable Files-Show Thumbnails [Yes] ;
* installed dconf-editor, jumping through all the hoops there too. 
 
No joy: the icon will display a thumbnail of the image immediately upon saving the image in GIMP (a rather blurry thumbnail, to be sure) but when I refresh Nemo, it's back to that completely useless GIMP icon.

Is this a Nemo or a GIMP issue?

### Steps to reproduce

I save an image as .xcf file, the thumbnail reflects the image. However, as soon as I do a refresh of a folder [Alt] [View] [Reload] in Nemo, the icon reverts back to the default GIMP icon

### Expected behavior

The icon is a thumbnail of the image, respecting the settings of Nemo and dconf-editor

**Comment by Lowrida** [comment]
Same here, but with xcursor files. Standard thumbnail in Nemo, but when i open the file in Gimp suddenly Nemo has a thumbnail for it. When i close Gimp (not even saving the cursor file), wait a few seconds and refresh Nemo the thumbnail is back to a standard useless thumb.

**Comment by mtwebster** [comment]
Normal behavior on reload is to wipe any existing thumbnail. It gets regenerated automatically. Unfortunately gimp does not provide a proper thumbnailing utility for file managers to use - it only happens while using gimp.

I'll try to add something to our [thumbnailers repo](https://github.com/linuxmint/xapp-thumbnailers) if I can figure out the command line to do this with gimp-console.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/xapp-thumbnailers/commit/034836faa6f1b56f2263c8a062e4581ab540da73

**Comment by Lowrida** [comment]
What about xcursor files? They are not made with Gimp, but installed as a package. They do not show a thumbnail in Nemo. I used Gimp as an example that it briefly shows a thumbnail, but after closing Gimp it is back as a standard thumbnail.

**Comment by mtwebster** [comment]
If you discover any other file types let me know.

**Comment by Jeremy7701** [comment]
A few EPUB's don't show a correct thumbnail - probably due to defective file formatting.
They are readable by EPUB readers and do show a cover picture.
Instead of a text file thumbnail, could a generic EPUB thumbnail be shown for these cases?

Example:-
But change the `.zip` to `.epub` because Github doesnt accept epub files.
[The Vampyre a Tale by Polidori, John William.zip](https://github.com/linuxmint/nemo/files/14388384/The.Vampyre.a.Tale.by.Polidori.John.William.zip)

Present Thumbnail:-
![Screenshot from 2024-02-23 17-48-47](https://github.com/linuxmint/nemo/assets/52585119/2217a6f0-ba87-4878-b7b4-6a1d61bea98a)

**Comment by mtwebster** [comment]
That's an icon theme issue.  For example, here's Yaru:
![image](https://github.com/linuxmint/nemo/assets/262776/3d77001c-5a78-445a-814c-e23996aae85f)

I meant any other file types gimp can thumbnail. I'll look into getting the Mint icon theme fixed for epubs

**Comment by robinboncoeur** [comment]
> [linuxmint/xapp-thumbnailers@dc150fa](https://github.com/linuxmint/xapp-thumbnailers/commit/dc150fa8f51a499667dc8d55ee75297c74564f5b)

Thanks for providing a solution, MTWebster. I'm a bit unclear how I would implement this... sorry, I'm not a particularly switched-on Linux user.
