### ISSUE TITLE
Remembering view/arrange settings per folder does not work (v6.0.2)

### ISSUE THREAD

**Issue by mildly-useful** [linuxmint/nemo#3375]
### Distribution

Mint 21.3 Edge

### Package version

6.0.2

### Frequency

Always

### Bug description

Since quite some time ago, very likely after I updated from Mint  21.2 to 21.3 (because I remember this feature working before the upgrade), the file manager doesn't remember view settings (AND the Arange Items setting) per folder on any of my HDDs.

I could enable/disable "Inherit view type from parent" from the Views section, or "Ignore per-folder view preferences," and both settings would have an effect. Now, both these options have no effect per folder.  Something was screwed up when I upgraded, is my guess. 

### Steps to reproduce

Select any of the Icon/List/Compact view in a folder, then exit the file manager or go back to a previous folder. When you re-enter the folder you changed the view settings on, the preference was not saved, it's still using the default view option. This also applies to the Arrange Items option. 

Turning off  "Ignore per-folder view preferences" still doesn't solve the issue.  "Inherit view type from parent" ON or OFF doesn't solve the issue.

### Expected behavior

I expect that in each folder, as long as "Ignore per-folder view preferences," is turned off, that the last view settings (list, icon, etc.) are saved for that specific folder.  I also expect the Arrange Items setting to be remembered. 

### Additional information

Nemo only remembers the custom Arrange Items settings in the Home folder, but even in there, it still doesn't remember the View settings. The only way I can change arranging and viewing settings is globally, by changing the Default View/Arranging.

I don't know what got broken that affects remembering these settings per folder. Any combination of turning on/off "Inherit view type from parent" and "Ignore per-folder view preferences" has no effect on making the per-folder feature working properly. 

I also don't see any relevant Nemo info in the .xsession-errors file. 

OS: Linux Mint 21.3 x86_64 (Edge)
Kernel: 6.5.0-21-generic
DE: Cinnamon 6.0.4

**Comment by mtwebster** [comment]
Are there any messages if you run nemo from a terminal? (make sure any existing nemo windows are closed first).

Try:
```
GSETTINGS_BACKEND=memory nemo
```
This will ignore your existing preferences for the duration of the process only. Try reproducing the behavior like you described above.

**Comment by mildly-useful** [comment]
I launched Nemo from the terminal using "GSETTINGS_BACKEND=memory nemo" and this time the feature worked as intended. When I was shifting through folders, the individual preferences for each folder has been saved, as well as the Arrange Items settings. And "Inherit view type from parent" also worked as intended. 

I do get some error messages though. I got this one time only:

`sys:1: Warning: g_object_weak_unref: couldn't find weak ref 0x7fab0ff8e240(0x564af8bad6c0)`

And then this several more times:

```
Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.
```

So yeah, launching it this way through the terminal does work. Thanks! Is there anything I can do to fix Nemo so it works normally?

**Comment by mildly-useful** [comment]
Huh... this is weird. Apparently, launching Nemo through "_GSETTINGS_BACKEND=memory nemo_" just once, then browsing through folders a bit and changing view/arrange preferences for a bunch of folders, and enabling and disabling "Inherit view type from parent" has fixed this issue for me. 

Now the features I had issues with work as intended, even after rebooting three times and opening folders normally (just double clicking, no terminal stuff). Though the terminal errors are still present if I launch it with that command. I don't know what's up with that.

**Comment by mtwebster** [comment]
Those warnings are 'normal'. That's very weird it fixed the issue.

I guess I'll close this for now - if it starts happening I'll reopen and we can troubleshoot further.

**Comment by mildly-useful** [comment]
Thanks for helping me solve it!

**Comment by mildly-useful** [comment]
Well, after 3 weeks later of this working, I changed my theme settings from the Cinnamon Themes menu. Stuff like icons, cursor, etc. The problem re-appeared, and it was, again, solved by  launching Nemo through "GSETTINGS_BACKEND=memory nemo" just once. I feel like I had to mention it, that changing the Theme settings also has an effect on this weird issue.

**Comment by Rik44444** [comment]
> Well, after 3 weeks later of this working, I changed my theme settings from the Cinnamon Themes menu. Stuff like icons, cursor, etc. The problem re-appeared, and it was, again, solved by launching Nemo through "GSETTINGS_BACKEND=memory nemo" just once. I feel like I had to mention it, that changing the Theme settings also has an effect on this weird issue.

Just here to say thank you for this workaround !!!! it worked and this will save me soo much irritation and time. I think you should re-open this issue, bc clearly it should be fixed without the workaround.  @mildly-useful
