### ISSUE TITLE
Persistent tabs/view

### ISSUE THREAD

**Issue by vxnick** [linuxmint/nemo#339]
It'd be great to have an option within Nemo to remember which tabs and directories I'm viewing so I don't have to setup my workflow when re-opening Nemo after a reboot, for example.

**Comment by rudametw** [comment]
+1... This would be very nice to have !

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
