### ISSUE TITLE
l_auncher? “The stupid underscore” not only here :smile: 

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/nemo#3395]
### Distribution

doesn't matter

### Package version

master branch

### Frequency

Always

### Bug description

https://github.com/linuxmint/nemo/blob/0961f07b4e0476746956ee19a592361b360dae38/data/nemo-actions/90_new-launcher.nemo_action.in#L3
Why are we writing l_auncher instead of just launcher? Ok, it may just be a typo, but this is something common: _Add, A_dd or in German A_bbrechen which would be something like C_ancel in english. I already encountered this in gitg and libreoffice.

### Steps to reproduce

View bug description

### Expected behavior

launcher instead of l_auncher

**Comment by JosephMcc** [comment]
> Please don't be angry if my language isn't very friendly, it's all okay 😄

If you feel the need to state this then maybe you should think about the way you are wording things.

**Comment by carlosmintfan** [comment]
> > Please don't be angry if my language isn't very friendly, it's all okay 😄
> 
> If you feel the need to state this then maybe you should think about the way you are wording things.

Well I didn't really write anything very bad, I just wrote this in a quick way and it's so a common issue in Linux apps :confused:

**Comment by carlosmintfan** [comment]
Just one example in gitg:
![gitg example](https://github.com/linuxmint/nemo/assets/118076740/740e9851-0498-4940-8a2b-f04026e20bcb)

**Comment by carlosmintfan** [comment]
I also encountered this in libreoffice...

**Comment by claudiux** [comment]
_Add means that 'a' is a shortcut to execute it.
l_auncher means the same thing.

**Comment by carlosmintfan** [comment]
> > > Please don't be angry if my language isn't very friendly, it's all okay 😄
> > 
> > 
> > If you feel the need to state this then maybe you should think about the way you are wording things.
> 
> Well I didn't really write anything very bad, I just wrote this in a quick way and it's so a common issue in Linux apps 😕

Rewrote this anyway

**Comment by carlosmintfan** [comment]
> _Add means that 'a' is a shortcut to execute it. l_auncher means the same thing.

Well, the way it looks, it doesn't look very good.

**Comment by carlosmintfan** [comment]
But if this is expected behaviour, leave it like that. But why do we need l_auncher then instead of _launcher? sometimes at the beginning, sometimes after the first letter.

**Comment by claudiux** [comment]
Maybe because l is another shortcut?

**Comment by carlosmintfan** [comment]
> Maybe because l is another shortcut?

But this is uglifying strings. If l is the shortcut, shouldn't the underscore be at the beginning?

**Comment by claudiux** [comment]
That depends on the user language and the action.

It's best to avoid changing users' habits; they usually protest when we take the liberty of doing so.

**Comment by carlosmintfan** [comment]
All right. What I hadn't thought of when reading that source file is that the underscore prefix is _rendered_ as an underscore directly under the letter, not before it. But this isn't done correctly in gitg and somewhere in LibreOffice, so when reading this I just thought about some stupid common behaviour and not that this is a rendering issue (but not in nemo).

**Comment by mtwebster** [comment]
The underscore tells the menu item or whatever whatever to make the following character a 'mnemonic' accelerator key, which, while that menu is open, will launch that item if used.

This underscore can be anywhere in the string, because:
a) There may be multiple menu items that start with the same character, or
b) Translators may move them to some character that makes more sense in their language.

If you tap alt while a menu is open, generally those underscores will appear (depending on what library the program uses).

**Comment by carlosmintfan** [comment]
> The underscore tells the menu item or whatever whatever to make the following character a 'mnemonic' accelerator key, which, while that menu is open, will launch that item if used.
> 
> This underscore can be anywhere in the string, because: a) There may be multiple menu items that start with the same character, or b) Translators may move them to some character that makes more sense in their language.
> 
> If you tap alt while a menu is open, generally those underscores will appear (depending on what library the program uses).

I understand, and thank you for explaining this. What I thought of were only the bugs I saw in gitg and LibreOffice where this wasn't rendered correctly so I thought of some "stupid convention"…
