### ISSUE TITLE
Nemo Segfault

### ISSUE THREAD

**Issue by charles-vomacka** [linuxmint/nemo#340]
Nemo segfaults when trying to browse Windows network. 

If i click the network location button and then double click the Windows Network icon, Nemo segfaults:

kernel: [ 1624.842870] nemo[2998]: segfault at 0 ip 00000000004ba0c9 sp 00007fff91839aa0 error 4 in nemo[400000+166000]

I have had this occur on machines running Linux Mint 14 Cinnamon 64 and Linux Mint 15 Cinnamon 64 with current updates when trying to browse my network. If I open the location bar and type in an smb location (for example: smb://falcon) nemo will display the shares available on that machine and allow me to mount them. It only crashes when trying to browse the entire network.

**Comment by Vahan86** [comment]
@charles-vomacka, does this issue still occur in Mint 18 (Nemo 3.0.6)?

**Comment by charles-vomacka** [comment]
@Vahan86, no, I have not had this occur in Mint 18 Cinnamon 64 Nemo 3.0.6

**Comment by Vahan86** [comment]
@charles-vomacka, thanks for reply, in this case can you please close this issue?
