### ISSUE TITLE
Nemo can't start non-default terminal

### ISSUE THREAD

**Issue by awvalenti** [linuxmint/nemo#3412]
```
 * Cinnamon version (cinnamon --version): Cinnamon 5.2.7
   - Using the daily builds PPA? No
 * Distribution: Mint 20.3
 * Graphics hardware: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller *and* native driver
 * 64 bit
 ```

**Issue**
Nemo can't start non-default terminal.

**Steps to reproduce**
- On Preferred Apps, set Terminator as default
- On Nemo, right-click empty space and click Open In Terminal
- Alternatively, click the Open Terminal button (it must be previously enabled on Edit > Preferences > Toolbar)

**Expected behaviour**
Opens Terminator

**Actual behaviour**
Nothing happens.

**Other information**
Tried opening Nemo via terminal to see if there was any output logged, but there wasn't.

May be related to linuxmint/cinnamon#9720.

GIF below shows the whole thing. It works with gnome-terminal, but not with Terminator. Terminator icon is different because I changed it via cinnamon-menu-editor.

![Peek 31-03-2022 12-35](https://user-images.githubusercontent.com/834921/161094773-d29d198e-7375-46d0-94d7-80396f8a91d5.gif)

**Comment by rcalixte** [comment]
This should be resolved by Nemo 5.8.x.
