### ISSUE TITLE
Can't compress archives

### ISSUE THREAD

**Issue by nazar-pc** [linuxmint/nemo#3419]
### Distribution

Ubuntu 24.04

### Package version

6.0.2

### Frequency

Always

### Bug description

Can't compress an archive. There are some formats that Nemo recognizes as archives, for which only extraction is available. For example I'm trying to compress FreeCAD project file (which is probably a zip archive internally), while uploading to GitHub requires zip archive. But I can't do that with Nemo conveniently.

### Steps to reproduce

Have zip archive file, try to compress it again into 7z, notice there is no compression button in the UI

### Expected behavior

Compression should be available for all files, even if Nemo recognizes the file as an archive for whatever reason

**Comment by leigh123linux** [comment]
File your issue against ubuntu file-roller,

https://launchpad.net/ubuntu/+source/file-roller

**Comment by nazar-pc** [comment]
I don't think it has anything to do with Ubuntu or file-roller, but I do see that I should have filed it in https://github.com/linuxmint/nemo-extensions since that is where integration comes from. Can you maybe move the issue there?

**Comment by leigh123linux** [comment]
The nemo-file-roller extension is just a front-end for file-roller.

**Comment by nazar-pc** [comment]
And this issue is about that frontend :shrug:

**Comment by Jeremy7701** [comment]
If you try to compress a single compressed file you will not save any space, so it's a pointless exercise.
If you want to archive multiple files into a single file, try `tar`.

**Comment by nazar-pc** [comment]
> If you try to compress a single compressed file you will not save any space, so it's a pointless exercise.

It is up to me to decide whether it is pointless or not. As already said in the very first message, I wanted to compress a file that I don't see as an archive in order to upload it to GitHub that doesn't accept original file natively, but does support zip file. It is not always about saving space.

GitHub doesn't support tar either and tar is a bad format due to how slow it is to open and extract individual files comparing to zip or 7z for example. I can compress any format with CLI, but my bug report is about Nemo (or specifically its extension), not CLI tools available of my Linux distribution.

**Comment by nazar-pc** [comment]
So does my explanation make sense, can this issue be moved to correct location, please?
