### ISSUE TITLE
Rename is grayed out 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#342]
Sometime the context menu option is greyed out but click able. 

I have just notice it with 1.8.2 on ubuntu Precise. All Folers are effected 
After nemo restart 
killall nemo
the issue is gone.  

I am not sure but I think I had similar issues on Ubuntu Raring, but there Rename was grayed out and not clickable at least a samba mount effected there.

**Comment by Vahan86** [comment]
@daschuer, is this still an issue for you with Nemo 3.0.6?

**Comment by daschuer** [comment]
I am now on Nemo 3.0.6 on Ubuntu Xenial and I have not seen the issue since long.

**Comment by Vahan86** [comment]
@daschuer, thanks for reply, in this case can you please close the issue?
