### ISSUE TITLE
Nemo hangs when emptying the trash

### ISSUE THREAD

**Issue by rei-zero246** [linuxmint/nemo#3428]
### Distribution

Mint 21.3

### Package version

nemo 6.0.2

### Frequency

Always

### Bug description

Nemo freezes when trying to empty the trash, or calculating the size of the tash space.

### Steps to reproduce

Empty trash or loading the trash properties.

### Expected behavior

An empty trash or size of the trash.

### Additional information

$ nemo

(nemo:6009): Gtk-WARNING **: 11:18:19.360: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Nemo-Share-Message: 11:18:19.712: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.

(gdk-pixbuf-thumbnailer:6041): GVFS-WARNING **: 11:18:51.609: The peer-to-peer connection failed: Timeout was reached. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(gdk-pixbuf-thumbnailer:6044): GVFS-WARNING **: 11:18:51.638: The peer-to-peer connection failed: Timeout was reached. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(gdk-pixbuf-thumbnailer:6048): GVFS-WARNING **: 11:18:51.658: The peer-to-peer connection failed: Timeout was reached. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(nemo:6009): GVFS-WARNING **: 11:19:03.559: The peer-to-peer connection failed: Timeout was reached. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
Nemo-Share-Message: 11:19:26.315: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.

**Comment by rei-zero246** [comment]
$ nemo --quit && nemo
Could not register nemo as a remote: Timeout was reached

**Comment by rei-zero246** [comment]
Secondary disk mounting at startup this way: rw,nosuid,nodev,relatime,uid=1000,gid=1000,windows_names,iocharset=utf8,uhelper=udisks2

**Comment by mtwebster** [comment]
Check if you have any invalid mount points or missing nfs drives, etc.. There's a bug in nemo that can cause it to hang while polling for mounts.

**Comment by rei-zero246** [comment]
It may have had something to do with the mounted drive; I changed the mounting parameters and will monitor. I already deleted the files from their respective trash folders.

**Comment by rei-zero246** [comment]
Making adjustments to the mount point resolved the issue.
