### ISSUE TITLE
Warning on action fields is not consistent with example action

### ISSUE THREAD

**Issue by wucke13** [linuxmint/nemo#3437]
The warning speaks about fields such as `Label` which are not at all present in the example.

https://github.com/linuxmint/nemo/blob/962d0617e72d8e0b1878b933a8ff8a41f33f486c/libnemo-private/nemo-action.c#L985-L987

https://github.com/linuxmint/nemo/blob/962d0617e72d8e0b1878b933a8ff8a41f33f486c/files/usr/share/nemo/actions/sample.nemo_action#L1-L160

**Comment by rcalixte** [comment]
It is probably a typo for `Name`.

**Comment by mtwebster** [comment]
Warning fixed, better documentation added.
