### ISSUE TITLE
Icons changed after system update

### ISSUE THREAD

**Issue by yuzhen1024** [linuxmint/nemo#3444]
### Distribution

arch

### Package version

6.2.6

### Frequency

Always

### Bug description

update packages

### Steps to reproduce

.

### Expected behavior

![2024-08-08T18:48:47,178084976+08:00](https://github.com/user-attachments/assets/9cb6c1e6-e8dc-4690-ad52-5bc2ee1b9584)
![2024-08-08T19:23:15,993928025+08:00](https://github.com/user-attachments/assets/6f06c455-b5aa-488d-b355-2abff8cba759)

- Folder and file icons appear blurry.
- In the Nemo file manager, options are displayed without icons.(as shown in the image)

### Additional information

I apologize if this isn't the appropriate place to raise this issue. The icon changes are also occurring in the GNOME file manager. I believe the main factor is related to the GTK icon theme. While I have some understanding of the cause, I'm seeking assistance to resolve this problem. So far, I've tried switching between all available icon themes, but the issue persists.

**Comment by mtwebster** [comment]
What icon theme is that in the images?

Is adwaita-icon-theme installed?

Please provide more system info - graphics, etc...

What desktop is this? Cinnamon? or something else.

**Comment by mtwebster** [comment]
> The system is using Wayland as the display server with a tiling desktop environment.

there are a thousand tiling desktops, why be vague?

I'm pretty certain there's some issue in your environment, but I have no idea what. Have you looked at bug trackers for your tiling desktop for similar issues? The fact it's not unique to Nemo pretty much confirms this isn't something we can really address here.
