### ISSUE TITLE
Document does not show in Nemo, but does in LibreOffice save as listing

### ISSUE THREAD

**Issue by TheUnhappyUser2024** [linuxmint/nemo#3451]
### Distribution

Linux Mint 21.2 Victoria     base: Ubuntu 22.04 jammy   Desktop: Cinnamon 5.8.4

### Package version

5.85

### Frequency

Only occasionally

### Bug description

Go to a desired directory. List of documents shows on screen. File I am looking for does NOT show in Nemo. Use LibreOffice to open file that was just created. Do File Save As and two copies of file with similar names shows in LO listing. Look at Nemo. Neither file shown there. Close Nemo window. Open Nemo new window. File still does not show. 
Close all occurrences of Nemo. Relaunch Nemo go to directory. Files now show up.
![How can I have a document open in LO and not have it show in directory -with versions of LO and Nemo 2024-08-26_11-19](https://github.com/user-attachments/assets/ab8faae2-e366-4e28-81f1-203ce71c76d6)

### Steps to reproduce

See description above.

### Expected behavior

File shows when I open new window

**Comment by mtwebster** [comment]
Can you try nemo 6.2 (maybe on a live mint iso)? I can't reproduce it.

**Comment by TheUnhappyUser2024** [comment]
I am sorry, but the only version available from your website is for the 5.8.5+victoria for my version of mint. I am unable to spend time running a live disk.
Thank you for trying to help. i guess i will just have to live with this issue until you update your version for mint.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by mtwebster** [comment]
Mint 21.2 will not being getting this update. To continue getting cinnamon/nemo updates you'll need to upgrade the system.
