### ISSUE TITLE
File / Create New Document / Empty Document creates a one byte file rather than a genuinely empty zero-length one

### ISSUE THREAD

**Issue by superian** [linuxmint/nemo#3452]
### Distribution

Mint 22

### Package version

6.2.8

### Frequency

Always

### Bug description

Creating an "empty document" creates a one-byte length file, a single LF character.

A file with contents is not an empty file!

### Steps to reproduce

File / Create New File / Empty Document menu. 
Name it.

### Expected behavior

Empty files were zero length files on GNOME 2 and remain so with MATE's Caja file browser.

This should be just like 'touch' for a filename that doesn't currently exist: a zero length file is created with that filename.

### Additional information

On some file systems, this has uses a cluster of disk space that would otherwise be unnecessary.

Various scripts may (and here, do) rely on "empty" files having zero length.

**Comment by mtwebster** [comment]
duplicate: https://github.com/linuxmint/nemo/issues/3450
