### ISSUE TITLE
can't browse lan computer with sftp

### ISSUE THREAD

**Issue by lm2lm2** [linuxmint/nemo#3478]
### Distribution

linux mint debian

### Package version

5.8.5

### Frequency

Always

### Bug description

if i try to reach sftp://user@1.2.3.4 i can't obtain via sftp the remote location.
on others systems, eg with thunar : it works.

### Steps to reproduce

if i try to reach sftp://user@1.2.3.4 i can't obtain via sftp the remote location.
on others systems, eg with thunar : it works.

### Expected behavior

software being able to browse ipv4/6 remote folders via sftp

**Comment by leigh123linux** [comment]
The issue doesn't reproduce.
I use nemo daily to browse and transfer files on remote sftp shares.
