### ISSUE TITLE
removable unopened sidebar folder shortcut drop, always copies.

### ISSUE THREAD

**Issue by splace** [linuxmint/nemo#348]
if you have a shortcut in the sidebar to an unmounted FS, shows a yellow indicator, then mount the FS and drag a file to that shortcut from the same FS, you get a copy rather than relink. after the folder is opened once, no yellow indicator, you get the expected relinking, ie a move.

nemo 1.8.3

(not a big deal, but added here for info.)

**Comment by Vahan86** [comment]
@splace, is this still an issue for you in Nemo 3.0.6?

**Comment by splace** [comment]
not currently running nemo, could close this, but if left open its more likely to remind me to try next time i use.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for a long time?
