### ISSUE TITLE
Search uses slow and unmaintained odt2txt

### ISSUE THREAD

**Issue by rosenbergd** [linuxmint/nemo#3481]
### Distribution

Mint 21.3

### Package version

6.0.2

### Frequency

Always

### Bug description

When searching by content, `odt2txt` is used whenever encountering certain file types.

The problem is that `odt2txt` is known to be slow on large documents (there's also an issue on the package's git repo indicating it's because it uses regex instead of an XML parser).

When searching, ODS files simply existing in the search location is enough to delay the search anywhere from a few minutes to a few hours depending on size and quantity.

Additionally, this pegs a single thread at 100% per search attempt and doesn't stop when the search is stopped (either by pressing the `x` button or closing the nemo window).

### Steps to reproduce

- Search by content in a folder with a large ODS file
- Let the search continue, or alternatively, stop the search by either pressing the `x` button on the searching indicator (bottom right) or closing the window
- Look for `odt2txt` instance spawned using task manager of choice (htop, etc.)

### Expected behavior

A more efficient alternative should be used to search, and when the search is stopped in either way, it should close all sub-processes generated as a result of the search.

### Additional information

I unfortunately can't share the files that slowed down search since they're under NDA, but most decently large ODS files experienced this behaviour. The files that experienced this also had formulas, but after removing the formulas, they were still just as slow to search.

These files were both 1MB+.

**Comment by Jeremy7701** [comment]
Content searching is always going to be slow, especially for ODS files which need decompressing, converting and only finally searching. So a full conversion to text occurs (you have to process the whole file).

Removing the file `/usr/share/nemo/search-helpers/libreoffice.nemo_search_helper` would cause ODS files to be omitted from content level searching - if that is what you would prefer?

**Comment by mtwebster** [comment]
I had a look at the format, I should be able to write something simple (and hopefully fast) to extract the text for the next release, and drop our dependency on odt2txt.

**Comment by claudiux** [comment]
Any .odt file can be extracted with `unzip`. There is a `content.xml` file containing the text (XML tags must be removed to obtain text only). The search can then be applied to the result.

**Comment by rosenbergd** [comment]
@Jeremy7701 - yes, I expect it to be slow, but when I say slow, I'm talking about >5 minutes for 1 file. In this case, >20 minutes for 1x 1.9MB ODS file (I killed the process after 20 minutes, I don't know how long it would have taken if I left it running).

> I had a look at the format, I should be able to write something simple (and hopefully fast) to extract the text for the next release, and drop our dependency on odt2txt.

That's great news, thanks

**Comment by Jeremy7701** [comment]
Sorry, didn't appreciate!
20 minutes is ridiculous - 2Mbytes is not large

**Comment by mtwebster** [comment]
I've got a basic processing script - there ended up being a library for open-document file types that seemed simplest for now. Before I finalize it I wouldn't mind some feedback on its speed and usefulness. It extracts file metadata (author, etc...) as well as text content. No formatting is preserved, so the preview snippet (tooltip on the search result) won't be all that useful 'visually'.

create this file in `/usr/bin/nemo-odf-to-txt`, then run `sudo chmod +x /usr/bin/nemo-odf-to-txt` to make it executable:
```python
#!/usr/bin/python3

import sys

from odf.opendocument import load
from odf.text import P

path = sys.argv[1]
doc = load(path)

for element in doc.meta.childNodes:
    if str(element) == "":
        continue
    print(f"{element.tagName}: {element}", flush=True, file=sys.stdout)

print("\n", flush=True, file=sys.stdout)

for element in doc.getElementsByType(P):
    if str(element) == "":
        continue
    print(element, end=", ", flush=True, file=sys.stdout)

print("\n", flush=True, file=sys.stdout)

exit(0)
```
and this file as `/usr/share/nemo/search_helpers/odf.nemo_search_helper`:
```desktop
[Nemo Search Helper]
TryExec=nemo-odf-to-txt;
Exec=nemo-odf-to-txt %s
MimeType=application/vnd.oasis.opendocument.text;application/vnd.oasis.opendocument.spreadsheet;application/vnd.oasis.opendocument.presentation;application/vnd.oasis.opendocument.graphics;
priority=200
```

You can also download the two files and copy them yourself:
[odf.zip](https://github.com/user-attachments/files/17704241/odf.zip)

Either way, the `/usr/bin/nemo-odf-to-txt` file *must* be made executable


Thanks!

**Comment by rosenbergd** [comment]
It stops calling odt2txt, but it doesn't find text inside ODS files (even text that is not a formula result).

I've set up the `nemo-odf-to-txt`, it has permissions: `root:root 755`.
I've also created `/usr/share/nemo/search-helpers/odf.nemo_search_helper`, I noticed the file path was `search-helpers` (`-` instead of `_`), so I'm guessing that's a typo?

Performance-wise, it now searches instantly, but since it's not finding results from ODS files, I'm not sure it counts.

**Comment by mtwebster** [comment]
Sorry, I've edited that path above.

The folder should be `/usr/share/nemo/search-helpers` (hyphen) but the file itself should end in `.search_helper` (underscore).

Strange, it works ok for me for .ods files. Your files aren't encrypted or have any other special properties do they?

One other typo I made - in the search_helper file, `priority` needs to be capitalized, I've edited the code above. (This is to make sure this helper is used instead of the odt2text one).

**Comment by rosenbergd** [comment]
No encryption or other special properties.

I just ran the command directly to use `nemo-odf-to-txt`, looks like it's just missing the `odfpy` module.

**Comment by mtwebster** [comment]
Strange it takes even that long. I'll create a larger spreadsheet for testing, maybe I'm underestimating how much content there is in a 2mb file.

**Comment by rosenbergd** [comment]
Sorry, this one is 5.8MB, both files took over 20 minutes before, so I just used one of them at random for testing this time

**Comment by mtwebster** [comment]
Ok... I've got another variation to try.

You can just replace the contents of `/usr/bin/nemo-odf-to-txt`.  Using a large 'test' spreadsheet, it's about 3x faster:

--------
### Using python-odf ([previous version](https://github.com/linuxmint/nemo/issues/3481#issuecomment-2468437932)):

##### Nemo content search (entered full filename so the calculated time would only involve the single file):
(nemo:378809): Nemo-DEBUG: 09:10:59.528: search_thread_done_idle: ../libnemo-private/nemo-search-engine-advanced.c:580: Search took: 3.185909 seconds

##### time nemo-odf-to-txt ~/Documents/test-odb/test-large-spreadsheet.ods:
real    0m3.170s
user    0m3.017s
sys 0m0.153s


### Using python zipfile + html.parser:

##### Nemo content search (entered full filename so the calculated time would only involve the single file):
(nemo:379353): Nemo-DEBUG: 09:14:56.408: search_thread_done_idle: ../libnemo-private/nemo-search-engine-advanced.c:580: Search took: 0.971013 seconds

##### time nemo-odf-to-txt ~/Documents/test-odb/test-large-spreadsheet.ods:
real    0m0.909s
user    0m0.885s
sys 0m0.020s

------

One caveat - I'm not 100% knowledgeable about OpenDocument formats, and I'm assuming pytho3-odf knows more, so I'm not sure this new variant will always capture *all* available text for every file type.

Thanks!

I've attached my test file if you want to compare apples to apples:

[test-large-spreadsheet.ods](https://github.com/user-attachments/files/17717981/test-large-spreadsheet.ods)

The search word is '**function**`

```
#!/usr/bin/python3


import sys
import zipfile
from pathlib import Path
from html.parser import HTMLParser

class Parser(HTMLParser):
    parsed = []
    get_next_data = False
    concat_next_data = False

    def handle_starttag(self, tag, attrs):
        if tag.startswith("text") or tag.startswith("meta"):
            if tag == "text:s":
                self.concat_next_data = True
            self.get_next_data = True

    def handle_endtag(self, tag):
        pass

    def handle_data(self, data):
        if self.get_next_data:
            if data != "\n":
                if self.concat_next_data:
                    self.parsed[-1] += " " + data
                    self.concat_next_data = False
                else:
                    self.parsed.append(data.strip())
                self.get_next_data = False

path = sys.argv[1]

parser = Parser()
zipfile = zipfile.ZipFile(path)
files = zipfile.infolist()

for f in files:
    if f.filename in ("meta.xml", "content.xml"):
        contents = zipfile.read(f.filename).decode()
        parser.feed(contents)
        if len(parser.parsed) == 0:
            continue

        out_str = ", ".join(parser.parsed)
        print(f"{Path(f.filename).stem}: {out_str}\n", flush=True, file=sys.stdout)
        parser.parsed = []
exit(0)
```

**Comment by rosenbergd** [comment]
That took 24s for the 5.8MB file and seems to find content as expected, I've also tested searching for content on different sheets.

With the file you've provided, it took ~1.6s:
```
nemo-odf-to-txt test-large-spreadsheet.ods  1.60s user 0.03s system 99% cpu 1.635 total
egrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} -o   0.00s user 0.01s system 0% cpu 1.634 total
```
