### ISSUE TITLE
Nemo plugins(actions) are not updated for multiple users via Mint update

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/nemo#3491]
### Distribution

LMDE 6

### Package version

nemo  6.2.8

### Frequency

Always

### Bug description

I ran mint update from an admin user which added 3 new plugin actions to nemo.
Running mint update for a second (non-admin) user did not update anything, including any nemo plugins.
So logging into the second user did not include these 3 nemo plugins.

### Steps to reproduce

I suspect that because plugin actions are placed in `/home/username/.local/share/nemo/actions/` that new plugins are ignored for more than one user. 

### Expected behavior

All users should receive the new or updated plugins.

**Comment by mtwebster** [comment]
> I ran mint update from an admin user which added 3 new plugin actions to nemo.

The update manager will only ever update actions that are already installed.



Downloaded Nemo Actions are a 'spice', and installed to the user's folder, not the system. They should not be available to other users.

Nemo *extensions*, on the other hand, are system packages, and should work for all users once installed.

**Comment by Jeremy7701** [comment]
Thanks
