### ISSUE TITLE
Nemo column view has duplicate records for creation and modification times

### ISSUE THREAD

**Issue by vajdao** [linuxmint/nemo#3501]
### Distribution

Mint 22

### Package version

5.8.4

### Frequency

Always

### Bug description

Nemo column view has duplicate records for creation and modification times as shown on picture.
![Képernyőkép_20241211_120956](https://github.com/user-attachments/assets/5bc12b56-31a0-40ba-9ca9-4927231bdbe8)

### Steps to reproduce

go column view and right click on any column to toggle the modification and creation options as shown on above pic.

### Expected behavior

only one of each type is necesarry

**Comment by claudiux** [comment]
This is normal if your file has not been modified since its creation.

**Comment by vajdao** [comment]
> This is normal if your file has not been modified since its creation.

No @claudiux ... you don't get my point @claudiux ... why having duplicate column categories for the same informations @claudiux ?

Inspect my screenshot a bit closer (hint: "equal" wording), instead of clicking on this issue and instantly closing it down without actually acknowledging the main problem.

**Comment by claudiux** [comment]
@vajdao A simple search gives you the answer:
https://superuser.com/questions/737247/get-last-modified-date-of-file-in-linux
