### ISSUE TITLE
auto-open automounted disk is not working well [Bug, Fix needed]

### ISSUE THREAD

**Issue by KDB2** [linuxmint/nemo#353]
Hi !

When you plug an external hard drive (or a flash disk...) the volume is automounted. Great. But then the folder doesn't auto-open. You should double click the icon to open it.

The option is checked in Nemo's option, but it's not working.

Thanks,

**Comment by Vahan86** [comment]
@KDB2, is this still an issue for you in Nemo 3.0.6?

**Comment by KDB2** [comment]
@Vahan86  & @JosephMcc 

I had forgotten about this 3.5 years old issue... 
In Nemo 3.2, this is working correctly with a flash disk. I assume hard drive also works.

**Comment by JosephMcc** [comment]
@KDB2 Thanks. Just trying to clean up some old issues.
