### ISSUE TITLE
[Feature Request] ACL support

### ISSUE THREAD

**Issue by schuetzm** [linuxmint/nemo#355]
It would be nice if Nemo's permissions dialog supported (Posix) ACLs.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
