### ISSUE TITLE
[Feature Request] Scroll while dragging files

### ISSUE THREAD

**Issue by Tele42** [linuxmint/nemo#356]
I would like to be able to use the scroll wheel to bring the target folder into view while dragging a file or folder in nemo.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
