### ISSUE TITLE
Desktop Icons rearrange on reboot/boot up

### ISSUE THREAD

**Issue by MeshWeaver** [linuxmint/nemo#358]
I originally posted this in the Cinnamon issue tracker, and I was told to try and post it here instead.

I recently switched back to Cinnamon from Mate, in Linux Mint 13 64bit, and 1.8 is great. However, I'm having an issue where every time I boot up my PC and/or reboot, all my desktop icons (about 20-30) auto-rearrange. Almost like when you sort them by name, only in random order - and all bunched together on the left side of my main screen. The main icons (computer, home, trash, etc) also get offset to the right, oddly enough.
I've looked it up and it seems a few others are also having this problem - apparently it could be that when the monitors start up, they aren't at their full resolution so the icon positions get messed up.

If that's the case, I'm thinking maybe the icons and/or desktop shouldn't load until all available monitors are at their full resolution?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for over 2 years?
