### ISSUE TITLE
Nemo Actions - Online repository - Easy Spices like Installation

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#372]
I believe we should have an online repository for Nemo Actions where users can download, install, rate, review the actions from a central repository similar to current online installation of Cinnamon Themes, Desklets, Applets and extensions . Such an option would make it trivial for users to find the actions they're looking for and make it easy for developers to share the services they create to an wider audience.

In KDE world , Dolphin services can be downloaded / installed online like how themes, widgets, etc are done. Screenshot below for reference.

![preferences-services 1](https://f.cloud.github.com/assets/4663298/899514/f47475d0-fb43-11e2-91fc-3c9eacf64b84.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by leigh123linux** [comment]
-1 to the idea, spices has no oversight so someone could add malicious code.
This isn't so much of an issue for non-root apps like cinnamon but nemo is capable of running with elevated permissions.

**Comment by anandrkris** [comment]
When I originally raised this request there was no Edit - Plugins. What I was looking for was easy repository of Nemo actions and plugins which is available now. Don't mind closing this now if others don't have related ideas.

Now Cinnamon Spices has also undergone a complete change with Cinnamon oversight - but agree on the security aspects. 

![nemo_plugins](https://cloud.githubusercontent.com/assets/4663298/22869885/a85fb7f2-f1c8-11e6-9875-4eeabeab3c0b.png)

**Comment by JosephMcc** [comment]
I'm going to close this. This isn't like Cinnamon spices where many people work on and develop these things. If someone wants to create a new one that can simply open a PR in nemo-extensions.
