### ISSUE TITLE
Copying large files over CIFS mounted shares causes considerable lag in user experience

### ISSUE THREAD

**Issue by adamryczkowski** [linuxmint/nemo#377]
This is such a great show-stopper, that I am sure a lot of people have already reported this, but to be sure, I post it myself (again?).

On Linux-Mint 15, Cinnamon 1.8.8 64 bit, when CIFS network shares are mounted, and especially when there is a copying on background in process, the screen periodically freezes for many seconds (excluding mouse movements). It is impossible to see any screen update during the freeze time, even movie playback and workspace switching.

"cinnamon --replace -d :0" from other tty doesn't help either.

The only thing that helps is to either to wait for the copying to finish, or abort it. Disabling the network card doesn't help here...

During that freeze all applications work as expected, only their output isn't produced on the screen. There is no CPU load (apart from normal, coming from background applications) during the freeze - it looks exactly like deadlock.

I initially filled this bug against Cinnamon (https://github.com/linuxmint/Cinnamon/issues/2340#issuecomment-22546484), but was redirected here (although I don't understand why, since this problem seems completely not relevant to Nemo - the file manager).

**Comment by Vahan86** [comment]
@adamryczkowski, is this still an issue for you in Nemo 3.0.6 (Cinnamon 3)?

**Comment by kaefert** [comment]
I'm running Nemo 3.0.6 and I observe Nemo becoming unresponsive on file copy / move operations from or to an MTP android device.

**Comment by Vahan86** [comment]
@adamryczkowski, @kaefert, is this still an issue in Cinnamon 4.2?

**Comment by adamryczkowski** [comment]
@Vahan86 I am no longer using Linux Mint

**Comment by kaefert** [comment]
I just copied 2.5gb which took around a minute and both the system (v19.1) and nemo (v4.0.6) stayed responsive. seems solved to me.

**Comment by adamryczkowski** [comment]
Then I close the issue
