### ISSUE TITLE
Closing trash tab kills process

### ISSUE THREAD

**Issue by CarVac** [linuxmint/nemo#379]
I'm using Ubuntu 13.10 and have nemo 1.8.4-1 from the saucy/universe repository.

Whenever I close a 'trash' tab or any window with 'trash' open, whether active or not, all nemo windows close immediately. This happens every time.

What is less repeatable is the following: Occasionally, when navigating away from 'trash', it crashes in an identical manner. Most of the time it doesn't, though.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 3 years?
