### ISSUE TITLE
two improvements in Nemo regarding the extra pane

### ISSUE THREAD

**Issue by rpremuz** [linuxmint/nemo#380]
Hi!

I'd like to suggest two improvements in Nemo when the extra pane is used (activated with F3).

Currently, when Nemo starts it always shows only one pane and the user has to press F3 to activate the extra pane. I'd like to have an option in Nemo preferences that would make the extra pane active at the start of Nemo.

Furthermore, when Nemo shows two panes it is difficult to recognize which pane has the focus. I'd suggest drawing a distinct border around the pane which has the focus.

**Comment by Vourhey** [comment]
Is there a shortcut for switching between panes?

**Comment by jpcours** [comment]
`F6`
But when only one pane is open it also switches between the sidebar and the pane.
