### ISSUE TITLE
Feature Request: Select on hover when "Single click to open items" is selected

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/nemo#385]
When using the option for "Single click to open items" then selecting/highlighting a file can be a pain, granted you kind of have to expect that when using this option.  
However Thunar (The file manager in XFCE) has a nifty little feature where once you select the option to "Single click to open items" then you can just hover the mouse pointer over a single item for a configurable amount of time to select/highlight just that single item. I think it would make a nice addition to Nemo

**Comment by francocurotto** [comment]
Please! I would love this feature.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by feren** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
