### ISSUE TITLE
Big icons in the first time the program is opened

### ISSUE THREAD

**Issue by he7d3r** [linuxmint/nemo#386]
Sometimes, when I first open my home folder, the icons of the files are diplayed as if I had pressed CTRL++ a few times. The left side of the screenshot shows the how it looks like and the right side is the normal size (CTRL+0). I'm using Nemo 1.8.3.
![screenshot-nemo-bug](https://f.cloud.github.com/assets/1754791/1062219/5230bf18-1231-11e3-921c-708df159fd5e.png)

**Comment by Vahan86** [comment]
@he7d3r, is this still an issue for you with Nemo 3.0.6 (Mint 18)?

**Comment by he7d3r** [comment]
I don't see this happening with Nemo 3.0.6 on Linux Mint 18 Sarah.

**Comment by Vahan86** [comment]
@he7d3r, thanks for your reply. In this case can you please close the issue?
