### ISSUE TITLE
Nautilus conflicts with nemo

### ISSUE THREAD

**Issue by joequant** [linuxmint/nemo#387]
Both Nautilus and Nemo are configured as the file manager, so when nemo is installed and someone boots up with gnome after installing cinnamon, they can get nemo rather than nautilius.

https://bugzilla.redhat.com/show_bug.cgi?id=963433

Redhat has a patch that selects nemo/nautilus based on whether cinnamon is running, but surely there must be a better way.

**Comment by leigh123linux** [comment]
@joequant  Is this still an issue for you?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
