### ISSUE TITLE
Feature request: improve views for left panel (the same of caja) and the buttons panel

### ISSUE THREAD

**Issue by geplus** [linuxmint/nemo#388]
Hi,
I'm using Caja and Nemo both as file managers, and I've noticed that Caja has lots of views in the left pane (Colums, tree, symbols, informations etc.) and nemo has only colums and tree. I'd like if Nemo have also the views of caja in left pane, i found them really usefull.
Also, I'd like the possibility to change the buttons position of the buttons panel with the mouse and add more buttons (for example, zoom + - and able/disable thumbinails button).
thanks for the attention!

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
I won't speak for the sidebar options but the button changes aren't going to happen.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
