### ISSUE TITLE
[Feature Request] Open Nemo-Window with hidden files hidden

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#397]
In Nemo 1.2 every newly opened instance of nemo was opened without showing hidden files. As it is now Nemo always starts with the last behavior, so most of the time it shows me hidden files, although i don't need them. It would be cool to have a tickbox in preferences, where i could enable something like "open new instances without showing hidden files" (maybe a little better name for the settings^^)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
