### ISSUE TITLE
[Feature Request]: Miller Columns View

### ISSUE THREAD

**Issue by dj-joshi** [linuxmint/nemo#399]
Is it possible to add a Miller Columns view to Nemo, like KDE Dolphin used to have, or OS X Finder has now?  I think Marlin / Files / Pantheon from Elementary OS just implemented it, but don't know what framework and language they are using.

http://en.wikipedia.org/wiki/Miller_Columns

**Comment by tchncs** [comment]
+1

**Comment by blackbookpro** [comment]
Please do so! I would be very glad for this feature! 

+1

**Comment by Anarcraft** [comment]
I still don't understand why this isn't a standard feature of every major file manager.  It was invented 35 years ago!

**Comment by TamasBarta** [comment]
Maybe that's the reason :P Don't get me wrong, I also want that feature...

2015-02-25 00:11 keltezéssel, Anarcraft írta:

**Comment by woodlander87** [comment]
+1

**Comment by nizur** [comment]
+1

**Comment by abedih** [comment]
+1

**Comment by SergeyLysyi** [comment]
+1

**Comment by stefysabbadin** [comment]
Miller Columns (or columns view) are a very nice feature to navigate deep nested trees. That would be a big plus for this file manager. 
+1

**Comment by VinnyFonseca** [comment]
+1

**Comment by zer0aster** [comment]
While on a Mac, in Finder, I use column view more than any other, it is my default view. So I really miss it in Nemo, which is otherwise a very impressive file manager; please implement this feature!

**Comment by cesss** [comment]
Please implement it.

**Comment by MggMuggins** [comment]
+1

**Comment by sikender** [comment]
+1

**Comment by lqmanh** [comment]
I also love **Columns View**. Hope to see the Mint team implement it into Nemo in a near future.

**Comment by geeksunny** [comment]
+1. Doesn't appear to be a priority, though...

**Comment by LeLocTai** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
