### ISSUE TITLE
Split view & mp3 players/cameras

### ISSUE THREAD

**Issue by jpeg729** [linuxmint/nemo#400]
When in split view, if you try opening a folder on a usb device that contains music files, that folder view gets a green bar at the top saying "These files are on an MP3 Player, do you want to open Banshee?" (nemo 1.8.3 on mint 13)

That is ok. The problem is that when the green bar appears its pane suddenly occupies 85% of the width even if the text in the green bar doesn't need anywhere near that amount of space.

IMHO the size change should not be automatic. If you really want to read the text the first time you see it you can move the panel divider just that once.

**Comment by Vahan86** [comment]
@jpeg729, is this still an issue for you with Nemo 3.0.6?

**Comment by jpeg729** [comment]
I have nemo 2.8.7 installed on Ubuntu 14.04, and I don't have the time to install nemo 3.0.6.

I can say that in nemo 2.8.7 the size change is much more reasonable.
The bar appears, but only increases the column size enough to accommodate an ellipsis and the button "Open Rythmbox Music Player".

**Comment by icarter09** [comment]
@jpeg729 are you still experiencing this issue on the latest version of nemo?
