### ISSUE TITLE
Can't empty Trash on nested filesystems

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#401]
Supposing I have a set of mountpoints like so:

```
/home/will
/home/will/tmp
```

if I create some files in /home/will/tmp, and then delete then with Nemo, they're moved to the Trash correctly (I can see the .Trash-1000 folder get created).

But, none of the empty trash options available in Nemo at the moment will actually empty this Trash folder - they'll only operate on the Trash folder in my home directory. 

Similarly, none of the quick access options for looking at the trash folder will let me see its contents.

**Comment by iyosifov** [comment]
Still happening, 3 years later, with Nemo 2.6.7 :(

**Comment by Vahan86** [comment]
@wrouesnel, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
