### ISSUE TITLE
[Feature Request] File extension exclusion in Nemo_Actions

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#405]
As it is possible now to add mime-types and file extensions it would be nice to have the possibility to let nemo_actions only work on files of given mime-type, but without defined extensions.
For example i am often working with maple which saves in xml-files, but i don't want to
open all xml files with maple.
Other example: sometimes i create my own file types which are most of the time tar-archives with file-extensions differing from tar. It would be great to have the possibility to use a nemo action for all of these with exception of files with the file-extension "tar"

**Comment by Magissia** [comment]
If you make an action to compress to bz2, you may want to disallow the action to run on .bz2 files.
Example on duplicate issue #1063

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
