### ISSUE TITLE
Copy Manager

### ISSUE THREAD

**Issue by jfsanchez-gh** [linuxmint/nemo#409]
Hello, I'm using Mint with Cinnamon and Nemo on my computer, so, I would like to see in the future of Nemo a copy manager, with PAUSE/PLAY, STOP, QUEUE, and some other options, Is it possible?. I would like to try to implement it, and I downloaded Nemo's source code from GitHub, but when I run ./configure it give me some missing packages, like X11, cinnamon-desktop, gail-3.0 and some others, and I don't know how to fix those problems. Somebody can give me the complete list of packages I need to install for compiling Nemo (I'm using Linux Mint 15 Olivia and my repository is configured on Ubuntu 13.04).
Sorry for my English, it isn't my natal language.
I'm expectant for your answers

**Comment by VolMi** [comment]
As far as I am aware, this is still not part of nemo 2.4. So, finally in 2.6?
All the UI work you did is really great but I actually miss having control over large copy/move operations a lot.

**Comment by thisischrys** [comment]
Still nothing in 2.6. Hmm.

**Comment by Vahan86** [comment]
This feature has been implemented in Nemo 2.6.

@JosephMcc, can we close the issue?
