### ISSUE TITLE
[Feature Request] Copy literal path

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#410]
A lot of applications do not, and will never understand, GVFS paths - but all GVFS paths are automatically mounted under $HOME/.gvfs, allowing most applications to use them directly.

It would be really helpful in Nemo if there were an option to explicitly copy just the direct path (through the .gvfs mount) to the clipboard so it could be pasted in other applications, rather then having to rely on them to convert the path when they get it (which most do not do).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
