### ISSUE TITLE
Right click->copy broken in Nemo 2.0

### ISSUE THREAD

**Issue by andyearnshaw** [linuxmint/nemo#420]
When Cinnamon upgraded over the weekend, I noticed the following strange issue with Nemo.  In any file or folder, if I right-click and then choose Copy, the item is not properly copied to the clipboard.  When I right-click to choose Paste, the menu item is disabled, even if I previously copied or cut a different file.

This does not seem to affect Ctrl+C or Edit->Copy, and right click->Cut works fine.  I'm running Cinnamon on Ubuntu 13.04.

**Comment by fedy2** [comment]
Randomly this happens also to me. Linux Mint 17, Cinnamon 2.2.16

**Comment by Vahan86** [comment]
@andyearnshaw, @fedy2, is this still an issue for you with Cinnamon 3.0.7 (Nemo 3.0.6)?

**Comment by fedy2** [comment]
For the moment not more an issue for me.
