### ISSUE TITLE
Nemo incredibly slow displaying contents of samba network shares

### ISSUE THREAD

**Issue by grrrrr** [linuxmint/nemo#424]
Following an update to `Cinnamon 2.0.3` `Nemo` is taking multiple times longer than `nautilus` to display the content of `gvfs` shares.

Shares mounted via following command

```
gvfs-mount smb://username@192.168.1.1/share
```

Time to display contents of share

Nemo: 13 seconds
Nautilus: 2 seconds

Prior to the install of Cinnamon 2.0.3, the `nemo` time was similar to `nautilus`

Also if laptop is moved to a different network while the shares are still mounted, opening results in nemo becoming useless getting a spinning icon over the mouse pointer, while I assume nemo tries to deal with the missing shared.  Previous versions of nemo were able to gracefully handle not being able to connect to the shares and let you work away on any other folder or file unencumbered 

OS info

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.3 LTS
Release:    12.04
Codename:   precise
```

Cinnamon info

```
$ dpkg -l | grep cinnamon
ii  cinnamon                                                    2.0.3-20131021040307-precise            Cinnamon desktop
ii  cinnamon-common                                             2.0.3-20131021040307-precise            Cinnamon desktop (Common data files)
ii  cinnamon-desktop-data                                       2.0.1-20131021011504-precise            Common files for Cinnamon desktop apps
ii  cinnamon-screensaver                                        2.0.1-20131021013003-precise            Cinnamon screen saver and locker
ii  cinnamon-session                                            2.0.1-20131021043004-precise            Cinnamon Session Manager - Minimal runtime
ii  cinnamon-settings-daemon                                    2.0.3-20131021004509-precise            daemon handling the Cinnamon session settings
ii  cinnamon-translations                                       2.0.1-20131021040407-precise            Translation files for the Cinnamon desktop
ii  gir1.2-cinnamondesktop-3.0                                  2.0.1-20131021011504-precise            Introspection data for CinnamonDesktop
ii  libcinnamon-desktop0                                        2.0.1-20131021011504-precise            Utility library for loading .desktop files - runtime files
```

Nemo info 

```
$ dpkg -l | grep nemo
ii  libnemo-extension1                                          2.0.1-20131021010006-precise            libraries for nemo components - runtime version
ii  nemo                                                        2.0.1-20131021010006-precise            file manager and graphical shell for Cinnamon
ii  nemo-data                                                   2.0.1-20131021010006-precise            data files for nemo
ii  nemo-fileroller                                             2.0.0-20131021020004-precise            File Roller integration for Nemo
```

**Comment by vranki** [comment]
On cinnamon 2.6.6 / nemo 2.6.5 this issue still happens. Regression perhaps, if brouillon's test is valid.

When browsing a SFTP share, Nemo clearly recurses subdirectories as it counts their contents. This needs to be reopened.

**Comment by eleksis** [comment]
i am not sure if this is the same problem/bug...but copying files to remote location with nemo (sftp) is a lot slower compared to command executed in terminal. copying over nemo: 3MB/s and cp in terminal: 12MB/s.

**Comment by cmcginty** [comment]
I've been having this same issue for last few months. To me it looks like a regression because NEMO was working correctly in early 2015.

**Comment by vranki** [comment]
@grrrrr can you reopen this or do we need a new ticket for the regression?

**Comment by hexxamillion** [comment]
I'm having same issue on Mint 18.

**Comment by CottonEaster** [comment]
It seems that either @hexxamillion (or @vranki or someone) should file a new bug report or @mtwebster (or someone?) should re-open this the present issue.

**Comment by mtwebster** [comment]
File operation and view loading performance is already being worked on pretty heavily for 3.6 - though only a couple of commits have landed on master so far (a7c6aad5fc6395a8f4 and 1ff745e4e53eeb63)

**Comment by hexxamillion** [comment]
I no longer have this issue.

**Comment by danger89** [comment]
I have two very fast computers running both Linux Mint with SSD's up to 250 Megabytes/s (2Gbit/s), connected with CAT6 cables, and gigabit Ethernet switch. iperf3 gives around 933 Mbit/s speeds (almost 1Gbit/s as expected).

However, using Samba within Linux Mint Nemo, and only get no more then 60 MB/s (=480Mbits/s) transfer speed :\.

So what is happening with Linux Mint Nemo & SAMBA??? This is no good.

iperf3 results seems OK:
```
Accepted connection from 192.168.1.108, port 35410
[  5] local 192.168.1.102 port 5201 connected to 192.168.1.108 port 35412
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   107 MBytes   900 Mbits/sec                  
[  5]   1.00-2.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   2.00-3.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   3.00-4.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   4.00-5.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   5.00-6.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   6.00-7.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   7.00-8.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   8.00-9.00   sec   112 MBytes   936 Mbits/sec                  
[  5]   9.00-10.00  sec   112 MBytes   936 Mbits/sec                  
[  5]  10.00-10.04  sec  4.37 MBytes   935 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-10.04  sec  1.09 GBytes   933 Mbits/sec                  receiver
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

**Comment by icarter09** [comment]
@danger89 are you still experiencing this issue on the latest version of nemo?

**Comment by danger89** [comment]
I'm now using Thunar (XFCE), bye bye Gnome.

**Comment by sricks** [comment]
I started experiencing this issue on arch linux a week ago. I tried Thunar, and it's working. I think that means bye bye nemo, thanks danger89

**Comment by monoboy-hh** [comment]
why is this closed as it is not solved?!
samba directory listing with nemo is still a huge PITA in 2024.
Nemo is as slow as running "ls -l" while "ls" of course is noticably faster. 
If the current view in nemo is not showing file details, there is no need to capture them making the user wait for double figure seconds (!) just to traverse into another subdirectory where one would have to wait again ...

**Comment by Majoraslayer** [comment]
> why is this closed as it is not solved?! samba directory listing with nemo is still a huge PITA in 2024. Nemo is as slow as running "ls -l" while "ls" of course is noticably faster. If the current view in nemo is not showing file details, there is no need to capture them making the user wait for double figure seconds (!) just to traverse into another subdirectory where one would have to wait again ...

Can confirm, I'm also having this problem in 2024.  Did any kind of workaround ever come out of this?

**Comment by mas1701** [comment]
2026: Still not resolved. Currently, Nemo freezes for a long time scanning a mounted WebDAV ressource.
