### ISSUE TITLE
'Extra pane' column width issue

### ISSUE THREAD

**Issue by grrrrr** [linuxmint/nemo#425]
Following an upgrade to `Cinnamon 2.0.x` and `Nemo 2.0.x` if you use the `extra pane` feature (f3)  all columns (name, size, type, e.t.c.) get resized so all columns in both panes get displayed with out a horizontal scroll bar.

**recreate:**
- open nemo
- select a directory
- press `f3`
- all columns get resized so they all fit on screen
- you have to manually resize columns to see file names

![nemo cleaned](https://f.cloud.github.com/assets/1025506/1392071/146cc7a4-3c06-11e3-85fd-a8e7e17fbd65.png)

**expected results** (as per `nemo 1.8` and `nautilus`)
- open nemo
- select a directory
- press `f3`
- columns do not get resized, you can read file names easily and if you need to see other columns you use horizontal scroll bar.

![nautilus cleaned](https://f.cloud.github.com/assets/1025506/1392074/1fa4dba2-3c06-11e3-9f09-1a4816d7a82c.png)

**Comment by Vahan86** [comment]
Checked in Nemo 3.0.6. The issue is fixed.
@JosephMcc, can we close the issue?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
