### ISSUE TITLE
"find in files" for Nemo / Integrate gnome-search-tool

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#426]
It would be nice if Nemo search can support searches like "find in files". 

This can be implemented by a Integrate gnome-seach-tool into nemo. 
The easiest way by launching gnome-seach-tool with an "advanced"  button.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by uocxp** [comment]
is there any progress relating this feature? That would be really helpful !

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
