### ISSUE TITLE
nemo out-of-sync with .desktop/mimecache entries?

### ISSUE THREAD

**Issue by buck2202** [linuxmint/nemo#427]
On ubuntu 13.10 with cinnamon/nemo installed from ppa:gwendal-lebihan-dev/cinnamon-stable, I'm having issues with some newly installed applications not being associated with their filetypes even with proper .desktop entries. As far as I can tell, the applications are being properly propagated to nautilus (which I only reinstalled to verify that this was a nemo-only issue)

Some particular applications that I'm having this issue with:
-java runtime (openjdk and oracle)
-wine applications (MS Office suite)

The relevant applications are properly shown in the "open with" context menu for nautilus, but not nemo. The applications are also entirely missing from nemo's right-click>properties>open with list.

**Comment by icarter09** [comment]
@buck2202 are you still experiencing this issue on the latest version of nemo?

**Comment by buck2202** [comment]
@icarter09 not to my knowledge; I don't have any wine applications installed to check right now, but I can see openjdk in the right-click context menu where appropriate and in the "open with" tab of the file properties screen on nemo 4.0.6. Rereading above and the commit history at https://bugzilla.gnome.org/show_bug.cgi?id=702681, it seems like it was probably fixed when ubuntu/mint moved past gtk 3.10

Apologies, I would've commented years ago, but I must've forgotten about having this issue as I migrated away from personal use of Office through Wine, and I guess github doesn't ping for references to subscribed issues. I'll close.

**Comment by icarter09** [comment]
@buck2202 no worries and thanks for the update.
