### ISSUE TITLE
[Feature Request] Standard UI for configuring extension preferences

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#428]
There doesn't seem to be a standard way of supplying a means by which nemo-extensions of various sorts can configure and store their own internal preferences.

It seems like the best answer is that they should be storing things in GSettings, and you can certainly ship an extension which does that, but it still leaves the problem of supplying a user interface.

What would be better, IMO, is if Nemo could define a GSettings sub-key where it expects to find extension keys, and then a panel in Edit->Preferences where it would list these by folder and allow users to edit their configuration.

This would save some work when developing extensions, and avoid possible interface clutter (i.e. from extensions having to add their own context menu entries settings panels). GSettings schema interface already provides most of the needed functionality (defines allowed values, provides friendly names, help text and default values).

EDIT: To extend this proposal a little further, my specific proposal is that Nemo should look for keys under `/org/nemo/extensions` and provide a dconf-editor like interface to set them, since GSettings already provides everything necessary. This wouldn't break any current extensions that I know of, and seems like a sensible way to compartmentalize. That said, I'm not super familiar with GSettings standards (since they seem very non-existent) so any input on this would be appreciated.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
