### ISSUE TITLE
Places sidebar should not read "My Computer"

### ISSUE THREAD

**Issue by aibaraiduas** [linuxmint/nemo#434]
The sidebar in "places" mode should not display the words "My Computer." "My Computer" invokes horrible memories of Windows within the mind of the user. 

Better alternatives include "Places" (what Nautilus now uses), "Username's Computer," or just plain "Computer."

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by feren** [comment]
This may've been patched in the latest Nemo, I can't see any mentions of My Computer anywhere instead just saying 'Computer' now...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
