### ISSUE TITLE
Nemo should offer "Date Created" as a method to order files

### ISSUE THREAD

**Issue by Pointedstick** [linuxmint/nemo#439]
Nemo can order files by Date Modified and Date Accessed, but not Date Created. It should.

**Comment by rodrigograca31** [comment]
+1
I've downloaded a bunch of youtube videos (one playlist) and now they are not ordered because "Date Accessed" changes every time I open one of them, and "Date Modified" doesn't match the order they were downloaded...

**Comment by DrupaListo-com** [comment]
+1

**Comment by rodrigograca31** [comment]
@DrupaListo-com Thanks! I will keep that in mind next time I use youtube-dl :smile:

**Comment by DanielJPetersen** [comment]
I could be misinterpreting this, but it looks like Linux now provides a system call to obtain the file creation date as of Kernal 4.11.  

https://lwn.net/Articles/720724/

I only bring this up because it would be a very nice feature to have.

**Comment by Pointedstick** [comment]
Indeed. It would be great to get this re-opened.

**Comment by bes1002t** [comment]
Please re-open this issue, it is a mess to watch holiday pictures because I can not change the order to "Date Created". This is a really common feature a file manager should support.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/1b8030b7f464ec8c1b372d34f74bc0988e888a2c
