### ISSUE TITLE
Nemo fills up .xsession_errors

### ISSUE THREAD

**Issue by vlatkoB** [linuxmint/nemo#442]
Hi,

on Ubuntu 12.04, 3.2.0-56-generic, x86_64, Cinnamon 2.0.6, Nemo 2.0.2,
every second/third day .xsession-errors file gets filled with

(nemo:3570): GLib-GObject-WARNING *_: instance of invalid non-instantiatable type (null)'
(nemo:3570): GLib-GObject-CRITICAL *_: g_signal_handlers_disconnect_matched: assertionG_TYPE_CHECK_INSTANCE (instance)' failed
*\* (nemo:3570): CRITICAL *_: nemo_directory_file_monitor_remove: assertion NEMO_IS_DIRECTORY (directory)' failed
*_ (nemo:3570): CRITICAL **: nemo_directory_unref: assertionNEMO_IS_DIRECTORY (directory)' failed

until log file consumes all the available space on $HOME.
After deleting logs and restart, all seems to work correctly for some time.
Haven't discovered what action is causing it.

Best regards,

vlatko

**Comment by Vahan86** [comment]
@vlatkoB, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc,can we close this issue?

**Comment by lehjr** [comment]
I'm using the nightly builds and this issue is still alive and well

**Comment by lehjr** [comment]
```(nemo:1783): Gtk-CRITICAL **: gtk_action_group_get_action: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed

(nemo:1783): Gtk-CRITICAL **: gtk_action_set_sensitive: assertion 'GTK_IS_ACTION (action)' failed

(nemo:1783): Gtk-CRITICAL **: gtk_action_group_get_action: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed

(nemo:1783): Gtk-CRITICAL **: gtk_action_set_sensitive: assertion 'GTK_IS_ACTION (action)' failed

(nemo:1783): Gtk-CRITICAL **: gtk_action_group_get_action: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed

(nemo:1783): Gtk-CRITICAL **: gtk_action_set_sensitive: assertion 'GTK_IS_ACTION (action)' failed

(nemo:1783): Gtk-CRITICAL **: gtk_action_group_get_action: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed```

**Comment by vlatkoB** [comment]
Forgot about this issue. Not happening anymore. Closing.
