### ISSUE TITLE
Nemo copy,paste file names

### ISSUE THREAD

**Issue by Tiger45** [linuxmint/nemo#444]
I would like to suggest to remove white spaces and change () to - in filenames when creating copies of a file in the same directory. Currently (in Nemo v1.8.3) file1.ext becomes 'file1 (copy).ext', 2nd copy becomes 'file1 (another copy).ext', 3rd copy becomes 'file1 (3rd copy).ext'. Could we change to the following naming scheme:
file1.ext
file1-copy.ext
file1-copy2.ext
file1-copy3.ext
etc.

Rationale: white spaces and () require \ when using command line and in scripts, - does not require .
and
copy, copy2, copy3, etc is more consistent than copy, another copy, 3rd copy, etc.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by triNem** [comment]
@Tiger45 

:+1: The issue still exists in v3.6.4

### French Translation :
This is also something that exists in the French translation of nemo. The copied files end up disorganized.

### I suggest a slightly modified renaming scheme : 
file1.ext
file1_copy01.ext
file1_copy02.ext
file1_copy03.ext
etc.

### This  has two advantages : 
-the 0 allows for more than 9 copies while keeping the logical order. 
-In some programs, the hyphen "-" prevents the full sorting of the files. The original file is treated as the last file. This is the case in pyrenamer. Maybe this is python related. Using an underscore "_" instead solves this issue.

### See screenshots:
With hyphen:
![image](https://user-images.githubusercontent.com/11160011/34557818-ca2e9592-f13b-11e7-84a0-855d88fc696e.png)


With underscore:
![01](https://user-images.githubusercontent.com/11160011/34557705-74f0431e-f13b-11e7-8886-70c90868a404.png)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
