### ISSUE TITLE
Copy/cut and paste stops working

### ISSUE THREAD

**Issue by dashesy** [linuxmint/nemo#452]
Am not sure what causes this but after some time ctrl+x/c and ctrl+p does not work, the only ways to move is to drag file between windows.
I am running 2.0.1 in Fedora19's in cinnamon.

Let me know where to look for better diagnosis

**Comment by sw2000** [comment]
In Nemo 4.2.2 this issue, or at least something similar, still occurs. I dont know what triggers it, but occasionally all ability to copy paste move duplicate trash or delete files stops working. I have to close and reopen Nemo. Once the bug occurs it happens to all open tabs until closed and reopened. Keyboard shortcuts dont work, and also the options are greyed out on right mouse click.

I'm using Nemo on XFCE Manjaro, not sure if that might have something to do with it.
