### ISSUE TITLE
Nemo 2.0.6, Cinnamon 2.0.12: Image icons on desktop and in nemo are not displayed as miniatures

### ISSUE THREAD

**Issue by vlatkoB** [linuxmint/nemo#453]
Image icons (jpeg and png) on desktop and in all views in nemo are not displayed as miniatures (little pictures), but as black rectangles with letters JPG or PNG.

Some image icons are correctly displayed in nemo when viewing Pictures directory, but when an image, whose icon was correctly displayed in Pictures directory, is copied to Desktop, nemo is not displaying it correctly.

Also, some, but not all image icons, are displayed correctly in Pictures directory, regardless of their type. 

Sometimes, not always, when picture is open with a viewer, its icon becomes displayed as image again.

Do not know does it matter, but nemo-preview is not installed because build is broken on PPA for Precise

On 2.0.11 it was OK.

System: 
  Ubuntu 12.04
  Nemo 2.0.6
  Cinnamon 2.0.12

Best regards,

vlatko

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 2 years?

**Comment by vlatkoB** [comment]
This issue is solved. Pics are displayed as miniatures. Sorry for not following on time.
