### ISSUE TITLE
Wrong icons in nemo (Iconset elementary)

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/nemo#454]
As you can see on this screenshot desktop icons are default and in comparison to nautilus (front) the icons nemo (back) uses are wrong:
![bildschirmfoto vom 2013-11-15 13 20 56](https://f.cloud.github.com/assets/636557/1549796/9ffe79ec-4df0-11e3-95ab-0ce5d1e0515c.png)

The iconset elementary is available here (Package elementary-icon-theme):
https://launchpad.net/~elementary-os/+archive/stable

**Comment by Vahan86** [comment]
@dtrunk90, Is this still an issue for you in Nemo 3.0.6?

**Comment by dtrunk90** [comment]
I don't use this iconset anymore. I guess you can close this issue.

**Comment by Vahan86** [comment]
@dtrunk90, thanks for your reply, in this case can you please close this issue?

**Comment by feren** [comment]
@dtrunk90 You still can, just add the elementary OS Project repository to Ubuntu/Linux Mint:
`sudo add-apt-repository ppa:elementary-os/stable`
Followed by:
`sudo apt update && sudo apt install elementary-icon-theme`
