### ISSUE TITLE
Column widths are not adjustable and make Name column unreadable

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#456]
There seems to have been a recent change in Nemo to constrain the span of columns to the Nemo window. The net effect of this however seems to have been to render the Detail view unusable with the normal set of columns, as the "Name" field gets crushed in a small window to being unreadable in favor of less important fields like "Type" which  take more width then they need.

The Name field can no longer be stretched as a result:
![image](https://f.cloud.github.com/assets/772445/1557576/c291f1e4-4f23-11e3-8919-72c433f6a1bf.png)

This behavior doesn't seem like a good compromise at the moment - in my normal usage, I don't need to see a lot of the fields all the time, but there's no way to view information like ownership or permissions quickly if I have to turn off the columns, and at any rate, hiding the name field in favor of the size, type and date modified fields is not good at all.

**Comment by Vahan86** [comment]
@wrouesnel, is this still an issue for you in Nemo 3.0.6?

**Comment by JosephMcc** [comment]
I'm closing this. As @mtwebster has pointed out in other issues. This has been reworked and we are happy with how it behaves currently.
