### ISSUE TITLE
Nemo status icon shows 99% when preparing to copy files

### ISSUE THREAD

**Issue by abn-volk** [linuxmint/nemo#458]
![untitled](https://f.cloud.github.com/assets/1829147/1579359/0cc50da2-5198-11e3-971e-3b8b0f39e538.png)
![screenshot - 19112013 - 16 53 51](https://f.cloud.github.com/assets/1829147/1579360/0d28e692-5198-11e3-985d-9d82d6470ce2.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for over 2 years?
