### ISSUE TITLE
There is no row/item highlight indicator anymore

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/nemo#460]
In most file managers, you have 3 states for items:
1. Nothing.
2. Highlighted.
3. Selected.

There is no _visual_ highlight state anymore. Only nothing or selected. When you move with the keyboard cursor, the highlighted item will automatically be selected, so you know where your 'cursor' is at.

But when making a selection using your keyboard cursor keys, holding CTRL, and using SPACE to select/unselect files, there is no visual hint as to where your cursor is anymore. Making it hard to do this when you skip a bunch of files before selecting a new one.

**Comment by Vahan86** [comment]
Icons do get highlighted with dash lines in all 3 views (Icon, List and Compact) in Mint-Y theme, though the issue is still reproducible when theme is set to Mint-X for example.

**Comment by JosephMcc** [comment]
This is a theme issue. In Mint-X they were removed intentionally.

**Comment by Redsandro** [comment]
@JosephMcc it feels though as if it was done intentionally by mistake.

By mistake I mean that the theme developer (clearly?) never used keyboard multi-selection and thought: _What is this border style for? I've never seen it in action. No one uses this. I might as well remove it._

Similarly, if I never use a mouse, I could decide to make a theme without a mouse cursor. Intentionally. That doesn't mean that it's a good design, or that we can't have a discussion about bringing the mouse cursor back because it's a default theme for an operating system on a computer that commonly has a mouse attached.

**Comment by JosephMcc** [comment]
> it feels though as if it was done intentionally by mistake, and I'm not sure if 'done intentionally' is a good reason for closing this issue.

Maybe, but the fact that it isn't an issue with Nemo is a perfect reason to close it.

> By mistake I mean that the theme developer (clearly?) never used keyboard multi-selection and thought: What is this border style for? I've never seen it in action. No one uses this. I might as well remove it.

Sure. That's how it happened. I learned a long time ago that no matter what decisions you make to something design wise, some people will hate it. It's the nature of the beast. Switch to a different theme. Problem solved.

**Comment by anandrkris** [comment]
@Redsandro - Please don't assume any intentions when we can ask?
@JosephMcc - Happy to raise a request under themes. Could you please share rationale for inconsistency in List view alone?

**Comment by JosephMcc** [comment]
@anandrkris Just for general info, this isn't going to be changed in Mint-X. The focus indicator in question here when keyboard navigating isn't visible in any view.

**Comment by Redsandro** [comment]
@anandrkris 
> Please don't assume any intentions when we can ask?

I merely intended to propose that closing an issue about UX removal on the grounds that it was intentional is not logical reasoning.

Logic is the study of the principles of reasoning. As a form of science, logic is used to solve various problems through the application of deductive reasoning.

That said, I won't be continuing my argument. Before there was Mint-Y, I found the necessity to use custom themes in order to get basic UX a bad logical choice for Linux Mint. Luckily there's Mint-Y now, and I like the theme, so for me personally it's not a problem any more. Note that this issue is from 2013.

**Comment by anandrkris** [comment]
I think what I'm seeing is another issue specific to List View. I will try to capture a small video - essentially no indication on hover in List View.

**Comment by JosephMcc** [comment]
Are you talking about the icon highlighting on mouse over?

**Comment by anandrkris** [comment]
Yes.
