### ISSUE TITLE
Open folder in new tab if Nemo is already opened

### ISSUE THREAD

**Issue by rodri042** [linuxmint/nemo#461]
I couldn't find this option. It would be great that opening a folder in Desktop (for example), doesn't create a new Nemo window if there is already one

**Comment by stilobique** [comment]
2015 and we can't use this option ? Very important feature (for me ^^).

**Comment by Redsandro** [comment]
+1

**Comment by smc217** [comment]
+1

**Comment by hetraeus** [comment]
+1

**Comment by Moilleadoir** [comment]
+1

**Comment by Gi11i4m** [comment]
+1

**Comment by hyrumwhite** [comment]
+1

**Comment by kern-development** [comment]
+1

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by lukerazor** [comment]
+100.

**Comment by leigh123linux** [comment]
If this request gets another morons +1 I will lock the issue!

**Comment by Redsandro** [comment]
-1 for calling me a moron

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
