### ISSUE TITLE
nemo does not build with ubuntu saucy 64bit

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#464]
./configure complains about syntax error  

./configure: line 16736: syntax error near unexpected token `0.6.4'
./configure: line 16736:`GOBJECT_INTROSPECTION_CHECK(0.6.4)'

automake warns about this:

Running automake-1.13...
automake-1.13: warning: autoconf input should be named 'configure.ac', not 'configure.in'
cut-n-paste-code/libegg/Makefile.am:5: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '__CPPFLAGS')
automake-1.13: warning: autoconf input should be named 'configure.ac', not 'configure.in'
eel/Makefile.am:5: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '__CPPFLAGS')
libnemo-extension/Makefile.am:67: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
libnemo-extension/Makefile.am:7: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '__CPPFLAGS')
libnemo-private/Makefile.am:5: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '__CPPFLAGS')
src/Makefile.am:13: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '__CPPFLAGS')
test/Makefile.am:3: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '__CPPFLAGS')

**Comment by jackweiwang** [comment]
Are there any other answers?  I have installed it "gobject-introspection" 
![image](https://cloud.githubusercontent.com/assets/19305790/18086773/272dc2ee-6ee4-11e6-9024-368f5fa8b764.png)
![image](https://cloud.githubusercontent.com/assets/19305790/18086786/3c5c14fe-6ee4-11e6-856f-ad97b4082cb2.png)

thank you!

**Comment by 123sonu** [comment]
Getting same error even after installing "gobject-introspection". Any Suggestions?

**Comment by mtwebster** [comment]
This is so old we don't even use this build system anymore. If you're having an issue building the latest release, open a new issue.
