### ISSUE TITLE
feature request: recoll search results integration

### ISSUE THREAD

**Issue by pharmville** [linuxmint/nemo#472]
Nemo search bar and cinnamon menu applet would be more powerful (and faster) if they could index the contents of files, and list results based on the index. Obviously the locations that are indexed should be configurable.

I propose using recoll to do the difficult work here. It is very modular (it uses "filters" written in bash to extract text from various files). I have tested the most recent version of recoll and it quickly and accurately indexes all the files I have tried (mostly ms office and pdf files). Seems bug free in my testing compared to the alternatives.

In summary it would be nice if the cinnamon menu and nemo searches could display results from searching the recoll index. This type of integration is the only thing I miss from windows: I could press the windows key and type my search term and the right document would pop up in the list, even if the term was in the body of the document and not the filename)

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
