### ISSUE TITLE
Dragging from one pane to the other

### ISSUE THREAD

**Issue by sprintcowboy** [linuxmint/nemo#475]
Mint 16
In duel pane mode the pane has to be highlighted before you can drag a file or folder to the other pane.
In Mint 14 you could drag and drop with out highlighting the pane or you could open a file or folder.
Is there any way to get this back?

**Comment by Swistaku** [comment]
Still and issue in mint 17.1 with nemo 2.4.4 :confused:

**Comment by ManIVIctorious** [comment]
Can confirm, this is really annoying

**Comment by Vahan86** [comment]
Still an issue in Mint 18 with Nemo 3.0.6.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
