### ISSUE TITLE
nemo segfaults (backtrace included).

### ISSUE THREAD

**Issue by jtts** [linuxmint/nemo#476]
Since beginning of October I have been experiencing multiple crashes (segfault / general protection) with nemo. Checking my package manager's (i.e. pacman) logs these crashes started around the time that I upgrade nemo to 2.0.0 and gnome to 3.10. Unfortunately I haven't been able to track down the trigger of these crashes, however I was able to get backtraces of the crashes (per Ubuntu's instructions). I'll attach these backtraces plus a collection of systemd's journal entries of the crashes.

**Comment by Vahan86** [comment]
@jtts, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
