### ISSUE TITLE
Nemo Extension - Install option for Font files

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#477]
Could you add an "Install" option for font files. (_.ttf)? 
Apologies, have no programming experience to modify the nemo actions....
I downloaded multiple font (_.ttf) files. If I wanted to add all downloaded fonts in one shot, should be able to (multi) select files and right-click and install. Currently, I have to open each one of them and install individually.

**Comment by sorinnn** [comment]
I use the last Nemo from the recent Cinnamon DE but I can't found Install_Font.nemo_action
can I get the script inside to make my own file ?  

Exec= cp %F ~/.fonts (tried /bin/cp also ) is not working .. on my own .nemo_action

so if anyone can help . .
