### ISSUE TITLE
huge tiff files cause cinnamon to max out cpu and eat endless amount of RAM

### ISSUE THREAD

**Issue by kaefert** [linuxmint/nemo#478]
I've first reported this bug in the cinnamon bug tracker here:
https://github.com/linuxmint/Cinnamon/issues/2703
But user leigh123linux told me there to report it here, because he thinks that nemo is the cause of this bug.

This could be relevant to:
http://forum.linuxmint.com/viewtopic.php?f=47&t=148767#p793371
(the background of nemo changes from white to gray in relation with this bug)

**Comment by kaefert** [comment]
In Linux Mint 18 Cinnamon it is no longer the Cinnamon process but the Nemo process that eats the resources, and it's no longer ever growing resources but "only" 2GB of RAM and 100% of one CPU core.

**Comment by icarter09** [comment]
@kaefert is this issue still occurring in the latest version of nemo?

**Comment by kaefert** [comment]
Hey there @icarter09! Sorry I don't have a system in place anymore with which I could test the issue.

The only Linux Mint machine I still have operating is my office desktop, and I probably won't get to that for another month or two because of the Corona measures...

**Comment by icarter09** [comment]
@kaefert no worries and thanks for the update. Hopefully in a month or two you can test it out again.

**Comment by icarter09** [comment]
@kaefert hopefully things are better now for you. Just touching base to see if you were able to retest this issue. If not, no worries. Thanks.

**Comment by kaefert** [comment]
Hi there @icarter09 ! Actually I've got my first in the office meeting since a few months planned for today.
So I just copied a 1.3 and a 3.5gb tiff file over from my archive to my laptop I'll carry with me and I'll test them on my Linux Mint office machine when I'm there.

**Comment by icarter09** [comment]
@kaefert glad to hear that you are able to safely make it back into the office. Sounds like issue is somewhat fixed??? But also sounds like there are other issues still occurring (that's what I derived from Update 1). Is that correct?

**Comment by kaefert** [comment]
Yes the issue with big CPU & RAM usage caused by the thumbnailing seems to be fixed.

And yes I guess you could still consider the observed behavior a bit buggy, but it's a huge step up and I would not have expect the thumbnailer to be able to thumbnail those huge tiff files - gimp takes a few minutes on those older systems and even on my very new laptop it takes nearly a minute - and lots of other imaging software simply fails to open those files.

**Comment by icarter09** [comment]
@kaefert thanks for the update. Do you feel this ticket can be closed?

**Comment by kaefert** [comment]
@icarter09 sure! I'll press the "Close and comment" button now myself :) Thank you for your persistence, amazing work! :)
