### ISSUE TITLE
[Feature Request] eicicl (extended ACL) integration

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/nemo#482]
If extended ACL are used (need to be turned on in the filesystem mount), then getfacl and setfacl can be used to manage these extended ACL entries.

The package eicicl integrates a tab in Nautilus | file properties to view and set these extended ACLs.  Would be AWESOME if this would work on Nemo also.  It would be of great value to anyone running filesharing that would require extended ACLs (multiple groups with differing levels of access) to files / folders.

Attached is a screenshot of the "Access Control List" tab that is integrated in Nautilus due to eicicl being installed.
![eiciel-nautilus](https://f.cloud.github.com/assets/2560632/1716777/16339154-61c6-11e3-938d-b31c318be899.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
