### ISSUE TITLE
[Feature Request] Alt-drag archives -> Add option "extract here"

### ISSUE THREAD

**Issue by kaefert** [linuxmint/nemo#484]
When I alt-drag files or folders to another folder in nemo, then I get a popup with 3 options:
copy, move & link.

It would be great if there was a 4th option for archives, to extract itself to the target folder. I thought I saw this previously, but I guess it was some other file browser, though I can't remember which one.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
