### ISSUE TITLE
[feature] Add 'alt+d' as an accelerator to focus location bar

### ISSUE THREAD

**Issue by leesei** [linuxmint/nemo#485]
Current accelerator is 'ctrl+l'. In Windows and most browsers, both accelerators works.
We can use the left hand to press 'alt+d' (and then 'ctrl+c', which is the most common use case), and keep the right hand on the mouse to focus on other windows for the pasting.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by MrChriZ** [comment]
+1 - Alt-D also works in Chrome

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by MrChriZ** [comment]
Why was this closed - still such an easy and thing that could be fixed in 2025!
