### ISSUE TITLE
Search while typing

### ISSUE THREAD

**Issue by arnotixe** [linuxmint/nemo#488]
I think the "search while typing" is an excellent and very efficient way to find files in NAUTILUS. Could that be ported? Now in nemo all that appears if you type something, is a little box in the lower right corner, seemingly doing nothing at all.

In nautilus, on the other hand, just type along and it will show only matching files. Partial matches also work, as do special characters.

For a video of this feature, see http://videobin.org/+75g/979.html

For now I "mv /usr/bin/nemo /usr/bin/nemo.old; ln -s /usr/bin/nautilus /usr/bin/nemo" to "Fix" it (probably breaking other stuff).

**Comment by Vahan86** [comment]
The requested feature is now available in Nemo.
@JosephMcc, can we close the issue?
