### ISSUE TITLE
[Feature Request] Search results display options

### ISSUE THREAD

**Issue by bugith** [linuxmint/nemo#492]
Hi the team, I just registered into github to BIG THANK YOU for nemo.
I use it (1.7.2) in ubuntu 13.04 with Unity and it is a great happiness to find back a true file browser since nautilus was shrinked to a prototypic idea.

Ignoring what is the best way to suggest features (I'm not a coder), I do it here, hoping I'll not borrow anyone.

My favorite display view being "Compact", I often search files in a tree, so I'd like to have a feature in preferences or elsewhere, to preset the search results displays in "List" mode which would allow me to preset the columns, I mean especially the "Place" one (and Permissions + Permissions octal if possible). This preset would be a different one than the "Columns of lists" preferences tab, as when just browsing in "List" mode, what I sometimes do, displaying the "Place" column seems useless to me and eats too much room on the screen.

Thank you again for your job.

**Comment by NChewie** [comment]
Bump!
With each new release of Mint, I rush in to see if this has been added.  Alas, not yet.
I see that there is now functionality for nemo-extensions.  Is there a place to make suggestions for a plug-in extension or something similar?

**Comment by NChewie** [comment]
Bump!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
