### ISSUE TITLE
Busy cursor launching quicklist or second file from nemo

### ISSUE THREAD

**Issue by bugith** [linuxmint/nemo#493]
Hi
I use your great nemo 1.7.2 in Ubuntu 13.04 with Unity, and I made it my default file browser.
I tweaked the ~/.local/share/applications/nemo.desktop to add quicklist to my main subfolders, this way:
[Desktop Entry]
Icon=folder_home
StartupNotify=false
Exec=nemo %U
X-GNOME-Bugzilla-Version=1.7.2
Comment[fr]=Accéder aux fichiers et les organiser
Type=Application
Categories=GNOME;GTK;Utility;Core;
Comment=Access and organize files
Terminal=false
X-GNOME-Bugzilla-Product=nemo
Actions=Action0;Action1;Action2;Action3
MimeType=inode/directory;application/x-gnome-saved-search;
Name=Files
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Component=general
OnlyShowIn=GNOME;Unity;
Name[fr]=Fichiers

[Desktop Action Action2]
Exec=nemo Images
Name=Images
Name[fr_FR]=Images

[Desktop Action Action0]
Exec=nemo Musique
Name=Musique
Name[fr_FR]=Musique

[Desktop Action Action1]
Exec=nemo Documents
Name=Documents
Name[fr_FR]=Documents

[Desktop Action Action3]
Exec=nemo Vidéos
Name=Vidéos
Name[fr_FR]=Vidéos

When I rigth-click the main icon then left click a sub-item I get a busy cursor for 15s whether or not I close the window or I keep it openned. Searching info on this I discovered I also have the same old cursor issue triggered when opening a second file in gedit, which is said to be fixed, maybe only for nautilus??? I can't decide.
(see https://bugs.launchpad.net/ubuntu/+source/gedit/+bug/792227 )
I don't get this busy cursor when I run in terminal or Alt+F2 , say "nemo pictures" or gedit /etc/fstab then gedit /etc/crontab.
I'm not really sure if the nemo quicklist and gedit both triggering the busy cursor for exactly 15s are related. 
Thanks again

**Comment by Vahan86** [comment]
@bugith, is this still an issue for you with Nemo 3.2?

**Comment by bugith** [comment]
I can't say, I still with 1.8.4

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by bugith** [comment]
Sure. Close it as I can live with it and it is surely no more an issue in recent nemo or distro.
Thank you
