### ISSUE TITLE
[Bug] Nemo Shutting Down 2.0.8

### ISSUE THREAD

**Issue by RaedsLab** [linuxmint/nemo#498]
I'm using Manjaro , keeping everything updated and all, but since the version 2.0.2 Nemo keeps getting shut down and I have to reopen it manually ..

**Comment by Vahan86** [comment]
@RaedsLab, is this still an issue for you with Nemo 3.0.6?

**Comment by RaedsLab** [comment]
Well, now I have new  clean install with Nemo 3.0.6. It seems fine, closing.
