### ISSUE TITLE
Incorrect permissions detected for an NFS mount

### ISSUE THREAD

**Issue by VladV** [linuxmint/nemo#499]
I have a directory mounted via NFS. Nemo apparently sees its owner/permissions as root:root 644 (as shown in directory properties dialog), and disables new file and directory creation.

In fact, the permissions are nobody:nogroup 777, so it is possible to create files. This only happens for a mount directory itself, its subdirectories are handled correctly.
Nautilus works fine with the same directory (shows correct owner/permissions, and allows file creation).

Ubuntu 12.04, 32bit. Nemo 2.0.8 (package 2.0.8-20131203010008-precise from ppa:gwendal-lebihan-dev/cinnamon-stable).

**Comment by Vahan86** [comment]
@VladV, is this still an issue for you with Nemo 3.0.6?

**Comment by VladV** [comment]
Well, I no longer have the system where the problem occured, so can't say for sure.
Currently I have Nemo 2.6.7 on Mint 17.2, some NFS mounts, and everything works as expected.

**Comment by Vahan86** [comment]
@VladV, thanks for reply. In this case can you please close the issue?
