### ISSUE TITLE
[Feature Request] Drag and drop file on a (shell) script

### ISSUE THREAD

**Issue by pjbarendrecht** [linuxmint/nemo#500]
It would be very useful if one could drag and drop a file onto a (shell) script, such that the script is executed with the name of the file as input argument.

It is possible to do this in Thunar, but only when the script is marked as executable (chmod +x). I don't know if this is possible in Nautilus. 

See also http://forums.linuxmint.com/viewtopic.php?f=190&t=143870

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by DarkOwl2** [comment]
Does "completed" mean this feature has been included in Nemo?  I can't make it work in Linux Mint, Nemo version 5.8.5.  The request was made ten years ago.

I would like to migrate away from Windows, but the ability to write .bat files which will then accept drag&drop file sets as input (parameters %1, %2, %3...) is very useful in my work.
