### ISSUE TITLE
File picker does not honor location entry toggle

### ISSUE THREAD

**Issue by sandys** [linuxmint/nemo#501]
Referring to https://github.com/linuxmint/Cinnamon/pull/1617  https://github.com/linuxmint/nemo/pull/184 and https://github.com/linuxmint/nemo/pull/95

Location entry as a toggle works perfectly on Nemo, however it does not stick on the file picker (when invoked from Firefox for instance).

I'm using Ubuntu 12.04 with Nemo 2.0.8

**Comment by Vahan86** [comment]
@sandys, is this still an issue for you with Nemo 3.2?

**Comment by JosephMcc** [comment]
That is a dialog provided by Gtk and has nothing to do with Nemo.
