### ISSUE TITLE
Apply zoom to text in icon views and compact views

### ISSUE THREAD

**Issue by geoffm** [linuxmint/nemo#504]
When zooming into compact view or icon view, text remains same (small) size. Only thumbnails are bigger. This makes those views unusable if we zoom in to see the text bigger. For instance, when using a large screen with hi resolution.
I suggest it is made optional for each view in the 'Preferences' dialog / 'Views' tab.
[x] Apply zoom to text not just icons

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?
