### ISSUE TITLE
nemo does not show devices

### ISSUE THREAD

**Issue by BigBrotherLovesYou** [linuxmint/nemo#505]
nemo sometimes does not show usbsticks/ntfs-partitions under "Devices", but rather my nfs mounts. the behaviour is inconsistent, it is not present on every boot. kill'ing the "nemo -n" process and opening a new nemo window then shows the expected behaviour (devices/partitions under "Devices", network mounts under "Network"

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 2 years?

**Comment by AudioArchitect-R** [comment]
I recently had the same problem.  Suddenly nemo no longer lists my NTFS partitions under devices. Devices section is completely gone.  I'm using Linux Mint 18 Sarah Cinnamon.

Any help would be greatly appreciated.
