### ISSUE TITLE
[Feature Request] Give a warning when a file is too big for the given filesystem

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#506]
Currently copying a file witch is bigger than 4GB onto a 32Bit Filesystem like fat32
nemo is copying the first 4GB of the file and then gives an error message which tells "not enough space on device"

It would be nice if nemo could check for this before it starts copying and not after 4GB have been sent, this would save a lot of time when using the wrong usb-stick.

**Comment by Vahan86** [comment]
The issue is fixed in Nemo 3.0.6.
@ManIVIctorious, is this still an issue for you?

**Comment by ManIVIctorious** [comment]
Ah, you are right, I am glad this was fixed
