### ISSUE TITLE
[Feature Request]Filter Bar Option in Nemo to filter files inside a Folder

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#507]
Nemo can add a filter bar to filter files matching a certain pattern. (IIRC, Dolphin (KDE) has this). I am aware that there is a Search option and also a "Select Items Matching" feature that can be used. But in cases where you just need to filter and view files, this could be useful. Search may take some time to search and display results in a large directory. But I believe filter can do it almost instantaneously.

Sample screen shot for reference.

![dolphin-filterbar](https://f.cloud.github.com/assets/4663298/1919189/7d6ef064-7dcf-11e3-8420-bf39c7e19b26.png)

P.S. Now dont ask me to use Dolphin instead. :wink: I love Cinnamon & Nemo. :smile: Just thought this would be a nice addition.

**Comment by gopalpeddinti** [comment]
I would love this feature too! But now that I am posting after an year almost, does this already exist?

**Comment by dcbishop** [comment]
+1

**Comment by tobiasBora** [comment]
Me too I would be really interested by this feature ! Any news ?

**Comment by alvago** [comment]
+1 

If I need to search something on a server via smb.... it takes sooooo long :/

**Comment by bidinou** [comment]
+ 1
Super useful feature which I use all the time :)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by hiboudev** [comment]
I like this feature too, but isn't the ctrl+f bar enough?

**Comment by ScottWelker** [comment]
+1

**Comment by mtwebster** [comment]
I’ve actually been considering replacing the type-to-select with a view filter.

**Comment by bigbruno** [comment]
"I’ve actually been considering replacing the type-to-select with a view filter."

This is a best idea, type-to-select in nemo is very bad, but if use like dolphin filter make this even better then all file managers.

**Comment by tiago4171** [comment]
+1 @bigbruno

**Comment by bigbruno** [comment]
@mtwebster any news about implementation of this feature?

**Comment by McDulles** [comment]
+1 @bigbruno

**Comment by rafael-neri** [comment]
+1 @bigbruno
This feature is super useful.

**Comment by fladner** [comment]
this feature is very interesting

**Comment by LordGiodai** [comment]
@bigbruno 
That's a great idea!

**Comment by talesam** [comment]
Também adoraria a implementação desse recurso, alguma precisão??

**Comment by bigbruno** [comment]
Hello?
Hello?
Is anyone there?
Hello?
We can lift you out to safety. Please answer
my call if you can hear me.
Forget it, Billy boy.
It's a dead place.

**Comment by sitonir** [comment]
In Nemo it is necessary to do a full search using the shortcut “ctrl + f”, which takes a lot if the folder has many files.
In nautilus, for example, you just type the term and it displays the files and directories that contain that term in the current folder. In Nemo, it just selects the first file that contains that term and only if it has the beginning of the file name.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by bigbruno** [comment]
But we don't know if this idea is accepted or not?

**Comment by bigbruno** [comment]
@mtwebster No more add this feature?

**Comment by thisnickwasfree** [comment]
Still no information?

**Comment by boussou** [comment]
+1
+1
+1

**Comment by bigbruno** [comment]
Maybe in more 10 years

**Comment by danijoo** [comment]
news?

**Comment by boussou** [comment]
My solution for myself: use dolphin.

**Comment by Jeremy7701** [comment]
Aren't Filtering and searching essentially the same thing?
Except that filtering doesn't need a search key pressing to make it work?

**Comment by vyvir** [comment]
Dolphin allows to quickly find and open files/directories in current directory just by typing its name in real time.

With Nemo, you have to first type its full name in the search bar, then pressing Enter, then finding it in a list view instead of icon view.
With Dolphin, you just type the name until the moment you find the file. You don't need to type the entire filename; once you see it, you can immediately do whatever you want with it. 

https://github.com/user-attachments/assets/a043b664-f81f-4b7e-b6ac-c561f36bcb5e

**Comment by vyvir** [comment]
The previous file didn't work; I updated it with a differently encoded one.

**Comment by vyvir** [comment]
I would also like to note that the example shows finding a file based on a keyword that the user knows.
That's one case scenario.

Another example would be knowing the filename but not bothering to look for it in the directory.
With filtering, you can just type the filename and immediately see and operate on the file you need, while retaining the same icon view.

**Comment by vyvir** [comment]
Here are two more examples of quick file navigation through filtering:

![example1](https://github.com/user-attachments/assets/dea614ea-033c-4599-b103-48f03b8bddad)
![example2](https://github.com/user-attachments/assets/84306341-657b-44b2-b630-2de86fd2322c)

**Comment by vyvir** [comment]
So you know the file is located inside the current directory, but you don't want to bother to look through the directory to find it.
That's where the filtering comes in.

**Comment by vyvir** [comment]
A similar example would be navigating to ~/.local/share/themes
You can just open the home directory, type local, press enter (or navigate with arrow keys & press enter), type share, enter, type themes, enter. Which is faster than looking through individual filenames in order to find the file you need.

**Comment by vyvir** [comment]
The difference between this and searching:

1. The list of files gets updated in real time, leaving only files pertaining to the current query
2. Filtering is not recursive; it only concerns current directory
3. The view does not get changed (i.e. from icon to list) while looking for the file
4. The user can empty the query (Ctrl+A and Del) and immediately return to the full file list
5. The user can quickly hop between directories just by remembering their names

The main difference:

- Filtering allows quick navigation within current directory and between directories (immediate but limited to current dir; allows for quick navigation; not suitable for finding files recursively)
- Searching looks for files that aren't known to be in the current directory (longer but recursive; allows to search for lost files; not suitable for quick navigation)

**Comment by Jeremy7701** [comment]
All good points, but 
You can choose non-recursive or recursive searching.
You can switch a line display to an icon display.
You can use a mouse click to return from a search.

As for the speed thing, it depends on file structure and the PC capabilities.
Personally, I want recursive filtering/searching.

**Comment by vyvir** [comment]
Here is another example conveying what I'm trying to say.

https://github.com/user-attachments/assets/5aa76232-c660-4e1d-b828-7523127d50b7

**Comment by vyvir** [comment]
This is quick navigation in a chain of directories.
The non-recursive filtering here is useful because we are navigating from parent dir to child dirs.
This is a GUI equivalent of typing "cd directory-name" in a terminal, except you don't have to finish typing your keyword to find the directory you need.

**Comment by vyvir** [comment]
The recording also not sped up; This is how fast it takes to find the directory you need if you know at least a keyword from its name.

**Comment by Jeremy7701** [comment]
It only appears to filter on partial **directory** names - which doesn't help you find a file, though.

**Comment by bigbruno** [comment]
The filter in Dolphin instantly filters folders and files, including folders with thousands of files. In the video, the demonstration was done using a folder that had no files, only other folders.

The filter also works instantly when we are using ssh or other methods over the network.

**Comment by vyvir** [comment]
Apologies for misunderstanding. Here's a clearer demonstration.

https://github.com/user-attachments/assets/297475ed-09dc-470b-b838-43c198bb3578

**Comment by vyvir** [comment]
TL;DW Yes, it works on files too.

**Comment by boussou** [comment]
Same was requested for Thunar

summary of differences : 

- Having a permanently visible input at the bottom of the window/pane which is a filter to limit the number of files to display 
- stays in the current view mode (icon/compact/detailed)
- should be cleared on changing directories
- filters files displayed by entering a text that match against file names, in any part of the filenames, and it is realtime while we type.
- no disk access/no fetch: so it is still fast over a remote folder (nfs etc) or where there is huge number of files
- it does NOT loose the current selection (files currently selected) when you filter or remove the filter





https://gitlab.xfce.org/xfce/thunar/-/issues/1096#note_86205
