### ISSUE TITLE
Enable file bookmarks

### ISSUE THREAD

**Issue by rottmann** [linuxmint/nemo#509]
In the old Nautilus (before they change everything) i could add a file (unofficial) in the bookmark conf-File.
In nemo i try the same, but only the folder of the file open, not the file itself.

Would be nice if you can enable that again. 
A general right click on a file "add to bookmarks" would be great too :)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
