### ISSUE TITLE
[Feature Request] Add a history of my actions

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#510]
Situation: often when I realize my files have been copied or moved to a wrong place, I can undo this action by using "ctrl+z", but how about the action which I have made several step ahead?

my idea: like what linux do in bash, how about make a list which can record what we have done in nemo, simply even it don't need to have some related "re/un-do" action.
And these actions could include like:move,copy,delete,create,rename,etc.

why I need: people often tell me I can search files when I forget where they are (often I need add some wildcard), but If it can be done by several click, it should be better.

Thanks for all you have done, I love NEMO.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
