### ISSUE TITLE
[Feature Request] integrate fileroller in dual pane view

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#511]
My idea: when open a zipped file by archive manager(fileroller), it will show just on the Right pane of the NEMO(when using dual pane view).

Why I need: 
1.Once integrated, it will be no necessary to switch between two programs
2.It will be easier to locate a downloaded zipped file in NEMO.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
