### ISSUE TITLE
[FEATURE REQUEST] double panel / double path

### ISSUE THREAD

**Issue by brouillon** [linuxmint/nemo#513]
Using F3 for opening a second panel, 
it can be easier having two 'path chooser' (don't know the name 'url bar' ?) for each panel as nautilus do ? 

My 2 cents.

**Comment by MarioMey** [comment]
Some time ago I made this "how Nemo double panel should be" image. I think you are talking about this.

And yes, it would be great to have this.

![nemo-should-be](https://cloud.githubusercontent.com/assets/4954109/7785423/b9e0cef8-0165-11e5-99a6-d85c20cdca34.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by MarioMey** [comment]
I have forgotten my previous comment... now, I use Ubuntu-Mate, file manager is "Caja". I think Caja is using this double panel / double path. It is not exactly the same as the generated image I posted before, but it is what I need.
![pantallazo-4](https://cloud.githubusercontent.com/assets/4954109/20655633/275e39c8-b503-11e6-811e-b90028207fe3.png)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
