### ISSUE TITLE
Nemo tab mouseover behavior

### ISSUE THREAD

**Issue by sddfdds** [linuxmint/nemo#514]
Usually when transferring files between two folders in nemo where I have both open in tabs in one Nemo window, I can grab the files, drag them to the destination tab, and when hovering on the destination tab, nemo will change focus to the tab I am hovering over, making it easy to select a subfolder for transfer in the destination tab. (For example, if i have folder A in one tab, and folder B in another, and i want to transfer something from B to subfolder C inside folder A) Since installing mint 16 though, hovering over the destination tab does not switch to that tab, so you have to preselect the destination folder. Is there a setting I'm missing to cause nemo to switch to a folder when you hover over it's tab?  Alternately, is this a bug or an intended change?

**Comment by Vahan86** [comment]
The issue is still existing in Nemo 3.0.6.

**Comment by JosephMcc** [comment]
Confirmed. I can drag and drop on the tab but hovering doesn't switch to that tab.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
