### ISSUE TITLE
[Feature Request] Copy as the default drag/drop

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#515]
I would like a setting in Behaviour which makes the default drag/drop: Copy, and not move - even between places in the same filesystem. I am sick and fed up of copying things back!

**Comment by xenopeek** [comment]
You can do Ctrl + drag to copy instead of move.

Many thanks for contributing to Cinnamon. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
