### ISSUE TITLE
Type-ahead find feature not working properly

### ISSUE THREAD

**Issue by hotice** [linuxmint/nemo#517]
The type-ahead find feature (in which you type to select a file or folder in Nemo) doesn't work properly. When you want to select the second or third file that matches what you type, you'd normally use the scroll wheel to jump to it but that's not working in Nemo: only the first matching file or folder is selected and you can't jump to the next matches.

**Comment by Vahan86** [comment]
@hotice, is this still an issue for you with Nemo 3.0.6?

**Comment by hotice** [comment]
I got used to it now but yeah, it's the same in all Nemo versions since then, including 3.2.0.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
