### ISSUE TITLE
Nemo fill disk with errors entries in gnome-session.log

### ISSUE THREAD

**Issue by FM33** [linuxmint/nemo#518]
Hello,

On Ubuntu 13.10 64 bits with nemo 2.0.8, from ppa:webupd8team/nemo :
~/.cache/upstart/gnome-session.log is filled to disk full with these lines repeated :

(nemo:1755): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

*\* (nemo:1755): CRITICAL **: nemo_directory_file_monitor_remove: assertion 'NEMO_IS_DIRECTORY (directory)' failed

*\* (nemo:1755): CRITICAL **: nemo_directory_unref: assertion 'NEMO_IS_DIRECTORY (directory)' failed

(nemo:1755): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'
---

(nemo:1690): GLib-GIO-CRITICAL **: g_app_info_equal: assertion 'G_IS_APP_INFO (appinfo2)' failed

(nemo:1690): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(nemo:1690): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(nemo:1690): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by Vahan86** [comment]
@FM33, is this still an issue for you with Nemo 3.0.6?

**Comment by FM33** [comment]
I can't tell for 3.0.6 while ubuntu 16.04 is stuck at 2.8.7 I don't have issue with that version.

**Comment by Vahan86** [comment]
@FM33, thanks for your reply. In this case can you  please close this issue?
