### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by werewolfy** [linuxmint/nemo#519]
I really don't get why useful features (especially those distinguishing the Linux tools from Windows!) are removed despite having already been implemented in previous versions.

E.g. in older Nemo versions (IIRC) there was a feature to hide files from displaying in the file manager, albeit only on a "click by click" basis.
Not only has this feature not been vamped up to be more useful, it is not present any more.

Now, the thing I am trying to do is the following:

I'm setting up Mint for some long term Windows users and want to make it as easy and non-error-prone as possible for them:

One main point is hiding annoying/confusing/dangerous files, mainly from shared NTFS-partitions (like "$RECYCLE.BIN", "System Volume Information" etc.)
I do this via ".hidden"-files (which thankfully still work...)

I do however run into problems inside the user's "Desktop" folder.
I want to hide the "*.desktop" files (launchers) from the user, because adding and removing them is best done with the context menu on the desktop itself.
The Desktop-folder when viewed inside Nemo should be dedicated to data (i.e. mostly transient user documents and folders).
Moreover, the launchers are reported to be of type "text" in Nemo (ugh, ugly...)

There is absolutely no way to achieve this!
- There is no "hide" option in Nemo
- Renaming those files to dot-files does obviously not work, because this effectively prohibits them from being displayed on the desktop itself
- And putting their names into a ".hidden" file does exactly the same 

Also there is one more problem with the current way the ".hidden" file works:
Newly added files must be added manually, as wildcards are not supported.

Now, what is needed is a customizable filter file like ".hidden", but more powerful, i.e. supporting filtering expressions (regex-support would be optimal, but simple wildcard matching would be a good start anyway) that decides which files are displayed inside Nemo, and
1) either only inside Nemo by default, or 
2) there must be some exception for dedicated desktop launchers ("*.desktop"), or
3) there is some switch to decide, whether the file (or files) in question should be suppressed on the desktop, or in Nemo, or in both
Of course 3) is the most desirable option.

Adding to such a file this line:
*.desktop  _(wildcard version)_
or this
.*\.desktop  _(regex version - make configurable which is used!)_
would already solve my current problem, but there are many more complex scenarios, especially on Windows partitions, where most system files are not fit for usage on Linux, but user created content of course is.
If files hidden that way have to be accessed anyway, the shell does this at any time.
To facilitate the creation of entries for end users, a "hide/unhide" option in the context menu would be feasible, and a way to edit wildcard patterns.
An option "show hidden files" is already present, it just has to honour the new filter file (as it already does with ".hidden"). 

Please make Linux tools superiour to Windows in such regards, because that is one USP when trying to win Windows users over to Linux!

**Comment by xenopeek** [comment]
I think this issue can be closed. This was probably solved a longer time ago. Nemo 3.0.6 shows .desktop files in ~/Desktop with the application icon and opening those files starts the application.

**Comment by xenopeek** [comment]
What parts of this feature request still stand today? Cinnamon has other ways to launch applications that may be viable alternatives to putting launchers on the desktop if you don't want them there (like favorite in the menu or quick launcher on the panel). On Nemo 3.0.6 if you browse ~/Desktop it shows the .desktop files with their application name and icon. If you open a .desktop file from there the application is started instead. If you open the properties of a .desktop file you get to edit the launcher (display name, icon and command).

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
