### ISSUE TITLE
Feature Request (renaming files by two times clicking on them)

### ISSUE THREAD

**Issue by arnaghizadeh** [linuxmint/nemo#520]
Hey folks
Long time ago when I was still using windows there was this very nice feature that i'm still missing in Linux world! It is not a big thing but can make your life a lot easier if you know what i'm saying (like that nice new button that opens nemo as root which makes your life easier)!
so here it is I want when we click two times on a file or folder, with a little bit pause between them, it triggers rename of that file or folder! 
For seeing this in action any windows version does work just click on a file, pause a moment and click on it again then you can see that you can rename the file.
Really appreciate if someone does implement it! 
thank you very much!

**Comment by Chivey101** [comment]
Shame! it is such a handy feature in windows, but is differently a feature you love or hate. 
But having more options can only be a good thing.

**Comment by AjvarXX** [comment]
Any "fastpoke" who accidentally triggers rename due to long thinking while doubleclicking could set trigger time window after a whole second... or not to turn it on at all. Why would I use 2 hands for simple rename? Just doubleclick name!

**Comment by tinyhazeleyes** [comment]
Thanks for adding this.  It's so handy.
