### ISSUE TITLE
[Feature Request] grouped bookmarks

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#521]
right now it seems that a bookmark is only a link to a path,
How about let us make it like in firefox, we can create folders->sub-folders->items.
the benefit is one can open multiple locations in different tabs/(even extra panes) at one time, and it will be more organized for the bookmarks.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by aschenkels-ictstudio** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by codeyash** [comment]
_When you submit an idea, it is processed and then closed. It might lead to an implementation, it might lead to a design discussion within the team, it might be planned for a particular release and put on the roadmap, it might lead to nothing at all, or it might stick in people’s minds as something they could improve later on. Either way, your role is done when the idea is reported and once it’s understood by the development team._

This looks good.

Although a proper comment regarding feature would be appreciated. Simply closing without proper status is looks rude. Also for developers also it's hard to track without a proper issue id. 

I suggest rather closing create a new label like Future, Planning, Discussion  or similar.

I love linux mint !!

**Comment by JosephMcc** [comment]
> Although a proper comment regarding feature would be appreciated. Simply closing without proper status is looks rude. Also for developers it's hard to track without a proper issue id.

I suggest rather closing create a new label like Future, Planning, Discussion or similar.

In the end github is here for the devs to track things. Currently our github issues are essentially unmanaged. Leaving something sitting open for years isn't doing anyone any good. Closing something also doesn't mean it's gone forever. It's a simple matter to search closed issues. There are a huge number of open issues and most of them are either feature requests that in truth will probably never be implemented or very poor bug reports. Moving forward feature requests are going to be left just sitting here open and neither will bug reports that don't provide enough info for us to actually be able to fix them.

Just sifting through issues currently trying to find "fixable" bugs is a chore. That needs to change.
