### ISSUE TITLE
How to compile the source code

### ISSUE THREAD

**Issue by arnaghizadeh** [linuxmint/nemo#522]
hey folks
I was wondering how can I actually compile nemo from source?! the INSTALL file suggests a standard ./configure make but i get this error:
$ ./configure
bash: ./configure: No such file or directory

I searched the internet a little bit but couldn't find anything useful! am I missing something?!
for the record I don't want it to go and spread into my root folders and mess up my current installation, everything should stay nice and clean in the folder of nemo!
tnx

**Comment by nkkollaw** [comment]
I'm having the same exact problem in 2018.
