### ISSUE TITLE
Renaming ".desktop"-Files

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#523]
There is some inconsistency in file renaming regarding .desktop files.

When i rename a DESKTOP-File the filename extension ".desktop" gets added.
if i rename xyz.desktop to abc.desktop and hit enter the filename becomes to
abc.desktop.desktop

Please change this behaviour, it is really anoying

**Comment by xenopeek** [comment]
Bug reproduced with Nemo 3.0.6 on Linux Mint 18 Cinnamon. When renaming a .desktop file, the .desktop extension is _always_ added. So if you don't delete it when renaming the file the extension becomes ".desktop.desktop". It will add ".desktop" to the end each time you rename the file.

**Comment by DigitalArchon** [comment]
I just ran into this now, it still seems to be an issue despite being closed many years ago. You can't get rid of the .desktop when renaming a file once it has that extension, it just puts it right back.
