### ISSUE TITLE
Nemo crashes and eats all diskspace

### ISSUE THREAD

**Issue by oniongarlic** [linuxmint/nemo#526]
Sometimes when nemo crashes it starts eating all my disk by writing a lot of stuff to .xsession-errors, see
du -h .xsession-errors
13G .xsession-errors

Nemo deb version is
Version: 2.0.8-20131203010008-precise

Log is full of:
(nemo:2864): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

*\* (nemo:2864): CRITICAL **: nemo_directory_file_monitor_remove: assertion `NEMO_IS_DIRECTORY (directory)' failed

*\* (nemo:2864): CRITICAL **: nemo_directory_unref: assertion `NEMO_IS_DIRECTORY (directory)' failed

(nemo:2864): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `(null)'

(nemo:2864): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

*\* (nemo:2864): CRITICAL **: nemo_directory_file_monitor_remove: assertion `NEMO_IS_DIRECTORY (directory)' failed

*\* (nemo:2864): CRITICAL **: nemo_directory_unref: assertion `NEMO_IS_DIRECTORY (directory)' failed

(nemo:2864): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `(null)'

**Comment by Vahan86** [comment]
@oniongarlic, is this still an issue for you with Nemo 3.0.6?

**Comment by MichaelJCole** [comment]
I can't speak for @oniongarlic, but this hasn't happened to me in awhile.

**Comment by oniongarlic** [comment]
I'm stuck on 2.6.7 but this haven't happened to me anymore.

**Comment by Vahan86** [comment]
@MichaelJCole, @oniongarlic, thanks for your reply.
@oniongarlic, in this case can you please close the issue?
