### ISSUE TITLE
These ugly icons on desktop [Feature Request]

### ISSUE THREAD

**Issue by arnaghizadeh** [linuxmint/nemo#530]
Hey guys
This problem has been bothering me for a very long time, I remember I was asking clem when they were in mint12 to do something about it but he said that the decision depends on nautilus people, now that the control is on the right place I'm going to ask again....I think the fact that icons do not have a transparent borderline when they are selected makes them very ugly to look at and work with! I think the problem specially shows itself on desktop, simply put icons on desktop seem very loose and aesthetically a disaster, they are not very responsive with drop and drug either also they are stretched out a little too much!
these things forces me to avoid using desktop as much as I can instead of enjoying it!
If you don't still believe me just take a look at this picture bellow I can put 100 icons onto each other, just see how stupid and ugly they are! so I wanted to know what do you think about it and if there is a plan to make this wrong thing right?! 

![screenshot from 2014-02-03 22 05 08](https://f.cloud.github.com/assets/3886854/2074144/ad600ecc-8d72-11e3-8205-6b0856353519.png)

**Comment by inf3rno** [comment]
+1, I hate these icons either, but the grid is much more annoying...
