### ISSUE TITLE
[FEATURE REQUEST] A place to drop files into the current folder in detail and list views

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#531]
Currently if you're using expanded folders in the detail and list views, there's no obvious place to "drop" a dragged file when you want to move it into the parent directory.

It would be nice if by dropping it onto the location bar or column bar, if Nemo would move/copy the file and interpret the current directory as the target. Ideally with a pop up message to indicate exactly what's happening.

**Comment by xenopeek** [comment]
This has been implemented at some point in time (you can drop files on Nemo's location bar to copy them to the directory you've dropped them on). Many thanks for contributing to Nemo.
