### ISSUE TITLE
Remember position in tree when changing location in left pane

### ISSUE THREAD

**Issue by jensb** [linuxmint/nemo#537]
Nemo should remember the expansion state of the tree view in the right pane, at least until you close the window. For example:
- In the left side "My Computer", choose "Home".
- On the right side, navigate to some deep subfolder (e.g. Documents/Programming/ProjectXYZ/source/whatever).
- Insert a CD. In the same Nemo window, select the CD and navigate to a subdirectory on this CD (e.g. to copy files).
- On the left side, choose "Home" again.

Expected results:
- The tree that was expanded in the second step should still be expanded.
- The same should be the case when you navigate back to the CD.

Actual results:
- The tree is completely collapsed in both cases.

Can this be implemented? I would be perfectly satisfied when Nemo would only save the last 100 or so directory settings. Or simply the cursor position (and re-expand as required to show the previously selected file). (I wouldn't want Nemo to sprinkle settings-dotfiles over all my network shares like ".directory", "thumbs.db" etc.)

Thank you!

**Comment by Vahan86** [comment]
Can't reproduce in Nemo 3.0.6.
@jensb, is this still an issue for you in Nemo 3.0.6?

**Comment by jensb** [comment]
Can't test due to lack of nemo3 packages for Ubuntu 16.04, still running patched 2.8.7. (from PPA)
Do you know of any Nemo 3.0.6 PPAs for Ubuntu (without most Cinnamon dependancies) to test this?
