### ISSUE TITLE
Nemo media file meta data

### ISSUE THREAD

**Issue by garrett85** [linuxmint/nemo#538]
When I was using Mint 13 Cinnamon I could access my .mp3 audio meta data. After upgrading to Mint 15 Cinnamon there is no longer an 'Audio' tab for the meta data after right clicking a file and selecting properties. Please add media meta data to the properties of files in Nemo. I'm having to keep Nautilus around just for that purpose.

**Comment by igorer88** [comment]
This is still missing :cry:

**Comment by smurphos** [comment]
I can recommend this third party extension - https://github.com/linux-man/nemo-mediainfo-tab

![screenshot-window-2019-03-22-064708](https://user-images.githubusercontent.com/29017677/54805335-8b60c800-4c6e-11e9-846c-a087499bb17d.png)

**Comment by leigh123linux** [comment]
You need to install nemo-audio-tab extension
