### ISSUE TITLE
Option to ignore specific file sharing protocols or hosts in "Network"

### ISSUE THREAD

**Issue by jensb** [linuxmint/nemo#539]
I have a NAS which offers FTP, SMB, NFS, AFP and SSH connections. In Nemo's "Network" viewer, this host appears five times, which is confusing. However, I cannot switch off the different NAS protocols - I need SMB for my Windows client, AFP for Apple Time Machine, NFS for a second NAS, SSH for configuration remote access and FTP for my Smart TV connection.

**An option (doesn't need a GUI) to ignore everything except SMB (NFS, ...) protocol shares**, or to ignore host X's shares, would be really good. If nobody wants to take this issue, I'd be glad to step in and try something - in that case, please point me to a place where to start digging and outline roughly what would need to be done.

Thanks!

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
