### ISSUE TITLE
samba drive paths with spaces are shown percent-encoded

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/nemo#541]
When browsing samba shares with Nemo, special characters (such as spaces) are shown percent-encoded in the path bar (e.g. spaces are shown as (%20). This makes them very difficult to read.

The same happens when pasting paths into the path bar with these characters; they get converted to their percent-encoded equivalent.

In 'breadcrumb' mode, these paths are shown properly, however.

If this is caused by Samba, I would still suggest to have Nemo automatically convert the encoded characters to readable ones for display, if only for consistency; because local drive paths never shown as percent-encoded.

**Comment by tolinho** [comment]
I would also like to see this changed.

**Comment by icarter09** [comment]
@GitHubIsToxic is this still an issue?

**Comment by GitHubIsToxic** [comment]
Yes, still happens on Mint 19 with Nemo 3.9.0:

![perc_path](https://user-images.githubusercontent.com/6215449/71324734-f9c70500-24e2-11ea-93e9-bbdc37d9e686.png)

**Comment by GitHubIsToxic** [comment]
Nice work, thanks! :)
