### ISSUE TITLE
[Feature Request] Configurable Icon Size in Sidebar

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#542]
I would love to see the icon size configurable for folder, devices, network, etc shown in Sidebar. I find it to be too small for my 24 inch monitor. :wink: 

This could be setting in Preferences. Thanks.

Please see the screenshot below from Dolphin for reference. Of course, Nemo / Cinnamon is welcome to implement it better.
http://freininghaus.files.wordpress.com/2012/11/dolphin-2-2-beta-1.png

**Comment by rik-shaw** [comment]
+1

**Comment by mtompkins** [comment]
+1

**Comment by techdev5521** [comment]
As someone with a visual impairment, I would find these addition invaluable. Seeing as Cinnamon doesn't have proper GTK3 headerbar support, using Nautilus isn't possible as a workaround.

**Comment by JosephMcc** [comment]
> As someone with a visual impairment, I would find these addition invaluable. Seeing as Cinnamon doesn't have proper GTK3 headerbar support, using Nautilus isn't possible as a workaround.

How do you mean? Header bar applications work fine in Cinnamon: http://imgur.com/a/ON2Uq

**Comment by muzso** [comment]
I had a similiar issue: I've found that the font size (labels) in Nemo's Places Sidebar are too small. Nemo uses the default Cinnamon theme parameters for the sidebar, thus to change anything there, you either have to change the theme parameters system-wide or you've to dig into a theme and mess around with CSS.

For the first approach: there doesn't seem the exist a separate parameter for the icon size. You can merely set in "System Settings" / "General" the value of "Use interface scaling". Unfortunately it's either normal or double (or larger ... but the scaling factor behind this option is an integer value). There's a separate setting for the font scaling though. For the font size you can set in "System Settings" / "Fonts" either in "Font Selection" the "Default font"'s size from 9 to a larger value, or you can change in "Font Settings" the "Text scaling factor" from 1,0 to something larger. Both will enlarge the font size in Nemo's Sidebar.

For the second approach (i.e. no system-wide change, just icon/font change in Nemo's Sidebar) check out the following Q+A: http://askubuntu.com/q/328520
You've to create a CSS file with the "proper" styles (I'm not familiar enough with GTK to tell you how to get the required CSS selectors, but eg. looking into the strings in "/usr/bin/nemo" or into the source of Nemo you can probably find them). The selectors should look something like these: https://github.com/linuxmint/nemo/blob/master/src/nemo-style-fallback.css

**Comment by muzso** [comment]
I tried to use gtkparasite (https://github.com/chipx86/gtkparasite) to locate any CSS styles that might affect the icon sizes, but didn't succeed. I could change the various text sizes though on any UI elements (locally), so my attempts were not in vain. I had to add my style modifications to "/usr/share/themes/Mint-Y-Dark/gtk-3.0/gtk.css". Eg. to change the text size of the sidebar's list elements, I added this:
NemoPlacesSidebar {
  font-size: larger;
}

Of course Nemo had to be restarted.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by WindowsAndLinux** [comment]
I fully subscribe / vote for this feature. It would be awesome ! Icon sizes in sidebar / side pane should be sizable as in dolphin or with some other method.
Thank you

**Comment by danger89** [comment]
+1

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by soviet-man** [comment]
Icon size in sidebar still can't be changed! Awful!

**Comment by stonks1334** [comment]
+1

**Comment by spacekookie** [comment]
Nemo is otherwise literally the perfect file explorer, except for the sidebar icons being too small for me to read at a glance :(

**Comment by stephenaustin** [comment]
As per the comments above. It would appear that Nemo still lacks a way to increase the font / icon size of the sidebar. Thanks.

**Comment by adrielcgx** [comment]
+1

**Comment by adrielcgx** [comment]
+1

**Comment by xEricL** [comment]
+1
