### ISSUE TITLE
[Feature Request] Opening executable files with default editor via context menu

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#544]
There are three options to handle executable files: Always run, always edit or ask. With the first two options, there is no (direct) way to do the opposite via the GUI, i.e. if set to execute, there is a "open with"-submenu, but the default editor is missing from it, because its spot in the context menu is replaced by "Open" that will run the file. I would prefer the context menu to always contain two entries that are unambiguously labelled e.g. "Edit" and "Run" not one ambiguous "Open" that does whatever the setting is. Even when set to always ask, it would be quicker to have an entry in the context menu. (Until now I have been avoiding the problem by creating a Nemo-script to open a file with gedit.)

**Comment by CottonEaster** [comment]
I will second this proposal, if I may. It seems to me that the current arrangement is confusing and unhelpful.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
