### ISSUE TITLE
System crash when copying large amount of data to NTFS drive via symlink

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#545]
System: Ubuntu 13.10, Nemo 2.0.8.2
This happened under very specific circumstances, so I am not entirely sure which component is to blame, but it happened repeatedly and predictably:
I tried copying about 50GB of files by dragging it onto a symlink to an NTFS partition on an external drive with about 60GB free space.
- After a while, Nemo crashes (i.e. is greyed out and does not respond). At this point the whole system seems to gradually fall apart. 
- The most immediate symptom is that it is not possible to log in to any TTY, in that 
  after entering the username, no password prompt shows up. (At the same time a rudimentary rectangular pointer representing mouse movement appears.)
- The Unity environment seems to stop working properly without crashing completely, pretty soon; no programs can be launched. Most keyboard shortcuts do not work.
- Some programs (Firefox, Thunderbird) continue to run normally for a while.
- System monitor does not run properly, but (Laptop) fan activity does not indicate high cpu usage.
- After a while, mouse movement freezes and only Sys-Rq commands get any response.

**Comment by Vahan86** [comment]
@HifeFish, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
