### ISSUE TITLE
 [Feature Request] Dual pane start with preset paths.

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#548]
I like the dual pane view in Nemo, very convenient for organizing files.
My question is: is there a command I can use to open Nemo with dual pane view, and each pane with customized path?

Thank you.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
