### ISSUE TITLE
[Nemo_Actions] Implement Loop Function in Nemo_Action

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#549]
I tried to write a nemo action for xmgrace which should convert .agr files to .eps ones:

[Nemo Action]
Active=true
Name=In EPS-Datei umwandeln
Exec=AgrConverter.sh "EPS" %P %F
Icon-Name=xmgrace
Selection=notnone
Mimetypes=application/grace;
Quote=double
Dependencies=xmgrace;

This is the file which gets executed:
# !/usr/bin/bash

fileextension="$1"
shift

while [ $# -gt 0 ]
do
    cd "$1"
    xmgrace -hdevice "$fileextension" -hardcopy "$2"

```
shift
shift
```

done

As you can see i wanted to give the script the path to current file and then the file and executed this as often as many files got selected.
If i run the script from bash the way:

Agr2Eps "EPS" Path1 File1 Path2 File2 Path3 File3 ...

it works quite good and i expected nemo to handle it  this way, but it seems to me nemo instead does this:

Agr2Eps "EPS" Path1 File1 File2 File3 File4 ...

It is no problem to make the Script work, but the way nemo handles this feels quite unnatural to me... 

Especially i miss something like a loop parameter (like Loop=true) which would execute the whole Exec Line as many times as files got selected. This would be very helpful for conversion.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
