### ISSUE TITLE
Add Sort-Option by fileextension

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#550]
I am working with a lot of textfiles which all have the mime-type "text/plain" and their
filetype is "text" so i don't have any possibility to order them, than by filename.

It would be enough to implement this sort-option in list-view

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by ByteHazard** [comment]
+1 for this missing feature. It is extremely frustrating having to sort out individual files by hand in folders containing a few dozen of text files, which is quite a common task.

**Comment by Joeppie** [comment]
I just ran into this missing feature too, now I have to manually sort files :(

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by VitanovG** [comment]
+1
