### ISSUE TITLE
Rename multiple files.

### ISSUE THREAD

**Issue by testman42** [linuxmint/nemo#553]
How is this not functional yet? It's 2014, that is half-past the future, and we still can not select and rename multiple files at once in Nemo (v2.0.8).
http://imgur.com/cXjFCls

**Comment by tp0** [comment]
I am using Thunar's bulk renamer. Works nicely and with multiple file selection too.

Instructions: http://forums.linuxmint.com/viewtopic.php?f=29&t=162435#p857689

**Comment by Madh93** [comment]
Any news?

**Comment by ManIVIctorious** [comment]
In gnome 3.22 nautilus gained support for renaming multiple files, couldn't test this by now, but if it's well made maybe this could be ported from there?

**Comment by feren** [comment]
@ManIVIctorious It would require un-headerbaring given Nemo's UI, but it should be possible, not a dev here, but I'd guess it'd work given that (I think) Nemo's a fork of Nautilus anyway

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by tethragon** [comment]
I really think nemo devs should reconsider this. Almost all file managers can mass rename files featuring many options (numbering, date, text replace etc.). Nemo can't out of the box mass rename files and users must install another file manager and set nemo to use the other file manager to mass rename files.

![File Management Preferences_002](https://user-images.githubusercontent.com/39238674/71771403-bf2d8580-2f42-11ea-9c0c-f8962f9e1086.jpg)

**Comment by saraaba** [comment]
I refuse to install another file manager just to bulk rename, that just shows failure of Nemo

Craete an extension and that is fine, installing a complete file manager is not.

**Comment by Jeremy7701** [comment]
See [https://mintguide.org/tools/596-pyrenamer-mass-rename-files-and-folders-in-linux.html](https://mintguide.org/tools/596-pyrenamer-mass-rename-files-and-folders-in-linux.html) for a GUI program.
Don't expect Nemo to do all possible things with the word "file" in them...

**Comment by smurphos** [comment]
pyrenamer is a dead project - not available in Mint 19 or 20.

You can use gprename with a wrapper script to get over gprename's dislike for URI format file paths.

1) Install gprename
```
apt install gprename
```
2) Create wrapper script
```
sudo tee /usr/local/bin/gprename-nemo <<'EOB'
#!/bin/bash
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }
filePath=$(urldecode "$1")
gprename "$(dirname "$filePath")"
EOB
```
3) Make wrapper script executable
```
sudo chmod +x /usr/local/bin/gprename-nemo
```
4) Set gprename-nemo as the bulk-renamer
```
dconf write /org/nemo/preferences/bulk-rename-tool "b'gprename-nemo'"
```

**Comment by KrischnaGabriel** [comment]
Welp, that didn't worked,

**Comment by Jeremy7701** [comment]
In what sense didn't it work? Is it possible that you need to exit nemo and restart?
"It works for me".

It's not a proper nemo multiple file rename feature; it just allows you to fire up `gprename` anytime you attempt to rename more than one file in nemo.
Both the actual file selection and renaming are done in a non-nemo program (`gprename`).
AFAIK the actual multiple nemo-rename feature is still to be implemented, but I might be wrong.

To use it, navigate to the appropriate directory in nemo, select say 2 files - doesn't matter which two, choose rename and `gprename` will pop-up a file selection screen for you to choose the multiple files to rename.

**Comment by mtwebster** [comment]
fyi: https://github.com/linuxmint/bulky

**Comment by ItzSwirlz** [comment]
Bulky would be the better solution (I took a quick glance at it).

**Comment by Jeremy7701** [comment]
I feel sure it will be included in Mint / LMDE quite soon.
*"It's an XApp so it can work in any distribution and many desktop environments (Cinnamon, MATE, GNOME, etc..)."*

**Comment by KrischnaGabriel** [comment]
With "It didn't worked" i mean, when trying to bulk rename files/folders after following the given instructions,
a window popped up and closed/crashed directly afterwards.
I tried to use Bulky as suggested, but couldn't compile it from source. This error occurred:
```
Building the mo files
# WARNING: the second sed below will only works correctly with the languages that don't contain "-"
for file in `ls po/*.po`; do \
	lang=`echo $file | sed 's@po/@@' | sed 's/\.po//' | sed 's/bulky-//'`; \
	install -d usr/share/locale/$lang/LC_MESSAGES/; \
	msgfmt -o usr/share/locale/$lang/LC_MESSAGES/bulky.mo $file; \
done \
```

What did worked out was Thunar as also called out from Bulky.
Installation was according to these guys:
https://forums.linuxmint.com/viewtopic.php?f=42&t=282508&p=1999896
