### ISSUE TITLE
Option To Show Folder Sizes In List View

### ISSUE THREAD

**Issue by InkKnife** [linuxmint/nemo#554]
As found in the OSX Finder. The option to tell Nemo to calculate and display folder sizes in list view.
![35ovsjo](https://f.cloud.github.com/assets/6894933/2366765/16889398-a71c-11e3-911f-6c0c066f8c8e.png)

**Comment by adamryczkowski** [comment]
This stuff may be **much** more costly if the directory is a 10TB+ remote folder full of kernel sources... I think the only practical solution is demand-only, otherwise this functionality would effectively prevent nemo from browsing anything remote and big (like NAS shares over WiFi).

**Comment by azjio** [comment]
In the folder properties. Folder Size is calculated once and the user's request. Folder size is calculated when you click on the tab. In the folder tree to make a context menu to jump to a folder. Also in the context menu there is an item to delete the selected folder. Sorting by size. The size of the folder appears at the beginning of the name (For example, "[97 Gb] Name"). Symbolic links are not processed (For example, "[?] Name")
http://s018.radikal.ru/i520/1503/c5/e2e9bc0d6d09.png

**Comment by tp0** [comment]
> This stuff may be much more costly if the directory is a 10TB+ remote folder full of kernel sources... I think the only practical solution is demand-only, otherwise this functionality would effectively prevent nemo from browsing anything remote and big (like NAS shares over WiFi).

Simple solution for that: calculate only local folders (just like Preferences > Preview > Show thumbnails > Always/Local files only).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by adotka** [comment]
+1. I miss this in Nemo forever

**Comment by mattmon** [comment]
+1

**Comment by nick-s-b** [comment]
So much this! This "9 Items" stuff in a size column is meaningless. It should display the actual size on disk and not this nonsensical "items" stuff.

![https://i.imgur.com/8xEOT89.jpg](https://i.imgur.com/8xEOT89.jpg)

@mattmon it takes less than a half a second for Nemo to calculate the size when I hit properties. Also, this can be cached.

**Comment by hipunk** [comment]
I also miss this feature a lot. It makes it much easier and also simpler to figure out what is what.

Making it optional would make everyone happy, I suppose.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by wimglenn** [comment]
Anywhere to see outcome of the review of a feature request? I read the FAQ linked, but it's not really clear whether resolution means "will not do" or "nice to have".

**Comment by alexanderdd** [comment]
@JosephMcc can you please specify which of these cases apply to this bug report:

> When you submit an idea, it is processed and then closed. It might lead to an implementation, it might lead to a design discussion within the team, it might be planned for a particular release and put on the roadmap, it might lead to nothing at all, or it might stick in people’s minds as something they could improve later on.
(from https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html)

**Comment by JosephMcc** [comment]
@alexanderdd I'm not really sure what answer you are looking for. The whole thing applies, That paragraph states pretty well how feature requests can be handled. This is clearly a request and not a bug report. It was marked as such and closed. That means anyone interested can still easily search for it and read what feedback people gave on the idea.

**Comment by alexanderdd** [comment]
@JosephMcc what is a good place for a meta discussion about how bug reports are handled in the linux mint project?

For this particular bug: For me a **review** includes a decision on how to continue with the issue. You said "Your suggestion was reviewed." I was expecting that you also specify which decision you made:

1. "will be implemented"
2. "will not be implemented"
3. "can be implemented if someone wants to do it"
4. "....."

Closing an issue implies that it has been fixed or there was a decision not to fix it/implement it.

**Comment by nav9** [comment]
I was just about to request for this feature on the Mint forum, and I found this issue closed. When we open a terminal and run `ls -altrh`, it displays the folder sizes. I'm assuming these are approximate sizes. Couldn't we use that information to display on Nemo? It really doesn't make sense to show the number of items in a column that says "[Size](https://ibb.co/PzQhywy)". I hope this issue could be re-opened.

**Comment by Jeremy7701** [comment]
A long-standing request.
However, showing a "size" of a folder can mean different things.
1. Is it the just the number of folders and files in a folder?
or is it
2. the number of folders and files +  sub-folders and files - but recursively?
or is it
Option 1 or 2 but the size in bytes?

**Comment by wimglenn** [comment]
Option 2 in bytes

**Comment by nav9** [comment]
My apologies. `ls -altrh` does not actually show the folder size. `du -sh *` did. But I noticed it took some time to calculate. So I guess it'd need to be part of a separate thread, if it's implemented and any user wishes to enable it. This would perhaps require changing the display word "Size" to "Items" or "Num items" and having a new column named "Size", which would perhaps be disabled by default, and the user could right click and enable. With SSD's and NVMe's, I guess there wouldn't be that much of a performance hit.

**Comment by azjio** [comment]
i made my own application
https://www.purebasic.fr/english/viewtopic.php?t=77012

ср, 5 июл. 2023 г. в 17:19, Nav ***@***.***>:

**Comment by hipunk** [comment]
Amazing, it works flawlessly. Thank you!
Here's the translation of the one text file, in case anyone needs (Yandex Mobile Translate):
"This file (FileSizesList.nemo_action) should be put in the folder "/usr/shares/Nemo/actions", if the Nemo file manager is used, then the folder's context menu will display the item "Folder sizes", all this is configured in the FileSizesList.nemo_action file itself."

Greetz


Am 9. August 2023 um 14:20 schrieb "azjio" ***@***.***>:

**Comment by tigger6333** [comment]
Hey azjio              

"i made my own application
https://www.purebasic.fr/english/viewtopic.php?t=77012"

Thanks for your FileSizesList Nemo add on. It's working terrifically well.
The only issue I have is that Window title and menu lists are in Russian. Is there a way that I can set them to be my default English?

Thanks again

**Comment by azjio** [comment]
>  Is there a way that I can set them to be my default English?
Yes, now I have made English the default. You can also use the Lang.txt file to set any language. Also you can use forcelang=1 in the ini file to force the use of the 1st internal language (English).
In addition, the ability to save the list to a file and disable sorting by size has been added.
