### ISSUE TITLE
[Feature Request] Back to real path of linked folder

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#555]
I just learned that in bash shell "pwd -P" can show real path(avoid symlinks) of file/folder
Can Nemo add an option to let nemo back from symlinked folder to the "real path" of it?

Thanks

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by mtwebster** [comment]
I'm not commenting one way or the other on the feature request yet (I'm still trying to wrap my old brain around it,) I just wanted to point out that if you enable the Preferences->Preview->Tooltips->File or Folder location option, it will show the original location in the tooltip, in case this wasn't known (of course the preferences page doesn't mention it)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
