### ISSUE TITLE
[Bug?] "open file manager" of  removable-driver applet not work

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#557]
When using removable-driver applet, there is a button called "open file manager"
but it didn't work in my computer, so I check  the applet.js , it indicates the applet run
let app = appSystem.lookup_app('nemo.desktop');
then I check what nemo.desktop do, it runs : nemo -n( --no-default-window)
Do it the reason why it doesn't work?
[nemo 2.0.8]

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for 2 years?
