### ISSUE TITLE
List mountpoints in sidebar

### ISSUE THREAD

**Issue by rjanja** [linuxmint/nemo#56]
I have a couple of hard drives that are mounted via `/etc/fstab` at mountpoints within `/mnt`. Although I could bookmark each one, and possibly move these bookmarks into the "Computer" sidebar section, I think there ought to be a standard behavior of listing mountpoints - at least for the devices where it would make sense to do so.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
