### ISSUE TITLE
[Feature Request] New Folder from Selection

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#560]
Some of my friends told me that there is a function call "New Folder from Selection" is coming in the new nautilus, it acts like following:
For example, files in folder: Pic01,Pic02,...,Pic10 ; after select these files and right click them, the "New Folder from Selection" in menu will make a folder called "Pic"(some common name from these files) and move all selected files into this folder.
In order to do so,I make a nemo-actions:
Name=Put them into same folder
Exec=<NewFolderWithSelection.py %F>
Quote=double

Code in this python:
# !/usr/bin/env python3

import os
import sys
from time import time,localtime,strftime
import shutil
# time-tag as the default folder name if the foldername is exist, better solutions?

DefPath=strftime("%Y-%m-%d_%H-%M-%S",localtime(time()))
AllPath=[]
for i in sys.argv[1:]:
    AllPath.append(i)
CommonPath=os.path.commonprefix(AllPath)
isExists=os.path.exists(CommonPath)
if not isExists:
    pass
else:
    CommonPath=os.path.join(CommonPath,DefPath)
# move selected files to the target folder

os.makedirs(CommonPath)
for i in sys.argv[1:]:
    shutil.move(i,CommonPath)

I just learned python this month, so I think there must be someone can make it better.

**Comment by andrew160** [comment]
:+1:

**Comment by alextpedro** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by byaruhaf** [comment]
+1

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by mxa** [comment]
I'd imagine it like this: I select a couple of items in a folder. Right-click and choose something like "move to new folder". This action will make a new folder, move the files into it and let's me name that folder. Miss this function very much!

**Comment by JosephMcc** [comment]
> 'd imagine it like this: I select a couple of items in a folder. Right-click and choose something like "move to new folder". This action will make a new folder, move the files into it and let's me name that folder. Miss this function very much!

Not sure how this is really saving you much over right-click->new folder, drag and drop the files to it.

**Comment by mxa** [comment]
Let's say it is a media directory and there are about 50 folders in there and 200 files. Down at the letter s you have tree files you would like to put in a folder. Making a new folder will place this at the letter N amongst fhe folders. Even naming it the same as the files will group it amongst the folders. It is messy.

**Comment by JosephMcc** [comment]
Fair point.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
