### ISSUE TITLE
]Feature Request] Auto Close Nemo After Opening File With Application

### ISSUE THREAD

**Issue by clive1000** [linuxmint/nemo#567]
Background: I am using LM16's multiple desktop feature and finding it a great boon.  However there are a lot of windows to look through when searching four desktops at quarter scale. Minimising the number of windows would be good.

Idea: It came to me that it would be helpful if nemo could automatically close after opening a file with an appropriate application using a special key combination - say shift-double left mouse click. This is perhaps analogous to the choice between opening an application in a terminal or not as required. The key combination shift-left mouse click would be appropriate in the nemo "open with" dialogue

Research: I checked cinnamon key assignments and could find none for this or a similar function so I am assuming it currently does not exist. Also, I cannot think of any settings I could make that would produce this functionality. Shift-Double left mouse click does not appear to used currently by nemo. 

Thoughts welcomed. I am not a programmer but I am able to help with testing if the idea has any legs.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by clive1000** [comment]
I was pleased to see this had not been lost or forgotten. I am on LM18.1 now, but the, 'New feature request #567,' is still applicable and still stands.

A couple of extra comments that come to mind:

1. The existing nemo option to choose between a single click or a double click  to launch a program with the selected file as the input would need to be respected. This should not be an issue with the proposed scheme.

2. An additional new option in nemo  preferences is not strictly required as holding down a shift key when single or double clicking a file does nothing currently so changing the operation to closing down the nemo instance after launching the program with the selected file should not break anything. However I would prefer a new option in the preferences to allow the user to set the default action to no-autoclose or autoclose, in which case holding down the shift key would invert whatever is the chosen default action.

I hope this is useful.

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
