### ISSUE TITLE
[Feature Request] show compress progress in popped up window

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#568]
I'm not sure if it is a nemo issue or cinnamon issue, but I post here first.
Situation: when compress files or folders with by using (rightClick Menu)->(compress...)
I can't see the percentage progress of the compress but only shows like N files renaming.
While using 7z command line, we can see this percentage progress[0%~100%]. So could this feature be embedded in?

Thanks

**Comment by Vahan86** [comment]
@JosephMcc, can be marked as a feature request?

**Comment by ManIVIctorious** [comment]
Honestly I don't think that this is a nemo issue.
When you use the rightclick compress option you are running the [nemo-fileroller](https://github.com/linuxmint/nemo-extensions/tree/master/nemo-fileroller) extension.

It may be possible that this is an issue of the extension, but I would expect the problem in fileroller itself, which the linuxmint developers don't maintain.
So chances are hight that this can't be adressed

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
