### ISSUE TITLE
[Feature Request] highlight tab of nemo

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#573]
Why I need this:
1. I can easily tell which tab I am in, 
2. more important, there is no warning windows(or I cancel that?) when closing nemo window with multiple tabs, sometime I may accidentally close other tabs.
How to highlight:
Add an option to let tab  highlight with some color( green ,blue ,orange...)
![screenshot](https://cloud.githubusercontent.com/assets/6413481/2598463/2a7887d6-bac8-11e3-870e-2981c5f073ea.png)
![screenshot](https://cloud.githubusercontent.com/assets/6413481/2598483/c1b1c392-bac8-11e3-9e7c-dee04f347de0.png)

**Comment by michalskop** [comment]
@JosephMcc is there a way to get different colours for panes (active vs. inactive) in Nemo for Ubuntu/Unity?

**Comment by JosephMcc** [comment]
It should be but it's really up to the theme you use to provide it. I'm haven't worked with gtk3.22 much myself but everything needed as far as selectors for the css should be there.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
