### ISSUE TITLE
Menu icons not following icon themes. Switch back to stock icons for menu bar 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#575]
https://github.com/linuxmint/nemo/commit/9598136c8737259d711d0570a93004d6d972809e
changes the menu icons from gtk stock icons to "nemo" prefixed symbolic items like "nemo-go-next-symbolic.svg"
This fixed the leak of svg icons in some stock item themes required on HiDPI displays. 

Unfortunately this moves away from an unified desktop experience. 
I like to have the same icon for the same things in all applications. 
The back button in Firefox should have the same appearance than the Nemo back button.  

Can we move back to gtk stock icons without "nemo" prefix? IMHO it is better to fix the Issue inside the Linux Mint Icon themes. This way all application will benefit from the scalable icons.

**Comment by icarter09** [comment]
@JosephMcc can this ticket be closed?
