### ISSUE TITLE
[Feature Request] Pure ASCII filename sorting

### ISSUE THREAD

**Issue by lore68cnc** [linuxmint/nemo#578]
Nemo 'by name' files sorting uses 'logical ordering' which fails in some cases (always with hexadecimal character in filenames).
I request to introduce an option in Nemo Preferences -> Behavior to use a "pure ASCII" order, like "ls -la" output.
In Windows this is very simple, see http://support.microsoft.com/kb/319827.
Why Linux is more more complicated than Windows?

Related to "Sorting by filenames - Incorrect order" #205

**Comment by NETHeader** [comment]
+1
I copy bbshopadmin's statement, would love to see that feature in nemo.

**Comment by hachesilva** [comment]
+1

**Comment by ByteHazard** [comment]
+1
Please fix this. This really is shortcoming so important, it should be classified a bug. There are no excuses, Windows 3.11 did this 1994!

**Comment by bernd-wechner** [comment]
+1 as well. Danged frustrating smarty sorting. Give us some sort options here, with plain old ASCII as one. Give me same order as `ls -l` for example.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by baikalov** [comment]
+1 
Is there an ETA for this? This is really frustrating to use it without ASCII sorting.
Please fix this!

**Comment by bernd-wechner** [comment]
Please, please, please fix this!

**Comment by binarez** [comment]
Is this caused by g_uri_escape_string ? It seems like the filenames are passed thru this func before sorting. Not sure if changing this would be a security issue. Thoughts?

**Comment by ManIVIctorious** [comment]
The file sorting is based on your local settings, I don't think this is in the scope of the project...

**Comment by bernd-wechner** [comment]
> The file sorting is based on your local settings, I don't think this is in the scope of the project...

I disagree. To begin with ls doesn't do any such thing, and I'd expect the default behaviour of a GUI file browser to be the same as ls. Secondly it is perfectly valid to desire a different sorting mechanism for different apps on a desktop system and so implementing a sort setting in Nemo one selection on which might be "As defined by locale" is sensible.

But that aside, you might help us by explaining just which locale settings influence Nemo's sorting behaviour and how to set them.

**Comment by ManIVIctorious** [comment]
Sorry, forgot about this...
The environment variable is LC_COLLATE (in my case =C) and nemo behaves exactly as ls does on my system

**Comment by bernd-wechner** [comment]
Nice. It does come with caveats mind you:

1) Far from intuitive. I mean how long did take the tip to reach this thread?

2) Double far form intuitive. How to do it? if I set this variable and run nemo form command line, it works. If I run nemo from start menu (Mint 18.2) it does not. It is set in .profile when I log in. Has always been so was when this Cinnamon session started. Yet running it from start menu does not see that variable.

I'm sure there's a way to do it but my point is, far from intuitive and I'm stumped for now.

**Comment by ManIVIctorious** [comment]
Well in that point I have to agree, its really not very intuitive.
It has definitely been a lot easier for me as Arch user, since I had to set this anyway... 

Just as information to set it permanently: You have to write it into the file /etc/locale.conf or you can set it by running `localectl set-locale  LC_COLLATE=C` with root privileges (at least if Mint is already that far up-to-date)

**Comment by w3333** [comment]
+1 
Already posted on #842. It would be very nice to have the option of a more standard way of name sorting. Either keep the current sorting as standard and add options like "(X) respect letter case" and "(x) do not ignore special characters" or make Linux standard sort order the default and add "(x) sort by name in logical order". Something like that.

**Comment by WhyNotHugo** [comment]
I've `LC_LOCALE` set to `C`. `ls -l` sorts the way I expect it to, but `nemo` sorts differently.

Apparently, nemo puts `.` before any numbers, so files are sorted kinda like:

```
file-7.png
file-100.png
```

The problem here is the inconsistency between ls (and others) and nemo. Rather than actually add a preference for this, I'd rather nemo merely picked up the system-wide value. Users can always configure that anyway.

**Comment by voltarontas** [comment]
+1

**Comment by Zapalot** [comment]
I had a tough time but made it work on my computer.

**First the trouble:**

`localectl set-locale LC_COLLATE=C`

indeed changed the order, but left the locale settings in a broken state so I could no longer run gnome-terminal and a lot of other configuration tools.
`localectl set-locale LANG=en_US.utf8` fixed that.

**Now the solution**
in order to get the desired sorting, you need to create your own localization.
(https://unix.stackexchange.com/questions/288333/how-can-i-make-ls-show-dotfiles-first-while-staying-case-insensitive/361006) gave me all the necessary information.

The actual sorting information is in the file `iso14651_t1_common`, which is referred to by `iso14651_t1`, which is in turn used by the actual locale definition (i.e. `en_US`, or whatever you prefer to use). We will make copies of all the files we change, compile those copies and tell the system to use the resulting binary.

1. go to `/usr/share/i18n/locales/`
2. make a copy of your desired locale definition (i.e. `en_US` to `en_US_sorted`)
3. make copies of the files that contain the ordering information (`iso14651_t1` and `iso14651_t1_common`)
4. edit  `en_US_sorted` to use `iso14651_t1_sorted` instead of `iso14651_t1`
5. edit `iso14651_t1_sorted` to use `iso14651_t1_common_sorted` instead of `iso14651_t1_common`
6. make the desired changed to `iso14651_t1_common_sorted` - the stackoverflow post above gives all the info you need. 
To make underscores appear first, I changed the line 
`<U005F> IGNORE;IGNORE;IGNORE;<U005F> # 33 _`
to
 `<U005F> <RES-1>;IGNORE;IGNORE;<U005F> # 33 _`

7. compile your locale definition (`localedef -i en_US_sorted  -f UTF-8 -vc en_US_sorted.UTF-8`). Lots of warnings unrelated to our edits, but works anyway.
8. tell the system to use the new locale (`localectl set-locale LANG=en_US_sorted.utf8`)
9. reboot

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by damian101** [comment]
I switched to Plasma, because Dolphin can sort my files in a useful way.
In Dolphin you can even choose between natural and alphabetical sorting.

**Comment by blueray453** [comment]
> I had a tough time but made it work on my computer.
> 
> **First the trouble:**
> 
> `localectl set-locale LC_COLLATE=C`
> 
> indeed changed the order, but left the locale settings in a broken state so I could no longer run gnome-terminal and a lot of other configuration tools.
> `localectl set-locale LANG=en_US.utf8` fixed that.
> 
> **Now the solution**
> in order to get the desired sorting, you need to create your own localization.
> (https://unix.stackexchange.com/questions/288333/how-can-i-make-ls-show-dotfiles-first-while-staying-case-insensitive/361006) gave me all the necessary information.
> 
> The actual sorting information is in the file `iso14651_t1_common`, which is referred to by `iso14651_t1`, which is in turn used by the actual locale definition (i.e. `en_US`, or whatever you prefer to use). We will make copies of all the files we change, compile those copies and tell the system to use the resulting binary.
> 
>     1. go to `/usr/share/i18n/locales/`
> 
>     2. make a copy of your desired locale definition (i.e. `en_US` to `en_US_sorted`)
> 
>     3. make copies of the files that contain the ordering information (`iso14651_t1` and `iso14651_t1_common`)
> 
>     4. edit  `en_US_sorted` to use `iso14651_t1_sorted` instead of `iso14651_t1`
> 
>     5. edit `iso14651_t1_sorted` to use `iso14651_t1_common_sorted` instead of `iso14651_t1_common`
> 
>     6. make the desired changed to `iso14651_t1_common_sorted` - the stackoverflow post above gives all the info you need.
>        To make underscores appear first, I changed the line
>        `<U005F> IGNORE;IGNORE;IGNORE;<U005F> # 33 _`
>        to
>        `<U005F> <RES-1>;IGNORE;IGNORE;<U005F> # 33 _`
> 
>     7. compile your locale definition (`localedef -i en_US_sorted  -f UTF-8 -vc en_US_sorted.UTF-8`). Lots of warnings unrelated to our edits, but works anyway.
> 
>     8. tell the system to use the new locale (`localectl set-locale LANG=en_US_sorted.utf8`)
> 
>     9. reboot

I was going to write the same solution. Came from the same sources which are -

[Specify the sort order with LC_COLLATE so lowercase is before uppercase](https://unix.stackexchange.com/a/361021/206574)
[How can I make “ls” show dotfiles first while staying case-insensitive?](https://unix.stackexchange.com/a/361006/206574)

For the time being, why can't we just ship the locale file with the next release? And sneak in a option in **File Management Preferences** somewhere.

**Comment by baikalov** [comment]
Create a locale file is a great idea.
There is a bit of improvement you can do for above solution.
You don't have to change iso14651_t1_common nor iso14651_t1
You can take advantage of "reorder-after"

Here is the procedure to make "_xxx" and other special characters sort to the top of the list.
You can adopt it to sort anything anyway you want.

1. make a copy of your favorite locale file. 
I will use "/usr/share/i18n/locales/en_CA" as example. 
Copy it to "/usr/share/i18n/locales/en_CA_sort"
2. Edit new file: add following right before line "reorder-end"
```
# following block uses "#" as a comment_char
# check the top of you file, if it defines different comment_char, 
# replace "#" with that character.
 
reorder-after <RES-1>
<U0020> <U0020>;IGNORE;IGNORE;IGNORE # 32 <SP>
<U005F> <U005F>;IGNORE;IGNORE;IGNORE # 33 _
<U0332> <U0332>;IGNORE;IGNORE;IGNORE # 34 <"_>
<U00AF> <U00AF>;IGNORE;IGNORE;IGNORE # 35 - (MACRON)
<U00AD> <U00AD>;IGNORE;IGNORE;IGNORE # 36 <SHY>
<U002D> <U002D>;IGNORE;IGNORE;IGNORE # 37 -
<U002C> <U002C>;IGNORE;IGNORE;IGNORE # 38 ,
<U003B> <U003B>;IGNORE;IGNORE;IGNORE # 39 ;
<U003A> <U003A>;IGNORE;IGNORE;IGNORE # 40 :
<U0021> <U0021>;IGNORE;IGNORE;IGNORE # 41 !
<U00A1> <U00A1>;IGNORE;IGNORE;IGNORE # 42 ¡
<U003F> <U003F>;IGNORE;IGNORE;IGNORE # 43 ?
<U00BF> <U00BF>;IGNORE;IGNORE;IGNORE # 44 ¿
<U002F> <U002F>;IGNORE;IGNORE;IGNORE # 45 </>
<U0338> <U0338>;IGNORE;IGNORE;IGNORE # 46 <"/>
<U002E> <U002E>;IGNORE;IGNORE;IGNORE # 47 .
<U00B7> <U00B7>;IGNORE;IGNORE;IGNORE # 58 ×
<U00B8> <U00B8>;IGNORE;IGNORE;IGNORE # 59 ¸
<U0328> <U0328>;IGNORE;IGNORE;IGNORE # 60 <";>
<U0027> <U0027>;IGNORE;IGNORE;IGNORE # 61 '
<U2018> <U2018>;IGNORE;IGNORE;IGNORE # 62 <'6>
<U2019> <U2019>;IGNORE;IGNORE;IGNORE # 63 <'9>
<U0022> <U0022>;IGNORE;IGNORE;IGNORE # 64 "
<U201C> <U201C>;IGNORE;IGNORE;IGNORE # 65 <"6>
<U201D> <U201D>;IGNORE;IGNORE;IGNORE # 66 <"9>
<U00AB> <U00AB>;IGNORE;IGNORE;IGNORE # 67 «
<U00BB> <U00BB>;IGNORE;IGNORE;IGNORE # 68 »
<U0028> <U0028>;IGNORE;IGNORE;IGNORE # 69 (
<U207D> <U207D>;IGNORE;IGNORE;IGNORE # 70 <(S>
<U0029> <U0029>;IGNORE;IGNORE;IGNORE # 71 )
<U207E> <U207E>;IGNORE;IGNORE;IGNORE # 72 <)S>
<U005B> <U005B>;IGNORE;IGNORE;IGNORE # 73 [
<U005D> <U005D>;IGNORE;IGNORE;IGNORE # 74 ]
<U007B> <U007B>;IGNORE;IGNORE;IGNORE # 75 {
<U007D> <U007D>;IGNORE;IGNORE;IGNORE # 76 }
<U00A7> <U00A7>;IGNORE;IGNORE;IGNORE # 77 §
<U00B6> <U00B6>;IGNORE;IGNORE;IGNORE # 78 ¶
<U00A9> <U00A9>;IGNORE;IGNORE;IGNORE # 79 ©
<U00AE> <U00AE>;IGNORE;IGNORE;IGNORE # 80 ®
<U2122> <U2122>;IGNORE;IGNORE;IGNORE # 81 <TM>
<U0040> <U0040>;IGNORE;IGNORE;IGNORE # 82 @
<U00A4> <U00A4>;IGNORE;IGNORE;IGNORE # 83 ¤
<U00A2> <U00A2>;IGNORE;IGNORE;IGNORE # 84 ¢
<U0024> <U0024>;IGNORE;IGNORE;IGNORE # 85 $
<U00A3> <U00A3>;IGNORE;IGNORE;IGNORE # 86 £
<U00A5> <U00A5>;IGNORE;IGNORE;IGNORE # 87 ¥
```
if you don't have "reorder-end" in your file, find "END LC_COLLATE" and insert line "reorder-end" before that line.

That is it, you are done. Save the file. Compile, set it as default locale and reboot
```
# compile
sudo localedef -v -c -i en_CA_sort -f UTF-8 en_CA_sort.UTF-8

# to set default locale edit following files if they exist (I am on ubuntu, for other distros you have to figure on your own how to switch default locale)
# ~/.pam_environment
# /etc/default/locale
# /etc/environment
# read https://help.ubuntu.com/community/Locale
```

There is one trick with Java apps.
If an app formats date/time for your locale, it is most probably not using date/time specs from locale file.
Java deducts your Country/Language from locale file name. "en_CA_..." would be resolved to English Canada. After that, Java just uses its own date/time format settings for that language/country.

So, if you want Thunderbird to show dates close to ISO 24H format, call your file "sv_SE_something".
Then in Thunderbird preferences on Advanced tab select "Regional settings locale: Swedish" and reload TB.

**Comment by damian101** [comment]
@blueray453
> For the time being, why can't we just ship the locale file with the next release? And sneak in a option in File Management Preferences somewhere.

That would only solve the problem for the English language. File managers like Dolphin and Deepin File Manager can sort files/directories the "correct" way for all languages while most other Linux file managers just use the "`ls`-sort-order" and apply natural sorting to it.
It shouldn't be extremely difficult to change the way files/directories are sorted in any Nautilus-based file manager as this is already being done by the application of natural sorting.
I'm not an expert though.
Does anyone here know how this "correct" way of sorting is called that is used in Dolphin, Deepin File Manager and the Explorer in Microsoft Windows? They all seem to sort files the same way. Or is it documented anywhere how they exactly sort their files?
By the way, I noticed a while ago that the "`ls`-sort-order" is slightly different on Manjaro than on any other distro I tested (including Arch Linux).

**Comment by stevenxxiu** [comment]
@baikalov Thank you for that solution, I tried it, `_` indeed comes first now, but `.` still does not come first, and I would like it to.

Does `.` come first for you?

**Comment by baikalov** [comment]
Here is how it sorts on my box:
```
~/dev/locale$ cat list.txt
1
a
C
B
2
c
3
A
b
10
9
8
7
6
5
4
_x
0
.dot
 space
<h>
<x>
<i>
<j>
<k>
.
-
_underscore
<q>
-------- dash
~/dev/locale$ LC_COLLATE=en_CA_sort.UTF-8 sort list.txt
 space
_underscore
_x
-
-------- dash
.
.dot
0
1
10
2
3
4
5
6
7
8
9
a
A
b
B
c
C
<h>
<i>
<j>
<k>
<q>
<x>
~/dev/locale$ 
```

**Comment by stevenxxiu** [comment]
@baikalov Ah thanks, mine sorts the same way, but in nemo files starting with `.` still gets sorted after regular files. Do you get that behavior too?

**Comment by baikalov** [comment]
It might be a specific coded behavior. Anything that starts with a dot is a hidden file on Linux.
The common thing is to sort hidden files/folders after non-hidden. 
So, nemo might be overriding locale sorting in this case (I am on Mate, I don't have nemo).
If it has a settings 'sort hidden files after regular', you might play with it. Other wise, there is nothing I can help you with.
Personally, I think Linux community dropped the boll on this. But I guess 80% of them work in console, not using nemo or any other 'windowed bull***'. It is really hard for people who see Win occasionally to emulate the whole OS. I am actually proud how good they did it. 
I truly regret that I can't contribute more time to Linux development (even though I would be one of the worst candidates for that).
I can only hope that nemo team would come up with a solution for this trivial problem.

**Comment by bjd-pfq** [comment]
Most elegant solution to this abomination: https://github.com/heralight/GlibSortFileNameHackLibrary

**Comment by damian101** [comment]
@bjd-pfq That only turns off natural sorting. As far as I understand many people here want a different sort order than the ls sort order, regardless if natural sorting is applied or not.
I personally prefer natural sorting over alphabetical sorting in my file manager.

**Comment by mtwebster** [comment]
I've tried that collate function directly in nemo a few months back, it doesn't appear to be what people want here.

**Comment by bjd-pfq** [comment]
In that case, obtain the sources to g_utf8_collate_key_for_filename.c() from the glib tree, hack those to your liking, and create an LD_PRELOAD object like laid out in my link. That's not hard, I more or less did so myself, before finding this complete github mini-package. (What I was doing was in  the functiong_utf8_collate_key_for_filename.c() just call g_utf8_collate_key() immediately with the same arguments; the cited package here basically does the same; you will have to really change around some of the code in there, which I think is pretty  starightforward.)
Let us know of your results.

**Comment by bjd-pfq** [comment]
The sources of g_utf8_collate_key_for_filename.c() is here:
https://github.com/GNOME/glib/blob/master/glib/gunicollate.c#L483
You can just cut out that function, add <include glib/glib.h> (from memory, but you get the idea) at the top and create a Makefile (use the one from the cited package as example).

Note the straightforward parsing in this function; wouldn't be too hard to get what you want

Nemo should imho definitely add this capability, just add the preload to /etc/ld_preload to make it system wide (you would also want a directory listing of say LibreOffice to reflect the order you want).

**Comment by bjd-pfq** [comment]
Note that when you test this on the cli, you have to give the variable a full path, like:
`LD_PRELOAD=/home/me/libs/lib.so nemo ~`

**Comment by bernd-wechner** [comment]
> Most elegant solution to this abomination: https://github.com/heralight/GlibSortFileNameHackLibrary

I'll have to try this out some time. It blows my mind to this day that these GUI file managers don't implement a "Sort like ls" option out of the box. It would seem totally to be expected that any person accustomed to working with the CLI that uses a desktop gets frustrated when they can't see directories sorted the same way and everything is out of order. 

Not least, and I'll use invoke the devil here, because I moved to Linux DEs  after decades of using Windows and the Windows Explorer always sorted my files the way ls does so I adopted wide sweeping naming conventions to get important stuff sorted up top for example and it all fell apart in Nemo!

**Comment by damian101** [comment]
@bernd-wechner But the Windows Explorer uses natural sorting, not Alphabetical sorting like the ls command does.
The Dolphin file manager can do both alphabetical and natural sorting, but there are some problems with Cinnamon: [https://github.com/linuxmint/cinnamon/issues/8584](https://github.com/linuxmint/cinnamon/issues/8584).

**Comment by bjd-pfq** [comment]
@bernd-wechner The abomination imho is that a library like glib involves itself in hardcoding a non-standard sort order. There's two grave issues there: a) hardcoding b) non-standard.
It should just get the collation from the environment, and maybe get deviations from that from a config in /etc or $HOME. Given that this prob. isn't going to happen, Linux Mint should offer an option to an LD_PRELOAD lib (I said nemo above, but I meant Linux Mint).

**Comment by bernd-wechner** [comment]
> @bernd-wechner But the Windows Explorer uses natural sorting, not Alphabetical sorting like the ls command does.
> The Dolphin file manager can do both alphabetical and natural sorting, but there are some problems with Cinnamon: [linuxmint/cinnamon#8584](https://github.com/linuxmint/cinnamon/issues/8584).

Can't comment at length about Windows internals only my experience with it, mostly many years with XP as the base in which I used case and prepended ! chars to force sorting special names high in lists and that worked for me with Windows Explorer and with ls (as in I had a Linux NAS and a Windows desktop), It wasn't until about 2016 I suspect that I tried a Linux DE (after total failures around 2004 getting one to run on on second hand business PCs I had) and was so blown away with how smooth and easy trying it out was on a Lice USB and that my screens and peripherals all worked fine that I've not looked back ;-).  But my main investment was in using case and ! chars. I do have loads of photos stored with number names representing date/times but haven't had any concern with those, it was sorting of my upper case and ! prefixed entries down into the mix that bugged me most.



> 
> @bernd-wechner The abomination imho is that a library like glib involves itself in hardcoding a non-standard sort order. There's two grave issues there: a) hardcoding b) non-standard.
> It should just get the collation from the environment, and maybe get deviations from that from a config in /etc or $HOME. Given that this prob. isn't going to happen, Linux Mint should offer an option to an LD_PRELOAD lib (I said nemo above, but I meant Linux Mint).

Totally agree! At the very least there should have been from the outset a documented environment variable to force legacy behaviours ... pretty standard design principle surrounding change management ... there's always a demography that doesn't like it.

e.g. When I upgrade to Mint 19, everything looked weird. Me no likey, and rethemed it from Mint-Y back to Mint-X and I'm a happy chappy again. Prudent, well designed support of legacy behavior.

**Comment by damian101** [comment]
@bernd-wechner The Windows Explorer in Windows XP indeed uses Alphabetical sorting, I just checked myself. Since Windows Vista the Windows Explorer uses Natural sorting.

**Comment by bjd-pfq** [comment]
To put some emphasis on my call for Linux Mint to circumvent this glib idiocy, here's a response from glib's developer to a bug report on this sorting issue:

<quote>
Matthias Clasen 2015-09-10 19:44:34 UTC

g_unicode_collate_for_filename does exactly what its documentation says it is supposed to do. I don't think it is a good idea to make low-level library API change behavior in response to random environment variables like this.
<end quote>

"_It does what its documentation says_". Priceless.
Also an indication that we're stuck with it, so circumvention is called for.

**Comment by bjd-pfq** [comment]
@stevenxxiu
But a file listing in let's say LibreOffice still shows the g_utf8_collate_key_for_filename() mess.  We need a solution on the same level (but earlier) as where the mess-up is: glib.

That forces an LD_PRELOAD solution upon you, which will also work for file lists in LibreOffice and anything else that depends on glib for file lists.

**Comment by bernd-wechner** [comment]
> To put some emphasis on my call for Linux Mint to circumvent this glib idiocy, here's a response from glib's developer to a bug report on this sorting issue:
> Matthias Clasen 2015-09-10 19:44:34 UTC
> 
> g_unicode_collate_for_filename does exactly what its documentation says it is supposed to do. I don't think it is a good idea to make low-level library API change behavior in response to random environment variables like this.

Yeah, Is aw that. Not a fan of that attitude. When a pile of people are unhappy with a behaviour the response "well it's the way we wanted it" doesn't cut the mustard so to speak with me. And calling control through an environment variable random is unnecessarily disparaging of a push for flexibility here to simply support legacy behaviours.

**Comment by stevenxxiu** [comment]
@baikalov Sadly the nemo team acted like "it's the way I want it" when I put in my pull request for this trivial issue.

I'm now building my own version of Nemo to use instead to get around this issue (using my own PKGBUILD in Arch Linux).

You can use [my patch](https://github.com/linuxmint/nemo/pull/2260) too if you want, it's quite a small patch.

If you want I can submit this to the AUR.

**Comment by blueray453** [comment]
This seems to be an interesting tool http://manpages.ubuntu.com/manpages/bionic/man1/natsort.1.html

**Comment by blueray453** [comment]
Some of you might find https://github.com/linuxmint/nemo/issues/2247#issuecomment-577118796 interesting

**Comment by stevenxxiu** [comment]
The discussion in the link above discovered that [GlibSortFileNameHackLibrary](https://github.com/heralight/GlibSortFileNameHackLibrary) **does not** solve the hidden files sorting issue, and [my patch](https://github.com/linuxmint/nemo/pull/2260) is still required.
