### ISSUE TITLE
Keep the current selection if the new typed text doesn't match any files 

### ISSUE THREAD

**Issue by he7d3r** [linuxmint/nemo#580]
Suppose I have a folder with the following files
- bar.txt
- baz.txt
- foo.txt

If I type "bar", the file "bar.txt" is selected. However, if I type "ba" and then accidentally type "t" instead of "r", no file is selected. If I typed "z" instead of "t", it would be ok to select "baz.txt", but nemo should not lose the focus from "bar.txt" when I type some character which is not part of the name of any file in the folder. In other words, keep the current selection unless there is a file whose name matches more characters from the string typed by the user.

This is particularly useful if the folder has many files and their names are longer than in the above example.

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
