### ISSUE TITLE
[Gnome Shell] Nemo starts hidden if another windows has "active" focus

### ISSUE THREAD

**Issue by FelixHaller** [linuxmint/nemo#583]
Hi,

I already filed this bug in Gnome Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1086984

There I was told, that this is a bug that wont be fixed, because Nemo is not designed to be used in Gnome Shell. Is that true? I thought nemo should be modular. I love it and would like to use it in Gnome Shell. and it's only that little bug that makes that a little bit annoying.
## Description of problem:

I am using Fedora 20 x64 with all updates and Gnome Shell 3.10.

I installed nemo on my system. After that I have created a startup entry for:

> nemo -n

and when I login, the desktop is filled with icons of my desktop folder. So far so good. Nemo is ready.
But working with nemo is a little bit annoying because sometimes after I clicked on the nemo("files") entry (which I pinned to dock), nemo is started but not focused and so it starts hidden. Fortunately I found a way to reproduce the bug.

Version-Release number of selected component: nemo 2.0.8-9.fc20
## How reproducible:

Everytime. Details see below...
## Steps to Reproduce:
1. pin nemo ("files") to dock
2. log in to Gnome with config provided above (nemo -n in autostart)
3. there will be only the icons of the desktop folder, no Nemo application window! (because -n option)
4. start a terminal (does not matter - we only need any other window)
5. klick on the terminal to be sure it has the focus
6. open activities overview (hit super button)
7. start nemo --> will start in background (behind the second window)
8. close nemo by clicking the cross in title bar (do not click anywhere else)
9. open activities again (super button)
10. start nemo again --> will start in front (with focus)
## Actual results:

If you have clicked a window and make it actively focused, nemo will start hidden(steps 4-6). If you do not explicitely select a window and start nemo (steps 7-9) it will start in foreground.
## Expected results:

I think nemo should always come to front if it's started (step 9).

**Comment by gcb** [comment]
incredible annoying. happens 100% of the time if you have another nemo window anywhere (even on another workspace) and you right click the icon and select `open another window` or if you middle click it.

**Comment by hotice** [comment]
If you use Compiz, here's a workaround for this issue: http://www.webupd8.org/2015/11/fix-for-some-apps-starting-behind.html

**Comment by icarter09** [comment]
@FelixHaller are you still experiencing this issue on the latest version of nemo?
