### ISSUE TITLE
No meta data

### ISSUE THREAD

**Issue by garrett85** [linuxmint/nemo#584]
Please please please make the meta data to media files view-able in Nemo. When I was running Mint 13 I could see the meta data by right clicking and going to properties, now that I'm running Mint 15 the meta data is no longer there so I'm having to use Nautilus, which I don't care for.

**Comment by rockorequin** [comment]
I can't find a way to make nemo-media-columns display audio information for movie files. Bitrate just displays n/a.

Additionally, once the extension is installed, opening folders with lots of files in them becomes chronically slow - even if I don't configure any media columns to display. nemo freezes and becomes unresponsive for minutes at a time. So the extension is unusable for me.

I'm using nemo 2.4.4 btw.

**Comment by RavetcoFX** [comment]
In progress https://github.com/linuxmint/nemo-extensions/pull/129

**Comment by leigh123linux** [comment]
You need to install nemo-audio-tab extension

**Comment by LinuxOnTheDesktop** [comment]
Forgive me if I am being dense, but does the Nemo included in Mint 20.1 have this functionality or else an extension that provides it? I cannot seem to find a way to show bitrate.

I would not ask, but Lollipop - perhaps the most polished Linux media player - does not show bitrate (in any way) and has even (in line with Gnome minimalism?) rebuffed a feature request to add that information anywhere.

**Comment by mtwebster** [comment]
nemo-media-columns? It's not installed by default, as it's a pretty heavy extension.

**Comment by LinuxOnTheDesktop** [comment]
Ah: it is an extension that gets enabled in Nemo once one installs it (the extension) using _apt_.

Yet, _having installed it I see no difference_, even though it shows as present and as enabled in Nemo's 'Plugins' list. I had restarted Nemo (at or at least windowed Nemo). Edit -> Preferences -> list columns: no change. The menu that appears when I right click a header in a list view.

Finally, by calling is a heavy extension, do you mean in disc space usage?

**Comment by LinuxOnTheDesktop** [comment]
Oh, the extra columns have appeared now, in (i) the column chooser that opens via right-clicking and (ii) in the 'List Columns' preferences section. I wonder (1) why those columns took a while to appear?

I wonder also (2) how to make meta-data columns appear in all, and in only, directories that contain media files.

I wonder (3) why getting the 'Properties' of a media file (by right-clicking it) does shows no meta-data.

Sorry to go on; I'm just trying to get some use out of the nemo-media-columns extension.
