### ISSUE TITLE
[Bug] File copy dialog "copying file..." don't match in the title and the window

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo#591]
![nemo-file_copy](https://cloud.githubusercontent.com/assets/2271906/2753762/bff31644-c93e-11e3-8699-4e4517a82513.png)

**Comment by Vahan86** [comment]
@gauravjuvekar, is this issue still relevant to Nemo 3.0.6?

**Comment by gauravjuvekar** [comment]
Yep, still exists.

**Comment by icarter09** [comment]
Verified this is still a bug on Nemo 4.8.2

**Comment by Jeremy7701** [comment]
Since it shows the file count twice, why not change the Window title to
"Copying XX% of 4095 to destination" - it wouldn't be strictly accurate, but it wouldn't be obviously wrong.

The window contents would show the accurate situation.

**Comment by icarter09** [comment]
@Jeremy7701 I like that idea, but it still leaves the issue at hand. I checked the percentage values at it copied over files and it was off as well. I will see what that looks though to have just that in the window title.
