### ISSUE TITLE
Nemo search does not work well

### ISSUE THREAD

**Issue by gunwald** [linuxmint/nemo#594]
The only thing I am really missing in Nemo is a good working file search. And this is the only thing, Nautlius is much better for. Would it be possible to integrate the search mechanism from Nautilus 3.10+ to Nemo? 
I am not talking about merging quick search and search as the crazy Gnome guys did, but about improving the search

**Comment by hrvoojex** [comment]
I use Nemo in Ubuntu because of F3 extra pane, but for searching I use Files. Nemo needs a few minutes to throw results back. Why? Please see my video

https://youtu.be/4psLT1SamO8

**Comment by Vahan86** [comment]
Tested in Nemo 3.0.6. It was necessary about 3 seconds to show 2,262 items (has been searched all files with .jpg extension).

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
