### ISSUE TITLE
Delayed second click on drop-down arrow in tree view changes folder

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#605]
If you click on a drop-down arrow to reveal the subfolders of a folder in the sidebar in tree view and click again after an arbitrary amount of time without moving the mouse in between, Nemo will change to the respective folder. Different behaviour depending on whether the mouse was moved in between feels highly unintuitive to me.

Even if it only happened with actual double clicks, I would not see the purpose, but like this it requires an extra step for some actions and I do not see any use case at all.

This does not happen in list view.

EDIT: Ubuntu 14.04, Nautilus 2.2.1

EDIT: This does not happen if the respective folder has no subfolders or is collapsed before loading all subfolders it contains.

**Comment by icarter09** [comment]
@HifeFish are you still experiencing this issue on the latest version of nemo?

**Comment by HifeFish** [comment]
@icarter09 I am no longer seeing this issue in version 3.6.5.
