### ISSUE TITLE
Desktop icon text looks ugly with Adwaita theme since Nemo 2.2.1

### ISSUE THREAD

**Issue by City-busz** [linuxmint/nemo#608]
After the following the commit 8a55bd4 , the text of the desktop icons looks ugly and hard to read with Adwaita theme, because nautilus-desktop class styles are no longer applied to Nemo.
![adwaita-theme](https://cloud.githubusercontent.com/assets/530525/2932173/905b6f72-d7ac-11e3-9ca6-34e3ac7523b2.png)

**Comment by City-busz** [comment]
Fixed by https://github.com/linuxmint/nemo/commit/e59cae7bd231bac01806458b377cd8c388503751

**Comment by monkbroc** [comment]
You're persistent @City-busz. You've waited a whole year for this!
