### ISSUE TITLE
 Nemo doesn't seem to use xdg-user-dirs in Lubuntu 14.04

### ISSUE THREAD

**Issue by scott092707** [linuxmint/nemo#610]
Hi.

I have been using Nemo successfully in Lubuntu in 13.10, and my defined xdg-user-dirs appear in the sidebar just fine.

Now, I have installed Lubuntu 14.04, and Nemo doesn't show any of my defined directories
[EDIT: except Desktop, for some reason...]

Enough of my other apps show my defined directories that I can be confident that Lubuntu is running the program that looks up my xdg-user-dirs.

Something must have changed in Nemo, that it no longer uses (or at least displays) my defined dirs.

Before, it was one click in the side-bar for my documents, or music or ...

Now, since I have my personal data in a separate partition, I must:
Click on FileSystem, double-click on data, double-click on Scott, and finally double-click on Documents (or Music or...).
If I have finished doing something with a document, and want to look at my music, I have to go through the whole rigmarole again.

Am I missing something - some option I need to set, perhaps - or is this a bug?

---

scott@scott-AsusM2N68-AM-Plus:~$ uname -a
Linux scott-AsusM2N68-AM-Plus 3.13.0-24-generic-tuxonice #46~ppa1-Ubuntu SMP Sun Apr 13 22:09:41 UTC 2014 i686 athlon i686 GNU/Linux

scott@scott-AsusM2N68-AM-Plus:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04 LTS
Release: 14.04
Codename: trusty
[Actually is Lubuntu]

scott@scott-AsusM2N68-AM-Plus:~$ nemo --version
nemo 1.8.4

I am not sure which version of Nemo I was using in Lubuntu 13.10.
[Other than the fact that I was up to date on any/all software-updates.]
If someone feels that it is vital that I provide that info, I can boot from that version and find out.

-Scott
![screenshot from 2014-05-10 14 32 37](https://cloud.githubusercontent.com/assets/7544310/2936777/ae56bc8c-d871-11e3-983d-497e7cfe56f2.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue since there is no response from OP for over 2 years?

**Comment by scott092707** [comment]
I somehow missed any comments to this bug until today...  Too bad I did not have my computer on yesterday, or I would have responded.

If this is "closed", then I will need to open a new one...

**Comment by icarter09** [comment]
@scott092707 are you still experiencing this issue on the latest version of nemo?
