### ISSUE TITLE
Cycle through sidebar and main window with the keyboard

### ISSUE THREAD

**Issue by demetriodn** [linuxmint/nemo#612]
It would be better if you could cycle through the sidebar and mainwindow with the TAB key from the keyboard, as in Nautilus. It seems that TAB does nothing by default.

**Comment by eiriklade** [comment]
+1

**Comment by jerkey** [comment]
+1

**Comment by Dukuu-Wild** [comment]
More than one year of these issues? This should be done anyway. It's very inconvenient to use double-pane nemo otherwise.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Closing in favor of https://github.com/linuxmint/nemo/issues/816 since it's a bit more general and about improving keyboard navigation overall.

**Comment by vstepaniuk** [comment]
+1
