### ISSUE TITLE
Adding support for "Copy" (Dropbox Alternative)

### ISSUE THREAD

**Issue by Danko8321** [linuxmint/nemo#615]
Hello. I've been thinking it would be great to make Nemo compatible with some file-syncing apps. As of now, I'm in love with Copy, but it doesn't work with Nemo (no possibility to show the status of sync, no menu-options) and I was wondering if that could be done by you guys or maybe the guys at copy had to. If the case is the second one, please disregard my request. I'm just thrilled about this kinds of things and I think nemo (and Cinnamon, in general) could benefit greatly by integrating Copy into it's list of supported file-syncing apps.

I hope you find time to consider my request. Cheers.

Danko.

PS: I'm so rusty at using GitHub that I don't even know if this is the way to ask for a feature; if I'm posting this in the wrong place, please do accept my dearest apologies and put it where it belongs. I thank you in advance.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
