### ISSUE TITLE
Tree/list view - empty folders - redux

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#616]
I am not quite happy with the way https://github.com/linuxmint/nemo/issues/344 was resolved. As of now, a folder in tree or list will not have an expand button if and only if it does not contain any currently visible folders or files.
I have two issues with that behaviour:
1. In list view, I used the option to expand an empty folder frequently, to copy/cut and paste files into a (newly created) empty folder without having to change folders; mostly when navigating by keyboard, thus not wanting to rely on drag & drop.
2. On the other hand, the issue in the tree is still the same for any folder without subfolders containing at least one file, still ending up with showing "(empty)" with no actual use, in contrast with the removed expandability in list view. At least as long as you do not choose to display files in the tree.

In my opinion, the ideal behaviour should be as follows:
1. In list view, always show expand-buttons.
2. In tree view hide expand-buttons if and only if there is nothing to be expanded, i.e. if there are no folders in the default setting or if there are no files or folders when files are displayed in tree.

The discriminative behaviour might be harder to implement, but in my opinion the current situation is worse than before.

<s>EDIT: One more issue with the current behaviour, that would also carry over to my suggestion: The expand-button remains hidden after dragging files or folders into an empty folder, unless you refresh, which is easy enough in list view by pressing F5, but can be a hassle in the tree, because you have to collapse and expand the parent folder to do so.
EDIT2: This goes as far as when creating a subfolder of an empty folder and subsequently opening it, the tree still only shows the initial folder without an expand button.</s>
Covered in https://github.com/linuxmint/nemo/issues/486 and https://github.com/linuxmint/nemo/issues/508 (original issue still stands).

**Comment by icarter09** [comment]
@HifeFish is this still an issue?

**Comment by HifeFish** [comment]
The issue still stands in Nemo 3.6.5.

**Comment by leigh123linux** [comment]
3.6.5 is EOL, feel free to reopen if you can reproduce with nemo-4.4.x
