### ISSUE TITLE
[Feature Request] Scrolling during drag & drop

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#617]
Currently, if the left mouse button is pressed, the mouse wheel does nothing. It would be nice to be able to scroll through the tree or list during drag & drop operations.

(Dragging to an edge of the window is quite inaccurate and often causes strange effects, such as expanding a bunch of folders along the way.)

**Comment by Vahan86** [comment]
@JosephMcc, Issue https://github.com/linuxmint/nemo/issues/356
