### ISSUE TITLE
Small debian packaging fixes

### ISSUE THREAD

**Issue by darealshinji** [linuxmint/nemo#618]
https://gist.github.com/darealshinji/e7ea0cd225bc823151ae
This adds a pixmap icon, which is referred in debian/menu but not installed, and it does some fixes in debian/control.

There's still two things left:
W: libnemo-extension1a: package-name-doesnt-match-sonames libnemo-extension1

W: nemo: desktop-entry-contains-unknown-key usr/share/applications/nemo-autostart.desktop:7 AutostartCondition
In a forum I found this information:
"I think you need to do something with the AutostartCondition variable in one of the .desktop files.
I don't know exactly what but they did something to prevent nemo from handling the desktop in a Gnome session because nemo was getting in the way of nautilus."
If this entry is really needed, you should override the tag.

**Comment by leigh123linux** [comment]
link is dead
