### ISSUE TITLE
"Run in Terminal" doesn't use org.cinnamon.desktop.default-applications.terminal exec

### ISSUE THREAD

**Issue by xhsdf** [linuxmint/nemo#620]
When I set "org.cinnamon.desktop.default-applications.terminal exec" to terminator "Open in Terminal" calls terminator as it should. But "Run in Terminal" always calls gnome-terminal.

nemo 2.2.1 on Archlinux

**Comment by xenopeek** [comment]
This also affects Linux Mint 18. Terminal configured to Terminator in Cinnamon Settings > Preferred Applications makes "Open in Terminal" use Terminator but "Run in Terminal" uses gnome-terminal.
