### ISSUE TITLE
Undo in name-edit mode undoes last file operation instead of last edit

### ISSUE THREAD

**Issue by autarkper** [linuxmint/nemo#621]
If you are editing the name of a file or a directory and press Ctrl-Z to undo an edit, the edit is not undone -  instead the last file operation is undone.

How to reproduce:
1) Create a scratch directory.
2) In the scratch directory, create two empty directories, named "dir1" and "dir2", in that order.
3) Start changing the name of "dir1" by pressing F2, and typing a few characters.
4) Press Ctrl-Z to undo the name edit.

Expected result: The name change is undone.
Actual result: The name change is not undone.

5) Press Escape to exit the name-edit mode.

Expected result: Everything should be unchanged.
Actual result: The name of "dir2" has unexpectedly been changed to "Untitled Folder".

(2.2.2-20140529010005-trusty).

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by ManuelSchneid3r** [comment]
This is not a feature, but a bug.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
