### ISSUE TITLE
Searching in Sub folders after quick find in current directory.

### ISSUE THREAD

**Issue by Siecje** [linuxmint/nemo#622]
To search in the current folder I can simple type. But then to search inside all sub folders I press ctrl+f and I have to re-type the search query.

It would be nice if when I pressed ctrl+f that the previously typed query would go into the search field.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
