### ISSUE TITLE
[BUG] Mint 17: Nemo: When trying to browse Windows Network, Nemo crashes 100% of time

### ISSUE THREAD

**Issue by gaetawoo** [linuxmint/nemo#624]
I have experienced this behavior on two separate computers and while running the Live CD. I open Nemo, click on Networks in the left menu. Then I double click on Windows Network to browse it and Nemo completely crashes, taking all the desktop icons along with it. When I open Nemo again, the desktop icons come back and the same behavior of crashing when trying to open the Windows Network occurs. I can successfully access Windows network shares by going directly to the address in Nemo (smb://192.168.1.10/Share).

There are others who experience this. Others have tried Dolphin or another file explorer and they don't have the problem. Something is wrong with Nemo. On Mint 15, I did not have this issue.

**Comment by mcatkins** [comment]
I'm now getting regular, frequent crashes of nemo, and nemo-dbg (2.2.4+qiana) on 64-bit Mint 17

Here is the gdb thread information:
...
(gdb) thread apply all bt

Thread 96 (Thread 0x7fffcdec0700 (LWP 31564)):
#0  0x00007ffff45997ce in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50afce5 in g_cond_wait_until ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff50441c1 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff504474b in g_async_queue_timeout_pop ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff5093956 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff5092f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff4595182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff42c200d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7fffed47d700 (LWP 31244)):
#0  0x00007ffff42b4cbd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff506dfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff506e0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff506e129 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff5092f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff4595182 in start_thread ()
---Type <return> to continue, or q <return> to quit---
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff42c200d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffe7fff700 (LWP 31243)):
#0  0x00007ffff42b4cbd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff506dfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff506e0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffec2761ad in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff5092f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff4595182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff42c200d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffedc7e700 (LWP 31240)):
#0  0x00007ffff42b4cbd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff506dfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff506e30a in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5655336 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff5092f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff4595182 in start_thread ()
---Type <return> to continue, or q <return> to quit---
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff42c200d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7fbc9c0 (LWP 31236)):
#0  0x00007ffff5089297 in g_slice_alloc ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff5069dd6 in g_list_prepend ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x000000000050ae0a in nemo_module_get_extensions_for_type (type=9155616)
    at nemo-module.c:266
#3  0x00000000004e9766 in nemo_file_invalidate_extension_info_internal (
    file=file@entry=0x13a14d0) at nemo-file.c:7581
#4  0x00000000004ce73b in nemo_directory_notify_files_changed (
    files=<optimised out>) at nemo-directory.c:1043
#5  0x00000000004d1b36 in nemo_file_changes_consume_changes (
    consume_all=consume_all@entry=1) at nemo-file-changes-queue.c:333
#6  0x000000000050b0be in call_consume_changes_idle_cb (
    not_used=<optimised out>) at nemo-monitor.c:69
#7  0x00007ffff506dce5 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff506e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff506e0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff5620b9c in g_application_run ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x000000000042bdf9 in main (argc=1, argv=0x7fffffffdf48) at nemo-main.c:101
(gdb)

**Comment by hadim** [comment]
I confirm the bug. Note that I can't install nemo-gdb since:

```
$ sudo apt-get install nemo-dbg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nemo-dbg : Depends: nemo (= 2.2.4+qiana) but 2.4.0+rebecca is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by DomingoMontoya** [comment]
I have a feeling this is related to what I just noticed gvfs samba fuse is doing. It seems that accessing shared folders that have a file or two that can't be read cause issues.

I can access the shares on my Windows machine for many folders just fine, but accessing C, Users, A user folder, cause either errors, no contents to show up, or some of the folders within to show up. Hitting refresh may cause different folders to be viewable, but never all of them.

**Comment by Vahan86** [comment]
@gaetawoo, is this still an issue for you with Nemo 3.2?

**Comment by gaetawoo** [comment]
@Vahan86 I haven't used Nemo 3.2 yet. Sorry. It was fixed for me on Aug. 2014 but i don't know if it's still an issue.
