### ISSUE TITLE
[Feature Request]add Chinese translation in new-launcher.nemo_action

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/nemo#628]
There plenty of elements in Mint17 not translated into Chinese, I hope I can help with this
one of them is new-launcher.nemo_action, you can add following lines:
Name[zh_CN]=添加新的启动器
Name[zh_HK]=添加新的啓動器
Comment[zh_CN]=在本文件夹中添加启动器
Comment[zh_HK]=在本文件夾中添加啓動器
as Chinese translation for zh_CN, zh_HK
not very familiar with zh_TW, but I think it should probably show as same as in zh_HK

**Comment by NikoKrause** [comment]
Is this still an issue in LM18.2?

**Comment by NikoKrause** [comment]
Since there is no response, I'll close this issue.
