### ISSUE TITLE
Nemo crash with broken symlinks

### ISSUE THREAD

**Issue by mickyz** [linuxmint/nemo#638]
I noticed random crashes in the last 2.2.2 when I try to open folders that contains broken symlinks which points to a image file. Please fix also the updating of thumbnails that remains outdated when the origin image has been changed, many times press F5 is not enough. Thanks.

**Comment by Vahan86** [comment]
@mickyz, does this issue still occur in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
