### ISSUE TITLE
files preview and file lock

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/nemo#639]
would it be possible to add a feature to
1.  lock files/folder
2. preview file on folder ??

![example-thumbnails-300x122](https://cloud.githubusercontent.com/assets/7669448/3318323/a4bf9cb2-f715-11e3-8210-822ce7e426cf.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by leigh123linux** [comment]
I would prefer to this to be a nemo-extension so it's easy to disable.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
