### ISSUE TITLE
New tab opens at max zoom out level

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo#640]
Nemo 2.0.8 on LMDE 64-bit

A new tab opened is completely zoomed out in list view. Other views are not affected. Ideally, it should preserve the zoom settings of the last active tab.

**Comment by Vahan86** [comment]
@gauravjuvekar, is this still an issue for you in Nemo 3.0.6?

**Comment by gauravjuvekar** [comment]
Resolved in 3.0.6 in Mint 18. Cannot confirm in LMDE. Closing
