### ISSUE TITLE
Icon view background changes when opening a new tab

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/nemo#641]
Nemo 2.0.8 on LMDE 64-bit

Open icon view
Create a new tab
Switch to the old tab
Background of old tabs changes
![a](https://cloud.githubusercontent.com/assets/2271906/3340846/4c4a2b74-f882-11e3-9d2d-3bc6264b8b82.gif)

**Comment by Vahan86** [comment]
Can't reproduce this issue in Nemo 3.0.6.
@gauravjuvekar, is this still an issue for you with Nemo 3.0.6?

**Comment by gauravjuvekar** [comment]
Resolved in 3.0.6 Mint 18. Cannot confirm in LMDE.
