### ISSUE TITLE
rename: echo fails after 2nd release of shift/ctrl/etc. char-alt key

### ISSUE THREAD

**Issue by scott092707** [linuxmint/nemo#645]
I filed a bug for my distro (well, for Ubuntu - I have Lubuntu...), but as no one has commented, I do not know if anyone has read it or not.

It was a bit rambling - I thought I knew what was going on, but as I tested and reported what I found, I refined what I now believe the problem is.

Normally, as one types characters into a rename text field, they echo and one sees them.
However, after the second time that Shift or Ctrl is released (one types a capital letter, one copies chars from or pastes chars into the field, etc.) the echoing stops.  One can continue typing, and when one finally presses Enter, one finds that Nemo was reading each of the keypresses, but if one has to correct a mistake and presses backspace, it is quite difficult correcting, as one is flying blind, so to speak.

The bug I filed at Launchpad for my distro is at: "https://bugs.launchpad.net/ubuntu/+source/nemo/+bug/1330122"
I don't know if it is a problem only for my distro's pkg. of Nemo, or for Nemo generally.

If someone would please verify the problem, and report back, I would appreciate it.
At least, please indicate that this is being read.

Thank you.

**Comment by fcastilloec** [comment]
I'm not sure if this is related to this bug, but when I'm renaming and press the Shift + "any key", nemo exits the renaming. There's nothing I can do, and no way on renaming the file except command line.

**Comment by icarter09** [comment]
@scott092707 are you still experiencing this issue on the latest version of nemo?
