### ISSUE TITLE
File rename not allowing text to be edited

### ISSUE THREAD

**Issue by hvva** [linuxmint/nemo#656]
- Default install of Linux Mint 17 64bit (Cinnamon 2.2.13) - had a similar issue with Mint 16.
- Nemo v2.2.2

**Issue**
When selecting "Rename..." from the file's context menu or edit menu, the file name text box looks editable, but the file name cannot be changed. Arrow keys also do not move a cursor in the text box.
- _Sometimes_ rename works the first time, but subsequent renames are likely not to work
- The file can be renamed from the command line
- Clicking off of the file removes the editable text box as expected
- In the attached screenshot, the file/folder had permissions changed to 777. Neither user or full permissions would allow the file name to be changed.
- In this test Nemo settings have not be altered from the default installation
- Same issue when creating a new folder using the "Create New Folder" icon in the top right of the window -- "Untitled Folder" text cannot be modified.

![rename](https://cloud.githubusercontent.com/assets/7194962/3485804/11cabd84-0402-11e4-807d-694a6b315ae2.jpg)

**Comment by bcousson** [comment]
I've been facing that issue since that time, and still facing it today with mint 17.3. I'm running nemo 2.8.6. I'm just doing upgrade now, so there is something that might not have been updated properly I guess. How the issue was fixed?
