### ISSUE TITLE
Smart replace options for file conflicts

### ISSUE THREAD

**Issue by Enkouyami** [linuxmint/nemo#659]
When there is a file conflict, have an option to use the file of the largest size and if they are the same size, skip it. Call it smart replace.

There could also be more options for users to customize how smart replace works. For example: use the file that has the most recent modification date and if that's the same, use the file of the largest size.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
I don't really get the point of this. A dialog pops up asking you which one you want to use.

**Comment by Enkouyami** [comment]
The point of this is so users won't have to click through hundreds of dialog pop-ups if there are hundreds of files with the same name.

**Comment by JosephMcc** [comment]
Not looking at it right now but I'm pretty sure there is an option to "Replace all".

**Comment by Enkouyami** [comment]
@JosephMcc if you've read my original post (especially the examples) and my 1st post, you would notice what I'm suggesting is different than the current implementation of "replace all."

**Comment by JosephMcc** [comment]
I understand. I'm just not sure I personally want something that's automatic. There will always be edge cases where it will give the wrong end result. Not something you want when dealing with peoples files. On top of that it doesn't seem like it provides some big improvement to workflow.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
