### ISSUE TITLE
[Feature Request] Spreadsheet style auto-filters for columns in list view

### ISSUE THREAD

**Issue by msmialow** [linuxmint/nemo#662]
It would be very cool to have auto filters similar to ones that you would use in a spreadsheet application for the list view columns.

As an example use case, I'm going through an old drive from a work machine and doing file cleansing.  One directory that I'm looking at has hundreds of csv files which I know I don't need.  From the context of the folder name, I know that if it only has csv files then I can purge the entire directory.

If the list view column had a filter, I could quickly click it and see a list of unique mime types.

To expand the use case, date modified would be interesting as well especially if you could set ranges.

Obviously using multiple column filters could prove quite useful to quickly find the files that you are looking for.  I could filter name contains 'data', last modified date between x and y, type = csv, etc.

It works extremely well for spreadsheets, why not file lists?  The benefit of searching for files this way rather than just sorting by a column or searching by a name is the immediate filter feedback to the user and the step by step funnel approach.

Not sure if this has been suggested before (different than #507 imo) or if any competing applications implement this, but the thought occurred to me as I was using nemo so decided to share the idea.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
