### ISSUE TITLE
sftp/smb root folder stops working after some time

### ISSUE THREAD

**Issue by artscoop** [linuxmint/nemo#663]
I am always able to reproduce this bug, but not on purpose.
After some time, remote _root_ folders (and only root folders) are not seen as folders anymore. This has happened with SMB shares and SFTP folders.
The error that pops is "Cannot display "sftp://root@virtual/". The location is not a directory." (but in french)

**Comment by vveliev** [comment]
+1. It's just stop working after time my system was up for 8 days and this happens 
nemo 2.4.5

**Comment by o1da** [comment]
Just after the update of linux mint to 17.1 it disappeared for me.

**Comment by Vahan86** [comment]
@artscoop, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by artscoop** [comment]
Still have part of the bug in 3.2.8: if I unmount a FTP mount, I have the same error if I try to mount it again. (SFTP is ok)

**Comment by mfreeman72** [comment]
I am also having this problem in Nemo 4.2.3. If I open an ftp location in Nemo, it connects and displays the first time. If I unmount, and then try to connect to the same ftp site again, it says, "Could not display {ftp address}. The location is not a folder." I've also seen this on occasion with smb connections as well. @JosephMcc : Can this issue be re-opened? Or do I have to make a new issue thread? This is still a problem.

**Comment by mbluett88** [comment]
I am using Nemo 4.4.2. It very periodically gives an error of "The location is not a folder" when in actual fact it is a folder that I have mounted many times in the past. This is when using SMB.
Another interesting thing is that right-clicking on that folder and clicking on Properties shows Type, Size, Volume, Accessed, Modified, Created are all set to "unknown". Locations shows correctly.
It also says Permissions could not be determined.

**Comment by mikenest** [comment]
I can confirm that SFTP issue is still here, nemo 4.4.2. After unmounting bookmarked SFTP I am unable to reconnect to it via bookmarks, only manually, specifying different directory. For example, if I had sftp://192.168.0.11/ bookmarked, mounted and unmounted I will only be able to connect to this address if I specify sftp://192.168.0.11/home/ or any other non-root directory in address. Btw, syslog shows nothing when this is happening. Issue is quite annoying cause I have to exec nemo -q every time.

**Comment by Joe1962** [comment]
Nemo 5.4.2 on freshly installed Mint 21 + updates till today, still same problem with ftp and smb links, but never ssh. This seems to be a very long-term issue indeed...
