### ISSUE TITLE
Nemo can't handle network locations as root

### ISSUE THREAD

**Issue by Obsidian-Jackal** [linuxmint/nemo#665]
When nemo is opened as root, trying to access any network location results in an error saying "Could not display "network:///". Nemo cannot handle "network" locations."

**Comment by MaDDmin** [comment]
More than 2 years and this is still an open issue??? My jaw just dropped.

**Comment by ACinnamonUserInUK** [comment]
+1.

**Comment by mattes42** [comment]
+1

**Comment by CottonEaster** [comment]
@leigh123linux : you may well have a point. If you do, why not make the feature look less like an ad hoc limitation than it does? That is: why not replace the 'cannot handle' message with something like, 'As a matter of security, root Nemo . .'?

Better (or as an addition): why not, in noot nemo, indicate in advance to the user that the inaccessible locations are inaccessible - by greying out network locations in the side bar, and suchlike?

If people suspect that what they want to do is foreclosed for a good reason, then that limitation is less likely to prompt them to complain or to confuse them.

**Comment by CottonEaster** [comment]
Thanks, Leigh, but, for my part, it's mainly the user experience that's at issue. That is: it seems to me that the you-can-press-it-but-it-will-do-nothing situation is unsatisfactory and should be resolved in one direction or the other.
