### ISSUE TITLE
Nemo cannot handle "computer" locations as root

### ISSUE THREAD

**Issue by Enkouyami** [linuxmint/nemo#666]
When nemo is opened as root, the "Go to Computer" icon is still on the main toolbar and using it or going to "computer:///" an error saying "Could not display "computer:". Nemo cannot handle "computer" locations."

**Comment by Vahan86** [comment]
I can reproduce this issue in Nemo 3.0.6 as well.

![3](https://cloud.githubusercontent.com/assets/12819058/20647018/dbd5727a-b4a1-11e6-82b4-9bec5c737946.png)

**Comment by leigh123linux** [comment]
Looks like root ignores xdg

```
[leigh@localhost ~]$ xdg-mime query default  x-scheme-handler/computer
nemo.desktop

[root@localhost Pictures]# xdg-mime query default  x-scheme-handler/computer
[root@localhost Pictures]#
```

**Comment by ACinnamonUserInUK** [comment]
I have experienced this problem too.
