### ISSUE TITLE
Desktop window lacks a role for targeting via window management software

### ISSUE THREAD

**Issue by dietrich-stein** [linuxmint/nemo#667]
Perhaps this is more appropriate as a feature request to my favored window management software, but I decided to report it here as a resource for others and in case my suggested solution is appropriate. I discovered this issue because I intended to cause devilspie to match non-desktop instances of the nemo window in order to force them to a specific workspace. Running xprop on the desktop window reveals:

```
WM_CLASS(STRING) = "desktop_window", "Nemo"
```

In the source for _nemo-desktop-window.c_, this is due to:

```
gtk_window_set_wmclass (GTK_WINDOW (window), "desktop_window", "Nemo");
```

The devilspie software is able to match upon WM_NAME, but it is unable match on the window class name as shown in the above code. Therefore it cannot differentiate between desktop and non-desktop nemo windows.

My suggestion to solve this for devilspie and other window management software is to make use of `gtk_window_set_role()` to set a desktop role for this window.

**Comment by icarter09** [comment]
@dietrich-stein is this a feature request?

**Comment by smurphos** [comment]
@icarter09 - this isn't relevant anymore as nemo-desktop now manages the desktop and it's trivial to distinguish it from a regular nemo window in scripts.
