### ISSUE TITLE
Nemo: No horizontal scrollbar in list-view with multiple columns displayed

### ISSUE THREAD

**Issue by TKOF** [linuxmint/nemo#673]
Nemo 2.2.3 (Updated by PPA), Ubuntu 14.04, GNOME Shell 3.10.4

Nemo does not seem able to display a horizontal scrollbar (in list view).
In list-view, with multiple columns displayed.

The action to resize a column, "reduces others  column"  Instead of "creating a horizontal scroll bar".
Also it does not seem to be a minimum size column, which can make viewing difficult.

Other problem: last column is difficult to rezise without this scroll bar.

This question have probably a link with:
https://github.com/linuxmint/nemo/issues/384 (disable auto-width columns in list view)
https://github.com/linuxmint/nemo/issues/626 (list view column width not remembered)

**Comment by bitonda** [comment]
It would be VERY useful ! many sw have h-scroll works in that way ...

**Comment by Vahan86** [comment]
@TKOF, is this still an issue for you in Nemo 3.0.6?

**Comment by JosephMcc** [comment]
As stated in https://github.com/linuxmint/nemo/issues/626 the list view columns now work the way they are going to work. At least in Nemo 3.2 a scrollbar becomes available when the window size become too small to display everything.
