### ISSUE TITLE
Dbus-launch issue

### ISSUE THREAD

**Issue by mboufleur** [linuxmint/nemo#674]
Hi everyone.

I normally have to use nemo with root privileges, so there is always a launcher at the desktop, with a copy from the desktop file "Files" from /usr/share/applications, with modified exec command to:

gksudo dbus-launch nemo %U

Usually it works without any issues, but with Mint version 17 64-bits, the command prompts for root password and after I enter the psw, nothing happens.

That happens with either gksu or gksudo.

If I just leave it as "gksudo nemo %U", the command works without any issues but I am no longer able to navigate into Trash or Network folders.

**Comment by xenopeek** [comment]
On current versions of Linux Mint, Nemo uses pkexec. So the command would be "pkexec nemo %U".
