### ISSUE TITLE
Open in remote terminal

### ISSUE THREAD

**Issue by heidi666** [linuxmint/nemo#675]
I switched from Nautilus because quite frankly it sucked. However, it did have one feature that I used very often, and cannot understand why it is not implemented by default: 'open in remote terminal'.

I've noticed this issue has existed [for a very long time](https://github.com/linuxmint/nemo/issues/23).

I've googled around and solutions mentioned [here](https://bugs.launchpad.net/linuxmint/+bug/1119283) are a) unsatisfactory, and b) fail to work for me.

**Comment by billymail** [comment]
+1

**Comment by xenopeek** [comment]
As noted this is a duplicate and should probably be closed.

**Comment by billymail** [comment]
Add link to the report that this is a dup of.

**Comment by JosephMcc** [comment]
Read the posts, it is there.
https://github.com/linuxmint/nemo/issues/23

**Comment by billymail** [comment]
Ctrl-F #23. Not there. Thanks tho.
