### ISSUE TITLE
Nemo opens in the background.

### ISSUE THREAD

**Issue by Semmu** [linuxmint/nemo#676]
Every time I open Nemo under Ubuntu 14.04, the window opens behind the  other ones, so it does not get the focus. How could I fix it?

**Comment by Vahan86** [comment]
@Semmu, is this issue still relevant to Nemo 3.0.6?

**Comment by Semmu** [comment]
I don't know exactly. The compiz workaround does indeed work, so it fixes the problem, but I don't know if Nemo itself could be improved to always open in the foreground (setting a property for the newly opened window or something like that)
But compiz is known to be buggy as hell, so this could be just another example of that.

**Comment by xenopeek** [comment]
If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
