### ISSUE TITLE
Nemo can't save bookmarks in windows with root privileges anymore

### ISSUE THREAD

**Issue by andrk** [linuxmint/nemo#680]
Linux Mint 17, 64 Bit, Cinnamon Edition
Cinnamon --version: 2.2.16
Nemo --version: 2.2.4
1. Open a new Nemo FileManager Window
2. Right clock and "Open as root" (i don't know the exact wording)
3. Put some bookmarks at the left side
4. Close Nemo FileManager Window
5. Open it again, all bookmarks are gone

Problem happened always.

**Comment by Vahan86** [comment]
I can't reproduce this issue in Nemo 3.0.6. It works fine for me.
@andrk, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
