### ISSUE TITLE
Connect to Server with ssh and TCPKeepAlive

### ISSUE THREAD

**Issue by graslandschaft** [linuxmint/nemo#682]
SSH connections with servers behind stateful firewalls will be dropped after a certain time of inactivity. I assume this behavior could be avoided by adding the possibility to usethe " TCPKeepAlive" option and maybe adjust the "ServerAliveInterval" parameter. Could this be implemented?

**Comment by Vahan86** [comment]
@graslandschaft, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
