### ISSUE TITLE
Nemo's Mount Archive And Check MD5 Actions Have Missing Translations

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/nemo#684]
Mount Archive and Check MD5 actions of Nemo have missing translations.

mint-md5sum.nemo_action
mount-archive.nemo_action

**Comment by Vahan86** [comment]
@kelebek333, is this still an issue for you with Nemo 3.0.6?

**Comment by kelebek333** [comment]
mint-md5sum.nemo_action change to mint-sha256sum.nemo_action
mount-archive.nemo_action available with nemo 3.2

**Comment by kelebek333** [comment]
Yes, this translations still missing.

mint-sha256sum.nemo_action
mount-archive.nemo_action

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by leigh123linux** [comment]
Translation issue belong 

https://github.com/linuxmint/cinnamon-translations/issues
