### ISSUE TITLE
Cannot unmount user-space devices

### ISSUE THREAD

**Issue by jhihn** [linuxmint/nemo#687]
Using sshfs, I can mount a remote FS. Nemo shows the mounted FS under "Devices" (ok so far). However I cannot unmount it from nemo. It complains that it's not in the 'fstab'.
the fs can be unmounted with : fusermount -u fs
What I would suggest is
`if (in fstab)
 umount-command
else
fusermount -u fs`

**Comment by Vahan86** [comment]
@jhihn, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by jhihn** [comment]
I'm sorry, I missed this, I will check tonight.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by jhihn** [comment]
I am sorry for missing the previous emails. I will try tonight and reply with the outcome.

**Comment by jhihn** [comment]
Ok, so it still doesn't quote work with 3.0.6.

When I mount the partition: sshfs -o IdentityFile=/home/jason/.ssh/id_rsa  ec2-user@domain.com: ~/remote_mount

It shows up.

But now when I attempt to umount it via the eject button, I get 
umount :/home/jason/remote_mount: Permission denied.

The proper command for this is actually:
 fusermount -u ~/remote_mount

**Comment by Vahan86** [comment]
@JosephMcc, can we remove "Close If No Response" label and mark this issue as a bug?

**Comment by icarter09** [comment]
@jhihn are you still experiencing this issue on the latest version of nemo?

**Comment by jhihn** [comment]
In the 5+ years since I filed this, and the 3 years my last response (3 years exactly),  I've since switched to MacOS, and I no longer have that environment to test with. However, I do still have that computer, and I will get up up to date and give it a shot.  It might take a day or two to get to it, but I will do it for the good of the project!
