### ISSUE TITLE
Nemo actions pass all files as a single argument

### ISSUE THREAD

**Issue by FM33** [linuxmint/nemo#693]
Hello,
This is a nemo-action specific issue. No problem using nemo scripts folder.
This makes scripts to fail with multiple selection + filenames containing spaces.

Test script :
# !/bin/sh

if [ -e /tmp/tbn.txt ]; then rm /tmp/tbn.txt;fi
for file in "$@"; do
    echo $file >> /tmp/tbn.txt
done
gedit /tmp/tbn.txt &

Test action :
[Nemo Action]
Active=true
Name=Test
Exec=/home/fabien/TMP/testbugnemo "%F"
Selection=NotNone
Extensions=any

Output with action :
/home/fabien/TMP/file 1 /home/fabien/TMP/file 2

Output with script submenu :
file 1
file 2

Output with action, without quotes around %F :
/home/fabien/TMP/file
1
/home/fabien/TMP/file
2

**Comment by vks** [comment]
I think not escaping filenames is a horrible default. It is very confusing, people will be running into this idiosyncrasy repeatedly, as this issue and issue #398 demonstrate.

More importantly, this behavior is *always* incorrect for multiple filenames containing spaces. Not escaping only works if there is only one filename or if there are no spaces.

Why not pick a more conservative default that is correct?
