### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [linuxmint/nemo#695]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/linuxmint/nemo/blob/f5bb277634be37768e281bd00e3a48976714471e/configure.in#L49)?

**Comment by leigh123linux** [comment]
nemo no longer use autotools, it has switched to meson.
