### ISSUE TITLE
Don't go backwards if "Host closed connection"

### ISSUE THREAD

**Issue by donquixote** [linuxmint/nemo#697]
Sometimes a remote connection (ftp, sft, whatever) breaks down.
Or a drive is no longer mounted. (didn't check that one)

In this case, Nemo shows a warning dialog (e.g. "host closed connection") and goes backwards. Sometimes multiple steps, if there are multiple broken connection directories in the history.

This behavior is undesirable.
When the connection is fixed, I now need to go forward multiple times to get back to where I intended to be.

Instead, Nemo should keep the user-entered location, and show a "currently unavailable. do you want to try again?" where it would normally display the folder contents.
Similar to web browser.

By going backwards, Nemo is messing with user data (the entered location). Even if it is not entirely lost (it can be retrieved by clicking forward), it certainly feels that way.

**Comment by Vahan86** [comment]
@donquixote, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
