### ISSUE TITLE
[Feature request] Automount of shares

### ISSUE THREAD

**Issue by vranki** [linuxmint/nemo#699]
Add a checkbox to connect to server dialog  which would allow to auto-mount share when user logs in.

I know this can be done on command line, but that's not good usability.

The use case for this would be that an app that doesn't know that the path is a network share could access the files directly. Currently user has to mount the share(s) from nemo before using such app.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
