### ISSUE TITLE
directory content counts show '--' when turned off

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#700]
version 2.3.0.  Directory content counts are turned on in the settings - preview, folders.  However the 'never' show option is not working properly, it is showing '--' under the folders when the icons are large enough to show a description under them.
![screenshot from 2014-09-17 11 33 51](https://cloud.githubusercontent.com/assets/6322481/4302097/39e50458-3e56-11e4-84f8-43ebd721140e.png)

This behaviour appears to come from function  'nemo_file_get_string_attribute_with_default_q' and as far as I can see this value is put in to make the sorts that call it work a certain way ... 

On a related matter the presentation is quite 'texty'.  As a potential enhancement could it be made more visual by, say, just showing the number overlaid on the blank part of the folder tab (top left), perhaps, if the icon is shown big enough ?  This sort of thing:
![example](https://cloud.githubusercontent.com/assets/6322481/4311503/7166f194-3eaf-11e4-90c8-c9a00decaaac.png)

However seeing how complex nemo code is, I rather suspect that the change required to do this would be extremely difficult

**Comment by Vahan86** [comment]
Can't reproduce the issue with Nemo 3.0.6.
@brownsr, is this still an issue for you?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
