### ISSUE TITLE
icon view zoom level is affecting the cinnamon desktop but not nemo

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#701]
Visually odd issue noted in 2.3.0, using the Cinnamon nightly PPA. If you go into the nemo file management preferences and change the icon view default zoom level then it changes the size of the icons on the main cinnamon desktop, but does not change the size of the icons in nemo. Example below shows effect of reducing zoom from 100% to 66%
![screenshot from 2014-09-17 11 37 28](https://cloud.githubusercontent.com/assets/6322481/4302141/c9d05202-3e56-11e4-8d2b-bf2def5eec59.png)
![screenshot from 2014-09-17 11 37 37](https://cloud.githubusercontent.com/assets/6322481/4302143/d11d9038-3e56-11e4-87e4-db8cf4e92658.png)

Folder icons also coming up larger than I recollect when initially loading.   Don't know if related.

In fact the more I explore the more issues I am finding around zoom behaviour, may be related.  Changing the list zoom level only appears to take effect when navigating to a new directory, apparently no way to change within the directory you are in, and its behaviour seems pretty curious with lists shown larger when the preferences are set to show smaller.  May investigate, add more detail, and transfer to a separate issue when I can

**Comment by Vahan86** [comment]
I can reproduce this issue with Nemo 3.0.6.

- When you change the icon view default zoom level it changes the size of the icons on the Desktop, in Documents, Music, Pictures folders, etc. besides of the icons in Home folder.

- Changing of default zoom levels of compact and list view doesn't work at all.

![untitled](https://cloud.githubusercontent.com/assets/12819058/20277845/c8c0ad0c-aabb-11e6-915f-9f4a540fe917.png)

**Comment by jfkpdq** [comment]
Any news on this?

**Comment by xenopeek** [comment]
Not reproducible with Nemo 4.6.4 on Linux Mint 20:

- Default zoom level for Icon View in Nemo Preferences affects icons shown in the Nemo window only;
- Icon Size in desktop context menu > Customize affects icons shown on the desktop only.
