### ISSUE TITLE
Feature Request - "My Clipboard" paste queue

### ISSUE THREAD

**Issue by asatbluesboy** [linuxmint/nemo#705]
So, every time I have to transfer music from my computer to my phone's card I have to go through the artist's folder, copy the album(s) to the card, go to the next artist, do the same &c. until I have a million copy threads going on at the same time. I was thinking it'd be pretty neat if I could just drag and drop all the folders and files I want into a "mini" window so as to have a sort of paste queue, and just copy them all to wherever I wanted. Something like this pic:
![nemo](https://cloud.githubusercontent.com/assets/8810999/4314042/fbecbd90-3ed6-11e4-9b71-44f1dc4e22d4.jpg)
The buttons are terrible, I think a "Clear" button as well as "Move" options could also be interesting and the icons and file/folder names are way too big, but I think it's a decent mock-up of what I'm trying to suggest. Not a programmer here at all, so sorry about that.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
