### ISSUE TITLE
Bookmarks lost on restart

### ISSUE THREAD

**Issue by robin92** [linuxmint/nemo#708]
**Software version:** _nemo 2.2.4-1_
**Operating system:** _Arch Linux_

Please investigate the following issue:
1. Open new Nemo window
2. Create a new dummy directory
3. Add directory to the bookmarks (with CTRL+D)
4. Close Nemo
5. Logout & login (or just reboot)
6. Open new Nemo window => Bookmarks are lost, only defaults preserved

Please let me know if you need any logs or other stuff.

UPDATE:
Based on your code I've noticed that I lacked a directory ~~`~/config/gtk-3.0/`~~ `~/.config/gtk-3.0/` so I've created it. Moreover, I've created a file `~/.config/gtk-3.0/bookmarks` and added my URIs there. Now I can add and remove bookmarks as expected.

This leads to the conclusion that the problem is with `g_build_filename` method, which seems to be from a 3rd party library (gnome-common perhaps?). This function doesn't create an entire directory tree if needed. Any comments?

**Comment by actionmystique** [comment]
same issue on Ubuntu 15.04 with nemo 2.2.4 run as root

**Comment by Vahan86** [comment]
@robin92, is this still an issue for you with Nemo 3.0.6?

**Comment by robin92** [comment]
@Vahan86 I have not been using Cinnamon for over a year now.
