### ISSUE TITLE
[Tree sidebar] The delete key does nothing

### ISSUE THREAD

**Issue by Xodetaetl** [linuxmint/nemo#709]
And this is unexpected. To delete something from the tree sidebar, you have to right click > delete. It's still annoying me after 5 years of using Nemo and nobody cares about the poor Tree panel :'(.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
