### ISSUE TITLE
[Tree sidebar] No drag & drop from the tree

### ISSUE THREAD

**Issue by Xodetaetl** [linuxmint/nemo#710]
In Nemo, I can't move stuff around in/from the sidebar.
Sometimes I'm dreaming of Windows 95 where I had a perfectly usable tree view. :)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
