### ISSUE TITLE
[Tree sidebar] The context menu isn't the same as the main view

### ISSUE THREAD

**Issue by Xodetaetl** [linuxmint/nemo#711]
Which leaves out many very practical things that I would like to do from the tree view, like renaming, opening a terminal from the folder, opening as root, opening with xxx, moving and copying to xxx, etc.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
