### ISSUE TITLE
Apostrophe becoming &#x27; in Launchpad

### ISSUE THREAD

**Issue by aldatsa** [linuxmint/nemo#713]
Hi,

while translating Nemo to Basque I found that the apostrophe appears as \&#x27;

For example, the string located in libnemo-private/nemo-file-operations.c:283 libnemo-private/nemo-file-operations.c:294 appears as:

```
%&#x27;d minute
%&#x27;d minutes
```

Instead of the original:

```
%'d minute
%'d minutes
```

If I use \&#x27; in my translation I got an error message that says:

 'msgstr[0]' is not a valid C format string, unlike 'msgid_plural'. Reason: In the directive number 1, the character '&' is not a valid conversion specifier.'msgstr[1]' is not a valid C format string, unlike 'msgid_plural'. Reason: In the directive number 1, the character '&' is not a valid conversion specifier. 

I managed to save my translations using ' instead of \&#x27; but I think that it's quite confusing.

Best regards

**Comment by Vahan86** [comment]
@aldatsa, is this still an issue for you?

**Comment by aldatsa** [comment]
No. I've just tested it. The problem is fixed.
