### ISSUE TITLE
[Regression] Passing non-latin uri's to actions.

### ISSUE THREAD

**Issue by fsnow-ru** [linuxmint/nemo#717]
In Nemo 2.2.4 the issue https://github.com/linuxmint/nemo/issues/459 appeared again.

**Comment by Vahan86** [comment]
@fsnow-ru, is this still an issue for you with Nemo 3.0.6?

**Comment by fsnow-ru** [comment]
@Vahan86, yes. In Nemo 3.0.6 issue still relevant.

**Comment by icarter09** [comment]
@fsnow-ru are you still experiencing this issue on the latest version of nemo?

**Comment by fsnow-ru** [comment]
Checked in Nemo 4.4.2: Works correctly.-- С уважением,FSnowmailto:fsnow@yandex.ruxmpp:fsnow@jabber.ru08.04.2020, 13:13, "Isaac Carter" <notifications@github.com>:
@fsnow-ru are you still experiencing this issue on the latest version of nemo?

**Comment by icarter09** [comment]
@fsnow-ru thanks for the update.
