### ISSUE TITLE
[feature request] can the 'loading' message be suppressed when not needed

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#718]
In the list view when expanding a directory 'loading' pops up.  This makes no sense when the results immediately overwrite it, it just looks clumsy.  It only makes sense if there is a long delay.  Could it be suppressed unless results really are taking a while to come back ?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
