### ISSUE TITLE
Feature request - Show in groups (for sorted column)

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#720]
I believe, this is much useful feature in terms of neatly managing files. 
For instance, while navigating though music files, I tend to sort the files by Album column and managing them would become easy if there was a group by feature. Or if i want to sort files by size and delete only the large files, this would be quite handy. Similarly, one could sort by date and have them displayed in groups, Today, This Week, Month Ago, etc. 

Obligatory screenshot reference - _(KDE's is shown below, even Windows has it.)_
![20101026141308 dolphin_show_in_groups_effect 1](https://cloud.githubusercontent.com/assets/4663298/4554348/95265752-4eac-11e4-88d8-f858d28059f1.png)

**Comment by BRKsays** [comment]
+1. Was about to request this feature, but decided to dig for previous entries first. Grouping items by file types, size etc. should be a feature to be considered.

**Comment by prat-man** [comment]
I yearn for the same feature. It would be very helpful if this feature is included in nemo.

**Comment by thorsummoner** [comment]
I could see the usefulness, I often go as far as sorting the details view by mime type to get at file type groups, but this would be ideal for that. I would especially like the ability to see this view with both file extension boundaries, and file mime-type boundaries as well.

**Comment by zbandhan** [comment]
I like to see this in my favorite LM

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by parijathakumar** [comment]
+1 for this feature request. This is one of the best features KDE's dolphin file manager has for a long time. In fact, I'be been requesting for this feature on veaious forums and social networks, not knowing that this is the right place. I would like to see this feature in Mate's file manager 'caja' too. Where should I file a feature request ?

**Comment by kronomia** [comment]
+1 - This is the most important feature in my opinion for those who work with lots of files. I am even willing to pay for this feature if anyone is willing to develop it for Nemo.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by masterofobzene** [comment]
EDIT: I'm making a new issue with my petition since its not clear if OP wanted groups or sorting-
