### ISSUE TITLE
Incorrect Sidebar Eject Icon 

### ISSUE THREAD

**Issue by Foggalong** [linuxmint/nemo#722]
Nemo does a pretty good job of picking all the right icons from whichever theme is the current default, except for it's media eject button.

With a non-application icon theme installed it takes on a grey circular icon which presumably doesn't take a name from the freedesktop standards as it isn't themed. I've shown it below with the Faba and Numix icon themes.

![Faba](http://i.imgur.com/wY2pQPY.png) ![Numix](http://i.imgur.com/ffHESNr.png)

With an application icon theme installed it becomes apparent that it takes the icon with the name `nemo.svg` which isn't great because it them picks up the application icon for Nemo from the users chosen theme. I've shown it below with the Moka and Numix Circle icon themes.

![Moka](http://i.imgur.com/olBPCL3.png) ![Circle](http://i.imgur.com/ZHZ4AQa.png)

The preferable change would be to make it so Nemo uses a standardised "media eject" icon name such as `media-eject-symbolic.svg` rather than `nemo.svg` for it's eject button.

**Comment by dobegor** [comment]
Issue is more than year old and it's still present.
Is there any workaround?

**Comment by Vahan86** [comment]
Can't reproduce this issue in Nemo 3.0.6.
@Foggalong, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
