### ISSUE TITLE
Folder view text Kerning error

### ISSUE THREAD

**Issue by MathSter** [linuxmint/nemo#724]
When re naming a folder in nemo I notised this minor kerning error. Its a bit an*l of me i know but it looks like the T and e are too close together, see below. Its probably not an issue with nemo its self, but the use and configuration of the font package in use, any ideas?
![screenshot from 2014-10-13 14 44 11](https://cloud.githubusercontent.com/assets/6420549/4614525/000e30de-52e1-11e4-905b-0de5e5841f83.png)

**Comment by Vahan86** [comment]
@MathSter, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
