### ISSUE TITLE
[feature request] list view - open all folders at once 

### ISSUE THREAD

**Issue by saqua** [linuxmint/nemo#726]
is there actually a way to mark all folders in list view, for example with:

strg+a
        + right arrow-key [to open all marked folders]
and
        + left arrow-key [to close all marked folders]

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
