### ISSUE TITLE
[feature request] Nemo Action - 'Extensions' option to support any extension but xyz. 

### ISSUE THREAD

**Issue by davenul** [linuxmint/nemo#729]
Nemo actions are great! I just couldn't find an option to exclude an action on certain file extensions.
ie. - show an action on any extension but gz;zip;rar; etc'.
Adding an additional option like ExtensionExclude=gz;zip;rar; will be great!!!

Thanks.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
