### ISSUE TITLE
Properties won't rescan if path doesn't change

### ISSUE THREAD

**Issue by nirvdrum** [linuxmint/nemo#730]
I've been cleaning up a lot of old files lately.  To see how I'm doing, I've been checking the current folder's properties to see how many files it still contains and what the total size is.  If I close the properties window and delete files, then re-open the properties window, it won't rescan and instead show bad cached values.  I have to change the path in the file browser window before I can get up-to-date results.

**Comment by Vahan86** [comment]
I can't reproduce the issue in Nemo 3.0.6.
@nirvdrum, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by nirvdrum** [comment]
Sorry. I've been meaning to make the time to try upgrading. I had a lot of issues with my first upgrade to 3.0, so I had to roll back. I had a stable system, so I haven't tried to upgrade since.
