### ISSUE TITLE
Memory not freed when closing nemo during file tree expansion

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#737]
I was exploring using '*' to open the file tree, and clearly managed to open up rather more than I had anticipated ... so I closed nemo using the normal x on the window to stop my runaway query.  The window closed, and after a while the system monitor showed that the search had stopped and the CPU% of nemo went down to zero.  Unfortunately the 700MB or so memory usage did not get freed up.  I waited quite a while in case the garbage collection was periodic, but no joy.

**Comment by icarter09** [comment]
@brownsr any update on this ticket?
