### ISSUE TITLE
Tree view bug (Nemo 2.2.4)

### ISSUE THREAD

**Issue by hipoloco** [linuxmint/nemo#743]
Because my english is very poor, I post a video with the error:

https://www.youtube.com/watch?v=myK5GhPECJE

Error output:

(nemo:8085): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(nemo:8085): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(nemo:8085): GdkPixbuf-CRITICAL *_: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
*_
Gdk:ERROR:/tmp/buildd/gtk+3.0-3.10.8~6+qiana/./gdk/gdkcairo.c:193:gdk_cairo_surface_paint_pixbuf: assertion failed: (cairo_image_surface_get_format (surface) == CAIRO_FORMAT_RGB24 || cairo_image_surface_get_format (surface) == CAIRO_FORMAT_ARGB32)

**Comment by Vahan86** [comment]
@hipoloco, does this issue still occur in Nemo 3.0.6 (Linux Mint 18)?

**Comment by DeathAintDead** [comment]
In my own case (Mint 18, Nemo 3.0.6) : no issue anymore

**Comment by hipoloco** [comment]
In this moment I'm using Mint 17.3 with Nemo 2.8.7 without issues.

**Comment by Vahan86** [comment]
@hipoloco, @DeathAintDead, thanks for reply. @hipoloco, in this case can you please close the issue?
