### ISSUE TITLE
[Regression]: custom Folder icon not shown in bookmarks

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#747]
In Nemo 1.8.4 from Ubuntu 14.04, a custom Folder-Icon I set is also shown when I drag & drop it onto Bookmarks, in 2.2.4 from webupd8 ppa, that's not the case, it just has the default  Folder-Icon in the bookmarks. 

I have set a custom Folder-Icon of a folder called Projects in my Home-Folder; If I browse the Home-Folder, the customized Icon gets shown as it should. If I do an ALT-TAB while Nemo is displaying this folder, it shows the Custom Icon in the ALT-TAB pane instead of the default folder icon, which is nice so that I know here my Projects folder is. 
But in the Sidebar, the bookmark of my Project Folder is not showing this icon. 

It would be nice if the Sidebar would respect Custom Icons again, as this would be the expected behavior and makes using Nemo more consistent.

**Comment by simonwiles** [comment]
Same issue here.  In the past, the icons would appear in the bookmarks bar when the folder was opened, even if not before, but now they just don't show at all.

    $ lsb_release -crid
    Distributor ID:	LinuxMint
    Description:		Linux Mint 19.1 Tessa
    Release:		19.1
    Codename:		tessa

    $ nemo --version
    nemo 4.0.6

Thanks!

**Comment by xenopeek** [comment]
The sidebar uses symbolic icons. It's by design that custom folder icons aren't shown in the sidebar.

**Comment by simonwiles** [comment]
Thanks for the update -- so it's a deliberate regression?  Was the (very useful) feature considered too onerous to maintain, do you know?
