### ISSUE TITLE
[feature request] symbols in "new document" menu

### ISSUE THREAD

**Issue by Hedaja** [linuxmint/nemo#748]
It would be nice to see the symbols of the templates inside the "new dokument" menu. I think this would make finding the correct document type faster.

**Comment by Vahan86** [comment]
Checked in Nemo 3.0.6. The issue is fixed.
@JosephMcc, can we close the issue?

**Comment by Hedaja** [comment]
yeah it seems like ti takes the symbols form the document type you save in ~/Templates

**Comment by Vahan86** [comment]
@Hedaja, if it's not an issue for you anymore, can you please close the issue?

**Comment by Hedaja** [comment]
-closed-
