### ISSUE TITLE
nemo logging millions of errors to ~/.xsession-errors

### ISSUE THREAD

**Issue by dhdurgee** [linuxmint/nemo#749]
In the past few weeks I have encountered several cases where a tremendous volume of errors have been logged to ~/.xsession-errors, in several cases completely filling the root partition.  Yesterday I was able to catch one of these run-away error logging conditions and reboot before the root was full.  I booted another linux partition and tallied the errors in the file.  The major offenders were:

2223522 *\* (nemo:2184): CRITICAL **: nemo_directory_file_monitor_remove: assertion `NEMO_IS_DIRECTORY (directory)' failed

2223522 *\* (nemo:2184): CRITICAL **: nemo_directory_unref: assertion `NEMO_IS_DIRECTORY (directory)' failed

2223522 (nemo:2184): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

2223523 (nemo:2184): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `(null)'

The above millions of errors were logged within a few minutes, as I caught this quickly since I was keeping an eye on that file for the run-away condition.

The system in question is a desktop with linux mint 13 maya x64 cinnamon installed.  If there is any further information needed to diagnose this problem please let me know.  Nemo shows as version 2.0.8 from the terminal window.

**Comment by Vahan86** [comment]
@dhdurgee, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
