### ISSUE TITLE
Pathbar ignoring :active/:selected in nemo.css

### ISSUE THREAD

**Issue by pocketpc** [linuxmint/nemo#750]
I have tested this with several themes, and Nemo 2.2.4 on Arch Linux is consistently ignoring rules for the active pathbar element. I also tried manually replacing :active with :selected in the theme files in case they were written wrong, to no avail.
![screenshot from 2014-10-30 21 24 53](https://cloud.githubusercontent.com/assets/1869543/4854922/c7d9cede-609c-11e4-9fba-7427aef35122.png)

**Comment by JosephMcc** [comment]
Closing this. The nemo pathbar has been completely made over since.
