### ISSUE TITLE
[Feature Request]: add Connect to Server... in sidepane

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#751]
nautilus 3.10+ has Connect to Server in side panel under Network, which is a good idea for people which use that often, albeit it should be an optional feature, toggleable via gsettings.

Connect to Server... the three dots are missing in nautilus, and as this is an action to run, these are mandatory in my opinion. 

Also, I would propose to add another gsettings value to switch between built-in connect-to-server dialogue and a custom one. Gigolo e.g has a more sophisticated interface with the ability to AutoConnect to many Bookmarked locations at once

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
