### ISSUE TITLE
Format USB stick action not displayed

### ISSUE THREAD

**Issue by ppareit** [linuxmint/nemo#752]
On Mint 17, right clicking in nemo on an usb stick, there is no 'Format USB stick' action displayed.

**Comment by eladhen** [comment]
I'm not sure if this is a bug or if this feature was removed on purpose... I just noticed Nemo has a "Format" plugin, but the option doesn't seem to appear... There's also a "Make bootable USB" plugin but no option to do it. What's going on?

**Comment by Vahan86** [comment]
The feature is enabled by default in Nemo 3.0.6.
@JosephMcc, can we close the issue?
