### ISSUE TITLE
[Feature Request] Open new tab on middle click on toolbar buttons

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#753]
The toolbar buttons (apart from bread crumbs) all do nothing on middle click.
Back, forward, up, home and computer could all be set to open the respective folders in a new tab on middle click. 
Even the refresh button could be set to open the current folder in a new tab.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by dg1727** [comment]
A variation on this, which I hope can be implemented, is to have a right-click menu (on each of the buttons in question) with options "Open in New Tab" and "Open in New Window."

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
