### ISSUE TITLE
the mount point gauge doesn't work

### ISSUE THREAD

**Issue by hafuz** [linuxmint/nemo#755]
On Ubuntu 14.04, nemo work wery well... Exept that the mount point gauge doesn't work.
![screenshot1](https://cloud.githubusercontent.com/assets/7572478/4916212/d05f4d7a-64d6-11e4-815d-19975abe0ddd.png)

**Comment by Vahan86** [comment]
@hafuz, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
