### ISSUE TITLE
Nemo always starts terminal in home directory instead of current.

### ISSUE THREAD

**Issue by NikNik77771** [linuxmint/nemo#759]
Linux Mint "Debian" - 201403 Cinnamon 64-bit
https://github.com/linuxmint/Cinnamon/issues/3653

**Comment by RavetcoFX** [comment]
are you using gnome-terminal?

**Comment by NikNik77771** [comment]
This is cinnamon standard terminal.

**Comment by xenopeek** [comment]
LMDE 1 is obsoleted so I think this can be closed.

**Comment by LinuxOnTheDesktop** [comment]
> LMDE 1 is obsoleted so I think this can be closed.

This happens to me, _on Linux Mint 20.1 Cinnamon_, when using the default gnome-terminal and when using xfce4-terminal. It would be good for many a person's workflow, I suspect, were

`~/myDir $ nemo`

or even e.g.

`~/myDir $ nemo -c`

to open Nemo in `~/myDir`.
