### ISSUE TITLE
Rename file not case-sensitive

### ISSUE THREAD

**Issue by FabrizioMarana** [linuxmint/nemo#762]
Problem:
Create new document - Empty Document
Change "Untitled Document" to "untitled Document"

Symptom:
Messagebox:
Window title: empty
Icon: stop
Bold title: "The item could not be renamed"
Text: "The name "untitled Document" is already used in this folder. Please use a diferent name."

Work-around:
Rename to "untitled Document-"
Rename again but now to "untitled Document"

Solution:
Nemo-file.c, 
nemo_file_rename (NemoFile *file, const char *new_name, NemoFileOperationCallback callback, gpointer callback_data)
Add support for case-sensitive rename.
(I'm too bad a programmer to fork and modify myself in this beautiful code....  ;) I will carefully look at the result once this bug gets closed though!

Thank you, Merci, Danke, Dank u, dankie, спасибо, ...

**Comment by metafarion** [comment]
This was definitely an issue as recently as 2.6.7 but appears to have been fixed since at least 2.8.6

**Comment by Vahan86** [comment]
Can't reproduce the issue. It works fine for me.
@FabrizioMarana, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
