### ISSUE TITLE
crash with SIGABRT after right click on "My Computer"

### ISSUE THREAD

**Issue by simon-schneider** [linuxmint/nemo#765]
On my machins, nemo **2.2.4+quiana** crashes with SIGABRT when I right click the headers in the tree view.

Steps to reproduce:
- open nemo
- right click on a tree header (localized for german as "Mein Rechner") 

![nemo-wheretoclick](https://cloud.githubusercontent.com/assets/9720359/5029589/aea3d458-6b48-11e4-9777-ba327d5d7642.png)

Expected behaviour:
- context menu opens / nothing at all

Actual behaviour:
- window disappears

Backtrace (gdb with nemo-dbg installed):

> GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> http://www.gnu.org/software/gdb/bugs/.
> Find the GDB manual and other documentation resources online at:
> http://www.gnu.org/software/gdb/documentation/.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from nemo...Reading symbols from /usr/lib/debug//usr/bin/nemo...done.
> done.
> (gdb) run
> Starting program: /usr/bin/nemo 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7fffed573700 (LWP 25452)]
> [New Thread 0x7fffecd72700 (LWP 25453)]
> [New Thread 0x7fffe7fff700 (LWP 25454)]
> [New Thread 0x7fffe6fa7700 (LWP 25455)]
> [New Thread 0x7fffe5eb4700 (LWP 25457)]
> [New Thread 0x7fffe5225700 (LWP 25458)]
> [New Thread 0x7fffd93b8700 (LWP 25459)]
> [Thread 0x7fffd93b8700 (LWP 25459) exited]
> [Thread 0x7fffe5225700 (LWP 25458) exited]
> [Thread 0x7fffe5eb4700 (LWP 25457) exited]
> **
> Gtk:ERROR:/tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcellrenderer.c:1735:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
> 
> Program received signal SIGABRT, Aborted.
> 0x00007ffff41fdbb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
> 56      ../nptl/sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
> (gdb) bt
> # 0  0x00007ffff41fdbb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
> # 1  0x00007ffff4200fc8 in __GI_abort () at abort.c:89
> # 2  0x00007ffff5092165 in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> # 3  0x00007ffff50921fa in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> # 4  0x00007ffff6c3d676 in gtk_cell_renderer_get_aligned_area (cell=0x7fffc8005e60, widget=0xc08ca0, flags=(GTK_CELL_RENDERER_PRELIT | GTK_CELL_RENDERER_FOCUSED | GTK_CELL_RENDERER_EXPANDABLE | GTK_CELL_RENDERER_EXPANDED), cell_area=0x7fffffffb6c0, aligned_area=0x7fffffffb6d0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcellrenderer.c:1735
> # 5  0x00007ffff6c34841 in render_cell (renderer=0x7fffc8005e60, cell_area=<optimized out>, cell_background=0x7fffffffb7e0, data=0x7fffffffb840) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcellarea.c:1148
> # 6  0x00007ffff6c371a6 in gtk_cell_area_box_foreach_alloc (area=0xcc93f0, context=<optimized out>, widget=0xc08ca0, cell_area=0x7fffffffba20, background_area=0x7fffffffba10, callback=0x7ffff6c347b0 <render_cell>, callback_data=0x7fffffffb840) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcellareabox.c:1289
> # 7  0x00007ffff6c3441d in gtk_cell_area_real_render (area=0xcc93f0, context=0xd6a6d0, widget=0xc08ca0, cr=0xc05040, background_area=0x7fffffffba10, cell_area=0x7fffffffba20, flags=(GTK_CELL_RENDERER_PRELIT | GTK_CELL_RENDERER_FOCUSED | GTK_CELL_RENDERER_EXPANDABLE | GTK_CELL_RENDERER_EXPANDED), paint_focus=0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcellarea.c:1213
> # 8  0x00007ffff6e1364a in _gtk_tree_view_column_cell_render (tree_column=<optimized out>, cr=0xc05040, background_area=0x7fffffffba10, cell_area=0x7fffffffba20, flags=114, draw_focus=0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtktreeviewcolumn.c:2951
> # 9  0x00007ffff6dfdb2e in gtk_tree_view_bin_draw (cr=0xc05040, widget=0xc08ca0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtktreeview.c:5198
> # 10 draw_bin (cr=0xc05040, user_data=0xc08ca0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtktreeview.c:5460
> # 11 0x00007ffff6d42588 in _gtk_pixel_cache_draw (cache=0xd6fc30, cr=cr@entry=0xc05040, window=0xe24d50, view_rect=view_rect@entry=0x7fffffffbb60, canvas_rect=canvas_rect@entry=0x7fffffffbb70, draw=draw@entry=0x7ffff6dfca80 <draw_bin>, user_data=user_data@entry=0xc08ca0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkpixelcache.c:440
> # 12 0x00007ffff6df7c28 in gtk_tree_view_draw (widget=0xc08ca0, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtktreeview.c:5503
> # 13 0x00007ffff6cf2d6e in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x7e09a0, return_value=return_value@entry=0x7fffffffbd50, instance=instance@entry=0xc08ca0, args=args@entry=0x7fffffffbe58, marshal_data=marshal_data@entry=0x7ffff6df7b30 <gtk_tree_view_draw>, n_params=n_params@entry=1, param_types=param_types@entry=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmarshalers.c:130
> # 14 0x00007ffff6e186ad in gtk_widget_draw_marshallerv (closure=0x7e09a0, return_value=0x7fffffffbd50, instance=0xc08ca0, args=0x7fffffffbe58, marshal_data=0x7ffff6df7b30 <gtk_tree_view_draw>, n_params=1, param_types=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:1009
> # 15 0x00007ffff533d55f in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 16 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 17 0x00007ffff5356ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 18 0x00007ffff6e25b96 in _gtk_widget_draw_internal (widget=widget@entry=0xc08ca0, cr=cr@entry=0xc05040, clip_to_size=clip_to_size@entry=1, window=window@entry=0xe24d50) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6441
> # 19 0x00007ffff6e271df in _gtk_widget_draw_internal (window=0xe24d50, clip_to_size=1, cr=0xc05040, widget=0xc08ca0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6420
> # 20 _gtk_widget_draw_windows (window=window@entry=0xe24d50, cr=cr@entry=0xc05040, window_x=<optimized out>, window_y=<optimized out>) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6542
> # 21 0x00007ffff6e27265 in _gtk_widget_draw_windows (window=window@entry=0xe24c20, cr=cr@entry=0xc05040, window_x=window_x@entry=0, window_y=window_y@entry=0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6562
> # 22 0x00007ffff6e27444 in _gtk_widget_draw (widget=widget@entry=0xc08ca0, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6613
> # 23 0x00007ffff6c6050d in gtk_container_propagate_draw (container=container@entry=0xd8c340, child=0xc08ca0, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3528
> # 24 0x00007ffff6c605d2 in gtk_container_draw (widget=0xd8c340, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3363
> # 25 0x00007ffff6d6479a in gtk_scrolled_window_draw (widget=0xd8c340, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkscrolledwindow.c:1442
> # 26 0x00007ffff6cf2d6e in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x7e09a0, return_value=return_value@entry=0x7fffffffc430, instance=instance@entry=0xd8c340, args=args@entry=0x7fffffffc538, marshal_data=marshal_data@entry=0x7ffff6d64710 <gtk_scrolled_window_draw>, n_params=n_params@entry=1, param_types=param_types@entry=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmarshalers.c:130
> # 27 0x00007ffff6e186ad in gtk_widget_draw_marshallerv (closure=0x7e09a0, return_value=0x7fffffffc430, instance=0xd8c340, args=0x7fffffffc538, marshal_data=0x7ffff6d64710 <gtk_scrolled_window_draw>, n_params=1, param_types=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:1009
> # 28 0x00007ffff533d55f in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 29 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 30 0x00007ffff5356ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 31 0x00007ffff6e25b96 in _gtk_widget_draw_internal (widget=widget@entry=0xd8c340, cr=cr@entry=0xc05040, clip_to_size=clip_to_size@entry=1, window=window@entry=0xe24af0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6441
> # 32 0x00007ffff6e271df in _gtk_widget_draw_internal (window=0xe24af0, clip_to_size=1, cr=0xc05040, widget=0xd8c340) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6420
> # 33 _gtk_widget_draw_windows (window=window@entry=0xe24af0, cr=cr@entry=0xc05040, window_x=<optimized out>, window_y=<optimized out>) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6542
> # 34 0x00007ffff6e27530 in _gtk_widget_draw (widget=widget@entry=0xd8c340, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6638
> # 35 0x00007ffff6c6050d in gtk_container_propagate_draw (container=container@entry=0xc92d50, child=0xd8c340, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3528
> # 36 0x00007ffff6c605d2 in gtk_container_draw (widget=0xc92d50, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3363
> # 37 0x00007ffff6cf2d6e in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x7e09a0, return_value=return_value@entry=0x7fffffffc9b0, instance=instance@entry=0xc92d50, args=args@entry=0x7fffffffcab8, marshal_data=marshal_data@entry=0x7ffff6c60550 <gtk_container_draw>, n_params=n_params@entry=1, param_types=param_types@entry=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmarshalers.c:130
> # 38 0x00007ffff6e186ad in gtk_widget_draw_marshallerv (closure=0x7e09a0, return_value=0x7fffffffc9b0, instance=0xc92d50, args=0x7fffffffcab8, marshal_data=0x7ffff6c60550 <gtk_container_draw>, n_params=1, param_types=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:1009
> # 39 0x00007ffff533d55f in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 40 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 41 0x00007ffff5356ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 42 0x00007ffff6e25b96 in _gtk_widget_draw_internal (widget=widget@entry=0xc92d50, cr=cr@entry=0xc05040, clip_to_size=clip_to_size@entry=1, window=window@entry=0xe24890) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6441
> # 43 0x00007ffff6e27573 in _gtk_widget_draw_internal (window=0xe24890, clip_to_size=1, cr=0xc05040, widget=0xc92d50) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6573
> # 44 _gtk_widget_draw (widget=widget@entry=0xc92d50, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6619
> # 45 0x00007ffff6c6050d in gtk_container_propagate_draw (container=container@entry=0x91a670, child=0xc92d50, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3528
> # 46 0x00007ffff6c605d2 in gtk_container_draw (widget=0x91a670, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3363
> # 47 0x00007ffff6d2a723 in gtk_paned_draw (widget=0x91a670, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkpaned.c:1612
> # 48 0x00007ffff6cf2d6e in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x7e09a0, return_value=return_value@entry=0x7fffffffcee0, instance=instance@entry=0x91a670, args=args@entry=0x7fffffffcfe8, marshal_data=marshal_data@entry=0x7ffff6d2a690 <gtk_paned_draw>, n_params=n_params@entry=1, param_types=param_types@entry=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmarshalers.c:130
> # 49 0x00007ffff6e186ad in gtk_widget_draw_marshallerv (closure=0x7e09a0, return_value=0x7fffffffcee0, instance=0x91a670, args=0x7fffffffcfe8, marshal_data=0x7ffff6d2a690 <gtk_paned_draw>, n_params=1, param_types=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:1009
> # 50 0x00007ffff533d55f in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 51 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 52 0x00007ffff5356ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 53 0x00007ffff6e25b96 in _gtk_widget_draw_internal (widget=widget@entry=0x91a670, cr=cr@entry=0xc05040, clip_to_size=clip_to_size@entry=1, window=window@entry=0xe24890) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6441
> # 54 0x00007ffff6e271df in _gtk_widget_draw_internal (window=0xe24890, clip_to_size=1, cr=0xc05040, widget=0x91a670) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6420
> # 55 _gtk_widget_draw_windows (window=window@entry=0xe24890, cr=cr@entry=0xc05040, window_x=<optimized out>, window_y=<optimized out>) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6542
> # 56 0x00007ffff6e27530 in _gtk_widget_draw (widget=widget@entry=0x91a670, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6638
> # 57 0x00007ffff6c6050d in gtk_container_propagate_draw (container=container@entry=0xc06250, child=0x91a670, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3528
> # 58 0x00007ffff6c605d2 in gtk_container_draw (widget=0xc06250, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3363
> # 59 0x00007ffff6cb8622 in gtk_grid_draw (widget=0xc06250, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkgrid.c:1698
> # 60 0x00007ffff6cf2d6e in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x7e09a0, return_value=return_value@entry=0x7fffffffd490, instance=instance@entry=0xc06250, args=args@entry=0x7fffffffd598, marshal_data=marshal_data@entry=0x7ffff6cb85b0 <gtk_grid_draw>, n_params=n_params@entry=1, param_types=param_types@entry=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmarshalers.c:130
> # 61 0x00007ffff6e186ad in gtk_widget_draw_marshallerv (closure=0x7e09a0, return_value=0x7fffffffd490, instance=0xc06250, args=0x7fffffffd598, marshal_data=0x7ffff6cb85b0 <gtk_grid_draw>, n_params=1, param_types=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:1009
> # 62 0x00007ffff533d55f in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 63 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 64 0x00007ffff5356ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 65 0x00007ffff6e25b96 in _gtk_widget_draw_internal (widget=widget@entry=0xc06250, cr=cr@entry=0xc05040, clip_to_size=clip_to_size@entry=1, window=window@entry=0x7fffc8005e90) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6441
> # 66 0x00007ffff6e27573 in _gtk_widget_draw_internal (window=0x7fffc8005e90, clip_to_size=1, cr=0xc05040, widget=0xc06250) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6573
> # 67 _gtk_widget_draw (widget=widget@entry=0xc06250, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6619
> # 68 0x00007ffff6c6050d in gtk_container_propagate_draw (container=container@entry=0xc08550, child=0xc06250, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3528
> # 69 0x00007ffff6c605d2 in gtk_container_draw (widget=0xc08550, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:3363
> # 70 0x00007ffff6e37a74 in gtk_window_draw (widget=0xc08550, cr=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwindow.c:9407
> # 71 0x00007ffff6cf2d6e in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x7e09a0, return_value=return_value@entry=0x7fffffffd9e0, instance=instance@entry=0xc08550, args=args@entry=0x7fffffffdae8, marshal_data=marshal_data@entry=0x7ffff6e37a10 <gtk_window_draw>, n_params=n_params@entry=1, param_types=param_types@entry=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmarshalers.c:130
> # 72 0x00007ffff6e186ad in gtk_widget_draw_marshallerv (closure=0x7e09a0, return_value=0x7fffffffd9e0, instance=0xc08550, args=0x7fffffffdae8, marshal_data=0x7ffff6e37a10 <gtk_window_draw>, n_params=1, param_types=0x7e0a10) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:1009
> # 73 0x00007ffff533d5e7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 74 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 75 0x00007ffff5356ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 76 0x00007ffff6e25b96 in _gtk_widget_draw_internal (widget=widget@entry=0xc08550, cr=cr@entry=0xc05040, clip_to_size=clip_to_size@entry=1, window=window@entry=0x7fffc8005e90) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6441
> # 77 0x00007ffff6e271df in _gtk_widget_draw_internal (window=0x7fffc8005e90, clip_to_size=1, cr=0xc05040, widget=0xc08550) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6420
> # 78 _gtk_widget_draw_windows (window=window@entry=0x7fffc8005e90, cr=cr@entry=0xc05040, window_x=window_x@entry=0, window_y=window_y@entry=0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6542
> # 79 0x00007ffff6e27444 in _gtk_widget_draw (widget=widget@entry=0xc08550, cr=cr@entry=0xc05040) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6613
> # 80 0x00007ffff6e27793 in gtk_widget_send_expose (widget=widget@entry=0xc08550, event=event@entry=0x7fffffffddb0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:6998
> # 81 0x00007ffff6cf2b8f in gtk_main_do_event (event=0x7fffffffddb0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkmain.c:1626
> # 82 0x00007ffff68de0bb in _gdk_window_process_updates_recurse_helper (window=0x7fffc8005e90, expose_region=<optimized out>, dx=<optimized out>, dy=0) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gdk/gdkwindow.c:3382
> # 83 0x00007ffff68dc465 in gdk_window_process_updates_internal (window=window@entry=0x7fffc8005e90) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gdk/gdkwindow.c:3490
> # 84 0x00007ffff68dc58d in gdk_window_process_updates_with_mode (window=<optimized out>, recurse_mode=<optimized out>) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gdk/gdkwindow.c:3689
> # 85 0x00007ffff533d5e7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 86 0x00007ffff5356088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 87 0x00007ffff5357212 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> # 88 0x00007ffff68d6838 in gdk_frame_clock_paint_idle (data=0xd94530) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gdk/gdkframeclockidle.c:430
> # 89 0x00007ffff68c8ec8 in gdk_threads_dispatch (data=0x114d080) at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gdk/gdk.c:804
> # 90 0x00007ffff506e703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> # 91 0x00007ffff506dce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> # 92 0x00007ffff506e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> # 93 0x00007ffff506e0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> # 94 0x00007ffff5620b9c in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
> # 95 0x000000000042bdf9 in main (argc=1, argv=0x7fffffffe4f8) at nemo-main.c:101
> 
> (gdb) kill
> Kill the program being debugged? (y or n) y
> (gdb) quit

**Comment by Vahan86** [comment]
Can't reproduce the issue.
@simon-schneider, is this still an issue for you in Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
