### ISSUE TITLE
Nemo closing unexpectedly after the last changes

### ISSUE THREAD

**Issue by ScipioAfricanus** [linuxmint/nemo#766]
In the last few days I've noticed that when I try to open some apparently random folders in Nemo, it (Nemo) unexpectedly close itself. I cannot reproduce it always, with every folder, but it happens very often. I'm using the latest Cinnamon/Nemo from the nightly ppa on Ubuntu 14.04.

**Comment by Vahan86** [comment]
@ScipioAfricanus, @ManIVIctorious, does this issue still occur in Nemo 3.0.6?

**Comment by ManIVIctorious** [comment]
I think this has been solved a long time ago, had no nemo crash for several weeks. Back when this issue was reported i had several per day
