### ISSUE TITLE
Nemo crashes on directories with JP2 files

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/nemo#767]
Hi, I'm using Cinnamon and Nemo, both at version 2.4 on openSUSE. I also have ffmpegthumbnailer installed. Nemo crashes every time upon opening a folder with JP2 (JPEG 2000) files in it, using the detailed list view. Not sure if it's Nemo or ffmpegthumbnailer that's at fault, but at any rate Nemo shouldn't crash.

Thanks for looking into this!

**Comment by Vahan86** [comment]
@geckolinux, is this still an issue for you with Nemo 3.0.6?

**Comment by geckolinux** [comment]
Looks like it's fixed now on Nemo **3.2.0** thanks.
