### ISSUE TITLE
Nemo action requests

### ISSUE THREAD

**Issue by KamDa** [linuxmint/nemo#770]
Hello. 

nemo_action is pretty cool already, but some features are lacking to make it more useful.
- Selection: for selecting multiple files, we have two options: "any" (combined with a mimetype), but in this case il will also work on a background click, which will select a folder, or "multiple", which only works... on multiple files (the menu entry doesn't show up if you select only one file). We really could use a "one or more files" option.
- Conditions: we need more of those. There's an option for desktop files. What about being able to specify the working dir instead, so the menu entry only appears in a specific folder? Apparently, there's no way atm to create an action only for the trash for instance.

Thanks for your time. Cheers.

**Comment by nemonein** [comment]
Any progress?
I also wish @KamDa's 2nd topic could be implemented.
For example, the Action only available under a specific directory.
If I set 'Conditions' to '/media/UserX/USB/Music', the Action works(shows) only under /media/UserX/USB/Music and its subdirectories(like /media/UserX/USB/Music/A, etc), not /media/UserX/USB/Picture or any other directories.

```
/media/UserX/USB/Music
/media/UserX/USB/Music/A
/media/UserX/USB/Music/B
/media/UserX/USB/Music/C
/media/UserX/USB/Picture
/media/UserX/USB/Video
```

**Comment by smurphos** [comment]
Hi,

Another request for additional conditionality  - the ability to only show an action based on the file/folders ownership. 

e.g.

Conditions: ownedbyuser;

or

Conditions: notownedbyuser;

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
