### ISSUE TITLE
Single click behaviour doesn't affect sidebar categories

### ISSUE THREAD

**Issue by davcri** [linuxmint/nemo#774]
I found out that enabling single click behaviour doesn't affect the sidebar.

![screenshot](http://imgur.com/gs1NL2W.png)

Single click on the blue rectangle will open (close) the list, instead a single click on the red rectangle will not trigger this action. 
Don't you think that the single click behaviour should be used also in the red rectangle ?  

I'm using _nemo 2.2.4_ with _Linux Mint 17_. :smile:

**Comment by davcri** [comment]
Behaviour isn't changed in _Nemo 2.4.5__.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
