### ISSUE TITLE
Nemo could omit current and future problems of sudo(more than 8 years old), to send the session as root, and could force to change all target files to /root.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/nemo#777]
At the start a nemo session as root, Nemo will need to change all target files to /root or neno can not control these files later, because were written with administrative privileges, when there was launched with administrative privileges. Please see:
https://github.com/linuxmint/Cinnamon/issues/3676
http://forums.linuxmint.com/viewtopic.php?f=208&t=183885

I previously thought, that has solved the problem here:
https://github.com/linuxmint/nemo/commit/acabbaf6ca8e5ffc29851d766339c602777c4427

but this only resolve partially the problem...
Thanks.

**Comment by clefebvre** [comment]
There's an easy way to prevent that. Nemo could check if it's run as root. In this case it could either:

- Make cache files it creates writable by all
- Or not write cache files at all when run with admin privileges

**Comment by mc0e** [comment]
If root is creating files under a user owned directory, that's often a recipe for race conditions being playable with symlinks.  In this case I think it's safe to assume that the user involved has root access anyway, but still, if nemo is run as root, it should not write to the user's cache.

**Comment by lestcape** [comment]
@clefebvre thanks, i will appreciate this patch, and also i think, this will help a lot to distinguish of a true nemo memory leak and a problem thats is create from a source that is outside nemo, so will stop several issues here.

The alternative of send all cache to root folder (not matter where inside it) if nemo is running as root, is not possible or will be hard? just to not lost data, i don't know what will be the difference of running without cache. Performance?

Regards.

**Comment by lestcape** [comment]
I see that Mint have a gedit copy (https://github.com/linuxmint/gedit), i don't know if it's in use and i don't know if will be helpfully apply the same in gedit for Mint users. Regards and thanks.

**Comment by mtwebster** [comment]
I was planning on looking into our gedit with regards to the recent places file issues.

**Comment by lestcape** [comment]
Thats good, i see they are not save in utf-8, that will help to properly show it in cinnamon, also the same happened on nemo bookmarks.

**Comment by mtwebster** [comment]
ah right, i'll check bookmarks too
