### ISSUE TITLE
 Remember column width in list view

### ISSUE THREAD

**Issue by 1enn0** [linuxmint/nemo#786]
It seems to me that nemo resets the column widths in list view everytime you close and start the application again.
For example, if you use the standard configuration (Name / Size / Type / Date Modified), you will find four columns of (pretty much) equal width. If you increase the width for the "name" column and decrease the width of the "size" column and restart nemo afterwards, you are back to 4 equal-width-columns. 
Especially on smaller screens (and when working with somewhat long filenames) it is kind of a pain to have to change this everytime by hand. 
Have I just not found the right button to click, or is this feature not implemented yet?

**Comment by Vahan86** [comment]
The issue is still existing in Nemo 3.0.6.

**Comment by Vahan86** [comment]
@JosephMcc, Issue #626.
