### ISSUE TITLE
strftime datetime display options

### ISSUE THREAD

**Issue by simonzack** [linuxmint/nemo#788]
It would be nice to allow for `strftime` datetime options instead of the default 3. This is far more flexible and done by a lot of linux applications.

Say I could specify `%M:%H` to display the minute and hour with everything else stripped.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
