### ISSUE TITLE
Nemo Hangs When Opening Certain Folders in 17.1

### ISSUE THREAD

**Issue by kendoori** [linuxmint/nemo#789]
I'm trying to open some folders off of my home/document tree and have discovered that certain folders will hang upon opening (they just have standard documents in there... PDfs, .XLS etc...) This problem is Nemo specific, as I'm able to open the same folder with no issues in Thunar or Double Commander.

What I see on my screen is the equivalent of the hourglass (I don't know what you call it in Mint) just churning away. I have to killall to get back running...

I've tried moving and renaming the folder to no avail.

**Comment by tjankov** [comment]
I also have issue with nemo freezing.
Nothing but the killall (when I manage to get to terminal) fixes the issue.

top shows that it takes over the CPU, practically.

**Comment by Vahan86** [comment]
@kendoori, is this still an issue for you in Nemo 3.0.6?

**Comment by kendoori** [comment]
@Vahan86 am now running 17.3 w/stock Nemo 2.8.7. No issues.

**Comment by Vahan86** [comment]
@kendoori, thanks for reply. In this case can you please close the issue?
