### ISSUE TITLE
opening trash causes a crash

### ISSUE THREAD

**Issue by hermann-san** [linuxmint/nemo#792]
for some reason nemo is crashing when I click on the trash symbol.  At first it takes a little time ( I guess for searching) and then the results comes up for a second and then Nemo is crashing.
I don't know if it's usefull to you but I've seen people posting debugging info of gdb, so I thought it might help.....

Mint 17 64bit , Cinnamon
Cinnamon 2.2.16
3.13.0-24-generic kernel 
Nemo 2.2.4

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nemo...Reading symbols from /usr/lib/debug//usr/bin/nemo...done.
done.

(gdb) run
Starting program: /usr/bin/nemo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffedb06700 (LWP 24274)]
[New Thread 0x7fffed305700 (LWP 24275)]
[New Thread 0x7fffecb04700 (LWP 24276)]
[New Thread 0x7fffe7fff700 (LWP 24277)]
[New Thread 0x7fffe71d2700 (LWP 24278)]
[New Thread 0x7fffe5f0f700 (LWP 24279)]
[New Thread 0x7fffe570e700 (LWP 24280)]
[New Thread 0x7fffe4f0d700 (LWP 24281)]
blah
blah
[New Thread 0x7fffcedf8700 (LWP 24283)]
[New Thread 0x7fffce5f7700 (LWP 24286)]
[New Thread 0x7fffcddf6700 (LWP 24287)]
[New Thread 0x7fffcd5f5700 (LWP 24288)]
[New Thread 0x7fffccdf4700 (LWP 24289)]
[Thread 0x7fffce5f7700 (LWP 24286) exited]
[Thread 0x7fffcddf6700 (LWP 24287) exited]
[Thread 0x7fffe5f0f700 (LWP 24279) exited]
[Thread 0x7fffccdf4700 (LWP 24289) exited]
[Thread 0x7fffe4f0d700 (LWP 24281) exited]
[Thread 0x7fffcd5f5700 (LWP 24288) exited]
[Thread 0x7fffcedf8700 (LWP 24283) exited]
[Thread 0x7fffecb04700 (LWP 24276) exited]
[Thread 0x7fffed305700 (LWP 24275) exited]
[Thread 0x7fffe570e700 (LWP 24280) exited]

[New Thread 0x7fffe570e700 (LWP 24299)]
[New Thread 0x7fffed305700 (LWP 24300)]
[Thread 0x7fffed305700 (LWP 24300) exited]

(nemo:24273): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed
**
ERROR:nemo-file.c:661:nemo_file_get_internal: assertion failed: (location != NULL)

Program received signal SIGABRT, Aborted.
0x00007ffff41fdbb9 in raise () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by SusisStrolch1** [comment]
I've had issues with the trash as well, which were related to a strange directory name moved to the trash. 
drwxr-xr-x  2 name name     4096 Nov 23 21:35 _!'@!~@!u!'c!cg"v!'c!cg"h!#4!c!"m!#4!}g"v!'8!d!!u!%0!}@"p!'4=/

deleting it did the job for me. but i also had root files in my trash too, which i deleted before the strange directory.

[Thread 0x7fffcd7fe700 (LWP 5960) exited]
[New Thread 0x7fffcd7fe700 (LWP 5964)]

(nemo:5948): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed
**
ERROR:nemo-file.c:661:nemo_file_get_internal: assertion failed: (location != NULL)

Program received signal SIGABRT, Aborted.
0x00007ffff41fcbb9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) thread apply all bt

Thread 10 (Thread 0x7fffcd7fe700 (LWP 5964)):
#0  0x00007ffff45987ce in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50aece5 in g_cond_wait_until () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff50431c1 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5092862 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff5091f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff4594182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff42c0efd in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7fffcffff700 (LWP 5957)):
#0  0x00007ffff45987ce in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff50aece5 in g_cond_wait_until () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff50431c1 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5092862 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff5091f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff4594182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff42c0efd in clone () from /lib/x86_64-linux-gnu/libc.so.6

---Type <return> to continue, or q <return> to quit---

**Comment by rapgro** [comment]
Similiar issue here, the command rm -rf ~/.local/share/Trash/files/* fixed it somehow.

**Comment by justinseiter** [comment]
I had a file in ~/.local/share/Trash/files/ with a leading % character that caused the issue. Removing that single file allowed me to open the Trash folder in Nemo.

%home%justin%Sites%ata%public%css%style.css.swp

**Comment by pamindic** [comment]
I have this problem too. Opening the Trash can folder in Nemo crashes it. I've removed all the files in ~/.local/share/Trash but it hasn't cured the problem. Curiously, although the files are deleted, they still list briefly in Nemo for a split second before it crashes. There must be some other Nemo file thats holding a cache that needs clearing out.

**Comment by poserman** [comment]
Issue is still active on Linux Mint 17.3 with Nemo 2.8.6

**Comment by ArkosX** [comment]
Yeah, still happening. The issue is here that one notices when going to the trash, usually to recover something important...
So ok, the solution posted here (flushing the trash can from cmd), solves the problem of accessing the trash can, but doesn't solve the real problem: one wants to get something back from the can.
In other words it is a patch which only partially solves the problem.
IMO the solution would the trash (I guess the files explorer/Nemo) not to crash. It is funny that if the fileexplorer is ok with whatever file name, the trashcan is not. Where to report that then? (sorry, I am kind of lost, I am a newbie).
BTW, I didn't have any folder with % name, but files with % in the name. REmoved them and now it works: so it is not for directory names with % but any file with % as well

**Comment by poserman** [comment]
ArkosX, the solution indeed works. It's not really a solution indeed. It's only temporary
