### ISSUE TITLE
Widths of columns in Nemo do not match width of texts in the cells

### ISSUE THREAD

**Issue by hub2git** [linuxmint/nemo#796]
Linux Mint 17.1 Rebecca Cinnamon.

 Nemo always has Size column wider than necessary.   The size column is always wide. The name column is always narrow.

Why does Nemo always have a wide Size column, wider than it needs to be? There doesn't seem to be any reason for Nemo's choice of widths. How can I have size column wide enough for just a few characters (e.g. "500 bytes")? How can I get the Name column to be wider?

Using the current Nemo version (2.4.4).

![nemo_file_manager_columns](https://cloud.githubusercontent.com/assets/7141051/5513681/8d095be2-87b8-11e4-9c48-cb5c0cae3bcc.jpg)

**Comment by Vahan86** [comment]
@JosephMcc, Issue #626.
