### ISSUE TITLE
"open in terminal here" always opens terminal at ~

### ISSUE THREAD

**Issue by simonnagl** [linuxmint/nemo#797]
Problem: When I klick on "open terminal here" (I hope it is that string in English, I am using german) the terminal always opens at standard location ~. 
dconf-Configuration
org.cinnamon.desktop.applications.terminal exec="lilyterm"; exec-arg="-x"

Used Software:
Nemo 2.4.4-1
Cinnamon 2.4.5-1
LilyTerm 0.9.9

**Comment by RavetcoFX** [comment]
This appears to be an issue with lilyterm as it is not accepting a path as a command to start with (and open in that location) Please close this as it is not an issue with Nemo, and open in https://github.com/Tetralet/LilyTerm/issues

~Thanks

**Comment by simonnagl** [comment]
Thanks for your reply.
