### ISSUE TITLE
Nemo actions mishandling apostrophes

### ISSUE THREAD

**Issue by renderhead** [linuxmint/nemo#798]
Using Nemo 2.4.4 on Ubuntu 14.04:

When creating a nemo action that passes the current path / filename to a shell script or python script (%P, %F %N etc.), the action either fails, or passes incorrect output if the path / filename contains apostrophes.

I wrote an action that echoes %N to a text file, to try and see what was happening - with the following results:
- If the path contains an odd number of apostrophes (1, 3, 5...), the action appears to abort and nothing is echoed to the text file.
- If the path contains an even number of apostrophes (2, 4, 6...), the directory name is echoed to the text file, but with all of the apostrophes stripped-out.

Testing with %P, I get the following results:
- /media/Photos/2014-12-20-Bongo's big day -> (no output)
- /media/Photos/2014-12-20-B'ongo's big day -> /media/Photos/2014-12-20-Bongos big day
- /media/Photos/2014-12-20-B'ongo's 'big day -> (no output)
- /media/Photos/2014-12-20-B'ongo's 'big day' -> /media/Photos/2014-12-20-Bongos big\ day
- /media/Photos/2014-12-20-'Bongos big day' -> /media/Photos/2014-12-20-Bongos\ big\ day

There seems to be a bug with the escaping of apostropes - they are stripped out, and backslashes are added before spaces that were enclosed by the apostrophes (but not to spaces that were not enclosed)

The only similar issue I've managed to find here is a bug with apostrophes using "Open as root", from a couple of years ago:
https://github.com/linuxmint/nemo/issues/195

**Comment by icarter09** [comment]
@renderhead is this still an issue?
