### ISSUE TITLE
Allow for thumbnails greater than 4GB

### ISSUE THREAD

**Issue by xeriouxi** [linuxmint/nemo#799]
I have quite a few movies on my machine which are greater than 4GB in size and I noticed that Nemo doesn't allow me to go above this limit in order to create thumbnails.

I found a way of doing it via dconf but I imagine this would be quite hard to figure out for new users. Is there a way we could allow this to be configured within Nemo to allow >4GB file sizes?

**Comment by Vahan86** [comment]
Now Nemo can show thumbnails of files which are smaller than **8GB**: https://github.com/linuxmint/nemo/pull/801
@JosephMcc, can we close this issue?
