### ISSUE TITLE
Compress doesn't honor Location:

### ISSUE THREAD

**Issue by tylery71** [linuxmint/nemo#800]
Mint 17.1 Cinnamon, nemo 2.4.4

To reproduce:

In nemo right click and choose Compress
Change location: Any of the options besides "Other.."
It will create the file in the current directory 

However, it works if you choose "Other.." and specify a new directory.

**Comment by Vahan86** [comment]
@tylery71, is this still an issue for you in Nemo 3.0.6?

**Comment by tylery71** [comment]
@Vahan86, no it appears to of been fixed

```
nemo --version
nemo 3.0.6
```
