### ISSUE TITLE
Moving many files crashes nemo

### ISSUE THREAD

**Issue by abimelex** [linuxmint/nemo#806]
I have a folder with abouth 1000 pdf files, if I move them to another folder nemo seems to crash. Copying the same files is no problem.
Version 2.4.4 on Mint 17
Is there any way to provide more information? Or is the problem reproducable?

**Comment by Vahan86** [comment]
@abimelex, is this issue still relevant to Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
