### ISSUE TITLE
Select all doesn't work sometimes (nemo 2.4.4)

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/nemo#807]
Since Mint 17.1 it rarely happens that ctrl+a or the menu "select all" doesn't have any effect (Cinnamon 64 bit edition). Nemo is set to list view. Opening a "new" nemo works like it should. Don't know how to force or debug this.

**Comment by Vahan86** [comment]
@Mintulix, is this still an issue for you with Nemo 3.0.6?

**Comment by Mintulix** [comment]
@Vahan86, I don't think so. I totally forgot this one...
But I don't use ctrl+a very often, so I'm not sure. Can't reproduce it in this moment, so I will close it for now.

**Comment by Vahan86** [comment]
ok @Mintulix, thanks.
