### ISSUE TITLE
Need to update-alternatives for nautilus-connect-server to point to nemo-connect-server

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#808]
Various useful Gnome programs tend to assume that things are going to be called "nautilus-*", and Nemo results in functions silently failing if you're not running in command line mode with them.

One of these is `nautilus-connect-server`, depended on by `baobab` (Disk Space Analyzer) to handle it's remote folder functionality. To fix this manually, you can run

``` bash
sudo update-alternatives --install /usr/bin/nautilus-connect-server nautilus-connect-server $(which nemo-connect-server) 1
```

Nemo should include this alternative in it's native packaging.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
