### ISSUE TITLE
Nemo 2.4 draws ugly borders around everything

### ISSUE THREAD

**Issue by xhsdf** [linuxmint/nemo#809]
Nemo 2.2:
![2015-01-02-165206_925x495_scrot](https://cloud.githubusercontent.com/assets/2945602/5597472/20372c38-92a3-11e4-87d0-6d39e22da827.png)

Nemo 2.4:
![2015-01-02-163725_925x495_scrot](https://cloud.githubusercontent.com/assets/2945602/5597468/1b21c348-92a3-11e4-8340-49ab3ee4f64c.png)

I'm using Nemo on Archlinux and no matter which theme, icons or GTK3 version I use I always get the same result.

**Comment by JosephMcc** [comment]
This isn't a bug. It was a style change in nemo 2.4.

**Comment by xhsdf** [comment]
Are you serious? It looked great before and they changed it to be ugly ON PURPOSE?! Did something happen?

**Comment by mtwebster** [comment]
Obviously that's your opinion.
