### ISSUE TITLE
Type-ahead box stays hidden

### ISSUE THREAD

**Issue by MaycneSonahoz** [linuxmint/nemo#811]
After opening Nemo, typing triggers the type-ahead feature and the box showing what's been typed is visible. But after navigating for some time, and quite often right after entering the first selected folder (by either double-clicking on it or hitting the Enter key), typing still triggers type-ahead, but the box stays hidden.
In this case, hitting Esc and typing again does not make the box show. Hitting Esc, refreshing (F5) the folder and typing again doesn't fix things either. So far, only closing Nemo and opening it again makes the box come back for some time.

My system is a Manjaro 0.8.11 (manjaro-system 20141220-1), using Cinnamon 2.4.5-1 and Nemo 2.4.4-1.
It's unlikely a driver issue since i have this on both my desktop (non-free Nvidia driver) and my laptop (free ATI driver). Changing kernel does not fix this either.

I haven't tried yet to revert Nemo to a previous version, in order to see when this occured first.

**Comment by MaycneSonahoz** [comment]
I downgraded Nemo several times, down to 2.0.8-3, and i still have the issue. I don't remember having encountered this issue this long ago, so it might come from another package, but which one?

I also failed to find logs for Nemo. If anyone can tell me where i should look, i'd appreciate it.

**Comment by Vahan86** [comment]
@MaycneSonahoz, does this issue still occur in Nemo 3.0.6?

**Comment by MaycneSonahoz** [comment]
@Vahan86 I got Nemo 3.2.0-2 and it seems running fine.
That being said, i haven't used Cinnamon for a long time, so this might not be relevant. If nobody else complains, it's as good as closed.

**Comment by Vahan86** [comment]
@MaycneSonahoz, thanks for your reply. In this case can you please close this issue?
