### ISSUE TITLE
Ignoring folder sticky bit

### ISSUE THREAD

**Issue by echotic** [linuxmint/nemo#813]
Hi!

When having a folder with the sticky bit set ( **chmod g+s** ) all subsequently created subfolders should inherit the attribute. This does happen when creating new folders, but not when copying an existing folder from a different location. The sticky bit is then discarded for the folder and all subfolders within. 
On the console ( **cp -r** ) this is done correctly and the sticky bit attribute is added to all folders. 

Echotic

**Comment by icarter09** [comment]
@echotic are you still experiencing this issue on the latest version of nemo?

**Comment by echotic** [comment]
I downloaded the latest Linux Mint 19.3 "Tricia" - Cinnamon (64-bit) and set it up as a kvm vm. I could not reproduce the previous behaviour: The sticky bit is not discarded anymore.

**Comment by icarter09** [comment]
@echotic thanks for the update.
