### ISSUE TITLE
[Feature Request] Focus: Switching via keyboard & visual indication

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#816]
I would like to have a way to switch focus between the folder column, the integrated terminal, possibly multiple, file views and maybe the menu bar. 

I would also prefer to have some visual indication for said focus, as, especially with the terminal, focus behaviour does not always seem consistent to me. But that might be a gui-theme thing.

Edit: When opening the integrated terminal with F4 the focus seems to be nowhere at all, at least typing text does not do anything at all.

**Comment by tp0** [comment]
+1

**Comment by eiriklade** [comment]
+1

**Comment by jerkey** [comment]
+1

**Comment by Dukuu-Wild** [comment]
Three issues that ask almost the same, and 1,5 years of freezzzz... +1, just add that setting!

**Comment by vstepaniuk** [comment]
+1

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Mintaka** [comment]
LinuxMint 20. 
Nemo 4.6.5
Still not working properly.

My AutoIT workaround script
binding on hotkey F3 

-----------
# Script on F3 hotkey in Nemo
# Do F3 and focus panel by refreshing it (F5)
# Made as workaround nemo pane switching bug

import time

winClass = window.get_active_class()
if winClass == "nemo.Nemo":
    keyboard.send_key("<f3>") 
    time.sleep(0.1)
    keyboard.send_key("<f5>")
