### ISSUE TITLE
Integrated terminal opens/closes on Alt+F4 for above window

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#817]
Whenever I close a window via Alt+F4 and Nemo happens to be the next window in focus, th integrated terminal will open or close.

**Comment by anandrkris** [comment]
I suppose, should be filed here https://github.com/linuxmint/nemo-extensions/issues

**Comment by HifeFish** [comment]
You are right, sorry about that, I will file the issue there.
It does seem to recognize the Alt key. If I deliberately keep Alt+F4 pressed down, Nemo will just close. I am probably unwittingly releasing Alt before F4.
