### ISSUE TITLE
nemo hangs onto memory when closing windows if managing the desktop

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#820]
Nemo naturally uses memory while viewing and working with files.  The usage can be quite large if there are a lot of files.  When closing the nemo windows this memory is not released if nemo is managing the desktop icons.  If you change the settings so that nemo is not showing desktop icons then the memory is released when exiting (all the) nemo windows, and the nemo process then appears to exit.

If the memory associated with the file management windows could be released when closing (the last) windows, even if nemo was still managing the desktop icons, then that would be better as it would avoid holding onto memory that is no longer needed for file management work.

Nemo 2.4.4, running in mint 17.1

**Comment by Vahan86** [comment]
@brownsr, is this still an issue for you with Nemo 3.2?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
