### ISSUE TITLE
Nemo fails to build its package on Debian Testing

### ISSUE THREAD

**Issue by kjfergu** [linuxmint/nemo#824]
Hello,

When attempting to build Nemo under Debian Testing, the build will fail during the packaging step.

Just to be clear - Nemo itself builds successfully (I.E - ./autogen.sh, ./configure, make is successful). The failed step is when dpkg-buildpackage takes over to construct the .deb.

Unfortunately, I don't have the line itself anymore but the essence is that it failed to find the component that should be located at

```
./debian/tmp/usr/lib/girepository-1.0/Nemo-3.0.typelib
```

Which is referred to by the file "./debian/gir1.2-nemo-3.0.install".

After a bit of digging, it turns out that the file in question (Nemo-3.0.typelib) actually ends up in

```
./debian/tmp/usr/lib/x86_64-linux-gnu/girepository-1.0/Nemo-3.0.typelib
```

and changing the path in "./debian/gir1.2-nemo-3.0.install" to reflect this allows the build to complete successfully.

**Comment by GLolol** [comment]
GLolol@8756fbbd8336be741c0930a12745f9720a9f5560 fixes this, though most likely in a backwards-incompatible way. The Debian packagers for Cinnamon were also hit by this ([source](http://bugs.debian.org/762837)), as far as I can tell.

**Comment by kjfergu** [comment]
I believe you are correct. I am unable to try building with that change right now, but I can't imagine it won't work.

Does dpkg-buildpackage (or whatever tool it's running at the time) have access to the standard environment variables (and do expansion)? A safer change might be 

    usr/lib/$(DEB_HOST_MULTIARCH)/girepository-1.0/nemo-3.0.typelib

which I think would still work if that variable is unset, which would avoid breaking backwards compatibility.

**Comment by GLolol** [comment]
I tried that, but unfortunately it seems the `.install` files won't expand variables.

**Comment by cpatrick08** [comment]
can confirm changing the file builds nemo 2.5.1 on fully up to date LMDE Betsy

**Comment by icarter09** [comment]
@kjfergu are you still experiencing this issue with the latest version of nemo?

**Comment by kjfergu** [comment]
I've honestly moved away from what I was working on at the time I filed this, so I can say I'm not experiencing this - but only because I'm not doing anything with it at all :)

I'll go ahead and close this since it seems that it was fixed according to @cpatrick08
