### ISSUE TITLE
Video thumbnails blurry when zooming in

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/nemo#825]
When the view zoom level is set to max (icon view for instance), video thumbnails are blurry.

It's probably not directly related to nemo, but to totem-thumbnailer instead... in any case, it's easier to track here on nemo's github repo.

**Comment by MySchizoBuddy** [comment]
pdf thumbnails are also blurry at max zoom. Note that the zoom slider in nemo has no text output so it's impossible to know what the current zoom level is.

**Comment by icarter09** [comment]
@clefebvre any update on this ticket?

**Comment by icarter09** [comment]
@MySchizoBuddy are you still experiencing this issue on the latest version of nemo?
