### ISSUE TITLE
[Strange Behavior] Line continuation in icon view compact layout

### ISSUE THREAD

**Issue by joe1970** [linuxmint/nemo#828]
Hi, 
I like nemo a lot. it is a pretty decent file manager except one thing that drives me crazy:
I use icon view arranged with compact layout. The icons are not arranged in a fixed grid, but they fill up lines according to their width until the line is full. This is great so far. The problem comes when browsing through the files using the arrow keys on the keyboard. For example when I use the right key and hit the end of a line, I would expect that it jumps to the first element in the following line. This sometimes works as expected and sometimes it jumps to the first element in a completely different line further down. I somehow feel that this happens when it leaves a line that happens to contain more elements than the others. 
If the first element of a line of icons is highlighted and I hit the left button, it always goes to the last element of the previous line. If i then hit the right button it sometimes does not go back to the first element of the previous line. 
Sonething similar also happens when using the down button. Sometimes it does not lead to highlight an element of the next line, but it skips a line. 
If all icons in the folder have the same width and therefore it all looks like arranged in a grid, this does not seem to happen.
It all looks like the the algorithm that figures out the next element to jump to and highlight when using the arrow buttons leads to quite unintuitive results. I would propose to change that to a more intuitively predictable behavior. 

I user Nemo Version 2.4.5 on Ubuntu 14.10 with latest updates. The described behavior is however not new. I have also experienced this when trying Nemo on Ubuntu 14.04.

best regards, Jorg

**Comment by joe1970** [comment]
Another observation: sometimes when using the up button it does not go one line up although there is another line of files above.

**Comment by icarter09** [comment]
@joe1970 are you still experiencing this issue?
