### ISSUE TITLE
Nemo doesn't display file name properly when renaming

### ISSUE THREAD

**Issue by jeychenne** [linuxmint/nemo#829]
Using Linux 17.1 64 bit with cinnamon, using French language with fr_FR.UTF-8 and AZERTY keyboard, nemo 2.4.5.

1) Run nemo, right click to create a new file or directory or rename an existing one. 

2) Press the shift key and one or more upper case letter(s), release the shift key and write more characters, so far so good. Now press the shift key again to enter an upper case or punctuation symbol requiring the shift key: characters are no longer displayed, even if you release the shift key. 

3) When you press enter, the file is correctly named, including the characters that were not properly displayed. 

This bug is always reproducible as far as I can tell.

**Comment by Vahan86** [comment]
@jeychenne, is this issue still relevant to Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by jeychenne** [comment]
@Vahan86  I am currently using Mint 19 (with Nemo 3.8.5) and I can confirm that the bug is still there.
