### ISSUE TITLE
Feature request: Sort folders before files hotkey/checkbox in view menu

### ISSUE THREAD

**Issue by punik** [linuxmint/nemo#830]
Hi, 
it will be nice to quickly change nemo's "Sort folders before files" behavior by placing this option into "view" menu or / and assign a hotkey for that (like F3 toggles single/dual pane view)

**Comment by Lirein** [comment]
This feature must be changed globally (as current feature works) and may applyed to individual folders too, for example with creating some filder flag or meta info (such as .hidden file). Ideally - have remembered option in View menu.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
