### ISSUE TITLE
Setting for default connect-server method

### ISSUE THREAD

**Issue by JacekPliszka** [linuxmint/nemo#831]
I often use connect to server feature and I always use SFTP.

I would love to be able to tweak it with gsettings.

Currently in nemo-connect-server-dialog.c there is:

static struct MethodInfo methods[] = {
	/* FIXME: we need to alias ssh to sftp */
	{ "sftp",  SHOW_PORT | SHOW_USER, 22 },
	{ "ftp",  SHOW_PORT | SHOW_USER, 21 },
	{ "ftp",  DEFAULT_METHOD | IS_ANONYMOUS | SHOW_PORT, 21 },
	{ "smb",  SHOW_SHARE | SHOW_USER | SHOW_DOMAIN, 0 },
	{ "dav",  SHOW_PORT | SHOW_USER, 80 },
	/* FIXME: hrm, shouldn't it work? */
	{ "davs", SHOW_PORT | SHOW_USER, 443 },
};

I would like to have gettings entry like 
NEMO_DEFAULT_CONNECT_SERVER_METHOD that could be set to 0,1,2 or other with gesttings and then the coresponding method would be the default one.

**Comment by mtompkins** [comment]
+1

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/47a29bd03dceec8f49507d2dd4d2f9148185a7f2

It's not exactly what's requested here, but it amounts to more or less the same thing, without having to add another setting.

**Comment by JacekPliszka** [comment]
Thank you very much! It is even better than what I suggested.
