### ISSUE TITLE
Nemo tabs + Search

### ISSUE THREAD

**Issue by thorsummoner** [linuxmint/nemo#834]
Steps to reproduce weirdness:
1. Open a directory and use the Nemo search to look for anything (In my case I had results, if that matters)
2. Open a new nemo tab (<kbd>ctrl</kbd>+<kbd>t</kbd> for me)
3. Select the first tab that had search results, the search bar comes back
4. Select the second tab that should not have search results. 

The search results stay on screen and the search button no longer indicates that search is open on the first tab.

Version: Nemo 2.4.4

**Comment by Vahan86** [comment]
Can't reproduce the issue. 
@thorsummoner, is this issue still relevant to Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
