### ISSUE TITLE
Nemo crashing on generating preview for seemingly-random picture

### ISSUE THREAD

**Issue by kupiakos** [linuxmint/nemo#836]
When previews are enabled, Nemo crashes while trying to generate the preview for [this SVG](https://dl.dropboxusercontent.com/u/48007253/Word%20Log.svg).

**Comment by stovocor** [comment]
This segfault happens with other SVG files, too, like [this one](https://openclipart.org/download/11059/sampler-Users-5.svg). The crash looks like this:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe02a1700 (LWP 6717)]
0x00007ffff086df9b in ?? () from /usr/lib/libfreetype.so
```

According to [this bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1084746) the error only occurs when using the freeype library from http://www.infinality.net/.

**Comment by Vahan86** [comment]
@kupiakos, @stovocor, is this still an issue for you with Nemo 3.0.6?

**Comment by stovocor** [comment]
@Vahan86 No, Nemo 3.0.6 renders the preview without crashing.
