### ISSUE TITLE
Nemo has duplicate folders

### ISSUE THREAD

**Issue by Doowon** [linuxmint/nemo#837]
When I download something from the Internet in Chrome, I am asked to select a specific folder to download. When I create a new folder where I want to download the file, and then open the new folder, but there is still the duplicate new folder there. I guess this is a minor bug.

 My nemo version is 2.4.5 and Linux 17.1

**Comment by Vahan86** [comment]
@Doowon, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
