### ISSUE TITLE
How to share a folder?

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/nemo#84]
I'm running Cinnamon with nemo and I'm not able to share a folder so another Ubuntu user can access it by clicking network in the nemo sidebar... I've installed samba and libpam-smbpass and restarted the whole machine for making sure all needed services are started.

**Comment by Vahan86** [comment]
Nemo-share extension is available by default in Nemo.
@dtrunk90, is this still an issue for you with Nemo 3.0.6?

**Comment by dtrunk90** [comment]
I needed to install `nemo-share` package manually in Ubuntu but now I'm having a nice GUI for sharing stuff in the network.
