### ISSUE TITLE
Allow actions to set environment variables/working directory

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/nemo#841]
In trying to create an iPython shell launcher, I got stuck trying to set the working directory of iPython when it opens to the current Nemo directory. The basic problem is you can't ask Nemo to set the environment or working directory of the spawned process.

Adding some syntax to allow this would make action writing a lot easier.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
