### ISSUE TITLE
Nemo crashes when unmounting a currently open FTP connection

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/nemo#843]
I often connect to FTP servers using Nemo, as this makes it very easy to change website code. However, often Nemo crashes when I close the FTP connection by clicking on the eject button next to the FTP root in the Network section of the left bar.

This happens when a FTP directory is still opened when clicking Eject. If I only have tabs open, which show a local directory, Nemo stays open after disconnecting the FTP server. Also, the Nemo background process crashes when closing a connection, of which there is still an open window, making my desktop icons disappear until I start Nemo again.

Whenever this happens, Nemo exits silently. I can't find any error messages etc. in dmesg or any log files.

Nemo 2.4.5

**Comment by FormidableInc** [comment]
Hello. It's still true as of today. Not only FTP but SSH/WebDav/Samba also. I did not see if it's linked to inactivity. It's really annoying. No trace in logs.

**Comment by Vahan86** [comment]
@theSeppi, @FormidableInc, is this still an issue for you with Nemo 3.0.6?

**Comment by theSeppi** [comment]
Can't tell for 3.0.6, but it doesn't occur in Nemo 3.2.0

**Comment by Vahan86** [comment]
@theSeppi, thanks for your reply. In this case can you please close the issue?
