### ISSUE TITLE
Too big icons in context menu

### ISSUE THREAD

**Issue by Ph1b** [linuxmint/nemo#844]
Im using nemo 2.4.5 on Arch Linux 3.18.6-1 with the [moka-icon-pack](https://aur.archlinux.org/packages/moka-icon-theme-git/). 

But nemo does not scale images correctly. Imo it should automatically scale the images, even if they are too big like in the attached screenshot.

![bildschirmfoto vom 2015-02-23 11 55 36](https://cloud.githubusercontent.com/assets/743462/6326552/2aeea2e0-bb53-11e4-96db-e08e8b8ee9a9.png)

**Comment by ManIVIctorious** [comment]
Technically this is neither a bug, nor has it to do anything with nemo. In newer versions of gtk the size restrictions of the icon theme get honored, before this change the icons got resized till they fitted.

So this is a change in gtk and the icon-theme developers have to adjust their themes to the new behaviour.
