### ISSUE TITLE
theme and icons fail to load

### ISSUE THREAD

**Issue by mwaterbu** [linuxmint/nemo#847]
Sometimes when running Linux Mint 17 Cinnamon, the theme for Nemo will not correctly load, leaving Nemo will old, ugly looking icons. When this happens, Nemo will still load the correct theme as su (see picture below), but the only way I am able to get a normal user to see the correct theme is to killall nemo.
![2015-02-28](https://cloud.githubusercontent.com/assets/11249060/6427924/2930d730-bf5d-11e4-8b25-de7d3d8d5d66.png)

**Comment by hyOzd** [comment]
Same thing is happening to me. It seems to start suddenly. Only solution I could find is to stop nemo with, `nemo -q` command. But it's the same after a restart.

**Comment by leigh123linux** [comment]
Does running this command restore the theme?

```
/usr/bin/cinnamon-settings-daemon
```

**Comment by hyOzd** [comment]
No it doesn't. Daemon is already running. Here is the output of the command `cinnamon-settings-daemon`

```
** (cinnamon-settings-daemon:2778): WARNING **: You can only run one xsettings manager at a time; exiting

** (cinnamon-settings-daemon:2778): WARNING **: Unable to start xsettings manager: Could not initialize xsettings manager.

** (cinnamon-settings-daemon:2778): WARNING **: Name taken or bus went away - shutting down

** (cinnamon-settings-daemon:2778): WARNING **: Name taken or bus went away - shutting down
```

But there is more. I have noticed this is not the only issue I'm having. I have an applet on my cinnamon panel which allows me to control LCD brightness. On startup this applet doesn't work. It says "Brightness not available". But if I restart cinnamon, it starts working! There are these lines at the beginning of looking-glass log:

```
warning t=1970-01-01T02:00:00Z ================ DBus connection lost ===============
info t=1970-01-01T02:00:00Z ================ DBus connection established ===============
```

Also when nemo displays the desktop on startup, it has black background. Wallpaper comes a couple seconds later.

Maybe this settings daemon is starting too late, or failing to start, restarting.. Should I file a bug report somewhere else? Please advise.

**Comment by Vahan86** [comment]
@mwaterbu, is this still an issue for you with Nemo 3.0.6 (Mint 18)?

**Comment by mwaterbu** [comment]
This issue has not reoccurred for me in quite some time. I am OK with this
being closed. However, I am still running Mint 17.3 with Nemo 2.8.7.

**Comment by Vahan86** [comment]
@mwaterbu, thanks for reply. In this case can you please close the issue?
