### ISSUE TITLE
nemo-scripts on network shares

### ISSUE THREAD

**Issue by kaefert** [linuxmint/nemo#849]
When executed on a network share (automounted through entering a smb:// or sftp:// uri in nemo)
the selected file paths which you locally find in either $@ or $NEMO_SCRIPT_SELECTED_FILE_PATHS 

Are empty. I found that the URIs of the files are in the variable $NEMO_SCRIPT_SELECTED_URIS and the directory path can be acquired by calling `pwd`.

So to make a nemo-script work on a network share the same as locally it currently would need to substring the filenames out of the URIs and join it together with the output of pwd.

for more details see also this forum post:
http://forums.linuxmint.com/viewtopic.php?f=208&t=190954

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
