### ISSUE TITLE
Trouble entering unreadable directory

### ISSUE THREAD

**Issue by autarkper** [linuxmint/nemo#85]
Steps to reproduce (current master):
1) Navigate to a directory that contains a directory to which you don't have read access.
2) Try to enter that directory.

Result: Nemo throws up a modal dialog: "The folder contents could not be displayed.", and the toolbar says: "Loading...", with a spinner. When you dismiss the dialog, the spinner keeps spinning until you stop it.
Expected result: Nemo should show a non-modal banner to the same effect, and the toolbar should stop being silly.

**Comment by Vahan86** [comment]
@autarkper, is this still an issue for you in Nemo 3.0.6?

**Comment by autarkper** [comment]
@Vahan86: I'm sorry I can't tell, as I am still on version 2.6.5.

**Comment by MrElectroNick** [comment]
@Vahan86 @autarkper - Not an issue in 2.8.7
