### ISSUE TITLE
Transparency of icons in menus

### ISSUE THREAD

**Issue by azjio** [linuxmint/nemo#850]
Nemo 2.4.4
Fedora 20 (DE Cinnamon)

Transparent pixels become gray.
http://s019.radikal.ru/i644/1503/29/3c6b1309e10a.png

**Comment by Vahan86** [comment]
@azjio, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
