### ISSUE TITLE
Mask for the name of the new document and template

### ISSUE THREAD

**Issue by azjio** [linuxmint/nemo#853]
Add the mask settings for the new document and template.
If empty, the default mask. If is specified, for example:
"%def %n" = "new document 1"
"file %n" = "file 1
"file" = "file" (when re-creating that will give the file already exists.
I often use the name "z_1", "z_2", so that new files have been at the end of the list, as long as they are not defined by a name.
You say to enable sorting by date. However, this option will sort all files, not just the new ones.
Theoretically I'm not hard to enter the name, but it's better to immediately press Enter.

Templates also have the disadvantage. On the left is the prefix, in the center - the name of the template, and the right - number. Need to clean all this every time (left and right).

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
