### ISSUE TITLE
sftp bookmarks don't show up in bookmarks menu.

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#854]
Bookmarks to sftp folders do not show up in the bookmarks menu in Nemo 2.4.5.

**Comment by melsophos** [comment]
I confirm this issue which is quite annoying (and present for several months). This occurs for any non-local bookmark (SFTP, FTP).
They are not accessible through the "Bookmarks" menu at the top of Nemo, but they are through the small icon "Display tree" at bottom (I am translating from french, so not sure what is the english version). They do not appear either in the menus open/save, but as soon as a distant connection is established then the corresponding entry appear (but only in save/open, not in Nemo itself).
I checked on a old version of the system and Nemo 2.0.8 was working well for this.
