### ISSUE TITLE
[bug] Nemo crash caused SSH folder to become disfunctional

### ISSUE THREAD

**Issue by tamis-laan** [linuxmint/nemo#855]
I am a linux mint user and i use nemo(2.2.4) aswel to work on remote files through SSH. However nemo froze. After i killed nemo the SSH folder won't open any more returning a error message saying the folder could not be mounted. 

After removing the folder and adding it again through file->connect to server... a new error message appears saying:

Could not display [folder]
The location is not a folder.

Is there someway to quick fix to this problem? For example can i deleate nemo's cash or prefrence folders?

**Comment by Vahan86** [comment]
@tamis-laan, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
