### ISSUE TITLE
Display 'cd' accessible path to mtp device in Nemo

### ISSUE THREAD

**Issue by janot** [linuxmint/nemo#856]
Nemo displays path to mtp device like that:

`mtp://[usb:001,007]/`
I think, it would be quite comfortable to be able to copy path from Nemo to terminal and cd there. Currently I have to do it this way:

 `cd /run/user/1000/gvfs/mtp:host=%5Busb%3A001%2C007%5D`

**Comment by KOLEGA007** [comment]
I think, that actuall type of path is clear, that it is remote dir and If you really want to go there with terminal, you will find your way ... And is clear what for device is that

**Comment by abdupattoh** [comment]
I agree with janot - I have been frustrated before trying to figure out how to use a shell to access an mtp device, and NEMO pops up in front showing the device with an "unusable" path.  It is good normal to be able to copy and paste paths from file managers across OS's.

**Comment by leigh123linux** [comment]
gvfs handles mtp mounts not nemo,
