### ISSUE TITLE
Cache search results so you can go back without searching again

### ISSUE THREAD

**Issue by pan100** [linuxmint/nemo#859]
I use v 2.4.4, I don't know if this is done in latest/later versions but I feel, since searching the file system takes a long time even on a nearly clean install, it would be good if you could cache the search results so that if one enters a folder and then goes back, the search result is still there. One can argue that the user might have changed files or folders so that the search result is no longer valid when the user goes back, but this can be solved by adding a notification popover of some kind, for instance just a line at the top of the folder view with the message "note: this search result might be out of date" with a "refresh button

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
