### ISSUE TITLE
Rotate image with Orientation EXIF tag not with image conversion

### ISSUE THREAD

**Issue by pvdl** [linuxmint/nemo#861]
Is it possible to rotate an image with the Orientation meta tag in stead of doing a image conversion.
Info:
http://sylvana.net/jpegcrop/exif_orientation.html
http://www.impulseadventure.com/photo/exif-orientation.html
http://www.sno.phy.queensu.ca/~phil/exiftool/exiftool_pod.html
Search for orientation

It is quicker and there is no loss of image quality.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
