### ISSUE TITLE
User would like facility to have nemo not manage mtp media files, so Banshee can do it

### ISSUE THREAD

**Issue by brownsr** [linuxmint/nemo#862]
User is trying to have banshee manage mtp media files from his android phone.  Says he is unable to do this as nemo is mounting and managing these files and conflicting with Banshee

http://askubuntu.com/questions/529477/14-04-cannot-create-delete-manipulate-files-on-my-android-device-via-usb

I do not have an android phone so am unable to test or confirm the report in any way.

**Comment by icarter09** [comment]
@brownsr any update on this ticket?

**Comment by brownsr** [comment]
I was reporting it on someone else's behalf. It's old now. I'd close it and see if it is reported again on a more recent version.
