### ISSUE TITLE
Nemo desktop icons wrong spacing

### ISSUE THREAD

**Issue by artscoop** [linuxmint/nemo#865]
Found something odd on the desktop icons. Let me just show you with 2 images:
First, when the .txt file has a short name and you order by name, icons are aligned perfectly (icons are displayed with a 150% zoom)
![nemo-1](https://cloud.githubusercontent.com/assets/1023091/6843892/4c379a8a-d3a7-11e4-96f2-23c9f43a8dd3.png)
Then I inflated the .txt filename artificially. The filename is wrapped under the document icon, yet when I order by name, the icon spacing goes wrong.
![nemo-2](https://cloud.githubusercontent.com/assets/1023091/6843932/a551e562-d3a7-11e4-8001-2e9693fbf47e.png)
I don't really mind having the desktop share the same settings as the browser (same zoom level) but this, I think this is a bug.

**Comment by Vahan86** [comment]
@artscoop, is this still an issue for you with Nemo 3.0.6?

**Comment by JosephMcc** [comment]
I'm just going to mark this as a bug. At some point I think there are plans to rework the layout of the nemo desktop window which will hopefully address all of these related issues.

**Comment by artscoop** [comment]
I've quit using Cinnamon (but still use Nemo), so I cannot tell if the behaviour still exists. But I suspect it's been fixed

**Comment by JosephMcc** [comment]
Alright, closing this.
