### ISSUE TITLE
Change the selection function when typing part of the name of a file

### ISSUE THREAD

**Issue by damaru2** [linuxmint/nemo#868]
If you type part of the beginning of a file name located in the current folder, it selects, like many other file managers, the file whose name matchs with what you type, or the first of them if there are many. For example if I have these four files in the current folder:

14Exam.pdf

Problem1.pdf

Problem2.pdf

Solution.pdf

and I start typing "Pro", then the file "Problem1.pdf" gets selected. If I type "14" instead, then 14Exam.pdf is selected and so on. 
But I miss an extra functionality. When I type some characters, and if those doesn't match with the beginning of a file, I would like nemo to search in the middle of the files and select the file which contains the characters I typed as a substring.

In the example mention above, I may have a lot of files and I want to search the exam file but It starts by "14" and I don't remember, so I want nemo to select the "14Exam.pdf" file when I type "Exam".

Another example: If I have a lot of files named "ProblemX.pdf" where X is a number, is difficult and slow for me to type "ProblemX" in order to select the file. With the extra functionality I mentioned, I could type "mX" and "ProblemX.pdf" would be selected.

Is there any way I could add this functionality to nemo? I don't know if there exists a plugin or so. In case not, Is there any way I could implement something like this?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
