### ISSUE TITLE
Desktop - Context Menu - Sort by Size, FIletype, etc

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#869]
At the moment only Organize desktop by Name is available under Desktop > Context Menu. 
Request to add other sort capabilities like Arrange by Size, Manually, Date, etc that are available in other folder views.
![desktop_context_menu](https://cloud.githubusercontent.com/assets/4663298/7005663/d8b3e10a-dc97-11e4-85f8-df05524ad3e9.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by leigh123linux** [comment]
This has been fixed in nemo-4.x.x
