### ISSUE TITLE
Nemo spawns desktop upon xrandr use, in spite of --no-desktop flag

### ISSUE THREAD

**Issue by dougmercer** [linuxmint/nemo#870]
Recently I've been tinkering with i3wm on a laptop I have typically used Mint/Cinnamon on.

Although Nemo initially behaves just fine when launched using the --no-desktop flag, I've found that Nemo exhibits some weird behavior when used in conjunction with xrandr (to accommodate multiple displays).

When I swap between using single or multi-monitor setups, nemo shows the desktop. As an example, this (xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --right-of $INTERNAL_OUTPUT) is a command in the shell script I use to govern display state change.

 I've included some images (as well as a screenfetch of my system) in the this imgur gallery (http://imgur.com/9qhKV1P,uOKg3gv,YdukWQ8).

If you have any questions, please let me know.

**Comment by xenopeek** [comment]
nemo-desktop is a separate process in current version of Nemo and only starts automatically when running a Cinnamon session. So we believe this is fixed
