### ISSUE TITLE
SCP options on remote server (with root because... sudo..)

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#874]
Random oddity encountered:

copying a large (8gb) items.tar file via a gui (because I'm feeling lazy today) using root (because I'm lazy), oddly has the following effect:

start copying the file to the local device

suddenly, I'm unable to see any items in the directory.

who knows.

**Comment by icarter09** [comment]
Closing this issue since the original submitter of this ticket is no longer present on Github.
