### ISSUE TITLE
Nemo segfaults (backtrace inside)

### ISSUE THREAD

**Issue by Almin17** [linuxmint/nemo#875]
Hey guys, 
if I start Nemo and click to open some of my directories (for instance 'Documents'), Nemo crashes.
It doesn't crash on all folders, just on some.
I could not found the reason or what properties those directories share (if there even are any).
I just realized, that it doesn't happen on Nautilus.
As I'm on Arch Linux using systemd I first looked into journald:

journalctl -xe gives me:
Apr 09 21:15:41 mypc kernel: nemo[8463]: segfault at ffffffffffffdfd8 ip 00007f5a0c7401ab sp 00007ffcccfaf7b0 error 7 in libexempi.so.3.2.4[7f5a0c6d7000+11b000]
Apr 09 21:15:41 mypc systemd-coredump[8493]: Process 8463 (nemo) of user 1000 dumped core.
-- Subject: Speicherabbild für Prozess 8463 (@COREDUMP_COMM) generiert
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
## -- Documentation: man:core(5)

-- Prozess 8463 (nemo) ist abgebrochen worden und
## -- ein Speicherabbild wurde generiert.

-- Üblicherweise ist dies ein Hinweis auf einen Programmfehler und sollte
-- als Fehler dem jeweiligen Hersteller gemeldet werden.

---

Sadly the output is in German and I don't know how to change it.
If there are any further ways to help you tracking down the problem, just let me know.

Additional info:
- I've got community/nemo 2.4.5-1 [Installed]
- I've got extra/exempi 2.2.2-1 [Installed]
- Linux mypc 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64 GNU/Linux

Steps to reproduce:
Basically execute Nemo and click on the Documents directory. (sorry for that weird reproducing step)

Btw, the above text is taken from a bug tracking ticket I opened at the the Arch Linux website:
https://bugs.archlinux.org/task/44513

Now I also tried to get a backtrace.

bt gives me:
(you can also watch it with nice syntax-highlighting:
http://pastebin.com/X460GqQ4
)
#0  0x00007ffff48b91ab in WXMPMeta_RegisterNamespace_1 () from /usr/lib/libexempi.so.3
#1  0x00007fffdaa69994 in TXMPMetastd::string::RegisterNamespace(char const_, char const_) () from /usr/lib/libexiv2.so.13
#2  0x00007fffdaa642f6 in Exiv2::XmpParser::initialize(void (_)(void_, bool), void*) () from /usr/lib/libexiv2.so.13
#3  0x00007fffdaa67038 in Exiv2::XmpParser::decode(Exiv2::XmpData&, std::string const&) () from /usr/lib/libexiv2.so.13
#4  0x00007fffda9cf646 in Exiv2::JpegBase::readMetadata() () from /usr/lib/libexiv2.so.13
#5  0x00007fffdb08a06a in exiv2wrapper::Image::readMetadata() () from /usr/lib/python2.7/site-packages/libexiv2python.so
#6  0x00007fffdb0970d6 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (exiv2wrapper::Image::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, exiv2wrapper::Image&> > >::operator()(_object_, _object_) () from /usr/lib/python2.7/site-packages/libexiv2python.so
#7  0x00007fffdadcf81d in boost::python::objects::function::call(_object_, _object_) const () from /usr/lib/libboost_python.so.1.57.0
#8  0x00007fffdadcfa38 in ?? () from /usr/lib/libboost_python.so.1.57.0
#9  0x00007fffdadd9783 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/libboost_python.so.1.57.0
#10 0x00007fffdb096e83 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Exiv2::BasicError<char>, void (_)(Exiv2::BasicError<char> const&)>, boost::_bi::list3boost::arg<1, boost::arg<2>, boost::_bi::value<void (_)(Exiv2::BasicError<char> const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/site-packages/libexiv2python.so
#11 0x00007fffdadd952d in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/libboost_python.so.1.57.0
#12 0x00007fffdadce219 in ?? () from /usr/lib/libboost_python.so.1.57.0
#13 0x00007fffe220e8c3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#14 0x00007fffe22a3c1c in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#15 0x00007fffe22a50ea in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#16 0x00007fffe22a6af0 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#17 0x00007fffe223352c in function_call () from /usr/lib/libpython2.7.so.1.0
#18 0x00007fffe220e8c3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#19 0x00007fffe221d7ad in instancemethod_call () from /usr/lib/libpython2.7.so.1.0
#20 0x00007fffe220e8c3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#21 0x00007fffe220e9a5 in call_function_tail () from /usr/lib/libpython2.7.so.1.0
#22 0x00007fffe220eca9 in PyObject_CallMethod () from /usr/lib/libpython2.7.so.1.0
#23 0x00007fffe2594fbc in ?? () from /usr/lib/nemo/extensions-3.0/libnemo-python.so
#24 0x00000000004c8f45 in extension_info_start (doing_io=<optimized out>, file=<optimized out>, directory=<optimized out>) at nemo-directory-async.c:4478
#25 start_or_stop_io (directory=0x1bbd4f0) at nemo-directory-async.c:4559
#26 0x00000000004cadc2 in nemo_directory_async_state_changed (directory=0x1bbd4f0) at nemo-directory-async.c:4590
#27 0x00000000004ced82 in thumbnail_done (tried_original=<optimized out>, pixbuf=0x1cdf400, file=0x176b770, directory=0x1bbd4f0) at nemo-directory-async.c:3786
#28 thumbnail_got_pixbuf (tried_original=<optimized out>, pixbuf=0x1cdf400, file=0x176b770, directory=0x1bbd4f0) at nemo-directory-async.c:3821
#29 thumbnail_read_callback (source_object=<optimized out>, res=<optimized out>, user_data=0x205d820) at nemo-directory-async.c:3955
#30 0x00007ffff53bf1a3 in ?? () from /usr/lib/libgio-2.0.so.0
#31 0x00007ffff53bf83e in ?? () from /usr/lib/libgio-2.0.so.0
#32 0x00007ffff537f258 in ?? () from /usr/lib/libgio-2.0.so.0
#33 0x00007ffff539970d in ?? () from /usr/lib/libgio-2.0.so.0
#34 0x00007ffff53bf1a3 in ?? () from /usr/lib/libgio-2.0.so.0
#35 0x00007ffff53bf1d9 in ?? () from /usr/lib/libgio-2.0.so.0
#36 0x00007ffff4e2490d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#37 0x00007ffff4e24ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#38 0x00007ffff4e24d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#39 0x00007ffff53e341c in g_application_run () from /usr/lib/libgio-2.0.so.0
#40 0x000000000042c7c9 in main (argc=1, argv=0x7fffffffe608) at nemo-main.c:101

and bt full gives me:
(again with nice syntax-highlighting:
http://pastebin.com/ML1nENr0
)
#0  0x00007ffff48b91ab in WXMPMeta_RegisterNamespace_1 () from /usr/lib/libexempi.so.3

No symbol table info available.
#1  0x00007fffdaa69994 in TXMPMetastd::string::RegisterNamespace(char const_, char const_) () from /usr/lib/libexiv2.so.13

No symbol table info available.
#2  0x00007fffdaa642f6 in Exiv2::XmpParser::initialize(void (_)(void_, bool), void*) () from /usr/lib/libexiv2.so.13

No symbol table info available.
#3  0x00007fffdaa67038 in Exiv2::XmpParser::decode(Exiv2::XmpData&, std::string const&) () from /usr/lib/libexiv2.so.13

No symbol table info available.
#4  0x00007fffda9cf646 in Exiv2::JpegBase::readMetadata() () from /usr/lib/libexiv2.so.13

No symbol table info available.
#5  0x00007fffdb08a06a in exiv2wrapper::Image::readMetadata() () from /usr/lib/python2.7/site-packages/libexiv2python.so

No symbol table info available.
#6  0x00007fffdb0970d6 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (exiv2wrapper::Image::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, exiv2wrapper::Image&> > >::operator()(_object_, _object_) () from /usr/lib/python2.7/site-packages/libexiv2python.so

No symbol table info available.
#7  0x00007fffdadcf81d in boost::python::objects::function::call(_object_, _object_) const () from /usr/lib/libboost_python.so.1.57.0

No symbol table info available.
#8  0x00007fffdadcfa38 in ?? () from /usr/lib/libboost_python.so.1.57.0

No symbol table info available.
#9  0x00007fffdadd9783 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/libboost_python.so.1.57.0

No symbol table info available.
#10 0x00007fffdb096e83 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Exiv2::BasicError<char>, void (_)(Exiv2::BasicError<char> const&)>, boost::_bi::list3boost::arg<1, boost::arg<2>, boost::_bi::value<void (_)(Exiv2::BasicError<char> const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/site-packages/libexiv2python.so

No symbol table info available.
#11 0x00007fffdadd952d in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/libboost_python.so.1.57.0

No symbol table info available.
#12 0x00007fffdadce219 in ?? () from /usr/lib/libboost_python.so.1.57.0

No symbol table info available.
#13 0x00007fffe220e8c3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#14 0x00007fffe22a3c1c in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#15 0x00007fffe22a50ea in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#16 0x00007fffe22a6af0 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#17 0x00007fffe223352c in function_call () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#18 0x00007fffe220e8c3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#19 0x00007fffe221d7ad in instancemethod_call () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#20 0x00007fffe220e8c3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#21 0x00007fffe220e9a5 in call_function_tail () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#22 0x00007fffe220eca9 in PyObject_CallMethod () from /usr/lib/libpython2.7.so.1.0

No symbol table info available.
#23 0x00007fffe2594fbc in ?? () from /usr/lib/nemo/extensions-3.0/libnemo-python.so

No symbol table info available.
#24 0x00000000004c8f45 in extension_info_start (doing_io=<optimized out>, file=<optimized out>, directory=<optimized out>) at nemo-directory-async.c:4478

```
    provider = 0x907400
    result = (NEMO_OPERATION_FAILED | unknown: 1397560856)
    handle = 0x0
    update_complete = 0x1d52e20
```
#25 start_or_stop_io (directory=0x1bbd4f0) at nemo-directory-async.c:4559

No locals.
#26 0x00000000004cadc2 in nemo_directory_async_state_changed (directory=0x1bbd4f0) at nemo-directory-async.c:4590

```
    directory = 0x1bbd4f0
```
#27 0x00000000004ced82 in thumbnail_done (tried_original=<optimized out>, pixbuf=0x1cdf400, file=0x176b770, directory=0x1bbd4f0) at nemo-directory-async.c:3786

```
    thumb_mtime_str = <optimized out>
    thumb_mtime = <optimized out>
```
#28 thumbnail_got_pixbuf (tried_original=<optimized out>, pixbuf=0x1cdf400, file=0x176b770, directory=0x1bbd4f0) at nemo-directory-async.c:3821

No locals.
---Type <return> to continue, or q <return> to quit---
#29 thumbnail_read_callback (source_object=<optimized out>, res=<optimized out>, user_data=0x205d820) at nemo-directory-async.c:3955

```
    state = 0x205d820
    file_size = 17161
    file_contents = 0x1e197c0 "\250\223\062\364\377\177"
    result = <optimized out>
    directory = 0x1bbd4f0
    pixbuf = <optimized out>
    location = <optimized out>
```
#30 0x00007ffff53bf1a3 in ?? () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#31 0x00007ffff53bf83e in ?? () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#32 0x00007ffff537f258 in ?? () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#33 0x00007ffff539970d in ?? () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#34 0x00007ffff53bf1a3 in ?? () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#35 0x00007ffff53bf1d9 in ?? () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#36 0x00007ffff4e2490d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0

No symbol table info available.
#37 0x00007ffff4e24ce0 in ?? () from /usr/lib/libglib-2.0.so.0

No symbol table info available.
#38 0x00007ffff4e24d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0

No symbol table info available.
#39 0x00007ffff53e341c in g_application_run () from /usr/lib/libgio-2.0.so.0

No symbol table info available.
#40 0x000000000042c7c9 in main (argc=1, argv=0x7fffffffe608) at nemo-main.c:101

```
    retval = <optimized out>
    application = 0x81e110
```

I would really like to hear some positive response. Maybe the problem might be caused by libexempi.
Just let me know if I might help you to further track down the problem.

**Comment by mtwebster** [comment]
Hi, what extensions do you have installed (just pacman list everything matching "nemo-")?

**Comment by Almin17** [comment]
In order to get both packages from the repository as well as from the AUR I used:
pacman -Qs nemo-
The output is:

local/nemo-emblems 2.4.3-1
    Nemo file emblems extension
local/nemo-fileroller 2.4.0-2
    File archiver extension for Nemo
local/nemo-media-columns 2.4.0-1
    Nemo extension to display music/EXIF and PDF metadata info
local/nemo-preview 2.4.0-2
    GtkClutter and Javascript-based quick previewer for Nemo
local/nemo-python 2.4.0-2
    Python2 binding for Nemo components
local/nemo-seahorse 2.4.0-2
    PGP encryption and signing extension for Nemo
local/nemo-share 2.4.0-2
    Samba extension for Nemo

**Comment by Almin17** [comment]
Hey guys, I've got some great news to track down the problem!
As a user in the Arch Linux Bug-Tracking-platform (György Balló (City-busz)) found out, the problem seems to be related to an extension: ''nemo-media-columns''
At least Nemo doesn't crash anymore for me after uninstalling it and restarting cinnamon.

**Comment by Daresch** [comment]
Same here. I got segfault if I try to go to a special folder. Removing the "nemo-media-columns" extension solved that problem for me, too.

Additional: This problem appears only in folders with JPG files, exported from Adobe Photoshop. If these pictures are in PNG format (exported form Adobe Photoshop), this problem doesn't appear.

**Comment by Vahan86** [comment]
@Almin17, is this issue still relevant to Nemo 3.0.6?

**Comment by JosephMcc** [comment]
Even if it is, it should probably be reported here: https://github.com/linuxmint/nemo-extensions
