### ISSUE TITLE
nemo does not open a new tab from a search result when right click -> 'open containing folder'

### ISSUE THREAD

**Issue by hansonap** [linuxmint/nemo#876]
After completing a search with nemo and right clicking and choosing 'open containing folder', the action is completed in the same tab.

This is an issue because many searches take much time, and almost always there are multiple locations you wish to open and explore, not just one.

I'd be interested in contributing to nemo with some guidance from the community if available.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by petermoo** [comment]
This is a problem for me too with Nemo 3.2.2.. The current search takes over a minute across terabytes. There are 16 folders to look at.

Open in new tab shows a new tab back at /home/me.
Open containing folder opens in same tab.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by atsag** [comment]
I still encounter this bug in Nemo v6.0.2
