### ISSUE TITLE
Copy and Paste stop working

### ISSUE THREAD

**Issue by fedy2** [linuxmint/nemo#878]
Often the Copy and Paste functionality stops working. To get it working again I have to kill Nemo. Really annoying.

**Comment by brouillon** [comment]
Same here, sometimes it silently fails.

**Comment by Vahan86** [comment]
@fedy2, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
