### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Alan01** [linuxmint/nemo#881]
In the sidebar of Nemo, Bookmarks is not translated. The other items (My Computer, Network etc.) are. It doesn't seem like Bookmarks is made translatable in Launchpad.

**Comment by to-ba** [comment]
I have the same problem with Nemo in:
Linux Mint 17.1 Rebecca
Linux Mint 17. Qiana

**Comment by to-ba** [comment]
It is fixed with the current translation file.

**Comment by Vahan86** [comment]
@Alan01, is this still an issue with Nemo 3.0.6?

**Comment by Alan01** [comment]
It has been fixed.
