### ISSUE TITLE
Reversed scroll direction in compact view

### ISSUE THREAD

**Issue by adam900710** [linuxmint/nemo#882]
When using compact view, the mid-button scroll direction is reversed.

Which means, when scroll down (finger from up to down), the view goes toward to first item.
That's completely different from list or icon view.

P.S: The version of nemo is 2.4.5

**Comment by Tofudrifter** [comment]
I noticed this after installing Ubuntu 15.04
Using the mouse wheel scrolling up scrolls right (Red) when mouse is hovered over directory and down goes left.
When the mouse is hovered over the scroll bar (Black) the scroll direction is correct when using scroll wheel.
![scrolling](https://cloud.githubusercontent.com/assets/12210105/7441304/1b8eb940-f125-11e4-80d3-634dece42649.jpg)

Installed Nemo from official repositories (2.2.4-2) and ran into this issue after switching to compact view.
Updated to the version on the Webupd8 PPA (2.4.5-2~webupd8~vivid2) and still encountered same issue.

**Comment by adam900710** [comment]
Yes, that's the same problem.

Quite annoying. And I didn't see any setting in dconf related to it, so it
should be a bug, not a new "feature".

Hopes some upstream developer can notice this.

2015-05-02 21:47 GMT+08:00 Tofudrifter <notifications@github.com>:

**Comment by Tofudrifter** [comment]
This was fixed a few months ago.

**Comment by JosephMcc** [comment]
This now seems to work as expected in nemo 2.8
