### ISSUE TITLE
Untrusted desktop launcher screen should allow opening the .desktop file in the default text editor

### ISSUE THREAD

**Issue by jlu5** [linuxmint/nemo#887]
Right now, the "Untrusted desktop launcher" screen only gives two options, to either Mark the `.desktop` file as trusted, or to launch it anyway. A third option, "Open in Text Editor" would be useful so one can see what the launcher does before running it.

![](https://dl.dropboxusercontent.com/u/18664770/untrusteddesktop.png)

At the same time, opening a `.desktop` file in the _default_ editor is inconvenient, requiring three clicks. The default application shows up only in the Open With dialog, and not the menu. Selecting Open will just give the popup above.

![](https://dl.dropboxusercontent.com/u/18664770/openwith.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
