### ISSUE TITLE
Arrow is not always displayed when a folder is not empty

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#894]
I noticed that in Nemo sometimes the arrow is not always displayed when a folder is not empty in list view. That can confuse you and make you think some folders are empty whereas there not.

This is this arrow I talk about
![screen](https://cloud.githubusercontent.com/assets/2451563/7779549/bfb13402-00d5-11e5-861b-8147ef909168.jpg)

**Comment by Paviluf** [comment]
I know this bug is small but it can confuse you and make you think some folders are empty whereas there not. That can lead you to delete some "empty" folders that are not so empty.

**Comment by Paviluf** [comment]
I need to test it more because with the latest version it don't seem to happen.

**Comment by Cobinja** [comment]
I notice this when copying something into an empty folder. Nemo doesn't seem to notice the content change. This also happens when emptying a folder. The arrow then stays.

**Comment by Vahan86** [comment]
@ghost, is this still an issue for you in Nemo 3.0.6?

**Comment by JosephMcc** [comment]
I can reproduce this on the latest Nemo. The "Size" column will change to indicate there is a change in the number of files but the arrow does not update it's visibility. I don't know if this is a bug in Nemo itself or an issue with GktTreeView's.

**Comment by dg1727** [comment]
This issue is like #508

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/nemo/issues/486

**Comment by mentrelli** [comment]
Nemo 3.2.2. still affected by the bug
