### ISSUE TITLE
tab key does not switch between panes

### ISSUE THREAD

**Issue by jerkey** [linuxmint/nemo#897]
nemo version 2.4.4 in linux mint 17.1 rebecca
pressing the tab key should cycle the highlighter between parts of the window, such as the sidepane, the files, and the buttons on the toolbar.

presently the tab key does nothing and the program can only be used with the mouse.

**Comment by HifeFish** [comment]
See also https://github.com/linuxmint/nemo/issues/612 and https://github.com/linuxmint/nemo/issues/816

**Comment by tp0** [comment]
+1

**Comment by IAmBroom** [comment]
It's the most simple of ideas, and universal to every other dual-pane file manager. Additionally, Tab should continue to cycle through the address bar and the folder tree before returning focus to the panes, and Shift+Tab should cycle in reverse order.

**Comment by tflori** [comment]
+1

**Comment by Dukuu-Wild** [comment]
This should be done anyway. It's very inconvenient to use double-pane nemo otherwise.

**Comment by Vahan86** [comment]
@JosephMcc, can this issue be marked as a feature request?

**Comment by JosephMcc** [comment]
Closing in favor of https://github.com/linuxmint/nemo/issues/816 since it's a bit more general and about improving keyboard navigation overall.

**Comment by vstepaniuk** [comment]
+1
