### ISSUE TITLE
The option compact layout doesn't work

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#900]
If you select compact layout in preferences for icon view it doesn't work. But if you activate it in "view / arrange items" that works

**Comment by JosephMcc** [comment]
I can reproduce this. I doesn't effect the view in Nemo but it does seem to affect the desktop icons.

**Comment by xenopeek** [comment]
Not reproducible on Nemo 4.6.4. This looks like it was related to #701 and no longer an issue. Desktop icons and Nemo window icons preferences have been split between desktop context menu > Customize and Nemo > Preferences and don't affect each other.
