### ISSUE TITLE
nemo actions cannot adequately handle filenames with double quotes or single quotes

### ISSUE THREAD

**Issue by bjd-pfq** [linuxmint/nemo#902]
Trying to cover /all/ bases for a simple 'du' action test case.

Many (classical) music filenames have double quotes in them.
Many other directories or filenames have single quotes in them (Carl Sagan's Cosmos),
some have both (Daniel Dennet's "The Mind's Eye").

Quote=double + EscapeSpaces + some sed'ing in the called script can make it work
for filenames with single quotes. All others fail hopelessly.

May find(1) be educational in its ability to output nul-terminated filenames.

**Comment by kehugter** [comment]
:+1: 
The option `Escape Spaces` could be generalised to `Escape` with optional characters to escape (multiple allowed). For example

`Escape =spaces;singlequotes;`

**Comment by icarter09** [comment]
@bjd-pfq is this still an issue?
