### ISSUE TITLE
[Feature Request] Improve Plugin-Manager

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#903]
I think that the implementation of a plugin-manager was a great idea, but it needs a little more finetuning. For Example it would be nice to be able to open the files (actions) directly with the preferred text-editor instead of opening the folder and searching again.

It would also be helpful if there would be an extra pane which shows the containing code, for example i have 2 actions whichs name is print (one for lpr and one for libreoffice) and it s quite hard to distinguish between these two without seeing the exec line.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
