### ISSUE TITLE
[Bug] Nemo doesn't fully honor PATH variable for action-dependencies

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#904]
Well, actually I'm not shure if this really is a bug, rather than a feature request...

I set my personal PATH Variable to 
PATH=PATH:Documents/bin
where i have a directory with my own Programs, Scripts, etc. I just wrote a Nemo-Action to open random files in the current directory and wanted to use the script "random-file", which i have written for this, as a dependency, which didn't work.

Nemo (and cinnamon as a whole) doesn't seem to read the PATH Variable

**Comment by mtwebster** [comment]
Not sure what file you're setting that in, but shoudn't you be adding it like this:

PATH=$PATH:<absolute path>

so for you it should be:

PATH=$PATH:/home/<you>/Documents/bin

**Comment by ManIVIctorious** [comment]
Well, it is set correctly, i just wrote from memory.

Forget about the Bugreport, i just had to restart nemo, sorry for bothering you
