### ISSUE TITLE
Share plugin with more option for Nemo

### ISSUE THREAD

**Issue by makafsal** [linuxmint/nemo#906]
The plugin nemo-share not provides option to share files via Bluetooth, wifi (with android),... may include other networking and social services. From a right click we can share the files than sending from bluetooth applet (In case of bluetooth). That is it's a more handy way to share the files choosing the option from it's right click menu.

**Comment by ACinnamonUserInUK** [comment]
I too would like Nemo to provide some bluetooth integration. At present, Nemo cannot even browse bluetooth devices - or at least not when the bluetooth is handled by `blueman` (and I know that Mint 18 comes with `blueberry`, but try as I might I couldn't get the latter to work).

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
