### ISSUE TITLE
nemo crasches with: create new folder + right click 

### ISSUE THREAD

**Issue by KDB2** [linuxmint/nemo#908]
Dear team,

A bug has been reported earlier and I can confirm it on Nemo 2.6.5

To reproduce:
Open Nemo. 
Then in list view create a new folder. 
Immediately issue a right click on the name of the folder (without clicking anywhere else before). Nemo crashes.

Regards,
KDB

**Comment by GLolol** [comment]
Confirmed here too (Nemo 2.6.5) - it seems to only affect List view, and not Compact or Icon view.

**Comment by bitboy85** [comment]
Seems to be fixed in Nemo 2.6.7
