### ISSUE TITLE
Rename bug disables copy and paste

### ISSUE THREAD

**Issue by gilbertohasnofb** [linuxmint/nemo#909]
Here is a bug that has been bothering me lately:

- right click on any file, select "Rename..." and type a new name, but do not press ENTER
- click on any location different than the one your file is using the sidepanel in the left side (such as Home or Desktop)
- Nemo now cannot copy and paste any file! 

At this point, only quitting and reopening Nemo seems to solve this.

**Comment by icarter09** [comment]
Verified this is a bug on Cinnamon 2.6.8

**Comment by AXDOOMER** [comment]
On my computer it's completely gone. "Copy to" and "Move to" don't appear. I have restarted my computer several times and they didn't came back. It bothers me a lot, I always use this feature.

**Comment by mtwebster** [comment]
Is this in Mint 17 or other?  I can't reproduce this.

**Comment by gilbertohasnofb** [comment]
@mtwebster I am on 17.1 64-bit. I am planning to upgrade to 17.2 soon and then I will test if this bug is still present there.

**Comment by bitboy85** [comment]
Can't reproduce on Linuxmint 17.2 Nemo 2.6.7

**Comment by mtwebster** [comment]
Finally able to reproduce.  Yay!
