### ISSUE TITLE
Volume is Busy error raised when USB stick contents are displayed

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/nemo#910]
If you try to eject a mounted USB stick while the contents of it are displayed in nemo, a "Volume is Busy" error is displayed even if no file operations are pending and no files are open. 

Navigating to a different folder, then ejecting the stick works as expected.

I see two problems here. First, the "Volume is Busy" error gives the user the impression that something other than nemo is accessing the stick, even when that's not the case. Second, if the user tries to eject the stick while looking at the contents, nemo should allow that to happen, and subsequently change the view to somewhere logical like the user's home folder.

Mint 17.1 x64 Cinnamon

**Comment by leigh123linux** [comment]
Viewing the contents (even an open terminal) of a mount is rightly considered a file action, this isn't a bug.

**Comment by rkingsbury** [comment]
You may be right about viewing the contents, but I still think this behavior is confusing. Perhaps the warning can be made more specific, or the user can be given the option to close the view and then unmount?  Cinnamon prides itself on being accessible to a wide audience, and I can absolutely see this tripping up many users.

All it says right now is "One or more applications are keeping the volume busy". This is rather mysterious and is likely to encourage users to physically unplug the stick rather than figure out what's actually happening and unmount it properly.  If nemo is keeping the stick busy, it seems like nemo should be able to reflect that in the warnings it raises.

**Comment by NetworkXXIII** [comment]
I second that. While it is not a bug, it certainly is a usability issue.

**Comment by icarter09** [comment]
Nemo v4.8.4
Mint 20.1 64bit

> If you try to eject a mounted USB stick while the contents of it are displayed in nemo, a "Volume is Busy" error is displayed even if no file operations are pending and no files are open.

I'm no longer seeing that issue.
