### ISSUE TITLE
Format USB stick fails when contents displayed

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/nemo#911]
If you try to format a mounted USB stick while the contents are displayed in nemo, the format fails with the error "An error occurred." If you first navigate to a different folder, the format completes successfully.

Apparently viewing the contents of the USB stick marks it as "busy," preventing the format. See #910 .
However, the error raised by the format command gives you no indication at all that this is the problem.

Displaying the contents of a USB stick should not prevent it's being formatted.

Mint 17.1 x64 Cinnamon

**Comment by leigh123linux** [comment]
I disagree, if your formatting you should always umount first.

**Comment by rkingsbury** [comment]
Maybe so. In any case the error message should be made more descriptive so that an unsophisticated user will understand what they need to do to get a successful format.

Even better, the user could be prompted with the option to unmount the stick.

**Comment by rkingsbury** [comment]
For what it's worth, the equivalent behavior in Windows file explorer is that if you choose "Eject" from the sidebar while viewing the contents of the USB stick, the drive is ejected and the file explorer window is immediately closed. I think this is what trained my expectations (and I suspect those of many other users) regarding how eject behavior should work.

**Comment by icarter09** [comment]
@rkingsbury are you still experiencing this issue on the latest version of nemo?
