### ISSUE TITLE
certain mimetype-icons are not displayed

### ISSUE THREAD

**Issue by rickandmorty100years** [linuxmint/nemo#912]
Nemo always uses text-x-preview.[svg|png] if present instead of the corresponding icons (text-x-c, text-x-plain, text-xml...)
Tested with faenza-Icon-Theme. Thunar and PCManFM do it right.
See screenie. Had similar issues with mkv, mp4...
![nemo-screenie](https://cloud.githubusercontent.com/assets/12847796/8113036/0cbb7ee4-105b-11e5-937f-05e4ebea6e41.jpg)

**Comment by JosephMcc** [comment]
Try going to Nemo->Edit->Preferences and on the Preview tab set "Show text in icons" to Never.

**Comment by rickandmorty100years** [comment]
That fixed it! (Always wondered what that option would do, but never tried it)
Thank you.

**Comment by dg1727** [comment]
It appears that mtwebster didn't really refer to this issue #912 in issue #4072.  Maybe he did by mistake and then edited or deleted that comment in issue #4072.  Either way, possibly it is a problem in GitHub.
