### ISSUE TITLE
"Copy to" and "Move to" are gone?

### ISSUE THREAD

**Issue by AXDOOMER** [linuxmint/nemo#915]
I have restarted my computer several times and these two options to move or copy a file to a bookmarked place are missing. I used them a lot and it really bothers me that I cannot use them right now. They are still available in the "Edit" menu. 

![screenshot from 2015-06-23 21 32 25](https://cloud.githubusercontent.com/assets/6194072/8321003/81523b88-19ef-11e5-8a5c-a26b6513dede.png)

**Comment by AXDOOMER** [comment]
![screenshot from 2015-06-23 21 43 11](https://cloud.githubusercontent.com/assets/6194072/8321170/97f4f0b8-19f1-11e5-8ee2-94a0d5e72ed5.png)

**Comment by mtwebster** [comment]
preferences -> display -> context menus, show all available actions.

**Comment by AXDOOMER** [comment]
Thanks! Is this option unchecked by default in Linux Mint version 17.2 ?

**Comment by AXDOOMER** [comment]
This bug report can be closed.

**Comment by jeffmcneill** [comment]
Note that as of Feb 2020, that preferences item no longer exists, and instead there is a small "plus" icon (toggle) on the right side of the title bar in the right-click menu. Click to toggle to enable displaying the menu items: Duplicate, Make Link, Copy To, and Move To.

**Comment by JosephMcc** [comment]
You have an old Nemo version. The option exists in Nemo 4.4

**Comment by jeffmcneill** [comment]
Yes indeed, thanks! I'm using 3.2.2 which is the latest dev release for the lmde3 platform (I'm on Debian so I figured this was the most reliable version to use).

**Comment by jeffmcneill** [comment]
Yes indeed, thanks! I'm using 3.2.2 which is the latest dev release for the lmde3 platform (I'm on Debian so I figured this was the most reliable version to use).

Found here: https://github.com/linuxmint/nemo/releases
