### ISSUE TITLE
Can't select all text in the search bar using Ctrl+A

### ISSUE THREAD

**Issue by AXDOOMER** [linuxmint/nemo#916]
In the search bar, I'd like to do Ctrl+A to select all the text then delete it quickly by pressing backspace, but when I do Ctrl+A, it selects the search results instead, even if I clicked in the search bar with my mouse to make sure it would select the text. Ctrl+C also doesn't work, but Ctrl+V works. 

Nemo version 2.6.7

**Comment by JosephMcc** [comment]
This now works in Nemo 3.0.6
