### ISSUE TITLE
[Request] Better show/hide menubar 

### ISSUE THREAD

**Issue by hetraeus** [linuxmint/nemo#918]
Hello, since I like to have a clean interface I have hidden the Menubar. Now the problem is that every time I press the Alt key the Menubar pops up with no need. Would it be possible to change the behaviour of Nemo to match the behaviour of Firefox*?

*Which means to unhide on Alt key release instead of press and only if Alt is not part of a keybind

**Comment by ManIVIctorious** [comment]
Or something like in kde where the most important settings get merged under one Button when menubar is not shown

**Comment by hetraeus** [comment]
A button would be a nice alternative indeed

**Comment by Vahan86** [comment]
@JosephMcc, the issue is still relevant to Nemo 3.0.6.

**Comment by feren** [comment]
This bug also triggers https://github.com/linuxmint/nemo/issues/1334 in Nemo's current state

**Comment by hobarrera** [comment]
<kbd>alt</kbd> is pretty universal to show the menubar in just about any app that hides it, I'd really go against having a different mechanism just here.

However, I do believe that #1389 should satisfy the UX problem triggering this request.

**Comment by JosephMcc** [comment]
Lets just keep this all in one place https://github.com/linuxmint/nemo/issues/1389

**Comment by joaopauloalbq** [comment]
I kept showing the menu bar accidentally when using other key combinations with <Alt> [[Video](https://youtu.be/fh1CXRAaYHc)]
