### ISSUE TITLE
support for custom views besides grid, list and compact view

### ISSUE THREAD

**Issue by jf99** [linuxmint/nemo#920]
Maybe this feature already exists and I've just not found it.

I'm using nemo-media-columns for my mp3 folders (and others). There are hundreds of them on my harddrive (one per artist). It's just too cumbersome to configure each folder on its own. There's a need for custom view profiles like "music", "documents", "pictures" and so on.

Another useful capability would be, if you could change the view AND apply these changes to all subfolders.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
