### ISSUE TITLE
nemo 2.6.7 bug - gnome_desktop_thumbnail_cache_check_permissions

### ISSUE THREAD

**Issue by OmarTrigui** [linuxmint/nemo#921]
I've just upgraded to Mint 17.2, nemo 2.6.7.
Unable to browse files even after installing gnome-tweak-tool and trying to enable/disable desktop icons

~ $ nemo
nemo: symbol lookup error: nemo: undefined symbol: gnome_desktop_thumbnail_cache_check_permissions

**Comment by mtwebster** [comment]
Did you somehow uninstall cinnamon-desktop?

`sudo apt-get install gir1.2-cinnamondesktop-3.0 libcinnamon-desktop4 cinnamon-desktop-data`

you can enable/disable desktop icons from Cinnamon Settings->Desktop, don't use gnome-tweak-tool (i doubt it even works for Cinnamon)

**Comment by mtwebster** [comment]
Check your versions of those as well - should be 2.6.5

**Comment by OmarTrigui** [comment]
All the needed dependencies are already installed !
Settings->Desktop doesn't fix the problem ! 
I can't even interact with the Desktop ( Right Click doesn't works )

I've checked the existence of files "ls Desktop/".

~ $ nemo --version
nemo 2.6.7

**Comment by mtwebster** [comment]
What versions of cinnamon-desktop are you on?
`dpkg --list | grep cinnamon-desktop`
and
`dpkg --list | grep cinnamondesktop`

Those should be 2.6.5.  Any other versions must be removed/purged.

Is this a clean install?  There's no official upgrade yet for 17.1->17.2.

**Comment by OmarTrigui** [comment]
```~ $ dpkg --list | grep cinnamondesktop   ```
  ```ii  gir1.2-cinnamondesktop-3.0                  2.6.5+rafaela  ```

  ```~ $ dpkg --list | grep cinnamon-desktop  ```
  ```ii  libcinnamon-desktop4:amd64                  2.6.5+rafaela  ```

Anyway, we'll wait for the official upgrade of Mint 17.2

**Comment by GLolol** [comment]
Check if `libcinnamon-desktop0` is installed on your computer. If it is, you'd want to remove that.

**Comment by OmarTrigui** [comment]
YES, that's it.
The problem was solved by removing libcinnamon-desktop0.
Greetings.
