### ISSUE TITLE
Nemo is infinitely slow to show folders which are updated often

### ISSUE THREAD

**Issue by sixtyfive** [linuxmint/nemo#926]
(I'm referencing here https://github.com/linuxmint/Cinnamon/issues/3572, even though I'm not sure if it's about the same issue).

One of my folders which I open many times a day contains the output of a Makefile which compiles my thesis (meaning there are some .txt files, a .tex, a .docx, and .html, an .odt and a .pdf in there, 9 files total, which is interesting if you look at the above link (only 16 files there, not a lot either). The size of all the files in the folder is 2.9MB, almost all of which belong to the PDF.

What usually (but not always) happens when I double-click this folder is that Nemo shows "Loading..." and a little spinner in the lower right corner. CPU utilization jumps to between 3% and 5% and then stays there until I click the little "stop" icon next to "Loading..." When I do that, the notice disappears and nothing is shown. I can then hit F5 and immediately see folder contents but no thumbnails. I've since disabled thumbnail creation because this got on my nerves bad. Just writing this report so you might have an eye out for the problem.

Edit: with "infinite" I mean that I've tried leaving the "Loading" thing going for up to 16 hours, which didn't make it succeed.

**Comment by HifeFish** [comment]
I have a very similar issue: When I have my Download folder opened in Nemo and I am downloading a video file, Nemo will use a lot of CPU time and eventually freeze up if the Download takes a while.

I assume the root of the problem is the same.

**Comment by sixtyfive** [comment]
I think these are two different things. In my case, the PDF thumbnailer seems to be the cause, and in your case it's the video thumbnailer. Anyways, perhaps Nemo could implement some sort of safeguard against runaway thumbnailers in general?

**Comment by HifeFish** [comment]
You are probably right. I assumed the problem might be that the respective thumbnailers are called too often, which might be a general problem. A possible "global" solution could be to only refresh thumbnails on refreshing, but that might not be desirable. Maybe one could have a minimum time between refreshes that could be set by the user. (In general I think Nemo should not freeze for thumbnailers, but prioritize just listing files and have the thumbnailer run independently and call back when it's ready, but I don't know if that's feasible.)

**Comment by Vahan86** [comment]
@sixtyfive, is this still an issue for you with Nemo 3.2?

**Comment by sixtyfive** [comment]
Sorry, @Vahan86, sometime between then and now Mint had that security debacle and I wasn't too happy with how it was handled and moved on to Debian.
