### ISSUE TITLE
Switch To New Tab Automatically

### ISSUE THREAD

**Issue by BigDaddyLinux** [linuxmint/nemo#927]
Not sure if this is this is the right place to do a feature request but here goes.

Please add a setting to be able to focus to a new tab when it opens. Right now the default behaviour is. Right click on a folder and "Open in new tab" and it opens in the background. Requesting that when you right click on a folder and "open in a new tab" it focuses on the new tab immediately.

Sorry if this is in the wrong section, I didn't see feature request anywhere.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
