### ISSUE TITLE
[Request] Add an option to restore the older Bread Crumbs bar behavior.

### ISSUE THREAD

**Issue by rgzdev** [linuxmint/nemo#928]
Please add an option to automatically revert the Location Entry to the Bread Crumbs bar when pressing enter.

This is the way Nautilus works.

**Comment by ManIVIctorious** [comment]
+1

**Comment by xenopeek** [comment]
This appears to be implemented. Toggling the location entry, modifying the location and pressing enter changes the location and reverts view to bread crumbs bar.
