### ISSUE TITLE
Ejecting network device while viewing it crashes nemo and desktop

### ISSUE THREAD

**Issue by qgates** [linuxmint/nemo#929]
Steps to reproduce:
1. Launch nemo and, using "Network" in the left pane, browse to a samba share and connect to it.
2. With the file contents of the share visible, click the eject button on the share as listed under "Network" in nemo's left pane (or right click it and choose "unmount")

Nemo instantly crashes (window disappears) and desktop icons vanish.

Workaround: Relaunch nemo with the following:
a) ALT+F2 followed by "nemo"
b) Bring up mintmenu and type "nemo" or "files" into the search. Run "Files"

Affects Cinnamon 2.4 and 2.6 (tested Linux Mint 17.1 / 17.2, 64-bit)

This bug is probably the same problem as described in #843

**Comment by KOLEGA007** [comment]
I can only reproduce this if the ftp connection becomes innactive after long time (closed by server) ...

Then I unmount the dir. and nemo crashes ...

**Comment by FormidableInc** [comment]
Hello. It's still true as of today. Not only FTP but SSH/WebDav/Samba also. I did not see if it's linked to inactivity. It's really annoying. No trace in logs.

**Comment by Vahan86** [comment]
@qgates, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
