### ISSUE TITLE
Add "open in a terminal" and "open as root" to the loaction bar context menu  

### ISSUE THREAD

**Issue by daschuer** [linuxmint/nemo#93]
For me it is the most natural place to look for those actions for the current folder.

**Comment by xenopeek** [comment]
Old one but should probably be tagged as a feature request. This may be nice.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
