### ISSUE TITLE
After entering password for keyring, nemo asks for password

### ISSUE THREAD

**Issue by ondrejkolin** [linuxmint/nemo#930]
_Problem_
When i run my Linux Mint 17.2 Cinnamon and want to go on some ftp server, the keyring (gnome-keyring) pass phrase needs to entered, but after that nemo (2.6.7) asks again for server credentials (like login, pass, etc.)
If I close this dialog and click again on bookmark with server, it connects instantly without asking for anything (using the keyring)
_Steps to reproduce_
Bookmark FTP server and save login informations for him.
Reboot 
Open Nemo
Try to open the bookmark

Hope, this is good description of my issue :)

**Comment by KOLEGA007** [comment]
Same issue on Thunar when on Linaro 14.04 Xfce

**Comment by icarter09** [comment]
@ondrejkolin are you still experiencing this issue on the latest version of nemo?
