### ISSUE TITLE
Scrolling with mouse wheel leaves items underlined when using "Single click to open items"

### ISSUE THREAD

**Issue by sumzary** [linuxmint/nemo#931]
This has nothing to do with any modifications I've made, I've had this issue ever since I installed it several months ago, vanilla, default skins and all. Once you hover over the items again the underlines go away. I'm using arch linux if that matters. I last updated Nemo 2 days ago.

![nemo](https://cloud.githubusercontent.com/assets/13392743/8761362/9ac134e6-2d56-11e5-879a-934282916303.png)

**Comment by Vahan86** [comment]
I can't reproduce the issue in Nemo 3.0.6 (Mint 18).
@Sumzary, is this still an issue for you with Nemo 3.0.6?

**Comment by Sumzary** [comment]
I'm on a freshly updated Ubuntu 16.04.
I installed Nemo on it for the first time since I've been on this system.
I went to a folder with lots of files.
I enabled list view.
I enabled the setting to open files with just one click.
Upon scrolling the issue still appears.

**Comment by JosephMcc** [comment]
I just tried this with the latest git version under Mint and can't reproduce it. Where did you install Nemo from? What version is it?

**Comment by Sumzary** [comment]
Installed it with apt-get from this PPA:
https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly
Nemo version is 3.2.0

**Comment by JosephMcc** [comment]
That's the same Nemo I'm using on Mint that I can't reproduce this with. Have you tried different gtk themes just to eliminate it being a theme issue?
