### ISSUE TITLE
Crash on unmounting remote FS (gvfs, ftp)

### ISSUE THREAD

**Issue by KOLEGA007** [linuxmint/nemo#932]
If I press in bookmarks the unmount sign on remote directory (ftp://... ) the nemo crashes ... 
Output from terminal while running "nemo"
`ERROR:nemo-bookmark.c:260:nemo_bookmark_connect_file: assertion failed: (!nemo_file_is_gone (bookmark->details->file))
Aborted
`

**Comment by qgates** [comment]
Probably duplicate of #929

**Comment by KOLEGA007** [comment]
Yeah, its duplicated ...
