### ISSUE TITLE
Move 2000 files between folders on same partition, nemo/queue freezes partway

### ISSUE THREAD

**Issue by qgates** [linuxmint/nemo#933]
Moving 2000 files between 2 folders on the same partition, nemo begins the move and shows the queue. The queue box says "preparing to move" and shows a stuck progressbar. Nemo hangs forever and no folders/files are browsable until nemo is killed and restarted.

Inspecting the filesystem with terminal, some of the files have been moved, say 150, but then the operation has stopped.

Mint 17.2 64-bit, Nemo 2.6.7

Repeated on 2 different machines / filesystems / harddrives

**Comment by trebushet** [comment]
I've experienced this bug also for a couple of years now, and I believe it was also in Nautilus if I remember correctly before Nemo forked. I have seen this bug not only using the same partition, but moving files from one hard drive to another. 

I did find a workaround, by moving the folder. Instead of highlighting the files and moving them, I just move the folder itself, and the issue does not happen as much or at all when moving the folder.

**Comment by sevenskull** [comment]
I am having this same issue on Mint 17.2, and it is not with 2000, about 200 (sometimes) happens, it just freeze, so or i move the folder like trebushet said, or select files in parts and move them.

**Comment by methodds** [comment]
I can confirm the issue, also with Mint 17.2 even for 150 files.

**Comment by kehugter** [comment]
~Same. I can stop the process, no `kill` needed.
Debian stretch, nemo 3.0.3.

**Comment by ppearson** [comment]
Often having the same issue on Linux Mint 18, with Nemo 3.0.6.

Most recent was moving ~450 .jpg files from one folder to another on the same hard disk and partition (just moving them up one level).

I wonder if it's anything to do with creating the thumbnail images?

**Comment by kehugter** [comment]
> anything to do with creating the thumbnail images?

I don't think so. For example, the set

```bash
for i in {0..1000}; do touch $i; done
```

is thumb-less but still freezes nemo (3.0.6).

Also worth noting: freezes are not always reproducible, not even for the same set of files.

**Comment by atomi** [comment]
This happens to me as well, moving large amount of images and then some files just disappear. :-1:

**Comment by kehugter** [comment]
> some files just disappear

I'd say that's a completely different and critical issue. You should create a new report and provide more details. CC @JosephMcc

**Comment by atomi** [comment]
@kehugter no I know better than to trust nemo. I've been backing up to cloud using rclone.

**Comment by JosephMcc** [comment]
> some files just disappear.

I don't think I've ever heard that before. I'm sure we would be more interested on how to reproduce this. How many files are you moving? What kind of file size are the images?

**Comment by atomi** [comment]
@JosephMcc 2-8MB over a thousand files. I think it might be that I had to sudo killall nemo during the move 5 or 6 times. I ultimately finished the job with find -exec mv instead. This was on an ntfs drive.

**Comment by icarter09** [comment]
@atomi are you still experiencing this issue on the latest version of nemo?
