### ISSUE TITLE
[Feature Request] Check boxes to select items when "single click to open items" is enabled

### ISSUE THREAD

**Issue by BRKsays** [linuxmint/nemo#934]
Dear devs, can we have a check box on top of a file, preferably on top left, to select it when we are selecting multiple items? The check box should appear on mouse cursor hover and otherwise invisible. I personally love it. Would love to see it in Nemo. Just an enhancement request though, no pressure.:)

**Comment by ManIVIctorious** [comment]
+1

**Comment by Vahan86** [comment]
Issue https://github.com/linuxmint/nemo/issues/385

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
