### ISSUE TITLE
File/folder vanished after renaming it to "... And Then We Started to Dance"!

### ISSUE THREAD

**Issue by blueyed** [linuxmint/nemo#935]
TEST CASE:

    mkdir -p /tmp/foo/bar
    cd /tmp/foo
    nemo .

Then press F2 on the folder "bar" and rename it to "... And Then We Started to Dance" (notice the ellipsis char at the beginning).
The folder view is not updated, and when reloading it (F5) the folder is gone!

I've seen this on the console several times, but cannot say if it is really related:
> (nemo:26690): GLib-GIO-CRITICAL **: g_file_get_parse_name: assertion 'G_IS_FILE (file)' failed

When trying this again, I've also seen an error:
> The item could not be renamed.
> The name "... And Then We Started to Dance" is already used in this folder. Please use a different name.

It's not really reproducible now anymore, and I wonder where my folder is gone now?!

It might be related to having multiple instanstes of nemo running?

I am using nemo 2.6.7-2~webupd8~vivid00.

**Comment by blueyed** [comment]
Somehow / somewhere the ellipsis appears to have changed into three dots, and then the folder was considered to be hidden.

Closing this as duplicate of https://github.com/linuxmint/nemo/issues/491.

**Comment by gauravjuvekar** [comment]
> Somehow / somewhere the ellipsis appears to have changed into three dots

That's still a bug. Reopen?

**Comment by blueyed** [comment]
@gauravjuvekar 
Thanks for asking, but I'm pretty sure that it wasn't Nemo.
I just mixed it up myself.
