### ISSUE TITLE
Segfault while opening share on Kodi/OSMC

### ISSUE THREAD

**Issue by petter3k** [linuxmint/nemo#936]
Nemo quit unexpectedly and gave segfault error in dmesg after mounting/opening share located on a Raspberry PI running Kodi/OSMC.

```
[10648.916345] nemo[1598]: segfault at 18 ip 00000000004f3a30 sp 00007ffe4f1af478 error 4 in nemo[400000+1c4000]

```

**Comment by Vahan86** [comment]
@petter3k, is this still an issue with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
