### ISSUE TITLE
Icon theme randomly falls back to gnome settings

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/nemo#937]
I cant reproduce it but every now and then the icon theme falls back to an other one. I found out that the "other one" is the one set with gnome-tweak-tool.

**Comment by Vahan86** [comment]
@ManuelSchneid3r, is this still an issue for you with Nemo 3.0.6?

**Comment by ManuelSchneid3r** [comment]
I didn't experience it a long time now. I will report back if it happens again.
