### ISSUE TITLE
Opening a folder is very slow comparing to nautilus

### ISSUE THREAD

**Issue by hadim** [linuxmint/nemo#939]
I am using Linux Mint 17.2 with `nemo` 2.6.7 and `nautilus` 1:3.10.1-0ubuntu9.9.

When I open a folder (whatever folder it is), it usually takes 1 or 2s (it can be even 5-10s for large folders) when using `nemo` while it is almost instantaneous when using `nautilus`. I don't have the time to see the "waiting cursor" with `nautilus`.

My workaround is simply to use nautilus for now...

Any idea ?

I can do more benchmarks if needed.

**Comment by hadim** [comment]
Just in case you ask : 

```sh
$ cd ~/.thumbnails/ && du -sh *
8,0K	fail
96K	normal
```

**Comment by yomli** [comment]
Same setup here, same issue.

Just for testing purpose, I went to `~/.thumbnails/normal`. There I have 33 000 files, 630 Mo.
+ Marlin: 3 seconds to open (no preview),
+ Thunar: 5 seconds to open (no preview),
+ Nautilus: 10 seconds to open (no preview),
+ Nemo: 10 minutes to open (no preview) !

A folder _on an external hard drive_ with more than 15 000 pictures (5Go):
+ Thunar: 9 seconds (with preview),
+ Nautilus: 18 seconds (with preview),
+ Nemo: 3 minutes (with preview), uses 72% of CPU and 1,5 Go of RAM !

I deactivate the preview, on the same folder:
+ Marlin: 2 seconds (no preview),
+ Nautilus: 7 seconds (no preview),
+ Nemo: 2 minutes (no preview) !

So I suspect it's not a thumbnailer issue. I deactivated all Nemo plugins. Same results.

**Comment by hadim** [comment]
I still have the same issue even with the last cinnamon nightly builds (https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly).

I really want to use nemo instead of nautilus but the inconvenient are too big for now... so i'm stuck with nautilus.

**Comment by howdev** [comment]
nemo 2.8.6 from cinnamon 2.8 is still very slow to show folder content. It is not very usable when switching folders. Huge lag when folders with many files like /usr/bin for example.
Thunar opens folders instantly.

**Comment by nicolas33** [comment]
Dups #1123
