### ISSUE TITLE
nemo's rename fails for me

### ISSUE THREAD

**Issue by RPeters52** [linuxmint/nemo#940]
I was wondering if anyone else was having problems with using nemo to rename folders and files.  I am using LM 17.2  
1) I own the file and can rename it with something as simple as 
    mv az AZ (                  for a folder)
    mv StateFair2015.pdf StateFair2015b.pdf  (for a file)

2) If I use nemo, nothing happens.  I select the folder or file name in nemo, choose Edit -> Rename or hit F2 and type.  No letters appear in nemo as I type and the name of the file or folder is NOT changed.

I then go to the terminal and change it using "mv".  This name change appears in the nemo gui immediately.

If I create a new folder with nemo, I get "Untitled Folder" as a name and I cannot change the name with nemo.

EXAMPLE:
ralph@sclero ~/Desktop/EchinocereusRed/NM $ ls
Orogrande  Orogrande__YardPlant  OteroMesa  Untitled Folder  W_Laguna
ralph@sclero ~/Desktop/EchinocereusRed/NM $ mv Untitled\ Folder/ SomethingElse
ralph@sclero ~/Desktop/EchinocereusRed/NM $ ls
Orogrande  Orogrande__YardPlant  OteroMesa  SomethingElse  W_Laguna

I have been using unix since the late 1980s and linux since the mid 1990s, so I am not a "newbie".

Further questions?  Drop me a note!
Ralph Peters

**Comment by gritty-gitty** [comment]
It’s a known issue inasmuch as *bulk renaming* doesn’t work either on file names with white or UTF-8 characters, see https://github.com/linuxmint/nemo/issues/614.

**Comment by RPeters52** [comment]
Hi!

Thanks for the response!

In my case, I was try to change the name of a single folder -- "az" to
"AZ".  I also tried to change a folder name "Untitled folder" to something
else like "CO"  The folder renaming problem has been a recurrent problem
for me with nemo.  I have *NOT* had this problem with any other folder/file
browser.

Thanks!
Ralph Peters

**Comment by RPeters52** [comment]
Hi,

BTW, this problem is intermittent (just to add to the fun).  Sometimes,
rename works, many times it doesn't.  I restarted my laptop, and now it
works.  In fact, I currently cannot get it to fail.  Who knows...

Ralph Peters

**Comment by RPeters52** [comment]
Hi,

I just had another rename failure with nemo -- in this case Untitled
Folder" to something useful .

I shut down all the nemo instances and everything else (firefox,..) and
tried again to do the rename.  That did not fix the problem.

So, I did a complete shutdown and restart and now I can rename the
"Untitled Folder" to something useful where I could not rename that folder
before.

Ralph

**Comment by Vahan86** [comment]
@RPeters52, is this still an issue for you with Nemo 3.0.6?

**Comment by RPeters52** [comment]
I have not had any problems recently.

On Mon, Nov 21, 2016 at 1:36 PM, Vahan Harutyunyan <notifications@github.com
