### ISSUE TITLE
Unknown type displayed with defined detailed type

### ISSUE THREAD

**Issue by jolkdarr** [linuxmint/nemo#942]
In the list view, Type should never be "Unknown" whenever Detailed type is specified and displayed.

**Comment by icarter09** [comment]
@jolkdarr do you have an example of this?

**Comment by jolkdarr** [comment]
@icarter09 Please, see example in the provided screenshot.
![Screenshot](https://user-images.githubusercontent.com/3129230/71472625-0fcf1100-27d4-11ea-90a9-61ac6ad0cc7d.png)

**Comment by leigh123linux** [comment]
@jolkdarr  Which distro and nemo version?

![Screenshot from 2019-12-26 10-52-31](https://user-images.githubusercontent.com/1299302/71473175-e90ddc00-27cd-11ea-8706-a999607ebb0e.png)

**Comment by jolkdarr** [comment]
LinuxMint 19.3, Nemo 4.4.2

Not all types are actually failing.
My screenshot shows numerous mimetypes with "undefined" types.

**Comment by xenopeek** [comment]
As an example download these RDF test files: https://www.w3.org/2000/10/rdf-tests/All.zip

- Nemo shows Type as Unknown
- Nemo shows Detailed Type as RDF File
- `file` shows "XML document, ASCII text"
- `xdg-mime query filetype` shows "application/rdf+xml"

**Comment by icarter09** [comment]
I put a PR for this which might be as good as this fix gets. This will help to replace "Unknown" with "Application" when a file type looks to be a generic application.
