### ISSUE TITLE
Breadcrumbs don't highlight current path

### ISSUE THREAD

**Issue by monkbroc** [linuxmint/nemo#945]
![breadcrumbs](https://cloud.githubusercontent.com/assets/1919681/9097799/d073fc72-3b93-11e5-9352-e0736cb15d1f.png)

On Ubuntu 15.04 with the default Ambiance theme the current path is not highlighted in the breadcrumbs (in the picture Wallpapers should be highlighted).  It used to be highlighted correctly in previous Ubuntu versions.

Is there a theme override that could fix this? I tried styling different combinations of NemoPathbarButton with :active and :hover but I could only change the color of all breadcrumbs, the one under the mouse or the one being clicked, not the one representing the current path of the Nemo window.

**Comment by monkbroc** [comment]
Does anybody have a clue why this might be happening? Is this theme related? I'm willing to try to fix the bug if someone could point me in the right direction.

**Comment by JosephMcc** [comment]
It could be theme related. The screenshot shows an older version of nemo. The breadcrumbs were changed awhile back.

**Comment by monkbroc** [comment]
Thanks. I'll take a look at upgrading to the latest version on Ubuntu. A simple `apt-get upgrade nemo` says it's the latest version (2.2.4), but I'll see if there's another package repository with a newer version.

**Comment by JosephMcc** [comment]
The newest version of nemo is 2.6.7

**Comment by monkbroc** [comment]
I no longer have this problem in nemo 2.8.0 under Ubuntu 15.10
