### ISSUE TITLE
Desktop icon overlap

### ISSUE THREAD

**Issue by jackssir** [linuxmint/nemo#946]
Mint 17 32-bit and 64-bit, I found a problem,  CD ROM driver the is a disk in, eject the disc, and then move a file to the CD room position,  and then close the CD rom, CD room and file overlapping.
![overlay](https://cloud.githubusercontent.com/assets/13670992/9105673/6ca90c3c-3c4c-11e5-9e1c-bfee31269a96.png)

**Comment by jackssir** [comment]
and the nautilus had the program!

**Comment by Vahan86** [comment]
@jackssir, is this still an issue for you in Mint 18?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
