### ISSUE TITLE
Regression: nemo --no-desktop does not work in openbox any more

### ISSUE THREAD

**Issue by revast** [linuxmint/nemo#947]
I sucessfully used nemo in openbox as filebrowser, without letting it draw the desktop, but this does not work anymore: even with --no-desktop specified, it now draws the desktop. Ubuntu 14.04, nemo 2.6.7, openbox 3.5.2. I have xfce4 installed on the same system - there it works flawlessly

**Comment by froderik** [comment]
similar behavior for me in new arch box. On old one it works nicely. Did I configure this somehow? I don't remember.... :-)

**Comment by mwz** [comment]
Same issue here with i3 after the recent upgrade to 2.8.6-20160111010010-trusty.

**Comment by roman-bronis** [comment]
Same here with i3 with nemo 2.8.6.r20.gf539ba5-1 and I think also with current GitHub master.

**Comment by mwz** [comment]
c1ae71e21e8af2985fd5f64ecd9e20b8549e0424 fixes this issue for me, thanks @daschuer!

**Comment by Vahan86** [comment]
@revast, is this still an issue for you with Nemo 3.0.6?

**Comment by daschuer** [comment]
This is fixed since 3.0.0
