### ISSUE TITLE
Fix thumbnail cache command

### ISSUE THREAD

**Issue by vaurelios** [linuxmint/nemo#948]
The fix thumbnail cache command:

```
g_spawn_command_line_sync ("sh -c \"pkexec nemo --fix-cache\"", NULL, NULL, NULL, NULL);
```

Is this working for you guys ? `pkexec` "doesn't allow" X11 applications to run:

http://www.freedesktop.org/software/polkit/docs/0.105/pkexec.1.html:

> As a result, pkexec will not allow you to run X11 applications as another user since the $DISPLAY and $XAUTHORITY environment variables are not set.

wouldn't be a better way run it through the `gksu` command ?

for me the actual way (`pkexec`) as expected _doesn't_ works! while running it in gksu works as expected!

**Comment by mtwebster** [comment]
Works fine here, and we also use pkexec to "Open as root" from the context menu.  Our policykit file for nemo has the *org.freedesktop.policykit.exec.allow_gui* annotation, which specifically overrides the environment issue - https://github.com/linuxmint/nemo/blob/master/src/org.nemo.root.policy.in#L21

`gksu` is no longer used by default in many distros, and (I had thought) pkexec is the way forward.

Also, the --fix-cache option should actually need X - it runs some i/o operations and then exits without ever creating a window (though it does register the nemo application temporarily).

What distro are you running on?

**Comment by hotvic** [comment]
It was fedora, but I'm not using anymore neither nemo (switched desktop environment alongside distro).

> Also, the --fix-cache option should actually need X - it runs some i/o operations and then exits without ever creating a window (though it does register the nemo application temporarily).

yeah, it fails if the `DISPLAY` variable isn't defined.

**Comment by leigh123linux** [comment]
Works fine her
