### ISSUE TITLE
Nemo get blank icons after set "Show text in icons" to Always.

### ISSUE THREAD

**Issue by gkjgithub** [linuxmint/nemo#949]
Version: nemo 2.6.7
LMDE 2 live DVD and Arch Linux have this issue, but Mint Linux 17.2 live DVD works fine.
![bi](https://cloud.githubusercontent.com/assets/3252483/9287219/da70ef22-433c-11e5-9f6a-33a863708258.png)

**Comment by JosephMcc** [comment]
If I remember correctly, this is due to a change in gtk itself. That little text that shows on the icons isn't supported in the newer gtk versions used by LMDE or Arch.

**Comment by X0rg** [comment]
The reason is given in #954, it is GTK itself.

**Comment by gkjgithub** [comment]
Thanks for replies.
