### ISSUE TITLE
[Feature Request] Nemo Desktop to be scrollable and not overflow Screen/Display borders

### ISSUE THREAD

**Issue by stefan123t** [linuxmint/nemo#951]
Dear Nemo team,

Thanks alot for all that went into Linux Mint 17.2, especially the new Snap Corners!

I would like to have the Desktop File/Folder view to be scrollable. As it is now, I sometimes have the constraint that the Desktop being filled with Files/Folders does not fit on the screen anymore. When I select "Organize Desktop by Name" it overflows screen real-estate and the last column gets piled up with icons. If the Nemo File Manager space on the desktop would be scrollable, this would not be such a problem.

On a side note, I also have the problem with the virtual-screen area of my dual-monitor setup (I have two screens of different height) which is occupied by Files/Folders when using the "Organize Desktop by Name", even though this is in the "dark side" area outside of my screens.

Kind regards,
Stefan

**Comment by leigh123linux** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
