### ISSUE TITLE
Inconsistent focus behaviour in path bar when entering a path and hitting enter key 

### ISSUE THREAD

**Issue by svaens** [linuxmint/nemo#952]
Inconsistent focus behaviour in path bar when entering a path and hitting enter key on linux mint version 17.2 , 3.13.0-24-generic
Nemo version 2.6.7

typing in a path, for example, /mnt
in the nemo path bar (after having toggled away from the button interface, OR freshly opened nemo with location bar already active)
the behaviour when hitting <enter> is inconsistent. That is;

After giving focus to path bar via 
a) opening nemo for the first time
b) ctrl-l to raise focus to path bar
focus is given to the folder view window pane

If mouse is used to click inside the path bar, 
subsequent uses of the <enter> key see the focus remain in the path bar, with the cursor ready at the end of the path to complete the path if necessary

The behaviour should probably be more consistent, and I personally would expect focus to remain in the path bar regardless of how one came to move the focus and cursor there. This is more convenient when, for example, one does not immediately know the full path, ... one enters in a partial path, hit enter, and seeing the folder view update, can proceed to enter in the remaining length of the path. 

The current behaviour with focus moving outside the path bar, makes easy navigation via the path bar and keyboard more difficult.

**Comment by svaens** [comment]
Actually, it seems a bit more inconsistent than that. 
I just had a case where the first <enter> saw the cursor remain in the path field, the 2nd also, but the 3rd move focus to the folder pane

**Comment by icarter09** [comment]
@svaens are you still experiencing this issue on the latest version of nemo?
