### ISSUE TITLE
[Feature Request] Pin favourite folders to the sidebar

### ISSUE THREAD

**Issue by samousli** [linuxmint/nemo#953]
The ability to pin most used folders into Nemo sidebar would give a great boost in productivity and speed of use for most users.

It's been an idea I was craving for quite some time and windows 10 also seems to have added support to it, it could be a mainstream feature many people would wish for in the near future.

I originally posted this in linux mint community: http://community.linuxmint.com/idea/view/5924

**Comment by ManIVIctorious** [comment]
I am not really sure what you mean by pin to sidebar, but if you mean what i think, then you have always been able to do so, it's just adding a bookmark (shortcut ctrl+d)

**Comment by samousli** [comment]
That's exactly what I meant, I wasn't aware of the shortcut, thanks for the help.

I think the only reason this can stay up is as a request for this feature to be more apparent/visual, but I will close it.

Thanks again

**Comment by mtwebster** [comment]
There are a bunch of ways to do this - you can simply drag folders there as well - depending on where you position things it can either move/copy a folder you're dragging into an existing bookmarked folder, or insert it at a position between other items.

You can also go to the menu and manage bookmarks.

**Comment by samousli** [comment]
Thanks, that was helpful too :)
