### ISSUE TITLE
"Show text in icons" on ArchLinux bug

### ISSUE THREAD

**Issue by X0rg** [linuxmint/nemo#954]
I'm using ArchLinux x86_64, and Nemo 2.6.7 is installed, but option "Show text in icons" doesn't work. I've tested on LinuxMint 17.2, it works.

Option "Show text in icons" is set to "Always", but text is missing in icons.
I have removed ~/.cache/thumbnails, it is not better.
I have run 'nemo --fix-cache' as root, same problem.

![nemo_thumbnails](https://cloud.githubusercontent.com/assets/2873785/9411684/b89b0276-4827-11e5-8570-65b6e0e2ab83.png)
Why?

**Comment by mtwebster** [comment]
You need an icon theme that supports it - does your theme contain files called `text-x-preview.png` and `text-x-preview.icon`?  I don't think gnome does anymore in Arch or other more bleeding-edge distros.

**Comment by X0rg** [comment]
I use Faenza.
```
$ find . -name text-x-preview.png             
./Faenza/mimetypes/24/text-x-preview.png
./Faenza/mimetypes/64/text-x-preview.png
./Faenza/mimetypes/32/text-x-preview.png
./Faenza/mimetypes/16/text-x-preview.png
./Faenza/mimetypes/48/text-x-preview.png
./Faenza/mimetypes/22/text-x-preview.png
./Faenza/mimetypes/96/text-x-preview.png
```

```
$ find . -name text-x-preview.icon
./Faenza/mimetypes/64/text-x-preview.icon
./Faenza/mimetypes/32/text-x-preview.icon
./Faenza/mimetypes/scalable/text-x-preview.icon
./Faenza/mimetypes/48/text-x-preview.icon
./Faenza/mimetypes/96/text-x-preview.icon
```

I have installed Mint-X icons to try, but problem is not solved.

**Comment by mtwebster** [comment]
Ah looks like they removed support in gtk - https://git.gnome.org/browse/gtk+/commit/gtk/gtkicontheme.c?id=aa44c0ca53b8d32c9bf3114b53ce4983ec05e86e

**Comment by X0rg** [comment]
LinuxMint uses GTK 3.10, I'm using GTK 3.16. GTK 3.18 will be release in late September.

Do you think "Show text in icons" will be dropped when a new version of GTK will come in LinuxMint, or it just need adjustment in Nemo?

**Comment by mtwebster** [comment]
If we wanted to keep it, we'd definitely need to implement it ourselves in Nemo (or patch the GTK that Mint will ship with) - neither of these is probably likely at this point - it's arguable how useful this feature really is (I mean in broad terms, not the individuals who *do* actually want it) - we'll need to weigh out the cost of it in performance and technical debt.

As a programmer, seeing the first couple lines of some source file is pretty useless, though it might be better with other text files.

**Comment by JosephMcc** [comment]
This is a duplicate of this: https://github.com/linuxmint/nemo/issues/949

**Comment by X0rg** [comment]
Ok, I consider it's a GTK regression, not a Nemo problem.
Sorry for duplicate, my search was with term "Thumbnail". So I close it, not a bug.
