### ISSUE TITLE
[Feature Request] Delete button

### ISSUE THREAD

**Issue by msegmx** [linuxmint/nemo#955]
I've downloaded lots of file managers in the past few weeks, tested them, and have to say Nemo is simply one of the best. Only Marlin could compete, imho, and that's only because it allows to select multiple files in list view by only using the mouse (like in Windows Explorer).

If I had to nitpick I'd say the tab headers are too big and their padding value is too high. Also tabs with fixed header sizez would look better, imho.

But that's all not that important, it doesn't interfere with functionality.
But there is one thing that does actually : the lack of a delete button in tool bar.
I always prefer the toolbar buttons instead of a right-click.
Is there a way to make the delete button appear (in config settings, etc) ?
If not, is a delete button for the toolbar planned in future releases ?
One last question, will we ever be able to rearrange buttons in the toolbar ?

**Comment by msegmx** [comment]
It's been almost a year since I wrote this. I totally forgot that I did.
Today I googled "linux mint nemo delete button" and found my own post.

Anyways, I hope someone is commenting soon on my little request / suggestion.

**Comment by JosephMcc** [comment]
You can never say never but right now I don't think there are any plans to add more buttons to the toolbar. I doubt you will see the ability to rearrange buttons either unless gtk gets some sort of native support for easily doing this at some point.

**Comment by anandrkris** [comment]
https://github.com/linuxmint/nemo/issues/1296 Another request for delete button. I suppose, this should appear only on item (folder/ file) selection?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by dannn-o** [comment]
Using Linux Mint 19.1 with Nemo 4.0.6, and within the "File Management Preferences" window there is a Toolbar option where various "Visible Buttons" can be toggled on/off, but there is none representing the "Delete" function.  I think it would be a time saver in certain circumstances compared to right-clicking or having to use the keyboard 'Del" key.  Adding another vote in favor of this as a feature.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Ne2hpmbw** [comment]
Nemo needs a Delete icon for many users.
Thank you.
Respectfully . . .
