### ISSUE TITLE
New folder permissions

### ISSUE THREAD

**Issue by roman-yagodin** [linuxmint/nemo#956]
On creating a new folder, Nemo makes it RW for current user (owner), R for user group and R for other users. But in shared environments like samba shares or just local folders with shared access for several users in same group, it would be better to inherit permissions from current folder. This will allow users in the same group to make changes in a folder without asking owner to adjust permissions or using superuser rights to do this.

**Comment by sbitzer** [comment]
I agree that this is an issue. I have exactly the same problem with a shared directory to which I connect via sftp. The shared directory has its setgid bit set (g+s) which ensures that files and subfolders will inherit the group of the shared directory, but there is no way in Nemo to set g+s for new folders, or indeed do this for existing folders. As a result, new folders created in subfolders of the shared directory will belong to the default group of the user which makes it inaccessible for other members of the shared group.

On the positive side: When I copy a folder with several sub- and subsubfolders into the shared directory, the group of all folders and files is set to that of the shared directory (even though subfolders usually lack setgid in the shared directory after copying).

**Comment by icarter09** [comment]
@roman-yagodin are you still experiencing this issue on the latest version of nemo?

**Comment by roman-yagodin** [comment]
Don't know about latest, but it's still there in Nemo 4.2.3.

Create folder with default permissions:
```Shell
mkdir test
ls -l | grep test
# output:
# drwxr-xr-x  2 user user    4096 Apr  9 10:13 test
```

Allow "video" group write access
```Shell
sudo chown -R user:video test
sudo chmod g+w test
ls -l | grep test
# output:
# drwxrwxr-x  2 user video            4096 Apr  9 10:13 test
```

Create file inside folder:
```Shell
touch test/newfile
ls -l .test/newfile
# output:
# -rw-r--r-- 1 user user 0 Apr  9 10:22 test/newfile
```

**Comment by icarter09** [comment]
@roman-yagodin thanks for the update.

**Comment by xenopeek** [comment]
This is not reproducible on Nemo 4.6.4, at least not for local folders. Mind that you need to set `chmod g+s` on a directory if you want new files created in it to inherit the group of the directory itself. I don't see that done in above example so closing this.
