### ISSUE TITLE
[feature request][UI] nemo help button on system folders

### ISSUE THREAD

**Issue by BlackDizel** [linuxmint/nemo#957]
add help button to nemo and highlight it in system folders (like etc folders) with show folder functions info on click

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
