### ISSUE TITLE
[Feature Request] Keyboard Shortcut to Open Current Directory in Terminal

### ISSUE THREAD

**Issue by pretodor** [linuxmint/nemo#958]
Like in Kali Linux when you hit F10+e, or in Ubuntu when you hit F12 after you follow these instructions:

http://askubuntu.com/questions/68078/keyboard-shortcut-for-open-a-terminal-here

Apologies if this has already been asked.

**Comment by tp0** [comment]
`org/cinnamon/desktop/interface/can-change-accels` exists in Cinnamon/Nemo too, but while Nemo has the "open in terminal" feature in the right mouse click context menu there is no "Open in terminal" in the File menu.

Best implementation would be obviously an actual setting the Nemo preferences.

One "workaround" is to install `nemo-terminal`, that's the built-in terminal in Nemo and can be accessed via F4, but personally I don't like the built-in terminal.

ps. #981

**Comment by tp0** [comment]
Solution: https://github.com/linuxmint/nemo/issues/981#issuecomment-147800040

**Comment by pretodor** [comment]
Brilliant! This is *the* solution. Thanks for the help, tp0.

**Comment by pretodor** [comment]
Seems like the solution @tp0 posted is only relevant for versions prior to 18. In Linux Mint 18 the `~/.gnome2` directory is missing.

**Comment by pretodor** [comment]
pretodor@gmail.com

**Comment by pretodor** [comment]
(I accidentally closed this issue.)

**Comment by pretodor** [comment]
The solution in Linux Mint 18 is to manually create the missing directories and files. What I did was:

`mkdir -p ~/.gnome2/accels`
`touch ~/.gnome2/accels/nemo`

Then I copy+pasted `(gtk_accel_path "<Actions>/DirViewActions/OpenInTerminal" "<Primary><Shift>t")` inside the 'nemo' file following @tp0's advice and, voila, the keyboard shortcut was working again.

**Comment by jonorthwash** [comment]
Editing that file doesn't seem to be having any effect with nemo 3.2.2 and cinnamon 3.2.7 (though the file does randomly change itself while those are running).  I've tried killing and restarting both (making sure that my changes weren't overwritten in the process) and also a range of different shortcuts—all to no avail.  Any suggestions?

**Comment by jonorthwash** [comment]
Aha, uncommented the line and it worked :-P  I guess edits to the comments get overwritten?
