### ISSUE TITLE
Columns get redrawn in List View upon various events

### ISSUE THREAD

**Issue by ienev** [linuxmint/nemo#96]
I'm not sure if this is related to Nemo or any underlying library (it exists in Nautilus too), but I didn't know where to post this.

When in List View the columns get redrawn on various events – switching between tabs, getting focus, another application gets focus with Nemo in the background etc. Here is how this happens in details:
- the initial state is - Nemo is on focus with the columns auto-adjusted to its content. 
- after one of the events in question the columns are shrunk to approximately around 60% of their initial width
- after this the columns are again auto-adjusted to its content

It seems that same bug is confirmed for Nautilus https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1018718

**Comment by Vahan86** [comment]
@ienev, is this still an issue for you with latest version of Nemo?

**Comment by ienev** [comment]
@Vahan86 I can confirm that with Nemo 3.2.2 this is not an issue anymore. It seems it has been fixed at some point although I can't say exactly when. If the Cinnamon theme matters - I'm currently using the Mint-Y theme (wasn't an issue with Mint-X before that either).
