### ISSUE TITLE
Columns size not optimal, austosize needs actions

### ISSUE THREAD

**Issue by FM33** [linuxmint/nemo#960]
Hello,
When opening a new window in nemo 2.6.7 [ppa webupd8, Ubuntu 14.04 x64], file name column is too small, and other ones are too large.
Enlarging file name column by drag&drop, then doing the same with detailed type, make nemo auto-size correctly the file size column.
This should be done automatically at window opening : 
Optimise size of other columns and maximise the file name column so file names are truncated only if way too long.

Video [4,3 Mib] https://webcloud.zaclys.com/index.php/s/onjK9vfUe7cvTKU

**Comment by koeur2pi** [comment]
Same request asked there: "Nemo, list view : reduce automatically the width of columns" http://community.linuxmint.com/idea/view/6011

**Comment by JosephMcc** [comment]
I can't reproduce this on Cinnamon 3.0.6. I seems the name column gets all the remaining width not taken by the other columns.
