### ISSUE TITLE
name sorting

### ISSUE THREAD

**Issue by simonzack** [linuxmint/nemo#963]
When sorting by file name underscores are ignored for some reason. It's rather annoying when `__pycache__` is not the first in a directory of python files. Can lexographic sorting be used instead?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
