### ISSUE TITLE
Unjustified successful unmount notifcation

### ISSUE THREAD

**Issue by Amarok19** [linuxmint/nemo#965]
When a drive is mounted by root and then a user attempts to unmount using Nemo, the operation fails due to insufficient privileges (as  expected), but a notification is issued about the possibility to safely remove the device (implying the unmount operation was successful, which is not true).
The notification should not be issued/displayed.

**Comment by Vahan86** [comment]
@Amarok19, is this still an issue for you in Mint 18?

**Comment by Amarok19** [comment]
Not using Mint since a long time, sorry, cannot verify. 
On 9 Nov 2016 7:50 p.m., Vahan Harutyunyan <notifications@github.com> wrote:@Amarok19, is this still an issue for you in Mint 18?

**Comment by Vahan86** [comment]
@Amarok19, thanks for your reply. In this case can you please close this issue?
