### ISSUE TITLE
Sidebar tree behaves weird

### ISSUE THREAD

**Issue by sixtyfive** [linuxmint/nemo#967]
When the list of folders is too high to fit into the window's height, something funny happens. Difficult to describe, so I've made a short video. I'm running Git as of 5 minutes ago. Here's the link: http://bit.ly/1OUTdj4.

**Comment by philippludwig1** [comment]
I've noticed the same issue, too. This does not happen with thunar or pcmanfm.

Furthermore, this seems to be related to the gtk theme. If you select e. g. the "Raleigh" theme, everything looks normal.

**Comment by JosephMcc** [comment]
That's because your using a newer version of gtk. I would guess 3.16 or greater. The Mint-X theme doesn't support the newer features of gtk since it's meant for Mint which currently only supports 3.10 (Mint) and 3.14 (LMDE).
