### ISSUE TITLE
Inflexible date format options

### ISSUE THREAD

**Issue by clidx** [linuxmint/nemo#968]
In preferences>Display>Date format, there are only 3 settings available.
I would propose allowing a custom date format, as per the stock calendar applet. Personally I use my machine as a tablet a lot of the time and also prefer list view. All the given options take up too much screen space.
Maybe there could be those 3 presets but an additional drop down option that allows you to enter your own format coding?

Thank you for reading.

**Comment by jensb** [comment]
I totally support this request. I have tried to patch Nemo but so far I have not been successful. With a litte support I might be able to create a pull request for this. Where in the source are the date formats defined?

**Comment by Vahan86** [comment]
@JosephMcc, can we mark the issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by MegaV0lt** [comment]
Any News?
