### ISSUE TITLE
Issues connecting to a samba share on QNAP NAS

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/nemo#969]
If i use the network connection to acess a share there are 3 things which can happen:
1. Nemo shows an empty folder (of course it isn't empty)
2. I get an error saying "$smbshare couldn't be displayed - The program aborted the connection. Use another viewer and try again."
3. It works

The first try connecting after a reboot leads to 1. or 2. Second try usually works.
If the share was already connected and you try to browse there again after a while you got the same error.

**Comment by Vahan86** [comment]
@bitboy85, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
