### ISSUE TITLE
Bus error when typing path

### ISSUE THREAD

**Issue by GasparPizarro** [linuxmint/nemo#975]
When I type a path in the address bar, it closes, and the terminal says "Bus error". I have Nemo 2.6.7, running with Cinnamon 2.6.13, on Ubuntu 14.04.

**Comment by JosephMcc** [comment]
I can't reproduce it here on the nightly builds. Does it happen when typing any path or just specific ones?

**Comment by GasparPizarro** [comment]
Every path, even the home folder.

**Comment by Vahan86** [comment]
@GasparPizarro, is this still an issue for you in Nemo 3.0.6?

**Comment by GasparPizarro** [comment]
Not anymore

**Comment by GasparPizarro** [comment]
Not anymore.
