### ISSUE TITLE
Crash when clicking in the extensions list in Plugins window

### ISSUE THREAD

**Issue by romainreignier** [linuxmint/nemo#976]
In the Nemo Plugins window, when clicking on the "No extension found" (personal translation) in the empty extensions list, the application crash with the following output in the console:

    (nemo:10416): GLib-GObject-WARNING **: invalid cast from 'GtkLabel' to 'GtkContainer'
    (nemo:10416): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
    Erreur de segmentation (core dumped)
![Nemo SegFault](https://cloud.githubusercontent.com/assets/8845664/10166798/e5feb962-66c5-11e5-823f-0e8f642b47a3.png)

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/nemo/commit/153942365bd04e5490b41d29c1121c470c72c712
