### ISSUE TITLE
[Request] Keep nemo actions on seperate folders.

### ISSUE THREAD

**Issue by queeup** [linuxmint/nemo#979]
My nemo actions folder is a mess. I love to have option to keep my nemo actions on separate folders.

example:

```
- nemo_action1(folder)
        nemo_action1.nemo_action(file)
        nemo_action1.py(file)
```

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
