### ISSUE TITLE
[Feature request] Add "Open in Terminal" to File menu

### ISSUE THREAD

**Issue by tp0** [linuxmint/nemo#981]
- no need to use keyboard
- it is already available in right mouse click context menu...
- ...but when using List View finding "empty space" to right click in can be hard
- right now File menu isn't too cluttered

Related: #958 

Nautius used to have it (don't remember if `nautilus-open-terminal` was needed):

![bmdqd](https://cloud.githubusercontent.com/assets/5863551/10266752/411f0922-6a7d-11e5-94bf-01c4bc1f0a63.png)

**Comment by bitboy85** [comment]
Maybe you can do the following:
1. Open settings
2. Go to Tool bar (last tab)
3. Enable show "open in Terminal"

You now have a button which opens the current directory in a new terminal window

**Comment by tp0** [comment]
I had probably forgot that. Helps with the list view "finding empty space" case, but still needs mouse interaction.

**Comment by bitboy85** [comment]
You can define Shortcuts on your own.
Open ~/.gnome2/accels/nemo

Find line (maybe its line 106)
; (gtk_accel_path "<Actions>/DirViewActions/OpenInTerminal" "")
and change it to
(gtk_accel_path "<Actions>/DirViewActions/OpenInTerminal" "F12")

save and restart.
Note: If you have a folder selected, it opens the selected folder, if nothing is selected, it opens the current folder in terminal, but if you have selected a file nothing will happen.

**Comment by tp0** [comment]
Thanks... I actually remember doing something similar back in Ubuntu & Nautilus time for another shortcut/feature.

The line needed to be though:

`(gtk_accel_path "<Actions>/DirViewActions/OpenInTerminal" "F12")`

and full restart isn't needed: `nemo -q`

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
