### ISSUE TITLE
"default-sort-order" is ignored when "ignore-view-metadata" is "true"

### ISSUE THREAD

**Issue by laurent22** [linuxmint/nemo#983]
I came across a strange behavior that took me a while to figure out.

My default sort order is "by name", however Nemo always sort by Last Modified Date by default. In fact, no matter which sorting field I choose, it's always going to start with a Last Modified Date sort order.

Eventually I found out that it is due to the "ignore-view-metadata" option. When set to "true", it always sorts by Last Modified Date, while when it's "false" it takes into account my preferences.

I don't think this is normal behavior - "ignore-view-metadata" should ignore the current folder preferences, but shouldn't ignore my global default preferences.

I have tried deleting `~/.local/share/gvfs-metadata` but that didn't help.

If that can be of any help, here is my dconf data dump:

	[org/nemo/preferences]
	show-reload-icon-toolbar=true
	show-full-path-titles=true
	show-advanced-permissions=false
	show-home-icon-toolbar=false
	show-new-folder-icon-toolbar=false
	show-up-icon-toolbar=true
	show-open-in-terminal-toolbar=true
	size-prefixes='base-10'
	default-folder-viewer='list-view'
	start-with-dual-pane=true
	thumbnail-limit=uint64 4294967295
	show-edit-icon-toolbar=true
	date-format='iso'
	show-hidden-files=false
	show-image-thumbnails='local-only'
	show-computer-icon-toolbar=true
	disable-menu-warning=true
	show-location-entry=true
	ignore-view-metadata=true
	show-places-in-to-menus=true

	[org/nemo/window-state]
	network-expanded=true
	start-with-sidebar=true
	geometry='1918x849+0+0'
	maximized=true
	sidebar-bookmark-breakpoint=4

	[org/nemo/icon-view]
	default-use-tighter-layout=true

	[org/nemo/desktop]
	show-desktop-icons=true
	home-icon-visible=false
	computer-icon-visible=false
	volumes-visible=false
	trash-icon-visible=true

And there's also an old thread about this on the Linux Mint forum: http://forums.linuxmint.com/viewtopic.php?f=208&t=187171&p=1077045

If I can be of any help to replicate or fix this issue, feel free to let me know.

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 3.0.6 on Linux Mint 18. Folder view stays on default. I think this one can be closed.
