### ISSUE TITLE
Add right-click option to open files as Root

### ISSUE THREAD

**Issue by grenzor** [linuxmint/nemo#985]
Currently you can only open folders as Root but not sure why open file as root isn't an option as I find that much more useful.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
