### ISSUE TITLE
[Feature Request] Nemo Folder icons on a server

### ISSUE THREAD

**Issue by nmjbhoffmann** [linuxmint/nemo#992]
I like being able to set icons in Nemo, though I don't really use it as much as I'd like to since you cannot set it on a server folder share, so if for instance, I have a few hundred Movies on a server, and have icons for each folder, I'd need to set all the icons for each client.

I think either having a .nemo_icontable (or something) file in the root of the share with icon paths for Nemo to read, or a server service (though I assume that would require more effort than needed).

I know Windows is a taboo here, but I'll bring it up because it has a way to do this, though it's not ideal, since it spams .ini files in every folder, which is messy, and Windows doesn't always like reading it. Hence why one file in the root of the share would be nice.

Maybe set priorities for where to get the icon from, something like:
1. Client Custom icon
2. .nemo_icontable (Real name TBA)
3. .ini for (Windows compatibility) (Ya ya, No-one likes Windows)
4. Not sure if OSX has an implementation, but if they do, then add that too.

Hope I'm posting this in the right place, if not, please let me know

**Comment by nmjbhoffmann** [comment]
Just for clarification:

I want this: http://imgur.com/a/iemb7

Set on my server for everyone viewing the share.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
