### ISSUE TITLE
File operations are blocked while nemo scans subdirectories

### ISSUE THREAD

**Issue by vranki** [linuxmint/nemo#993]
1. Mount a sftp (or probably any) share, preferably with slow connection.
2. Browse to a directory with a lot of subdirectories.
3. While Nemo is scanning for file counts in subdirectories: Select a file, ctrl-c to copy. 
4. Notice that there is error sound and nothing else happens.
5. Wait until scanning is finished ("..." turns into "n files" on each subdirectory) 
6. Try the same copy operation. Now it works as expected.

This is annoying while working on remote shares. User must wait until scan is finished until any file operations can be done. #424 is somewhat related - if we had configuration option to disable subdirectory scanning on remote shares this would not be an issue. 

Tested on 2.6.5-201506 on Ubuntu 15.04.

**Comment by vranki** [comment]
This doesn't limit to just file ops - opening a new window with ctrl-n doesn't work until directories are scanned.

**Comment by cmcginty** [comment]
In my environment mounts can take upto 60s and the entire desktop UI is disabled for that time. Very frustrating! :angry: :-1: :snail:

**Comment by icarter09** [comment]
@vranki are you still experiencing this issue on the latest version of nemo?

**Comment by vranki** [comment]
Sorry, I'm no longer using Cinnamon/Nemo.

**Comment by icarter09** [comment]
@vranki no worries and thanks for the update.
