### ISSUE TITLE
Eject icon theme support

### ISSUE THREAD

**Issue by sbsbs15** [linuxmint/nemo#994]
Hi, I've been using nemo for a long time, but I decided to change the default theme recently and I realized that the "nemo-eject" icon does not correspond to the theme icon.

![eject_bug](https://cloud.githubusercontent.com/assets/15521217/10863478/46d7e4bc-7fcf-11e5-989e-7ef97b37198b.png)

I tried to copy the "nemo-eject.png" icon in the folder of the new theme and has not worked. 
Can you change nemo to use the "media-eject" icon?

Thanks in advance.

Edit: I think that changing "nemo-eject" by "media-eject" in the line 318 of  nemo/src/nemo-places-sidebar.c, can work.

**Comment by Vahan86** [comment]
Can't reproduce the issue in Nemo 3.0.6. @sbsbs15, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, duplicate of issue https://github.com/linuxmint/nemo/issues/722
