### ISSUE TITLE
Button [<] doesn't go to the previously visited folder

### ISSUE THREAD

**Issue by jf99** [linuxmint/nemo#995]
Nemo has those buttons [<][>][^] to go back, forward and up. In Nemo 2.6.7 on Arch Linux however, the buttons [<] and [^] do the same: They take you one level higher in the file hierarchy.

**Comment by ManIVIctorious** [comment]
I have the same issue, same version, same distro...

**Comment by jf99** [comment]
I just noticed that my issue description isn't quite accurate. The button [<] does go to the previously visited folder in some cases. But here's an example where it doesn't:

First viisit
/home/jf99/
Then click your way through to
/home/jf99/Downloads/
/home/jf99/Downloads/tmp/
Now (depending on how you configured nemo) there is a line of buttons representing the current path:
[.][jf99][Downloads][tmp]
If you click on [Downloads] now, and then use the [<] button, it doesn't take you back to /home/jf99/Downlaods/tmp/. Instead it takes you to /home/jf99/, which is not what you would expect.

The above example covers >90% of the cases where I use the [<] button, which is why I didn't notice that the [<] button actually works fine in other cases.

**Comment by jf99** [comment]
The Arch packages got an update and now I have nemo 2.8.5. Nothing related to this issue has changed.

**Comment by Vahan86** [comment]
@jf99, is this issue still relevant to Nemo 3.0.6?

**Comment by jf99** [comment]
@Vahan86 Well, Nemo 3.0.6 is already outdated. But Nemo 3.2.0 still behaves as described above.

**Comment by xenopeek** [comment]
If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
