### ISSUE TITLE
Icons on desktop placed acc. to highest resolution

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/nemo#996]
I have a 4K monitor in the middle, flanked by a 1600x1200 on either side.

Desktop Icons seem to be sorted on the left screen, but as if that screen was 4K as well, meaning that a number of icons are - effectively - off-screen.

**Comment by Pe3ucTop** [comment]
+1
Same problem ! Big issue !
When second monitor with higher Vertical resolution connected (at right of primary screen) and both aligned by bottom , result is icons on primary screen get show higher ( in respect to virtual Vertical resolution, not real one of primary screen ) .
Issue - icons get shown out of real monitor resolution !

**Comment by Pe3ucTop** [comment]
Also I think this issue is connected to issue #1002  ...

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by icarter09** [comment]
@Pe3ucTop are you still experiencing this issue on the latest version of nemo?
