### ISSUE TITLE
Nemo ignores starting window position in system settings

### ISSUE THREAD

**Issue by AdmiralAnimE** [linuxmint/nemo#997]
My window position is set to centered, I'm using MInt 17.2 Cinnamon. Happens only when other windows are open. Nemo doesn't launch in the center of the screen, it opens in one of the corners.

**Comment by Vahan86** [comment]
@AdmiralAnimE, is this still an issue for you with Nemo 3.0.6?

**Comment by AdmiralAnimE** [comment]
It's fixed :)

**Comment by Vahan86** [comment]
@AdmiralAnimE, in this case can you please close the issue?
