### ISSUE TITLE
Folder Delete deleted parent folder

### ISSUE THREAD

**Issue by pfannkuchengesicht** [linuxmint/nemo#998]
Hello,
I had a weird bug today which caused me some data loss.
So I wanted to delete a folder, I right-clicked on that folder then selected the "delete" option and clicked on that. Usually that would prompt me with a dialog which requires me to confirm this action. Today that didn't happen, it just started deleting the folder, but furthermore not only that folder but also the entire parent folder.
That was kinda odd and now I've lost about 300 photos. Unfortunately I hadn't backed them up yet <_<

Steps to reproduce:
1. navigate to folder in which the other folder is
2. right-click on folder
3. select "delete"
4. click the selected option
5. see your parent folder go

System:
Linux Mint 17 with latest updates as of today(06.11.15)
Files were on a Samsung EVO 830 64GB SSD

It's probably impossible to fix this since it happens so rarely and the circumstances that caused this aren't clear. But I'm hoping that someone may still find something in the code for this function that might be suspicious.

**Comment by veikk0** [comment]
I just experienced this same bug when attempting to delete four files (two of which were .mp4 files, the other two were Handbrake encode logs for said files). Suddenly the whole directory was removed. Fortunately I had a backup of the 9 GB of files I lost. However, I've noticed another bug during/before this incident that I suspect might be related. Sometimes when Nemo has been running for some time (hours, sometimes days) the right-click context menu for files changes to a much more extensive one that seems to include every option you can think of, even ones that aren't related to the selected file/files such as "Open containing folder", "Eject", and "Connect To This Server". There are 26 context menu options, when normally the selected files should only have only about 10.

It is also notable that the correct default action for opening the selected file (which in my case for media files is "Open With mpv Media Player") is not present. However, pressing Enter while the file is highlighted in Nemo still opens the file with the correct player.

I only tested various video files during this latest occurence of the bug but if I remember right, this bug also happens with any selected item (be it a file of any type or a directory). I'll try to remember to test other files and directories next time this occurs.

[Screenshot of a buggy context menu](http://i.imgur.com/YRzYQMq.png)
[Screenshot of expected context menu](http://i.imgur.com/bbhhnVM.png)

Oh, and this always seems to be limited to a specific Nemo window/session, as starting a new Nemo window/process doesn't "inherit" this problem. I also utilise Nemo tabs and most of the time have at least 4 tabs open in one window, often there are 6 or more tabs open.

System information:
Linux Mint 17.2 64-bit with the latest updates (as of 13.6.2016)
Nemo version: 2.6.7
Active Nemo plugins: (Actions) Format, Check MD5, Set as Wallpaper, Create a new launcher here, Mount archive (Scripts) avconvert (https://www.gnome-look.org/p/1007700/) (Extensions) ChangeColorFolder+NemoPython, EmblemPropertyPage+NemoPython, Nemo Fileroller

**Comment by Vahan86** [comment]
@pfannkuchengesicht, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by pfannkuchengesicht** [comment]
It's really hard to reproduce and maybe happens once a year, so I can't really say if it's still an issue. Since it didn't happen in quite a while I suppose it could be resolved and the issue can be closed. I'll just reopen it when it ever happens again.

**Comment by Vahan86** [comment]
@pfannkuchengesicht, thank you for your response, in this case can you please close the issue?
